### ISSUE TITLE
Error on https://ducklife2hacked.weebly.com/duck-life-5-hacked.html

### ISSUE THREAD

**Issue by TheGamesss** [ruffle-rs/ruffle#10015]
# Error Info
Error name: Error
Error message: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:626:14
Error stack:
```
Error: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:626:14
    at imports.wbg.__wbg_new_15d3966e9981a196 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:2158:21)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h321a9078ff9936f2 (wasm://wasm/02962ab2:wasm-function[7834]:0x7cc186)
    at std::panicking::rust_panic_with_hook::h8d0a63d0479a36c8 (wasm://wasm/02962ab2:wasm-function[5302]:0x7125e6)
    at core::panicking::panic_fmt::h2a7f454a5f5da218 (wasm://wasm/02962ab2:wasm-function[7726]:0x7c775e)
    at core::option::expect_failed::hc28dae4f096efed4 (wasm://wasm/02962ab2:wasm-function[8987]:0x7f3d75)
    at ruffle_core::display_object::stage::Stage::root_clip::h7c8ba84cf2bfc875 (wasm://wasm/02962ab2:wasm-function[4354]:0x6bcc73)
    at ruffle_web::Ruffle::tick::h2000682d298368c3 (wasm://wasm/02962ab2:wasm-function[677]:0x240b5e)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h820d06e21ce20de4 (wasm://wasm/02962ab2:wasm-function[9434]:0x804c3a)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::ha6dba4b7bc395bcc (wasm://wasm/02962ab2:wasm-function[8338]:0x7d7f16)
    at __wbg_adapter_58 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:282:10)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://ducklife2hacked.weebly.com/duck-life-5-hacked.html
SWF URL: https://www.hackedarcadegames.com/swf/Duck-Life-Treasure-Hunt-Ldrp13.swf?version=1417497996

# Browser Info
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
Platform: MacIntel
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-03-12
Channel: nightly
Built: 2023-03-12T00:19:04.440Z
Commit: 1deebc87e869387c962f97b665d26785d0a2b52f
Is extension: true

# Metadata
width: 800
height: 450
frameRate: 50
numFrames: 1
swfVersion: 17
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 9346348

**Comment by Bale001** [comment]
Fixed by #10026, still broken due to domain lock.
