### ISSUE TITLE
Error on https://www.thesbcommunity.com/games/sb_ship/

### ISSUE THREAD

**Issue by Esreever** [ruffle-rs/ruffle#10060]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:629:28
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:629:28
    at W.n.wbg.__wbg_new_f9bb493369a83c12 (https://www.thesbcommunity.com/games/ruffle/core.ruffle.db3735ad129c601c6f82.js:1:5412)
    at std::sync::once::Once::call_once::{{closure}}::hfb695c8f07f1e72c (wasm://wasm/027ca67e:wasm-function[1921]:0x493e07)
    at std::sys_common::once::generic::Once::call::he3f17a186e209b2a (wasm://wasm/027ca67e:wasm-function[1856]:0x48283c)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hc93fb6a80fc6ff8b (wasm://wasm/027ca67e:wasm-function[7144]:0x768468)
    at std::panicking::rust_panic_with_hook::hd000e9fb43b5781d (wasm://wasm/027ca67e:wasm-function[5044]:0x6c399a)
    at core::panicking::panic_fmt::h9d972fcdb087ce21 (wasm://wasm/027ca67e:wasm-function[7453]:0x7770ef)
    at core::panicking::panic::h364c37174a08a6a4 (wasm://wasm/027ca67e:wasm-function[6868]:0x743f3c)
    at ruffle_core::display_object::container::ChildContainer::replace_at_depth::hf914fd1db14ed5cb (wasm://wasm/027ca67e:wasm-function[1569]:0x416bd1)
    at ruffle_core::display_object::container::TDisplayObjectContainer::replace_at_depth::h884ac007e7ce58de (wasm://wasm/027ca67e:wasm-function[4695]:0x6a6102)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::h79ba63d9a06b5dc5 (wasm://wasm/027ca67e:wasm-function[717]:0x24042a)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://www.thesbcommunity.com/games/sb_ship/
SWF URL: https://www.thesbcommunity.com/games/sb_ship/ship_o_ghouls.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-02-07
Channel: nightly
Built: 2023-02-07T00:21:37.543Z
Commit: 48f4df51a51cc1e2e009b2212eaa14459488a1e4
Is extension: false

# Metadata
width: 600
height: 300
frameRate: 35
numFrames: 56
swfVersion: 8
backgroundColor: #FFFFFF
isActionScript3: false
uncompressedLength: 1696607

**Comment by n0samu** [comment]
Same bug as #10314. This was already fixed by #10362. Please contact the site owner and ask them to update their copy of Ruffle.
