### ISSUE TITLE
Error on http://nextframe.jp/flash/gunReport.html

### ISSUE THREAD

**Issue by SeruranBlue** [ruffle-rs/ruffle#10072]
### Describe what you were doing

Boot up the game.

### What does the crash message say?

# Error Info
Error name: Error
Error message: Failed to fetch: http://nextframe.jp/swf/gunReport.swf
Error stack:
```
Error: Failed to fetch: http://nextframe.jp/swf/gunReport.swf
    at RuffleObject.displayRootMovieDownloadFailedMessage (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/ruffle.js?id=39650339930:2420:27)
    at imports.wbg.__wbg_displayRootMovieDownloadFailedMessage_ed4ad3ae9522c8a3 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:652:14)
    at <ruffle_web::ui::WebUiBackend as ruffle_core::backend::ui::UiBackend>::display_root_movie_download_failed_message::h744578780e22f8dd (wasm://wasm/0298a2f6:wasm-function[9488]:0x80c5a2)
    at ruffle_core::loader::Loader::root_movie_loader::{{closure}}::h6fe5127144d7e631 (wasm://wasm/0298a2f6:wasm-function[760]:0x28325c)
    at <ruffle_web::navigator::WebNavigatorBackend as ruffle_core::backend::navigator::NavigatorBackend>::spawn_future::{{closure}}::h980992db56e3135e (wasm://wasm/0298a2f6:wasm-function[940]:0x30f547)
    at wasm_bindgen_futures::queue::Queue::new::{{closure}}::hed6133f14c689d32 (wasm://wasm/0298a2f6:wasm-function[3419]:0x64326e)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h7df137e5e84b814f (wasm://wasm/0298a2f6:wasm-function[8481]:0x7e0321)
    at closure4912 externref shim (wasm://wasm/0298a2f6:wasm-function[8669]:0x7e418b)
    at __wbg_adapter_63 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:286:10)
    at real (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:259:20)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: ../swf/gunReport.swf
Param quality: high
Param swfversion: 8.0.35.0
Param expressinstall: ../Scripts/expressInstall.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: http://nextframe.jp/flash/gunReport.html
SWF URL: http://nextframe.jp/swf/gunReport.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-03-14
Channel: nightly
Built: 2023-03-14T00:19:05.444Z
Commit: cd1a0326e7058ea9bf62f603d63dca7e137b72ed
Is extension: true

# Metadata

### Ruffle Version

Ruffle extension nightly 2023-03-14

### Affected platform

Browser's extension

### Operating system

Windows 10

### Additional information

Chrome 111.0.5563.65

**Comment by n0samu** [comment]
The SWF file no longer exists. You can find it on the Wayback Machine: http://web.archive.org/web/20201231050011/http://nextframe.jp/swf/gunReport.swf
