### ISSUE TITLE
Regression on Penguin Dive

### ISSUE THREAD

**Issue by sombraguerrero** [ruffle-rs/ruffle#10117]
# Error Info
Error name: Error
Error message: panicked at 'index out of bounds: the len is 90000 but the index is 91200', /home/runner/.cargo/git/checkouts/h263-rs-6a92376340b27390/8c00d0e/h263/src/decoder/cpu/idct.rs:142:48
Error stack:
```
Error: panicked at 'index out of bounds: the len is 90000 but the index is 91200', /home/runner/.cargo/git/checkouts/h263-rs-6a92376340b27390/8c00d0e/h263/src/decoder/cpu/idct.rs:142:48
    at U.n.wbg.__wbg_new_15d3966e9981a196 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.5ae1578b595b3e28cc24.js:1:47866)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hf9c4513da7c8b909 (wasm://wasm/02a0afd6:wasm-function[7903]:0x7e1bcb)
    at std::panicking::rust_panic_with_hook::h8d0a63d0479a36c8 (wasm://wasm/02a0afd6:wasm-function[5362]:0x71f673)
    at core::panicking::panic_fmt::h2a7f454a5f5da218 (wasm://wasm/02a0afd6:wasm-function[7794]:0x7dd15c)
    at core::panicking::panic_bounds_check::h69c7a7cd0b1c2bb8 (wasm://wasm/02a0afd6:wasm-function[6276]:0x7663c4)
    at h263_rs::decoder::cpu::idct::idct_channel::h0aadb2755ac8afeb (wasm://wasm/02a0afd6:wasm-function[563]:0x169a9c)
    at <ruffle_video_software::decoder::h263::H263Decoder as ruffle_video_software::decoder::VideoDecoder>::decode_frame::h50ab21c4e4faaa53 (wasm://wasm/02a0afd6:wasm-function[3519]:0x65f189)
    at <ruffle_video_software::backend::SoftwareVideoBackend as ruffle_video::backend::VideoBackend>::decode_video_stream_frame::h4dc6608492b407e6 (wasm://wasm/02a0afd6:wasm-function[1678]:0x47c14f)
    at ruffle_core::display_object::video::Video::seek::h025bd1948fdc3e41 (wasm://wasm/02a0afd6:wasm-function[714]:0x25e28f)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::hbabead7ceaddcfb9 (wasm://wasm/02a0afd6:wasm-function[3072]:0x5f63e8)
```

# Player Info
Allows script access: true

# Page Info
Local test bed - not accessible to the internet. SWF attached. Issue also producible on desktop builds.

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-03-16
Channel: nightly
Built: 2023-03-16T00:21:48.376Z
Commit: 6eeb2de2133d1a52650216080003c311fccf6300
Is extension: false

# Metadata
width: 620
height: 600
frameRate: 14
numFrames: 2
swfVersion: 6
backgroundColor: #0066FF
isActionScript3: false
uncompressedLength: 446486

Regression occurred after 3/11/23 nightly builds.
[penguindive.zip](https://github.com/ruffle-rs/ruffle/files/10987802/penguindive.zip)

**Comment by torokati44** [comment]
Oh shoot, this is on me, thanks for the report!
