### ISSUE TITLE
Error on https://ruffle.rs/demo/

### ISSUE THREAD

**Issue by Robert9157** [ruffle-rs/ruffle#10182]
[dragon-fire_v1.zip](https://github.com/ruffle-rs/ruffle/files/11005951/dragon-fire_v1.zip)
# Error Info
Error name: Error
Error message: panicked at 'No script object for display object', core/src/avm1/activation.rs:396:18
Error stack:
```
Error: panicked at 'No script object for display object', core/src/avm1/activation.rs:396:18
    at U.n.wbg.__wbg_new_15d3966e9981a196 (https://ruffle.rs/demo/339.index.js:1:47925)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::ha96929d97ebd9a99 (wasm://wasm/02a694aa:wasm-function[8042]:0x7f1d4e)
    at std::panicking::rust_panic_with_hook::h8d0a63d0479a36c8 (wasm://wasm/02a694aa:wasm-function[5357]:0x728e1e)
    at core::panicking::panic_fmt::h2a7f454a5f5da218 (wasm://wasm/02a694aa:wasm-function[7921]:0x7ed049)
    at ruffle_core::display_object::edit_text::EditText::try_bind_text_field_variable::h9c5fbbbb126491b9 (wasm://wasm/02a694aa:wasm-function[3700]:0x67dc27)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::h0bbcae0b3527237f (wasm://wasm/02a694aa:wasm-function[3074]:0x600fb0)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::hd244d6ebb7358c42 (wasm://wasm/02a694aa:wasm-function[773]:0x29aecf)
    at ruffle_core::display_object::movie_clip::MovieClip::place_object::h97ffd21186ba2fdd (wasm://wasm/02a694aa:wasm-function[1559]:0x42fb05)
    at <ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::enter_frame::h57e3f4ff64f72aa1 (wasm://wasm/02a694aa:wasm-function[788]:0x2a5877)
    at <ruffle_core::display_object::loader_display::LoaderDisplay as ruffle_core::display_object::TDisplayObject>::enter_frame::he06e52605ff8f9e8 (wasm://wasm/02a694aa:wasm-function[3604]:0x673fef)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://ruffle.rs/demo/

# Browser Info
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-03-17
Channel: nightly
Built: 2023-03-17T00:19:04.444Z
Commit: 32f8330199d6c244e41d15fcbb9a9d028fc83af8
Is extension: false

# Metadata
width: 800
height: 600
frameRate: 30
numFrames: 2
swfVersion: 10
backgroundColor: #FFFFFF
isActionScript3: true
uncompressedLength: 532454

**Comment by n0samu** [comment]
This is an AVM1 game encrypted with MochiCrypt, which uses AVM2. Ruffle does not correctly play AVM1 movies loaded by AVM2 movies right now. If the original AVM1 movie is extracted from the MochiCrypt wrapper and played on its own, Ruffle works fine.
