### ISSUE TITLE
Oiche Mhaith: Black Screen issue

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#10206]
### Describe the bug

https://www.newgrounds.com/portal/view/585928?emulate=flash
Music plays, but game breaks on a black screen without showing the title screen (Obligatory NSFW warning, I don't know whats in it, i'm just going off what the NG rating was)

[www.newgrounds.com-1679118476779.log](https://github.com/ruffle-rs/ruffle/files/11007611/www.newgrounds.com-1679118476779.log)

### Expected behavior

Game should be loading to the title screen.

### Affected platform

Browser's extension

### Operating system

Windows 11

### Browser

Edge 110

**Comment by Lord-McSweeney** [comment]
This needs `flash.filters::ShaderFilter`.

**Comment by waspennator** [comment]
Update, game breaks on the ruffle crash error screen with this in the log.

# Error Info
Error name: Error
Error message: panicked at render/naga-pixelbender/src/lib.rs:1241:29:
Unimplemented opcode IntToBool
Error stack:
```
Error: panicked at render/naga-pixelbender/src/lib.rs:1241:29:
Unimplemented opcode IntToBool
    at H.n.wbg.__wbg_new_ab87fd305ed9004b (https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.d273449361a0cd066e42.js:1:56255)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h189f598b25fe4514 (wasm://wasm/033ef5ea:wasm-function[9962]:0x9cb822)
    at std::panicking::rust_panic_with_hook::h3aa054d35a0817d7 (wasm://wasm/033ef5ea:wasm-function[6532]:0x8cf542)
    at core::panicking::panic_fmt::h3e1dd3d08288569e (wasm://wasm/033ef5ea:wasm-function[9762]:0x9c6622)
    at <ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::compile_pixelbender_shader::h3e51aff7793c2452 (wasm://wasm/033ef5ea:wasm-function[8098]:0x941e15)
    at ruffle_core::avm2::globals::flash::display::shader_data::init::h6abade01daa3eabe (wasm://wasm/033ef5ea:wasm-function[1255]:0x427036)
    at ruffle_core::avm2::function::Executable::exec::h5f1cc5027f97d972 (wasm://wasm/033ef5ea:wasm-function[923]:0x33a8d9)
    at ruffle_core::avm2::object::TObject::call_property::he550187b27956506 (wasm://wasm/033ef5ea:wasm-function[1241]:0x41bdfe)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::hd5278b92e4cbdff7 (wasm://wasm/033ef5ea:wasm-function[2842]:0x69fbb0)
    at ruffle_core::avm2::activation::Activation::run_actions::h8c6d292a45ce9af6 (wasm://wasm/033ef5ea:wasm-function[568]:0x40317)
```
AVM2 stack:
```
    at flash.display::ShaderData/flash::display::ShaderData::init()
    at flash.display::ShaderData()
    at flash.display::Shader/set byteCode()
    at flash.display::Shader()
    at Main/gameinit()
    at flash.display::DisplayObjectContainer/flash::display::DisplayObjectContainer::addChild()
    at Preloader/startup()
    at Preloader/checkFrame()
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (AMD, AMD Radeon(TM) Graphics (0x00001638) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.67&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1699622433%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F585000%2F585928_oiche.swf%3F1324082691%22%2C%22vars%22%3A%7B%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%22654ed94413178%22%2C%22NewgroundsAPI_SessionID%22%3A%22KDjE9ohvg39mRrerDZCw618def3c9d3bd3978094f2909af4993ee19629ecrjTN%22%2C%22NewgroundsAPI_UserName%22%3A%22waspennator%22%2C%22NewgroundsAPI_UserID%22%3A1692431%2C%22ng_username%22%3A%22waspennator%22%7D%2C%22width%22%3A640%2C%22height%22%3A480%2C%22icon%22%3A%22https%3A%2F%2Fimg.ngfiles.com%2Fdefaults%2Ficon-portal-xl-a.gif%3Ff1601395813%22%2C%22warnOnUnsupportedContent%22%3Afalse%7D
SWF URL: https://uploads.ungrounded.net/585000/585928_oiche.swf?1324082691

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-11-10
Channel: nightly
Built: 2023-11-10T00:25:11.047Z
Commit: d98a2750a07e313bef80f6ed2bcd1cce3888f094
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 60
numFrames: 2
swfVersion: 11
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 8845648
