### ISSUE TITLE
Error on https://ruffle.rs/demo/

### ISSUE THREAD

**Issue by Captain-Toad18** [ruffle-rs/ruffle#10290]
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-core-0.1.30/src/dispatcher.rs:790:31
Error stack:
```
Error: panicked at 'already borrowed: BorrowMutError', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-core-0.1.30/src/dispatcher.rs:790:31
    at U.n.wbg.__wbg_new_15d3966e9981a196 (https://ruffle.rs/demo/339.index.js:1:47925)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::ha96929d97ebd9a99 (wasm://wasm/02a87c42:wasm-function[8044]:0x7f7bdb)
    at std::panicking::rust_panic_with_hook::h8d0a63d0479a36c8 (wasm://wasm/02a87c42:wasm-function[5356]:0x72dd93)
    at core::panicking::panic_fmt::h2a7f454a5f5da218 (wasm://wasm/02a87c42:wasm-function[7924]:0x7f2f33)
    at core::result::unwrap_failed::h6072dd9795ba6508 (wasm://wasm/02a87c42:wasm-function[6138]:0x76b170)
    at tracing_core::dispatcher::set_default::h7776741f443ddcbd (wasm://wasm/02a87c42:wasm-function[4832]:0x7038e4)
    at ruffle_web::audio::Buffer::play::h373acb4d2b9a2216 (wasm://wasm/02a87c42:wasm-function[539]:0x129a26)
    at ruffle_web::audio::Buffer::new::{{closure}}::h079ce4547ccedf23 (wasm://wasm/02a87c42:wasm-function[3097]:0x60b0c2)
    at <dyn core::ops::function::FnMut<()>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h9629bcf0a8d17d09 (wasm://wasm/02a87c42:wasm-function[8687]:0x804ae5)
    at v (https://ruffle.rs/demo/339.index.js:1:2502)
```

# Player Info
Allows script access: false
(Cached) Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "Mesa DRI Intel(R) UHD Graphics 600 (GLK 2)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: PUSH_CONSTANTS | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES
Available features: TEXTURE_COMPRESSION_BC | TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC_LDR | CLEAR_TEXTURE | TEXTURE_COMPRESSION_ASTC_HDR
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://ruffle.rs/demo/

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-03-19
Channel: nightly
Built: 2023-03-19T00:18:45.479Z
Commit: 5aac938e868e7dab2550d9482f754a6daf314921
Is extension: false

# Metadata
width: 800
height: 600
frameRate: 30
numFrames: 41
swfVersion: 8
backgroundColor: #CCCCCC
isActionScript3: false
uncompressedLength: 36209977

**Comment by n0samu** [comment]
Hi, can you tell us what SWF you were trying to run when this error occurred?

**Comment by n0samu** [comment]
No information provided, closing
