### ISSUE TITLE
Error on https://www.jogos360.com.br/the_king_of_fighters_wing_v_1_8.html

### ISSUE THREAD

**Issue by tiago-dev135** [ruffle-rs/ruffle#10309]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:644:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:644:18
    at U.n.wbg.__wbg_new_15d3966e9981a196 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.cd727afb548a22ea8f11.js:1:48013)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h83e4aeec3086bf1a (wasm://wasm/02a965fe:wasm-function[8064]:0x7f9da4)
    at std::panicking::rust_panic_with_hook::h8d0a63d0479a36c8 (wasm://wasm/02a965fe:wasm-function[5365]:0x72dfdf)
    at core::panicking::panic_fmt::h2a7f454a5f5da218 (wasm://wasm/02a965fe:wasm-function[7948]:0x7f51bf)
    at core::panicking::panic::ha3ebcac1438d9280 (wasm://wasm/02a965fe:wasm-function[7361]:0x7c1152)
    at ruffle_core::display_object::container::ChildContainer::replace_at_depth::hd8f9b9624cb2b5bd (wasm://wasm/02a965fe:wasm-function[1575]:0x43f714)
    at ruffle_core::display_object::container::TDisplayObjectContainer::replace_at_depth::hd98f0eb88047ecd2 (wasm://wasm/02a965fe:wasm-function[4833]:0x7035b2)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::h6d9d3dbf6b16f408 (wasm://wasm/02a965fe:wasm-function[772]:0x290939)
    at ruffle_core::display_object::movie_clip::MovieClip::run_goto::{{closure}}::h28ca79f8cbf403a3 (wasm://wasm/02a965fe:wasm-function[871]:0x2e8ec7)
    at ruffle_core::display_object::movie_clip::MovieClip::run_goto::h0c6247e7119ee78a (wasm://wasm/02a965fe:wasm-function[619]:0x1dec24)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://www.jogos360.com.br/the_king_of_fighters_wing_v_1_8.html
SWF URL: https://cdn.jogos360.com.br/files/games/th/ek/the-king-of-fighters-wing-v-1-8.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-03-22
Channel: nightly
Built: 2023-03-22T00:22:15.218Z
Commit: d7c842a1393b9824ae9f455b60843dc76a341b4d
Is extension: false

# Metadata
width: 660
height: 485
frameRate: 33
numFrames: 45
swfVersion: 9
backgroundColor: #333333
isActionScript3: false
uncompressedLength: 32261779

**Comment by kjarosh** [comment]
Fixed by https://github.com/ruffle-rs/ruffle/pull/10362
