### ISSUE TITLE
Error on https://www.cooljuegos.com/embed/the-king-of-fighters-wing/

### ISSUE THREAD

**Issue by jared0192galicia** [ruffle-rs/ruffle#10318]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:644:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:644:18
    at U.n.wbg.__wbg_new_15d3966e9981a196 (https://www.cooljuegos.com/emulators/ruffle/core.ruffle.1f937704edf22423e060.js:1:48013)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::he136b2cec2ed9e70 (wasm://wasm/02a910b2:wasm-function[8061]:0x7f8a09)
    at std::panicking::rust_panic_with_hook::h8d0a63d0479a36c8 (wasm://wasm/02a910b2:wasm-function[5358]:0x72bdf0)
    at core::panicking::panic_fmt::h2a7f454a5f5da218 (wasm://wasm/02a910b2:wasm-function[7945]:0x7f3e24)
    at core::panicking::panic::ha3ebcac1438d9280 (wasm://wasm/02a910b2:wasm-function[7358]:0x7bfde4)
    at ruffle_core::display_object::container::ChildContainer::replace_at_depth::h4901a3b9374324e1 (wasm://wasm/02a910b2:wasm-function[1574]:0x43e53b)
    at ruffle_core::display_object::container::TDisplayObjectContainer::replace_at_depth::hc24b15f13538b364 (wasm://wasm/02a910b2:wasm-function[4826]:0x7013a9)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::h67efb7f04aa03871 (wasm://wasm/02a910b2:wasm-function[771]:0x28fa40)
    at ruffle_core::display_object::movie_clip::MovieClip::run_goto::{{closure}}::h320dac28ba3a67e5 (wasm://wasm/02a910b2:wasm-function[870]:0x2e7f98)
    at ruffle_core::display_object::movie_clip::MovieClip::run_goto::h8021fd86b9ee71e6 (wasm://wasm/02a910b2:wasm-function[619]:0x1deb12)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.cooljuegos.com/embed/the-king-of-fighters-wing/
SWF URL: https://data.gameflare.com/games/874/0UkDs3JZA0YTKM.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-03-21
Channel: nightly
Built: 2023-03-21T00:21:35.556Z
Commit: 7c280fc1716a98b400da96e28195bdebaad669d9
Is extension: false

# Metadata
width: 660
height: 485
frameRate: 40
numFrames: 39
swfVersion: 8
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 13554555

**Comment by kjarosh** [comment]
Fixed by https://github.com/ruffle-rs/ruffle/pull/10362
