### ISSUE TITLE
Kickflip - Panicks at Start

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#10331]
# Error Info
Error name: Error
Error message: panicked at 'No script object for display object', core/src/avm1/activation.rs:396:18
Error stack:
```
Error: panicked at 'No script object for display object', core/src/avm1/activation.rs:396:18
    at U.n.wbg.__wbg_new_15d3966e9981a196 (https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.cd727afb548a22ea8f11.js:1:48013)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h83e4aeec3086bf1a (wasm://wasm/02a965fe:wasm-function[8064]:0x7f9da4)
    at std::panicking::rust_panic_with_hook::h8d0a63d0479a36c8 (wasm://wasm/02a965fe:wasm-function[5365]:0x72dfdf)
    at core::panicking::panic_fmt::h2a7f454a5f5da218 (wasm://wasm/02a965fe:wasm-function[7948]:0x7f51bf)
    at ruffle_core::display_object::edit_text::EditText::try_bind_text_field_variable::h1ae18c9dca6dee2e (wasm://wasm/02a965fe:wasm-function[3711]:0x6838b9)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::h6ed6896f3ac579fd (wasm://wasm/02a965fe:wasm-function[3071]:0x6060ed)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::h6d9d3dbf6b16f408 (wasm://wasm/02a965fe:wasm-function[772]:0x291cc8)
    at ruffle_core::display_object::movie_clip::MovieClip::place_object::h449732ec5036c12c (wasm://wasm/02a965fe:wasm-function[1555]:0x432d81)
    at <ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::enter_frame::ha8d16585f0aa96b9 (wasm://wasm/02a965fe:wasm-function[787]:0x29cb5b)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::h6d9d3dbf6b16f408 (wasm://wasm/02a965fe:wasm-function[772]:0x291d04)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.67&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1679486661%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F462000%2F462444_kickflip.swf%3F1223532382%22%2C%22vars%22%3A%7B%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%22641c20190cff2%22%2C%22NewgroundsAPI_SessionID%22%3A%22OHFsVDuAdMY64RkrG3Gpc5b697c86598e4612a7237a047e13486d0a42f0bI6Ai%22%2C%22NewgroundsAPI_UserName%22%3A%22spiele-umsonst%22%2C%22NewgroundsAPI_UserID%22%3A2677902%2C%22ng_username%22%3A%22spiele-umsonst%22%7D%2C%22width%22%3A640%2C%22height%22%3A420%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F462000%2Fflash_462444.jpg%3Ff1363835833%22%2C%22warnOnUnsupportedContent%22%3Afalse%7D
SWF URL: https://uploads.ungrounded.net/462000/462444_kickflip.swf?1223532382

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-03-22
Channel: nightly
Built: 2023-03-22T00:22:15.218Z
Commit: d7c842a1393b9824ae9f455b60843dc76a341b4d
Is extension: false

# Metadata
width: 640
height: 420
frameRate: 51
numFrames: 2
swfVersion: 9
backgroundColor: #333333
isActionScript3: true
uncompressedLength: 3279558

**Comment by Lord-McSweeney** [comment]
Fixed by #11005
