### ISSUE TITLE
Error on https://f.kbhgames.com/2014/OmniverseCollection/game.htm

### ISSUE THREAD

**Issue by ahmed2006453** [ruffle-rs/ruffle#10391]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/library.rs:326:26
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/library.rs:326:26
    at imports.wbg.__wbg_new_15d3966e9981a196 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:2215:21)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h837712c2d6f5ba6c (wasm://wasm/02acc9be:wasm-function[8120]:0x802444)
    at std::panicking::rust_panic_with_hook::ha23c8ba67d558e34 (wasm://wasm/02acc9be:wasm-function[5401]:0x737571)
    at core::panicking::panic_fmt::h573ffd15dee74109 (wasm://wasm/02acc9be:wasm-function[7999]:0x7fd51f)
    at core::panicking::panic::hb07ae4df23db8663 (wasm://wasm/02acc9be:wasm-function[7406]:0x7ca00b)
    at ruffle_core::display_object::movie_clip::MovieClip::preload::h054aaa0428b759f2 (wasm://wasm/02acc9be:wasm-function[620]:0x1e6bc6)
    at ruffle_core::loader::Loader::preload_tick::h00f7a0e42a06483e (wasm://wasm/02acc9be:wasm-function[795]:0x2a9fe7)
    at ruffle_web::Ruffle::tick::h98104193cf237788 (wasm://wasm/02acc9be:wasm-function[694]:0x24c026)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h34a4cd50e0a5d019 (wasm://wasm/02acc9be:wasm-function[9752]:0x83b5e6)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::heaf8b3636e007a05 (wasm://wasm/02acc9be:wasm-function[8635]:0x80dd0b)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: game.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://f.kbhgames.com/2014/OmniverseCollection/game.htm
SWF URL: https://f.kbhgames.com/2014/OmniverseCollection/game.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-03-26
Channel: nightly
Built: 2023-03-26T00:19:13.964Z
Commit: 65d2fca7bd850cdfff1942ae7926fd910e05ec24
Is extension: true

# Metadata
width: 800
height: 800
frameRate: 24
numFrames: 1
swfVersion: 8
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 10342

**Comment by Lord-McSweeney** [comment]
This seems to be related to an AVM1 movie loading an AVM2 movie.

**Comment by Lord-McSweeney** [comment]
There are still some minor text rendering issues, but this no longer panics (was fixed by #11005).
