### ISSUE TITLE
Error on https://www.gameflare.com/embed/dream-car-racing/

### ISSUE THREAD

**Issue by continuum1** [ruffle-rs/ruffle#10448]
# Error Info
Error name: Error
Error message: panicked at 'internal error: entered unreachable code', core/src/avm2/regexp.rs:411:22
Error stack:
```
Error: panicked at 'internal error: entered unreachable code', core/src/avm2/regexp.rs:411:22
    at imports.wbg.__wbg_new_15d3966e9981a196 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:2212:21)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hdb025c08ea6ea4a5 (wasm://wasm/02ac463e:wasm-function[8125]:0x800631)
    at std::panicking::rust_panic_with_hook::hc53aea0352e77326 (wasm://wasm/02ac463e:wasm-function[5413]:0x735ad3)
    at core::panicking::panic_fmt::hf4a9df75710ece83 (wasm://wasm/02ac463e:wasm-function[8009]:0x7fb842)
    at core::panicking::panic::h54beb3f515dd3c6d (wasm://wasm/02ac463e:wasm-function[7416]:0x7c83c0)
    at ruffle_core::avm2::regexp::RegExp::find_utf16_match::hef91262c330313a7 (wasm://wasm/02ac463e:wasm-function[774]:0x29d92c)
    at ruffle_core::avm2::globals::string::replace::ha02cb1031b187b65 (wasm://wasm/02ac463e:wasm-function[943]:0x3282b0)
    at ruffle_core::avm2::function::Executable::exec::h2774ab58e122c725 (wasm://wasm/02ac463e:wasm-function[912]:0x30cec3)
    at ruffle_core::avm2::object::TObject::call_property::hd73f35ad6f42cb31 (wasm://wasm/02ac463e:wasm-function[1087]:0x371eed)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::h58b73a121c778a83 (wasm://wasm/02ac463e:wasm-function[2651]:0x5b4f88)
```
AVM2 stack:
```
    at String/replace()
    at ----___-__$/-___-_---__()
    at local::-_--__----$/--_-___-__-()
    at local::-_--__----$/--__--__--_()
    at -__-_--___--/init()
    at flash.display::DisplayObjectContainer/flash::display::DisplayObjectContainer::addChild()
    at --__-_---_/init()
    at flash.display::DisplayObjectContainer/flash::display::DisplayObjectContainer::addChild()
    at Main/521423742387123423632234()
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.gameflare.com/embed/dream-car-racing/
SWF URL: https://data.gameflare.com/games/5094/PKEFtOfnJ3QyHY.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 OPR/96.0.0.0
Platform: Win32
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-03-29
Channel: nightly
Built: 2023-03-29T00:22:09.432Z
Commit: b0eb1057f1c084c054ea51aed5ab7d8e2d451db9
Is extension: false

# Metadata
width: 800
height: 600
frameRate: 30
numFrames: 2
swfVersion: 11
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 1686168

**Comment by n0samu** [comment]
This will be fixed by #10445
