### ISSUE TITLE
Error on https://game98309.konggames.com/games/gamezhero/tentacle-wars/frame/7c96976f-173d-4547-acea-902ccb430381/

### ISSUE THREAD

**Issue by vedabrat** [ruffle-rs/ruffle#10450]
# Error Info
Error name: Error
Error message: panicked at 'No caller domain available - use Activation::from_domain when constructing your domain', core/src/avm2/activation.rs:676:28
Error stack:
```
Error: panicked at 'No caller domain available - use Activation::from_domain when constructing your domain', core/src/avm2/activation.rs:676:28
    at O.n.wbg.__wbg_new_15d3966e9981a196 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.bbf92d6ba39c089443f3.js:1:47895)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hdb025c08ea6ea4a5 (wasm://wasm/02ac463e:wasm-function[8125]:0x800631)
    at std::panicking::rust_panic_with_hook::hc53aea0352e77326 (wasm://wasm/02ac463e:wasm-function[5413]:0x735ad3)
    at core::panicking::panic_fmt::hf4a9df75710ece83 (wasm://wasm/02ac463e:wasm-function[8009]:0x7fb870)
    at core::option::expect_failed::h8f07431afd4c5625 (wasm://wasm/02ac463e:wasm-function[9294]:0x828594)
    at ruffle_core::avm2::function::Executable::exec::h2774ab58e122c725 (wasm://wasm/02ac463e:wasm-function[912]:0x30cf22)
    at ruffle_core::avm2::object::TObject::call_method::h3addb25e0d597ed1 (wasm://wasm/02ac463e:wasm-function[1848]:0x4c7eb6)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::init_property::ha4b5dcaf3d08ce1f (wasm://wasm/02ac463e:wasm-function[548]:0x141c14)
    at ruffle_core::display_object::TDisplayObject::on_construction_complete::hd2cc79057b7943f9 (wasm://wasm/02ac463e:wasm-function[1020]:0x352f3c)
    at <ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::construct_frame::h63a82ea9f5d8d2d0 (wasm://wasm/02ac463e:wasm-function[609]:0x1c7fb3)
```
AVM2 stack:
```
    at flash.display::DisplayObject/flash.display::DisplayObject()
    at flash.display::InteractiveObject/flash.display::InteractiveObject()
    at flash.display::DisplayObjectContainer/flash.display::DisplayObjectContainer()
    at flash.display::Sprite()
    at flash.display::MovieClip()
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://game98309.konggames.com/games/gamezhero/tentacle-wars/frame/7c96976f-173d-4547-acea-902ccb430381/?kongregate_host=www.kongregate.com
SWF URL: https://game98309.konggames.com/gamez/0009/8309/live/tentaclewars_v1_1_kg_score_plus_ach_2.swf?kongregate_game_version=1292577006

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
Platform: Win32
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-03-29
Channel: nightly
Built: 2023-03-29T00:22:09.432Z
Commit: b0eb1057f1c084c054ea51aed5ab7d8e2d451db9
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 20
numFrames: 2
swfVersion: 10
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 1773491

**Comment by desertking** [comment]
The game seems to still have an error after each level the sponsor logo is out of the box and blocks the buttons
