### ISSUE TITLE
Error on https://www.gameflare.com/embed/go-to-hell/

### ISSUE THREAD

**Issue by dansolgit** [ruffle-rs/ruffle#10473]
# Error Info
Error name: Error
Error message: panicked at 'already mutably borrowed: BorrowError', core/src/avm2/globals/flash/display/bitmap_data.rs:262:46
Error stack:
```
Error: panicked at 'already mutably borrowed: BorrowError', core/src/avm2/globals/flash/display/bitmap_data.rs:262:46
    at U.n.wbg.__wbg_new_15d3966e9981a196 (https://www.gameflare.com/emulators/ruffle/core.ruffle.9355db4f71f177e62aac.js:1:48013)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h837712c2d6f5ba6c (wasm://wasm/02ac07e6:wasm-function[8120]:0x7fedc1)
    at std::panicking::rust_panic_with_hook::ha23c8ba67d558e34 (wasm://wasm/02ac07e6:wasm-function[5403]:0x7332ad)
    at core::panicking::panic_fmt::h573ffd15dee74109 (wasm://wasm/02ac07e6:wasm-function[7999]:0x7f9eca)
    at core::result::unwrap_failed::h26e3bef5a756b770 (wasm://wasm/02ac07e6:wasm-function[6184]:0x7719aa)
    at gc_arena::gc_cell::GcCell<T>::read::h00062293a33f0c55 (wasm://wasm/02ac07e6:wasm-function[7056]:0x7b8c72)
    at ruffle_core::avm2::globals::flash::display::bitmap_data::copy_pixels::h8f04f9dc4a00d7fd (wasm://wasm/02ac07e6:wasm-function[669]:0x22ce6d)
    at ruffle_core::avm2::function::Executable::exec::h7b3f7079a4ab3b00 (wasm://wasm/02ac07e6:wasm-function[909]:0x30940b)
    at ruffle_core::avm2::object::TObject::call_property::h6115d16b4c7945d0 (wasm://wasm/02ac07e6:wasm-function[1064]:0x365638)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::h2974edcd7b828c8d (wasm://wasm/02ac07e6:wasm-function[2649]:0x5b3ccd)
```
AVM2 stack:
```
    at flash.display::BitmapData/flash::display::BitmapData::copyPixels()
    at go_to_hell::Metaboard/render()
    at go_to_hell::Board/processFrame()
    at go_to_hell::Board/enterFrame()
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.gameflare.com/embed/go-to-hell/
SWF URL: https://data.gameflare.com/games/553/lcZ0cuI1WNhkeH.swf

# Browser Info
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
Platform: MacIntel
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-03-27
Channel: nightly
Built: 2023-03-27T00:19:44.420Z
Commit: cb9d02e3dd462ce390c7752aaaf915929b1e770a
Is extension: false

# Metadata
width: 400
height: 440
frameRate: 30
numFrames: 4
swfVersion: 9
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 2046482

**Comment by Lord-McSweeney** [comment]
Closing in favor of #9669.
