### ISSUE TITLE
Error on https://kdata1.com/games/SSF9_2011/

### ISSUE THREAD

**Issue by NeoSora2003** [ruffle-rs/ruffle#10505]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/library.rs:347:26
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/library.rs:347:26
    at imports.wbg.__wbg_new_15d3966e9981a196 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:2212:21)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h927501cce3fc7417 (wasm://wasm/02add8aa:wasm-function[8169]:0x8058cd)
    at std::panicking::rust_panic_with_hook::hc53aea0352e77326 (wasm://wasm/02add8aa:wasm-function[5446]:0x7390b5)
    at core::panicking::panic_fmt::hf4a9df75710ece83 (wasm://wasm/02add8aa:wasm-function[8051]:0x80053c)
    at core::panicking::panic::h54beb3f515dd3c6d (wasm://wasm/02add8aa:wasm-function[7456]:0x7cc303)
    at ruffle_core::display_object::movie_clip::MovieClip::preload::h8b435e95ba744ef1 (wasm://wasm/02add8aa:wasm-function[617]:0x1e3ba7)
    at ruffle_core::loader::Loader::preload_tick::h047fbf064d084cd5 (wasm://wasm/02add8aa:wasm-function[758]:0x286f25)
    at ruffle_web::Ruffle::tick::h34d7356c042327a9 (wasm://wasm/02add8aa:wasm-function[683]:0x23c0dd)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h3339895efa4d93d4 (wasm://wasm/02add8aa:wasm-function[9796]:0x83e2ad)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hfa30efc5d157bfb9 (wasm://wasm/02add8aa:wasm-function[8683]:0x8111e1)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: game.swf
Param movie: game.swf
Param wmode: direct
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined

# Page Info
Page URL: https://kdata1.com/games/SSF9_2011/
SWF URL: https://kdata1.com/games/SSF9_2011/game.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-04-01
Channel: nightly
Built: 2023-04-01T00:23:12.618Z
Commit: 6fda813f0c329200cb6ca345c3f3debf35423f40
Is extension: true

# Metadata
width: 800
height: 800
frameRate: 24
numFrames: 1
swfVersion: 8
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 10342

**Comment by Lord-McSweeney** [comment]
This is caused by an AVM1 movie loading an AVM2 movie, which Ruffle does not yet support.
