### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by fryiopl** [ruffle-rs/ruffle#10537]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/bitmap/bitmap_data.rs:595:51
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/bitmap/bitmap_data.rs:595:51
    at O.n.wbg.__wbg_new_15d3966e9981a196 (https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.d0557de10628cbe98f62.js:1:47949)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h927501cce3fc7417 (wasm://wasm/02a79bda:wasm-function[8163]:0x7ef5ba)
    at std::panicking::rust_panic_with_hook::hc53aea0352e77326 (wasm://wasm/02a79bda:wasm-function[5431]:0x71d11b)
    at core::panicking::panic_fmt::hf4a9df75710ece83 (wasm://wasm/02a79bda:wasm-function[8045]:0x7ea229)
    at core::panicking::panic::h54beb3f515dd3c6d (wasm://wasm/02a79bda:wasm-function[7446]:0x7b6c2c)
    at ruffle_core::bitmap::bitmap_data::BitmapData::update_dirty_texture::hee3ddbdfbdc50e9d (wasm://wasm/02a79bda:wasm-function[1247]:0x3a8cdd)
    at <ruffle_core::library::MovieLibrarySource as ruffle_render::bitmap::BitmapSource>::bitmap_handle::h0909caf8b3654249 (wasm://wasm/02a79bda:wasm-function[3167]:0x5fb350)
    at <ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::register_shape::hd515b52f2b24d068 (wasm://wasm/02a79bda:wasm-function[1036]:0x3413a1)
    at ruffle_core::display_object::movie_clip::MovieClipData::define_shape::h2a01979e41768b81 (wasm://wasm/02a79bda:wasm-function[2984]:0x5dfcfd)
    at ruffle_core::display_object::movie_clip::MovieClip::preload::h8b435e95ba744ef1 (wasm://wasm/02a79bda:wasm-function[618]:0x1ca2c5)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.67&browsermode=mobile&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1680481367%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F774000%2F774829_flash-belt-fourze.swf%3F1644856400%22%2C%22vars%22%3A%7B%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%22642ac562ec952%22%2C%22NewgroundsAPI_SessionID%22%3A%22%22%2C%22NewgroundsAPI_UserName%22%3A%22%26lt%3Bdeleted%26gt%3B%22%2C%22NewgroundsAPI_UserID%22%3A0%2C%22ng_username%22%3A%22%26lt%3Bdeleted%26gt%3B%22%7D%2C%22width%22%3A1040%2C%22height%22%3A585%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F774000%2Fflash_774829_card.png%3Ff1608248133%22%2C%22warnOnUnsupportedContent%22%3Afalse%7D
SWF URL: https://uploads.ungrounded.net/774000/774829_flash-belt-fourze.swf?1644856400

# Browser Info
User Agent: Mozilla/5.0 (Linux; Android 13; SM-F916N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Mobile Safari/537.36
Platform: Linux aarch64
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-04-03
Channel: nightly
Built: 2023-04-03T00:21:21.992Z
Commit: 9441182b7d70d334ea6a7921f9b5541246a5a447
Is extension: false

# Metadata
width: 1040
height: 585
frameRate: 30
numFrames: 502
swfVersion: 15
backgroundColor: #FFFFFF
isActionScript3: false
uncompressedLength: 62964677

**Comment by n0samu** [comment]
Hi, can you tell us what led up to this error? Did it happen at a specific point in the game?
