### ISSUE TITLE
Anbot - Weird Loops everywhere

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#10546]
# Error Info
Error name: Error
Error message: panicked at 'No script object for display object', core/src/avm1/activation.rs:396:18
Error stack:
```
Error: panicked at 'No script object for display object', core/src/avm1/activation.rs:396:18
    at O.n.wbg.__wbg_new_15d3966e9981a196 (https://www.spiele-umsonst.de/ruffle/core.ruffle.d0557de10628cbe98f62.js:1:47949)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h927501cce3fc7417 (wasm://wasm/02a79bda:wasm-function[8163]:0x7ef5ba)
    at std::panicking::rust_panic_with_hook::hc53aea0352e77326 (wasm://wasm/02a79bda:wasm-function[5431]:0x71d11b)
    at core::panicking::panic_fmt::hf4a9df75710ece83 (wasm://wasm/02a79bda:wasm-function[8045]:0x7ea229)
    at ruffle_core::display_object::edit_text::EditText::try_bind_text_field_variable::hd3678225016fbaa9 (wasm://wasm/02a79bda:wasm-function[864]:0x2dab45)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::hcd6dc3ef44c0642a (wasm://wasm/02a79bda:wasm-function[2817]:0x5b8648)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::h3e925d65c8f046f1 (wasm://wasm/02a79bda:wasm-function[775]:0x29027a)
    at ruffle_core::display_object::movie_clip::MovieClip::place_object::h6857bb7c2b238038 (wasm://wasm/02a79bda:wasm-function[1565]:0x42345a)
    at <ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::enter_frame::hb8ef6c72ed998900 (wasm://wasm/02a79bda:wasm-function[785]:0x297979)
    at <ruffle_core::display_object::loader_display::LoaderDisplay as ruffle_core::display_object::TDisplayObject>::enter_frame::hebf232eab80e2adf (wasm://wasm/02a79bda:wasm-function[3016]:0x5e5cdb)
```

# Player Info
Allows script access: false

# Page Info
SWF URL: https://www.spiele-umsonst.de/azad/downloads/flashgames/Anbot.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-04-03
Channel: nightly
Built: 2023-04-03T00:21:21.992Z
Commit: 9441182b7d70d334ea6a7921f9b5541246a5a447
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 40
numFrames: 2
swfVersion: 10
backgroundColor: #FFFFFF
isActionScript3: true
uncompressedLength: 2366401

**Comment by n0samu** [comment]
This is an AVM1 game encrypted with MochiCrypt, which uses AVM2. Ruffle does not correctly play AVM1 movies loaded by AVM2 movies right now. If the original AVM1 movie is extracted from the MochiCrypt wrapper and played on its own, Ruffle works fine.
