### ISSUE TITLE
Error on https://ruffle.rs/demo/

### ISSUE THREAD

**Issue by EARTH-CODE-42** [ruffle-rs/ruffle#10568]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/bitmap/bitmap_data.rs:602:51
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/bitmap/bitmap_data.rs:602:51
    at O.n.wbg.__wbg_new_15d3966e9981a196 (https://ruffle.rs/demo/339.index.js:1:48008)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h31d10b9661c38166 (wasm://wasm/02a88bae:wasm-function[8148]:0x7f2725)
    at std::panicking::rust_panic_with_hook::hc53aea0352e77326 (wasm://wasm/02a88bae:wasm-function[5438]:0x7271c7)
    at core::panicking::panic_fmt::hf4a9df75710ece83 (wasm://wasm/02a88bae:wasm-function[8029]:0x7ed363)
    at core::panicking::panic::h54beb3f515dd3c6d (wasm://wasm/02a88bae:wasm-function[7437]:0x7b9f9f)
    at ruffle_core::bitmap::bitmap_data::BitmapData::update_dirty_texture::hefb37dc961254f68 (wasm://wasm/02a88bae:wasm-function[1229]:0x3a6875)
    at ruffle_core::bitmap::operations::draw::h4d71a1aa8096bd73 (wasm://wasm/02a88bae:wasm-function[961]:0x324dce)
    at ruffle_core::avm2::globals::flash::display::bitmap_data::draw::h0bf64697d4f531a9 (wasm://wasm/02a88bae:wasm-function[811]:0x2b3197)
    at ruffle_core::avm2::function::Executable::exec::h459ce63d33fcd2f3 (wasm://wasm/02a88bae:wasm-function[926]:0x30cedd)
    at ruffle_core::avm2::object::TObject::call_property::h1097bc6af6a3d974 (wasm://wasm/02a88bae:wasm-function[1059]:0x3550f4)
```
AVM2 stack:
```
    at flash.display::BitmapData/flash::display::BitmapData::draw()
    at items::ItemManager$/init()
    at EverybodyEdits/handleAttach()
    at flash.display::DisplayObjectContainer/flash::display::DisplayObjectContainer::addChild()
    at MethodInfo-2()
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://ruffle.rs/demo/

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 Edg/111.0.1661.62
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-04-05
Channel: nightly
Built: 2023-04-05T00:22:01.065Z
Commit: e9a030de54762c9b83bf8ab8370753b00f669dd3
Is extension: false

# Metadata
width: 850
height: 500
frameRate: 60
numFrames: 2
swfVersion: 34
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 10658966

**Comment by n0samu** [comment]
The game is "Everybody Edits", right? https://web.archive.org/web/20200919143152/https://everybodyedits.com/game.swf

**Comment by EARTH-CODE-42** [comment]
> The game is "Everybody Edits", right? https://web.archive.org/web/20200919143152/https://everybodyedits.com/game.swf

yep😉
[EE Rewritten 1.4.0.zip](https://github.com/ruffle-rs/ruffle/files/11711626/EE.Rewritten.1.4.0.zip)

**Comment by n0samu** [comment]
I'm getting a slightly different error now:
```
thread 'main' panicked at 'wgpu error: Validation Error

Caused by:
    In CommandEncoder::copy_texture_to_buffer
    Copy error
    Copy of Y 0..16 would end up overrunning the bounds of the Source texture of Y size 14

', C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wgpu-0.16.1\src\backend\direct.rs:3019:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
AVM2 stack trace:
        at flash.display::BitmapData/flash::display::BitmapData::copyPixels()
        at items::ItemManager$/init()
        at EverybodyEdits/handleAttach()
        at flash.display::DisplayObjectContainer/flash::display::DisplayObjectContainer::addChild()
        at MethodInfo-2()
```

**Comment by Lord-McSweeney** [comment]
The original issue with the unwrap is fixed; someone else reported the same panic nosamu did, so closing in favor of #11662.
