### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by Georgiy-Kinyov** [ruffle-rs/ruffle#10607]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create texture object"', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.15.4/src/gles/web.rs:288:60
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create texture object"', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.15.4/src/gles/web.rs:288:60
    at O.n.wbg.__wbg_new_15d3966e9981a196 (https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.0c10f8af20d5d933ac27.js:1:47949)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hbac0af9b7f44ed2e (wasm://wasm/02a8eb4e:wasm-function[8149]:0x7f3533)
    at std::panicking::rust_panic_with_hook::hc53aea0352e77326 (wasm://wasm/02a8eb4e:wasm-function[5440]:0x727eec)
    at core::panicking::panic_fmt::hf4a9df75710ece83 (wasm://wasm/02a8eb4e:wasm-function[8031]:0x7ee1d0)
    at core::result::unwrap_failed::hc92dbc81ca7d2f52 (wasm://wasm/02a8eb4e:wasm-function[6215]:0x7658de)
    at <T as wgpu::context::DynContext>::surface_configure::h3b702125795a0fc6 (wasm://wasm/02a8eb4e:wasm-function[6824]:0x78a59a)
    at wgpu::Surface::configure::hc7ffaeb0fbe560bb (wasm://wasm/02a8eb4e:wasm-function[3114]:0x6022cf)
    at <ruffle_render_wgpu::target::SwapChainTarget as ruffle_render_wgpu::target::RenderTarget>::resize::h3882ca712f13572f (wasm://wasm/02a8eb4e:wasm-function[8411]:0x7f9684)
    at <ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::set_viewport_dimensions::hb88783ca2e8aca13 (wasm://wasm/02a8eb4e:wasm-function[4432]:0x6d052e)
    at ruffle_core::player::Player::set_viewport_dimensions::h4202cf4a6b549ef8 (wasm://wasm/02a8eb4e:wasm-function[1413]:0x3f2c87)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.67&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1680916555%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F544000%2F544332_Tower_of_Heaven.swf%3F1282644012%22%2C%22vars%22%3A%7B%22ngio_session_id%22%3A%2206215090.57c95a7f401346b516d2053a685990f5503f97bcd4d5f3%22%2C%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%22643104f7a691e%22%2C%22NewgroundsAPI_SessionID%22%3A%22zBvRrENywyQ7O5dkPut1a9941a099417fb196d4fa9763c50a9a39a248d89Iy9P%22%2C%22NewgroundsAPI_UserName%22%3A%22GeorgiyKinyov%22%2C%22NewgroundsAPI_UserID%22%3A13655338%2C%22ng_username%22%3A%22GeorgiyKinyov%22%7D%2C%22width%22%3A640%2C%22height%22%3A480%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F544000%2Fflash_544332_card.png%3Ff1608142002%22%2C%22warnOnUnsupportedContent%22%3Afalse%7D
SWF URL: https://uploads.ungrounded.net/544000/544332_Tower_of_Heaven.swf?1282644012

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-04-08
Channel: nightly
Built: 2023-04-08T00:21:09.271Z
Commit: d9e69563d3310edafb1806c91371f245c595738b
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 30
numFrames: 2
swfVersion: 10
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 11187374

**Comment by Georgiy-Kinyov** [comment]
Notice: this error is intermittent. Everything worked just fine when I tried reloading the page.
