### ISSUE TITLE
Error on https://flashstorage.games/embed/intrusion-2

### ISSUE THREAD

**Issue by Sirinsaniac** [ruffle-rs/ruffle#10618]
# Error Info
Error name: Error
Error message: panicked at 'index out of bounds: the len is 512 but the index is 512', core/src/bitmap/bitmap_data.rs:596:9
Error stack:
```
Error: panicked at 'index out of bounds: the len is 512 but the index is 512', core/src/bitmap/bitmap_data.rs:596:9
    at O.n.wbg.__wbg_new_15d3966e9981a196 (https://flashstorage.games/public/js/emulators/ruffle/core.ruffle.3bff15b5edc179b68ef0.js:1:47949)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hbac0af9b7f44ed2e (wasm://wasm/02a8d9ae:wasm-function[8145]:0x7f325f)
    at std::panicking::rust_panic_with_hook::hc53aea0352e77326 (wasm://wasm/02a8d9ae:wasm-function[5436]:0x727c18)
    at core::panicking::panic_fmt::hf4a9df75710ece83 (wasm://wasm/02a8d9ae:wasm-function[8027]:0x7edefc)
    at core::panicking::panic_bounds_check::h8c0b59521a475ac0 (wasm://wasm/02a8d9ae:wasm-function[6431]:0x7724f8)
    at ruffle_core::bitmap::operations::copy_channel::h9c6c101512cf728e (wasm://wasm/02a8d9ae:wasm-function[1300]:0x3c72a4)
    at ruffle_core::avm2::globals::flash::display::bitmap_data::copy_channel::h3a5ef16ac340cffd (wasm://wasm/02a8d9ae:wasm-function[804]:0x2ae523)
    at ruffle_core::avm2::function::Executable::exec::h459ce63d33fcd2f3 (wasm://wasm/02a8d9ae:wasm-function[923]:0x309847)
    at ruffle_core::avm2::object::TObject::call_property::h1097bc6af6a3d974 (wasm://wasm/02a8d9ae:wasm-function[1056]:0x352980)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::h3f129770ed67884e (wasm://wasm/02a8d9ae:wasm-function[2624]:0x59daa5)
```
AVM2 stack:
```
    at flash.display::BitmapData/flash::display::BitmapData::copyChannel()
    at BitmapFont()
    at  "/Init()
    at Main/init()
    at flash.display::DisplayObjectContainer/flash::display::DisplayObjectContainer::addChild()
    at Preloader/startup()
    at Preloader/loadingFinished()
    at Preloader/checkFrame()
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://flashstorage.games/embed/intrusion-2
SWF URL: https://flashstorage.games/public/storage/games/FLASHJanuary2022/intrusion-2.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-04-07
Channel: nightly
Built: 2023-04-07T00:18:37.990Z
Commit: 60ae2edf92496436797aea4e2c97da1c970d6f38
Is extension: false

# Metadata
width: 720
height: 540
frameRate: 30
numFrames: 2
swfVersion: 9
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 20750030

**Comment by n0samu** [comment]
See also: #9623

**Comment by n0samu** [comment]
This regression was caused by commit 2b84e926ecd9fb03e81c61c0fb6df0bf0a1fa6d7 of #10315.

**Comment by Lord-McSweeney** [comment]
Fixed.
