### ISSUE TITLE
Error on https://frivlegend.com/public/files/slice-the-box

### ISSUE THREAD

**Issue by Sirinsaniac** [ruffle-rs/ruffle#10619]
# Error Info
Error name: Error
Error message: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:594:9
Error stack:
```
Error: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:594:9
    at W.n.wbg.__wbg_new_f9bb493369a83c12 (https://frivlegend.com/public/js/ruffle/core.ruffle.c110e09463ad81cadf9e.js:1:5412)
    at std::sync::once::Once::call_once::{{closure}}::h24436b3e76607d05 (wasm://wasm/027a13a6:wasm-function[1921]:0x48dea0)
    at std::sys_common::once::generic::Once::call::he3f17a186e209b2a (wasm://wasm/027a13a6:wasm-function[1855]:0x47daa8)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hdf8faf7e861f36fc (wasm://wasm/027a13a6:wasm-function[7118]:0x7611cb)
    at std::panicking::rust_panic_with_hook::hd000e9fb43b5781d (wasm://wasm/027a13a6:wasm-function[5050]:0x6bedb5)
    at core::panicking::panic_fmt::h9d972fcdb087ce21 (wasm://wasm/027a13a6:wasm-function[7429]:0x76fef8)
    at core::option::expect_failed::h2a3c274559c0100e (wasm://wasm/027a13a6:wasm-function[8605]:0x79a609)
    at ruffle_core::display_object::stage::Stage::root_clip::h5e15fdfcc38dec3c (wasm://wasm/027a13a6:wasm-function[5042]:0x6bdd03)
    at ruffle_web::Ruffle::tick::h4371493cd888805b (wasm://wasm/027a13a6:wasm-function[655]:0x2028d6)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::hefde812b3acf17fb (wasm://wasm/027a13a6:wasm-function[9053]:0x7ab9ea)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://frivlegend.com/public/files/slice-the-box
SWF URL: https://frivlegend.com/public/storage/games/January2022/slice-the-box.swf?at=2022-01-28%2008:35:17

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-02-02
Channel: nightly
Built: 2023-02-02T00:19:19.827Z
Commit: 198e40fd2ef4a36b7a3679d24dd3e567bdc63423
Is extension: false

# Metadata
width: 800
height: 600
frameRate: 30
numFrames: 2
swfVersion: 18
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 1996282

**Comment by Lord-McSweeney** [comment]
Panic fixed in latest Ruffle.
