### ISSUE TITLE
Error on https://www.numuki.com/game/quirky-turkey/

### ISSUE THREAD

**Issue by Metallochrome** [ruffle-rs/ruffle#10652]
# Error Info
Error name: Error
Error message: panicked at 'slice index starts at 15 but ends at 14', /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/alloc/src/vec/mod.rs:2004:36
Error stack:
```
Error: panicked at 'slice index starts at 15 but ends at 14', /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/alloc/src/vec/mod.rs:2004:36
    at imports.wbg.__wbg_new_15d3966e9981a196 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:2216:21)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hbac0af9b7f44ed2e (wasm://wasm/02a7012a:wasm-function[8135]:0x7ecb7a)
    at std::panicking::rust_panic_with_hook::hc53aea0352e77326 (wasm://wasm/02a7012a:wasm-function[5462]:0x725777)
    at core::panicking::panic_fmt::hf4a9df75710ece83 (wasm://wasm/02a7012a:wasm-function[8017]:0x7e7817)
    at core::slice::index::slice_index_order_fail::h99ced4f7f4f5ffc8 (wasm://wasm/02a7012a:wasm-function[9307]:0x813fa4)
    at ruffle_core::avm2::globals::array::splice::h06be6cd53fbac52e (wasm://wasm/02a7012a:wasm-function[935]:0x301a2a)
    at ruffle_core::avm2::function::Executable::exec::h459ce63d33fcd2f3 (wasm://wasm/02a7012a:wasm-function[921]:0x2f8312)
    at ruffle_core::avm2::object::TObject::call_property::he6c88e95915a6dcd (wasm://wasm/02a7012a:wasm-function[1099]:0x3599fc)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::h3f129770ed67884e (wasm://wasm/02a7012a:wasm-function[2643]:0x59c863)
    at ruffle_core::avm2::activation::Activation::run_actions::hfdee8d876b27b45a (wasm://wasm/02a7012a:wasm-function[482]:0x2a0f8)
```
AVM2 stack:
```
    at Array/splice()
    at com.indigo.jp.utils.satellite::EventSatellite/destroySubscriber()
    at com.indigo.jp.objects::CustomObject/_killListeners_primary()
    at com.indigo.jp.objects::CustomObject/destroy()
    at com.indigo.jp.objects::ObstacleObject/destroy()
    at com.indigo.jp.objects::LevelObject/removeObject()
    at Function/apply()
    at com.greensock.core::TweenCore/complete()
    at com.greensock::TweenMax/complete()
    at com.greensock::TweenMax/renderTime()
    at com.greensock.core::SimpleTimeline/renderTime()
    at com.greensock::TweenLite$/updateAll()
```

# Player Info
Allows script access: false
Player type: Object
SWF URL: https://media.numuki.com/spongebob/games/spongebob-quirky-turkey/game.swf
Param movie: https://media.numuki.com/spongebob/games/spongebob-quirky-turkey/game.swf
Param base: https://media.numuki.com/spongebob/games/spongebob-quirky-turkey/
Param quality: best
Param allowScriptAccess: never
Param allowNetworking: internal
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://www.numuki.com/game/quirky-turkey/
SWF URL: https://media.numuki.com/spongebob/games/spongebob-quirky-turkey/game.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
Platform: Win32
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-04-10
Channel: nightly
Built: 2023-04-10T00:19:26.594Z
Commit: 81d907b9f0a3f4eae46e55d9abfa0f46796874e6
Is extension: true

# Metadata
width: 960
height: 500
frameRate: 30
numFrames: 2
swfVersion: 11
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 2662759

**Comment by Lord-McSweeney** [comment]
The easiest way to reproduce this bug is like this:
```
arr = [1, 2, 3];
arr.splice(2, -1);
```

**Comment by n0samu** [comment]
Yep, here is the relevant avmplus code: https://github.com/adobe/avmplus/blob/master/core/Array.as#L313

playerglobal is just taking in an array of arguments without looking at them. The native code is what's doing the coercion and I think we've learned before that Flash Player internally (on the native side) doesn't make much distinction between int and uint.

**Comment by Lord-McSweeney** [comment]
Fixed by #22045
