### ISSUE TITLE
Error on https://www.gamesflow.com/jeux.php

### ISSUE THREAD

**Issue by y4nci** [ruffle-rs/ruffle#10677]
# Error Info
Error name: Error
Error message: panicked at 'No script object for display object', core/src/avm1/activation.rs:396:18
Error stack:
```
Error: panicked at 'No script object for display object', core/src/avm1/activation.rs:396:18
    at U.n.wbg.__wbg_new_15d3966e9981a196 (https://www.gamesflow.com/include/p_jeux/ruffle/core.ruffle.828c823147b3e01419a0.js:1:47866)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h0312d4caddbaee90 (wasm://wasm/02a8438a:wasm-function[8041]:0x7f70c8)
    at std::panicking::rust_panic_with_hook::h8d0a63d0479a36c8 (wasm://wasm/02a8438a:wasm-function[5353]:0x72d280)
    at core::panicking::panic_fmt::h2a7f454a5f5da218 (wasm://wasm/02a8438a:wasm-function[7921]:0x7f23f2)
    at ruffle_core::display_object::edit_text::EditText::try_bind_text_field_variable::h9c5fbbbb126491b9 (wasm://wasm/02a8438a:wasm-function[3706]:0x68392c)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::he4a116ef9010da52 (wasm://wasm/02a8438a:wasm-function[3069]:0x604073)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::hd244d6ebb7358c42 (wasm://wasm/02a8438a:wasm-function[768]:0x28fda1)
    at ruffle_core::display_object::movie_clip::MovieClip::place_object::h97ffd21186ba2fdd (wasm://wasm/02a8438a:wasm-function[1560]:0x4352bf)
    at <ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::enter_frame::h57e3f4ff64f72aa1 (wasm://wasm/02a8438a:wasm-function[783]:0x29acd9)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::hd244d6ebb7358c42 (wasm://wasm/02a8438a:wasm-function[768]:0x28fddd)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://www.gamesflow.com/jeux.php?id=2183793
SWF URL: https://www.gamesflow.com/jeux/52eaf7b1b136d.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-03-19
Channel: nightly
Built: 2023-03-19T00:19:16.337Z
Commit: 5aac938e868e7dab2550d9482f754a6daf314921
Is extension: false

# Metadata
width: 550
height: 450
frameRate: 12
numFrames: 2
swfVersion: 10
backgroundColor: #FFFFFF
isActionScript3: true
uncompressedLength: 398344

**Comment by n0samu** [comment]
This is an AVM1 game encrypted with MochiCrypt, which uses AVM2. Ruffle does not correctly play AVM1 movies loaded by AVM2 movies right now. If the original AVM1 movie is extracted from the MochiCrypt wrapper and played on its own, Ruffle works fine.

**Comment by Lord-McSweeney** [comment]
This seems to be working now
