### ISSUE TITLE
Error on https://www.gamesitive.com/action/ninja-assassin.html

### ISSUE THREAD

**Issue by Awoursafid** [ruffle-rs/ruffle#10675]
# Error Info
Error name: Error
Error message: panicked at 'No script object for display object', core/src/avm1/activation.rs:396:18
Error stack:
```
Error: panicked at 'No script object for display object', core/src/avm1/activation.rs:396:18
    at U.n.wbg.__wbg_new_15d3966e9981a196 (https://www.gamesitive.com/ruffle/core.ruffle.491bd18f6064cdfdd2f6.js:1:48013)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h97b8c4d82111f198 (wasm://wasm/02ab2b12:wasm-function[8064]:0x7ffb63)
    at std::panicking::rust_panic_with_hook::ha23c8ba67d558e34 (wasm://wasm/02ab2b12:wasm-function[5408]:0x735907)
    at core::panicking::panic_fmt::h573ffd15dee74109 (wasm://wasm/02ab2b12:wasm-function[7947]:0x7fad41)
    at ruffle_core::display_object::edit_text::EditText::try_bind_text_field_variable::h9dde958a34b62e5e (wasm://wasm/02ab2b12:wasm-function[3726]:0x689b6b)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::h5108bb3a0793daee (wasm://wasm/02ab2b12:wasm-function[3078]:0x6057d1)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::ha8bf951187d53c3a (wasm://wasm/02ab2b12:wasm-function[771]:0x28b1ae)
    at ruffle_core::display_object::movie_clip::MovieClip::place_object::h0449b28a9eef9149 (wasm://wasm/02ab2b12:wasm-function[1558]:0x42ca9d)
    at <ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::enter_frame::h21477462c993e4c5 (wasm://wasm/02ab2b12:wasm-function[786]:0x298d3e)
    at ruffle_core::frame_lifecycle::catchup_display_object_to_frame::h2f5a7d6bf9bfe03c (wasm://wasm/02ab2b12:wasm-function[6135]:0x7703e1)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: https://www.gamesitive.com/games/Ninja-assassin.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://www.gamesitive.com/action/ninja-assassin.html
SWF URL: https://www.gamesitive.com/games/Ninja-assassin.swf

# Browser Info
User Agent: Mozilla/5.0 (Linux; Android 12; SAMSUNG SM-A125F) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/19.0 Chrome/102.0.5005.125 Mobile Safari/537.36
Platform: Linux armv8l
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-03-24
Channel: nightly
Built: 2023-03-24T00:24:35.383Z
Commit: eb44cc5395a9f2a0aa07e9bc9ef6b20d5c4249c2
Is extension: false

# Metadata
width: 550
height: 400
frameRate: 30
numFrames: 2
swfVersion: 10
backgroundColor: #009966
isActionScript3: true
uncompressedLength: 338470

**Comment by n0samu** [comment]
This is an AVM1 game encrypted with MochiCrypt, which uses AVM2. Ruffle does not correctly play AVM1 movies loaded by AVM2 movies right now. If the original AVM1 movie is extracted from the MochiCrypt wrapper and played on its own, Ruffle works fine.

**Comment by Awoursafid** [comment]
> This is an AVM1 game encrypted with MochiCrypt, which uses AVM2. Ruffle does not correctly play AVM1 movies loaded by AVM2 movies right now. If the original AVM1 movie is extracted from the MochiCrypt wrapper and played on its own, Ruffle works fine.

Thank you very much for your reply, I will try.
