### ISSUE TITLE
Error on http://www.era-igr.ru/games/embeded/battle-for-darkness/cheat-74/

### ISSUE THREAD

**Issue by rgsgs** [ruffle-rs/ruffle#10676]
# Error Info
Error name: Error
Error message: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:594:9
Error stack:
```
Error: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:594:9
    at W.n.wbg.__wbg_new_f9bb493369a83c12 (chrome-extension://oakbcaafbicdddpdlhbchhpblmhefngh/dist/966.js:1:5351)
    at std::sync::once::Once::call_once::{{closure}}::h5f93984c1300ca75 (wasm://wasm/02716a0a:wasm-function[1567]:0x40425f)
    at std::sys_common::once::generic::Once::call::h8801249ea31ccf7a (wasm://wasm/02716a0a:wasm-function[1975]:0x4959cd)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::he904c54109aabe24 (wasm://wasm/02716a0a:wasm-function[7086]:0x740531)
    at std::panicking::rust_panic_with_hook::hb42d415afcc11f2f (wasm://wasm/02716a0a:wasm-function[5008]:0x6a159c)
    at core::panicking::panic_fmt::h32de9c76c9d5eb0c (wasm://wasm/02716a0a:wasm-function[7406]:0x74f295)
    at core::option::expect_failed::hb1beef3e49ebedf1 (wasm://wasm/02716a0a:wasm-function[8488]:0x778b27)
    at ruffle_core::display_object::stage::Stage::root_clip::hee2f08cf0070ee82 (wasm://wasm/02716a0a:wasm-function[5018]:0x6a1e1f)
    at ruffle_web::Ruffle::tick::h0417e6aa98969dee (wasm://wasm/02716a0a:wasm-function[634]:0x20b05c)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h64fd3f678b931ac2 (wasm://wasm/02716a0a:wasm-function[8930]:0x788e47)
```

# Player Info
Allows script access: false

# Page Info
Page URL: http://www.era-igr.ru/games/embeded/battle-for-darkness/cheat-74/
SWF URL: http://www.flashgamehacks.com/games/battle-for-darknessp.swf?version=1418880165

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-01-19
Channel: nightly
Built: 2023-01-19T06:30:28.821Z
Commit: f19e31d005c278685fea2de5aaa1c89675ce8714
Is extension: true

# Metadata
width: 800
height: 550
frameRate: 60
numFrames: 50
swfVersion: 17
backgroundColor: #003300
isActionScript3: true
uncompressedLength: 11484074

**Comment by Lord-McSweeney** [comment]
This panic has been fixed in the latest version of Ruffle.
