### ISSUE TITLE
Error on https://ruffle.rs/demo/

### ISSUE THREAD

**Issue by kevinchen2046** [ruffle-rs/ruffle#10687]
# Error Info
Error name: Error
Error message: panicked at 'Vertex shader failed to compile: MissingVertexAttributeData(1)', render/wgpu/src/context3d/current_pipeline.rs:437:10
Error stack:
```
Error: panicked at 'Vertex shader failed to compile: MissingVertexAttributeData(1)', render/wgpu/src/context3d/current_pipeline.rs:437:10
    at O.n.wbg.__wbg_new_15d3966e9981a196 (https://ruffle.rs/demo/339.index.js:1:48008)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h31d10b9661c38166 (wasm://wasm/02a7ac72:wasm-function[8139]:0x7ef248)
    at std::panicking::rust_panic_with_hook::hc53aea0352e77326 (wasm://wasm/02a7ac72:wasm-function[5466]:0x727eb6)
    at core::panicking::panic_fmt::hf4a9df75710ece83 (wasm://wasm/02a7ac72:wasm-function[8020]:0x7e9eb4)
    at core::result::unwrap_failed::hc92dbc81ca7d2f52 (wasm://wasm/02a7ac72:wasm-function[6190]:0x761816)
    at <ruffle_render_wgpu::context3d::WgpuContext3D as ruffle_render::backend::Context3D>::process_command::h576dfea976007f71 (wasm://wasm/02a7ac72:wasm-function[508]:0xc0a7f)
    at ruffle_core::avm2::globals::flash::display3D::context_3d::draw_triangles::h29a321268fd884ca (wasm://wasm/02a7ac72:wasm-function[2303]:0x537f80)
    at ruffle_core::avm2::function::Executable::exec::h459ce63d33fcd2f3 (wasm://wasm/02a7ac72:wasm-function[924]:0x2fd480)
    at ruffle_core::avm2::object::TObject::call_property::hef16a247d2776989 (wasm://wasm/02a7ac72:wasm-function[1067]:0x34de9f)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::h3f129770ed67884e (wasm://wasm/02a7ac72:wasm-function[2649]:0x59ebb1)
```
AVM2 stack:
```
    at flash.display3D::Context3D/flash::display3D::Context3D::drawTriangles()
    at com.kickbackgames.s3d::Stage3DSpriteStage/renderScene()
    at com.kickbackgames.s3d::Stage3DSpriteStage/render()
    at net.flashpunk::Screen/redraw()
    at net.flashpunk::Engine/render()
    at net.flashpunk::Engine/onEnterFrame()
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://ruffle.rs/demo/

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-04-14
Channel: nightly
Built: 2023-04-14T00:19:18.722Z
Commit: fef7eeed907bb03bc02e92723b21fade6b4521a7
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 60
numFrames: 1
swfVersion: 13
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 26634464

**Comment by n0samu** [comment]
Hi, what SWF were you trying to play when the error occurred?

**Comment by n0samu** [comment]
No information provided, closing
