### ISSUE TITLE
Error on https://frivlegend.com/public/files/tu-95

### ISSUE THREAD

**Issue by Sef69** [ruffle-rs/ruffle#10723]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/bitmap/bitmap_data.rs:602:51
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/bitmap/bitmap_data.rs:602:51
    at O.n.wbg.__wbg_new_15d3966e9981a196 (https://frivlegend.com/public/js/ruffle/core.ruffle.3bff15b5edc179b68ef0.js:1:47949)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hbac0af9b7f44ed2e (wasm://wasm/02a8d9ae:wasm-function[8145]:0x7f325f)
    at std::panicking::rust_panic_with_hook::hc53aea0352e77326 (wasm://wasm/02a8d9ae:wasm-function[5436]:0x727c18)
    at core::panicking::panic_fmt::hf4a9df75710ece83 (wasm://wasm/02a8d9ae:wasm-function[8027]:0x7edece)
    at core::panicking::panic::h54beb3f515dd3c6d (wasm://wasm/02a8d9ae:wasm-function[7434]:0x7baace)
    at ruffle_core::bitmap::bitmap_data::BitmapData::update_dirty_texture::hefb37dc961254f68 (wasm://wasm/02a8d9ae:wasm-function[1225]:0x3a3a5c)
    at <ruffle_core::library::MovieLibrarySource as ruffle_render::bitmap::BitmapSource>::bitmap_handle::h38d21e8290bf8b6c (wasm://wasm/02a8d9ae:wasm-function[3179]:0x60c7e9)
    at <ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::register_shape::hae4c31908e0addd1 (wasm://wasm/02a8d9ae:wasm-function[1037]:0x3494e0)
    at ruffle_core::display_object::movie_clip::MovieClipData::define_shape::h6634889bf94fc67f (wasm://wasm/02a8d9ae:wasm-function[2998]:0x5f0251)
    at ruffle_core::display_object::movie_clip::MovieClip::preload::h515cadf80469be7e (wasm://wasm/02a8d9ae:wasm-function[619]:0x1d2bd1)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://frivlegend.com/public/files/tu-95
SWF URL: https://frivlegend.com/public/storage/games/November2021/puuROYRMXjJHzm68REMX.swf?at=2021-11-16%2000:29:43

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-04-07
Channel: nightly
Built: 2023-04-07T00:18:37.990Z
Commit: 60ae2edf92496436797aea4e2c97da1c970d6f38
Is extension: false

# Metadata
width: 670
height: 450
frameRate: 24
numFrames: 31
swfVersion: 9
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 3871229

**Comment by Lord-McSweeney** [comment]
Closing in favor of #10843.
