### ISSUE TITLE
"Mad Karate Man" Crash on start (Build nightly 2023-04-19)

### ISSUE THREAD

**Issue by RStryke** [ruffle-rs/ruffle#10740]
### Describe what you were doing

Attempting to play "Mad Karate Man" at: https://www.kongregate.com/games/ninjakiwi/mad-karate-man

### What does the crash message say?

# Error Info
Error name: Error
Error message: panicked at 'No script object for display object', core/src/avm1/activation.rs:396:18
Error stack:
```
Error: panicked at 'No script object for display object', core/src/avm1/activation.rs:396:18
    at O.n.wbg.__wbg_new_15d3966e9981a196 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.a648731f80678e415588.js:1:47949)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hbac0af9b7f44ed2e (wasm://wasm/02a7785a:wasm-function[8134]:0x7ee7f9)
    at std::panicking::rust_panic_with_hook::hc53aea0352e77326 (wasm://wasm/02a7785a:wasm-function[5462]:0x727498)
    at core::panicking::panic_fmt::hf4a9df75710ece83 (wasm://wasm/02a7785a:wasm-function[8016]:0x7e9468)
    at ruffle_core::display_object::edit_text::EditText::try_bind_text_field_variable::h5e7c07cdf91e2471 (wasm://wasm/02a7785a:wasm-function[864]:0x2d1bb9)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::h1dba24217afabf1d (wasm://wasm/02a7785a:wasm-function[2847]:0x5c2184)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::hd84fb6f602ec2e60 (wasm://wasm/02a7785a:wasm-function[777]:0x293b4b)
    at ruffle_core::display_object::movie_clip::MovieClip::place_object::h74a63696e0e4a88f (wasm://wasm/02a7785a:wasm-function[1563]:0x41dbe8)
    at <ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::enter_frame::h3c3024109b2e33ab (wasm://wasm/02a7785a:wasm-function[788]:0x29abfb)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::hd84fb6f602ec2e60 (wasm://wasm/02a7785a:wasm-function[777]:0x293b87)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://game73259.konggames.com/games/Ninjakiwi/mad-karate-man/frame/368ea2e9-95f5-429c-b873-b50b95ec337d/?kongregate_host=www.kongregate.com
SWF URL: https://game73259.konggames.com/gamez/0007/3259/live/mkm_world.swf?kongregate_game_version=1267572991

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-04-19
Channel: nightly
Built: 2023-04-19T00:19:17.744Z
Commit: 4f4327b152087379bae0d566a5d80aa7c9b9c477
Is extension: false

# Metadata
width: 550
height: 400
frameRate: 60
numFrames: 2
swfVersion: 10
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 1069870

### Ruffle Version

nightly 2023-04-19

### Affected platform

Self-hosted version

### Operating system

Windows 10

**Comment by n0samu** [comment]
This is an AVM1 game encrypted with MochiCrypt, which uses AVM2. Ruffle does not correctly play AVM1 movies loaded by AVM2 movies right now. If the original AVM1 movie is extracted from the MochiCrypt wrapper and played on its own, Ruffle works fine.

**Comment by RStryke** [comment]
Can verify the game works now, great work y'all!
