### ISSUE TITLE
Error on https://www.gamezhero.com/get-game-code/164bf317ea19ccfd9e97853edc2389f4

### ISSUE THREAD

**Issue by lalaisbaby** [ruffle-rs/ruffle#10851]
# Error Info
Error name: Error
Error message: panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:525:5
Error stack:
```
Error: panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:525:5
    at imports.wbg.__wbg_new_15d3966e9981a196 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:2258:21)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hd28f65a61f685e47 (wasm://wasm/02b61d02:wasm-function[8383]:0x80c16a)
    at std::panicking::rust_panic_with_hook::h7f7102b82d51338f (wasm://wasm/02b61d02:wasm-function[5498]:0x72f1b8)
    at core::panicking::panic_fmt::he4489d678d6570d5 (wasm://wasm/02b61d02:wasm-function[8238]:0x8069e8)
    at alloc::raw_vec::capacity_overflow::h743526e95bf6b28b (wasm://wasm/02b61d02:wasm-function[8014]:0x801def)
    at alloc::raw_vec::RawVec<T,A>::reserve::do_reserve_and_handle::h07da55bc9c349c86 (wasm://wasm/02b61d02:wasm-function[5377]:0x722fb0)
    at ruffle_core::avm2::globals::flash::utils::byte_array::set_length::ha3af8f98056fb6c9 (wasm://wasm/02b61d02:wasm-function[3403]:0x64a16a)
    at ruffle_core::avm2::function::Executable::exec::hb5981ebd76854dce (wasm://wasm/02b61d02:wasm-function[781]:0x2ac733)
    at ruffle_core::avm2::object::TObject::call_method::h058bcfcd584e2d7c (wasm://wasm/02b61d02:wasm-function[1929]:0x4c3f2d)
    at ruffle_core::avm2::object::TObject::set_property::hf7ac531dae35065d (wasm://wasm/02b61d02:wasm-function[2163]:0x510091)
```
AVM2 stack:
```
    at flash.utils::ByteArray/flash::utils::ByteArray::length()
    at global()
    at global()
    at global()
    at global()
    at global()
    at global()
    at global()
    at global()
    at global()
    at global()
    at global()
    at global()
    at global()
    at com.adobe.flascc::CModule$/callI()
    at com.adobe.flascc::CModule$/start()
    at com.adobe.flascc::CModule$/startAsync()
    at com.adobe.flascc::Console/enterFrame()
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: //files.gamezhero.com/game/da6/28f/da628fb30b7463a5/data/minidash.swf
Param allowfullscreen: true
Param swliveconnect: true
Param allowscriptaccess: always
Param wmode: direct
Param base: //files.gamezhero.com/game/da6/28f/da628fb30b7463a5/data/
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined

# Page Info
Page URL: https://www.gamezhero.com/get-game-code/164bf317ea19ccfd9e97853edc2389f4
SWF URL: https://files.gamezhero.com/game/da6/28f/da628fb30b7463a5/data/minidash.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-04-27
Channel: nightly
Built: 2023-04-27T00:19:14.885Z
Commit: e5caf0fda82f408af6f2b4f8d05c44603b037eee
Is extension: true

# Metadata
width: 800
height: 533
frameRate: 0.1171875
numFrames: 1
swfVersion: 18
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 20580648

**Comment by n0samu** [comment]
See also: full stack trace in #11854

**Comment by Lord-McSweeney** [comment]
Closing in favor of #21604
