### ISSUE TITLE
Error on https://sexgamescc.com/ebb0a538ff098bb37dcb82d09f52c93f-slave-lords-of-the-galaxy-1-0-1

### ISSUE THREAD

**Issue by NAHV-yo** [ruffle-rs/ruffle#10895]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:491:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:491:50
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://sexgamescc.com/assets/ruffle/ruffle.js:1:7026)
    at std::sync::once::Once::call_once::{{closure}}::h6e694fc45f651103 (https://sexgamescc.com/assets/ruffle/bf26055d72565393d5ae.wasm:wasm-function[1085]:0x28c132)
    at std::sync::once::Once::call_inner::h99e47643887ee5a5 (https://sexgamescc.com/assets/ruffle/bf26055d72565393d5ae.wasm:wasm-function[960]:0x26329f)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hb552ca3003b47989 (https://sexgamescc.com/assets/ruffle/bf26055d72565393d5ae.wasm:wasm-function[3856]:0x41f24c)
    at std::panicking::rust_panic_with_hook::h03201bc01a0ed891 (https://sexgamescc.com/assets/ruffle/bf26055d72565393d5ae.wasm:wasm-function[3008]:0x3bacee)
    at rust_begin_unwind (https://sexgamescc.com/assets/ruffle/bf26055d72565393d5ae.wasm:wasm-function[4064]:0x424b97)
    at core::panicking::panic_fmt::hd44f353696296fec (https://sexgamescc.com/assets/ruffle/bf26055d72565393d5ae.wasm:wasm-function[4212]:0x42b594)
    at core::option::expect_none_failed::hf7dab2706f1a5551 (https://sexgamescc.com/assets/ruffle/bf26055d72565393d5ae.wasm:wasm-function[3448]:0x40d618)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::he06901c88d3868a1 (https://sexgamescc.com/assets/ruffle/bf26055d72565393d5ae.wasm:wasm-function[604]:0x1aacae)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::register_glyph_shape::h7dde7e72de3b7b27 (https://sexgamescc.com/assets/ruffle/bf26055d72565393d5ae.wasm:wasm-function[2172]:0x363b03)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: https://v8p5i7f9.ssl.hwcdn.net/games/swf/a/1/4/a147d61b8fb6986859d85dff2c9b458c/a147d61b8fb6986859d85dff2c9b458c.swf
Param movie: https://v8p5i7f9.ssl.hwcdn.net/games/swf/a/1/4/a147d61b8fb6986859d85dff2c9b458c/a147d61b8fb6986859d85dff2c9b458c.swf
Param quality: high
Param bgcolor: #000000
Param play: true
Param loop: true
Param wmode: window
Param scale: showall
Param menu: true
Param devicefont: false
Param allowScriptAccess: always
Param SCALE: default
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined
Attribute 6: undefined

# Page Info
Page URL: https://sexgamescc.com/ebb0a538ff098bb37dcb82d09f52c93f-slave-lords-of-the-galaxy-1-0-1
SWF URL: https://v8p5i7f9.ssl.hwcdn.net/games/swf/a/1/4/a147d61b8fb6986859d85dff2c9b458c/a147d61b8fb6986859d85dff2c9b458c.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 Edg/112.0.1722.32
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-06-17
Channel: nightly
Built: 2021-06-17T00:11:56.220Z
Commit: 622f35eb713c224a980ab67eb251a4b6880e1834

**Comment by kjarosh** [comment]
Should be fixed as of the newest version
