### ISSUE TITLE
Error on https://blog.gskinner.com//assets/spectrum_blaze/

### ISSUE THREAD

**Issue by Andrewknackstedt** [ruffle-rs/ruffle#10899]
# Error Info
Error name: Error
Error message: panicked at 'No uniform for push constant', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.16.0/src/gles/command.rs:725:17
Error stack:
```
Error: panicked at 'No uniform for push constant', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.16.0/src/gles/command.rs:725:17
    at imports.wbg.__wbg_new_15d3966e9981a196 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:2258:21)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hd28f65a61f685e47 (wasm://wasm/02b74ace:wasm-function[8390]:0x81042c)
    at std::panicking::rust_panic_with_hook::h7f7102b82d51338f (wasm://wasm/02b74ace:wasm-function[5498]:0x732337)
    at core::panicking::panic_fmt::he4489d678d6570d5 (wasm://wasm/02b74ace:wasm-function[8245]:0x80acaa)
    at wgpu_hal::gles::command::<impl wgpu_hal::CommandEncoder<wgpu_hal::gles::Api> for wgpu_hal::gles::CommandEncoder>::set_push_constants::h5b2ba164d09bf61d (wasm://wasm/02b74ace:wasm-function[3346]:0x63f0de)
    at <T as wgpu::context::DynContext>::command_encoder_end_render_pass::h187969ed2c67add7 (wasm://wasm/02b74ace:wasm-function[7810]:0x7f670a)
    at <wgpu::RenderPass as core::ops::drop::Drop>::drop::hcea9842e61dbecf8 (wasm://wasm/02b74ace:wasm-function[6614]:0x78c225)
    at <ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::apply_filter::h71f0c67924a1f0fc (wasm://wasm/02b74ace:wasm-function[1306]:0x3e33df)
    at ruffle_core::avm2::globals::flash::display::bitmap_data::apply_filter::h0add2026ab4f888a (wasm://wasm/02b74ace:wasm-function[1136]:0x393034)
    at ruffle_core::avm2::function::Executable::exec::hb5981ebd76854dce (wasm://wasm/02b74ace:wasm-function[781]:0x2ac725)
```
AVM2 stack:
```
    at flash.display::BitmapData/flash::display::BitmapData::applyFilter()
    at BlazeLogo/tick()
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://blog.gskinner.com//assets/spectrum_blaze/
SWF URL: https://blog.gskinner.com//assets/spectrum_blaze/blazeLogo.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-05-01
Channel: nightly
Built: 2023-05-01T00:19:34.037Z
Commit: ee7403952afe1436d84f94bcbdd0d23209cb7d39
Is extension: true

# Metadata
width: 600
height: 600
frameRate: 30
numFrames: 1
swfVersion: 9
backgroundColor: #050505
isActionScript3: true
uncompressedLength: 4587

**Comment by n0samu** [comment]
Should be fixed by #11753 and #11750
