### ISSUE TITLE
Error on https://rawcdn.githack.com/lioxryt/lioxryt-assets/a4041fc9b45936f148d3d7134977d5df4329e237/flash/index.html

### ISSUE THREAD

**Issue by UMADBRO233** [ruffle-rs/ruffle#10904]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/bitmap/bitmap_data.rs:602:51
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/bitmap/bitmap_data.rs:602:51
    at O.n.wbg.__wbg_new_15d3966e9981a196 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.312167b7d45670ed237b.js:1:48745)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hd28f65a61f685e47 (wasm://wasm/02b74ace:wasm-function[8390]:0x81042c)
    at std::panicking::rust_panic_with_hook::h7f7102b82d51338f (wasm://wasm/02b74ace:wasm-function[5498]:0x732337)
    at core::panicking::panic_fmt::he4489d678d6570d5 (wasm://wasm/02b74ace:wasm-function[8245]:0x80acaa)
    at core::panicking::panic::hea78c4e8b318407d (wasm://wasm/02b74ace:wasm-function[7551]:0x7d095e)
    at ruffle_core::bitmap::bitmap_data::BitmapData::update_dirty_texture::h69e242bde85db84e (wasm://wasm/02b74ace:wasm-function[1279]:0x3d523d)
    at <ruffle_core::library::MovieLibrarySource as ruffle_render::bitmap::BitmapSource>::bitmap_handle::h218cbf3363c21bf3 (wasm://wasm/02b74ace:wasm-function[3247]:0x61c312)
    at <ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::register_shape::haa5f47cd0e691a1c (wasm://wasm/02b74ace:wasm-function[1120]:0x3868d1)
    at ruffle_core::display_object::movie_clip::MovieClipData::define_shape::h127073ca34759630 (wasm://wasm/02b74ace:wasm-function[3609]:0x66ba07)
    at ruffle_core::display_object::movie_clip::MovieClip::preload::h30e5eba151b7c315 (wasm://wasm/02b74ace:wasm-function[621]:0x1dece0)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://rawcdn.githack.com/lioxryt/lioxryt-assets/a4041fc9b45936f148d3d7134977d5df4329e237/flash/index.html?swf=pottyracers3.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 Edg/112.0.1722.58
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-05-01
Channel: nightly
Built: 2023-05-01T00:19:34.037Z
Commit: ee7403952afe1436d84f94bcbdd0d23209cb7d39
Is extension: false

# Metadata
width: 730
height: 500
frameRate: 30
numFrames: 11
swfVersion: 9
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 13223643

**Comment by Lord-McSweeney** [comment]
Fixed by #10908.
