### ISSUE TITLE
Error on https://game36911.konggames.com/games/Megadev/time4cat/frame/8aad93cd-f776-40b0-abef-ba86ae178ef7/

### ISSUE THREAD

**Issue by orion140** [ruffle-rs/ruffle#10954]
# Error Info
Error name: Error
Error message: panicked at 'index out of bounds: the len is 4800 but the index is 4800', core/src/bitmap/bitmap_data.rs:604:9
Error stack:
```
Error: panicked at 'index out of bounds: the len is 4800 but the index is 4800', core/src/bitmap/bitmap_data.rs:604:9
    at O.n.wbg.__wbg_new_15d3966e9981a196 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.7d3ff466cfbd971981de.js:1:48914)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hd28f65a61f685e47 (wasm://wasm/02b8133e:wasm-function[8418]:0x811c6f)
    at std::panicking::rust_panic_with_hook::h7f7102b82d51338f (wasm://wasm/02b8133e:wasm-function[5512]:0x733897)
    at core::panicking::panic_fmt::he4489d678d6570d5 (wasm://wasm/02b8133e:wasm-function[8271]:0x80c4b5)
    at core::panicking::panic_bounds_check::h1213b10c1e002d73 (wasm://wasm/02b8133e:wasm-function[6633]:0x78d676)
    at ruffle_core::bitmap::operations::copy_on_cpu::ha57d1f647286244e (wasm://wasm/02b8133e:wasm-function[779]:0x2aafb6)
    at ruffle_core::bitmap::operations::draw::hba4e79233cd20803 (wasm://wasm/02b8133e:wasm-function[800]:0x2c4c08)
    at ruffle_core::avm2::globals::flash::display::bitmap_data::draw::hae63a30bb1476f73 (wasm://wasm/02b8133e:wasm-function[807]:0x2cb7ac)
    at ruffle_core::avm2::function::Executable::exec::hb5981ebd76854dce (wasm://wasm/02b8133e:wasm-function[780]:0x2ab7ae)
    at ruffle_core::avm2::object::TObject::call_property::hbef9b7a23152cbbb (wasm://wasm/02b8133e:wasm-function[1116]:0x386444)
```
AVM2 stack:
```
    at flash.display::BitmapData/flash::display::BitmapData::draw()
    at Time4Cat/_tf71()
    at Time4Cat/_xe194()
    at Time4Cat/draw()
    at Time4Cat/update()
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://game36911.konggames.com/games/Megadev/time4cat/frame/8aad93cd-f776-40b0-abef-ba86ae178ef7/?kongregate_host=www.kongregate.com
SWF URL: https://game36911.konggames.com/gamez/0003/6911/live/Time4Cat.swf?kongregate_game_version=1234311281

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-05-05
Channel: nightly
Built: 2023-05-05T00:22:42.542Z
Commit: 58d786b8694d46fd12a10418604968d067ac7684
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 31
numFrames: 2
swfVersion: 9
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 2509508

**Comment by Lord-McSweeney** [comment]
https://github.com/ruffle-rs/ruffle/blob/8377fe023310b6d130f97a4a21cd8d9bb4bf50ad/core/src/bitmap/bitmap_data.rs#L604
