### ISSUE TITLE
Error on https://www.gameflare.com/embed/sequester/

### ISSUE THREAD

**Issue by NullPainter2** [ruffle-rs/ruffle#10965]
# Error Info
Error name: Error
Error message: panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`: cannot recursively acquire mutex', /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys/wasm/../unsupported/locks/mutex.rs:20:9
Error stack:
```
Error: panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`: cannot recursively acquire mutex', /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys/wasm/../unsupported/locks/mutex.rs:20:9
    at O.n.wbg.__wbg_new_15d3966e9981a196 (https://www.gameflare.com/emulators/ruffle/core.ruffle.312167b7d45670ed237b.js:1:48745)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hd28f65a61f685e47 (wasm://wasm/02b74ace:wasm-function[8390]:0x81042c)
    at std::panicking::rust_panic_with_hook::h7f7102b82d51338f (wasm://wasm/02b74ace:wasm-function[5498]:0x732337)
    at core::panicking::panic_fmt::he4489d678d6570d5 (wasm://wasm/02b74ace:wasm-function[8245]:0x80acd8)
    at core::panicking::assert_failed_inner::h2c9bd6d3ed542c7e (wasm://wasm/02b74ace:wasm-function[3432]:0x64bbd9)
    at core::panicking::assert_failed::hced4fa3f6a53cbc0 (wasm://wasm/02b74ace:wasm-function[7397]:0x7cb889)
    at ruffle_core::loader::Loader::load_url_loader::{{closure}}::hf3a12b822f9ef39d (wasm://wasm/02b74ace:wasm-function[1855]:0x4a90cc)
    at <ruffle_web::navigator::WebNavigatorBackend as ruffle_core::backend::navigator::NavigatorBackend>::spawn_future::{{closure}}::h87d7dba1a5187b6c (wasm://wasm/02b74ace:wasm-function[1002]:0x34c79b)
    at wasm_bindgen_futures::queue::Queue::new::{{closure}}::haff0004aace70f2e (wasm://wasm/02b74ace:wasm-function[3509]:0x659f47)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::ha0d971e5acc26876 (wasm://wasm/02b74ace:wasm-function[9015]:0x828372)
```
AVM2 stack:
```
    at flash.display::BitmapData/flash::display::BitmapData::draw()
    at main/createSpriteSheet()
    at main/createAllSpriteSheets()
    at main()
    at THECUBE3_fla::MainTimeline/frame6()
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.gameflare.com/embed/sequester/
SWF URL: https://data.gameflare.com/games/2712/JAema3kuHUC5eD.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-05-02
Channel: nightly
Built: 2023-05-02T00:22:53.750Z
Commit: e1d47e3527335db2ee8198be1ce60f6c69dbbbeb
Is extension: false

# Metadata
width: 560
height: 560
frameRate: 25
numFrames: 26
swfVersion: 13
backgroundColor: #0033CC
isActionScript3: true
uncompressedLength: 11280352

**Comment by Lord-McSweeney** [comment]
Hi, can you explain what you were doing that led to this error?

**Comment by NullPainter2** [comment]
I don't know what I did back then.

But now I tried it again -> I opened that page -> closed ad -> it crashed in Chrome. It crashed only first time - subsequent reloads were fine. Removing cookies did not help. Also no crash in Firefox.

It crashed with this message on first load:
```
# Error Info
Error name: Error
Error message: Failed to fetch: https://data.gameflare.com/games/2712/JAema3kuHUC5eD.swf
Error stack:
```
Error: Failed to fetch: https://data.gameflare.com/games/2712/JAema3kuHUC5eD.swf
    at Le.displayRootMovieDownloadFailedMessage (https://www.gameflare.com/emulators/ruffle/ruffle.js?release=2023-06-16:1:330025)
    at U.n.wbg.__wbg_displayRootMovieDownloadFailedMessage_ed4ad3ae9522c8a3 (https://www.gameflare.com/emulators/ruffle/core.ruffle.cf9a18439af3234f2c03.js:1:6993)
    at <ruffle_web::ui::WebUiBackend as ruffle_core::backend::ui::UiBackend>::display_root_movie_download_failed_message::h92773e89a680a05b (wasm://wasm/02c61e22:wasm-function[10479]:0x8786a7)
    at ruffle_core::loader::Loader::root_movie_loader::{{closure}}::hc812c8eb1b090f1c (wasm://wasm/02c61e22:wasm-function[849]:0x2e6f47)
    at <ruffle_web::navigator::WebNavigatorBackend as ruffle_core::backend::navigator::NavigatorBackend>::spawn_future::{{closure}}::h80597e70c79ace5f (wasm://wasm/02c61e22:wasm-function[1021]:0x35bdf2)
    at wasm_bindgen_futures::queue::Queue::new::{{closure}}::ha37f2732e67f2e3a (wasm://wasm/02c61e22:wasm-function[3691]:0x697a37)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h735d2626f98e113e (wasm://wasm/02c61e22:wasm-function[9306]:0x855378)
    at closure5401 externref shim (wasm://wasm/02c61e22:wasm-function[9608]:0x85a3c9)
    at D (https://www.gameflare.com/emulators/ruffle/core.ruffle.cf9a18439af3234f2c03.js:1:2866)
    at f (https://www.gameflare.com/emulators/ruffle/core.ruffle.cf9a18439af3234f2c03.js:1:2511)
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (AMD, AMD Radeon RX 6600 Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://www.gameflare.com/embed/sequester/
SWF URL: https://data.gameflare.com/games/2712/JAema3kuHUC5eD.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-06-16
Channel: nightly
Built: 2023-06-16T00:20:31.625Z
Commit: 69fce3f7f86d8c661a80c19873711956bcc7fbbc
Is extension: false

# Metadata
```
