### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by Winternoble** [ruffle-rs/ruffle#11017]
# Error Info
Error name: Error
Error message: panicked at 'index out of bounds: the len is 39032 but the index is 39032', core/src/bitmap/bitmap_data.rs:604:9
Error stack:
```
Error: panicked at 'index out of bounds: the len is 39032 but the index is 39032', core/src/bitmap/bitmap_data.rs:604:9
    at O.n.wbg.__wbg_new_15d3966e9981a196 (https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.5aaa2c772ada72a64348.js:1:49872)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::haa731965db7740b6 (wasm://wasm/02c352a6:wasm-function[8575]:0x832305)
    at std::panicking::rust_panic_with_hook::h7f7102b82d51338f (wasm://wasm/02c352a6:wasm-function[5601]:0x75639f)
    at core::panicking::panic_fmt::he4489d678d6570d5 (wasm://wasm/02c352a6:wasm-function[8424]:0x82ca69)
    at core::panicking::panic_bounds_check::h1213b10c1e002d73 (wasm://wasm/02c352a6:wasm-function[6725]:0x7ab6b4)
    at ruffle_core::bitmap::operations::copy_on_cpu::h77f382aa99fa6357 (wasm://wasm/02c352a6:wasm-function[791]:0x2ae489)
    at ruffle_core::bitmap::operations::copy_pixels::h1b4d32ad17038d9a (wasm://wasm/02c352a6:wasm-function[4299]:0x6e6c08)
    at ruffle_core::avm2::globals::flash::display::bitmap_data::copy_pixels::hd0c99dec715eed5f (wasm://wasm/02c352a6:wasm-function[725]:0x273f95)
    at ruffle_core::avm2::function::Executable::exec::h13c3bc91d186b7aa (wasm://wasm/02c352a6:wasm-function[794]:0x2b0164)
    at ruffle_core::avm2::object::TObject::call_property::hf0564dd227fd8e78 (wasm://wasm/02c352a6:wasm-function[1121]:0x38a2bd)
```
AVM2 stack:
```
    at flash.display::BitmapData/flash::display::BitmapData::copyPixels()
    at Game/drawGame()
    at Game/loop()
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.67&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1683807984%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F653000%2F653016_dontescape2.swf%3F1551187751%22%2C%22vars%22%3A%7B%22ngio_session_id%22%3A%2236983243.0e190408a8d546ed470534f010524f41a506b9d8588363%22%2C%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%22645d8cfd7e3fb%22%2C%22NewgroundsAPI_SessionID%22%3A%225Q8LIdpvONtUKyZNKGNj02706810fdff30f0d0f0a08d71416a958f7e4198WbZE%22%2C%22NewgroundsAPI_UserName%22%3A%22AnthonyLohnes%22%2C%22NewgroundsAPI_UserID%22%3A5751498%2C%22ng_username%22%3A%22AnthonyLohnes%22%7D%2C%22width%22%3A720%2C%22height%22%3A540%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F653000%2Fflash_653016_card.png%3Ff1661226942%22%2C%22warnOnUnsupportedContent%22%3Afalse%7D
SWF URL: https://uploads.ungrounded.net/653000/653016_dontescape2.swf?1551187751

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 Edg/112.0.1722.32
Platform: Win32
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-05-11
Channel: nightly
Built: 2023-05-11T00:25:16.774Z
Commit: e488cc9f7a56b809de527c4bb4d0034cfa23cae4
Is extension: false

# Metadata
width: 720
height: 540
frameRate: 30
numFrames: 2
swfVersion: 22
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 11153224

**Comment by iwannabethedev** [comment]
I have tried running the .swf file in https://github.com/ruffle-rs/ruffle/issues/11017 , but when I click the button to "Play" while running a local desktop build of Ruffle, I only get re-directed to newgrounds.com. However, this very much looks like a bug that will be fixed by #10955 , and I hope to get that PR merged as soon as possible.
