### ISSUE TITLE
Error on Starmageddon

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#11019]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm2/globals/flash/geom/transform.rs:22:10
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm2/globals/flash/geom/transform.rs:22:10
    at O.n.wbg.__wbg_new_15d3966e9981a196 (https://www.spiele-umsonst.de/ruffle/core.ruffle.1f63c5b1396ac9e10d6d.js:1:49872)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::haa731965db7740b6 (wasm://wasm/02c2d3da:wasm-function[8572]:0x830b2a)
    at std::panicking::rust_panic_with_hook::h7f7102b82d51338f (wasm://wasm/02c2d3da:wasm-function[5598]:0x754c53)
    at core::panicking::panic_fmt::he4489d678d6570d5 (wasm://wasm/02c2d3da:wasm-function[8421]:0x82b260)
    at core::panicking::panic::hea78c4e8b318407d (wasm://wasm/02c2d3da:wasm-function[7699]:0x7ef168)
    at ruffle_core::avm2::globals::flash::geom::transform::get_display_object::h8d72e8ea7b41c4c5 (wasm://wasm/02c2d3da:wasm-function[3724]:0x696ecc)
    at ruffle_core::avm2::globals::flash::geom::transform::get_color_transform::h8153a03323b40847 (wasm://wasm/02c2d3da:wasm-function[2891]:0x5e7083)
    at ruffle_core::avm2::function::Executable::exec::h13c3bc91d186b7aa (wasm://wasm/02c2d3da:wasm-function[793]:0x2af197)
    at ruffle_core::avm2::object::TObject::call_method::h51daaeed0dd62767 (wasm://wasm/02c2d3da:wasm-function[1969]:0x4d9b4c)
    at ruffle_core::avm2::object::TObject::get_property::h54421ff0e45e0d2b (wasm://wasm/02c2d3da:wasm-function[1401]:0x413bfd)
```
AVM2 stack:
```
    at flash.geom::Transform/flash::geom::Transform::colorTransform()
    at info::Alerter()
    at Game()
    at gash.prep::PrepCreateAppPhases/performStep()
    at gash.prep::PrepAbstract/perform()
    at gash.prep::Preper/step()
    at gash.prep::Preper/prepare()
    at Application/prep()
    at App/boot()
    at Doc/loaded()
    at gash.preloader::Preloader/deactivate()
    at gash.preloader::MochiPreloader/preloaderFinished()
    at MethodInfo-482()
```

# Player Info
Allows script access: false

# Page Info
SWF URL: https://www.spiele-umsonst.de/azad/downloads/flashgames/starmageddon.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-05-09
Channel: nightly
Built: 2023-05-09T00:25:26.314Z
Commit: 72769eeefa66b617d3d7f710a76f4ea78ec16104
Is extension: false

# Metadata
width: 500
height: 600
frameRate: 30
numFrames: 2
swfVersion: 10
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 5896550

**Comment by kjarosh** [comment]
The code related to the panic changed a lot, the game works pretty well
