### ISSUE TITLE
Overflow or something

### ISSUE THREAD

**Issue by AnnoyingPotatos** [ruffle-rs/ruffle#11129]
### Describe the bug

# Error Info
Error name: Error
Error message: panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:525:5
Error stack:
```
Error: panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:525:5
    at W.n.wbg.__wbg_new_87297f22973157c8 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.1d8b9613154ab995c7b5.js:1:50371)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h9058a63962169328 (wasm://wasm/02c3171e:wasm-function[8575]:0x830974)
    at std::panicking::rust_panic_with_hook::h7f7102b82d51338f (wasm://wasm/02c3171e:wasm-function[5600]:0x7548a5)
    at core::panicking::panic_fmt::he4489d678d6570d5 (wasm://wasm/02c3171e:wasm-function[8426]:0x82bce0)
    at alloc::raw_vec::capacity_overflow::h743526e95bf6b28b (wasm://wasm/02c3171e:wasm-function[8193]:0x825bd1)
    at swf::read::decompress_swf::hfa8b7dc54d30bac9 (wasm://wasm/02c3171e:wasm-function[683]:0x23a406)
    at ruffle_core::loader::Loader::root_movie_loader::{{closure}}::ha877e548f98f5e97 (wasm://wasm/02c3171e:wasm-function[823]:0x2d1c6d)
    at <ruffle_web::navigator::WebNavigatorBackend as ruffle_core::backend::navigator::NavigatorBackend>::spawn_future::{{closure}}::h84b0d8a8e0f6eebc (wasm://wasm/02c3171e:wasm-function[1023]:0x355ca8)
    at wasm_bindgen_futures::queue::Queue::new::{{closure}}::h006015b89e4aca53 (wasm://wasm/02c3171e:wasm-function[3559]:0x67b219)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::ha6be78b82c5fe0fa (wasm://wasm/02c3171e:wasm-function[9207]:0x849ec7)
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "Mesa DRI Intel(R) UHD Graphics 600 (GLK 2)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | TEXTURE_COMPRESSION_ASTC_HDR | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 700, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://11c71043-b955-411e-9487-8b3f13a8eea7.filesusr.com/html/ceae95_1ea82e4cb60f52363d98b993c4aea460.html
SWF URL: https://static.wixstatic.com/media/ceae95_4951db2f10204944ab76e5e3739d2a8b.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-05-19
Channel: nightly
Built: 2023-05-19T00:19:09.231Z
Commit: 5c68bceb7b48651236efc8c5dae598038cace737
Is extension: false

# Metadata

### Expected behavior

To run it.

### Affected platform

Self-hosted version

### Operating system

ChromeOS

### Browser

Chromium

**Comment by Lord-McSweeney** [comment]
I believe this is due to the server scattering a number of `EF BF BD` bytes (the UTF-8 replacement character)- the SWF is corrupted.

**Comment by n0samu** [comment]
It looks like the file was somehow uploaded in text mode instead of binary mode, or something along those lines

**Comment by Lord-McSweeney** [comment]
Thanks to #23962, this should now bring up a proper "invalid SWF" screen.
