### ISSUE TITLE
Error on https://www.crazymonkeygames.com/Boxhead-the-Nightmare.html

### ISSUE THREAD

**Issue by benjathje** [ruffle-rs/ruffle#11181]
# Error Info
Error name: Error
Error message: panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:525:5
Error stack:
```
Error: panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:525:5
    at W.n.wbg.__wbg_new_87297f22973157c8 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.5414b0614180f4f61fb1.js:1:50966)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hee170dc26e4169dd (wasm://wasm/02c1df5a:wasm-function[8612]:0x82a42c)
    at std::panicking::rust_panic_with_hook::h7f7102b82d51338f (wasm://wasm/02c1df5a:wasm-function[5567]:0x74b6b6)
    at core::panicking::panic_fmt::he4489d678d6570d5 (wasm://wasm/02c1df5a:wasm-function[8461]:0x825799)
    at alloc::raw_vec::capacity_overflow::h743526e95bf6b28b (wasm://wasm/02c1df5a:wasm-function[8228]:0x81f64d)
    at alloc::raw_vec::RawVec<T,A>::reserve::do_reserve_and_handle::h4a88660e747c3079 (wasm://wasm/02c1df5a:wasm-function[5218]:0x732b2e)
    at <ruffle_core::avm2::object::array_object::ArrayObject as ruffle_core::avm2::object::TObject>::set_property_local::he9db43d487a55d10 (wasm://wasm/02c1df5a:wasm-function[2335]:0x54aa31)
    at ruffle_core::avm2::object::TObject::set_property::hb996e809938cbc5f (wasm://wasm/02c1df5a:wasm-function[2210]:0x52bd8b)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::set_property::hc9a31028b2ff5000 (wasm://wasm/02c1df5a:wasm-function[1835]:0x4affcd)
    at ruffle_core::avm2::activation::Activation::run_actions::h8d795f90d570dca1 (wasm://wasm/02c1df5a:wasm-function[510]:0x3c0ee)
```
AVM2 stack:
```
    at frontend.data::DataConnector/storeData()
    at frontend.data::FData$/firstTimeUnlocks()
    at frontend.data::FData/e_USER_DATA_LOADED()
    at flash.events::EventDispatcher/flash::events::EventDispatcher::dispatchEvent()
    at frontend.data::DataConnector/loadData()
    at frontend.data::DataConnector/getUserData()
    at frontend.data::FData/e_FILE_COMPLETE()
    at flash.events::EventDispatcher/flash::events::EventDispatcher::dispatchEvent()
    at frontend.data::FMedia/e_SWF_LOADED()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Google, Vulkan 1.3.0 (SwiftShader Device (Subzero) (0x0000C0DE)), SwiftShader driver)"
Adapter Device Type: Cpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | TEXTURE_COMPRESSION_ASTC_HDR | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 8192, max_texture_dimension_2d: 8192, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://www.crazymonkeygames.com/Boxhead-the-Nightmare.html
SWF URL: https://www.crazymonkeygames.com/swf-nr2kjn-jekb/secure_bxhnm.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-05-22
Channel: nightly
Built: 2023-05-22T00:19:58.859Z
Commit: 6ac4e5256da25d462f88bd85b23d6619ff70b2f0
Is extension: false

# Metadata
width: 760
height: 576
frameRate: 60
numFrames: 3
swfVersion: 10
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 5592133

**Comment by n0samu** [comment]
Looks like Ruffle is running out of memory, so there's something we're doing very inefficiently

**Comment by Lord-McSweeney** [comment]
Possibly related to https://github.com/ruffle-rs/ruffle/issues/10022 ?

**Comment by benjathje** [comment]
And I was on 32 gigs of ram

**Comment by Lord-McSweeney** [comment]
RAM doesn't matter- IIRC WebAssembly is limited to accessing 4 GB of memory.

**Comment by iwannabethedev** [comment]
I imagine that it should be fairly straight-forward to write tests for this, if the issue is something like `var array = new Array(); array[veryLargeNumber] = "test";`.

**Comment by iwannabethedev** [comment]
This program:

```ActionScript
﻿package {
	import flash.net.SharedObject;
	import flash.display.Sprite;
	public class test extends Sprite {
	}	
}

var array: Array = new Array();

array[5501159448] = "test";

trace("array[5501159448]: " + array[5501159448]);
```

, when compiled with `mxmlc` and run with Flash Player, gives:

```
array[5501159448]: test
```

, and when run with Ruffle, crashes.

**Comment by iwannabethedev** [comment]
I think I figured it out.

Running in Flash Player:

```ActionScript
﻿﻿package {
	import flash.net.SharedObject;
	import flash.display.Sprite;
	public class test extends Sprite {
	}	
}

trace("***************************************************************************************************");
trace("***********************   THIS PROGRAM WILL TAKE A FEW SECONDS TO FINISH.   ***********************");
trace("***************************************************************************************************");

var array: Array = new Array();

var large: Number = uint.MAX_VALUE + 100000;

trace("uint.MAX_VALUE: " + uint.MAX_VALUE);
trace("large: " + "uint.MAX_VALUE + 100000 = " + large);
trace("large - uint.MAX_VALUE: " + (large - uint.MAX_VALUE));

array[large] = "test";
trace("array[" + large + "]: " + array[large]);
trace("array.length(): " + array.length);

array[4] = "other test";
trace("array[4]: " + array[4]);
trace("array.length(): " + array.length);

array = new Array();
trace("New array.");

var i: Number;

var attemptCount: int = 0;

for (i = large; i > 0; i -= 1) {
    attemptCount += 1;
    array[i] = "test";
    if (array.length != 0) {
        trace("First index at which 'array.length' was non-zero: " + i + ", length is: " + array.length + ", attemptCount: " + attemptCount);
        break;
    }

    // Content check.
    if (array[i] != "test") {
        trace("Content was not stored, for index: " + i);
        break;
    }
    delete array[i];
}
```

gives this output (after a few seconds):

```
***************************************************************************************************
***********************   THIS PROGRAM WILL TAKE A FEW SECONDS TO FINISH.   ***********************
***************************************************************************************************
uint.MAX_VALUE: 4294967295
large: uint.MAX_VALUE + 100000 = 4295067295
large - uint.MAX_VALUE: 100000
array[4295067295]: test
array.length(): 0
array[4]: other test
array.length(): 5
New array.
First index at which 'array.length' was non-zero: 4294967294, length is: 4294967295, attemptCount: 100002
```

My guess is that any index that is outside the range of `[uint.MIN_VALUE..uint.MAX_VALUE[` will not modify the `length`, and the index and value will not be stored as an array index and element, but some other way (possibly just as an `Object` property, since `Array`s can also have property names for its properties that are not numbers - like, `var arr = new Array(); arr.strangePropertyNameForAnArray = "test";` is valid code and will store the value `"test"` for the property name `"strangePropertyNameForAnArray"`).

**Comment by n0samu** [comment]
The error now is:
`ERROR run_frame:run_all_phases_avm2: ruffle_core::avm2::events: Error dispatching event EventObject(EventObject { type: "USER_DATA_LOADED", class: flash.events::Event, ptr: 0x25c4a3c9bd0 }) to handler FunctionObject(FunctionObject { ptr: 0x25c4dff4df0 }) : RustError("Ruffle does not support sparse arrays yet.")`

**Comment by jarca0123** [comment]
If my sparse array implementation is correct, then there are two errors, one after getting to the title screen:
```
Error dispatching event EventObject(EventObject { type: "addedToStage", class: flash.events::Event, ptr: 0x5d97c6d65600 }) to handler FunctionObject(FunctionObject { ptr: 0x5d97c6c59d40, name: Ok("frontend.display::FClickArea/initialize()") }) : TypeError: Error #1009: Cannot access a property or method of a null object reference. (accessing field: addEventListener)
        at frontend.display::FClickArea/initializeMouseEvents()
        at frontend.display::FClickArea/initialize()
        at flash.display::DisplayObject/flash.display::DisplayObject()
        at flash.display::InteractiveObject/flash.display::InteractiveObject()
        at flash.display::DisplayObjectContainer/flash.display::DisplayObjectContainer()
        at flash.display::Sprite()
        at frontend.display::FDisplayObject()
        at frontend.display::FScreen()
        at frontend.screen.title::FScreenTitle()
        at frontend.screen.cmg::FScreenCMG/e_ENTER_FRAME()
```
        
and one when loading the game, which it never loads: 
```
Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x5d97cb5603a0 }) to handler FunctionObject(FunctionObject { ptr: 0x5d97c2788a80, name: Ok("frontend::FMain/process()") }) : TypeError: Error #1009: Cannot access a property or method of a null object reference.
        at bxhnm.world::GWorld/process()
        at Game/process()
        at frontend.screen.game::FScreenGame/state_active()
        at frontend.utils::State/process()
        at frontend.display::FScreen/process()
        at frontend.display::FScreenContainer/process()
        at frontend::FMain/process()
 ```

**Comment by SuchAFuriousDeath** [comment]
I looked into this, seems like an issue with amf serialization
