### ISSUE TITLE
DDtank Marksman 7road

### ISSUE THREAD

**Issue by zijad3002** [ruffle-rs/ruffle#11224]
### Describe what you were doing
https://ddtank.wan.com/

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) HD Graphics 4000 Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/player.html?url=https%3A%2F%2Fres57-land-ddt.7road.net%2Fflash%2FLoading.swf%3Fuser%3D130939%26key%3D%257BC4B11CA3-A3A1-4ECB-48DA-E5D53E4FDBAE%257D%26isGuest%3DFalse%26ua%3D%26fbapp%3Dfalse%26uag%3D0%26source%3D%26v%3D10950%26rand%3D638206837620686811%26config%3Dhttps%253A%252F%252Fs57-land-ddt.7road.net%252Fconfig.xml%26site%3D%26sitename%3D%26rid%3D%26enterCode%3D%26sex%3D
SWF URL: https://res57-land-ddt.7road.net/flash/Loading.swf?user=130939&key=%7BC4B11CA3-A3A1-4ECB-48DA-E5D53E4FDBAE%7D&isGuest=False&ua=&fbapp=false&uag=0&source=&v=10950&rand=638206837620686811&config=https%3A%2F%2Fs57-land-ddt.7road.net%2Fconfig.xml&site=&sitename=&rid=&enterCode=&sex=

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-05-26
Channel: nightly
Built: 2023-05-26T00:23:58.942Z
Commit: 6d76e9669c54f7712ba4273d15e90f5683160955
Is extension: true

# Metadata
width: 1000
height: 600
frameRate: 25
numFrames: 1
swfVersion: 28
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 370080

### What does the crash message say?

ntent.js:184 Unable to check top-level optout: Blocked a frame with origin "https://s57-land-ddt.7road.net" from accessing a cross-origin frame.
checkPageOptout @ content.js:184
isSafeFlash.js:71 Uncaught SyntaxError: missing ) after argument list
Default.aspx?user=130939&key={C4B11CA3-A3A1-4ECB-48DA-E5D53E4FDBAE}:23 Uncaught DOMException: Failed to set the 'domain' property on 'Document': 'ddtank.us' is not a suffix of '7road.net'.
    at https://s57-land-ddt.7road.net/Default.aspx?user=130939&key={C4B11CA3-A3A1-4ECB-48DA-E5D53E4FDBAE}:23:17
prototype.js:3964 Uncaught TypeError: element.dispatchEvent is not a function
    at fire (prototype.js:3964:17)
    at HTMLDocument._methodized [as fire] (prototype.js:238:23)
    at fireContentLoadedEvent (prototype.js:3998:14)
    at wrapper (prototype.js:3869:15)
ruffle.js?id=9968856959:3599 New Ruffle instance created (WebAssembly extensions: ON | Used renderer: wgpu-webgl)
ruffle.js?id=9968856959:3751 Loading SWF file https://res57-land-ddt.7road.net/flash/Loading.swf?user=130939&key=%7bC4B11CA3-A3A1-4ECB-48DA-E5D53E4FDBAE%7d&isGuest=False&ua=&fbapp=false&uag=0&source=&v=10950&rand=638206837620686811&config=https://s57-land-ddt.7road.net/config.xml
s57-land-ddt.7road.net/CrossDomain.ashx?url=http://quest57-land-ddt.7road.net/UpdateVersion.ashx?Version=32.0.0.0:1     Failed to load resource: the server responded with a status of 404 (Not Found)
s57-land-ddt.7road.net/CrossDomain.ashx?url=http://quest57-land-ddt.7road.net/UpdateVersion.ashx?Version=32.0.0.0:1     Failed to load resource: the server responded with a status of 404 (Not Found)
Default.aspx:1 Access to fetch at 'https://res57-land-ddt.7road.net/flash/Loading.swf?user=130939&key=%7bC4B11CA3-A3A1-4ECB-48DA-E5D53E4FDBAE%7d&isGuest=False&ua=&fbapp=false&uag=0&source=&v=10950&rand=638206837620686811&config=https://s57-land-ddt.7road.net/config.xml' from origin 'https://s57-land-ddt.7road.net' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
res57-land-ddt.7road.net/flash/Loading.swf?user=130939&key=%7bC4B11CA3-A3A1-4ECB-48DA-E5D53E4FDBAE%7d&isGuest=False&ua=&fbapp=false&uag=0&source=&v=10950&rand=638206837620686811&config=https://s57-land-ddt.7road.net/config.xml:1     Failed to load resource: net::ERR_FAILED
339.js:802 ERROR web/src/navigator.rs:260 Asynchronous error occurred: Could not fetch: Got JS error
DevTools failed to load source map: Could not load content for https://static-bm.wan.com/static/7/sq/style/js/jquery.min.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

### Ruffle Version

0.1.0 nightly 2023-05-26

### Affected platform

Browser's extension

### Operating system

windows 11 revops

### Additional information

the loading screen and clicking on attack the pirates is working ,but after that crashes on brave

**Comment by n0samu** [comment]
That looks like a CORS error, which Ruffle can't do anything about unfortunately

**Comment by danielhjacobs** [comment]
The extension player page is not subject to CORS and so this should be fixed now.
