### ISSUE TITLE
Error on https://games.crazygames.com/en_US/minecraft-tower-defense/index.html

### ISSUE THREAD

**Issue by AdrianVicent** [ruffle-rs/ruffle#11232]
# Error Info
Error name: Error
Error message: panicked at 'index out of bounds: the len is 0 but the index is 0', core/src/backend/audio/decoders/mp3.rs:137:26
Error stack:
```
Error: panicked at 'index out of bounds: the len is 0 but the index is 0', core/src/backend/audio/decoders/mp3.rs:137:26
    at O.n.wbg.__wbg_new_15d3966e9981a196 (https://files.crazygames.com/gameframe/ruffle/2023-05-09/core.ruffle.1f63c5b1396ac9e10d6d.js:1:49872)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::haa731965db7740b6 (wasm://wasm/02c2d3da:wasm-function[8572]:0x830b2a)
    at std::panicking::rust_panic_with_hook::h7f7102b82d51338f (wasm://wasm/02c2d3da:wasm-function[5598]:0x754c53)
    at core::panicking::panic_fmt::he4489d678d6570d5 (wasm://wasm/02c2d3da:wasm-function[8421]:0x82b28e)
    at core::panicking::panic_bounds_check::h1213b10c1e002d73 (wasm://wasm/02c2d3da:wasm-function[6721]:0x7a9e91)
    at <ruffle_core::backend::audio::decoders::mp3::Mp3Decoder as ruffle_core::backend::audio::decoders::SeekableDecoder>::seek_to_sample_frame::hbbd3d1cbbcab5cd6 (wasm://wasm/02c2d3da:wasm-function[3489]:0x6712fb)
    at <ruffle_web::audio::WebAudioBackend as ruffle_core::backend::audio::AudioBackend>::start_sound::h29300bc0c86ae32a (wasm://wasm/02c2d3da:wasm-function[9570]:0x851781)
    at ruffle_core::backend::audio::AudioManager::start_sound::haa6a9a198e2cafc1 (wasm://wasm/02c2d3da:wasm-function[3698]:0x6936bd)
    at ruffle_core::avm1::globals::sound::start::hfeb00c3dabd77e61 (wasm://wasm/02c2d3da:wasm-function[932]:0x322c07)
    at ruffle_core::avm1::function::Executable::exec::h4a8a22b8624a5db2 (wasm://wasm/02c2d3da:wasm-function[602]:0x1b4562)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://games.crazygames.com/en_US/minecraft-tower-defense/index.html
SWF URL: https://files.crazygames.com/minecrafttowerdefense.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-05-09
Channel: nightly
Built: 2023-05-09T00:25:26.314Z
Commit: 72769eeefa66b617d3d7f710a76f4ea78ec16104
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 60
numFrames: 15
swfVersion: 10
backgroundColor: #009933
isActionScript3: false
uncompressedLength: 4853509

**Comment by Lord-McSweeney** [comment]
Hello, how did you trigger this error?

**Comment by Lord-McSweeney** [comment]
Closing as not reproducible
