### ISSUE TITLE
Error on https://www.gameflare.com/embed/jacksmith/

### ISSUE THREAD

**Issue by moisesbroz** [ruffle-rs/ruffle#11279]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create texture object"', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.16.0/src/gles/device.rs:704:52
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create texture object"', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.16.0/src/gles/device.rs:704:52
    at imports.wbg.__wbg_new_87297f22973157c8 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:2380:21)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hf586b8fd5967b71f (wasm://wasm/02c3fd4a:wasm-function[8634]:0x83080c)
    at std::panicking::rust_panic_with_hook::h7f7102b82d51338f (wasm://wasm/02c3fd4a:wasm-function[5629]:0x753fa3)
    at core::panicking::panic_fmt::he4489d678d6570d5 (wasm://wasm/02c3fd4a:wasm-function[8483]:0x82bba7)
    at core::result::unwrap_failed::h9c69c0d7a98df92b (wasm://wasm/02c3fd4a:wasm-function[6555]:0x798142)
    at <T as wgpu::context::DynContext>::device_create_texture::h450f28396c087060 (wasm://wasm/02c3fd4a:wasm-function[6320]:0x788479)
    at wgpu::Device::create_texture::h97ceb9e64db3df56 (wasm://wasm/02c3fd4a:wasm-function[4372]:0x6e73da)
    at <ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::register_bitmap::h1c8e038f8e8f1038 (wasm://wasm/02c3fd4a:wasm-function[1642]:0x465eee)
    at ruffle_core::bitmap::bitmap_data::BitmapData::bitmap_handle::hd4d312869c6f2596 (wasm://wasm/02c3fd4a:wasm-function[1359]:0x3d4cde)
    at ruffle_core::bitmap::bitmap_data::BitmapData::update_dirty_texture::h178eb3e98df54e01 (wasm://wasm/02c3fd4a:wasm-function[1338]:0x3ce0c5)
```
AVM2 stack:
```
    at flash.display::BitmapData/flash::display::BitmapData::draw()
    at swordGame.models::Soldier/spriteSheetBlit()
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) UHD Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://www.gameflare.com/embed/jacksmith/
SWF URL: https://data.gameflare.com/games/3054/iOdVF4I6Kwnblp.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-05-29
Channel: nightly
Built: 2023-05-29T00:19:07.550Z
Commit: 0955ab40e67d4668f3ebd5fbdf3602750e35abb8
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 30
numFrames: 2
swfVersion: 10
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 6578963

**Comment by CreaZyp154** [comment]
Where does the bug appear? I've played the first level without issues
