### ISSUE TITLE
Ruffle Chrome (and Firefox) extension crash Nvidia's login

### ISSUE THREAD

**Issue by daniel11420** [ruffle-rs/ruffle#1138]
When trying to log into your Nvidia account (for example, login button at top right of [the GeForce forums](https://www.nvidia.com/en-us/geforce/forums/discover/)), if Ruffle is installed & enabled then the tab will freeze.

Tested by both me and Dinnerbone, the bug happens on both Microsoft Edge Dev (chromium-based so I put chrome in the title) and Firefox (tested by Dinnerbone).

Contrary to what Dinnerbone's error message (attached below) said, this has nothing to do with BitWarden (disabling Ruffle makes the issue not happen, and No BitWarden + Ruffle enabled the issue also happens)

![](https://media.discordapp.net/attachments/722872096002408529/752603845783453796/unknown.png)

The error in the Dev Tools console: 

```
Uncaught DOMException: Blocked a frame with origin https://login.nvgs.nvidia.com from accessing a cross-origin frame
    at g (chrome-extension://jdpbfbhchkclipmabpdhlaifjknfnlch/dist/ruffle.js:1:34017)
    at p (chrome-extension://jdpbfbhchkclipmabpdhlaifjknfnlch/dist/ruffle.js:1:33979)
    at g (chrome-extension://jdpbfbhchkclipmabpdhlaifjknfnlch/dist/ruffle.js:1:34013)
    at MutationObserver.w (chrome-extension://jdpbfbhchkclipmabpdhlaifjknfnlch/dist/ruffle.js:1:34150)
    at a.invoke (https://login.nvgs.nvidia.com/polyfills-es2015.3d529e6b9080fc91b712.js:1:6395)
    at s.runGuarded (https://login.nvgs.nvidia.com/polyfills-es2015.3d529e6b9080fc91b712.js:1:2027)
    at MutationObserver.<anonymous> (https://login.nvgs.nvidia.com/polyfills-es2015.3d529e6b9080fc91b712.js:1:1806)
```
Around ~100 of these errors appear every second (they are grouped together in the developer tools as one error)

cc: @Dinnerbone

**Comment by Toad06** [comment]
There are some issues when polyfilling iframes, most common is cross-domain requests.
Also happens on these sites for example (open the browser's console):
https://www.amazon.com/
https://www.y8.com/games/garfield_coop_catch

**Comment by andremichelle** [comment]
Same goes for https://docs.google.com

**Comment by Justin-CB** [comment]
I suspect I left out a `try{}catch` statement somewhere because the logging statement for that also runs.

**Comment by daniel11420** [comment]
Same goes for https://account.microsoft.com
