### ISSUE TITLE
Error on https://www.y8.com/games/berzerker_stick

### ISSUE THREAD

**Issue by oliverthedeveloper** [ruffle-rs/ruffle#11400]
# Error Info
Error name: Error
Error message: panicked at 'No script object for display object', core/src/avm1/activation.rs:396:18
Error stack:
```
Error: panicked at 'No script object for display object', core/src/avm1/activation.rs:396:18
    at imports.wbg.__wbg_new_87297f22973157c8 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:2380:21)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h21b91a0c05b68a64 (wasm://wasm/02c17266:wasm-function[8614]:0x82671e)
    at std::panicking::rust_panic_with_hook::h85b7f6628c291e12 (wasm://wasm/02c17266:wasm-function[5647]:0x74e548)
    at core::panicking::panic_fmt::hf5c4cd929d4aaa9e (wasm://wasm/02c17266:wasm-function[8481]:0x822371)
    at ruffle_core::display_object::edit_text::EditText::try_bind_text_field_variable::hb3ecbc4b633f63cb (wasm://wasm/02c17266:wasm-function[3360]:0x6384d3)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::h9e40c4eb70891438 (wasm://wasm/02c17266:wasm-function[2886]:0x5daaca)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::h8a5107d6e12a9a27 (wasm://wasm/02c17266:wasm-function[803]:0x2aac5b)
    at ruffle_core::display_object::movie_clip::MovieClip::place_object::hfe56150d658c7ae6 (wasm://wasm/02c17266:wasm-function[1370]:0x3f8fec)
    at <ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::enter_frame::hcf9fc59c718f192e (wasm://wasm/02c17266:wasm-function[778]:0x297ca2)
    at ruffle_core::loader::Loader::movie_loader_complete::h33c9533d15bd5360 (wasm://wasm/02c17266:wasm-function[739]:0x27556c)
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) Iris(R) Xe Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://www.y8.com/games/berzerker_stick
SWF URL: https://img.y8.com/cloud/y8-flash-game/contents/item_versions/flash_games/37634/original/berzerker_stick.swf?1521510408

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.37
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-06-06
Channel: nightly
Built: 2023-06-06T00:19:40.791Z
Commit: 10134467c97a27a9a67dfd663f95dacd8c413dbe
Is extension: true

# Metadata
width: 800
height: 400
frameRate: 30
numFrames: 2
swfVersion: 10
backgroundColor: #FFFFFF
isActionScript3: true
uncompressedLength: 1811117

**Comment by Lord-McSweeney** [comment]
#11005 progresses this, but key controls are noticeably broken.
