### ISSUE TITLE
Error on https://www.spiele-kostenlos-online.de/puzzlespiele/raetselspiele/affen-raetsel/

### ISSUE THREAD

**Issue by Stefan219** [ruffle-rs/ruffle#11431]
# Error Info
Error name: TypeError
Error message: Cannot read properties of undefined (reading 'get')
Error stack:
```
TypeError: Cannot read properties of undefined (reading 'get')
    at https://cdn.spiele-kostenlos-online.de/wp-content/themes/spiele-kostenlos-online/js/ruffle/2023_06_04/core.ruffle.cbcc48fd1ce1a3abc16c.js:1:55974
    at async q (https://cdn.spiele-kostenlos-online.de/wp-content/themes/spiele-kostenlos-online/js/ruffle/2023_06_04/core.ruffle.cbcc48fd1ce1a3abc16c.js:1:55741)
    at async https://cdn.spiele-kostenlos-online.de/wp-content/themes/spiele-kostenlos-online/js/ruffle/2023_06_04/ruffle.js:2:105709
    at async qe.ensureFreshInstance (https://cdn.spiele-kostenlos-online.de/wp-content/themes/spiele-kostenlos-online/js/ruffle/2023_06_04/ruffle.js:2:295742)
    at async qe.load (https://cdn.spiele-kostenlos-online.de/wp-content/themes/spiele-kostenlos-online/js/ruffle/2023_06_04/ruffle.js:2:299270)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://www.spiele-kostenlos-online.de/puzzlespiele/raetselspiele/affen-raetsel/

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-06-04
Channel: nightly
Built: 2023-06-04T00:19:21.198Z
Commit: f62d80dd93c4d7e4ebec5a15b93eb92e89f10fae
Is extension: false

# Metadata

**Comment by n0samu** [comment]
I cannot reproduce this error. Did you do something specific to get it?
