### ISSUE TITLE
Error on https://www.wowgirls.jp/game_html/2916.html

### ISSUE THREAD

**Issue by kenkennkaki** [ruffle-rs/ruffle#11475]
# Error Info
Error name: Error
Error message: panicked at 'No script object for display object', core/src/avm1/activation.rs:372:18
Error stack:
```
Error: panicked at 'No script object for display object', core/src/avm1/activation.rs:372:18
    at W.n.wbg.__wbg_new_15d3966e9981a196 (https://www.wowgirls.jp/script_sp/ruffle/ruffle-nightly-2023_03_01-web-selfhosted/core.ruffle.6187c9182b6127e1f004.js:1:46356)
    at std::sync::once::Once::call_once::{{closure}}::he65b5fd094519943 (wasm://wasm/028652c6:wasm-function[1973]:0x4b9480)
    at std::sys_common::once::generic::Once::call::h6b012ac601cc39bf (wasm://wasm/028652c6:wasm-function[1904]:0x4a8244)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h78e1320fad5dea52 (wasm://wasm/028652c6:wasm-function[7372]:0x7837bd)
    at std::panicking::rust_panic_with_hook::hbafe3e603d331223 (wasm://wasm/028652c6:wasm-function[5199]:0x6db5a1)
    at core::panicking::panic_fmt::h1d17fc068f528130 (wasm://wasm/028652c6:wasm-function[7688]:0x792702)
    at ruffle_core::display_object::edit_text::EditText::try_bind_text_field_variable::h8ca345739d2a4a99 (wasm://wasm/028652c6:wasm-function[3605]:0x636eb3)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::h4cd475d826815b9e (wasm://wasm/028652c6:wasm-function[2634]:0x56e25e)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::h3676beef18416a75 (wasm://wasm/028652c6:wasm-function[698]:0x24fd33)
    at ruffle_core::display_object::movie_clip::MovieClip::place_object::h36e36fcadc88b17e (wasm://wasm/028652c6:wasm-function[1468]:0x3e919d)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://www.wowgirls.jp/game_html/2916.html
SWF URL: https://www.wowgirls.jp/game_files/2916/2916.swf?affiliate_id=50778a867952b492

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.43
Platform: Win32
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-03-01
Channel: nightly
Built: 2023-03-01T00:20:16.562Z
Commit: 93ce5e2328466f80dab83164136da9bd0869f891
Is extension: false

# Metadata
width: 720
height: 600
frameRate: 30
numFrames: 2
swfVersion: 10
backgroundColor: #CCCCCC
isActionScript3: true
uncompressedLength: 643758

**Comment by Lord-McSweeney** [comment]
This seems to be working now
