### ISSUE TITLE
Error on https://ruffle.rs/demo/

### ISSUE THREAD

**Issue by bruhcode68** [ruffle-rs/ruffle#11498]
# Error Info
Error name: Error
Error message: Ruffle is panicking!
Error stack:
```
Error: Ruffle is panicking!
    at Je.load (https://ruffle.rs/demo/index.js:2:245703)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://ruffle.rs/demo/

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36    
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-06-12
Channel: nightly
Built: 2023-06-12T00:19:08.889Z
Commit: da6e2a96bf93d00a06066b2c36fc3ec5ab437d43
Is extension: false

# Metadata

**Comment by bruhcode68** [comment]
im using brave and i use ducklife.swf

https://github.com/Howstheaqua/flashgames/blob/master/duck-life.swf

**Comment by n0samu** [comment]
How did you download the SWF file?

**Comment by bruhcode68** [comment]
i pressed the download button at the right, the down arrow

**Comment by bruhcode68** [comment]
also it works on the downloaded version of ruffle, i used june 7th for the desktop mode

**Comment by bruhcode68** [comment]
i found this aswell in the console at https://ruffle.rs/demo

```
ruffle_web-wasm_extensions.js:676 panicked at 'called `Option::unwrap()` on a `None` value', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/glow-0.12.2/src/web_sys.rs:282:78

Stack:

Error
    at O.n.wbg.__wbg_new_abda76e883ba8a5f (https://ruffle.rs/demo/339.index.js:1:8035)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hf3aedee836863915 (wasm://wasm/02c045ce:wasm-function[8589]:0x82610d)
    at std::panicking::rust_panic_with_hook::h85b7f6628c291e12 (wasm://wasm/02c045ce:wasm-function[5590]:0x74c15d)
    at core::panicking::panic_fmt::hf5c4cd929d4aaa9e (wasm://wasm/02c045ce:wasm-function[8455]:0x82201c)
    at core::panicking::panic::h2f041bf6aa990dfd (wasm://wasm/02c045ce:wasm-function[7725]:0x7e6c0d)
    at <T as wgpu::context::DynContext>::instance_request_adapter::h5bfa5c787a9338c4 (wasm://wasm/02c045ce:wasm-function[5413]:0x73ebb4)
    at ruffle_render_wgpu::backend::WgpuRenderBackend<ruffle_render_wgpu::target::SwapChainTarget>::for_canvas::{{closure}}::hec3561b30c8e2bd3 (wasm://wasm/02c045ce:wasm-function[755]:0x259926)
    at wasm_bindgen_futures::future_to_promise::{{closure}}::{{closure}}::h5097774011593455 (wasm://wasm/02c045ce:wasm-function[1482]:0x40cd7d)
    at wasm_bindgen_futures::queue::Queue::new::{{closure}}::h51a6b377977070fd (wasm://wasm/02c045ce:wasm-function[3670]:0x684348)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hb2f3d4feab119254 (wasm://wasm/02c045ce:wasm-function[9234]:0x83f535)


O.n.wbg.__wbg_error_f851667af71bcfc6 @ ruffle_web-wasm_extensions.js:676
02c045ce:0x74c180 Uncaught (in promise) RuntimeError: unreachable
    at std::panicking::rust_panic_with_hook::h85b7f6628c291e12 (02c045ce:0x74c180)
    at core::panicking::panic_fmt::hf5c4cd929d4aaa9e (02c045ce:0x82201c)
    at core::panicking::panic::h2f041bf6aa990dfd (02c045ce:0x7e6c0d)
    at <T as wgpu::context::DynContext>::instance_request_adapter::h5bfa5c787a9338c4 (02c045ce:0x73ebb4)
    at ruffle_render_wgpu::backend::WgpuRenderBackend<ruffle_render_wgpu::target::SwapChainTarget>::for_canvas::{{closure}}::hec3561b30c8e2bd3 (02c045ce:0x259926)
    at wasm_bindgen_futures::future_to_promise::{{closure}}::{{closure}}::h5097774011593455 (02c045ce:0x40cd7d)
    at wasm_bindgen_futures::queue::Queue::new::{{closure}}::h51a6b377977070fd (02c045ce:0x684348)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hb2f3d4feab119254 (02c045ce:0x83f535)
    at closure5336 externref shim (02c045ce:0x8443b5)
    at D (ruffle_web-wasm_extensions.js:212:10)
```

**Comment by n0samu** [comment]
Thanks for letting us know! In the Ruffle Web Demo, do the sample SWFs work for you? Or is everything broken?
![image](https://github.com/ruffle-rs/ruffle/assets/71368227/d20089ac-8477-42b8-b565-8511f94b7d45)

**Comment by bruhcode68** [comment]
no, not even the ruffle logo swf, no files work

**Comment by n0samu** [comment]
That is strange. Can you send the full error report when Ruffle crashes on the logo SWF? (Click "Report bug")

**Comment by n0samu** [comment]
Does the WebGL test page https://get.webgl.org/ work for you?

**Comment by bruhcode68** [comment]
i cant see the spinning cube, but the top says "your browser supports webgl" so i will click the support link to try and turn it on or smth

**Comment by bruhcode68** [comment]
bro💀💀💀 i fixed it by turning off "shields" in brave, webgl was on the entire time

thanks for your help a lot, you are very epic cool👍
