### ISSUE TITLE
Error on https://flashstorage.games/embed/mini-dash

### ISSUE THREAD

**Issue by Wujaklija7** [ruffle-rs/ruffle#11515]
# Error Info
Error name: Error
Error message: panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:524:5
Error stack:
```
Error: panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:524:5
    at U.n.wbg.__wbg_new_87297f22973157c8 (https://flashstorage.games/public/js/emulators/ruffle/core.ruffle.a5e8c30abf93b74ef9dc.js:1:51022)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h21b91a0c05b68a64 (wasm://wasm/02c1b5fa:wasm-function[8609]:0x8270f7)
    at std::panicking::rust_panic_with_hook::h85b7f6628c291e12 (wasm://wasm/02c1b5fa:wasm-function[5647]:0x74f4be)
    at core::panicking::panic_fmt::hf5c4cd929d4aaa9e (wasm://wasm/02c1b5fa:wasm-function[8476]:0x822d4a)
    at alloc::raw_vec::capacity_overflow::h3bb4537b5f9f8404 (wasm://wasm/02c1b5fa:wasm-function[8223]:0x81c2bf)
    at alloc::raw_vec::RawVec<T,A>::reserve::do_reserve_and_handle::h6e31589ac913ea85 (wasm://wasm/02c1b5fa:wasm-function[5529]:0x748618)
    at ruffle_core::avm2::globals::flash::utils::byte_array::set_length::h0b7e6c1ee02d09d8 (wasm://wasm/02c1b5fa:wasm-function[3420]:0x645692)
    at ruffle_core::avm2::function::Executable::exec::hc8df0910658abbbf (wasm://wasm/02c1b5fa:wasm-function[806]:0x2b22a0)
    at ruffle_core::avm2::object::TObject::call_method::h53c9c3bd5de47541 (wasm://wasm/02c1b5fa:wasm-function[1976]:0x4d68fa)
    at ruffle_core::avm2::object::TObject::set_property::h42d7100df1221ab3 (wasm://wasm/02c1b5fa:wasm-function[2144]:0x513b91)
```
AVM2 stack:
```
    at flash.utils::ByteArray/flash::utils::ByteArray::length()
    at global()
    at global()
    at global()
    at global()
    at global()
    at global()
    at global()
    at global()
    at global()
    at global()
    at global()
    at global()
    at global()
    at com.adobe.flascc::CModule$/callI()
    at com.adobe.flascc::CModule$/start()
    at com.adobe.flascc::CModule$/startAsync()
    at com.adobe.flascc::Console/enterFrame()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (AMD, AMD Radeon RX 6600 XT Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://flashstorage.games/embed/mini-dash
SWF URL: https://flashstorage.games/public/storage/games/November2021/QD21VEcY10LnXC2ISIAK.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-06-08
Channel: nightly
Built: 2023-06-08T00:19:37.028Z
Commit: 8ce8b775a70f291aadd534e7505e2ceae9b06557
Is extension: false

# Metadata
width: 800
height: 533
frameRate: 0.1171875
numFrames: 1
swfVersion: 18
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 20666034

**Comment by n0samu** [comment]
Closing in favor of #10851
