### ISSUE TITLE
whats wrong with this game?Error on https://www.mostfungames.com/pac-man.htm

### ISSUE THREAD

**Issue by Amier2Fly** [ruffle-rs/ruffle#11574]
# Error Info
Error name: CompileError
Error message: WebAssembly.instantiate(): BufferSource argument is empty
Error stack:
```
CompileError: WebAssembly.instantiate(): BufferSource argument is empty
    at https://www.mostfungames.com/wp-content/themes/kizitheme/ruffle/ruffle.js:1:32477
    at async e (https://www.mostfungames.com/wp-content/themes/kizitheme/ruffle/ruffle.js:1:31949)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.mostfungames.com/pac-man.htm

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.43
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-25
Channel: nightly
Built: 2021-01-25T01:05:41.178Z
Commit: 32fd3fb71befbceecbba7c73d08af5ddd0f5a3d0

**Comment by n0samu** [comment]
Hi @Amier2Fly, can you tell me whether the Ruffle Web Demo works for you? https://ruffle.rs/demo/

**Comment by Lord-McSweeney** [comment]
Not an issue with Ruffle, and the site was using a version that is now 4 years outdated
