### ISSUE TITLE
Error on http://itcg.eredan.com/

### ISSUE THREAD

**Issue by jeyjey7878** [ruffle-rs/ruffle#11610]
# Error Info
Error name: Error
Error message: panicked at 'not implemented: Unimplemented opcode Equal', render/naga-pixelbender/src/lib.rs:725:29
Error stack:
```
Error: panicked at 'not implemented: Unimplemented opcode Equal', render/naga-pixelbender/src/lib.rs:725:29
    at imports.wbg.__wbg_new_d258248ed531ff54 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:2396:21)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hcb6f72ebd1a9c8bd (wasm://wasm/02c6e572:wasm-function[8637]:0x83fb82)
    at std::panicking::rust_panic_with_hook::h85b7f6628c291e12 (wasm://wasm/02c6e572:wasm-function[5602]:0x767995)
    at core::panicking::panic_fmt::hf5c4cd929d4aaa9e (wasm://wasm/02c6e572:wasm-function[8501]:0x83b7ba)
    at <ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::compile_pixelbender_shader::h32721b91b5483ef8 (wasm://wasm/02c6e572:wasm-function[7143]:0x7d5dd9)
    at ruffle_core::avm2::globals::flash::display::shader_data::init::hff8e040f78a1b1ba (wasm://wasm/02c6e572:wasm-function[960]:0x3357ed)
    at ruffle_core::avm2::function::Executable::exec::h3325d83591e2f464 (wasm://wasm/02c6e572:wasm-function[811]:0x2aed6f)
    at ruffle_core::avm2::object::TObject::call_property::h4741aae4da6be41a (wasm://wasm/02c6e572:wasm-function[1126]:0x398dd0)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::h0d99b33f9b54fbc7 (wasm://wasm/02c6e572:wasm-function[2687]:0x5ca9c0)
    at ruffle_core::avm2::activation::Activation::run_actions::h207061ade6afadd9 (wasm://wasm/02c6e572:wasm-function[516]:0x2906c)
```
AVM2 stack:
```
    at flash.display::ShaderData/flash::display::ShaderData::init()
    at flash.display::ShaderData()
    at flash.display::Shader/set byteCode()
    at flash.display::Shader()
    at feerik.shaders::BorderShaderFilter()
    at feerik.Eredan.control.tips::ExternalTip/_ExternalTip_BorderShaderFilter1_c()
    at MethodInfo-2967()
    at Function/call()
    at mx.core::ComponentDescriptor/get properties()
    at mx.core::Container/createComponentFromDescriptor()
    at mx.core::Container/createComponentsFromDescriptors()
    at mx.core::Container/createChildren()
    at mx.core::UIComponent/initialize()
    at mx.core::Container/initialize()
    at feerik.Eredan.control.tips::ExternalTip/initialize()
    at mx.core::UIComponent/http://www.adobe.com/2006/flex/mx/internal::childAdded()
    at mx.core::Container/http://www.adobe.com/2006/flex/mx/internal::childAdded()
    at mx.core::Container/addChildAt()
    at EredanSite/addTip()
    at EredanSite/addTip()
    at EredanSite/showLoadingBar()
    at EredanSite/startLoadGroupModule()
    at EredanSite/initEnd()
    at flash.events::EventDispatcher/flash::events::EventDispatcher::dispatchEvent()
    at StyleEventDispatcher/moduleInfo_readyHandler()
    at flash.events::EventDispatcher/flash::events::EventDispatcher::dispatchEvent()
    at ModuleInfoProxy/moduleEventHandler()
    at flash.events::EventDispatcher/flash::events::EventDispatcher::dispatchEvent()
    at ModuleInfo/readyHandler()
    at flash.events::EventDispatcher/flash::events::EventDispatcher::dispatchEvent()
    at mx.core::FlexModuleFactory/update()
    at mx.core::FlexModuleFactory/docFrameHandler()
    at mx.core::FlexModuleFactory/docFrameListener()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) HD Graphics 4000 Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: http://itcg.eredan.com/?p=jeu_afficher2&reply=Joueur_login&result=eyJtb2RlIjoibm9ybWFsIiwib3duZXIiOiJmZWVyaWsiLCJqaWQiOjQxMjc5OTYsInNlc3Npb24iOiJ6ZE8xYzM5bEx2TmNCOVROM01IVGoyRldDTmlnWW12NTZMUEJlZm8xQmhSRWVIcWJJQ2pSUFBvYVZRcEc5eEprZDNpcjVXNHlcL1c4RHVnWGw0VGdHR1BaSFA0ZldXUWRXSlgrSXdCbFRsNm1PczU4emNUbTh5dz09IiwiaXYiOiJhdWlKdHZIciIsInRvcyI6MX0%3D
SWF URL: http://itcg.eredan.com/EredanSite_1508839584.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-06-18
Channel: nightly
Built: 2023-06-18T00:19:35.526Z
Commit: 7bbaeb2a61703c919d961ec6624fb531dbc89485
Is extension: true

# Metadata
width: 500
height: 375
frameRate: 24
numFrames: 2
swfVersion: 10
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 3276449

**Comment by Lord-McSweeney** [comment]
Opcode has since been implemented, though the SWF doesn't fully work yet.
