### ISSUE TITLE
Error on https://arcadespot.com/game/nambers/

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#11630]
# Error Info
Error name: Error
Error message: panicked at 'Tex storage 2D multisample is not supported', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/glow-0.12.2/src/web_sys.rs:3141:9
Error stack:
```
Error: panicked at 'Tex storage 2D multisample is not supported', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/glow-0.12.2/src/web_sys.rs:3141:9
    at imports.wbg.__wbg_new_d258248ed531ff54 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:2396:21)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hcb6f72ebd1a9c8bd (wasm://wasm/02c6cd7e:wasm-function[8635]:0x83f65f)
    at std::panicking::rust_panic_with_hook::h85b7f6628c291e12 (wasm://wasm/02c6cd7e:wasm-function[5602]:0x767517)
    at core::panicking::panic_fmt::hf5c4cd929d4aaa9e (wasm://wasm/02c6cd7e:wasm-function[8499]:0x83b269)
    at <T as wgpu::context::DynContext>::device_create_texture::h2eb6e848288d8733 (wasm://wasm/02c6cd7e:wasm-function[6323]:0x79b06a)
    at wgpu::Device::create_texture::ha235fa98dfb3ff4e (wasm://wasm/02c6cd7e:wasm-function[4408]:0x702d1e)
    at <ruffle_render_wgpu::context3d::WgpuContext3D as ruffle_render::backend::Context3D>::process_command::h1e8733e3f3231cfb (wasm://wasm/02c6cd7e:wasm-function[531]:0xc2a67)
    at ruffle_core::avm2::globals::flash::display3D::context_3d::set_render_to_texture::had439fd829536164 (wasm://wasm/02c6cd7e:wasm-function[1539]:0x451401)
    at ruffle_core::avm2::function::Executable::exec::h3325d83591e2f464 (wasm://wasm/02c6cd7e:wasm-function[811]:0x2ae9e1)
    at ruffle_core::avm2::object::TObject::call_property::h03891e9d704e019e (wasm://wasm/02c6cd7e:wasm-function[1142]:0x3a5f81)
```
AVM2 stack:
```
    at flash.display3D::Context3D/flash::display3D::Context3D::setRenderToTexture()
    at starling.core::RenderSupport/setRenderTarget()
    at starling.textures::RenderTexture/renderBundled()
    at starling.textures::RenderTexture/draw()
    at ui::LevelPack/lock()
    at ui::LevelPack/validate()
    at ui::LevelPack()
    at ui::LevelSelect()
    at Main/loadLanguageAssets()
    at Main/init_()
    at Main/init()
    at Function/App.as$1:anonymous()
    at Function/Assets.as$0:anonymous()
    at Function/AssetManager.as$3:anonymous()
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) Iris(R) Xe Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 1200, height: 900, depth_or_array_layers: 1 }
Player type: Object
SWF URL: https://static.arcadespot.com/wp-content/uploads/2015/10/nambers.swf
Param movie: https://static.arcadespot.com/wp-content/uploads/2015/10/nambers.swf
Param wmode: direct
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined

# Page Info
Page URL: https://arcadespot.com/game/nambers/
SWF URL: https://static.arcadespot.com/wp-content/uploads/2015/10/nambers.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.51
Platform: Win32
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-06-19
Channel: nightly
Built: 2023-06-19T00:19:56.752Z
Commit: 700f765f91830358cf9b8ecb8647bb5645a5bb7d
Is extension: true

# Metadata
width: 800
height: 600
frameRate: 24
numFrames: 2
swfVersion: 21
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 4734542

**Comment by n0samu** [comment]
The problem is also occurring in all of the other Kings Kollege games: [Nambers](https://arcadespot.com/game/nambers/), [Fillz](https://arcadespot.com/game/fillz/), [Hivex](https://arcadespot.com/game/hivex/).

**Comment by Aaron1011** [comment]
This should now be working on the latest `master`
