### ISSUE TITLE
Error on https://lbannana.github.io/lbannana-assets/flash/index.html

### ISSUE THREAD

**Issue by Hruday4** [ruffle-rs/ruffle#11650]
# Error Info
Error name: Error
Error message: panicked at 'not implemented: Unimplemented opcode Pow', render/naga-pixelbender/src/lib.rs:725:29
Error stack:
```
Error: panicked at 'not implemented: Unimplemented opcode Pow', render/naga-pixelbender/src/lib.rs:725:29
    at U.n.wbg.__wbg_new_d258248ed531ff54 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.5dfd87665d54aa7c3b27.js:1:51306)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hcb6f72ebd1a9c8bd (wasm://wasm/02c6a346:wasm-function[8635]:0x83ebbe)
    at std::panicking::rust_panic_with_hook::h85b7f6628c291e12 (wasm://wasm/02c6a346:wasm-function[5603]:0x766b9f)
    at core::panicking::panic_fmt::hf5c4cd929d4aaa9e (wasm://wasm/02c6a346:wasm-function[8499]:0x83a7f6)
    at <ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::compile_pixelbender_shader::h32721b91b5483ef8 (wasm://wasm/02c6a346:wasm-function[7142]:0x7d4e14)
    at ruffle_core::avm2::globals::flash::display::shader_data::init::hff8e040f78a1b1ba (wasm://wasm/02c6a346:wasm-function[960]:0x334d23)
    at ruffle_core::avm2::function::Executable::exec::h3325d83591e2f464 (wasm://wasm/02c6a346:wasm-function[811]:0x2ae214)
    at ruffle_core::avm2::object::TObject::call_property::h4741aae4da6be41a (wasm://wasm/02c6a346:wasm-function[1125]:0x397cb2)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::h0d99b33f9b54fbc7 (wasm://wasm/02c6a346:wasm-function[2690]:0x5ca73e)
    at ruffle_core::avm2::activation::Activation::run_actions::h207061ade6afadd9 (wasm://wasm/02c6a346:wasm-function[516]:0x28fc2)
```
AVM2 stack:
```
    at flash.display::ShaderData/flash::display::ShaderData::init()
    at flash.display::ShaderData()
    at flash.display::Shader/set byteCode()
    at flash.display::Shader()
    at filters::FilterPack()
    at scratch::ScratchStage()
    at Scratch/getScratchStage()
    at Scratch/initialize()
    at Loader::SB2Loader/determineJSAccess()
    at Scratch()
    at Loader::SB2Loader()
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "Mesa DRI Intel(R) UHD Graphics 600 (GLK 2)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | TEXTURE_COMPRESSION_ASTC_HDR | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://lbannana.github.io/lbannana-assets/flash/index.html?swf=cookie-clicker-hacked.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-06-20
Channel: nightly
Built: 2023-06-20T00:20:10.263Z
Commit: 18fb5064d3c0244b82cfbee428759bc2a76aafbc
Is extension: false

# Metadata
width: 480
height: 360
frameRate: 24
numFrames: 1
swfVersion: 14
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 11642144

**Comment by Lord-McSweeney** [comment]
Opcode has since been implemented.
