### ISSUE TITLE
Error on https://famitama.xyz/pc/index.html

### ISSUE THREAD

**Issue by rhythmichi** [ruffle-rs/ruffle#11668]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/library.rs:350:26
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/library.rs:350:26
    at imports.wbg.__wbg_new_d258248ed531ff54 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:2396:21)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hcb6f72ebd1a9c8bd (wasm://wasm/02c6a84e:wasm-function[8635]:0x83ec5c)
    at std::panicking::rust_panic_with_hook::h85b7f6628c291e12 (wasm://wasm/02c6a84e:wasm-function[5603]:0x766c3d)
    at core::panicking::panic_fmt::hf5c4cd929d4aaa9e (wasm://wasm/02c6a84e:wasm-function[8499]:0x83a866)
    at core::panicking::panic::h2f041bf6aa990dfd (wasm://wasm/02c6a84e:wasm-function[7756]:0x809830)
    at ruffle_core::display_object::movie_clip::MovieClip::preload::hd423123fbfc4ea6b (wasm://wasm/02c6a84e:wasm-function[646]:0x1f2d10)
    at ruffle_core::loader::Loader::preload_tick::h34a49ba98b65c11c (wasm://wasm/02c6a84e:wasm-function[1665]:0x4862c4)
    at ruffle_core::loader::Loader::movie_loader_data::hb7fa154deb2c41c2 (wasm://wasm/02c6a84e:wasm-function[2555]:0x5a8bd4)
    at ruffle_core::loader::Loader::movie_loader::{{closure}}::h103be6e9de20330c (wasm://wasm/02c6a84e:wasm-function[718]:0x24de3c)
    at <ruffle_web::navigator::WebNavigatorBackend as ruffle_core::backend::navigator::NavigatorBackend>::spawn_future::{{closure}}::h4e80d7d8baa33206 (wasm://wasm/02c6a84e:wasm-function[1023]:0x35c95a)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "Mesa DRI Intel(R) UHD Graphics 600 (GLK 2)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | TEXTURE_COMPRESSION_ASTC_HDR | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://famitama.xyz/pc/index.html
SWF URL: https://famitama.xyz/pc/famitama_shell_patch.swf?init_site_lang=en

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-06-21
Channel: nightly
Built: 2023-06-21T00:19:43.730Z
Commit: b3c40ecda107ee33cbc44868fcd7dfdbdc634775
Is extension: true

# Metadata
width: 752
height: 564
frameRate: 12
numFrames: 1
swfVersion: 8
backgroundColor: #FFFFFF
isActionScript3: false
uncompressedLength: 1021590

**Comment by Lord-McSweeney** [comment]
Hello @rhythmichi, what were you doing when this error appeared?

**Comment by Lord-McSweeney** [comment]
I've figured out a reproduction. Go to the Gotchi Amusement Park, then click Stepping Stones on the left, then click "Click here if you don't have a V.5/Familitchi toy."
