### ISSUE TITLE
Error on Snipr

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#11677]
# Error Info
Error name: Error
Error message: panicked at 'No script object for display object', core/src/avm1/activation.rs:396:18
Error stack:
```
Error: panicked at 'No script object for display object', core/src/avm1/activation.rs:396:18
    at U.n.wbg.__wbg_new_d258248ed531ff54 (https://www.spiele-umsonst.de/ruffle/core.ruffle.5dfd87665d54aa7c3b27.js:1:51306)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hcb6f72ebd1a9c8bd (wasm://wasm/02c6a346:wasm-function[8635]:0x83ebbe)
    at std::panicking::rust_panic_with_hook::h85b7f6628c291e12 (wasm://wasm/02c6a346:wasm-function[5603]:0x766b9f)
    at core::panicking::panic_fmt::hf5c4cd929d4aaa9e (wasm://wasm/02c6a346:wasm-function[8499]:0x83a7c8)
    at ruffle_core::display_object::edit_text::EditText::try_bind_text_field_variable::hfa767080570162c4 (wasm://wasm/02c6a346:wasm-function[3367]:0x65a5ee)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::h86a92d34f43fca6b (wasm://wasm/02c6a346:wasm-function[2924]:0x5ff0cb)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::h93ae68f7244fa0b9 (wasm://wasm/02c6a346:wasm-function[810]:0x2ad9ec)
    at ruffle_core::display_object::movie_clip::MovieClip::place_object::hb2bf6fcc9f70c38a (wasm://wasm/02c6a346:wasm-function[1382]:0x40fb3e)
    at <ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::enter_frame::he7b7d267973943c2 (wasm://wasm/02c6a346:wasm-function[787]:0x29d12d)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::h93ae68f7244fa0b9 (wasm://wasm/02c6a346:wasm-function[810]:0x2ada27)
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA GeForce GTX 1050 Ti Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
SWF URL: https://www.spiele-umsonst.de/azad/downloads/flashgames/snipr.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-06-20
Channel: nightly
Built: 2023-06-20T00:20:10.263Z
Commit: 18fb5064d3c0244b82cfbee428759bc2a76aafbc
Is extension: false

# Metadata
width: 550
height: 400
frameRate: 33
numFrames: 2
swfVersion: 10
backgroundColor: #FFFFFF
isActionScript3: true
uncompressedLength: 6167035

**Comment by Lord-McSweeney** [comment]
Fixed by #11005
