### ISSUE TITLE
Error on https://kdata1.com/games/onepiece17/

### ISSUE THREAD

**Issue by MassKyz** [ruffle-rs/ruffle#11692]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/library.rs:348:26
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/library.rs:348:26
    at imports.wbg.__wbg_new_d258248ed531ff54 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:2396:21)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hcb6f72ebd1a9c8bd (wasm://wasm/02c6c64a:wasm-function[8635]:0x83e821)
    at std::panicking::rust_panic_with_hook::h85b7f6628c291e12 (wasm://wasm/02c6c64a:wasm-function[5602]:0x76674c)
    at core::panicking::panic_fmt::hf5c4cd929d4aaa9e (wasm://wasm/02c6c64a:wasm-function[8499]:0x83a42b)
    at core::panicking::panic::h2f041bf6aa990dfd (wasm://wasm/02c6c64a:wasm-function[7756]:0x8093f5)
    at ruffle_core::display_object::movie_clip::MovieClip::preload::hd423123fbfc4ea6b (wasm://wasm/02c6c64a:wasm-function[646]:0x1f2b99)
    at ruffle_core::loader::Loader::preload_tick::h34a49ba98b65c11c (wasm://wasm/02c6c64a:wasm-function[1664]:0x485802)
    at ruffle_web::Ruffle::tick::h454fc6e5dc8d3cb0 (wasm://wasm/02c6c64a:wasm-function[739]:0x268d45)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h0c495ff367a052fd (wasm://wasm/02c6c64a:wasm-function[10432]:0x87a70b)
    at wasm_bindgen::convert::closures::invoke1_mut::h53850446a55636df (wasm://wasm/02c6c64a:wasm-function[9242]:0x85741c)
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) UHD Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 936, height: 696, depth_or_array_layers: 1 }

# Page Info
Page URL: https://kdata1.com/games/onepiece17/
SWF URL: https://kdata1.com/games/onepiece17/game.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-06-23
Channel: nightly
Built: 2023-06-23T00:25:27.882Z
Commit: e0cc7f1e544044ba78568df1152366631bc86153
Is extension: true

# Metadata
width: 800
height: 800
frameRate: 24
numFrames: 1
swfVersion: 8
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 10342

**Comment by Lord-McSweeney** [comment]
Fixed by #11005
