### ISSUE TITLE
Error on https://www.comdotgame.com/play/super-deepthroat

### ISSUE THREAD

**Issue by Wibu6789** [ruffle-rs/ruffle#11695]
# Error Info
Error name: Error
Error message: panicked at 'not implemented: Unimplemented opcode Max', render/naga-pixelbender/src/lib.rs:725:29
Error stack:
```
Error: panicked at 'not implemented: Unimplemented opcode Max', render/naga-pixelbender/src/lib.rs:725:29
    at U.n.wbg.__wbg_new_d258248ed531ff54 (https://echo.comdotgame.com/ruffle/core.ruffle.92cbde08851f80731139.js:1:51306)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hcb6f72ebd1a9c8bd (wasm://wasm/02c6cd7e:wasm-function[8635]:0x83f65f)
    at std::panicking::rust_panic_with_hook::h85b7f6628c291e12 (wasm://wasm/02c6cd7e:wasm-function[5602]:0x767517)
    at core::panicking::panic_fmt::hf5c4cd929d4aaa9e (wasm://wasm/02c6cd7e:wasm-function[8499]:0x83b297)
    at <ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::compile_pixelbender_shader::h32721b91b5483ef8 (wasm://wasm/02c6cd7e:wasm-function[7142]:0x7d58b5)
    at ruffle_core::avm2::globals::flash::display::shader_data::init::hff8e040f78a1b1ba (wasm://wasm/02c6cd7e:wasm-function[960]:0x33549c)
    at ruffle_core::avm2::function::Executable::exec::h3325d83591e2f464 (wasm://wasm/02c6cd7e:wasm-function[811]:0x2ae9e1)
    at ruffle_core::avm2::object::TObject::call_property::h4741aae4da6be41a (wasm://wasm/02c6cd7e:wasm-function[1125]:0x39845f)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::h0d99b33f9b54fbc7 (wasm://wasm/02c6cd7e:wasm-function[2687]:0x5ca542)
    at ruffle_core::avm2::activation::Activation::run_actions::h207061ade6afadd9 (wasm://wasm/02c6cd7e:wasm-function[516]:0x28fcc)
```
AVM2 stack:
```
    at flash.display::ShaderData/flash::display::ShaderData::init()
    at flash.display::ShaderData()
    at flash.display::Shader/set byteCode()
    at flash.display::Shader()
    at DT()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Qualcomm, Adreno (TM) 650, OpenGL ES 3.2)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | TEXTURE_COMPRESSION_ASTC_HDR | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 4096, max_texture_dimension_2d: 4096, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }
Player type: Object
SWF URL: https://echo.comdotgame.com/4x90xhl3k0/games/files/f623ea7559ef39d96ebb0ca7530586b8.swf
Param allowscriptaccess: always
Param bgcolor: ffffff
Param wmode: gpu
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined
Attribute 6: undefined

# Page Info
Page URL: https://www.comdotgame.com/play/super-deepthroat?ruffle
SWF URL: https://echo.comdotgame.com/4x90xhl3k0/games/files/f623ea7559ef39d96ebb0ca7530586b8.swf

# Browser Info
User Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Mobile Safari/537.36
Platform: Linux armv81
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-06-19
Channel: nightly
Built: 2023-06-19T00:19:56.752Z
Commit: 700f765f91830358cf9b8ecb8647bb5645a5bb7d
Is extension: false

# Metadata
width: 700
height: 600
frameRate: 30
numFrames: 3
swfVersion: 11
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 2251296

**Comment by Lord-McSweeney** [comment]
`Max` has since been implemented; I'm not testing to see if the game needs any more opcodes.
