### ISSUE TITLE
Error on https://ruffle-regressions.github.io/

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#11737]
# Error Info
Error name: Error
Error message: panicked at 'No uniform for push constant', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.16.1/src/gles/command.rs:725:17
Error stack:
```
Error: panicked at 'No uniform for push constant', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.16.1/src/gles/command.rs:725:17
    at U.n.wbg.__wbg_new_d258248ed531ff54 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2023.6.26/core.ruffle.56816cf5272d884d6339.js:1:51428)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hcb6f72ebd1a9c8bd (wasm://wasm/02cac98e:wasm-function[8726]:0x84c1e2)
    at std::panicking::rust_panic_with_hook::h85b7f6628c291e12 (wasm://wasm/02cac98e:wasm-function[5669]:0x76679b)
    at core::panicking::panic_fmt::hf5c4cd929d4aaa9e (wasm://wasm/02cac98e:wasm-function[8589]:0x847d5d)
    at wgpu_hal::gles::command::<impl wgpu_hal::CommandEncoder<wgpu_hal::gles::Api> for wgpu_hal::gles::CommandEncoder>::set_push_constants::h03b954e6f15c565d (wasm://wasm/02cac98e:wasm-function[3402]:0x654fb0)
    at <T as wgpu::context::DynContext>::command_encoder_end_render_pass::he918cbd1928e62dc (wasm://wasm/02cac98e:wasm-function[8106]:0x83214d)
    at <wgpu::RenderPass as core::ops::drop::Drop>::drop::h58858ceefb13079f (wasm://wasm/02cac98e:wasm-function[6825]:0x7c85b6)
    at ruffle_render_wgpu::surface::Surface::apply_filter::h02f31cff376bd126 (wasm://wasm/02cac98e:wasm-function[691]:0x229fac)
    at <ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::submit_frame::h75c1d32dbe5d64e4 (wasm://wasm/02cac98e:wasm-function[670]:0x20cf92)
    at ruffle_web::Ruffle::tick::h454fc6e5dc8d3cb0 (wasm://wasm/02cac98e:wasm-function[744]:0x2723df)
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Qualcomm, Adreno (TM) 730, OpenGL ES 3.2)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | TEXTURE_COMPRESSION_ASTC_HDR | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 4096, max_texture_dimension_2d: 4096, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://ruffle-regressions.github.io/?version=0.1.0-nightly.2023.6.26
SWF URL: https://ruffle-regressions.github.io/swfs/saturday_morning_watchmen.swf

# Browser Info
User Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Mobile Safari/537.36
Platform: Linux armv81
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-06-26
Channel: nightly
Built: 2023-06-26T00:19:41.849Z
Commit: 8c40e97ab55590c4d78de37a3dfb51624d005062
Is extension: false

# Metadata
width: 699
height: 525
frameRate: 25
numFrames: 2160
swfVersion: 9
backgroundColor: #FFFFFF
isActionScript3: false
uncompressedLength: 6490001

**Comment by waspennator** [comment]
Swf worked fine yesterday, but broke with today's build.

**Comment by waspennator** [comment]
Fixed as of latest nightly.
