### ISSUE TITLE
Error on https://www.mathsisfun.com/games/addemup.html

### ISSUE THREAD

**Issue by SueO2** [ruffle-rs/ruffle#11765]
# Error Info
Error name: ChunkLoadError
Error message: Loading chunk 662 failed.
(error: https://www.mathsisfun.com/images/ruffle/core.ruffle.0197a207ce1d77ef54e9.js)
Error stack:
```
ChunkLoadError: Loading chunk 662 failed.
(error: https://www.mathsisfun.com/images/ruffle/core.ruffle.0197a207ce1d77ef54e9.js)
    at Si.f.j (https://www.mathsisfun.com/images/ruffle/ruffle.js:1:37770)
    at https://www.mathsisfun.com/images/ruffle/ruffle.js:1:36164
    at Array.reduce (<anonymous>)
    at Si.e (https://www.mathsisfun.com/images/ruffle/ruffle.js:1:36141)
    at o (https://www.mathsisfun.com/images/ruffle/ruffle.js:1:2657)
    at o.next (<anonymous>)
    at https://www.mathsisfun.com/images/ruffle/ruffle.js:1:2957
    at new Promise (<anonymous>)
    at https://www.mathsisfun.com/images/ruffle/ruffle.js:1:2693
    at o (https://www.mathsisfun.com/images/ruffle/ruffle.js:1:2980)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.mathsisfun.com/games/addemup.html

# Browser Info
Useragent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-16
Channel: nightly
Built: 2021-01-16T01:09:33.302Z
Commit: 9df7facdb8d37a5d007a13c25efcc176ed4675e0

**Comment by n0samu** [comment]
See https://github.com/ruffle-rs/ruffle/issues/11762#issuecomment-1610593397

**Comment by Lord-McSweeney** [comment]
Not an issue with Ruffle, and the site was using a version that is now 4 years outdated
