### ISSUE TITLE
Panic in font wrapping calculations

### ISSUE THREAD

**Issue by Dinnerbone** [ruffle-rs/ruffle#1183]
In [Ragdoll Cannon 2](https://www.newgrounds.com/portal/view/453500?emulate=flash), we panic with the following error on the first frame:
```
thread 'main' panicked at 'byte index 1 is not a char boundary; it is inside '\u{a0}' (bytes 0..2) of `                                                                                                                         `', C:\Users\dinne\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib/rustlib/src/rust\src\libcore\str\mod.rs:1920:47
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.46\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print_fmt
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\sys_common\backtrace.rs:78
   2: std::sys_common::backtrace::_print::{{impl}}::fmt
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\sys_common\backtrace.rs:59
   3: core::fmt::write
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libcore\fmt\mod.rs:1069
   4: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\io\mod.rs:1504
   5: std::sys_common::backtrace::_print
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\sys_common\backtrace.rs:62
   6: std::sys_common::backtrace::print
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\sys_common\backtrace.rs:49
   7: std::panicking::default_hook::{{closure}}
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\panicking.rs:198
   8: std::panicking::default_hook
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\panicking.rs:218
   9: std::panicking::rust_panic_with_hook
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\panicking.rs:511
  10: std::panicking::begin_panic_handler
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\panicking.rs:419
  11: core::panicking::panic_fmt
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libcore\panicking.rs:111
  12: core::str::slice_error_fail
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libcore\str\mod.rs:0
  13: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
  14: ruffle_core::font::Font::wrap_line
  15: ruffle_core::bounding_box::BoundingBox::transform
  16: ruffle_core::display_object::edit_text::EditText::from_swf_tag
  17: hashbrown::map::make_hash
  18: ruffle_core::tag_utils::decode_tags
  19: ruffle_core::display_object::movie_clip::MovieClip::preload
  20: ruffle_core::player::Player::set_root_movie
  21: hashbrown::map::make_hash
  22: <T as core::any::Any>::type_id
  23: std::rt::lang_start_internal::{{closure}}
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\rt.rs:52
  24: std::panicking::try::do_call
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\panicking.rs:331
  25: std::panicking::try
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\panicking.rs:274
  26: std::panic::catch_unwind
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\panic.rs:394
  27: std::rt::lang_start_internal
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\rt.rs:51
  28: main
  29: post_pgo_initializer
  30: <unknown>
```

**Comment by adrian17** [comment]
Looks like tag parsing is working now; but now it just hangs in AS3 preloader.

**Comment by Lord-McSweeney** [comment]
The preloader also works now, so I think this issue can be closed.
