### ISSUE TITLE
Error on https://g80g.com/game.php

### ISSUE THREAD

**Issue by rge9po0kfjsd** [ruffle-rs/ruffle#11833]
# Error Info
Error name: Error
Error message: panicked at 'not implemented: Unimplemented opcode Pow', render/naga-pixelbender/src/lib.rs:725:29
Error stack:
```
Error: panicked at 'not implemented: Unimplemented opcode Pow', render/naga-pixelbender/src/lib.rs:725:29
    at imports.wbg.__wbg_new_d258248ed531ff54 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:2400:21)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h02df5e9c2be9a573 (wasm://wasm/02ce7e4a:wasm-function[8732]:0x858ef5)
    at std::panicking::rust_panic_with_hook::h85b7f6628c291e12 (wasm://wasm/02ce7e4a:wasm-function[5685]:0x77e246)
    at core::panicking::panic_fmt::hf5c4cd929d4aaa9e (wasm://wasm/02ce7e4a:wasm-function[8594]:0x854a70)
    at <ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::compile_pixelbender_shader::h32bc2a7b89c10d47 (wasm://wasm/02ce7e4a:wasm-function[7222]:0x7ee57f)
    at ruffle_core::avm2::globals::flash::display::shader_data::init::he821fe54f613e9f2 (wasm://wasm/02ce7e4a:wasm-function[830]:0x2cef98)
    at ruffle_core::avm2::function::Executable::exec::hfddced13e47fe227 (wasm://wasm/02ce7e4a:wasm-function[819]:0x2bbd25)
    at ruffle_core::avm2::object::TObject::call_property::h8a732cf0e7f618c3 (wasm://wasm/02ce7e4a:wasm-function[1128]:0x3a139a)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::h863788d9e2d42858 (wasm://wasm/02ce7e4a:wasm-function[2693]:0x5d3cae)
    at ruffle_core::avm2::activation::Activation::run_actions::hf738c67c77d190e5 (wasm://wasm/02ce7e4a:wasm-function[517]:0x29243)
```
AVM2 stack:
```
    at flash.display::ShaderData/flash::display::ShaderData::init()
    at flash.display::ShaderData()
    at flash.display::Shader/set byteCode()
    at flash.display::Shader()
    at filters::FilterPack()
    at scratch::ScratchStage()
    at Scratch/getScratchStage()
    at Scratch/initialize()
    at Loader::SB2Loader/determineJSAccess()
    at Scratch()
    at Loader::SB2Loader()
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Google, Vulkan 1.3.0 (SwiftShader Device (Subzero) (0x0000C0DE)), SwiftShader driver)"
Adapter Device Type: Cpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | TEXTURE_COMPRESSION_ASTC_HDR | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 8192, max_texture_dimension_2d: 8192, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://g80g.com/game.php?id=7513
SWF URL: https://img-hws.y8.com/cloud/y8-flash-game/contents/item_versions/flash_games/93077/original/scratch_minecraft.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-07-01
Channel: nightly
Built: 2023-07-01T00:25:59.437Z
Commit: 29a5c6a4cd9918d5e1eb89cc42ccd03d4e920931
Is extension: true

# Metadata
width: 480
height: 380
frameRate: 24
numFrames: 1
swfVersion: 14
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 6821422

**Comment by Lord-McSweeney** [comment]
Since `Pow` has been implemented, this now needs Atan2. See #11865.
