### ISSUE TITLE
Error on http://swordandsandals.top/swords-and-sandals-2-full-version/

### ISSUE THREAD

**Issue by AleksGeorg** [ruffle-rs/ruffle#11852]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create texture object"', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.16.1/src/gles/device.rs:704:52
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create texture object"', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.16.1/src/gles/device.rs:704:52
    at U.n.wbg.__wbg_new_d258248ed531ff54 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.f56267020d1df1980a84.js:1:51428)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hac2de81f3b71691d (wasm://wasm/02d0bae6:wasm-function[8753]:0x86097f)
    at std::panicking::rust_panic_with_hook::h85b7f6628c291e12 (wasm://wasm/02d0bae6:wasm-function[5685]:0x76cda2)
    at core::panicking::panic_fmt::hf5c4cd929d4aaa9e (wasm://wasm/02d0bae6:wasm-function[8615]:0x85c4fa)
    at core::result::unwrap_failed::he0ddc269083098af (wasm://wasm/02d0bae6:wasm-function[6645]:0x7be002)
    at <T as wgpu::context::DynContext>::device_create_texture::h848f850c6594584b (wasm://wasm/02d0bae6:wasm-function[6428]:0x7ad22f)
    at wgpu::Device::create_texture::h127f33138a2dca5d (wasm://wasm/02d0bae6:wasm-function[4439]:0x6fb44e)
    at <ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::create_empty_texture::hcf67a01347ea6535 (wasm://wasm/02d0bae6:wasm-function[4785]:0x71d5ac)
    at ruffle_core::display_object::render_base::h74549ec45d988460 (wasm://wasm/02d0bae6:wasm-function[637]:0x1b838b)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render::h42c8c3ac01e6af34 (wasm://wasm/02d0bae6:wasm-function[6228]:0x79a395)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA GeForce GTX 1660 Ti Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: http://swordandsandals.top/swords-and-sandals-2-full-version/
SWF URL: http://swordandsandals.top/wp-content/uploads/swords-and-sandals-2.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-07-02
Channel: nightly
Built: 2023-07-02T00:20:03.951Z
Commit: bd043c09c7a4526d569da2ec5ea22695366ba7dc
Is extension: false

# Metadata
width: 640
height: 420
frameRate: 30
numFrames: 277
swfVersion: 8
backgroundColor: #FFCC66
isActionScript3: false
uncompressedLength: 5282134

**Comment by Lord-McSweeney** [comment]
Duplicate of #18248
