### ISSUE TITLE
GPU gets 'stuck' on certain movies

### ISSUE THREAD

**Issue by Dinnerbone** [ruffle-rs/ruffle#1186]
On exporter, this shows as:
```
thread 'main' panicked at 'GPU got stuck :(', C:\Users\dinne\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.6.0\src\backend\direct.rs:1323:35
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

On desktop, with vulkan validation enabled, I get this:
```
[2020-09-17T22:09:16Z WARN  ruffle_render_wgpu] Couldn't begin new render frame: A timeout was encountered while trying to acquire the next frame
[2020-09-17T22:09:16Z ERROR gfx_backend_vulkan] 
    VALIDATION [UNASSIGNED-CoreValidation-DrawState-InvalidFence (319439728)] : Validation Error: [ UNASSIGNED-CoreValidation-DrawState-InvalidFence ] Object 0: handle = 0x948acd0000000008, type = VK_OBJECT_TYPE_FENCE; | MessageID = 0x130a4370 | VkFence 0x948acd0000000008[] is already in use by another submission.
    object info: (type: FENCE, hndl: 10703592864283099144)
```

Example movies (desktop / exporter only):
- [Seinfeld Soundsboard](https://www.newgrounds.com/portal/view/196481?emulate=flash)
- [Operation FLASHback](https://www.newgrounds.com/portal/view/257109?emulate=flash)

**Comment by Dinnerbone** [comment]
@Herschel can we get a wgpu label too please?

Maybe categorise all the rendering backends as render-wgpu render-canvas etc

**Comment by n0samu** [comment]
Operation FLASHback seems to be working fine now, but Seinfeld Soundsboard is still crashing. Here's the log from Ruffle:
```
[WARN  ruffle_core::tag_utils] Unknown tag code: 25
[WARN  ruffle_core::tag_utils] Unknown tag code: 25
thread 'main' panicked at 'Error in Queue::submit: parent device is lost', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.13.1\src\backend\direct.rs:281:9
```

**Comment by relrelb** [comment]
Seinfeld Soundsboard was fixed between https://github.com/ruffle-rs/ruffle/compare/nightly-2023-01-23...nightly-2023-01-24.
