### ISSUE TITLE
Incorrect graphics and slow tessellation in CYSTIA

### ISSUE THREAD

**Issue by Dinnerbone** [ruffle-rs/ruffle#1188]
[\*\*\*CYSTIA!\*\*\*](https://www.newgrounds.com/portal/view/204806?emulate=flash) will hang on the first frame, consuming all available GPU memory and then panic when it runs out. For me, it takes a few minutes to get to 11GB and then will panic.

It appears to load on webgl, but will hang the browser completely for a minute or so whilst it does so. Additionally, the graphics appear broken, I assume because it's not a hard panic when it runs out of memory, but is silently dropping extra data?

```
thread 'main' panicked at 'not enough memory left', C:\Users\dinne\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.6.0\src\backend\direct.rs:1323:35
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.46\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print_fmt
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\sys_common\backtrace.rs:78
   2: std::sys_common::backtrace::_print::{{impl}}::fmt
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\sys_common\backtrace.rs:59
   3: core::fmt::write
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libcore\fmt\mod.rs:1069
   4: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\io\mod.rs:1504
   5: std::sys_common::backtrace::_print
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\sys_common\backtrace.rs:62
   6: std::sys_common::backtrace::print
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\sys_common\backtrace.rs:49
   7: std::panicking::default_hook::{{closure}}
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\panicking.rs:198
   8: std::panicking::default_hook
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\panicking.rs:218
   9: std::panicking::rust_panic_with_hook
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\panicking.rs:511
  10: std::panicking::begin_panic_handler
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\panicking.rs:419
  11: std::panicking::begin_panic_fmt
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\panicking.rs:373
  12: wgpu::backend::direct::{{impl}}::unwrap_pretty::{{closure}}<wgpu_core::id::Id<wgpu_core::resource::Buffer<gfx_backend_empty::Backend>>,wgpu_core::resource::CreateBufferError>
             at C:\Users\dinne\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.6.0\src\backend\direct.rs:1323
  13: core::result::Result<wgpu_core::id::Id<wgpu_core::resource::Buffer<gfx_backend_empty::Backend>>, wgpu_core::resource::CreateBufferError>::unwrap_or_else<wgpu_core::id::Id<wgpu_core::resource::Buffer<gfx_backend_empty::Backend>>,wgpu_core::resource::Create
             at C:\Users\dinne\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\result.rs:853
  14: wgpu::backend::direct::{{impl}}::unwrap_pretty<wgpu_core::id::Id<wgpu_core::resource::Buffer<gfx_backend_empty::Backend>>,wgpu_core::resource::CreateBufferError>
             at C:\Users\dinne\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.6.0\src\backend\direct.rs:1323
  15: wgpu::backend::direct::{{impl}}::device_create_buffer
             at C:\Users\dinne\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.6.0\src\backend\direct.rs:796
  16: wgpu::util::{{impl}}::create_buffer_init
             at C:\Users\dinne\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.6.0\src\util\mod.rs:79
  17: ruffle_render_wgpu::utils::create_buffer_with_data
             at W:\personal\ruffle\render\wgpu\src\utils.rs:63
  18: ruffle_render_wgpu::{{impl}}::register_shape_internal::flush_draw
             at W:\personal\ruffle\render\wgpu\src\lib.rs:290
  19: ruffle_render_wgpu::WgpuRenderBackend<ruffle_render_wgpu::target::SwapChainTarget>::register_shape_internal<ruffle_render_wgpu::target::SwapChainTarget>
             at W:\personal\ruffle\render\wgpu\src\lib.rs:612
  20: ruffle_render_wgpu::{{impl}}::register_shape<ruffle_render_wgpu::target::SwapChainTarget>
             at W:\personal\ruffle\render\wgpu\src\lib.rs:869
  21: ruffle_core::display_object::morph_shape::MorphShapeStatic::register_ratio
             at W:\personal\ruffle\core\src\display_object\morph_shape.rs:270
  22: ruffle_core::display_object::movie_clip::MovieClipData::preload_place_object
             at W:\personal\ruffle\core\src\display_object\movie_clip.rs:1693
  23: ruffle_core::display_object::movie_clip::{{impl}}::preload::{{closure}}
             at W:\personal\ruffle\core\src\display_object\movie_clip.rs:290
  24: ruffle_core::tag_utils::decode_tags<slice<u8>*,closure-0>
             at W:\personal\ruffle\core\src\tag_utils.rs:285
  25: ruffle_core::display_object::movie_clip::MovieClip::preload
             at W:\personal\ruffle\core\src\display_object\movie_clip.rs:351
  26: ruffle_core::player::{{impl}}::preload::{{closure}}
             at W:\personal\ruffle\core\src\player.rs:762
  27: ruffle_core::player::{{impl}}::mutate_with_update_context::{{closure}}<closure-0,()>
             at W:\personal\ruffle\core\src\player.rs:1115
  28: ruffle_core::player::GcArena::mutate<closure-0,()>
             at C:\Users\dinne\.cargo\registry\src\github.com-1ecc6299db9ec823\gc-arena-0.2.0\src\arena.rs:161
  29: ruffle_core::player::Player::mutate_with_update_context<closure-0,()>
             at W:\personal\ruffle\core\src\player.rs:1062
  30: ruffle_core::player::Player::preload
             at W:\personal\ruffle\core\src\player.rs:759
  31: ruffle_core::player::Player::set_root_movie
             at W:\personal\ruffle\core\src\player.rs:382
  32: ruffle_desktop::run_player
             at .\src\main.rs:181
  33: ruffle_desktop::main
             at .\src\main.rs:114
  34: std::rt::lang_start::{{closure}}<()>
             at C:\Users\dinne\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\rt.rs:67
  35: std::rt::lang_start_internal::{{closure}}
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\rt.rs:52
  36: std::panicking::try::do_call
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\panicking.rs:331
  37: std::panicking::try
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\panicking.rs:274
  38: std::panic::catch_unwind
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\panic.rs:394
  39: std::rt::lang_start_internal
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\rt.rs:51
  40: std::rt::lang_start<()>
             at C:\Users\dinne\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\rt.rs:67
  41: main
  42: invoke_main
             at d:\A01\_work\6\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  43: __scrt_common_main_seh
             at d:\A01\_work\6\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  44: BaseThreadInitThunk
  45: RtlUserThreadStart
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

Process finished with exit code -1

```

**Comment by n0samu** [comment]
Seems to be fixed now!
