### ISSUE TITLE
register_bitmap_jpeg_2 tries to draw more pixels than we allocate a texture for

### ISSUE THREAD

**Issue by Dinnerbone** [ruffle-rs/ruffle#1189]
This is a warning on webgl, and the extra data is lost:
```
WebGL warning: texImage: Desired upload requires more data than is available: (854 rows plus 654 pixels needed, 285 rows plus 0 pixels available)
```

This is a panic on wgpu:
```
thread 'main' panicked at 'copy would end up overruning the bounds of the destination buffer/texture', C:\Users\dinne\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.6.0\src\backend\direct.rs:1323:35
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.46\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print_fmt
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\sys_common\backtrace.rs:78
   2: std::sys_common::backtrace::_print::{{impl}}::fmt
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\sys_common\backtrace.rs:59
   3: core::fmt::write
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libcore\fmt\mod.rs:1069
   4: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\io\mod.rs:1504
   5: std::sys_common::backtrace::_print
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\sys_common\backtrace.rs:62
   6: std::sys_common::backtrace::print
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\sys_common\backtrace.rs:49
   7: std::panicking::default_hook::{{closure}}
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\panicking.rs:198
   8: std::panicking::default_hook
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\panicking.rs:218
   9: std::panicking::rust_panic_with_hook
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\panicking.rs:511
  10: std::panicking::begin_panic_handler
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\panicking.rs:419
  11: std::panicking::begin_panic_fmt
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\panicking.rs:373
  12: wgpu::backend::direct::{{impl}}::unwrap_pretty::{{closure}}<(),wgpu_core::device::queue::QueueWriteError>
             at C:\Users\dinne\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.6.0\src\backend\direct.rs:1323
  13: core::result::Result<(), wgpu_core::device::queue::QueueWriteError>::unwrap_or_else<(),wgpu_core::device::queue::QueueWriteError,closure-0>
             at C:\Users\dinne\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\result.rs:853
  14: wgpu::backend::direct::{{impl}}::unwrap_pretty<(),wgpu_core::device::queue::QueueWriteError>
             at C:\Users\dinne\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.6.0\src\backend\direct.rs:1323
  15: wgpu::backend::direct::{{impl}}::queue_write_texture
             at C:\Users\dinne\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.6.0\src\backend\direct.rs:1286
  16: wgpu::Queue::write_texture
             at C:\Users\dinne\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.6.0\src\lib.rs:2497
  17: ruffle_render_wgpu::WgpuRenderBackend<ruffle_render_wgpu::target::SwapChainTarget>::register_bitmap<ruffle_render_wgpu::target::SwapChainTarget>
             at W:\personal\ruffle\render\wgpu\src\lib.rs:671
  18: ruffle_render_wgpu::{{impl}}::register_bitmap_jpeg_2<ruffle_render_wgpu::target::SwapChainTarget>
             at W:\personal\ruffle\render\wgpu\src\lib.rs:899
  19: ruffle_core::display_object::movie_clip::MovieClipData::define_bits_jpeg_2
             at W:\personal\ruffle\core\src\display_object\movie_clip.rs:1797
  20: ruffle_core::display_object::movie_clip::{{impl}}::preload::{{closure}}
             at W:\personal\ruffle\core\src\display_object\movie_clip.rs:166
  21: ruffle_core::tag_utils::decode_tags<slice<u8>*,closure-0>
             at W:\personal\ruffle\core\src\tag_utils.rs:285
  22: ruffle_core::display_object::movie_clip::MovieClip::preload
             at W:\personal\ruffle\core\src\display_object\movie_clip.rs:351
  23: ruffle_core::player::{{impl}}::preload::{{closure}}
             at W:\personal\ruffle\core\src\player.rs:762
  24: ruffle_core::player::{{impl}}::mutate_with_update_context::{{closure}}<closure-0,()>
             at W:\personal\ruffle\core\src\player.rs:1115
  25: ruffle_core::player::GcArena::mutate<closure-0,()>
             at C:\Users\dinne\.cargo\registry\src\github.com-1ecc6299db9ec823\gc-arena-0.2.0\src\arena.rs:161
  26: ruffle_core::player::Player::mutate_with_update_context<closure-0,()>
             at W:\personal\ruffle\core\src\player.rs:1062
  27: ruffle_core::player::Player::preload
             at W:\personal\ruffle\core\src\player.rs:759
  28: ruffle_core::player::Player::set_root_movie
             at W:\personal\ruffle\core\src\player.rs:382
  29: ruffle_desktop::run_player
             at .\src\main.rs:181
  30: ruffle_desktop::main
```

Example movies:
- [JACK Arc 1-2 Fixed](https://www.newgrounds.com/portal/view/270058?emulate=flash) (NSFW)
- [Tasty Planet](https://www.newgrounds.com/portal/view/561194?emulate=flash)
- [Hunger for Banana](https://www.newgrounds.com/portal/view/636069?emulate=flash)

**Comment by Herschel** [comment]
Looks like these are using grayscale/CMYK color formats in JPEG.

**Comment by torokati44** [comment]
Looks like at least the JPEG part got fixed by https://github.com/ruffle-rs/ruffle/pull/2895 and https://github.com/ruffle-rs/ruffle/pull/6595. :)
Two of the movies still don't work though, as they are AVM2 ones.
