### ISSUE TITLE
Error on https://www.jeuxclic.com/jeux.php

### ISSUE THREAD

**Issue by annemayo** [ruffle-rs/ruffle#11925]
# Error Info
Error name: Error
Error message: panicked at 'No script object for display object', core/src/avm1/activation.rs:396:18
Error stack:
```
Error: panicked at 'No script object for display object', core/src/avm1/activation.rs:396:18
    at U.n.wbg.__wbg_new_15d3966e9981a196 (https://www.jeuxclic.com/include/p_jeux/ruffle/core.ruffle.828c823147b3e01419a0.js:1:47866)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h0312d4caddbaee90 (wasm://wasm/02a8438a:wasm-function[8041]:0x7f70c8)
    at std::panicking::rust_panic_with_hook::h8d0a63d0479a36c8 (wasm://wasm/02a8438a:wasm-function[5353]:0x72d280)
    at core::panicking::panic_fmt::h2a7f454a5f5da218 (wasm://wasm/02a8438a:wasm-function[7921]:0x7f23f2)
    at ruffle_core::display_object::edit_text::EditText::try_bind_text_field_variable::h9c5fbbbb126491b9 (wasm://wasm/02a8438a:wasm-function[3706]:0x68392c)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::he4a116ef9010da52 (wasm://wasm/02a8438a:wasm-function[3069]:0x604073)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::hd244d6ebb7358c42 (wasm://wasm/02a8438a:wasm-function[768]:0x28fda1)
    at ruffle_core::display_object::movie_clip::MovieClip::place_object::h97ffd21186ba2fdd (wasm://wasm/02a8438a:wasm-function[1560]:0x4352bf)
    at <ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::enter_frame::h57e3f4ff64f72aa1 (wasm://wasm/02a8438a:wasm-function[783]:0x29acd9)
    at <ruffle_core::display_object::loader_display::LoaderDisplay as ruffle_core::display_object::TDisplayObject>::enter_frame::he06e52605ff8f9e8 (wasm://wasm/02a8438a:wasm-function[3074]:0x607a6c)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://www.jeuxclic.com/jeux.php?id=1000219
SWF URL: https://www.jeuxclic.com/jeux/1000219-bleachvsna.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.51
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-03-19
Channel: nightly
Built: 2023-03-19T00:19:16.337Z
Commit: 5aac938e868e7dab2550d9482f754a6daf314921
Is extension: false

# Metadata
width: 600
height: 400
frameRate: 40
numFrames: 2
swfVersion: 10
backgroundColor: #FFFFFF
isActionScript3: true
uncompressedLength: 709050

**Comment by Lord-McSweeney** [comment]
This doesn't panic after #11005
