### ISSUE TITLE
Error on Ducateers Bling Bling Blaster

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#11932]
# Error Info
Error name: Error
Error message: panicked at 'No script object for display object', core/src/avm1/activation.rs:396:18
Error stack:
```
Error: panicked at 'No script object for display object', core/src/avm1/activation.rs:396:18
    at U.n.wbg.__wbg_new_d258248ed531ff54 (https://www.spiele-umsonst.de/ruffle/core.ruffle.dc92645d13601e80b33b.js:1:51428)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hc123de34c3ab8e83 (wasm://wasm/02d1711a:wasm-function[8764]:0x861256)
    at std::panicking::rust_panic_with_hook::h85b7f6628c291e12 (wasm://wasm/02d1711a:wasm-function[5753]:0x77c615)
    at core::panicking::panic_fmt::hf5c4cd929d4aaa9e (wasm://wasm/02d1711a:wasm-function[8625]:0x85cd6e)
    at ruffle_core::display_object::edit_text::EditText::try_bind_text_field_variable::h095ba6fa80ffe5d6 (wasm://wasm/02d1711a:wasm-function[3412]:0x658fe6)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::h430f360175c563f2 (wasm://wasm/02d1711a:wasm-function[3075]:0x61ba98)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::h4138991de9857d1f (wasm://wasm/02d1711a:wasm-function[867]:0x2dd1b3)
    at ruffle_core::display_object::movie_clip::MovieClip::place_object::hafab9b24c97a7016 (wasm://wasm/02d1711a:wasm-function[1385]:0x3f2b7d)
    at <ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::enter_frame::hc45165873d04f1c3 (wasm://wasm/02d1711a:wasm-function[795]:0x289e15)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::h4138991de9857d1f (wasm://wasm/02d1711a:wasm-function[867]:0x2dd1ee)
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) UHD Graphics 620 Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
SWF URL: https://www.spiele-umsonst.de/azad/downloads/flashgames/dukateersblingblingblaster.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-07-04
Channel: nightly
Built: 2023-07-04T00:20:28.931Z
Commit: c943866745281bad7f75fcc859ab7f2734385951
Is extension: false

# Metadata
width: 600
height: 460
frameRate: 35
numFrames: 2
swfVersion: 9
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 879262

**Comment by Lord-McSweeney** [comment]
This seems to be working now
