### ISSUE TITLE
Error on https://www.gamesflow.com/jeux.php

### ISSUE THREAD

**Issue by DavidJuny** [ruffle-rs/ruffle#11964]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:644:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:644:18
    at U.n.wbg.__wbg_new_15d3966e9981a196 (https://www.gamesflow.com/include/p_jeux/ruffle/core.ruffle.828c823147b3e01419a0.js:1:47866)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h0312d4caddbaee90 (wasm://wasm/02a8438a:wasm-function[8041]:0x7f70c8)
    at std::panicking::rust_panic_with_hook::h8d0a63d0479a36c8 (wasm://wasm/02a8438a:wasm-function[5353]:0x72d280)
    at core::panicking::panic_fmt::h2a7f454a5f5da218 (wasm://wasm/02a8438a:wasm-function[7921]:0x7f23f2)
    at core::panicking::panic::ha3ebcac1438d9280 (wasm://wasm/02a8438a:wasm-function[7335]:0x7be476)
    at ruffle_core::display_object::container::ChildContainer::replace_at_depth::h1988f3a12a2ddfbe (wasm://wasm/02a8438a:wasm-function[1281]:0x3c4e75)
    at ruffle_core::display_object::container::TDisplayObjectContainer::replace_at_depth::h7782dd22b5767442 (wasm://wasm/02a8438a:wasm-function[4823]:0x702719)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::hd244d6ebb7358c42 (wasm://wasm/02a8438a:wasm-function[768]:0x28ea12)
    at ruffle_core::display_object::movie_clip::MovieClip::run_goto::{{closure}}::hb116f6084cffb519 (wasm://wasm/02a8438a:wasm-function[870]:0x2e7fca)
    at ruffle_core::display_object::movie_clip::MovieClip::run_goto::hca3887f318a8683a (wasm://wasm/02a8438a:wasm-function[671]:0x22722a)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://www.gamesflow.com/jeux.php?id=2206048
SWF URL: https://www.gamesflow.com/jeux/5478ed5487102.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-03-19
Channel: nightly
Built: 2023-03-19T00:19:16.337Z
Commit: 5aac938e868e7dab2550d9482f754a6daf314921
Is extension: false

# Metadata
width: 660
height: 485
frameRate: 34
numFrames: 45
swfVersion: 12
backgroundColor: #111111
isActionScript3: false
uncompressedLength: 41140291

**Comment by kjarosh** [comment]
Fixed by https://github.com/ruffle-rs/ruffle/pull/10362
