### ISSUE TITLE
Error on https://kdata1.com/games/SSF22/

### ISSUE THREAD

**Issue by Brandonjackso** [ruffle-rs/ruffle#12093]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/library.rs:348:26
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/library.rs:348:26
    at imports.wbg.__wbg_new_d258248ed531ff54 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/159.js:2426:21)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h6ef40e3717251c02 (<anonymous>:wasm-function[9038]:0x90d310)
    at std::panicking::rust_panic_with_hook::h5cee2a9564faeb6d (<anonymous>:wasm-function[5965]:0x80a9a9)
    at core::panicking::panic_fmt::h8a19fa1eb63fbb67 (<anonymous>:wasm-function[8889]:0x9087c1)
    at core::panicking::panic::h42080e1e32ba4b73 (<anonymous>:wasm-function[8533]:0x8f5a71)
    at ruffle_core::display_object::movie_clip::MovieClip::preload::h0b9f96de5a57a809 (<anonymous>:wasm-function[662]:0x1f35e3)
    at ruffle_core::loader::Loader::preload_tick::h6200c892b8d58bc9 (<anonymous>:wasm-function[1620]:0x491b0d)
    at ruffle_web::Ruffle::tick::hb0c11c442422f4f4 (<anonymous>:wasm-function[737]:0x255e73)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h3d1e4510e6b9c799 (<anonymous>:wasm-function[10689]:0x943cde)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hceb40709914c01ae (<anonymous>:wasm-function[9660]:0x92873f)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "Mesa DRI Intel(R) HD Graphics (BYT)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_COMPRESSION_ETC2 | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 640, height: 480, depth_or_array_layers: 1 }
Player type: Object
SWF URL: game.swf
Param movie: game.swf
Param wmode: direct
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined

# Page Info
Page URL: https://kdata1.com/games/SSF22/
SWF URL: https://kdata1.com/games/SSF22/game.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14092.77.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.107 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-07-15
Channel: nightly
Built: 2023-07-15T00:22:32.222Z
Commit: ee7412d73396824392f6a08bbd4f9276c013cba5
Is extension: true

# Metadata
width: 800
height: 800
frameRate: 24
numFrames: 1
swfVersion: 8
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 10342

**Comment by Lord-McSweeney** [comment]
This seems to be working now
