### ISSUE TITLE
Error on https://ruffle.rs/demo/

### ISSUE THREAD

**Issue by MSSBGC** [ruffle-rs/ruffle#12097]
# Error Info
Error name: Error
Error message: panicked at 'Unimplemented opcode LessThanEqual', render/naga-pixelbender/src/lib.rs:1305:29
Error stack:
```
Error: panicked at 'Unimplemented opcode LessThanEqual', render/naga-pixelbender/src/lib.rs:1305:29
    at O.n.wbg.__wbg_new_d258248ed531ff54 (https://ruffle.rs/demo/339.index.js:1:51515)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h52ffccac2d79ee27 (wasm://wasm/02efd33e:wasm-function[9063]:0x8c8387)
    at std::panicking::rust_panic_with_hook::h5cee2a9564faeb6d (wasm://wasm/02efd33e:wasm-function[5938]:0x7cad85)
    at core::panicking::panic_fmt::h8a19fa1eb63fbb67 (wasm://wasm/02efd33e:wasm-function[8901]:0x8c376b)
    at <ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::compile_pixelbender_shader::h7b4240e11b663786 (wasm://wasm/02efd33e:wasm-function[7140]:0x83af64)
    at ruffle_core::avm2::globals::flash::display::shader_data::init::hf41ee384b0050ed3 (wasm://wasm/02efd33e:wasm-function[1154]:0x3952b6)
    at ruffle_core::avm2::function::Executable::exec::h1346d0442e27c444 (wasm://wasm/02efd33e:wasm-function[815]:0x299463)
    at ruffle_core::avm2::object::TObject::call_property::hcc0b4846db98cc55 (wasm://wasm/02efd33e:wasm-function[1088]:0x36fc96)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::h1750ce5d77c26140 (wasm://wasm/02efd33e:wasm-function[2779]:0x5f933e)
    at ruffle_core::avm2::activation::Activation::run_actions::h871cacfbb644e09b (wasm://wasm/02efd33e:wasm-function[518]:0x2a1f1)
```
AVM2 stack:
```
    at flash.display::ShaderData/flash::display::ShaderData::init()
    at flash.display::ShaderData()
    at flash.display::Shader/set byteCode()
    at flash.display::Shader()
    at filters::FilterPack()
    at scratchplayer::ScratchSprite/setEmptyStage()
    at scratchplayer::StageArea/emptyProject()
    at Scratch()
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (AMD, AMD Radeon (TM) Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://ruffle.rs/demo/

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Platform: Win32
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-07-16
Channel: nightly
Built: 2023-07-16T00:23:27.657Z
Commit: cd2d01bf6f2565e1aa442da671ca7e27ed186629
Is extension: false

# Metadata
width: 1000
height: 630
frameRate: 24
numFrames: 1
swfVersion: 10
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 446286

**Comment by Lord-McSweeney** [comment]
Fixed by #12194
