### ISSUE TITLE
Error on https://www.minijuegos.com/helpers/game/sandbox.php

### ISSUE THREAD

**Issue by pericosoos** [ruffle-rs/ruffle#12165]
# Error Info
Error name: Error
Error message: panicked at 'No script object for display object', core/src/avm1/activation.rs:404:18
Error stack:
```
Error: panicked at 'No script object for display object', core/src/avm1/activation.rs:404:18
    at W.n.wbg.__wbg_new_d258248ed531ff54 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.aab2b3501e3c0fcaac35.js:1:51547)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hb515a2c9ffd29eb6 (wasm://wasm/02eff92e:wasm-function[9059]:0x8c8013)
    at std::panicking::rust_panic_with_hook::h5cee2a9564faeb6d (wasm://wasm/02eff92e:wasm-function[5924]:0x7c9eac)
    at core::panicking::panic_fmt::h8a19fa1eb63fbb67 (wasm://wasm/02eff92e:wasm-function[8903]:0x8c34f4)
    at ruffle_core::display_object::edit_text::EditText::try_bind_text_field_variable::hf7c5e136f19e62a3 (wasm://wasm/02eff92e:wasm-function[3569]:0x687ca0)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::h66b7dbfdbf7630dc (wasm://wasm/02eff92e:wasm-function[3026]:0x626e99)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::h749f8e6a94272341 (wasm://wasm/02eff92e:wasm-function[1036]:0x34fd8d)
    at ruffle_core::display_object::movie_clip::MovieClip::place_object::hd84173e9af2dd7db (wasm://wasm/02eff92e:wasm-function[1850]:0x4dbe48)
    at <ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::enter_frame::he1d750b6abb09a42 (wasm://wasm/02eff92e:wasm-function[819]:0x29e29b)
    at <ruffle_core::display_object::loader_display::LoaderDisplay as ruffle_core::display_object::TDisplayObject>::enter_frame::h1ac4ef52b6d70c52 (wasm://wasm/02eff92e:wasm-function[2519]:0x5a6673)
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (AMD, AMD Radeon(TM) RX Vega 11 Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 630, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://www.minijuegos.com/helpers/game/sandbox.php?mp_assets=https%3A%2F%2Fs2.minijuegosgratis.com%2F&mp_embed=0&mp_game_id=11627&mp_game_uid=impossible&mp_game_url=https%3A%2F%2Fwww.minijuegos.com%2Fembed%2Fimpossible&mp_int=1&mp_locale=es_ES&mp_player_type=FLASH&mp_player_url=aHR0cHM6Ly93d3cubWluaWp1ZWdvc2dyYXRpcy5jb20vZmxhc2gxMjM0L25vX2hvdGxpbmsvaW1wb3NzaWJsZS5zd2Y%3D&mp_site_https_url=https%3A%2F%2Fwww.minijuegos.com%2F&mp_site_name=minijuegos.com&mp_site_url=https%3A%2F%2Fwww.minijuegos.com%2F&mp_timezone=Europe%2FMadrid&mp_view_type=
SWF URL: https://www.minijuegosgratis.com/flash1234/no_hotlink/impossible.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-07-19
Channel: nightly
Built: 2023-07-19T00:19:35.462Z
Commit: 0fa16dfe6994a6bd6ed1106acb88203c135268f7
Is extension: false

# Metadata
width: 550
height: 400
frameRate: 30
numFrames: 2
swfVersion: 9
backgroundColor: #FFFFFF
isActionScript3: true
uncompressedLength: 2558638

**Comment by Lord-McSweeney** [comment]
This seems to be working now
