### ISSUE TITLE
Error on https://www.surfertoday.com/games/surf-dude

### ISSUE THREAD

**Issue by ghost** [ruffle-rs/ruffle#12224]
# Error Info
Error name: Error
Error message: panicked at 'No script object for display object', core/src/avm1/activation.rs:396:18
Error stack:
```
Error: panicked at 'No script object for display object', core/src/avm1/activation.rs:396:18
    at W.n.wbg.__wbg_new_87297f22973157c8 (https://www.surfertoday.com/templates/surfertoday/js/ruffle/core.ruffle.aeaca10e31ad891978a3.js:1:50966)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hafc7beb469c6cb04 (wasm://wasm/02c3cb9a:wasm-function[8617]:0x8309af)
    at std::panicking::rust_panic_with_hook::h7f7102b82d51338f (wasm://wasm/02c3cb9a:wasm-function[5612]:0x753a1a)
    at core::panicking::panic_fmt::he4489d678d6570d5 (wasm://wasm/02c3cb9a:wasm-function[8466]:0x82bd1c)
    at ruffle_core::display_object::edit_text::EditText::try_bind_text_field_variable::hf914e5172417f935 (wasm://wasm/02c3cb9a:wasm-function[3368]:0x644fb8)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::ha627f066e0df8c58 (wasm://wasm/02c3cb9a:wasm-function[2911]:0x5e7b41)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::h30f32f2393e933dc (wasm://wasm/02c3cb9a:wasm-function[814]:0x2948ca)
    at ruffle_core::display_object::movie_clip::MovieClip::place_object::hf0ddbf722d78835e (wasm://wasm/02c3cb9a:wasm-function[1615]:0x45b328)
    at <ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::enter_frame::h60deeb2eb7eb5357 (wasm://wasm/02c3cb9a:wasm-function[823]:0x2a43c4)
    at <ruffle_core::display_object::loader_display::LoaderDisplay as ruffle_core::display_object::TDisplayObject>::enter_frame::h3edd1b42eb5012bf (wasm://wasm/02c3cb9a:wasm-function[3103]:0x615655)
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA T1000 8GB Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://www.surfertoday.com/games/surf-dude
SWF URL: https://www.surfertoday.com/game-files/surf-dude.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-05-24
Channel: nightly
Built: 2023-05-24T00:22:28.395Z
Commit: 358beabf5a49807bafd0122a73ff62514ceb4b9a
Is extension: false

# Metadata
width: 680
height: 460
frameRate: 22
numFrames: 2
swfVersion: 10
backgroundColor: #99CCCC
isActionScript3: true
uncompressedLength: 184944

**Comment by n0samu** [comment]
This has been fixed for a while
