### ISSUE TITLE
Error on https://www.miniplay.com/helpers/game/sandbox.php

### ISSUE THREAD

**Issue by nguyetdi** [ruffle-rs/ruffle#12227]
# Error Info
Error name: Error
Error message: panicked at 'Missing method for id 8', core/src/avm2/globals/flash/utils.rs:430:44
Error stack:
```
Error: panicked at 'Missing method for id 8', core/src/avm2/globals/flash/utils.rs:430:44
    at W.n.wbg.__wbg_new_d258248ed531ff54 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.910932826a9e894fa2ba.js:1:51547)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hb515a2c9ffd29eb6 (wasm://wasm/02f2fb6e:wasm-function[9095]:0x8d153a)
    at std::panicking::rust_panic_with_hook::h5cee2a9564faeb6d (wasm://wasm/02f2fb6e:wasm-function[5945]:0x7d3756)
    at core::panicking::panic_fmt::h8a19fa1eb63fbb67 (wasm://wasm/02f2fb6e:wasm-function[8939]:0x8cca49)
    at ruffle_core::avm2::globals::flash::utils::describe_internal_body::h2467e80d75c10e5c (wasm://wasm/02f2fb6e:wasm-function[583]:0x145eb0)
    at ruffle_core::avm2::globals::flash::utils::describe_type::h133663ff43554f17 (wasm://wasm/02f2fb6e:wasm-function[1017]:0x33e276)
    at ruffle_core::avm2::function::Executable::exec::h70afbd0b721055f5 (wasm://wasm/02f2fb6e:wasm-function[822]:0x2a3f53)
    at ruffle_core::avm2::object::TObject::call_property::h8b0fb9294ce532a8 (wasm://wasm/02f2fb6e:wasm-function[1116]:0x382389)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::hdd0c032051093e63 (wasm://wasm/02f2fb6e:wasm-function[2768]:0x5f58e7)
    at ruffle_core::avm2::activation::Activation::run_actions::h82da41ed664c205b (wasm://wasm/02f2fb6e:wasm-function[517]:0x2a013)
```
AVM2 stack:
```
    at global/flash.utils::describeType()
    at com.lachhhEngine.multilingual::TextFactory/BuildTextDictFromClass()
    at com.lachhhEngine.multilingual::TextFactory/BuildTextDict()
    at com.lachhhEngine.multilingual::TextFactory/Init()
    at com.lachhhEngine.multilingual::TextFactory$/CreateInstance()
    at com.homerun::Main/CreateManagers()
    at com.lachhhEngine.games::MainGame/Init()
    at com.homerun::Main/Init()
    at com.lachhhEngine.initializers::Initializer/StartMain()
    at com.lachhhEngine.initializers::Initializer/PreloaderEnded()
    at Function/apply()
    at com.lachhhEngine.io::Callback/DoCallback()
    at com.lachhhEngine.initializers.preloader::NextPlayPreloader/Close()
    at com.lachhhEngine.initializers.preloader::NextPlayPreloader/onEnterFrame()
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) Iris(R) Xe Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 875, height: 687, depth_or_array_layers: 1 }

# Page Info
Page URL: https://www.miniplay.com/helpers/game/sandbox.php?mp_assets=https%3A%2F%2Fs2.minijuegosgratis.com%2F&mp_embed=0&mp_game_id=16883&mp_game_uid=berzerk-ball&mp_game_url=https%3A%2F%2Fwww.miniplay.com%2Fembed%2Fberzerk-ball&mp_int=1&mp_locale=en_US&mp_player_type=FLASH&mp_player_url=aHR0cHM6Ly93d3cubWluaWp1ZWdvc2dyYXRpcy5jb20vZmxhc2gxMjM0L25vX2hvdGxpbmsvYmVyemVya2JhbGwuc3dm&mp_site_https_url=https%3A%2F%2Fwww.miniplay.com%2F&mp_site_name=miniplay.com&mp_site_url=https%3A%2F%2Fwww.miniplay.com%2F&mp_timezone=Europe%2FMadrid&mp_view_type=
SWF URL: https://www.minijuegosgratis.com/flash1234/no_hotlink/berzerkball.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-07-22
Channel: nightly
Built: 2023-07-22T00:19:38.712Z
Commit: 77c0dac64be338500e8dbba1d8ad37d13a10cb5b
Is extension: false

# Metadata
width: 700
height: 550
frameRate: 50
numFrames: 2
swfVersion: 10
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 7886031

**Comment by Lord-McSweeney** [comment]
This is a regression caused by [#12105](https://github.com/ruffle-rs/ruffle/pull/12105). @Aaron1011, pinging you as the author of the PR that caused the regression.

**Comment by Lord-McSweeney** [comment]
Looking at the code, this seems to mean that one of the superclass's VTable properties were not present on a subclass's VTable properties, which...should be impossible?

**Comment by Lord-McSweeney** [comment]
This no longer panics (but it's stuck on playerglobal versioning now).
