### ISSUE TITLE
Error on https://frivold.menu/public/files/mini-dash

### ISSUE THREAD

**Issue by VaanillLA** [ruffle-rs/ruffle#12284]
# Error Info
Error name: Error
Error message: panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:524:5
Error stack:
```
Error: panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:524:5
    at W.n.wbg.__wbg_new_d258248ed531ff54 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.8239f37515825dae254b.js:1:51449)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hb515a2c9ffd29eb6 (wasm://wasm/02f80c2e:wasm-function[9161]:0x8e27ed)
    at std::panicking::rust_panic_with_hook::h5cee2a9564faeb6d (wasm://wasm/02f80c2e:wasm-function[6022]:0x7f07b2)
    at core::panicking::panic_fmt::h8a19fa1eb63fbb67 (wasm://wasm/02f80c2e:wasm-function[9005]:0x8de1a7)
    at alloc::raw_vec::capacity_overflow::hd69aa0483dc8b564 (wasm://wasm/02f80c2e:wasm-function[9004]:0x8de0b7)
    at alloc::raw_vec::RawVec<T,A>::reserve::do_reserve_and_handle::h6d1bf7efee7eb61d (wasm://wasm/02f80c2e:wasm-function[5898]:0x7e40ba)
    at ruffle_core::avm2::globals::flash::utils::byte_array::set_length::h4bd105e9fdebdd97 (wasm://wasm/02f80c2e:wasm-function[3358]:0x67fd62)
    at ruffle_core::avm2::function::Executable::exec::hf76317149d93a358 (wasm://wasm/02f80c2e:wasm-function[833]:0x2be6c1)
    at ruffle_core::avm2::object::TObject::call_method::h59e02cdf22bc7f2d (wasm://wasm/02f80c2e:wasm-function[2003]:0x52861e)
    at ruffle_core::avm2::object::TObject::set_property::h331d5b76e4a4393e (wasm://wasm/02f80c2e:wasm-function[2306]:0x5836d3)
```
AVM2 stack:
```
    at flash.utils::ByteArray/flash::utils::ByteArray::length()
    at global/F_avm2_casRamLength()
    at global/F___sys_mmap()
    at global/F_mmap()
    at global/F_pages_map()
    at global/F_base_pages_alloc()
    at global/F_base_alloc()
    at global/F_arenas_extend()
    at global/F_malloc_init()
    at global/F_malloc()
    at global/F__Znwj()
    at global/F__Z16CreateGameObjectv()
    at global/F_main()
    at global/F__start1()
    at com.adobe.flascc::CModule$/callI()
    at com.adobe.flascc::CModule$/start()
    at com.adobe.flascc::CModule$/startAsync()
    at com.adobe.flascc::Console/enterFrame()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (AMD, AMD Radeon(TM) Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://frivold.menu/public/files/mini-dash
SWF URL: https://frivold.menu/public/storage/games/November2021/QD21VEcY10LnXC2ISIAK.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-07-24
Channel: nightly
Built: 2023-07-24T00:19:57.431Z
Commit: cd9efb2dfa8a8e034bd6a1bd65df099d9f4b8bba
Is extension: false

# Metadata
width: 800
height: 533
frameRate: 0.1171875
numFrames: 1
swfVersion: 18
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 20666034

**Comment by Lord-McSweeney** [comment]
Closing in favor of https://github.com/ruffle-rs/ruffle/issues/10851
