### ISSUE TITLE
Error on https://homestuck.giovanh.com/unlock/PS_titlescreen

### ISSUE THREAD

**Issue by illusoryMechanist** [ruffle-rs/ruffle#12283]
### Describe what you were doing

Was attempting to load the flash file: https://filedn.com/lANSiYhDVpD4ou6Gt17Ij9m/AssetPackV2Lite/extras/PS_titlescreen/PS_titlescreen.swf on https://homestuck.giovanh.com/unlock/PS_titlescreen

Running it in a different browser tab worked.

### What does the crash message say?

# Error Info
Error name: Error
Error message: Failed to fetch: https://filedn.com/lANSiYhDVpD4ou6Gt17Ij9m/AssetPackV2Lite/extras/PS_titlescreen/PS_titlescreen.swf
Error stack:
```
Error: Failed to fetch: https://filedn.com/lANSiYhDVpD4ou6Gt17Ij9m/AssetPackV2Lite/extras/PS_titlescreen/PS_titlescreen.swf
    at Je.displayRootMovieDownloadFailedMessage (https://unpkg.com/@ruffle-rs/ruffle:2:356109)
    at W.n.wbg.__wbg_displayRootMovieDownloadFailedMessage_ed4ad3ae9522c8a3 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.8239f37515825dae254b.js:1:7014)
    at <ruffle_web::ui::WebUiBackend as ruffle_core::backend::ui::UiBackend>::display_root_movie_download_failed_message::h5ee9a750b1daad2e (wasm://wasm/02f80c2e:wasm-function[10961]:0x922178)
    at ruffle_core::loader::Loader::root_movie_loader::{{closure}}::ha37b847f65ab7606 (wasm://wasm/02f80c2e:wasm-function[870]:0x2ea7f8)
    at <ruffle_web::navigator::WebNavigatorBackend as ruffle_core::backend::navigator::NavigatorBackend>::spawn_future::{{closure}}::hfce1b9e19541fd3e (wasm://wasm/02f80c2e:wasm-function[1124]:0x38b5c5)
    at wasm_bindgen_futures::queue::Queue::new::{{closure}}::h24708fe6d333ca4f (wasm://wasm/02f80c2e:wasm-function[3900]:0x6db6ee)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hafb4a535e559ce5b (wasm://wasm/02f80c2e:wasm-function[9825]:0x8fff0b)
    at closure4145 externref shim (wasm://wasm/02f80c2e:wasm-function[10138]:0x9052ed)
    at D (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.8239f37515825dae254b.js:1:2985)
    at f (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.8239f37515825dae254b.js:1:2511)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "Adreno (TM) 650"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | TEXTURE_COMPRESSION_ASTC_HDR | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 4096, max_texture_dimension_2d: 4096, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }
Player type: Object
SWF URL: https://filedn.com/lANSiYhDVpD4ou6Gt17Ij9m/AssetPackV2Lite/extras/PS_titlescreen/PS_titlescreen.swf
Param movie: https://filedn.com/lANSiYhDVpD4ou6Gt17Ij9m/AssetPackV2Lite/extras/PS_titlescreen/PS_titlescreen.swf
Param play: true
Param loop: true
Param quality: high
Param bgcolor: #fff
Param devicefont: false
Param allowScriptAccess: always
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined

# Page Info
Page URL: about:srcdoc
SWF URL: https://filedn.com/lANSiYhDVpD4ou6Gt17Ij9m/AssetPackV2Lite/extras/PS_titlescreen/PS_titlescreen.swf

# Browser Info
User Agent: Mozilla/5.0 (Linux; Android 13; SM-N986U1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Mobile Safari/537.36
Platform: Linux aarch64
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-07-24
Channel: nightly
Built: 2023-07-24T00:19:57.431Z
Commit: cd9efb2dfa8a8e034bd6a1bd65df099d9f4b8bba
Is extension: false

# Metadata

### Ruffle Version

Ruffle extension nightly 2023-07-24

### Affected platform

Browser's extension

### Operating system

Android 13

### Additional information

Using Kiwi browser to run extension on mobile. Site also independently uses Ruffle.

**Comment by GiovanH** [comment]
I don't think this is an error with ruffle, I think it's an issue with the site. `https://filedn.com/lANSiYhDVpD4ou6Gt17Ij9m/AssetPackV2Lite/extras/PS_titlescreen/PS_titlescreen.swf` is being blocked by CORS. I'm not sure why you're getting an obtuse error instead of it saying that.
