### ISSUE TITLE
Error on https://game94229.konggames.com/games/Ninjadoodle/clickplay-2/frame/e69839fd-6695-4bf0-a436-6de37e89df73/

### ISSUE THREAD

**Issue by Ilbko** [ruffle-rs/ruffle#12411]
# Error Info
Error name: Error
Error message: panicked at 'No script object for display object', core/src/avm1/activation.rs:404:18
Error stack:
```
Error: panicked at 'No script object for display object', core/src/avm1/activation.rs:404:18
    at W.n.wbg.__wbg_new_d258248ed531ff54 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.c34e368c32c8fb766c63.js:1:51449)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h0e63761b8083e365 (wasm://wasm/02facdf2:wasm-function[9182]:0x8ebfe1)
    at std::panicking::rust_panic_with_hook::h5cee2a9564faeb6d (wasm://wasm/02facdf2:wasm-function[6045]:0x7fab73)
    at core::panicking::panic_fmt::h8a19fa1eb63fbb67 (wasm://wasm/02facdf2:wasm-function[9026]:0x8e799b)
    at ruffle_core::display_object::edit_text::EditText::try_bind_text_field_variable::h3d2446bffed486b2 (wasm://wasm/02facdf2:wasm-function[3795]:0x6d6ce9)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::h5264a7ddc8a5f2c6 (wasm://wasm/02facdf2:wasm-function[3232]:0x67a979)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::h6f82c0646e121c5c (wasm://wasm/02facdf2:wasm-function[1049]:0x362c2a)
    at ruffle_core::display_object::movie_clip::MovieClip::place_object::h76e07ad057cc12c2 (wasm://wasm/02facdf2:wasm-function[1881]:0x50bae5)
    at <ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::enter_frame::h396627410674d50e (wasm://wasm/02facdf2:wasm-function[823]:0x2b21a0)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::h6f82c0646e121c5c (wasm://wasm/02facdf2:wasm-function[1049]:0x362c66)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (AMD, AMD Radeon(TM) Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://game94229.konggames.com/games/Ninjadoodle/clickplay-2/frame/e69839fd-6695-4bf0-a436-6de37e89df73/?kongregate_host=www.kongregate.com
SWF URL: https://game94229.konggames.com/gamez/0009/4229/live/clickplay2.swf?kongregate_game_version=1287111044

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 OPR/100.0.0.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-07-29
Channel: nightly
Built: 2023-07-29T00:19:39.173Z
Commit: 82b88ebff59f7992eeb4d10a18dec28d8714d338
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 60
numFrames: 2
swfVersion: 10
backgroundColor: #CCCCCC
isActionScript3: true
uncompressedLength: 2269426

**Comment by jacobgkau** [comment]
Still getting this when trying to play ClickPlay 2 with the current nightly (`2023-09-08`).

<details>
<summary>Auto-generated report:</summary>

# Error Info
Error name: Error
Error message: panicked at 'No script object for display object', core/src/avm1/activation.rs:404:18
Error stack:
```
Error: panicked at 'No script object for display object', core/src/avm1/activation.rs:404:18
    at V.n.wbg.__wbg_new_d258248ed531ff54 (https://jkthesite.com/flash/ruffle/core.ruffle.d7aa3f1b78bee47b8cf0.js:1:51843)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h2e7c106a4724653e (wasm://wasm/030bd5e2:wasm-function[9339]:0x925e3a)
    at std::panicking::rust_panic_with_hook::h7601402c0a383194 (wasm://wasm/030bd5e2:wasm-function[6090]:0x824e15)
    at core::panicking::panic_fmt::h6dad0405f48e39e2 (wasm://wasm/030bd5e2:wasm-function[9175]:0x92141e)
    at ruffle_core::display_object::edit_text::EditText::try_bind_text_field_variable::he5173faae2d59382 (wasm://wasm/030bd5e2:wasm-function[3216]:0x682ed4)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::h4ee4dd0593be2e39 (wasm://wasm/030bd5e2:wasm-function[3132]:0x6706ee)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::h1ef5ab08462851ca (wasm://wasm/030bd5e2:wasm-function[1053]:0x36914c)
    at ruffle_core::display_object::movie_clip::MovieClip::place_object::h097d7ee698c3efb7 (wasm://wasm/030bd5e2:wasm-function[1897]:0x51da3e)
    at <ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::enter_frame::h883c60417fe7424b (wasm://wasm/030bd5e2:wasm-function[804]:0x2a6ec5)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::h1ef5ab08462851ca (wasm://wasm/030bd5e2:wasm-function[1053]:0x369188)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Google, Vulkan 1.3.0 (SwiftShader Device (Subzero) (0x0000C0DE)), SwiftShader driver)"
Adapter Device Type: Cpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 8192, max_texture_dimension_2d: 8192, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://jkthesite.com/Games/gamesp8CP2.htm
SWF URL: https://jkthesite.com/flash/apps/onemorelevel/clickplay-2.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-09-08
Channel: nightly
Built: 2023-09-08T00:23:38.879Z
Commit: a3e0a84a3d3b8618c45cf8b652e3340328dc5a12
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 60
numFrames: 2
swfVersion: 10
backgroundColor: #CCCCCC
isActionScript3: true
uncompressedLength: 2269422
</details>

**Comment by Lord-McSweeney** [comment]
This seems to be working now

**Comment by jacobgkau** [comment]
Confirmed at least for my case, ClickPlay 2 is working with the `2025_09_17` nightly!
