### ISSUE TITLE
Error on http://www.hackedfreegames.com/game/6047/loot-heroes

### ISSUE THREAD

**Issue by alariceeeeee** [ruffle-rs/ruffle#12487]
# Error Info
Error name: Error
Error message: panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:525:5
Error stack:
```
Error: panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:525:5
    at W.n.wbg.__wbg_new_87297f22973157c8 (http://www.hackedfreegames.com/applications/gameportal/js/ruffle-nightly-2023_05_24-web-selfhosted/core.ruffle.aeaca10e31ad891978a3.js:1:50966)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hafc7beb469c6cb04 (wasm://wasm/02c3cb9a:wasm-function[8617]:0x8309af)
    at std::panicking::rust_panic_with_hook::h7f7102b82d51338f (wasm://wasm/02c3cb9a:wasm-function[5612]:0x753a1a)
    at core::panicking::panic_fmt::he4489d678d6570d5 (wasm://wasm/02c3cb9a:wasm-function[8466]:0x82bd1c)
    at alloc::raw_vec::capacity_overflow::h743526e95bf6b28b (wasm://wasm/02c3cb9a:wasm-function[8233]:0x825bd0)
    at alloc::raw_vec::RawVec<T,A>::reserve::do_reserve_and_handle::hd3d161acc95dba65 (wasm://wasm/02c3cb9a:wasm-function[5277]:0x73b865)
    at <ruffle_core::avm2::object::array_object::ArrayObject as ruffle_core::avm2::object::TObject>::set_property_local::h1e1da69ec1b0a718 (wasm://wasm/02c3cb9a:wasm-function[2340]:0x54677f)
    at ruffle_core::avm2::object::TObject::set_property::haf2d1640a0c85159 (wasm://wasm/02c3cb9a:wasm-function[2211]:0x524cce)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::set_property::h23583d31a705aa91 (wasm://wasm/02c3cb9a:wasm-function[1832]:0x4a6f18)
    at ruffle_core::avm2::activation::Activation::run_actions::h8571213dee4e97d8 (wasm://wasm/02c3cb9a:wasm-function[510]:0x3c164)
```
AVM2 stack:
```
    at universe::Universe/setChunk()
    at universe::Level$/load()
    at BackgroundBattle/start()
    at menu::Start()
    at menu::GameMenu$/goto()
    at Game/frame3()
    at flash.display::MovieClip/flash::display::MovieClip::gotoAndStop()
    at icons::Icon/setBackground()
    at icons::Icon()
    at icons::SkillIcon()
    at flash.display::DisplayObject/flash.display::DisplayObject()
    at flash.display::InteractiveObject/flash.display::InteractiveObject()
    at flash.display::DisplayObjectContainer/flash.display::DisplayObjectContainer()
    at flash.display::Sprite()
    at flash.display::MovieClip()
    at GameInterface()
    at flash.display::MovieClip/flash::display::MovieClip::nextFrame()
    at Dungeon_fla::Intro_33/frame160()
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "Mesa DRI Intel(R) HD Graphics 500 (APL 2)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | TEXTURE_COMPRESSION_ASTC_HDR | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: medium
Surface samples: 2
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: http://www.hackedfreegames.com/game/6047/loot-heroes
SWF URL: http://cache.hackedfreegames.com/uploads/games/files/831/JTJWSON0W8IE.swf?version=5

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-05-24
Channel: nightly
Built: 2023-05-24T00:22:28.395Z
Commit: 358beabf5a49807bafd0122a73ff62514ceb4b9a
Is extension: false

# Metadata
width: 800
height: 500
frameRate: 30
numFrames: 3
swfVersion: 10
backgroundColor: #009900
isActionScript3: true
uncompressedLength: 7959429

**Comment by Lord-McSweeney** [comment]
This seems to be working now
