### ISSUE TITLE
Error on https://www.minijogos.com.br/helpers/game/sandbox.php

### ISSUE THREAD

**Issue by simuacion** [ruffle-rs/ruffle#12497]
# Error Info
Error name: Error
Error message: panicked at 'No script object for display object', core/src/avm1/activation.rs:404:18
Error stack:
```
Error: panicked at 'No script object for display object', core/src/avm1/activation.rs:404:18
    at W.n.wbg.__wbg_new_d258248ed531ff54 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.92e6746d93be1e95cd77.js:1:51449)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h8b0b313a9b2fe55f (wasm://wasm/02f98346:wasm-function[9186]:0x8e70a7)
    at std::panicking::rust_panic_with_hook::h5cee2a9564faeb6d (wasm://wasm/02f98346:wasm-function[6037]:0x7f89a0)
    at core::panicking::panic_fmt::h8a19fa1eb63fbb67 (wasm://wasm/02f98346:wasm-function[9022]:0x8e28db)
    at ruffle_core::display_object::edit_text::EditText::try_bind_text_field_variable::hbc601c520fca1d9a (wasm://wasm/02f98346:wasm-function[3798]:0x6d8470)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::h915d8fe0eef04769 (wasm://wasm/02f98346:wasm-function[3233]:0x67b965)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::hca2c85aaf6295955 (wasm://wasm/02f98346:wasm-function[1045]:0x3618ed)
    at ruffle_core::display_object::movie_clip::MovieClip::place_object::h2a17ef3feef4597c (wasm://wasm/02f98346:wasm-function[1882]:0x50aedc)
    at <ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::enter_frame::hce8c2b09d85b3b06 (wasm://wasm/02f98346:wasm-function[817]:0x2aea27)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::hca2c85aaf6295955 (wasm://wasm/02f98346:wasm-function[1045]:0x361929)
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "Mesa DRI Intel(R) UHD Graphics 600 (GLK 2)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | TEXTURE_COMPRESSION_ASTC_HDR | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 800, height: 440, depth_or_array_layers: 1 }

# Page Info
Page URL: https://www.minijogos.com.br/helpers/game/sandbox.php?mp_assets=https%3A%2F%2Fs2.minijuegosgratis.com%2F&mp_embed=0&mp_game_id=19285&mp_game_uid=feed-us-2&mp_game_url=https%3A%2F%2Fwww.minijogos.com.br%2Fembed%2Ffeed-us-2&mp_int=1&mp_locale=pt_BR&mp_player_type=FLASH&mp_player_url=aHR0cHM6Ly93d3cubWluaWp1ZWdvc2dyYXRpcy5jb20vdjMvZ2FtZXMvZ2FtZXMvcHJvZC8xOTI4NS9mZWVkdXMyLnN3Zg%3D%3D&mp_site_https_url=https%3A%2F%2Fwww.minijogos.com.br%2F&mp_site_name=minijogos.com.br&mp_site_url=https%3A%2F%2Fwww.minijogos.com.br%2F&mp_timezone=America%2FSao_Paulo&mp_view_type=
SWF URL: https://www.minijuegosgratis.com/v3/games/games/prod/19285/feedus2.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-08-02
Channel: nightly
Built: 2023-08-02T00:22:54.390Z
Commit: 006393c5816e68b54c6720fcd8e657009cfb90d8
Is extension: false

# Metadata
width: 800
height: 440
frameRate: 50
numFrames: 2
swfVersion: 17
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 3524534

**Comment by Lord-McSweeney** [comment]
Was fixed by #11005
