### ISSUE TITLE
Error on https://ooooooooo.ooo/static/

### ISSUE THREAD

**Issue by zjk261** [ruffle-rs/ruffle#12543]
# Error Info
Error name: Error
Error message: panicked at 'index out of bounds: the len is 260 but the index is 260', render/src/utils.rs:303:33
Error stack:
```
Error: panicked at 'index out of bounds: the len is 260 but the index is 260', render/src/utils.rs:303:33
    at W.n.wbg.__wbg_new_d258248ed531ff54 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.18e89839c4257ed9f1ae.js:1:51449)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hd045a4c294d004d3 (wasm://wasm/02faf016:wasm-function[9213]:0x8eaa53)
    at std::panicking::rust_panic_with_hook::h6df5db7ad9f65dc8 (wasm://wasm/02faf016:wasm-function[6049]:0x7faa42)
    at core::panicking::panic_fmt::h2d3c5586175098d9 (wasm://wasm/02faf016:wasm-function[9057]:0x8e643b)
    at core::panicking::panic_bounds_check::hce207096b968561d (wasm://wasm/02faf016:wasm-function[7388]:0x868dd8)
    at ruffle_core::display_object::movie_clip::MovieClipData::define_bits_lossless::h00e502be06067ee0 (wasm://wasm/02faf016:wasm-function[3349]:0x68f405)
    at ruffle_core::display_object::movie_clip::MovieClip::preload::h216aec2620bf1294 (wasm://wasm/02faf016:wasm-function[663]:0x1ddede)
    at ruffle_core::display_object::movie_clip::MovieClip::preload::h216aec2620bf1294 (wasm://wasm/02faf016:wasm-function[663]:0x1dfd49)
    at ruffle_web::Ruffle::tick::h8fba5a4973e43f72 (wasm://wasm/02faf016:wasm-function[790]:0x284878)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::he098d3773fee7c4f (wasm://wasm/02faf016:wasm-function[11011]:0x929ed4)
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) Iris(R) Xe Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://ooooooooo.ooo/static/?4a11c628-6600-4f00-b8f8-a431d38485d9
SWF URL: http://media.flasharcade.com/flashgames/swf/flashgame_7997_mariozerogravity.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-08-04
Channel: nightly
Built: 2023-08-04T00:19:39.973Z
Commit: 5f200dc2a9fd992575c4bb5c49973f203cccf43a
Is extension: false

# Metadata
width: 550
height: 400
frameRate: 25
numFrames: 5
swfVersion: 6
backgroundColor: #009999
isActionScript3: false
uncompressedLength: 885930

**Comment by Lord-McSweeney** [comment]
This happens when the SWF lies about the width and height of a bitmap image (it says that they're higher than they actually are), so we try to read past the end of the SWF tag, which panics.
