### ISSUE TITLE
Make My Mcdonalds ....Error on https://ruffle-regressions.github.io/

### ISSUE THREAD

**Issue by olux997** [ruffle-rs/ruffle#12594]
# Error Info
Error name: Error
Error message: panicked at 'No script object for display object', core/src/avm1/activation.rs:404:18
Error stack:
```
Error: panicked at 'No script object for display object', core/src/avm1/activation.rs:404:18
    at W.n.wbg.__wbg_new_d258248ed531ff54 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.7df8d57dd988159db160.js:1:51449)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hd045a4c294d004d3 (wasm://wasm/02fc191e:wasm-function[9220]:0x8eea8f)
    at std::panicking::rust_panic_with_hook::h6df5db7ad9f65dc8 (wasm://wasm/02fc191e:wasm-function[6051]:0x7fc66b)
    at core::panicking::panic_fmt::h2d3c5586175098d9 (wasm://wasm/02fc191e:wasm-function[9064]:0x8ea449)
    at ruffle_core::display_object::edit_text::EditText::try_bind_text_field_variable::hf556a9ea4c97797d (wasm://wasm/02fc191e:wasm-function[3311]:0x689f66)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::h51e12ca9f173d808 (wasm://wasm/02fc191e:wasm-function[3225]:0x67a969)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::h4032fd6f17aae8e6 (wasm://wasm/02fc191e:wasm-function[1047]:0x3608a0)
    at ruffle_core::display_object::movie_clip::MovieClip::place_object::he559b71030701478 (wasm://wasm/02fc191e:wasm-function[1877]:0x50c876)
    at <ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::enter_frame::hcb61dd33c52f8a84 (wasm://wasm/02fc191e:wasm-function[817]:0x2abd41)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::h4032fd6f17aae8e6 (wasm://wasm/02fc191e:wasm-function[1047]:0x3608dc)
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) HD Graphics 630 Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://ruffle-regressions.github.io/

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-08-06
Channel: nightly
Built: 2023-08-06T00:22:54.670Z
Commit: 690ce110d84dcf8925d60247f685587d8c53adfc
Is extension: false

# Metadata
width: 660
height: 410
frameRate: 12
numFrames: 1
swfVersion: 10
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 1469746

SWF:
[make-my-mcdonalds.zip](https://github.com/ruffle-rs/ruffle/files/12269805/make-my-mcdonalds.zip)

**Comment by Lord-McSweeney** [comment]
This no longer panics, but the SWF hangs on Ruffle after loading the title screen:
```
Overhead  Command          Shared Object            Symbol
  24.18%  ruffle_desktop   ruffle_desktop           [.] swf::avm1::read::Reader::read_action                          
  13.73%  ruffle_desktop   ruffle_desktop           [.] ruffle_core::avm1::activation::Activation::do_action          
   6.61%  ruffle_desktop   ruffle_desktop           [.] swf::avm1::read::Reader::read_push                            
   6.07%  ruffle_desktop   ruffle_desktop           [.] ruffle_core::avm1::activation::Activation::action_push        
   4.13%  ruffle_desktop   libc-2.31.so             [.] malloc                                                        
   4.04%  ruffle_desktop   ruffle_desktop           [.] swf::avm1::read::Reader::read_opcode_and_length               
   4.03%  ruffle_desktop   ruffle_desktop           [.] ruffle_core::avm1::runtime::Avm1::pop                         
```
It works fine in FP.
