### ISSUE TITLE
Error on https://flashpointproject.github.io/flashpoint-database/search/

### ISSUE THREAD

**Issue by Sumus125** [ruffle-rs/ruffle#12639]
# Error Info
Error name: Error
Error message: panicked at 'No script object for display object', core/src/avm1/activation.rs:404:18
Error stack:
```
Error: panicked at 'No script object for display object', core/src/avm1/activation.rs:404:18
    at V.n.wbg.__wbg_new_d258248ed531ff54 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.1dc2d4a7e4ffa0d9fd4c.js:1:51553)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hd045a4c294d004d3 (wasm://wasm/02fc88ee:wasm-function[9229]:0x8efebf)
    at std::panicking::rust_panic_with_hook::h6df5db7ad9f65dc8 (wasm://wasm/02fc88ee:wasm-function[6059]:0x7fda28)
    at core::panicking::panic_fmt::h2d3c5586175098d9 (wasm://wasm/02fc88ee:wasm-function[9072]:0x8eb84b)
    at ruffle_core::display_object::edit_text::EditText::try_bind_text_field_variable::hf556a9ea4c97797d (wasm://wasm/02fc88ee:wasm-function[3316]:0x68ad9a)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::h51e12ca9f173d808 (wasm://wasm/02fc88ee:wasm-function[3230]:0x67b79d)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::h4032fd6f17aae8e6 (wasm://wasm/02fc88ee:wasm-function[1047]:0x3600e9)
    at ruffle_core::display_object::movie_clip::MovieClip::place_object::he559b71030701478 (wasm://wasm/02fc88ee:wasm-function[1878]:0x50b03d)
    at <ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::enter_frame::hcb61dd33c52f8a84 (wasm://wasm/02fc88ee:wasm-function[817]:0x2a4440)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::h4032fd6f17aae8e6 (wasm://wasm/02fc88ee:wasm-function[1047]:0x360125)
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (AMD, AMD Radeon(TM) Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://flashpointproject.github.io/flashpoint-database/search/#a32e739d-347a-926a-b040-980f9d86384f
SWF URL: http://ht.cdn.turner.com/toon/games/chowder/bookincook/preload.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0+2023-08-08
Name: nightly 2023-08-08
Channel: nightly
Built: 2023-08-08T00:19:27.762Z
Commit: 68f8cd6149395b61f96d7404dcccf113bb0aac7d
Is extension: false

# Metadata
width: 600
height: 400
frameRate: 30
numFrames: 45
swfVersion: 9
backgroundColor: #FFFFFF
isActionScript3: true
uncompressedLength: 139818

**Comment by Lord-McSweeney** [comment]
This doesn't panic anymore, but it doesn't get past the loading screen due to an error:
```
Error occurred when running AVM2 frame script: TypeError: Error #1009: Cannot access a property or method of a null object reference.
	at net.yamago.Chowder::Preload/__setProp___id0__Scene1_config_9()
	at net.yamago.Chowder::Preload/frame9()
```

**Comment by Lord-McSweeney** [comment]
Closing in favor of #15039
