### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by blind09** [ruffle-rs/ruffle#12635]
# Error Info
Error name: Error
Error message: panicked at 'Unimplemented opcode LogicalAnd', render/naga-pixelbender/src/lib.rs:1315:29
Error stack:
```
Error: panicked at 'Unimplemented opcode LogicalAnd', render/naga-pixelbender/src/lib.rs:1315:29
    at W.n.wbg.__wbg_new_d258248ed531ff54 (https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.18e89839c4257ed9f1ae.js:1:51449)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hd045a4c294d004d3 (wasm://wasm/02faedb6:wasm-function[9213]:0x8ea9bb)
    at std::panicking::rust_panic_with_hook::h6df5db7ad9f65dc8 (wasm://wasm/02faedb6:wasm-function[6049]:0x7fa9aa)
    at core::panicking::panic_fmt::h2d3c5586175098d9 (wasm://wasm/02faedb6:wasm-function[9057]:0x8e63a3)
    at <ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::compile_pixelbender_shader::h49f0d33e4626967f (wasm://wasm/02faedb6:wasm-function[7267]:0x85f1ef)
    at ruffle_core::avm2::globals::flash::display::shader_data::init::hdcb34ac2ff9449cf (wasm://wasm/02faedb6:wasm-function[864]:0x2eb577)
    at ruffle_core::avm2::function::Executable::exec::h4c0b40e138b66391 (wasm://wasm/02faedb6:wasm-function[837]:0x2c67b6)
    at ruffle_core::avm2::object::TObject::call_property::hc9cbb9ab08e9f727 (wasm://wasm/02faedb6:wasm-function[1069]:0x3710a9)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::h9a983d7c928eeea6 (wasm://wasm/02faedb6:wasm-function[2778]:0x616b75)
    at ruffle_core::avm2::activation::Activation::run_actions::h6fcca51df5c78ad9 (wasm://wasm/02faedb6:wasm-function[516]:0x2a729)
```
AVM2 stack:
```
    at flash.display::ShaderData/flash::display::ShaderData::init()
    at flash.display::ShaderData()
    at flash.display::Shader/set byteCode()
    at flash.display::Shader()
    at viga.gfx.states::GfxStateShader/init()
    at viga.core.states::StateTransition/init()
    at viga.gfx.states::GfxStateTransition/init()
    at viga.core.states::StateTransition()
    at viga.gfx.states::GfxStateTransition()
    at viga.gfx.states::GfxStateCrossShader()
    at lib.states::AppStateManager()
    at viga.core.app.boot.prep::PrepMember/run()
    at viga.core.app.boot.prep::Preps/run()
    at viga.core.app.boot::Preper/run()
    at lib.config.newgrounds::NewgroundsPreper/run()
    at viga.core.app::Application/runPreper()
    at viga.core.app::Document/runPreper()
    at viga.core.app::Document/onEnterFrame()
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel Open Source Technology Center, Mesa DRI Intel(R) UHD Graphics 600 (GLK 2), OpenGL ES 3.2)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | TEXTURE_COMPRESSION_ASTC_HDR | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 4096, max_texture_dimension_2d: 4096, max_texture_dimension_3d: 1024, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.67&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1691234886%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F597000%2F597732_Electropede.swf%3F1340321511%22%2C%22vars%22%3A%7B%22ngio_session_id%22%3A%2219369020.70534c96472d467c1f8726ccac5f36bb49b6231c7bb526%22%2C%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%2264d27473193ce%22%2C%22NewgroundsAPI_SessionID%22%3A%22LqH7ZTgDWmfacMFmuBUJ54307c5967b8dcfc4339c3dcb9bb9cb5cbaec1d3qEZW%22%2C%22NewgroundsAPI_UserName%22%3A%22blindlemoneyes%22%2C%22NewgroundsAPI_UserID%22%3A10071094%2C%22ng_username%22%3A%22blindlemoneyes%22%7D%2C%22width%22%3A500%2C%22height%22%3A600%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F597000%2Fflash_597732_card.png%3Ff1601420150%22%2C%22warnOnUnsupportedContent%22%3Afalse%7D
SWF URL: https://uploads.ungrounded.net/597000/597732_Electropede.swf?1340321511

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-08-05
Channel: nightly
Built: 2023-08-05T00:19:09.531Z
Commit: f75b36a32a9cc1f1b99ed168107738218d7dabb3
Is extension: false

# Metadata
width: 500
height: 600
frameRate: 30
numFrames: 2
swfVersion: 14
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 9078531

**Comment by torokati44** [comment]
This might be interesting for you, @Aaron1011, given that it's in `naga-pixelbender`.

**Comment by Lord-McSweeney** [comment]
Was fixed by https://github.com/ruffle-rs/ruffle/pull/13375
