### ISSUE TITLE
Error on https://www.numuki.com/gameframe/ben-to-the-rescue

### ISSUE THREAD

**Issue by ryannlopes** [ruffle-rs/ruffle#12698]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:942:22
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:942:22
    at imports.wbg.__wbg_new_d258248ed531ff54 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:2403:21)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h47c86d7a777c7d0f (wasm://wasm/02fd1a7a:wasm-function[9224]:0x8f2109)
    at std::panicking::rust_panic_with_hook::h6df5db7ad9f65dc8 (wasm://wasm/02fd1a7a:wasm-function[6059]:0x8006e9)
    at core::panicking::panic_fmt::h2d3c5586175098d9 (wasm://wasm/02fd1a7a:wasm-function[9067]:0x8eda95)
    at core::panicking::panic::h04b2835ef9b41d19 (wasm://wasm/02fd1a7a:wasm-function[8706]:0x8deab2)
    at core::ops::function::FnOnce::call_once::h9515a0660cef5abb (wasm://wasm/02fd1a7a:wasm-function[945]:0x326b6a)
    at ruffle_core::avm1::function::Executable::exec::h0169d53c63eacb86 (wasm://wasm/02fd1a7a:wasm-function[629]:0x1a38a6)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h1d2895105a95b56e (wasm://wasm/02fd1a7a:wasm-function[5004]:0x7a4550)
    at ruffle_core::avm1::activation::Activation::run_actions::h60efdaa4cbba10f5 (wasm://wasm/02fd1a7a:wasm-function[516]:0x2443c)
    at ruffle_core::avm1::function::Executable::exec::h0169d53c63eacb86 (wasm://wasm/02fd1a7a:wasm-function[629]:0x1a36e8)
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) UHD Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: best
Surface samples: 4
Surface size: Extent3d { width: 600, height: 403, depth_or_array_layers: 1 }

# Page Info
Page URL: https://www.numuki.com/gameframe/ben-to-the-rescue
SWF URL: https://media.numuki.com/ben-10/games/ben-to-the-rescue/preload.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
Platform: Win32
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-08-10
Channel: nightly
Built: 2023-08-10T00:23:43.496Z
Commit: fb01473bb3a096d9afca4e464ce6961a45b09045
Is extension: true

# Metadata
width: 600
height: 400
frameRate: 30
numFrames: 43
swfVersion: 8
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 63469

**Comment by n0samu** [comment]
This happens after beating the first area of the second level. I'll see if I can get a save file or more info later.

**Comment by leana8959** [comment]
I'm having the same issue, I would like to be able to help to provide more information, is there anything I can do ?

Thanks !
