### ISSUE TITLE
Error on https://www.neopets.com/games/play_flash.phtml

### ISSUE THREAD

**Issue by Gathouria** [ruffle-rs/ruffle#12729]
This appears to be happening for more than one game, but this one is Catch the Petpet: https://www.neopets.com/petpetpark/games.phtml?game_id=1034

Game either fails to load entirely (message "Adobe Flash Player is no longer supported") or occasionally will show Ruffle attempting to load briefly before going to the error/report screen.

# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/library.rs:348:26
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/library.rs:348:26
    at imports.wbg.__wbg_new_d258248ed531ff54 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:2403:21)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h47c86d7a777c7d0f (wasm://wasm/02fe37e6:wasm-function[9233]:0x8f67e0)
    at std::panicking::rust_panic_with_hook::h6df5db7ad9f65dc8 (wasm://wasm/02fe37e6:wasm-function[6049]:0x7f67f0)
    at core::panicking::panic_fmt::h2d3c5586175098d9 (wasm://wasm/02fe37e6:wasm-function[9076]:0x8f216c)
    at core::panicking::panic::h04b2835ef9b41d19 (wasm://wasm/02fe37e6:wasm-function[8715]:0x8e3189)
    at ruffle_core::display_object::movie_clip::MovieClip::preload::hce260bb4de8d08b9 (wasm://wasm/02fe37e6:wasm-function[666]:0x1eeae2)
    at ruffle_core::loader::Loader::preload_tick::h50f20d544766d07c (wasm://wasm/02fe37e6:wasm-function[1644]:0x484adb)
    at ruffle_web::Ruffle::tick::h968e8360581307dd (wasm://wasm/02fe37e6:wasm-function[791]:0x280474)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h0909598910466b05 (wasm://wasm/02fe37e6:wasm-function[11037]:0x935745)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h496e7bd9f54461c0 (wasm://wasm/02fe37e6:wasm-function[9891]:0x9136c2)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Google, Vulkan 1.3.0 (SwiftShader Device (Subzero) (0x0000C0DE)), SwiftShader driver)"
Adapter Device Type: Cpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | TEXTURE_COMPRESSION_ASTC_HDR | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 8192, max_texture_dimension_2d: 8192, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://www.neopets.com/games/play_flash.phtml?va=&game_id=1034&nc_referer=&age=1&hiscore=&sp=0&questionSet=&r=979826&width=640&height=500&quality=high
SWF URL: https://images.neopets.com/games/gaming_system/np8_loader_v3_18.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-08-13
Channel: nightly
Built: 2023-08-13T00:23:15.804Z
Commit: 3117469e20eeb1a435e678268252a4545228c030
Is extension: true

# Metadata
width: 1000
height: 1000
frameRate: 18
numFrames: 21
swfVersion: 8
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 9994

**Comment by n0samu** [comment]
If you mean the error message, that's known to happen for Catch the Petpet, but I can't reproduce it for any of the other games you mentioned.

**Comment by n0samu** [comment]
Please send the error report/text for any of the other games you're saying have the problem.

**Comment by Gathouria** [comment]
> Please send the error report/text for any of the other games you're saying have the problem.

The other games I can't get through to the error screen at all, it's just an uninteractable "Adobe Flash Player is no longer supported" grey screen. I assumed they were the same issue because 80% of the time loading Catch the Petpet gives the same screen and doesn't show the Ruffle screen either, but perhaps they're not.

Not sure if there's another way to access the error report when Ruffle doesn't load properly at all?

**Comment by Gathouria** [comment]
Update: Switched over to Firefox (neo normally works better on Chrome for me) and games appear to be working, but Chrome is still having issue, though Roodoku looks fine again at least for now

**Comment by n0samu** [comment]
Seeing an "Adobe Flash Player is no longer supported" message is an entirely separate problem. And I can't reproduce it in Chrome or Firefox for any game you mentioned.

**Comment by Gathouria** [comment]
Strange, as I'm not running any weird plugins on Chrome except uBlock, which I switched off and continued to see the problem for.. I will update with a comment here if I find anything else out.
