### ISSUE TITLE
Error on https://www.minigamers.com/games/spongebob-skater~18022/ (weird ass site i found)

### ISSUE THREAD

**Issue by SharkLover12** [ruffle-rs/ruffle#12737]
# Error Info
Error name: Error
Error message: panicked at 'No script object for display object', core/src/avm1/activation.rs:404:18
Error stack:
```
Error: panicked at 'No script object for display object', core/src/avm1/activation.rs:404:18
    at V.n.wbg.__wbg_new_d258248ed531ff54 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.b8e8d3700219a22fa58f.js:1:51553)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h47c86d7a777c7d0f (wasm://wasm/02fe37e6:wasm-function[9233]:0x8f67e0)
    at std::panicking::rust_panic_with_hook::h6df5db7ad9f65dc8 (wasm://wasm/02fe37e6:wasm-function[6049]:0x7f67f0)
    at core::panicking::panic_fmt::h2d3c5586175098d9 (wasm://wasm/02fe37e6:wasm-function[9076]:0x8f216c)
    at ruffle_core::display_object::edit_text::EditText::try_bind_text_field_variable::h9d29c9133c8d5e7a (wasm://wasm/02fe37e6:wasm-function[3149]:0x655a98)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::h0b1947b48d35b9e3 (wasm://wasm/02fe37e6:wasm-function[3075]:0x6448c0)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::hbe74bc6172fd2e2b (wasm://wasm/02fe37e6:wasm-function[1040]:0x358fa5)
    at ruffle_core::display_object::movie_clip::MovieClip::place_object::he475252b76ef3756 (wasm://wasm/02fe37e6:wasm-function[1879]:0x500d4f)
    at <ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::enter_frame::h5b34e76ebb53cb5f (wasm://wasm/02fe37e6:wasm-function[815]:0x2a3dbd)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::hbe74bc6172fd2e2b (wasm://wasm/02fe37e6:wasm-function[1040]:0x358fe1)
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA GeForce RTX 3070 Ti Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://www.minigamers.com/games/spongebob-skater~18022/
SWF URL: https://games.macrojuegos.com/25000/25691/b4c2c23a6db47bec766ba8c151ecgfuy.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-08-13
Channel: nightly
Built: 2023-08-13T00:23:15.804Z
Commit: 3117469e20eeb1a435e678268252a4545228c030
Is extension: false

# Metadata
width: 800
height: 580
frameRate: 23
numFrames: 32
swfVersion: 9
backgroundColor: #FFFFFF
isActionScript3: true
uncompressedLength: 2901526

**Comment by Lord-McSweeney** [comment]
Fixed by #11005
