### ISSUE TITLE
Error on https://kdata1.com/2016/11/anime-legends-25/

### ISSUE THREAD

**Issue by BossJames134** [ruffle-rs/ruffle#12773]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/library.rs:348:26
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/library.rs:348:26
    at imports.wbg.__wbg_new_d258248ed531ff54 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:2403:21)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h47c86d7a777c7d0f (wasm://wasm/02fe6f02:wasm-function[9238]:0x8f741a)
    at std::panicking::rust_panic_with_hook::h6df5db7ad9f65dc8 (wasm://wasm/02fe6f02:wasm-function[6053]:0x7f74f7)
    at core::panicking::panic_fmt::h2d3c5586175098d9 (wasm://wasm/02fe6f02:wasm-function[9081]:0x8f2da6)
    at core::panicking::panic::h04b2835ef9b41d19 (wasm://wasm/02fe6f02:wasm-function[8720]:0x8e3dc3)
    at ruffle_core::display_object::movie_clip::MovieClip::preload::hce260bb4de8d08b9 (wasm://wasm/02fe6f02:wasm-function[666]:0x1eeaf7)
    at ruffle_core::loader::Loader::preload_tick::h50f20d544766d07c (wasm://wasm/02fe6f02:wasm-function[1644]:0x484e99)
    at ruffle_web::Ruffle::tick::h968e8360581307dd (wasm://wasm/02fe6f02:wasm-function[791]:0x280489)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h0909598910466b05 (wasm://wasm/02fe6f02:wasm-function[11042]:0x93637f)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h496e7bd9f54461c0 (wasm://wasm/02fe6f02:wasm-function[9896]:0x9142fc)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel Open Source Technology Center, Mesa DRI Intel(R) UHD Graphics 600 (GLK 2), OpenGL ES 3.2)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | TEXTURE_COMPRESSION_ASTC_HDR | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 4096, max_texture_dimension_2d: 4096, max_texture_dimension_3d: 1024, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }
Player type: Object
SWF URL: loader.swf
Param movie: loader.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined

# Page Info
Page URL: https://kdata1.com/2016/11/anime-legends-25/
SWF URL: https://kdata1.com/2016/11/anime-legends-25/loader.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-08-14
Channel: nightly
Built: 2023-08-14T00:19:51.507Z
Commit: 56b97e7b40ea40061d0844ac4d691d0e07ac4c05
Is extension: true

# Metadata
width: 800
height: 800
frameRate: 24
numFrames: 1
swfVersion: 8
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 10147

**Comment by Lord-McSweeney** [comment]
This seems to be working now
