### ISSUE TITLE
Error on https://www.superhry.cz/games/2539/

### ISSUE THREAD

**Issue by SebikPlacer** [ruffle-rs/ruffle#12808]
# Error Info
Error name: Error
Error message: panicked at 'not implemented: Unimplemented opcode NotEqual', render/naga-pixelbender/src/lib.rs:725:29
Error stack:
```
Error: panicked at 'not implemented: Unimplemented opcode NotEqual', render/naga-pixelbender/src/lib.rs:725:29
    at W.n.wbg.__wbg_new_d258248ed531ff54 (https://www.superhry.cz/js/ruffle30062023/core.ruffle.b07a8feae68bea95793e.js:1:51548)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h29556e60c8892742 (wasm://wasm/02cc8262:wasm-function[8730]:0x8535a0)
    at std::panicking::rust_panic_with_hook::h85b7f6628c291e12 (wasm://wasm/02cc8262:wasm-function[5675]:0x76dcd1)
    at core::panicking::panic_fmt::hf5c4cd929d4aaa9e (wasm://wasm/02cc8262:wasm-function[8592]:0x84f118)
    at <ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::compile_pixelbender_shader::h38d5ad46b2101964 (wasm://wasm/02cc8262:wasm-function[7228]:0x7e908a)
    at ruffle_core::avm2::globals::flash::display::shader_data::init::h499ce55c412b9194 (wasm://wasm/02cc8262:wasm-function[830]:0x2cd33a)
    at ruffle_core::avm2::function::Executable::exec::h7f5c710bb48597ca (wasm://wasm/02cc8262:wasm-function[818]:0x2b987f)
    at ruffle_core::avm2::object::TObject::call_property::h92676acd1a3d08c2 (wasm://wasm/02cc8262:wasm-function[1133]:0x3a0896)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::hc75e401718bd829c (wasm://wasm/02cc8262:wasm-function[2688]:0x5c5538)
    at ruffle_core::avm2::activation::Activation::run_actions::h0ade8598513bdd11 (wasm://wasm/02cc8262:wasm-function[517]:0x29e85)
```
AVM2 stack:
```
    at flash.display::ShaderData/flash::display::ShaderData::init()
    at flash.display::ShaderData()
    at flash.display::Shader/set byteCode()
    at flash.display::Shader()
    at as_files::Filter$/outLining()
    at as_files::LevelBackground()
    at level_1_background()
    at flash.display::DisplayObject/flash.display::DisplayObject()
    at flash.display::InteractiveObject/flash.display::InteractiveObject()
    at flash.display::DisplayObjectContainer/flash.display::DisplayObjectContainer()
    at flash.display::Sprite()
    at flash.display::MovieClip()
    at as_files::Level()
    at level_1()
    at flash.display::DisplayObject/flash.display::DisplayObject()
    at flash.display::InteractiveObject/flash.display::InteractiveObject()
    at flash.display::DisplayObjectContainer/flash.display::DisplayObjectContainer()
    at flash.display::Sprite()
    at flash.display::MovieClip()
    at as_files::LayerLevel()
    at as_files::Game$/createLayers()
    at as_files::Game()
    at flash.display::MovieClip/flash::display::MovieClip::nextFrame()
    at as_files::Menu/nextGame()
    at as_files::Menu/update()
    at as_files::Menu/enter_frame()
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) HD Graphics 520 Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://www.superhry.cz/games/2539/
SWF URL: https://www.superhry.cz/cnt_img/002/2539.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.200
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-06-30
Channel: nightly
Built: 2023-06-30T00:19:35.533Z
Commit: 1c151a86d6d3ecc4a4e0d41aeee2b7b1c878f170
Is extension: false

# Metadata
width: 800
height: 400
frameRate: 24
numFrames: 5
swfVersion: 10
backgroundColor: #CCCCCC
isActionScript3: true
uncompressedLength: 22198035

**Comment by n0samu** [comment]
Note: The site calls the game "Mstitel" (Avenger) but its English title is Mr. Vengeance Act II

**Comment by n0samu** [comment]
This has actually been implemented already, the site just needs to update their copy of Ruffle. I suggest installing the Ruffle extension to use the most updated version, and contacting the site owner to ask them to update.
