### ISSUE TITLE
Error on Cargo Bridge

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#12817]
# Error Info
Error name: Error
Error message: panicked at 'Unimplemented opcode Loop', render/naga-pixelbender/src/lib.rs:1315:29
Error stack:
```
Error: panicked at 'Unimplemented opcode Loop', render/naga-pixelbender/src/lib.rs:1315:29
    at imports.wbg.__wbg_new_d258248ed531ff54 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:2403:21)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h665574cf5fec7903 (wasm://wasm/02fe6fae:wasm-function[9263]:0x8f7370)
    at std::panicking::rust_panic_with_hook::h6df5db7ad9f65dc8 (wasm://wasm/02fe6fae:wasm-function[6062]:0x7f64e0)
    at core::panicking::panic_fmt::h2d3c5586175098d9 (wasm://wasm/02fe6fae:wasm-function[9105]:0x8f2ce2)
    at <ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::compile_pixelbender_shader::h7ef69e88d065da15 (wasm://wasm/02fe6fae:wasm-function[7310]:0x86aaec)
    at ruffle_core::avm2::globals::flash::display::shader_data::init::h1d8f6482f11b2caf (wasm://wasm/02fe6fae:wasm-function[1126]:0x38debc)
    at ruffle_core::avm2::function::Executable::exec::he43152352eaf271c (wasm://wasm/02fe6fae:wasm-function[837]:0x2c3d16)
    at ruffle_core::avm2::object::TObject::call_property::h0f5d62801da41514 (wasm://wasm/02fe6fae:wasm-function[1062]:0x367064)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::h5bf5b32aeac02da6 (wasm://wasm/02fe6fae:wasm-function[2766]:0x603337)
    at ruffle_core::avm2::activation::Activation::run_actions::h7b8351faf31ade1f (wasm://wasm/02fe6fae:wasm-function[517]:0x2a761)
```
AVM2 stack:
```
    at flash.display::ShaderData/flash::display::ShaderData::init()
    at flash.display::ShaderData()
    at flash.display::Shader/set byteCode()
    at flash.display::Shader()
    at bridge.level::TerrainBuilder/twirl()
    at bridge.level::TerrainBuilder/buildBackground()
    at bridge.level::Ground/createBackground()
    at bridge.level::XmlGround/createBackground()
    at bridge.level::Ground/initialize()
    at bridge.level::Level/initialize()
    at bridge.level::XmlLevel/callSuperInitialize()
    at bridge.level::CompiledXmlLevel/initialize()
    at bridge.director::GameScene/initialize()
    at Main/initLevel()
    at flash.events::EventDispatcher/flash::events::EventDispatcher::dispatchEvent()
    at bridge.mainMenu.screen::LevelsScreen/onLevelClick()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (AMD, AMD FirePro W5100 Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 640, height: 440, depth_or_array_layers: 1 }
Player type: Object
SWF URL: https://www.hoodamath.com/flash/cargobridge.swf
Param movie: https://www.hoodamath.com/flash/cargobridge.swf
Param quality: high
Param play: true
Param loop: true
Param wmode: window
Param scale: showall
Param menu: true
Param devicefont: false
Param allowScriptAccess: sameDomain
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined

# Page Info
Page URL: https://www.hoodamath.com/games/cargobridge.html#gsc.tab=0
SWF URL: https://www.hoodamath.com/flash/cargobridge.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.203
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-08-17
Channel: nightly
Built: 2023-08-17T00:20:13.730Z
Commit: f00671e9cca2fdf395ecf0c26873e50f7efd74cc
Is extension: true

# Metadata
width: 800
height: 550
frameRate: 30
numFrames: 2
swfVersion: 10
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 758186

**Comment by n0samu** [comment]
Panic is fixed now but the game has a lot of other problems - see #13982
