### ISSUE TITLE
Error on http://localhost/index.html

### ISSUE THREAD

**Issue by sergo-zu** [ruffle-rs/ruffle#12883]
My test with video embedded in swf IDE CS.5.5.... I am going on testings...

# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/library.rs:348:26
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/library.rs:348:26
    at n.wbg.__wbg_new_d258248ed531ff54 (http://localhost/core.ruffle.0d9085989d1a8506ac6a.js:1:54008)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hc22db995a124727b (wasm://wasm/03108076:wasm-function[9292]:0x947f41)
    at std::panicking::rust_panic_with_hook::h6df5db7ad9f65dc8 (wasm://wasm/03108076:wasm-function[6135]:0x84194f)
    at core::panicking::panic_fmt::h2d3c5586175098d9 (wasm://wasm/03108076:wasm-function[9140]:0x943a19)
    at core::panicking::panic::h04b2835ef9b41d19 (wasm://wasm/03108076:wasm-function[8777]:0x931c35)
    at ruffle_core::display_object::movie_clip::MovieClip::preload::h2fea1fd53a51439f (wasm://wasm/03108076:wasm-function[671]:0x205134)
    at ruffle_core::loader::Loader::preload_tick::hd1207a460d0f028f (wasm://wasm/03108076:wasm-function[1624]:0x4b3703)
    at ruffle_web::Ruffle::tick::h458475d324f9c3f9 (wasm://wasm/03108076:wasm-function[805]:0x2b8569)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::ha2aca24c3210b04a (wasm://wasm/03108076:wasm-function[10975]:0x97fcf6)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h462a2ce6730fd3f6 (wasm://wasm/03108076:wasm-function[9933]:0x9642a9)
```

# Player Info
Allows script access: true
Renderer: Canvas
Player type: Object
SWF URL: xml5.swf
Param movie: xml5.swf
Attribute 0: undefined
Attribute 1: undefined

# Page Info
Page URL: http://localhost/index.html
SWF URL: http://localhost/xml5.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 YaBrowser/23.7.3.823 Yowser/2.5 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-08-20
Channel: nightly
Built: 2023-08-20T00:22:55.066Z
Commit: 891e369f4873ea876888badff8359387271db666
Is extension: false

# Metadata
width: 1280
height: 680
frameRate: 12
numFrames: 1
swfVersion: 8
backgroundColor: #333333
isActionScript3: false
uncompressedLength: 80358

**Comment by n0samu** [comment]
Hi, can you please zip and attach the SWF file?

**Comment by Lord-McSweeney** [comment]
Closing in favor of #12907.
