### ISSUE TITLE
Error on https://www.zuzu.games/g/jumping-finn

### ISSUE THREAD

**Issue by LETSGOBAI** [ruffle-rs/ruffle#12882]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/bitmap/bitmap_data.rs:1292:51
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/bitmap/bitmap_data.rs:1292:51
    at U.n.wbg.__wbg_new_15d3966e9981a196 (https://www.zuzu.games/js/frontend/vendor/ruffle/core.ruffle.232c98a410606efcc0cf.js:1:47866)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h8cd677756bfcdf86 (wasm://wasm/0298ba0a:wasm-function[7876]:0x7d3f51)
    at std::panicking::rust_panic_with_hook::h8d0a63d0479a36c8 (wasm://wasm/0298ba0a:wasm-function[5335]:0x717e4e)
    at core::panicking::panic_fmt::h2a7f454a5f5da218 (wasm://wasm/0298ba0a:wasm-function[7767]:0x7cf4c7)
    at core::panicking::panic::ha3ebcac1438d9280 (wasm://wasm/0298ba0a:wasm-function[7182]:0x79b26f)
    at ruffle_core::bitmap::bitmap_data::BitmapData::update_dirty_texture::he70a9bca9133a4ae (wasm://wasm/0298ba0a:wasm-function[1241]:0x3a1709)
    at ruffle_core::bitmap::bitmap_data::wrapper::BitmapDataWrapper::overwrite_cpu_pixels_from_gpu::h9f2dbcb21ebe171f (wasm://wasm/0298ba0a:wasm-function[5458]:0x72047b)
    at ruffle_core::avm2::globals::flash::display::bitmap_data::draw::h2c2d5411393474ce (wasm://wasm/0298ba0a:wasm-function[699]:0x251bad)
    at ruffle_core::avm2::function::Executable::exec::hc93135fb74ac10de (wasm://wasm/0298ba0a:wasm-function[890]:0x2ec17b)
    at ruffle_core::avm2::object::TObject::call_property::h48d63e043be67773 (wasm://wasm/0298ba0a:wasm-function[1048]:0x347891)
```
AVM2 stack:
```
    at flash.display::BitmapData/flash::display::BitmapData::draw()
    at currentGame.gameObjects::Level()
    at currentGame.states::StateGame/init()
    at ilmare.StateLib::StateManager/update()
    at Main/update()
    at flash.events::EventDispatcher/flash::events::EventDispatcher::dispatchEvent()
    at flash.utils::Timer/onUpdate()
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: https://www.zuzu.games/upload/swf/jumping-finn-1562753601.swf
Param movie: https://www.zuzu.games/upload/swf/jumping-finn-1562753601.swf
Param SCALE: exactfit
Param BGCOLOR: #FFF
Param AllowScriptAccess: always
Param quality: high
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined

# Page Info
Page URL: https://www.zuzu.games/g/jumping-finn
SWF URL: https://www.zuzu.games/upload/swf/jumping-finn-1562753601.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-03-13
Channel: nightly
Built: 2023-03-13T00:19:09.191Z
Commit: b527054a1e2317d9e17ed0dfbfc0e9cceaafd760
Is extension: false

# Metadata
width: 600
height: 400
frameRate: 30
numFrames: 2
swfVersion: 10
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 7452286

**Comment by n0samu** [comment]
This site is using an outdated version of Ruffle. This specific error has already been fixed.
