### ISSUE TITLE
Error on http://flash.7k7k.com/cms/cms10/20161017/0852279722/11/game.html

### ISSUE THREAD

**Issue by ardithho** [ruffle-rs/ruffle#12898]
# Error Info
Error name: Error
Error message: panicked at 'Unexpected non-object value in object vector', core/src/avm2/amf.rs:99:34
Error stack:
```
Error: panicked at 'Unexpected non-object value in object vector', core/src/avm2/amf.rs:99:34
    at imports.wbg.__wbg_new_d258248ed531ff54 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:2403:21)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h68328b569f1b749d (wasm://wasm/03004c9a:wasm-function[9274]:0x8fe0a7)
    at std::panicking::rust_panic_with_hook::h6df5db7ad9f65dc8 (wasm://wasm/03004c9a:wasm-function[6075]:0x7fd8f9)
    at core::panicking::panic_fmt::h2d3c5586175098d9 (wasm://wasm/03004c9a:wasm-function[9116]:0x8f9a19)
    at core::option::expect_failed::h3af12667ecd4887c (wasm://wasm/03004c9a:wasm-function[8024]:0x8b9e05)
    at ruffle_core::avm2::amf::serialize_value::hcd39d6c94d8dcea7 (wasm://wasm/03004c9a:wasm-function[735]:0x243a30)
    at ruffle_core::avm2::amf::recursive_serialize::h8f604c2b0b4112f4 (wasm://wasm/03004c9a:wasm-function[2403]:0x5975f8)
    at ruffle_core::avm2::globals::flash::net::shared_object::new_lso::hd05459a73dfa1c22 (wasm://wasm/03004c9a:wasm-function[2566]:0x5c222b)
    at ruffle_core::avm2::globals::flash::net::shared_object::flush::h651e8f5ebde40d8c (wasm://wasm/03004c9a:wasm-function[1467]:0x43e891)
    at ruffle_core::avm2::function::Executable::exec::h9f4a66d15a9ddc9d (wasm://wasm/03004c9a:wasm-function[836]:0x2b7d43)
```
AVM2 stack:
```
    at flash.net::SharedObject/flash::net::SharedObject::flush()
    at com.spilgames.api.core.tracking.ext.spilet.trackStates::NotSpilState/updateSharedObject()
    at com.spilgames.api.core.tracking.ext.spilet.trackStates::NotSpilState/addElementToQueue()
    at com.spilgames.api.core.tracking.ext.spilet.trackStates::NotSpilState/startSession()
    at com.spilgames.api.core.tracking.ext.spilet.trackStates::NotSpilState/init()
    at com.spilgames.api.core.tracking.ext.spilet.trackStates::NotSpilState()
    at com.spilgames.api.core.tracking.ext.spilet.setTracker::SET$/setEnvironment()
    at com.spilgames.api.core.tracking.ext.spilet.setTracker::SET$/init()
    at com.spilgames.api.core.tracking.ext.spilet.setTracker::SET$/getInstance()
    at com.spilgames.api.core.tracking.ext.spilet::SETTracker/setup()
    at com.spilgames.api.core.tracking.ext::ATracker/setClass()
    at com.spilgames.api.core.tracking.ext::TrackerLoader/load()
    at com.spilgames.api.core.tracking::TrackController/loadLibraries()
    at com.spilgames.api.core.tracking::TrackController/onLoadConfig()
    at com.spilgames.api.core.tracking::TrackConfig/onLoadConfig()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA GeForce GTX 1650 Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: http://flash.7k7k.com/cms/cms10/20161017/0852279722/11/game.html
SWF URL: http://flash.7k7k.com/cms/cms10/20161017/0852279722/11/game.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-08-22
Channel: nightly
Built: 2023-08-22T00:24:04.167Z
Commit: 3de4b4e989afb873b207eb885177b193a4d53b4e
Is extension: true

# Metadata
width: 700
height: 500
frameRate: 24
numFrames: 9
swfVersion: 11
backgroundColor: #FFFFFF
isActionScript3: true
uncompressedLength: 2618122

**Comment by SuchAFuriousDeath** [comment]
Fixed by #13537.
