### ISSUE TITLE
Error on https://f.kbhgames.com/2014/OmniverseCollection/game.htm

### ISSUE THREAD

**Issue by TAMATEM0** [ruffle-rs/ruffle#12947]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/library.rs:348:26
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/library.rs:348:26
    at imports.wbg.__wbg_new_d258248ed531ff54 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:2403:21)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h68328b569f1b749d (wasm://wasm/0302832e:wasm-function[9312]:0x9035a5)
    at std::panicking::rust_panic_with_hook::h6df5db7ad9f65dc8 (wasm://wasm/0302832e:wasm-function[6105]:0x80fa87)
    at core::panicking::panic_fmt::h2d3c5586175098d9 (wasm://wasm/0302832e:wasm-function[9154]:0x8ff060)
    at core::panicking::panic::h04b2835ef9b41d19 (wasm://wasm/0302832e:wasm-function[8792]:0x8eff80)
    at ruffle_core::display_object::movie_clip::MovieClip::preload::h197297f0edc47c62 (wasm://wasm/0302832e:wasm-function[668]:0x1f28c6)
    at ruffle_core::loader::Loader::preload_tick::hb9396d86253a3b4e (wasm://wasm/0302832e:wasm-function[1645]:0x4902cd)
    at ruffle_web::Ruffle::tick::hd6287a8af3b04833 (wasm://wasm/0302832e:wasm-function[794]:0x27f745)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h0bcd3805fc451e27 (wasm://wasm/0302832e:wasm-function[11123]:0x945306)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h643d7fc428c271c4 (wasm://wasm/0302832e:wasm-function[9969]:0x92121a)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel Inc., Intel(R) Iris(TM) Plus Graphics OpenGL Engine (1x6x8 (fused) LP, OpenGL 4.1)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 1200, height: 800, depth_or_array_layers: 1 }
Player type: Object
SWF URL: game.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://f.kbhgames.com/2014/OmniverseCollection/game.htm
SWF URL: https://f.kbhgames.com/2014/OmniverseCollection/game.swf

# Browser Info
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Platform: MacIntel
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-08-24
Channel: nightly
Built: 2023-08-24T00:20:48.719Z
Commit: 1b03ce9ae668ea2b40f03f24ad38af95d1e92e80
Is extension: true

# Metadata
width: 800
height: 800
frameRate: 24
numFrames: 1
swfVersion: 8
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 10342

**Comment by Lord-McSweeney** [comment]
Should be fixed by #11005
