### ISSUE TITLE
Error on Project Anilam

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#13004]
# Error Info
Error name: Error
Error message: panicked at 'Tex storage 2D multisample is not supported', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/glow-0.12.3/src/web_sys.rs:3167:9
Error stack:
```
Error: panicked at 'Tex storage 2D multisample is not supported', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/glow-0.12.3/src/web_sys.rs:3167:9
    at V.n.wbg.__wbg_new_d258248ed531ff54 (https://www.spiele-umsonst.de/ruffle/core.ruffle.0865d85c7c067dcfcad7.js:1:51553)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h68328b569f1b749d (wasm://wasm/0302832e:wasm-function[9312]:0x9035a5)
    at std::panicking::rust_panic_with_hook::h6df5db7ad9f65dc8 (wasm://wasm/0302832e:wasm-function[6105]:0x80fa87)
    at core::panicking::panic_fmt::h2d3c5586175098d9 (wasm://wasm/0302832e:wasm-function[9154]:0x8ff060)
    at <T as wgpu::context::DynContext>::device_create_texture::h9c53417b1ed2a6a6 (wasm://wasm/0302832e:wasm-function[6778]:0x843bc3)
    at wgpu::Device::create_texture::ha8f32fe3c5d3a516 (wasm://wasm/0302832e:wasm-function[5148]:0x7bc5d3)
    at <ruffle_render_wgpu::context3d::WgpuContext3D as ruffle_render::backend::Context3D>::process_command::h6667fcda790a0e7d (wasm://wasm/0302832e:wasm-function[533]:0x9d963)
    at ruffle_core::avm2::globals::flash::display3D::context_3d::set_render_to_texture::hdb265e6d2a6dd2c9 (wasm://wasm/0302832e:wasm-function[1781]:0x4e511b)
    at ruffle_core::avm2::function::Executable::exec::h9f4a66d15a9ddc9d (wasm://wasm/0302832e:wasm-function[837]:0x2bc111)
    at ruffle_core::avm2::object::TObject::call_property::hfc0f9de65af3fac4 (wasm://wasm/0302832e:wasm-function[1104]:0x37bcfa)
```
AVM2 stack:
```
    at flash.display3D::Context3D/flash::display3D::Context3D::setRenderToTexture()
    at away3d.core.managers::Stage3DProxy/setRenderTarget()
    at away3d.core.render::RendererBase/executeRender()
    at away3d.core.render::RendererBase/render()
    at away3d.lights.shadowmaps::DirectionalShadowMapper/drawDepthMap()
    at away3d.lights.shadowmaps::ShadowMapperBase/renderDepthMap()
    at away3d.core.render::DefaultRenderer/updateLights()
    at away3d.core.render::DefaultRenderer/executeRender()
    at away3d.core.render::RendererBase/render()
    at away3d.containers::View3D/render()
    at project_alnilam/onEnterFrame()
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) UHD Graphics 620 Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
SWF URL: https://www.spiele-umsonst.de/azad/downloads/flashgames/projectalinlam.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-08-24
Channel: nightly
Built: 2023-08-24T00:20:48.719Z
Commit: 1b03ce9ae668ea2b40f03f24ad38af95d1e92e80
Is extension: false

# Metadata
width: 800
height: 480
frameRate: 60
numFrames: 3
swfVersion: 15
backgroundColor: #EEEEEE
isActionScript3: true
uncompressedLength: 9091589

**Comment by Aaron1011** [comment]
This should be fixed as of https://github.com/ruffle-rs/ruffle/commit/520045de4688d01b75310a6392434d919410cadb

**Comment by Lord-McSweeney** [comment]
I think #12982 fixed this
