### ISSUE TITLE
Error on http://img-hws.y8.com/cloud/y8-flash-game/contents/item_versions/flash_games/8784/original/aqua_turret.swf

### ISSUE THREAD

**Issue by Mysterious-Mus** [ruffle-rs/ruffle#13010]
# File
[http://img-hws.y8.com/cloud/y8-flash-game/contents/item_versions/flash_games/8784/original/aqua_turret.swf](url)

# Error Info
Error name: Error
Error message: RuntimeError: memory access out of bounds
Error stack:
```
Error: RuntimeError: memory access out of bounds
    at Un.load (https://ruffle.rs/demo/index.js:2:273881)
    at async Un.reload (https://ruffle.rs/demo/index.js:2:272988)
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) UHD Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://ruffle.rs/demo/

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 Edg/116.0.1938.62
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-08-29
Channel: nightly
Built: 2023-08-29T00:25:38.056Z
Commit: 0ed447b42877b10fdaaf913015eb2783cd9afb04
Is extension: false

# Metadata

**Comment by n0samu** [comment]
Here's the error I'm getting:
```
0306b726:0x2949eb  Uncaught RangeError: Maximum call stack size exceeded
    at ruffle_core::avm2::function::Executable::exec::h66c199093db9deaf (0306b726:0x2949eb)
    at ruffle_core::avm2::activation::Activation::super_init::h80a0b9b44c5c1602 (0306b726:0x7ae72f)
    at ruffle_core::avm2::globals::flash::display::interactive_object::native_instance_init::h04f6ae6050485060 (0306b726:0x8cd259)
    at ruffle_core::avm2::function::Executable::exec::h66c199093db9deaf (0306b726:0x2966ea)
    at ruffle_core::avm2::activation::Activation::super_init::h80a0b9b44c5c1602 (0306b726:0x7ae72f)
    at ruffle_core::avm2::globals::flash::display::display_object_container::native_instance_init::h00dafb60f9b7c3c6 (0306b726:0x8ccf98)
    at ruffle_core::avm2::function::Executable::exec::h66c199093db9deaf (0306b726:0x2966ea)
    at ruffle_core::avm2::activation::Activation::run_actions::h65f656b485b30e84 (0306b726:0x2ccd9)
    at ruffle_core::avm2::function::Executable::exec::h66c199093db9deaf (0306b726:0x29633f)
    at ruffle_core::avm2::activation::Activation::run_actions::h65f656b485b30e84 (0306b726:0x2ccd9)
```
This is similar to #11534.
