### ISSUE TITLE
Error on https://www.minijuegos.com/helpers/game/sandbox.php

### ISSUE THREAD

**Issue by maryansnz** [ruffle-rs/ruffle#13038]
# Error Info
Error name: Error
Error message: panicked at 'Unexpected non-object value in object vector', core/src/avm2/amf.rs:99:34
Error stack:
```
Error: panicked at 'Unexpected non-object value in object vector', core/src/avm2/amf.rs:99:34
    at V.n.wbg.__wbg_new_d258248ed531ff54 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.9cdaa3ec5f23e9e60beb.js:1:51650)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h3959f346f7109267 (wasm://wasm/0306993a:wasm-function[9258]:0x9138dc)
    at std::panicking::rust_panic_with_hook::h7601402c0a383194 (wasm://wasm/0306993a:wasm-function[6015]:0x8139ef)
    at core::panicking::panic_fmt::h6dad0405f48e39e2 (wasm://wasm/0306993a:wasm-function[9098]:0x90efb5)
    at core::option::expect_failed::h980aad86598061bd (wasm://wasm/0306993a:wasm-function[7989]:0x8cd26c)
    at ruffle_core::avm2::amf::serialize_value::h0c6e51a27b6adf32 (wasm://wasm/0306993a:wasm-function[757]:0x264ea4)
    at ruffle_core::avm2::amf::recursive_serialize::hc449dd3981488c2f (wasm://wasm/0306993a:wasm-function[2399]:0x5ae9a6)
    at ruffle_core::avm2::globals::flash::net::shared_object::new_lso::h202a3cd4a0ee1271 (wasm://wasm/0306993a:wasm-function[3004]:0x64d064)
    at ruffle_core::avm2::globals::flash::net::shared_object::flush::ha1f8433d7a91916a (wasm://wasm/0306993a:wasm-function[1471]:0x44c0e8)
    at ruffle_core::avm2::function::Executable::exec::hebfea0b7e1b2fb7d (wasm://wasm/0306993a:wasm-function[829]:0x2b778d)
```
AVM2 stack:
```
    at flash.net::SharedObject/flash::net::SharedObject::flush()
    at SelectLevelState()
    at StateManager/onResourcesLoaded()
    at Function/call()
    at ResourceManager/onResourcesLoaded()
    at Function/call()
    at Resources/loadImage()
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) UHD Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 800, height: 480, depth_or_array_layers: 1 }

# Page Info
Page URL: https://www.minijuegos.com/helpers/game/sandbox.php?mp_assets=https%3A%2F%2Fs2.minijuegosgratis.com%2F&mp_embed=0&mp_game_id=24429&mp_game_uid=parking-mania&mp_game_url=https%3A%2F%2Fwww.minijuegos.com%2Fembed%2Fparking-mania&mp_int=1&mp_locale=es_ES&mp_player_type=FLASH&mp_player_url=aHR0cHM6Ly93d3cubWluaWp1ZWdvc2dyYXRpcy5jb20vZmxhc2gxMjM0L25vX2hvdGxpbmsvcGFya2luZ21hbmlhLnN3Zg%3D%3D&mp_site_https_url=https%3A%2F%2Fwww.minijuegos.com%2F&mp_site_name=minijuegos.com&mp_site_url=https%3A%2F%2Fwww.minijuegos.com%2F&mp_timezone=Europe%2FMadrid&mp_view_type=
SWF URL: https://www.minijuegosgratis.com/flash1234/no_hotlink/parkingmania.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 Edg/116.0.1938.62
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-09-01
Channel: nightly
Built: 2023-09-01T00:22:25.963Z
Commit: 5edba670de11203b01ec8cd8ff95f777be63230d
Is extension: false

# Metadata
width: 800
height: 480
frameRate: 60
numFrames: 2
swfVersion: 11
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 6872196

**Comment by SuchAFuriousDeath** [comment]
Fixed by #13537.
