### ISSUE TITLE
Error on http://www.dinodan.com/raise-a-dino.html

### ISSUE THREAD

**Issue by Scourgeface** [ruffle-rs/ruffle#13052]
# Error Info
Error name: Error
Error message: panicked at 'Unexpected non-object value in object vector', core/src/avm2/amf.rs:99:34
Error stack:
```
Error: panicked at 'Unexpected non-object value in object vector', core/src/avm2/amf.rs:99:34
    at imports.wbg.__wbg_new_d258248ed531ff54 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:2406:21)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h3959f346f7109267 (wasm://wasm/0306993a:wasm-function[9258]:0x9138dc)
    at std::panicking::rust_panic_with_hook::h7601402c0a383194 (wasm://wasm/0306993a:wasm-function[6015]:0x8139ef)
    at core::panicking::panic_fmt::h6dad0405f48e39e2 (wasm://wasm/0306993a:wasm-function[9098]:0x90efb5)
    at core::option::expect_failed::h980aad86598061bd (wasm://wasm/0306993a:wasm-function[7989]:0x8cd26c)
    at ruffle_core::avm2::amf::serialize_value::h0c6e51a27b6adf32 (wasm://wasm/0306993a:wasm-function[757]:0x264ea4)
    at ruffle_core::avm2::globals::flash::utils::byte_array::write_object::hb3b6060792d31756 (wasm://wasm/0306993a:wasm-function[1535]:0x463972)
    at ruffle_core::avm2::function::Executable::exec::hebfea0b7e1b2fb7d (wasm://wasm/0306993a:wasm-function[829]:0x2b778d)
    at ruffle_core::avm2::object::TObject::call_property::hf16af7f608ae0aae (wasm://wasm/0306993a:wasm-function[1085]:0x37b3a8)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::h06fdc5dac2b91b2a (wasm://wasm/0306993a:wasm-function[2769]:0x616794)
```
AVM2 stack:
```
    at flash.utils::ByteArray/flash::utils::ByteArray::writeObject()
    at ca.sinkingship.common.util::SerializationUtils$/serializeToString()
    at ca.sinkingship.rad.game.environment::EnvironmentData/getDinoDataBase64()
    at ca.sinkingship.rad.web::DatabaseManager/saveRadToDatabase()
    at ca.sinkingship.rad.web::DatabaseManager/handlePointSaveComplete()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Apple, Apple M2 Pro, OpenGL 4.1)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: http://www.dinodan.com/raise-a-dino.html
SWF URL: http://www.dinodan.com/swf/wrapper/newNav.swf

# Browser Info
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
Platform: MacIntel
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-09-03
Channel: nightly
Built: 2023-09-03T00:19:43.518Z
Commit: 2996f97578f4b9541029f0318d7b87a60664cf23
Is extension: true

# Metadata
width: 1024
height: 768
frameRate: 24
numFrames: 31
swfVersion: 15
backgroundColor: #FFFFFF
isActionScript3: true
uncompressedLength: 459583

**Comment by SuchAFuriousDeath** [comment]
Fixed by #13537.
