### ISSUE TITLE
Error on http://files3.swfchan.com/ruffle/index.html

### ISSUE THREAD

**Issue by alexander-clawthorne** [ruffle-rs/ruffle#13059]
# Error Info
Error name: Error
Error message: panicked at 'No script object for display object', core/src/avm1/activation.rs:404:18
Error stack:
```
Error: panicked at 'No script object for display object', core/src/avm1/activation.rs:404:18
    at W.n.wbg.__wbg_new_d258248ed531ff54 (http://files3.swfchan.com/ruffle/core.ruffle.ae229442625544714080.js:1:51449)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h8b0b313a9b2fe55f (wasm://wasm/02f98b1a:wasm-function[9186]:0x8e7136)
    at std::panicking::rust_panic_with_hook::h5cee2a9564faeb6d (wasm://wasm/02f98b1a:wasm-function[6037]:0x7f8a2f)
    at core::panicking::panic_fmt::h8a19fa1eb63fbb67 (wasm://wasm/02f98b1a:wasm-function[9022]:0x8e296a)
    at ruffle_core::display_object::edit_text::EditText::try_bind_text_field_variable::hbc601c520fca1d9a (wasm://wasm/02f98b1a:wasm-function[3798]:0x6d84c0)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::h915d8fe0eef04769 (wasm://wasm/02f98b1a:wasm-function[3233]:0x67b9b5)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::hca2c85aaf6295955 (wasm://wasm/02f98b1a:wasm-function[1045]:0x3618b8)
    at ruffle_core::display_object::movie_clip::MovieClip::place_object::h2a17ef3feef4597c (wasm://wasm/02f98b1a:wasm-function[1882]:0x50af19)
    at <ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::enter_frame::hce8c2b09d85b3b06 (wasm://wasm/02f98b1a:wasm-function[817]:0x2ae9f2)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::hca2c85aaf6295955 (wasm://wasm/02f98b1a:wasm-function[1045]:0x3618f4)
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (AMD, AMD Custom GPU 0405 (vangogh LLVM 15.0.7), OpenGL 4.6)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 8192, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: http://files3.swfchan.com/ruffle/index.html?http://files3.swfchan.com/Mad%20Karate%20Man.swfSWF=-_=_-=CHAN%3C21447930-2484689280-9127274611SWF=_-=-_=CHANnone

# Browser Info
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-08-01
Channel: nightly
Built: 2023-08-01T00:22:57.291Z
Commit: 2621dd78eefab17e98dc03fafa25ed421784a712
Is extension: false

# Metadata
width: 550
height: 400
frameRate: 60
numFrames: 2
swfVersion: 10
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 1069800

**Comment by Lord-McSweeney** [comment]
This seems to be working now
