### ISSUE TITLE
Error on https://n-5oiodrgsmvkz5qd5feq5dsqnvrlo2b2ompgc73y-0lu-script.googleusercontent.com/userCodeAppPanel

### ISSUE THREAD

**Issue by godzilla214** [ruffle-rs/ruffle#13162]
# Error Info
Error name: Error
Error message: panicked at 'Reference still held to rc', /home/runner/.cargo/git/checkouts/rust-flash-lso-7db697fbf6bd96f3/3669a35/flash-lso/src/amf3/read.rs:260:18
Error stack:
```
Error: panicked at 'Reference still held to rc', /home/runner/.cargo/git/checkouts/rust-flash-lso-7db697fbf6bd96f3/3669a35/flash-lso/src/amf3/read.rs:260:18
    at V.n.wbg.__wbg_new_d258248ed531ff54 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.ca014f3bb2f19b3cfe1a.js:1:51843)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h2e7c106a4724653e (wasm://wasm/030be46a:wasm-function[9327]:0x925500)
    at std::panicking::rust_panic_with_hook::h7601402c0a383194 (wasm://wasm/030be46a:wasm-function[6094]:0x824f58)
    at core::panicking::panic_fmt::h6dad0405f48e39e2 (wasm://wasm/030be46a:wasm-function[9163]:0x920b12)
    at core::option::expect_failed::h980aad86598061bd (wasm://wasm/030be46a:wasm-function[8059]:0x8def93)
    at flash_lso::amf3::read::AMF3Decoder::parse_single_element::h6aab104467b704cd (wasm://wasm/030be46a:wasm-function[563]:0x110b0b)
    at <F as nom::internal::Parser<I,O,E>>::parse::hdf1cb4c7014a9237 (wasm://wasm/030be46a:wasm-function[3835]:0x6f5bc8)
    at flash_lso::read::Reader::parse::h5f4f050ee7ed8eeb (wasm://wasm/030be46a:wasm-function[4284]:0x734f8e)
    at ruffle_core::avm2::globals::flash::net::shared_object::get_local::haebd289abffaa752 (wasm://wasm/030be46a:wasm-function[564]:0x112869)
    at ruffle_core::avm2::function::Executable::exec::h99b6131666fb1feb (wasm://wasm/030be46a:wasm-function[837]:0x2c0c17)
```
AVM2 stack:
```
    at flash.net::SharedObject/flash::net::SharedObject::getLocal()
    at DoomGame/initGame()
    at DoomGame/tickPreloader()
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) Iris(R) Xe Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://n-5oiodrgsmvkz5qd5feq5dsqnvrlo2b2ompgc73y-0lu-script.googleusercontent.com/userCodeAppPanel
SWF URL: https://godzilla214.github.io/gsiteswf/doom-1.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Platform: Win32
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-09-12
Channel: nightly
Built: 2023-09-12T00:25:43.153Z
Commit: 53199a51164ce338a259f1dba5a850eb7280cf92
Is extension: false

# Metadata
width: 960
height: 600
frameRate: 35
numFrames: 2
swfVersion: 10
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 6421559

**Comment by CUB3D** [comment]
I tested this on the latest version I could get to build (2024-05-01) as well as latest (e353fdc1c3e47939807e1d9b109050ed68ca5d62) and could't rcreate this on either that version or on latest, tried both saving and loading. Issue might only be present further in but at ~0.3 fps this isn't easy to test
