### ISSUE TITLE
Panic tesselating morphed shapes

### ISSUE THREAD

**Issue by Dinnerbone** [ruffle-rs/ruffle#1318]
In movies such as https://www.newgrounds.com/portal/view/193 or https://www.newgrounds.com/portal/view/101407, Ruffle will panic in debug mode:
```
thread 'main' panicked at 'assertion failed: a != b', C:\Users\dinne\.cargo\registry\src\github.com-1ecc6299db9ec823\lyon_tessellation-0.16.2\src\geometry_builder.rs:520:9
stack backtrace:
   0: std::panicking::begin_panic<str*>
             at C:\Users\dinne\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panicking.rs:497
   1: lyon_tessellation::geometry_builder::{{impl}}::add_triangle<ruffle_render_wgpu::GPUVertex,u16,ruffle_render_wgpu::RuffleVertexCtor>
             at C:\Users\dinne\.cargo\registry\src\github.com-1ecc6299db9ec823\lyon_tessellation-0.16.2\src\geometry_builder.rs:520
   2: lyon_tessellation::stroke::StrokeBuilder::tessellate_round_join
             at C:\Users\dinne\.cargo\registry\src\github.com-1ecc6299db9ec823\lyon_tessellation-0.16.2\src\stroke.rs:1065
   3: lyon_tessellation::stroke::StrokeBuilder::tessellate_join
             at C:\Users\dinne\.cargo\registry\src\github.com-1ecc6299db9ec823\lyon_tessellation-0.16.2\src\stroke.rs:902
   4: lyon_tessellation::stroke::StrokeBuilder::edge_to
             at C:\Users\dinne\.cargo\registry\src\github.com-1ecc6299db9ec823\lyon_tessellation-0.16.2\src\stroke.rs:646
   5: lyon_tessellation::stroke::{{impl}}::line_to
             at C:\Users\dinne\.cargo\registry\src\github.com-1ecc6299db9ec823\lyon_tessellation-0.16.2\src\stroke.rs:248
   6: lyon_path::builder::PathBuilder::path_event<lyon_tessellation::stroke::StrokeBuilder>
             at C:\Users\dinne\.cargo\registry\src\github.com-1ecc6299db9ec823\lyon_path-0.16.2\src\builder.rs:133
   7: lyon_tessellation::stroke::StrokeTessellator::tessellate<lyon_path::path::Iter>
             at C:\Users\dinne\.cargo\registry\src\github.com-1ecc6299db9ec823\lyon_tessellation-0.16.2\src\stroke.rs:109
   8: lyon_tessellation::stroke::StrokeTessellator::tessellate_path<lyon_path::path::Path*>
             at C:\Users\dinne\.cargo\registry\src\github.com-1ecc6299db9ec823\lyon_tessellation-0.16.2\src\stroke.rs:160
   9: ruffle_render_wgpu::WgpuRenderBackend<ruffle_render_wgpu::target::TextureTarget>::register_shape_internal<ruffle_render_wgpu::target::TextureTarget>
             at W:\personal\ruffle\render\wgpu\src\lib.rs:605
  10: ruffle_render_wgpu::{{impl}}::register_shape<ruffle_render_wgpu::target::TextureTarget>
             at W:\personal\ruffle\render\wgpu\src\lib.rs:765
  11: ruffle_core::display_object::morph_shape::MorphShapeStatic::register_ratio
             at W:\personal\ruffle\core\src\display_object\morph_shape.rs:271
  12: ruffle_core::display_object::morph_shape::MorphShapeStatic::from_swf_tag
             at W:\personal\ruffle\core\src\display_object\morph_shape.rs:134
  13: ruffle_core::display_object::movie_clip::MovieClipData::define_morph_shape
             at W:\personal\ruffle\core\src\display_object\movie_clip.rs:2181
  14: ruffle_core::display_object::movie_clip::{{impl}}::preload::{{closure}}
             at W:\personal\ruffle\core\src\display_object\movie_clip.rs:256
  15: ruffle_core::tag_utils::decode_tags<slice<u8>*,closure-0>
             at W:\personal\ruffle\core\src\tag_utils.rs:304
  16: ruffle_core::display_object::movie_clip::MovieClip::preload
             at W:\personal\ruffle\core\src\display_object\movie_clip.rs:392
  17: ruffle_core::player::{{impl}}::preload::{{closure}}
             at W:\personal\ruffle\core\src\player.rs:791
  18: ruffle_core::player::{{impl}}::mutate_with_update_context::{{closure}}<closure-0,tuple<>>
             at W:\personal\ruffle\core\src\player.rs:1145
  19: ruffle_core::player::GcArena::mutate<closure-0,tuple<>>
             at C:\Users\dinne\.cargo\registry\src\github.com-1ecc6299db9ec823\gc-arena-0.2.0\src\arena.rs:161
  20: ruffle_core::player::Player::mutate_with_update_context<closure-0,tuple<>>
             at W:\personal\ruffle\core\src\player.rs:1092
  21: ruffle_core::player::Player::preload
             at W:\personal\ruffle\core\src\player.rs:788
  22: ruffle_core::player::Player::set_root_movie
             at W:\personal\ruffle\core\src\player.rs:409
  23: exporter::take_screenshot
             at .\src\main.rs:123
  24: exporter::capture_multiple_swfs
             at .\src\main.rs:297
  25: exporter::main
```

**Comment by relrelb** [comment]
Fixed by #2264.
