### ISSUE TITLE
Error on https://web.archive.org/web/20090219234214/http://www.waltswarning.com/

### ISSUE THREAD

**Issue by Filename99** [ruffle-rs/ruffle#13186]
# Error Info
Error name: Error
Error message: Failed to fetch: http://media.amctv.com/waltswarning/Menu.swf
Error stack:
```
Error: Failed to fetch: http://media.amctv.com/waltswarning/Menu.swf
    at Je.displayRootMovieDownloadFailedMessage (https://web.archive.org/_static/js/ruffle.js:2:349472)
    at W.n.wbg.__wbg_displayRootMovieDownloadFailedMessage_ed4ad3ae9522c8a3 (https://web.archive.org/_static/js/core.ruffle.92e6746d93be1e95cd77.js:1:7014)
    at <ruffle_web::ui::WebUiBackend as ruffle_core::backend::ui::UiBackend>::display_root_movie_download_failed_message::hdc7b2467229066fb (wasm://wasm/02f98346:wasm-function[10986]:0x92605f)
    at ruffle_core::loader::Loader::root_movie_loader::{{closure}}::h27e7a80404b1a839 (wasm://wasm/02f98346:wasm-function[870]:0x2ef832)
    at <ruffle_web::navigator::WebNavigatorBackend as ruffle_core::backend::navigator::NavigatorBackend>::spawn_future::{{closure}}::h59fccc39c587f869 (wasm://wasm/02f98346:wasm-function[1127]:0x3922c5)
    at wasm_bindgen_futures::queue::Queue::new::{{closure}}::hbb66f7af2d96f794 (wasm://wasm/02f98346:wasm-function[3910]:0x6ee501)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h0219aedcaa846c26 (wasm://wasm/02f98346:wasm-function[9841]:0x90423d)
    at closure4161 externref shim (wasm://wasm/02f98346:wasm-function[10160]:0x9091a7)
    at D (https://web.archive.org/_static/js/core.ruffle.92e6746d93be1e95cd77.js:1:2985)
    at f (https://web.archive.org/_static/js/core.ruffle.92e6746d93be1e95cd77.js:1:2511)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (AMD, AMD Radeon(TM) Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }
Player type: Object
SWF URL: http://media.amctv.com/waltswarning/Menu.swf
Param quality: high
Param scale: noscale
Param allowscriptaccess: always
Param bgcolor: #000000
Param allowfullscreen: true
Param flashvars: amc=1
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined

# Page Info
Page URL: https://web.archive.org/web/20090219234214/http://www.waltswarning.com/
SWF URL: http://media.amctv.com/waltswarning/Menu.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-08-02
Channel: nightly
Built: 2023-08-02T00:22:54.390Z
Commit: 006393c5816e68b54c6720fcd8e657009cfb90d8
Is extension: false

# Metadata

**Comment by Lord-McSweeney** [comment]
This looks like a network issue unrelated to Ruffle.
