### ISSUE TITLE
CCTV access

### ISSUE THREAD

**Issue by Trevork27** [ruffle-rs/ruffle#1325]
# Error Info
Error name: Error
Error message: Unknown panic
Error stack:
```
Error: Unknown panic
    at Object.H (chrome-extension://hgkcglcbhkibggmmgklggfkcmgfidlbb/dist/core.ruffle.js:1:31501)
    at __wbg_new_df6e6ab7a65c4c4d (chrome-extension://hgkcglcbhkibggmmgklggfkcmgfidlbb/dist/ruffle.js:1:655)
    at chrome-extension://hgkcglcbhkibggmmgklggfkcmgfidlbb/dist/6a20871cdcbc9c57534a.module.wasm:wasm-function[1435]:0x234483
    at chrome-extension://hgkcglcbhkibggmmgklggfkcmgfidlbb/dist/6a20871cdcbc9c57534a.module.wasm:wasm-function[1330]:0x224357
    at chrome-extension://hgkcglcbhkibggmmgklggfkcmgfidlbb/dist/6a20871cdcbc9c57534a.module.wasm:wasm-function[3610]:0x2ceaaf
    at chrome-extension://hgkcglcbhkibggmmgklggfkcmgfidlbb/dist/6a20871cdcbc9c57534a.module.wasm:wasm-function[2970]:0x2b9f02
    at chrome-extension://hgkcglcbhkibggmmgklggfkcmgfidlbb/dist/6a20871cdcbc9c57534a.module.wasm:wasm-function[3786]:0x2d1bf4
    at chrome-extension://hgkcglcbhkibggmmgklggfkcmgfidlbb/dist/6a20871cdcbc9c57534a.module.wasm:wasm-function[3915]:0x2d37dc
    at chrome-extension://hgkcglcbhkibggmmgklggfkcmgfidlbb/dist/6a20871cdcbc9c57534a.module.wasm:wasm-function[3274]:0x2c6874
    at chrome-extension://hgkcglcbhkibggmmgklggfkcmgfidlbb/dist/6a20871cdcbc9c57534a.module.wasm:wasm-function[2858]:0x2b3d1f
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: JaViewer.swf?player_max=4
Param player_max: 8
Param allowFullScreen: true
Param flashvars: player_max=8&usr=admin&pwd=Spain2010
Attribute 0: [object Attr]
Attribute 1: [object Attr]
Attribute 2: [object Attr]
Attribute 3: [object Attr]
Attribute 4: [object Attr]
Attribute 5: [object Attr]

# Page Info
Page URL: http://192.168.0.2/view2.html

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36
OS: Win32

# Ruffle Info
Ruffle version: 0.1.0
Ruffle source: undefined

**Comment by Justin-CB** [comment]
There's not a whole lot we can do to poke at this if it's hosted on your local network. We might be able to help you if you upload the SWF, tho.

**Comment by Trevork27** [comment]
Hi Justin,

Thanks for looking at it. 

Will download a browser with flash and not allow it to update!

**Comment by Justin-CB** [comment]
Flash has a kill switch that will activate at the end of 2020.
