### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by Holixx** [ruffle-rs/ruffle#13283]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create texture object"', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.17.0/src/gles/device.rs:705:52
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create texture object"', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.17.0/src/gles/device.rs:705:52
    at V.n.wbg.__wbg_new_d258248ed531ff54 (https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.94ad4a844ac59e0f95cb.js:1:51844)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h57def9a78408b97f (wasm://wasm/030ad9d6:wasm-function[9339]:0x920b83)
    at std::panicking::rust_panic_with_hook::he017c20114c82dea (wasm://wasm/030ad9d6:wasm-function[6103]:0x822330)
    at core::panicking::panic_fmt::h7859ddfa497c0e61 (wasm://wasm/030ad9d6:wasm-function[9175]:0x91c19a)
    at core::result::unwrap_failed::h99b8d970e94e9f11 (wasm://wasm/030ad9d6:wasm-function[7260]:0x88aeff)
    at <T as wgpu::context::DynContext>::device_create_texture::hd75bf96a78085521 (wasm://wasm/030ad9d6:wasm-function[6783]:0x8627f3)
    at wgpu::Device::create_texture::h4bef13ee00489352 (wasm://wasm/030ad9d6:wasm-function[5160]:0x7cbe98)
    at <ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::create_empty_texture::h57076720cb6bc923 (wasm://wasm/030ad9d6:wasm-function[4997]:0x7bdb69)
    at ruffle_core::display_object::render_base::h68dc2f2671d0b7e3 (wasm://wasm/030ad9d6:wasm-function[564]:0x1118f4)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render::hff0fbf6b3b700c8f (wasm://wasm/030ad9d6:wasm-function[6675]:0x853624)
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel Open Source Technology Center, Mesa DRI Intel(R) UHD Graphics 600 (GLK 2), OpenGL ES 3.2)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | TEXTURE_COMPRESSION_ASTC_HDR | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 4096, max_texture_dimension_2d: 4096, max_texture_dimension_3d: 1024, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.67&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1695474658%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F592000%2F592473_MadnessGame_ULTIMATE.swf%3F1507662264%22%2C%22vars%22%3A%7B%22ngio_session_id%22%3A%2297775969.6c2a3ae6bee05636b58054711803d0020a150e55c7305e%22%2C%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%22650eeb6ea5ef6%22%2C%22NewgroundsAPI_SessionID%22%3A%22SwiRek1hlyZlv0U4LIyh1c0f5e19d80cd66e1af419f556fe00cd257b93f1WzHp%22%2C%22NewgroundsAPI_UserName%22%3A%22IwantOli%22%2C%22NewgroundsAPI_UserID%22%3A18977527%2C%22ng_username%22%3A%22IwantOli%22%7D%2C%22width%22%3A850%2C%22height%22%3A530%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F592000%2Fflash_592473_card.webp%3Ff1669742379%22%2C%22warnOnUnsupportedContent%22%3Afalse%7D
SWF URL: https://uploads.ungrounded.net/592000/592473_MadnessGame_ULTIMATE.swf?1507662264

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-09-23
Channel: nightly
Built: 2023-09-23T00:20:20.140Z
Commit: dc537584880b733b65765088d71ed88e443be7b6
Is extension: false

# Metadata
width: 850
height: 530
frameRate: 30
numFrames: 30
swfVersion: 10
backgroundColor: #FFFFFF
isActionScript3: false
uncompressedLength: 20491352

**Comment by Lord-McSweeney** [comment]
Duplicate of #12236
