### ISSUE TITLE
Error on https://f.kbhgames.com/RS/game.php

### ISSUE THREAD

**Issue by fsgfdg432423** [ruffle-rs/ruffle#13297]
# Error Info
Error name: Error
Error message: panicked at 'No script object for display object', core/src/avm1/activation.rs:404:18
Error stack:
```
Error: panicked at 'No script object for display object', core/src/avm1/activation.rs:404:18
    at V.n.wbg.__wbg_new_d258248ed531ff54 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.38d6cc97fe16314132cf.js:1:51844)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h57def9a78408b97f (wasm://wasm/030bf8fe:wasm-function[9332]:0x925370)
    at std::panicking::rust_panic_with_hook::he017c20114c82dea (wasm://wasm/030bf8fe:wasm-function[6098]:0x825e87)
    at core::panicking::panic_fmt::h7859ddfa497c0e61 (wasm://wasm/030bf8fe:wasm-function[9168]:0x920959)
    at ruffle_core::display_object::edit_text::EditText::try_bind_text_field_variable::h14eb1f832a121a6f (wasm://wasm/030bf8fe:wasm-function[3219]:0x68853a)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::h879e95c3fa54541e (wasm://wasm/030bf8fe:wasm-function[3138]:0x6769e4)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::h06b11f5af92d9a74 (wasm://wasm/030bf8fe:wasm-function[1063]:0x36e61f)
    at ruffle_core::display_object::movie_clip::MovieClip::place_object::he6100c482f7cb25f (wasm://wasm/030bf8fe:wasm-function[1893]:0x52788c)
    at <ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::enter_frame::h8c61286ee075faa9 (wasm://wasm/030bf8fe:wasm-function[662]:0x1e25a5)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::h06b11f5af92d9a74 (wasm://wasm/030bf8fe:wasm-function[1063]:0x36e65b)
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) HD Graphics Family Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 600, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://f.kbhgames.com/RS/game.php?r=//f.kbhgames.com/2018/swf/halflifemadness.swf&w=600&h=400&warnsupport=true
SWF URL: https://f.kbhgames.com/2018/swf/halflifemadness.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-09-24
Channel: nightly
Built: 2023-09-24T00:20:46.080Z
Commit: 8aec2f17037506d9d8ecf36cbc4908a061652daf
Is extension: false

# Metadata
width: 600
height: 400
frameRate: 30
numFrames: 2
swfVersion: 10
backgroundColor: #CCCCCC
isActionScript3: true
uncompressedLength: 950408

**Comment by Lord-McSweeney** [comment]
Fixed by #11005
