### ISSUE TITLE
Error on https://www8.agame.com/mirror/flash/b/battle-arena-artic/index.html

### ISSUE THREAD

**Issue by Monostegotops** [ruffle-rs/ruffle#13328]
# Error Info
Error name: Error
Error message: panicked at 'No script object for display object', core/src/avm1/activation.rs:404:18
Error stack:
```
Error: panicked at 'No script object for display object', core/src/avm1/activation.rs:404:18
    at imports.wbg.__wbg_new_d258248ed531ff54 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:2414:21)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hd6a9dc3a3c36784e (wasm://wasm/030baad6:wasm-function[9335]:0x924a1b)
    at std::panicking::rust_panic_with_hook::he017c20114c82dea (wasm://wasm/030baad6:wasm-function[6109]:0x826933)
    at core::panicking::panic_fmt::h7859ddfa497c0e61 (wasm://wasm/030baad6:wasm-function[9171]:0x920004)
    at ruffle_core::display_object::edit_text::EditText::try_bind_text_field_variable::hf16794cadeba3715 (wasm://wasm/030baad6:wasm-function[3237]:0x68992c)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::hcf245b440e59dee2 (wasm://wasm/030baad6:wasm-function[3149]:0x6769ca)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::h9d307400f60e61a9 (wasm://wasm/030baad6:wasm-function[1055]:0x364864)
    at ruffle_core::display_object::movie_clip::MovieClip::place_object::h035ad4329a8c6fa9 (wasm://wasm/030baad6:wasm-function[1890]:0x51dadd)
    at <ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::enter_frame::h680eb3afaeafa74f (wasm://wasm/030baad6:wasm-function[832]:0x2b7580)
    at <ruffle_core::display_object::loader_display::LoaderDisplay as ruffle_core::display_object::TDisplayObject>::enter_frame::h3132f2c0e7e8f626 (wasm://wasm/030baad6:wasm-function[2633]:0x5f255d)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel Inc., Intel(R) Iris(TM) Plus Graphics 645, OpenGL 4.1)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }
Player type: Object
SWF URL: bin/swf/games/battle/game-battle-arena.swf
Param allowScriptAccess: always
Param flashvars: home=http://webosaurs.com/campaign/90850/&video=http://webosaurs.com/campaign/90850/video&btid=23
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined

# Page Info
Page URL: https://www8.agame.com/mirror/flash/b/battle-arena-artic/index.html
SWF URL: https://www8.agame.com/mirror/flash/b/battle-arena-artic/bin/swf/games/battle/game-battle-arena.swf

# Browser Info
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
Platform: MacIntel
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-09-26
Channel: nightly
Built: 2023-09-26T00:20:19.266Z
Commit: 7e4e4d4c5b1f55614b98b33b7cc6f70567c52bab
Is extension: true

# Metadata
width: 800
height: 600
frameRate: 30
numFrames: 1
swfVersion: 9
backgroundColor: #FFFFFF
isActionScript3: true
uncompressedLength: 807541

**Comment by Lord-McSweeney** [comment]
This seems to be working now
