### ISSUE TITLE
Error on https://game81541.konggames.com/games/Vitaly/endless-war-defense/frame/08a185bc-6f3e-46c8-9176-4a1234f47a41/

### ISSUE THREAD

**Issue by MoxyK** [ruffle-rs/ruffle#13332]
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', core/src/bitmap/bitmap_data.rs:319:45
Error stack:
```
Error: panicked at 'already borrowed: BorrowMutError', core/src/bitmap/bitmap_data.rs:319:45
    at V.n.wbg.__wbg_new_d258248ed531ff54 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.01e3aa49bccd1859a908.js:1:51844)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hd6a9dc3a3c36784e (wasm://wasm/030baad6:wasm-function[9335]:0x924a1b)
    at std::panicking::rust_panic_with_hook::he017c20114c82dea (wasm://wasm/030baad6:wasm-function[6109]:0x826933)
    at core::panicking::panic_fmt::h7859ddfa497c0e61 (wasm://wasm/030baad6:wasm-function[9171]:0x920032)
    at core::result::unwrap_failed::h99b8d970e94e9f11 (wasm://wasm/030baad6:wasm-function[7255]:0x88f41d)
    at ruffle_core::bitmap::bitmap_data::wrapper::BitmapDataWrapper::sync::hb5442a4d1246a38e (wasm://wasm/030baad6:wasm-function[4231]:0x726c53)
    at ruffle_core::bitmap::bitmap_data::wrapper::BitmapDataWrapper::read_area::h0f348e643dfac14a (wasm://wasm/030baad6:wasm-function[5721]:0x806d6c)
    at ruffle_core::bitmap::operations::hit_test_bitmapdata::h27d16eeb1d35e0e6 (wasm://wasm/030baad6:wasm-function[2548]:0x5df796)
    at ruffle_core::avm2::globals::flash::display::bitmap_data::hit_test::hd1853cb1facadfce (wasm://wasm/030baad6:wasm-function[676]:0x2025fe)
    at ruffle_core::avm2::function::Executable::exec::hc5c114b3f5fd1a13 (wasm://wasm/030baad6:wasm-function[836]:0x2bbb6f)
```
AVM2 stack:
```
    at flash.display::BitmapData/flash::display::BitmapData::hitTest()
    at GameArea$/getIntersectingUnit()
    at APC/descentAI()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA GeForce GTX 960 Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://game81541.konggames.com/games/Vitaly/endless-war-defense/frame/08a185bc-6f3e-46c8-9176-4a1234f47a41/?kongregate_host=www.kongregate.com
SWF URL: https://game81541.konggames.com/gamez/0008/1541/live/ewd_1k.swf?kongregate_game_version=1280138922

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-09-26
Channel: nightly
Built: 2023-09-26T00:20:19.266Z
Commit: 7e4e4d4c5b1f55614b98b33b7cc6f70567c52bab
Is extension: false

# Metadata
width: 800
height: 600
frameRate: 30
numFrames: 5
swfVersion: 10
backgroundColor: #FFFFFF
isActionScript3: true
uncompressedLength: 4113357

**Comment by Lord-McSweeney** [comment]
This seems to be working now
