### ISSUE TITLE
Error on https://www.minijuegos.com/helpers/game/sandbox.php

### ISSUE THREAD

**Issue by David27051304** [ruffle-rs/ruffle#13339]
# Error Info
Error name: Error
Error message: panicked at 'No script object for display object', core/src/avm1/activation.rs:404:18
Error stack:
```
Error: panicked at 'No script object for display object', core/src/avm1/activation.rs:404:18
    at V.n.wbg.__wbg_new_d258248ed531ff54 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.01e3aa49bccd1859a908.js:1:51844)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hd6a9dc3a3c36784e (wasm://wasm/030baad6:wasm-function[9335]:0x924a1b)
    at std::panicking::rust_panic_with_hook::he017c20114c82dea (wasm://wasm/030baad6:wasm-function[6109]:0x826933)
    at core::panicking::panic_fmt::h7859ddfa497c0e61 (wasm://wasm/030baad6:wasm-function[9171]:0x920004)
    at ruffle_core::display_object::edit_text::EditText::try_bind_text_field_variable::hf16794cadeba3715 (wasm://wasm/030baad6:wasm-function[3237]:0x68992c)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::hcf245b440e59dee2 (wasm://wasm/030baad6:wasm-function[3149]:0x6769ca)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::h9d307400f60e61a9 (wasm://wasm/030baad6:wasm-function[1055]:0x364864)
    at ruffle_core::display_object::movie_clip::MovieClip::place_object::h035ad4329a8c6fa9 (wasm://wasm/030baad6:wasm-function[1890]:0x51dadd)
    at <ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::enter_frame::h680eb3afaeafa74f (wasm://wasm/030baad6:wasm-function[832]:0x2b7580)
    at ruffle_core::loader::Loader::movie_loader_complete::hff4a4ec70f84a47d (wasm://wasm/030baad6:wasm-function[683]:0x20c34c)
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) UHD Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 1000, height: 550, depth_or_array_layers: 1 }

# Page Info
Page URL: https://www.minijuegos.com/helpers/game/sandbox.php?mp_assets=https%3A%2F%2Fs2.minijuegosgratis.com%2F&mp_embed=0&mp_game_id=22937&mp_game_uid=feed-us-4&mp_game_url=https%3A%2F%2Fwww.minijuegos.com%2Fembed%2Ffeed-us-4&mp_int=1&mp_locale=es_ES&mp_player_type=FLASH&mp_player_url=aHR0cHM6Ly93d3cubWluaWp1ZWdvc2dyYXRpcy5jb20vdjMvZ2FtZXMvZ2FtZXMvcHJvZC8yMjkzNy9mZWVkdXM0LnN3Zg%3D%3D&mp_site_https_url=https%3A%2F%2Fwww.minijuegos.com%2F&mp_site_name=minijuegos.com&mp_site_url=https%3A%2F%2Fwww.minijuegos.com%2F&mp_timezone=America%2FCosta_Rica&mp_view_type=
SWF URL: https://www.minijuegosgratis.com/v3/games/games/prod/22937/feedus4.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-09-26
Channel: nightly
Built: 2023-09-26T00:20:19.266Z
Commit: 7e4e4d4c5b1f55614b98b33b7cc6f70567c52bab
Is extension: false

# Metadata
width: 800
height: 440
frameRate: 50
numFrames: 2
swfVersion: 17
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 5923021

**Comment by Lord-McSweeney** [comment]
Was fixed by #11005
