### ISSUE TITLE
Website error

### ISSUE THREAD

**Issue by Giuli26112002** [ruffle-rs/ruffle#1336]
bug, the website didn't load 

error log:
# Error Info
Error name: Error
Error message: Unknown panic
Error stack:
```
Error: Unknown panic
    at Object.H (http://www.webgeo.de/common/vendor/ruffle/core.ruffle.0cf6244766a84a15c234.js:1:31494)
    at __wbg_new_df6e6ab7a65c4c4d (http://www.webgeo.de/common/vendor/ruffle/ruffle.js:1:655)
    at http://www.webgeo.de/common/vendor/ruffle/1108163a500b7b584721.module.wasm:wasm-function[1435]:0x234483
    at http://www.webgeo.de/common/vendor/ruffle/1108163a500b7b584721.module.wasm:wasm-function[1330]:0x224357
    at http://www.webgeo.de/common/vendor/ruffle/1108163a500b7b584721.module.wasm:wasm-function[3610]:0x2ceaaf
    at http://www.webgeo.de/common/vendor/ruffle/1108163a500b7b584721.module.wasm:wasm-function[2970]:0x2b9f02
    at http://www.webgeo.de/common/vendor/ruffle/1108163a500b7b584721.module.wasm:wasm-function[3786]:0x2d1bf4
    at http://www.webgeo.de/common/vendor/ruffle/1108163a500b7b584721.module.wasm:wasm-function[3915]:0x2d37dc
    at http://www.webgeo.de/common/vendor/ruffle/1108163a500b7b584721.module.wasm:wasm-function[3274]:0x2c6874
    at http://www.webgeo.de/common/vendor/ruffle/1108163a500b7b584721.module.wasm:wasm-function[2858]:0x2b3d1f
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: ./contents/g_003_01.swf
Param allowScriptAccess: sameDomain
Param movie: ./contents/g_003_01.swf
Param quality: high
Param bgcolor: #ffffff
Attribute 0: [object Attr]
Attribute 1: [object Attr]
Attribute 2: [object Attr]
Attribute 3: [object Attr]
Attribute 4: [object Attr]
Attribute 5: [object Attr]

# Page Info
Page URL: http://www.webgeo.de/g_003/#1

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36
OS: Win32

# Ruffle Info
Ruffle version: 0.1.0
Ruffle source: undefined
![Screenshot_6](https://user-images.githubusercontent.com/63163602/96335098-38cbd580-1076-11eb-831b-b6723565a35c.png)

**Comment by Dinnerbone** [comment]
Can you please try this on the latest version and confirm if it's still an issue?

**Comment by Poopooracoocoo** [comment]
I think the error occurs when you click on the links: 
![image](https://user-images.githubusercontent.com/51363864/103169895-ebe55600-4893-11eb-8a7d-04dea9251cc1.png)

The error screen appeared briefly and then it redirected to that link. The crash screen only appeared once though. It must've been cached or something.

**Comment by n0samu** [comment]
This doesn't seem to be happening anymore, can anyone confirm?

**Comment by adrian17** [comment]
Confirmed :)
