### ISSUE TITLE
Error on https://www.newgrounds.com/portal/view/571250/group/107/play/53285

### ISSUE THREAD

**Issue by CoolDudeT** [ruffle-rs/ruffle#13370]
# Error Info
Error name: Error
Error message: panicked at 'Positive culling not implemented', core/src/avm2/globals/flash/display/graphics.rs:1057:13
Error stack:
```
Error: panicked at 'Positive culling not implemented', core/src/avm2/globals/flash/display/graphics.rs:1057:13
    at imports.wbg.__wbg_new_d258248ed531ff54 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:2414:21)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h327b73cb23b2fa83 (wasm://wasm/032916fa:wasm-function[9709]:0x98b9d0)
    at std::panicking::rust_panic_with_hook::he017c20114c82dea (wasm://wasm/032916fa:wasm-function[6338]:0x882c95)
    at core::panicking::panic_fmt::h7859ddfa497c0e61 (wasm://wasm/032916fa:wasm-function[9542]:0x986f14)
    at ruffle_core::avm2::globals::flash::display::graphics::draw_triangle_internal::had214c4479d4583c (wasm://wasm/032916fa:wasm-function[5800]:0x855d86)
    at ruffle_core::avm2::globals::flash::display::graphics::draw_triangles::h3f05c8b40da48926 (wasm://wasm/032916fa:wasm-function[765]:0x28af45)
    at ruffle_core::avm2::function::Executable::exec::h2e9745f664f735f5 (wasm://wasm/032916fa:wasm-function[785]:0x2b3212)
    at ruffle_core::avm2::object::TObject::call_property::h1261ae45f8c6d586 (wasm://wasm/032916fa:wasm-function[1124]:0x3b4fc9)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::h189cbaab9a3846f9 (wasm://wasm/032916fa:wasm-function[2875]:0x66e752)
    at ruffle_core::avm2::activation::Activation::run_actions::h63f2f2c43b4c5eb9 (wasm://wasm/032916fa:wasm-function[520]:0x2a6a7)
```
AVM2 stack:
```
    at flash.display::Graphics/flash::display::Graphics::drawTriangles()
    at Triangle3D/draw()
    at Object3D/draw()
    at MinecraftViewer/render()
    at MinecraftViewer/setDefaultPosition()
    at MinecraftViewer()
    at PreviewBox()
    at flash.display::MovieClip/flash::display::MovieClip::gotoAndStop()
    at Main/press_btnImportTXT()
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (ARM, Mali-G72, OpenGL ES 3.2)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | TEXTURE_COMPRESSION_ASTC_HDR | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 16383, max_texture_dimension_2d: 16383, max_texture_dimension_3d: 16383, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }
Player type: Object
SWF URL: https://uploads.ungrounded.net/571000/571250_SkinCreator.swf?1393965712
Param wmode: direct
Param allowscriptaccess: never
Param allowfullscreen: true
Param allowfullscreeninteractive: true
Param flashvars: ngio_session_id=48636565.940b38b46181569786ac7ac595b77b55827db3730c6d08&NewgroundsAPI_PublisherID=1&NewgroundsAPI_SandboxID=65181672cd7e6&NewgroundsAPI_SessionID=g6JQHb5H4kxbwlsp0GRk033c5751da6da87c3d7ad4f28bcff9fca9a45d59Efoq&NewgroundsAPI_UserName=CoolDudeT1&NewgroundsAPI_UserID=8154732&NewgroundsAPI_SaveFileID=53285&NewgroundsAPI_SaveGroupID=107&ng_username=CoolDudeT1
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined

# Page Info
Page URL: https://www.newgrounds.com/portal/view/571250/group/107/play/53285
SWF URL: https://uploads.ungrounded.net/571000/571250_SkinCreator.swf?1393965712

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-09-30
Channel: nightly
Built: 2023-09-30T00:20:30.366Z
Commit: f140e7a14b379993625b07524c4453ae98592384
Is extension: true

# Metadata
width: 700
height: 394
frameRate: 30
numFrames: 12
swfVersion: 10
backgroundColor: #E1E1E1
isActionScript3: true
uncompressedLength: 1412220

**Comment by Lord-McSweeney** [comment]
This doesn't panic anymore, as positive culling has been implemented. See #12001 for other rendering issues with the SWF
