### ISSUE TITLE
Error on https://archive.org/details/scratchx

### ISSUE THREAD

**Issue by Quartonos** [ruffle-rs/ruffle#13445]
# Error Info
Error name: Error
Error message: panicked at 'Unimplemented opcode Atan2', render/naga-pixelbender/src/lib.rs:1267:29
Error stack:
```
Error: panicked at 'Unimplemented opcode Atan2', render/naga-pixelbender/src/lib.rs:1267:29
    at U.n.wbg.__wbg_new_d258248ed531ff54 (https://cors.archive.org/cors/emularity_engine_v1/ruffle/core.ruffle.9a24273e0a1180f66c43.js:1:51428)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hc123de34c3ab8e83 (wasm://wasm/02d23fce:wasm-function[8764]:0x860673)
    at std::panicking::rust_panic_with_hook::h85b7f6628c291e12 (wasm://wasm/02d23fce:wasm-function[5747]:0x774433)
    at core::panicking::panic_fmt::hf5c4cd929d4aaa9e (wasm://wasm/02d23fce:wasm-function[8625]:0x85c1c3)
    at <ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::compile_pixelbender_shader::h95b2db2e396a9b88 (wasm://wasm/02d23fce:wasm-function[7081]:0x7e3c86)
    at ruffle_core::avm2::globals::flash::display::shader_data::init::h162166cce60fe321 (wasm://wasm/02d23fce:wasm-function[840]:0x2e25be)
    at ruffle_core::avm2::function::Executable::exec::h7fb4dd4d49b7c764 (wasm://wasm/02d23fce:wasm-function[738]:0x26d4ce)
    at ruffle_core::avm2::object::TObject::call_property::h1be5391cb8bbbf7a (wasm://wasm/02d23fce:wasm-function[1046]:0x37abc7)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::hd2beedd80eee577b (wasm://wasm/02d23fce:wasm-function[2699]:0x5c82cb)
    at ruffle_core::avm2::activation::Activation::run_actions::hf927b6b0d8284c02 (wasm://wasm/02d23fce:wasm-function[517]:0x29156)
```
AVM2 stack:
```
    at flash.display::ShaderData/flash::display::ShaderData::init()
    at flash.display::ShaderData()
    at flash.display::Shader/set byteCode()
    at flash.display::Shader()
    at filters::FilterPack()
    at scratch::ScratchStage()
    at Scratch/getScratchStage()
    at Scratch/initialize()
    at Scratch/jsAccessDetermined()
    at Scratch/determineJSAccess()
    at Scratch()
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (AMD, AMD Radeon (TM) Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 700, height: 480, depth_or_array_layers: 1 }

# Page Info
Page URL: https://archive.org/details/scratchx

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.47
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-07-08
Channel: nightly
Built: 2023-07-08T00:23:31.270Z
Commit: b38bd604dbe2051b7febd6e0c3435801beecfbed
Is extension: false

# Metadata
width: 800
height: 600
frameRate: 24
numFrames: 1
swfVersion: 19
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 8352792

**Comment by Lord-McSweeney** [comment]
`Atan2` was already implemented in #11896; Archive.org needs to update their Ruffle version
