### ISSUE TITLE
Assertion failure / panic when rendering masks

### ISSUE THREAD

**Issue by Dinnerbone** [ruffle-rs/ruffle#1347]
In the game [Chronicles of Raynor](https://www.newgrounds.com/portal/view/523350?emulate=flash), Ruffle panics with the following error:

```
thread 'main' panicked at 'assertion failed: self.mask_state == MaskState::NoMask ||
    self.mask_state == MaskState::DrawMaskedContent', W:\personal\ruffle\render\wgpu\src\lib.rs:1420:9
stack backtrace:
   0:     0x7ff7318f6959 - std::backtrace_rs::backtrace::dbghelp::trace
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:98
   1:     0x7ff7318f6959 - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ff7318f6959 - std::sys_common::backtrace::_print_fmt
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\sys_common\backtrace.rs:79
   3:     0x7ff7318f6959 - std::sys_common::backtrace::_print::{{impl}}::fmt
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\sys_common\backtrace.rs:58
   4:     0x7ff73190fdab - core::fmt::write
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\core\src\fmt\mod.rs:1082
   5:     0x7ff7318f2234 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\io\mod.rs:1514
   6:     0x7ff7318f99fb - std::sys_common::backtrace::_print
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\sys_common\backtrace.rs:61
   7:     0x7ff7318f99fb - std::sys_common::backtrace::print
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\sys_common\backtrace.rs:48
   8:     0x7ff7318f99fb - std::panicking::default_hook::{{closure}}
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\panicking.rs:200
   9:     0x7ff7318f9639 - std::panicking::default_hook
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\panicking.rs:219
  10:     0x7ff7318fa1df - std::panicking::rust_panic_with_hook
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\panicking.rs:569
  11:     0x7ff7318d0d7a - std::panicking::begin_panic::{{closure}}<str*>
                               at C:\Users\dinne\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panicking.rs:498
  12:     0x7ff7318d0a4f - std::sys_common::backtrace::__rust_end_short_backtrace<closure-0,!>
                               at C:\Users\dinne\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\sys_common\backtrace.rs:153
  13:     0x7ff7318d0ce7 - std::panicking::begin_panic<str*>
                               at C:\Users\dinne\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panicking.rs:497
  14:     0x7ff7302f0a59 - ruffle_render_wgpu::{{impl}}::push_mask<ruffle_render_wgpu::target::TextureTarget>
                               at W:\personal\ruffle\render\wgpu\src\lib.rs:1420
  15:     0x7ff73111511a - ruffle_core::display_object::render_children
                               at W:\personal\ruffle\core\src\display_object.rs:1170
  16:     0x7ff730f4fffc - ruffle_core::display_object::movie_clip::{{impl}}::render
                               at W:\personal\ruffle\core\src\display_object\movie_clip.rs:1667
  17:     0x7ff73111a70a - ruffle_core::display_object::{{impl}}::render
                               at W:\personal\ruffle\core\src\display_object.rs:371
  18:     0x7ff73111512c - ruffle_core::display_object::render_children
                               at W:\personal\ruffle\core\src\display_object.rs:1171
  19:     0x7ff730f4fffc - ruffle_core::display_object::movie_clip::{{impl}}::render
                               at W:\personal\ruffle\core\src\display_object\movie_clip.rs:1667
  20:     0x7ff73111a70a - ruffle_core::display_object::{{impl}}::render
                               at W:\personal\ruffle\core\src\display_object.rs:371
  21:     0x7ff73111515e - ruffle_core::display_object::render_children
                               at W:\personal\ruffle\core\src\display_object.rs:1175
  22:     0x7ff730f4fffc - ruffle_core::display_object::movie_clip::{{impl}}::render
                               at W:\personal\ruffle\core\src\display_object\movie_clip.rs:1667
  23:     0x7ff73111a70a - ruffle_core::display_object::{{impl}}::render
                               at W:\personal\ruffle\core\src\display_object.rs:371
  24:     0x7ff7310cfae6 - ruffle_core::player::{{impl}}::render::{{closure}}
                               at W:\personal\ruffle\core\src\player.rs:853
  25:     0x7ff7310dc2e3 - ruffle_core::player::GcArena::mutate<closure-0,tuple<>>
                               at C:\Users\dinne\.cargo\registry\src\github.com-1ecc6299db9ec823\gc-arena-0.2.0\src\arena.rs:161
  26:     0x7ff730ded844 - ruffle_core::player::Player::render
                               at W:\personal\ruffle\core\src\player.rs:842
  27:     0x7ff7302dc6f6 - exporter::take_screenshot
                               at W:\personal\ruffle\exporter\src\main.rs:135
  28:     0x7ff7302dd74c - exporter::capture_single_swf
                               at W:\personal\ruffle\exporter\src\main.rs:226
  29:     0x7ff7302dff77 - exporter::main
                               at W:\personal\ruffle\exporter\src\main.rs:394
  30:     0x7ff7303025db - core::ops::function::FnOnce::call_once<fn() -> core::result::Result<tuple<>, alloc::boxed::Box<Error>>,tuple<>>
                               at C:\Users\dinne\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\ops\function.rs:227
  31:     0x7ff7302fa17e - std::sys_common::backtrace::__rust_begin_short_backtrace<fn() -> core::result::Result<tuple<>, alloc::boxed::Box<Error>>,core::result::Result<tuple<>, alloc::boxed::Box<Error>>>
                               at C:\Users\dinne\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\sys_common\backtrace.rs:137
  32:     0x7ff7302e4cf1 - std::rt::lang_start::{{closure}}<core::result::Result<tuple<>, alloc::boxed::Box<Error>>>
                               at C:\Users\dinne\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\rt.rs:66
  33:     0x7ff7318fa4f6 - core::ops::function::impls::{{impl}}::call_once
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\library\core\src\ops\function.rs:280
  34:     0x7ff7318fa4f6 - std::panicking::try::do_call
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\panicking.rs:373
  35:     0x7ff7318fa4f6 - std::panicking::try
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\panicking.rs:337
  36:     0x7ff7318fa4f6 - std::panic::catch_unwind
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\panic.rs:379
  37:     0x7ff7318fa4f6 - std::rt::lang_start_internal
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\rt.rs:51
  38:     0x7ff7302e4cc3 - std::rt::lang_start<core::result::Result<tuple<>, alloc::boxed::Box<Error>>>
                               at C:\Users\dinne\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\rt.rs:65
  39:     0x7ff7302e11e0 - main
  40:     0x7ff731b5f464 - invoke_main
                               at D:\agent\_work\9\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  41:     0x7ff731b5f464 - __scrt_common_main_seh
                               at D:\agent\_work\9\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  42:     0x7ff9b32f7034 - BaseThreadInitThunk
  43:     0x7ff9b39bcec1 - RtlUserThreadStart
error: process didn't exit successfully: `target\debug\exporter.exe w:\swfs\newgrounds.com\523000\523350_Chronicles_of_Raynor_secur202c.swf test.png` (exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN)
```

**Comment by Herschel** [comment]
I'm going to add some mask-inside-mask samples to visual-tests, should I make separate FLAs for them?

**Comment by Dinnerbone** [comment]
Yeah separate FLAs sound good.

This issue unfortunately still exists in [11 Seconds](https://www.newgrounds.com/portal/view/629012?emulate=flash)

**Comment by Toad06** [comment]
FWIW, this issue also happens in [Super Mario 63](https://www.newgrounds.com/portal/view/498969), after you've completed the first part of the first level.

**Comment by Herschel** [comment]
Thx for the repro cases!

**Comment by onkrot** [comment]
Also happens on https://z0r.de/954

**Comment by the-garlic-os** [comment]
If it's any help, here's the auto-generated error information from z0r.de/954:

# Error Info
Error name: Error
Error message: panicked at 'assertion failed: self.mask_state == MaskState::NoMask ||
    self.mask_state == MaskState::DrawMaskedContent', render/webgl/src/lib.rs:1239:9
Error stack:
```
Error: panicked at 'assertion failed: self.mask_state == MaskState::NoMask ||
    self.mask_state == MaskState::DrawMaskedContent', render/webgl/src/lib.rs:1239:9
    at Object.$ (https://z0r.de/inc/core.ruffle.0c4ecaaeea5510153af3.js:1:20420)
    at __wbg_new_df6e6ab7a65c4c4d (https://z0r.de/inc/ruffle.js:1:35604)
    at https://z0r.de/inc/58a496f0592feec491a5.module.wasm:wasm-function[1073]:0x20c304
    at https://z0r.de/inc/58a496f0592feec491a5.module.wasm:wasm-function[1403]:0x24c526
    at https://z0r.de/inc/58a496f0592feec491a5.module.wasm:wasm-function[3794]:0x305b30
    at https://z0r.de/inc/58a496f0592feec491a5.module.wasm:wasm-function[2991]:0x2e717f
    at https://z0r.de/inc/58a496f0592feec491a5.module.wasm:wasm-function[4147]:0x30b181
    at https://z0r.de/inc/58a496f0592feec491a5.module.wasm:wasm-function[4097]:0x30a8e3
    at https://z0r.de/inc/58a496f0592feec491a5.module.wasm:wasm-function[4148]:0x30b1aa
    at https://z0r.de/inc/58a496f0592feec491a5.module.wasm:wasm-function[4095]:0x30a885
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://z0r.de/954
SWF URL: https://z0r.de/L/z0r-de_954.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2020-12-15
Channel: nightly
Built: 2020-12-15T00:33:46.121Z
Commit: 709561a25557520b5c537aad32e6b78512127cdb

**Comment by paq** [comment]
This panic maybe occurs when using Dynamic Text Field as a mask.

[issue1347.zip](https://github.com/ruffle-rs/ruffle/files/5758776/issue1347.zip)
It is a minimal repro case.

**Comment by poudink** [comment]
Seems to me like this is fixed. At the very least, I do not have any issue getting past the Super Mario 63 tutorial stage. However, it is still impossible to progress to the first level as the game will crash when entering the castle.

**Comment by Lord-McSweeney** [comment]
Closing as the issue no longer occurs in neither the z0r nor the Newgrounds.

**Comment by n0samu** [comment]
> This panic maybe occurs when using Dynamic Text Field as a mask.
> 
> [issue1347.zip](https://github.com/ruffle-rs/ruffle/files/5758776/issue1347.zip) It is a minimal repro case.

This no longer panics, but it does not display anything either because clipping layers are unimplemented. See #6784

**Comment by n0samu** [comment]
For the record, I was wrong about clipping layers being unimplemented - it was just a problem with dynamic text field masks in particular (#9664). That has since been fixed.
