### ISSUE TITLE
Error on https://ooooooooo.ooo/static/

### ISSUE THREAD

**Issue by gnarlom** [ruffle-rs/ruffle#13496]
# Error Info
Error name: Error
Error message: panicked at core/src/avm2/amf.rs:99:34:
Unexpected non-object value in object vector
Error stack:
```
Error: panicked at core/src/avm2/amf.rs:99:34:
Unexpected non-object value in object vector
    at V.n.wbg.__wbg_new_d258248ed531ff54 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.4f64c86b2b458fb5d643.js:1:51724)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h73a0ca99bc054b64 (wasm://wasm/0323790e:wasm-function[9651]:0x9772c7)
    at std::panicking::rust_panic_with_hook::h3aa054d35a0817d7 (wasm://wasm/0323790e:wasm-function[6313]:0x87bef6)
    at core::panicking::panic_fmt::h3e1dd3d08288569e (wasm://wasm/0323790e:wasm-function[9458]:0x972224)
    at core::option::expect_failed::hea22cf135ad64e98 (wasm://wasm/0323790e:wasm-function[8873]:0x9490ae)
    at ruffle_core::avm2::amf::serialize_value::hca58e65f647b2bde (wasm://wasm/0323790e:wasm-function[785]:0x2bfdbb)
    at ruffle_core::avm2::amf::recursive_serialize::h93440d029b8f6f3e (wasm://wasm/0323790e:wasm-function[2528]:0x62ab06)
    at ruffle_core::avm2::globals::flash::net::shared_object::new_lso::h372db29e313fcaf9 (wasm://wasm/0323790e:wasm-function[2529]:0x62ad44)
    at ruffle_core::avm2::globals::flash::net::shared_object::flush::h9a89cccf372f113b (wasm://wasm/0323790e:wasm-function[1734]:0x4fa23d)
    at ruffle_core::avm2::function::Executable::exec::hb0c767d900156b9f (wasm://wasm/0323790e:wasm-function[872]:0x320deb)
```
AVM2 stack:
```
    at flash.net::SharedObject/flash::net::SharedObject::flush()
    at com.spilgames.api.core.tracking.ext.spilet.trackStates::NotSpilState/updateSharedObject()
    at com.spilgames.api.core.tracking.ext.spilet.trackStates::NotSpilState/addElementToQueue()
    at com.spilgames.api.core.tracking.ext.spilet.trackStates::NotSpilState/startSession()
    at com.spilgames.api.core.tracking.ext.spilet.trackStates::NotSpilState/init()
    at com.spilgames.api.core.tracking.ext.spilet.trackStates::NotSpilState()
    at com.spilgames.api.core.tracking.ext.spilet.setTracker::SET$/setEnvironment()
    at com.spilgames.api.core.tracking.ext.spilet.setTracker::SET$/init()
    at com.spilgames.api.core.tracking.ext.spilet.setTracker::SET$/getInstance()
    at com.spilgames.api.core.tracking.ext.spilet::SETTracker/setup()
    at com.spilgames.api.core.tracking.ext::ATracker/setClass()
    at com.spilgames.api.core.tracking.ext::TrackerLoader/load()
    at com.spilgames.api.core.tracking::TrackController/loadLibraries()
    at com.spilgames.api.core.tracking::TrackController/onLoadConfig()
    at com.spilgames.api.core.tracking::TrackConfig/onLoadConfig()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) UHD Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://ooooooooo.ooo/static/?1f98c7b4-2676-45f2-8e2a-52458d0e22f8
SWF URL: http://www8.agame.com/games/flash/c/cute_horse_hospital/cute_horse_hospital_default.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.60
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-10-10
Channel: nightly
Built: 2023-10-10T00:27:25.054Z
Commit: 7254cdeef9f9fadf86ffeaddb2735de99cf8fb3d
Is extension: false

# Metadata
width: 700
height: 510
frameRate: 30
numFrames: 3
swfVersion: 10
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 9944993

**Comment by SuchAFuriousDeath** [comment]
Fixed by #13537.
