### ISSUE TITLE
Saving in Scuba endlessly consumes memory

### ISSUE THREAD

**Issue by mateon1** [ruffle-rs/ruffle#13515]
### Describe the bug

After starting a new game in Scuba (SWF: https://web.archive.org/web/20160501114055id_/http://games.jayisgames.com/scuba.swf) (note: it takes a while, world generation takes significantly longer than it used to on Flash Player), when you open the menu and click save game, Ruffle starts consuming all memory it can (rapidly consumed >100G on one of my machines, without stopping), and eventually dies due to OOM.

IMPORTANT NOTE: When reproducing the problem look at any kind of resource monitor or task manager, and be ready to kill ruffle. It eats memory *fast*.

### Expected behavior

Saving succeeds, game does not die due to OOM or any other reason.

### Affected platform

Desktop app

### Operating system

Linux - NixOS unstable

**Comment by mateon1** [comment]
Seems like it's an issue caused by misbehaving AVM2 code, here's a backtrace taken while the game is trying to save, it seems to be constantly concatenating AvmStrings together until it runs out of memory
<details><summary>GDB Backtrace</summary>

```rust
#0  __memcpy_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:488
#1  0x0000555555d26333 in core::intrinsics::copy_nonoverlapping<u8> (src=<optimized out>, dst=<optimized out>, count=<optimized out>)
    at /rustc/bf9a1c8a193fc373897196321215794c8bebbeec/library/core/src/intrinsics.rs:2690
#2  core::ptr::const_ptr::{impl#0}::copy_to_nonoverlapping<u8> (self=<optimized out>, dest=<optimized out>, count=<optimized out>)
    at /rustc/bf9a1c8a193fc373897196321215794c8bebbeec/library/core/src/ptr/const_ptr.rs:1308
#3  alloc::slice::hack::{impl#1}::to_vec<u8, alloc::alloc::Global> (s=..., alloc=...) at /rustc/bf9a1c8a193fc373897196321215794c8bebbeec/library/alloc/src/slice.rs:167
#4  alloc::slice::hack::to_vec<u8, alloc::alloc::Global> (s=...) at /rustc/bf9a1c8a193fc373897196321215794c8bebbeec/library/alloc/src/slice.rs:111
#5  alloc::slice::{impl#0}::to_vec_in<u8, alloc::alloc::Global> (self=...) at /rustc/bf9a1c8a193fc373897196321215794c8bebbeec/library/alloc/src/slice.rs:441
#6  alloc::slice::{impl#0}::to_vec<u8> (self=...) at /rustc/bf9a1c8a193fc373897196321215794c8bebbeec/library/alloc/src/slice.rs:416
#7  alloc::slice::{impl#9}::to_owned<u8> (self=...) at /rustc/bf9a1c8a193fc373897196321215794c8bebbeec/library/alloc/src/slice.rs:823
#8  ruffle_wstr::buf::WString::from_wstr (s=...) at wstr/src/buf.rs:116
#9  ruffle_wstr::buf::{impl#4}::to_owned () at wstr/src/buf.rs:498
#10 ruffle_wstr::buf::{impl#10}::from () at wstr/src/buf.rs:549
#11 ruffle_core::string::avm_string::AvmString::concat (gc_context=0x5555570b5fd0, left=..., right=...) at core/src/string/avm_string.rs:80
#12 0x0000555555d704cb in ruffle_core::avm2::activation::Activation::op_add (self=0x7ffffffe9328) at core/src/avm2/activation.rs:2130
#13 0x0000555555d6cd00 in ruffle_core::avm2::activation::Activation::do_next_opcode (self=0x7ffffffe9328, method=..., reader=0x7ffffffe8930, full_data=...)
    at core/src/avm2/activation.rs:1012
#14 ruffle_core::avm2::activation::Activation::run_actions (self=0x7ffffffe9328, method=...) at core/src/avm2/activation.rs:844
#15 0x0000555555d69b82 in ruffle_core::avm2::function::Executable::exec (self=<optimized out>, unbound_receiver=..., arguments=..., activation=0x7ffffffea4e8, callee=...)
    at core/src/avm2/function.rs:193
#16 0x0000555555dbe28f in ruffle_core::avm2::object::TObject::call_property<ruffle_core::avm2::object::script_object::ScriptObject> (self=..., multiname=0x5555aacc4690, arguments=..., 
    activation=0x7ffffffea4e8) at core/src/avm2/object.rs:483
#17 0x0000555555d726c4 in ruffle_core::avm2::activation::Activation::op_call_prop_void (self=0x7ffffffea4e8, method=..., index=..., arg_count=5) at core/src/avm2/activation.rs:1352
#18 0x0000555555d6ad2b in ruffle_core::avm2::activation::Activation::do_next_opcode (self=0x7ffffffea4e8, method=..., reader=0x7ffffffe9af0, full_data=...)
    at core/src/avm2/activation.rs:956
#19 ruffle_core::avm2::activation::Activation::run_actions (self=0x7ffffffea4e8, method=...) at core/src/avm2/activation.rs:844
#20 0x0000555555d69b82 in ruffle_core::avm2::function::Executable::exec (self=<optimized out>, unbound_receiver=..., arguments=..., activation=0x7ffffffeb648, callee=...)
    at core/src/avm2/function.rs:193
#21 0x0000555555d946f7 in ruffle_core::avm2::object::function_object::{impl#2}::call (self=..., receiver=..., arguments=..., activation=0x0)
    at core/src/avm2/object/function_object.rs:191
#22 ruffle_core::avm2::object::{impl#5}::call (self=..., _receiver=..., _arguments=..., _activation=<optimized out>) at core/src/avm2/object.rs:138
#23 0x0000555555d71cdd in ruffle_core::avm2::activation::Activation::op_call (self=0x7ffffffeb648, arg_count=1) at core/src/avm2/activation.rs:1263
#24 0x0000555555d6bd72 in ruffle_core::avm2::activation::Activation::do_next_opcode (self=0x7ffffffeb648, method=..., reader=0x7ffffffeac50, full_data=...)
    at core/src/avm2/activation.rs:947
#25 ruffle_core::avm2::activation::Activation::run_actions (self=0x7ffffffeb648, method=...) at core/src/avm2/activation.rs:844
#26 0x0000555555d69b82 in ruffle_core::avm2::function::Executable::exec (self=<optimized out>, unbound_receiver=..., arguments=..., activation=0x7ffffffec218, callee=...)
    at core/src/avm2/function.rs:193
#27 0x0000555555d946f7 in ruffle_core::avm2::object::function_object::{impl#2}::call (self=..., receiver=..., arguments=..., activation=0x0)
    at core/src/avm2/object/function_object.rs:191
#28 ruffle_core::avm2::object::{impl#5}::call (self=..., _receiver=..., _arguments=..., _activation=<optimized out>) at core/src/avm2/object.rs:138
#29 0x0000555555e0ad99 in ruffle_core::avm2::events::dispatch_event_to_target (activation=0x7ffffffec218, dispatcher=..., target=..., event=...) at core/src/avm2/events.rs:423
#30 0x0000555555e0a69a in ruffle_core::avm2::events::dispatch_event (activation=0x7ffffffec218, this=..., event=...) at core/src/avm2/events.rs:514
#31 0x0000555555e19143 in ruffle_core::avm2::Avm2::dispatch_event (context=<optimized out>, event=..., target=...) at core/src/avm2.rs:350
#32 0x0000555555e341f5 in ruffle_core::display_object::interactive::TInteractiveObject::event_dispatch_to_avm2<ruffle_core::display_object::movie_clip::MovieClip> (self=..., 
    context=0x7ffffffec9b0, event=...) at core/src/display_object/interactive.rs:306
#33 ruffle_core::display_object::interactive::{impl#11}::event_dispatch_to_avm2 (self=..., context=0x7ffffffec9b0, event=...) at core/src/display_object/interactive.rs:105
#34 0x0000555555e2eda7 in ruffle_core::player::{impl#2}::update_mouse_state::{closure#0} (context=0x7ffffffec9b0) at core/src/player.rs:1509
#35 ruffle_core::player::{impl#2}::mutate_with_update_context::{closure#0}<ruffle_core::player::{impl#2}::update_mouse_state::{closure_env#0}, bool> (gc_context=<optimized out>, 
    gc_root=<optimized out>) at core/src/player.rs:1950
#36 gc_arena::arena::Arena<gc_arena::arena::__DynRootable<dyn gc_arena::arena::Rootable<Root=ruffle_core::player::GcRoot>>>::mutate<gc_arena::arena::__DynRootable<dyn gc_arena::arena::Rootable<Root=ruffle_core::player::GcRoot>>, ruffle_core::player::{impl#2}::mutate_with_update_context::{closure_env#0}<ruffle_core::player::{impl#2}::update_mouse_state::{closure_env#0}, bool>, bool> (self=<optimized out>, f=...) at /home/mateon/.cargo/git/checkouts/gc-arena-f613d25074b8ab45/efd89fc/src/gc-arena/src/arena.rs:155
#37 ruffle_core::player::Player::mutate_with_update_context<ruffle_core::player::{impl#2}::update_mouse_state::{closure_env#0}, bool> (self=0x555557047ce8, f=...)
    at core/src/player.rs:1869
#38 ruffle_core::player::Player::update_mouse_state (self=0x555557047ce8, is_mouse_button_changed=<optimized out>, is_mouse_moved=false) at core/src/player.rs:1295
#39 0x00005555560e9861 in ruffle_core::player::Player::handle_event (self=0x555557047ce8, event=...) at core/src/player.rs:1204
#40 0x0000555555808293 in ruffle_desktop::player::PlayerController::handle_event (self=<optimized out>, event=...) at desktop/src/player.rs:246
#41 0x00005555557cb931 in ruffle_desktop::app::{impl#0}::run::{closure#0} (event=..., _window_target=<optimized out>, control_flow=0x7ffffffee740) at desktop/src/app.rs:225
#42 0x000055555579201c in winit::platform_impl::platform::x11::{impl#2}::drain_events::{closure#0}::{closure#0}<ruffle_desktop::custom_event::RuffleEvent, ruffle_desktop::app::{impl#0}::run::{closure_env#0}> (event=<error reading variable: Cannot access memory at address 0x0>, window_target=<optimized out>, control_flow=<optimized out>)
    at /home/mateon/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.7/src/platform_impl/linux/x11/mod.rs:522
#43 0x000055555579201c in winit::platform_impl::platform::sticky_exit_callback<ruffle_desktop::custom_event::RuffleEvent, winit::platform_impl::platform::x11::{impl#2}::drain_events::{closure#0}::{closure_env#0}<ruffle_desktop::custom_event::RuffleEvent, ruffle_desktop::app::{impl#0}::run::{closure_env#0}>> (evt=..., target=0x5563894197e0, control_flow=<optimized out>, 
    callback=<optimized out>)
#44 winit::platform_impl::platform::x11::{impl#2}::drain_events::{closure#0}<ruffle_desktop::custom_event::RuffleEvent, ruffle_desktop::app::{impl#0}::run::{closure_env#0}> (event=...)
    at /home/mateon/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.7/src/platform_impl/linux/x11/mod.rs:513
#45 0x0000555555790170 in winit::platform_impl::platform::x11::event_processor::EventProcessor<ruffle_desktop::custom_event::RuffleEvent>::process_event<ruffle_desktop::custom_event::RuffleEvent, winit::platform_impl::platform::x11::{impl#2}::drain_events::{closure_env#0}<ruffle_desktop::custom_event::RuffleEvent, ruffle_desktop::app::{impl#0}::run::{closure_env#0}>> (
    self=0x7ffffffee8d8, xev=<optimized out>, callback=...)
    at /home/mateon/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.7/src/platform_impl/linux/x11/event_processor.rs:1137
#46 0x0000555555790f4c in winit::platform_impl::platform::x11::EventLoop<ruffle_desktop::custom_event::RuffleEvent>::drain_events<ruffle_desktop::custom_event::RuffleEvent, ruffle_desktop::app::{impl#0}::run::{closure_env#0}> (self=0x7ffffffee8d8, callback=0x7ffffffeeb60, control_flow=0x7ffffffee740)
    at /home/mateon/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.7/src/platform_impl/linux/x11/mod.rs:512
#47 winit::platform_impl::platform::x11::{impl#2}::run_return::single_iteration<ruffle_desktop::custom_event::RuffleEvent, ruffle_desktop::app::{impl#0}::run::{closure_env#0}> (
    this=0x7ffffffee8d8, control_flow=0x7ffffffee740, cause=0x7ffffffee7e0, callback=0x7ffffffeeb60)
    at /home/mateon/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.7/src/platform_impl/linux/x11/mod.rs:343
#48 0x0000555555791d6e in winit::platform_impl::platform::x11::EventLoop<ruffle_desktop::custom_event::RuffleEvent>::run_return<ruffle_desktop::custom_event::RuffleEvent, ruffle_desktop::app::{impl#0}::run::{closure_env#0}> (self=0x7ffffffee8d8, callback=...)
    at /home/mateon/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.7/src/platform_impl/linux/x11/mod.rs:483
#49 0x0000555555789a0e in winit::platform_impl::platform::x11::EventLoop<ruffle_desktop::custom_event::RuffleEvent>::run<ruffle_desktop::custom_event::RuffleEvent, ruffle_desktop::app::{impl#0}::run::{closure_env#0}> (self=<error reading variable: Cannot access memory at address 0x0>, callback=<error reading variable: Cannot access memory at address 0x30>)
    at /home/mateon/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.7/src/platform_impl/linux/x11/mod.rs:498
#50 winit::platform_impl::platform::EventLoop<ruffle_desktop::custom_event::RuffleEvent>::run<ruffle_desktop::custom_event::RuffleEvent, ruffle_desktop::app::{impl#0}::run::{closure_env#0}> (self=..., callback=...) at /home/mateon/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.7/src/platform_impl/linux/mod.rs:792
#51 0x00005555557c35d6 in winit::event_loop::EventLoop<ruffle_desktop::custom_event::RuffleEvent>::run<ruffle_desktop::custom_event::RuffleEvent, ruffle_desktop::app::{impl#0}::run::{closure_env#0}> (event_handler=<error reading variable: Cannot access memory at address 0x30>)
    at /home/mateon/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.7/src/event_loop.rs:305
#52 ruffle_desktop::app::App::run (self=...) at desktop/src/app.rs:99
#53 0x0000555555815100 in ruffle_desktop::main::{closure#0} (app=...) at desktop/src/main.rs:162
#54 core::result::Result<ruffle_desktop::app::App, anyhow::Error>::map<ruffle_desktop::app::App, anyhow::Error, (), ruffle_desktop::main::{closure_env#0}> (self=..., op=...)
--Type <RET> for more, q to quit, c to continue without paging--
    at /rustc/bf9a1c8a193fc373897196321215794c8bebbeec/library/core/src/result.rs:746
#55 ruffle_desktop::main () at desktop/src/main.rs:162
```
</details>
