### ISSUE TITLE
Panic on fedora 38 on wayland

### ISSUE THREAD

**Issue by zeskeertwee** [ruffle-rs/ruffle#13512]
### Describe what you were doing

Launching the application on wayland.

### What does the crash message say?

panicked at /home/runner/.cargo/git/checkouts/wgpu-c26c9ef766f7dc30/c4b8787/wgpu/src/backend/direct.rs:771:18:
Error in Surface::configure: Validation Error

Caused by:
    Parent device is lost

### Ruffle Version

0.1.0-nightly (0ef28604b16bb9b27ee9291f527a1827d7713b7b 2023-10-10)

### Affected platform

Desktop app

### Operating system

Fedora 38.0.0 [64-bit]

**Comment by Lord-McSweeney** [comment]
Can you post some GPU info please? Ruffle doesn't do well on old GPUs.

**Comment by zeskeertwee** [comment]
The laptop has an i7-12700H with iGPU and a dedicated RTX A1000 GPU, but im not sure which one WGPU is using.
The DE is running on the iGPU.
I'll try to see if i can force it to use either one.

**Comment by zeskeertwee** [comment]
I ran it with `RUST_LOG=trace` and it seems to be using the A1000 GPU:
```
2023-10-12T07:54:04.251499Z  INFO wgpu_hal::vulkan::instance: Instance version: 0x4030f3    
2023-10-12T07:54:04.251529Z  INFO wgpu_hal::vulkan::instance: Debug utils not enabled: debug_utils_user_data not passed to Instance::from_raw    
2023-10-12T07:54:04.251535Z  INFO wgpu_hal::vulkan::instance: Enabling device properties2    
2023-10-12T07:54:04.260250Z  WARN wgpu_hal::vulkan::instance: Disabling presentation on 'Intel(R) Graphics (ADL GT2)' (id 0x561cf4676260) because of NV Optimus (on Linux)    
2023-10-12T07:54:04.263011Z  INFO wgpu_core::instance: Adapter Vulkan AdapterInfo { name: "NVIDIA RTX A1000 Laptop GPU", vendor: 4318, device: 9657, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "535.113.01", backend: Vulkan }    
2023-10-12T07:54:04.263086Z DEBUG wgpu_hal::vulkan::adapter: Supported extensions: ["VK_KHR_swapchain", "VK_KHR_swapchain_mutable_format", "VK_EXT_robustness2"]    
2023-10-12T07:54:04.311565Z  INFO wgpu_core::device::global: configuring surface with SurfaceConfiguration { usage: TextureUsages(RENDER_ATTACHMENT), format: Bgra8Unorm, width: 800, height: 600, present_mode: Fifo, alpha_mode: Auto, view_formats: [] }    
2023-10-12T07:54:04.312124Z  INFO wgpu_core::device::global: Automatically choosing alpha mode by rule Auto. Chose Opaque    
2023-10-12T07:54:04.323252Z  WARN wgpu_hal::vulkan: Unrecognized device error ERROR_INITIALIZATION_FAILED    
thread 'main' panicked at /home/runner/.cargo/git/checkouts/wgpu-c26c9ef766f7dc30/c4b8787/wgpu/src/backend/direct.rs:771:18:
Error in Surface::configure: Validation Error

Caused by:
    Parent device is lost

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)

```

**Comment by torokati44** [comment]
> Is there a way i can force it to use the iGPU?

The `--power low` command line arguments should do that.
