### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by Nick12390** [ruffle-rs/ruffle#13521]
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/git/checkouts/wgpu-c26c9ef766f7dc30/c4b8787/wgpu-hal/src/gles/device.rs:705:52:
called `Result::unwrap()` on an `Err` value: "Unable to create texture object"
Error stack:
```
Error: panicked at /home/runner/.cargo/git/checkouts/wgpu-c26c9ef766f7dc30/c4b8787/wgpu-hal/src/gles/device.rs:705:52:
called `Result::unwrap()` on an `Err` value: "Unable to create texture object"
    at V.n.wbg.__wbg_new_d258248ed531ff54 (https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.6e4d2c1da0a3fd6f0339.js:1:51724)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hae20252bd0e594a8 (wasm://wasm/032537fe:wasm-function[9643]:0x97dc8c)
    at std::panicking::rust_panic_with_hook::h3aa054d35a0817d7 (wasm://wasm/032537fe:wasm-function[6308]:0x883a71)
    at core::panicking::panic_fmt::h3e1dd3d08288569e (wasm://wasm/032537fe:wasm-function[9448]:0x978b7f)
    at core::result::unwrap_failed::h8b3db0f11171b57b (wasm://wasm/032537fe:wasm-function[7920]:0x90138f)
    at <T as wgpu::context::DynContext>::device_create_texture::h4ce58e0f21d891e5 (wasm://wasm/032537fe:wasm-function[7019]:0x8bc1f8)
    at wgpu::Device::create_texture::h3e30fecafbb94149 (wasm://wasm/032537fe:wasm-function[5366]:0x832641)
    at <ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::create_empty_texture::hb8a5310ccda11ecd (wasm://wasm/032537fe:wasm-function[5182]:0x82068e)
    at ruffle_core::display_object::render_base::hcf05f08247c2f9ba (wasm://wasm/032537fe:wasm-function[572]:0x136958)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render::h73064dd5c3a5e165 (wasm://wasm/032537fe:wasm-function[6896]:0x8a9ad1)
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) UHD Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.67&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1697015849%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F592000%2F592473_MadnessGame_ULTIMATE.swf%3F1507662264%22%2C%22vars%22%3A%7B%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%226526df998633a%22%2C%22NewgroundsAPI_SessionID%22%3A%22%22%2C%22NewgroundsAPI_UserName%22%3A%22%26lt%3Bdeleted%26gt%3B%22%2C%22NewgroundsAPI_UserID%22%3A0%2C%22ng_username%22%3A%22%26lt%3Bdeleted%26gt%3B%22%7D%2C%22width%22%3A850%2C%22height%22%3A530%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F592000%2Fflash_592473_card.webp%3Ff1669742379%22%2C%22warnOnUnsupportedContent%22%3Afalse%7D
SWF URL: https://uploads.ungrounded.net/592000/592473_MadnessGame_ULTIMATE.swf?1507662264

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 OPR/102.0.0.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-10-11
Channel: nightly
Built: 2023-10-11T00:22:14.322Z
Commit: 0ef28604b16bb9b27ee9291f527a1827d7713b7b
Is extension: false

# Metadata
width: 850
height: 530
frameRate: 30
numFrames: 30
swfVersion: 10
backgroundColor: #FFFFFF
isActionScript3: false
uncompressedLength: 20491352

**Comment by Lord-McSweeney** [comment]
Duplicate of #12236
