### ISSUE TITLE
Error on https://www.gameflare.com/embed/slow-and-blow-pirates/

### ISSUE THREAD

**Issue by Averell2003** [ruffle-rs/ruffle#13535]
# Error Info
Error name: Error
Error message: panicked at core/src/avm2/amf.rs:99:34:
Unexpected non-object value in object vector
Error stack:
```
Error: panicked at core/src/avm2/amf.rs:99:34:
Unexpected non-object value in object vector
    at V.n.wbg.__wbg_new_d258248ed531ff54 (https://www.gameflare.com/emulators/ruffle/core.ruffle.7f221ea7883c89c5de86.js:1:51724)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hae20252bd0e594a8 (wasm://wasm/0326105a:wasm-function[9620]:0x982397)
    at std::panicking::rust_panic_with_hook::h3aa054d35a0817d7 (wasm://wasm/0326105a:wasm-function[6303]:0x889c33)
    at core::panicking::panic_fmt::h3e1dd3d08288569e (wasm://wasm/0326105a:wasm-function[9425]:0x97d28a)
    at core::option::expect_failed::hea22cf135ad64e98 (wasm://wasm/0326105a:wasm-function[8834]:0x95535e)
    at ruffle_core::avm2::amf::serialize_value::haba092c728a4659c (wasm://wasm/0326105a:wasm-function[781]:0x2bb793)
    at ruffle_core::avm2::amf::recursive_serialize::ha9d40dd4152cc4cb (wasm://wasm/0326105a:wasm-function[2535]:0x635974)
    at ruffle_core::avm2::globals::flash::net::shared_object::new_lso::h5f57135a3c941ebe (wasm://wasm/0326105a:wasm-function[2726]:0x6624f7)
    at ruffle_core::avm2::globals::flash::net::shared_object::flush::hf6db7ae54b008e90 (wasm://wasm/0326105a:wasm-function[1726]:0x4f9371)
    at ruffle_core::avm2::function::Executable::exec::h9d385c5a8eabfedd (wasm://wasm/0326105a:wasm-function[869]:0x32025e)
```
AVM2 stack:
```
    at flash.net::SharedObject/flash::net::SharedObject::flush()
    at Main$/LoadGame()
    at Main/Init()
    at Main/Start()
    at Slow_and_Blow_Pirates_fla::MainTimeline/frame3()
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) UHD Graphics 730 (0x00004682) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://www.gameflare.com/embed/slow-and-blow-pirates/
SWF URL: https://data.gameflare.com/games/2243/ffO6O0Myxymd4r.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-10-12
Channel: nightly
Built: 2023-10-12T00:20:36.060Z
Commit: 2422793d1be3929e7b4e0fd0bf47bd1bcc7c0126
Is extension: false

# Metadata
width: 700
height: 500
frameRate: 60
numFrames: 2
swfVersion: 10
backgroundColor: #FFFFCC
isActionScript3: true
uncompressedLength: 8430155

**Comment by SuchAFuriousDeath** [comment]
Fixed by #13537.
