### ISSUE TITLE
Error on http://web.archive.org/web/20070529084424/www.myspace.com/thrashpolo

### ISSUE THREAD

**Issue by ruffalou** [ruffle-rs/ruffle#13544]
### Describe what you were doing

Error Description: The music player close to the bottom can't load(it says that its likely due to the CORS policy). It was able to load some things last time i tried it a couple of months ago(the player itself was able to load and the other things), but the songs weren't loading and I just got a message that said "Error Loading XML Document". 

What I Expect: I expect everything to load in including the songs no matter how long it takes to load without any major issues and some expected minor issues. 

I don't mind if it takes long, I just expect a good result.

### What does the crash message say?

Error stack:
```
Error: Failed to fetch: http://lads.myspace.com/music/musicplayer.swf?n=aHR0cDovL211c2ljLm15c3BhY2UuY29t&t=gq+g5dWjljTWmAht0zsHJCS8LzvO6xx6JYuXz0itr3YBQVzVTLwsAIVMJrsYE3B04XH3Y0i3hrB+iugqDHKyEA==&u=LTE=&a=0&d=ODczMTc0MjBeMTE4MDQwMzY3Mw==
    at Ze.displayRootMovieDownloadFailedMessage (http://web.archive.org/_static/js/ruffle.js:2:349472)
    at W.n.wbg.__wbg_displayRootMovieDownloadFailedMessage_ed4ad3ae9522c8a3 (http://web.archive.org/_static/js/core.ruffle.92e6746d93be1e95cd77.js:1:7014)
    at <ruffle_web::ui::WebUiBackend as ruffle_core::backend::ui::UiBackend>::display_root_movie_download_failed_message::hdc7b2467229066fb (wasm://wasm/02f98346:wasm-function[10986]:0x92605f)
    at ruffle_core::loader::Loader::root_movie_loader::{{closure}}::h27e7a80404b1a839 (wasm://wasm/02f98346:wasm-function[870]:0x2ef832)
    at <ruffle_web::navigator::WebNavigatorBackend as ruffle_core::backend::navigator::NavigatorBackend>::spawn_future::{{closure}}::h59fccc39c587f869 (wasm://wasm/02f98346:wasm-function[1127]:0x3922c5)
    at wasm_bindgen_futures::queue::Queue::new::{{closure}}::hbb66f7af2d96f794 (wasm://wasm/02f98346:wasm-function[3910]:0x6ee501)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h0219aedcaa846c26 (wasm://wasm/02f98346:wasm-function[9841]:0x90423d)
    at closure4161 externref shim (wasm://wasm/02f98346:wasm-function[10160]:0x9091a7)
    at D (http://web.archive.org/_static/js/core.ruffle.92e6746d93be1e95cd77.js:1:2985)
    at f (http://web.archive.org/_static/js/core.ruffle.92e6746d93be1e95cd77.js:1:2511)
```

### Ruffle Version

Nightly 2023-10-14

### Affected platform

Browser's extension

### Operating system

Windows 11

### Additional information

I am new to the ruffle/flash community, so I may not know what some things are.

**Comment by Lord-McSweeney** [comment]
The original music player SWF is gone and was never archived on the Wayback Machine. Recently, Archive.org integrated Ruffle with their environment, which means that when Ruffle attempts to fetch a file, it is routed through the Wayback Machine. However, it never archived the music player SWF, and from what you're saying, it seems that Myspace removed it from their servers, too. So it's likely that the original SWF is irrecoverably lost, and similarly likely that the songs are lost.

I suggest heading over to our [discord](https://discord.com/invite/ruffle) to continue the discussion.

**Comment by ruffalou** [comment]
I am already in the discord, so maybe we can still continue it in there.
