### ISSUE TITLE
Error on https://www.minijogos.com.br/helpers/game/sandbox.php

### ISSUE THREAD

**Issue by JamPedr** [ruffle-rs/ruffle#13550]
# Error Info
Error name: Error
Error message: panicked at core/src/avm2/globals/flash/display/graphics.rs:1057:13:
Positive culling not implemented
Error stack:
```
Error: panicked at core/src/avm2/globals/flash/display/graphics.rs:1057:13:
Positive culling not implemented
    at n.wbg.__wbg_new_d258248ed531ff54 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.93c3f747b3c160c1df96.js:1:54129)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hae20252bd0e594a8 (wasm://wasm/03349c7e:wasm-function[9634]:0x9c3e96)
    at std::panicking::rust_panic_with_hook::h3aa054d35a0817d7 (wasm://wasm/03349c7e:wasm-function[6334]:0x8be9d7)
    at core::panicking::panic_fmt::h3e1dd3d08288569e (wasm://wasm/03349c7e:wasm-function[9444]:0x9becf8)
    at ruffle_core::avm2::globals::flash::display::graphics::draw_triangle_internal::hbacdbeb43f8b83a4 (wasm://wasm/03349c7e:wasm-function[5540]:0x881f87)
    at ruffle_core::avm2::globals::flash::display::graphics::draw_triangles::h85edb35b705a5cc3 (wasm://wasm/03349c7e:wasm-function[730]:0x2784d6)
    at ruffle_core::avm2::function::Executable::exec::h9d385c5a8eabfedd (wasm://wasm/03349c7e:wasm-function[745]:0x292cf3)
    at ruffle_core::avm2::object::TObject::call_property::h33173276e0222dea (wasm://wasm/03349c7e:wasm-function[1226]:0x41565a)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::hed6504d95031336b (wasm://wasm/03349c7e:wasm-function[2951]:0x6bb376)
    at ruffle_core::avm2::activation::Activation::run_actions::h9c9a6a0c435b4fc8 (wasm://wasm/03349c7e:wasm-function[522]:0x27832)
```
AVM2 stack:
```
    at flash.display::Graphics/flash::display::Graphics::drawTriangles()
    at Triangle3D/draw()
    at Object3D/draw()
    at MinecraftViewer/render()
    at MinecraftViewer/setDefaultPosition()
    at MinecraftViewer()
    at PreviewBox()
    at Main/loadPreviewBox()
    at Main/initMenuBrowse()
    at Main/frame9()
    at flash.display::MovieClip/flash::display::MovieClip::gotoAndStop()
    at Main/press_btnBrowseUploads()
```

# Player Info
Allows script access: false
Renderer: WebGL 1.0
Adapter Vendor: WebKit
Adapter Renderer: WebKit WebGL
Adapter Version: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Surface samples: 1 x 
Surface size: 980 x 550

# Page Info
Page URL: https://www.minijogos.com.br/helpers/game/sandbox.php?mp_assets=https%3A%2F%2Fs2.minijuegosgratis.com%2F&mp_embed=0&mp_game_id=202219&mp_game_uid=skincraft&mp_game_url=https%3A%2F%2Fwww.minijogos.com.br%2Fembed%2Fskincraft&mp_int=1&mp_locale=pt_BR&mp_player_type=FLASH&mp_player_url=aHR0cHM6Ly93d3cubWluaWp1ZWdvc2dyYXRpcy5jb20vdjMvZ2FtZXMvZ2FtZXMvcHJvZC8yMDIyMTkvc2tpbmNyYWZ0LnN3Zg%3D%3D&mp_site_https_url=https%3A%2F%2Fwww.minijogos.com.br%2F&mp_site_name=minijogos.com.br&mp_site_url=https%3A%2F%2Fwww.minijogos.com.br%2F&mp_timezone=America%2FSao_Paulo&mp_view_type=
SWF URL: https://www.minijuegosgratis.com/v3/games/games/prod/202219/skincraft.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 OPR/102.0.0.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-10-14
Channel: nightly
Built: 2023-10-14T00:21:06.189Z
Commit: 93aa3a493ba4c42f80e5d5a17044702e4942f89d
Is extension: false

# Metadata
width: 700
height: 394
frameRate: 30
numFrames: 12
swfVersion: 10
backgroundColor: #E1E1E1
isActionScript3: true
uncompressedLength: 1406230

**Comment by Lord-McSweeney** [comment]
Was fixed by #16762
