### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by Reox14** [ruffle-rs/ruffle#13552]
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/git/checkouts/wgpu-c26c9ef766f7dc30/c4b8787/wgpu/src/backend/direct.rs:3056:5:
wgpu error: Validation Error

Caused by:
    In Device::create_buffer
    Not enough memory left

Error stack:
```
Error: panicked at /home/runner/.cargo/git/checkouts/wgpu-c26c9ef766f7dc30/c4b8787/wgpu/src/backend/direct.rs:3056:5:
wgpu error: Validation Error

Caused by:
    In Device::create_buffer
    Not enough memory left


    at V.n.wbg.__wbg_new_d258248ed531ff54 (https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.ba551adeafef75c8ec4f.js:1:51724)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hae20252bd0e594a8 (wasm://wasm/0326457a:wasm-function[9629]:0x98166d)
    at std::panicking::rust_panic_with_hook::h3aa054d35a0817d7 (wasm://wasm/0326457a:wasm-function[6300]:0x8856b5)
    at core::panicking::panic_fmt::h3e1dd3d08288569e (wasm://wasm/0326457a:wasm-function[9434]:0x97c560)
    at core::ops::function::Fn::call::h80d36f2a35ba57e0 (wasm://wasm/0326457a:wasm-function[6475]:0x88f8e0)
    at wgpu::backend::direct::ErrorSinkRaw::handle_error::hb5bdd3e97fef1fdc (wasm://wasm/0326457a:wasm-function[5215]:0x82a41a)
    at <T as wgpu::context::DynContext>::device_create_buffer::h1e68b2dbf8989bd4 (wasm://wasm/0326457a:wasm-function[7254]:0x8dad29)
    at <wgpu::Device as wgpu::util::device::DeviceExt>::create_buffer_init::h451b1e19c1592212 (wasm://wasm/0326457a:wasm-function[1601]:0x4b6fe3)
    at ruffle_render_wgpu::surface::target::CommandTarget::new::h8361520fb815e413 (wasm://wasm/0326457a:wasm-function[839]:0x2edd9e)
    at ruffle_render_wgpu::surface::Surface::draw_commands::h25542954d5b40ea0 (wasm://wasm/0326457a:wasm-function[671]:0x212c4a)
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) HD Graphics 500 Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.67&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1697290836%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F592000%2F592473_MadnessGame_ULTIMATE.swf%3F1507662264%22%2C%22vars%22%3A%7B%22ngio_session_id%22%3A%2203239102.8ccf3b8abfa25626f1c9e7f16f7df010514afea92c7242%22%2C%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%22652afba8b535a%22%2C%22NewgroundsAPI_SessionID%22%3A%22w6u5pizjAPfBWyOU7V51ff3571d4a899f098390151986144f1a5f52b34dfUCOA%22%2C%22NewgroundsAPI_UserName%22%3A%22Reox14%22%2C%22NewgroundsAPI_UserID%22%3A19065241%2C%22ng_username%22%3A%22Reox14%22%7D%2C%22width%22%3A850%2C%22height%22%3A530%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F592000%2Fflash_592473_card.webp%3Ff1669742379%22%2C%22warnOnUnsupportedContent%22%3Afalse%7D
SWF URL: https://uploads.ungrounded.net/592000/592473_MadnessGame_ULTIMATE.swf?1507662264

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-10-14
Channel: nightly
Built: 2023-10-14T00:21:06.189Z
Commit: 93aa3a493ba4c42f80e5d5a17044702e4942f89d
Is extension: false

# Metadata
width: 850
height: 530
frameRate: 30
numFrames: 30
swfVersion: 10
backgroundColor: #FFFFFF
isActionScript3: false
uncompressedLength: 20491352

**Comment by Reox14** [comment]
I was playing and suddenly the game went dark and the error occurred. Postata was playing mpn
