### ISSUE TITLE
Sproadic error when loading a page w/ both selfhosted and extension

### ISSUE THREAD

**Issue by Herschel** [ruffle-rs/ruffle#1355]
I get the following error occasionally when loading a page using self-hosted while also having the extension installed:

```
Loading SWF file 3516_McFretN2.swf
chrome-extension://ifmckhjopmakpbnopakgedkpoemlmijg/dist/core.ruffle.fb766b0716ee43d8022f.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
ruffle.js:1 Serious error loading Ruffle: ChunkLoadError: Loading chunk 798 failed.
(error: chrome-extension://ifmckhjopmakpbnopakgedkpoemlmijg/dist/core.ruffle.fb766b0716ee43d8022f.js)
(anonymous) @ ruffle.js:1
ruffle.js:1 Serious error occurred loading SWF file: ChunkLoadError: Loading chunk 798 failed.
(error: chrome-extension://ifmckhjopmakpbnopakgedkpoemlmijg/dist/core.ruffle.fb766b0716ee43d8022f.js)
stream_swf_url @ ruffle.js:1
ruffle.js:1 Uncaught (in promise) ChunkLoadError: Loading chunk 798 failed.
(error: chrome-extension://ifmckhjopmakpbnopakgedkpoemlmijg/dist/core.ruffle.fb766b0716ee43d8022f.js)
    at Object.ao.f.j (http://localhost:8000/ruffle/ruffle.js:1:25738)
    at http://localhost:8000/ruffle/ruffle.js:1:24017
    at Array.reduce (<anonymous>)
    at Function.ao.e (http://localhost:8000/ruffle/ruffle.js:1:23994)
    at http://localhost:8000/ruffle/ruffle.js:1:1351
    at e.exports (http://localhost:8000/ruffle/ruffle.js:1:1386)
    at new e (http://localhost:8000/ruffle/ruffle.js:1:12261)
    at new e (http://localhost:8000/ruffle/ruffle.js:1:7941)
    at Function.from_native_embed_element (http://localhost:8000/ruffle/ruffle.js:1:8803)
    at f (http://localhost:8000/ruffle/ruffle.js:1:3494)
```
Occurs both in Firefox 82.0 and Chrome 86, often on the first load of the page in a tab. Reloading the page seems to fix the error.
This is running off of a local Python webserver (have not yet tried on a live server).

~May be related to #1354 and started with the bump to webpack 5.~

**Comment by Herschel** [comment]
This occurs for me on pre-webpack 5 builds as well, except with a different error (straight 404 instead of the LoadChunk error).

Seems like the extension and self-hosted are conflicting with each other; when the error occurs, the network inspector shows that `chrome-extension://ifmckhjopmakpbnopakgedkpoemlmijg/dist/core.ruffle.fb766b0716ee43d8022f.js` is trying to load, compared to `core.ruffle.js` when it works correctly. So the file URLs are perhaps getting mixed up depending on the order of execution for self-hosted vs. the extension.
