### ISSUE TITLE
Error on https://phvt7w-8080.csb.app/get/aHR0cHM6Ly9pbnRlcnN0ZWxsYXI0MjAubmV0bGlmeS5hcHA=/play/flash/

### ISSUE THREAD

**Issue by BejotaTigre3** [ruffle-rs/ruffle#13574]
# Error Info
Error name: TypeError
Error message: str.startsWith is not a function
Error stack:
```
TypeError: str.startsWith is not a function
    at rewrite_url (https://phvt7w-8080.csb.app/get/static/inject.js:9:13)
    at window.fetch (https://phvt7w-8080.csb.app/get/static/inject.js:29:11)
    at r (https://phvt7w-8080.csb.app/get/aHR0cHM6Ly9pbnRlcnN0ZWxsYXI0MjAubmV0bGlmeS5hcHA=/play/flash/ruffle.js:1:37197)
    at https://phvt7w-8080.csb.app/get/aHR0cHM6Ly9pbnRlcnN0ZWxsYXI0MjAubmV0bGlmeS5hcHA=/play/flash/ruffle.js:1:39645
    at H (https://phvt7w-8080.csb.app/get/aHR0cHM6Ly9pbnRlcnN0ZWxsYXI0MjAubmV0bGlmeS5hcHA=/play/flash/ruffle.js:1:39651)
    at ce.ensureFreshInstance (https://phvt7w-8080.csb.app/get/aHR0cHM6Ly9pbnRlcnN0ZWxsYXI0MjAubmV0bGlmeS5hcHA=/play/flash/ruffle.js:1:52378)
    at ce.load (https://phvt7w-8080.csb.app/get/aHR0cHM6Ly9pbnRlcnN0ZWxsYXI0MjAubmV0bGlmeS5hcHA=/play/flash/ruffle.js:1:54751)
    at startPlayer (https://phvt7w-8080.csb.app/get/aHR0cHM6Ly9pbnRlcnN0ZWxsYXI0MjAubmV0bGlmeS5hcHA=/play/flash/?swf=riddleschool5.swf:286:14)
    at ffd.style.display (https://phvt7w-8080.csb.app/get/aHR0cHM6Ly9pbnRlcnN0ZWxsYXI0MjAubmV0bGlmeS5hcHA=/play/flash/?swf=riddleschool5.swf:324:7)
    at req.onload (https://phvt7w-8080.csb.app/get/aHR0cHM6Ly9pbnRlcnN0ZWxsYXI0MjAubmV0bGlmeS5hcHA=/play/flash/?swf=riddleschool5.swf:251:7)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://phvt7w-8080.csb.app/get/aHR0cHM6Ly9pbnRlcnN0ZWxsYXI0MjAubmV0bGlmeS5hcHA=/play/flash/?swf=riddleschool5.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-12-21
Channel: nightly
Built: 2021-12-21T00:14:34.280Z
Commit: ccef61d0764c66d2f034ea07273d218b0f98e529
Is extension: false

**Comment by Lord-McSweeney** [comment]
This is not an issue with Ruffle, the proxy rewrites `window.fetch` to only correctly handle passing `String`s to it. This breaks when Ruffle attempts to call `window.fetch` with a `Request` as the parameter.
