### ISSUE TITLE
Error on https://game52567.konggames.com/games/raitendo/you-only-live-once/frame/de75b4fa-7c64-4844-8f2e-fc58e6c4e20c/

### ISSUE THREAD

**Issue by DemianZwart** [ruffle-rs/ruffle#13614]
# Error Info
Error name: Error
Error message: panicked at core/src/avm1/activation.rs:404:18:
No script object for display object
Error stack:
```
Error: panicked at core/src/avm1/activation.rs:404:18:
No script object for display object
    at U.n.wbg.__wbg_new_d258248ed531ff54 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.b3970bebcf9c117d3dbf.js:1:53228)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h307f95dbfd4e7fe6 (wasm://wasm/032955f2:wasm-function[9716]:0x98c1a1)
    at std::panicking::rust_panic_with_hook::h3aa054d35a0817d7 (wasm://wasm/032955f2:wasm-function[6377]:0x890b79)
    at core::panicking::panic_fmt::h3e1dd3d08288569e (wasm://wasm/032955f2:wasm-function[9525]:0x98713c)
    at ruffle_core::display_object::edit_text::EditText::try_bind_text_field_variable::h5b1bba80bb37c830 (wasm://wasm/032955f2:wasm-function[3339]:0x6ed35a)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::ha97b1733acb894c9 (wasm://wasm/032955f2:wasm-function[3986]:0x75ebfc)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::h7a5f8699b4672689 (wasm://wasm/032955f2:wasm-function[1104]:0x3b78fb)
    at ruffle_core::display_object::movie_clip::MovieClip::place_object::h98bd700ef1624d4a (wasm://wasm/032955f2:wasm-function[1978]:0x56a31b)
    at <ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::enter_frame::h21d70e119c8b988b (wasm://wasm/032955f2:wasm-function[885]:0x311c8b)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::h7a5f8699b4672689 (wasm://wasm/032955f2:wasm-function[1104]:0x3b7937)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) UHD Graphics (0x00004E71) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://game52567.konggames.com/games/raitendo/you-only-live-once/frame/de75b4fa-7c64-4844-8f2e-fc58e6c4e20c/?kongregate_host=www.kongregate.com
SWF URL: https://game52567.konggames.com/gamez/0005/2567/live/yolo.swf?kongregate_game_version=1249158969

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Edg/118.0.2088.46
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-10-19
Channel: nightly
Built: 2023-10-19T00:23:16.593Z
Commit: fd4d6921d851e788b1386affae1498e46cda939c
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 50
numFrames: 2
swfVersion: 10
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 5566959

**Comment by Lord-McSweeney** [comment]
Fixed by #11005
