### ISSUE TITLE
Error on https://venue.nu/infusions/varcade/arcade.php

### ISSUE THREAD

**Issue by trickstermuse** [ruffle-rs/ruffle#13610]
# Error Info
Error name: Error
Error message: panicked at library/alloc/src/raw_vec.rs:534:5:
capacity overflow
Error stack:
```
Error: panicked at library/alloc/src/raw_vec.rs:534:5:
capacity overflow
    at imports.wbg.__wbg_new_d258248ed531ff54 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:2479:21)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h307f95dbfd4e7fe6 (wasm://wasm/032955f2:wasm-function[9716]:0x98c1a1)
    at std::panicking::rust_panic_with_hook::h3aa054d35a0817d7 (wasm://wasm/032955f2:wasm-function[6377]:0x890b79)
    at core::panicking::panic_fmt::h3e1dd3d08288569e (wasm://wasm/032955f2:wasm-function[9525]:0x98713c)
    at alloc::raw_vec::capacity_overflow::h956ebe6bf04b9c73 (wasm://wasm/032955f2:wasm-function[9524]:0x987047)
    at ruffle_core::tag_utils::SwfMovie::from_data::h4392754d02d1ae28 (wasm://wasm/032955f2:wasm-function[792]:0x2ac222)
    at ruffle_core::loader::Loader::root_movie_loader::{{closure}}::h1d9a535ed5fd6ff0 (wasm://wasm/032955f2:wasm-function[935]:0x3467cc)
    at <ruffle_web::navigator::WebNavigatorBackend as ruffle_core::backend::navigator::NavigatorBackend>::spawn_future::{{closure}}::hfc021e1d1261a0b0 (wasm://wasm/032955f2:wasm-function[1261]:0x40fb72)
    at wasm_bindgen_futures::queue::Queue::new::{{closure}}::h9b62c1bee715c81d (wasm://wasm/032955f2:wasm-function[4345]:0x79573d)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h9e8fd55686842caf (wasm://wasm/032955f2:wasm-function[10495]:0x9a8b95)
```

# Player Info
Allows script access: true
Renderer: WebGL 2.0
Adapter Vendor: WebKit
Adapter Renderer: WebKit WebGL
Adapter Version: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Surface samples: 4 x 
Surface size: 300 x 150
Player type: Object
SWF URL: https://venue.nu/infusions/varcade/uploads/flash/MagnificentGardensAS3v2DR.swf
Param movie: https://venue.nu/infusions/varcade/uploads/flash/MagnificentGardensAS3v2DR.swf
Param quality: high
Param controller: true
Param wmode: opaque
Param play: true
Param allowfullscreen: true
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://venue.nu/infusions/varcade/arcade.php?game=8274
SWF URL: https://venue.nu/infusions/varcade/uploads/flash/MagnificentGardensAS3v2DR.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-10-19
Channel: nightly
Built: 2023-10-19T00:23:16.593Z
Commit: fd4d6921d851e788b1386affae1498e46cda939c
Is extension: true

# Metadata

**Comment by Lord-McSweeney** [comment]
The site is serving a corrupt SWF file, see https://github.com/ruffle-rs/ruffle/issues/6473
