### ISSUE TITLE
Error on Degree V12 Challenge

### ISSUE THREAD

**Issue by Computerdude77** [ruffle-rs/ruffle#13624]
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/git/checkouts/nihav-vp6-660fee9efdd4622a/83c7e10/nihav-duck/src/codecs/vp56.rs:1030:18:
index out of bounds: the len is 2 but the index is 2
Error stack:
```
Error: panicked at /home/runner/.cargo/git/checkouts/nihav-vp6-660fee9efdd4622a/83c7e10/nihav-duck/src/codecs/vp56.rs:1030:18:
index out of bounds: the len is 2 but the index is 2
    at imports.wbg.__wbg_new_d258248ed531ff54 (chrome-extension://okdbphaljlmehkflmhmkaedhebdkdiej/dist/339.js:2479:21)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h307f95dbfd4e7fe6 (wasm://wasm/032955f2:wasm-function[9716]:0x98c1a1)
    at std::panicking::rust_panic_with_hook::h3aa054d35a0817d7 (wasm://wasm/032955f2:wasm-function[6377]:0x890b79)
    at core::panicking::panic_fmt::h3e1dd3d08288569e (wasm://wasm/032955f2:wasm-function[9525]:0x98716a)
    at core::panicking::panic_bounds_check::h9245d4a825cc5107 (wasm://wasm/032955f2:wasm-function[8375]:0x933fb5)
    at nihav_duck::codecs::vp56::VP56Decoder::predict_dc::he755df5bc182e6f2 (wasm://wasm/032955f2:wasm-function[2147]:0x5b0ec2)
    at nihav_duck::codecs::vp56::VP56Decoder::decode_planes::hf1a32db45c1b2742 (wasm://wasm/032955f2:wasm-function[550]:0x837e1)
    at <ruffle_video_software::decoder::vp6::Vp6Decoder as ruffle_video_software::decoder::VideoDecoder>::decode_frame::hc2baecd7086898ae (wasm://wasm/032955f2:wasm-function[743]:0x270530)
    at <ruffle_video_software::backend::SoftwareVideoBackend as ruffle_video::backend::VideoBackend>::decode_video_stream_frame::hd2753e2339bc907f (wasm://wasm/032955f2:wasm-function[2276]:0x5d2805)
    at ruffle_web::Ruffle::tick::h916b91ed10df2686 (wasm://wasm/032955f2:wasm-function[820]:0x2da213)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (AMD, AMD Radeon(TM) Graphics (0x00001681) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }
Player type: Object
SWF URL: /games/degree_v12_challenge/degreecsshell.swf
Param bgcolor: #91e3ff
Param menu: false
Param base: /games/degree_v12_challenge/
Param flashvars: sw1=/submit-score-ticket-award-only.do?id=18603&sw2=CopyrightWrigley&sw3=12b7e958-af88-48f8-9983-89e0d2fc84c6&sw4=%2Fsubmit-score.do%3Fgame_id%3D18603%26&sw5=&sw6=18603&sw7=method%3Dget%26events%3D1111%26url%3Dhttp%3A%2F%2Fgt.candystand.com%2Fgame-track.do%3Fuuid%3D12b7e958-af88-48f8-9983-89e0d2fc84c6%26&sw8=&sw9=/games/degree_v12_challenge/us/&swlist=/games/stingers_as3/stinger_mouse.swf&session_id=2e5e0159-c37c-4ec7-938b-2cf7deea49bf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined
Attribute 6: undefined
Attribute length: undefined
Attribute getNamedItem: undefined
Attribute getNamedItemNS: undefined
Attribute item: undefined
Attribute removeNamedItem: undefined
Attribute removeNamedItemNS: undefined
Attribute setNamedItem: undefined
Attribute setNamedItemNS: undefined

# Page Info
Page URL: https://web.archive.org/web/20090704115847/http://www.candystand.com:80/play/degree-v12-challenge
SWF URL: http://www.candystand.com/games/degree_v12_challenge/degreecsshell.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-10-19
Channel: nightly
Built: 2023-10-19T00:23:16.593Z
Commit: fd4d6921d851e788b1386affae1498e46cda939c
Is extension: true

# Metadata
width: 720
height: 400
frameRate: 30
numFrames: 1
swfVersion: 9
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 222628

#Extra Info
This error occurs after the intro. Interestingly enough, the game used to load past the intro, but would have its own issues, like the video not displaying over the entire screen and the game freezing after a while. However, as of the 10-12-2023 nightly, it now has this issue. I'm not sure if this should be considered a regression or not, so I will just leave this info here for now.

**Comment by Computerdude77** [comment]
As of the 2023-12-13 nightly, the crash issue has been fixed! However, there are a few more issues that occur that I will comment on. The gameplay has an issue where the background video does not fit fully on the screen, but the objects are still in their proper place. There is an additional issue where the game will freeze after a few seconds of playing. However, clicking the instructions and closing them again will unfreeze the game for a few seconds. I have a video that shows off the issues in Ruffle and what the game is supposed to look like:

Ruffle:
https://github.com/ruffle-rs/ruffle/assets/55714746/28d2fae5-f3f4-4d67-a6a5-438924c7852e

Original Flash:
https://github.com/ruffle-rs/ruffle/assets/55714746/de97ecf6-17c1-4915-9a34-6f4d22a65d7c
