### ISSUE TITLE
Error on https://archive.aramcoworld.com/issue/200901/al-haram/tour.htm

### ISSUE THREAD

**Issue by JennyNW** [ruffle-rs/ruffle#13629]
# Error Info
Error name: Error
Error message: panicked at core/src/avm2/globals/flash/display/graphics.rs:1060:13:
Negative culling not implemented
Error stack:
```
Error: panicked at core/src/avm2/globals/flash/display/graphics.rs:1060:13:
Negative culling not implemented
    at imports.wbg.__wbg_new_d258248ed531ff54 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:2479:21)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h307f95dbfd4e7fe6 (wasm://wasm/03297862:wasm-function[9716]:0x98c95f)
    at std::panicking::rust_panic_with_hook::h3aa054d35a0817d7 (wasm://wasm/03297862:wasm-function[6377]:0x891359)
    at core::panicking::panic_fmt::h3e1dd3d08288569e (wasm://wasm/03297862:wasm-function[9525]:0x9878fa)
    at ruffle_core::avm2::globals::flash::display::graphics::draw_triangle_internal::h8d6e363c37a7e324 (wasm://wasm/03297862:wasm-function[5576]:0x854cd2)
    at ruffle_core::avm2::globals::flash::display::graphics::draw_triangles::h8bd6b7dee748e5c4 (wasm://wasm/03297862:wasm-function[806]:0x2bc9be)
    at ruffle_core::avm2::function::Executable::exec::hc502e89c019e3e09 (wasm://wasm/03297862:wasm-function[892]:0x31be6d)
    at ruffle_core::avm2::object::TObject::call_property::ha4fd34921622e94c (wasm://wasm/03297862:wasm-function[1213]:0x3f3da3)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::h04abc8832aa06d60 (wasm://wasm/03297862:wasm-function[2918]:0x6916a0)
    at ruffle_core::avm2::activation::Activation::run_actions::h68e789367910a4e8 (wasm://wasm/03297862:wasm-function[541]:0x3f068)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (AMD, AMD Radeon(TM) Graphics (0x00001636) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }
Player type: Object
SWF URL: flash/map.swf
Param quality: high
Param scale: noscale
Param menu: false
Param salign: tl
Param allowScriptAccess: always
Param flashvars: debugMode=5
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined
Attribute 6: undefined

# Page Info
Page URL: https://archive.aramcoworld.com/issue/200901/al-haram/tour.htm
SWF URL: https://archive.aramcoworld.com/issue/200901/al-haram/flash/map.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-10-20
Channel: nightly
Built: 2023-10-20T00:20:58.027Z
Commit: 8b5b135a2d08ed7b311fd0d081b32bd087e24d21
Is extension: true

# Metadata
width: 405
height: 320
frameRate: 12
numFrames: 1
swfVersion: 9
backgroundColor: #FFFFFF
isActionScript3: true
uncompressedLength: 111655

**Comment by kjarosh** [comment]
Fixed by https://github.com/ruffle-rs/ruffle/pull/13631 & https://github.com/ruffle-rs/ruffle/pull/16762
