### ISSUE TITLE
Error on https://www.minijuegos.com/helpers/game/sandbox.php

### ISSUE THREAD

**Issue by JUANJONAS20** [ruffle-rs/ruffle#13648]
# Error Info
Error name: Error
Error message: panicked at render/wgpu/src/context3d/shader_pair.rs:63:18:
called `Result::unwrap()` on an `Err` value: MissingVertexAttributeData(3)
Error stack:
```
Error: panicked at render/wgpu/src/context3d/shader_pair.rs:63:18:
called `Result::unwrap()` on an `Err` value: MissingVertexAttributeData(3)
    at U.n.wbg.__wbg_new_d258248ed531ff54 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.d576ea082d4d22534cc3.js:1:53228)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h307f95dbfd4e7fe6 (wasm://wasm/0327abbe:wasm-function[9690]:0x985fbe)
    at std::panicking::rust_panic_with_hook::h3aa054d35a0817d7 (wasm://wasm/0327abbe:wasm-function[6364]:0x88a0f6)
    at core::panicking::panic_fmt::h3e1dd3d08288569e (wasm://wasm/0327abbe:wasm-function[9498]:0x980f5d)
    at core::result::unwrap_failed::h8b3db0f11171b57b (wasm://wasm/0327abbe:wasm-function[7975]:0x9069c8)
    at <ruffle_render_wgpu::context3d::WgpuContext3D as ruffle_render::backend::Context3D>::process_command::h4cfb6c2298c45603 (wasm://wasm/0327abbe:wasm-function[560]:0xb391c)
    at ruffle_core::avm2::globals::flash::display3D::context_3d::draw_triangles::h053b7b1b25a99107 (wasm://wasm/0327abbe:wasm-function[2779]:0x65bd98)
    at ruffle_core::avm2::function::Executable::exec::hc502e89c019e3e09 (wasm://wasm/0327abbe:wasm-function[892]:0x3199ae)
    at ruffle_core::avm2::object::TObject::call_property::h38ae097804350add (wasm://wasm/0327abbe:wasm-function[1192]:0x3ea311)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::h04abc8832aa06d60 (wasm://wasm/0327abbe:wasm-function[2917]:0x6875ef)
```
AVM2 stack:
```
    at flash.display3D::Context3D/flash::display3D::Context3D::drawTriangles()
    at de.nulldesign.nd2d.materials::Sprite2DBatchMaterial/drawCurrentBatch()
    at de.nulldesign.nd2d.materials::Sprite2DBatchMaterial/processAndRenderNodes()
    at de.nulldesign.nd2d.materials::Sprite2DBatchMaterial/processAndRenderNodes()
    at de.nulldesign.nd2d.materials::Sprite2DBatchMaterial/processAndRenderNodes()
    at de.nulldesign.nd2d.materials::Sprite2DBatchMaterial/renderBatch()
    at de.nulldesign.nd2d.display::Sprite2DBatch/draw()
    at de.nulldesign.nd2d.display::Sprite2DBatch/drawNode()
    at de.nulldesign.nd2d.display::Scene2D/drawNode()
    at de.nulldesign.nd2d.display::World2D/mainLoop()
    at com.mobirate.deadahead::cWorld/mainLoop()
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA GeForce GT 220  Direct3D11 vs_4_1 ps_4_1, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 8192, max_texture_dimension_2d: 8192, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 640, height: 360, depth_or_array_layers: 1 }

# Page Info
Page URL: https://www.minijuegos.com/helpers/game/sandbox.php?mp_assets=https%3A%2F%2Fs2.minijuegosgratis.com%2F&mp_embed=0&mp_game_id=216407&mp_game_uid=dead-ahead&mp_game_url=https%3A%2F%2Fwww.minijuegos.com%2Fembed%2Fdead-ahead&mp_int=1&mp_locale=es_ES&mp_player_type=FLASH&mp_player_url=aHR0cHM6Ly93d3cubWluaWp1ZWdvc2dyYXRpcy5jb20vdjMvZ2FtZXMvZ2FtZXMvcHJvZC8yMTY0MDcvZGVhZGFoZWFkLnN3Zg%3D%3D&mp_site_https_url=https%3A%2F%2Fwww.minijuegos.com%2F&mp_site_name=minijuegos.com&mp_site_url=https%3A%2F%2Fwww.minijuegos.com%2F&mp_timezone=Europe%2FMadrid&mp_view_type=
SWF URL: https://www.minijuegosgratis.com/v3/games/games/prod/216407/deadahead.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-10-21
Channel: nightly
Built: 2023-10-21T00:20:29.571Z
Commit: 94174b30fed8e2d0762374238cc3af54701335b1
Is extension: false

# Metadata
width: 640
height: 360
frameRate: 60
numFrames: 2
swfVersion: 18
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 10856590

**Comment by n0samu** [comment]
Seems like this was fixed by #14141.
