### ISSUE TITLE
Error on https://matrix3d.github.io/assets/gl3d/test_shader/index.html

### ISSUE THREAD

**Issue by matrix3d** [ruffle-rs/ruffle#13713]
# Error Info
Error name: Error
Error message: panicked at render/wgpu/src/context3d/shader_pair.rs:77:18:
called `Result::unwrap()` on an `Err` value: Unimplemented("Unimplemented dest reg type: DestField { register_type: Attribute, write_mask: Mask(0x0), reg_num: 0 }")
Error stack:
```
Error: panicked at render/wgpu/src/context3d/shader_pair.rs:77:18:
called `Result::unwrap()` on an `Err` value: Unimplemented("Unimplemented dest reg type: DestField { register_type: Attribute, write_mask: Mask(0x0), reg_num: 0 }")
    at U.n.wbg.__wbg_new_d258248ed531ff54 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.fa55cd8e4a345c6a0df5.js:1:53228)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hee68611ee8147044 (wasm://wasm/032bf7de:wasm-function[9747]:0x995320)
    at std::panicking::rust_panic_with_hook::h3aa054d35a0817d7 (wasm://wasm/032bf7de:wasm-function[6416]:0x8981dd)
    at core::panicking::panic_fmt::h3e1dd3d08288569e (wasm://wasm/032bf7de:wasm-function[9549]:0x990199)
    at core::result::unwrap_failed::h8b3db0f11171b57b (wasm://wasm/032bf7de:wasm-function[8009]:0x915c64)
    at <ruffle_render_wgpu::context3d::WgpuContext3D as ruffle_render::backend::Context3D>::process_command::hb06bb08545441921 (wasm://wasm/032bf7de:wasm-function[561]:0xb6b5a)
    at ruffle_core::avm2::globals::flash::display3D::context_3d::draw_triangles::hf5be799537e2d53f (wasm://wasm/032bf7de:wasm-function[2811]:0x66c85b)
    at ruffle_core::avm2::function::Executable::exec::h12f8e818565825c7 (wasm://wasm/032bf7de:wasm-function[895]:0x31acc4)
    at ruffle_core::avm2::object::TObject::call_property::hb312d6c32b4a5a27 (wasm://wasm/032bf7de:wasm-function[1220]:0x3f63e3)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::h32f7a3c234fc924d (wasm://wasm/032bf7de:wasm-function[2938]:0x694515)
```
AVM2 stack:
```
    at flash.display3D::Context3D/flash::display3D::Context3D::drawTriangles()
    at gl3d.core.renders::GL/drawTriangles()
    at gl3d.core.shaders::GLShader/update()
    at gl3d.core::Material/draw()
    at gl3d.core::Node3D/update()
    at gl3d.core.renders::Stage3DRender/render()
    at gl3d.core::View3D/render()
    at BaseExample/enterFrame()
    at TestShader/enterFrame()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) UHD Graphics (0x00009B41) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }
Player type: Object
SWF URL: FlashShader.swf?v=1
Param wmode: direct
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined
Attribute 6: undefined

# Page Info
Page URL: https://matrix3d.github.io/assets/gl3d/test_shader/index.html
SWF URL: https://matrix3d.github.io/assets/gl3d/test_shader/FlashShader.swf?v=1

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Edg/118.0.2088.61
Platform: Win32
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-10-25
Channel: nightly
Built: 2023-10-25T00:24:21.468Z
Commit: 1a853803448ae68ce919ae19a2ee2c212476ac5b
Is extension: false

# Metadata
width: 800
height: 600
frameRate: 60
numFrames: 1
swfVersion: 30
backgroundColor: #FFFFFF
isActionScript3: true
uncompressedLength: 565767

**Comment by Aaron1011** [comment]
This SWF is checking `Context3D.profile`, and adjusting its AGAL generation based on the value. However, it ends up generating invalid bytecode with "baseline" (which it doesn't request, but we were returning).
