### ISSUE TITLE
Error on http://swordandsandals.top/swords-and-sandals-2-hacked/

### ISSUE THREAD

**Issue by Atman31** [ruffle-rs/ruffle#13724]
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/49d16f7/wgpu-hal/src/gles/device.rs:705:52:
called `Result::unwrap()` on an `Err` value: "Unable to create texture object"
Error stack:
```
Error: panicked at /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/49d16f7/wgpu-hal/src/gles/device.rs:705:52:
called `Result::unwrap()` on an `Err` value: "Unable to create texture object"
    at U.n.wbg.__wbg_new_d258248ed531ff54 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.fa55cd8e4a345c6a0df5.js:1:53228)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hee68611ee8147044 (wasm://wasm/032bf7de:wasm-function[9747]:0x995320)
    at std::panicking::rust_panic_with_hook::h3aa054d35a0817d7 (wasm://wasm/032bf7de:wasm-function[6416]:0x8981dd)
    at core::panicking::panic_fmt::h3e1dd3d08288569e (wasm://wasm/032bf7de:wasm-function[9549]:0x990199)
    at core::result::unwrap_failed::h8b3db0f11171b57b (wasm://wasm/032bf7de:wasm-function[8009]:0x915c64)
    at <T as wgpu::context::DynContext>::device_create_texture::he876a6b2d583c4cf (wasm://wasm/032bf7de:wasm-function[7117]:0x8d0237)
    at wgpu::Device::create_texture::h1488ca4a9eae3889 (wasm://wasm/032bf7de:wasm-function[5474]:0x8456d0)
    at <ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::create_empty_texture::h7d610b414d010f7e (wasm://wasm/032bf7de:wasm-function[5280]:0x8359cf)
    at ruffle_core::display_object::render_base::he237c99ce8842038 (wasm://wasm/032bf7de:wasm-function[597]:0x143d8e)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render::he3bea35f3cc1df26 (wasm://wasm/032bf7de:wasm-function[6965]:0x8bae7d)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA GeForce GT 730 (0x00000F02) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: http://swordandsandals.top/swords-and-sandals-2-hacked/
SWF URL: http://swordandsandals.top/wp-content/uploads/swordsandsandals2-hacked.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-10-26
Channel: nightly
Built: 2023-10-26T00:21:16.921Z
Commit: 27831d78810de2db5214c298b0eb46c7cc3c6299
Is extension: false

# Metadata
width: 700
height: 525
frameRate: 30
numFrames: 1
swfVersion: 8
backgroundColor: #FFFFFF
isActionScript3: false
uncompressedLength: 760

**Comment by evilpie** [comment]
Duplicate of https://github.com/ruffle-rs/ruffle/issues/11852
