### ISSUE TITLE
Error on https://www.minijuegos.mx/helpers/game/sandbox.php

### ISSUE THREAD

**Issue by Verito2912** [ruffle-rs/ruffle#13748]
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/git/checkouts/rust-flash-lso-7db697fbf6bd96f3/3669a35/flash-lso/src/amf3/read.rs:418:14:
Unable to get Object
Error stack:
```
Error: panicked at /home/runner/.cargo/git/checkouts/rust-flash-lso-7db697fbf6bd96f3/3669a35/flash-lso/src/amf3/read.rs:418:14:
Unable to get Object
    at U.n.wbg.__wbg_new_d258248ed531ff54 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.01a65266b2f772fe899a.js:1:53228)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hee68611ee8147044 (wasm://wasm/032c14e6:wasm-function[9747]:0x995843)
    at std::panicking::rust_panic_with_hook::h3aa054d35a0817d7 (wasm://wasm/032c14e6:wasm-function[6417]:0x898717)
    at core::panicking::panic_fmt::h3e1dd3d08288569e (wasm://wasm/032c14e6:wasm-function[9550]:0x9906eb)
    at core::option::expect_failed::hea22cf135ad64e98 (wasm://wasm/032c14e6:wasm-function[8958]:0x966c70)
    at flash_lso::amf3::read::AMF3Decoder::parse_element_object::hd9b49926bf1e8bd3 (wasm://wasm/032c14e6:wasm-function[703]:0x2203da)
    at flash_lso::amf3::read::AMF3Decoder::parse_single_element::h732c6207cdeec25b (wasm://wasm/032c14e6:wasm-function[596]:0x141abb)
    at nom::multi::many_m_n::{{closure}}::h449c1f05ae1be736 (wasm://wasm/032c14e6:wasm-function[3018]:0x6a4371)
    at flash_lso::amf3::read::AMF3Decoder::parse_single_element::h732c6207cdeec25b (wasm://wasm/032c14e6:wasm-function[596]:0x141859)
    at flash_lso::amf3::read::AMF3Decoder::parse_object_static::h8fbeac513fdcae0f (wasm://wasm/032c14e6:wasm-function[4102]:0x7742ca)
```
AVM2 stack:
```
    at flash.utils::ByteArray/flash::utils::ByteArray::readObject()
    at BinaryData$/getMovieClipManager()
    at Game/onLoadComplete()
    at Game()
    at Main/createGame()
    at Main/onRootCreated()
    at starling.events::EventDispatcher/invokeEvent()
    at starling.events::EventDispatcher/dispatchEvent()
    at starling.events::EventDispatcher/dispatchEventWith()
    at starling.core::Starling/initializeRoot()
    at starling.core::Starling/initialize()
    at starling.core::Starling/onContextCreated()
    at flash.events::EventDispatcher/flash::events::EventDispatcher::dispatchEvent()
    at flash.display::Stage3D/flash::display::Stage3D::requestContext3D_internal()
    at MethodInfo-1727()
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) UHD Graphics (0x00009A78) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 800, height: 600, depth_or_array_layers: 1 }

# Page Info
Page URL: https://www.minijuegos.mx/helpers/game/sandbox.php?mp_assets=https%3A%2F%2Fs2.minijuegosgratis.com%2F&mp_embed=0&mp_game_id=206531&mp_game_uid=tequila-zombies-3&mp_game_url=https%3A%2F%2Fwww.minijuegos.mx%2Fembed%2Ftequila-zombies-3&mp_int=1&mp_locale=es_MX&mp_player_type=FLASH&mp_player_url=aHR0cHM6Ly93d3cubWluaWp1ZWdvc2dyYXRpcy5jb20vdjMvZ2FtZXMvZ2FtZXMvcHJvZC8yMDY1MzEvdGVxdWlsYS0zLnN3Zg%3D%3D&mp_site_https_url=https%3A%2F%2Fwww.minijuegos.mx%2F&mp_site_name=minijuegos.mx&mp_site_url=https%3A%2F%2Fwww.minijuegos.mx%2F&mp_timezone=America%2FMexico_City&mp_view_type=
SWF URL: https://www.minijuegosgratis.com/v3/games/games/prod/206531/tequila-3.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-10-27
Channel: nightly
Built: 2023-10-27T00:28:30.256Z
Commit: fd6568aa8076bc42f71d40d3d0ec955342d38ea6
Is extension: false

# Metadata
width: 800
height: 600
frameRate: 30
numFrames: 2
swfVersion: 21
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 38081696

**Comment by Verito2912** [comment]
no pued jugar pesimo servicio

**Comment by randomusername-a** [comment]
> no pued jugar pesimo servicio

a quien pagaste para que te estés quejando 💀

**Comment by torokati44** [comment]
This supposedly got fixed by https://github.com/ruffle-rs/ruffle/pull/18046.
