### ISSUE TITLE
Error on https://www.miniplay.com/helpers/game/sandbox.php

### ISSUE THREAD

**Issue by kowsarashkir** [ruffle-rs/ruffle#13795]
# Error Info
Error name: Error
Error message: panicked at core/src/avm1/activation.rs:404:18:
No script object for display object
Error stack:
```
Error: panicked at core/src/avm1/activation.rs:404:18:
No script object for display object
    at U.n.wbg.__wbg_new_d258248ed531ff54 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.4b9d9d5a2a685b3f3581.js:1:53303)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h39d263798a7efedc (wasm://wasm/032bc3de:wasm-function[9762]:0x994ddb)
    at std::panicking::rust_panic_with_hook::h3aa054d35a0817d7 (wasm://wasm/032bc3de:wasm-function[6409]:0x895dc9)
    at core::panicking::panic_fmt::h3e1dd3d08288569e (wasm://wasm/032bc3de:wasm-function[9568]:0x98fcea)
    at ruffle_core::display_object::edit_text::EditText::try_bind_text_field_variable::hba1f4b2c188c2b69 (wasm://wasm/032bc3de:wasm-function[3493]:0x715323)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::h1244176c7cd99039 (wasm://wasm/032bc3de:wasm-function[5126]:0x8216e4)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::hb98dd0b51c125840 (wasm://wasm/032bc3de:wasm-function[1138]:0x3d5298)
    at ruffle_core::display_object::movie_clip::MovieClip::place_object::h57ff300bdbb69d05 (wasm://wasm/032bc3de:wasm-function[2009]:0x581fbd)
    at <ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::enter_frame::h57f1c62ec10ee565 (wasm://wasm/032bc3de:wasm-function[886]:0x31775b)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::hb98dd0b51c125840 (wasm://wasm/032bc3de:wasm-function[1138]:0x3d52d4)
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel Inc., Intel(R) HD Graphics 6000, OpenGL 4.1)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 800, height: 440, depth_or_array_layers: 1 }

# Page Info
Page URL: https://www.miniplay.com/helpers/game/sandbox.php?mp_assets=https%3A%2F%2Fs2.minijuegosgratis.com%2F&mp_embed=0&mp_game_id=200426&mp_game_uid=sift-heads-cartels&mp_game_url=https%3A%2F%2Fwww.miniplay.com%2Fembed%2Fsift-heads-cartels&mp_int=1&mp_locale=en_US&mp_player_type=FLASH&mp_player_url=aHR0cHM6Ly93d3cubWluaWp1ZWdvc2dyYXRpcy5jb20vdjMvZ2FtZXMvZ2FtZXMvcHJvZC8yMDA0MjYvc2lmdGhlYWRzY2FydGVsczEuc3dm&mp_site_https_url=https%3A%2F%2Fwww.miniplay.com%2F&mp_site_name=miniplay.com&mp_site_url=https%3A%2F%2Fwww.miniplay.com%2F&mp_timezone=Europe%2FLondon&mp_view_type=
SWF URL: https://www.minijuegosgratis.com/v3/games/games/prod/200426/siftheadscartels1.swf

# Browser Info
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
Platform: MacIntel
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-10-30
Channel: nightly
Built: 2023-10-30T00:20:56.782Z
Commit: 5bebebddbe3c39362ba520cb0c9c28b3cb7f72a3
Is extension: false

# Metadata
width: 800
height: 440
frameRate: 50
numFrames: 2
swfVersion: 17
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 8246607

**Comment by n0samu** [comment]
Fixed by #11005
