### ISSUE TITLE
Error on https://game211184.konggames.com/games/Runouw/last-legacy-null-space/frame/8f335376-2df1-4b22-bb14-d07719106225/

### ISSUE THREAD

**Issue by SemmZemm** [ruffle-rs/ruffle#13797]
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/git/checkouts/rust-flash-lso-7db697fbf6bd96f3/3669a35/flash-lso/src/amf3/read.rs:260:18:
Reference still held to rc
Error stack:
```
Error: panicked at /home/runner/.cargo/git/checkouts/rust-flash-lso-7db697fbf6bd96f3/3669a35/flash-lso/src/amf3/read.rs:260:18:
Reference still held to rc
    at U.n.wbg.__wbg_new_d258248ed531ff54 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.4b9d9d5a2a685b3f3581.js:1:53303)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h39d263798a7efedc (wasm://wasm/032bc3de:wasm-function[9762]:0x994ddb)
    at std::panicking::rust_panic_with_hook::h3aa054d35a0817d7 (wasm://wasm/032bc3de:wasm-function[6409]:0x895dc9)
    at core::panicking::panic_fmt::h3e1dd3d08288569e (wasm://wasm/032bc3de:wasm-function[9568]:0x98fd18)
    at core::option::expect_failed::hea22cf135ad64e98 (wasm://wasm/032bc3de:wasm-function[8973]:0x96507a)
    at flash_lso::amf3::read::AMF3Decoder::parse_single_element::h732c6207cdeec25b (wasm://wasm/032bc3de:wasm-function[596]:0x13f62d)
    at flash_lso::amf3::read::AMF3Decoder::parse_element_object::hd9b49926bf1e8bd3 (wasm://wasm/032bc3de:wasm-function[701]:0x225e9a)
    at flash_lso::amf3::read::AMF3Decoder::parse_single_element::h732c6207cdeec25b (wasm://wasm/032bc3de:wasm-function[596]:0x13de28)
    at nom::multi::many_m_n::{{closure}}::h449c1f05ae1be736 (wasm://wasm/032bc3de:wasm-function[3051]:0x6b2e65)
    at flash_lso::amf3::read::AMF3Decoder::parse_single_element::h732c6207cdeec25b (wasm://wasm/032bc3de:wasm-function[596]:0x13dbc6)
```
AVM2 stack:
```
    at flash.net::SharedObject/flash::net::SharedObject::getLocal()
    at com.runouw.ll::SavedData()
    at com.runouw.ll::Main/init()
    at flash.display::DisplayObjectContainer/flash::display::DisplayObjectContainer::addChild()
    at com.runouw.ll::Preloader/startup()
    at com.runouw.ll::Preloader/loadingFinished()
    at com.runouw.ll::Preloader/checkFrame()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Apple, Apple M1 Pro, OpenGL 4.1)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://game211184.konggames.com/games/Runouw/last-legacy-null-space/frame/8f335376-2df1-4b22-bb14-d07719106225/?kongregate_host=www.kongregate.com
SWF URL: https://game211184.konggames.com/gamez/0021/1184/live/LastLegacy2.swf?kongregate_game_version=1402460597

# Browser Info
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
Platform: MacIntel
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-10-30
Channel: nightly
Built: 2023-10-30T00:20:56.782Z
Commit: 5bebebddbe3c39362ba520cb0c9c28b3cb7f72a3
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 30
numFrames: 2
swfVersion: 15
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 22785924

**Comment by CUB3D** [comment]
As of e353fdc1c3e47939807e1d9b109050ed68ca5d62, I'm unable to recreate this. Tried: creating a save, beating first level, restarting Ruffle, loading save. Also doesn't panic on nightly-2024-05-01, might be fixed?
