### ISSUE TITLE
Error on https://flashthemes.net/character/browser/family

### ISSUE THREAD

**Issue by MrButton5** [ruffle-rs/ruffle#13836]
# Error Info
Error name: Error
Error message: panicked at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys/wasm/../unsupported/locks/mutex.rs:20:9:
assertion `left == right` failed: cannot recursively acquire mutex
  left: true
 right: false
Error stack:
```
Error: panicked at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys/wasm/../unsupported/locks/mutex.rs:20:9:
assertion `left == right` failed: cannot recursively acquire mutex
  left: true
 right: false
    at imports.wbg.__wbg_new_d258248ed531ff54 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:2483:21)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h39d263798a7efedc (wasm://wasm/032bc3de:wasm-function[9762]:0x994ddb)
    at std::panicking::rust_panic_with_hook::h3aa054d35a0817d7 (wasm://wasm/032bc3de:wasm-function[6409]:0x895dc9)
    at core::panicking::panic_fmt::h3e1dd3d08288569e (wasm://wasm/032bc3de:wasm-function[9568]:0x98fd18)
    at core::panicking::assert_failed_inner::hef8aa9140ed3b15c (wasm://wasm/032bc3de:wasm-function[4612]:0x7b5f64)
    at core::panicking::assert_failed::h591ffc75efea41fe (wasm://wasm/032bc3de:wasm-function[9588]:0x990f05)
    at ruffle_core::loader::Loader::root_movie_loader::{{closure}}::h8b7f993c49690a23 (wasm://wasm/032bc3de:wasm-function[931]:0x349b81)
    at <ruffle_web::navigator::WebNavigatorBackend as ruffle_core::backend::navigator::NavigatorBackend>::spawn_future::{{closure}}::h8243354044484218 (wasm://wasm/032bc3de:wasm-function[1272]:0x41c7d3)
    at wasm_bindgen_futures::queue::Queue::new::{{closure}}::h9b62c1bee715c81d (wasm://wasm/032bc3de:wasm-function[4382]:0x7977c9)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h9e8fd55686842caf (wasm://wasm/032bc3de:wasm-function[10539]:0x9b2607)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) HD Graphics 610 Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 990, height: 1200, depth_or_array_layers: 1 }
Player type: Object
SWF URL: /static/animationnew/414827163ad4eb60/cc_browser.swf
Param align: middle
Param allowScriptAccess: always
Param allowFullScreen: true
Param wmode: transparent
Param flashvars: apiserver=https%3A%2F%2Fflashthemes.net%2F&userId=2687&isLogin=Y&m_mode=school&isEmbed=0&ctc=go&tlang=en_US&appCode=go&storePath=%2Fstatic%2Fstore%2F%3Cstore%3E&ut=60&v=2687&nextUrl=https%3A%2F%2Fflashthemes.net%2Fcharacter%2Fbrowser&clientThemePath=%2Fstatic%2Fct%2Fad44370a650793d9%2F%3Cclient_theme%3E&themeId=family
Param movie: /static/animationnew/414827163ad4eb60/cc_browser.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://flashthemes.net/character/browser/family
SWF URL: https://flashthemes.net/static/animationnew/414827163ad4eb60/cc_browser.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 OPR/102.0.0.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-10-30
Channel: nightly
Built: 2023-10-30T00:20:56.782Z
Commit: 5bebebddbe3c39362ba520cb0c9c28b3cb7f72a3
Is extension: true

# Metadata

**Comment by n0samu** [comment]
Closing in favor of #13974
