### ISSUE TITLE
Error on http://www.trochoivui.com/game/19782/thi-dau-bong-da-euro-2016.html

### ISSUE THREAD

**Issue by Huonghuong1** [ruffle-rs/ruffle#13861]
# Error Info
Error name: Error
Error message: panicked at core/src/avm2/globals/flash/display/graphics.rs:1057:13:
Positive culling not implemented
Error stack:
```
Error: panicked at core/src/avm2/globals/flash/display/graphics.rs:1057:13:
Positive culling not implemented
    at U.n.wbg.__wbg_new_d258248ed531ff54 (http://www.trochoivui.com/ruffle/core.ruffle.b57a46ab31c228f2633f.js:1:53228)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h307f95dbfd4e7fe6 (wasm://wasm/0329d22a:wasm-function[9706]:0x98e419)
    at std::panicking::rust_panic_with_hook::h3aa054d35a0817d7 (wasm://wasm/0329d22a:wasm-function[6362]:0x8921d3)
    at core::panicking::panic_fmt::h3e1dd3d08288569e (wasm://wasm/0329d22a:wasm-function[9515]:0x9893b4)
    at ruffle_core::avm2::globals::flash::display::graphics::draw_triangle_internal::h8d6e363c37a7e324 (wasm://wasm/0329d22a:wasm-function[5565]:0x855ca1)
    at ruffle_core::avm2::globals::flash::display::graphics::draw_triangles::h8bd6b7dee748e5c4 (wasm://wasm/0329d22a:wasm-function[807]:0x2bb3ef)
    at ruffle_core::avm2::function::Executable::exec::hc502e89c019e3e09 (wasm://wasm/0329d22a:wasm-function[891]:0x31860d)
    at ruffle_core::avm2::object::TObject::call_property::ha4fd34921622e94c (wasm://wasm/0329d22a:wasm-function[1212]:0x3f1468)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::h04abc8832aa06d60 (wasm://wasm/0329d22a:wasm-function[2924]:0x69675e)
    at ruffle_core::avm2::activation::Activation::run_actions::h68e789367910a4e8 (wasm://wasm/0329d22a:wasm-function[541]:0x3f136)
```
AVM2 stack:
```
    at flash.display::Graphics/flash::display::Graphics::drawTriangles()
    at _-WZ::_-75/Render()
    at _-WZ::_-HX/Render()
    at _-IX/Render()
    at _-N5/Render()
    at _-2l::_-C0/RenderI()
    at _-2l::_-0U/Render()
    at Mr::_-T5/Render()
    at _-De::Platform/Update()
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) HD Graphics 5500 Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: http://www.trochoivui.com/game/19782/thi-dau-bong-da-euro-2016.html
SWF URL: http://www.trochoivui.com/giaitri/game3/speedplay-soccer-4.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-10-18
Channel: nightly
Built: 2023-10-18T00:25:07.036Z
Commit: e6f9796094b645566050c7e45b6f642d4887a149
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 60
numFrames: 2
swfVersion: 10
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 1943340

**Comment by Lord-McSweeney** [comment]
Was fixed by #16762
