### ISSUE TITLE
Error on https://game165174.konggames.com/games/ffgameplayer/clan-wars-2-red-reign/frame/66988d78-7043-4964-beb4-91dd81dc1628/

### ISSUE THREAD

**Issue by Mechbomber06** [ruffle-rs/ruffle#13873]
# Error Info
Error name: Error
Error message: panicked at core/src/avm1/activation.rs:404:18:
No script object for display object
Error stack:
```
Error: panicked at core/src/avm1/activation.rs:404:18:
No script object for display object
    at imports.wbg.__wbg_new_d258248ed531ff54 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:2617:21)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h1ee9579dbb0a58f1 (wasm://wasm/03376b0e:wasm-function[9862]:0x9b4830)
    at std::panicking::rust_panic_with_hook::h3aa054d35a0817d7 (wasm://wasm/03376b0e:wasm-function[6477]:0x8b5902)
    at core::panicking::panic_fmt::h3e1dd3d08288569e (wasm://wasm/03376b0e:wasm-function[9663]:0x9af629)
    at ruffle_core::display_object::edit_text::EditText::try_bind_text_field_variable::he6a1f53fc6389a67 (wasm://wasm/03376b0e:wasm-function[3458]:0x71885f)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::h889f6dbc74506cc4 (wasm://wasm/03376b0e:wasm-function[4078]:0x784bd3)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::hb938c09cf7461cb3 (wasm://wasm/03376b0e:wasm-function[1137]:0x3c7ee8)
    at ruffle_core::display_object::movie_clip::MovieClip::place_object::h1e404ec0f13d4a17 (wasm://wasm/03376b0e:wasm-function[2052]:0x597ccc)
    at <ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::enter_frame::h762e4f21ff4d93bb (wasm://wasm/03376b0e:wasm-function[911]:0x31c2b7)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::hb938c09cf7461cb3 (wasm://wasm/03376b0e:wasm-function[1137]:0x3c7f24)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (ATI Technologies Inc., AMD Radeon Pro 5500M OpenGL Engine, OpenGL 4.1)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 16384, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://game165174.konggames.com/games/ffgameplayer/clan-wars-2-red-reign/frame/66988d78-7043-4964-beb4-91dd81dc1628/?kongregate_host=www.kongregate.com
SWF URL: https://game165174.konggames.com/gamez/0016/5174/live/Clan-Wars-2-Red-Reign.swf?kongregate_game_version=1359068642

# Browser Info
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36
Platform: MacIntel
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-11-05
Channel: nightly
Built: 2023-11-05T00:22:28.791Z
Commit: fca17a0061d30342ab06f4b0443212ca93d1c3f8
Is extension: true

# Metadata
width: 700
height: 500
frameRate: 24
numFrames: 2
swfVersion: 14
backgroundColor: #999999
isActionScript3: true
uncompressedLength: 5735239

**Comment by Lord-McSweeney** [comment]
Fixed by #11005
