### ISSUE TITLE
Error on http://chicken.rf.gd/

### ISSUE THREAD

**Issue by Tardidusers21** [ruffle-rs/ruffle#13897]
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/git/checkouts/rust-flash-lso-7db697fbf6bd96f3/3669a35/flash-lso/src/amf3/read.rs:260:18:
Reference still held to rc
Error stack:
```
Error: panicked at /home/runner/.cargo/git/checkouts/rust-flash-lso-7db697fbf6bd96f3/3669a35/flash-lso/src/amf3/read.rs:260:18:
Reference still held to rc
    at H.n.wbg.__wbg_new_d258248ed531ff54 (https://cdn.jsdelivr.net/npm/@ruffle-rs/ruffle@0.1.0-nightly.2023.11.5/core.ruffle.7d4e43a51c194b119ab2.js:1:55843)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h1ee9579dbb0a58f1 (wasm://wasm/03376b0e:wasm-function[9862]:0x9b4830)
    at std::panicking::rust_panic_with_hook::h3aa054d35a0817d7 (wasm://wasm/03376b0e:wasm-function[6477]:0x8b5902)
    at core::panicking::panic_fmt::h3e1dd3d08288569e (wasm://wasm/03376b0e:wasm-function[9663]:0x9af657)
    at core::option::expect_failed::hea22cf135ad64e98 (wasm://wasm/03376b0e:wasm-function[9068]:0x98727c)
    at flash_lso::amf3::read::AMF3Decoder::parse_single_element::h732c6207cdeec25b (wasm://wasm/03376b0e:wasm-function[619]:0x13c574)
    at <F as nom::internal::Parser<I,O,E>>::parse::h61f03220d68d1f6f (wasm://wasm/03376b0e:wasm-function[4133]:0x78e4dd)
    at flash_lso::read::Reader::parse::h76706ab3c669a7f0 (wasm://wasm/03376b0e:wasm-function[4581]:0x7caf63)
    at ruffle_core::avm2::globals::flash::net::shared_object::get_local::h6c28511391013044 (wasm://wasm/03376b0e:wasm-function[637]:0x17062a)
    at ruffle_core::avm2::function::Executable::exec::hf82ffb5f0197d6d7 (wasm://wasm/03376b0e:wasm-function[853]:0x2e39d6)
```
AVM2 stack:
```
    at flash.net::SharedObject/flash::net::SharedObject::getLocal()
    at DoomGame/initGame()
    at DoomGame/tickPreloader()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA GeForce RTX 3050 (0x00002507) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }
Player type: Object
SWF URL: doom.swf
Param movie: doom.swf
Param quality: high
Param play: true
Param loop: true
Param wmode: transparent
Param allowFullScreen: true
Attribute 0: undefined
Attribute 1: undefined

# Page Info
Page URL: http://chicken.rf.gd/?i=1
SWF URL: http://chicken.rf.gd/doom.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-11-05
Channel: nightly
Built: 2023-11-05T00:22:28.791Z
Commit: fca17a0061d30342ab06f4b0443212ca93d1c3f8
Is extension: false

# Metadata
width: 960
height: 600
frameRate: 35
numFrames: 2
swfVersion: 10
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 6421559

**Comment by CUB3D** [comment]
This looks like a dupe of #13162
