### ISSUE TITLE
Error on https://flashthemes.net/

### ISSUE THREAD

**Issue by Torunskie** [ruffle-rs/ruffle#13974]
# Error Info
Error name: Error
Error message: panicked at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys/wasm/../unsupported/locks/mutex.rs:20:9:
assertion `left == right` failed: cannot recursively acquire mutex
  left: true
 right: false
Error stack:
```
Error: panicked at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys/wasm/../unsupported/locks/mutex.rs:20:9:
assertion `left == right` failed: cannot recursively acquire mutex
  left: true
 right: false
    at imports.wbg.__wbg_new_ab87fd305ed9004b (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:2624:21)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h2b09d9124792ee2e (wasm://wasm/0340036e:wasm-function[9968]:0x9cff40)
    at std::panicking::rust_panic_with_hook::h3aa054d35a0817d7 (wasm://wasm/0340036e:wasm-function[6528]:0x8cfe82)
    at core::panicking::panic_fmt::h3e1dd3d08288569e (wasm://wasm/0340036e:wasm-function[9765]:0x9caca7)
    at core::panicking::assert_failed_inner::hef8aa9140ed3b15c (wasm://wasm/0340036e:wasm-function[4689]:0x7ec47a)
    at core::panicking::assert_failed::h23aa3e358d9e8b41 (wasm://wasm/0340036e:wasm-function[9788]:0x9cbf39)
    at ruffle_core::loader::Loader::load_url_loader::{{closure}}::h0364a7103619666f (wasm://wasm/0340036e:wasm-function[2367]:0x61cdf4)
    at <ruffle_web::navigator::WebNavigatorBackend as ruffle_core::backend::navigator::NavigatorBackend>::spawn_future::{{closure}}::ha900fb615bdef76b (wasm://wasm/0340036e:wasm-function[1276]:0x4289e9)
    at wasm_bindgen_futures::queue::Queue::new::{{closure}}::he37abb0fe73c3c00 (wasm://wasm/0340036e:wasm-function[4427]:0x7cab57)
    at wasm_bindgen::convert::closures::invoke1_mut::hc3ec77a0497bbd89 (wasm://wasm/0340036e:wasm-function[10749]:0x9ec5cb)
```
AVM2 stack:
```
    at flash.external::ExternalInterface/flash::external::ExternalInterface::addCallback()
    at anifire.player.components::PreviewPlayer/initAPI()
    at anifire.player.components::PreviewPlayer/onCreationCompleted()
    at anifire.player.components::PreviewPlayer/___PreviewPlayer_Group1_creationComplete()
    at flash.events::EventDispatcher/flash::events::EventDispatcher::dispatchEvent()
    at mx.core::UIComponent/dispatchEvent()
    at mx.core::UIComponent/set initialized()
    at mx.managers::LayoutManager/doPhasedInstantiation()
    at mx.managers::LayoutManager/doPhasedInstantiationCallback()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA GeForce GT 1030 (0x00001D01) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: low
Surface samples: 1
Surface size: Extent3d { width: 550, height: 384, depth_or_array_layers: 1 }
Player type: Object
SWF URL: /static/animationnew/414827163ad4eb60/player.swf
Param bgcolor: #000000
Param scale: exactfit
Param quality: low
Param allowScriptAccess: always
Param allowFullScreen: true
Param flashvars: movieId=qDCWDEn&storePath=%2Fstatic%2Fstore%2F%3Cstore%3E%3Fv%3D490&thumburl=%2Fmovie_thumbs%2Fthumb-qDCWDEn.png&v=490&movieLid=6&pwm=0&ut=-1&apiserver=https%3A%2F%2Fflashthemes.net%2F&playcount=1&copyable=0&isPublished=1&ctc=go&tlang=en_US&is_private_shared=0&autostart=1&isInitFromExternal=0&isWide=0&appCode=go&is_slideshow=0&is_emessage=0&clientThemePath=%2Fstatic%2Fct%2Fad44370a650793d9%2F%3Cclient_theme%3E&animationPath=&isEmbed=0&&&&isTemplate=0&showButtons=1&chain_mids=&endStyle=0&showshare=true
Param movie: /static/animationnew/414827163ad4eb60/player.swf
Param wmode: opaque
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://flashthemes.net/
SWF URL: https://flashthemes.net/static/animationnew/414827163ad4eb60/player.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-11-12
Channel: nightly
Built: 2023-11-12T00:23:04.159Z
Commit: c360d45729a3fde837f4ce380e67cb9b6398f3a3
Is extension: true

# Metadata
width: 500
height: 375
frameRate: 24
numFrames: 2
swfVersion: 14
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 1799596

**Comment by Thehelper104** [comment]
im assuming that the api class used for this on flashthemes isnt currently in ruffle.

**Comment by danielhjacobs** [comment]
The issue is actually slightly interesting here. A function called isPlaying is being added to the SWF embed on this website by ExternalInterface. Unfortunately, the RufflePlayer has a function called isPlaying as well. @Dinnerbone suggested on Discord to fix this as follows:

> Polyfilled elements would only have one new method, ruffle(apiVersion). Everything else matches flash

This would be a breaking change. I believe the intent is you could then do `embed.ruffle("1.0.0").isPlaying()` to use the `isPlaying()` method of `RufflePlayer`, but `embed.isPlaying()`, which is what this does essentially, would call the ExternalInterface `isPlaying()` function. Similarly, `embed.Play();` could then be used for things like https://github.com/ruffle-rs/ruffle/issues/7868

**Comment by Outfit8TSB** [comment]
oh, i posted #16567 and i just realize that someone was experiencing same issues. flashthemes should fix the issue by themself.
