### ISSUE TITLE
Error on https://www.spiele-kostenlos-online.de/fungames/lustige-ballerspiele/tequila-zombies-3/

### ISSUE THREAD

**Issue by Antoniobajan1** [ruffle-rs/ruffle#14002]
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/git/checkouts/rust-flash-lso-7db697fbf6bd96f3/2f976fb/flash-lso/src/amf3/read.rs:417:14:
Unable to get Object
Error stack:
```
Error: panicked at /home/runner/.cargo/git/checkouts/rust-flash-lso-7db697fbf6bd96f3/2f976fb/flash-lso/src/amf3/read.rs:417:14:
Unable to get Object
    at N.n.wbg.__wbg_new_ab87fd305ed9004b (https://cdn.spiele-kostenlos-online.de/wp-content/themes/spiele-kostenlos-online/js/ruffle/2023_11_13/core.ruffle.f2fd497abcf86f9db206.js:1:58763)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h2b09d9124792ee2e (<anonymous>:wasm-function[10023]:0xa1ed65)
    at std::panicking::rust_panic_with_hook::h3aa054d35a0817d7 (<anonymous>:wasm-function[6611]:0x9084c4)
    at core::panicking::panic_fmt::h3e1dd3d08288569e (<anonymous>:wasm-function[9826]:0xa19a97)
    at core::option::expect_failed::hea22cf135ad64e98 (<anonymous>:wasm-function[9215]:0x9e3440)
    at flash_lso::amf3::read::AMF3Decoder::parse_single_element::hb60ca089266ca7ff (<anonymous>:wasm-function[620]:0x14a824)
    at flash_lso::amf3::read::AMF3Decoder::parse_single_element::hb60ca089266ca7ff (<anonymous>:wasm-function[620]:0x147d1c)
    at flash_lso::amf3::read::AMF3Decoder::parse_object_static::haa531cedeb2ef2b5 (<anonymous>:wasm-function[4282]:0x7e0db6)
    at flash_lso::amf3::read::AMF3Decoder::parse_single_element::hb60ca089266ca7ff (<anonymous>:wasm-function[620]:0x14a65e)
    at flash_lso::amf3::read::AMF3Decoder::parse_object_static::haa531cedeb2ef2b5 (<anonymous>:wasm-function[4282]:0x7e0db6)
```
AVM2 stack:
```
    at flash.utils::ByteArray/flash::utils::ByteArray::readObject()
    at BinaryData$/getMovieClipManager()
    at Game/onLoadComplete()
    at Game()
    at Main/createGame()
    at Main/onRootCreated()
    at starling.events::EventDispatcher/invokeEvent()
    at starling.events::EventDispatcher/dispatchEvent()
    at starling.events::EventDispatcher/dispatchEventWith()
    at starling.core::Starling/initializeRoot()
    at starling.core::Starling/initialize()
    at starling.core::Starling/onContextCreated()
    at flash.events::EventDispatcher/flash::events::EventDispatcher::dispatchEvent()
    at flash.display::Stage3D/flash::display::Stage3D::requestContext3D_internal()
    at MethodInfo-1806()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel(R) UHD Graphics 630 Direct3D11 vs_5_0 ps_5_0)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://www.spiele-kostenlos-online.de/fungames/lustige-ballerspiele/tequila-zombies-3/
SWF URL: https://cache.spiele-kostenlos-online.de/flashgames/TequilaZombies3AS3v2TH.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-11-13
Channel: nightly
Built: 2023-11-13T00:14:23.579Z
Commit: 11c5a68452e53858871a0c3567a3c8368d6596be
Is extension: false

# Metadata
width: 800
height: 600
frameRate: 30
numFrames: 2
swfVersion: 21
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 38091418

**Comment by n0samu** [comment]
Duplicate of #13748
