### ISSUE TITLE
Error on https://www.miniplay.com/helpers/game/sandbox.php

### ISSUE THREAD

**Issue by sdwqefgwef666** [ruffle-rs/ruffle#14027]
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/49d16f7/wgpu/src/backend/direct.rs:3056:5:
wgpu error: Validation Error

Caused by:
    In CommandEncoder::copy_texture_to_texture
    Copy error
    Copy of Y 4294967293..214 would end up overrunning the bounds of the Destination texture of Y size 545

Error stack:
```
Error: panicked at /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/49d16f7/wgpu/src/backend/direct.rs:3056:5:
wgpu error: Validation Error

Caused by:
    In CommandEncoder::copy_texture_to_texture
    Copy error
    Copy of Y 4294967293..214 would end up overrunning the bounds of the Destination texture of Y size 545


    at H.n.wbg.__wbg_new_ab87fd305ed9004b (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.5dcaa225af3bc049878c.js:1:56255)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h0ac237062e7987e0 (wasm://wasm/033f8df2:wasm-function[9988]:0x9cdb73)
    at std::panicking::rust_panic_with_hook::h3aa054d35a0817d7 (wasm://wasm/033f8df2:wasm-function[6557]:0x8cdb63)
    at core::panicking::panic_fmt::h3e1dd3d08288569e (wasm://wasm/033f8df2:wasm-function[9785]:0x9c88da)
    at core::ops::function::Fn::call::h3af7d6d7e5bfc22d (wasm://wasm/033f8df2:wasm-function[6740]:0x8d8400)
    at wgpu::backend::direct::ErrorSinkRaw::handle_error::h840aa012e740d34e (wasm://wasm/033f8df2:wasm-function[5409]:0x86992b)
    at wgpu::backend::direct::Context::handle_error::hf89728d9c5f71438 (wasm://wasm/033f8df2:wasm-function[2762]:0x686daa)
    at <T as wgpu::context::DynContext>::command_encoder_copy_texture_to_texture::hde60f1b879c660ca (wasm://wasm/033f8df2:wasm-function[9264]:0x9a6974)
    at wgpu::CommandEncoder::copy_texture_to_texture::hbd9a9179a9bfa7bc (wasm://wasm/033f8df2:wasm-function[8727]:0x9856f3)
    at <ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::apply_filter::h2e53dd6ff3829c25 (wasm://wasm/033f8df2:wasm-function[2122]:0x5d282a)
```
AVM2 stack:
```
    at flash.display::BitmapData/flash::display::BitmapData::applyFilter()
    at game.display.render::WaterRenderer/renderWater()
    at game.display.render::WaterRenderer/render()
    at engine::Screen/update()
    at engine.level::Level/update()
    at engine.level::GameLevel/update()
    at Main/update()
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA GeForce RTX 3060 (0x00002504) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 700, height: 525, depth_or_array_layers: 1 }

# Page Info
Page URL: https://www.miniplay.com/helpers/game/sandbox.php?mp_assets=https%3A%2F%2Fs2.minijuegosgratis.com%2F&mp_embed=0&mp_game_id=24909&mp_game_uid=feed-me-moar&mp_game_url=https%3A%2F%2Fwww.miniplay.com%2Fembed%2Ffeed-me-moar&mp_int=1&mp_locale=en_US&mp_player_type=FLASH&mp_player_url=aHR0cHM6Ly93d3cubWluaWp1ZWdvc2dyYXRpcy5jb20vZmxhc2gxMjM0L25vX2hvdGxpbmsvZmVlZG1lbW9hci5zd2Y%3D&mp_site_https_url=https%3A%2F%2Fwww.miniplay.com%2F&mp_site_name=miniplay.com&mp_site_url=https%3A%2F%2Fwww.miniplay.com%2F&mp_timezone=Asia%2FBaghdad&mp_view_type=
SWF URL: https://www.minijuegosgratis.com/flash1234/no_hotlink/feedmemoar.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-11-14
Channel: nightly
Built: 2023-11-14T00:21:56.078Z
Commit: b196c8d1bcc2d691c61d8d78b17b5fd60e0234b8
Is extension: false

# Metadata
width: 700
height: 525
frameRate: 30
numFrames: 2
swfVersion: 11
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 7395482

**Comment by n0samu** [comment]
The problem occurs in the first level after you click the character and let the water flow for a little bit:

https://github.com/user-attachments/assets/1b6948ab-5cca-4742-be53-5fdebeabc831

**Comment by torokati44** [comment]
This looks suspiciously like a small negative number (-2 or -3) got bitcasted to an `u32` somewhere. Maybe it should have been clamped or something like that...
