### ISSUE TITLE
Error on https://gaw.ncardenascota.repl.co/player

### ISSUE THREAD

**Issue by c4artisan** [ruffle-rs/ruffle#14046]
# Error Info
Error name: Error
Error message: panicked at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys/wasm/../unsupported/locks/mutex.rs:20:9:
assertion `left == right` failed: cannot recursively acquire mutex
  left: true
 right: false
Error stack:
```
Error: panicked at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys/wasm/../unsupported/locks/mutex.rs:20:9:
assertion `left == right` failed: cannot recursively acquire mutex
  left: true
 right: false
    at imports.wbg.__wbg_new_ab87fd305ed9004b (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:2624:21)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h0ac237062e7987e0 (wasm://wasm/033f8df2:wasm-function[9988]:0x9cdb73)
    at std::panicking::rust_panic_with_hook::h3aa054d35a0817d7 (wasm://wasm/033f8df2:wasm-function[6557]:0x8cdb63)
    at core::panicking::panic_fmt::h3e1dd3d08288569e (wasm://wasm/033f8df2:wasm-function[9785]:0x9c88da)
    at core::panicking::assert_failed_inner::hef8aa9140ed3b15c (wasm://wasm/033f8df2:wasm-function[4685]:0x7e7119)
    at core::panicking::assert_failed::h0d5b2756b57047ad (wasm://wasm/033f8df2:wasm-function[9806]:0x9c9afb)
    at ruffle_core::loader::Loader::load_url_loader::{{closure}}::hb14fd745d3300ba0 (wasm://wasm/033f8df2:wasm-function[2366]:0x61763f)
    at <ruffle_web::navigator::WebNavigatorBackend as ruffle_core::backend::navigator::NavigatorBackend>::spawn_future::{{closure}}::hf51673417c841668 (wasm://wasm/033f8df2:wasm-function[1274]:0x423039)
    at wasm_bindgen_futures::queue::Queue::new::{{closure}}::hfeb89abaa6791602 (wasm://wasm/033f8df2:wasm-function[4427]:0x7c5fc0)
    at wasm_bindgen::convert::closures::invoke1_mut::hecf1ccd8fc8595a0 (wasm://wasm/033f8df2:wasm-function[10769]:0x9ea34d)
```
AVM2 stack:
```
    at flash.external::ExternalInterface/flash::external::ExternalInterface::addCallback()
    at anifire.player.components::PreviewPlayer/initAPI()
    at anifire.player.components::PreviewPlayer/onCreationCompleted()
    at anifire.player.components::PreviewPlayer/___PreviewPlayer_Group1_creationComplete()
    at flash.events::EventDispatcher/flash::events::EventDispatcher::dispatchEvent()
    at mx.core::UIComponent/dispatchEvent()
    at mx.core::UIComponent/set initialized()
    at mx.managers::LayoutManager/doPhasedInstantiation()
    at mx.managers::LayoutManager/doPhasedInstantiationCallback()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA GeForce RTX 3050 (0x00002507) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }
Player type: Object
SWF URL: https://c4artisan.github.io/fireload/animation/414827163ad4eb60/player.swf
Param flashvars: apiserver=%2F&storePath=https%3A%2F%2Fc4artisan.github.io%2Ffireload%2Fstore%2F3a981f5cb2739137%2F%3Cstore%3E&ut=60&autostart=1&isWide=1&clientThemePath=https%3A%2F%2Fc4artisan.github.io%2Ffireload%2Fstatic%2Fad44370a650793d9%2F%3Cclient_theme%3E&movieId=m-672
Param allowScriptAccess: always
Param allowFullScreen: true
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://gaw.ncardenascota.repl.co/player?movieId=m-672
SWF URL: https://c4artisan.github.io/fireload/animation/414827163ad4eb60/player.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-11-14
Channel: nightly
Built: 2023-11-14T00:21:56.078Z
Commit: b196c8d1bcc2d691c61d8d78b17b5fd60e0234b8
Is extension: true

# Metadata
width: 500
height: 375
frameRate: 24
numFrames: 2
swfVersion: 14
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 1816359

**Comment by c4artisan** [comment]
to replicate, https://gaw.ncardenascota.repl.co/player?movieId=m-672
