### ISSUE TITLE
Error on https://fourthskys.net/

### ISSUE THREAD

**Issue by wildmaster84** [ruffle-rs/ruffle#14055]
# Error Info
Error name: Error
Error message: panicked at core/src/library.rs:331:26:
called `Option::unwrap()` on a `None` value
Error stack:
```
Error: panicked at core/src/library.rs:331:26:
called `Option::unwrap()` on a `None` value
    at H.n.wbg.__wbg_new_ab87fd305ed9004b (https://fourthskys.net/assets/scripts/lib/ruffle/core.ruffle.5dcaa225af3bc049878c.js:1:56255)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h0ac237062e7987e0 (wasm://wasm/033f8df2:wasm-function[9988]:0x9cdb73)
    at std::panicking::rust_panic_with_hook::h3aa054d35a0817d7 (wasm://wasm/033f8df2:wasm-function[6557]:0x8cdb63)
    at core::panicking::panic_fmt::h3e1dd3d08288569e (wasm://wasm/033f8df2:wasm-function[9785]:0x9c88ac)
    at core::panicking::panic::h0f0c05b20da93dd7 (wasm://wasm/033f8df2:wasm-function[9448]:0x9ba4e6)
    at ruffle_core::display_object::movie_clip::MovieClip::handle_bytecode_tag::hf86fc4360652d98b (wasm://wasm/033f8df2:wasm-function[621]:0x146ccb)
    at ruffle_core::display_object::movie_clip::MovieClip::run_frame_internal::hf819389406197367 (wasm://wasm/033f8df2:wasm-function[778]:0x27fbf4)
    at <ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::run_frame_avm1::h67a24e91b5c95e5a (wasm://wasm/033f8df2:wasm-function[5675]:0x87fecf)
    at ruffle_web::Ruffle::tick::ha7d0e3b1f0c59fe9 (wasm://wasm/033f8df2:wasm-function[853]:0x2dcb71)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::hb24ce84c4bc5b881 (wasm://wasm/033f8df2:wasm-function[12152]:0xa1c8e9)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA GeForce GTX 1650 (0x00002188) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: low
Surface samples: 1
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://fourthskys.net/
SWF URL: https://fourthskys.net/assets/media/games/swf/kernal.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-11-14
Channel: nightly
Built: 2023-11-14T00:21:56.078Z
Commit: b196c8d1bcc2d691c61d8d78b17b5fd60e0234b8
Is extension: false

# Metadata
width: 760
height: 480
frameRate: 24
numFrames: 1
swfVersion: 15
backgroundColor: #666666
isActionScript3: false
uncompressedLength: 322252

**Comment by Lord-McSweeney** [comment]
The site seems to have been taken down a few months ago, and the SWF was not archived on the Wayback Machine.

**Comment by wildmaster84** [comment]
Yes the project was canceled because the community wrapped around the project was.. not very good. the error was caused by something related to as3 which was still early in testing so this is most like fixed by now.
