### ISSUE TITLE
Error on https://game179258.konggames.com/games/randomnine/cardinal-quest-2/frame/50203974-0b2f-46ab-aa11-7f68ce07dbcf/

### ISSUE THREAD

**Issue by KyleChongHengKai** [ruffle-rs/ruffle#14068]
# Error Info
Error name: Error
Error message: panicked at render/naga-pixelbender/src/lib.rs:1241:29:
Unimplemented opcode Step
Error stack:
```
Error: panicked at render/naga-pixelbender/src/lib.rs:1241:29:
Unimplemented opcode Step
    at H.n.wbg.__wbg_new_ab87fd305ed9004b (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.9319559a195fae019006.js:1:56255)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hb1c47d692dbcedf6 (wasm://wasm/0336f48a:wasm-function[9803]:0x9b0c0a)
    at std::panicking::rust_panic_with_hook::hc20eadded6bfe687 (wasm://wasm/0336f48a:wasm-function[6278]:0x89aea5)
    at core::panicking::panic_fmt::h7a368385936888dc (wasm://wasm/0336f48a:wasm-function[9603]:0x9aba14)
    at <ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::compile_pixelbender_shader::h9ef81f25215a56a4 (wasm://wasm/0336f48a:wasm-function[7928]:0x920856)
    at ruffle_core::avm2::globals::flash::display::shader_data::init::hf8d7d968a64019e5 (wasm://wasm/0336f48a:wasm-function[996]:0x377bda)
    at ruffle_core::avm2::function::Executable::exec::h031e8aa5585ebf44 (wasm://wasm/0336f48a:wasm-function[871]:0x2ffc95)
    at ruffle_core::avm2::object::TObject::call_property::h1a856e8c3ef51de1 (wasm://wasm/0336f48a:wasm-function[1263]:0x41e36d)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::h54f2da80b95b334b (wasm://wasm/0336f48a:wasm-function[2810]:0x67e9eb)
    at ruffle_core::avm2::activation::Activation::run_actions::h2dcd308c4e56efcb (wasm://wasm/0336f48a:wasm-function[568]:0x3f842)
```
AVM2 stack:
```
    at flash.display::ShaderData/flash::display::ShaderData::init()
    at flash.display::ShaderData()
    at flash.display::Shader/set byteCode()
    at flash.display::Shader()
    at flixelcq.tile::FlxCqTilemap()
    at cq::CqLevel()
    at cq::CqWorld/executeGoToLevel()
    at cq.states::GameState/continueInitialisation()
    at cq.states::GameState/update()
    at flixel::FlxState/tryUpdate()
    at flixel::FlxGame/update()
    at cq::Main/update()
    at flixel::FlxGame/step()
    at flixel::FlxGame/onEnterFrame()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) UHD Graphics (0x00004E71) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://game179258.konggames.com/games/randomnine/cardinal-quest-2/frame/50203974-0b2f-46ab-aa11-7f68ce07dbcf/?kongregate_host=www.kongregate.com
SWF URL: https://game179258.konggames.com/gamez/0017/9258/live/cq2.swf?kongregate_game_version=1465851167

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
Platform: Win32
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-11-17
Channel: nightly
Built: 2023-11-17T00:14:46.670Z
Commit: a78a67ee24a4a172e6fae0ce03979e63864270c6
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 30
numFrames: 2
swfVersion: 15
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 20519535

**Comment by adrian17** [comment]
This now works and renders correctly (unfortunately it's slow...)

**Comment by kjarosh** [comment]
It works pretty well performance-wise for me on desktop, runs poorly on web though
