### ISSUE TITLE
Error on https://flashthemes.net/movie/7lBty38MRmG

### ISSUE THREAD

**Issue by Kidzohair1000** [ruffle-rs/ruffle#14072]
# Error Info
Error name: Error
Error message: panicked at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys/wasm/../unsupported/locks/mutex.rs:20:9:
assertion `left == right` failed: cannot recursively acquire mutex
  left: true
 right: false
Error stack:
```
Error: panicked at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys/wasm/../unsupported/locks/mutex.rs:20:9:
assertion `left == right` failed: cannot recursively acquire mutex
  left: true
 right: false
    at imports.wbg.__wbg_new_ab87fd305ed9004b (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:2624:21)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h0ac237062e7987e0 (wasm://wasm/033f8df2:wasm-function[9988]:0x9cdb73)
    at std::panicking::rust_panic_with_hook::h3aa054d35a0817d7 (wasm://wasm/033f8df2:wasm-function[6557]:0x8cdb63)
    at core::panicking::panic_fmt::h3e1dd3d08288569e (wasm://wasm/033f8df2:wasm-function[9785]:0x9c88da)
    at core::panicking::assert_failed_inner::hef8aa9140ed3b15c (wasm://wasm/033f8df2:wasm-function[4685]:0x7e7119)
    at core::panicking::assert_failed::h0d5b2756b57047ad (wasm://wasm/033f8df2:wasm-function[9806]:0x9c9afb)
    at ruffle_core::loader::Loader::load_url_loader::{{closure}}::hb14fd745d3300ba0 (wasm://wasm/033f8df2:wasm-function[2366]:0x61763f)
    at <ruffle_web::navigator::WebNavigatorBackend as ruffle_core::backend::navigator::NavigatorBackend>::spawn_future::{{closure}}::hf51673417c841668 (wasm://wasm/033f8df2:wasm-function[1274]:0x423039)
    at wasm_bindgen_futures::queue::Queue::new::{{closure}}::hfeb89abaa6791602 (wasm://wasm/033f8df2:wasm-function[4427]:0x7c5fc0)
    at wasm_bindgen::convert::closures::invoke1_mut::hecf1ccd8fc8595a0 (wasm://wasm/033f8df2:wasm-function[10769]:0x9ea34d)
```
AVM2 stack:
```
    at flash.external::ExternalInterface/flash::external::ExternalInterface::addCallback()
    at anifire.player.components::PreviewPlayer/initAPI()
    at anifire.player.components::PreviewPlayer/onCreationCompleted()
    at anifire.player.components::PreviewPlayer/___PreviewPlayer_Group1_creationComplete()
    at flash.events::EventDispatcher/flash::events::EventDispatcher::dispatchEvent()
    at mx.core::UIComponent/dispatchEvent()
    at mx.core::UIComponent/set initialized()
    at mx.managers::LayoutManager/doPhasedInstantiation()
    at mx.managers::LayoutManager/doPhasedInstantiationCallback()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) Iris(R) Xe Graphics (0x00009A49) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: low
Surface samples: 1
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }
Player type: Object
SWF URL: https://flashthemes.net/static/animationnew/414827163ad4eb60/player.swf
Param bgcolor: #000000
Param scale: exactfit
Param quality: low
Param allowScriptAccess: always
Param allowFullScreen: true
Param wmode: transparent
Param flashvars: movieOwner=&movieOwnerId=930&movieId=7lBty38MRmG&movieLid=6&pwm=0&movieDesc=View-Monster%2520https%253A%252F%252Fflashthemes.net%252Fshop%252Fitem%252F21705145316606&userId=930&username=&uemail=&ut=-1&numContact=&apiserver=https%3A%2F%2Fflashthemes.net%2F&duration=53&playcount=1&thumbnailURL=%2Fmovie_thumbs%2Fthumb-7lBty38MRmG.png&copyable=0&isPublished=1&ctc=go&tlang=en_US&is_private_shared=0&autostart=0&isInitFromExternal=0&isWide=1&appCode=go&is_slideshow=0&is_emessage=0&storePath=%2Fstatic%2Fstore%2F%3Cstore%3E%3Fv%3D930&clientThemePath=%2Fstatic%2Fct%2Fad44370a650793d9%2F%3Cclient_theme%3E&animationPath=&isEmbed=1&&&&isTemplate=0&showButtons=1&chain_mids=&averageRating=0&ratingCount=2&endStyle=0&showshare=false
Param movie: https://flashthemes.net/static/animationnew/414827163ad4eb60/player.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://flashthemes.net/movie/7lBty38MRmG
SWF URL: https://flashthemes.net/static/animationnew/414827163ad4eb60/player.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
Platform: Win32
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-11-16
Channel: nightly
Built: 2023-11-16T00:14:37.965Z
Commit: ffdb248872c89b586a83aaefc5cca3c98b8e5e8c
Is extension: true

# Metadata
width: 500
height: 375
frameRate: 24
numFrames: 2
swfVersion: 14
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 1799596

**Comment by n0samu** [comment]
Closing in favor of #13974
