### ISSUE TITLE
Error message: Failed to fetch: https://www.mnindustries.store/355-2/mecha-arena-1409705b0.swf

### ISSUE THREAD

**Issue by TheUndercoverPerson** [ruffle-rs/ruffle#14095]
### Describe the bug

So I am coding a game website and I am trying to load an SWF file without the URL because in the github project that I made sometimes the SWF file did not load and just said something went wrong. Now that I have done this it wont load either. With the last method I used I get the same error as this time but with a different URL here is the error message please help:

# Error Info
Error name: Error
Error message: Failed to fetch: https://www.mnindustries.store/355-2/mecha-arena-1409705b0.swf
Error stack:
```
Error: Failed to fetch: https://www.mnindustries.store/355-2/mecha-arena-1409705b0.swf
    at dt.displayRootMovieDownloadFailedMessage (https://unpkg.com/@ruffle-rs/ruffle:2:374321)
    at H.n.wbg.__wbg_displayRootMovieDownloadFailedMessage_ed4ad3ae9522c8a3 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.f8d86a1fb855b0d2aaff.js:1:7518)
    at <ruffle_web::ui::WebUiBackend as ruffle_core::backend::ui::UiBackend>::display_root_movie_download_failed_message::h7b2295bf8f69f4fd (wasm://wasm/0336fd8e:wasm-function[11960]:0x9ff3c1)
    at ruffle_core::loader::Loader::root_movie_loader::{{closure}}::h9afb9d9fb53076b3 (wasm://wasm/0336fd8e:wasm-function[957]:0x3564c7)
    at <ruffle_web::navigator::WebNavigatorBackend as ruffle_core::backend::navigator::NavigatorBackend>::spawn_future::{{closure}}::hcbc3f1dbde5b2b5c (wasm://wasm/0336fd8e:wasm-function[1242]:0x4144e0)
    at wasm_bindgen_futures::queue::Queue::new::{{closure}}::hc37e26db6daee956 (wasm://wasm/0336fd8e:wasm-function[3547]:0x734379)
    at wasm_bindgen::convert::closures::invoke1_mut::h2c7feb67e27e88e8 (wasm://wasm/0336fd8e:wasm-function[10525]:0x9cc443)
    at closure4422 externref shim (wasm://wasm/0336fd8e:wasm-function[10867]:0x9d8b4a)
    at E (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.f8d86a1fb855b0d2aaff.js:1:3204)
    at c (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.f8d86a1fb855b0d2aaff.js:1:2503)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) Iris(R) Xe Graphics (0x000046A8) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://www.mnindustries.store/355-2/
SWF URL: https://www.mnindustries.store/355-2/mecha-arena-1409705b0.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0
Platform: Win32
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-11-20
Channel: nightly
Built: 2023-11-20T00:14:33.063Z
Commit: 23a65c50f22195f916dc4c19453c04a915962f89
Is extension: false

### Expected behavior

I expected it to play the game

### Content Location

[https://github.com/TheUndercoverPerson/Premium-Games/blob/main/mecha-arena-1409705b0.swf]

### Affected platform

Self-hosted version

### Operating system

Windows 11

### Browser

Google chrome

**Comment by Lord-McSweeney** [comment]
You did not properly upload the SWF; if you navigate to https://www.mnindustries.store/355-2/mecha-arena-1409705b0.swf it returns a 404.
