### ISSUE TITLE
Error on https://flashthemes.net/movie/39khlRH

### ISSUE THREAD

**Issue by SonnyGithub2022** [ruffle-rs/ruffle#14107]
# Error Info
Error name: Error
Error message: panicked at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys/wasm/../unsupported/locks/mutex.rs:20:9:
assertion `left == right` failed: cannot recursively acquire mutex
  left: true
 right: false
Error stack:
```
Error: panicked at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys/wasm/../unsupported/locks/mutex.rs:20:9:
assertion `left == right` failed: cannot recursively acquire mutex
  left: true
 right: false
    at imports.wbg.__wbg_new_ab87fd305ed9004b (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:2624:21)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h878d7563074f0d48 (wasm://wasm/03372a32:wasm-function[9786]:0x9b279d)
    at std::panicking::rust_panic_with_hook::hc20eadded6bfe687 (wasm://wasm/03372a32:wasm-function[6287]:0x8a3733)
    at core::panicking::panic_fmt::h7a368385936888dc (wasm://wasm/03372a32:wasm-function[9593]:0x9ad711)
    at core::panicking::assert_failed_inner::h8608b548c883ea8f (wasm://wasm/03372a32:wasm-function[4283]:0x7a96f4)
    at core::panicking::assert_failed::h17b5d38068ec0858 (wasm://wasm/03372a32:wasm-function[9615]:0x9ae976)
    at ruffle_core::loader::Loader::load_url_loader::{{closure}}::h18896b9812ab490b (wasm://wasm/03372a32:wasm-function[2302]:0x5fdd4d)
    at <ruffle_web::navigator::WebNavigatorBackend as ruffle_core::backend::navigator::NavigatorBackend>::spawn_future::{{closure}}::h9df0fa2fb880cf27 (wasm://wasm/03372a32:wasm-function[1242]:0x41acfb)
    at wasm_bindgen_futures::queue::Queue::new::{{closure}}::hc37e26db6daee956 (wasm://wasm/03372a32:wasm-function[3562]:0x73a67d)
    at wasm_bindgen::convert::closures::invoke1_mut::h2c7feb67e27e88e8 (wasm://wasm/03372a32:wasm-function[10515]:0x9cdf1a)
```
AVM2 stack:
```
    at flash.external::ExternalInterface/flash::external::ExternalInterface::addCallback()
    at anifire.player.components::PreviewPlayer/initAPI()
    at anifire.player.components::PreviewPlayer/onCreationCompleted()
    at anifire.player.components::PreviewPlayer/___PreviewPlayer_Group1_creationComplete()
    at flash.events::EventDispatcher/flash::events::EventDispatcher::dispatchEvent()
    at mx.core::UIComponent/dispatchEvent()
    at mx.core::UIComponent/set initialized()
    at mx.managers::LayoutManager/doPhasedInstantiation()
    at mx.managers::LayoutManager/doPhasedInstantiationCallback()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (AMD, AMD Radeon(TM) Graphics (0x000015D8) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: low
Surface samples: 1
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }
Player type: Object
SWF URL: https://flashthemes.net/static/animationnew/414827163ad4eb60/player.swf
Param bgcolor: #000000
Param scale: exactfit
Param quality: low
Param allowScriptAccess: always
Param allowFullScreen: true
Param wmode: transparent
Param flashvars: movieOwner=&movieOwnerId=580&movieId=39khlRH&movieLid=6&pwm=0&movieDesc=Like%252C%2520comment%252C%2520and%2520follow%2520for%2520more%2520videos%2520%253A)&userId=580&username=&uemail=&ut=-1&numContact=&apiserver=https%3A%2F%2Fflashthemes.net%2F&duration=53&playcount=1&thumbnailURL=%2Fmovie_thumbs%2Fthumb-39khlRH.png&copyable=0&isPublished=1&ctc=go&tlang=en_US&is_private_shared=0&autostart=0&isInitFromExternal=0&isWide=1&appCode=go&is_slideshow=0&is_emessage=0&storePath=%2Fstatic%2Fstore%2F%3Cstore%3E%3Fv%3D580&clientThemePath=%2Fstatic%2Fct%2Fad44370a650793d9%2F%3Cclient_theme%3E&animationPath=&isEmbed=1&&&&isTemplate=0&showButtons=1&chain_mids=&averageRating=0&ratingCount=2&endStyle=0&showshare=false
Param movie: https://flashthemes.net/static/animationnew/414827163ad4eb60/player.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://flashthemes.net/movie/39khlRH
SWF URL: https://flashthemes.net/static/animationnew/414827163ad4eb60/player.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-11-22
Channel: nightly
Built: 2023-11-22T00:14:54.210Z
Commit: 16567cfa970736d0d3f69d975cbd8f9f00b61b26
Is extension: true

# Metadata
width: 500
height: 375
frameRate: 24
numFrames: 2
swfVersion: 14
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 1799596

**Comment by n0samu** [comment]
Closing in favor of #13974
