### ISSUE TITLE
Error on https://ruffle.rs/demo/

### ISSUE THREAD

**Issue by rclaretianafm105** [ruffle-rs/ruffle#14137]
# Error Info
Error name: Error
Error message: panicked at library/alloc/src/raw_vec.rs:534:5:
capacity overflow
Error stack:
```
Error: panicked at library/alloc/src/raw_vec.rs:534:5:
capacity overflow
    at V.n.wbg.__wbg_new_ab87fd305ed9004b (https://ruffle.rs/demo/339.index.js:1:56224)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h6ed365ff1edf313d (wasm://wasm/0336ea96:wasm-function[9806]:0x9b0a09)
    at std::panicking::rust_panic_with_hook::hc20eadded6bfe687 (wasm://wasm/0336ea96:wasm-function[6288]:0x8a13eb)
    at core::panicking::panic_fmt::h7a368385936888dc (wasm://wasm/0336ea96:wasm-function[9613]:0x9ab94e)
    at alloc::raw_vec::capacity_overflow::h847a682b42dd684f (wasm://wasm/0336ea96:wasm-function[9612]:0x9ab854)
    at swf::read::decompress_swf::h9e3f1cf860f093d4 (wasm://wasm/0336ea96:wasm-function[868]:0x2fbce2)
    at ruffle_core::tag_utils::SwfMovie::from_data::hc5634e9938bf2374 (wasm://wasm/0336ea96:wasm-function[3875]:0x7608ed)
    at ruffle_load_data externref shim (wasm://wasm/0336ea96:wasm-function[10361]:0x9c9d99)
    at W.load_data (https://ruffle.rs/demo/339.index.js:1:4607)
    at kt.load (https://ruffle.rs/demo/index.js:2:299283)
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Google, Vulkan 1.3.0 (SwiftShader Device (Subzero) (0x0000C0DE)), SwiftShader driver)"
Adapter Device Type: Cpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 8192, max_texture_dimension_2d: 8192, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://ruffle.rs/demo/

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-11-24
Channel: nightly
Built: 2023-11-24T00:14:22.393Z
Commit: 96059a8e25603ba9dddaf7d178191e9304a11045
Is extension: false

# Metadata

**Comment by Lord-McSweeney** [comment]
Closing as likely invalid SWF (bad encoding)
