### ISSUE TITLE
Fatal Error upon fresh Windows 10 64-bit download from Latest Nightly 2023-12-01 build

### ISSUE THREAD

**Issue by ShahAKahn** [ruffle-rs/ruffle#14267]
### Describe what you were doing

I downloaded the .zip file from the 'Latest Nightly Release' part of the Downloads section of Ruffle.rs website and the program keeps crashing **with or without loading** a .swf or any flash file into it. Yes , it happens immediately upon opening Ruffle just like n0samu asked on issue/ticket #13021 from Jacianto (whom never bothered to reply >.>)

P.S : I am writing this as the program automatically directly led me to this page so I wanted to write a report as this was so straightforward . Take your time to resolve this . No hurry , no worry :3 

### What does the crash message say?

panicked at C:\Users\runneradmin\.cargo\git\checkouts\wgpu-53e70f8674b08dd4\fb4f9c5\wgpu\src\backend\direct.rs:3056:5:
wgpu error: Validation Error

Caused by:
    In Queue::write_buffer_with
    Parent device is lost

panicked at C:\Users\runneradmin\.cargo\git\checkouts\wgpu-53e70f8674b08dd4\fb4f9c5\wgpu\src\backend\direct.rs:3056:5:
wgpu error: Out of Memory ( when I tried to run it using 'Run as Administrator' )

### Ruffle Version

0.1.0-nightly (656d41f022dbf4e54921b89882451eba625b98bd 2023-11-30)

### Affected platform

Desktop app

### Operating system

Windows 10.0.17134 (Windows 10 Pro) [64-bit]

**Comment by n0samu** [comment]
Hi, what video card do you have?

**Comment by ShahAKahn** [comment]
Integrated Graphics 4400 . _Ancient_ . I know :/

**Comment by n0samu** [comment]
Yes, that would be the reason. You can try using the [Ruffle Web Demo](https://ruffle.rs/demo/) instead.

**Comment by torokati44** [comment]
You could also try switching graphics backends by adding the `-g dx11` command line arguments.

**Comment by n0samu** [comment]
No, Ruffle does not support DX11

**Comment by torokati44** [comment]
Oooh, sorry, I'm not up to date on our Windows situation. There is still `vk` and `dx12` to try. And hopefully soon (#13732) `gl` too.
Until then, another thing you can try is making sure you have the latest graphics drivers for that GPU.

**Comment by n0samu** [comment]
Honestly such an old card is hopeless, web demo might be ok but will definitely be slow. I suggest just [downloading the Flash projector](https://web.archive.org/web/20220401020702/https://www.adobe.com/support/flashplayer/debug_downloads.html)

**Comment by ShahAKahn** [comment]
Excellent. Both options worked as-is. Could you either sticky this thread or add a short note about this on Ruffle website (or anywhere you see fit) please? It would help people to know workarounds. Thank you :))

**Comment by torokati44** [comment]
> Both options worked as-is.

I'm glad! But exactly which options do you mean? 😅

**Comment by n0samu** [comment]
They meant the Ruffle Web Demo and the Flash projector
