### ISSUE TITLE
Error on https://flashthemes.net/movie/5EK9uvJ

### ISSUE THREAD

**Issue by MrButton5** [ruffle-rs/ruffle#14304]
# Error Info
Error name: Error
Error message: panicked at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys/wasm/../unsupported/locks/mutex.rs:20:9:
assertion `left == right` failed: cannot recursively acquire mutex
  left: true
 right: false
Error stack:
```
Error: panicked at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys/wasm/../unsupported/locks/mutex.rs:20:9:
assertion `left == right` failed: cannot recursively acquire mutex
  left: true
 right: false
    at imports.wbg.__wbg_new_ab87fd305ed9004b (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:2624:21)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h56e6782497447280 (wasm://wasm/03397206:wasm-function[9812]:0x9ba2d4)
    at std::panicking::rust_panic_with_hook::hc20eadded6bfe687 (wasm://wasm/03397206:wasm-function[6300]:0x8ac218)
    at core::panicking::panic_fmt::h7a368385936888dc (wasm://wasm/03397206:wasm-function[9617]:0x9b51f0)
    at core::panicking::assert_failed_inner::h8608b548c883ea8f (wasm://wasm/03397206:wasm-function[4294]:0x7b0f2d)
    at core::panicking::assert_failed::h8c38c887d8c698c9 (wasm://wasm/03397206:wasm-function[9640]:0x9b6474)
    at ruffle_core::loader::Loader::load_url_loader::{{closure}}::hf70f6498852f7fdc (wasm://wasm/03397206:wasm-function[2351]:0x60f305)
    at <ruffle_web::navigator::WebNavigatorBackend as ruffle_core::backend::navigator::NavigatorBackend>::spawn_future::{{closure}}::h49375eef9b84824e (wasm://wasm/03397206:wasm-function[1243]:0x418b8b)
    at wasm_bindgen_futures::queue::Queue::new::{{closure}}::hd19f0ab82415c764 (wasm://wasm/03397206:wasm-function[3565]:0x744234)
    at wasm_bindgen::convert::closures::invoke1_mut::h120c8d16e52dfda9 (wasm://wasm/03397206:wasm-function[10538]:0x9d5a1a)
```
AVM2 stack:
```
    at flash.external::ExternalInterface/flash::external::ExternalInterface::addCallback()
    at anifire.player.components::PreviewPlayer/initAPI()
    at anifire.player.components::PreviewPlayer/onCreationCompleted()
    at anifire.player.components::PreviewPlayer/___PreviewPlayer_Group1_creationComplete()
    at flash.events::EventDispatcher/flash::events::EventDispatcher::dispatchEvent()
    at mx.core::UIComponent/dispatchEvent()
    at mx.core::UIComponent/set initialized()
    at mx.managers::LayoutManager/doPhasedInstantiation()
    at mx.managers::LayoutManager/doPhasedInstantiationCallback()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) HD Graphics 610 (0x00005902) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: low
Surface samples: 1
Surface size: Extent3d { width: 560, height: 315, depth_or_array_layers: 1 }
Player type: Object
SWF URL: https://flashthemes.net/static/animationnew/414827163ad4eb60/player.swf
Param bgcolor: #000000
Param scale: exactfit
Param quality: low
Param allowScriptAccess: always
Param allowFullScreen: true
Param wmode: transparent
Param flashvars: movieOwner=&movieOwnerId=2687&movieId=5EK9uvJ&movieLid=6&pwm=0&movieDesc=&userId=2687&username=&uemail=&ut=-1&numContact=&apiserver=https%3A%2F%2Fflashthemes.net%2F&duration=53&playcount=1&thumbnailURL=%2Fmovie_thumbs%2Fthumb-5EK9uvJ.png&copyable=0&isPublished=1&ctc=go&tlang=en_US&is_private_shared=0&autostart=0&isInitFromExternal=0&isWide=1&appCode=go&is_slideshow=0&is_emessage=0&storePath=%2Fstatic%2Fstore%2F%3Cstore%3E%3Fv%3D2687&clientThemePath=%2Fstatic%2Fct%2Fad44370a650793d9%2F%3Cclient_theme%3E&animationPath=&isEmbed=1&&&&isTemplate=0&showButtons=1&chain_mids=&averageRating=0&ratingCount=2&endStyle=0&showshare=false
Param movie: https://flashthemes.net/static/animationnew/414827163ad4eb60/player.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://flashthemes.net/movie/5EK9uvJ
SWF URL: https://flashthemes.net/static/animationnew/414827163ad4eb60/player.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-12-03
Channel: nightly
Built: 2023-12-03T00:15:50.278Z
Commit: 947785607955e8b2a39d5dbb7cb98f0d37f38eb2
Is extension: true

# Metadata
width: 500
height: 375
frameRate: 24
numFrames: 2
swfVersion: 14
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 1799596

**Comment by n0samu** [comment]
Closing in favor of #13974
