### ISSUE TITLE
Error on Busman Parking 3D

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#14317]
Games asks to get in fullscreen mode. If you press yes, this happens

# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/fb4f9c5/wgpu-core/src/resource.rs:207:13:
Map callback was leaked
Error stack:
```
Error: panicked at /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/fb4f9c5/wgpu-core/src/resource.rs:207:13:
Map callback was leaked
    at H.n.wbg.__wbg_new_ab87fd305ed9004b (https://www.spiele-umsonst.de/ruffle/core.ruffle.c315785ec851d1863ad5.js:1:56255)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h56e6782497447280 (wasm://wasm/03397206:wasm-function[9812]:0x9ba2d4)
    at std::panicking::rust_panic_with_hook::hc20eadded6bfe687 (wasm://wasm/03397206:wasm-function[6300]:0x8ac218)
    at core::panicking::panic_fmt::h7a368385936888dc (wasm://wasm/03397206:wasm-function[9617]:0x9b51bd)
    at <wgpu_core::resource::BufferMapCallback as core::ops::drop::Drop>::drop::h4657c882822a2a15 (wasm://wasm/03397206:wasm-function[8960]:0x97237d)
    at <T as wgpu::context::DynContext>::surface_configure::h28e5cf32d0842281 (wasm://wasm/03397206:wasm-function[8123]:0x93b2ad)
    at wgpu::Surface::configure::hf3c22ff9f0572e34 (wasm://wasm/03397206:wasm-function[4163]:0x79bb20)
    at <ruffle_render_wgpu::target::SwapChainTarget as ruffle_render_wgpu::target::RenderTarget>::resize::haa229506bf47cede (wasm://wasm/03397206:wasm-function[10179]:0x9cf22e)
    at <ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::set_viewport_dimensions::ha8caf0f51f136c30 (wasm://wasm/03397206:wasm-function[5118]:0x8438d6)
    at ruffle_core::player::Player::set_viewport_dimensions::h7b1e8310a0a1dfeb (wasm://wasm/03397206:wasm-function[1643]:0x4e7ece)
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA GeForce GTX 1050 Ti (0x00001C82) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://www.spiele-umsonst.de/games/?api&gametype=ruffle&thumburl=https://cdn2.spiele-umsonst.de/flash_thumb/busmanparking3d.jpg&width=700&height=500&title=Busman%20Parking%203D&url=https://www.spiele-umsonst.de/azad/downloads/flashgames/busmanparking3d.swf
SWF URL: https://www.spiele-umsonst.de/azad/downloads/flashgames/busmanparking3d.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-12-03
Channel: nightly
Built: 2023-12-03T00:15:50.278Z
Commit: 947785607955e8b2a39d5dbb7cb98f0d37f38eb2
Is extension: false

# Metadata
width: 700
height: 500
frameRate: 30
numFrames: 2
swfVersion: 17
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 4648320

**Comment by n0samu** [comment]
Fixed by #13732
