### ISSUE TITLE
Error on https://game267424.konggames.com/games/PlasticContainer/youtube-lets-player-simulator-2016/frame/81c00cdf-ba18-4bbd-98e9-8f4e2ff84ce0/

### ISSUE THREAD

**Issue by ZennnShadow** [ruffle-rs/ruffle#14322]
# Error Info
Error name: Error
Error message: panicked at render/naga-pixelbender/src/lib.rs:1241:29:
Unimplemented opcode Step
Error stack:
```
Error: panicked at render/naga-pixelbender/src/lib.rs:1241:29:
Unimplemented opcode Step
    at H.n.wbg.__wbg_new_a64e3f2afc2cf2f8 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.b870c0ea12682a83e69a.js:1:56255)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h1312934804186e57 (wasm://wasm/0339a31e:wasm-function[9818]:0x9bab3b)
    at std::panicking::rust_panic_with_hook::hc20eadded6bfe687 (wasm://wasm/0339a31e:wasm-function[6302]:0x8ac760)
    at core::panicking::panic_fmt::h7a368385936888dc (wasm://wasm/0339a31e:wasm-function[9624]:0x9b5a84)
    at <ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::compile_pixelbender_shader::h6db5bf1731d34ed8 (wasm://wasm/0339a31e:wasm-function[7947]:0x92bd9d)
    at ruffle_core::avm2::globals::flash::display::shader_data::init::h9af3b03d092e4707 (wasm://wasm/0339a31e:wasm-function[764]:0x2612d6)
    at ruffle_core::avm2::function::Executable::exec::ha7f2f4db98f9eadd (wasm://wasm/0339a31e:wasm-function[870]:0x306b03)
    at ruffle_core::avm2::object::TObject::call_property::hf34f505b959b64c6 (wasm://wasm/0339a31e:wasm-function[1317]:0x443e14)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::hc318e778d9b00106 (wasm://wasm/0339a31e:wasm-function[2827]:0x689c40)
    at ruffle_core::avm2::activation::Activation::run_actions::he0a33a17cdb1d680 (wasm://wasm/0339a31e:wasm-function[568]:0x401ce)
```
AVM2 stack:
```
    at flash.display::ShaderData/flash::display::ShaderData::init()
    at flash.display::ShaderData()
    at flash.display::Shader/set byteCode()
    at flash.display::Shader()
    at com.animenight.igs::PosterGenerator$/opEdgeDetect()
    at com.animenight.igs::PosterGenerator$/generatePoster()
    at com.animenight.igs::Games/generateGame()
    at com.animenight.igs::Games/generateGames()
    at com.animenight.igs::Player()
    at Function/MenuScene.as$11:anonymous()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA GeForce RTX 3060 Ti (0x00002489) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://game267424.konggames.com/games/PlasticContainer/youtube-lets-player-simulator-2016/frame/81c00cdf-ba18-4bbd-98e9-8f4e2ff84ce0/?kongregate_host=www.kongregate.com
SWF URL: https://game267424.konggames.com/gamez/0026/7424/live/IGS.swf?kongregate_game_version=1474257956

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-12-05
Channel: nightly
Built: 2023-12-05T00:14:44.474Z
Commit: aa6dc221245015cb7bd8d0f2404f6b63dc6b5cc9
Is extension: false

# Metadata
width: 800
height: 600
frameRate: 30
numFrames: 2
swfVersion: 32
backgroundColor: #FFFFFF
isActionScript3: true
uncompressedLength: 21286544

**Comment by kjarosh** [comment]
That seems to be fully working as of today's version
