### ISSUE TITLE
Error on https://www.spiele-kostenlos-online.de/strategiespiele/zeitmanagement/youda-sushi-chef-2/

### ISSUE THREAD

**Issue by Lukas20069** [ruffle-rs/ruffle#14375]
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/fb4f9c5/wgpu-core/src/resource.rs:207:13:
Map callback was leaked
Error stack:
```
Error: panicked at /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/fb4f9c5/wgpu-core/src/resource.rs:207:13:
Map callback was leaked
    at H.n.wbg.__wbg_new_a64e3f2afc2cf2f8 (https://cdn.spiele-kostenlos-online.de/wp-content/themes/spiele-kostenlos-online/js/ruffle/2023_12_07/core.ruffle.62a8f0c82d1a76601817.js:1:56255)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h2c4885bc68fd7d6d (wasm://wasm/03399e2a:wasm-function[9815]:0x9bac4c)
    at std::panicking::rust_panic_with_hook::hc20eadded6bfe687 (wasm://wasm/03399e2a:wasm-function[6301]:0x8acafe)
    at core::panicking::panic_fmt::h7a368385936888dc (wasm://wasm/03399e2a:wasm-function[9620]:0x9b5b35)
    at <wgpu_core::resource::BufferMapCallback as core::ops::drop::Drop>::drop::h82038e5d317b604b (wasm://wasm/03399e2a:wasm-function[8963]:0x972d15)
    at <T as wgpu::context::DynContext>::surface_configure::h67bbae5107631ff4 (wasm://wasm/03399e2a:wasm-function[8123]:0x93bb23)
    at wgpu::Surface::configure::h75d991822992c10a (wasm://wasm/03399e2a:wasm-function[4165]:0x79c440)
    at <ruffle_render_wgpu::target::SwapChainTarget as ruffle_render_wgpu::target::RenderTarget>::resize::h828dd6d2999d69e5 (wasm://wasm/03399e2a:wasm-function[10180]:0x9cfaa7)
    at <ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::set_viewport_dimensions::h40ca9795fbde52bd (wasm://wasm/03399e2a:wasm-function[5120]:0x84420e)
    at ruffle_core::player::Player::set_viewport_dimensions::hdad28dfaa1fed59b (wasm://wasm/03399e2a:wasm-function[1644]:0x4e9805)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) HD Graphics 620 (0x00005916) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://www.spiele-kostenlos-online.de/strategiespiele/zeitmanagement/youda-sushi-chef-2/
SWF URL: https://cache.spiele-kostenlos-online.de/flashgames/sushi-chef-2.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 OPR/104.0.0.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-12-07
Channel: nightly
Built: 2023-12-07T00:15:04.300Z
Commit: 41ddb316a2b0a91c0d32e8f54eb0f020be42831f
Is extension: false

# Metadata
width: 1024
height: 768
frameRate: 24
numFrames: 1
swfVersion: 23
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 21462055

**Comment by n0samu** [comment]
This should be fixed by #13732
