### ISSUE TITLE
Error on https://game229842.konggames.com/games/Kajenx/blast-magus/frame/ff0357de-943d-4e62-9bc1-23dc6937ce4d/

### ISSUE THREAD

**Issue by yosheeck** [ruffle-rs/ruffle#14417]
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/e16f7b4/wgpu/src/backend/direct.rs:3111:5:
wgpu error: Validation Error

Caused by:
    In Device::create_shader_module
      note: label = `AGAL vertex shader`
    
Shader validation error: 

    Entry point main at Vertex is invalid
    Expression [11] is invalid
    Type resolution failed
    Invalid access into expression [10], indexed: true

Error stack:
```
Error: panicked at /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/e16f7b4/wgpu/src/backend/direct.rs:3111:5:
wgpu error: Validation Error

Caused by:
    In Device::create_shader_module
      note: label = `AGAL vertex shader`
    
Shader validation error: 


    Entry point main at Vertex is invalid
    Expression [11] is invalid
    Type resolution failed
    Invalid access into expression [10], indexed: true


    at H.n.wbg.__wbg_new_a64e3f2afc2cf2f8 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.a3b58c9561ea1b1ac807.js:1:56204)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h853353504563e1d1 (wasm://wasm/0340a3e2:wasm-function[9867]:0x9d1e53)
    at std::panicking::rust_panic_with_hook::hbf46ef0245cc9589 (wasm://wasm/0340a3e2:wasm-function[6312]:0x8bc006)
    at core::panicking::panic_fmt::h14c85a61aa3d538e (wasm://wasm/0340a3e2:wasm-function[9658]:0x9cca9f)
    at core::ops::function::Fn::call::hd4843f9563c537d4 (wasm://wasm/0340a3e2:wasm-function[6575]:0x8d3e54)
    at wgpu::backend::direct::ErrorSinkRaw::handle_error::he5f626f98eb0bfe7 (wasm://wasm/0340a3e2:wasm-function[5371]:0x865c46)
    at wgpu::backend::direct::Context::handle_error::h4190857f8954b5ad (wasm://wasm/0340a3e2:wasm-function[2576]:0x660bf8)
    at <T as wgpu::context::DynContext>::device_create_shader_module::h57854567bea6b17f (wasm://wasm/0340a3e2:wasm-function[8361]:0x95d5be)
    at wgpu::Device::create_shader_module::hcba7350bc87737c1 (wasm://wasm/0340a3e2:wasm-function[6989]:0x8f2271)
    at <ruffle_render_wgpu::context3d::WgpuContext3D as ruffle_render::backend::Context3D>::process_command::h542650a51d7100b5 (wasm://wasm/0340a3e2:wasm-function[587]:0xdf338)
```
AVM2 stack:
```
    at flash.display3D::Context3D/flash::display3D::Context3D::drawTriangles()
    at com.genome2d.context.stage3d.materials::GQuadTextureShaderMaterial3/push()
    at com.genome2d.context::IContext/setCamera()
    at com.genome2d::Genome2D/render()
    at Main/FrameHandler()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (AMD, AMD Radeon(TM) Graphics (0x00001638) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 31, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://game229842.konggames.com/games/Kajenx/blast-magus/frame/ff0357de-943d-4e62-9bc1-23dc6937ce4d/?kongregate_host=www.kongregate.com
SWF URL: https://game229842.konggames.com/gamez/0022/9842/live/secure_BlastMagus.swf?kongregate_game_version=1442378695

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-12-16
Channel: nightly
Built: 2023-12-16T00:14:52.642Z
Commit: f427cd58bb6420bcd28e55526578bcebecb5f67e
Is extension: false

# Metadata
width: 700
height: 475
frameRate: 30
numFrames: 2
swfVersion: 17
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 11098892

**Comment by SuchAFuriousDeath** [comment]
Fixed by #22365, appears playable.
