### ISSUE TITLE
Error on https://cdn.primarygames.com/ruffle_noTouchSupport/run3/

### ISSUE THREAD

**Issue by Tamakingi** [ruffle-rs/ruffle#14423]
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/git/checkouts/wgpu-c26c9ef766f7dc30/c4b8787/wgpu-core/src/resource.rs:207:13:
Map callback was leaked
Error stack:
```
Error: panicked at /home/runner/.cargo/git/checkouts/wgpu-c26c9ef766f7dc30/c4b8787/wgpu-core/src/resource.rs:207:13:
Map callback was leaked
    at V.n.wbg.__wbg_new_d258248ed531ff54 (https://cdn.primarygames.com/js/ruffle/core.ruffle.6e4d2c1da0a3fd6f0339.js:1:51724)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hae20252bd0e594a8 (wasm://wasm/032537fe:wasm-function[9643]:0x97dc8c)
    at std::panicking::rust_panic_with_hook::h3aa054d35a0817d7 (wasm://wasm/032537fe:wasm-function[6308]:0x883a71)
    at core::panicking::panic_fmt::h3e1dd3d08288569e (wasm://wasm/032537fe:wasm-function[9448]:0x978b51)
    at <wgpu_core::resource::BufferMapCallback as core::ops::drop::Drop>::drop::h3caf8b509884ed1c (wasm://wasm/032537fe:wasm-function[8815]:0x942362)
    at <T as wgpu::context::DynContext>::surface_configure::hd1f89251583100d3 (wasm://wasm/032537fe:wasm-function[7982]:0x905a2d)
    at wgpu::Surface::configure::h6f8dbd55d0ea42e5 (wasm://wasm/032537fe:wasm-function[4066]:0x762d74)
    at <ruffle_render_wgpu::target::SwapChainTarget as ruffle_render_wgpu::target::RenderTarget>::resize::had110f32c6c7a9f2 (wasm://wasm/032537fe:wasm-function[10070]:0x9938d3)
    at <ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::set_viewport_dimensions::hb7555c50eaaad5cc (wasm://wasm/032537fe:wasm-function[5026]:0x80ecb2)
    at ruffle_core::player::Player::set_viewport_dimensions::h00e76a1fac74d9ef (wasm://wasm/032537fe:wasm-function[1538]:0x4b6b82)
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Mesa Intel(R) UHD Graphics 600 (GLK 2), OpenGL ES 3.2)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 1352, height: 760, depth_or_array_layers: 1 }

# Page Info
Page URL: https://cdn.primarygames.com/ruffle_noTouchSupport/run3/
SWF URL: https://cdn.primarygames.com/ruffle_noTouchSupport/run3/run3old.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-10-11
Channel: nightly
Built: 2023-10-11T00:22:14.322Z
Commit: 0ef28604b16bb9b27ee9291f527a1827d7713b7b
Is extension: false

# Metadata
width: 800
height: 600
frameRate: 60
numFrames: 1
swfVersion: 15
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 7165547

**Comment by n0samu** [comment]
Fixed by #13732
