### ISSUE TITLE
Error on https://game234473.konggames.com/games/jhall_/beez/frame/3ee3f019-efa1-47bd-87a9-64a7ae62ec72/

### ISSUE THREAD

**Issue by themongoose** [ruffle-rs/ruffle#14457]
# Error Info
Error name: Error
Error message: panicked at core/src/bitmap/bitmap_data.rs:340:45:
already borrowed: BorrowMutError
Error stack:
```
Error: panicked at core/src/bitmap/bitmap_data.rs:340:45:
already borrowed: BorrowMutError
    at H.n.wbg.__wbg_new_a64e3f2afc2cf2f8 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.bcdfe2733239b38b9831.js:1:56204)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h2d9165a4d6fb7858 (wasm://wasm/034006ea:wasm-function[9865]:0x9cd933)
    at std::panicking::rust_panic_with_hook::hbf46ef0245cc9589 (wasm://wasm/034006ea:wasm-function[6309]:0x8b9850)
    at core::panicking::panic_fmt::h14c85a61aa3d538e (wasm://wasm/034006ea:wasm-function[9656]:0x9c857f)
    at core::cell::panic_already_borrowed::h37a8f240df7d5148 (wasm://wasm/034006ea:wasm-function[9007]:0x9912af)
    at ruffle_core::bitmap::bitmap_data::wrapper::BitmapDataWrapper::sync::h07652fc2af4154c0 (wasm://wasm/034006ea:wasm-function[4671]:0x7ece9d)
    at ruffle_core::bitmap::operations::hit_test_bitmapdata::hc2dbc0235ad68094 (wasm://wasm/034006ea:wasm-function[2209]:0x5eb6f7)
    at ruffle_core::avm2::globals::flash::display::bitmap_data::hit_test::h50ca25e218827a22 (wasm://wasm/034006ea:wasm-function[787]:0x2b3d4b)
    at ruffle_core::avm2::function::Executable::exec::hff51af7d7adfbc02 (wasm://wasm/034006ea:wasm-function[875]:0x32f91c)
    at ruffle_core::avm2::object::TObject::call_property::h250c9bb578884c9c (wasm://wasm/034006ea:wasm-function[1285]:0x456def)
```
AVM2 stack:
```
    at flash.display::BitmapData/flash::display::BitmapData::hitTest()
    at BattleController$/hittingOtherHives()
    at BattleController$/addHives()
    at BattleController$/initialize()
    at Game/queryClick()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) HD Graphics 630 (0x0000591B) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 31, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://game234473.konggames.com/games/jhall_/beez/frame/3ee3f019-efa1-47bd-87a9-64a7ae62ec72/?kongregate_host=www.kongregate.com
SWF URL: https://game234473.konggames.com/gamez/0023/4473/live/secure_Beez.swf?kongregate_game_version=1438340133

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 OPR/105.0.0.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-12-18
Channel: nightly
Built: 2023-12-18T00:15:23.274Z
Commit: ecfb3b1c4c028aa3ab86835b2c2e20617698e4d9
Is extension: false

# Metadata
width: 700
height: 640
frameRate: 60
numFrames: 2
swfVersion: 10
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 1239421

**Comment by n0samu** [comment]
The problem occurs after clicking the battle button (5-dots icon)
![image](https://github.com/ruffle-rs/ruffle/assets/71368227/a520488d-bb33-43e0-896c-da92c2badbe2)

**Comment by n0samu** [comment]
The crash seems to happen inconsistently, so I was unable to do regression testing 😦
