### ISSUE TITLE
Error on http://flash.7k7k.com/cms/cms10/20220530/1613249511/index2(12(3).html

### ISSUE THREAD

**Issue by leonwh9910** [ruffle-rs/ruffle#14505]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:494:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:494:50
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (http://flash.7k7k.com/cms/cms10/20220209/1143049001/core.ruffle.6e6f3dd88c4d27073bd4.js:1:6964)
    at std::sync::once::Once::call_once::{{closure}}::h4dcb78b97de78bcf (http://flash.7k7k.com/cms/cms10/20220209/1143049001/dfa4a78c9057787bfd60.wasm:wasm-function[1018]:0x2f7fc7)
    at std::sync::once::Once::call_inner::h9279eef47cf85b81 (http://flash.7k7k.com/cms/cms10/20220209/1143049001/dfa4a78c9057787bfd60.wasm:wasm-function[1151]:0x329175)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h7e6cf7c840665392 (http://flash.7k7k.com/cms/cms10/20220209/1143049001/dfa4a78c9057787bfd60.wasm:wasm-function[4723]:0x4d573e)
    at std::panicking::rust_panic_with_hook::h47a0e203360b6c10 (http://flash.7k7k.com/cms/cms10/20220209/1143049001/dfa4a78c9057787bfd60.wasm:wasm-function[3191]:0x481112)
    at core::panicking::panic_fmt::h4ca53049f45e3264 (http://flash.7k7k.com/cms/cms10/20220209/1143049001/dfa4a78c9057787bfd60.wasm:wasm-function[4995]:0x4e13e2)
    at core::result::unwrap_failed::h6d050dbd00b66340 (http://flash.7k7k.com/cms/cms10/20220209/1143049001/dfa4a78c9057787bfd60.wasm:wasm-function[4021]:0x4be42e)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::ha51e1fedf51093c8 (http://flash.7k7k.com/cms/cms10/20220209/1143049001/dfa4a78c9057787bfd60.wasm:wasm-function[749]:0x26f493)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::register_shape::h485a634f1a1ccfdd (http://flash.7k7k.com/cms/cms10/20220209/1143049001/dfa4a78c9057787bfd60.wasm:wasm-function[3183]:0x47f3a7)
    at ruffle_core::drawing::Drawing::render::h082aa644309e2cfa (http://flash.7k7k.com/cms/cms10/20220209/1143049001/dfa4a78c9057787bfd60.wasm:wasm-function[718]:0x260e78)
```

# Player Info
Allows script access: false

# Page Info
Page URL: http://flash.7k7k.com/cms/cms10/20220530/1613249511/index2(12(3).html
SWF URL: http://flash.7k7k.com/cms/cms10/20220530/1610113381/hejindantou4.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.5735.289 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-02-07
Channel: nightly
Built: 2022-02-07T00:21:18.799Z
Commit: 562a205f3d873720ae71989850240e3ae729df64
Is extension: false

**Comment by kjarosh** [comment]
Should be fixed as of the newest version
