### ISSUE TITLE
Error on https://play.cpjourney.net/

### ISSUE THREAD

**Issue by Silly-Bacon** [ruffle-rs/ruffle#14523]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create texture object"', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.16.2/src/gles/device.rs:704:52
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create texture object"', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.16.2/src/gles/device.rs:704:52
    at W.n.wbg.__wbg_new_d258248ed531ff54 (https://cdn.jsdelivr.net/npm/@ruffle-rs/ruffle@0.1.0-nightly.2023.7.17/core.ruffle.6b69f50e7628707885d1.js:1:51547)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::he4e551a70a6b726d (wasm://wasm/02f0e486:wasm-function[9066]:0x8cc257)
    at std::panicking::rust_panic_with_hook::h5cee2a9564faeb6d (wasm://wasm/02f0e486:wasm-function[5941]:0x7cc8fb)
    at core::panicking::panic_fmt::h8a19fa1eb63fbb67 (wasm://wasm/02f0e486:wasm-function[8910]:0x8c7766)
    at core::result::unwrap_failed::h11ff2abd8d53a5bd (wasm://wasm/02f0e486:wasm-function[7045]:0x833937)
    at <T as wgpu::context::DynContext>::device_create_texture::h939dfed73011c19f (wasm://wasm/02f0e486:wasm-function[6574]:0x80b4cc)
    at wgpu::Device::create_texture::h66a8ef5ee00deefb (wasm://wasm/02f0e486:wasm-function[5017]:0x77bcec)
    at <ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::create_empty_texture::hfe58e9f8c5ffaee9 (wasm://wasm/02f0e486:wasm-function[4862]:0x76cdd0)
    at ruffle_core::display_object::render_base::hae49404d5f40cfc7 (wasm://wasm/02f0e486:wasm-function[626]:0x19bfb5)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render::hf10b412e17e56774 (wasm://wasm/02f0e486:wasm-function[6472]:0x7fde27)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA GeForce RTX 2070 (0x00001F10) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://play.cpjourney.net/
SWF URL: https://cdn.cpjourney.net/assets/media/flash/boot.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 OPR/105.0.0.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-07-17
Channel: nightly
Built: 2023-07-17T00:19:49.491Z
Commit: de9ea9571bd813c32318042af2e67dec246c8211
Is extension: false

# Metadata
width: 760
height: 480
frameRate: 24
numFrames: 1
swfVersion: 15
backgroundColor: #FFFFFF
isActionScript3: false
uncompressedLength: 88201

**Comment by Silly-Bacon** [comment]
Oh and btw to any mods who may see this, yesterday i had a different error with the same orange screen but was a validation error, i saved the error info about that one so if you want me to post the entire error details just let me know and ill upload it, this was the basic of yesterdays error- seems like a my end type of deal though lol

Error: panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_buffer
    Not enough memory left
