### ISSUE TITLE
Cocolani mini games doesn't start

### ISSUE THREAD

**Issue by cmdocmd** [ruffle-rs/ruffle#14586]
### Describe the bug

![image](https://github.com/ruffle-rs/ruffle/assets/55096480/175eff48-0136-47a9-8586-ad1525746079)

So as you can see, in console its detecting that an exit button is pressed but still doesn't exit the mini game, also the same thing it doesn't start the game (Note not all mini games inside cocolani have this issue, however, they also have other issues)

### Expected behavior

When click start game or exit game. it should start the game or close it.

### Content Location

https://safariislandsgame.com/play/

### Affected platform

Self-hosted version

### Operating system

Windows 10

### Browser

Google Chrome

**Comment by cmdocmd** [comment]
FIXED

**Comment by cmdocmd** [comment]
Some mini games started freeze 

# Error Info
Error name: Error
Error message: panicked at core/src/context.rs:511:19:
capacity overflow
Error stack:
```
Error: panicked at core/src/context.rs:511:19:
capacity overflow
    at Fe.n.wbg.__wbg_new_c68d7209be747379 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.74293a141ebb74df7286.js:1:56087)
    at ruffle_web.wasm.js_sys::Error::new::hf0b597334e970ab5 (wasm://wasm/ruffle_web.wasm-0324d5be:wasm-function[12918]:0x9993d3)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::h3a5e7d53cc41c0d7 (wasm://wasm/ruffle_web.wasm-0324d5be:wasm-function[9992]:0x94244d)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::hcc2503a68438883e (wasm://wasm/ruffle_web.wasm-0324d5be:wasm-function[7041]:0x8a4665)
    at ruffle_web.wasm.core::panicking::panic_fmt::h931ec2537c26fa22 (wasm://wasm/ruffle_web.wasm-0324d5be:wasm-function[10847]:0x9671d3)
    at ruffle_web.wasm.alloc::raw_vec::handle_error::h48c301ced15e16ee (wasm://wasm/ruffle_web.wasm-0324d5be:wasm-function[11661]:0x970526)
    at ruffle_web.wasm.alloc::raw_vec::RawVec<T,A>::grow_one::h1bc71afd617fb097 (wasm://wasm/ruffle_web.wasm-0324d5be:wasm-function[6194]:0x84c2ba)
    at ruffle_web.wasm.alloc::collections::vec_deque::VecDeque<T,A>::grow::h406e7fb7ef97e93e (wasm://wasm/ruffle_web.wasm-0324d5be:wasm-function[7612]:0x8c7881)
    at ruffle_web.wasm.<ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::interactive::TInteractiveObject>::event_dispatch::h7509dcc2f5111612 (wasm://wasm/ruffle_web.wasm-0324d5be:wasm-function[2148]:0x5234cd)
    at ruffle_web.wasm.<ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::run_frame_avm1::h43537c95f1bfafc5 (wasm://wasm/ruffle_web.wasm-0324d5be:wasm-function[4805]:0x7b0a6d)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA GeForce RTX 2060 (0x00001F15) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: "WebGL 2.0 (OpenGL ES 3.0 Chromium)"
Enabled features: Features(TEXTURE_COMPRESSION_BC | FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES)
Available features: Features(DEPTH32FLOAT_STENCIL8 | TEXTURE_COMPRESSION_BC_SLICED_3D | PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_color_attachments: 8, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)
Player type: Object
SWF URL: cocolani.swf
Param movie: cocolani.swf
Param allowFullScreen: true
Param allowFullScreenInteractive: true
Param FlashVars: regurl=php/req/&ip=127.0.0.1&lang=1&connLimit=99&baseURL=&port=9339&swfURL=swf/&cid=0&zn=1&SRon=0&zone=cocolani&lang=1
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined

# Page Info
Page URL: http://localhost/cocolani-test/
SWF URL: http://localhost/cocolani-test/cocolani.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2025-02-20
Channel: nightly
Built: 2025-02-20T00:06:10.243Z
Commit: 87ce6444166111fb0ffe0dd3e064e4a8152dfe6b
Is extension: false

# Metadata
width: 925
height: 600
frameRate: 21
numFrames: 3
swfVersion: 15
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 297651

**Comment by Kambushed12312** [comment]
Hello, sorry to bother you mate. I have the cocolani files, but im struggling to run them locally on my computer. Please help me with it, we can talk over discord if you prefer

**Comment by cmdocmd** [comment]
FIXED
