### ISSUE TITLE
Error on http://energy.melinkcorp.com/melink/html/mpower/MPowerFlash.html

### ISSUE THREAD

**Issue by bmiller-melink** [ruffle-rs/ruffle#14624]
# Error Info
Error name: Error
Error message: panicked at core/src/avm2/globals/flash/display/shader_job.rs:76:26:
Missing value property: TypeError: Error #1009: Cannot access a property or method of a null object reference. (accessing field: concat)
Error stack:
```
Error: panicked at core/src/avm2/globals/flash/display/shader_job.rs:76:26:
Missing value property: TypeError: Error #1009: Cannot access a property or method of a null object reference. (accessing field: concat)
    at imports.wbg.__wbg_new_a64e3f2afc2cf2f8 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:2624:21)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h2784d75c097bd38f (wasm://wasm/035bd9fa:wasm-function[10700]:0xa01d11)
    at std::panicking::rust_panic_with_hook::h62090d3fc0630473 (wasm://wasm/035bd9fa:wasm-function[6560]:0x8ebe24)
    at core::panicking::panic_fmt::hd79411a297d06dc8 (wasm://wasm/035bd9fa:wasm-function[10423]:0x9fba8e)
    at core::result::unwrap_failed::h59d2e017e8867fe4 (wasm://wasm/035bd9fa:wasm-function[8010]:0x95a84e)
    at <core::iter::adapters::flatten::FlatMap<I,U,F> as core::iter::traits::iterator::Iterator>::next::h8dcf9db3e1eb2d4f (wasm://wasm/035bd9fa:wasm-function[4663]:0x82d01a)
    at ruffle_core::avm2::globals::flash::display::shader_job::get_shader_args::hde3bedde8a2eaf3d (wasm://wasm/035bd9fa:wasm-function[3119]:0x6e1dd9)
    at <ruffle_render::filters::Filter as ruffle_core::avm2::filters::FilterAvm2Ext>::from_avm2_object::ha6e267e62da336a7 (wasm://wasm/035bd9fa:wasm-function[615]:0x12778c)
    at ruffle_core::avm2::globals::flash::display::display_object::set_filters::h9c937177cfd519c4 (wasm://wasm/035bd9fa:wasm-function[1737]:0x50f2ed)
    at ruffle_core::avm2::function::Executable::exec::hac5e086b2a7e9b24 (wasm://wasm/035bd9fa:wasm-function[866]:0x2f886e)
```
AVM2 stack:
```
    at flash.display::DisplayObject/flash::display::DisplayObject::filters()
    at mx.core::UIComponent/set filters()
    at spark.effects.supportClasses::AnimateTransitionShaderInstance/animationStart()
    at spark.effects.animation::Animation/sendAnimationEvent()
    at spark.effects.animation::Animation/start()
    at spark.effects.animation::Animation/play()
    at spark.effects.supportClasses::AnimateInstance/play()
    at spark.effects.supportClasses::AnimateTransitionShaderInstance/play()
    at spark.effects.supportClasses::AnimateInstance/startEffect()
    at mx.effects::Effect/play()
    at mx.core::UIComponent/commitCurrentState()
    at mx.core::UIComponent/setCurrentState()
    at mx.core::UIComponent/set currentState()
    at spark.components.supportClasses::SkinnableComponent/commitProperties()
    at spark.components.supportClasses::ButtonBase/commitProperties()
    at mx.core::UIComponent/validateProperties()
    at mx.managers::LayoutManager/validateProperties()
    at mx.managers::LayoutManager/doPhasedInstantiation()
    at mx.managers::LayoutManager/doPhasedInstantiationCallback()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) UHD Graphics 620 (0x00003EA0) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 31, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: http://energy.melinkcorp.com/melink/html/mpower/MPowerFlash.html
SWF URL: http://energy.melinkcorp.com/melink/html/mpower/mpower-flash-1.0.3.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-01-05
Channel: nightly
Built: 2024-01-05T00:14:48.382Z
Commit: 89b7f7a6b8e851d5d76c94ca5db969a8457b5ab1
Is extension: true

# Metadata
width: 500
height: 375
frameRate: 24
numFrames: 2
swfVersion: 10
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 5772557

**Comment by evilpie** [comment]
- There is some problem with a ShaderParameter where the value is null. (Maybe a bug in the original code, too?)
- XML::name() needs to set the attribute flag.

![image](https://github.com/ruffle-rs/ruffle/assets/296445/6a6dabe3-c3a1-42bf-8e4f-cad6300c88d0)

**Comment by Lord-McSweeney** [comment]
@Aaron1011 can you look into the pixel bender side of this?
