### ISSUE TITLE
Error on https://clickjogos.netlify.app/jogos/footballtennisgoldmaster

### ISSUE THREAD

**Issue by Rodrigo3441** [ruffle-rs/ruffle#14642]
# Error Info
Error name: Error
Error message: panicked at library/alloc/src/raw_vec.rs:545:5:
capacity overflow
Error stack:
```
Error: panicked at library/alloc/src/raw_vec.rs:545:5:
capacity overflow
    at H.n.wbg.__wbg_new_a64e3f2afc2cf2f8 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.bc67547d0a971bd36f7d.js:1:56204)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h2784d75c097bd38f (wasm://wasm/035b44e2:wasm-function[10687]:0x9fea52)
    at std::panicking::rust_panic_with_hook::h62090d3fc0630473 (wasm://wasm/035b44e2:wasm-function[6554]:0x8ea228)
    at core::panicking::panic_fmt::hd79411a297d06dc8 (wasm://wasm/035b44e2:wasm-function[10410]:0x9f879c)
    at alloc::raw_vec::capacity_overflow::hfd18578094e5282c (wasm://wasm/035b44e2:wasm-function[10409]:0x9f8699)
    at ruffle_core::tag_utils::SwfMovie::from_data::hdb24402a8f7ac7a6 (wasm://wasm/035b44e2:wasm-function[4007]:0x79d7a1)
    at ruffle_core::loader::Loader::root_movie_loader::{{closure}}::h07faf9c80601526c (wasm://wasm/035b44e2:wasm-function[953]:0x345a8a)
    at <ruffle_web::navigator::WebNavigatorBackend as ruffle_core::backend::navigator::NavigatorBackend>::spawn_future::{{closure}}::hfa8beaa0cfd6ab75 (wasm://wasm/035b44e2:wasm-function[1265]:0x42c4e0)
    at wasm_bindgen_futures::queue::Queue::new::{{closure}}::hf3d45b9fcb0286e9 (wasm://wasm/035b44e2:wasm-function[3700]:0x76aa7c)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h4b99ccc6980aa0f1 (wasm://wasm/035b44e2:wasm-function[11638]:0xa1b0ba)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) HD Graphics (0x00000152) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 31, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }
Player type: Object
SWF URL: games/footballtennisgoldmaster.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://clickjogos.netlify.app/jogos/footballtennisgoldmaster
SWF URL: https://clickjogos.netlify.app/jogos/games/footballtennisgoldmaster.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-01-06
Channel: nightly
Built: 2024-01-06T00:14:38.881Z
Commit: 47deaf50a20bf996cc93c18ea61160d3f0b97fb9
Is extension: false

# Metadata

**Comment by Lord-McSweeney** [comment]
The site is serving a corrupt SWF file, see #6473
