### ISSUE TITLE
Error on https://sitescours.monportail.ulaval.ca/contenu/sitescours/036/03607/202401/site163212/modules1235818/module1548727/page4199569/page4199570/bloccontenu4386526/productionweb7878097/Processus%20de%20design%20-%20Presenter%20output/presentation.html

### ISSUE THREAD

**Issue by Melissa9824** [ruffle-rs/ruffle#14747]
# Error Info
Error name: Error
Error message: panicked at core/src/display_object/movie_clip.rs:2575:28:
already borrowed: BorrowMutError
Error stack:
```
Error: panicked at core/src/display_object/movie_clip.rs:2575:28:
already borrowed: BorrowMutError
    at imports.wbg.__wbg_new_a64e3f2afc2cf2f8 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:2624:21)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h5a435d7beef43b50 (wasm://wasm/0363c85e:wasm-function[10780]:0xa1e15d)
    at std::panicking::rust_panic_with_hook::h62090d3fc0630473 (wasm://wasm/0363c85e:wasm-function[6596]:0x905eda)
    at core::panicking::panic_fmt::hd79411a297d06dc8 (wasm://wasm/0363c85e:wasm-function[10492]:0xa17cc2)
    at core::cell::panic_already_borrowed::h8c62ffbd80fe44ce (wasm://wasm/0363c85e:wasm-function[9711]:0x9e2c10)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::set_maskee::h46176307e53d6723 (wasm://wasm/0363c85e:wasm-function[1614]:0x4eb8cd)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::set_masker::h5fe608d7e3cebbe3 (wasm://wasm/0363c85e:wasm-function[2086]:0x5c5255)
    at ruffle_core::avm2::globals::flash::display::display_object::set_mask::h99270021bf24acba (wasm://wasm/0363c85e:wasm-function[3956]:0x7ab5e0)
    at ruffle_core::avm2::function::Executable::exec::h0105c140d9037b4e (wasm://wasm/0363c85e:wasm-function[872]:0x310811)
    at ruffle_core::avm2::object::TObject::call_method::h51c513e0ffe9daad (wasm://wasm/0363c85e:wasm-function[2736]:0x69ed18)
```
AVM2 stack:
```
    at flash.display::DisplayObject/flash::display::DisplayObject::mask()
    at com.articulate.bw.v3_0.objects::bwStageObject/Destroy()
    at com.articulate.bw.v3_0.objects::bwSmoothSequenceControl/Destroy()
    at com.articulate.bw.v3_0.core::bwSlide/DestroySlideObjects()
    at com.articulate.bw.v3_0.core::bwSlide/KillSlideDisplay()
    at com.articulate.bw.v3_0.core::bwSlide/HideSlide()
    at com.articulate.bw.v3_0.core::bwSlide/NotifySlideTransitionInComplete()
    at com.articulate.bw.v3_0.core::bwSlide/AnimationComplete()
    at flash.events::EventDispatcher/flash::events::EventDispatcher::dispatchEvent()
    at com.articulate.bw.v3_0.animation::bwAnimation/StepAnimation()
    at com.articulate.bw.v3_0.animation::bwAnimation/PlayAnimation()
    at com.articulate.bw.v3_0.core::bwSlide/ShowSlide()
    at com.articulate.bw.v3_0.core::bwActionHandler/GotoAndPlaySlide()
    at com.articulate.bw.v3_0.core::bwActionHandler/NextDrawSlide()
    at com.articulate.bw.v3_0.core::bwActionHandler/DoActionEvent()
    at com.articulate.bw.v3_0.core::bwSlide/DoActionEvent()
    at com.articulate.bw.v3_0.core::bwObjectSprite/ExecuteActions()
    at com.articulate.bw.v3_0.objects::bwStageObject/DoEventActions()
    at com.articulate.bw.v3_0.objects::bwStageObject/HandleMouseEvent()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) HD Graphics (0x00000F31) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 31, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96, max_non_sampler_bindings: 1000000 }
Surface quality: best
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://sitescours.monportail.ulaval.ca/contenu/sitescours/036/03607/202401/site163212/modules1235818/module1548727/page4199569/page4199570/bloccontenu4386526/productionweb7878097/Processus%20de%20design%20-%20Presenter%20output/presentation.html
SWF URL: https://sitescours.monportail.ulaval.ca/contenu/sitescours/036/03607/202401/site163212/modules1235818/module1548727/page4199569/page4199570/bloccontenu4386526/productionweb7878097/Processus%20de%20design%20-%20Presenter%20output/presentation.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-01-14
Channel: nightly
Built: 2024-01-14T00:15:12.544Z
Commit: 2557d1467810ff48c913fa7a6939242287a7224b
Is extension: true

# Metadata
width: 980
height: 634
frameRate: 30
numFrames: 1
swfVersion: 12
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 711691

**Comment by n0samu** [comment]
Hi @Melissa9824, could you please provide the SWF file that triggered this problem?
