### ISSUE TITLE
Stealth Hunter 2 - Game softlocks itself after exceeding the maximum call stack size in the first level

### ISSUE THREAD

**Issue by Molisson** [ruffle-rs/ruffle#14744]
### Describe the bug

1. Play the first level as usual
2. Reach the second cutscene trigger, where the main protagonist talks about the shipment and wait until the cutscene ends

If done correctly, the game should be softlocked for you and you are unable to progress

### Expected behavior

The game should not be softlocked and progress the game

### Content Location

https://www.newgrounds.com/portal/view/592710?emulate=flash

### Affected platform

Self-hosted version

### Operating system

Windows 11

### Browser

Microsoft Edge

### Additional information

One error log I found

```
Uncaught RangeError: Maximum call stack size exceeded
    at ruffle_core::avm2::activation::Activation::resolve_parameters::h20d8c8beac9ae0e8 (0363ec7e:0x6b08ba)
    at ruffle_core::avm2::function::Executable::exec::h0105c140d9037b4e (0363ec7e:0x317699)
    at <ruffle_core::avm2::object::class_object::ClassObject as ruffle_core::avm2::object::TObject>::construct::hd8e3428cf17f259f (0363ec7e:0x849eee)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::construct::hac23978d6b60af93 (0363ec7e:0x42c006)
    at ruffle_core::avm2::activation::Activation::run_actions::h8dfafc6a0c0a2658 (0363ec7e:0x30700)
    at ruffle_core::avm2::function::Executable::exec::h0105c140d9037b4e (0363ec7e:0x317db6)
    at ruffle_core::avm2::object::TObject::call_method::h091cbfec09dcbe4f (0363ec7e:0x69912f)
    at ruffle_core::avm2::object::TObject::get_property::haf4707cd908ef05c (0363ec7e:0x5c149c)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::get_public_property::hd4fd23124ac9d159 (0363ec7e:0x2330bd)
    at ruffle_core::avm2::amf::recursive_serialize::hd04ba0c22de04ef0 (0363ec7e:0x4806dc)
```

**Comment by Lord-McSweeney** [comment]
This may be related to recursive serialization of objects into AMF in AVM2

**Comment by Molisson** [comment]
Looks like it displays a different error message now:
# Error Info
Error name: Error
Error message: panicked at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/sys/sync/mutex/no_threads.rs:20:9:
assertion `left == right` failed: cannot recursively acquire mutex
  left: true
 right: false
Error stack:
```
Error: panicked at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/sys/sync/mutex/no_threads.rs:20:9:
assertion `left == right` failed: cannot recursively acquire mutex
  left: true
 right: false
    at n.wbg.__wbg_new_796382978dfd4fb0 (https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.ea72a1b0ea04de9f53d9.js:1:84118)
    at ruffle_web.wasm.js_sys::Error::new::h707edc16dc8b9bc8 (wasm://wasm/ruffle_web.wasm-03241f5e:wasm-function[12797]:0x98f58a)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::hdac645c719d844de (wasm://wasm/ruffle_web.wasm-03241f5e:wasm-function[9768]:0x91ec01)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h33fe77d38d305ca3 (wasm://wasm/ruffle_web.wasm-03241f5e:wasm-function[6367]:0x8178d4)
    at ruffle_web.wasm.core::panicking::panic_fmt::hde8b7aa66e2831e1 (wasm://wasm/ruffle_web.wasm-03241f5e:wasm-function[9484]:0x90f19f)
    at ruffle_web.wasm.core::panicking::assert_failed_inner::hc95b7725cb4077cb (wasm://wasm/ruffle_web.wasm-03241f5e:wasm-function[4450]:0x74f823)
    at ruffle_web.wasm.core::panicking::assert_failed::he542e3a695f39576 (wasm://wasm/ruffle_web.wasm-03241f5e:wasm-function[10238]:0x93b95d)
    at ruffle_web.wasm.ruffle_core::loader::Loader::load_url_loader::{{closure}}::h1472d3323e8aef50 (wasm://wasm/ruffle_web.wasm-03241f5e:wasm-function[3855]:0x6e8a3c)
    at ruffle_web.wasm.<ruffle_web::navigator::WebNavigatorBackend as ruffle_core::backend::navigator::NavigatorBackend>::spawn_future::{{closure}}::hd7b5de012cba516f (wasm://wasm/ruffle_web.wasm-03241f5e:wasm-function[1523]:0x42bc2f)
    at ruffle_web.wasm.wasm_bindgen_futures::queue::Queue::new::{{closure}}::hca68ab360cc78174 (wasm://wasm/ruffle_web.wasm-03241f5e:wasm-function[3673]:0x6c01d0)
```
AVM2 stack:
```
    at sh3.engine.core::SHEntity/get location()
    at flash.utils::ByteArray/flash::utils::ByteArray::writeObject()
    at sh3.vo::CheckpointVO$/create()
    at sh3.util::GameUtils$/checkpoint()
    at sh3.world.the_landing::TheLanding/checkpoint()
    at Function/apply()
    at jrlib.util.queue.items::CallFunctionTask/execute()
    at jrlib.util.queue::QueueItem/_execute()
    at jrlib.util.queue::CommandQueue/process()
    at jrlib.util.queue::CommandQueue/process()
    at jrlib.util.queue::CommandQueue/process()
    at jrlib.util.queue::CommandQueue/process()
    at jrlib.util.queue::CommandQueue/process()
    at jrlib.util.queue::CommandQueue/process()
    at sh3.engine.components::EngineCinematics/update()
    at jrlib.util.components::ComponentSet/update()
    at giraffetile::TileEngine/update()
    at sh3.engine::SHEngine/update()
    at sh3.view::GameScreen/update()
    at jrlib.display.screenmanager::ScreenManager/run()
```
