### ISSUE TITLE
Error on https://www.arcadeprehacks.com/game/31959/pre-civilization-3-marble-age.html

### ISSUE THREAD

**Issue by Malagalius** [ruffle-rs/ruffle#14752]
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/daedf03/wgpu/src/backend/direct.rs:3111:5:
wgpu error: Validation Error

Caused by:
    In Device::create_texture
    Dimension Y is zero

Error stack:
```
Error: panicked at /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/daedf03/wgpu/src/backend/direct.rs:3111:5:
wgpu error: Validation Error

Caused by:
    In Device::create_texture
    Dimension Y is zero


    at imports.wbg.__wbg_new_a64e3f2afc2cf2f8 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:2624:21)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h5a435d7beef43b50 (wasm://wasm/0363ec7e:wasm-function[10793]:0xa1f551)
    at std::panicking::rust_panic_with_hook::h62090d3fc0630473 (wasm://wasm/0363ec7e:wasm-function[6608]:0x906d55)
    at core::panicking::panic_fmt::hd79411a297d06dc8 (wasm://wasm/0363ec7e:wasm-function[10505]:0xa190b6)
    at core::ops::function::Fn::call::ha42a97d062520d10 (wasm://wasm/0363ec7e:wasm-function[6911]:0x91da8d)
    at wgpu::backend::direct::ErrorSinkRaw::handle_error::haebbe3d4b91cfc0a (wasm://wasm/0363ec7e:wasm-function[5436]:0x89ea6a)
    at <T as wgpu::context::DynContext>::device_create_texture::h5ba6f27923826b30 (wasm://wasm/0363ec7e:wasm-function[7421]:0x94a7c9)
    at wgpu::Device::create_texture::h90d943038ac7ff31 (wasm://wasm/0363ec7e:wasm-function[5768]:0x8bb8ee)
    at <ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::register_bitmap::hcec93820ad2d1bb6 (wasm://wasm/0363ec7e:wasm-function[2204]:0x600b15)
    at ruffle_core::bitmap::bitmap_data::BitmapData::bitmap_handle::hee3b4bac80fb03ae (wasm://wasm/0363ec7e:wasm-function[1605]:0x4e57ea)
```
AVM2 stack:
```
    at flash.display::BitmapData/flash::display::BitmapData::draw()
    at com.emibap.textureAtlas::DynamicAtlas$/drawItem()
    at com.emibap.textureAtlas::DynamicAtlas$/fromMovieClipContainer()
    at Asset$/loadAtlas()
    at Asset$/init()
    at Classes$/init()
    at MainMenu()
    at starling.core::Starling/initializeRoot()
    at starling.core::Starling/initialize()
    at starling.core::Starling/onContextCreated()
    at flash.events::EventDispatcher/flash::events::EventDispatcher::dispatchEvent()
    at flash.display::Stage3D/flash::display::Stage3D::requestContext3D_internal()
    at MethodInfo-1863()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (AMD, AMD Radeon (TM) Graphics (0x000015E7) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 31, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://www.arcadeprehacks.com/game/31959/pre-civilization-3-marble-age.html
SWF URL: https://www.arcadeprehacks.com/swf/precivilization_3_marble_age-hacked.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0
Platform: Win32
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-01-13
Channel: nightly
Built: 2024-01-13T00:14:58.057Z
Commit: 2775c917bf61254dbddf67b604d36157efdff7d5
Is extension: true

# Metadata
width: 800
height: 641
frameRate: 30
numFrames: 5
swfVersion: 19
backgroundColor: #FFFFFF
isActionScript3: true
uncompressedLength: 70579

**Comment by MartySVK** [comment]
already created - https://github.com/ruffle-rs/ruffle/issues/13946
