### ISSUE TITLE
`Parent device is lost` on startup

### ISSUE THREAD

**Issue by MeowKatee** [ruffle-rs/ruffle#14834]
### Describe what you were doing

Trying to load any flash game with `ruffle xxx.swf`

### What does the crash message say?

panicked at /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/daedf03/wgpu/src/backend/direct.rs:778:18:
Error in Surface::configure: Validation Error

Caused by:
    Parent device is lost

### Ruffle Version

0.1.0-nightly (5f123c3c011b044670602c2b0bb986527fc57135 2024-01-19)

### Affected platform

Desktop app

### Operating system

Arch Linux Rolling Release [64-bit]

### Additional information

CPU: Intel i5-6300HQ (4) @ 3.200GHz
GPU: NVIDIA GeForce GTX 960M
Kernel: 6.6.11-x64v2-xanmod1-1
Running Plasma 5.27.10 on wayland

**Comment by poly000** [comment]
may related to https://github.com/gfx-rs/wgpu/issues/2519

**Comment by MeowKatee** [comment]
https://github.com/ruffle-rs/ruffle/blob/233478a2738c4d5a3c5423fc5007cd9814613103/render/wgpu/src/backend.rs#L1055-L1080

I am unsure but seems ruffle will ignore `WGPU_ADAPTER_NAME`, the environment variable that wgpu allows user to specify their wanted GPU to run on
I will try add [`initialize_adapter_from_env`](https://docs.rs/wgpu/latest/wgpu/util/fn.initialize_adapter_from_env.html) here

**Comment by MeowKatee** [comment]
```text
2024-01-20T15:39:31.402717Z DEBUG sctk: Bound new global [47] wl_output v4    
2024-01-20T15:39:31.402863Z DEBUG sctk: Bound new global [32] zxdg_output_manager_v1 v3    
2024-01-20T15:39:31.402955Z DEBUG sctk: Bound new global [12] wl_seat v7    
2024-01-20T15:39:31.406721Z DEBUG sctk: supported wl_shm format Argb8888    
2024-01-20T15:39:31.406790Z DEBUG sctk: supported wl_shm format Xrgb8888    
2024-01-20T15:39:31.406844Z DEBUG sctk: supported wl_shm format Argb2101010    
2024-01-20T15:39:31.406911Z DEBUG sctk: supported wl_shm format Xrgb2101010    
2024-01-20T15:39:31.406935Z DEBUG sctk: supported wl_shm format Abgr2101010    
2024-01-20T15:39:31.406956Z DEBUG sctk: supported wl_shm format Xbgr2101010    
2024-01-20T15:39:31.406975Z DEBUG sctk: supported wl_shm format Abgr16161616    
2024-01-20T15:39:31.406994Z DEBUG sctk: supported wl_shm format Xbgr16161616    
2024-01-20T15:39:31.536799Z  WARN wgpu_hal::vulkan::instance: InstanceFlags::VALIDATION requested, but unable to find layer: VK_LAYER_KHRONOS_validation    
2024-01-20T15:39:31.544576Z  INFO wgpu_hal::vulkan::instance: Instance version: 0x403112    
2024-01-20T15:39:31.544638Z  INFO wgpu_hal::vulkan::instance: Debug utils not enabled: debug_utils_user_data not passed to Instance::from_raw    
2024-01-20T15:39:31.544672Z  INFO wgpu_hal::vulkan::instance: Enabling device properties2    
2024-01-20T15:39:31.544719Z DEBUG wgpu_core::instance: Instance::new: created Vulkan backend    
2024-01-20T15:39:31.549653Z  WARN wgpu_hal::vulkan::instance: Disabling presentation on 'Intel(R) HD Graphics 530 (SKL GT2)' (id 0x56062b180d70) due to NV Optimus and Intel Mesa < v21.2    
2024-01-20T15:39:31.549838Z  INFO wgpu_core::instance: Adapter Vulkan AdapterInfo { name: "NVIDIA GeForce GTX 960M", vendor: 4318, device: 5019, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "545.29.06", backend: Vulkan }    
2024-01-20T15:39:31.556756Z DEBUG wgpu_hal::vulkan::adapter: Supported extensions: ["VK_KHR_swapchain", "VK_KHR_swapchain_mutable_format", "VK_EXT_robustness2"]    
2024-01-20T15:39:31.597632Z  INFO wgpu_core::device::global: configuring surface with SurfaceConfiguration { usage: TextureUsages(RENDER_ATTACHMENT), format: Bgra8UnormSrgb, width: 800, height: 600, present_mode: Fifo, alpha_mode: Auto, view_formats: [] }    
2024-01-20T15:39:31.597786Z  INFO wgpu_core::device::global: Automatically choosing alpha mode by rule Auto. Chose Opaque    
2024-01-20T15:39:31.608029Z  WARN wgpu_hal::vulkan: Unrecognized device error ERROR_INITIALIZATION_FAILED    
thread 'main' panicked at /home/meowkate/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/daedf03/wgpu/src/backend/direct.rs:778:18:
Error in Surface::configure: Validation Error

Caused by:
    Parent device is lost

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2024-01-20T15:39:43.429727Z  INFO wgpu_core::global: Dropping Global    
2024-01-20T15:39:43.429915Z  INFO wgpu_core::device: Destroying 0 command encoders    
```

**Comment by MeowKatee** [comment]
nevermind, just after KDE's strange behavior I found my kernel parameter `nvidia-drm.modset=1`, there is a missing letter 'e', that NVIDIA doesn't work

**Comment by MeowKatee** [comment]
nevermind, it's all due to bad kernel parameter: I missed a 'e' in `nvidia_drm.modeset=1`
