### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by Blackskull66** [ruffle-rs/ruffle#14995]
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.19.1/src/backend/wgpu_core.rs:3009:5:
wgpu error: Validation Error

Caused by:
    In Device::create_buffer
    Not enough memory left.

Error stack:
```
Error: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.19.1/src/backend/wgpu_core.rs:3009:5:
wgpu error: Validation Error

Caused by:
    In Device::create_buffer
    Not enough memory left.


    at Y.n.wbg.__wbg_new_3a66822ed076951c (https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.b56fab9bb3661146be49.js:1:73909)
    at js_sys::Error::new::h728118aa18eebd18 (wasm://wasm/038693c6:wasm-function[13695]:0xae0564)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hfc928092015e7dff (wasm://wasm/038693c6:wasm-function[11318]:0xa8b041)
    at std::panicking::rust_panic_with_hook::h62090d3fc0630473 (wasm://wasm/038693c6:wasm-function[6936]:0x949573)
    at core::panicking::panic_fmt::hd79411a297d06dc8 (wasm://wasm/038693c6:wasm-function[11040]:0xa847b8)
    at core::ops::function::Fn::call::h15de8e8c05bfa63c (wasm://wasm/038693c6:wasm-function[7234]:0x96031c)
    at wgpu::backend::wgpu_core::ErrorSinkRaw::handle_error::h2f49cf1f9462116e (wasm://wasm/038693c6:wasm-function[5748]:0x8dd942)
    at <T as wgpu::context::DynContext>::device_create_buffer::h3faa3fcecc009374 (wasm://wasm/038693c6:wasm-function[7964]:0x9a40f3)
    at <wgpu::Device as wgpu::util::device::DeviceExt>::create_buffer_init::hb585a5e684f8561f (wasm://wasm/038693c6:wasm-function[2011]:0x56bebb)
    at ruffle_render_wgpu::buffer_builder::BufferBuilder::finish::h19cd563afbd0dbd4 (wasm://wasm/038693c6:wasm-function[8092]:0x9ad533)
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Mesa Intel(R) HD Graphics 620 (KBL GT2), OpenGL 4.6)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(FLOAT32_FILTERABLE | TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 31, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.67&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1706534391%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F592000%2F592473_MadnessGame_ULTIMATE.swf%3F1507662264%22%2C%22vars%22%3A%7B%22ngio_session_id%22%3A%2228873496.93e5dac0ea7b569d3d6f5cab4885dc0a8276e50f8132bb%22%2C%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%2265b7ae3359fe5%22%2C%22NewgroundsAPI_SessionID%22%3A%229EW5xU6eBQ8eDPkIu3FB158df33471fecad9f1183c35df3ee53083cc1535wOh2%22%2C%22NewgroundsAPI_UserName%22%3A%22Kalle23%22%2C%22NewgroundsAPI_UserID%22%3A14417295%2C%22ng_username%22%3A%22Kalle23%22%7D%2C%22width%22%3A850%2C%22height%22%3A530%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F592000%2Fflash_592473_card.webp%3Ff1669742379%22%2C%22warnOnUnsupportedContent%22%3Afalse%7D
SWF URL: https://uploads.ungrounded.net/592000/592473_MadnessGame_ULTIMATE.swf?1507662264

# Browser Info
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-01-29
Channel: nightly
Built: 2024-01-29T00:15:42.399Z
Commit: f2880975ba9cb16fa3a96c5c0d529cbeac81fe78
Is extension: false

# Metadata
width: 850
height: 530
frameRate: 30
numFrames: 30
swfVersion: 10
backgroundColor: #FFFFFF
isActionScript3: false
uncompressedLength: 20491352

**Comment by Lord-McSweeney** [comment]
Duplicate of #9834
