### ISSUE TITLE
Error on https://static.familyspace.ru/swf/tree/tree.test.domain.swf

### ISSUE THREAD

**Issue by Pr0gra2Mer** [ruffle-rs/ruffle#15037]
# Error Info
Error name: Error
Error message: panicked at library/alloc/src/raw_vec.rs:545:5:
capacity overflow
Error stack:
```
Error: panicked at library/alloc/src/raw_vec.rs:545:5:
capacity overflow
    at imports.wbg.__wbg_new_3a66822ed076951c (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:3476:21)
    at js_sys::Error::new::h728118aa18eebd18 (wasm://wasm/038673d6:wasm-function[13699]:0xadfb64)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hfc928092015e7dff (wasm://wasm/038673d6:wasm-function[11320]:0xa8a4da)
    at std::panicking::rust_panic_with_hook::h62090d3fc0630473 (wasm://wasm/038673d6:wasm-function[6942]:0x948d3c)
    at core::panicking::panic_fmt::hd79411a297d06dc8 (wasm://wasm/038673d6:wasm-function[11042]:0xa83c1e)
    at alloc::raw_vec::capacity_overflow::hfd18578094e5282c (wasm://wasm/038673d6:wasm-function[11041]:0xa83b1b)
    at alloc::raw_vec::RawVec<T,A>::reserve::do_reserve_and_handle::h4ff941c72b9393b7 (wasm://wasm/038673d6:wasm-function[6800]:0x93c405)
    at <ruffle_core::avm2::object::array_object::ArrayObject as ruffle_core::avm2::object::TObject>::set_property_local::h49bf8c8340d44bf1 (wasm://wasm/038673d6:wasm-function[3000]:0x6d08b5)
    at ruffle_core::avm2::object::TObject::set_property::h4bbe594b51fb4c27 (wasm://wasm/038673d6:wasm-function[3066]:0x6de742)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::set_property::h0bf23c0fe8c5dac2 (wasm://wasm/038673d6:wasm-function[2896]:0x6b2635)
```
AVM2 stack:
```
    at tree.model.base::ModelCollection/add()
    at tree.command::ConstructTreeModel/createPersonsinXmlTree()
    at tree.manager::Ticker/onTick()
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) HD Graphics 530 (0x00001912) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(FLOAT32_FILTERABLE | TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 31, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)

# Page Info
Page URL: chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/player.html#https://static.familyspace.ru/swf/tree/tree.test.domain.swf?get=uid%3D80825564&script_path=https%3A%2F%2Fwww.familyspace.ru%2Fajax.php
SWF URL: https://static.familyspace.ru/swf/tree/tree.test.domain.swf?get=uid%3D80825564&script_path=https%3A%2F%2Fwww.familyspace.ru%2Fajax.php

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-01-30
Channel: nightly
Built: 2024-01-30T00:15:06.684Z
Commit: 1cf669c75e81654f83e20900a683cdb22e14a6d2
Is extension: true

# Metadata
width: 1000
height: 950
frameRate: 30
numFrames: 2
swfVersion: 14
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 1327237

**Comment by Lord-McSweeney** [comment]
I don't remember this panicking, but apparently it does, since at least nightly `2024-01-13`

**Comment by Lord-McSweeney** [comment]
This problem is also present in nightly 2024-01-13
