### ISSUE TITLE
Can no longer compile web builds

### ISSUE THREAD

**Issue by Toad06** [ruffle-rs/ruffle#1517]
I was able to compile web builds using `npm run bootstrap` and then `npm run build`, but this last command no longer works. Here's the log:
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.14.6
3 info using node@v12.18.3
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle ruffle@0.1.0~prebuild: ruffle@0.1.0
6 info lifecycle ruffle@0.1.0~build: ruffle@0.1.0
7 verbose lifecycle ruffle@0.1.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle ruffle@0.1.0~build: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\toad\Desktop\Ruffle\ruffle-master\web\node_modules\.bin;C:\Python38\Scripts\;C:\Python38\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Users\toad\.cargo\bin;C:\Users\toad\AppData\Local\Microsoft\WindowsApps;C:\Users\toad\AppData\Roaming\npm;C:\Users\toad\AppData\Local\GitHubDesktop\bin
9 verbose lifecycle ruffle@0.1.0~build: CWD: C:\Users\toad\Desktop\Ruffle\ruffle-master\web
10 silly lifecycle ruffle@0.1.0~build: Args: [ '/d /s /c', 'lerna run build --stream' ]
11 silly lifecycle ruffle@0.1.0~build: Returned: code: 2  signal: null
12 info lifecycle ruffle@0.1.0~build: Failed to exec build script
13 verbose stack Error: ruffle@0.1.0 build: `lerna run build --stream`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid ruffle@0.1.0
15 verbose cwd C:\Users\toad\Desktop\Ruffle\ruffle-master\web
16 verbose Windows_NT 10.0.19041
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v12.18.3
19 verbose npm  v6.14.6
20 error code ELIFECYCLE
21 error errno 2
22 error ruffle@0.1.0 build: `lerna run build --stream`
22 error Exit status 2
23 error Failed at the ruffle@0.1.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
```
For some reason, reverting the changes introduced in #1495 allows me to compile again.

(while I'm at it, I'd like to let you know that the version number of [nightly 2020-11-06](https://github.com/ruffle-rs/ruffle/releases/tag/nightly-2020-11-06) is `2020-11-04` which doesn't seem correct?)

**Comment by Dinnerbone** [comment]
Aha, that introduced a dependency on git. I should make that optional!
