### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by 1109-Robins-Aaron** [ruffle-rs/ruffle#15266]
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.19.1/src/gles/device.rs:752:52:
called `Result::unwrap()` on an `Err` value: "Unable to create texture object"
Error stack:
```
Error: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.19.1/src/gles/device.rs:752:52:
called `Result::unwrap()` on an `Err` value: "Unable to create texture object"
    at N.n.wbg.__wbg_new_3a66822ed076951c (https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.d7a66e39a50acd53556d.js:1:72830)
    at js_sys::Error::new::he329e38f5ae64355 (wasm://wasm/03915672:wasm-function[13733]:0xb05b80)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h9929706439805e04 (wasm://wasm/03915672:wasm-function[11349]:0xaaffa6)
    at std::panicking::rust_panic_with_hook::h1e6ac5d404b8e31b (wasm://wasm/03915672:wasm-function[6918]:0x96ef84)
    at core::panicking::panic_fmt::h87755523850ece9e (wasm://wasm/03915672:wasm-function[11065]:0xaa95b1)
    at core::result::unwrap_failed::hd86007cff22dcd83 (wasm://wasm/03915672:wasm-function[8530]:0x9fecd8)
    at <T as wgpu::context::DynContext>::device_create_texture::hcd2a8599823851e2 (wasm://wasm/03915672:wasm-function[7637]:0x9a6ebc)
    at wgpu::Device::create_texture::hd644553ce3a5784a (wasm://wasm/03915672:wasm-function[6087]:0x922363)
    at <ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::create_empty_texture::h1ce67725572c50a2 (wasm://wasm/03915672:wasm-function[5879]:0x90e69b)
    at ruffle_core::display_object::render_base::hfc80bc1aa035ecbf (wasm://wasm/03915672:wasm-function[796]:0x150572)
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) UHD Graphics (0x00009BC4) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(FLOAT32_FILTERABLE | TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 31, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.67&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1708091642%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F592000%2F592473_MadnessGame_ULTIMATE.swf%3F1507662264%22%2C%22vars%22%3A%7B%22ngio_session_id%22%3A%2256465455.7e120d2dee1d56a10864bbae6d47cfe20bd3b5a0b78bd0%22%2C%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%2265d1eed2d1217%22%2C%22NewgroundsAPI_SessionID%22%3A%22qpdUF3H5tjV46pTCD8Js2d5c5ca74e7e42da700111a8a457159e9a1d9d81e7Ge%22%2C%22NewgroundsAPI_UserName%22%3A%22ajrobins11%22%2C%22NewgroundsAPI_UserID%22%3A7426585%2C%22ng_username%22%3A%22ajrobins11%22%7D%2C%22width%22%3A850%2C%22height%22%3A530%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F592000%2Fflash_592473_card.webp%3Ff1669742379%22%2C%22warnOnUnsupportedContent%22%3Afalse%7D
SWF URL: https://uploads.ungrounded.net/592000/592473_MadnessGame_ULTIMATE.swf?1507662264

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0
Platform: Win32
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-02-16
Channel: nightly
Built: 2024-02-16T00:16:18.720Z
Commit: 4bcba369570532471e8da2b9c9b6c894e991e914
Is extension: false

# Metadata
width: 850
height: 530
frameRate: 30
numFrames: 30
swfVersion: 10
backgroundColor: #FFFFFF
isActionScript3: false
uncompressedLength: 20491352

**Comment by Lord-McSweeney** [comment]
Duplicate of #12236
