### ISSUE TITLE
Error on http://www.squeakland.org/resources/audioVisual/movie.jsp

### ISSUE THREAD

**Issue by wwj718** [ruffle-rs/ruffle#15389]
# Error Info
Error name: Error
Error message: panicked at core/src/avm2/flv.rs:67:17:
not implemented: FLV data to AVM2 data conversion unimplemented for Date { unix_time: 1217601487883.075, local_offset: -240 }
Error stack:
```
Error: panicked at core/src/avm2/flv.rs:67:17:
not implemented: FLV data to AVM2 data conversion unimplemented for Date { unix_time: 1217601487883.075, local_offset: -240 }
    at imports.wbg.__wbg_new_3a66822ed076951c (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/69.js:3393:21)
    at js_sys::Error::new::h139de3c383c43588 (wasm://wasm/039a1976:wasm-function[13790]:0xaf7325)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hbbbdb2452be96bef (wasm://wasm/039a1976:wasm-function[11414]:0xaa26f1)
    at std::panicking::rust_panic_with_hook::h1e6ac5d404b8e31b (wasm://wasm/039a1976:wasm-function[6983]:0x96a7b9)
    at core::panicking::panic_fmt::h87755523850ece9e (wasm://wasm/039a1976:wasm-function[11126]:0xa9bc27)
    at <flv_rs::script::Value as ruffle_core::avm2::flv::FlvValueAvm2Ext>::to_avm2_value::h30221f8c05204fac (wasm://wasm/039a1976:wasm-function[6538]:0x947275)
    at <flv_rs::script::Value as ruffle_core::avm2::flv::FlvValueAvm2Ext>::to_avm2_value::h30221f8c05204fac (wasm://wasm/039a1976:wasm-function[6538]:0x947747)
    at ruffle_web::Ruffle::tick::h928bfc2502629bdc (wasm://wasm/039a1976:wasm-function[1052]:0x31be76)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h78e5658c5c8010a5 (wasm://wasm/039a1976:wasm-function[13727]:0xaf6c58)
    at wasm_bindgen::convert::closures::invoke1_mut::h1719b46e70956c35 (wasm://wasm/039a1976:wasm-function[12367]:0xac02bd)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Apple, Apple M1, OpenGL 4.1)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(PUSH_CONSTANTS | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 31, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)

# Page Info
Page URL: http://www.squeakland.org/resources/audioVisual/movie.jsp?id=16
SWF URL: http://www.squeakland.org/sm/includes/flvplayer.swf

# Browser Info
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
Platform: MacIntel
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-03-02
Channel: nightly
Built: 2024-03-02T00:05:25.161Z
Commit: 8b8d028816e6a04a8ce48e6352a804334bbd6ec2
Is extension: true

# Metadata
width: 400
height: 300
frameRate: 30
numFrames: 1
swfVersion: 9
backgroundColor: #FFFFFF
isActionScript3: true
uncompressedLength: 85652

**Comment by evilpie** [comment]
Fixed by #16563.
