### ISSUE TITLE
Error on https://game286444.konggames.com/games/clarusvictoria/pre-civilization-marble-age/frame/1bb59046-378b-4059-85f9-abee136945e3/

### ISSUE THREAD

**Issue by darin-holloway** [ruffle-rs/ruffle#15510]
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.19.3/src/backend/wgpu_core.rs:3006:5:
wgpu error: Validation Error

Caused by:
    In Device::create_texture
    Dimension Y is zero

Error stack:
```
Error: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.19.3/src/backend/wgpu_core.rs:3006:5:
wgpu error: Validation Error

Caused by:
    In Device::create_texture
    Dimension Y is zero


    at J.n.wbg.__wbg_new_28c511d9baebfa89 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.951b6dbcf877cc86896c.js:1:73906)
    at js_sys::Error::new::ha368c9ce23eebad4 (wasm://wasm/03a2749e:wasm-function[13908]:0xb1523f)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h9c4751e459e0dc59 (wasm://wasm/03a2749e:wasm-function[11514]:0xabfeef)
    at std::panicking::rust_panic_with_hook::h1e6ac5d404b8e31b (wasm://wasm/03a2749e:wasm-function[7071]:0x9863f5)
    at core::panicking::panic_fmt::h87755523850ece9e (wasm://wasm/03a2749e:wasm-function[11224]:0xab9849)
    at core::ops::function::Fn::call::hf4106a1d147d6ddb (wasm://wasm/03a2749e:wasm-function[7395]:0x99ebdb)
    at wgpu::backend::wgpu_core::ErrorSinkRaw::handle_error::h57720170fe96b3b9 (wasm://wasm/03a2749e:wasm-function[5839]:0x915d36)
    at <T as wgpu::context::DynContext>::device_create_texture::h01cd8cd4a732bb85 (wasm://wasm/03a2749e:wasm-function[7780]:0x9b7be2)
    at wgpu::Device::create_texture::he66f3cfebffc592e (wasm://wasm/03a2749e:wasm-function[6217]:0x9392e5)
    at <ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::register_bitmap::hc1339e2f44b8a4e3 (wasm://wasm/03a2749e:wasm-function[2464]:0x658eed)
```
AVM2 stack:
```
    at flash.display::BitmapData/flash::display::BitmapData::draw()
    at com.emibap.textureAtlas::DynamicAtlas$/drawItem()
    at com.emibap.textureAtlas::DynamicAtlas$/fromMovieClipContainer()
    at Asset$/loadAtlas()
    at Asset$/init()
    at Classes$/init()
    at MainMenu()
    at starling.core::Starling/initializeRoot()
    at starling.core::Starling/initialize()
    at starling.core::Starling/onContextCreated()
    at flash.events::EventDispatcher/flash::events::EventDispatcher::dispatchEvent()
    at flash.display::Stage3D/flash::display::Stage3D::requestContext3D_internal()
    at MethodInfo-1906()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Apple, ANGLE Metal Renderer: Apple M2 Pro, Unspecified Version)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(FLOAT32_FILTERABLE | TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | TEXTURE_COMPRESSION_ASTC_HDR | PUSH_CONSTANTS | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)

# Page Info
Page URL: https://game286444.konggames.com/games/clarusvictoria/pre-civilization-marble-age/frame/1bb59046-378b-4059-85f9-abee136945e3/?kongregate_host=www.kongregate.com
SWF URL: https://game286444.konggames.com/gamez/0028/6444/live/ma2.9.8GProt.swf?kongregate_game_version=1506420754

# Browser Info
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
Platform: MacIntel
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-03-10
Channel: nightly
Built: 2024-03-10T00:05:34.457Z
Commit: 2065661874083687135807b622d5972972684967
Is extension: false

# Metadata
width: 800
height: 533
frameRate: 30
numFrames: 2
swfVersion: 34
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 9716767

**Comment by Lord-McSweeney** [comment]
Duplicate of #13946
