### ISSUE TITLE
Error on https://class-room6x.github.io/files/GunMayhem2/

### ISSUE THREAD

**Issue by andrewclark3244** [ruffle-rs/ruffle#15528]
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/49d16f7/wgpu/src/backend/direct.rs:3056:5:
wgpu error: Validation Error

Caused by:
    In Device::create_buffer
    Not enough memory left

Error stack:
```
Error: panicked at /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/49d16f7/wgpu/src/backend/direct.rs:3056:5:
wgpu error: Validation Error

Caused by:
    In Device::create_buffer
    Not enough memory left


    at U.n.wbg.__wbg_new_d258248ed531ff54 (https://class-room6x.github.io/files/ruffle/core.ruffle.b3970bebcf9c117d3dbf.js:1:53228)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h307f95dbfd4e7fe6 (wasm://wasm/032955f2:wasm-function[9716]:0x98c1a1)
    at std::panicking::rust_panic_with_hook::h3aa054d35a0817d7 (wasm://wasm/032955f2:wasm-function[6377]:0x890b79)
    at core::panicking::panic_fmt::h3e1dd3d08288569e (wasm://wasm/032955f2:wasm-function[9525]:0x98716a)
    at core::ops::function::Fn::call::h29d499b8947f9422 (wasm://wasm/032955f2:wasm-function[6554]:0x89b0bf)
    at wgpu::backend::direct::ErrorSinkRaw::handle_error::h0b7e9b7bd4967d5c (wasm://wasm/032955f2:wasm-function[5278]:0x8324bc)
    at <T as wgpu::context::DynContext>::device_create_buffer::h81ba37c770f75660 (wasm://wasm/032955f2:wasm-function[7345]:0x8e44e6)
    at <wgpu::Device as wgpu::util::device::DeviceExt>::create_buffer_init::h481c6961f2e6a8f4 (wasm://wasm/032955f2:wasm-function[1631]:0x4cc6eb)
    at core::cell::once::OnceCell<T>::get_or_try_init::outlined_call::hf4657bef5ad8fe82 (wasm://wasm/032955f2:wasm-function[5872]:0x86db54)
    at ruffle_render_wgpu::surface::Surface::draw_commands_and_copy_to::h125bcc7e8e573fb3 (wasm://wasm/032955f2:wasm-function[1670]:0x4d93b9)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) UHD Graphics 605 (0x00003184) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://class-room6x.github.io/files/GunMayhem2/
SWF URL: https://class-room6x.github.io/files/GunMayhem2/gm2.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0
Platform: Win32
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-10-19
Channel: nightly
Built: 2023-10-19T00:23:16.593Z
Commit: fd4d6921d851e788b1386affae1498e46cda939c
Is extension: false

# Metadata
width: 900
height: 600
frameRate: 35
numFrames: 10
swfVersion: 9
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 10276995

**Comment by andrewclark3244** [comment]
but that error was sort of my fault, computer laggy and stuff

**Comment by andrewclark3244** [comment]
ok end of thread :)
