### ISSUE TITLE
Error on https://sonic.sega.jp/riders/ShootingStarStory/

### ISSUE THREAD

**Issue by AjitForLife** [ruffle-rs/ruffle#15602]
# Error Info
Error name: Error
Error message: panicked at core/src/string/repr.rs:43:22:
string indices out of bounds
Error stack:
```
Error: panicked at core/src/string/repr.rs:43:22:
string indices out of bounds
    at imports.wbg.__wbg_new_28c511d9baebfa89 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/69.js:3393:21)
    at js_sys::Error::new::h088cdeaec8ced39f (wasm://wasm/03a27a66:wasm-function[13906]:0xb150ab)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h35eae935d786d067 (wasm://wasm/03a27a66:wasm-function[11511]:0xabfbbd)
    at std::panicking::rust_panic_with_hook::h1e6ac5d404b8e31b (wasm://wasm/03a27a66:wasm-function[7062]:0x985f43)
    at core::panicking::panic_fmt::h87755523850ece9e (wasm://wasm/03a27a66:wasm-function[11222]:0xab9550)
    at core::option::expect_failed::h65a8ce8e046de7db (wasm://wasm/03a27a66:wasm-function[9796]:0xa5d64e)
    at ruffle_core::string::avm_string::AvmString::new_dependent::h9a5c3e020230206d (wasm://wasm/03a27a66:wasm-function[5158]:0x8c4f21)
    at ruffle_core::avm2::globals::string::substr::h4bb8f178e9dcd5fc (wasm://wasm/03a27a66:wasm-function[2340]:0x6244e4)
    at ruffle_core::avm2::function::Executable::exec::h4770d407d922d395 (wasm://wasm/03a27a66:wasm-function[1043]:0x2f8910)
    at ruffle_core::avm2::object::TObject::call_property::h9ce468a85e4ce06a (wasm://wasm/03a27a66:wasm-function[1573]:0x4a52eb)
```
AVM2 stack:
```
    at String/substr()
    at myAS::textAnimation/randomTxtFnc()
    at myAS::textAnimation/textChange()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) HD Graphics 4000 (0x00000166) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(FLOAT32_FILTERABLE | TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)

# Page Info
Page URL: https://sonic.sega.jp/riders/ShootingStarStory/
SWF URL: https://sonic.sega.jp/riders/ShootingStarStory/swf/top.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-03-16
Channel: nightly
Built: 2024-03-16T00:05:18.708Z
Commit: abf7d3fa208430042c33374025cd34e52bcb3338
Is extension: true

# Metadata
width: 800
height: 720
frameRate: 26
numFrames: 177
swfVersion: 9
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 415645

**Comment by n0samu** [comment]
This should be fixed by #16571.
