### ISSUE TITLE
ruffle desktop crashes when  mouse on overlays it.

### ISSUE THREAD

**Issue by unmellow** [ruffle-rs/ruffle#15617]
### Describe what you were doing

I get this error with the aur package and the linux exxecutible downloaded from ruffle.rs

it mainly occurs when i move my mouse onto the app.

i am using the sway window manager on manjaro linux.

### What does the crash message say?

panicked at desktop/src/gui/controller.rs:234:14:
Surface became unavailable: Timeout

### Ruffle Version

0.1.0-nightly (5d6d097fb1989ac381653270ad8127e7d2f4d4db 2024-03-17)

### Affected platform

Desktop app

### Operating system

Manjaro 23.1.3 (Vulcan) [64-bit]

### Additional information

2024-03-17T22:30:14.007898Z  INFO ruffle_desktop::gui::controller: Using graphics API vulkan on AMD Radeon RX 5700 XT (type: DiscreteGpu)
2024-03-17T22:30:14.037233Z  WARN egui_winit::clipboard: Failed to initialize arboard clipboard: Unknown error while interacting with the clipboard: X11 server connection timed out because it was unreachable    
2024-03-17T22:30:14.037936Z  WARN egui_wgpu::renderer: Detected a linear (sRGBA aware) framebuffer Bgra8UnormSrgb. egui prefers Rgba8Unorm or Bgra8Unorm    
2024-03-17T22:30:14.038420Z  INFO ruffle_desktop::gui::controller: loaded cjk fallback font "FreeSans"
thread 'main' panicked at desktop/src/gui/controller.rs:234:14:
Surface became unavailable: Timeout
stack backtrace:
   0:     0x55b2be928b86 - std::backtrace_rs::backtrace::libunwind::trace::hbee8a7973eeb6c93
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x55b2be928b86 - std::backtrace_rs::backtrace::trace_unsynchronized::hc8ac75eea3aa6899
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55b2be928b86 - std::sys_common::backtrace::_print_fmt::hc7f3e3b5298b1083
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x55b2be928b86 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hbb235daedd7c6190
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55b2be9593e0 - core::fmt::rt::Argument::fmt::h76c38a80d925a410
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/rt.rs:142:9
   5:     0x55b2be9593e0 - core::fmt::write::h3ed6aeaa977c8e45
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/mod.rs:1120:17
   6:     0x55b2be92445f - std::io::Write::write_fmt::h78b18af5775fedb5
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/io/mod.rs:1810:15
   7:     0x55b2be928964 - std::sys_common::backtrace::_print::h5d645a07e0fcfdbb
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x55b2be928964 - std::sys_common::backtrace::print::h85035a511aafe7a8
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x55b2be92a297 - std::panicking::default_hook::{{closure}}::hcce8cea212785a25
  10:     0x55b2be929ff9 - std::panicking::default_hook::hf5fcb0f213fe709a
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:292:9
  11:     0x55b2bd6a5021 - ruffle_desktop::init::{{closure}}::hec96a81a39e5cb77
  12:     0x55b2be92a8b6 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hbc5ccf4eb663e1e5
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/alloc/src/boxed.rs:2029:9
  13:     0x55b2be92a8b6 - std::panicking::rust_panic_with_hook::h095fccf1dc9379ee
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:783:13
  14:     0x55b2be92a602 - std::panicking::begin_panic_handler::{{closure}}::h032ba12139b353db
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:657:13
  15:     0x55b2be929086 - std::sys_common::backtrace::__rust_end_short_backtrace::h9259bc2ff8fd0f76
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:171:18
  16:     0x55b2be92a360 - rust_begin_unwind
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
  17:     0x55b2bd56cbf5 - core::panicking::panic_fmt::h784f20a50eaab275
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
  18:     0x55b2bd56d143 - core::result::unwrap_failed::h03d8a5018196e1cd
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/result.rs:1649:5
  19:     0x55b2bd6a43c5 - ruffle_desktop::gui::controller::GuiController::render::hf23880656ef2b7b6
  20:     0x55b2bd5e5637 - core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut::h47b3281821755d0e
  21:     0x55b2bd5ba531 - winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::pump_events::hbdd08738ba64b199
  22:     0x55b2bd5b3c4b - winit::platform_impl::platform::EventLoop<T>::run_on_demand::hc91db78bd8238d62
  23:     0x55b2bd60325c - ruffle_desktop::app::App::run::h4711916972f0240e
  24:     0x55b2bd6a69b3 - ruffle_desktop::main::h352c8cdb553dd0f3
  25:     0x55b2bd693d53 - std::sys_common::backtrace::__rust_begin_short_backtrace::hcdd862729f4e79aa
[1]    251978 IOT instruction (core dumped)  RUST_BACKTRACE=full Downloads/ruffle/ruffle

**Comment by unmellow** [comment]
i had a faulty harddrive have not tested yet but my linux install has been having issues and so has windows.

**Comment by unmellow** [comment]
can confirm after removing the faulty drive this software works fine
