### ISSUE TITLE
Error on https://sexgamefun.com/sex_games_jolly_friends_fuck_show.php

### ISSUE THREAD

**Issue by guybrz** [ruffle-rs/ruffle#15704]
# Error Info
Error name: TypeError
Error message: Failed to fetch
Error stack:
```
TypeError: Failed to fetch
    at https://www.sexgamefun.com/assets/ruffle/ruffle.js:1:68047
    at Array.forEach (<anonymous>)
    at yi.f.wasm (https://www.sexgamefun.com/assets/ruffle/ruffle.js:1:67974)
    at https://www.sexgamefun.com/assets/ruffle/ruffle.js:1:35888
    at Array.reduce (<anonymous>)
    at yi.e (https://www.sexgamefun.com/assets/ruffle/ruffle.js:1:35865)
    at o (https://www.sexgamefun.com/assets/ruffle/ruffle.js:1:2651)
    at o.next (<anonymous>)
    at https://www.sexgamefun.com/assets/ruffle/ruffle.js:1:2951
    at new Promise (<anonymous>)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://sexgamefun.com/sex_games_jolly_friends_fuck_show.php

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-12
Channel: nightly
Built: 2021-01-12T00:55:17.048Z
Commit: 73d123091014e190f4bc4d8edf98cab2e671cc3a

**Comment by Lord-McSweeney** [comment]
Closing as old Ruffle version and likely network error.
