### ISSUE TITLE
fbbs-spies-on-stage

### ISSUE THREAD

**Issue by markman12345** [ruffle-rs/ruffle#15715]
### Describe what you were doing

https://www.numuki.com/game/fbbs-spies-on-stage/   tryint o play the game

### What does the crash message say?

# Error Info
Error name: Error
Error message: Failed to fetch: https://files.numuki.com/games/the-fresh-beat-band/freshbeat-spiesonstage/targets/main-flash.swf
Error stack:
```
Error: Failed to fetch: https://files.numuki.com/games/the-fresh-beat-band/freshbeat-spiesonstage/targets/main-flash.swf
    at RuffleObject.displayRootMovieDownloadFailedMessage (chrome-extension://fmondcinlnhahjfpibpecccbgkfagpom/dist/ruffle.js?id=35051641664:5704:27)
    at imports.wbg.__wbg_displayRootMovieDownloadFailedMessage_ed4ad3ae9522c8a3 (chrome-extension://fmondcinlnhahjfpibpecccbgkfagpom/dist/69.js:882:14)
    at <ruffle_web::ui::WebUiBackend as ruffle_core::backend::ui::UiBackend>::display_root_movie_download_failed_message::h6b3e77577e6aaeb6 (wasm://wasm/03a1c2a6:wasm-function[13441]:0xb02737)
    at ruffle_core::loader::Loader::root_movie_loader::{{closure}}::h076d5f343f360e25 (wasm://wasm/03a1c2a6:wasm-function[1041]:0x2fac84)
    at <ruffle_web::navigator::WebNavigatorBackend as ruffle_core::backend::navigator::NavigatorBackend>::spawn_future::{{closure}}::haa6dd6e7d50dd1d0 (wasm://wasm/03a1c2a6:wasm-function[1456]:0x4726f8)
    at wasm_bindgen_futures::queue::Queue::new::{{closure}}::h234a3dc3acaace0b (wasm://wasm/03a1c2a6:wasm-function[4090]:0x7f393b)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h0e8be99ba65f19d8 (wasm://wasm/03a1c2a6:wasm-function[12550]:0xadd95a)
    at closure8616 externref shim (wasm://wasm/03a1c2a6:wasm-function[12862]:0xae9603)
    at __wbg_adapter_91 (chrome-extension://fmondcinlnhahjfpibpecccbgkfagpom/dist/69.js:324:10)
    at real (chrome-extension://fmondcinlnhahjfpibpecccbgkfagpom/dist/69.js:281:20)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) UHD Graphics 630 (0x00003E9B) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(FLOAT32_FILTERABLE | TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (1800, 1050, 1)
Player type: Object
SWF URL: targets/main-flash.swf
Param allowScriptAccess: always
Param allowFullScreen: true
Param wmode: direct
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined
Attribute 6: undefined

# Page Info
Page URL: https://files.numuki.com/games/the-fresh-beat-band/freshbeat-spiesonstage/index.html
SWF URL: https://files.numuki.com/games/the-fresh-beat-band/freshbeat-spiesonstage/targets/main-flash.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-03-19
Channel: nightly
Built: 2024-03-19T00:05:39.978Z
Commit: 9dc45b3aced673dde2ee3efe88df58f46e07377e
Is extension: true

# Metadata

### Ruffle Version

2024 03 19

### Affected platform

Browser's extension

### Operating system

windows 11

**Comment by adrian17** [comment]
Looks like they just deleted the Flash content.
From what I see, if you just disable Ruffle extension, you'll get a working non-Flash version of the game. Please try steps like this next time before posting the issue.
