### ISSUE TITLE
Error on https://www.miniplay.com/helpers/game/sandbox.php

### ISSUE THREAD

**Issue by GoodBoy7720** [ruffle-rs/ruffle#15757]
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.19.3/src/backend/wgpu_core.rs:3006:5:
wgpu error: Validation Error

Caused by:
    In Device::create_buffer
    Not enough memory left.

Error stack:
```
Error: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.19.3/src/backend/wgpu_core.rs:3006:5:
wgpu error: Validation Error

Caused by:
    In Device::create_buffer
    Not enough memory left.


    at J.n.wbg.__wbg_new_28c511d9baebfa89 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.3d81f7fc11d1ed5ff982.js:1:73847)
    at js_sys::Error::new::hef550139643a029c (wasm://wasm/03a30cd6:wasm-function[13902]:0xb194cd)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hdd59db8e12749b4f (wasm://wasm/03a30cd6:wasm-function[11487]:0xac2bec)
    at std::panicking::rust_panic_with_hook::h6b00a1542b7e827c (wasm://wasm/03a30cd6:wasm-function[7062]:0x98bca5)
    at core::panicking::panic_fmt::h7d22643b0becf577 (wasm://wasm/03a30cd6:wasm-function[11195]:0xabc516)
    at core::ops::function::Fn::call::hed206ee5db4ff309 (wasm://wasm/03a30cd6:wasm-function[7389]:0x9a47f4)
    at wgpu::backend::wgpu_core::ErrorSinkRaw::handle_error::h7a736fa8cfc6f543 (wasm://wasm/03a30cd6:wasm-function[5834]:0x91b852)
    at <T as wgpu::context::DynContext>::device_create_buffer::hf87ba7a1ebe88910 (wasm://wasm/03a30cd6:wasm-function[8167]:0x9e7678)
    at <wgpu::Device as wgpu::util::device::DeviceExt>::create_buffer_init::h26bbb63c5d7777e9 (wasm://wasm/03a30cd6:wasm-function[2024]:0x595c25)
    at ruffle_render_wgpu::buffer_builder::BufferBuilder::finish::hddeaf5b165f42c3c (wasm://wasm/03a30cd6:wasm-function[8083]:0x9dd107)
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA GeForce GTS 360M (0x00000CB1) Direct3D11 vs_4_1 ps_4_1, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(PUSH_CONSTANTS | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 8192, max_texture_dimension_2d: 8192, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (800, 600, 1)

# Page Info
Page URL: https://www.miniplay.com/helpers/game/sandbox.php?mp_assets=https%3A%2F%2Fs2.minijuegosgratis.com%2F&mp_embed=0&mp_game_id=209864&mp_game_uid=strike-force-heroes-3&mp_game_url=https%3A%2F%2Fwww.miniplay.com%2Fembed%2Fstrike-force-heroes-3&mp_int=1&mp_locale=en_US&mp_player_type=FLASH&mp_player_url=aHR0cHM6Ly93d3cubWluaWp1ZWdvc2dyYXRpcy5jb20vdjMvZ2FtZXMvZ2FtZXMvcHJvZC8yMDk4NjQvc3RyaWtlLWZvcmNlLTMuc3dm&mp_site_https_url=https%3A%2F%2Fwww.miniplay.com%2F&mp_site_name=miniplay.com&mp_site_url=https%3A%2F%2Fwww.miniplay.com%2F&mp_timezone=America%2FHalifax&mp_view_type=
SWF URL: https://www.minijuegosgratis.com/v3/games/games/prod/209864/strike-force-3.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-03-24
Channel: nightly
Built: 2024-03-24T00:06:24.557Z
Commit: 08157a056eba8d3637293d35dae631dd6a48f471
Is extension: false

# Metadata
width: 800
height: 600
frameRate: 30
numFrames: 25
swfVersion: 15
backgroundColor: #999999
isActionScript3: true
uncompressedLength: 22292517

**Comment by GoodBoy7720** [comment]
please assist
