### ISSUE TITLE
Error on https://play.dragonfable.com/game/web.asp

### ISSUE THREAD

**Issue by waelayoub** [ruffle-rs/ruffle#15813]
# Error Info
Error name: Error
Error message: panicked at core/src/library.rs:331:26:
called `Option::unwrap()` on a `None` value
Error stack:
```
Error: panicked at core/src/library.rs:331:26:
called `Option::unwrap()` on a `None` value
    at G.n.wbg.__wbg_new_d258248ed531ff54 (chrome-extension://oakbcaafbicdddpdlhbchhpblmhefngh/dist/339.js:1:53378)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hb809f5d0f30b8e2f (wasm://wasm/03322bd2:wasm-function[9817]:0x9a3837)
    at std::panicking::rust_panic_with_hook::h3aa054d35a0817d7 (wasm://wasm/03322bd2:wasm-function[6450]:0x8a672d)
    at core::panicking::panic_fmt::h3e1dd3d08288569e (wasm://wasm/03322bd2:wasm-function[9617]:0x99e61e)
    at core::panicking::panic::h0f0c05b20da93dd7 (wasm://wasm/03322bd2:wasm-function[9293]:0x990611)
    at ruffle_core::display_object::movie_clip::MovieClip::handle_bytecode_tag::h7e54efd3e61c37e6 (wasm://wasm/03322bd2:wasm-function[595]:0x13dd70)
    at ruffle_core::display_object::movie_clip::MovieClip::run_frame_internal::hef45a1f81e2b55e0 (wasm://wasm/03322bd2:wasm-function[739]:0x25c471)
    at <ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::run_frame_avm1::h685c4730093ccd71 (wasm://wasm/03322bd2:wasm-function[5590]:0x85a8bb)
    at ruffle_web::Ruffle::tick::h8d137fe7e7f3ae7a (wasm://wasm/03322bd2:wasm-function[818]:0x2b9089)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::hc1e33d91dfbb4b62 (wasm://wasm/03322bd2:wasm-function[11948]:0x9f2364)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) UHD Graphics (0x0000A7A8) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://play.dragonfable.com/game/web.asp
SWF URL: https://play.dragonfable.com/game/DFLoader.swf?ver=1653030

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-11-03
Channel: nightly
Built: 2023-11-03T00:14:13.838Z
Commit: 8138b689195dd674f022efa7a8d83b62d34cb9ae
Is extension: true

# Metadata
width: 750
height: 550
frameRate: 24
numFrames: 10
swfVersion: 8
backgroundColor: #660000
isActionScript3: false
uncompressedLength: 6713

**Comment by Lord-McSweeney** [comment]
This was probably fixed by #11005
