### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by greyco1** [ruffle-rs/ruffle#15833]
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.19.3/src/gles/device.rs:752:52:
called `Result::unwrap()` on an `Err` value: "Unable to create texture object"
Error stack:
```
Error: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.19.3/src/gles/device.rs:752:52:
called `Result::unwrap()` on an `Err` value: "Unable to create texture object"
    at J.n.wbg.__wbg_new_28c511d9baebfa89 (https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.d19c4956e0fa3a55e30e.js:1:73847)
    at js_sys::Error::new::h8e593d55ccfdbc76 (wasm://wasm/03a4db42:wasm-function[13912]:0xb210a0)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hc1495a37ebcbc9dc (wasm://wasm/03a4db42:wasm-function[11503]:0xacbc93)
    at std::panicking::rust_panic_with_hook::h5ca5fd3b2064be1b (wasm://wasm/03a4db42:wasm-function[7082]:0x99528d)
    at core::panicking::panic_fmt::h2582bddf31c1c986 (wasm://wasm/03a4db42:wasm-function[11210]:0xac558f)
    at core::result::unwrap_failed::h3688b75fcae89377 (wasm://wasm/03a4db42:wasm-function[8655]:0xa1ac4b)
    at <T as wgpu::context::DynContext>::device_create_texture::h0c78afb9545fe740 (wasm://wasm/03a4db42:wasm-function[7890]:0x9d465c)
    at wgpu::Device::create_texture::h3fd92112584a5c00 (wasm://wasm/03a4db42:wasm-function[6221]:0x9462ee)
    at <ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::create_empty_texture::h2fa1c397222ef3ca (wasm://wasm/03a4db42:wasm-function[6000]:0x9304f2)
    at ruffle_core::display_object::render_base::hcc2145c68c45a07f (wasm://wasm/03a4db42:wasm-function[802]:0x166283)
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (AMD, AMD Radeon RX 5700 XT (0x0000731F) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(FLOAT32_FILTERABLE | TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.67&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1711772068%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F592000%2F592473_MadnessGame_ULTIMATE.swf%3F1507662264%22%2C%22vars%22%3A%7B%22ngio_session_id%22%3A%2239542596.44ad4904fca0661c8caea2c29aad7b6aab417aadaf9805%22%2C%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%22660acf4095e0c%22%2C%22NewgroundsAPI_SessionID%22%3A%22Lmz0gm3i1aaR2Gywn6r4e3f3adcba4416533b42fa64714c54b70e49bd9c3U3z1%22%2C%22NewgroundsAPI_UserName%22%3A%22memelord123445%22%2C%22NewgroundsAPI_UserID%22%3A8407255%2C%22ng_username%22%3A%22memelord123445%22%7D%2C%22width%22%3A850%2C%22height%22%3A530%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F592000%2Fflash_592473_card.webp%3Ff1669742379%22%2C%22warnOnUnsupportedContent%22%3Afalse%7D
SWF URL: https://uploads.ungrounded.net/592000/592473_MadnessGame_ULTIMATE.swf?1507662264

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-03-30
Channel: nightly
Built: 2024-03-30T00:05:09.123Z
Commit: d0e2483bc772d25c5eb7e6774392df44cfa3b88d
Is extension: false

# Metadata
width: 850
height: 530
frameRate: 30
numFrames: 30
swfVersion: 10
backgroundColor: #FFFFFF
isActionScript3: false
uncompressedLength: 20491352

**Comment by Lord-McSweeney** [comment]
Duplicate of #12236
