### ISSUE TITLE
segfault with https://www.free-culture.tk/lfc-loader.swf

### ISSUE THREAD

**Issue by ousia** [ruffle-rs/ruffle#161]
@Herschel,

https://www.free-culture.tk/ contains _Free Culture_, a presentation by Lawrence Lessig.

The loader  (https://www.free-culture.tk/lfc-loader.swf) refers to the actual presentation (https://www.free-culture.tk/lfc-presentation.swf).

Downloading and playing it with the desktop version (Linux, if this might be relevant) seems to segfault the program.

Here you have the backtrace:

```
$ RUST_BACKTRACE=full ./ruffle lfc-loader.swf 
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Expected Object, found Undefined"', src/libcore/result.rs:1165:5
stack backtrace:
   0:     0x55aacd2a2e04 - backtrace::backtrace::libunwind::trace::hda41dbcdfba36aa0
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1:     0x55aacd2a2e04 - backtrace::backtrace::trace_unsynchronized::h1a8d6e1f8cb3f5d4
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2:     0x55aacd2a2e04 - std::sys_common::backtrace::_print_fmt::h610c4127487e10da
                               at src/libstd/sys_common/backtrace.rs:76
   3:     0x55aacd2a2e04 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h0722dc552e01bd1d
                               at src/libstd/sys_common/backtrace.rs:60
   4:     0x55aacd2c9e7c - core::fmt::write::h01edf6dd68a42c9c
                               at src/libcore/fmt/mod.rs:1030
   5:     0x55aacd29fd37 - std::io::Write::write_fmt::hf15985f193f03c04
                               at src/libstd/io/mod.rs:1412
   6:     0x55aacd2a5335 - std::sys_common::backtrace::_print::hd8d5d08a1795e743
                               at src/libstd/sys_common/backtrace.rs:64
   7:     0x55aacd2a5335 - std::sys_common::backtrace::print::hf89a79e3921a2366
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x55aacd2a5335 - std::panicking::default_hook::{{closure}}::h3a8f42beb3bb8ae3
                               at src/libstd/panicking.rs:196
   9:     0x55aacd2a5026 - std::panicking::default_hook::h8f803b0bc31a5c37
                               at src/libstd/panicking.rs:210
  10:     0x55aacd2a5a35 - std::panicking::rust_panic_with_hook::h825f041245da8739
                               at src/libstd/panicking.rs:473
  11:     0x55aacd2a55d2 - std::panicking::continue_panic_fmt::hbe0378e33481e81b
                               at src/libstd/panicking.rs:380
  12:     0x55aacd2a54c6 - rust_begin_unwind
                               at src/libstd/panicking.rs:307
  13:     0x55aacd2c5c2a - core::panicking::panic_fmt::h527855ce0bc891f6
                               at src/libcore/panicking.rs:85
  14:     0x55aacd2c5d27 - core::result::unwrap_failed::ha8b77e6004f0ba38
                               at src/libcore/result.rs:1165
  15:     0x55aacd1c8b71 - ruffle_core::avm1::Avm1::action_set_target::he2fd017ccd64132b
  16:     0x55aacd1b4622 - ruffle_core::avm1::Avm1::do_next_action::hb240d87670c57a0f
  17:     0x55aacd1ac31c - ruffle_core::avm1::Avm1::run_stack_till_empty::hd6510719e766dfed
  18:     0x55aaccee7ac0 - ruffle_core::player::Player<Audio,Renderer,Navigator>::run_actions::hbfd3b55adcee53cf
  19:     0x55aacceea5e8 - ruffle_core::player::Player<Audio,Renderer,Navigator>::tick::h908d9ec688cf3124
  20:     0x55aacceb9c41 - ruffle_desktop::run_player::{{closure}}::ha0b1a02a96c67e4e
  21:     0x55aacceb8622 - winit::platform_impl::platform::x11::EventLoop<T>::run::ha1a5e03fc1b91a65
  22:     0x55aaccf3d41f - winit::platform_impl::platform::EventLoop<T>::run::h74de571adf051db0
  23:     0x55aaccec50fa - winit::event_loop::EventLoop<T>::run::h1fd6e8420b30d0dc
  24:     0x55aaccec7503 - ruffle_desktop::main::h95f196023056692a
  25:     0x55aacceb0183 - std::rt::lang_start::{{closure}}::h333bf746580efc7b
  26:     0x55aacd2a5463 - std::rt::lang_start_internal::{{closure}}::ha04574f12d97cbe2
                               at src/libstd/rt.rs:49
  27:     0x55aacd2a5463 - std::panicking::try::do_call::h7c2a8488f72db90c
                               at src/libstd/panicking.rs:292
  28:     0x55aacd2ad95a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  29:     0x55aacd2a5fed - std::panicking::try::hc3a9b5da4250385d
                               at src/libstd/panicking.rs:271
  30:     0x55aacd2a5fed - std::panic::catch_unwind::hf27600bf8c37809a
                               at src/libstd/panic.rs:394
  31:     0x55aacd2a5fed - std::rt::lang_start_internal::h409d4f2fe51133b0
                               at src/libstd/rt.rs:48
  32:     0x55aaccec7802 - main
  33:     0x7f8b4020311b - __libc_start_main
                               at ../csu/libc-start.c:308
  34:     0x55aacce8e1da - _start
  35:                0x0 - <unknown>
```

Many thanks for your help.

**Comment by ousia** [comment]
@Herschel, sorry, but shouldn’t be this issue labeled _panic_ too?

**Comment by ousia** [comment]
No segfault with Nightly 2020-11-15.

Many thanks for your excellent work.
