### ISSUE TITLE
Error on https://game286444.konggames.com/games/clarusvictoria/pre-civilization-marble-age/frame/a89ed05c-5306-401c-bbbd-f867ea0494b2/

### ISSUE THREAD

**Issue by AnIZeyOasis** [ruffle-rs/ruffle#16108]
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.19.4/src/backend/wgpu_core.rs:3006:5:
wgpu error: Validation Error

Caused by:
    In Device::create_texture
    Dimension Y is zero

Error stack:
```
Error: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.19.4/src/backend/wgpu_core.rs:3006:5:
wgpu error: Validation Error

Caused by:
    In Device::create_texture
    Dimension Y is zero


    at J.n.wbg.__wbg_new_28c511d9baebfa89 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.22214d8f93677f6269cd.js:1:73847)
    at js_sys::Error::new::hdd220ef72a1ea21f (wasm://wasm/03a9687a:wasm-function[13935]:0xb31b9c)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h0b0ddc27f3250923 (wasm://wasm/03a9687a:wasm-function[11527]:0xadb90e)
    at std::panicking::rust_panic_with_hook::h9aabd906218897c3 (wasm://wasm/03a9687a:wasm-function[7110]:0x9a3a37)
    at core::panicking::panic_fmt::h3aff855fe938c13f (wasm://wasm/03a9687a:wasm-function[11243]:0xad53d2)
    at core::ops::function::Fn::call::hf5f90cade0ef61c3 (wasm://wasm/03a9687a:wasm-function[7433]:0x9bc2d9)
    at wgpu::backend::wgpu_core::ErrorSinkRaw::handle_error::had90d7b00951c1c1 (wasm://wasm/03a9687a:wasm-function[5869]:0x93181d)
    at <T as wgpu::context::DynContext>::device_create_texture::h8e8fec58f620d214 (wasm://wasm/03a9687a:wasm-function[7932]:0x9e4688)
    at wgpu::Device::create_texture::hafc31c0e2b96b4f5 (wasm://wasm/03a9687a:wasm-function[6239]:0x954a65)
    at <ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::register_bitmap::hec7dbd0df79b0757 (wasm://wasm/03a9687a:wasm-function[2322]:0x622a29)
```
AVM2 stack:
```
    at flash.display::BitmapData/flash::display::BitmapData::draw()
    at com.emibap.textureAtlas::DynamicAtlas$/drawItem()
    at com.emibap.textureAtlas::DynamicAtlas$/fromMovieClipContainer()
    at Asset$/loadAtlas()
    at Asset$/init()
    at Classes$/init()
    at MainMenu()
    at starling.core::Starling/initializeRoot()
    at starling.core::Starling/initialize()
    at starling.core::Starling/onContextCreated()
    at flash.events::EventDispatcher/flash::events::EventDispatcher::dispatchEvent()
    at flash.display::Stage3D/flash::display::Stage3D::requestContext3D_internal()
    at MethodInfo-1921()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Mesa Intel(R) UHD Graphics 600 (GLK 2), OpenGL ES 3.2)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(FLOAT32_FILTERABLE | TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | PUSH_CONSTANTS | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 128, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)

# Page Info
Page URL: https://game286444.konggames.com/games/clarusvictoria/pre-civilization-marble-age/frame/a89ed05c-5306-401c-bbbd-f867ea0494b2/?kongregate_host=www.kongregate.com
SWF URL: https://game286444.konggames.com/gamez/0028/6444/live/ma2.9.8GProt.swf?kongregate_game_version=1506420754

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-04-24
Channel: nightly
Built: 2024-04-24T00:06:53.855Z
Commit: f30c04e8b4d77bae221b2cfc3ce03faf1f06eeb2
Is extension: false

# Metadata
width: 800
height: 533
frameRate: 30
numFrames: 2
swfVersion: 34
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 9716767

**Comment by MartySVK** [comment]
duplicate of https://github.com/ruffle-rs/ruffle/issues/13946
