### ISSUE TITLE
Error on https://beatablemeat.github.io/games/hexic/

### ISSUE THREAD

**Issue by ArisuSanchez** [ruffle-rs/ruffle#16127]
# Error Info
Error name: Error
Error message: panicked at core/src/library.rs:188:55:
called `Option::unwrap()` on a `None` value
Error stack:
```
Error: panicked at core/src/library.rs:188:55:
called `Option::unwrap()` on a `None` value
    at imports.wbg.__wbg_new_28c511d9baebfa89 (chrome-extension://pipjjbgofgieknlpefmcckdmgaaegban/dist/69.js:3393:21)
    at js_sys::Error::new::hf655a9c3d4762b78 (wasm://wasm/03a88812:wasm-function[13948]:0xb2e209)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h0469bb069fdb7363 (wasm://wasm/03a88812:wasm-function[11540]:0xad7f42)
    at std::panicking::rust_panic_with_hook::h9aabd906218897c3 (wasm://wasm/03a88812:wasm-function[7112]:0x99f6c0)
    at core::panicking::panic_fmt::h3aff855fe938c13f (wasm://wasm/03a88812:wasm-function[11256]:0xad1a4b)
    at core::panicking::panic::h11a2021d92dc1cbb (wasm://wasm/03a88812:wasm-function[10777]:0xaa4c31)
    at core::option::unwrap_failed::h0e0b231623e0d004 (wasm://wasm/03a88812:wasm-function[13401]:0xb1c923)
    at ruffle_core::library::MovieLibrary::character_by_export_name::h40b16564872ab3ae (wasm://wasm/03a88812:wasm-function[5136]:0x8d4c3d)
    at ruffle_core::avm1::globals::sound::attach_sound::hda5023d16d392621 (wasm://wasm/03a88812:wasm-function[1222]:0x3c96d0)
    at ruffle_core::avm1::function::Executable::exec::h28d610c2ad9c1f4e (wasm://wasm/03a88812:wasm-function[885]:0x207806)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA GeForce RTX 3060 Ti (0x00002489) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(FLOAT32_FILTERABLE | TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)
Player type: Object
SWF URL: HexicDeluxe.swf
Param movie: HexicDeluxe.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined

# Page Info
Page URL: https://beatablemeat.github.io/games/hexic/
SWF URL: https://beatablemeat.github.io/games/hexic/HexicDeluxe.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-04-23
Channel: nightly
Built: 2024-04-23T00:06:38.023Z
Commit: 09e932163b2e9b51454d6d176a272d817efd1d2b
Is extension: true

# Metadata
width: 1280
height: 720
frameRate: 60
numFrames: 427
swfVersion: 6
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 2432177

**Comment by Lord-McSweeney** [comment]
```
    pub fn character_by_export_name(
        &self,
        name: AvmString<'gc>,
    ) -> Option<(CharacterId, &Character<'gc>)> {
        if let Some(id) = self.export_characters.get(name, false) {
            return Some((*id, self.characters.get(id).unwrap()));
        }
        None
    }
```
