### ISSUE TITLE
Error on https://flashgames.cx/embed/mario-defender

### ISSUE THREAD

**Issue by Lavender1059** [ruffle-rs/ruffle#16144]
# Error Info
Error name: Error
Error message: panicked at core/src/display_object/movie_clip.rs:432:9:
assertion `left == right` failed: Called replace_movie on a clip with LoaderInfo set
  left: Some(LoaderInfoObject(LoaderInfoObject { ptr: 0x11ee110 }))
 right: None
Error stack:
```
Error: panicked at core/src/display_object/movie_clip.rs:432:9:
assertion `left == right` failed: Called replace_movie on a clip with LoaderInfo set
  left: Some(LoaderInfoObject(LoaderInfoObject { ptr: 0x11ee110 }))
 right: None
    at imports.wbg.__wbg_new_28c511d9baebfa89 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/69.js:3393:21)
    at js_sys::Error::new::hdd220ef72a1ea21f (wasm://wasm/03a96b1e:wasm-function[13935]:0xb31b9c)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h0b0ddc27f3250923 (wasm://wasm/03a96b1e:wasm-function[11527]:0xadb90e)
    at std::panicking::rust_panic_with_hook::h9aabd906218897c3 (wasm://wasm/03a96b1e:wasm-function[7110]:0x9a3a37)
    at core::panicking::panic_fmt::h3aff855fe938c13f (wasm://wasm/03a96b1e:wasm-function[11243]:0xad53d2)
    at core::panicking::assert_failed_inner::hc4f70f3da5729a72 (wasm://wasm/03a96b1e:wasm-function[4925]:0x88bc98)
    at ruffle_core::display_object::movie_clip::MovieClip::replace_with_movie::hb130a2be68a69986 (wasm://wasm/03a96b1e:wasm-function[1445]:0x46fa6c)
    at ruffle_core::loader::Loader::movie_loader::{{closure}}::h30051570cd972128 (wasm://wasm/03a96b1e:wasm-function[958]:0x296a7b)
    at <ruffle_web::navigator::WebNavigatorBackend as ruffle_core::backend::navigator::NavigatorBackend>::spawn_future::{{closure}}::hc4448cdc58137e9b (wasm://wasm/03a96b1e:wasm-function[1444]:0x46ec19)
    at wasm_bindgen_futures::queue::Queue::new::{{closure}}::h4ff844159d54b67e (wasm://wasm/03a96b1e:wasm-function[4079]:0x802923)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Mesa Intel(R) UHD Graphics 600 (GLK 2), OpenGL ES 3.2)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(FLOAT32_FILTERABLE | TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | PUSH_CONSTANTS | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 128, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (918, 630, 1)

# Page Info
Page URL: https://flashgames.cx/embed/mario-defender
SWF URL: http://media.y8.com/system/contents/21213/original/Mario_Defender.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-04-27
Channel: nightly
Built: 2024-04-27T00:06:08.215Z
Commit: 6203f99dd7b59b5f0f70fdbfbb9665abbae46091
Is extension: true

# Metadata
width: 750
height: 480
frameRate: 60
numFrames: 301
swfVersion: 10
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 2668419

**Comment by Lavender1059** [comment]
Games like this one give off that nostalgic feeling to me, owing to having played this when I was younger, but there might not be time to relive those past times if this issue remains, however...

**Comment by Lavender1059** [comment]
See what you can do and holler back if you've got something that could help ;)
