### ISSUE TITLE
Windows 50p Edition - web.archive.org

### ISSUE THREAD

**Issue by Chris-Mingay** [ruffle-rs/ruffle#1615]
Was prompted to submit a crash report so here you go!

# Error Info
Error name: Error
Error message: panicked at 'already mutably borrowed: BorrowError', C:\Users\Michael Welsh\.cargo\registry\src\github.com-1ecc6299db9ec823\gc-arena-0.2.0\src\gc_cell.rs:54:21
Error stack:
```
Error: panicked at 'already mutably borrowed: BorrowError', C:\Users\Michael Welsh\.cargo\registry\src\github.com-1ecc6299db9ec823\gc-arena-0.2.0\src\gc_cell.rs:54:21
    at Object.Y (https://cors.archive.org/cors/emularity_engine_v1/core.ruffle.a8f0d0fd0a0f0ab41246.js:1:20278)
    at __wbg_new_df6e6ab7a65c4c4d (https://cors.archive.org/cors/emularity_engine_v1/ruffle.js:1:31106)
    at https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[1208]:0x227539
    at https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[1363]:0x242e78
    at https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[3581]:0x2eccfd
    at https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[2807]:0x2cf748
    at https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[3878]:0x2f1969
    at https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[3906]:0x2f1e53
    at https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[3781]:0x2f04e6
    at https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[3908]:0x2f1eb7
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://archive.org/details/swf_windows_50p

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36
OS: Win32

# Ruffle Info
Ruffle version: 0.1.0
Ruffle source: undefined

**Comment by Toad06** [comment]
Thank you for reporting this issue.

The issue was related to text fields (see bug report #1580 and commit #1602).
I'm going to close this as the fix is now available in the [Nightly 2020-11-21 release](https://github.com/ruffle-rs/ruffle/releases/tag/nightly-2020-11-21) (hopefully archive.org will soon update their build!).

Thanks again.

**Comment by rugk** [comment]
Same bug with 2020-11-18

Seems Archive.org just has not updated yet.

# Error Info
Error name: Error
Error message: panicked at 'already mutably borrowed: BorrowError', C:\Users\Michael Welsh\.cargo\registry\src\github.com-1ecc6299db9ec823\gc-arena-0.2.0\src\gc_cell.rs:54:21
Error stack:
```
Y@https://cors.archive.org/cors/emularity_engine_v1/core.ruffle.a8f0d0fd0a0f0ab41246.js:1:20278
__wbg_new_df6e6ab7a65c4c4d@https://cors.archive.org/cors/emularity_engine_v1/ruffle.js:1:31106
@https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[1208]:0x227539
@https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[1363]:0x242e78
@https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[3581]:0x2eccfd
@https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[2807]:0x2cf748
@https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[3878]:0x2f1969
@https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[3906]:0x2f1e53
@https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[3781]:0x2f04e6
@https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[3908]:0x2f1eb7
@https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[3308]:0x2e62e3
@https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[2014]:0x29485a
@https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[1641]:0x26b6ac
@https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[1313]:0x23a77c
@https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[1203]:0x2267b9
@https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[1280]:0x234a7c
@https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[3035]:0x2db925
@https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[2837]:0x2d10fd
@https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[707]:0x1a41ed
@https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[740]:0x1afc67
@https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[464]:0x13448d
@https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[2336]:0x2b0b95
@https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[273]:0xf73f
@https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[2343]:0x2b1440
@https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[894]:0x1df500
@https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[391]:0xfdd92
@https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[330]:0xbe101
@https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[1350]:0x240d37
@https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[4067]:0x2f39ec
F@https://cors.archive.org/cors/emularity_engine_v1/core.ruffle.a8f0d0fd0a0f0ab41246.js:1:18113
f@https://cors.archive.org/cors/emularity_engine_v1/core.ruffle.a8f0d0fd0a0f0ab41246.js:1:17378

```

# Player Info
Allows script access: false

# Page Info
Page URL: https://archive.org/details/swf_windows_50p

# Browser Info
Useragent: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:83.0) Gecko/20100101 Firefox/83.0
OS: Linux x86_64

# Ruffle Info
Ruffle version: 0.1.0
Ruffle source: undefined
