### ISSUE TITLE
Error on https://flashmuseum.org/red-blue-balls-treasure-island/

### ISSUE THREAD

**Issue by amaristarks** [ruffle-rs/ruffle#16192]
# Error Info
Error name: Error
Error message: panicked at core/src/display_object/movie_clip.rs:424:9:
assertion `left == right` failed: Called replace_movie on a clip with LoaderInfo set
  left: Some(LoaderInfoObject(LoaderInfoObject { ptr: 0xcf9558 }))
 right: None
Error stack:
```
Error: panicked at core/src/display_object/movie_clip.rs:424:9:
assertion `left == right` failed: Called replace_movie on a clip with LoaderInfo set
  left: Some(LoaderInfoObject(LoaderInfoObject { ptr: 0xcf9558 }))
 right: None
    at J.n.wbg.__wbg_new_28c511d9baebfa89 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.ee356e6681ff2c99f867.js:1:73847)
    at js_sys::Error::new::hdd220ef72a1ea21f (wasm://wasm/03ab1dba:wasm-function[13983]:0xb37155)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h022c91248dc5bdaa (wasm://wasm/03ab1dba:wasm-function[11580]:0xae38b4)
    at std::panicking::rust_panic_with_hook::h9aabd906218897c3 (wasm://wasm/03ab1dba:wasm-function[7154]:0x9a8543)
    at core::panicking::panic_fmt::h3aff855fe938c13f (wasm://wasm/03ab1dba:wasm-function[11297]:0xadd3a8)
    at core::panicking::assert_failed_inner::hc4f70f3da5729a72 (wasm://wasm/03ab1dba:wasm-function[4940]:0x890250)
    at ruffle_core::display_object::movie_clip::MovieClip::replace_with_movie::hd819b270a4d71d60 (wasm://wasm/03ab1dba:wasm-function[1444]:0x47fd50)
    at ruffle_core::loader::Loader::movie_loader::{{closure}}::h7493a5781492d82b (wasm://wasm/03ab1dba:wasm-function[959]:0x2972ab)
    at <ruffle_web::navigator::WebNavigatorBackend as ruffle_core::backend::navigator::NavigatorBackend>::spawn_future::{{closure}}::h2ac03c2fa58c070a (wasm://wasm/03ab1dba:wasm-function[1446]:0x480583)
    at wasm_bindgen_futures::queue::Queue::new::{{closure}}::h4ff844159d54b67e (wasm://wasm/03ab1dba:wasm-function[4094]:0x808078)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) HD Graphics 4600 (0x00000412) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(FLOAT32_FILTERABLE | TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)

# Page Info
Page URL: https://flashmuseum.org/red-blue-balls-treasure-island/
SWF URL: http://redball17levels.com/uploads/4/4/4/9/44495037/randbballsfix.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
![image](https://github.com/ruffle-rs/ruffle/assets/159977249/5381ae02-2c4f-44d4-a19f-621c3e6532b3)

Version: 0.1.0
Name: nightly 2024-05-01
Channel: nightly
Built: 2024-05-01T00:06:39.532Z
Commit: cca6c13710834fffededab150101be617340aa55
Is extension: false

# Metadata
width: 550
height: 400
frameRate: 30
numFrames: 9
swfVersion: 9
backgroundColor: #FFFFFF
isActionScript3: true
uncompressedLength: 3318612

**Comment by amaristarks** [comment]
![image](https://github.com/ruffle-rs/ruffle/assets/159977249/5cbaabfc-c91e-4ddf-8031-20a7d6d08798)
