### ISSUE TITLE
Error on https://flashgames.cx/embed/mario-defender

### ISSUE THREAD

**Issue by Lavender1059** [ruffle-rs/ruffle#16243]
# Error Info
Error name: Error
Error message: panicked at core/src/display_object/movie_clip.rs:424:9:
assertion `left == right` failed: Called replace_movie on a clip with LoaderInfo set
  left: Some(LoaderInfoObject(LoaderInfoObject { ptr: 0x484ec8 }))
 right: None
Error stack:
```
Error: panicked at core/src/display_object/movie_clip.rs:424:9:
assertion `left == right` failed: Called replace_movie on a clip with LoaderInfo set
  left: Some(LoaderInfoObject(LoaderInfoObject { ptr: 0x484ec8 }))
 right: None
    at imports.wbg.__wbg_new_28c511d9baebfa89 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/69.js:3393:21)
    at ruffle_web.wasm.js_sys::Error::new::h2234a378a3d95323 (wasm://wasm/ruffle_web.wasm-03a22efa:wasm-function[14076]:0xb13c7f)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::h14ffa3c2df79f491 (wasm://wasm/ruffle_web.wasm-03a22efa:wasm-function[11609]:0xabf118)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h32c80a64fe4de396 (wasm://wasm/ruffle_web.wasm-03a22efa:wasm-function[7047]:0x97da90)
    at ruffle_web.wasm.core::panicking::panic_fmt::hc7427f902a13f1a9 (wasm://wasm/ruffle_web.wasm-03a22efa:wasm-function[11309]:0xab72d8)
    at ruffle_web.wasm.core::panicking::assert_failed_inner::h0379ad51ee2a5759 (wasm://wasm/ruffle_web.wasm-03a22efa:wasm-function[5118]:0x888a1b)
    at ruffle_web.wasm.ruffle_core::display_object::movie_clip::MovieClip::replace_with_movie::h15566c079dcf65fa (wasm://wasm/ruffle_web.wasm-03a22efa:wasm-function[1546]:0x4b14e2)
    at ruffle_web.wasm.ruffle_core::loader::Loader::movie_loader::{{closure}}::h4c62071d5f5948cd (wasm://wasm/ruffle_web.wasm-03a22efa:wasm-function[1079]:0x334ffa)
    at ruffle_web.wasm.<ruffle_web::navigator::WebNavigatorBackend as ruffle_core::backend::navigator::NavigatorBackend>::spawn_future::{{closure}}::hf7295974e10f49ed (wasm://wasm/ruffle_web.wasm-03a22efa:wasm-function[1543]:0x4af87f)
    at ruffle_web.wasm.wasm_bindgen_futures::queue::Queue::new::{{closure}}::h408b096479b868da (wasm://wasm/ruffle_web.wasm-03a22efa:wasm-function[4300]:0x80b57e)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Mesa Intel(R) UHD Graphics 600 (GLK 2), OpenGL ES 3.2)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(FLOAT32_FILTERABLE | TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | PUSH_CONSTANTS | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 128, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (918, 630, 1)

# Page Info
Page URL: https://flashgames.cx/embed/mario-defender
SWF URL: http://media.y8.com/system/contents/21213/original/Mario_Defender.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-05-07
Channel: nightly
Built: 2024-05-07T00:05:18.326Z
Commit: 5bc55f5f3b28955e61795a77e1e401b8f29719cb
Is extension: true

# Metadata
width: 750
height: 480
frameRate: 60
numFrames: 301
swfVersion: 10
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 2668419

**Comment by Lavender1059** [comment]
Games like this give me huge nostalgia vibes

**Comment by Lavender1059** [comment]
If something can be done about the "panicked at core/src/display_object/movie_clip.rs:424:9:" thing, then it may entirely be possible to play this game again

**Comment by Lavender1059** [comment]
This game does work on Ruffle's web demo thing, but some of the text doesn't seem to be loaded in full, having their, erm, I'll say "outline" missing, but it's still fine nonetheless
