### ISSUE TITLE
Error on http://192.168.21.83/GUI.swf

### ISSUE THREAD

**Issue by Nkaati** [ruffle-rs/ruffle#16278]
# Error Info
Error name: Error
Error message: panicked at core/src/avm2/amf.rs:147:18:
called `Result::unwrap()` on an `Err` value: Error: Unknown Property: '-1'.
Error stack:
```
Error: panicked at core/src/avm2/amf.rs:147:18:
called `Result::unwrap()` on an `Err` value: Error: Unknown Property: '-1'.
    at imports.wbg.__wbg_new_28c511d9baebfa89 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/69.js:3399:21)
    at ruffle_web.wasm.js_sys::Error::new::h2234a378a3d95323 (wasm://wasm/ruffle_web.wasm-03a26ca2:wasm-function[14082]:0xb144ee)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::h14ffa3c2df79f491 (wasm://wasm/ruffle_web.wasm-03a26ca2:wasm-function[11610]:0xabfb6f)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h32c80a64fe4de396 (wasm://wasm/ruffle_web.wasm-03a26ca2:wasm-function[7037]:0x97f75e)
    at ruffle_web.wasm.core::panicking::panic_fmt::hc7427f902a13f1a9 (wasm://wasm/ruffle_web.wasm-03a26ca2:wasm-function[11312]:0xab7f8b)
    at ruffle_web.wasm.core::result::unwrap_failed::h8c7a47192e7f0267 (wasm://wasm/ruffle_web.wasm-03a26ca2:wasm-function[8966]:0xa11948)
    at ruffle_web.wasm.ruffle_core::avm2::amf::serialize_value::h36692213098d1fb0 (wasm://wasm/ruffle_web.wasm-03a26ca2:wasm-function[1121]:0x35799a)
    at ruffle_web.wasm.ruffle_core::avm2::amf::get_or_create_element::hdb4623f71c89dfe3 (wasm://wasm/ruffle_web.wasm-03a26ca2:wasm-function[2799]:0x6b2f97)
    at ruffle_web.wasm.ruffle_core::avm2::amf::recursive_serialize::hccf2a254ad7f46a8 (wasm://wasm/ruffle_web.wasm-03a26ca2:wasm-function[1514]:0x49e398)
    at ruffle_web.wasm.ruffle_core::avm2::globals::flash::net::shared_object::new_lso::hd9031b339f83cd25 (wasm://wasm/ruffle_web.wasm-03a26ca2:wasm-function[2765]:0x6a95c2)
```
AVM2 stack:
```
    at flash.net::SharedObject/flash::net::SharedObject::flush()
    at com.rtlogic.utils::ObjectPersistence/save()
    at com.rtlogic.frameworks.mdi.containers::WindowTabContainer/persistWindowState()
    at flash.events::EventDispatcher/flash::events::EventDispatcher::dispatchEvent()
    at mx.core::UIComponent/dispatchEvent()
    at mx.core::Container/http://www.adobe.com/2006/flex/mx/internal::childAdded()
    at mx.core::Container/addChildAt()
    at mx.core::Container/addChild()
    at com.rtlogic.frameworks.mdi.containers::WindowTabContainer/addWindow()
    at com.rtlogic.frameworks.mdi.managers::PropertyNavigatorManager/AddPropertyNavigatorAtLocation()
    at com.rtlogic.frameworks.mdi.managers::PropertyNavigatorManager/AddPropertyNavigator()
    at application::T3MDIApplication/initializeDefaultWindows()
    at application::T3MDIApplication/onComplete()
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) Iris(R) Xe Graphics (0x000046A6) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(FLOAT32_FILTERABLE | TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)

# Page Info
Page URL: chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/player.html#http://192.168.21.83/GUI.swf
SWF URL: http://192.168.21.83/GUI.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-05-10
Channel: nightly
Built: 2024-05-10T00:05:55.188Z
Commit: 8eaede1c2cbbab1555b8ac71ad8b46401b0b232a
Is extension: true

# Metadata
width: 500
height: 375
frameRate: 24
numFrames: 2
swfVersion: 9
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 7973735

**Comment by n0samu** [comment]
Hi @Nkaati, could you tell us what content you were trying to play/use when the error occurred? And provide a copy of the files if possible?

**Comment by Nkaati** [comment]
Hi, this is the main interface to a Kratos RF Modem, I was hoping that with Ruffle it was possible to run this interface.
This seems to be the main SWF file embedded on the index page when connecting to the device. Let me know if there is any other info I can try to find to help.
[GUI_swf.zip](https://github.com/ruffle-rs/ruffle/files/15292419/GUI_swf.zip)

**Comment by n0samu** [comment]
Hi, I'm unable to reproduce the panic with just the single SWF. Running this type of sophisticated application may be beyond Ruffle's capabilities at the moment. I'd suggest your organization look into HARMAN's packaged browser solution for running Flash content.
