### ISSUE TITLE
Ruffle crash on launch Arch linux (Vulkan)

### ISSUE THREAD

**Issue by Nova-archx86** [ruffle-rs/ruffle#16304]
### Describe what you were doing

Just opened the application and waited about half a second

### What does the crash message say?

panicked at desktop/src/gui/controller.rs:230:14:
Surface became unavailable: Timeout

### Ruffle Version

0.1.0-nightly (3d412c955ff2a84f02de7ef17be9eba70f3da5d2 2024-05-11)

### Affected platform

Desktop app

### Operating system

Arch Linux Rolling Release [64-bit]

### Additional information

Kernel version: Linux 6.8.9-arch1-2
CPU: AMD Ryzen 5 3600 (6 cores)
GPU: Radeon RX 7600 (8GB) (Vulkan)

Although this report is for the ruffle-nightly-bin aur package, I've experienced the same issue when compiling the source from ruffle-git (ruffle-adapter-git too) as well as when downloading the official linux binary on the website.

Logs:
2024-05-13T05:28:57.762423Z  WARN wgpu_hal::vulkan::instance: Unable to find extension: VK_EXT_swapchain_colorspace    
2024-05-13T05:28:57.781805Z  INFO ruffle_desktop::gui::controller: Using preferred backend Vulkan
2024-05-13T05:28:57.787678Z  INFO ruffle_desktop::gui::controller: Using graphics API vulkan on AMD Radeon RX 7600 (type: DiscreteGpu)
2024-05-13T05:28:57.810688Z  WARN egui_wgpu::renderer: Detected a linear (sRGBA aware) framebuffer Bgra8UnormSrgb. egui prefers Rgba8Unorm or Bgra8Unorm    
thread 'main' panicked at desktop/src/gui/controller.rs:230:14:
Surface became unavailable: Timeout
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)

**Comment by Nova-archx86** [comment]
From what I've tested ruffle seems to work just fine when only using opengl... Im wondering if this might be a vulkan issue?
