### ISSUE TITLE
Error on https://web.archive.org/web/20120423103844/http://icanbe.barbie.com/en_US/games/years-of-careers.html

### ISSUE THREAD

**Issue by BlessedJael** [ruffle-rs/ruffle#16331]
# Error Info
Error name: Error
Error message: Failed to fetch: http://icanbe.barbie.com/Resources/Games_data/years_of_careers/HeritageGame.swf
Error stack:
```
Error: Failed to fetch: http://icanbe.barbie.com/Resources/Games_data/years_of_careers/HeritageGame.swf
    at ht.displayRootMovieDownloadFailedMessage (https://web-static.archive.org/_static/js/ruffle/ruffle.js:2:381767)
    at H.n.wbg.__wbg_displayRootMovieDownloadFailedMessage_ed4ad3ae9522c8a3 (https://web-static.archive.org/_static/js/ruffle/core.ruffle.67bc37f4e63c43ff9c64.js:1:7518)
    at <ruffle_web::ui::WebUiBackend as ruffle_core::backend::ui::UiBackend>::display_root_movie_download_failed_message::h823ef5c443b6b226 (wasm://wasm/035cabca:wasm-function[12886]:0xa53c4c)
    at ruffle_core::loader::Loader::root_movie_loader::{{closure}}::h3d99367fb670b5df (wasm://wasm/035cabca:wasm-function[955]:0x344e02)
    at <ruffle_web::navigator::WebNavigatorBackend as ruffle_core::backend::navigator::NavigatorBackend>::spawn_future::{{closure}}::h5c663d37bec393c0 (wasm://wasm/035cabca:wasm-function[1264]:0x42cc07)
    at wasm_bindgen_futures::queue::Queue::new::{{closure}}::hf3d45b9fcb0286e9 (wasm://wasm/035cabca:wasm-function[3710]:0x771a26)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h4b99ccc6980aa0f1 (wasm://wasm/035cabca:wasm-function[11656]:0xa1f5c6)
    at closure5566 externref shim (wasm://wasm/035cabca:wasm-function[11973]:0xa2ad6a)
    at E (https://web-static.archive.org/_static/js/ruffle/core.ruffle.67bc37f4e63c43ff9c64.js:1:3204)
    at c (https://web-static.archive.org/_static/js/ruffle/core.ruffle.67bc37f4e63c43ff9c64.js:1:2503)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) UHD Graphics (0x00009A78) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 31, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }
Player type: Object
SWF URL: /Resources/Games_data/years_of_careers/HeritageGame.swf
Param menu: false
Param bgcolor: #FFFFFF
Param quality: high
Param align: middle
Param wmode: transparent
Param allowScriptAccess: SameDomain
Param flashvars: config=/Resources/games_data/years_of_careers/en_US/game_config.xmlx&uid=153&oauthKey=normal&oauthSecret=user&language=en_US&path=/Resources/Games_data/years_of_careers
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined

# Page Info
Page URL: https://web.archive.org/web/20120423103844/http://icanbe.barbie.com/en_US/games/years-of-careers.html
SWF URL: http://icanbe.barbie.com/Resources/Games_data/years_of_careers/HeritageGame.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-01-08
Channel: nightly
Built: 2024-01-08T00:15:28.895Z
Commit: 47db84473a639c405289bb86ce238a83af574137
Is extension: false

# Metadata

**Comment by danielhjacobs** [comment]
The actual Flash content was never archived on the Internet Archive, closing as can't fix, hoping to improve the error message soon.
