### ISSUE TITLE
Error on https://www.gameflare.com/embed/vision-by-proxy/

### ISSUE THREAD

**Issue by Galladegamer1** [ruffle-rs/ruffle#16343]
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.19.4/src/backend/wgpu_core.rs:3006:5:
wgpu error: Validation Error

Caused by:
    In CommandEncoder::copy_texture_to_texture
    Copy error
    Copy of Y 4294967295..449 would end up overrunning the bounds of the Destination texture of Y size 450

Error stack:
```
Error: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.19.4/src/backend/wgpu_core.rs:3006:5:
wgpu error: Validation Error

Caused by:
    In CommandEncoder::copy_texture_to_texture
    Copy error
    Copy of Y 4294967295..449 would end up overrunning the bounds of the Destination texture of Y size 450


    at J.n.wbg.__wbg_new_28c511d9baebfa89 (https://www.gameflare.com/emulators/ruffle/core.ruffle.e55f7bfe82f42d8208a0.js:1:74263)
    at ruffle_web.wasm.js_sys::Error::new::h2e3218c7b6976bb5 (wasm://wasm/ruffle_web.wasm-03a1331a:wasm-function[14065]:0xb0fd83)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::he5ab5fef274a3c75 (wasm://wasm/ruffle_web.wasm-03a1331a:wasm-function[11609]:0xabb75a)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h32c80a64fe4de396 (wasm://wasm/ruffle_web.wasm-03a1331a:wasm-function[7038]:0x97919f)
    at ruffle_web.wasm.core::panicking::panic_fmt::hc7427f902a13f1a9 (wasm://wasm/ruffle_web.wasm-03a1331a:wasm-function[11309]:0xab3b15)
    at ruffle_web.wasm.core::ops::function::Fn::call::hc55b2486ae3a5715 (wasm://wasm/ruffle_web.wasm-03a1331a:wasm-function[8057]:0x9c19a9)
    at ruffle_web.wasm.wgpu::backend::wgpu_core::ErrorSinkRaw::handle_error::hc39ac16adade08fc (wasm://wasm/ruffle_web.wasm-03a1331a:wasm-function[5949]:0x918da6)
    at ruffle_web.wasm.wgpu::backend::wgpu_core::ContextWgpuCore::handle_error::hfc66cc2cd357662c (wasm://wasm/ruffle_web.wasm-03a1331a:wasm-function[3176]:0x70f46a)
    at ruffle_web.wasm.<T as wgpu::context::DynContext>::command_encoder_copy_texture_to_texture::h244d465bd6575fd8 (wasm://wasm/ruffle_web.wasm-03a1331a:wasm-function[10803]:0xa84f36)
    at ruffle_web.wasm.wgpu::CommandEncoder::copy_texture_to_texture::h478745349eff813b (wasm://wasm/ruffle_web.wasm-03a1331a:wasm-function[10390]:0xa6461c)
```
AVM2 stack:
```
    at flash.display::BitmapData/flash::display::BitmapData::applyFilter()
    at VisionByProxy2/constantUpdate()
    at flash.events::EventDispatcher/flash::events::EventDispatcher::dispatchEvent()
    at flash.utils::Timer/onUpdate()
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA GeForce GTX 1650 (0x00001F82) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(FLOAT32_FILTERABLE | TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)

# Page Info
Page URL: https://www.gameflare.com/embed/vision-by-proxy/
SWF URL: https://data.gameflare.com/games/1989/gCNjnsfZmg6KnK.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-05-16
Channel: nightly
Built: 2024-05-16T00:05:26.436Z
Commit: ef1f6ce29bb0af881184eb1cd9c499c4ccc6e1ca
Is extension: false

# Metadata
width: 650
height: 450
frameRate: 30
numFrames: 2
swfVersion: 10
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 7807481

**Comment by Galladegamer1** [comment]
I haven't played this game in over a decade, so I hope this is solved soon
