### ISSUE TITLE
Error on https://archive.org/details/helicoptergame_flash

### ISSUE THREAD

**Issue by jasondavies** [ruffle-rs/ruffle#1638]
# Error Info
Error name: Error
Error message: panicked at 'already mutably borrowed: BorrowError', C:\Users\Michael Welsh\.cargo\registry\src\github.com-1ecc6299db9ec823\gc-arena-0.2.0\src\gc_cell.rs:54:21
Error stack:
```
Error: panicked at 'already mutably borrowed: BorrowError', C:\Users\Michael Welsh\.cargo\registry\src\github.com-1ecc6299db9ec823\gc-arena-0.2.0\src\gc_cell.rs:54:21
    at Object.Y (https://cors.archive.org/cors/emularity_engine_v1/core.ruffle.a8f0d0fd0a0f0ab41246.js:1:20278)
    at __wbg_new_df6e6ab7a65c4c4d (https://cors.archive.org/cors/emularity_engine_v1/ruffle.js:1:31106)
    at https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[1208]:0x227539
    at https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[1363]:0x242e78
    at https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[3581]:0x2eccfd
    at https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[2807]:0x2cf748
    at https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[3878]:0x2f1969
    at https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[3906]:0x2f1e53
    at https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[3781]:0x2f04e6
    at https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[3908]:0x2f1eb7
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://archive.org/details/helicoptergame_flash

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.67 Safari/537.36
OS: MacIntel

# Ruffle Info
Ruffle version: 0.1.0
Ruffle source: undefined

**Comment by Toad06** [comment]
Thank you for reporting this issue.

We already have a bug report for this game (#1607) and I'm confident this bug is already fixed in the [Nightly 2020-11-21 release](https://github.com/ruffle-rs/ruffle/releases/tag/nightly-2020-11-21) (archive.org will have to update their build).

Thanks again!
