### ISSUE TITLE
Audio only, video broken on certain flash videos (in Archive.org items)

### ISSUE THREAD

**Issue by mekarpeles** [ruffle-rs/ruffle#1653]
Helping debug Internet Archive's flash setup:

Item: https://archive.org/details/moresexthanme (apologies for the crude example)

audio works, video does not show up.

Linux (debian 10) + Chrome Version 87.0.4280.66 (Official Build) (64-bit) 

```
core.ruffle.0fd06c20088dfaa8135b.js:1 panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create framebuffer"', render/webgl/src/lib.rs:739:35
```

Possibly also related:
```
Unable to change audio state: TypeError: Cannot read property 'cwrap' of null
    at Emulator.setMute (loader.js?v=bebf8b8b:1357)
    at Emulator.mute (loader.js?v=bebf8b8b:1342)
    at Function.value (play8.min.js?v=bebf8b8b:2)
    at moresexthanme:2210
    at HTMLDocument.<anonymous> (play8.min.js?v=bebf8b8b:2)
    at c (jquery-1.10.2.min.js?v1.10.2:4)
    at Object.fireWith [as resolveWith] (jquery-1.10.2.min.js?v1.10.2:4)
    at Function.ready (jquery-1.10.2.min.js?v1.10.2:4)
    at HTMLDocument.q (jquery-1.10.2.min.js?v1.10.2:4)
```
![2020-11-21-213013_1600x900_scrot](https://user-images.githubusercontent.com/978325/99895980-452cea80-2c41-11eb-94ba-4936efc34e7a.png)

**Comment by parkerlreed** [comment]
As noted in the Discord,

Check your chrome://gpu to make sure WebGL is listed as enabled. You may need a couple extra flags to get everything working.

**Comment by darkdragon-001** [comment]
I am having the same problem with the game on https://www.playing-with-fire-game.com/ in Google Chrome. In Firefox both, this game and the one linked in the original question are working fine. WebGL is enabled and listed enabled (hardware accelerated).

Error Info:
<details>

# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:460:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:460:50
    at Object.$ (chrome-extension://jbkdnjeggncfecacmlbcdcmhmohkgcdf/dist/core.ruffle.js:1:20276)
    at __wbg_new_df6e6ab7a65c4c4d (chrome-extension://jbkdnjeggncfecacmlbcdcmhmohkgcdf/dist/ruffle.js:1:31347)
    at chrome-extension://jbkdnjeggncfecacmlbcdcmhmohkgcdf/dist/85f5e4a29d83ee43a391.module.wasm:wasm-function[1201]:0x22757d
    at chrome-extension://jbkdnjeggncfecacmlbcdcmhmohkgcdf/dist/85f5e4a29d83ee43a391.module.wasm:wasm-function[1358]:0x2436eb
    at chrome-extension://jbkdnjeggncfecacmlbcdcmhmohkgcdf/dist/85f5e4a29d83ee43a391.module.wasm:wasm-function[3589]:0x2eee47
    at chrome-extension://jbkdnjeggncfecacmlbcdcmhmohkgcdf/dist/85f5e4a29d83ee43a391.module.wasm:wasm-function[2813]:0x2d15fd
    at chrome-extension://jbkdnjeggncfecacmlbcdcmhmohkgcdf/dist/85f5e4a29d83ee43a391.module.wasm:wasm-function[3884]:0x2f3a65
    at chrome-extension://jbkdnjeggncfecacmlbcdcmhmohkgcdf/dist/85f5e4a29d83ee43a391.module.wasm:wasm-function[3913]:0x2f3f9a
    at chrome-extension://jbkdnjeggncfecacmlbcdcmhmohkgcdf/dist/85f5e4a29d83ee43a391.module.wasm:wasm-function[3789]:0x2f2642
    at chrome-extension://jbkdnjeggncfecacmlbcdcmhmohkgcdf/dist/85f5e4a29d83ee43a391.module.wasm:wasm-function[3914]:0x2f3fd0
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: https://www.playing-with-fire-game.com/playing-with-fire-game.swf
Param movie: https://www.playing-with-fire-game.com/playing-with-fire-game.swf
Param menu: false
Param quality: high
Param bgcolor: #000000
Attribute 0: [object Attr]
Attribute 1: [object Attr]
Attribute 2: [object Attr]
Attribute 3: [object Attr]
Attribute 4: [object Attr]

# Page Info
Page URL: https://www.playing-with-fire-game.com/

# Browser Info
Useragent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Ruffle version: 0.1.0
Ruffle source: undefined
</details>

**Comment by parkerlreed** [comment]
@darkdragon-001 Are you also on Linux? This is working for me with ruffle extension and Chromium.

Try these flags

```
$ cat ~/.config/chromium-flags.conf 
--ignore-gpu-blocklist
--enable-gpu-rasterization
--enable-native-gpu-memory-buffers
--enable-zero-copy
--disable-gpu-driver-bug-workarounds
--use-gl=desktop
```

**Comment by ousia** [comment]
@mekarpeles, using extension 2021-01-28 for Firefox on Linux displays the video for me.

Could you check it again?
