### ISSUE TITLE
Error on https://play.myclubpengu.in/

### ISSUE THREAD

**Issue by diegoa23** [ruffle-rs/ruffle#16538]
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.20.0/src/gles/device.rs:775:52:
called `Result::unwrap()` on an `Err` value: "Unable to create texture object"
Error stack:
```
Error: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.20.0/src/gles/device.rs:775:52:
called `Result::unwrap()` on an `Err` value: "Unable to create texture object"
    at J.n.wbg.__wbg_new_28c511d9baebfa89 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.2cb72f1010853c617c50.js:1:74960)
    at ruffle_web.wasm.js_sys::Error::new::hb829810012112a2e (wasm://wasm/ruffle_web.wasm-0336be92:wasm-function[12794]:0x9f0895)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::h7965d11526a58f9a (wasm://wasm/ruffle_web.wasm-0336be92:wasm-function[10416]:0x9a9dd6)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h32c80a64fe4de396 (wasm://wasm/ruffle_web.wasm-0336be92:wasm-function[6512]:0x8759b3)
    at ruffle_web.wasm.core::panicking::panic_fmt::hc7427f902a13f1a9 (wasm://wasm/ruffle_web.wasm-0336be92:wasm-function[10155]:0x9a2a88)
    at ruffle_web.wasm.core::result::unwrap_failed::h8c7a47192e7f0267 (wasm://wasm/ruffle_web.wasm-0336be92:wasm-function[8263]:0x901245)
    at ruffle_web.wasm.<T as wgpu::context::DynContext>::device_create_texture::h6327af07a273051e (wasm://wasm/ruffle_web.wasm-0336be92:wasm-function[7508]:0x8bdd09)
    at ruffle_web.wasm.wgpu::Device::create_texture::h4b29db4603aabb38 (wasm://wasm/ruffle_web.wasm-0336be92:wasm-function[5967]:0x8463fd)
    at ruffle_web.wasm.<ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::register_bitmap::h6e40a8c82982cbc6 (wasm://wasm/ruffle_web.wasm-0336be92:wasm-function[2152]:0x56c43b)
    at ruffle_web.wasm.<ruffle_core::library::MovieLibrarySource as ruffle_render::bitmap::BitmapSource>::bitmap_handle::he94d1ce5df428182 (wasm://wasm/ruffle_web.wasm-0336be92:wasm-function[1317]:0x3c658a)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (AMD, AMD Radeon(TM) Graphics (0x0000164C) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: "WebGL 2.0 (OpenGL ES"
Adapter Driver Info: "3.0 Chromium)"
Enabled features: Features(TEXTURE_COMPRESSION_BC | FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(DEPTH32FLOAT_STENCIL8 | PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_color_attachments: 8, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)

# Page Info
Page URL: https://play.myclubpengu.in/
SWF URL: https://play.myclubpengu.in/ninja/media/flash/game.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-05-31
Channel: nightly
Built: 2024-05-31T00:05:04.612Z
Commit: 0b2881c8a61bee4604bcbdfd83d54233b82a0633
Is extension: false

# Metadata
width: 760
height: 480
frameRate: 24
numFrames: 1
swfVersion: 15
backgroundColor: #FFFFFF
isActionScript3: false
uncompressedLength: 3549

**Comment by 7yyutttytyt** [comment]
# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (AMD, AMD Radeon(TM) Graphics (0x0000164C) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: "WebGL 2.0 (OpenGL ES 3.0 Chromium)"
Enabled features: Features(TEXTURE_COMPRESSION_BC | FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES)
Available features: Features(DEPTH32FLOAT_STENCIL8 | TEXTURE_COMPRESSION_BC_SLICED_3D | PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_color_attachments: 8, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)
Player type: Object
SWF URL: https://pelikone.fi/games/files/gbj1u3Lhx48ecZQ.swf
Param wmode: gpu
Param allowscriptaccess: always
Param bgcolor: 000000
Param base: https://pelikone.fi/games/files/4987/
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined
Attribute 6: undefined
Attribute 7: undefined

# Page Info
Page URL: https://pelikone.fi/pelit/autopelit/Stuntrider/4987?archive=true
SWF URL: https://pelikone.fi/games/files/gbj1u3Lhx48ecZQ.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-12-21
Channel: nightly
Built: 2024-12-21T00:06:12.256Z
Commit: 412da7787714c9cf603cf0105c5b8f7b1bd99e41
Is extension: true

# Metadata
width: 500
height: 350
frameRate: 25
numFrames: 23
swfVersion: 8
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 2664481
