### ISSUE TITLE
Error on https://www.gameslol.net/anime-battle-2-2-1290.html

### ISSUE THREAD

**Issue by mehdi7457** [ruffle-rs/ruffle#16569]
# Error Info
Error name: Error
Error message: panicked at core/src/string/repr.rs:43:22:
string indices out of bounds
Error stack:
```
Error: panicked at core/src/string/repr.rs:43:22:
string indices out of bounds
    at J.n.wbg.__wbg_new_28c511d9baebfa89 (https://www.gameslol.net/data/ruffle/core.ruffle.fab3c72643c8c47b69cf.js:1:74263)
    at ruffle_web.wasm.js_sys::Error::new::h2234a378a3d95323 (wasm://wasm/ruffle_web.wasm-03a364ba:wasm-function[14081]:0xb180a9)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::h14ffa3c2df79f491 (wasm://wasm/ruffle_web.wasm-03a364ba:wasm-function[11616]:0xac3a54)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h32c80a64fe4de396 (wasm://wasm/ruffle_web.wasm-03a364ba:wasm-function[7050]:0x98229b)
    at ruffle_web.wasm.core::panicking::panic_fmt::hc7427f902a13f1a9 (wasm://wasm/ruffle_web.wasm-03a364ba:wasm-function[11319]:0xabbea9)
    at ruffle_web.wasm.core::panicking::panic_display::h57441543e669293c (wasm://wasm/ruffle_web.wasm-03a364ba:wasm-function[11028]:0xaa5f82)
    at ruffle_web.wasm.core::option::expect_failed::h44ad93b37e925be9 (wasm://wasm/ruffle_web.wasm-03a364ba:wasm-function[12004]:0xad4192)
    at ruffle_web.wasm.ruffle_core::string::interner::AvmStringInterner::substring::hf3f542dfa39c11b9 (wasm://wasm/ruffle_web.wasm-03a364ba:wasm-function[6845]:0x974784)
    at ruffle_web.wasm.ruffle_core::avm2::globals::string::substr::h37f2142277d3a78a (wasm://wasm/ruffle_web.wasm-03a364ba:wasm-function[2774]:0x6ad138)
    at ruffle_web.wasm.ruffle_core::avm2::function::Executable::exec::haac3dce50c7c1222 (wasm://wasm/ruffle_web.wasm-03a364ba:wasm-function[1049]:0x3160dd)
```
AVM2 stack:
```
    at String/substr()
    at game2016::RoleParsing$/getKeyString()
    at SystemComponent::SystemGameRole/getSkillName()
    at SystemComponent::SystemGameRole/Down()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) HD Graphics 630 (0x0000591B) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(FLOAT32_FILTERABLE | TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)

# Page Info
Page URL: https://www.gameslol.net/anime-battle-2-2-1290.html
SWF URL: https://www.gameslol.net/data/animebattle22/game.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 OPR/109.0.0.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-05-12
Channel: nightly
Built: 2024-05-12T00:05:54.705Z
Commit: 3d412c955ff2a84f02de7ef17be9eba70f3da5d2
Is extension: false

# Metadata
width: 700
height: 500
frameRate: 32
numFrames: 1
swfVersion: 19
backgroundColor: #FFFFFF
isActionScript3: true
uncompressedLength: 6157688

**Comment by adrian17** [comment]
This should be fixed on the next release of Ruffle (we'll create one within the next couple hours), so from tomorrow it's on https://www.gameslol.net to update.
