### ISSUE TITLE
Error on https://gamaverse.com/c/f/g/madness-accelerant/

### ISSUE THREAD

**Issue by Ow2ks** [ruffle-rs/ruffle#16703]
# Error Info
Error name: TypeError
Error message: WebAssembly.compileStreaming(): Argument 0 must be provided and must be a Response or Response promise
Error stack:
```
TypeError: WebAssembly.compileStreaming(): Argument 0 must be provided and must be a Response or Response promise
    at https://gamaverse.com/tmp/ruffle.js:1:32421
    at e (https://gamaverse.com/tmp/ruffle.js:1:32911)
    at <anonymous>
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://gamaverse.com/c/f/g/madness-accelerant/

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) 37abc/2.0.6.16 Chrome/60.0.3112.113 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-02-21
Channel: nightly
Built: 2021-02-21T00:20:18.629Z
Commit: eb173f06ca0918e2d2b488cd14849152db607e51

**Comment by Lord-McSweeney** [comment]
Not an issue with Ruffle
