### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by MauLang18** [ruffle-rs/ruffle#16799]
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.20.1/src/backend/wgpu_core.rs:2996:5:
wgpu error: Validation Error

Caused by:
    In Device::create_buffer
    Not enough memory left.

Error stack:
```
Error: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.20.1/src/backend/wgpu_core.rs:2996:5:
wgpu error: Validation Error

Caused by:
    In Device::create_buffer
    Not enough memory left.


    at n.wbg.__wbg_new_28c511d9baebfa89 (https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.a245cc768ffed8421768.js:1:79390)
    at ruffle_web.wasm.js_sys::Error::new::hf68801b1208761e0 (wasm://wasm/ruffle_web.wasm-03344202:wasm-function[12832]:0x9e0008)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::h34e38fc10c81aa2e (wasm://wasm/ruffle_web.wasm-03344202:wasm-function[9857]:0x975bf2)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h6731baa78621a747 (wasm://wasm/ruffle_web.wasm-03344202:wasm-function[6523]:0x869409)
    at ruffle_web.wasm.core::panicking::panic_fmt::h5c7ce52813e94bcd (wasm://wasm/ruffle_web.wasm-03344202:wasm-function[10287]:0x9a0a45)
    at ruffle_web.wasm.core::ops::function::Fn::call::hccb370a581821d1b (wasm://wasm/ruffle_web.wasm-03344202:wasm-function[7362]:0x8ab47a)
    at ruffle_web.wasm.<T as wgpu::context::DynContext>::device_create_buffer::ha3937e6eece1f753 (wasm://wasm/ruffle_web.wasm-03344202:wasm-function[7649]:0x8c4e9d)
    at ruffle_web.wasm.<wgpu::Device as wgpu::util::device::DeviceExt>::create_buffer_init::h8e151bf6dd1e2621 (wasm://wasm/ruffle_web.wasm-03344202:wasm-function[1902]:0x504918)
    at ruffle_web.wasm.ruffle_render_wgpu::buffer_builder::BufferBuilder::finish::hb670734ace5fa15d (wasm://wasm/ruffle_web.wasm-03344202:wasm-function[7790]:0x8cbd79)
    at ruffle_web.wasm.ruffle_render_wgpu::backend::WgpuRenderBackend<T>::register_shape_internal::hb208094223d7a02a (wasm://wasm/ruffle_web.wasm-03344202:wasm-function[1064]:0x2f9dc1)
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) UHD Graphics (0x00009B41) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: "WebGL 2.0 (OpenGL ES"
Adapter Driver Info: "3.0 Chromium)"
Enabled features: Features(TEXTURE_COMPRESSION_BC | FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(DEPTH32FLOAT_STENCIL8 | PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_color_attachments: 8, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.67&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1718856838%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F592000%2F592473_MadnessGame_ULTIMATE.swf%3F1507662264%22%2C%22vars%22%3A%7B%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%226674b50b2215d%22%2C%22NewgroundsAPI_SessionID%22%3A%22%22%2C%22NewgroundsAPI_UserName%22%3A%22%26lt%3Bdeleted%26gt%3B%22%2C%22NewgroundsAPI_UserID%22%3A0%2C%22ng_username%22%3A%22%26lt%3Bdeleted%26gt%3B%22%7D%2C%22width%22%3A850%2C%22height%22%3A530%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F592000%2Fflash_592473_card.webp%3Ff1669742379%22%2C%22warnOnUnsupportedContent%22%3Afalse%7D
SWF URL: https://uploads.ungrounded.net/592000/592473_MadnessGame_ULTIMATE.swf?1507662264

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 OPR/109.0.0.0
Platform: Win32
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-06-20
Channel: nightly
Built: 2024-06-20T00:05:30.479Z
Commit: c16b03f010a6dae4786ee0ea0e4c77c2411507a1
Is extension: false

# Metadata
width: 850
height: 530
frameRate: 30
numFrames: 30
swfVersion: 10
backgroundColor: #FFFFFF
isActionScript3: false
uncompressedLength: 20491352

**Comment by Lord-McSweeney** [comment]
Duplicate of #9834
