### ISSUE TITLE
,

### ISSUE THREAD

**Issue by MonzaOverdose** [ruffle-rs/ruffle#16848]
,

**Comment by torokati44** [comment]
FWIW, the original content was something like this:

Error Info

Error name: Error
Error message: panicked at core/src/avm1/runtime.rs:449:41:
called Option::unwrap() on a None value
Error stack:

Error: panicked at core/src/avm1/runtime.rs:449:41:
called `Option::unwrap()` on a `None` value
    at n.wbg.__wbg_new_28c511d9baebfa89 (https://www.officegamespot.com/ruffle/core.ruffle.e88cc385ca3824332d82.js:1:79124)
    at ruffle_web.wasm.js_sys::Error::new::h78d47deb446e5ef2 (wasm://wasm/ruffle_web.wasm-032c06ba:wasm-function[12858]:0x9d99c6)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::hf64bdfce4c5d3d74 (wasm://wasm/ruffle_web.wasm-032c06ba:wasm-function[9855]:0x96b69a)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h6731baa78621a747 (wasm://wasm/ruffle_web.wasm-032c06ba:wasm-function[6539]:0x857875)
    at ruffle_web.wasm.core::panicking::panic_fmt::h5c7ce52813e94bcd (wasm://wasm/ruffle_web.wasm-032c06ba:wasm-function[10293]:0x9970b8)
    at ruffle_web.wasm.core::panicking::panic::h3b99507adb69386a (wasm://wasm/ruffle_web.wasm-032c06ba:wasm-function[10022]:0x981027)
    at ruffle_web.wasm.core::option::unwrap_failed::h0d060778de0f79e8 (wasm://wasm/ruffle_web.wasm-032c06ba:wasm-function[12376]:0x9cb307)
    at ruffle_web.wasm.ruffle_core::player::Player::tick::hc728dd35d790ae5c (wasm://wasm/ruffle_web.wasm-032c06ba:wasm-function[883]:0x1d12ef)
    at ruffle_web.wasm.ruffle_web::RuffleHandle::tick::h6879a334f0b78db3 (wasm://wasm/ruffle_web.wasm-032c06ba:wasm-function[1070]:0x2f8776)
    at ruffle_web.wasm.ruffle_web::RuffleHandle::new_internal::{{closure}}::{{closure}}::{{closure}}::h4532eacc498a0ec7 (wasm://wasm/ruffle_web.wasm-032c06ba:wasm-function[12791]:0x9d91e4)

Player Info

Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA GeForce GTX 1660 Ti (0x00002182) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: "WebGL 2.0 (OpenGL ES"
Adapter Driver Info: "3.0 Chromium)"
Enabled features: Features(TEXTURE_COMPRESSION_BC | FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(DEPTH32FLOAT_STENCIL8 | PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_color_attachments: 8, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)
Page Info

Page URL: [officegamespot.com/freegames/scorched_pods.htm](https://www.officegamespot.com/freegames/scorched_pods.htm)
SWF URL: [officegamespot.com/freegames/scorchedpods.swf](https://www.officegamespot.com/freegames/scorchedpods.swf)
Browser Info

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false
Ruffle Info

Version: 0.1.0
Name: nightly 2024-06-15
Channel: nightly
Built: 2024-06-15T00:05:26.496Z
Commit: 30cc299ed6fd74225420372f8698490532ce8652
Is extension: false
Metadata

width: 945
height: 525
frameRate: 38
numFrames: 47
swfVersion: 8
backgroundColor: #5C41A7
isActionScript3: false
uncompressedLength: 3594108
