### ISSUE TITLE
Error on https://matrix3d.github.io/assets/gl3d/test_text2/index.html

### ISSUE THREAD

**Issue by matrix3d** [ruffle-rs/ruffle#16879]
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.20.1/src/backend/wgpu_core.rs:2996:5:
wgpu error: Validation Error

Caused by:
    In Device::create_texture
    Dimension Y is zero

Error stack:
```
Error: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.20.1/src/backend/wgpu_core.rs:2996:5:
wgpu error: Validation Error

Caused by:
    In Device::create_texture
    Dimension Y is zero


    at n.wbg.__wbg_new_28c511d9baebfa89 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.8413c1e69e2f0e8b03a2.js:1:79048)
    at ruffle_web.wasm.js_sys::Error::new::h4d90f277f68d570d (wasm://wasm/ruffle_web.wasm-033421f6:wasm-function[12880]:0x9e0531)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::h55ede6a173052926 (wasm://wasm/ruffle_web.wasm-033421f6:wasm-function[9897]:0x975e00)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h6731baa78621a747 (wasm://wasm/ruffle_web.wasm-033421f6:wasm-function[6556]:0x86904b)
    at ruffle_web.wasm.core::panicking::panic_fmt::h5c7ce52813e94bcd (wasm://wasm/ruffle_web.wasm-033421f6:wasm-function[10329]:0x9a05b6)
    at ruffle_web.wasm.core::ops::function::Fn::call::hb4c12c7f4d33d40c (wasm://wasm/ruffle_web.wasm-033421f6:wasm-function[7391]:0x8ab0b7)
    at ruffle_web.wasm.<T as wgpu::context::DynContext>::device_create_texture::hb3630b8f8cff77fb (wasm://wasm/ruffle_web.wasm-033421f6:wasm-function[7563]:0x8b6d9c)
    at ruffle_web.wasm.wgpu::Device::create_texture::hff7c3ba2959bf2d1 (wasm://wasm/ruffle_web.wasm-033421f6:wasm-function[5988]:0x834d1c)
    at ruffle_web.wasm.<ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::register_bitmap::h96d0340f195921ef (wasm://wasm/ruffle_web.wasm-033421f6:wasm-function[2095]:0x543739)
    at ruffle_web.wasm.ruffle_core::bitmap::bitmap_data::BitmapData::bitmap_handle::h41b26485d7cd2e42 (wasm://wasm/ruffle_web.wasm-033421f6:wasm-function[2097]:0x543ee5)
```
AVM2 stack:
```
    at flash.display::BitmapData/flash::display::BitmapData::draw()
    at gl3d.text::BitmapDataFromText()
    at gl3d.text::CharSet/update()
    at gl3d.text::Text/update()
    at gl3d.core.renders::Stage3DRender/render()
    at gl3d.core::View3D/render()
    at BaseExample/enterFrame()
    at TestText/enterFrame()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA GeForce RTX 4070 (0x00002786) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: "WebGL 2.0 (OpenGL ES"
Adapter Driver Info: "3.0 Chromium)"
Enabled features: Features(TEXTURE_COMPRESSION_BC | FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(DEPTH32FLOAT_STENCIL8 | PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_color_attachments: 8, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)
Player type: Object
SWF URL: FlashShader.swf?v=1
Param wmode: direct
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined
Attribute 6: undefined

# Page Info
Page URL: https://matrix3d.github.io/assets/gl3d/test_text2/index.html
SWF URL: https://matrix3d.github.io/assets/gl3d/test_text2/FlashShader.swf?v=1

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-06-25
Channel: nightly
Built: 2024-06-25T00:05:32.860Z
Commit: e83e39ad27aacde29583d51ed0ad234de4f370ef
Is extension: false

# Metadata
width: 800
height: 600
frameRate: 60
numFrames: 1
swfVersion: 30
backgroundColor: #FFFFFF
isActionScript3: true
uncompressedLength: 223328

**Comment by rmwesley** [comment]
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.20.1/src/backend/wgpu_core.rs:2996:5:
wgpu error: Validation Error

Caused by:
    In Device::create_render_pipeline
    Internal error in ShaderStages(VERTEX) shader: 


Error stack:
```
Error: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.20.1/src/backend/wgpu_core.rs:2996:5:
wgpu error: Validation Error

Caused by:
    In Device::create_render_pipeline
    Internal error in ShaderStages(VERTEX) shader: 


    at n.wbg.__wbg_new_28c511d9baebfa89 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.ac1e5c3bf7fdd66df597.js:1:79048)
    at ruffle_web.wasm.js_sys::Error::new::h4d90f277f68d570d (wasm://wasm/ruffle_web.wasm-033a35ea:wasm-function[12893]:0x9f162d)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::h770044e5f3bef765 (wasm://wasm/ruffle_web.wasm-033a35ea:wasm-function[9907]:0x98742b)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h6731baa78621a747 (wasm://wasm/ruffle_web.wasm-033a35ea:wasm-function[6566]:0x87c0d0)
    at ruffle_web.wasm.core::panicking::panic_fmt::h5c7ce52813e94bcd (wasm://wasm/ruffle_web.wasm-033a35ea:wasm-function[10338]:0x9b2023)
    at ruffle_web.wasm.core::ops::function::Fn::call::h6606612287aa3e89 (wasm://wasm/ruffle_web.wasm-033a35ea:wasm-function[7409]:0x8be631)
    at ruffle_web.wasm.<T as wgpu::context::DynContext>::device_create_render_pipeline::h1b402405501ed85a (wasm://wasm/ruffle_web.wasm-033a35ea:wasm-function[9039]:0x94df7b)
    at ruffle_web.wasm.wgpu::Device::create_render_pipeline::h99dcc51ba1cfaa4c (wasm://wasm/ruffle_web.wasm-033a35ea:wasm-function[7582]:0x8cf439)
    at ruffle_web.wasm.ruffle_render_wgpu::utils::run_copy_pipeline::hfd57a344019539f9 (wasm://wasm/ruffle_web.wasm-033a35ea:wasm-function[2965]:0x65a936)
    at ruffle_web.wasm.ruffle_render_wgpu::surface::Surface::draw_commands_and_copy_to::h90f873fb86973eea (wasm://wasm/ruffle_web.wasm-033a35ea:wasm-function[2603]:0x5f9b56)
```

# Player Info
Allows script access: true

Player type: Object
SWF URL: FlashShader.swf?v=1
Param wmode: direct
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined
Attribute 6: undefined

# Page Info
Page URL: https://matrix3d.github.io/assets/gl3d/test_text2/index.html

# Browser Info
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-06-29
Channel: nightly
Built: 2024-06-29T00:05:37.413Z
Commit: 948987b7438ff5ab085f919df28742d301e056db
Is extension: false

# Metadata

**Comment by rmwesley** [comment]
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.20.1/src/backend/wgpu_core.rs:2996:5:
wgpu error: Validation Error

Caused by:
    In Device::create_render_pipeline
    Internal error in ShaderStages(VERTEX) shader: 


Error stack:
```
Error: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.20.1/src/backend/wgpu_core.rs:2996:5:
wgpu error: Validation Error

Caused by:
    In Device::create_render_pipeline
    Internal error in ShaderStages(VERTEX) shader: 


    at n.wbg.__wbg_new_28c511d9baebfa89 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.ac1e5c3bf7fdd66df597.js:1:79048)
    at ruffle_web.wasm.js_sys::Error::new::h4d90f277f68d570d (wasm://wasm/ruffle_web.wasm-033a35ea:wasm-function[12893]:0x9f162d)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::h770044e5f3bef765 (wasm://wasm/ruffle_web.wasm-033a35ea:wasm-function[9907]:0x98742b)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h6731baa78621a747 (wasm://wasm/ruffle_web.wasm-033a35ea:wasm-function[6566]:0x87c0d0)
    at ruffle_web.wasm.core::panicking::panic_fmt::h5c7ce52813e94bcd (wasm://wasm/ruffle_web.wasm-033a35ea:wasm-function[10338]:0x9b2023)
    at ruffle_web.wasm.core::ops::function::Fn::call::h6606612287aa3e89 (wasm://wasm/ruffle_web.wasm-033a35ea:wasm-function[7409]:0x8be631)
    at ruffle_web.wasm.<T as wgpu::context::DynContext>::device_create_render_pipeline::h1b402405501ed85a (wasm://wasm/ruffle_web.wasm-033a35ea:wasm-function[9039]:0x94df7b)
    at ruffle_web.wasm.wgpu::Device::create_render_pipeline::h99dcc51ba1cfaa4c (wasm://wasm/ruffle_web.wasm-033a35ea:wasm-function[7582]:0x8cf439)
    at ruffle_web.wasm.ruffle_render_wgpu::utils::run_copy_pipeline::hfd57a344019539f9 (wasm://wasm/ruffle_web.wasm-033a35ea:wasm-function[2965]:0x65a936)
    at ruffle_web.wasm.ruffle_render_wgpu::surface::Surface::draw_commands_and_copy_to::h90f873fb86973eea (wasm://wasm/ruffle_web.wasm-033a35ea:wasm-function[2603]:0x5f9b56)
```

# Player Info
Allows script access: true

Player type: Object
SWF URL: FlashShader.swf?v=1
Param wmode: direct
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined
Attribute 6: undefined

# Page Info
Page URL: https://matrix3d.github.io/assets/gl3d/test_text2/index.html

# Browser Info
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-06-29
Channel: nightly
Built: 2024-06-29T00:05:37.413Z
Commit: 948987b7438ff5ab085f919df28742d301e056db
Is extension: false

**Comment by rmwesley** [comment]
Also, I get the same error when trying to play the flash game https://armorgames.com/play/505/sonny:

# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/daedf03/wgpu/src/backend/direct.rs:3111:5:
wgpu error: Validation Error

Caused by:
    In Device::create_render_pipeline
    Internal error in ShaderStages(VERTEX) shader: 


Error stack:
```
Error: panicked at /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/daedf03/wgpu/src/backend/direct.rs:3111:5:
wgpu error: Validation Error

Caused by:
    In Device::create_render_pipeline
    Internal error in ShaderStages(VERTEX) shader: 


    at H.n.wbg.__wbg_new_a64e3f2afc2cf2f8 (https://agi.armorgames.com/ruffle/core.ruffle.67bc37f4e63c43ff9c64.js:1:56204)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hbaaeff1a92f05ba2 (wasm://wasm/035cabca:wasm-function[10705]:0xa04127)
    at std::panicking::rust_panic_with_hook::h62090d3fc0630473 (wasm://wasm/035cabca:wasm-function[6570]:0x8f2a2a)
    at core::panicking::panic_fmt::hd79411a297d06dc8 (wasm://wasm/035cabca:wasm-function[10428]:0x9fdea4)
    at core::ops::function::Fn::call::h31fcd9672878c467 (wasm://wasm/035cabca:wasm-function[6874]:0x90981a)
    at wgpu::backend::direct::ErrorSinkRaw::handle_error::h55f5091b89514ccd (wasm://wasm/035cabca:wasm-function[5422]:0x88b06e)
    at <T as wgpu::context::DynContext>::device_create_render_pipeline::h1a53adb9fd52b148 (wasm://wasm/035cabca:wasm-function[8950]:0x99b5f1)
    at wgpu::Device::create_render_pipeline::h94c39f35d351948f (wasm://wasm/035cabca:wasm-function[7327]:0x9278ce)
    at ruffle_render_wgpu::utils::run_copy_pipeline::h835b81ae05ca5a43 (wasm://wasm/035cabca:wasm-function[2622]:0x66e4e0)
    at ruffle_render_wgpu::surface::Surface::draw_commands_and_copy_to::h8d07ca3d10908b30 (wasm://wasm/035cabca:wasm-function[2551]:0x65c0d1)
```

# Player Info
Allows script access: true


# Page Info
Page URL: https://armorgames.com/play/505/sonny

# Browser Info
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-01-08
Channel: nightly
Built: 2024-01-08T00:15:28.895Z
Commit: 47db84473a639c405289bb86ce238a83af574137
Is extension: false
