### ISSUE TITLE
Error on https://www.4399.com/flash/80597_4.htm

### ISSUE THREAD

**Issue by fhyjs** [ruffle-rs/ruffle#16976]
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.20.1/src/backend/wgpu_core.rs:2996:5:
wgpu error: Validation Error

Caused by:
    In Device::create_buffer
    Not enough memory left.

Error stack:
```
Error: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.20.1/src/backend/wgpu_core.rs:2996:5:
wgpu error: Validation Error

Caused by:
    In Device::create_buffer
    Not enough memory left.


    at imports.wbg.__wbg_new_28c511d9baebfa89 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/69.js:3701:21)
    at ruffle_web.wasm.js_sys::Error::new::h7d42a5777dfd5fa9 (wasm://wasm/ruffle_web.wasm-033b7956:wasm-function[12891]:0x9f490a)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::h1d5d927fd22d08ce (wasm://wasm/ruffle_web.wasm-033b7956:wasm-function[9891]:0x98973e)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h6731baa78621a747 (wasm://wasm/ruffle_web.wasm-033b7956:wasm-function[6566]:0x87e5b4)
    at ruffle_web.wasm.core::panicking::panic_fmt::h5c7ce52813e94bcd (wasm://wasm/ruffle_web.wasm-033b7956:wasm-function[10326]:0x9b5311)
    at ruffle_web.wasm.core::ops::function::Fn::call::ha9bb06c582fc9b82 (wasm://wasm/ruffle_web.wasm-033b7956:wasm-function[6863]:0x897410)
    at ruffle_web.wasm.<T as wgpu::context::DynContext>::device_create_buffer::h6674a0812f77e93f (wasm://wasm/ruffle_web.wasm-033b7956:wasm-function[7689]:0x8d848c)
    at ruffle_web.wasm.<wgpu::Device as wgpu::util::device::DeviceExt>::create_buffer_init::hc400bae5a62cada5 (wasm://wasm/ruffle_web.wasm-033b7956:wasm-function[1917]:0x519559)
    at ruffle_web.wasm.core::cell::once::OnceCell<T>::try_init::h40ae43a04a9a96b8 (wasm://wasm/ruffle_web.wasm-033b7956:wasm-function[5442]:0x813af6)
    at ruffle_web.wasm.ruffle_render_wgpu::surface::Surface::draw_commands_and_copy_to::h7503a89959789b22 (wasm://wasm/ruffle_web.wasm-033b7956:wasm-function[2610]:0x5fde7f)
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA GeForce GT 730 (0x00001287) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: "WebGL 2.0 (OpenGL ES"
Adapter Driver Info: "3.0 Chromium)"
Enabled features: Features(TEXTURE_COMPRESSION_BC | FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(DEPTH32FLOAT_STENCIL8 | PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_color_attachments: 8, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (660, 495, 1)

# Page Info
Page URL: https://www.4399.com/flash/80597_4.htm
SWF URL: https://sda.4399.com/4399swf/upload_swf/ftp7/weijianp/20120117/4.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-07-02
Channel: nightly
Built: 2024-07-02T00:05:38.347Z
Commit: 2093d950e5f5c6820e33caf4dc14dac1920699dc
Is extension: true

# Metadata
width: 800
height: 600
frameRate: 15
numFrames: 73
swfVersion: 6
backgroundColor: #999999
isActionScript3: false
uncompressedLength: 5121825

**Comment by riku-42** [comment]
Looks like the game is playable with `0.1.0 nightly 2024-08-04`. Can you give it another try?
