### ISSUE TITLE
Error on https://armorgames.com/play/17643/strikeforce-kitty-2

### ISSUE THREAD

**Issue by bookgames** [ruffle-rs/ruffle#17015]
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.20.1/src/backend/wgpu_core.rs:2996:5:
wgpu error: Validation Error

Caused by:
    In Device::create_buffer
    Not enough memory left.

Error stack:
```
Error: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.20.1/src/backend/wgpu_core.rs:2996:5:
wgpu error: Validation Error

Caused by:
    In Device::create_buffer
    Not enough memory left.


    at imports.wbg.__wbg_new_28c511d9baebfa89 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/69.js:3701:21)
    at ruffle_web.wasm.js_sys::Error::new::h7d42a5777dfd5fa9 (wasm://wasm/ruffle_web.wasm-033febee:wasm-function[12912]:0xa05b79)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::h1d5d927fd22d08ce (wasm://wasm/ruffle_web.wasm-033febee:wasm-function[9908]:0x99b106)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h6731baa78621a747 (wasm://wasm/ruffle_web.wasm-033febee:wasm-function[6576]:0x87f972)
    at ruffle_web.wasm.core::panicking::panic_fmt::h5c7ce52813e94bcd (wasm://wasm/ruffle_web.wasm-033febee:wasm-function[10344]:0x9c6df0)
    at ruffle_web.wasm.core::ops::function::Fn::call::ha9bb06c582fc9b82 (wasm://wasm/ruffle_web.wasm-033febee:wasm-function[6880]:0x89d18f)
    at ruffle_web.wasm.<T as wgpu::context::DynContext>::device_create_buffer::h6674a0812f77e93f (wasm://wasm/ruffle_web.wasm-033febee:wasm-function[7710]:0x8e3636)
    at ruffle_web.wasm.<wgpu::Device as wgpu::util::device::DeviceExt>::create_buffer_init::hc400bae5a62cada5 (wasm://wasm/ruffle_web.wasm-033febee:wasm-function[1904]:0x50f2e1)
    at ruffle_web.wasm.ruffle_render_wgpu::surface::target::CommandTarget::new::h61b8eb4a262ec28f (wasm://wasm/ruffle_web.wasm-033febee:wasm-function[1138]:0x34a934)
    at ruffle_web.wasm.ruffle_render_wgpu::surface::Surface::draw_commands::h6553863fe541a6bb (wasm://wasm/ruffle_web.wasm-033febee:wasm-function[870]:0x1ba7e7)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) Iris(R) Xe Graphics (0x00009A49) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: "WebGL 2.0 (OpenGL ES"
Adapter Driver Info: "3.0 Chromium)"
Enabled features: Features(TEXTURE_COMPRESSION_BC | FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(DEPTH32FLOAT_STENCIL8 | PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_color_attachments: 8, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)

# Page Info
Page URL: https://armorgames.com/play/17643/strikeforce-kitty-2?
SWF URL: https://cache.armorgames.com/files/games/strikeforce-kitty-2-17643.swf?v=1423725280

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-07-03
Channel: nightly
Built: 2024-07-03T00:05:23.559Z
Commit: 803a8c427ac6449fc4a604351c0b3ed654b5d29e
Is extension: true

# Metadata
width: 765
height: 540
frameRate: 60
numFrames: 95
swfVersion: 20
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 12673065

**Comment by bookgames** [comment]
After finishing a level , but i finished it multible time.
