### ISSUE TITLE
Error on https://slothtoss.com/projects/flash_tone-tuner/

### ISSUE THREAD

**Issue by Danbytronic** [ruffle-rs/ruffle#17071]
# Error Info
Error name: Error
Error message: panicked at library/alloc/src/raw_vec.rs:25:5:
capacity overflow
Error stack:
```
Error: panicked at library/alloc/src/raw_vec.rs:25:5:
capacity overflow
    at imports.wbg.__wbg_new_28c511d9baebfa89 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/69.js:3701:21)
    at ruffle_web.wasm.js_sys::Error::new::hda2cb16801956d39 (wasm://wasm/ruffle_web.wasm-0336c5d6:wasm-function[12819]:0x9df7cd)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::h4efee46b7e0e8825 (wasm://wasm/ruffle_web.wasm-0336c5d6:wasm-function[9849]:0x976437)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h6731baa78621a747 (wasm://wasm/ruffle_web.wasm-0336c5d6:wasm-function[6498]:0x869085)
    at ruffle_web.wasm.core::panicking::panic_fmt::h5c7ce52813e94bcd (wasm://wasm/ruffle_web.wasm-0336c5d6:wasm-function[10249]:0x9a06e8)
    at ruffle_web.wasm.alloc::raw_vec::handle_error::h6991f391977ec209 (wasm://wasm/ruffle_web.wasm-0336c5d6:wasm-function[11630]:0x9b9e53)
    at ruffle_web.wasm.alloc::raw_vec::RawVec<T,A>::reserve::do_reserve_and_handle::h928580553dba031d (wasm://wasm/ruffle_web.wasm-0336c5d6:wasm-function[6804]:0x882f0d)
    at ruffle_web.wasm.ruffle_core::avm2::globals::flash::media::sound::extract::he263669cdbbad40f (wasm://wasm/ruffle_web.wasm-0336c5d6:wasm-function[2812]:0x62fbf6)
    at ruffle_web.wasm.ruffle_core::avm2::function::exec::hb515bf7fba8514ec (wasm://wasm/ruffle_web.wasm-0336c5d6:wasm-function[1129]:0x32fd46)
    at ruffle_web.wasm.ruffle_core::avm2::object::TObject::call_method::h9d8bad046d5ae69b (wasm://wasm/ruffle_web.wasm-0336c5d6:wasm-function[2058]:0x53d1e7)
```
AVM2 stack:
```
    at flash.media::Sound/flash::media::Sound::extract()
    at org::Tuner/setOrigFileData()
    at org::Overlay/baOrigIsReady()
    at org::Overlay/mp3LoaderCompleteHandler()
    at flash.events::EventDispatcher/flash::events::EventDispatcher::dispatchEvent()
    at org.audiofx.mp3Importer::MP3FileReferenceLoader/swfCreated()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (AMD, AMD Radeon(TM) Graphics (0x00001636) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: "WebGL 2.0 (OpenGL ES"
Adapter Driver Info: "3.0 Chromium)"
Enabled features: Features(TEXTURE_COMPRESSION_BC | FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(DEPTH32FLOAT_STENCIL8 | PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_color_attachments: 8, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (800, 500, 1)
Player type: Object
SWF URL: auto-tune.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined

# Page Info
Page URL: https://slothtoss.com/projects/flash_tone-tuner/
SWF URL: https://slothtoss.com/projects/flash_tone-tuner/auto-tune.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-07-09
Channel: nightly
Built: 2024-07-09T00:05:50.583Z
Commit: eec5e908adb9c8809865dd534fbfff8116a43bdb
Is extension: true

# Metadata
width: 640
height: 400
frameRate: 24
numFrames: 2
swfVersion: 10
backgroundColor: #FFFFFF
isActionScript3: true
uncompressedLength: 1103408

**Comment by Lord-McSweeney** [comment]
```
            while(loc2 != this.ba_orig.position) {
                loc2 = int(this.ba_orig.position);
                param1.extract(this.ba_orig,2048);
            }
```
The SWF depends on `Sound.extract` eventually finishing the entire sound and writing 0 bytes to the `ByteArray`
