### ISSUE TITLE
Canyon Defense 2 [panicked at core/src/display_object/movie_clip.rs:417:9:]

### ISSUE THREAD

**Issue by Stefannag** [ruffle-rs/ruffle#17097]
### Describe the bug

```
panicked at core/src/display_object/movie_clip.rs:417:9:
assertion `left == right` failed: Called replace_movie on a clip with LoaderInfo set
  left: Some(LoaderInfoObject(LoaderInfoObject { ptr: 0x521c1c8 }))
 right: None

Stack:

Error
    at n.wbg.__wbg_new_abda76e883ba8a5f (https://www.getgames.io/scripts/ruffle/core.ruffle.8413c1e69e2f0e8b03a2.js:1:15987)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::h55ede6a173052926 (wasm://wasm/ruffle_web.wasm-033421f6:wasm-function[9897]:0x975adf)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h6731baa78621a747 (wasm://wasm/ruffle_web.wasm-033421f6:wasm-function[6556]:0x86904b)
    at ruffle_web.wasm.core::panicking::panic_fmt::h5c7ce52813e94bcd (wasm://wasm/ruffle_web.wasm-033421f6:wasm-function[10329]:0x9a05b6)
    at ruffle_web.wasm.core::panicking::assert_failed_inner::h95edf372af7e7269 (wasm://wasm/ruffle_web.wasm-033421f6:wasm-function[4560]:0x798fcc)
    at ruffle_web.wasm.ruffle_core::display_object::movie_clip::MovieClip::replace_with_movie::h24697dc933b6e904 (wasm://wasm/ruffle_web.wasm-033421f6:wasm-function[2292]:0x57ccaa)
    at ruffle_web.wasm.ruffle_core::loader::Loader::movie_loader::{{closure}}::h932de344c9032a9f (wasm://wasm/ruffle_web.wasm-033421f6:wasm-function[1061]:0x302bd5)
    at ruffle_web.wasm.<ruffle_web::navigator::WebNavigatorBackend as ruffle_core::backend::navigator::NavigatorBackend>::spawn_future::{{closure}}::h18d49d95db73f125 (wasm://wasm/ruffle_web.wasm-033421f6:wasm-function[1366]:0x3fa125)
    at ruffle_web.wasm.wasm_bindgen_futures::queue::QueueState::run_all::h2202916a5e928dc7 (wasm://wasm/ruffle_web.wasm-033421f6:wasm-function[4043]:0x743b0e)
    at ruffle_web.wasm.wasm_bindgen_futures::queue::Queue::new::{{closure}}::h1274b2c1f63611b9 (wasm://wasm/ruffle_web.wasm-033421f6:wasm-function[11474]:0x9b6b5d)
```

`ERROR web/src/lib.rs:1037 Unable to lock Ruffle core`

```
ruffle_web.wasm-033421f6:0x869071 Uncaught 
RuntimeError: unreachable
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h6731baa78621a747 (ruffle_web.wasm-033421f6:0x869071)
    at ruffle_web.wasm.core::panicking::panic_fmt::h5c7ce52813e94bcd (ruffle_web.wasm-033421f6:0x9a05b6)
    at ruffle_web.wasm.core::panicking::assert_failed_inner::h95edf372af7e7269 (ruffle_web.wasm-033421f6:0x798fcc)
    at ruffle_web.wasm.ruffle_core::display_object::movie_clip::MovieClip::replace_with_movie::h24697dc933b6e904 (ruffle_web.wasm-033421f6:0x57ccaa)
    at ruffle_web.wasm.ruffle_core::loader::Loader::movie_loader::{{closure}}::h932de344c9032a9f (ruffle_web.wasm-033421f6:0x302bd5)
    at ruffle_web.wasm.<ruffle_web::navigator::WebNavigatorBackend as ruffle_core::backend::navigator::NavigatorBackend>::spawn_future::{{closure}}::h18d49d95db73f125 (ruffle_web.wasm-033421f6:0x3fa125)
    at ruffle_web.wasm.wasm_bindgen_futures::queue::QueueState::run_all::h2202916a5e928dc7 (ruffle_web.wasm-033421f6:0x743b0e)
    at ruffle_web.wasm.wasm_bindgen_futures::queue::Queue::new::{{closure}}::h1274b2c1f63611b9 (ruffle_web.wasm-033421f6:0x9b6b5d)
    at ruffle_web.wasm.<dyn core::ops::function::FnMut<(emulate/A,)>+Output …e_web.wasm-033421f6)
    at ruffle_web.wasm.closure7407 externref shim (ruffle_web.wasm-033421f6:0x9bc18b)
```

`Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received`

### Expected behavior

To not panic. 

### Content Location

[Canyon Defense 2](https://www.archive.play-games.com/games/ruffle/?swf=miniclip/canyondefense/2v4.swf&params=&name=Canyon%20Defense%202)

### Affected platform

Self-hosted version

### Operating system

Windows 11

### Browser

Google Chrome Version 120.0.6099.200 (Official Build) (64-bit)

**Comment by Stefannag** [comment]
The game is working now.

**Comment by M00NJ** [comment]
> The game is working now.

You can play it? What's your setup? 
It's not panicking anymore but for me #11429 still persists.

**Comment by Stefannag** [comment]
> > The game is working now.
> 
> You can play it? What's your setup? It's not panicking anymore but for me [#11429](https://github.com/ruffle-rs/ruffle/issues/11429) still persists.

Sorry for the late reply. Somehow I wanted to answer but I forgot. You can check the setup directly on the linked I added, in source code. Nothing fancy, it's just a normal setup for web. 

If I can help you with more, please let me know.

**Comment by M00NJ** [comment]
No worries :) Thanks for still coming through. Indeed it's playable with this setup, though I didn't find out why it's working here and not in the Ruffle desktop app yet.
