### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by SarethW** [ruffle-rs/ruffle#1710]
When trying to play this flash game in Firefox Nightly, using this version of Ruffle right here:
**https://github.com/ruffle-rs/ruffle/releases/tag/nightly-2020-11-25**
and trying to play this game:
**https://armorgames.com/play/17897/exorcist**
It crashed and gave me this error:

# Error Info
Error name: Error
Error message: panicked at 'not implemented', core/src/display_object/movie_clip.rs:263:41
Error stack:
```
j@moz-extension://2172524b-985a-435f-99dc-871e9e2a3261/dist/core.ruffle.js:1:20183
__wbg_new_df6e6ab7a65c4c4d@moz-extension://2172524b-985a-435f-99dc-871e9e2a3261/dist/ruffle.js:1:31150
@moz-extension://2172524b-985a-435f-99dc-871e9e2a3261/dist/184ce67da0c38ffac000.module.wasm:wasm-function[1034]:0x1f91e2
@moz-extension://2172524b-985a-435f-99dc-871e9e2a3261/dist/184ce67da0c38ffac000.module.wasm:wasm-function[1363]:0x2392b9
@moz-extension://2172524b-985a-435f-99dc-871e9e2a3261/dist/184ce67da0c38ffac000.module.wasm:wasm-function[3652]:0x2e88c8
@moz-extension://2172524b-985a-435f-99dc-871e9e2a3261/dist/184ce67da0c38ffac000.module.wasm:wasm-function[2867]:0x2cab2c
@moz-extension://2172524b-985a-435f-99dc-871e9e2a3261/dist/184ce67da0c38ffac000.module.wasm:wasm-function[4012]:0x2ee037
@moz-extension://2172524b-985a-435f-99dc-871e9e2a3261/dist/184ce67da0c38ffac000.module.wasm:wasm-function[3959]:0x2ed715
@moz-extension://2172524b-985a-435f-99dc-871e9e2a3261/dist/184ce67da0c38ffac000.module.wasm:wasm-function[4009]:0x2edfbc
@moz-extension://2172524b-985a-435f-99dc-871e9e2a3261/dist/184ce67da0c38ffac000.module.wasm:wasm-function[279]:0x4e68e
@moz-extension://2172524b-985a-435f-99dc-871e9e2a3261/dist/184ce67da0c38ffac000.module.wasm:wasm-function[1071]:0x2016bb
@moz-extension://2172524b-985a-435f-99dc-871e9e2a3261/dist/184ce67da0c38ffac000.module.wasm:wasm-function[715]:0x19da22
@moz-extension://2172524b-985a-435f-99dc-871e9e2a3261/dist/184ce67da0c38ffac000.module.wasm:wasm-function[326]:0xb6a0d
@moz-extension://2172524b-985a-435f-99dc-871e9e2a3261/dist/184ce67da0c38ffac000.module.wasm:wasm-function[547]:0x159567
@moz-extension://2172524b-985a-435f-99dc-871e9e2a3261/dist/184ce67da0c38ffac000.module.wasm:wasm-function[1530]:0x2529a6
@moz-extension://2172524b-985a-435f-99dc-871e9e2a3261/dist/184ce67da0c38ffac000.module.wasm:wasm-function[2687]:0x2c06bb
@moz-extension://2172524b-985a-435f-99dc-871e9e2a3261/dist/184ce67da0c38ffac000.module.wasm:wasm-function[2425]:0x2ae5ee
@moz-extension://2172524b-985a-435f-99dc-871e9e2a3261/dist/184ce67da0c38ffac000.module.wasm:wasm-function[4141]:0x2ef62b
k@moz-extension://2172524b-985a-435f-99dc-871e9e2a3261/dist/core.ruffle.js:1:18573
f@moz-extension://2172524b-985a-435f-99dc-871e9e2a3261/dist/core.ruffle.js:1:17376

```

# Player Info
Allows script access: true
Player type: Object
SWF URL: https://cache.armorgames.com/files/games/exorcist-17897.swf?v=1447525911
Param allowScriptAccess: always
Param movie: https://cache.armorgames.com/files/games/exorcist-17897.swf?v=1447525911
Param quality: 
Param wmode: window
Param allowfullscreen: 
Param allowfullscreeninteractive: false
Param fullScreenAspectRatio: 
Param play: true
Param loop: true
Param menu: 
Param flashvars: gameID=17897
Param hasPriority: true
Attribute 0: [object Attr]
Attribute 1: [object Attr]
Attribute 2: [object Attr]
Attribute 3: [object Attr]
Attribute 4: [object Attr]
Attribute 5: [object Attr]

# Page Info
Page URL: https://armorgames.com/play/17897/exorcist

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:85.0) Gecko/20100101 Firefox/85.0
OS: Win32

# Ruffle Info
Ruffle version: 0.1.0
Ruffle source: undefined

**Comment by jeffallen** [comment]
Some more messages from the desktop before the crash:
```
[2020-12-01T10:34:12Z ERROR ruffle_core::avm2::activation] AVM2 error: Property does not exist: Some(AvmString { source: Owned("URLRequest") })
[2020-12-01T10:34:12Z ERROR ruffle_core::avm2::activation] AVM2 error: Property does not exist: Some(AvmString { source: Owned("URLRequest") })
[2020-12-01T10:34:12Z ERROR ruffle_core::display_object::movie_clip] Got Property does not exist: Some(AvmString { source: Owned("URLRequest") }) when constructing AVM2 side of display object
thread 'main' panicked at 'not implemented', core/src/display_object/movie_clip.rs:265:41
```

**Comment by ousia** [comment]
Direct link to SWF specification https://www.adobe.com/content/dam/acom/en/devnet/pdf/swf-file-format-spec.pdf#page=177.

**Comment by relrelb** [comment]
Doesn't panic since #1813. However, still unimplemented.
