### ISSUE TITLE
bug issue in playing a game.

### ISSUE THREAD

**Issue by Moonlight1999** [ruffle-rs/ruffle#17139]
### Describe the bug

# Error Info
Error name: Error
Error message: panicked at library/alloc/src/raw_vec.rs:25:5:
capacity overflow
Error stack:
```
Error: panicked at library/alloc/src/raw_vec.rs:25:5:
capacity overflow
    at imports.wbg.__wbg_new_28c511d9baebfa89 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/69.js:3711:21)
    at ruffle_web.wasm.js_sys::Error::new::h5917b4042e40a5aa (wasm://wasm/ruffle_web.wasm-03389462:wasm-function[12826]:0x9e5b6f)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::hf0b897470a9bbdb1 (wasm://wasm/ruffle_web.wasm-03389462:wasm-function[9860]:0x97b963)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h6731baa78621a747 (wasm://wasm/ruffle_web.wasm-03389462:wasm-function[6503]:0x870167)
    at ruffle_web.wasm.core::panicking::panic_fmt::h5c7ce52813e94bcd (wasm://wasm/ruffle_web.wasm-03389462:wasm-function[10260]:0x9a6d84)
    at ruffle_web.wasm.alloc::raw_vec::handle_error::h6991f391977ec209 (wasm://wasm/ruffle_web.wasm-03389462:wasm-function[11628]:0x9bffef)
    at ruffle_web.wasm.alloc::raw_vec::RawVec<T,A>::grow_one::h579029d72e56ae90 (wasm://wasm/ruffle_web.wasm-03389462:wasm-function[6690]:0x882f8d)
    at ruffle_web.wasm.alloc::collections::vec_deque::VecDeque<T,A>::grow::he4cb6e82eccc97a6 (wasm://wasm/ruffle_web.wasm-03389462:wasm-function[7510]:0x8b91d3)
    at ruffle_web.wasm.<ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::interactive::TInteractiveObject>::event_dispatch::h5e3a70fcfc467f26 (wasm://wasm/ruffle_web.wasm-03389462:wasm-function[1990]:0x52ff2c)
    at ruffle_web.wasm.<ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::run_frame_avm1::h2234684993318837 (wasm://wasm/ruffle_web.wasm-03389462:wasm-function[4707]:0x7b3933)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) UHD Graphics 600 (0x00003185) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: "WebGL 2.0 (OpenGL ES"
Adapter Driver Info: "3.0 Chromium)"
Enabled features: Features(TEXTURE_COMPRESSION_BC | FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(DEPTH32FLOAT_STENCIL8 | PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_color_attachments: 8, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)

# Page Info
Page URL: https://www.arcadeprehacks.com/game/540/Swords-and-Sandals-3.html
SWF URL: https://www.arcadeprehacks.com/swf/ss3_loader.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
Platform: Win32
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-07-16
Channel: nightly
Built: 2024-07-16T00:05:34.758Z
Commit: 6e93927f631fb317a6b40f031457c47d3e399e27
Is extension: true

# Metadata
width: 640
height: 480
frameRate: 30
numFrames: 1
swfVersion: 9
backgroundColor: #FFFFFF
isActionScript3: false
uncompressedLength: 191

this a copy paste from ruffle failing to load a game im playing.

### Expected behavior

the ruffle having issues making the game unplayable.

### Content Location

https://www.arcadeprehacks.com/game/540/Swords-and-Sandals-3.html#

### Affected platform

Browser's extension

### Operating system

Windows 11.

### Browser

Google Chrome

**Comment by Dinnerbone** [comment]
This game doesn't work in Flash Player either. The comments on the page suggest it stopped working in 2018.
It's trying to load things that don't exist anymore, not a ruffle bug sorry :(
