### ISSUE TITLE
Error on https://game286444.konggames.com/games/clarusvictoria/pre-civilization-marble-age/frame/6e050cd9-8474-4a5b-be24-3a468359b075/

### ISSUE THREAD

**Issue by barretta-r** [ruffle-rs/ruffle#17240]
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.20.1/src/backend/wgpu_core.rs:2996:5:
wgpu error: Validation Error

Caused by:
    In Device::create_texture
    Dimension Y is zero

Error stack:
```
Error: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.20.1/src/backend/wgpu_core.rs:2996:5:
wgpu error: Validation Error

Caused by:
    In Device::create_texture
    Dimension Y is zero


    at n.wbg.__wbg_new_28c511d9baebfa89 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.9ac16791b6831b373fbe.js:1:79242)
    at ruffle_web.wasm.js_sys::Error::new::hf03bfdfe20712a15 (wasm://wasm/ruffle_web.wasm-033838de:wasm-function[12858]:0x9e40a8)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::hc88c405174a9e2d2 (wasm://wasm/ruffle_web.wasm-033838de:wasm-function[9885]:0x97a962)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h6731baa78621a747 (wasm://wasm/ruffle_web.wasm-033838de:wasm-function[6537]:0x86d3a2)
    at ruffle_web.wasm.core::panicking::panic_fmt::h5c7ce52813e94bcd (wasm://wasm/ruffle_web.wasm-033838de:wasm-function[10287]:0x9a5642)
    at ruffle_web.wasm.core::ops::function::Fn::call::ha78fd0945830235c (wasm://wasm/ruffle_web.wasm-033838de:wasm-function[6835]:0x886a1a)
    at ruffle_web.wasm.<T as wgpu::context::DynContext>::device_create_texture::h887797d57ceb260d (wasm://wasm/ruffle_web.wasm-033838de:wasm-function[7575]:0x8bb89f)
    at ruffle_web.wasm.wgpu::Device::create_texture::ha0e401571dfb0389 (wasm://wasm/ruffle_web.wasm-033838de:wasm-function[5951]:0x836635)
    at ruffle_web.wasm.<ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::register_bitmap::h95318e14995fa62b (wasm://wasm/ruffle_web.wasm-033838de:wasm-function[2093]:0x5465ea)
    at ruffle_web.wasm.ruffle_core::bitmap::bitmap_data::BitmapData::bitmap_handle::h7f9131800428c5e6 (wasm://wasm/ruffle_web.wasm-033838de:wasm-function[2096]:0x547222)
```
AVM2 stack:
```
    at flash.display::BitmapData/flash::display::BitmapData::draw()
    at com.emibap.textureAtlas::DynamicAtlas$/drawItem()
    at com.emibap.textureAtlas::DynamicAtlas$/fromMovieClipContainer()
    at Asset$/loadAtlas()
    at Asset$/init()
    at Classes$/init()
    at MainMenu()
    at starling.core::Starling/initializeRoot()
    at starling.core::Starling/initialize()
    at starling.core::Starling/onContextCreated()
    at flash.events::EventDispatcher/flash::events::EventDispatcher::dispatchEvent()
    at flash.display::Stage3D/flash::display::Stage3D::requestContext3D_internal()
    at MethodInfo-2032()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Apple, ANGLE Metal Renderer: Apple M1 Pro, Unspecified Version)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: "WebGL 2.0 (OpenGL ES"
Adapter Driver Info: "3.0 Chromium)"
Enabled features: Features(TEXTURE_COMPRESSION_BC | FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(DEPTH32FLOAT_STENCIL8 | TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | TEXTURE_COMPRESSION_ASTC_HDR | PUSH_CONSTANTS | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_color_attachments: 8, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)

# Page Info
Page URL: https://game286444.konggames.com/games/clarusvictoria/pre-civilization-marble-age/frame/6e050cd9-8474-4a5b-be24-3a468359b075/?kongregate_host=www.kongregate.com
SWF URL: https://game286444.konggames.com/gamez/0028/6444/live/ma2.9.8GProt.swf?kongregate_game_version=1506420754

# Browser Info
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
Platform: MacIntel
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-07-23
Channel: nightly
Built: 2024-07-23T00:05:24.982Z
Commit: e9c610816b04d9cc8d21ebee2c6aab5e8995a8eb
Is extension: false

# Metadata
width: 800
height: 533
frameRate: 30
numFrames: 2
swfVersion: 34
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 9716767

**Comment by Lord-McSweeney** [comment]
Duplicate of #13946
