### ISSUE TITLE
Error at doitpoms.ac.uk

### ISSUE THREAD

**Issue by PinwheelGalaxy101** [ruffle-rs/ruffle#1744]
(I'm just an end user, not a developer; I'm just reporting an issue I have found)

While trying to play the flash at https://www.doitpoms.ac.uk/tlplib/crystallography3/systems.php , I encountered the following error message:

# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:462:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:462:50
    at Object.j (chrome-extension://mfffnnlbmhhjbhnocpngbfjejebgcfha/dist/core.ruffle.js:1:20233)
    at __wbg_new_df6e6ab7a65c4c4d (chrome-extension://mfffnnlbmhhjbhnocpngbfjejebgcfha/dist/ruffle.js:1:34277)
    at chrome-extension://mfffnnlbmhhjbhnocpngbfjejebgcfha/dist/633b58938fe25014a592.module.wasm:wasm-function[1041]:0x20395c
    at chrome-extension://mfffnnlbmhhjbhnocpngbfjejebgcfha/dist/633b58938fe25014a592.module.wasm:wasm-function[1365]:0x2429ea
    at chrome-extension://mfffnnlbmhhjbhnocpngbfjejebgcfha/dist/633b58938fe25014a592.module.wasm:wasm-function[3659]:0x2f28b0
    at chrome-extension://mfffnnlbmhhjbhnocpngbfjejebgcfha/dist/633b58938fe25014a592.module.wasm:wasm-function[2873]:0x2d4a72
    at chrome-extension://mfffnnlbmhhjbhnocpngbfjejebgcfha/dist/633b58938fe25014a592.module.wasm:wasm-function[3955]:0x2f7514
    at chrome-extension://mfffnnlbmhhjbhnocpngbfjejebgcfha/dist/633b58938fe25014a592.module.wasm:wasm-function[3985]:0x2f7a77
    at chrome-extension://mfffnnlbmhhjbhnocpngbfjejebgcfha/dist/633b58938fe25014a592.module.wasm:wasm-function[3860]:0x2f60f1
    at chrome-extension://mfffnnlbmhhjbhnocpngbfjejebgcfha/dist/633b58938fe25014a592.module.wasm:wasm-function[3986]:0x2f7aad
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: flash/Tri.swf
Param movie: flash/Tri.swf
Param quality: high
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://www.doitpoms.ac.uk/tlplib/crystallography3/systems.php

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2020-11-27
Channel: nightly
Built: 2020-11-27T00:30:29.363Z
Commit: 1d648a1d557d8d692becf9cbb12922dcb1f5db17

**Comment by Toad06** [comment]
I wasn't able to reproduce this on my end. However, we've fixed a few issues since then, could you please check if everything works now using [the last nightly build](https://github.com/ruffle-rs/ruffle/tags)? Thanks in advance!

**Comment by Herschel** [comment]
Dupe, closing in favor of #1905.
