### ISSUE TITLE
Error on https://localhost.issess.net/swf.html

### ISSUE THREAD

**Issue by raden-andrianto** [ruffle-rs/ruffle#17498]
# Error Info
Error name: Error
Error message: panicked at core/src/avm2/globals/flash/display/bitmap_data.rs:71:30:
Failed to decode BitmapData: InvalidZlibCompression
Error stack:
```
Error: panicked at core/src/avm2/globals/flash/display/bitmap_data.rs:71:30:
Failed to decode BitmapData: InvalidZlibCompression
    at J.n.wbg.__wbg_new_28c511d9baebfa89 (https://localhost.issess.net/ruffle/ruffle/core.ruffle.2bdce3d13ee9db3415e5.js:1:73847)
    at js_sys::Error::new::ha2f6fa40afaacb83 (wasm://wasm/03a684ce:wasm-function[13903]:0xb26e35)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h7f02ae3a8308da6d (wasm://wasm/03a684ce:wasm-function[11505]:0xad1c9d)
    at std::panicking::rust_panic_with_hook::h9aabd906218897c3 (wasm://wasm/03a684ce:wasm-function[7076]:0x99aed9)
    at core::panicking::panic_fmt::h3aff855fe938c13f (wasm://wasm/03a684ce:wasm-function[11212]:0xacb59c)
    at core::result::unwrap_failed::had70491c62ee681b (wasm://wasm/03a684ce:wasm-function[8662]:0xa210f9)
    at ruffle_core::avm2::globals::flash::display::bitmap_data::fill_bitmap_data_from_symbol::hfc7e5fd185bd04a3 (wasm://wasm/03a684ce:wasm-function[4231]:0x822159)
    at ruffle_core::avm2::globals::flash::display::bitmap::bitmap_allocator::h3b30dae1482077d5 (wasm://wasm/03a684ce:wasm-function[1255]:0x3eaf0f)
    at <ruffle_core::avm2::object::class_object::ClassObject as ruffle_core::avm2::object::TObject>::construct::h2c051a4cb30f94dd (wasm://wasm/03a684ce:wasm-function[5145]:0x8d30fe)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::construct::h27424b57b604a4ae (wasm://wasm/03a684ce:wasm-function[1398]:0x457c38)
```
AVM2 stack:
```
    at com.smbc.graphics::BmdInfo$/addMainPalette()
    at com.smbc.graphics::BmdInfo$cinit()
    at global$init() [TU=frame1]
    at com.smbc.data::GameSettings$cinit()
    at global$init() [TU=frame1]
    at com.smbc.data::OnlineData$/initiate()
    at com.smbc::SuperMarioBrosCrossover/addedToStageHandler()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "PowerVR SGX Doma"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | PUSH_CONSTANTS | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 4096, max_texture_dimension_2d: 4096, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 134217728, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 64, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: low
Surface samples: 1
Surface size: (550, 400, 1)
Player type: Object
SWF URL: http://localhost.issess.net/cached.swf
Param movie: http://localhost.issess.net/cached.swf
Param quality: low
Param wmode: window
Param allowScriptAccess: always
Param menu: false
Param allowFullScreen: true
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined
Attribute 6: undefined

# Page Info
Page URL: https://localhost.issess.net/swf.html
SWF URL: http://localhost.issess.net/cached.swf

# Browser Info
User Agent: Mozilla/5.0 (Linux; Android 12; V2120 Build/SP1A.210812.003; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/127.0.6533.66 Mobile Safari/537.36
Platform: Linux armv7l
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-04-10
Channel: nightly
Built: 2024-04-10T00:05:50.866Z
Commit: 0f1cdf491dfe84f34f4b9c3505306cb6d5046931
Is extension: false

# Metadata
width: 512
height: 480
frameRate: 24
numFrames: 1
swfVersion: 14
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 42693822

**Comment by n0samu** [comment]
Hi @raden-andrianto, can you please zip and attach the SWF file that you were testing? Thanks!

**Comment by raden-andrianto** [comment]
I'm really sorry just found out you sent an message and email to me. As far as I remember, this is my favorite game I tried playing with "ruffle" and an error occurred[
[Uploading schoolgirlvsorcs.zip…]()
](url)

**Comment by raden-andrianto** [comment]
I'm really sorry just found out you sent an message and email to me. As far as I remember, this is my favorite game I tried playing with "ruffle" and an error occurred.

[schoolgirlvsorcs.zip](https://github.com/user-attachments/files/16863134/schoolgirlvsorcs.zip)

**Comment by n0samu** [comment]
Hi, the error stack doesn't seem to match that game. I think the game you were trying to play was one of the Super Mario Bros. Crossover games. But I wasn't able to find a version that reproduces your error.

**Comment by raden-andrianto** [comment]
sorry sending the wrong SWF file, this is the "Super Mario Bros. crossover" game that I have been collecting for a long time, thank you for replying to my message.
[SMBC3.zip](https://github.com/user-attachments/files/16971550/SMBC3.zip)

**Comment by n0samu** [comment]
I am still unable to reproduce the error from your original message with the SWF you provided.

**Comment by raden-andrianto** [comment]
t's okay if the error still unable to reproduce with the SWF. I'll look for the latest version of that SWF game that can be played with "ruffle", thanks 🙏

**Comment by raden-andrianto** [comment]
It's okay if the error still unable to reproduce with the SWF. I'll look for the latest version of that SWF game that can be played with "ruffle", thanks 🙏

**Comment by raden-andrianto** [comment]
it's okay if the error still unable to reproduce with the SWF. I'll look
for the latest version of that SWF game that can be played with "ruffle",
thanks 🙏

Pada Kam, 12 Sep 2024 pukul 07.11 nosamu ***@***.***> menulis:
