### ISSUE TITLE
Error on https://game141094.konggames.com/games/RAC7/stealth-hunter-2/frame/3f1f19e4-8165-454e-bd5e-ba5176b4797b/

### ISSUE THREAD

**Issue by yukaleong** [ruffle-rs/ruffle#17510]
# Error Info
Error name: Error
Error message: panicked at core/src/avm2/amf.rs:157:18:
called `Result::unwrap()` on an `Err` value: ReferenceError: Error #1069: Property copyFrom not found on flash.geom.Rectangle and there is no default value.
Error stack:
```
Error: panicked at core/src/avm2/amf.rs:157:18:
called `Result::unwrap()` on an `Err` value: ReferenceError: Error #1069: Property copyFrom not found on flash.geom.Rectangle and there is no default value.
    at n.wbg.__wbg_new_28c511d9baebfa89 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.6cacaad5d7da2c0ea30f.js:1:80322)
    at ruffle_web.wasm.js_sys::Error::new::h69e363d74b15dc09 (wasm://wasm/ruffle_web.wasm-031e4e6e:wasm-function[12698]:0x980ef6)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::h16a6474029cce8cf (wasm://wasm/ruffle_web.wasm-031e4e6e:wasm-function[9749]:0x9100de)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h47bd3d747ed79dc3 (wasm://wasm/ruffle_web.wasm-031e4e6e:wasm-function[6288]:0x806882)
    at ruffle_web.wasm.core::panicking::panic_fmt::hb859252f4b513814 (wasm://wasm/ruffle_web.wasm-031e4e6e:wasm-function[10158]:0x92b23d)
    at ruffle_web.wasm.core::result::unwrap_failed::h9c8291f73d3ee71a (wasm://wasm/ruffle_web.wasm-031e4e6e:wasm-function[7929]:0x8930b3)
    at ruffle_web.wasm.ruffle_core::avm2::amf::serialize_value::h70e3c588c4b5aa70 (wasm://wasm/ruffle_web.wasm-031e4e6e:wasm-function[1105]:0x3003b5)
    at ruffle_web.wasm.ruffle_core::avm2::amf::get_or_create_element::h0e48877d43e6b013 (wasm://wasm/ruffle_web.wasm-031e4e6e:wasm-function[2567]:0x5c5beb)
    at ruffle_web.wasm.ruffle_core::avm2::amf::recursive_serialize::h449570419d31fd76 (wasm://wasm/ruffle_web.wasm-031e4e6e:wasm-function[1473]:0x40c8c3)
    at ruffle_web.wasm.ruffle_core::avm2::amf::serialize_value::h70e3c588c4b5aa70 (wasm://wasm/ruffle_web.wasm-031e4e6e:wasm-function[1105]:0x300299)
```
AVM2 stack:
```
    at flash.utils::ByteArray/flash::utils::ByteArray::writeObject()
    at sh3.vo::CheckpointVO$/create()
    at sh3.util::GameUtils$/checkpoint()
    at sh3.world.the_landing::TheLanding/checkpoint()
    at Function/apply()
    at jrlib.util.queue.items::CallFunctionTask/execute()
    at jrlib.util.queue::QueueItem/_execute()
    at jrlib.util.queue::CommandQueue/process()
    at jrlib.util.queue::CommandQueue/process()
    at jrlib.util.queue::CommandQueue/process()
    at jrlib.util.queue::CommandQueue/process()
    at jrlib.util.queue::CommandQueue/process()
    at jrlib.util.queue::CommandQueue/process()
    at sh3.engine.components::EngineCinematics/update()
    at jrlib.util.components::ComponentSet/update()
    at giraffetile::TileEngine/update()
    at sh3.engine::SHEngine/update()
    at sh3.commands::SkipCinematicCommand/doWork()
    at jrlib.command::SlowCommand/run()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) Iris(R) Xe Graphics (0x00009A49) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: "WebGL 2.0 (OpenGL ES 3.0 Chromium)"
Enabled features: Features(TEXTURE_COMPRESSION_BC | FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES)
Available features: Features(DEPTH32FLOAT_STENCIL8 | PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_color_attachments: 8, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)

# Page Info
Page URL: https://game141094.konggames.com/games/RAC7/stealth-hunter-2/frame/3f1f19e4-8165-454e-bd5e-ba5176b4797b/?kongregate_host=www.kongregate.com
SWF URL: https://game141094.konggames.com/gamez/0014/1094/live/SHPreloader_Kong.swf?kongregate_game_version=1334135101

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-08-14
Channel: nightly
Built: 2024-08-14T00:05:43.527Z
Commit: 11e15d1accad217bfa6a418c99664011c1934d46
Is extension: false

# Metadata
width: 850
height: 595
frameRate: 60
numFrames: 2
swfVersion: 11
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 8207225

**Comment by n0samu** [comment]
Confirmed this is reproducible by playing through the tutorial up until you're told that you need to sneak into the warehouse. (Takes about 1 minute)

**Comment by n0samu** [comment]
#14744 was occurring at exactly the same spot in the game. But this panic started occurring instead after #17485 was merged.

**Comment by n0samu** [comment]
Here is the decrypted SWF for easier inspection: [SH2_decrypted.zip](https://github.com/user-attachments/files/16612009/SH2_decrypted.zip)

**Comment by Molisson** [comment]
https://github.com/ruffle-rs/ruffle/pull/17787 will probably fix this.

**Comment by Molisson** [comment]
Tested through https://www.newgrounds.com/portal/view/592710?emulate=flash and this error stack doesn't appear anymore, however it still softlocks there (see https://github.com/ruffle-rs/ruffle/issues/14744.)
