### ISSUE TITLE
Error on https://www.gameflare.com/embed/resort-empire/

### ISSUE THREAD

**Issue by Arya-Azaria** [ruffle-rs/ruffle#17612]
# Error Info
Error name: Error
Error message: panicked at core/src/avm2/amf.rs:157:18:
called `Result::unwrap()` on an `Err` value: ReferenceError: Error #1069: Property copyFrom not found on flash.geom.Point and there is no default value.
Error stack:
```
Error: panicked at core/src/avm2/amf.rs:157:18:
called `Result::unwrap()` on an `Err` value: ReferenceError: Error #1069: Property copyFrom not found on flash.geom.Point and there is no default value.
    at n.wbg.__wbg_new_796382978dfd4fb0 (https://www.gameflare.com/emulators/ruffle/core.ruffle.19f889005897ddc03573.js:1:83857)
    at ruffle_web.wasm.js_sys::Error::new::he5ee53fe8c974231 (wasm://wasm/ruffle_web.wasm-031f502a:wasm-function[12752]:0x9813e3)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::hc5f0283980ec2f43 (wasm://wasm/ruffle_web.wasm-031f502a:wasm-function[9807]:0x90fc26)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h47bd3d747ed79dc3 (wasm://wasm/ruffle_web.wasm-031f502a:wasm-function[6269]:0x7f10ea)
    at ruffle_web.wasm.core::panicking::panic_fmt::hb859252f4b513814 (wasm://wasm/ruffle_web.wasm-031f502a:wasm-function[10217]:0x92b74b)
    at ruffle_web.wasm.core::result::unwrap_failed::h9c8291f73d3ee71a (wasm://wasm/ruffle_web.wasm-031f502a:wasm-function[7996]:0x897510)
    at ruffle_web.wasm.ruffle_core::avm2::amf::serialize_value::h795b732bc5de87f6 (wasm://wasm/ruffle_web.wasm-031f502a:wasm-function[1107]:0x30a3ae)
    at ruffle_web.wasm.ruffle_core::avm2::amf::get_or_create_element::hc027517ac8206691 (wasm://wasm/ruffle_web.wasm-031f502a:wasm-function[2448]:0x591ce9)
    at ruffle_web.wasm.ruffle_core::avm2::amf::recursive_serialize::h9e7ed41fd77faa7f (wasm://wasm/ruffle_web.wasm-031f502a:wasm-function[1465]:0x404dc8)
    at ruffle_web.wasm.ruffle_core::avm2::amf::serialize_value::h795b732bc5de87f6 (wasm://wasm/ruffle_web.wasm-031f502a:wasm-function[1107]:0x30a292)
```
AVM2 stack:
```
    at flash.utils::ByteArray/flash::utils::ByteArray::writeObject()
    at pack::co$/cloning()
    at Application/NeedToGameRecord()
    at Application/autoSaved()
    at Application/autoSavedDataCalling()
    at Application/closingStatFunction()
    at ResortEmpire_fla::statD_734/clickFunction()
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) UHD Graphics 620 (0x00003EA0) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: "WebGL 2.0 (OpenGL ES 3.0 Chromium)"
Enabled features: Features(TEXTURE_COMPRESSION_BC | FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES)
Available features: Features(DEPTH32FLOAT_STENCIL8 | PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_color_attachments: 8, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)

# Page Info
Page URL: https://www.gameflare.com/embed/resort-empire/
SWF URL: https://data.gameflare.com/games/3705/tQSKbxkA1IgxKe.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
Platform: Win32
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-08-21
Channel: nightly
Built: 2024-08-21T00:05:50.477Z
Commit: 2889a715ad7979370dcc069d70abea09c48045da
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 23
numFrames: 13
swfVersion: 9
backgroundColor: #CCCCCC
isActionScript3: true
uncompressedLength: 3839261

**Comment by adrian17** [comment]
This error should be fixed by https://github.com/ruffle-rs/ruffle/pull/17787 .
