### ISSUE TITLE
Error on https://archive.org/details/resort_empire_

### ISSUE THREAD

**Issue by Rychard2107** [ruffle-rs/ruffle#17719]
# Error Info
Error name: Error
Error message: panicked at core/src/avm2/amf.rs:157:18:
called `Result::unwrap()` on an `Err` value: ReferenceError: Error #1069: Property copyFrom not found on flash.geom.Point and there is no default value.
Error stack:
```
Error: panicked at core/src/avm2/amf.rs:157:18:
called `Result::unwrap()` on an `Err` value: ReferenceError: Error #1069: Property copyFrom not found on flash.geom.Point and there is no default value.
    at imports.wbg.__wbg_new_796382978dfd4fb0 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/69.js:3784:21)
    at ruffle_web.wasm.js_sys::Error::new::h88ecd9455fcda73d (wasm://wasm/ruffle_web.wasm-031e789e:wasm-function[12710]:0x97fbde)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::h62db458ea18d0144 (wasm://wasm/ruffle_web.wasm-031e789e:wasm-function[9780]:0x90e2f5)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h47bd3d747ed79dc3 (wasm://wasm/ruffle_web.wasm-031e789e:wasm-function[6259]:0x7edf9e)
    at ruffle_web.wasm.core::panicking::panic_fmt::hb859252f4b513814 (wasm://wasm/ruffle_web.wasm-031e789e:wasm-function[10189]:0x929e68)
    at ruffle_web.wasm.core::result::unwrap_failed::h9c8291f73d3ee71a (wasm://wasm/ruffle_web.wasm-031e789e:wasm-function[7980]:0x895be5)
    at ruffle_web.wasm.ruffle_core::avm2::amf::serialize_value::h3fb55794607fdee6 (wasm://wasm/ruffle_web.wasm-031e789e:wasm-function[1105]:0x302803)
    at ruffle_web.wasm.ruffle_core::avm2::amf::get_or_create_element::h77c1a7e326489c08 (wasm://wasm/ruffle_web.wasm-031e789e:wasm-function[2440]:0x58be13)
    at ruffle_web.wasm.ruffle_core::avm2::amf::recursive_serialize::h9b9a14fdc3d32ff2 (wasm://wasm/ruffle_web.wasm-031e789e:wasm-function[1460]:0x4006cd)
    at ruffle_web.wasm.ruffle_core::avm2::amf::serialize_value::h3fb55794607fdee6 (wasm://wasm/ruffle_web.wasm-031e789e:wasm-function[1105]:0x3026e7)
```
AVM2 stack:
```
    at flash.utils::ByteArray/flash::utils::ByteArray::writeObject()
    at pack::co$/cloning()
    at Application/NeedToGameRecord()
    at Application/autoSaved()
    at Application/autoSavedDataCalling()
    at Application/closingStatFunction()
    at ResortEmpire_fla::statD_734/clickFunction()
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) HD Graphics 5500 (0x00001616) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: "WebGL 2.0 (OpenGL ES 3.0 Chromium)"
Enabled features: Features(TEXTURE_COMPRESSION_BC | FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES)
Available features: Features(DEPTH32FLOAT_STENCIL8 | PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_color_attachments: 8, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (560, 384, 1)

# Page Info
Page URL: https://archive.org/details/resort_empire_#

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-08-31
Channel: nightly
Built: 2024-08-31T00:05:26.054Z
Commit: 2fd8f600bc23ab0f7b35949b853f245cea016c20
Is extension: true

# Metadata
width: 640
height: 480
frameRate: 23
numFrames: 13
swfVersion: 9
backgroundColor: #CCCCCC
isActionScript3: true
uncompressedLength: 3839261

**Comment by adrian17** [comment]
This error should be fixed by https://github.com/ruffle-rs/ruffle/pull/17787 .
