### ISSUE TITLE
Error on https://www.minijuegos.com/helpers/game/sandbox.php

### ISSUE THREAD

**Issue by Xiomara-273** [ruffle-rs/ruffle#17713]
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-22.1.0/src/backend/wgpu_core.rs:3411:5:
wgpu error: Validation Error

Caused by:
  In Device::create_buffer
    Not enough memory left.

Error stack:
```
Error: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-22.1.0/src/backend/wgpu_core.rs:3411:5:
wgpu error: Validation Error

Caused by:
  In Device::create_buffer
    Not enough memory left.


    at n.wbg.__wbg_new_796382978dfd4fb0 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.d2ad1c02716c700d7923.js:1:83857)
    at ruffle_web.wasm.js_sys::Error::new::h88ecd9455fcda73d (wasm://wasm/ruffle_web.wasm-031e789e:wasm-function[12710]:0x97fbde)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::h62db458ea18d0144 (wasm://wasm/ruffle_web.wasm-031e789e:wasm-function[9780]:0x90e2f5)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h47bd3d747ed79dc3 (wasm://wasm/ruffle_web.wasm-031e789e:wasm-function[6259]:0x7edf9e)
    at ruffle_web.wasm.core::panicking::panic_fmt::hb859252f4b513814 (wasm://wasm/ruffle_web.wasm-031e789e:wasm-function[10189]:0x929e68)
    at ruffle_web.wasm.core::ops::function::Fn::call::ha46f26812c6bbe09 (wasm://wasm/ruffle_web.wasm-031e789e:wasm-function[6573]:0x810aa5)
    at ruffle_web.wasm.<T as wgpu::context::DynContext>::device_create_buffer::h8f452277386af216 (wasm://wasm/ruffle_web.wasm-031e789e:wasm-function[7507]:0x86474d)
    at ruffle_web.wasm.<wgpu::Device as wgpu::util::device::DeviceExt>::create_buffer_init::hfc1cf77c02c75dab (wasm://wasm/ruffle_web.wasm-031e789e:wasm-function[1847]:0x4b2f40)
    at ruffle_web.wasm.ruffle_render_wgpu::buffer_builder::BufferBuilder::finish::h0583eec18270efeb (wasm://wasm/ruffle_web.wasm-031e789e:wasm-function[7658]:0x86bffc)
    at ruffle_web.wasm.ruffle_render_wgpu::backend::WgpuRenderBackend<T>::register_shape_internal::h608438d01311d493 (wasm://wasm/ruffle_web.wasm-031e789e:wasm-function[1385]:0x3cd3bd)
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (AMD, AMD Radeon(TM) Graphics (0x000015D8) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: "WebGL 2.0 (OpenGL ES 3.0 Chromium)"
Enabled features: Features(TEXTURE_COMPRESSION_BC | FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES)
Available features: Features(DEPTH32FLOAT_STENCIL8 | PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_color_attachments: 8, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (660, 485, 1)

# Page Info
Page URL: https://www.minijuegos.com/helpers/game/sandbox.php?mp_assets=https%3A%2F%2Fs2.minijuegosgratis.com%2F&mp_embed=0&mp_game_id=17181&mp_game_uid=the-king-of-fighters-wing-v1-4&mp_game_url=https%3A%2F%2Fwww.minijuegos.com%2Fembed%2Fthe-king-of-fighters-wing-v1-4&mp_int=1&mp_locale=es_ES&mp_player_type=FLASH&mp_player_url=aHR0cHM6Ly93d3cubWluaWp1ZWdvc2dyYXRpcy5jb20vZmxhc2gxMjM0L25vX2hvdGxpbmsvdGhla2luZ29mZmlnaHRlcnN3aW5nMTQuc3dm&mp_site_https_url=https%3A%2F%2Fwww.minijuegos.com%2F&mp_site_name=minijuegos.com&mp_site_url=https%3A%2F%2Fwww.minijuegos.com%2F&mp_timezone=America%2FGuayaquil&mp_view_type=
SWF URL: https://www.minijuegosgratis.com/flash1234/no_hotlink/thekingoffighterswing14.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-08-31
Channel: nightly
Built: 2024-08-31T00:05:26.054Z
Commit: 2fd8f600bc23ab0f7b35949b853f245cea016c20
Is extension: false

# Metadata
width: 660
height: 485
frameRate: 32
numFrames: 39
swfVersion: 9
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 18876807

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
