### ISSUE TITLE
Error on https://game101267.konggames.com/games/ArmorGames/shift-freedom/frame/0be54181-d31d-4db3-9f96-e2eb756c476d/

### ISSUE THREAD

**Issue by DorkenVader** [ruffle-rs/ruffle#17731]
# Error Info
Error name: Error
Error message: panicked at core/src/avm2/amf.rs:156:18:
called `Result::unwrap()` on an `Err` value: ReferenceError: Error #1069: Property copyFrom not found on flash.geom.Point and there is no default value.
Error stack:
```
Error: panicked at core/src/avm2/amf.rs:156:18:
called `Result::unwrap()` on an `Err` value: ReferenceError: Error #1069: Property copyFrom not found on flash.geom.Point and there is no default value.
    at n.wbg.__wbg_new_796382978dfd4fb0 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.704c45a5fccd76ca0532.js:1:83857)
    at ruffle_web.wasm.js_sys::Error::new::h88ecd9455fcda73d (wasm://wasm/ruffle_web.wasm-031dc7ce:wasm-function[12691]:0x97d966)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::h62db458ea18d0144 (wasm://wasm/ruffle_web.wasm-031dc7ce:wasm-function[9767]:0x90c947)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h47bd3d747ed79dc3 (wasm://wasm/ruffle_web.wasm-031dc7ce:wasm-function[6257]:0x7ecd2e)
    at ruffle_web.wasm.core::panicking::panic_fmt::hb859252f4b513814 (wasm://wasm/ruffle_web.wasm-031dc7ce:wasm-function[10178]:0x928441)
    at ruffle_web.wasm.core::result::unwrap_failed::h9c8291f73d3ee71a (wasm://wasm/ruffle_web.wasm-031dc7ce:wasm-function[7965]:0x89423f)
    at ruffle_web.wasm.ruffle_core::avm2::amf::serialize_value::h3fb55794607fdee6 (wasm://wasm/ruffle_web.wasm-031dc7ce:wasm-function[1112]:0x2facdd)
    at ruffle_web.wasm.ruffle_core::avm2::amf::get_or_create_element::h77c1a7e326489c08 (wasm://wasm/ruffle_web.wasm-031dc7ce:wasm-function[2535]:0x5a3cfd)
    at ruffle_web.wasm.ruffle_core::avm2::amf::recursive_serialize::h9b9a14fdc3d32ff2 (wasm://wasm/ruffle_web.wasm-031dc7ce:wasm-function[1466]:0x40485b)
    at ruffle_web.wasm.ruffle_core::avm2::amf::serialize_value::h3fb55794607fdee6 (wasm://wasm/ruffle_web.wasm-031dc7ce:wasm-function[1112]:0x2f9ed5)
```
AVM2 stack:
```
    at flash.net::SharedObject/flash::net::SharedObject::flush()
    at AltShiftVer15TheEscapePublicKONG_fla::MainTimeline/saveGame()
    at AltShiftVer15TheEscapePublicKONG_fla::MainTimeline/setDefaultSave()
    at AltShiftVer15TheEscapePublicKONG_fla::MainTimeline/loadSave()
    at AltShiftVer15TheEscapePublicKONG_fla::MainTimeline/frame10()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (AMD, AMD Radeon HD 7800 Series (0x00006818) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: "WebGL 2.0 (OpenGL ES 3.0 Chromium)"
Enabled features: Features(TEXTURE_COMPRESSION_BC | FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES)
Available features: Features(DEPTH32FLOAT_STENCIL8 | PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_color_attachments: 8, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)

# Page Info
Page URL: https://game101267.konggames.com/games/ArmorGames/shift-freedom/frame/0be54181-d31d-4db3-9f96-e2eb756c476d/?kongregate_host=www.kongregate.com
SWF URL: https://game101267.konggames.com/gamez/0010/1267/live/Alt_Shift_Ver15_The_Escape_Public_KONG.swf?kongregate_game_version=1294571596

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-09-01
Channel: nightly
Built: 2024-09-01T00:06:38.962Z
Commit: ad0d3f8fbf4cba09e66d84d077f6a2df23a409b9
Is extension: false

# Metadata
width: 800
height: 600
frameRate: 30
numFrames: 36
swfVersion: 10
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 8444563

**Comment by adrian17** [comment]
This error should be fixed by https://github.com/ruffle-rs/ruffle/pull/17787 .
