### ISSUE TITLE
Error on https://www.megaigry.ru/embed/zombidle/

### ISSUE THREAD

**Issue by CraMbic444** [ruffle-rs/ruffle#17782]
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/git/checkouts/rust-flash-lso-7db697fbf6bd96f3/98679aa/flash-lso/src/amf3/read.rs:435:14:
Unable to get Object
Error stack:
```
Error: panicked at /home/runner/.cargo/git/checkouts/rust-flash-lso-7db697fbf6bd96f3/98679aa/flash-lso/src/amf3/read.rs:435:14:
Unable to get Object
    at n.wbg.__wbg_new_796382978dfd4fb0 (https://www.megaigry.ru/emulators/ruffle/core.ruffle.1fad5110710476fd8724.js:1:83857)
    at ruffle_web.wasm.js_sys::Error::new::hfb561c222a4e70eb (wasm://wasm/ruffle_web.wasm-0320469e:wasm-function[12753]:0x98635f)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::h81099db94754a517 (wasm://wasm/ruffle_web.wasm-0320469e:wasm-function[9827]:0x917b42)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h33fe77d38d305ca3 (wasm://wasm/ruffle_web.wasm-0320469e:wasm-function[6388]:0x80ffe8)
    at ruffle_web.wasm.core::panicking::panic_fmt::hde8b7aa66e2831e1 (wasm://wasm/ruffle_web.wasm-0320469e:wasm-function[9548]:0x908861)
    at ruffle_web.wasm.core::option::expect_failed::hacfbd4e0f8d6ca3b (wasm://wasm/ruffle_web.wasm-0320469e:wasm-function[8930]:0x8e731c)
    at ruffle_web.wasm.flash_lso::amf3::read::AMF3Decoder::parse_single_element::h1c9def9900e85592 (wasm://wasm/ruffle_web.wasm-0320469e:wasm-function[795]:0xe5a5d)
    at ruffle_web.wasm.ruffle_core::avm2::globals::flash::utils::byte_array::read_object::h9393bade97bee456 (wasm://wasm/ruffle_web.wasm-0320469e:wasm-function[902]:0x1e410f)
    at ruffle_web.wasm.ruffle_core::avm2::function::exec::hc31dc0a4622656ce (wasm://wasm/ruffle_web.wasm-0320469e:wasm-function[1355]:0x3ccc8e)
    at ruffle_web.wasm.ruffle_core::avm2::object::TObject::call_method::h2d3e5f044e8376aa (wasm://wasm/ruffle_web.wasm-0320469e:wasm-function[2440]:0x5a5887)
```
AVM2 stack:
```
    at flash.utils::ByteArray/flash::utils::ByteArray::readObject()
    at com.berzerkstudio::ModelFla/loadFromByteArray()
    at com.lachhhStarling.berzerk::BerzerkZipModelFlaLoader/loadNextFla()
    at com.lachhhStarling.berzerk::BerzerkZipModelFlaLoader/loadAllFlas()
    at com.zombidle::MainGameWebStarling/loadModelFlas()
    at com.zombidle::MainGameWebStarling/loadZipFile()
    at Function/apply()
    at com.lachhh.io::Callback/call()
    at com.lachhhStarling::StarlingMain$/startGame()
    at MethodInfo-3324()
    at starling.utils::AssetManager/loadQueue()
    at com.lachhhStarling::StarlingMain$/loadAssetsDesktop()
    at MethodInfo-3322()
    at starling.events::EventDispatcher/invokeEvent()
    at starling.events::EventDispatcher/dispatchEvent()
    at starling.events::EventDispatcher/dispatchEventWith()
    at starling.core::Starling/initializeRoot()
    at starling.core::Starling/initialize()
    at starling.core::Starling/onContextCreated()
    at flash.events::EventDispatcher/flash::events::EventDispatcher::dispatchEvent()
    at flash.display::Stage3D/flash::display::Stage3D::requestContext3D_internal()
    at MethodInfo-2018()
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) HD Graphics (0x000022B1) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: "WebGL 2.0 (OpenGL ES 3.0 Chromium)"
Enabled features: Features(TEXTURE_COMPRESSION_BC | FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES)
Available features: Features(DEPTH32FLOAT_STENCIL8 | PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_color_attachments: 8, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)

# Page Info
Page URL: https://www.megaigry.ru/embed/zombidle/
SWF URL: https://data.gameflare.com/games/6929/bc3OPnDSAYKX0a.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 YaBrowser/24.7.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-09-06
Channel: nightly
Built: 2024-09-06T00:06:03.493Z
Commit: 5550443fdb27d6318e3882949dedffd48725e05a
Is extension: false

# Metadata
width: 960
height: 640
frameRate: 60
numFrames: 2
swfVersion: 14
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 22341052

**Comment by n0samu** [comment]
Fixed by #18046
