### ISSUE TITLE
Crash on launch some Korean flash games

### ISSUE THREAD

**Issue by jooy0224** [ruffle-rs/ruffle#1779]
Ruffle crashes after a while after launching the game.
It seems to be caused by Hangul initials (uncombined characters).
Thanks!

# Error Info
Error name: Error
Error message: panicked at 'byte index 1 is not a char boundary; it is inside 'ㅁ' (bytes 0..3) of `ㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅍㅁㅁㅁㅁ`', core/src/font.rs:334:39
Error stack:
```
Error: panicked at 'byte index 1 is not a char boundary; it is inside 'ㅁ' (bytes 0..3) of `ㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅍㅁㅁㅁㅁ`', core/src/font.rs:334:39
    at Object.D (https://flasharch.com/js/ruffle/core.ruffle.a2dfc53a3fdf3085c069.js:1:20372)
    at __wbg_new_df6e6ab7a65c4c4d (https://flasharch.com/js/ruffle/ruffle.js:1:34986)
    at https://flasharch.com/js/ruffle/2583fcc0c02f07ea94e3.module.wasm:wasm-function[1058]:0x206ad5
    at https://flasharch.com/js/ruffle/2583fcc0c02f07ea94e3.module.wasm:wasm-function[1378]:0x244bb3
    at https://flasharch.com/js/ruffle/2583fcc0c02f07ea94e3.module.wasm:wasm-function[3687]:0x2f7a6b
    at https://flasharch.com/js/ruffle/2583fcc0c02f07ea94e3.module.wasm:wasm-function[2918]:0x2da6de
    at https://flasharch.com/js/ruffle/2583fcc0c02f07ea94e3.module.wasm:wasm-function[3984]:0x2fc718
    at https://flasharch.com/js/ruffle/2583fcc0c02f07ea94e3.module.wasm:wasm-function[4014]:0x2fcc7b
    at https://flasharch.com/js/ruffle/2583fcc0c02f07ea94e3.module.wasm:wasm-function[3889]:0x2fb2e8
    at https://flasharch.com/js/ruffle/2583fcc0c02f07ea94e3.module.wasm:wasm-function[4015]:0x2fccb1
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://flasharch.com/en/archive/play/e6e1b503a898a13996a45f28abf0c716

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2020-11-30
Channel: nightly
Built: 2020-11-30T00:33:10.981Z
Commit: d27b46b3dc421263555299cdf05a632dde27899e

**Comment by jooy0224** [comment]
Not reproduced in recent Nightly builds. It appears to have been resolved, so I will close the issue.
