### ISSUE TITLE
Error on https://game190896.konggames.com/games/Vitaly/feudalism-iii/frame/b636869d-ed6d-42c2-b4c2-151a6db7f178/

### ISSUE THREAD

**Issue by jm709** [ruffle-rs/ruffle#17807]
# Error Info
Error name: Error
Error message: panicked at core/src/avm2/amf.rs:156:18:
called `Result::unwrap()` on an `Err` value: ReferenceError: Error #1069: Property copyFrom not found on flash.geom.Point and there is no default value.
Error stack:
```
Error: panicked at core/src/avm2/amf.rs:156:18:
called `Result::unwrap()` on an `Err` value: ReferenceError: Error #1069: Property copyFrom not found on flash.geom.Point and there is no default value.
    at n.wbg.__wbg_new_796382978dfd4fb0 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.d486ef35541f20024e70.js:1:83857)
    at ruffle_web.wasm.js_sys::Error::new::hfb561c222a4e70eb (wasm://wasm/ruffle_web.wasm-03216dce:wasm-function[12756]:0x989444)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::h81099db94754a517 (wasm://wasm/ruffle_web.wasm-03216dce:wasm-function[9826]:0x91a555)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h33fe77d38d305ca3 (wasm://wasm/ruffle_web.wasm-03216dce:wasm-function[6387]:0x8132dd)
    at ruffle_web.wasm.core::panicking::panic_fmt::hde8b7aa66e2831e1 (wasm://wasm/ruffle_web.wasm-03216dce:wasm-function[9542]:0x90b0fe)
    at ruffle_web.wasm.core::result::unwrap_failed::h472431483d5eea7f (wasm://wasm/ruffle_web.wasm-03216dce:wasm-function[8006]:0x89bcc8)
    at ruffle_web.wasm.ruffle_core::avm2::amf::serialize_value::hce2511480f779846 (wasm://wasm/ruffle_web.wasm-03216dce:wasm-function[1074]:0x2e0b11)
    at ruffle_web.wasm.ruffle_core::avm2::amf::get_or_create_element::hb6debcdd382358f6 (wasm://wasm/ruffle_web.wasm-03216dce:wasm-function[2532]:0x5c5b4f)
    at ruffle_web.wasm.ruffle_core::avm2::amf::recursive_serialize::he2fec61e271bede9 (wasm://wasm/ruffle_web.wasm-03216dce:wasm-function[1336]:0x3c0eb1)
    at ruffle_web.wasm.ruffle_core::avm2::globals::flash::net::shared_object::new_lso::h45cc3f752d5e7a37 (wasm://wasm/ruffle_web.wasm-03216dce:wasm-function[2667]:0x5e926c)
```
AVM2 stack:
```
    at flash.net::SharedObject/flash::net::SharedObject::flush()
    at PlayerProfile$/save()
    at locations::Town/enterTown()
    at locations::Town/enter()
    at Tutorial$/end()
    at Tutorial/lessonStart16()
    at Tutorial/onTimer()
    at flash.events::EventDispatcher/flash::events::EventDispatcher::dispatchEvent()
    at flash.utils::Timer/onUpdate()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) Iris(R) Xe Graphics (0x000046A8) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: "WebGL 2.0 (OpenGL ES 3.0 Chromium)"
Enabled features: Features(TEXTURE_COMPRESSION_BC | FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES)
Available features: Features(DEPTH32FLOAT_STENCIL8 | PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_color_attachments: 8, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)

# Page Info
Page URL: https://game190896.konggames.com/games/Vitaly/feudalism-iii/frame/b636869d-ed6d-42c2-b4c2-151a6db7f178/?kongregate_host=www.kongregate.com
SWF URL: https://game190896.konggames.com/gamez/0019/0896/live/f3.swf?kongregate_game_version=1384190542

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-09-07
Channel: nightly
Built: 2024-09-07T00:05:48.737Z
Commit: 43f5aaaab94dbcf271819504fe952e69270da7fb
Is extension: false

# Metadata
width: 800
height: 500
frameRate: 30
numFrames: 3
swfVersion: 10
backgroundColor: #242A52
isActionScript3: true
uncompressedLength: 11854484

**Comment by adrian17** [comment]
This error should be fixed by https://github.com/ruffle-rs/ruffle/pull/17787 .
