### ISSUE TITLE
Error on https://images-opensocial.googleusercontent.com/gadgets/ifr

### ISSUE THREAD

**Issue by hhirschi1234** [ruffle-rs/ruffle#17861]
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-22.1.0/src/backend/wgpu_core.rs:3411:5:
wgpu error: Validation Error

Caused by:
  In Device::create_buffer
    Not enough memory left.

Error stack:
```
Error: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-22.1.0/src/backend/wgpu_core.rs:3411:5:
wgpu error: Validation Error

Caused by:
  In Device::create_buffer
    Not enough memory left.


    at n.wbg.__wbg_new_796382978dfd4fb0 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.6c9ab55eb51519cd6d18.js:1:83857)
    at ruffle_web.wasm.js_sys::Error::new::ha4990c08e4b8c418 (wasm://wasm/ruffle_web.wasm-031e155a:wasm-function[12701]:0x979bd8)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::he12a364ec508badc (wasm://wasm/ruffle_web.wasm-031e155a:wasm-function[9779]:0x908ca2)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h47bd3d747ed79dc3 (wasm://wasm/ruffle_web.wasm-031e155a:wasm-function[6265]:0x7e94b0)
    at ruffle_web.wasm.core::panicking::panic_fmt::hb859252f4b513814 (wasm://wasm/ruffle_web.wasm-031e155a:wasm-function[10188]:0x924edf)
    at ruffle_web.wasm.core::ops::function::Fn::call::h096d13d1829bc87a (wasm://wasm/ruffle_web.wasm-031e155a:wasm-function[6576]:0x80c16a)
    at ruffle_web.wasm.<T as wgpu::context::DynContext>::device_create_buffer::h529171fa57417315 (wasm://wasm/ruffle_web.wasm-031e155a:wasm-function[7497]:0x85e8fc)
    at ruffle_web.wasm.<wgpu::Device as wgpu::util::device::DeviceExt>::create_buffer_init::hb6a05bd04c14413f (wasm://wasm/ruffle_web.wasm-031e155a:wasm-function[1847]:0x4b7321)
    at ruffle_web.wasm.ruffle_render_wgpu::surface::target::CommandTarget::new::h50791439f5944deb (wasm://wasm/ruffle_web.wasm-031e155a:wasm-function[1147]:0x30d975)
    at ruffle_web.wasm.ruffle_render_wgpu::surface::Surface::draw_commands::h160bd79757770abf (wasm://wasm/ruffle_web.wasm-031e155a:wasm-function[887]:0x1a71ed)
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Vulkan 1.3.274 (Intel(R) UHD Graphics (JSL) (0x00004E55)), Intel open-source Mesa driver)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: "WebGL 2.0 (OpenGL ES 3.0 Chromium)"
Enabled features: Features(TEXTURE_COMPRESSION_BC | FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES)
Available features: Features(DEPTH32FLOAT_STENCIL8 | TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 64, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 112, max_color_attachments: 8, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)

# Page Info
Page URL: https://images-opensocial.googleusercontent.com/gadgets/ifr?url=https://s3.amazonaws.com/production-assetsbucket-8ljvyr1xczmb/f107b843-3661-4036-9397-2b0c6414a369%2Fburrito_bison.xml&container=ig
SWF URL: https://cdn.jsdelivr.net/gh/auserishere/Testing-Platform-Games-Resources@786105e16b35d564d90eb1071d257c502a96fb0d/dagobah_burrito_bison.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-09-11
Channel: nightly
Built: 2024-09-11T00:06:20.152Z
Commit: aded7906728a83f54d29f9d4c0957b6d2e111158
Is extension: false

# Metadata
width: 720
height: 480
frameRate: 45
numFrames: 99
swfVersion: 10
backgroundColor: #A5EAFE
isActionScript3: true
uncompressedLength: 8600134

**Comment by jfrenl** [comment]
Does anyone have a new fix for this since it's been a while and i keep getting 404 not found.
