### ISSUE TITLE
Demolition City 2: Ruffle Crash

### ISSUE THREAD

**Issue by TomFulp** [ruffle-rs/ruffle#17883]
### Describe the bug

Click Start on the title screen, select the first level and then Ruffle will crash with these details:

# Error Info
Error name: Error
Error message: panicked at core/src/avm2/globals/flash/display/shader_job.rs:76:26:
Shader property is not an object
Error stack:
```
Error: panicked at core/src/avm2/globals/flash/display/shader_job.rs:76:26:
Shader property is not an object
    at n.wbg.__wbg_new_796382978dfd4fb0 (https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.2f0ea05f03d14efb94b9.js:1:83857)
    at ruffle_web.wasm.js_sys::Error::new::ha4990c08e4b8c418 (wasm://wasm/ruffle_web.wasm-031c8846:wasm-function[12693]:0x974255)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::he12a364ec508badc (wasm://wasm/ruffle_web.wasm-031c8846:wasm-function[9774]:0x90496d)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h47bd3d747ed79dc3 (wasm://wasm/ruffle_web.wasm-031c8846:wasm-function[6288]:0x7f5c77)
    at ruffle_web.wasm.core::panicking::panic_fmt::hb859252f4b513814 (wasm://wasm/ruffle_web.wasm-031c8846:wasm-function[10181]:0x91fbdd)
    at ruffle_web.wasm.core::option::expect_failed::h9d0c8588efc786aa (wasm://wasm/ruffle_web.wasm-031c8846:wasm-function[8886]:0x8d5225)
    at ruffle_web.wasm.core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once::hf7c1fc9d2c603ac5 (wasm://wasm/ruffle_web.wasm-031c8846:wasm-function[1171]:0x33ccfd)
    at ruffle_web.wasm.ruffle_core::avm2::globals::flash::display::shader_job::get_shader_args::hd0b35aafd822785d (wasm://wasm/ruffle_web.wasm-031c8846:wasm-function[2875]:0x602834)
    at ruffle_web.wasm.<ruffle_render::filters::Filter as ruffle_core::avm2::filters::FilterAvm2Ext>::from_avm2_object::h4375970f648fe3b0 (wasm://wasm/ruffle_web.wasm-031c8846:wasm-function[788]:0xdb349)
    at ruffle_web.wasm.ruffle_core::avm2::globals::flash::display::display_object::set_filters::hc47c1aab0c91f918 (wasm://wasm/ruffle_web.wasm-031c8846:wasm-function[1404]:0x3cf929)
```
AVM2 stack:
```
    at flash.display::DisplayObject/flash::display::DisplayObject::filters()
    at Main/loadLevelBitmap()
    at Main/openMapArea()
    at Main/handleTownClick()
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA GeForce RTX 4070 (0x00002786) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: "WebGL 2.0 (OpenGL ES 3.0 Chromium)"
Enabled features: Features(TEXTURE_COMPRESSION_BC | FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES)
Available features: Features(DEPTH32FLOAT_STENCIL8 | PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_color_attachments: 8, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.67&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1726114534%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F516000%2F516016_Demolition2_ng.swf%3F1256668454%22%2C%22vars%22%3A%7B%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%2266e34180befc6%22%2C%22NewgroundsAPI_SessionID%22%3A%22wrZNEw8njFDVLDkZdon1356a192b7913b04c54574d18c28d46e6395428abe5DF%22%2C%22NewgroundsAPI_UserName%22%3A%22TomFulp%22%2C%22NewgroundsAPI_UserID%22%3A1%2C%22ng_username%22%3A%22TomFulp%22%7D%2C%22width%22%3A700%2C%22height%22%3A600%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F516000%2Fflash_516016.gif%3Ff1279833010%22%2C%22warnOnUnsupportedContent%22%3Atrue%7D
SWF URL: https://uploads.ungrounded.net/516000/516016_Demolition2_ng.swf?1256668454

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-09-12
Channel: nightly
Built: 2024-09-12T00:06:03.350Z
Commit: 3b6d5088d1b49e38698f3750212a5dea0783b0d7
Is extension: false

# Metadata
width: 700
height: 600
frameRate: 60
numFrames: 2
swfVersion: 10
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 3366039

### Expected behavior

No crash.

### Content Location

https://www.newgrounds.com/portal/view/516016

### Affected platform

Self-hosted version

### Operating system

Windows 11

### Browser

Google Chrome Version 128.0.6613.120 (Official Build) (64-bit)

**Comment by waspennator** [comment]
Still occurring as of latest nightly
