### ISSUE TITLE
Error on https://www.minijuegos.com/helpers/game/sandbox.php

### ISSUE THREAD

**Issue by mateoelproo** [ruffle-rs/ruffle#17902]
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/git/checkouts/rust-flash-lso-7db697fbf6bd96f3/98679aa/flash-lso/src/amf3/read.rs:435:14:
Unable to get Object
Error stack:
```
Error: panicked at /home/runner/.cargo/git/checkouts/rust-flash-lso-7db697fbf6bd96f3/98679aa/flash-lso/src/amf3/read.rs:435:14:
Unable to get Object
    at n.wbg.__wbg_new_796382978dfd4fb0 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.eff553c567a7ead39869.js:1:83857)
    at ruffle_web.wasm.js_sys::Error::new::hfb561c222a4e70eb (wasm://wasm/ruffle_web.wasm-03212586:wasm-function[12740]:0x985756)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::he535d08ebd1aba14 (wasm://wasm/ruffle_web.wasm-03212586:wasm-function[9796]:0x915500)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h33fe77d38d305ca3 (wasm://wasm/ruffle_web.wasm-03212586:wasm-function[6360]:0x805dca)
    at ruffle_web.wasm.core::panicking::panic_fmt::hde8b7aa66e2831e1 (wasm://wasm/ruffle_web.wasm-03212586:wasm-function[9515]:0x906186)
    at ruffle_web.wasm.core::option::expect_failed::hacfbd4e0f8d6ca3b (wasm://wasm/ruffle_web.wasm-03212586:wasm-function[8896]:0x8e472c)
    at ruffle_web.wasm.flash_lso::amf3::read::AMF3Decoder::parse_single_element::h1c9def9900e85592 (wasm://wasm/ruffle_web.wasm-03212586:wasm-function[795]:0xe5e4d)
    at ruffle_web.wasm.flash_lso::amf3::read::AMF3Decoder::parse_single_element::h1c9def9900e85592 (wasm://wasm/ruffle_web.wasm-03212586:wasm-function[795]:0xe32a1)
    at ruffle_web.wasm.flash_lso::amf3::read::AMF3Decoder::parse_object_static::hb59892bc89244ac7 (wasm://wasm/ruffle_web.wasm-03212586:wasm-function[4238]:0x724530)
    at ruffle_web.wasm.flash_lso::amf3::read::AMF3Decoder::parse_single_element::h1c9def9900e85592 (wasm://wasm/ruffle_web.wasm-03212586:wasm-function[795]:0xe5cb6)
```
AVM2 stack:
```
    at flash.utils::ByteArray/flash::utils::ByteArray::readObject()
    at BinaryData$/getMovieClipManager()
    at Game/onLoadComplete()
    at Game()
    at Main/createGame()
    at Main/onRootCreated()
    at starling.events::EventDispatcher/invokeEvent()
    at starling.events::EventDispatcher/dispatchEvent()
    at starling.events::EventDispatcher/dispatchEventWith()
    at starling.core::Starling/initializeRoot()
    at starling.core::Starling/initialize()
    at starling.core::Starling/onContextCreated()
    at flash.events::EventDispatcher/flash::events::EventDispatcher::dispatchEvent()
    at flash.display::Stage3D/flash::display::Stage3D::requestContext3D_internal()
    at MethodInfo-2283()
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) UHD Graphics 610 (0x00003E90) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: "WebGL 2.0 (OpenGL ES 3.0 Chromium)"
Enabled features: Features(TEXTURE_COMPRESSION_BC | FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES)
Available features: Features(DEPTH32FLOAT_STENCIL8 | PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_color_attachments: 8, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (800, 600, 1)

# Page Info
Page URL: https://www.minijuegos.com/helpers/game/sandbox.php?mp_assets=https%3A%2F%2Fs2.minijuegosgratis.com%2F&mp_embed=0&mp_game_id=206531&mp_game_uid=tequila-zombies-3&mp_game_url=https%3A%2F%2Fwww.minijuegos.com%2Fembed%2Ftequila-zombies-3&mp_int=1&mp_locale=es_ES&mp_player_type=FLASH&mp_player_url=aHR0cHM6Ly93d3cubWluaWp1ZWdvc2dyYXRpcy5jb20vdjMvZ2FtZXMvZ2FtZXMvcHJvZC8yMDY1MzEvdGVxdWlsYS0zLnN3Zg%3D%3D&mp_site_https_url=https%3A%2F%2Fwww.minijuegos.com%2F&mp_site_name=minijuegos.com&mp_site_url=https%3A%2F%2Fwww.minijuegos.com%2F&mp_timezone=America%2FGuayaquil&mp_view_type=
SWF URL: https://www.minijuegosgratis.com/v3/games/games/prod/206531/tequila-3.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-09-14
Channel: nightly
Built: 2024-09-14T00:05:30.925Z
Commit: 7d1373368b0f0b327f69f5d8751a4c49d1e266f1
Is extension: false

# Metadata
width: 800
height: 600
frameRate: 30
numFrames: 2
swfVersion: 21
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 38081696

**Comment by torokati44** [comment]
This supposedly got fixed by https://github.com/ruffle-rs/ruffle/pull/18046.
