### ISSUE TITLE
Error on http://swordandsandals.top/swords-and-sandals-2-full-version/

### ISSUE THREAD

**Issue by FreeManFreakk** [ruffle-rs/ruffle#17923]
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-22.0.0/src/gles/device.rs:779:52:
called `Result::unwrap()` on an `Err` value: "Unable to create texture object"
Error stack:
```
Error: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-22.0.0/src/gles/device.rs:779:52:
called `Result::unwrap()` on an `Err` value: "Unable to create texture object"
    at n.wbg.__wbg_new_796382978dfd4fb0 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.eff553c567a7ead39869.js:1:83857)
    at ruffle_web.wasm.js_sys::Error::new::hfb561c222a4e70eb (wasm://wasm/ruffle_web.wasm-03212586:wasm-function[12740]:0x985756)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::he535d08ebd1aba14 (wasm://wasm/ruffle_web.wasm-03212586:wasm-function[9796]:0x915500)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h33fe77d38d305ca3 (wasm://wasm/ruffle_web.wasm-03212586:wasm-function[6360]:0x805dca)
    at ruffle_web.wasm.core::panicking::panic_fmt::hde8b7aa66e2831e1 (wasm://wasm/ruffle_web.wasm-03212586:wasm-function[9515]:0x906186)
    at ruffle_web.wasm.core::result::unwrap_failed::h472431483d5eea7f (wasm://wasm/ruffle_web.wasm-03212586:wasm-function[7979]:0x89689c)
    at ruffle_web.wasm.<T as wgpu::context::DynContext>::device_create_texture::hfe32c4c2afa47182 (wasm://wasm/ruffle_web.wasm-03212586:wasm-function[7434]:0x865c4a)
    at ruffle_web.wasm.wgpu::Device::create_texture::hff3b3320b1997cfe (wasm://wasm/ruffle_web.wasm-03212586:wasm-function[5727]:0x7d27fa)
    at ruffle_web.wasm.<ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::create_empty_texture::hedc8a54e06be6179 (wasm://wasm/ruffle_web.wasm-03212586:wasm-function[5509]:0x7bd697)
    at ruffle_web.wasm.ruffle_core::display_object::render_base::hefc0535cc81d7732 (wasm://wasm/ruffle_web.wasm-03212586:wasm-function[807]:0x101cf6)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (AMD, Radeon RX 580 Series (0x000067DF) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: "WebGL 2.0 (OpenGL ES 3.0 Chromium)"
Enabled features: Features(TEXTURE_COMPRESSION_BC | FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES)
Available features: Features(DEPTH32FLOAT_STENCIL8 | PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_color_attachments: 8, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)

# Page Info
Page URL: http://swordandsandals.top/swords-and-sandals-2-full-version/
SWF URL: http://swordandsandals.top/wp-content/uploads/swords-and-sandals-2.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-09-14
Channel: nightly
Built: 2024-09-14T00:05:30.925Z
Commit: 7d1373368b0f0b327f69f5d8751a4c49d1e266f1
Is extension: false

# Metadata
width: 640
height: 420
frameRate: 30
numFrames: 277
swfVersion: 8
backgroundColor: #FFCC66
isActionScript3: false
uncompressedLength: 5282134

**Comment by Lord-McSweeney** [comment]
Duplicate of #18248
