### ISSUE TITLE
Error on https://game253127.konggames.com/games/BerzerkStudio/zombidle/frame/e345f000-e5cf-43e8-98eb-03abb6336fb4/

### ISSUE THREAD

**Issue by estani** [ruffle-rs/ruffle#17980]
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/git/checkouts/rust-flash-lso-7db697fbf6bd96f3/98679aa/flash-lso/src/amf3/read.rs:435:14:
Unable to get Object
Error stack:
```
Error: panicked at /home/runner/.cargo/git/checkouts/rust-flash-lso-7db697fbf6bd96f3/98679aa/flash-lso/src/amf3/read.rs:435:14:
Unable to get Object
    at n.wbg.__wbg_new_796382978dfd4fb0 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.98119c25bc73657c8ea8.js:1:83857)
    at ruffle_web.wasm.js_sys::Error::new::hfb561c222a4e70eb (wasm://wasm/ruffle_web.wasm-03213e2a:wasm-function[12736]:0x985945)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::h8a2a563fa204b611 (wasm://wasm/ruffle_web.wasm-03213e2a:wasm-function[9790]:0x91578d)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h33fe77d38d305ca3 (wasm://wasm/ruffle_web.wasm-03213e2a:wasm-function[6356]:0x8057fe)
    at ruffle_web.wasm.core::panicking::panic_fmt::hde8b7aa66e2831e1 (wasm://wasm/ruffle_web.wasm-03213e2a:wasm-function[9512]:0x9064e0)
    at ruffle_web.wasm.core::option::expect_failed::hacfbd4e0f8d6ca3b (wasm://wasm/ruffle_web.wasm-03213e2a:wasm-function[8887]:0x8e4aaf)
    at ruffle_web.wasm.flash_lso::amf3::read::AMF3Decoder::parse_single_element::h1c9def9900e85592 (wasm://wasm/ruffle_web.wasm-03213e2a:wasm-function[795]:0xe60de)
    at ruffle_web.wasm.ruffle_core::avm2::globals::flash::utils::byte_array::read_object::h82856d43eb7b85b4 (wasm://wasm/ruffle_web.wasm-03213e2a:wasm-function[953]:0x24eb97)
    at ruffle_web.wasm.ruffle_core::avm2::function::exec::hb8d085b2d02c4fdb (wasm://wasm/ruffle_web.wasm-03213e2a:wasm-function[1328]:0x3aca3d)
    at ruffle_web.wasm.ruffle_core::avm2::object::TObject::call_method::h853e955a0e789809 (wasm://wasm/ruffle_web.wasm-03213e2a:wasm-function[2446]:0x59e5f9)
```
AVM2 stack:
```
    at flash.utils::ByteArray/flash::utils::ByteArray::readObject()
    at com.berzerkstudio::ModelFla/loadFromByteArray()
    at com.lachhhStarling.berzerk::BerzerkZipModelFlaLoader/loadNextFla()
    at com.lachhhStarling.berzerk::BerzerkZipModelFlaLoader/loadBunch()
    at com.lachhhStarling.berzerk::BerzerkZipModelFlaLoader/loadAllFlas()
    at com.zombidle::MainGameWebStarling/loadModelFlas()
    at com.zombidle::MainGameWebStarling/loadZipFile()
    at Function/apply()
    at com.lachhh.io::Callback/call()
    at com.lachhhStarling::StarlingMain$/startGame()
    at MethodInfo-5838()
    at starling.utils::AssetManager/loadQueue()
    at com.lachhhStarling::StarlingMain$/loadAssetsDesktop()
    at MethodInfo-5836()
    at starling.events::EventDispatcher/invokeEvent()
    at starling.events::EventDispatcher/dispatchEvent()
    at starling.events::EventDispatcher/dispatchEventWith()
    at starling.core::Starling/initializeRoot()
    at starling.core::Starling/initialize()
    at starling.core::Starling/onContextCreated()
    at flash.events::EventDispatcher/flash::events::EventDispatcher::dispatchEvent()
    at flash.display::Stage3D/flash::display::Stage3D::requestContext3D_internal()
    at MethodInfo-2283()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Apple, ANGLE Metal Renderer: Apple M1 Pro, Unspecified Version)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: "WebGL 2.0 (OpenGL ES 3.0 Chromium)"
Enabled features: Features(TEXTURE_COMPRESSION_BC | FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES)
Available features: Features(DEPTH32FLOAT_STENCIL8 | TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | TEXTURE_COMPRESSION_ASTC_HDR | PUSH_CONSTANTS | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_color_attachments: 8, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)

# Page Info
Page URL: https://game253127.konggames.com/games/BerzerkStudio/zombidle/frame/e345f000-e5cf-43e8-98eb-03abb6336fb4/?kongregate_host=www.kongregate.com
SWF URL: https://game253127.konggames.com/gamez/0025/3127/live/ZI_FGL.swf?kongregate_game_version=1570126011

# Browser Info
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
Platform: MacIntel
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-09-18
Channel: nightly
Built: 2024-09-18T00:05:43.159Z
Commit: 35f1fda4b2eb363696842b4d4fc23a9ad8cf0e0f
Is extension: false

# Metadata
width: 960
height: 640
frameRate: 60
numFrames: 2
swfVersion: 14
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 64218669

**Comment by CUB3D** [comment]
Likely a dupe of #17782
