### ISSUE TITLE
Error "panicked at 'cannot recursively acquire mutex'" after pausing the game.

### ISSUE THREAD

**Issue by ItsGravix** [ruffle-rs/ruffle#1806]
I called `rufflePlayer.pause()` on my game, and this is what I get. Music still keeps playing after receiving this error.

# Error Info
Error name: Error
Error message: panicked at 'cannot recursively acquire mutex', C:\Users\Gravix\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib/rustlib/src/rust\src/libstd/macros.rs:13:23
Error stack:
```
Error: panicked at 'cannot recursively acquire mutex', C:\Users\Gravix\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib/rustlib/src/rust\src/libstd/macros.rs:13:23
    at Object.X (http://127.0.0.1:1959/editor/external/CPRClient/assets/lib/ruffle/core.ruffle.da582bc5014c8eebda92.js:1:20372)
    at __wbg_new_df6e6ab7a65c4c4d (<anonymous>:1:34986)
    at http://127.0.0.1:1959/editor/external/CPRClient/assets/lib/ruffle/54d69e17fef57cd18f7e.module.wasm:wasm-function[1038]:0x20f50a
    at http://127.0.0.1:1959/editor/external/CPRClient/assets/lib/ruffle/54d69e17fef57cd18f7e.module.wasm:wasm-function[1417]:0x258648
    at http://127.0.0.1:1959/editor/external/CPRClient/assets/lib/ruffle/54d69e17fef57cd18f7e.module.wasm:wasm-function[3674]:0x301fd5
    at http://127.0.0.1:1959/editor/external/CPRClient/assets/lib/ruffle/54d69e17fef57cd18f7e.module.wasm:wasm-function[2907]:0x2e4fc0
    at http://127.0.0.1:1959/editor/external/CPRClient/assets/lib/ruffle/54d69e17fef57cd18f7e.module.wasm:wasm-function[3974]:0x306e2c
    at http://127.0.0.1:1959/editor/external/CPRClient/assets/lib/ruffle/54d69e17fef57cd18f7e.module.wasm:wasm-function[1971]:0x29e276
    at ruffle_pause (http://127.0.0.1:1959/editor/external/CPRClient/assets/lib/ruffle/54d69e17fef57cd18f7e.module.wasm:wasm-function[3651]:0x301818)
    at I.pause (http://127.0.0.1:1959/editor/external/CPRClient/assets/lib/ruffle/core.ruffle.da582bc5014c8eebda92.js:1:19686)
```

# Player Info
Allows script access: true

# Page Info
Page URL: http://127.0.0.1:1959/editor/external/CPRClient/?ip=ws://127.0.0.1:7070&ssl=false&debug=true

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2020-12-01
Channel: nightly
Built: 2020-12-01T16:45:13.406Z
Commit: 25e7ec99a0980cd90a0184bd4312f474d6973136

**Comment by Herschel** [comment]
This is caused by a call chain going from Flash ExternalInterface -> JS -> back to RufflePlayer. The `pause` call tries to grab the lock to the player again while it's still being held, which panics.

In this specific case, we could remove the `is_playing` parameter from the player and move it to the JS frontend, which is probably better anyway. But the same issue could occur with other APIs.

We could prohibit resurcively calling back into the core; this is also mentioned in the ExternalInterface API docs:
https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/external/ExternalInterface.html#call()
"if there is no such function in the container, the interface is not available, *a recursion occurred (with a Netscape or Opera browser)*, or there is a security issue– null is returned and an error is thrown."

**Comment by Herschel** [comment]
Hi @ItsGravix, is this still an issue?
