### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by RuslanIschuk** [ruffle-rs/ruffle#18159]
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-22.0.0/src/gles/device.rs:779:52:
called `Result::unwrap()` on an `Err` value: "Unable to create texture object"
Error stack:
```
Error: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-22.0.0/src/gles/device.rs:779:52:
called `Result::unwrap()` on an `Err` value: "Unable to create texture object"
    at n.wbg.__wbg_new_796382978dfd4fb0 (https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.ed7d2583e9291124a46c.js:1:83857)
    at ruffle_web.wasm.js_sys::Error::new::hea22a414f237eb04 (wasm://wasm/ruffle_web.wasm-0321209a:wasm-function[12737]:0x9846ee)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::he009475d8c349687 (wasm://wasm/ruffle_web.wasm-0321209a:wasm-function[9797]:0x9152b3)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h33fe77d38d305ca3 (wasm://wasm/ruffle_web.wasm-0321209a:wasm-function[6387]:0x80f7b0)
    at ruffle_web.wasm.core::panicking::panic_fmt::hde8b7aa66e2831e1 (wasm://wasm/ruffle_web.wasm-0321209a:wasm-function[9520]:0x906097)
    at ruffle_web.wasm.core::result::unwrap_failed::h472431483d5eea7f (wasm://wasm/ruffle_web.wasm-0321209a:wasm-function[7991]:0x896856)
    at ruffle_web.wasm.<T as wgpu::context::DynContext>::device_create_texture::heeabd866a14a49b5 (wasm://wasm/ruffle_web.wasm-0321209a:wasm-function[7452]:0x86919c)
    at ruffle_web.wasm.wgpu::Device::create_texture::ha36da400147b31c3 (wasm://wasm/ruffle_web.wasm-0321209a:wasm-function[5748]:0x7d9cde)
    at ruffle_web.wasm.<ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::create_empty_texture::h576e4a577a45ebb9 (wasm://wasm/ruffle_web.wasm-0321209a:wasm-function[5520]:0x7c4294)
    at ruffle_web.wasm.ruffle_core::display_object::render_base::h0b24143ecb153fcd (wasm://wasm/ruffle_web.wasm-0321209a:wasm-function[808]:0x10bb7a)
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) UHD Graphics 620 (0x00005917) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: "WebGL 2.0 (OpenGL ES 3.0 Chromium)"
Enabled features: Features(TEXTURE_COMPRESSION_BC | FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES)
Available features: Features(DEPTH32FLOAT_STENCIL8 | PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_color_attachments: 8, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.67&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1727928910%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F592000%2F592473_MadnessGame_ULTIMATE.swf%3F1507662264%22%2C%22vars%22%3A%7B%22ngio_session_id%22%3A%2227711231.3dc9cc4bc9ef6699155229cdecebe61f932a093ed2d85e%22%2C%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%2266fe9d0538a61%22%2C%22NewgroundsAPI_SessionID%22%3A%22skdROwAtE66y8wI8sFmx5a5e7a78f120dd2a1612d12268085f4e0cf947c7EHXK%22%2C%22NewgroundsAPI_UserName%22%3A%22Ruslan-Ischuk%22%2C%22NewgroundsAPI_UserID%22%3A11389124%2C%22ng_username%22%3A%22Ruslan-Ischuk%22%7D%2C%22width%22%3A850%2C%22height%22%3A530%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F592000%2Fflash_592473_card.webp%3Ff1669742379%22%2C%22warnOnUnsupportedContent%22%3Afalse%7D
SWF URL: https://uploads.ungrounded.net/592000/592473_MadnessGame_ULTIMATE.swf?1507662264

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-10-03
Channel: nightly
Built: 2024-10-03T00:06:04.800Z
Commit: b5b5e76e4ac389bb02269cbd6066ccd6b959a323
Is extension: false

# Metadata
width: 850
height: 530
frameRate: 30
numFrames: 30
swfVersion: 10
backgroundColor: #FFFFFF
isActionScript3: false
uncompressedLength: 20491352

**Comment by Lord-McSweeney** [comment]
Duplicate of #12236
