### ISSUE TITLE
Error on https://newcp.net/play/gameframe.html

### ISSUE THREAD

**Issue by zukitrukis** [ruffle-rs/ruffle#18191]
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-22.1.0/src/backend/wgpu_core.rs:3411:5:
wgpu error: Validation Error

Caused by:
  In Device::create_buffer
    Not enough memory left.

Error stack:
```
Error: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-22.1.0/src/backend/wgpu_core.rs:3411:5:
wgpu error: Validation Error

Caused by:
  In Device::create_buffer
    Not enough memory left.


    at n.wbg.__wbg_new_796382978dfd4fb0 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.dcfa3c9d8d109b5ae831.js:1:83857)
    at ruffle_web.wasm.js_sys::Error::new::hea22a414f237eb04 (wasm://wasm/ruffle_web.wasm-03223006:wasm-function[12745]:0x9886b8)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::he009475d8c349687 (wasm://wasm/ruffle_web.wasm-03223006:wasm-function[9803]:0x918ca0)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h33fe77d38d305ca3 (wasm://wasm/ruffle_web.wasm-03223006:wasm-function[6378]:0x8112e3)
    at ruffle_web.wasm.core::panicking::panic_fmt::hde8b7aa66e2831e1 (wasm://wasm/ruffle_web.wasm-03223006:wasm-function[9525]:0x909a43)
    at ruffle_web.wasm.core::ops::function::Fn::call::h6819c41ae1e5c14f (wasm://wasm/ruffle_web.wasm-03223006:wasm-function[6597]:0x82a10e)
    at ruffle_web.wasm.<T as wgpu::context::DynContext>::device_create_buffer::he703a4fa13028090 (wasm://wasm/ruffle_web.wasm-03223006:wasm-function[7618]:0x878eb6)
    at ruffle_web.wasm.<wgpu::Device as wgpu::util::device::DeviceExt>::create_buffer_init::h7c1aa22b0c1a4254 (wasm://wasm/ruffle_web.wasm-03223006:wasm-function[1922]:0x4e8339)
    at ruffle_web.wasm.ruffle_render_wgpu::buffer_builder::BufferBuilder::finish::h5dcbc1f7b7913e7e (wasm://wasm/ruffle_web.wasm-03223006:wasm-function[7679]:0x87caa2)
    at ruffle_web.wasm.ruffle_render_wgpu::backend::WgpuRenderBackend<T>::register_shape_internal::h88b2b03d6e90c77e (wasm://wasm/ruffle_web.wasm-03223006:wasm-function[1405]:0x3df78d)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "Adreno (TM) 660"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: "WebGL 2.0 (OpenGL ES 3.0 Chromium)"
Enabled features: Features(FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES)
Available features: Features(DEPTH32FLOAT_STENCIL8 | TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | TEXTURE_COMPRESSION_ASTC_HDR | PUSH_CONSTANTS | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 4096, max_texture_dimension_2d: 4096, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 124, max_color_attachments: 8, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)
Player type: Object
SWF URL: https://media1.newcp.net/play/v2/client/club_penguin.swf?clientVersion=1727567130
Param menu: false
Param quality: high
Param allowscriptaccess: always
Param wmode: direct
Param flashvars: play=https://media1.newcp.net/play/&client=https://media1.newcp.net/play/v2/client/&content=https://media1.newcp.net/play/v2/content/&games=https://media1.newcp.net/play/v2/games/&connectionID=cp68294&a=0&p=1&nau=&nal=&nas=&nad=&lang=es&phrasechat=https://n7vcp1clubpwns.newcp.net/social/autocomplete/v2/search/&isAS3WebServicesOn=true&cacheVersion=0&clientVersion=1727567130&configVersion=1727567130&contentVersion=1727567130&minigameVersion=1727567130
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined
Attribute 6: undefined
Attribute 7: undefined

# Page Info
Page URL: https://newcp.net/play/gameframe.html?cache=1728158066308#/login
SWF URL: https://media1.newcp.net/play/v2/client/club_penguin.swf?clientVersion=1727567130

# Browser Info
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
Platform: Linux armv81
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-10-05
Channel: nightly
Built: 2024-10-05T00:06:07.565Z
Commit: eecb77a26442b9ef7cb9d85fc1b6d4f7f5df6db6
Is extension: false

# Metadata
width: 760
height: 480
frameRate: 24
numFrames: 1
swfVersion: 38
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 1172226

**Comment by zukitrukis** [comment]
se me traba demasiado el juegooooooooo
