### ISSUE TITLE
Crash on https://play.cpimagined.net (depends on #18297)

### ISSUE THREAD

**Issue by ERmilburn02** [ruffle-rs/ruffle#18298]
### Describe what you were doing

When the minigame "Card-Jitsu Snow" inside of Club Penguin is about to start, it crashes due to missing shaders. 

### What does the crash message say?

# Error Info
Error name: Error
Error message: panicked at render/wgpu/src/context3d/current_pipeline.rs:332:54:
Missing shaders!
Error stack:
```
Error: panicked at render/wgpu/src/context3d/current_pipeline.rs:332:54:
Missing shaders!
    at imports.wbg.__wbg_new_796382978dfd4fb0 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/69.js:3802:21)
    at ruffle_web.wasm.js_sys::Error::new::h707edc16dc8b9bc8 (wasm://wasm/ruffle_web.wasm-0322ffd6:wasm-function[12780]:0x98ae76)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::h86f2a265c75437ec (wasm://wasm/ruffle_web.wasm-0322ffd6:wasm-function[9834]:0x91d3b7)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h33fe77d38d305ca3 (wasm://wasm/ruffle_web.wasm-0322ffd6:wasm-function[6383]:0x8142bb)
    at ruffle_web.wasm.core::panicking::panic_fmt::hde8b7aa66e2831e1 (wasm://wasm/ruffle_web.wasm-0322ffd6:wasm-function[9552]:0x90d9e6)
    at ruffle_web.wasm.core::option::expect_failed::hacfbd4e0f8d6ca3b (wasm://wasm/ruffle_web.wasm-0322ffd6:wasm-function[8933]:0x8ec249)
    at ruffle_web.wasm.<ruffle_render_wgpu::context3d::WgpuContext3D as ruffle_render::backend::Context3D>::process_command::h1a1a683103efd0bb (wasm://wasm/ruffle_web.wasm-0322ffd6:wasm-function[771]:0x6f338)
    at ruffle_web.wasm.ruffle_core::avm2::globals::flash::display3D::context_3d::draw_triangles::heccb8f223e002523 (wasm://wasm/ruffle_web.wasm-0322ffd6:wasm-function[3658]:0x6ba113)
    at ruffle_web.wasm.ruffle_core::avm2::function::exec::hbb0dcd888b853831 (wasm://wasm/ruffle_web.wasm-0322ffd6:wasm-function[1356]:0x3b6ea7)
    at ruffle_web.wasm.ruffle_core::avm2::object::TObject::call_method::h3fed44591d3ce2d1 (wasm://wasm/ruffle_web.wasm-0322ffd6:wasm-function[2448]:0x5a0f3c)
```
AVM2 stack:
```
    at flash.display3D::Context3D/flash::display3D::Context3D::drawTriangles()
    at com.disney.alpine.scene::Scene3D/drawTriangles()
    at render3d.assets3D.renderables::MpBillboardRenderable/render()
    at renderGroups::MpRenderGroup/renderAll()
    at render3d.scenes3D::MpScene3D/renderRenderables()
    at com.disney.alpine.scene::Scene3D/render()
    at render3d::SceneGraph3D/update()
    at com.disney::OS/callUpdates()
    at com.disney::OS/safeUpdate()
    at com.disney::OS/onEnterFrame()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA GeForce GTX 1650 (0x00001F99) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: "WebGL 2.0 (OpenGL ES 3.0 Chromium)"
Enabled features: Features(TEXTURE_COMPRESSION_BC | FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES)
Available features: Features(DEPTH32FLOAT_STENCIL8 | PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_color_attachments: 8, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (1578, 976, 1)
Player type: Object
SWF URL: https://media.cpimagined.net/game/mpassets/playclients/r3662/flash_client_base_fp11.swf
Param menu: false
Param quality: high
Param allowscriptaccess: always
Param wmode: direct
Param bgColor: #333
Param flashvars: mpProduct=cjsnow&snfSession=test&pid=101&worldName=cjsnow_1&base_asset_url=https://media.cpimagined.net/game/mpassets&assetServer=https://media.cpimagined.net/game/mpassets&assetSeed=https://media.cpimagined.net/game/mpassets&manifest=https://media.cpimagined.net/game/mpassets/publishdata/r5309/manifest/manifest_tokenized.json&devMode=false&wns=https://play.cpimagined.net&lang=en_US&SWF_ERRORS=https://media.cpimagined.net/game/mpassets/minigames/cjsnow/en_US/deploy/swf/ui/assets/ErrorMessages.swf&SWF_LOADER=https://media.cpimagined.net/game/mpassets/minigames/cjsnow/en_US/deploy/swf/ui/assets/cardjitsu_snowbetapreloader.swf&queryString=battleMode%3D0%26base_asset_url%3Dhttps%3A%2F%2Fmedia.cpimagined.net%2Fgame%2Fmpassets&DEVICE_STRING=large&PLACE=snow_lobby&isMuted=false
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined
Attribute 6: undefined

# Page Info
Page URL: https://play.cpimagined.net/
SWF URL: https://media.cpimagined.net/game/mpassets/playclients/r3662/flash_client_base_fp11.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-10-17
Channel: nightly
Built: 2024-10-17T00:06:10.933Z
Commit: 41598c6fdb7ee797f0a8ee86f25f9c9cd1b9b39a
Is extension: true

# Metadata
width: 1024
height: 768
frameRate: 30
numFrames: 1
swfVersion: 13
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 1225071

### Ruffle Version

nightly 2024-10-17

### Affected platform

Browser's extension

### Operating system

Windows 11 23H2 (22631.4317)

### Additional information

This issue depends on ~~both #18296 (fixed as of at least nightly 2024-12-14) and~~ #18297 getting fixed first, as without them it requires a lot of manual work-arounds in order to get the game client to load properly.

**Comment by torokati44** [comment]
This should be fixed now. Thanks, @AllinolCP!
