### ISSUE TITLE
Cosmo Cabs Crash

### ISSUE THREAD

**Issue by TomFulp** [ruffle-rs/ruffle#18317]
https://www.newgrounds.com/portal/view/427349/format/flash?emulate=flash

After getting through the instructions screen, Cosmo Cabs crashes with this error:

# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-22.0.0/src/gles/device.rs:779:52:
called `Result::unwrap()` on an `Err` value: "Unable to create texture object"
Error stack:
```
Error: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-22.0.0/src/gles/device.rs:779:52:
called `Result::unwrap()` on an `Err` value: "Unable to create texture object"
    at n.wbg.__wbg_new_796382978dfd4fb0 (https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.80738d45489f7f5f6247.js:1:84118)
    at ruffle_web.wasm.js_sys::Error::new::h6cc27b63b536b514 (wasm://wasm/ruffle_web.wasm-0328e5de:wasm-function[12770]:0x9a2161)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::h97b75757bc3b995e (wasm://wasm/ruffle_web.wasm-0328e5de:wasm-function[9755]:0x932552)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::he5c089ac7305193e (wasm://wasm/ruffle_web.wasm-0328e5de:wasm-function[6457]:0x832085)
    at ruffle_web.wasm.core::panicking::panic_fmt::hdc8d2d914c0710e4 (wasm://wasm/ruffle_web.wasm-0328e5de:wasm-function[9480]:0x923112)
    at ruffle_web.wasm.core::result::unwrap_failed::hdbb420d9dacf5a62 (wasm://wasm/ruffle_web.wasm-0328e5de:wasm-function[7966]:0x8afbaf)
    at ruffle_web.wasm.<T as wgpu::context::DynContext>::device_create_texture::h49957921db6a1784 (wasm://wasm/ruffle_web.wasm-0328e5de:wasm-function[7457]:0x88599a)
    at ruffle_web.wasm.wgpu::Device::create_texture::h9ff723e1379eae2e (wasm://wasm/ruffle_web.wasm-0328e5de:wasm-function[5788]:0x7fd170)
    at ruffle_web.wasm.<ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::register_bitmap::hfdf1871484edee70 (wasm://wasm/ruffle_web.wasm-0328e5de:wasm-function[2108]:0x529858)
    at ruffle_web.wasm.ruffle_core::bitmap::bitmap_data::BitmapData::bitmap_handle::h60f13afef21af52b (wasm://wasm/ruffle_web.wasm-0328e5de:wasm-function[2156]:0x538de0)
```
AVM2 stack:
```
    at flash.display::BitmapData/flash::display::BitmapData::draw()
    at net.superflashbros.utils::FullHitTest$/objectHitMask()
    at net.superflashbros.game::Terrain/fullHitTest()
    at net.superflashbros.game::Terrain/hitTest()
    at net.superflashbros.game::World/render()
    at flash.events::EventDispatcher/flash::events::EventDispatcher::dispatchEvent()
    at flash.utils::Timer/onUpdate()
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA GeForce RTX 3080 (0x00002206) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: "WebGL 2.0 (OpenGL ES 3.0 Chromium)"
Enabled features: Features(TEXTURE_COMPRESSION_BC | FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES)
Available features: Features(DEPTH32FLOAT_STENCIL8 | PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_color_attachments: 8, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.67&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1729224944%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F427000%2F427349_Cosmo_Cabs_v03.swf%3F1204074437%22%2C%22vars%22%3A%7B%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%2267130bb9df224%22%2C%22NewgroundsAPI_SessionID%22%3A%22G7pS484BC4F1AXLK3V2s356a192b7913b04c54574d18c28d46e6395428abqKCh%22%2C%22NewgroundsAPI_UserName%22%3A%22TomFulp%22%2C%22NewgroundsAPI_UserID%22%3A1%2C%22ng_username%22%3A%22TomFulp%22%7D%2C%22width%22%3A550%2C%22height%22%3A400%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F427000%2Fflash_427349.gif%3Ff1276814763%22%2C%22warnOnUnsupportedContent%22%3Atrue%7D
SWF URL: https://uploads.ungrounded.net/427000/427349_Cosmo_Cabs_v03.swf?1204074437

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-10-18
Channel: nightly
Built: 2024-10-18T00:06:13.525Z
Commit: 5faa313a70d6ad47af18ad4b2f6517696118ef07
Is extension: false

# Metadata
width: 550
height: 400
frameRate: 15
numFrames: 8
swfVersion: 9
backgroundColor: #16181D
isActionScript3: true
uncompressedLength: 1401295

**Comment by adrian17** [comment]
Yeah, it's us being super inefficient.
The single `bitmapdata.draw` tries to draw a displayobject with 1000+ children with `BlendType.OVERLAY`, each one trying to allocate a 2314x1328 texture because of our current blending implementation; which adds up to ~20GB of VRAM usage.
We do have rough ideas for improving blending, but they've not figured out fully how to do them yet.

**Comment by torokati44** [comment]
Reopening since the PR that fixed it got reverted: https://github.com/ruffle-rs/ruffle/pull/18742
