### ISSUE TITLE
Error on https://newcp.net/play/gameframe.html

### ISSUE THREAD

**Issue by mollyylt** [ruffle-rs/ruffle#18313]
# Error Info
Error name: Error
Error message: panicked at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/sys/sync/mutex/no_threads.rs:20:9:
assertion `left == right` failed: cannot recursively acquire mutex
  left: true
 right: false
Error stack:
```
Error: panicked at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/sys/sync/mutex/no_threads.rs:20:9:
assertion `left == right` failed: cannot recursively acquire mutex
  left: true
 right: false
    at n.wbg.__wbg_new_796382978dfd4fb0 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.80738d45489f7f5f6247.js:1:84118)
    at ruffle_web.wasm.js_sys::Error::new::h6cc27b63b536b514 (wasm://wasm/ruffle_web.wasm-0328e5de:wasm-function[12770]:0x9a2161)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::h97b75757bc3b995e (wasm://wasm/ruffle_web.wasm-0328e5de:wasm-function[9755]:0x932552)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::he5c089ac7305193e (wasm://wasm/ruffle_web.wasm-0328e5de:wasm-function[6457]:0x832085)
    at ruffle_web.wasm.core::panicking::panic_fmt::hdc8d2d914c0710e4 (wasm://wasm/ruffle_web.wasm-0328e5de:wasm-function[9480]:0x923112)
    at ruffle_web.wasm.core::panicking::assert_failed_inner::hac6df1fbe8940f48 (wasm://wasm/ruffle_web.wasm-0328e5de:wasm-function[4497]:0x768ec3)
    at ruffle_web.wasm.core::panicking::assert_failed::hbbfae290663f537c (wasm://wasm/ruffle_web.wasm-0328e5de:wasm-function[10213]:0x94dfd1)
    at ruffle_web.wasm.ruffle_core::loader::Loader::movie_loader::{{closure}}::hecd70566db660abd (wasm://wasm/ruffle_web.wasm-0328e5de:wasm-function[1071]:0x2e5a75)
    at ruffle_web.wasm.<ruffle_web::navigator::WebNavigatorBackend as ruffle_core::backend::navigator::NavigatorBackend>::spawn_future::{{closure}}::h5a40db58c5c5298c (wasm://wasm/ruffle_web.wasm-0328e5de:wasm-function[1195]:0x35af5b)
    at ruffle_web.wasm.wasm_bindgen_futures::queue::Queue::new::{{closure}}::h4d7434f07dbf6190 (wasm://wasm/ruffle_web.wasm-0328e5de:wasm-function[3715]:0x6d7027)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA GeForce RTX 3060 Ti (0x00002489) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: "WebGL 2.0 (OpenGL ES 3.0 Chromium)"
Enabled features: Features(TEXTURE_COMPRESSION_BC | FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES)
Available features: Features(DEPTH32FLOAT_STENCIL8 | PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_color_attachments: 8, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)
Player type: Object
SWF URL: https://media1.newcp.net/play/v2/client/club_penguin.swf?clientVersion=1729121402
Param menu: false
Param quality: high
Param allowscriptaccess: always
Param wmode: direct
Param flashvars: play=https://media1.newcp.net/play/&client=https://media1.newcp.net/play/v2/client/&content=https://media1.newcp.net/play/v2/content/&games=https://media1.newcp.net/play/v2/games/&connectionID=cp68294&a=0&p=1&nau=&nal=&nas=&nad=&lang=en&phrasechat=https://n7vcp1clubpwns.newcp.net/social/autocomplete/v2/search/&isAS3WebServicesOn=true&cacheVersion=0&clientVersion=1729121402&configVersion=1729121402&contentVersion=1729121402&minigameVersion=1729121402
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined
Attribute 6: undefined
Attribute 7: undefined

# Page Info
Page URL: https://newcp.net/play/gameframe.html?cache=1729281142933#/login
SWF URL: https://media1.newcp.net/play/v2/client/club_penguin.swf?clientVersion=1729121402

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-10-18
Channel: nightly
Built: 2024-10-18T00:06:13.525Z
Commit: 5faa313a70d6ad47af18ad4b2f6517696118ef07
Is extension: false

# Metadata
width: 760
height: 480
frameRate: 24
numFrames: 1
swfVersion: 38
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 1172226

**Comment by Lord-McSweeney** [comment]
Duplicate of https://github.com/ruffle-rs/ruffle/issues/18131
