### ISSUE TITLE
segfault with http://www.mejorar-presentaciones.tk/mejorar-presentaciones-presentation.swf

### ISSUE THREAD

**Issue by ousia** [ruffle-rs/ruffle#184]
I don’t know whether this is related to #161 or not.

http://www.mejorar-presentaciones.tk/mejorar-presentaciones-presentation.swf segfaults _Ruffle_.

```
$ RUST_BACKTRACE=full ~/ruffle mejorar-presentaciones-presentation.swf 
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 1741', core/src/shape_utils.rs:523:26
stack backtrace:
   0:     0x55d7f00f1724 - backtrace::backtrace::libunwind::trace::hda41dbcdfba36aa0
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1:     0x55d7f00f1724 - backtrace::backtrace::trace_unsynchronized::h1a8d6e1f8cb3f5d4
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2:     0x55d7f00f1724 - std::sys_common::backtrace::_print_fmt::h610c4127487e10da
                               at src/libstd/sys_common/backtrace.rs:76
   3:     0x55d7f00f1724 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h0722dc552e01bd1d
                               at src/libstd/sys_common/backtrace.rs:60
   4:     0x55d7f01184dc - core::fmt::write::h01edf6dd68a42c9c
                               at src/libcore/fmt/mod.rs:1030
   5:     0x55d7f00ee657 - std::io::Write::write_fmt::hf15985f193f03c04
                               at src/libstd/io/mod.rs:1412
   6:     0x55d7f00f3c55 - std::sys_common::backtrace::_print::hd8d5d08a1795e743
                               at src/libstd/sys_common/backtrace.rs:64
   7:     0x55d7f00f3c55 - std::sys_common::backtrace::print::hf89a79e3921a2366
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x55d7f00f3c55 - std::panicking::default_hook::{{closure}}::h3a8f42beb3bb8ae3
                               at src/libstd/panicking.rs:196
   9:     0x55d7f00f3946 - std::panicking::default_hook::h8f803b0bc31a5c37
                               at src/libstd/panicking.rs:210
  10:     0x55d7f00f4355 - std::panicking::rust_panic_with_hook::h825f041245da8739
                               at src/libstd/panicking.rs:473
  11:     0x55d7f00f3ef2 - std::panicking::continue_panic_fmt::hbe0378e33481e81b
                               at src/libstd/panicking.rs:380
  12:     0x55d7f00f3de6 - rust_begin_unwind
                               at src/libstd/panicking.rs:307
  13:     0x55d7f011454a - core::panicking::panic_fmt::h527855ce0bc891f6
                               at src/libcore/panicking.rs:85
  14:     0x55d7f0114505 - core::panicking::panic_bounds_check::h3efaadd5b995f90a
                               at src/libcore/panicking.rs:61
  15:     0x55d7f0081c68 - ruffle_core::shape_utils::ShapeConverter::flush_layer::ha4963a37bfcfbb8b
  16:     0x55d7f0080513 - ruffle_core::shape_utils::swf_shape_to_paths::h35ca9b9d834440e9
  17:     0x55d7efd45f09 - ruffle_desktop::render::GliumRenderBackend::register_shape_internal::h72eca2ba119888ca
  18:     0x55d7efd486f4 - <ruffle_desktop::render::GliumRenderBackend as ruffle_core::backend::render::RenderBackend>::register_glyph_shape::h73cc947e1d8d3cd6
  19:     0x55d7f0017352 - ruffle_core::font::Font::from_swf_tag::h33a8198523090ae5
  20:     0x55d7f00635c8 - ruffle_core::display_object::movie_clip::MovieClipData::preload::{{closure}}::h300bd466a3936fa6
  21:     0x55d7f006ace7 - ruffle_core::tag_utils::decode_tags::hecbf1ab641e2f702
  22:     0x55d7f0003279 - ruffle_core::display_object::movie_clip::MovieClip::preload::hc5785be89e097adb
  23:     0x55d7efcd82c4 - ruffle_core::player::Player<Audio,Renderer,Navigator>::new::hdc3234c189d67b63
  24:     0x55d7efcd4c0e - ruffle_desktop::main::hb7dd4ef6d081ee8b
  25:     0x55d7efcc7f53 - std::rt::lang_start::{{closure}}::hf8a16fbf403909ea
  26:     0x55d7f00f3d83 - std::rt::lang_start_internal::{{closure}}::ha04574f12d97cbe2
                               at src/libstd/rt.rs:49
  27:     0x55d7f00f3d83 - std::panicking::try::do_call::h7c2a8488f72db90c
                               at src/libstd/panicking.rs:292
  28:     0x55d7f00fc27a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  29:     0x55d7f00f490d - std::panicking::try::hc3a9b5da4250385d
                               at src/libstd/panicking.rs:271
  30:     0x55d7f00f490d - std::panic::catch_unwind::hf27600bf8c37809a
                               at src/libstd/panic.rs:394
  31:     0x55d7f00f490d - std::rt::lang_start_internal::h409d4f2fe51133b0
                               at src/libstd/rt.rs:48
  32:     0x55d7efcd5ab2 - main
  33:     0x7f95aafb911b - __libc_start_main
                               at ../csu/libc-start.c:308
  34:     0x55d7efca61da - _start
  35:                0x0 - <unknown>
```

I hope it helps.

**Comment by Herschel** [comment]
Caused by a weirdo DefineFont tag (this SWF is created by a third party program). The data for the first glyph of one of the fonts overlaps with the second glyph. I'll have to read in the font data as a whole and use the offsets in the offset table instead of relying on the glyphs being tightly packed.

**Comment by ousia** [comment]
Yes, this is from _SWFTools_ (I don’t use _Adobe_ products [they don’t even run on _Linux_).

**Comment by ousia** [comment]
No segfault as with Nightly 2020-11-15.

Many thanks for your excellent work.
