### ISSUE TITLE
Buzzbuster crashes on startup

### ISSUE THREAD

**Issue by TomFulp** [ruffle-rs/ruffle#18628]
# Error Info
Error name: Error
Error message: panicked at core/src/display_object/movie_clip.rs:2891:16:
already borrowed: BorrowMutError
Error stack:
```
Error: panicked at core/src/display_object/movie_clip.rs:2891:16:
already borrowed: BorrowMutError
    at n.wbg.__wbg_new_70a2f23d1565c04c (https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.533e39b748b267de0547.js:1:85360)
    at ruffle_web.wasm.js_sys::Error::new::hf99c185550382360 (wasm://wasm/ruffle_web.wasm-031d398e:wasm-function[12822]:0x970fac)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::h7d9c5b3c08f8c110 (wasm://wasm/ruffle_web.wasm-031d398e:wasm-function[9741]:0x8f02ec)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h33fe77d38d305ca3 (wasm://wasm/ruffle_web.wasm-031d398e:wasm-function[6391]:0x818224)
    at ruffle_web.wasm.core::panicking::panic_fmt::hde8b7aa66e2831e1 (wasm://wasm/ruffle_web.wasm-031d398e:wasm-function[9455]:0x8e93e1)
    at ruffle_web.wasm.core::cell::panic_already_borrowed::hb8d645dce0969dae (wasm://wasm/ruffle_web.wasm-031d398e:wasm-function[9276]:0x8e5a04)
    at ruffle_web.wasm.<ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::construct_frame::h7bdc57f99aa70325 (wasm://wasm/ruffle_web.wasm-031d398e:wasm-function[2424]:0x57a1f8)
    at ruffle_web.wasm.<ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::construct_frame::h8efba7eec86d76c5 (wasm://wasm/ruffle_web.wasm-031d398e:wasm-function[2929]:0x5f8a3f)
    at ruffle_web.wasm.<ruffle_core::display_object::stage::Stage as ruffle_core::display_object::TDisplayObject>::construct_frame::he788a4a7a5e565cb (wasm://wasm/ruffle_web.wasm-031d398e:wasm-function[5257]:0x7a1891)
    at ruffle_web.wasm.ruffle_core::frame_lifecycle::run_inner_goto_frame::he760d189f77b626d (wasm://wasm/ruffle_web.wasm-031d398e:wasm-function[2797]:0x5dafb5)
```
AVM2 stack:
```
    at flash.display::MovieClip/flash::display::MovieClip::gotoAndStop()
    at com.newgrounds.components::FlashAdBase()
    at com.newgrounds.components::FlashAd()
    at global$init() [TU=frame1]
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA GeForce RTX 3080 (0x00002206) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: "WebGL 2.0 (OpenGL ES 3.0 Chromium)"
Enabled features: Features(TEXTURE_COMPRESSION_BC | FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES)
Available features: Features(DEPTH32FLOAT_STENCIL8 | TEXTURE_COMPRESSION_BC_SLICED_3D | PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_color_attachments: 8, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.67&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1731820546%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F624000%2F624195_buzzbuster.swf%3F1377899328%22%2C%22vars%22%3A%7B%22ngio_session_id%22%3A%2265048308.50a9bcefaf93769825a12da559a635995ab76848918bb8%22%2C%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%226739fb857e9e4%22%2C%22NewgroundsAPI_SessionID%22%3A%22qGW9kInbmLlQFUl8L7nu356a192b7913b04c54574d18c28d46e6395428abTedb%22%2C%22NewgroundsAPI_UserName%22%3A%22TomFulp%22%2C%22NewgroundsAPI_UserID%22%3A1%2C%22ng_username%22%3A%22TomFulp%22%7D%2C%22width%22%3A400%2C%22height%22%3A640%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F624000%2Fflash_624195_card.png%3Ff1601417111%22%2C%22warnOnUnsupportedContent%22%3Atrue%7D
SWF URL: https://uploads.ungrounded.net/624000/624195_buzzbuster.swf?1377899328

https://www.newgrounds.com/portal/view/624195

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-11-17
Channel: nightly
Built: 2024-11-17T00:06:50.213Z
Commit: 114d24f73109ca6bbeb5784f81fa5b62988d154d
Is extension: false

# Metadata
width: 400
height: 640
frameRate: 24
numFrames: 1
swfVersion: 14
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 1832347

**Comment by Lord-McSweeney** [comment]
This no longer panics, but it doesn't get to the title screen either
