### ISSUE TITLE
Queen Develop Crash Report

### ISSUE THREAD

**Issue by olux997** [ruffle-rs/ruffle#18687]
### Describe what you were doing

[queen-develop.zip](https://github.com/user-attachments/files/17833530/queen-develop.zip)

# Error Info
Error name: Error
Error message: panicked at core/src/avm1/activation.rs:343:14:
AVM1 should always have a root movie
Error stack:
```
Error: panicked at core/src/avm1/activation.rs:343:14:
AVM1 should always have a root movie
    at n.wbg.__wbg_new_70a2f23d1565c04c (http://ruff/core.ruffle.533e39b748b267de0547.js:1:85360)
    at ruffle_web.wasm.js_sys::Error::new::hf99c185550382360 (wasm://wasm/ruffle_web.wasm-031d3bca:wasm-function[12822]:0x971027)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::h7d9c5b3c08f8c110 (wasm://wasm/ruffle_web.wasm-031d3bca:wasm-function[9741]:0x8f0367)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h33fe77d38d305ca3 (wasm://wasm/ruffle_web.wasm-031d3bca:wasm-function[6391]:0x81829f)
    at ruffle_web.wasm.core::panicking::panic_fmt::hde8b7aa66e2831e1 (wasm://wasm/ruffle_web.wasm-031d3bca:wasm-function[9455]:0x8e945c)
    at ruffle_web.wasm.core::option::expect_failed::hacfbd4e0f8d6ca3b (wasm://wasm/ruffle_web.wasm-031d3bca:wasm-function[8892]:0x8da53e)
    at ruffle_web.wasm.ruffle_core::avm1::activation::Activation::from_stub::hde2dcafa69d6c2c7 (wasm://wasm/ruffle_web.wasm-031d3bca:wasm-function[5091]:0x793485)
    at ruffle_web.wasm.ruffle_core::loader::Loader::load_vars_loader::{{closure}}::hbb380b9f800c0376 (wasm://wasm/ruffle_web.wasm-031d3bca:wasm-function[3856]:0x6c727b)
    at ruffle_web.wasm.<ruffle_web::navigator::WebNavigatorBackend as ruffle_core::backend::navigator::NavigatorBackend>::spawn_future::{{closure}}::h5a465eb387de935c (wasm://wasm/ruffle_web.wasm-031d3bca:wasm-function[1532]:0x415385)
    at ruffle_web.wasm.wasm_bindgen_futures::queue::Queue::new::{{closure}}::h22a07629a8fe1e16 (wasm://wasm/ruffle_web.wasm-031d3bca:wasm-function[3698]:0x6a893f)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) HD Graphics 630 (0x0000591B) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: "WebGL 2.0 (OpenGL ES 3.0 Chromium)"
Enabled features: Features(TEXTURE_COMPRESSION_BC | FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES)
Available features: Features(DEPTH32FLOAT_STENCIL8 | TEXTURE_COMPRESSION_BC_SLICED_3D | PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_color_attachments: 8, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-11-18
Channel: nightly
Built: 2024-11-18T00:07:06.463Z
Commit: b7bc3d57c950256fea96d912ce8a1b03a68dd0e5
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 20
numFrames: 1
swfVersion: 10
backgroundColor: #006600
isActionScript3: true
uncompressedLength: 18845610

### What does the crash message say?

Queen Develop Crash Report

### Ruffle Version

Queen Develop Crash Report

### Affected platform

Self-hosted version

### Operating system

windows 10

### Additional information

Queen Develop Crash Report

**Comment by kjarosh** [comment]
It looks like it's caused by the depth list desync. Stage does have one child that thinks is at depth 0, but the depth list is empty.
