### ISSUE TITLE
Error on https://game286444.konggames.com/games/clarusvictoria/pre-civilization-marble-age/frame/a68ebb3b-8256-4613-8ac5-46954c9c13fb/

### ISSUE THREAD

**Issue by ShrekStan** [ruffle-rs/ruffle#18693]
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-23.0.0/src/backend/wgpu_core.rs:1222:18:
wgpu error: Validation Error

Caused by:
  In Device::create_texture
    Dimension Y is zero

Error stack:
```
Error: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-23.0.0/src/backend/wgpu_core.rs:1222:18:
wgpu error: Validation Error

Caused by:
  In Device::create_texture
    Dimension Y is zero


    at n.wbg.__wbg_new_70a2f23d1565c04c (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.e1ab5671fe9d69a41e55.js:1:85360)
    at ruffle_web.wasm.js_sys::Error::new::hf99c185550382360 (wasm://wasm/ruffle_web.wasm-031d25c2:wasm-function[12834]:0x97088b)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::h52d59cb7a23c95c3 (wasm://wasm/ruffle_web.wasm-031d25c2:wasm-function[9767]:0x8f000c)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h33fe77d38d305ca3 (wasm://wasm/ruffle_web.wasm-031d25c2:wasm-function[6415]:0x8187dc)
    at ruffle_web.wasm.core::panicking::panic_fmt::hde8b7aa66e2831e1 (wasm://wasm/ruffle_web.wasm-031d25c2:wasm-function[9477]:0x8e8e08)
    at ruffle_web.wasm.wgpu::backend::wgpu_core::ContextWgpuCore::handle_error_inner::ha745257bc9204404 (wasm://wasm/ruffle_web.wasm-031d25c2:wasm-function[2633]:0x5b4f82)
    at ruffle_web.wasm.<T as wgpu::context::DynContext>::device_create_texture::hc9949bcd9bcf22e4 (wasm://wasm/ruffle_web.wasm-031d25c2:wasm-function[8634]:0x8c9b25)
    at ruffle_web.wasm.wgpu::api::device::Device::create_texture::h023abd201b274079 (wasm://wasm/ruffle_web.wasm-031d25c2:wasm-function[6807]:0x832ed7)
    at ruffle_web.wasm.<ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::register_bitmap::h05f48139215bb17d (wasm://wasm/ruffle_web.wasm-031d25c2:wasm-function[2166]:0x50efb7)
    at ruffle_web.wasm.ruffle_core::bitmap::bitmap_data::BitmapData::bitmap_handle::ha00bd82d832f1eb0 (wasm://wasm/ruffle_web.wasm-031d25c2:wasm-function[2114]:0x4ff24d)
```
AVM2 stack:
```
    at flash.display::BitmapData/flash::display::BitmapData::draw()
    at com.emibap.textureAtlas::DynamicAtlas$/drawItem()
    at com.emibap.textureAtlas::DynamicAtlas$/fromMovieClipContainer()
    at Asset$/loadAtlas()
    at Asset$/init()
    at Classes$/init()
    at MainMenu()
    at starling.core::Starling/initializeRoot()
    at starling.core::Starling/initialize()
    at starling.core::Starling/onContextCreated()
    at flash.events::EventDispatcher/flash::events::EventDispatcher::dispatchEvent()
    at flash.display::Stage3D/flash::display::Stage3D::requestContext3D_internal()
    at MethodInfo-2291()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA GeForce RTX 3060 Ti (0x00002414) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: "WebGL 2.0 (OpenGL ES 3.0 Chromium)"
Enabled features: Features(TEXTURE_COMPRESSION_BC | FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES)
Available features: Features(DEPTH32FLOAT_STENCIL8 | TEXTURE_COMPRESSION_BC_SLICED_3D | PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_color_attachments: 8, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)

# Page Info
Page URL: https://game286444.konggames.com/games/clarusvictoria/pre-civilization-marble-age/frame/a68ebb3b-8256-4613-8ac5-46954c9c13fb/?kongregate_host=www.kongregate.com
SWF URL: https://game286444.konggames.com/gamez/0028/6444/live/ma2.9.8GProt.swf?kongregate_game_version=1506420754

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 OPR/114.0.0.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-11-21
Channel: nightly
Built: 2024-11-21T00:06:20.798Z
Commit: ed26f40810aa6773a4bff3a62d02c9a7c7979344
Is extension: false

# Metadata
width: 800
height: 533
frameRate: 30
numFrames: 2
swfVersion: 34
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 9716767

**Comment by Lord-McSweeney** [comment]
Duplicate of #13946
