### ISSUE TITLE
Error on https://flashmuseum.org/thunderax-9k/

### ISSUE THREAD

**Issue by Zarale00** [ruffle-rs/ruffle#18704]
# Error Info
Error name: Error
Error message: panicked at core/src/avm2/globals/flash/display/graphics.rs:109:14:
Ratios should never be null
Error stack:
```
Error: panicked at core/src/avm2/globals/flash/display/graphics.rs:109:14:
Ratios should never be null
    at n.wbg.__wbg_new_70a2f23d1565c04c (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.e1ab5671fe9d69a41e55.js:1:85360)
    at ruffle_web.wasm.js_sys::Error::new::hf99c185550382360 (wasm://wasm/ruffle_web.wasm-031d25c2:wasm-function[12834]:0x97088b)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::h52d59cb7a23c95c3 (wasm://wasm/ruffle_web.wasm-031d25c2:wasm-function[9767]:0x8f000c)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h33fe77d38d305ca3 (wasm://wasm/ruffle_web.wasm-031d25c2:wasm-function[6415]:0x8187dc)
    at ruffle_web.wasm.core::panicking::panic_fmt::hde8b7aa66e2831e1 (wasm://wasm/ruffle_web.wasm-031d25c2:wasm-function[9477]:0x8e8e08)
    at ruffle_web.wasm.core::option::expect_failed::hacfbd4e0f8d6ca3b (wasm://wasm/ruffle_web.wasm-031d25c2:wasm-function[8916]:0x8d9f81)
    at ruffle_web.wasm.ruffle_core::avm2::globals::flash::display::graphics::begin_gradient_fill::h189402fc00ecc30f (wasm://wasm/ruffle_web.wasm-031d25c2:wasm-function[1223]:0x34a370)
    at ruffle_web.wasm.ruffle_core::avm2::function::exec::h103a1cf95be9be72 (wasm://wasm/ruffle_web.wasm-031d25c2:wasm-function[1361]:0x3b6169)
    at ruffle_web.wasm.ruffle_core::avm2::object::TObject::call_method::h1f14700c551816ff (wasm://wasm/ruffle_web.wasm-031d25c2:wasm-function[2430]:0x5782a8)
    at ruffle_web.wasm.ruffle_core::avm2::object::TObject::call_property::h29988b8e08112b3a (wasm://wasm/ruffle_web.wasm-031d25c2:wasm-function[2812]:0x5dc9b3)
```
AVM2 stack:
```
    at flash.display::Graphics/flash::display::Graphics::beginGradientFill()
    at cLoader$text()
    at cLoader()
    at Main$/startLevel()
    at MethodInfo-2318()
    at tTransitionDoors/run()
    at Main$/run()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Mesa Intel(R) UHD Graphics 620 (KBL GT2), OpenGL 4.6)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: "WebGL 2.0 (OpenGL ES 3.0 Chromium)"
Enabled features: Features(TEXTURE_COMPRESSION_BC | FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES)
Available features: Features(DEPTH32FLOAT_STENCIL8 | TEXTURE_COMPRESSION_BC_SLICED_3D | TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 128, max_color_attachments: 8, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (825, 600, 1)

# Page Info
Page URL: https://flashmuseum.org/thunderax-9k/
SWF URL: http://arcadebomb.com/Thundera%20x9k/97b5b812-125c-ace9-6c17-3cdf410dafe2.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-11-22
Channel: nightly
Built: 2024-11-22T00:06:32.302Z
Commit: cec004add72855c0adc6db9aa86494a82d0d5ca0
Is extension: false

# Metadata
width: 480
height: 360
frameRate: 12
numFrames: 21
swfVersion: 9
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 8027492

**Comment by Lord-McSweeney** [comment]
Should have been fixed by #18699
