### ISSUE TITLE
Error on https://chasovnya.msk.ru/test.php

### ISSUE THREAD

**Issue by Kicksback** [ruffle-rs/ruffle#18811]
# Error Info
Error name: Error
Error message: panicked at core/src/html/layout.rs:399:48:
called `Option::unwrap()` on a `None` value
Error stack:
```
Error: panicked at core/src/html/layout.rs:399:48:
called `Option::unwrap()` on a `None` value
    at n.wbg.__wbg_new_70a2f23d1565c04c (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.1bb0d7819817410a0695.js:1:85360)
    at ruffle_web.wasm.js_sys::Error::new::hc7430be370242701 (wasm://wasm/ruffle_web.wasm-03229c4a:wasm-function[12865]:0x98663a)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::h1a8fe10950133898 (wasm://wasm/ruffle_web.wasm-03229c4a:wasm-function[9790]:0x9041a4)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h33fe77d38d305ca3 (wasm://wasm/ruffle_web.wasm-03229c4a:wasm-function[6416]:0x82a155)
    at ruffle_web.wasm.core::panicking::panic_fmt::hde8b7aa66e2831e1 (wasm://wasm/ruffle_web.wasm-03229c4a:wasm-function[9502]:0x8fd257)
    at ruffle_web.wasm.core::panicking::panic::hcaca2598a27ec0fc (wasm://wasm/ruffle_web.wasm-03229c4a:wasm-function[9972]:0x915ae8)
    at ruffle_web.wasm.core::option::unwrap_failed::h9aa82eb71128b127 (wasm://wasm/ruffle_web.wasm-03229c4a:wasm-function[12351]:0x96344d)
    at ruffle_web.wasm.ruffle_core::html::layout::LayoutContext::fixup_line::hb75da25946570994 (wasm://wasm/ruffle_web.wasm-03229c4a:wasm-function[890]:0x192f58)
    at ruffle_web.wasm.ruffle_core::html::layout::lower_from_text_spans_known_width::h3bf6d46fd7b8ee5d (wasm://wasm/ruffle_web.wasm-03229c4a:wasm-function[982]:0x25eb60)
    at ruffle_web.wasm.ruffle_core::html::layout::lower_from_text_spans::h0487313abcdcea0e (wasm://wasm/ruffle_web.wasm-03229c4a:wasm-function[4111]:0x70708d)
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) Iris(R) Xe Graphics (0x00009A49) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: "WebGL 2.0 (OpenGL ES 3.0 Chromium)"
Enabled features: Features(TEXTURE_COMPRESSION_BC | FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES)
Available features: Features(DEPTH32FLOAT_STENCIL8 | TEXTURE_COMPRESSION_BC_SLICED_3D | PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_color_attachments: 8, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (2518, 1208, 1)

# Page Info
Page URL: https://chasovnya.msk.ru/test.php
SWF URL: https://chasovnya.msk.ru/chasovnya7.swf?viewer_id=web&i=test.php&

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-11-30
Channel: nightly
Built: 2024-11-30T00:06:12.482Z
Commit: 0c1806badcb0869c609c9191d86fc993cf806133
Is extension: false

# Metadata
width: 609
height: 592
frameRate: 18
numFrames: 260
swfVersion: 15
backgroundColor: #FFFFFF
isActionScript3: false
uncompressedLength: 1605259

**Comment by kjarosh** [comment]
Not related to https://github.com/ruffle-rs/ruffle/pull/18708

Based on static analysis: this panics because font resolution failed and due to that, no box was added to the line (each line has to have at least one box).

By looking at the configuration, I can see the web config refers to fonts (`Helvetica`, `Arial`) that are missing (no `fontSources`).
