### ISSUE TITLE
bug on ruffle

### ISSUE THREAD

**Issue by jttt1000** [ruffle-rs/ruffle#18828]
### Describe what you were doing

app will not open and says, panicked at desktop\src\app.rs:466:14:
GUI controller should be created: No compatible graphics backends of any kind were available

### What does the crash message say?

panicked at desktop\src\app.rs:466:14:
GUI controller should be created: No compatible graphics backends of any kind were available

### Ruffle Version

0.1.0-nightly (130385c564777eb8eab326ec083d76a20845f743 2024-11-30)

### Affected platform

Desktop app

### Operating system

Windows 10.0.18363 (Windows 10 Home) [64-bit]

**Comment by jttt1000** [comment]
app wouldnt open from desktop

**Comment by kjarosh** [comment]
Could you attach the logs that Ruffle produces? Do you have a GPU?
