### ISSUE TITLE
Error on chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/player.html

### ISSUE THREAD

**Issue by figueiredo-jml** [ruffle-rs/ruffle#18935]
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-23.0.1/src/gles/device.rs:785:52:
called `Result::unwrap()` on an `Err` value: "Unable to create texture object"
Error stack:
```
Error: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-23.0.1/src/gles/device.rs:785:52:
called `Result::unwrap()` on an `Err` value: "Unable to create texture object"
    at imports.wbg.__wbg_new_4d81617a04bc1b5b (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/69.js:2877:21)
    at ruffle_web.wasm.js_sys::Error::new::h5021eff635514cb9 (wasm://wasm/ruffle_web.wasm-032474f6:wasm-function[12849]:0x987bb4)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::he83741d9aebac240 (wasm://wasm/ruffle_web.wasm-032474f6:wasm-function[9769]:0x904ceb)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h33fe77d38d305ca3 (wasm://wasm/ruffle_web.wasm-032474f6:wasm-function[6412]:0x82a905)
    at ruffle_web.wasm.core::panicking::panic_fmt::hde8b7aa66e2831e1 (wasm://wasm/ruffle_web.wasm-032474f6:wasm-function[9485]:0x8fdf68)
    at ruffle_web.wasm.core::result::unwrap_failed::h472431483d5eea7f (wasm://wasm/ruffle_web.wasm-032474f6:wasm-function[7986]:0x8a4f26)
    at ruffle_web.wasm.<D as wgpu_hal::dynamic::device::DynDevice>::create_texture::h4e83dc9383b0d48d (wasm://wasm/ruffle_web.wasm-032474f6:wasm-function[8190]:0x8aed7f)
    at ruffle_web.wasm.<T as wgpu::context::DynContext>::device_create_texture::h3388f1ba17c0f049 (wasm://wasm/ruffle_web.wasm-032474f6:wasm-function[8643]:0x8de373)
    at ruffle_web.wasm.wgpu::api::device::Device::create_texture::h89fb65be08dbef56 (wasm://wasm/ruffle_web.wasm-032474f6:wasm-function[6797]:0x844c82)
    at ruffle_web.wasm.<ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::create_empty_texture::he7a16a5057141a28 (wasm://wasm/ruffle_web.wasm-032474f6:wasm-function[5668]:0x7e12f6)
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA GeForce GTX 1060 3GB (0x00001C02) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: "WebGL 2.0 (OpenGL ES 3.0 Chromium)"
Enabled features: Features(TEXTURE_COMPRESSION_BC | FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES)
Available features: Features(DEPTH32FLOAT_STENCIL8 | TEXTURE_COMPRESSION_BC_SLICED_3D | PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_color_attachments: 8, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)

# Page Info
Page URL: chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/player.html

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 OPR/114.0.0.0 (Edition std-1)
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-12-10
Channel: nightly
Built: 2024-12-10T00:07:10.275Z
Commit: 362c8a846fe41b59836e9ca8c306c45317929a8d
Is extension: true

# Metadata
width: 640
height: 420
frameRate: 30
numFrames: 270
swfVersion: 11
backgroundColor: #FFFFFF
isActionScript3: false
uncompressedLength: 7563577

**Comment by Lord-McSweeney** [comment]
Duplicate of #16993
