### ISSUE TITLE
Error on https://www.twoplayergames.org/embed/super-smash-flash-2

### ISSUE THREAD

**Issue by montrealmorrison** [ruffle-rs/ruffle#19003]
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-23.0.1/src/backend/wgpu_core.rs:1196:18:
wgpu error: Validation Error

Caused by:
  In Device::create_buffer
    Not enough memory left.

Error stack:
```
Error: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-23.0.1/src/backend/wgpu_core.rs:1196:18:
wgpu error: Validation Error

Caused by:
  In Device::create_buffer
    Not enough memory left.


    at n.wbg.__wbg_new_4d81617a04bc1b5b (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.5a848ecc57e781affe58.js:1:57779)
    at ruffle_web.wasm.js_sys::Error::new::hbd6599149fe8f1e5 (wasm://wasm/ruffle_web.wasm-031a027e:wasm-function[12837]:0x986e37)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::h1dcc320e3659af23 (wasm://wasm/ruffle_web.wasm-031a027e:wasm-function[9791]:0x90339b)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h33fe77d38d305ca3 (wasm://wasm/ruffle_web.wasm-031a027e:wasm-function[6438]:0x82910f)
    at ruffle_web.wasm.core::panicking::panic_fmt::hde8b7aa66e2831e1 (wasm://wasm/ruffle_web.wasm-031a027e:wasm-function[9511]:0x8fc61e)
    at ruffle_web.wasm.wgpu::backend::wgpu_core::ContextWgpuCore::handle_error_inner::h1e8dafc09190f193 (wasm://wasm/ruffle_web.wasm-031a027e:wasm-function[2641]:0x5c3ad3)
    at ruffle_web.wasm.<T as wgpu::context::DynContext>::device_create_buffer::h26e8525360c3d6fb (wasm://wasm/ruffle_web.wasm-031a027e:wasm-function[8721]:0x8dd924)
    at ruffle_web.wasm.<wgpu::api::device::Device as wgpu::util::device::DeviceExt>::create_buffer_init::h6a43922a4966c9e8 (wasm://wasm/ruffle_web.wasm-031a027e:wasm-function[1847]:0x4b7e15)
    at ruffle_web.wasm.ruffle_render_wgpu::surface::target::CommandTarget::new::h0039dee40ab40039 (wasm://wasm/ruffle_web.wasm-031a027e:wasm-function[1312]:0x3a13a9)
    at ruffle_web.wasm.ruffle_render_wgpu::surface::Surface::draw_commands::h00650eb1d0b7d03a (wasm://wasm/ruffle_web.wasm-031a027e:wasm-function[892]:0x19f289)
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Vulkan 1.3.278 (Intel(R) Graphics (ADL-N) (0x000046D1)), Intel open-source Mesa driver)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: "WebGL 2.0 (OpenGL ES 3.0 Chromium)"
Enabled features: Features(TEXTURE_COMPRESSION_BC | FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES)
Available features: Features(DEPTH32FLOAT_STENCIL8 | TEXTURE_COMPRESSION_BC_SLICED_3D | TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 64, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 112, max_color_attachments: 8, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)

# Page Info
Page URL: https://www.twoplayergames.org/embed/super-smash-flash-2
SWF URL: https://files.twoplayergames.org/files/games/o3/super-smash-flash-2-v1.3/SSF2Beta_v1.3.1.2.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-12-17
Channel: nightly
Built: 2024-12-17T00:06:58.837Z
Commit: c1a4df4c36531910de7bcd69236ee4124692d168
Is extension: false

# Metadata
width: 640
height: 360
frameRate: 30
numFrames: 1
swfVersion: 40
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 3823894

**Comment by montrealmorrison** [comment]
super smash bros flash 2
