### ISSUE TITLE
Error on https://oldswf.com/game/17815

### ISSUE THREAD

**Issue by williamlovecs** [ruffle-rs/ruffle#19034]
# Error Info
Error name: Error
Error message: Failed to load Ruffle WASM
Error stack:
```
Error: Failed to load Ruffle WASM
    at https://s4.zstatic.net/ajax/libs/ruffle-rs/0.1.0-nightly.2024.9.13/ruffle.js:1:314370
    at async on.ensureFreshInstance (https://s4.zstatic.net/ajax/libs/ruffle-rs/0.1.0-nightly.2024.9.13/ruffle.js:1:314248)
    at async on.load (https://s4.zstatic.net/ajax/libs/ruffle-rs/0.1.0-nightly.2024.9.13/ruffle.js:1:317466)
    at async bn.load (https://s4.zstatic.net/ajax/libs/ruffle-rs/0.1.0-nightly.2024.9.13/ruffle.js:1:336392)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://oldswf.com/game/17815

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-09-13
Channel: nightly
Built: 2024-09-13T00:06:10.802Z
Commit: f1da1457ebf86ddad4c27ddd20621b0162a2fa6e
Is extension: false

# Metadata

**Comment by Benman2785** [comment]
dont use Cross-Origin for loading ruffle...
