### ISSUE TITLE
Error on https://flashmuseum.org/saras-cooking-class-homemade-strawberry-ice-cream/

### ISSUE THREAD

**Issue by GEMS1994** [ruffle-rs/ruffle#19057]
# Error Info
Error name: Error
Error message: panicked at core/src/display_object/movie_clip.rs:478:9:
assertion `left == right` failed: Called replace_movie on a clip with LoaderInfo set
  left: Some(LoaderInfoObject(LoaderInfoObject { ptr: 0x199a400 }))
 right: None
Error stack:
```
Error: panicked at core/src/display_object/movie_clip.rs:478:9:
assertion `left == right` failed: Called replace_movie on a clip with LoaderInfo set
  left: Some(LoaderInfoObject(LoaderInfoObject { ptr: 0x199a400 }))
 right: None
    at n.wbg.__wbg_new_6799ef630abee97c (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.d984d23f41d03f120a74.js:1:57598)
    at ruffle_web.wasm.js_sys::Error::new::heb462701c44fe90a (wasm://wasm/ruffle_web.wasm-031a8536:wasm-function[12840]:0x9887c5)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::h4d932a7f3750c764 (wasm://wasm/ruffle_web.wasm-031a8536:wasm-function[9784]:0x90547c)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h33fe77d38d305ca3 (wasm://wasm/ruffle_web.wasm-031a8536:wasm-function[6441]:0x82bd6a)
    at ruffle_web.wasm.core::panicking::panic_fmt::hde8b7aa66e2831e1 (wasm://wasm/ruffle_web.wasm-031a8536:wasm-function[9503]:0x8fe6b0)
    at ruffle_web.wasm.core::panicking::assert_failed_inner::hc95b7725cb4077cb (wasm://wasm/ruffle_web.wasm-031a8536:wasm-function[4501]:0x751b6c)
    at ruffle_web.wasm.ruffle_core::display_object::movie_clip::MovieClip::replace_with_movie::h3c70cbb6a97b872c (wasm://wasm/ruffle_web.wasm-031a8536:wasm-function[2049]:0x4fe981)
    at ruffle_web.wasm.ruffle_core::loader::Loader::movie_loader::{{closure}}::h66ad3c3173ef67a4 (wasm://wasm/ruffle_web.wasm-031a8536:wasm-function[1079]:0x2ccfb7)
    at ruffle_web.wasm.<ruffle_web::navigator::WebNavigatorBackend as ruffle_core::backend::navigator::NavigatorBackend>::spawn_future::{{closure}}::h1acde55187ab34ee (wasm://wasm/ruffle_web.wasm-031a8536:wasm-function[1347]:0x3b6f8a)
    at ruffle_web.wasm.wasm_bindgen_futures::queue::Queue::new::{{closure}}::hb037ecf550cc427c (wasm://wasm/ruffle_web.wasm-031a8536:wasm-function[3718]:0x6b9dc1)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) UHD Graphics (0x00009B41) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: "WebGL 2.0 (OpenGL ES 3.0 Chromium)"
Enabled features: Features(TEXTURE_COMPRESSION_BC | FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES)
Available features: Features(DEPTH32FLOAT_STENCIL8 | TEXTURE_COMPRESSION_BC_SLICED_3D | PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_color_attachments: 8, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (687, 500, 1)

# Page Info
Page URL: https://flashmuseum.org/saras-cooking-class-homemade-strawberry-ice-cream/
SWF URL: http://www8.agame.com/mirror/flash/c/cookinggamesggg/files/homemade-strawberry-ice-cream.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-12-24
Channel: nightly
Built: 2024-12-24T00:06:28.268Z
Commit: 049cae3759d842dd777cfaef02131cb49ebaf878
Is extension: false

# Metadata
width: 600
height: 500
frameRate: 30
numFrames: 4
swfVersion: 9
backgroundColor: #FB8FCF
isActionScript3: true
uncompressedLength: 1298419

**Comment by GEMS1994** [comment]
very angry

**Comment by GEMS1994** [comment]
so

**Comment by GEMS1994** [comment]
angry
