### ISSUE TITLE
Error in AwayBuilder Live Tool

### ISSUE THREAD

**Issue by cyberix3d2** [ruffle-rs/ruffle#19092]
Hello,

I would like to report an error in the AwayBuilder live tool, a 3D modeling online tool.

http://awaytools.com/awaybuilder/live-tool/

When loading the tool with RuffleJS, the following error occurs:

Console log:
ERROR core/src/avm2/events.rs:429 Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0xe313fb8 }) to handler FunctionObject(FunctionObject { ptr: 0xcb4e08, name: Ok("mx.managers::LayoutManager/doPhasedInstantiationCallback()") }) : ReferenceError: Error #1069: Property getFontMetrics not found on flash.text.engine.ElementFormat and there is no default value.

Thanks in advance!

**Comment by cyberix3d2** [comment]
Now, the Away Builder tool has finished loading, but it has another error:

http://awaytools.com/awaybuilder/live-tool/

# Error Info
Error name: Error
Error message: panicked at render/wgpu/src/context3d/shader_pair.rs:62:91:
called `Result::unwrap()` on an `Err` value: MissingVertexAttributeData
Error stack:
```
Error: panicked at render/wgpu/src/context3d/shader_pair.rs:62:91:
called `Result::unwrap()` on an `Err` value: MissingVertexAttributeData
    at __wbg_new_c9ea13ea803a692e (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/655.js:2487:25)
    at ruffle_web.wasm.<js_sys[ae59b16485bc8f31]::Error>::new::__wbg_new_c9ea13ea803a692e externref shim (wasm://wasm/ruffle_web.wasm-035b4262:wasm-function[12602]:0x9526da)
    at ruffle_web.wasm.ruffle_web[6c7c1bbb583caf98]::global_init::{closure#0} (wasm://wasm/ruffle_web.wasm-035b4262:wasm-function[10552]:0x926015)
    at ruffle_web.wasm.std[9b61791517946214]::panicking::panic_with_hook (wasm://wasm/ruffle_web.wasm-035b4262:wasm-function[6539]:0x82a0ee)
    at ruffle_web.wasm.core[9b3796e30d99ddb7]::panicking::panic_fmt (wasm://wasm/ruffle_web.wasm-035b4262:wasm-function[10816]:0x92b6ca)
    at ruffle_web.wasm.core[9b3796e30d99ddb7]::result::unwrap_failed (wasm://wasm/ruffle_web.wasm-035b4262:wasm-function[9309]:0x8f96ae)
    at ruffle_web.wasm.<ruffle_render_wgpu[1a8f8edd33ae07ed]::context3d::WgpuContext3D as ruffle_render[cc4dd89ac054abcd]::backend::Context3D>::process_command (wasm://wasm/ruffle_web.wasm-035b4262:wasm-function[934]:0x7c94e)
    at ruffle_web.wasm.ruffle_core[1118c8b38c5392c3]::avm2::globals::flash::display3D::context_3d::draw_triangles (wasm://wasm/ruffle_web.wasm-035b4262:wasm-function[4562]:0x7566ee)
    at ruffle_web.wasm.ruffle_core[1118c8b38c5392c3]::avm2::function::exec (wasm://wasm/ruffle_web.wasm-035b4262:wasm-function[1610]:0x40367e)
    at ruffle_web.wasm.<ruffle_core[1118c8b38c5392c3]::avm2::value::Value>::call_method_with_args (wasm://wasm/ruffle_web.wasm-035b4262:wasm-function[2813]:0x5b5825)
```
AVM2 stack:
```
    at flash.display3D::Context3D/drawTriangles()
    at away3d.materials.passes::SegmentPass/render()
    at away3d.materials::MaterialBase/renderPass()
    at away3d.core.render::DefaultRenderer/drawRenderables()
    at away3d.core.render::DefaultRenderer/draw()
    at away3d.core.render::RendererBase/executeRender()
    at away3d.core.render::DefaultRenderer/executeRender()
    at away3d.core.render::RendererBase/render()
    at away3d.containers::View3D/render()
    at awaybuilder.utils.scene::Scene3DManager/loop()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Apple, ANGLE Metal Renderer: Apple M4 Pro, Unspecified Version)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: "WebGL 2.0 (OpenGL ES 3.0 Chromium)"
Enabled features: Features { features_wgpu: FeaturesWGPU(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES), features_webgpu: FeaturesWebGPU(TEXTURE_COMPRESSION_BC | FLOAT32_FILTERABLE) }
Available features: Features { features_wgpu: FeaturesWGPU(TEXTURE_COMPRESSION_ASTC_HDR | PUSH_CONSTANTS | CLEAR_TEXTURE), features_webgpu: FeaturesWebGPU(DEPTH32FLOAT_STENCIL8 | TEXTURE_COMPRESSION_BC_SLICED_3D | TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | TEXTURE_COMPRESSION_ASTC_SLICED_3D) }
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_binding_array_elements_per_shader_stage: 0, max_binding_array_sampler_elements_per_shader_stage: 0, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_color_attachments: 4, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000, max_task_workgroup_total_count: 0, max_task_workgroups_per_dimension: 0, max_mesh_output_layers: 0, max_mesh_multiview_count: 0, max_blas_primitive_count: 0, max_blas_geometry_count: 0, max_tlas_instance_count: 0, max_acceleration_structures_per_shader_stage: 0 }
Surface quality: high
Surface samples: 4
Surface size: (5120, 2400, 1)
Player type: Object
SWF URL: AwayBuilderApplication.swf
Param quality: high
Param bgcolor: #333333
Param wmode: direct
Param allowscriptaccess: sameDomain
Param allowfullscreen: true
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined
Attribute 6: undefined

# Page Info
Page URL: http://awaytools.com/awaybuilder/live-tool/
SWF URL: http://awaytools.com/awaybuilder/live-tool/AwayBuilderApplication.swf

# Browser Info
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/150.0.0.0 Safari/537.36
Platform: MacIntel
Has touch support: false

# Ruffle Info
Version: 0.5.0
Name: 0.5.0
Channel: stable
Built: 2026-08-03T22:27:09.537Z
Commit: a4f5b5256e245693bc9077ef6c6b6abc95490e7f
Is extension: true

# Metadata
width: 500
height: 375
frameRate: 60
numFrames: 2
swfVersion: 20
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 3931648
