### ISSUE TITLE
Crash after using newly integrated bitmapdata a few times

### ISSUE THREAD

**Issue by Txori** [ruffle-rs/ruffle#2009]
In the example at https://www.txori.com/stuff/ruffle/debug/extsprites_r.php
Click the faces a few times, usually 4 or 5 times, to break ruffle.
If needed, sources are there: https://www.txori.com/stuff/ruffle/debug/

# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/gc-arena-0.2.0/src/gc_cell.rs:62:29
Error stack:
```
Error: panicked at 'already borrowed: BorrowMutError', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/gc-arena-0.2.0/src/gc_cell.rs:62:29
    at Object.Y (https://www.txori.com/stuff/ruffle/core.ruffle.8523be3f1afb3ed16c0c.js:1:20617)
    at __wbg_new_df6e6ab7a65c4c4d (https://www.txori.com/stuff/ruffle/ruffle.js:1:35853)
    at https://www.txori.com/stuff/ruffle/dbf98fe6de1f14b77b7a.module.wasm:wasm-function[1117]:0x22cea9
    at https://www.txori.com/stuff/ruffle/dbf98fe6de1f14b77b7a.module.wasm:wasm-function[1457]:0x26f425
    at https://www.txori.com/stuff/ruffle/dbf98fe6de1f14b77b7a.module.wasm:wasm-function[3876]:0x329523
    at https://www.txori.com/stuff/ruffle/dbf98fe6de1f14b77b7a.module.wasm:wasm-function[3036]:0x3092fe
    at https://www.txori.com/stuff/ruffle/dbf98fe6de1f14b77b7a.module.wasm:wasm-function[4179]:0x32e379
    at https://www.txori.com/stuff/ruffle/dbf98fe6de1f14b77b7a.module.wasm:wasm-function[4209]:0x32e8dc
    at https://www.txori.com/stuff/ruffle/dbf98fe6de1f14b77b7a.module.wasm:wasm-function[4082]:0x32cecc
    at https://www.txori.com/stuff/ruffle/dbf98fe6de1f14b77b7a.module.wasm:wasm-function[4210]:0x32e912
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: extsprites.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined

# Page Info
Page URL: https://www.txori.com/stuff/ruffle/debug/extsprites_r.php
SWF URL: https://www.txori.com/stuff/ruffle/debug/extsprites.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2020-12-18
Channel: nightly
Built: 2020-12-18T00:34:17.923Z
Commit: beed570475728423564d319543f95a4f67300382

**Comment by Txori** [comment]
In fact, this error appears once you clicked a face only once. Just wait a few seconds and it should crash.
