### ISSUE TITLE
Flash Introduction has major visual issues

### ISSUE THREAD

**Issue by SoulRepo** [ruffle-rs/ruffle#2069]
Flash Introduction by Tom Fulp has major graphical issues, as many parts of it are stretched far from the original version. I am testing on Chrome 87.
![image](https://user-images.githubusercontent.com/24778461/102865391-aba15600-4403-11eb-9bdb-ba115c2020ba.png)

**Comment by ZingBallyhoo** [comment]
Are you using the extension, Newgrounds' Ruffle integration, or something else? I can't reproduce on https://www.newgrounds.com/portal/view/324411 (ruffle enabled)

**Comment by Herschel** [comment]
Could you press F12 and paste the information output to the console? Thank you!

**Comment by SoulRepo** [comment]
@ZingBallyhoo I'm using the Newgrounds integration.
@Herschel Will do.

**Comment by SoulRepo** [comment]
Here's what I have.
```
ruffle.js loaded
ruffleembed.html?v=1.0.64&browsermode=default&props={"ruffle"%3A"%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1609073615"%2C"public_path"%3A"%2Fruffle_wrapper%2Flib%2F"%2C"swf"%3A"https%3A%2F%2Fuploads.ungrounded.net%2F324000%2F324411_demo.swf%3F1152708349"%2C"vars"%3A{"NewgroundsAPI_PublisherID"%3A1%2C"NewgroundsAPI_SandboxID"%3A"5fe95022965cb"%2C"NewgroundsAPI_SessionID"%3A"0Gbb9nS7XGkNqyP6EUkW35ba13d0afc8a9438d019cd70a20307278c0a523PuHD"%2C"NewgroundsAPI_UserName"%3A"Souliousery"%2C"NewgroundsAPI_UserID"%3A6849677%2C"ng_username"%3A"Souliousery"}%2C"width"%3A600%2C"height"%3A400%2C"icon"%3A"https%3A%2F%2Fpicon.ngfiles.com%2F324000%2Fflash_324411.gif%3Ff1275075712"}:181 audio initialized
ruffle_web_bg.js:1261 Creating WebGL renderer...
ruffle_web_bg.js:1261 Creating WebGL2 context.
ruffle_web_bg.js:1261 Device only supports 2xMSAA
ruffle_web_bg.js:1261 WebGL graphics driver: <unknown>
ruffle_web_bg.js:1261 Minimum audio buffer sample rate: 5512

Unable to use localStorage: Err(JsValue(SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
Error: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at Object.<anonymous> (https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.bbb40c85e6191179c48b.js:1:22887)
    at Object.<anonymous> (https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.bbb40c85e6191179c48b.js:1:19522)
    at __wbg_localStorage_a6fd83fc300473fc (https://uploads.ungrounded.net/ruffle_wrapper/lib/ruffle.js?1609073615:1:41601)
    at https://uploads.ungrounded.net/ruffle_wrapper/lib/1b1712c67d2cce7c4184.module.wasm:wasm-function[3880]:0x32fe6f
    at https://uploads.ungrounded.net/ruffle_wrapper/lib/1b1712c67d2cce7c4184.module.wasm:wasm-function[455]:0x130702
    at ruffle_new (https://uploads.ungrounded.net/ruffle_wrapper/lib/1b1712c67d2cce7c4184.module.wasm:wasm-function[3643]:0x32947f)
    at new W (https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.bbb40c85e6191179c48b.js:1:19748)
    at HTMLElement.<anonymous> (https://uploads.ungrounded.net/ruffle_wrapper/lib/ruffle.js?1609073615:1:16269)
    at Generator.next (<anonymous>)
    at c (https://uploads.ungrounded.net/ruffle_wrapper/lib/ruffle.js?1609073615:1:12436)))
Data will not save.

New Ruffle instance created.
ruffle_web_bg.js:1261 PLAY!
ruffle-player.js:392 Loading SWF file https://uploads.ungrounded.net/324000/324411_demo.swf?1152708349
ruffleembed.html?v=1.0.64&browsermode=default&props={"ruffle"%3A"%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1609073615"%2C"public_path"%3A"%2Fruffle_wrapper%2Flib%2F"%2C"swf"%3A"https%3A%2F%2Fuploads.ungrounded.net%2F324000%2F324411_demo.swf%3F1152708349"%2C"vars"%3A{"NewgroundsAPI_PublisherID"%3A1%2C"NewgroundsAPI_SandboxID"%3A"5fe95022965cb"%2C"NewgroundsAPI_SessionID"%3A"0Gbb9nS7XGkNqyP6EUkW35ba13d0afc8a9438d019cd70a20307278c0a523PuHD"%2C"NewgroundsAPI_UserName"%3A"Souliousery"%2C"NewgroundsAPI_UserID"%3A6849677%2C"ng_username"%3A"Souliousery"}%2C"width"%3A600%2C"height"%3A400%2C"icon"%3A"https%3A%2F%2Fpicon.ngfiles.com%2F324000%2Fflash_324411.gif%3Ff1275075712"}:128 ruffle promise successful
ruffle_web_bg.js:1261 Loaded SWF version 4, with a resolution of 600x400
```

**Comment by Lord-McSweeney** [comment]
@soulthunk can you still reproduce this issue?
