### ISSUE TITLE
Ruffle Error on https://play.cprewritten.net/2020/

### ISSUE THREAD

**Issue by Max-Rodriguez** [ruffle-rs/ruffle#2124]
# Error Info
Error name: Error
Error message: panicked at 'cannot recursively acquire mutex', C:\Users\Gravix\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib/rustlib/src/rust\src/libstd/macros.rs:13:23
Error stack:
```
Error: panicked at 'cannot recursively acquire mutex', C:\Users\Gravix\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib/rustlib/src/rust\src/libstd/macros.rs:13:23
    at Object.X (https://play.cprewritten.net/2020/assets/lib/ruffle/core.ruffle.76384a7c00f1a9593662.js:1:20834)
    at __wbg_new_df6e6ab7a65c4c4d (<anonymous>:1:37870)
    at https://play.cprewritten.net/2020/assets/lib/ruffle/b9c2c2007fce5860f3f6.module.wasm:wasm-function[1269]:0x24c7b7
    at https://play.cprewritten.net/2020/assets/lib/ruffle/b9c2c2007fce5860f3f6.module.wasm:wasm-function[1519]:0x2790fe
    at https://play.cprewritten.net/2020/assets/lib/ruffle/b9c2c2007fce5860f3f6.module.wasm:wasm-function[4024]:0x335b89
    at https://play.cprewritten.net/2020/assets/lib/ruffle/b9c2c2007fce5860f3f6.module.wasm:wasm-function[3167]:0x314d3a
    at https://play.cprewritten.net/2020/assets/lib/ruffle/b9c2c2007fce5860f3f6.module.wasm:wasm-function[4337]:0x33ad29
    at https://play.cprewritten.net/2020/assets/lib/ruffle/b9c2c2007fce5860f3f6.module.wasm:wasm-function[2131]:0x2c63a0
    at ruffle_pause (https://play.cprewritten.net/2020/assets/lib/ruffle/b9c2c2007fce5860f3f6.module.wasm:wasm-function[3999]:0x335325)
    at W.pause (https://play.cprewritten.net/2020/assets/lib/ruffle/core.ruffle.76384a7c00f1a9593662.js:1:20057)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://play.cprewritten.net/2020/
SWF URL: https://play.cprewritten.net/2020/assets/flash/global/games/boot.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2020-12-27
Channel: nightly
Built: 2020-12-27T03:29:29.906Z
Commit: c3811b30f5bf27e1c33939e76f0c4b01ff93c1ef

**Comment by Poopooracoocoo** [comment]
What minigame were you playing?

**Comment by Max-Rodriguez** [comment]
I think this was Dance Contest on club penguin rewritten.
