### ISSUE TITLE
Ruffle throw's error when I switch off Hardware acceleration in Google Chrome

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#2312]
Some people turn it off when they have sync problems with video/audio. I got an error on every game when I switched it off and it didn't run anymore. Is it intended? Does it only work when it's on or is it a bug?

**Comment by Poopooracoocoo** [comment]
also see #672 and #1185

**Comment by ROBERT-MCDOWELL** [comment]
ha ok I see. it's a HW accel. apparently.
I use an old nvidia quadro FX 2700M

**Comment by Herschel** [comment]
We would hopefully fall back to the Canvas backend if HW acceleration is unavailable. Could you post the log from the developer console (F12)?

**Comment by desertking** [comment]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: JsValue(InvalidStateError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
Error: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
    at Object.<anonymous> (https://www.spiele-umsonst.de/ruffle/core.ruffle.fb39aa46f71a4c17d772.js:1:32417)
    at Object.<anonymous> (https://www.spiele-umsonst.de/ruffle/core.ruffle.fb39aa46f71a4c17d772.js:1:19680)
    at __wbg_drawImage_801ad094f4734689 (https://www.spiele-umsonst.de/ruffle/ruffle.js:1:61043)
    at web_sys::features::gen_CanvasRenderingContext2d::CanvasRenderingContext2d::draw_image_with_html_canvas_element::h533b9c690d0b8e36 (https://www.spiele-umsonst.de/ruffle/70264772349ad693cb33.module.wasm:wasm-function[4364]:0x361d1e)
    at <ruffle_render_canvas::WebCanvasRenderBackend as ruffle_core::backend::render::RenderBackend>::pop_mask::ha6a53f4d027e5730 (https://www.spiele-umsonst.de/ruffle/70264772349ad693cb33.module.wasm:wasm-function[1038]:0x2254f5)
    at ruffle_core::display_object::container::TDisplayObjectContainer::render_children::h61a2281d6d9ef1a3 (https://www.spiele-umsonst.de/ruffle/70264772349ad693cb33.module.wasm:wasm-function[1191]:0x24a99a)
    at <ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::render::h98e98b997a7e6488 (https://www.spiele-umsonst.de/ruffle/70264772349ad693cb33.module.wasm:wasm-function[3346]:0x33d175)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render::hed8c4aaca339dfde (https://www.spiele-umsonst.de/ruffle/70264772349ad693cb33.module.wasm:wasm-function[3116]:0x3304cc)
    at ruffle_core::display_object::container::TDisplayObjectContainer::render_children::h61a2281d6d9ef1a3 (https://www.spiele-umsonst.de/ruffle/70264772349ad693cb33.module.wasm:wasm-function[1191]:0x24aae3)
    at <ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::render::h98e98b997a7e6488 (https://www.spiele-umsonst.de/ruffle/70264772349ad693cb33.module.wasm:wasm-function[3346]:0x33d175))', render/canvas/src/lib.rs:685:14

# Player Info
Allows script access: true

# Page Info
Page URL: https://www.spiele-umsonst.de/plazma-burst-forward-to-the-past-t690.html
SWF URL: https://www.spiele-umsonst.de/azad/downloads/flashgames/plazma_burst.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-09
Channel: nightly
Built: 2021-01-09T00:51:37.925Z
Commit: 828dbcb00c0a25b861ad844a49ac058bb63c73c1

**Comment by relrelb** [comment]
Fixed by #7026.
