### ISSUE TITLE
Ruffle Error on http://www.freeworldgroup.com/games6/gameindex/fwgknight2.htm

### ISSUE THREAD

**Issue by freeworldgroup** [ruffle-rs/ruffle#2328]
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/gc-arena-0.2.0/src/gc_cell.rs:62:29
Error stack:
```
Error: panicked at 'already borrowed: BorrowMutError', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/gc-arena-0.2.0/src/gc_cell.rs:62:29
    at Object.J (http://www.freeworldgroup.com/ruffle/core.ruffle.9eec0e753f06015bcd55.js:1:20928)
    at __wbg_new_df6e6ab7a65c4c4d (http://www.freeworldgroup.com/ruffle/ruffle.js:1:38622)
    at std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f (http://www.freeworldgroup.com/ruffle/827bed83bde6126886bf.module.wasm:wasm-function[1474]:0x27899e)
    at std::sync::once::Once::call_inner::h02eac160d339afc2 (http://www.freeworldgroup.com/ruffle/827bed83bde6126886bf.module.wasm:wasm-function[1491]:0x27ba15)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801 (http://www.freeworldgroup.com/ruffle/827bed83bde6126886bf.module.wasm:wasm-function[4122]:0x345e9e)
    at std::panicking::rust_panic_with_hook::h123718ba3bf480af (http://www.freeworldgroup.com/ruffle/827bed83bde6126886bf.module.wasm:wasm-function[3198]:0x3224b3)
    at std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2 (http://www.freeworldgroup.com/ruffle/827bed83bde6126886bf.module.wasm:wasm-function[3748]:0x33c4e6)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925 (http://www.freeworldgroup.com/ruffle/827bed83bde6126886bf.module.wasm:wasm-function[4464]:0x34b500)
    at rust_begin_unwind (http://www.freeworldgroup.com/ruffle/827bed83bde6126886bf.module.wasm:wasm-function[4339]:0x349b9d)
    at core::panicking::panic_fmt::h285dc015a87be5a4 (http://www.freeworldgroup.com/ruffle/827bed83bde6126886bf.module.wasm:wasm-function[4466]:0x34b564)
```

# Player Info
Allows script access: true

# Page Info
Page URL: http://www.freeworldgroup.com/games6/gameindex/fwgknight2.htm
SWF URL: http://www.freeworldgroup.com/games6/fwgknight2/fwgknight2.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-07
Channel: nightly
Built: 2021-01-07T00:50:17.728Z
Commit: 02c591958e4623398b8f283cd56f123b7fdb6788

**Comment by Lord-McSweeney** [comment]
This game seems to have some obfuscated code that Ruffle doesn't handle correctly, which results in several `Unknown AVM1 opcode: Unknown { opcode: 252, data: [3, 0] }` and the game speeds through the intro without stopping.

When clicking the top-most button at the main menu, Ruffle panics with 
```
panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:856:22

Stack:

Error
    at imports.wbg.__wbg_new_abda76e883ba8a5f (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:742:21)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h9058a63962169328 (wasm://wasm/02c3edce:wasm-function[8575]:0x833c23)
    at std::panicking::rust_panic_with_hook::h7f7102b82d51338f (wasm://wasm/02c3edce:wasm-function[5595]:0x757931)
    at core::panicking::panic_fmt::he4489d678d6570d5 (wasm://wasm/02c3edce:wasm-function[8426]:0x82f280)
    at core::panicking::panic::hea78c4e8b318407d (wasm://wasm/02c3edce:wasm-function[7699]:0x7f2ff7)
    at core::ops::function::FnOnce::call_once::h8fd5708e18911197 (wasm://wasm/02c3edce:wasm-function[904]:0x310630)
    at ruffle_core::avm1::function::Executable::exec::h6c9b407eb09c0e2f (wasm://wasm/02c3edce:wasm-function[603]:0x1b53c1)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::hc31f851673e2e015 (wasm://wasm/02c3edce:wasm-function[2643]:0x5a975e)
    at ruffle_core::avm1::activation::Activation::run_actions::h74b67cfb04506d51 (wasm://wasm/02c3edce:wasm-function[502]:0x22c5b)
    at ruffle_core::avm1::function::Executable::exec::h6c9b407eb09c0e2f (wasm://wasm/02c3edce:wasm-function[603]:0x1b51cc)
```
