### ISSUE TITLE
Error on http://momentium.biz/missions/m18e1/launch.php?lc=VDBpae6C

### ISSUE THREAD

**Issue by yohio** [ruffle-rs/ruffle#2429]
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/gc-arena-0.2.0/src/gc_cell.rs:62:29
Error stack:
```
Error: panicked at 'already borrowed: BorrowMutError', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/gc-arena-0.2.0/src/gc_cell.rs:62:29
    at Object.Q (chrome-extension://lmeponjjaheagcabjadlbpbpandmplng/dist/core.ruffle.js:1:21332)
    at __wbg_new_df6e6ab7a65c4c4d (<anonymous>:3:38357)
    at std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f (chrome-extension://lmeponjjaheagcabjadlbpbpandmplng/dist/b4716f96db7fd93a9458.module.wasm:wasm-function[1288]:0x2636a1)
    at std::sync::once::Once::call_inner::h02eac160d339afc2 (chrome-extension://lmeponjjaheagcabjadlbpbpandmplng/dist/b4716f96db7fd93a9458.module.wasm:wasm-function[1539]:0x291d92)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801 (chrome-extension://lmeponjjaheagcabjadlbpbpandmplng/dist/b4716f96db7fd93a9458.module.wasm:wasm-function[4281]:0x3658db)
    at std::panicking::rust_panic_with_hook::h123718ba3bf480af (chrome-extension://lmeponjjaheagcabjadlbpbpandmplng/dist/b4716f96db7fd93a9458.module.wasm:wasm-function[3312]:0x34053c)
    at std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2 (chrome-extension://lmeponjjaheagcabjadlbpbpandmplng/dist/b4716f96db7fd93a9458.module.wasm:wasm-function[3889]:0x35b821)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925 (chrome-extension://lmeponjjaheagcabjadlbpbpandmplng/dist/b4716f96db7fd93a9458.module.wasm:wasm-function[4627]:0x36b02f)
    at rust_begin_unwind (chrome-extension://lmeponjjaheagcabjadlbpbpandmplng/dist/b4716f96db7fd93a9458.module.wasm:wasm-function[4500]:0x36966c)
    at core::panicking::panic_fmt::h285dc015a87be5a4 (chrome-extension://lmeponjjaheagcabjadlbpbpandmplng/dist/b4716f96db7fd93a9458.module.wasm:wasm-function[4629]:0x36b093)
```

# Player Info
Allows script access: true

# Page Info
Page URL: http://momentium.biz/missions/m18e1/launch.php?lc=VDBpae6C
SWF URL: http://momentium.biz/missions/common/container.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-12
Channel: nightly
Built: 2021-01-12T00:55:17.048Z
Commit: 73d123091014e190f4bc4d8edf98cab2e671cc3a

**Comment by dginovker** [comment]
Site is down, isn't on any archive sites. Does the app have a name so we can find it?

**Comment by n0samu** [comment]
The site is still online here: http://momentium.ca/
But it requires registering an account, which in turn requires an access code that I do not have. So I cannot investigate this issue.

**Comment by Lord-McSweeney** [comment]
Closing as the site was using a version of Ruffle that is now 4 years outdated
