### ISSUE TITLE
Error on https://ruffle.rs/demo/

### ISSUE THREAD

**Issue by lemur117** [ruffle-rs/ruffle#2434]
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/gc-arena-0.2.0/src/gc_cell.rs:62:29
Error stack:
```
U@https://ruffle.rs/demo/662.index.js:1:21265
__wbg_new_df6e6ab7a65c4c4d@https://ruffle.rs/demo/index.js:1:50631
std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f@https://ruffle.rs/demo/14d80b2900ca11106a81.module.wasm:wasm-function[1288]:0x2636a1
std::sync::once::Once::call_inner::h02eac160d339afc2@https://ruffle.rs/demo/14d80b2900ca11106a81.module.wasm:wasm-function[1539]:0x291d92
core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801@https://ruffle.rs/demo/14d80b2900ca11106a81.module.wasm:wasm-function[4281]:0x3658db
std::panicking::rust_panic_with_hook::h123718ba3bf480af@https://ruffle.rs/demo/14d80b2900ca11106a81.module.wasm:wasm-function[3312]:0x34053c
std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2@https://ruffle.rs/demo/14d80b2900ca11106a81.module.wasm:wasm-function[3889]:0x35b821
std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925@https://ruffle.rs/demo/14d80b2900ca11106a81.module.wasm:wasm-function[4627]:0x36b02f
rust_begin_unwind@https://ruffle.rs/demo/14d80b2900ca11106a81.module.wasm:wasm-function[4500]:0x36966c
core::panicking::panic_fmt::h285dc015a87be5a4@https://ruffle.rs/demo/14d80b2900ca11106a81.module.wasm:wasm-function[4629]:0x36b093
core::option::expect_none_failed::hb95d2b1dc5448c17@https://ruffle.rs/demo/14d80b2900ca11106a81.module.wasm:wasm-function[3969]:0x35dfe0
ruffle_core::avm2::object::TObject::install_foreign_trait::hfb2804f046af4d5c@https://ruffle.rs/demo/14d80b2900ca11106a81.module.wasm:wasm-function[335]:0xbb753
ruffle_core::avm2::object::TObject::set_property::h97babd6ad7fd796f@https://ruffle.rs/demo/14d80b2900ca11106a81.module.wasm:wasm-function[668]:0x1ab38a
<ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::set_property::hb2527de7a6f78954@https://ruffle.rs/demo/14d80b2900ca11106a81.module.wasm:wasm-function[370]:0xe8091
ruffle_core::avm2::activation::Activation::do_next_opcode::hebafc45a7bb91939@https://ruffle.rs/demo/14d80b2900ca11106a81.module.wasm:wasm-function[285]:0x22339
ruffle_core::avm2::activation::Activation::run_actions::hbf8aa9119c1bed38@https://ruffle.rs/demo/14d80b2900ca11106a81.module.wasm:wasm-function[3035]:0x330589
ruffle_core::avm2::function::Executable::exec::h345a406a7a80a3ba@https://ruffle.rs/demo/14d80b2900ca11106a81.module.wasm:wasm-function[1768]:0x2b49b7
<ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call::h4db5e75023f059c8@https://ruffle.rs/demo/14d80b2900ca11106a81.module.wasm:wasm-function[2378]:0x2fb47b
ruffle_core::avm2::activation::Activation::do_next_opcode::hebafc45a7bb91939@https://ruffle.rs/demo/14d80b2900ca11106a81.module.wasm:wasm-function[285]:0x20aac
ruffle_core::avm2::activation::Activation::run_actions::hbf8aa9119c1bed38@https://ruffle.rs/demo/14d80b2900ca11106a81.module.wasm:wasm-function[3035]:0x330589
ruffle_core::avm2::function::Executable::exec::h345a406a7a80a3ba@https://ruffle.rs/demo/14d80b2900ca11106a81.module.wasm:wasm-function[1768]:0x2b49b7
<ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call::h4db5e75023f059c8@https://ruffle.rs/demo/14d80b2900ca11106a81.module.wasm:wasm-function[2378]:0x2fb47b
ruffle_core::avm2::activation::Activation::super_init::h5dccbf2412ef8631@https://ruffle.rs/demo/14d80b2900ca11106a81.module.wasm:wasm-function[1711]:0x2ac3a0
ruffle_core::avm2::activation::Activation::do_next_opcode::hebafc45a7bb91939@https://ruffle.rs/demo/14d80b2900ca11106a81.module.wasm:wasm-function[285]:0x2511e
ruffle_core::avm2::activation::Activation::run_actions::hbf8aa9119c1bed38@https://ruffle.rs/demo/14d80b2900ca11106a81.module.wasm:wasm-function[3035]:0x330589
ruffle_core::avm2::function::Executable::exec::h345a406a7a80a3ba@https://ruffle.rs/demo/14d80b2900ca11106a81.module.wasm:wasm-function[1768]:0x2b49b7
<ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call::h4db5e75023f059c8@https://ruffle.rs/demo/14d80b2900ca11106a81.module.wasm:wasm-function[2378]:0x2fb47b
ruffle_core::display_object::movie_clip::MovieClip::construct_as_avm2_object::hef9ca116da49941d@https://ruffle.rs/demo/14d80b2900ca11106a81.module.wasm:wasm-function[824]:0x1e753f
ruffle_core::display_object::movie_clip::MovieClip::preload::{{closure}}::hede52f627e31dd28@https://ruffle.rs/demo/14d80b2900ca11106a81.module.wasm:wasm-function[290]:0x50513
ruffle_core::tag_utils::decode_tags::hd683cfe1173875cb@https://ruffle.rs/demo/14d80b2900ca11106a81.module.wasm:wasm-function[1228]:0x256acd
ruffle_core::display_object::movie_clip::MovieClip::preload::h6d2a6cfec4104f16@https://ruffle.rs/demo/14d80b2900ca11106a81.module.wasm:wasm-function[799]:0x1dea50
ruffle_core::player::Player::set_root_movie::h845c3c3e295a8897@https://ruffle.rs/demo/14d80b2900ca11106a81.module.wasm:wasm-function[327]:0xae9be
std::thread::local::LocalKey<T>::with::hbd230a07fdb53262@https://ruffle.rs/demo/14d80b2900ca11106a81.module.wasm:wasm-function[1724]:0x2ae2c8
ruffle_web::Ruffle::load_data::h833f0b896dbe5d4b@https://ruffle.rs/demo/14d80b2900ca11106a81.module.wasm:wasm-function[1700]:0x2aab78
ruffle_load_data@https://ruffle.rs/demo/14d80b2900ca11106a81.module.wasm:wasm-function[4015]:0x35f552
load_data@https://ruffle.rs/demo/662.index.js:1:20243
load/<@https://ruffle.rs/demo/index.js:1:28268
c@https://ruffle.rs/demo/index.js:1:22798

```

# Player Info
Allows script access: false

# Page Info
Page URL: https://ruffle.rs/demo/
SWF URL: https://ruffle.rs/demo/swfs/alien_hominid.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; Ubuntu; Linux aarch64; rv:84.0) Gecko/20100101 Firefox/84.0
OS: Linux aarch64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-12
Channel: nightly
Built: 2021-01-12T00:55:17.048Z
Commit: 73d123091014e190f4bc4d8edf98cab2e671cc3a

**Comment by lemur117** [comment]
The "SWF URL" reported automatically above does not look right, as I tried loading a local SWF of Patterns Link when the issue occurred.  

I also tried building ruffle_desktop from source and loading the patterns_link.swf with it, and I got the same error:
thread 'main' panicked at 'already borrowed: BorrowMutError', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/gc-arena-0.2.0/src/gc_cell.rs:62:29

**Comment by Poopooracoocoo** [comment]
Do you have a link to Patterns Link? I think it'd be easier for the developers :)

**Comment by lemur117** [comment]
I've attached the swf file, and here's a link to the original site: https://www.agame.com/game/patterns-link

[patterns_link.swf.zip](https://github.com/ruffle-rs/ruffle/files/5861604/patterns_link.swf.zip)

**Comment by lemur117** [comment]
Any update on this issue?

**Comment by dginovker** [comment]
Works as of 0.1.0.544

**Comment by Poopooracoocoo** [comment]
Closing as I'm not seeing this panic on Ruffle Nightly 2022-07-26
