### ISSUE TITLE
Error on https://www.newgrounds.com/portal/view/562116

### ISSUE THREAD

**Issue by MercWithMouth** [ruffle-rs/ruffle#2444]
#Well, very simply, I was trying to play REBUILD on Newgrounds, and I got sent to a screen where it said "RUFFLE ENCOUNTERED A BUG." Here's a screenshot: http://my.jetscreenshot.com/2306/20210113-sm8a-80kb 

# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/gc-arena-0.2.0/src/gc_cell.rs:62:29
Error stack:
```
Error: panicked at 'already borrowed: BorrowMutError', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/gc-arena-0.2.0/src/gc_cell.rs:62:29
    at Object.N (chrome-extension://aceohknomfblfmadfgcammjgobjfjmkg/dist/core.ruffle.js:1:21219)
    at __wbg_new_df6e6ab7a65c4c4d (<anonymous>:3:38351)
    at std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f (chrome-extension://aceohknomfblfmadfgcammjgobjfjmkg/dist/aababf0a1e5ed63fc484.module.wasm:wasm-function[1279]:0x25eedb)
    at std::sync::once::Once::call_inner::h02eac160d339afc2 (chrome-extension://aceohknomfblfmadfgcammjgobjfjmkg/dist/aababf0a1e5ed63fc484.module.wasm:wasm-function[1537]:0x28eac1)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801 (chrome-extension://aceohknomfblfmadfgcammjgobjfjmkg/dist/aababf0a1e5ed63fc484.module.wasm:wasm-function[4274]:0x361c64)
    at std::panicking::rust_panic_with_hook::h123718ba3bf480af (chrome-extension://aceohknomfblfmadfgcammjgobjfjmkg/dist/aababf0a1e5ed63fc484.module.wasm:wasm-function[3304]:0x33c6a5)
    at std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2 (chrome-extension://aceohknomfblfmadfgcammjgobjfjmkg/dist/aababf0a1e5ed63fc484.module.wasm:wasm-function[3885]:0x357ce6)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925 (chrome-extension://aceohknomfblfmadfgcammjgobjfjmkg/dist/aababf0a1e5ed63fc484.module.wasm:wasm-function[4618]:0x36733c)
    at rust_begin_unwind (chrome-extension://aceohknomfblfmadfgcammjgobjfjmkg/dist/aababf0a1e5ed63fc484.module.wasm:wasm-function[4492]:0x3659ab)
    at core::panicking::panic_fmt::h285dc015a87be5a4 (chrome-extension://aceohknomfblfmadfgcammjgobjfjmkg/dist/aababf0a1e5ed63fc484.module.wasm:wasm-function[4620]:0x3673a0)
```

# Player Info
Allows script access: false
Player type: Object
SWF URL: https://uploads.ungrounded.net/562000/562116_Rebuilder___newg.swf?123
Param wmode: direct
Param allowscriptaccess: never
Param allowfullscreen: true
Param allowfullscreeninteractive: true
Param flashvars: NewgroundsAPI_PublisherID=1&NewgroundsAPI_SandboxID=5ffe626c6be18&NewgroundsAPI_SessionID=pyh8TfKx6P9pzdi2Eeizd6626beaaa2e2ca91da1c64596773f371e0f1a42tY9j&NewgroundsAPI_UserName=AlphaFactor&NewgroundsAPI_UserID=118199&ng_username=AlphaFactor
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined

# Page Info
Page URL: https://www.newgrounds.com/portal/view/562116
SWF URL: https://uploads.ungrounded.net/562000/562116_Rebuilder___newg.swf?123

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-11
Channel: nightly
Built: 2021-01-11T00:53:04.486Z
Commit: cce3a8199d48ecbce536a0e49efd501d97a2b370

**Comment by n0samu** [comment]
The panic seems to be fixed now. There are some AVM2 issues preventing the game from working, though:
```
AVM2 error: Object(ErrorObject(ErrorObject(GcCell(Gc { ptr: 0xea2e3c }))))
Error: URLRequest.data setter is not yet implemented!
AVM2 error: Object(ErrorObject(ErrorObject(GcCell(Gc { ptr: 0xea2e3c }))))
Error: URLRequest.data setter is not yet implemented!
AVM2 error: Object(ErrorObject(ErrorObject(GcCell(Gc { ptr: 0xea2e3c }))))
Error: URLRequest.data setter is not yet implemented!
AVM2 error: Object(ErrorObject(ErrorObject(GcCell(Gc { ptr: 0xea2e3c }))))
Error: URLRequest.data setter is not yet implemented!
AVM2 error: Object(ErrorObject(ErrorObject(GcCell(Gc { ptr: 0xea2e3c }))))
Error: URLRequest.data setter is not yet implemented!
Got AvmError(Object(ErrorObject(ErrorObject(GcCell(Gc { ptr: 0xea2e3c }))))) when constructing AVM2 side of movie clip of type rebuilder::Rebuilder
AVM2 error: Object(ErrorObject(ErrorObject(GcCell(Gc { ptr: 0x2d7b704 }))))
ReferenceError: Error #1069: Property redMultiplier not found on flash.geom.Matrix and there is no default value.
AVM2 error: Object(ErrorObject(ErrorObject(GcCell(Gc { ptr: 0x2d7b704 }))))
ReferenceError: Error #1069: Property redMultiplier not found on flash.geom.Matrix and there is no default value.
AVM2 error: Object(ErrorObject(ErrorObject(GcCell(Gc { ptr: 0x2d7b704 }))))
ReferenceError: Error #1069: Property redMultiplier not found on flash.geom.Matrix and there is no default value.
AVM2 error: Object(ErrorObject(ErrorObject(GcCell(Gc { ptr: 0x2d7b704 }))))
ReferenceError: Error #1069: Property redMultiplier not found on flash.geom.Matrix and there is no default value.
AVM2 error: Object(ErrorObject(ErrorObject(GcCell(Gc { ptr: 0x2d7b704 }))))
ReferenceError: Error #1069: Property redMultiplier not found on flash.geom.Matrix and there is no default value.
ERROR - Couldn't instanciate the game context. ReferenceError: Error #1069: Property redMultiplier not found on flash.geom.Matrix and there is no default value. null
Could not start the game: Fail while initializing Context.
```

**Comment by Lord-McSweeney** [comment]
No longer panics, but needs XML.

**Comment by Lord-McSweeney** [comment]
Regressed because of #10392. Panic:
```

Error: panicked at 'No caller domain available - use Activation::from_domain when constructing your domain', core/src/avm2/activation.rs:676:9

$core::option::expect_failed::hde6894209e142acf
$ruffle_core::avm2::function::Executable::exec::hf5adae3430b678ba
$ruffle_core::avm2::object::TObject::call_method::h213a28241f9cfd39
$ruffle_core::avm2::object::TObject::init_property::hc75eaa0792a615c3
$<ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::init_property::h667a53127576af13
$ruffle_core::display_object::TDisplayObject::on_construction_complete::hac915a1f4cc208ce


AVM2 stack:

    at flash.display::DisplayObject/flash.display::DisplayObject()
    at flash.display::InteractiveObject/flash.display::InteractiveObject()
    at flash.display::DisplayObjectContainer/flash.display::DisplayObjectContainer()
    at flash.display::Sprite()
    at flash.display::MovieClip()
    at flash.display::DisplayObject/flash.display::DisplayObject()
    at flash.display::InteractiveObject/flash.display::InteractiveObject()
    at flash.display::DisplayObjectContainer/flash.display::DisplayObjectContainer()
    at flash.display::Sprite()
    at flash.display::MovieClip()
    at flash.display::DisplayObject/flash.display::DisplayObject()
    at flash.display::InteractiveObject/flash.display::InteractiveObject()
    at flash.display::DisplayObjectContainer/flash.display::DisplayObjectContainer()
    at flash.display::Sprite()
    at flash.display::MovieClip()
    at flash.display::DisplayObject/flash.display::DisplayObject()
    at flash.display::InteractiveObject/flash.display::InteractiveObject()
    at flash.display::DisplayObjectContainer/flash.display::DisplayObjectContainer()
    at flash.display::Sprite()
    at flash.display::MovieClip()
    at GuiGraphics()
    at rebuilder.gui::Gui()
    at rebuilder.fort::Context$/init()
    at rebuilder.fort::Context()
    at rebuilder::Rebuilder/loadEnterFrame()


# Ruffle Info
Version: 0.1.0
Name: nightly 2023-03-27
Channel: nightly
Built: 2023-03-27T04:39:07.549Z
Commit: 87dad709b8fac1510b8055c006b848663b52cd88
Is extension: true

**Comment by Lord-McSweeney** [comment]
Still stuck on the same issue.

**Comment by sleepycatcoding** [comment]
With #13041 the game progresses and hits a new error `RustError("Modifying an XMLList object is not yet implemented: need to resolve")`
