### ISSUE TITLE
Error on https://chatarcade.co.uk/index.php?ipsproarcade/playgame/1420-craps

### ISSUE THREAD

**Issue by Logan0** [ruffle-rs/ruffle#2464]
# Error Info
Error name: Error
Error message: panicked at 'Bitset contains invalid variants.', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/enumset-1.0.1/src/lib.rs:489:1
Error stack:
```
Error: panicked at 'Bitset contains invalid variants.', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/enumset-1.0.1/src/lib.rs:489:1
    at Object.Q (chrome-extension://eebhlpdjhiligpgajgjoghphfejaillh/dist/core.ruffle.js:1:21332)
    at __wbg_new_df6e6ab7a65c4c4d (<anonymous>:3:38357)
    at std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f (chrome-extension://eebhlpdjhiligpgajgjoghphfejaillh/dist/b4716f96db7fd93a9458.module.wasm:wasm-function[1288]:0x2636a1)
    at std::sync::once::Once::call_inner::h02eac160d339afc2 (chrome-extension://eebhlpdjhiligpgajgjoghphfejaillh/dist/b4716f96db7fd93a9458.module.wasm:wasm-function[1539]:0x291d92)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801 (chrome-extension://eebhlpdjhiligpgajgjoghphfejaillh/dist/b4716f96db7fd93a9458.module.wasm:wasm-function[4281]:0x3658db)
    at std::panicking::rust_panic_with_hook::h123718ba3bf480af (chrome-extension://eebhlpdjhiligpgajgjoghphfejaillh/dist/b4716f96db7fd93a9458.module.wasm:wasm-function[3312]:0x34053c)
    at std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2 (chrome-extension://eebhlpdjhiligpgajgjoghphfejaillh/dist/b4716f96db7fd93a9458.module.wasm:wasm-function[3889]:0x35b821)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925 (chrome-extension://eebhlpdjhiligpgajgjoghphfejaillh/dist/b4716f96db7fd93a9458.module.wasm:wasm-function[4627]:0x36b02f)
    at rust_begin_unwind (chrome-extension://eebhlpdjhiligpgajgjoghphfejaillh/dist/b4716f96db7fd93a9458.module.wasm:wasm-function[4500]:0x36966c)
    at core::panicking::panic_fmt::h285dc015a87be5a4 (chrome-extension://eebhlpdjhiligpgajgjoghphfejaillh/dist/b4716f96db7fd93a9458.module.wasm:wasm-function[4629]:0x36b093)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: https://chatarcade.co.uk/arcade/craps.swf
Param movie: https://chatarcade.co.uk/arcade/craps.swf
Param pluginspage: http://www.macromedia.com/go/getflashplayer/
Param bgcolor: #000000
Param quality: high
Param menu: true
Param wmode: direct
Param allowScriptAccess: always
Param play: true
Param loop: true
Param hasPriority: true
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined

# Page Info
Page URL: https://chatarcade.co.uk/index.php?ipsproarcade/playgame/1420-craps
SWF URL: https://chatarcade.co.uk/arcade/craps.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36 Edg/87.0.664.75
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-12
Channel: nightly
Built: 2021-01-12T00:55:17.048Z
Commit: 73d123091014e190f4bc4d8edf98cab2e671cc3a

**Comment by Herschel** [comment]
Panic fixed in #2467.
