### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by wojtekpolska** [ruffle-rs/ruffle#2483]
I was using Ruffle on Opera (Opera says it supports Chrome extensions so i tried the Chrome version, because there is no dedicated version)

Also - the "Report Bug" button didn't work, i had to manually copy the contents. it said: 
`"Server github.com rejected connection ERR_BLOCKED_BY_RESPONSE"`

Opera 73.0.3856.329 Windows10 64x

Error Detalis:

# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/gc-arena-0.2.0/src/gc_cell.rs:62:29
Error stack:
```
Error: panicked at 'already borrowed: BorrowMutError', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/gc-arena-0.2.0/src/gc_cell.rs:62:29
    at Object.Q (chrome-extension://cmlgdijmjjcboaafihnikolkneidipoh/dist/core.ruffle.js:1:21332)
    at __wbg_new_df6e6ab7a65c4c4d (<anonymous>:3:38357)
    at std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f (chrome-extension://cmlgdijmjjcboaafihnikolkneidipoh/dist/128dbf02473fd3dc59bb.module.wasm:wasm-function[1273]:0x2610c0)
    at std::sync::once::Once::call_inner::h02eac160d339afc2 (chrome-extension://cmlgdijmjjcboaafihnikolkneidipoh/dist/128dbf02473fd3dc59bb.module.wasm:wasm-function[1519]:0x28e96f)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801 (chrome-extension://cmlgdijmjjcboaafihnikolkneidipoh/dist/128dbf02473fd3dc59bb.module.wasm:wasm-function[4297]:0x364a21)
    at std::panicking::rust_panic_with_hook::h123718ba3bf480af (chrome-extension://cmlgdijmjjcboaafihnikolkneidipoh/dist/128dbf02473fd3dc59bb.module.wasm:wasm-function[3306]:0x33e5d5)
    at std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2 (chrome-extension://cmlgdijmjjcboaafihnikolkneidipoh/dist/128dbf02473fd3dc59bb.module.wasm:wasm-function[3906]:0x35aa17)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925 (chrome-extension://cmlgdijmjjcboaafihnikolkneidipoh/dist/128dbf02473fd3dc59bb.module.wasm:wasm-function[4643]:0x36a175)
    at rust_begin_unwind (chrome-extension://cmlgdijmjjcboaafihnikolkneidipoh/dist/128dbf02473fd3dc59bb.module.wasm:wasm-function[4516]:0x3687b2)
    at core::panicking::panic_fmt::h285dc015a87be5a4 (chrome-extension://cmlgdijmjjcboaafihnikolkneidipoh/dist/128dbf02473fd3dc59bb.module.wasm:wasm-function[4645]:0x36a1d9)
    at core::option::expect_none_failed::hb95d2b1dc5448c17 (chrome-extension://cmlgdijmjjcboaafihnikolkneidipoh/dist/128dbf02473fd3dc59bb.module.wasm:wasm-function[3984]:0x35d0bf)
    at ruffle_core::avm2::object::TObject::install_foreign_trait::hfb2804f046af4d5c (chrome-extension://cmlgdijmjjcboaafihnikolkneidipoh/dist/128dbf02473fd3dc59bb.module.wasm:wasm-function[335]:0xbf934)
    at ruffle_core::avm2::object::TObject::set_property::h97babd6ad7fd796f (chrome-extension://cmlgdijmjjcboaafihnikolkneidipoh/dist/128dbf02473fd3dc59bb.module.wasm:wasm-function[665]:0x1ac016)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::set_property::hb2527de7a6f78954 (chrome-extension://cmlgdijmjjcboaafihnikolkneidipoh/dist/128dbf02473fd3dc59bb.module.wasm:wasm-function[508]:0x15ac35)
    at ruffle_core::avm2::activation::Activation::do_next_opcode::hebafc45a7bb91939 (chrome-extension://cmlgdijmjjcboaafihnikolkneidipoh/dist/128dbf02473fd3dc59bb.module.wasm:wasm-function[285]:0x22263)
    at ruffle_core::avm2::activation::Activation::run_actions::hbf8aa9119c1bed38 (chrome-extension://cmlgdijmjjcboaafihnikolkneidipoh/dist/128dbf02473fd3dc59bb.module.wasm:wasm-function[3024]:0x32e129)
    at ruffle_core::avm2::function::Executable::exec::h345a406a7a80a3ba (chrome-extension://cmlgdijmjjcboaafihnikolkneidipoh/dist/128dbf02473fd3dc59bb.module.wasm:wasm-function[1750]:0x2b19f6)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call::h4db5e75023f059c8 (chrome-extension://cmlgdijmjjcboaafihnikolkneidipoh/dist/128dbf02473fd3dc59bb.module.wasm:wasm-function[2367]:0x2f9095)
    at ruffle_core::display_object::movie_clip::MovieClip::construct_as_avm2_object::hef9ca116da49941d (chrome-extension://cmlgdijmjjcboaafihnikolkneidipoh/dist/128dbf02473fd3dc59bb.module.wasm:wasm-function[817]:0x1e68a0)
    at ruffle_core::display_object::movie_clip::MovieClip::preload::{{closure}}::hede52f627e31dd28 (chrome-extension://cmlgdijmjjcboaafihnikolkneidipoh/dist/128dbf02473fd3dc59bb.module.wasm:wasm-function[291]:0x59dc0)
    at ruffle_core::tag_utils::decode_tags::hd683cfe1173875cb (chrome-extension://cmlgdijmjjcboaafihnikolkneidipoh/dist/128dbf02473fd3dc59bb.module.wasm:wasm-function[1216]:0x254f5c)
    at ruffle_core::display_object::movie_clip::MovieClip::preload::h6d2a6cfec4104f16 (chrome-extension://cmlgdijmjjcboaafihnikolkneidipoh/dist/128dbf02473fd3dc59bb.module.wasm:wasm-function[791]:0x1dd83a)
    at ruffle_core::player::Player::set_root_movie::h845c3c3e295a8897 (chrome-extension://cmlgdijmjjcboaafihnikolkneidipoh/dist/128dbf02473fd3dc59bb.module.wasm:wasm-function[327]:0xb286f)
    at <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h979d6e546c1aef97 (chrome-extension://cmlgdijmjjcboaafihnikolkneidipoh/dist/128dbf02473fd3dc59bb.module.wasm:wasm-function[565]:0x17bef1)
    at <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h349280db1ec0e0e5 (chrome-extension://cmlgdijmjjcboaafihnikolkneidipoh/dist/128dbf02473fd3dc59bb.module.wasm:wasm-function[1751]:0x2b1bcf)
    at wasm_bindgen_futures::task::singlethread::Task::run::hf61719043c941cb5 (chrome-extension://cmlgdijmjjcboaafihnikolkneidipoh/dist/128dbf02473fd3dc59bb.module.wasm:wasm-function[3091]:0x3322b0)
    at wasm_bindgen_futures::queue::Queue::new::{{closure}}::he1caab9384257aa6 (chrome-extension://cmlgdijmjjcboaafihnikolkneidipoh/dist/128dbf02473fd3dc59bb.module.wasm:wasm-function[2805]:0x31e801)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hd0dd9605a857d885 (chrome-extension://cmlgdijmjjcboaafihnikolkneidipoh/dist/128dbf02473fd3dc59bb.module.wasm:wasm-function[4825]:0x36c030)
    at O (chrome-extension://cmlgdijmjjcboaafihnikolkneidipoh/dist/core.ruffle.js:1:19326)
    at f (chrome-extension://cmlgdijmjjcboaafihnikolkneidipoh/dist/core.ruffle.js:1:17974)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: https://files.crazygames.com/globetrotterxl.swf
Param bgcolor: #fff
Param quality: high
Param allowNetworking: all
Param allowScriptAccess: always
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://www.crazygames.com/gameframe/globetrotter-xl
SWF URL: https://files.crazygames.com/globetrotterxl.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36 OPR/73.0.3856.329
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-13
Channel: nightly
Built: 2021-01-13T01:01:47.998Z
Commit: 63f2b4f02f8fa4fa69ce61a5f6710bb07fcd2f33

**Comment by n0samu** [comment]
This error seems to be fixed now
