### ISSUE TITLE
Error on https://petrovka-beauty.ru/u/?m=pic

### ISSUE THREAD

**Issue by crash-bash** [ruffle-rs/ruffle#2493]
# Error Info
Error name: TypeError
Error message: JSON.stringify is not a function
Error stack:
```
TypeError: JSON.stringify is not a function
    at Object.K (chrome-extension://ffkenlglcbljbmafdealaiaeieajemmk/dist/core.ruffle.js:1:21515)
    at __wbindgen_json_serialize (<anonymous>:3:39024)
    at ruffle_web::Ruffle::new::ha55206f91423035f (chrome-extension://ffkenlglcbljbmafdealaiaeieajemmk/dist/ea023900695f5748b1e9.module.wasm:wasm-function[385]:0xfe184)
    at ruffle_new (chrome-extension://ffkenlglcbljbmafdealaiaeieajemmk/dist/ea023900695f5748b1e9.module.wasm:wasm-function[3933]:0x3608f9)
    at new G (chrome-extension://ffkenlglcbljbmafdealaiaeieajemmk/dist/core.ruffle.js:1:20011)
    at HTMLElement.<anonymous> (<anonymous>:3:18490)
    at Generator.next (<anonymous>)
    at c (<anonymous>:3:14611)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: https://petrovka-beauty.ru/tmplts/u/pic/upload_pic.swf
Param bgcolor: #e8eef7
Param flashvars: uploadURL=../../../u/_pic_upload.php?folder=0&maxFileSize=8806775
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined

# Page Info
Page URL: https://petrovka-beauty.ru/u/?m=pic

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-14
Channel: nightly
Built: 2021-01-14T01:08:37.174Z
Commit: c1c1c59bb51d2d20d2e601b5e4ff75ddfca528cb

**Comment by n0samu** [comment]
Looks like the same error as #2436. But the page has been taken down and was never archived.

**Comment by Lord-McSweeney** [comment]
Not an issue with Ruffle, and the site was using a version that is now 4 years outdated
