### ISSUE TITLE
Error on https://www.superhry.cz/games/1485/

### ISSUE THREAD

**Issue by Chesters-CZ** [ruffle-rs/ruffle#2525]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: JsValue(InvalidStateError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
Error: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
    at Object.<anonymous> (chrome-extension://jmoobmambohhgekjgoalkegahmhgapio/dist/core.ruffle.js:1:32682)
    at Object.<anonymous> (chrome-extension://jmoobmambohhgekjgoalkegahmhgapio/dist/core.ruffle.js:1:19781)
    at __wbg_drawImage_801ad094f4734689 (<anonymous>:3:60847)
    at web_sys::features::gen_CanvasRenderingContext2d::CanvasRenderingContext2d::draw_image_with_html_canvas_element::ha9de5d2aab9ff0dd (chrome-extension://jmoobmambohhgekjgoalkegahmhgapio/dist/ea023900695f5748b1e9.module.wasm:wasm-function[4410]:0x36c232)
    at <ruffle_render_canvas::WebCanvasRenderBackend as ruffle_core::backend::render::RenderBackend>::pop_mask::ha6a53f4d027e5730 (chrome-extension://jmoobmambohhgekjgoalkegahmhgapio/dist/ea023900695f5748b1e9.module.wasm:wasm-function[1041]:0x22e628)
    at ruffle_core::display_object::container::TDisplayObjectContainer::render_children::ha1dfb334281bffb0 (chrome-extension://jmoobmambohhgekjgoalkegahmhgapio/dist/ea023900695f5748b1e9.module.wasm:wasm-function[1187]:0x25202d)
    at <ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::render::h9f6a20cad0eb4554 (chrome-extension://jmoobmambohhgekjgoalkegahmhgapio/dist/ea023900695f5748b1e9.module.wasm:wasm-function[3351]:0x34583b)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render::h60cbeccbff9a8088 (chrome-extension://jmoobmambohhgekjgoalkegahmhgapio/dist/ea023900695f5748b1e9.module.wasm:wasm-function[3123]:0x338d93)
    at ruffle_core::display_object::container::TDisplayObjectContainer::render_children::ha1dfb334281bffb0 (chrome-extension://jmoobmambohhgekjgoalkegahmhgapio/dist/ea023900695f5748b1e9.module.wasm:wasm-function[1187]:0x251f3b)
    at <ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::render::h9f6a20cad0eb4554 (chrome-extension://jmoobmambohhgekjgoalkegahmhgapio/dist/ea023900695f5748b1e9.module.wasm:wasm-function[3351]:0x34583b))', render/canvas/src/lib.rs:685:14

# Player Info
Allows script access: true

# Page Info
Page URL: https://www.superhry.cz/games/1485/
SWF URL: https://www.superhry.cz/cnt_img/001/1485.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-14
Channel: nightly
Built: 2021-01-14T01:08:37.174Z
Commit: c1c1c59bb51d2d20d2e601b5e4ff75ddfca528cb

**Comment by zohebnsr** [comment]
I see nothing about Ruffle there. It's just flash.
![Screen Shot 2021-01-15 at 1 09 38 AM](https://user-images.githubusercontent.com/45603200/104649700-8d5f0b00-56ce-11eb-905c-421b9ef14e6a.jpg)

**Comment by Chesters-CZ** [comment]
I think you need to enable Flash as well as Rufus.

**Comment by zohebnsr** [comment]
No, you don't need to enable Flash to use Ruffle. It works without it

**Comment by Chesters-CZ** [comment]
but the webpage won't let you through without flash

**Comment by zohebnsr** [comment]
Not Sure, How to integrate it, but this is how it works:

- Download the Nightly Build, unzip it and name the folder whatever you like it to name.
- Upload the whole folder to Websites' Root Directory. ruffle.js file should be accessible via https://www.superhry.cz/yourrufflefolder/ruffle.js
- Now on your game page, add <script src="https://www.superhry.cz/yourrufflefolder/ruffle.js"></script> somewhere. Try both head and body where it works for you.
- Now it should load.
- If it doesn't (if you are using JS Minify Tool, try disabling and rechek.
- There is no need to enable/disable flash. It has no connection with adobe flash.

**Comment by relrelb** [comment]
Fixed by #7026.
