### ISSUE TITLE
Error on http://web.archive.org/web/20170912175333/http://thcnet.net/

### ISSUE THREAD

**Issue by ThirdWhirledCounTree** [ruffle-rs/ruffle#2538]
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/gc-arena-0.2.0/src/gc_cell.rs:62:29
Error stack:
```
Error: panicked at 'already borrowed: BorrowMutError', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/gc-arena-0.2.0/src/gc_cell.rs:62:29
    at Object.Y (chrome-extension://iddlgjbbagenocfgaldpaippaigplkfb/dist/core.ruffle.js:1:21332)
    at __wbg_new_df6e6ab7a65c4c4d (<anonymous>:3:38627)
    at std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f (chrome-extension://iddlgjbbagenocfgaldpaippaigplkfb/dist/ea023900695f5748b1e9.module.wasm:wasm-function[1274]:0x264cdf)
    at std::sync::once::Once::call_inner::h02eac160d339afc2 (chrome-extension://iddlgjbbagenocfgaldpaippaigplkfb/dist/ea023900695f5748b1e9.module.wasm:wasm-function[1538]:0x295324)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801 (chrome-extension://iddlgjbbagenocfgaldpaippaigplkfb/dist/ea023900695f5748b1e9.module.wasm:wasm-function[4317]:0x36a68d)
    at std::panicking::rust_panic_with_hook::h123718ba3bf480af (chrome-extension://iddlgjbbagenocfgaldpaippaigplkfb/dist/ea023900695f5748b1e9.module.wasm:wasm-function[3314]:0x343811)
    at std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2 (chrome-extension://iddlgjbbagenocfgaldpaippaigplkfb/dist/ea023900695f5748b1e9.module.wasm:wasm-function[3925]:0x3604fb)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925 (chrome-extension://iddlgjbbagenocfgaldpaippaigplkfb/dist/ea023900695f5748b1e9.module.wasm:wasm-function[4659]:0x36fcf7)
    at rust_begin_unwind (chrome-extension://iddlgjbbagenocfgaldpaippaigplkfb/dist/ea023900695f5748b1e9.module.wasm:wasm-function[4533]:0x36e366)
    at core::panicking::panic_fmt::h285dc015a87be5a4 (chrome-extension://iddlgjbbagenocfgaldpaippaigplkfb/dist/ea023900695f5748b1e9.module.wasm:wasm-function[4661]:0x36fd5b)
```

# Player Info
Allows script access: true

# Page Info
Page URL: http://web.archive.org/web/20170912175333/http://thcnet.net/
SWF URL: http://www.youtube.com/v/iFurvAEPmZg?hl=en_US&version=3&rel=0

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-14
Channel: nightly
Built: 2021-01-14T01:08:37.174Z
Commit: c1c1c59bb51d2d20d2e601b5e4ff75ddfca528cb

**Comment by n0samu** [comment]
Panic seems to be fixed now
