### ISSUE TITLE
Error on https://www.x-oo.com/flash-online-games/kartenspiele/spider-solitaire.html

### ISSUE THREAD

**Issue by balkongaertnerin** [ruffle-rs/ruffle#2590]
# Error Info
Error name: TypeError
Error message: o(...).values is not a function
Error stack:
```
TypeError: o(...).values is not a function
    at Object.gr (https://www.x-oo.com/cms/ruffle/core.ruffle.0197a207ce1d77ef54e9.js:1:33951)
    at __wbg_values_f28e313e2260a03a (https://www.x-oo.com/cms/ruffle/ruffle.js:1:63985)
    at js_sys::Array::values::hd705a756d95c3352 (wasm-function[5211]:6)
    at ruffle_web::populate_movie_parameters::he34c2666dc432a09 (wasm-function[1896]:59)
    at std::thread::local::LocalKey<T>::with::h55c081758324e6ca (wasm-function[1428]:217)
    at ruffle_stream_from (wasm-function[3658]:112)
    at W.stream_from (https://www.x-oo.com/cms/ruffle/core.ruffle.0197a207ce1d77ef54e9.js:1:20306)
    at HTMLElement.<anonymous> (https://www.x-oo.com/cms/ruffle/ruffle.js:1:18299)
    at Generator.next (<anonymous>)
    at c (https://www.x-oo.com/cms/ruffle/ruffle.js:1:12837)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: upload/Onlinespiele/spider.swf
Param src: upload/Onlinespiele/spider.swf
Param wmode: opaque
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://www.x-oo.com/flash-online-games/kartenspiele/spider-solitaire.html
SWF URL: https://www.x-oo.com/flash-online-games/kartenspiele/upload/Onlinespiele/spider.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.52 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-16
Channel: nightly
Built: 2021-01-16T01:09:33.302Z
Commit: 9df7facdb8d37a5d007a13c25efcc176ed4675e0

**Comment by adrian17** [comment]
From what I see, this is Chrome 63, which is way below officially supported version (https://github.com/ruffle-rs/ruffle/wiki#web). That also explains the error (`array.values()` indeed didn't exist in that Chrome version yet). So with this, I'm closing this issue.
