### ISSUE TITLE
Error on https://www.mostfungames.com/taxi-rush.htm

### ISSUE THREAD

**Issue by homehealthcareshoppe** [ruffle-rs/ruffle#2628]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm1/globals/color_transform.rs:67:47
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm1/globals/color_transform.rs:67:47
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://www.mostfungames.com/wp-content/themes/kizitheme/ruffle/ruffle.js:1:6333)
    at std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f (https://www.mostfungames.com/wp-content/themes/kizitheme/ruffle/43f8e1e34e0629f740121b10aab750da.wasm:wasm-function[1280]:0x263ca7)
    at std::sync::once::Once::call_inner::h02eac160d339afc2 (https://www.mostfungames.com/wp-content/themes/kizitheme/ruffle/43f8e1e34e0629f740121b10aab750da.wasm:wasm-function[1548]:0x294bd2)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801 (https://www.mostfungames.com/wp-content/themes/kizitheme/ruffle/43f8e1e34e0629f740121b10aab750da.wasm:wasm-function[4312]:0x368af7)
    at std::panicking::rust_panic_with_hook::h123718ba3bf480af (https://www.mostfungames.com/wp-content/themes/kizitheme/ruffle/43f8e1e34e0629f740121b10aab750da.wasm:wasm-function[3310]:0x341daf)
    at std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2 (https://www.mostfungames.com/wp-content/themes/kizitheme/ruffle/43f8e1e34e0629f740121b10aab750da.wasm:wasm-function[3919]:0x35e8f6)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925 (https://www.mostfungames.com/wp-content/themes/kizitheme/ruffle/43f8e1e34e0629f740121b10aab750da.wasm:wasm-function[4655]:0x36e191)
    at rust_begin_unwind (https://www.mostfungames.com/wp-content/themes/kizitheme/ruffle/43f8e1e34e0629f740121b10aab750da.wasm:wasm-function[4529]:0x36c811)
    at core::panicking::panic_fmt::h285dc015a87be5a4 (https://www.mostfungames.com/wp-content/themes/kizitheme/ruffle/43f8e1e34e0629f740121b10aab750da.wasm:wasm-function[4657]:0x36e1f5)
    at core::panicking::panic::h0abe4e7a620ae568 (https://www.mostfungames.com/wp-content/themes/kizitheme/ruffle/43f8e1e34e0629f740121b10aab750da.wasm:wasm-function[4464]:0x36b714)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.mostfungames.com/taxi-rush.htm
SWF URL: https://www.mostfungames.com/wp-content/uploads/games/imported-games/taxirush.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-17
Channel: nightly
Built: 2021-01-17T01:05:59.152Z
Commit: c2b768c453f281a988c71a829e7a71bb106302fa

**Comment by Herschel** [comment]
Fixed by #2706.
