### ISSUE TITLE
Error on https://flash.porno-apk.com/game.php?i=4

### ISSUE THREAD

**Issue by qw12345678qw** [ruffle-rs/ruffle#2664]
# Error Info
Error name: TypeError
Error message: o(...).values is not a function
Error stack:
```
TypeError: o(...).values is not a function
    at Object.ur (https://flash.porno-apk.com/ruffle/11-01-2021/core.ruffle.3be12cf6e13daeeedf58.js:1:33469)
    at __wbg_values_f28e313e2260a03a (https://flash.porno-apk.com/ruffle/11-01-2021/ruffle.js:1:63243)
    at js_sys::Array::values::hfe81db5d547ca803 (wasm-function[5167]:6)
    at ruffle_web::populate_movie_parameters::hb42d752746f477c9 (wasm-function[1878]:59)
    at std::thread::local::LocalKey<T>::with::h2ea8de2a8acc03ac (wasm-function[1435]:226)
    at ruffle_stream_from (wasm-function[3625]:112)
    at W.stream_from (https://flash.porno-apk.com/ruffle/11-01-2021/core.ruffle.3be12cf6e13daeeedf58.js:1:20060)
    at HTMLElement.<anonymous> (https://flash.porno-apk.com/ruffle/11-01-2021/ruffle.js:1:18211)
    at Generator.next (<anonymous>)
    at c (https://flash.porno-apk.com/ruffle/11-01-2021/ruffle.js:1:12825)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: game/4.swf
Param movie: game/4.swf
Param quality: high
Param play: true
Param loop: true
Param wmode: window
Param scale: showall
Param allowFullScreen: true
Param menu: true
Param devicefont: false
Param allowScriptAccess: always
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined

# Page Info
Page URL: https://flash.porno-apk.com/game.php?i=4
SWF URL: https://flash.porno-apk.com/game/4.swf

# Browser Info
Useragent: Mozilla/5.0 (Linux; Android 9; V1934A Build/PPR1.180610.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.84 Mobile Safari/537.36 VivoBrowser/8.9.12.6
OS: Linux armv8l

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-11
Channel: nightly
Built: 2021-01-11T00:53:04.486Z
Commit: cce3a8199d48ecbce536a0e49efd501d97a2b370

**Comment by adrian17** [comment]
From what I see, this version of VivoBrowser is based on Chrome 62, which is way below officially supported version (https://github.com/ruffle-rs/ruffle/wiki#web). That also explains the error (`.values()` indeed didn't exist in that Chrome version yet). So with this, I'm closing this issue.
