### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by Netherbrine5902** [ruffle-rs/ruffle#2737]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/movie_clip.rs:3107:14
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/movie_clip.rs:3107:14
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://uploads.ungrounded.net/ruffle_wrapper/lib/ruffle.js?1611229718:1:6518)
    at std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f (https://uploads.ungrounded.net/ruffle_wrapper/lib/0f45cf0b731a577a20886dbd5bf07618.wasm:wasm-function[1282]:0x25c34b)
    at std::sync::once::Once::call_inner::h02eac160d339afc2 (https://uploads.ungrounded.net/ruffle_wrapper/lib/0f45cf0b731a577a20886dbd5bf07618.wasm:wasm-function[1549]:0x28d0c2)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801 (https://uploads.ungrounded.net/ruffle_wrapper/lib/0f45cf0b731a577a20886dbd5bf07618.wasm:wasm-function[4308]:0x3605d1)
    at std::panicking::rust_panic_with_hook::h123718ba3bf480af (https://uploads.ungrounded.net/ruffle_wrapper/lib/0f45cf0b731a577a20886dbd5bf07618.wasm:wasm-function[3302]:0x33958f)
    at std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2 (https://uploads.ungrounded.net/ruffle_wrapper/lib/0f45cf0b731a577a20886dbd5bf07618.wasm:wasm-function[3915]:0x356497)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925 (https://uploads.ungrounded.net/ruffle_wrapper/lib/0f45cf0b731a577a20886dbd5bf07618.wasm:wasm-function[4654]:0x365d09)
    at rust_begin_unwind (https://uploads.ungrounded.net/ruffle_wrapper/lib/0f45cf0b731a577a20886dbd5bf07618.wasm:wasm-function[4526]:0x364329)
    at core::panicking::panic_fmt::h285dc015a87be5a4 (https://uploads.ungrounded.net/ruffle_wrapper/lib/0f45cf0b731a577a20886dbd5bf07618.wasm:wasm-function[4656]:0x365d6d)
    at core::panicking::panic::h0abe4e7a620ae568 (https://uploads.ungrounded.net/ruffle_wrapper/lib/0f45cf0b731a577a20886dbd5bf07618.wasm:wasm-function[4460]:0x3631ee)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.64&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1611229718%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F587000%2F587121_creep.swf%3F1336113712%22%2C%22vars%22%3A%7B%22ngio_session_id%22%3A%2205138975.129cbc29f0a006889653d9faa48751cfb98bd0f08fff3d%22%2C%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%22600a0fdadb9b9%22%2C%22NewgroundsAPI_SessionID%22%3A%222m5b9sK5v37GQIushx8g40dd0b695c1dcc52230dedf86b8d9c82218ec7d3WacK%22%2C%22NewgroundsAPI_UserName%22%3A%22Netherbrine5902%22%2C%22NewgroundsAPI_UserID%22%3A8120525%2C%22ng_username%22%3A%22Netherbrine5902%22%7D%2C%22width%22%3A700%2C%22height%22%3A400%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F587000%2Fflash_587121.jpg%3Ff1363840295%22%7D
SWF URL: https://uploads.ungrounded.net/587000/587121_creep.swf?1336113712

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-21
Channel: nightly
Built: 2021-01-21T01:06:17.627Z
Commit: dc2b4fcc42e447097d6432479a122b34fcbc3999

**Comment by Poopooracoocoo** [comment]
Link to Creep Craft on Newgrounds:
https://www.newgrounds.com/portal/view/587121
