### ISSUE TITLE
Error on http://recon.gr/

### ISSUE THREAD

**Issue by Displav** [ruffle-rs/ruffle#2759]
# Error Info
Error name: Error
Error message: panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:542:5
Error stack:
```
Error: panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:542:5
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (<anonymous>:3:6487)
    at std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f (chrome-extension://hnhnfimandinolgiklbmoigppgdcgiaf/dist/8d62e449f4e6f83e50950ed46a920f36.wasm:wasm-function[1272]:0x257d2b)
    at std::sync::once::Once::call_inner::h02eac160d339afc2 (chrome-extension://hnhnfimandinolgiklbmoigppgdcgiaf/dist/8d62e449f4e6f83e50950ed46a920f36.wasm:wasm-function[1537]:0x288710)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801 (chrome-extension://hnhnfimandinolgiklbmoigppgdcgiaf/dist/8d62e449f4e6f83e50950ed46a920f36.wasm:wasm-function[4316]:0x35e2ca)
    at std::panicking::rust_panic_with_hook::h123718ba3bf480af (chrome-extension://hnhnfimandinolgiklbmoigppgdcgiaf/dist/8d62e449f4e6f83e50950ed46a920f36.wasm:wasm-function[3311]:0x33733d)
    at std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2 (chrome-extension://hnhnfimandinolgiklbmoigppgdcgiaf/dist/8d62e449f4e6f83e50950ed46a920f36.wasm:wasm-function[3923]:0x35414d)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925 (chrome-extension://hnhnfimandinolgiklbmoigppgdcgiaf/dist/8d62e449f4e6f83e50950ed46a920f36.wasm:wasm-function[4662]:0x363a0c)
    at rust_begin_unwind (chrome-extension://hnhnfimandinolgiklbmoigppgdcgiaf/dist/8d62e449f4e6f83e50950ed46a920f36.wasm:wasm-function[4534]:0x362022)
    at core::panicking::panic_fmt::h285dc015a87be5a4 (chrome-extension://hnhnfimandinolgiklbmoigppgdcgiaf/dist/8d62e449f4e6f83e50950ed46a920f36.wasm:wasm-function[4664]:0x363a70)
    at core::panicking::panic::h0abe4e7a620ae568 (chrome-extension://hnhnfimandinolgiklbmoigppgdcgiaf/dist/8d62e449f4e6f83e50950ed46a920f36.wasm:wasm-function[4468]:0x360ee7)
```

# Player Info
Allows script access: true

# Page Info
Page URL: http://recon.gr/
SWF URL: http://recon.gr/recon_gr.swf

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-22
Channel: nightly
Built: 2021-01-22T01:05:46.108Z
Commit: b05c6540e18bcca93dce9ed6f65fe1f38d65a979

**Comment by relrelb** [comment]
At least on desktop, this seems to get stuck while processing the first `DefineBits` tag here:
https://github.com/ruffle-rs/ruffle/blob/c088c1851759635605bf20f6cabfd7212437f82c/core/src/backend/render.rs#L332
The JPEG metadata reports dimensions of 36356x30789 (>1GB), but the actual data is just few MBs. So `jpeg-decoder` tries to allocate 1GB, and never returns.

**Comment by Lord-McSweeney** [comment]
Still happening :\
