### ISSUE TITLE
Error on https://mysexgames.com/games/?id=603&h=&sess=WDAwMHgwODox

### ISSUE THREAD

**Issue by 2364727092** [ruffle-rs/ruffle#2760]
# Error Info
Error name: Error
Error message: panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`: cannot recursively acquire mutex', /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys/wasm/../unsupported/mutex.rs:23:9
Error stack:
```
Error: panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`: cannot recursively acquire mutex', /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys/wasm/../unsupported/mutex.rs:23:9
    at Object.U (https://mysexgames.com/ruffle/core.ruffle.ab9406d542303de5ee9b.js:1:21277)
    at __wbg_new_df6e6ab7a65c4c4d (https://mysexgames.com/ruffle/ruffle.js:1:38987)
    at std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f (https://mysexgames.com/ruffle/14d80b2900ca11106a81.module.wasm:wasm-function[1288]:0x2636a1)
    at std::sync::once::Once::call_inner::h02eac160d339afc2 (https://mysexgames.com/ruffle/14d80b2900ca11106a81.module.wasm:wasm-function[1539]:0x291d92)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801 (https://mysexgames.com/ruffle/14d80b2900ca11106a81.module.wasm:wasm-function[4281]:0x3658db)
    at std::panicking::rust_panic_with_hook::h123718ba3bf480af (https://mysexgames.com/ruffle/14d80b2900ca11106a81.module.wasm:wasm-function[3312]:0x34053c)
    at std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2 (https://mysexgames.com/ruffle/14d80b2900ca11106a81.module.wasm:wasm-function[3889]:0x35b821)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925 (https://mysexgames.com/ruffle/14d80b2900ca11106a81.module.wasm:wasm-function[4627]:0x36b02f)
    at rust_begin_unwind (https://mysexgames.com/ruffle/14d80b2900ca11106a81.module.wasm:wasm-function[4500]:0x36966c)
    at std::panicking::begin_panic_fmt::h96153d9dc0e882ed (https://mysexgames.com/ruffle/14d80b2900ca11106a81.module.wasm:wasm-function[4597]:0x36aac7)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://mysexgames.com/games/?id=603&h=&sess=WDAwMHgwODox
SWF URL: https://mysexgames.com/gamefiles/simseh-chapter-1.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-12
Channel: nightly
Built: 2021-01-12T00:55:17.048Z
Commit: 73d123091014e190f4bc4d8edf98cab2e671cc3a

**Comment by Herschel** [comment]
Same issue as #2361.
