### ISSUE TITLE
Error on https://ridesims.com/ride-simulators/Stealth

### ISSUE THREAD

**Issue by JoeP257** [ruffle-rs/ruffle#2761]
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', web/src/lib.rs:602:42
Error stack:
```
Error: panicked at 'already borrowed: BorrowMutError', web/src/lib.rs:602:42
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (<anonymous>:1:6518)
    at std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f (https://ridesims.com/ruffle/8d62e449f4e6f83e50950ed46a920f36.wasm:wasm-function[1272]:0x257d2b)
    at std::sync::once::Once::call_inner::h02eac160d339afc2 (https://ridesims.com/ruffle/8d62e449f4e6f83e50950ed46a920f36.wasm:wasm-function[1537]:0x288710)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801 (https://ridesims.com/ruffle/8d62e449f4e6f83e50950ed46a920f36.wasm:wasm-function[4316]:0x35e2ca)
    at std::panicking::rust_panic_with_hook::h123718ba3bf480af (https://ridesims.com/ruffle/8d62e449f4e6f83e50950ed46a920f36.wasm:wasm-function[3311]:0x33733d)
    at std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2 (https://ridesims.com/ruffle/8d62e449f4e6f83e50950ed46a920f36.wasm:wasm-function[3923]:0x354174)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925 (https://ridesims.com/ruffle/8d62e449f4e6f83e50950ed46a920f36.wasm:wasm-function[4662]:0x363a0c)
    at rust_begin_unwind (https://ridesims.com/ruffle/8d62e449f4e6f83e50950ed46a920f36.wasm:wasm-function[4534]:0x362022)
    at core::panicking::panic_fmt::h285dc015a87be5a4 (https://ridesims.com/ruffle/8d62e449f4e6f83e50950ed46a920f36.wasm:wasm-function[4664]:0x363a70)
    at core::option::expect_none_failed::hb95d2b1dc5448c17 (https://ridesims.com/ruffle/8d62e449f4e6f83e50950ed46a920f36.wasm:wasm-function[4003]:0x356955)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://ridesims.com/ride-simulators/Stealth
SWF URL: https://ridesims.com/sites/default/files/2021-01/StealthV1.2.swf

# Browser Info
Useragent: Mozilla/5.0 (Linux; Android 10; VOG-L09) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Mobile Safari/537.36
OS: Linux armv8l

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-22
Channel: nightly
Built: 2021-01-22T01:05:46.108Z
Commit: b05c6540e18bcca93dce9ed6f65fe1f38d65a979

**Comment by Lord-McSweeney** [comment]
Closing as the site was using a version of Ruffle that is now 4 years outdated
