### ISSUE TITLE
Error on https://homestarrunner.com/toons/yellodello-mark2

### ISSUE THREAD

**Issue by Lucoshi** [ruffle-rs/ruffle#2770]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: JsValue(TypeError: Failed to fetch
TypeError: Failed to fetch)', web/src/navigator.rs:201:18
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: JsValue(TypeError: Failed to fetch
TypeError: Failed to fetch)', web/src/navigator.rs:201:18
    at Object.Z (https://homestarrunner.com/assets/js/core.ruffle.a63e1c79e919bd6509c7.js:1:21277)
    at __wbg_new_df6e6ab7a65c4c4d (https://homestarrunner.com/assets/js/ruffle.1610600923.js:1:39257)
    at std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f (https://homestarrunner.com/assets/js/9787cfba420e7deb83df.module.wasm:wasm-function[1274]:0x264cdf)
    at std::sync::once::Once::call_inner::h02eac160d339afc2 (https://homestarrunner.com/assets/js/9787cfba420e7deb83df.module.wasm:wasm-function[1538]:0x295324)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801 (https://homestarrunner.com/assets/js/9787cfba420e7deb83df.module.wasm:wasm-function[4317]:0x36a68d)
    at std::panicking::rust_panic_with_hook::h123718ba3bf480af (https://homestarrunner.com/assets/js/9787cfba420e7deb83df.module.wasm:wasm-function[3314]:0x343811)
    at std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2 (https://homestarrunner.com/assets/js/9787cfba420e7deb83df.module.wasm:wasm-function[3925]:0x3604fb)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925 (https://homestarrunner.com/assets/js/9787cfba420e7deb83df.module.wasm:wasm-function[4659]:0x36fcf7)
    at rust_begin_unwind (https://homestarrunner.com/assets/js/9787cfba420e7deb83df.module.wasm:wasm-function[4533]:0x36e366)
    at core::panicking::panic_fmt::h285dc015a87be5a4 (https://homestarrunner.com/assets/js/9787cfba420e7deb83df.module.wasm:wasm-function[4661]:0x36fd5b)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://homestarrunner.com/toons/yellodello-mark2
SWF URL: https://homestarrunner.com/media/pages/toons/yellodello-mark2/495fd01c20-1609456536/yellodello_mark2.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-14
Channel: nightly
Built: 2021-01-14T01:08:37.174Z
Commit: c1c1c59bb51d2d20d2e601b5e4ff75ddfca528cb

**Comment by rufflue** [comment]
try updating the ruffle extension as my version of ruffle is 2021-01-20 and the homestar runner cartoon works great

**Comment by Sonikkustar** [comment]
The movie appears to load up without any issues:
![image](https://github.com/ruffle-rs/ruffle/assets/22226938/b4fb09cb-1c0d-4c55-a676-5f6c27138d66)

Site now uses **nightly-2023-11-24**. Also man, this certainly takes me back.

**Comment by n0samu** [comment]
This was probably a transient server error.
