### ISSUE TITLE
Error on https://z0r.de/221

### ISSUE THREAD

**Issue by exchange12rocks** [ruffle-rs/ruffle#2780]
# Error Info
Error name: Error
Error message: panicked at 'range end index 514 out of range for slice of length 325', core/src/tag_utils.rs:295:26
Error stack:
```
Error: panicked at 'range end index 514 out of range for slice of length 325', core/src/tag_utils.rs:295:26
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://z0r.de/inc/ruffle.js:1:6416)
    at std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f (https://z0r.de/inc/be6c528498ea370abf3cab1d51680b0d.wasm:wasm-function[1413]:0x2b1268)
    at std::sync::once::Once::call_inner::h02eac160d339afc2 (https://z0r.de/inc/be6c528498ea370abf3cab1d51680b0d.wasm:wasm-function[1695]:0x2e4bde)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801 (https://z0r.de/inc/be6c528498ea370abf3cab1d51680b0d.wasm:wasm-function[4616]:0x3cc5b9)
    at std::panicking::rust_panic_with_hook::h123718ba3bf480af (https://z0r.de/inc/be6c528498ea370abf3cab1d51680b0d.wasm:wasm-function[3569]:0x3a1613)
    at std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2 (https://z0r.de/inc/be6c528498ea370abf3cab1d51680b0d.wasm:wasm-function[4209]:0x3c10c0)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925 (https://z0r.de/inc/be6c528498ea370abf3cab1d51680b0d.wasm:wasm-function[4975]:0x3d2ffd)
    at rust_begin_unwind (https://z0r.de/inc/be6c528498ea370abf3cab1d51680b0d.wasm:wasm-function[4841]:0x3d13f8)
    at core::panicking::panic_fmt::h285dc015a87be5a4 (https://z0r.de/inc/be6c528498ea370abf3cab1d51680b0d.wasm:wasm-function[4977]:0x3d3061)
    at core::slice::index::slice_end_index_len_fail::h6f6253f4aa8173a8 (https://z0r.de/inc/be6c528498ea370abf3cab1d51680b0d.wasm:wasm-function[4398]:0x3c70e3)
    at ruffle_core::tag_utils::decode_tags::hc3a65e676e3b9d66 (https://z0r.de/inc/be6c528498ea370abf3cab1d51680b0d.wasm:wasm-function[1541]:0x2ca3e8)
    at ruffle_core::display_object::movie_clip::MovieClip::preload::ha420ae4996b7b298 (https://z0r.de/inc/be6c528498ea370abf3cab1d51680b0d.wasm:wasm-function[832]:0x20f277)
    at ruffle_core::player::Player::set_root_movie::hfaf52534cde1ac44 (https://z0r.de/inc/be6c528498ea370abf3cab1d51680b0d.wasm:wasm-function[358]:0xe22ab)
    at <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h06f67e980da4e3be (https://z0r.de/inc/be6c528498ea370abf3cab1d51680b0d.wasm:wasm-function[606]:0x1abb23)
    at <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hcff96150af6e498f (https://z0r.de/inc/be6c528498ea370abf3cab1d51680b0d.wasm:wasm-function[1941]:0x30a776)
    at wasm_bindgen_futures::task::singlethread::Task::run::h478926eeec80b706 (https://z0r.de/inc/be6c528498ea370abf3cab1d51680b0d.wasm:wasm-function[3362]:0x3955d2)
    at wasm_bindgen_futures::queue::Queue::new::{{closure}}::h9338cad833970627 (https://z0r.de/inc/be6c528498ea370abf3cab1d51680b0d.wasm:wasm-function[3068]:0x380582)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hcbd198c5f38f914c (https://z0r.de/inc/be6c528498ea370abf3cab1d51680b0d.wasm:wasm-function[5145]:0x3d4bca)
    at T (https://z0r.de/inc/ruffle.js:1:4192)
    at a (https://z0r.de/inc/ruffle.js:1:2840)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://z0r.de/221
SWF URL: https://z0r.de/L/z0r-de_221.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-21
Channel: nightly
Built: 2021-01-21T10:41:23.411Z
Commit: 584b4fbb61d7694725a060250a61582d960f9975

**Comment by Toad06** [comment]
This is already fixed by #2729, z0r.de will need to update their build. Thanks for reporting.
