### ISSUE TITLE
Error on https://sonix.tk/emu/test.html

### ISSUE THREAD

**Issue by Ramilchik** [ruffle-rs/ruffle#2806]
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', web/src/lib.rs:830:49
Error stack:
```
Error: panicked at 'already borrowed: BorrowMutError', web/src/lib.rs:830:49
    at Object.J (https://sonix.tk/emu/ruffle/core.ruffle.b038bd33651650e53735.js:1:21279)
    at __wbg_new_df6e6ab7a65c4c4d (https://sonix.tk/emu/ruffle/ruffle.js:1:38978)
    at std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f (https://sonix.tk/emu/ruffle/4ee107bd02685b71c22f.module.wasm:wasm-function[1279]:0x2649fb)
    at std::sync::once::Once::call_inner::h02eac160d339afc2 (https://sonix.tk/emu/ruffle/4ee107bd02685b71c22f.module.wasm:wasm-function[1547]:0x295a73)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801 (https://sonix.tk/emu/ruffle/4ee107bd02685b71c22f.module.wasm:wasm-function[4311]:0x3699c8)
    at std::panicking::rust_panic_with_hook::h123718ba3bf480af (https://sonix.tk/emu/ruffle/4ee107bd02685b71c22f.module.wasm:wasm-function[3309]:0x342c41)
    at std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2 (https://sonix.tk/emu/ruffle/4ee107bd02685b71c22f.module.wasm:wasm-function[3918]:0x35f7ca)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925 (https://sonix.tk/emu/ruffle/4ee107bd02685b71c22f.module.wasm:wasm-function[4654]:0x36f065)
    at rust_begin_unwind (https://sonix.tk/emu/ruffle/4ee107bd02685b71c22f.module.wasm:wasm-function[4528]:0x36d6e5)
    at core::panicking::panic_fmt::h285dc015a87be5a4 (https://sonix.tk/emu/ruffle/4ee107bd02685b71c22f.module.wasm:wasm-function[4656]:0x36f0c9)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://sonix.tk/emu/test.html
SWF URL: https://sonix.tk/files/swf/sonic_ultimate.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-15
Channel: nightly
Built: 2021-01-15T01:03:45.335Z
Commit: 09a48a71d8608803fd5dba4343c5f10c928f9652

**Comment by ousia** [comment]
@Ramilchik,

many thanks for reporting the issue.

I can play the game, so could you give the steps to reproduce the issue?
