### ISSUE TITLE
Error on https://dearfox.github.io/reference-online/swf-test/test.html

### ISSUE THREAD

**Issue by DearFox** [ruffle-rs/ruffle#2851]
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', web/src/lib.rs:836:49
Error stack:
```
Error: panicked at 'already borrowed: BorrowMutError', web/src/lib.rs:836:49
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://dearfox.github.io/reference-online/swf-test/ruffle/ruffle.js:1:6349)
    at std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f (wasm-function[1265]:169)
    at std::sync::once::Once::call_inner::h02eac160d339afc2 (wasm-function[1528]:675)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801 (wasm-function[4309]:67)
    at std::panicking::rust_panic_with_hook::h123718ba3bf480af (wasm-function[3299]:224)
    at std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2 (wasm-function[3916]:159)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925 (wasm-function[4655]:40)
    at rust_begin_unwind (wasm-function[4526]:89)
    at core::panicking::panic_fmt::h285dc015a87be5a4 (wasm-function[4657]:48)
    at core::option::expect_none_failed::hb95d2b1dc5448c17 (wasm-function[3996]:123)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://dearfox.github.io/reference-online/swf-test/test.html
SWF URL: https://dearfox.github.io/reference-online/swf-test/swf.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.111 Safari/537.36
OS: Linux armv8l

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-25
Channel: nightly
Built: 2021-01-25T01:05:41.178Z
Commit: 32fd3fb71befbceecbba7c73d08af5ddd0f5a3d0

**Comment by DearFox** [comment]
I tried running my SWF through a browser using ruffle on my Android 6.0.1 smartphone
but got it.

**Comment by Poopooracoocoo** [comment]
Chrome 63 is pretty old. I don't think it supports WebAssembly fully, a modern web technology that Ruffle depends on. 
Could you test on another browser like Brave, Vivaldi, Firefox, etc? (if you don't want to update Chrome) 
Which Android device or SoC?

**Comment by DearFox** [comment]
> Chrome 63 довольно старый. Я не думаю, что он полностью поддерживает WebAssembly, современную веб-технологию, от которой зависит Ruffle.
> Не могли бы вы протестировать в другом браузере, таком как Brave, Vivaldi, Firefox и т. Д.? (если вы не хотите обновлять Chrome)
> Какое устройство Android или SoC?
> 
> изменить: и мне это просто нравится

Thanks, I updated my browser on my phone and it worked.
(in the place where I live there are problems with automatic updating of Soft on phones)
Everything works, it's a pity that everything slows down, but this is most likely a problem with my phone.

> Chrome 63 is pretty old. I don't think it supports WebAssembly fully, a modern web technology that Ruffle depends on.
> Could you test on another browser like Brave, Vivaldi, Firefox, etc? (if you don't want to update Chrome)
> Which Android device or SoC?
> 
> edit: and i just love that

Thanks, I updated my browser on my phone and it worked.
(in the place where I live there are problems with automatic updating of Soft on phones)
Everything works, it's a pity that everything slows down, but this is most likely a problem with my phone.
