### ISSUE TITLE
Error on https://www.crazygames.com/gameframe/robot-unicorn-attack?v13bb

### ISSUE THREAD

**Issue by matsiyasei** [ruffle-rs/ruffle#2870]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/movie_clip.rs:3108:14
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/movie_clip.rs:3108:14
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://files.crazygames.com/gameframe/ruffle/2021-01-25/ruffle.js:1:6349)
    at std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f (https://files.crazygames.com/gameframe/ruffle/2021-01-25/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[1265]:0x24e3c9)
    at std::sync::once::Once::call_inner::h02eac160d339afc2 (https://files.crazygames.com/gameframe/ruffle/2021-01-25/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[1528]:0x27e7a0)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801 (https://files.crazygames.com/gameframe/ruffle/2021-01-25/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[4309]:0x3537a0)
    at std::panicking::rust_panic_with_hook::h123718ba3bf480af (https://files.crazygames.com/gameframe/ruffle/2021-01-25/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[3299]:0x32c417)
    at std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2 (https://files.crazygames.com/gameframe/ruffle/2021-01-25/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[3916]:0x3495ce)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925 (https://files.crazygames.com/gameframe/ruffle/2021-01-25/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[4655]:0x358eda)
    at rust_begin_unwind (https://files.crazygames.com/gameframe/ruffle/2021-01-25/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[4526]:0x3574b8)
    at core::panicking::panic_fmt::h285dc015a87be5a4 (https://files.crazygames.com/gameframe/ruffle/2021-01-25/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[4657]:0x358f3e)
    at core::panicking::panic::h0abe4e7a620ae568 (https://files.crazygames.com/gameframe/ruffle/2021-01-25/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[4460]:0x35637d)
    at ruffle_core::display_object::movie_clip::ClipAction::from_action_and_movie::ha450ca3cd3934f9e (https://files.crazygames.com/gameframe/ruffle/2021-01-25/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[2291]:0x2dfd2f)
    at <core::iter::adapters::flatten::Flatten<I> as core::iter::traits::iterator::Iterator>::next::hce2d5299c1409f8b (https://files.crazygames.com/gameframe/ruffle/2021-01-25/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[1207]:0x2421d7)
    at <alloc::vec::Vec<T> as alloc::vec::SpecFromIter<T,I>>::from_iter::h88e5355d9c89839e (https://files.crazygames.com/gameframe/ruffle/2021-01-25/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[1160]:0x237598)
    at ruffle_core::display_object::TDisplayObject::apply_place_object::h73afed2053d4ee6b (https://files.crazygames.com/gameframe/ruffle/2021-01-25/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[820]:0x1d7412)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::apply_place_object::hbb808030940498ae (https://files.crazygames.com/gameframe/ruffle/2021-01-25/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[3986]:0x34b91c)
    at ruffle_core::display_object::movie_clip::MovieClip::run_goto::{{closure}}::hbac06c5fcaeaeabd (https://files.crazygames.com/gameframe/ruffle/2021-01-25/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[2447]:0x2eedcd)
    at ruffle_core::display_object::movie_clip::MovieClip::run_goto::hc4f028aee85a0d7e (https://files.crazygames.com/gameframe/ruffle/2021-01-25/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[454]:0x1264d1)
    at ruffle_core::display_object::movie_clip::MovieClip::goto_frame::hf5392d57580c8de1 (https://files.crazygames.com/gameframe/ruffle/2021-01-25/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[2740]:0x3080c8)
    at ruffle_core::avm1::activation::Activation::do_action::hda59a17d9b889cf0 (https://files.crazygames.com/gameframe/ruffle/2021-01-25/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[286]:0xddbc)
    at ruffle_core::avm1::activation::Activation::run_actions::h508dec666a958907 (https://files.crazygames.com/gameframe/ruffle/2021-01-25/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[2773]:0x30a743)
    at ruffle_core::avm1::Avm1::run_stack_frame_for_action::h2a72d99fbd71b6c7 (https://files.crazygames.com/gameframe/ruffle/2021-01-25/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[1116]:0x22d399)
    at ruffle_core::player::Player::run_actions::h714de2b6884fe9d4 (https://files.crazygames.com/gameframe/ruffle/2021-01-25/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[429]:0x111cb0)
    at ruffle_core::player::Player::handle_event::h4439c0767e7f3f2a (https://files.crazygames.com/gameframe/ruffle/2021-01-25/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[329]:0xa8191)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::h8d74c2021600451e (https://files.crazygames.com/gameframe/ruffle/2021-01-25/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[1380]:0x264a85)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h0eb418e044fe8e5c (https://files.crazygames.com/gameframe/ruffle/2021-01-25/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[4838]:0x35adc3)
    at E (https://files.crazygames.com/gameframe/ruffle/2021-01-25/ruffle.js:1:3429)
    at a (https://files.crazygames.com/gameframe/ruffle/2021-01-25/ruffle.js:1:2840)
    at r (https://gameframe.crazygames.com/crazygames-gameframe-v1.bundle.js:1:57957)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.crazygames.com/gameframe/robot-unicorn-attack?v13bb
SWF URL: https://files.crazygames.com/robot-unicorn-attack/1/robot%20unicorn%20attack.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-25
Channel: nightly
Built: 2021-01-25T01:05:41.178Z
Commit: 32fd3fb71befbceecbba7c73d08af5ddd0f5a3d0

**Comment by Toad06** [comment]
Thanks for the report. This is a regression (there's no crash in nightly-2021-01-20 and older). To reproduce, start a new game, lose it and press Z.

I ran a bisect and it appears this has something to do with commit 19034b76e440429a9132c2c7bffc18f634de8fb8.

**Comment by Herschel** [comment]
The game uses `loadMovie` for its music, and this is causing some mismatch between movie and clip event data in `apply_place_object`, so `SwfSlice::to_unbounded_slice` returns None because the slice isn't from the given movie. Previous to 19034b7, all clip events copied themselves into their own Vec before execution.
