### ISSUE TITLE
Error on https://flash.porno-apk.com/game.php?i=18

### ISSUE THREAD

**Issue by qxiaolong** [ruffle-rs/ruffle#2898]
# Error Info
Error name: Error
Error message: panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`: cannot recursively acquire mutex', /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys/wasm/../unsupported/mutex.rs:23:9
Error stack:
```
Error: panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`: cannot recursively acquire mutex', /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys/wasm/../unsupported/mutex.rs:23:9
    at Object.Q (https://flash.porno-apk.com/ruffle/11-01-2021/core.ruffle.3be12cf6e13daeeedf58.js:1:21164)
    at __wbg_new_df6e6ab7a65c4c4d (https://flash.porno-apk.com/ruffle/11-01-2021/ruffle.js:1:38981)
    at std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f (wasm-function[1279]:169)
    at std::sync::once::Once::call_inner::h02eac160d339afc2 (wasm-function[1537]:675)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801 (wasm-function[4274]:67)
    at std::panicking::rust_panic_with_hook::h123718ba3bf480af (wasm-function[3304]:224)
    at std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2 (wasm-function[3885]:159)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925 (wasm-function[4618]:40)
    at rust_begin_unwind (wasm-function[4492]:89)
    at std::panicking::begin_panic_fmt::h96153d9dc0e882ed (wasm-function[4588]:48)
    at std::thread::local::LocalKey<T>::with::heec732f6205b965b (wasm-function[759]:1177)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::h40a4f972bb9b20fd (wasm-function[4525]:36)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::he8c3c8b5e6191161 (wasm-function[4799]:14)
    at k (https://flash.porno-apk.com/ruffle/11-01-2021/core.ruffle.3be12cf6e13daeeedf58.js:1:18617)
    at f (https://flash.porno-apk.com/ruffle/11-01-2021/core.ruffle.3be12cf6e13daeeedf58.js:1:17873)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: game/18.swf
Param movie: game/18.swf
Param quality: high
Param play: true
Param loop: true
Param wmode: window
Param scale: showall
Param allowFullScreen: true
Param menu: true
Param devicefont: false
Param allowScriptAccess: always
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined

# Page Info
Page URL: https://flash.porno-apk.com/game.php?i=18
SWF URL: https://flash.porno-apk.com/game/18.swf

# Browser Info
Useragent: Mozilla/5.0 (Linux; U; Android 6.0.1; zh-cn; OPPO R9sk Build/MMB29M) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/66.0.3359.126 MQQBrowser/10.4 Mobile Safari/537.36
OS: Linux armv8l

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-11
Channel: nightly
Built: 2021-01-11T00:53:04.486Z
Commit: cce3a8199d48ecbce536a0e49efd501d97a2b370

**Comment by Herschel** [comment]
Same issue as #2888.
