### ISSUE TITLE
Error on https://connectdot.connectsolutions.com/l8sxlq958m4/?refresh-parent=true

### ISSUE THREAD

**Issue by SBCounty79** [ruffle-rs/ruffle#2915]
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/gc-arena-0.2.0/src/gc_cell.rs:62:29
Error stack:
```
Error: panicked at 'already borrowed: BorrowMutError', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/gc-arena-0.2.0/src/gc_cell.rs:62:29
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (<anonymous>:3:6318)
    at std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f (chrome-extension://dnnlkjinemffgambpnajiaalgekbmlkk/dist/3cd5f7d3975fd7cf00f7100c4528fd22.wasm:wasm-function[1267]:0x24ed9a)
    at std::sync::once::Once::call_inner::h02eac160d339afc2 (chrome-extension://dnnlkjinemffgambpnajiaalgekbmlkk/dist/3cd5f7d3975fd7cf00f7100c4528fd22.wasm:wasm-function[1527]:0x27e99c)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801 (chrome-extension://dnnlkjinemffgambpnajiaalgekbmlkk/dist/3cd5f7d3975fd7cf00f7100c4528fd22.wasm:wasm-function[4308]:0x353b94)
    at std::panicking::rust_panic_with_hook::h123718ba3bf480af (chrome-extension://dnnlkjinemffgambpnajiaalgekbmlkk/dist/3cd5f7d3975fd7cf00f7100c4528fd22.wasm:wasm-function[3298]:0x32c823)
    at std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2 (chrome-extension://dnnlkjinemffgambpnajiaalgekbmlkk/dist/3cd5f7d3975fd7cf00f7100c4528fd22.wasm:wasm-function[3915]:0x3499fe)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925 (chrome-extension://dnnlkjinemffgambpnajiaalgekbmlkk/dist/3cd5f7d3975fd7cf00f7100c4528fd22.wasm:wasm-function[4654]:0x3592ce)
    at rust_begin_unwind (chrome-extension://dnnlkjinemffgambpnajiaalgekbmlkk/dist/3cd5f7d3975fd7cf00f7100c4528fd22.wasm:wasm-function[4525]:0x3578ac)
    at core::panicking::panic_fmt::h285dc015a87be5a4 (chrome-extension://dnnlkjinemffgambpnajiaalgekbmlkk/dist/3cd5f7d3975fd7cf00f7100c4528fd22.wasm:wasm-function[4656]:0x359332)
    at core::option::expect_none_failed::hb95d2b1dc5448c17 (chrome-extension://dnnlkjinemffgambpnajiaalgekbmlkk/dist/3cd5f7d3975fd7cf00f7100c4528fd22.wasm:wasm-function[3995]:0x34c20e)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://connectdot.connectsolutions.com/l8sxlq958m4/?refresh-parent=true
SWF URL: https://connectdot.connectsolutions.com/l8sxlq958m4/default/viewer.swf?aicc_url=https%3A%2F%2Fconnectdot.connectsolutions.com%2Fservlet%2Fverify%3Fsco-id%3D1040471472%3B1303335689%26airspeed%3D1&aicc_sid=kgiaay7cz7mx2tpbuiqdoxv9mphsnmpm&airspeed=1%2Flmsproxy%3Fsco-id%3D1040471472%26link-transcript-id%3D1303335689%26sid%3Dkgiaay7cz7mx2tpbuiqdoxv9mphsnmpm%26qdata%3D&baseurl=%2Fl8sxlq958m4%2Fdefault%2F&plugin=plugin.swf&host=connectdot.connectsolutions.com&link-transcript-id=1303335689&path=%2Fl8sxlq958m4%2F&refresh-parent=true&reserved-license-id=1303335690&sco-id=1040480818&ticket=kgiaay7cz7mx2tpbuiqdoxv9mphsnmpm&transcript-id=1303335688&isLive=false&room=1040471472;session=breezbreeze9sh24yvpvkgyqov&ticket=kgiaay7cz7mx2tpbuiqdoxv9mphsnmpm&proxy=false&appInstance=7/1030773862-2/output/&ott=smx5kio8ke&css=airspeed&fcsContent=true&pbMode=normal&conStrings=rtmps%3A%2F%2Fdot-fms1.connectsolutions.com%3A443%2F%3Frtmp%3A%2F%2Flocalhost%3A8506%2F&connectors=iad-acts06.cosocloud.com,iad-acts01.cosocloud.com&connector_proto=wss:443&lang=en&account_id=7

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-27
Channel: nightly
Built: 2021-01-27T00:33:31.688Z
Commit: a0159a5efaf9cb29f3d0e5b4a1e1173ad811728a

**Comment by SBCounty79** [comment]
Left an earlier report for Firefox this was in Google Chrome

**Comment by Poopooracoocoo** [comment]
*Requires an Adobe Connect meeting in order to reproduce.

**Comment by SBCounty79** [comment]
I’m not sure if this is for Chrome or FireFox.  I was able to find an app on FireFox for Ruffle.  I installed it and it would not work.  I uninstalled it to try another app, but when I went back to re-install the Ruffle app was not available.  I am seeing that Adobe is blocking Flash content.

**Comment by Lord-McSweeney** [comment]
Closing as the site was using a version of Ruffle that is now 4 years outdated
