### ISSUE TITLE
Error on https://dl.gsu.by/viewtask.asp?nid=1490315&cid=974&lnid=1495681&nttos=&snum=371&tpt=371

### ISSUE THREAD

**Issue by SpectreKr** [ruffle-rs/ruffle#2959]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:490:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:490:50
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (<anonymous>:3:6123)
    at std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f (chrome-extension://imgcmbdifkphgejkpcckgkbnmaghnokg/dist/46f130a0bf0e67be61630875891b8c8a.wasm:wasm-function[1278]:0x25797d)
    at std::sync::once::Once::call_inner::h02eac160d339afc2 (chrome-extension://imgcmbdifkphgejkpcckgkbnmaghnokg/dist/46f130a0bf0e67be61630875891b8c8a.wasm:wasm-function[1534]:0x28683f)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801 (chrome-extension://imgcmbdifkphgejkpcckgkbnmaghnokg/dist/46f130a0bf0e67be61630875891b8c8a.wasm:wasm-function[4361]:0x35d034)
    at std::panicking::rust_panic_with_hook::h123718ba3bf480af (chrome-extension://imgcmbdifkphgejkpcckgkbnmaghnokg/dist/46f130a0bf0e67be61630875891b8c8a.wasm:wasm-function[3307]:0x334b7b)
    at std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2 (chrome-extension://imgcmbdifkphgejkpcckgkbnmaghnokg/dist/46f130a0bf0e67be61630875891b8c8a.wasm:wasm-function[3919]:0x351a34)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925 (chrome-extension://imgcmbdifkphgejkpcckgkbnmaghnokg/dist/46f130a0bf0e67be61630875891b8c8a.wasm:wasm-function[4693]:0x362365)
    at rust_begin_unwind (chrome-extension://imgcmbdifkphgejkpcckgkbnmaghnokg/dist/46f130a0bf0e67be61630875891b8c8a.wasm:wasm-function[4572]:0x360b37)
    at core::panicking::panic_fmt::h285dc015a87be5a4 (chrome-extension://imgcmbdifkphgejkpcckgkbnmaghnokg/dist/46f130a0bf0e67be61630875891b8c8a.wasm:wasm-function[4695]:0x3623c9)
    at core::option::expect_none_failed::hb95d2b1dc5448c17 (chrome-extension://imgcmbdifkphgejkpcckgkbnmaghnokg/dist/46f130a0bf0e67be61630875891b8c8a.wasm:wasm-function[4003]:0x354479)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://dl.gsu.by/viewtask.asp?nid=1490315&cid=974&lnid=1495681&nttos=&snum=371&tpt=371
SWF URL: https://dl.gsu.by/images/tangram/tangram.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-29
Channel: nightly
Built: 2021-01-29T00:34:32.424Z
Commit: bb4240ad1f9705b080c9f7861e38b6677a62d76b

**Comment by Poopooracoocoo** [comment]
FYI this is a learning portal that requires a login.

Loading up the SWF in the web demo says that it contains AS3. Loading it in Adobe Flash brings up some kind of error, I think. It looks like there's a button below that text but I don't know what it does as it's in Russian.
