### ISSUE TITLE
Error on https://www.stsci.edu/~marel/black_holes/modules.html

### ISSUE THREAD

**Issue by shentino** [ruffle-rs/ruffle#2967]
# Error Info
Error name: Error
Error message: panicked at 'slice index starts at 103452 but ends at 0', web/src/audio.rs:435:26
Error stack:
```
Error: panicked at 'slice index starts at 103452 but ends at 0', web/src/audio.rs:435:26
    at Object.Q (chrome-extension://ekjcoklmihdkllfmcfhmjlpihkkjeahh/dist/core.ruffle.js:1:21332)
    at __wbg_new_df6e6ab7a65c4c4d (<anonymous>:3:38357)
    at std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f (chrome-extension://ekjcoklmihdkllfmcfhmjlpihkkjeahh/dist/b4716f96db7fd93a9458.module.wasm:wasm-function[1288]:0x2636a1)
    at std::sync::once::Once::call_inner::h02eac160d339afc2 (chrome-extension://ekjcoklmihdkllfmcfhmjlpihkkjeahh/dist/b4716f96db7fd93a9458.module.wasm:wasm-function[1539]:0x291d92)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801 (chrome-extension://ekjcoklmihdkllfmcfhmjlpihkkjeahh/dist/b4716f96db7fd93a9458.module.wasm:wasm-function[4281]:0x3658db)
    at std::panicking::rust_panic_with_hook::h123718ba3bf480af (chrome-extension://ekjcoklmihdkllfmcfhmjlpihkkjeahh/dist/b4716f96db7fd93a9458.module.wasm:wasm-function[3312]:0x34053c)
    at std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2 (chrome-extension://ekjcoklmihdkllfmcfhmjlpihkkjeahh/dist/b4716f96db7fd93a9458.module.wasm:wasm-function[3889]:0x35b821)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925 (chrome-extension://ekjcoklmihdkllfmcfhmjlpihkkjeahh/dist/b4716f96db7fd93a9458.module.wasm:wasm-function[4627]:0x36b02f)
    at rust_begin_unwind (chrome-extension://ekjcoklmihdkllfmcfhmjlpihkkjeahh/dist/b4716f96db7fd93a9458.module.wasm:wasm-function[4500]:0x36966c)
    at core::panicking::panic_fmt::h285dc015a87be5a4 (chrome-extension://ekjcoklmihdkllfmcfhmjlpihkkjeahh/dist/b4716f96db7fd93a9458.module.wasm:wasm-function[4629]:0x36b093)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://www.stsci.edu/~marel/black_holes/modules.html
SWF URL: https://www.stsci.edu/~marel/black_holes/blackholes.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-12
Channel: nightly
Built: 2021-01-12T00:55:17.048Z
Commit: 73d123091014e190f4bc4d8edf98cab2e671cc3a

**Comment by Herschel** [comment]
Hi, could you try with a recent version of the extension? I think this would be fixed, and I'm not able to repro with a recent version. Thank you!

**Comment by shentino** [comment]
"FlashPlayer - SWF to HTML" can't find any flash content on this page for some reason.  What's the best way to actually invoke ruffle from a web page?

**Comment by Poopooracoocoo** [comment]
You should use the actual Ruffle extension. It's not in the Chrome Web Store and needs to be sideloaded at the moment. It can't be automatically updated in Chrome, while I think it *can* be in Firefox. It's fairly straightforward to install. :)
