### ISSUE TITLE
Error on https://web.archive.org/web/20110228011756/http://faunasphere.com/

### ISSUE THREAD

**Issue by austereskylark** [ruffle-rs/ruffle#2970]
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/gc-arena-0.2.0/src/gc_cell.rs:62:29
Error stack:
```
Error: panicked at 'already borrowed: BorrowMutError', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/gc-arena-0.2.0/src/gc_cell.rs:62:29
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (<anonymous>:3:6123)
    at std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f (chrome-extension://jgbgmnfapejidjljbpidnolhcfpgdoko/dist/46f130a0bf0e67be61630875891b8c8a.wasm:wasm-function[1278]:0x25797d)
    at std::sync::once::Once::call_inner::h02eac160d339afc2 (chrome-extension://jgbgmnfapejidjljbpidnolhcfpgdoko/dist/46f130a0bf0e67be61630875891b8c8a.wasm:wasm-function[1534]:0x28683f)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801 (chrome-extension://jgbgmnfapejidjljbpidnolhcfpgdoko/dist/46f130a0bf0e67be61630875891b8c8a.wasm:wasm-function[4361]:0x35d034)
    at std::panicking::rust_panic_with_hook::h123718ba3bf480af (chrome-extension://jgbgmnfapejidjljbpidnolhcfpgdoko/dist/46f130a0bf0e67be61630875891b8c8a.wasm:wasm-function[3307]:0x334b7b)
    at std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2 (chrome-extension://jgbgmnfapejidjljbpidnolhcfpgdoko/dist/46f130a0bf0e67be61630875891b8c8a.wasm:wasm-function[3919]:0x351a34)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925 (chrome-extension://jgbgmnfapejidjljbpidnolhcfpgdoko/dist/46f130a0bf0e67be61630875891b8c8a.wasm:wasm-function[4693]:0x362365)
    at rust_begin_unwind (chrome-extension://jgbgmnfapejidjljbpidnolhcfpgdoko/dist/46f130a0bf0e67be61630875891b8c8a.wasm:wasm-function[4572]:0x360b37)
    at core::panicking::panic_fmt::h285dc015a87be5a4 (chrome-extension://jgbgmnfapejidjljbpidnolhcfpgdoko/dist/46f130a0bf0e67be61630875891b8c8a.wasm:wasm-function[4695]:0x3623c9)
    at core::option::expect_none_failed::hb95d2b1dc5448c17 (chrome-extension://jgbgmnfapejidjljbpidnolhcfpgdoko/dist/46f130a0bf0e67be61630875891b8c8a.wasm:wasm-function[4003]:0x354479)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: http://assets.faunasphere.com/fauna_us/images/en/splash.valentines.swf
Param quality: high
Param bgcolor: #FFFFFF
Param allowscriptaccess: always
Param wmode: transparent
Param name: splashvid
Param flashvars: gameLinkUrl=https://web.archive.org/web/20110228011756/https://susi.faunasphere.com/login.php?l=JuyF6qZnSoQWWgMilqKKqs2qAARco3i_kBhc5FIZERj7tt4hcCe0n7Np7qUYCSli&ol=RPCeHXZ6TlUQQ72skA-YUA&amp;sid=rawScErWShvw0MKC4B3g8A&amp;lid=3U0gWMyeDgXCt6MCT1wchA&facebookCanvasUrl=https://web.archive.org/web/20110228011756/http://www.faunasphere.com/help/?rn=1020
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined

# Page Info
Page URL: https://web.archive.org/web/20110228011756/http://faunasphere.com/
SWF URL: http://assets.faunasphere.com/fauna_us/images/en/splash.valentines.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-29
Channel: nightly
Built: 2021-01-29T00:34:32.424Z
Commit: bb4240ad1f9705b080c9f7861e38b6677a62d76b

**Comment by Poopooracoocoo** [comment]
I'm not sure if that game would work anyway as I think it requires a server and has an online aspect. 

Seeing that news post that they're shutting the game down made me really really sad and I never even played it. It makes me wish I never saw it.

**Comment by aruite** [comment]
> I'm not sure if that game would work anyway as I think it requires a server and has an online aspect.
> 
> Seeing that news post that they're shutting the game down made me really really sad and I never even played it. It makes me wish I never saw it.
> 
> Edit: but try playing the SWF by itself in Ruffle and in Flash Player (which you can get from BlueMaxima's Flashpoint)

thanks, how do you get the swf though ? also it was just on the home screen which i dont think is the actual game (though it would be awesome to get the swf of the actual game).

**Comment by Lord-McSweeney** [comment]
Closing as the site was using a version of Ruffle that is now 4 years outdated
