### ISSUE TITLE
Error on http://mevytenlinea.inea.gob.mx/implantacion2a/mod/inea/inea.php/23,30,154/lye_v2/navegacion/left2.htm

### ISSUE THREAD

**Issue by javier292** [ruffle-rs/ruffle#3054]
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/gc-arena-0.2.0/src/gc_cell.rs:62:29
Error stack:
```
Error: panicked at 'already borrowed: BorrowMutError', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/gc-arena-0.2.0/src/gc_cell.rs:62:29
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (<anonymous>:3:6389)
    at std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f (chrome-extension://ikjfaefpiggklhjgfhlnddpeggfpekfm/dist/e3d4317b919f1d350ef3af3e3967d738.wasm:wasm-function[1289]:0x292750)
    at std::sync::once::Once::call_inner::h02eac160d339afc2 (chrome-extension://ikjfaefpiggklhjgfhlnddpeggfpekfm/dist/e3d4317b919f1d350ef3af3e3967d738.wasm:wasm-function[1557]:0x2c773a)
    at ruffle_web::set_panic_handler::{{closure}}::{{closure}}::h3ce0d4de7eb2263c (chrome-extension://ikjfaefpiggklhjgfhlnddpeggfpekfm/dist/e3d4317b919f1d350ef3af3e3967d738.wasm:wasm-function[4646]:0x3c0dd4)
    at std::panicking::rust_panic_with_hook::h123718ba3bf480af (chrome-extension://ikjfaefpiggklhjgfhlnddpeggfpekfm/dist/e3d4317b919f1d350ef3af3e3967d738.wasm:wasm-function[3530]:0x39430e)
    at std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2 (chrome-extension://ikjfaefpiggklhjgfhlnddpeggfpekfm/dist/e3d4317b919f1d350ef3af3e3967d738.wasm:wasm-function[4184]:0x3b43a9)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925 (chrome-extension://ikjfaefpiggklhjgfhlnddpeggfpekfm/dist/e3d4317b919f1d350ef3af3e3967d738.wasm:wasm-function[5043]:0x3c72f4)
    at rust_begin_unwind (chrome-extension://ikjfaefpiggklhjgfhlnddpeggfpekfm/dist/e3d4317b919f1d350ef3af3e3967d738.wasm:wasm-function[4884]:0x3c5212)
    at core::panicking::panic_fmt::h285dc015a87be5a4 (chrome-extension://ikjfaefpiggklhjgfhlnddpeggfpekfm/dist/e3d4317b919f1d350ef3af3e3967d738.wasm:wasm-function[5045]:0x3c7358)
    at core::option::expect_none_failed::hb95d2b1dc5448c17 (chrome-extension://ikjfaefpiggklhjgfhlnddpeggfpekfm/dist/e3d4317b919f1d350ef3af3e3967d738.wasm:wasm-function[4275]:0x3b74b7)
```

# Player Info
Allows script access: true

# Page Info
Page URL: http://mevytenlinea.inea.gob.mx/implantacion2a/mod/inea/inea.php/23,30,154/lye_v2/navegacion/left2.htm
SWF URL: http://mevytenlinea.inea.gob.mx/implantacion2a/mod/inea/inea.php/23,30,154/lye_v2/navegacion/flash/left2.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-02-02
Channel: nightly
Built: 2021-02-02T00:21:23.909Z
Commit: 5783021d99477357a1d291d47fc0fd16082fbd98

**Comment by Lord-McSweeney** [comment]
Closing as the site was using a version of Ruffle that is now 4 years outdated
