### ISSUE TITLE
Error on http://pecsappn1.pec.be:50000/OrgChart/ChartAppWithPhone.jsp?splitdirectory=true

### ISSUE THREAD

**Issue by klewais** [ruffle-rs/ruffle#3058]
# Error Info
Error name: Error
Error message: panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:542:5
Error stack:
```
Error: panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:542:5
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (<anonymous>:3:6695)
    at std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f (chrome-extension://eedhcdhcgkfbbcjbgjankglhehknkoka/dist/84f8af60b6c09883bb6522c94d475007.wasm:wasm-function[1597]:0x2dd2cf)
    at std::sync::once::Once::call_inner::h02eac160d339afc2 (chrome-extension://eedhcdhcgkfbbcjbgjankglhehknkoka/dist/84f8af60b6c09883bb6522c94d475007.wasm:wasm-function[1619]:0x2e14da)
    at ruffle_web::set_panic_handler::{{closure}}::{{closure}}::h3ce0d4de7eb2263c (chrome-extension://eedhcdhcgkfbbcjbgjankglhehknkoka/dist/84f8af60b6c09883bb6522c94d475007.wasm:wasm-function[4895]:0x3e5686)
    at std::panicking::rust_panic_with_hook::h123718ba3bf480af (chrome-extension://eedhcdhcgkfbbcjbgjankglhehknkoka/dist/84f8af60b6c09883bb6522c94d475007.wasm:wasm-function[3672]:0x3b4fdc)
    at std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2 (chrome-extension://eedhcdhcgkfbbcjbgjankglhehknkoka/dist/84f8af60b6c09883bb6522c94d475007.wasm:wasm-function[4371]:0x3d70be)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925 (chrome-extension://eedhcdhcgkfbbcjbgjankglhehknkoka/dist/84f8af60b6c09883bb6522c94d475007.wasm:wasm-function[5314]:0x3ec15d)
    at rust_begin_unwind (chrome-extension://eedhcdhcgkfbbcjbgjankglhehknkoka/dist/84f8af60b6c09883bb6522c94d475007.wasm:wasm-function[5150]:0x3e9f81)
    at core::panicking::panic_fmt::h285dc015a87be5a4 (chrome-extension://eedhcdhcgkfbbcjbgjankglhehknkoka/dist/84f8af60b6c09883bb6522c94d475007.wasm:wasm-function[5316]:0x3ec1c1)
    at core::panicking::panic::h0abe4e7a620ae568 (chrome-extension://eedhcdhcgkfbbcjbgjankglhehknkoka/dist/84f8af60b6c09883bb6522c94d475007.wasm:wasm-function[5070]:0x3e8ac3)
```

# Player Info
Allows script access: true

# Page Info
Page URL: http://pecsappn1.pec.be:50000/OrgChart/ChartAppWithPhone.jsp?splitdirectory=true
SWF URL: http://pecsappn1.pec.be:50000/OrgChart/OrgChart.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-02-03
Channel: nightly
Built: 2021-02-03T00:18:37.586Z
Commit: 59966348c6e7adf88f2cf28e5ebdcebc9f2c0881

**Comment by n0samu** [comment]
The webpage no longer exists and was never archived :(
