### ISSUE TITLE
Error on globetrotterxl.swf

### ISSUE THREAD

**Issue by rmertens** [ruffle-rs/ruffle#3071]
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/gc-arena-0.2.0/src/gc_cell.rs:62:29
Error stack:
```
Error: panicked at 'already borrowed: BorrowMutError', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/gc-arena-0.2.0/src/gc_cell.rs:62:29
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://ruffle.rs/demo/index.js:1:17560)
    at std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f (https://ruffle.rs/demo/72622b051eb31ffb7c70ef3f0ca63e55.wasm:wasm-function[1566]:0x29e166)
    at std::sync::once::Once::call_inner::h02eac160d339afc2 (https://ruffle.rs/demo/72622b051eb31ffb7c70ef3f0ca63e55.wasm:wasm-function[1588]:0x2a1ed6)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801 (https://ruffle.rs/demo/72622b051eb31ffb7c70ef3f0ca63e55.wasm:wasm-function[4604]:0x38394c)
    at std::panicking::rust_panic_with_hook::h123718ba3bf480af (https://ruffle.rs/demo/72622b051eb31ffb7c70ef3f0ca63e55.wasm:wasm-function[3449]:0x357d9b)
    at std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2 (https://ruffle.rs/demo/72622b051eb31ffb7c70ef3f0ca63e55.wasm:wasm-function[4109]:0x376e2f)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925 (https://ruffle.rs/demo/72622b051eb31ffb7c70ef3f0ca63e55.wasm:wasm-function[4957]:0x38914a)
    at rust_begin_unwind (https://ruffle.rs/demo/72622b051eb31ffb7c70ef3f0ca63e55.wasm:wasm-function[4832]:0x38785d)
    at core::panicking::panic_fmt::h285dc015a87be5a4 (https://ruffle.rs/demo/72622b051eb31ffb7c70ef3f0ca63e55.wasm:wasm-function[4959]:0x3891ae)
    at core::option::expect_none_failed::hb95d2b1dc5448c17 (https://ruffle.rs/demo/72622b051eb31ffb7c70ef3f0ca63e55.wasm:wasm-function[4205]:0x379e88)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://ruffle.rs/demo/
SWF URL: https://files.crazygames.com/globetrotterxl.swf

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-02-04
Channel: nightly
Built: 2021-02-04T00:17:27.254Z
Commit: ac47b56fef8781a21ed5a26858c73d7d6d18e132

**Comment by Poopooracoocoo** [comment]
Not seeing any errors with the latest version of Ruffle.
