### ISSUE TITLE
Error on http://www.novalight.net/NOVALIGHT.html

### ISSUE THREAD

**Issue by thedarkb** [ruffle-rs/ruffle#3101]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:490:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:490:50
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (http://www.novalight.net/ruffle.js:1:6349)
    at std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f (<anonymous>:wasm-function[1267]:0x24ef2a)
    at std::sync::once::Once::call_inner::h02eac160d339afc2 (<anonymous>:wasm-function[1528]:0x27ed9a)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801 (<anonymous>:wasm-function[4308]:0x353f1a)
    at std::panicking::rust_panic_with_hook::h123718ba3bf480af (<anonymous>:wasm-function[3299]:0x32cc21)
    at std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2 (<anonymous>:wasm-function[3916]:0x349dfc)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925 (<anonymous>:wasm-function[4654]:0x359654)
    at rust_begin_unwind (<anonymous>:wasm-function[4525]:0x357c32)
    at core::panicking::panic_fmt::h285dc015a87be5a4 (<anonymous>:wasm-function[4656]:0x3596b8)
    at core::option::expect_none_failed::hb95d2b1dc5448c17 (<anonymous>:wasm-function[3995]:0x34c594)
```

# Player Info
Allows script access: true

# Page Info
Page URL: http://www.novalight.net/NOVALIGHT.html
SWF URL: http://www.novalight.net/NOVALIGHTY.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-26
Channel: nightly
Built: 2021-01-26T00:36:48.131Z
Commit: 7856cdd3d770e406ce546bf1745d8046d7b716f8

**Comment by ousia** [comment]
@thedarkb,

in order to reproduce the issue, could you describe what you were doing before it happened?

**Comment by thedarkb** [comment]
I opened the page and got the error. It went away when I refreshed.
