### ISSUE TITLE
Here are the details for the issue that I have just encountered.

### ISSUE THREAD

**Issue by wsssmith20** [ruffle-rs/ruffle#3106]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:465:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:465:50
    at Object.D (https://www.mathsworkout.co.uk/legacy/ruffle/core.ruffle.a2dfc53a3fdf3085c069.js:1:20372)
    at __wbg_new_df6e6ab7a65c4c4d (https://www.mathsworkout.co.uk/legacy/ruffle/ruffle.js:1:34986)
    at https://www.mathsworkout.co.uk/legacy/ruffle/2583fcc0c02f07ea94e3.module.wasm:wasm-function[1058]:0x206ad5
    at https://www.mathsworkout.co.uk/legacy/ruffle/2583fcc0c02f07ea94e3.module.wasm:wasm-function[1378]:0x244bb3
    at https://www.mathsworkout.co.uk/legacy/ruffle/2583fcc0c02f07ea94e3.module.wasm:wasm-function[3687]:0x2f7a6b
    at https://www.mathsworkout.co.uk/legacy/ruffle/2583fcc0c02f07ea94e3.module.wasm:wasm-function[2918]:0x2da6de
    at https://www.mathsworkout.co.uk/legacy/ruffle/2583fcc0c02f07ea94e3.module.wasm:wasm-function[3984]:0x2fc718
    at https://www.mathsworkout.co.uk/legacy/ruffle/2583fcc0c02f07ea94e3.module.wasm:wasm-function[4014]:0x2fcc7b
    at https://www.mathsworkout.co.uk/legacy/ruffle/2583fcc0c02f07ea94e3.module.wasm:wasm-function[3889]:0x2fb2e8
    at https://www.mathsworkout.co.uk/legacy/ruffle/2583fcc0c02f07ea94e3.module.wasm:wasm-function[4015]:0x2fccb1
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: pythagoras.swf
Param movie: pythagoras.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined

# Page Info
Page URL: https://www.mathsworkout.co.uk/legacy/pythagoras.php

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2020-11-30
Channel: nightly
Built: 2020-11-30T00:33:10.981Z
Commit: d27b46b3dc421263555299cdf05a632dde27899e

**Comment by ousia** [comment]
@wsssmith20,

It requires username and password.

Could you provide a direct link to the SWF animation?

**Comment by wsssmith20** [comment]
Hi, what is the SWF?

**Comment by ousia** [comment]
The animation file that Ruffle displays.

**Comment by ousia** [comment]
SWF stands for _Shockwave Flash_, now called _Macromedia Flash_.

**Comment by wsssmith20** [comment]
Hi, thank you, if it is alright if I send this through tomorrow?

**Comment by ousia** [comment]
@wsssmith20,

it is perfectly fine that you attach the SWF here when it is better for you.

By the way, I’m not the one who is going to fix the issue. I cannot write code.

I’m only trying to clarify which is the error you are facing with Ruffle, so any developer might fix it.

Besides the error message, it would be helpful that you describe what you were doing when you got it.

Errors might be fixed only when they can be replicated by developers (so they can see what is going wrong in Ruffle).

I hope it helps. Enjoy your weekend.

**Comment by Poopooracoocoo** [comment]
@wsssmith20 \*ahem*
