### ISSUE TITLE
Error on https://www.uclick.com/client/boh/sudoc/2021/01/23/

### ISSUE THREAD

**Issue by dlm1111** [ruffle-rs/ruffle#3109]
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', web/src/lib.rs:838:49
Error stack:
```
Error: panicked at 'already borrowed: BorrowMutError', web/src/lib.rs:838:49
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (<anonymous>:3:6695)
    at std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f (chrome-extension://flacbdmmakcdkgejddnlcckkngdkhcde/dist/72622b051eb31ffb7c70ef3f0ca63e55.wasm:wasm-function[1566]:0x29e166)
    at std::sync::once::Once::call_inner::h02eac160d339afc2 (chrome-extension://flacbdmmakcdkgejddnlcckkngdkhcde/dist/72622b051eb31ffb7c70ef3f0ca63e55.wasm:wasm-function[1588]:0x2a1ed6)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801 (chrome-extension://flacbdmmakcdkgejddnlcckkngdkhcde/dist/72622b051eb31ffb7c70ef3f0ca63e55.wasm:wasm-function[4604]:0x38394c)
    at std::panicking::rust_panic_with_hook::h123718ba3bf480af (chrome-extension://flacbdmmakcdkgejddnlcckkngdkhcde/dist/72622b051eb31ffb7c70ef3f0ca63e55.wasm:wasm-function[3449]:0x357d9b)
    at std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2 (chrome-extension://flacbdmmakcdkgejddnlcckkngdkhcde/dist/72622b051eb31ffb7c70ef3f0ca63e55.wasm:wasm-function[4109]:0x376e2f)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925 (chrome-extension://flacbdmmakcdkgejddnlcckkngdkhcde/dist/72622b051eb31ffb7c70ef3f0ca63e55.wasm:wasm-function[4957]:0x38914a)
    at rust_begin_unwind (chrome-extension://flacbdmmakcdkgejddnlcckkngdkhcde/dist/72622b051eb31ffb7c70ef3f0ca63e55.wasm:wasm-function[4832]:0x38785d)
    at core::panicking::panic_fmt::h285dc015a87be5a4 (chrome-extension://flacbdmmakcdkgejddnlcckkngdkhcde/dist/72622b051eb31ffb7c70ef3f0ca63e55.wasm:wasm-function[4959]:0x3891ae)
    at core::option::expect_none_failed::hb95d2b1dc5448c17 (chrome-extension://flacbdmmakcdkgejddnlcckkngdkhcde/dist/72622b051eb31ffb7c70ef3f0ca63e55.wasm:wasm-function[4205]:0x379e88)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://www.uclick.com/client/boh/sudoc/2021/01/23/
SWF URL: https://www.uclick.com/puzzles/sudoc/sudoku_engine_daily.swf?dt=210123&xurl=https://www.uclick.com/puzzles/sudoc/su_control.xml&m=1

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-02-04
Channel: nightly
Built: 2021-02-04T00:17:27.254Z
Commit: ac47b56fef8781a21ed5a26858c73d7d6d18e132

**Comment by dlm1111** [comment]
Crashes when the animated victory screen is displayed upon winning the sudoku game.

**Comment by Lord-McSweeney** [comment]
Closing as the site was using a version of Ruffle that is now 4 years outdated
