### ISSUE TITLE
Error on https://www.clickjogos.com.br/Jogos-online/Acao-e-Aventura/Road-of-the-Dead

### ISSUE THREAD

**Issue by Mr51x** [ruffle-rs/ruffle#3116]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: JsValue(TypeError: Failed to fetch
TypeError: Failed to fetch)', web/src/navigator.rs:201:18
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: JsValue(TypeError: Failed to fetch
TypeError: Failed to fetch)', web/src/navigator.rs:201:18
    at Object.J (https://www.clickjogos.com.br/ruffle/core.ruffle.b038bd33651650e53735.js:898:18)
    at __wbg_new_df6e6ab7a65c4c4d (https://www.clickjogos.com.br/ruffle/ruffle.js:1835:65)
    at std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f (https://www.clickjogos.com.br/ruffle/4ee107bd02685b71c22f.module.wasm:wasm-function[1279]:0x2649fb)
    at std::sync::once::Once::call_inner::h02eac160d339afc2 (https://www.clickjogos.com.br/ruffle/4ee107bd02685b71c22f.module.wasm:wasm-function[1547]:0x295a73)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801 (https://www.clickjogos.com.br/ruffle/4ee107bd02685b71c22f.module.wasm:wasm-function[4311]:0x3699c8)
    at std::panicking::rust_panic_with_hook::h123718ba3bf480af (https://www.clickjogos.com.br/ruffle/4ee107bd02685b71c22f.module.wasm:wasm-function[3309]:0x342c41)
    at std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2 (https://www.clickjogos.com.br/ruffle/4ee107bd02685b71c22f.module.wasm:wasm-function[3918]:0x35f7ca)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925 (https://www.clickjogos.com.br/ruffle/4ee107bd02685b71c22f.module.wasm:wasm-function[4654]:0x36f065)
    at rust_begin_unwind (https://www.clickjogos.com.br/ruffle/4ee107bd02685b71c22f.module.wasm:wasm-function[4528]:0x36d6e5)
    at core::panicking::panic_fmt::h285dc015a87be5a4 (https://www.clickjogos.com.br/ruffle/4ee107bd02685b71c22f.module.wasm:wasm-function[4656]:0x36f0c9)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: https://img.clickjogos.com.br/dl/6/6dfc6ab13ba5ebc114d093d0227d4189/src.swf
Param movie: https://img.clickjogos.com.br/dl/6/6dfc6ab13ba5ebc114d093d0227d4189/src.swf
Param allowScriptAccess: always
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://www.clickjogos.com.br/Jogos-online/Acao-e-Aventura/Road-of-the-Dead
SWF URL: https://img.clickjogos.com.br/dl/6/6dfc6ab13ba5ebc114d093d0227d4189/src.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-15
Channel: nightly
Built: 2021-01-15T01:03:45.335Z
Commit: 09a48a71d8608803fd5dba4343c5f10c928f9652

**Comment by Poopooracoocoo** [comment]
Road of the Dead is written in ActionScript 3, the newer language for SWFs, usually from 2006 and onwards. Ruffle does not currently support it. Support for it may take several months. Consider contributing to Ruffle's code or donating ;)
