### ISSUE TITLE
Error on https://playsexgames.xxx/pineapple-mermaid/

### ISSUE THREAD

**Issue by malone484** [ruffle-rs/ruffle#3143]
# Error Info
Error name: Error
Error message: panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`: cannot recursively acquire mutex', /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys/wasm/../unsupported/mutex.rs:23:9
Error stack:
```
Error: panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`: cannot recursively acquire mutex', /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys/wasm/../unsupported/mutex.rs:23:9
    at Object.Q (https://playsexgames.xxx/html/core.ruffle.3be12cf6e13daeeedf58.js:1:21164)
    at __wbg_new_df6e6ab7a65c4c4d (https://playsexgames.xxx/html/ruffle.js:1:38981)
    at std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f (https://playsexgames.xxx/html/bbc3b10d6b9019cdac0b.module.wasm:wasm-function[1279]:0x25eedb)
    at std::sync::once::Once::call_inner::h02eac160d339afc2 (https://playsexgames.xxx/html/bbc3b10d6b9019cdac0b.module.wasm:wasm-function[1537]:0x28eac1)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801 (https://playsexgames.xxx/html/bbc3b10d6b9019cdac0b.module.wasm:wasm-function[4274]:0x361c64)
    at std::panicking::rust_panic_with_hook::h123718ba3bf480af (https://playsexgames.xxx/html/bbc3b10d6b9019cdac0b.module.wasm:wasm-function[3304]:0x33c6a5)
    at std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2 (https://playsexgames.xxx/html/bbc3b10d6b9019cdac0b.module.wasm:wasm-function[3885]:0x357ce6)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925 (https://playsexgames.xxx/html/bbc3b10d6b9019cdac0b.module.wasm:wasm-function[4618]:0x36733c)
    at rust_begin_unwind (https://playsexgames.xxx/html/bbc3b10d6b9019cdac0b.module.wasm:wasm-function[4492]:0x3659ab)
    at std::panicking::begin_panic_fmt::h96153d9dc0e882ed (https://playsexgames.xxx/html/bbc3b10d6b9019cdac0b.module.wasm:wasm-function[4588]:0x366dd4)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://playsexgames.xxx/pineapple-mermaid/
SWF URL: https://playsexgames.xxx/play-sex-games/pineapple_mermaid.swf

# Browser Info
Useragent: Mozilla/5.0 (Linux; Android 10; moto e) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.141 Mobile Safari/537.36
OS: Linux armv7l

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-11
Channel: nightly
Built: 2021-01-11T00:53:04.486Z
Commit: cce3a8199d48ecbce536a0e49efd501d97a2b370

**Comment by Lord-McSweeney** [comment]
Closing as the SWF was run with a version of Ruffle that is now five years outdated
