### ISSUE TITLE
Error on https://playsexgames.xxx/the-classic/

### ISSUE THREAD

**Issue by z862** [ruffle-rs/ruffle#3182]
# Error Info
Error name: TypeError
Error message: o(...).values is not a function
Error stack:
```
TypeError: o(...).values is not a function
    at Object.ur (https://playsexgames.xxx/html/core.ruffle.3be12cf6e13daeeedf58.js:1:33469)
    at __wbg_values_f28e313e2260a03a (https://playsexgames.xxx/html/ruffle.js:1:63243)
    at js_sys::Array::values::hfe81db5d547ca803 (wasm-function[5167]:6)
    at ruffle_web::populate_movie_parameters::hb42d752746f477c9 (wasm-function[1878]:59)
    at std::thread::local::LocalKey<T>::with::h2ea8de2a8acc03ac (wasm-function[1435]:226)
    at ruffle_stream_from (wasm-function[3625]:112)
    at W.stream_from (https://playsexgames.xxx/html/core.ruffle.3be12cf6e13daeeedf58.js:1:20060)
    at HTMLElement.<anonymous> (https://playsexgames.xxx/html/ruffle.js:1:18211)
    at Generator.next (<anonymous>)
    at c (https://playsexgames.xxx/html/ruffle.js:1:12825)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://playsexgames.xxx/the-classic/
SWF URL: https://playsexgames.xxx/play-sex-games/the_classic.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-11
Channel: nightly
Built: 2021-01-11T00:53:04.486Z
Commit: cce3a8199d48ecbce536a0e49efd501d97a2b370

**Comment by killme990** [comment]
ah yes my favorite game sit playsexgames.xxx

**Comment by adrian17** [comment]
From what I see, this is Chrome 63, which is way below officially supported version (https://github.com/ruffle-rs/ruffle/wiki#web). That also explains the error (`array.values()` indeed didn't exist in that Chrome version yet). So with this, I'm closing this issue.
