### ISSUE TITLE
Error on https://coolpiano.ru/super-bass--nicki-minaj/

### ISSUE THREAD

**Issue by Jakshbae** [ruffle-rs/ruffle#3225]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:490:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:490:50
    at r.wbg.__wbg_new_df6e6ab7a65c4c4d (<anonymous>:3:11028)
    at std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f (chrome-extension://hnicgckkbamlonjfbkdilljeegpbjabo/dist/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[1265]:0x24e3c9)
    at std::sync::once::Once::call_inner::h02eac160d339afc2 (chrome-extension://hnicgckkbamlonjfbkdilljeegpbjabo/dist/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[1528]:0x27e7a0)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801 (chrome-extension://hnicgckkbamlonjfbkdilljeegpbjabo/dist/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[4309]:0x3537a0)
    at std::panicking::rust_panic_with_hook::h123718ba3bf480af (chrome-extension://hnicgckkbamlonjfbkdilljeegpbjabo/dist/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[3299]:0x32c417)
    at std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2 (chrome-extension://hnicgckkbamlonjfbkdilljeegpbjabo/dist/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[3916]:0x3495f5)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925 (chrome-extension://hnicgckkbamlonjfbkdilljeegpbjabo/dist/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[4655]:0x358eda)
    at rust_begin_unwind (chrome-extension://hnicgckkbamlonjfbkdilljeegpbjabo/dist/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[4526]:0x3574b8)
    at core::panicking::panic_fmt::h285dc015a87be5a4 (chrome-extension://hnicgckkbamlonjfbkdilljeegpbjabo/dist/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[4657]:0x358f3e)
    at core::option::expect_none_failed::hb95d2b1dc5448c17 (chrome-extension://hnicgckkbamlonjfbkdilljeegpbjabo/dist/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[3996]:0x34be07)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: /instruments/piano/piano.swf
Param quality: high
Param bgcolor: #ffffff
Param allowscriptaccess: sameDomain
Param allowfullscreen: true
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined
Attribute 6: undefined

# Page Info
Page URL: https://coolpiano.ru/super-bass--nicki-minaj/
SWF URL: https://coolpiano.ru/instruments/piano/piano.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-25
Channel: nightly
Built: 2021-01-25T01:05:41.178Z
Commit: 32fd3fb71befbceecbba7c73d08af5ddd0f5a3d0

**Comment by Poopooracoocoo** [comment]
AS3 warning when SWF is played in the demo... I get a white screen when I open the SWF.
