### ISSUE TITLE
Error on https://megami.starcreator.com/nanaca-crash/

### ISSUE THREAD

**Issue by shinstc** [ruffle-rs/ruffle#3246]
Error occurs when opening the menu on the top left of the screen and highlighting either Quality or Sound when in pre-game or mid-game. Does not occur if done in post-game.

# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/gc-arena-0.2.0/src/gc_cell.rs:62:29
Error stack:
```
Error: panicked at 'already borrowed: BorrowMutError', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/gc-arena-0.2.0/src/gc_cell.rs:62:29
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://megami.starcreator.com/nanaca-crash/ruffle.js:1:6799)
    at std::sync::once::Once::call_once::{{closure}}::hce6501f6f20767e4 (https://megami.starcreator.com/nanaca-crash/4d640ad5aa95d1360f7c8c38e9c8b0d8.wasm:wasm-function[1327]:0x26ba91)
    at std::sync::once::Once::call_inner::hd3d269a4946f2df2 (https://megami.starcreator.com/nanaca-crash/4d640ad5aa95d1360f7c8c38e9c8b0d8.wasm:wasm-function[1604]:0x29efac)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h6ed7686ed76cb258 (https://megami.starcreator.com/nanaca-crash/4d640ad5aa95d1360f7c8c38e9c8b0d8.wasm:wasm-function[4639]:0x3823e3)
    at std::panicking::rust_panic_with_hook::h4f753dc70b771d8e (https://megami.starcreator.com/nanaca-crash/4d640ad5aa95d1360f7c8c38e9c8b0d8.wasm:wasm-function[3509]:0x357cb7)
    at std::panicking::begin_panic_handler::{{closure}}::h5c9fc29957309ae8 (https://megami.starcreator.com/nanaca-crash/4d640ad5aa95d1360f7c8c38e9c8b0d8.wasm:wasm-function[4146]:0x37594f)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h92808941d97e9b21 (https://megami.starcreator.com/nanaca-crash/4d640ad5aa95d1360f7c8c38e9c8b0d8.wasm:wasm-function[4985]:0x387ab4)
    at rust_begin_unwind (https://megami.starcreator.com/nanaca-crash/4d640ad5aa95d1360f7c8c38e9c8b0d8.wasm:wasm-function[4870]:0x3863b1)
    at core::panicking::panic_fmt::hbd8a975261a5f466 (https://megami.starcreator.com/nanaca-crash/4d640ad5aa95d1360f7c8c38e9c8b0d8.wasm:wasm-function[4986]:0x387aea)
    at core::option::expect_none_failed::hbea1e2e5b59d80cc (https://megami.starcreator.com/nanaca-crash/4d640ad5aa95d1360f7c8c38e9c8b0d8.wasm:wasm-function[4244]:0x378a28)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: nanaca-crash_v110.swf
Param movie: nanaca-crash_v110.swf
Attribute 0: undefined
Attribute 1: undefined

# Page Info
Page URL: https://megami.starcreator.com/nanaca-crash/
SWF URL: https://megami.starcreator.com/nanaca-crash/nanaca-crash_v110.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-02-14
Channel: nightly
Built: 2021-02-14T00:19:03.523Z
Commit: ecd873eb39c141f9bf2e41454c7a47d5f7e9507c

**Comment by adrian17** [comment]
Better error stack:

```
Error message: panicked at 'already borrowed: BorrowMutError', core/src/avm1/object/stage_object.rs:92:14
Error stack:

core::option::expect_none_failed
<ruffle_core::display_object::edit_text::EditText as ruffle_core::display_object::TDisplayObject>::unload
<ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::unload
<ruffle_core::display_object::button::Button as ruffle_core::display_object::container::TDisplayObjectContainer>::replace_at_depth
ruffle_core::display_object::button::Button::set_state
core::ops::function::FnOnce::call_once
ruffle_core::avm1::function::Executable::exec
ruffle_core::avm1::object::script_object::ScriptObject::internal_set
<ruffle_core::avm1::object::stage_object::StageObject as ruffle_core::avm1::object::TObject>::set
<ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::set
ruffle_core::avm1::activation::Activation::do_action
```

**Comment by adrian17** [comment]
Crash fixed by https://github.com/ruffle-rs/ruffle/pull/3322 .
