### ISSUE TITLE
Error on https://www.mostfungames.com/desktop-tower-defence.htm

### ISSUE THREAD

**Issue by Roeusvm** [ruffle-rs/ruffle#3256]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm1/globals/movie_clip.rs:955:10
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm1/globals/movie_clip.rs:955:10
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (<anonymous>:3:6695)
    at std::sync::once::Once::call_once::{{closure}}::hce6501f6f20767e4 (chrome-extension://kidjkckbdcojpdlkohagkdoeafakbppm/dist/4d640ad5aa95d1360f7c8c38e9c8b0d8.wasm:wasm-function[1327]:0x26ba91)
    at std::sync::once::Once::call_inner::hd3d269a4946f2df2 (chrome-extension://kidjkckbdcojpdlkohagkdoeafakbppm/dist/4d640ad5aa95d1360f7c8c38e9c8b0d8.wasm:wasm-function[1604]:0x29efac)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h6ed7686ed76cb258 (chrome-extension://kidjkckbdcojpdlkohagkdoeafakbppm/dist/4d640ad5aa95d1360f7c8c38e9c8b0d8.wasm:wasm-function[4639]:0x3823e3)
    at std::panicking::rust_panic_with_hook::h4f753dc70b771d8e (chrome-extension://kidjkckbdcojpdlkohagkdoeafakbppm/dist/4d640ad5aa95d1360f7c8c38e9c8b0d8.wasm:wasm-function[3509]:0x357cb7)
    at std::panicking::begin_panic_handler::{{closure}}::h5c9fc29957309ae8 (chrome-extension://kidjkckbdcojpdlkohagkdoeafakbppm/dist/4d640ad5aa95d1360f7c8c38e9c8b0d8.wasm:wasm-function[4146]:0x375928)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h92808941d97e9b21 (chrome-extension://kidjkckbdcojpdlkohagkdoeafakbppm/dist/4d640ad5aa95d1360f7c8c38e9c8b0d8.wasm:wasm-function[4985]:0x387ab4)
    at rust_begin_unwind (chrome-extension://kidjkckbdcojpdlkohagkdoeafakbppm/dist/4d640ad5aa95d1360f7c8c38e9c8b0d8.wasm:wasm-function[4870]:0x3863b1)
    at core::panicking::panic_fmt::hbd8a975261a5f466 (chrome-extension://kidjkckbdcojpdlkohagkdoeafakbppm/dist/4d640ad5aa95d1360f7c8c38e9c8b0d8.wasm:wasm-function[4986]:0x387aea)
    at core::panicking::panic::h8e74859c8f9988ca (chrome-extension://kidjkckbdcojpdlkohagkdoeafakbppm/dist/4d640ad5aa95d1360f7c8c38e9c8b0d8.wasm:wasm-function[4801]:0x3851fb)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.mostfungames.com/desktop-tower-defence.htm
SWF URL: https://www.mostfungames.com/wp-content/uploads/games/imported-games/desktoptowerdefense.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36 Edg/88.0.705.68
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-02-14
Channel: nightly
Built: 2021-02-14T00:19:03.523Z
Commit: ecd873eb39c141f9bf2e41454c7a47d5f7e9507c

**Comment by relrelb** [comment]
Fixed by #3454.
