### ISSUE TITLE
Error on https://funkypotato.com/rollercoaster-creator-2/

### ISSUE THREAD

**Issue by perelowski** [ruffle-rs/ruffle#3294]
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/gc-arena-0.2.0/src/gc_cell.rs:62:29
Error stack:
```
Error: panicked at 'already borrowed: BorrowMutError', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/gc-arena-0.2.0/src/gc_cell.rs:62:29
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (<anonymous>:3:6695)
    at std::sync::once::Once::call_once::{{closure}}::hce6501f6f20767e4 (chrome-extension://cfffheakccjmlhnfhpdbdnbhdaeokmhb/dist/90797cff9fcf5439a21889280011890d.wasm:wasm-function[1327]:0x26ba91)
    at std::sync::once::Once::call_inner::hd3d269a4946f2df2 (chrome-extension://cfffheakccjmlhnfhpdbdnbhdaeokmhb/dist/90797cff9fcf5439a21889280011890d.wasm:wasm-function[1604]:0x29efac)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h6ed7686ed76cb258 (chrome-extension://cfffheakccjmlhnfhpdbdnbhdaeokmhb/dist/90797cff9fcf5439a21889280011890d.wasm:wasm-function[4639]:0x382410)
    at std::panicking::rust_panic_with_hook::h4f753dc70b771d8e (chrome-extension://cfffheakccjmlhnfhpdbdnbhdaeokmhb/dist/90797cff9fcf5439a21889280011890d.wasm:wasm-function[3509]:0x357ce4)
    at std::panicking::begin_panic_handler::{{closure}}::h5c9fc29957309ae8 (chrome-extension://cfffheakccjmlhnfhpdbdnbhdaeokmhb/dist/90797cff9fcf5439a21889280011890d.wasm:wasm-function[4146]:0x37597c)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h92808941d97e9b21 (chrome-extension://cfffheakccjmlhnfhpdbdnbhdaeokmhb/dist/90797cff9fcf5439a21889280011890d.wasm:wasm-function[4985]:0x387ae1)
    at rust_begin_unwind (chrome-extension://cfffheakccjmlhnfhpdbdnbhdaeokmhb/dist/90797cff9fcf5439a21889280011890d.wasm:wasm-function[4870]:0x3863de)
    at core::panicking::panic_fmt::hbd8a975261a5f466 (chrome-extension://cfffheakccjmlhnfhpdbdnbhdaeokmhb/dist/90797cff9fcf5439a21889280011890d.wasm:wasm-function[4986]:0x387b17)
    at core::option::expect_none_failed::hbea1e2e5b59d80cc (chrome-extension://cfffheakccjmlhnfhpdbdnbhdaeokmhb/dist/90797cff9fcf5439a21889280011890d.wasm:wasm-function[4244]:0x378a55)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: /gamez/rollercoaster-creator-2.swf
Param movie: /gamez/rollercoaster-creator-2.swf
Param quality: best
Param bgcolor: #000000
Param wmode: direct
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined

# Page Info
Page URL: https://funkypotato.com/rollercoaster-creator-2/
SWF URL: https://funkypotato.com/gamez/rollercoaster-creator-2.swf

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_16_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-02-16
Channel: nightly
Built: 2021-02-16T00:17:10.309Z
Commit: 85069f6ccf3fbbe88de6d40094aa9e9dba616e2a

**Comment by Lord-McSweeney** [comment]
This needs XML `children` and `child`.

**Comment by Lord-McSweeney** [comment]
Working fine now (game available at http://web.archive.org/web/20150321103125/https://funkypotato.com/gamez/rollercoaster-creator-2.swf)
