### ISSUE TITLE
Error on https://ruffle.rs/demo/

### ISSUE THREAD

**Issue by plastictown** [ruffle-rs/ruffle#3298]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm1/globals/movie_clip.rs:955:10
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm1/globals/movie_clip.rs:955:10
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://ruffle.rs/demo/index.js:1:17560)
    at std::sync::once::Once::call_once::{{closure}}::hce6501f6f20767e4 (https://ruffle.rs/demo/90797cff9fcf5439a21889280011890d.wasm:wasm-function[1327]:0x26ba91)
    at std::sync::once::Once::call_inner::hd3d269a4946f2df2 (https://ruffle.rs/demo/90797cff9fcf5439a21889280011890d.wasm:wasm-function[1604]:0x29efac)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h6ed7686ed76cb258 (https://ruffle.rs/demo/90797cff9fcf5439a21889280011890d.wasm:wasm-function[4639]:0x382410)
    at std::panicking::rust_panic_with_hook::h4f753dc70b771d8e (https://ruffle.rs/demo/90797cff9fcf5439a21889280011890d.wasm:wasm-function[3509]:0x357ce4)
    at std::panicking::begin_panic_handler::{{closure}}::h5c9fc29957309ae8 (https://ruffle.rs/demo/90797cff9fcf5439a21889280011890d.wasm:wasm-function[4146]:0x375955)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h92808941d97e9b21 (https://ruffle.rs/demo/90797cff9fcf5439a21889280011890d.wasm:wasm-function[4985]:0x387ae1)
    at rust_begin_unwind (https://ruffle.rs/demo/90797cff9fcf5439a21889280011890d.wasm:wasm-function[4870]:0x3863de)
    at core::panicking::panic_fmt::hbd8a975261a5f466 (https://ruffle.rs/demo/90797cff9fcf5439a21889280011890d.wasm:wasm-function[4986]:0x387b17)
    at core::panicking::panic::h8e74859c8f9988ca (https://ruffle.rs/demo/90797cff9fcf5439a21889280011890d.wasm:wasm-function[4801]:0x385228)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://ruffle.rs/demo/
SWF URL: https://ruffle.rs/demo/swfs/wasted_sky.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-02-16
Channel: nightly
Built: 2021-02-16T00:17:10.309Z
Commit: 85069f6ccf3fbbe88de6d40094aa9e9dba616e2a

**Comment by Poopooracoocoo** [comment]
What SWF were you trying to run? The error report doesn't say when you play your own SWF.

**Comment by plastictown** [comment]
[this file](https://disk.yandex.ru/d/SwyiWlUMBrblHA)
