### ISSUE TITLE
Error on http://oldgoanimate.herokuapp.com/character/browser?themeId=family

### ISSUE THREAD

**Issue by KaylaColeman** [ruffle-rs/ruffle#3341]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:490:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:490:50
    at r.wbg.__wbg_new_df6e6ab7a65c4c4d (<anonymous>:3:11028)
    at std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f (wasm-function[1265]:169)
    at std::sync::once::Once::call_inner::h02eac160d339afc2 (wasm-function[1528]:675)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801 (wasm-function[4309]:67)
    at std::panicking::rust_panic_with_hook::h123718ba3bf480af (wasm-function[3299]:224)
    at std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2 (wasm-function[3916]:159)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925 (wasm-function[4655]:40)
    at rust_begin_unwind (wasm-function[4526]:89)
    at core::panicking::panic_fmt::h285dc015a87be5a4 (wasm-function[4657]:48)
    at core::option::expect_none_failed::hb95d2b1dc5448c17 (wasm-function[3996]:123)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: https://josephcrosmanplays532.github.io/GoAnimate-Assets/animation/414827163ad4eb60/cc_browser.swf
Param flashvars: apiserver=%2F&storePath=https%3A%2F%2Fjosephcrosmanplays532.github.io%2FGoAnimate-Assets%2Fstore%2F3a981f5cb2739137%2F%3Cstore%3E&clientThemePath=https%3A%2F%2Fjosephcrosmanplays532.github.io%2FGoAnimate-Assets%2Fstatic%2Fad44370a650793d9%2F%3Cclient_theme%3E&themeId=family&ut=60&appCode=go&page=&siteId=go&m_mode=school&isLogin=Y&isEmbed=1&ctc=go&tlang=en_US&lid=13
Param allowScriptAccess: always
Param movie: https://josephcrosmanplays532.github.io/GoAnimate-Assets/animation/414827163ad4eb60/cc_browser.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: http://oldgoanimate.herokuapp.com/character/browser?themeId=family
SWF URL: https://josephcrosmanplays532.github.io/GoAnimate-Assets/animation/414827163ad4eb60/cc_browser.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-25
Channel: nightly
Built: 2021-01-25T01:05:41.178Z
Commit: 32fd3fb71befbceecbba7c73d08af5ddd0f5a3d0

**Comment by Poopooracoocoo** [comment]
This SWF is written in ActionScript 3, the newer language for SWFs made after 2006. Ruffle does not yet support it and it may take several months.

You're also running an older version of Chrome that may not support WebAssembly properly. WebAssembly is a relatively new web technology that Ruffle uses. You could consider using another Chromium based browser or Firefox if you don't wish to update Chrome. 

You may not have seen the ActionScript 3 warning with your version of the Ruffle extension.

On the latest version of Chrome and Ruffle, I can see the AS3 warning and when I clicked on Run anyway, I saw a white screen.
