### ISSUE TITLE
Error on https://www.forum-thueringen.de/ufp_start.php?do=playgame&gameid=178

### ISSUE THREAD

**Issue by buh1m** [ruffle-rs/ruffle#3352]
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', core/src/avm1/object/stage_object.rs:102:14

# Player Info
Allows script access: true

# Page Info
Page URL: https://www.forum-thueringen.de/ufp_start.php?do=playgame&gameid=178
SWF URL: https://www.forum-thueringen.de/games/1starshipDR.swf?location=http://www.forum-thueringen.de&gameid=178&sid=&PHPSESSID=5&goldid=mrsarcade

# Browser Info
Useragent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:85.0) Gecko/20100101 Firefox/85.0
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-02-19
Channel: nightly
Built: 2021-02-19T00:17:04.316Z
Commit: 75fca8f6b6ae38303de294051bd560b20c183258

**Comment by buh1m** [comment]
> # Error Info
> 
> Error name: Error
> Error message: panicked at 'already borrowed: BorrowMutError', core/src/avm1/object/stage_object.rs:102:14
> # Player Info
> 
> Allows script access: true
> # Page Info
> 
> Page URL: https://www.forum-thueringen.de/ufp_start.php?do=playgame&gameid=178
> # Browser Info
> 
> Useragent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:85.0) Gecko/20100101 Firefox/85.0
> OS: Linux x86_64
> # Ruffle Info
> 
> Version: 0.1.0
> Name: nightly 2021-02-19
> Channel: nightly
> Built: 2021-02-19T00:17:04.316Z
> Commit: [75fca8f](https://github.com/ruffle-rs/ruffle/commit/75fca8f6b6ae38303de294051bd560b20c183258)

**Comment by relrelb** [comment]
Probably fixed by #3322?
