### ISSUE TITLE
Error on https://gamesfuckgirls.com/game.php?i=988

### ISSUE THREAD

**Issue by Arf3ds** [ruffle-rs/ruffle#3361]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: JsValue(TypeError: Failed to fetch
TypeError: Failed to fetch)', web/src/navigator.rs:162:18
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: JsValue(TypeError: Failed to fetch
TypeError: Failed to fetch)', web/src/navigator.rs:162:18
    at Object.Q (https://gamesfuckgirls.com/ruffle/11-01-2021/core.ruffle.3be12cf6e13daeeedf58.js:1:21164)
    at __wbg_new_df6e6ab7a65c4c4d (https://gamesfuckgirls.com/ruffle/11-01-2021/ruffle.js:1:38981)
    at std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f (https://gamesfuckgirls.com/ruffle/11-01-2021/bbc3b10d6b9019cdac0b.module.wasm:wasm-function[1279]:0x25eedb)
    at std::sync::once::Once::call_inner::h02eac160d339afc2 (https://gamesfuckgirls.com/ruffle/11-01-2021/bbc3b10d6b9019cdac0b.module.wasm:wasm-function[1537]:0x28eac1)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801 (https://gamesfuckgirls.com/ruffle/11-01-2021/bbc3b10d6b9019cdac0b.module.wasm:wasm-function[4274]:0x361c64)
    at std::panicking::rust_panic_with_hook::h123718ba3bf480af (https://gamesfuckgirls.com/ruffle/11-01-2021/bbc3b10d6b9019cdac0b.module.wasm:wasm-function[3304]:0x33c6a5)
    at std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2 (https://gamesfuckgirls.com/ruffle/11-01-2021/bbc3b10d6b9019cdac0b.module.wasm:wasm-function[3885]:0x357ce6)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925 (https://gamesfuckgirls.com/ruffle/11-01-2021/bbc3b10d6b9019cdac0b.module.wasm:wasm-function[4618]:0x36733c)
    at rust_begin_unwind (https://gamesfuckgirls.com/ruffle/11-01-2021/bbc3b10d6b9019cdac0b.module.wasm:wasm-function[4492]:0x3659ab)
    at core::panicking::panic_fmt::h285dc015a87be5a4 (https://gamesfuckgirls.com/ruffle/11-01-2021/bbc3b10d6b9019cdac0b.module.wasm:wasm-function[4620]:0x3673a0)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: game/swf/988.swf
Param movie: game/swf/988.swf
Param quality: high
Param play: true
Param loop: true
Param wmode: window
Param scale: showall
Param allowFullScreen: true
Param menu: true
Param devicefont: false
Param allowScriptAccess: always
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://gamesfuckgirls.com/game.php?i=988
SWF URL: https://gamesfuckgirls.com/game/swf/988.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-11
Channel: nightly
Built: 2021-01-11T00:53:04.486Z
Commit: cce3a8199d48ecbce536a0e49efd501d97a2b370

**Comment by rufflue** [comment]
@Herschel can you add the NSFW tag on this issue

**Comment by kjarosh** [comment]
Should be fixed as of the newest version
