### ISSUE TITLE
Error on https://pedantic-torvalds-a7ae6f.netlify.app/7750/index.html

### ISSUE THREAD

**Issue by gorbypark** [ruffle-rs/ruffle#3365]
# Error Info
Error name: Error
Error message: panicked at 'index out of bounds: the len is 15 but the index is 4294967295', render/webgl/src/lib.rs:541:37
Error stack:
```
Error: panicked at 'index out of bounds: the len is 15 but the index is 4294967295', render/webgl/src/lib.rs:541:37
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://pedantic-torvalds-a7ae6f.netlify.app/js/ruffle.js:1:6553)
    at std::sync::once::Once::call_once::{{closure}}::hce6501f6f20767e4 (https://pedantic-torvalds-a7ae6f.netlify.app/js/bf4d4f25e545c29722d2ab3143ad22e4.wasm:wasm-function[1356]:0x27acb7)
    at std::sync::once::Once::call_inner::hd3d269a4946f2df2 (https://pedantic-torvalds-a7ae6f.netlify.app/js/bf4d4f25e545c29722d2ab3143ad22e4.wasm:wasm-function[1636]:0x2af21f)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h6ed7686ed76cb258 (https://pedantic-torvalds-a7ae6f.netlify.app/js/bf4d4f25e545c29722d2ab3143ad22e4.wasm:wasm-function[4833]:0x3a4f55)
    at std::panicking::rust_panic_with_hook::h4f753dc70b771d8e (https://pedantic-torvalds-a7ae6f.netlify.app/js/bf4d4f25e545c29722d2ab3143ad22e4.wasm:wasm-function[3691]:0x379777)
    at std::panicking::begin_panic_handler::{{closure}}::h5c9fc29957309ae8 (https://pedantic-torvalds-a7ae6f.netlify.app/js/bf4d4f25e545c29722d2ab3143ad22e4.wasm:wasm-function[4349]:0x3986e8)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h92808941d97e9b21 (https://pedantic-torvalds-a7ae6f.netlify.app/js/bf4d4f25e545c29722d2ab3143ad22e4.wasm:wasm-function[5189]:0x3aa8a4)
    at rust_begin_unwind (https://pedantic-torvalds-a7ae6f.netlify.app/js/bf4d4f25e545c29722d2ab3143ad22e4.wasm:wasm-function[5068]:0x3a9057)
    at core::panicking::panic_fmt::hbd8a975261a5f466 (https://pedantic-torvalds-a7ae6f.netlify.app/js/bf4d4f25e545c29722d2ab3143ad22e4.wasm:wasm-function[5190]:0x3aa8da)
    at core::panicking::panic_bounds_check::h81a63bf79280172d (https://pedantic-torvalds-a7ae6f.netlify.app/js/bf4d4f25e545c29722d2ab3143ad22e4.wasm:wasm-function[4570]:0x39eec0)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://pedantic-torvalds-a7ae6f.netlify.app/7750/index.html
SWF URL: https://pedantic-torvalds-a7ae6f.netlify.app/7750/7750.swf

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-02-21
Channel: nightly
Built: 2021-02-21T00:20:18.629Z
Commit: eb173f06ca0918e2d2b488cd14849152db607e51

**Comment by adrian17** [comment]
Looks like the SWF is technically invalid: according to spec, `GRADIENT` should have between 1 and 15 gradient colors, but Shape ID 296 has a linear gradient with 0 colors.
That said, if JPEXS and Flash Player accept them, that means we need to handle this edge case too...
