### ISSUE TITLE
Error on https://10.1.0.91:1158/em/console/database/instance/sitemap

### ISSUE THREAD

**Issue by GaryChuang-CKP** [ruffle-rs/ruffle#3425]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:490:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:490:50
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (<anonymous>:3:6449)
    at std::sync::once::Once::call_once::{{closure}}::hce6501f6f20767e4 (chrome-extension://gadpmmhbdnicgpcofbabgpfpbmfigdop/dist/bf4d4f25e545c29722d2ab3143ad22e4.wasm:wasm-function[1356]:0x27acb7)
    at std::sync::once::Once::call_inner::hd3d269a4946f2df2 (chrome-extension://gadpmmhbdnicgpcofbabgpfpbmfigdop/dist/bf4d4f25e545c29722d2ab3143ad22e4.wasm:wasm-function[1636]:0x2af21f)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h6ed7686ed76cb258 (chrome-extension://gadpmmhbdnicgpcofbabgpfpbmfigdop/dist/bf4d4f25e545c29722d2ab3143ad22e4.wasm:wasm-function[4833]:0x3a4f55)
    at std::panicking::rust_panic_with_hook::h4f753dc70b771d8e (chrome-extension://gadpmmhbdnicgpcofbabgpfpbmfigdop/dist/bf4d4f25e545c29722d2ab3143ad22e4.wasm:wasm-function[3691]:0x379777)
    at std::panicking::begin_panic_handler::{{closure}}::h5c9fc29957309ae8 (chrome-extension://gadpmmhbdnicgpcofbabgpfpbmfigdop/dist/bf4d4f25e545c29722d2ab3143ad22e4.wasm:wasm-function[4349]:0x3986e8)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h92808941d97e9b21 (chrome-extension://gadpmmhbdnicgpcofbabgpfpbmfigdop/dist/bf4d4f25e545c29722d2ab3143ad22e4.wasm:wasm-function[5189]:0x3aa8a4)
    at rust_begin_unwind (chrome-extension://gadpmmhbdnicgpcofbabgpfpbmfigdop/dist/bf4d4f25e545c29722d2ab3143ad22e4.wasm:wasm-function[5068]:0x3a9057)
    at core::panicking::panic_fmt::hbd8a975261a5f466 (chrome-extension://gadpmmhbdnicgpcofbabgpfpbmfigdop/dist/bf4d4f25e545c29722d2ab3143ad22e4.wasm:wasm-function[5190]:0x3aa8da)
    at core::option::expect_none_failed::hbea1e2e5b59d80cc (chrome-extension://gadpmmhbdnicgpcofbabgpfpbmfigdop/dist/bf4d4f25e545c29722d2ab3143ad22e4.wasm:wasm-function[4448]:0x39b8b8)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://10.1.0.91:1158/em/console/database/instance/sitemap?event=doLoad&target=JDEDB&type=oracle_database&pageNum=2
SWF URL: https://10.1.0.91:1158/em/database/flex/perf112.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-02-21
Channel: nightly
Built: 2021-02-21T00:20:18.629Z
Commit: eb173f06ca0918e2d2b488cd14849152db607e51

**Comment by Poopooracoocoo** [comment]
got any more information? you're running that on localhost.

**Comment by GaryChuang-CKP** [comment]
> got any more information? you're running that on localhost.

Sorry ~~~ This is the Web Site of Oracle Enterprise Manager. 
I can't put this on internet. so ...
What's Information I can get for you ?
