### ISSUE TITLE
Error on https://www.jeu-fille.net/my-new-room-3-1300.html

### ISSUE THREAD

**Issue by 26042004** [ruffle-rs/ruffle#3429]
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/gc-arena-0.2.0/src/gc_cell.rs:62:29
Error stack:
```
Error: panicked at 'already borrowed: BorrowMutError', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/gc-arena-0.2.0/src/gc_cell.rs:62:29
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (eval at <anonymous> (https://www.jeu-fille.net/js/jquery/jquery.js?2:2:4904), <anonymous>:1:6343)
    at std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f (https://www.jeu-fille.net/data/ruffle/90d03b7718fde93d787334ae45f283f3.wasm:wasm-function[1277]:0x2570ef)
    at std::sync::once::Once::call_inner::h02eac160d339afc2 (https://www.jeu-fille.net/data/ruffle/90d03b7718fde93d787334ae45f283f3.wasm:wasm-function[1536]:0x28688a)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801 (https://www.jeu-fille.net/data/ruffle/90d03b7718fde93d787334ae45f283f3.wasm:wasm-function[4372]:0x35d891)
    at std::panicking::rust_panic_with_hook::h123718ba3bf480af (https://www.jeu-fille.net/data/ruffle/90d03b7718fde93d787334ae45f283f3.wasm:wasm-function[3313]:0x335027)
    at std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2 (https://www.jeu-fille.net/data/ruffle/90d03b7718fde93d787334ae45f283f3.wasm:wasm-function[3929]:0x352215)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925 (https://www.jeu-fille.net/data/ruffle/90d03b7718fde93d787334ae45f283f3.wasm:wasm-function[4705]:0x362bff)
    at rust_begin_unwind (https://www.jeu-fille.net/data/ruffle/90d03b7718fde93d787334ae45f283f3.wasm:wasm-function[4584]:0x3613d1)
    at core::panicking::panic_fmt::h285dc015a87be5a4 (https://www.jeu-fille.net/data/ruffle/90d03b7718fde93d787334ae45f283f3.wasm:wasm-function[4707]:0x362c63)
    at core::option::expect_none_failed::hb95d2b1dc5448c17 (https://www.jeu-fille.net/data/ruffle/90d03b7718fde93d787334ae45f283f3.wasm:wasm-function[4013]:0x354c68)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://www.jeu-fille.net/my-new-room-3-1300.html
SWF URL: https://www.jeu-fille.net/data/1300.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-30
Channel: nightly
Built: 2021-01-30T00:35:10.218Z
Commit: 02dfb23c6738bc5a576113b3f1794127bc7ae84e

**Comment by Lord-McSweeney** [comment]
Closing as the site was using a version of Ruffle that is now 4 years outdated
