### ISSUE TITLE
Error on https://files.twoplayergames.org/files/games/ruffle/player.html?file=o4/Naruto_vs_One_Piece_2_0.swf

### ISSUE THREAD

**Issue by saldua123** [ruffle-rs/ruffle#3445]
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', web/src/lib.rs:836:49
Error stack:
```
Error: panicked at 'already borrowed: BorrowMutError', web/src/lib.rs:836:49
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://files.twoplayergames.org/files/games/ruffle/ruffle.js:1:6349)
    at std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f (wasm-function[1267]:169)
    at std::sync::once::Once::call_inner::h02eac160d339afc2 (wasm-function[1528]:675)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801 (wasm-function[4308]:67)
    at std::panicking::rust_panic_with_hook::h123718ba3bf480af (wasm-function[3299]:224)
    at std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2 (wasm-function[3916]:159)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925 (wasm-function[4654]:40)
    at rust_begin_unwind (wasm-function[4525]:89)
    at core::panicking::panic_fmt::h285dc015a87be5a4 (wasm-function[4656]:48)
    at core::option::expect_none_failed::hb95d2b1dc5448c17 (wasm-function[3995]:123)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://files.twoplayergames.org/files/games/ruffle/player.html?file=o4/Naruto_vs_One_Piece_2_0.swf
SWF URL: https://files.twoplayergames.org/files/games/o4/Naruto_vs_One_Piece_2_0.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-26
Channel: nightly
Built: 2021-01-26T00:36:48.131Z
Commit: 7856cdd3d770e406ce546bf1745d8046d7b716f8

**Comment by Poopooracoocoo** [comment]
Woah, that's an old version of Chrome! If you don't want to update Chrome, use Firefox or a Chromium based browser that supports the WebAssembly web technologies that Ruffle uses. 

That SWF uses ActionScript 3, the newer language for SWFs that Ruffle does not yet support. Ruffle started with AS1 and AS2 support and is still under development. Support may take several months. 

Mind closing this issue in favour of #1368?
