### ISSUE TITLE
Ruffle Error on https://www.eftelingfanzine.com/efteling-simulaties/halve-maen/

### ISSUE THREAD

**Issue by achilj** [ruffle-rs/ruffle#3456]
# Error Info
Error name: ChunkLoadError
Error message: Loading chunk 662 failed.
(error: https://www.eftelingfanzine.com/wp-content/cache/autoptimize/js/core.ruffle.0296c9616faebbfc4898.js)
Error stack:
```
ChunkLoadError: Loading chunk 662 failed.
(error: https://www.eftelingfanzine.com/wp-content/cache/autoptimize/js/core.ruffle.0296c9616faebbfc4898.js)
    at Object.vi.f.j (https://www.eftelingfanzine.com/wp-content/cache/autoptimize/js/autoptimize_13c8d8ec0da404183bc8a60b3f52b8a3.js:3:36903)
    at https://www.eftelingfanzine.com/wp-content/cache/autoptimize/js/autoptimize_13c8d8ec0da404183bc8a60b3f52b8a3.js:3:35299
    at Array.reduce (<anonymous>)
    at Function.vi.e (https://www.eftelingfanzine.com/wp-content/cache/autoptimize/js/autoptimize_13c8d8ec0da404183bc8a60b3f52b8a3.js:3:35276)
    at o (https://www.eftelingfanzine.com/wp-content/cache/autoptimize/js/autoptimize_13c8d8ec0da404183bc8a60b3f52b8a3.js:3:2595)
    at o.next (<anonymous>)
    at https://www.eftelingfanzine.com/wp-content/cache/autoptimize/js/autoptimize_13c8d8ec0da404183bc8a60b3f52b8a3.js:3:2895
    at new Promise (<anonymous>)
    at https://www.eftelingfanzine.com/wp-content/cache/autoptimize/js/autoptimize_13c8d8ec0da404183bc8a60b3f52b8a3.js:3:2631
    at o (https://www.eftelingfanzine.com/wp-content/cache/autoptimize/js/autoptimize_13c8d8ec0da404183bc8a60b3f52b8a3.js:3:2918)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.eftelingfanzine.com/efteling-simulaties/halve-maen/

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-01
Channel: nightly
Built: 2021-01-01T00:47:35.621Z
Commit: 8cdf04384c79c60e066c945566128b7e7ee2620b

**Comment by EmperorBale** [comment]
This issue was caused by the wordpress plugin "autooptimize", I don't think there is anything Ruffle can do to fix this

**Comment by Lord-McSweeney** [comment]
Not an issue with Ruffle, and the site was using a version that is now 4 years outdated
