### ISSUE TITLE
Error on https://ruffle.rs/demo/

### ISSUE THREAD

**Issue by Baydock** [ruffle-rs/ruffle#3457]
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', web/src/lib.rs:641:42
Error stack:
```
Error: panicked at 'already borrowed: BorrowMutError', web/src/lib.rs:641:42
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://ruffle.rs/demo/index.js:1:17366)
    at std::sync::once::Once::call_once::{{closure}}::hce6501f6f20767e4 (https://ruffle.rs/demo/5cf6745297fb4a9d7eff6801084361aa.wasm:wasm-function[1355]:0x27a9f3)
    at std::sync::once::Once::call_inner::hd3d269a4946f2df2 (https://ruffle.rs/demo/5cf6745297fb4a9d7eff6801084361aa.wasm:wasm-function[1636]:0x2af37a)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h6ed7686ed76cb258 (https://ruffle.rs/demo/5cf6745297fb4a9d7eff6801084361aa.wasm:wasm-function[4834]:0x3a52f0)
    at std::panicking::rust_panic_with_hook::h4f753dc70b771d8e (https://ruffle.rs/demo/5cf6745297fb4a9d7eff6801084361aa.wasm:wasm-function[3692]:0x379b0d)
    at std::panicking::begin_panic_handler::{{closure}}::h5c9fc29957309ae8 (https://ruffle.rs/demo/5cf6745297fb4a9d7eff6801084361aa.wasm:wasm-function[4350]:0x398a7e)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h92808941d97e9b21 (https://ruffle.rs/demo/5cf6745297fb4a9d7eff6801084361aa.wasm:wasm-function[5190]:0x3aac3f)
    at rust_begin_unwind (https://ruffle.rs/demo/5cf6745297fb4a9d7eff6801084361aa.wasm:wasm-function[5069]:0x3a93f2)
    at core::panicking::panic_fmt::hbd8a975261a5f466 (https://ruffle.rs/demo/5cf6745297fb4a9d7eff6801084361aa.wasm:wasm-function[5191]:0x3aac75)
    at core::option::expect_none_failed::hbea1e2e5b59d80cc (https://ruffle.rs/demo/5cf6745297fb4a9d7eff6801084361aa.wasm:wasm-function[4449]:0x39bc4e)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://ruffle.rs/demo/

# Browser Info
Useragent: Mozilla/5.0 (Linux; Android 11; KB2005) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.181 Mobile Safari/537.36
OS: Linux armv8l

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-02-27
Channel: nightly
Built: 2021-02-27T00:17:48.863Z
Commit: 8500a676cfb694dc46fd258c0802c3dee4d61f66

**Comment by Poopooracoocoo** [comment]
What SWF were you trying to play? You can upload SWFs in zip files to GitHub.

**Comment by Baydock** [comment]
I am trying to play submachine 10. It is the paid version so I am not sure of I can upload it in good conscience. From my testing, it can be run in the demo when on computer but not on mobile which is where this error is from. My guess would be the file size since it is 30 MB, which is much bigger than all of the previous games, which all work.

**Comment by DependentAppearance0** [comment]
At least currently the free version of this game appears to run on [this website](https://www.y8.com/games/submachine_10_the_exit).

The game doesn't however seem to function quite propertly since it appears like there is some kind of a red filter over the whole game.
![kuva](https://user-images.githubusercontent.com/68330228/120105352-3b8cbe00-c161-11eb-85de-5ccdaa6ca503.png)

As far as I'm able to tell the image above should look something like this
![kuva](https://user-images.githubusercontent.com/68330228/120105404-64ad4e80-c161-11eb-9660-f50351cb0c0e.png)

also some glow effects seem to be missing right at the start

**Comment by Poopooracoocoo** [comment]
@Baydock Do you still see the error on your phone by the way?

**Comment by Lord-McSweeney** [comment]
Closing as the site was using a version of Ruffle that is now 4 years outdated
