### ISSUE TITLE
Error on https://armorgames.com/play/3099/stormwinds-the-lost-campaigns

### ISSUE THREAD

**Issue by LannieLona** [ruffle-rs/ruffle#3527]
# Error Info
Error name: Error
Error message: panicked at 'index out of bounds: the len is 0 but the index is 4294967295', core/src/avm1/object/script_object.rs:807:17
Error stack:
```
Error: panicked at 'index out of bounds: the len is 0 but the index is 4294967295', core/src/avm1/object/script_object.rs:807:17
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://agi.armorgames.com/ruffle/ruffle.js:1:6392)
    at std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f (https://agi.armorgames.com/ruffle/05be98acabee5bdacb848b714e072d80.wasm:wasm-function[1276]:0x25acf1)
    at std::sync::once::Once::call_inner::h02eac160d339afc2 (https://agi.armorgames.com/ruffle/05be98acabee5bdacb848b714e072d80.wasm:wasm-function[1533]:0x289f4e)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801 (https://agi.armorgames.com/ruffle/05be98acabee5bdacb848b714e072d80.wasm:wasm-function[4371]:0x36167b)
    at std::panicking::rust_panic_with_hook::h123718ba3bf480af (https://agi.armorgames.com/ruffle/05be98acabee5bdacb848b714e072d80.wasm:wasm-function[3312]:0x338d3c)
    at std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2 (https://agi.armorgames.com/ruffle/05be98acabee5bdacb848b714e072d80.wasm:wasm-function[3929]:0x356034)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925 (https://agi.armorgames.com/ruffle/05be98acabee5bdacb848b714e072d80.wasm:wasm-function[4705]:0x3669fe)
    at rust_begin_unwind (https://agi.armorgames.com/ruffle/05be98acabee5bdacb848b714e072d80.wasm:wasm-function[4583]:0x3651a1)
    at core::panicking::panic_fmt::h285dc015a87be5a4 (https://agi.armorgames.com/ruffle/05be98acabee5bdacb848b714e072d80.wasm:wasm-function[4707]:0x366a62)
    at core::panicking::panic_bounds_check::heedacfd10d9ec31d (https://agi.armorgames.com/ruffle/05be98acabee5bdacb848b714e072d80.wasm:wasm-function[4114]:0x35b779)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://armorgames.com/play/3099/stormwinds-the-lost-campaigns
SWF URL: https://cache.armorgames.com/files/games/stormwinds-the-lost--3099.swf?v=1373587521

# Browser Info
Useragent: Mozilla/5.0 (X11; CrOS x86_64 13597.66.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.109 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-02-01
Channel: nightly
Built: 2021-02-01T00:36:59.488Z
Commit: d1fb36fbe2b31b9392d995ac67315aa02aee3fbc

**Comment by LannieLona** [comment]
This error happens when I click New Game or Load Game, it won't let me past that stage.

**Comment by adrian17** [comment]
AFAIK this should be fixed in newer versions of Ruffle.
