### ISSUE TITLE
Error on https://kdata1.com/2016/11/anime-legends-25/

### ISSUE THREAD

**Issue by Anyucpouakot64** [ruffle-rs/ruffle#3564]
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', web/src/lib.rs:836:49
Error stack:
```
Error: panicked at 'already borrowed: BorrowMutError', web/src/lib.rs:836:49
    at r.wbg.__wbg_new_df6e6ab7a65c4c4d (<anonymous>:3:11028)
    at wasm-function[1265]:169
    at wasm-function[1528]:675
    at wasm-function[4309]:67
    at wasm-function[3299]:224
    at wasm-function[3916]:159
    at wasm-function[4655]:40
    at wasm-function[4526]:89
    at wasm-function[4657]:48
    at wasm-function[3996]:123
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: loader.swf
Param movie: loader.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined

# Page Info
Page URL: https://kdata1.com/2016/11/anime-legends-25/
SWF URL: https://kdata1.com/2016/11/anime-legends-25/loader.swf

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-25
Channel: nightly
Built: 2021-01-25T01:05:41.178Z
Commit: 32fd3fb71befbceecbba7c73d08af5ddd0f5a3d0

**Comment by Poopooracoocoo** [comment]
https://github.com/ruffle-rs/ruffle/issues/3565#issuecomment-792683407 

The SWF isn't AS3, but nothing appears on my side.

**Comment by Lord-McSweeney** [comment]
Closing as the site was using a version of Ruffle that is now 4 years outdated
