### ISSUE TITLE
Error on http://v.apelearn.com/student.php

### ISSUE THREAD

**Issue by Vantone** [ruffle-rs/ruffle#3569]
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', web/src/lib.rs:847:49
Error stack:
```
Error: panicked at 'already borrowed: BorrowMutError', web/src/lib.rs:847:49
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (<anonymous>:3:6449)
    at std::sync::once::Once::call_once::{{closure}}::hce6501f6f20767e4 (<WASM>[1460]+169)
    at std::sync::once::Once::call_inner::hd3d269a4946f2df2 (<WASM>[1731]+675)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h6ed7686ed76cb258 (<WASM>[5188]+67)
    at std::panicking::rust_panic_with_hook::h4f753dc70b771d8e (<WASM>[3948]+224)
    at std::panicking::begin_panic_handler::{{closure}}::h5c9fc29957309ae8 (<WASM>[4669]+159)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h92808941d97e9b21 (<WASM>[5560]+40)
    at rust_begin_unwind (<WASM>[5431]+89)
    at core::panicking::panic_fmt::hbd8a975261a5f466 (<WASM>[5561]+48)
    at core::option::expect_none_failed::hbea1e2e5b59d80cc (<WASM>[4783]+123)
```

# Player Info
Allows script access: true

# Page Info
Page URL: http://v.apelearn.com/student.php?view_unit=2592
SWF URL: http://player.polyv.net/videos/player.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-03-08
Channel: nightly
Built: 2021-03-08T00:16:43.196Z
Commit: 8f21c176831985f01986a952490cd09fe2ecafed

**Comment by Poopooracoocoo** [comment]
@Vantone Woah! That's a really old version of Chrome! Chrome started to add support for the modern web technologies such as WebAssembly that Ruffle uses in version 70 and onwards. Please consider updating Chrome or using a different, up to date, browser.

Note that you may still run into a crash with Ruffle. Create a new issue if it does!

**Comment by Poopooracoocoo** [comment]
@Vantone Have you tried using a newer version of Chrome?
