### ISSUE TITLE
Error on https://mysexgames.com/games/1318/crimson_keep_episode_3_lumen_city

### ISSUE THREAD

**Issue by wdsj123456** [ruffle-rs/ruffle#3585]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: JsValue(TypeError: Failed to fetch
TypeError: Failed to fetch)', web/src/navigator.rs:201:18
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: JsValue(TypeError: Failed to fetch
TypeError: Failed to fetch)', web/src/navigator.rs:201:18
    at Object.U (https://mysexgames.com/ruffle/core.ruffle.ab9406d542303de5ee9b.js:1:21277)
    at __wbg_new_df6e6ab7a65c4c4d (https://mysexgames.com/ruffle/ruffle.js:1:38987)
    at std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f (wasm-function[1288]:0x2636a1)
    at std::sync::once::Once::call_inner::h02eac160d339afc2 (wasm-function[1539]:0x291d92)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801 (wasm-function[4281]:0x3658db)
    at std::panicking::rust_panic_with_hook::h123718ba3bf480af (wasm-function[3312]:0x34053c)
    at std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2 (wasm-function[3889]:0x35b821)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925 (wasm-function[4627]:0x36b02f)
    at rust_begin_unwind (wasm-function[4500]:0x36966c)
    at core::panicking::panic_fmt::h285dc015a87be5a4 (wasm-function[4629]:0x36b093)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://mysexgames.com/games/1318/crimson_keep_episode_3_lumen_city
SWF URL: https://mysexgames.com/gamefiles/001318.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-12
Channel: nightly
Built: 2021-01-12T00:55:17.048Z
Commit: 73d123091014e190f4bc4d8edf98cab2e671cc3a

**Comment by wdsj123456** [comment]
3esdwders

**Comment by Poopooracoocoo** [comment]
That's an older version of Ruffle and an older version of Chrome. Could you try updating Chrome and then try playing the SWF on the Ruffle demo to use the latest version of Ruffle?
