### ISSUE TITLE
Error on https://ruffle.rs/demo/

### ISSUE THREAD

**Issue by clem39** [ruffle-rs/ruffle#3619]
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', core/src/avm2/object/function_object.rs:281:5
Error stack:
```
Error: panicked at 'already borrowed: BorrowMutError', core/src/avm2/object/function_object.rs:281:5
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://ruffle.rs/demo/index.js:1:16953)
    at std::sync::once::Once::call_once::{{closure}}::hce6501f6f20767e4 (https://ruffle.rs/demo/e48d67a029dc969004e2da7b91af2cc9.wasm:wasm-function[1470]:0x2bf954)
    at std::sync::once::Once::call_inner::hd3d269a4946f2df2 (https://ruffle.rs/demo/e48d67a029dc969004e2da7b91af2cc9.wasm:wasm-function[1736]:0x2f13e2)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h6ed7686ed76cb258 (https://ruffle.rs/demo/e48d67a029dc969004e2da7b91af2cc9.wasm:wasm-function[5191]:0x3f8636)
    at std::panicking::rust_panic_with_hook::h4f753dc70b771d8e (https://ruffle.rs/demo/e48d67a029dc969004e2da7b91af2cc9.wasm:wasm-function[3951]:0x3c91d7)
    at std::panicking::begin_panic_handler::{{closure}}::h5c9fc29957309ae8 (https://ruffle.rs/demo/e48d67a029dc969004e2da7b91af2cc9.wasm:wasm-function[4672]:0x3eaf5c)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h92808941d97e9b21 (https://ruffle.rs/demo/e48d67a029dc969004e2da7b91af2cc9.wasm:wasm-function[5563]:0x3fe36f)
    at rust_begin_unwind (https://ruffle.rs/demo/e48d67a029dc969004e2da7b91af2cc9.wasm:wasm-function[5434]:0x3fc97c)
    at core::panicking::panic_fmt::hbd8a975261a5f466 (https://ruffle.rs/demo/e48d67a029dc969004e2da7b91af2cc9.wasm:wasm-function[5564]:0x3fe3a5)
    at core::option::expect_none_failed::hbea1e2e5b59d80cc (https://ruffle.rs/demo/e48d67a029dc969004e2da7b91af2cc9.wasm:wasm-function[4786]:0x3ee7e6)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://ruffle.rs/demo/

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36 OPR/73.0.3856.415
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-03-12
Channel: nightly
Built: 2021-03-12T00:19:02.503Z
Commit: 2ca6d2bf6c263343a8da86debaf08780b22da881

**Comment by Poopooracoocoo** [comment]
@clem39 Which SWF file were you trying to play?

**Comment by Poopooracoocoo** [comment]
Closing due a lack of a response from reporter.
