### ISSUE TITLE
Error on http://www.educaplus.org/game/alcance-y-altura-maxima

### ISSUE THREAD

**Issue by ElvisClaros** [ruffle-rs/ruffle#3620]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:490:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:490:50
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (http://www.educaplus.org/ruffle/ruffle.js:1:6553)
    at std::sync::once::Once::call_once::{{closure}}::hce6501f6f20767e4 (http://www.educaplus.org/ruffle/d2d3bb6d5ecd32fa76e686100724cfbc.wasm:wasm-function[1359]:0x27a97a)
    at std::sync::once::Once::call_inner::hd3d269a4946f2df2 (http://www.educaplus.org/ruffle/d2d3bb6d5ecd32fa76e686100724cfbc.wasm:wasm-function[1637]:0x2ae95b)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h6ed7686ed76cb258 (http://www.educaplus.org/ruffle/d2d3bb6d5ecd32fa76e686100724cfbc.wasm:wasm-function[4837]:0x3a4c21)
    at std::panicking::rust_panic_with_hook::h4f753dc70b771d8e (http://www.educaplus.org/ruffle/d2d3bb6d5ecd32fa76e686100724cfbc.wasm:wasm-function[3694]:0x3793d9)
    at std::panicking::begin_panic_handler::{{closure}}::h5c9fc29957309ae8 (http://www.educaplus.org/ruffle/d2d3bb6d5ecd32fa76e686100724cfbc.wasm:wasm-function[4352]:0x39834a)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h92808941d97e9b21 (http://www.educaplus.org/ruffle/d2d3bb6d5ecd32fa76e686100724cfbc.wasm:wasm-function[5193]:0x3aa570)
    at rust_begin_unwind (http://www.educaplus.org/ruffle/d2d3bb6d5ecd32fa76e686100724cfbc.wasm:wasm-function[5072]:0x3a8d23)
    at core::panicking::panic_fmt::hbd8a975261a5f466 (http://www.educaplus.org/ruffle/d2d3bb6d5ecd32fa76e686100724cfbc.wasm:wasm-function[5194]:0x3aa5a6)
    at core::option::expect_none_failed::hbea1e2e5b59d80cc (http://www.educaplus.org/ruffle/d2d3bb6d5ecd32fa76e686100724cfbc.wasm:wasm-function[4451]:0x39b51a)
```

# Player Info
Allows script access: true

# Page Info
Page URL: http://www.educaplus.org/game/alcance-y-altura-maxima
SWF URL: http://www.educaplus.org/rf/tiro_vectores_ymax_xmax_pr.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-02-19
Channel: nightly
Built: 2021-02-19T00:17:04.316Z
Commit: 75fca8f6b6ae38303de294051bd560b20c183258

**Comment by relrelb** [comment]
Unfortunately this doesn't happen to me (same Chrome version on Windows 10). Is there any special way to reproduce the error?
Also, since I suspect this is related to hardware availability, can you please run the following in your browser console (open using F12, paste and press enter) and send the output:
```js
document.createElement("canvas").getContext("webgl").getSupportedExtensions();
document.createElement("canvas").getContext("webgl2").getSupportedExtensions();
```

**Comment by ElvisClaros** [comment]
`document.createElement("canvas").getContext("webgl").getSupportedExtensions();
(34) ["ANGLE_instanced_arrays", "EXT_blend_minmax", "EXT_color_buffer_half_float", "EXT_disjoint_timer_query", "EXT_float_blend", "EXT_frag_depth", "EXT_shader_texture_lod", "EXT_texture_compression_bptc", "EXT_texture_compression_rgtc", "EXT_texture_filter_anisotropic", "WEBKIT_EXT_texture_filter_anisotropic", "EXT_sRGB", "KHR_parallel_shader_compile", "OES_element_index_uint", "OES_fbo_render_mipmap", "OES_standard_derivatives", "OES_texture_float", "OES_texture_float_linear", "OES_texture_half_float", "OES_texture_half_float_linear", "OES_vertex_array_object", "WEBGL_color_buffer_float", "WEBGL_compressed_texture_etc1", "WEBGL_compressed_texture_s3tc", "WEBKIT_WEBGL_compressed_texture_s3tc", "WEBGL_compressed_texture_s3tc_srgb", "WEBGL_debug_renderer_info", "WEBGL_debug_shaders", "WEBGL_depth_texture", "WEBKIT_WEBGL_depth_texture", "WEBGL_draw_buffers", "WEBGL_lose_context", "WEBKIT_WEBGL_lose_context", "WEBGL_multi_draw"]
0: "ANGLE_instanced_arrays"
1: "EXT_blend_minmax"
2: "EXT_color_buffer_half_float"
3: "EXT_disjoint_timer_query"
4: "EXT_float_blend"
5: "EXT_frag_depth"
6: "EXT_shader_texture_lod"
7: "EXT_texture_compression_bptc"
8: "EXT_texture_compression_rgtc"
9: "EXT_texture_filter_anisotropic"
10: "WEBKIT_EXT_texture_filter_anisotropic"
11: "EXT_sRGB"
12: "KHR_parallel_shader_compile"
13: "OES_element_index_uint"
14: "OES_fbo_render_mipmap"
15: "OES_standard_derivatives"
16: "OES_texture_float"
17: "OES_texture_float_linear"
18: "OES_texture_half_float"
19: "OES_texture_half_float_linear"
20: "OES_vertex_array_object"
21: "WEBGL_color_buffer_float"
22: "WEBGL_compressed_texture_etc1"
23: "WEBGL_compressed_texture_s3tc"
24: "WEBKIT_WEBGL_compressed_texture_s3tc"
25: "WEBGL_compressed_texture_s3tc_srgb"
26: "WEBGL_debug_renderer_info"
27: "WEBGL_debug_shaders"
28: "WEBGL_depth_texture"
29: "WEBKIT_WEBGL_depth_texture"
30: "WEBGL_draw_buffers"
31: "WEBGL_lose_context"
32: "WEBKIT_WEBGL_lose_context"
33: "WEBGL_multi_draw"
length: 34
__proto__: Array(0)
document.createElement("canvas").getContext("webgl2").getSupportedExtensions();
(18) ["EXT_color_buffer_float", "EXT_color_buffer_half_float", "EXT_disjoint_timer_query_webgl2", "EXT_float_blend", "EXT_texture_compression_bptc", "EXT_texture_compression_rgtc", "EXT_texture_filter_anisotropic", "EXT_texture_norm16", "KHR_parallel_shader_compile", "OES_texture_float_linear", "WEBGL_compressed_texture_etc1", "WEBGL_compressed_texture_s3tc", "WEBGL_compressed_texture_s3tc_srgb", "WEBGL_debug_renderer_info", "WEBGL_debug_shaders", "WEBGL_lose_context", "WEBGL_multi_draw", "OVR_multiview2"]
0: "EXT_color_buffer_float"
1: "EXT_color_buffer_half_float"
2: "EXT_disjoint_timer_query_webgl2"
3: "EXT_float_blend"
4: "EXT_texture_compression_bptc"
5: "EXT_texture_compression_rgtc"
6: "EXT_texture_filter_anisotropic"
7: "EXT_texture_norm16"
8: "KHR_parallel_shader_compile"
9: "OES_texture_float_linear"
10: "WEBGL_compressed_texture_etc1"
11: "WEBGL_compressed_texture_s3tc"
12: "WEBGL_compressed_texture_s3tc_srgb"
13: "WEBGL_debug_renderer_info"
14: "WEBGL_debug_shaders"
15: "WEBGL_lose_context"
16: "WEBGL_multi_draw"
17: "OVR_multiview2"
length: 18
__proto__: Array(0)`

**Comment by relrelb** [comment]
Thanks, this looks okay.

Can you please run the following:
```js
var canvas = document.createElement("canvas");
var gl = canvas.getContext("webgl2");
var vao = gl.createVertexArray();
gl.bindVertexArray(vao);
```
Does it throw an error?

**Comment by ElvisClaros** [comment]
I have to  run in the browser console?
![13-03-2021-12-54-21_528x340_escrotum](https://user-images.githubusercontent.com/19779840/111036306-5b7fd180-83fd-11eb-9af7-e9bf1c234289.png)

**Comment by relrelb** [comment]
Hmmm... This looks okay as well... Are you sure this runs on the same browser the error occurs in? Did you do something special to get the error?

**Comment by ElvisClaros** [comment]
**Are you sure this runs on the same browser the error occurs in?**
_yes_
**Did you do something special to get the error?**
_no_

**Comment by ElvisClaros** [comment]
thanks for your help, in firefox everything works perfect, it only happens  me in chrome
