### ISSUE TITLE
Error on http://www.archivesnationales.culture.gouv.fr/anom/fr/Action-culturelle/Dossiers-du-mois/1310-Theatre-francais/Dossier-Theatre-Francais-en-Indochine.html

### ISSUE THREAD

**Issue by ducxop** [ruffle-rs/ruffle#3629]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:490:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:490:50
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (<anonymous>:3:6449)
    at std::sync::once::Once::call_once::{{closure}}::hce6501f6f20767e4 (chrome-extension://laacemfnjhpofbphldkjnbabnhcahnfe/dist/e48d67a029dc969004e2da7b91af2cc9.wasm:wasm-function[1470]:0x2bf954)
    at std::sync::once::Once::call_inner::hd3d269a4946f2df2 (chrome-extension://laacemfnjhpofbphldkjnbabnhcahnfe/dist/e48d67a029dc969004e2da7b91af2cc9.wasm:wasm-function[1736]:0x2f13e2)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h6ed7686ed76cb258 (chrome-extension://laacemfnjhpofbphldkjnbabnhcahnfe/dist/e48d67a029dc969004e2da7b91af2cc9.wasm:wasm-function[5191]:0x3f8636)
    at std::panicking::rust_panic_with_hook::h4f753dc70b771d8e (chrome-extension://laacemfnjhpofbphldkjnbabnhcahnfe/dist/e48d67a029dc969004e2da7b91af2cc9.wasm:wasm-function[3951]:0x3c91d7)
    at std::panicking::begin_panic_handler::{{closure}}::h5c9fc29957309ae8 (chrome-extension://laacemfnjhpofbphldkjnbabnhcahnfe/dist/e48d67a029dc969004e2da7b91af2cc9.wasm:wasm-function[4672]:0x3eaf5c)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h92808941d97e9b21 (chrome-extension://laacemfnjhpofbphldkjnbabnhcahnfe/dist/e48d67a029dc969004e2da7b91af2cc9.wasm:wasm-function[5563]:0x3fe36f)
    at rust_begin_unwind (chrome-extension://laacemfnjhpofbphldkjnbabnhcahnfe/dist/e48d67a029dc969004e2da7b91af2cc9.wasm:wasm-function[5434]:0x3fc97c)
    at core::panicking::panic_fmt::hbd8a975261a5f466 (chrome-extension://laacemfnjhpofbphldkjnbabnhcahnfe/dist/e48d67a029dc969004e2da7b91af2cc9.wasm:wasm-function[5564]:0x3fe3a5)
    at core::option::expect_none_failed::hbea1e2e5b59d80cc (chrome-extension://laacemfnjhpofbphldkjnbabnhcahnfe/dist/e48d67a029dc969004e2da7b91af2cc9.wasm:wasm-function[4786]:0x3ee7e6)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: CHARGEUR_v2012.swf
Param movie: CHARGEUR_v2012.swf
Param quality: high
Param wmode: opaque
Param swfversion: 6.0.65.0
Param expressinstall: ../../../Scripts/expressInstall.swf
Param allowFullScreen: true
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined
Attribute 6: undefined

# Page Info
Page URL: http://www.archivesnationales.culture.gouv.fr/anom/fr/Action-culturelle/Dossiers-du-mois/1310-Theatre-francais/Dossier-Theatre-Francais-en-Indochine.html
SWF URL: http://www.archivesnationales.culture.gouv.fr/anom/fr/Action-culturelle/Dossiers-du-mois/1310-Theatre-francais/CHARGEUR_v2012.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-03-12
Channel: nightly
Built: 2021-03-12T00:19:02.503Z
Commit: 2ca6d2bf6c263343a8da86debaf08780b22da881

**Comment by ducxop** [comment]
there's problem with swf file
