### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by yasuo5201** [ruffle-rs/ruffle#3640]
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', web/src/lib.rs:847:49
Error stack:
```
Error: panicked at 'already borrowed: BorrowMutError', web/src/lib.rs:847:49
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://uploads.ungrounded.net/ruffle_wrapper/lib/ruffle.js?1615651419:1:6553)
    at std::sync::once::Once::call_once::{{closure}}::hce6501f6f20767e4 (wasm-function[1470]:169)
    at std::sync::once::Once::call_inner::hd3d269a4946f2df2 (wasm-function[1736]:675)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h6ed7686ed76cb258 (wasm-function[5191]:67)
    at std::panicking::rust_panic_with_hook::h4f753dc70b771d8e (wasm-function[3951]:224)
    at std::panicking::begin_panic_handler::{{closure}}::h5c9fc29957309ae8 (wasm-function[4672]:159)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h92808941d97e9b21 (wasm-function[5563]:40)
    at rust_begin_unwind (wasm-function[5434]:89)
    at core::panicking::panic_fmt::hbd8a975261a5f466 (wasm-function[5564]:48)
    at core::option::expect_none_failed::hbea1e2e5b59d80cc (wasm-function[4786]:123)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.64&browsermode=mobile&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1615651419%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F690000%2F690595_preparation-final.swf%3F1490153322%22%2C%22vars%22%3A%7B%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%22604d3c222b90f%22%2C%22NewgroundsAPI_SessionID%22%3A%22%22%2C%22NewgroundsAPI_UserName%22%3A%22%26lt%3Bdeleted%26gt%3B%22%2C%22NewgroundsAPI_UserID%22%3A0%2C%22ng_username%22%3A%22%26lt%3Bdeleted%26gt%3B%22%7D%2C%22width%22%3A900%2C%22height%22%3A600%2C%22icon%22%3A%22https%3A%2F%2Fimg.ngfiles.com%2Fdefaults%2Ficon-portal-xl-a.gif%3Ff1601395813%22%7D
SWF URL: https://uploads.ungrounded.net/690000/690595_preparation-final.swf?1490153322

# Browser Info
Useragent: Mozilla/5.0 (Linux; Android 10; V2001A; wv) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.84 Mobile Safari/537.36 VivoBrowser/9.1.10.1
OS: Linux armv8l

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-03-13
Channel: nightly
Built: 2021-03-13T00:18:20.687Z
Commit: 1c2492005c30e0f6bf867211307484e9c23da7c6

**Comment by Poopooracoocoo** [comment]
@yasuo5201 Do you encounter this error on a newer version of Chrome? If not, please close this issue. Ruffle supports version 87 and above of Chrome. It's also worth looking at other browsers _based on_ version Chromium 87 and above. Some examples of such browsers are Bromite and Brave. 

Vivo Browser 9.1 is based on Chromium 62 which does not support the modern web technologies that Ruffle utilizes. 

I understand that accessing different browsers is complicated in China but you should be able to sideload them with an APK.
