### ISSUE TITLE
Error on http://www.kidszzanggame.com/d/player.html?game_id=3775

### ISSUE THREAD

**Issue by hyun-tae04** [ruffle-rs/ruffle#3667]
# Error Info
Error name: Error
Error message: panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:542:5
Error stack:
```
Error: panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:542:5
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (http://www.kidszzanggame.com/ruffle/ruffle.js:1:6799)
    at std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f (http://www.kidszzanggame.com/ruffle/8010f9be08ca2f55253297e95a72ef45.wasm:wasm-function[1319]:0x26d032)
    at std::sync::once::Once::call_inner::h02eac160d339afc2 (http://www.kidszzanggame.com/ruffle/8010f9be08ca2f55253297e95a72ef45.wasm:wasm-function[1589]:0x29e913)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801 (http://www.kidszzanggame.com/ruffle/8010f9be08ca2f55253297e95a72ef45.wasm:wasm-function[4613]:0x38065e)
    at std::panicking::rust_panic_with_hook::h123718ba3bf480af (http://www.kidszzanggame.com/ruffle/8010f9be08ca2f55253297e95a72ef45.wasm:wasm-function[3452]:0x354705)
    at std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2 (http://www.kidszzanggame.com/ruffle/8010f9be08ca2f55253297e95a72ef45.wasm:wasm-function[4116]:0x373a6b)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925 (http://www.kidszzanggame.com/ruffle/8010f9be08ca2f55253297e95a72ef45.wasm:wasm-function[4967]:0x385ead)
    at rust_begin_unwind (http://www.kidszzanggame.com/ruffle/8010f9be08ca2f55253297e95a72ef45.wasm:wasm-function[4843]:0x3845ee)
    at core::panicking::panic_fmt::h285dc015a87be5a4 (http://www.kidszzanggame.com/ruffle/8010f9be08ca2f55253297e95a72ef45.wasm:wasm-function[4969]:0x385f11)
    at core::panicking::panic::h0abe4e7a620ae568 (http://www.kidszzanggame.com/ruffle/8010f9be08ca2f55253297e95a72ef45.wasm:wasm-function[4776]:0x3834b7)
```

# Player Info
Allows script access: true

# Page Info
Page URL: http://www.kidszzanggame.com/d/player.html?game_id=3775
SWF URL: http://www.kidszzanggame.com/honeygame/swf/3775.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-02-05
Channel: nightly
Built: 2021-02-05T00:17:35.210Z
Commit: b5749ee2285e240f87757f95369d5af2159e2812

**Comment by adrian17** [comment]
The crash was fixed and the game loads. The mouse interaction still doesn't work so the game isn't yet playable unfortunately; I submitted https://github.com/ruffle-rs/ruffle/issues/3723 for this issue.
