### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by DazedNConfused-** [ruffle-rs/ruffle#3753]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:490:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:490:50
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://uploads.ungrounded.net/ruffle_wrapper/lib/ruffle.js?1616425469:1:6553)
    at std::sync::once::Once::call_once::{{closure}}::hce6501f6f20767e4 (https://uploads.ungrounded.net/ruffle_wrapper/lib/dd280c8a7aa464beeccc78df18fd16df.wasm:wasm-function[1470]:0x2c47ba)
    at std::sync::once::Once::call_inner::hd3d269a4946f2df2 (https://uploads.ungrounded.net/ruffle_wrapper/lib/dd280c8a7aa464beeccc78df18fd16df.wasm:wasm-function[1760]:0x2fa94f)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h6ed7686ed76cb258 (https://uploads.ungrounded.net/ruffle_wrapper/lib/dd280c8a7aa464beeccc78df18fd16df.wasm:wasm-function[5222]:0x404b8b)
    at std::panicking::rust_panic_with_hook::h4f753dc70b771d8e (https://uploads.ungrounded.net/ruffle_wrapper/lib/dd280c8a7aa464beeccc78df18fd16df.wasm:wasm-function[4007]:0x3d664d)
    at std::panicking::begin_panic_handler::{{closure}}::h5c9fc29957309ae8 (https://uploads.ungrounded.net/ruffle_wrapper/lib/dd280c8a7aa464beeccc78df18fd16df.wasm:wasm-function[4717]:0x3f7a92)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h92808941d97e9b21 (https://uploads.ungrounded.net/ruffle_wrapper/lib/dd280c8a7aa464beeccc78df18fd16df.wasm:wasm-function[5590]:0x40a7e9)
    at rust_begin_unwind (https://uploads.ungrounded.net/ruffle_wrapper/lib/dd280c8a7aa464beeccc78df18fd16df.wasm:wasm-function[5465]:0x408ec7)
    at core::panicking::panic_fmt::hbd8a975261a5f466 (https://uploads.ungrounded.net/ruffle_wrapper/lib/dd280c8a7aa464beeccc78df18fd16df.wasm:wasm-function[5591]:0x40a81f)
    at core::option::expect_none_failed::hbea1e2e5b59d80cc (https://uploads.ungrounded.net/ruffle_wrapper/lib/dd280c8a7aa464beeccc78df18fd16df.wasm:wasm-function[4823]:0x3faf5e)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.64&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1616425469%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F376000%2F376206_PICO3.swf%3F1177911334%22%2C%22vars%22%3A%7B%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%226059e8c28d5c4%22%2C%22NewgroundsAPI_SessionID%22%3A%22%22%2C%22NewgroundsAPI_UserName%22%3A%22%26lt%3Bdeleted%26gt%3B%22%2C%22NewgroundsAPI_UserID%22%3A0%2C%22ng_username%22%3A%22%26lt%3Bdeleted%26gt%3B%22%7D%2C%22width%22%3A550%2C%22height%22%3A400%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F376000%2Fflash_376206.png%3Ff1364564222%22%7D
SWF URL: https://uploads.ungrounded.net/376000/376206_PICO3.swf?1177911334

# Browser Info
Useragent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-03-22
Channel: nightly
Built: 2021-03-22T00:19:43.563Z
Commit: 760e8421ab2b41ed11e124334d81325c7e0f235e

**Comment by DazedNConfused-** [comment]
A page reload solved the issue. Closing this.
