### ISSUE TITLE
Error on https://www.flashgamehacks.com/hacked/77-skies-of-war-extended

### ISSUE THREAD

**Issue by Darkiring** [ruffle-rs/ruffle#3765]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm1/globals/bitmap_data.rs:1212:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm1/globals/bitmap_data.rs:1212:18
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://www.flashgamehacks.com/js/ruffle.js?1111:1:6553)
    at std::sync::once::Once::call_once::{{closure}}::hce6501f6f20767e4 (https://www.flashgamehacks.com/js/67039e8beeaa6e66ebaa95e9fd36ad42.wasm:wasm-function[1471]:0x2bfd2d)
    at std::sync::once::Once::call_inner::hd3d269a4946f2df2 (https://www.flashgamehacks.com/js/67039e8beeaa6e66ebaa95e9fd36ad42.wasm:wasm-function[1752]:0x2f41ec)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h6ed7686ed76cb258 (https://www.flashgamehacks.com/js/67039e8beeaa6e66ebaa95e9fd36ad42.wasm:wasm-function[5184]:0x3fa7b7)
    at std::panicking::rust_panic_with_hook::h4f753dc70b771d8e (https://www.flashgamehacks.com/js/67039e8beeaa6e66ebaa95e9fd36ad42.wasm:wasm-function[3968]:0x3cc3d0)
    at std::panicking::begin_panic_handler::{{closure}}::h5c9fc29957309ae8 (https://www.flashgamehacks.com/js/67039e8beeaa6e66ebaa95e9fd36ad42.wasm:wasm-function[4676]:0x3ed558)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h92808941d97e9b21 (https://www.flashgamehacks.com/js/67039e8beeaa6e66ebaa95e9fd36ad42.wasm:wasm-function[5556]:0x4004f0)
    at rust_begin_unwind (https://www.flashgamehacks.com/js/67039e8beeaa6e66ebaa95e9fd36ad42.wasm:wasm-function[5427]:0x3feafd)
    at core::panicking::panic_fmt::hbd8a975261a5f466 (https://www.flashgamehacks.com/js/67039e8beeaa6e66ebaa95e9fd36ad42.wasm:wasm-function[5557]:0x400526)
    at core::panicking::panic::h8e74859c8f9988ca (https://www.flashgamehacks.com/js/67039e8beeaa6e66ebaa95e9fd36ad42.wasm:wasm-function[5357]:0x3fd900)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.flashgamehacks.com/hacked/77-skies-of-war-extended
SWF URL: http://www.flashgamehacks.com/games/skiesofwarextended.swf

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-03-19
Channel: nightly
Built: 2021-03-19T00:19:11.729Z
Commit: 7eb4c1440abc39360d4de148311b5fad46b92696

**Comment by adrian17** [comment]
> Invalid BitmapData size 3840x1440

@CUB3D what was the source of the 2880 size limit?

**Comment by CUB3D** [comment]
The ActionScript 2 reference(page 299):
```The maximum width and maximum height of a BitmapData object is 2880 pixels. If you specify a width or height value that is greater than 2880, a new instance is not created.```
However, since implementing this I found some more information in the ActionScript 3 docs [here](https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/display/BitmapData.html), specifically: 
```In AIR 1.5 and Flash Player 10, the maximum size for a BitmapData object is 8,191 pixels in width or height, and the total number of pixels cannot exceed 16,777,215 pixels. (So, if a BitmapData object is 8,191 pixels wide, it can only be 2,048 pixels high.) In Flash Player 9 and earlier and AIR 1.1 and earlier, the limitation is 2,880 pixels in height and 2,880 in width. Starting with AIR 3 and Flash player 11, the size limits for a BitmapData object have been removed. The maximum size of a bitmap is now dependent on the operating system.``` 
This check probably needs to either vary based on the SWF version
