### ISSUE TITLE
Error on https://w8.snokido.com/games/flash/index.html

### ISSUE THREAD

**Issue by uchihaboy-max** [ruffle-rs/ruffle#3809]
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', web/src/lib.rs:847:49
Error stack:
```
Error: panicked at 'already borrowed: BorrowMutError', web/src/lib.rs:847:49
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://w8.snokido.com/games/flash/ruffle/140321/ruffle.js:1:6553)
    at wasm-function[1470]:169
    at wasm-function[1734]:675
    at wasm-function[5189]:67
    at wasm-function[3949]:224
    at wasm-function[4670]:159
    at wasm-function[5561]:40
    at wasm-function[5432]:89
    at wasm-function[5562]:48
    at wasm-function[4784]:123
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://w8.snokido.com/games/flash/index.html?g=catburglar-magic-museum
SWF URL: https://w8.snokido.com/games/flash/catburglar-magic-museum.swf

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-03-14
Channel: nightly
Built: 2021-03-14T00:19:50.145Z
Commit: 12dee2199e41146017a0435ea30fac4ff2b57b1c

**Comment by Lord-McSweeney** [comment]
Closing as the site was using a version of Ruffle that is now 4 years outdated
