### ISSUE TITLE
Error on https://www.jogos360.com.br/uno.html

### ISSUE THREAD

**Issue by sulamitasouza** [ruffle-rs/ruffle#3811]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: JsValue(InvalidStateError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
Error: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
    at https://www.jogos360.com.br/js/ruffle/ruffle.js:1:26521
    at https://www.jogos360.com.br/js/ruffle/ruffle.js:1:4505
    at web_sys::features::gen_CanvasRenderingContext2d::CanvasRenderingContext2d::draw_image_with_html_canvas_element::h5c60240fe66a1cea (https://www.jogos360.com.br/js/ruffle/bf4d4f25e545c29722d2ab3143ad22e4.wasm:wasm-function[4934]:0x3a6c85)
    at <ruffle_render_canvas::WebCanvasRenderBackend as ruffle_core::backend::render::RenderBackend>::pop_mask::ha6a53f4d027e5730 (https://www.jogos360.com.br/js/ruffle/bf4d4f25e545c29722d2ab3143ad22e4.wasm:wasm-function[1059]:0x234b8d)
    at ruffle_core::display_object::container::TDisplayObjectContainer::render_children::h2310fc3bd338c05a (https://www.jogos360.com.br/js/ruffle/bf4d4f25e545c29722d2ab3143ad22e4.wasm:wasm-function[1244]:0x262a99)
    at ruffle_core::display_object::TDisplayObject::render::hc9ed9af41803d351 (https://www.jogos360.com.br/js/ruffle/bf4d4f25e545c29722d2ab3143ad22e4.wasm:wasm-function[1576]:0x2a4d39)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render::h8e6836539bd490c0 (https://www.jogos360.com.br/js/ruffle/bf4d4f25e545c29722d2ab3143ad22e4.wasm:wasm-function[4434]:0x39b1ad)
    at ruffle_core::display_object::container::TDisplayObjectContainer::render_children::h2310fc3bd338c05a (https://www.jogos360.com.br/js/ruffle/bf4d4f25e545c29722d2ab3143ad22e4.wasm:wasm-function[1244]:0x2629a7)
    at ruffle_core::display_object::TDisplayObject::render::hc9ed9af41803d351 (https://www.jogos360.com.br/js/ruffle/bf4d4f25e545c29722d2ab3143ad22e4.wasm:wasm-function[1576]:0x2a4d39)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render::h8e6836539bd490c0 (https://www.jogos360.com.br/js/ruffle/bf4d4f25e545c29722d2ab3143ad22e4.wasm:wasm-function[4434]:0x39b1ad))', render/canvas/src/lib.rs:685:14

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.jogos360.com.br/uno.html
SWF URL: https://cdn.jogos360.com.br/files/games/un/o1/uno.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-02-21
Channel: nightly
Built: 2021-02-21T00:20:18.629Z
Commit: eb173f06ca0918e2d2b488cd14849152db607e51

**Comment by relrelb** [comment]
Fixed by #7026.
