### ISSUE TITLE
Error on https://flash.porno-apk.com/game.php

### ISSUE THREAD

**Issue by 205767** [ruffle-rs/ruffle#3813]
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', web/src/lib.rs:847:49
Error stack:
```
Error: panicked at 'already borrowed: BorrowMutError', web/src/lib.rs:847:49
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://flash.porno-apk.com/ruffle/14-03-2021/ruffle.js:1:6553)
    at std::sync::once::Once::call_once::{{closure}}::hce6501f6f20767e4 (wasm-function[1470]:169)
    at std::sync::once::Once::call_inner::hd3d269a4946f2df2 (wasm-function[1734]:675)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h6ed7686ed76cb258 (wasm-function[5189]:67)
    at std::panicking::rust_panic_with_hook::h4f753dc70b771d8e (wasm-function[3949]:224)
    at std::panicking::begin_panic_handler::{{closure}}::h5c9fc29957309ae8 (wasm-function[4670]:159)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h92808941d97e9b21 (wasm-function[5561]:40)
    at rust_begin_unwind (wasm-function[5432]:89)
    at core::panicking::panic_fmt::hbd8a975261a5f466 (wasm-function[5562]:48)
    at core::option::expect_none_failed::hbea1e2e5b59d80cc (wasm-function[4784]:123)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: game/13.swf
Param movie: game/13.swf
Param quality: high
Param play: true
Param loop: true
Param wmode: window
Param scale: showall
Param allowFullScreen: true
Param menu: true
Param devicefont: false
Param allowScriptAccess: always
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined

# Page Info
Page URL: https://flash.porno-apk.com/game.php?i=13
SWF URL: https://flash.porno-apk.com/game/13.swf

# Browser Info
Useragent: Mozilla/5.0 (Linux; Android 9; V1901A Build/P00610; wv) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.84 Mobile Safari/537.36 VivoBrowser/9.1.15.0
OS: Linux armv8l

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-03-14
Channel: nightly
Built: 2021-03-14T00:19:50.145Z
Commit: 12dee2199e41146017a0435ea30fac4ff2b57b1c

**Comment by Poopooracoocoo** [comment]
Closing for same reasons as #2664
