### ISSUE TITLE
Error on https://flash.porno-apk.com/game.php

### ISSUE THREAD

**Issue by zzeer** [ruffle-rs/ruffle#3881]
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', web/src/lib.rs:847:49
Error stack:
```
Error: panicked at 'already borrowed: BorrowMutError', web/src/lib.rs:847:49
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://flash.porno-apk.com/ruffle/02-04-2021/ruffle.js:1:6915)
    at std::sync::once::Once::call_once::{{closure}}::h098c4530511c1407 (wasm-function[1196]:183)
    at std::sync::once::Once::call_inner::hf7fd718057964857 (wasm-function[1782]:675)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h6c44fc25588b0f32 (wasm-function[5307]:67)
    at std::panicking::rust_panic_with_hook::h9d91fa0fae16500f (wasm-function[4081]:222)
    at std::panicking::begin_panic_handler::{{closure}}::h2d82b5b2db976f3f (wasm-function[4788]:159)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h24539600b7e2452c (wasm-function[5680]:40)
    at rust_begin_unwind (wasm-function[5551]:89)
    at core::panicking::panic_fmt::h91d2023e5afe1929 (wasm-function[5682]:48)
    at core::option::expect_none_failed::h203584ddbc785ca2 (wasm-function[4904]:123)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: game/4.swf
Param movie: game/4.swf
Param quality: high
Param play: true
Param loop: true
Param wmode: window
Param scale: showall
Param allowFullScreen: true
Param menu: true
Param devicefont: false
Param allowScriptAccess: always
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined

# Page Info
Page URL: https://flash.porno-apk.com/game.php?i=4
SWF URL: https://flash.porno-apk.com/game/4.swf

# Browser Info
Useragent: Mozilla/5.0 (Linux; Android 10; V2034A; wv) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.84 Mobile Safari/537.36 VivoBrowser/9.1.10.1
OS: Linux armv8l

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-04-02
Channel: nightly
Built: 2021-04-02T00:48:56.172Z
Commit: bbded906971e98016cd104d47dcd2fa34fd001c2

**Comment by Lord-McSweeney** [comment]
Closing as the site was using a version of Ruffle that is now 4 years outdated
