### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by lovqslut** [ruffle-rs/ruffle#3946]
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', web/src/lib.rs:847:49
Error stack:
```
Error: panicked at 'already borrowed: BorrowMutError', web/src/lib.rs:847:49
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://uploads.ungrounded.net/ruffle_wrapper/lib/ruffle.js?1617971093:1:6915)
    at std::sync::once::Once::call_once::{{closure}}::h098c4530511c1407 (wasm-function[1226]:183)
    at std::sync::once::Once::call_inner::hf7fd718057964857 (wasm-function[1852]:675)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h6c44fc25588b0f32 (wasm-function[5327]:67)
    at std::panicking::rust_panic_with_hook::h9d91fa0fae16500f (wasm-function[4134]:222)
    at std::panicking::begin_panic_handler::{{closure}}::h2d82b5b2db976f3f (wasm-function[4809]:159)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h24539600b7e2452c (wasm-function[5710]:40)
    at rust_begin_unwind (wasm-function[5578]:89)
    at core::panicking::panic_fmt::h91d2023e5afe1929 (wasm-function[5712]:48)
    at core::option::expect_none_failed::h203584ddbc785ca2 (wasm-function[4919]:123)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.64&browsermode=mobile&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1617971093%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F385000%2F385828_pocketemo.swf%3F1188309694%22%2C%22vars%22%3A%7B%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%226070de1cca433%22%2C%22NewgroundsAPI_SessionID%22%3A%22%22%2C%22NewgroundsAPI_UserName%22%3A%22%26lt%3Bdeleted%26gt%3B%22%2C%22NewgroundsAPI_UserID%22%3A0%2C%22ng_username%22%3A%22%26lt%3Bdeleted%26gt%3B%22%7D%2C%22width%22%3A300%2C%22height%22%3A420%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F385000%2Fflash_385828.png%3Ff1364564905%22%7D
SWF URL: https://uploads.ungrounded.net/385000/385828_pocketemo.swf?1188309694

# Browser Info
Useragent: Mozilla/5.0 (Linux; Android 8.1.0; vivo 1820 Build/O11019; wv) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.84 Mobile Safari/537.36 VivoBrowser/7.3.0.1
OS: Linux armv8l

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-04-09
Channel: nightly
Built: 2021-04-09T00:39:28.452Z
Commit: ed6fe86e31d6dbef47aebdef71a95ddfb1ca6172

**Comment by Poopooracoocoo** [comment]
Link to Pocket Emo on Newgrounds:
https://www.newgrounds.com/portal/view/385828

**Comment by Lord-McSweeney** [comment]
Closing as the site was using a version of Ruffle that is now 4 years outdated
