### ISSUE TITLE
Error on https://h-flash.com/pgspotstudios-wheel-of-fucktion/

### ISSUE THREAD

**Issue by sxmonster233** [ruffle-rs/ruffle#3983]
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', web/src/lib.rs:641:42
Error stack:
```
Error: panicked at 'already borrowed: BorrowMutError', web/src/lib.rs:641:42
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://h-flash.com/data/ruffle/ruffle.js:1:6915)
    at std::sync::once::Once::call_once::{{closure}}::h098c4530511c1407 (wasm-function[1226]:183)
    at std::sync::once::Once::call_inner::hf7fd718057964857 (wasm-function[1852]:675)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h6c44fc25588b0f32 (wasm-function[5327]:67)
    at std::panicking::rust_panic_with_hook::h9d91fa0fae16500f (wasm-function[4134]:222)
    at std::panicking::begin_panic_handler::{{closure}}::h2d82b5b2db976f3f (wasm-function[4809]:159)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h24539600b7e2452c (wasm-function[5710]:40)
    at rust_begin_unwind (wasm-function[5578]:89)
    at core::panicking::panic_fmt::h91d2023e5afe1929 (wasm-function[5712]:48)
    at core::option::expect_none_failed::h203584ddbc785ca2 (wasm-function[4919]:123)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://h-flash.com/pgspotstudios-wheel-of-fucktion/
SWF URL: https://h-flash.com/data/swf/2021/03/698973_wheeloffucktion-minigame.swf

# Browser Info
Useragent: Mozilla/5.0 (Linux; Android 10; V1962A; wv) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.84 Mobile Safari/537.36 VivoBrowser/9.2.70.0
OS: Linux armv8l

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-04-09
Channel: nightly
Built: 2021-04-09T00:39:28.452Z
Commit: ed6fe86e31d6dbef47aebdef71a95ddfb1ca6172

**Comment by DJTyt** [comment]
use this proxy site:
https://ersupport.com/plugins/QuickWebProxy/miniProxy.php

**Comment by Lord-McSweeney** [comment]
Closing as the site was using a version of Ruffle that is now 4 years outdated
