### ISSUE TITLE
Error on https://ruffle.rs/demo/

### ISSUE THREAD

**Issue by smb64** [ruffle-rs/ruffle#3998]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:499:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:499:50
    at r.wbg.__wbg_new_df6e6ab7a65c4c4d (https://ruffle.rs/demo/index.js:1:17343)
    at std::sync::once::Once::call_once::{{closure}}::h098c4530511c1407 (https://ruffle.rs/demo/56ce8e9cbf30a8f737e3556d0c544316.wasm:wasm-function[1222]:0x2abc22)
    at std::sync::once::Once::call_inner::hf7fd718057964857 (https://ruffle.rs/demo/56ce8e9cbf30a8f737e3556d0c544316.wasm:wasm-function[1841]:0x32e1d3)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h6c44fc25588b0f32 (https://ruffle.rs/demo/56ce8e9cbf30a8f737e3556d0c544316.wasm:wasm-function[5350]:0x43c24d)
    at std::panicking::rust_panic_with_hook::h9d91fa0fae16500f (https://ruffle.rs/demo/56ce8e9cbf30a8f737e3556d0c544316.wasm:wasm-function[4141]:0x40e6da)
    at std::panicking::begin_panic_handler::{{closure}}::h2d82b5b2db976f3f (https://ruffle.rs/demo/56ce8e9cbf30a8f737e3556d0c544316.wasm:wasm-function[4826]:0x42e87b)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h24539600b7e2452c (https://ruffle.rs/demo/56ce8e9cbf30a8f737e3556d0c544316.wasm:wasm-function[5733]:0x4421f6)
    at rust_begin_unwind (https://ruffle.rs/demo/56ce8e9cbf30a8f737e3556d0c544316.wasm:wasm-function[5601]:0x44079a)
    at core::panicking::panic_fmt::h91d2023e5afe1929 (https://ruffle.rs/demo/56ce8e9cbf30a8f737e3556d0c544316.wasm:wasm-function[5735]:0x44225a)
    at core::option::expect_none_failed::h203584ddbc785ca2 (https://ruffle.rs/demo/56ce8e9cbf30a8f737e3556d0c544316.wasm:wasm-function[4944]:0x432327)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://ruffle.rs/demo/

# Browser Info
Useragent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.105 Safari/537.36
OS: Linux aarch64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-04-14
Channel: nightly
Built: 2021-04-14T00:39:28.120Z
Commit: ee0b473f7d9511d75a9bb626e97ea7ed2dbc1591

**Comment by Poopooracoocoo** [comment]
Which SWF were you trying to play? You can upload it to GitHub by zipping it.
