### ISSUE TITLE
Error on https://69games.xxx/games/milk_plant_7

### ISSUE THREAD

**Issue by jokerlly** [ruffle-rs/ruffle#4042]
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', web/src/lib.rs:632:42
Error stack:
```
Error: panicked at 'already borrowed: BorrowMutError', web/src/lib.rs:632:42
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://cdn.69games.xxx/common/flashes/js/ruffle210214/ruffle.js:1:6799)
    at std::sync::once::Once::call_once::{{closure}}::hce6501f6f20767e4 (wasm-function[1327]:169)
    at std::sync::once::Once::call_inner::hd3d269a4946f2df2 (wasm-function[1604]:675)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h6ed7686ed76cb258 (wasm-function[4639]:67)
    at std::panicking::rust_panic_with_hook::h4f753dc70b771d8e (wasm-function[3509]:224)
    at std::panicking::begin_panic_handler::{{closure}}::h5c9fc29957309ae8 (wasm-function[4146]:159)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h92808941d97e9b21 (wasm-function[4985]:40)
    at rust_begin_unwind (wasm-function[4870]:89)
    at core::panicking::panic_fmt::hbd8a975261a5f466 (wasm-function[4986]:48)
    at core::option::expect_none_failed::hbea1e2e5b59d80cc (wasm-function[4244]:123)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://69games.xxx/games/milk_plant_7
SWF URL: https://cdn.69games.xxx/common/flashes/ff/m/milk_plant_7.swf?d=20120403112318

# Browser Info
Useragent: Mozilla/5.0 (Linux; Android 7.1.1; vivo Y75A Build/N6F26Q; wv) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.84 Mobile Safari/537.36 VivoBrowser/9.2.12.0
OS: Linux armv8l

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-02-14
Channel: nightly
Built: 2021-02-14T00:19:03.523Z
Commit: ecd873eb39c141f9bf2e41454c7a47d5f7e9507c

**Comment by jokerlly** [comment]
Closing questions

**Comment by Lord-McSweeney** [comment]
Closing as the site was using a version of Ruffle that is now 4 years outdated
