### ISSUE TITLE
Error on https://istaging.cde.ca.gov:8900/contribute/admin/server.cfm

### ISSUE THREAD

**Issue by ClaySilva** [ruffle-rs/ruffle#4109]
# Error Info
Error name: Error
Error message: panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:536:5
Error stack:
```
Error: panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:536:5
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://alllepeipkepepakhnfeolihbidoanbp/dist/ruffle.js?uniqueMessageSuffix=40380821808:1:7447)
    at std::sync::once::Once::call_once::{{closure}}::h098c4530511c1407 (chrome-extension://alllepeipkepepakhnfeolihbidoanbp/dist/b3448156c16abc79d249.wasm:wasm-function[838]:0x228391)
    at std::sync::once::Once::call_inner::hf7fd718057964857 (chrome-extension://alllepeipkepepakhnfeolihbidoanbp/dist/b3448156c16abc79d249.wasm:wasm-function[1230]:0x2aacde)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h6c44fc25588b0f32 (chrome-extension://alllepeipkepepakhnfeolihbidoanbp/dist/b3448156c16abc79d249.wasm:wasm-function[3690]:0x43294f)
    at std::panicking::rust_panic_with_hook::h9d91fa0fae16500f (chrome-extension://alllepeipkepepakhnfeolihbidoanbp/dist/b3448156c16abc79d249.wasm:wasm-function[2689]:0x39a39b)
    at rust_begin_unwind (chrome-extension://alllepeipkepepakhnfeolihbidoanbp/dist/b3448156c16abc79d249.wasm:wasm-function[3892]:0x43806d)
    at core::panicking::panic_fmt::h91d2023e5afe1929 (chrome-extension://alllepeipkepepakhnfeolihbidoanbp/dist/b3448156c16abc79d249.wasm:wasm-function[4004]:0x43b989)
    at core::panicking::panic::h5da66f104e83c46a (chrome-extension://alllepeipkepepakhnfeolihbidoanbp/dist/b3448156c16abc79d249.wasm:wasm-function[3834]:0x435d96)
    at alloc::raw_vec::capacity_overflow::h19880780afbbe0f4 (chrome-extension://alllepeipkepepakhnfeolihbidoanbp/dist/b3448156c16abc79d249.wasm:wasm-function[4355]:0x43fdee)
    at alloc::raw_vec::RawVec<T,A>::reserve::h6741f8a9cc602da6 (chrome-extension://alllepeipkepepakhnfeolihbidoanbp/dist/b3448156c16abc79d249.wasm:wasm-function[2507]:0x38c934)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://istaging.cde.ca.gov:8900/contribute/admin/server.cfm
SWF URL: https://istaging.cde.ca.gov:8900/contribute/admin/server.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36 Edg/90.0.818.46
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-04-24
Channel: nightly
Built: 2021-04-24T00:32:40.634Z
Commit: 10b014bf1802d405c3c52a2243186f0022dcc0b8

**Comment by ClaySilva** [comment]
These URLs are not publicly accessible. Maybe that kills the chance to fix this? We are trying to keep a legacy application working that uses Flash for the admin interface. Any assistance or suggestions is appreciated. Running Ruffle from the browser extension on an inside-only network. I can control the environment  at the destination (istaging in this case), which is a MS web server/IIS.
