### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by PrimusRex** [ruffle-rs/ruffle#4166]
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', core/src/avm2/object/function_object.rs:280:5
Error stack:
```
Error: panicked at 'already borrowed: BorrowMutError', core/src/avm2/object/function_object.rs:280:5
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://uploads.ungrounded.net/ruffle_wrapper/lib/ruffle.js?1619614181:1:7830)
    at std::sync::once::Once::call_once::{{closure}}::h098c4530511c1407 (https://uploads.ungrounded.net/ruffle_wrapper/lib/5d3e5d908118de813bff.wasm:wasm-function[1039]:0x27cd55)
    at std::sync::once::Once::call_inner::hf7fd718057964857 (https://uploads.ungrounded.net/ruffle_wrapper/lib/5d3e5d908118de813bff.wasm:wasm-function[1241]:0x2b103a)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h6c44fc25588b0f32 (https://uploads.ungrounded.net/ruffle_wrapper/lib/5d3e5d908118de813bff.wasm:wasm-function[3721]:0x43f570)
    at std::panicking::rust_panic_with_hook::h9d91fa0fae16500f (https://uploads.ungrounded.net/ruffle_wrapper/lib/5d3e5d908118de813bff.wasm:wasm-function[2719]:0x399921)
    at rust_begin_unwind (https://uploads.ungrounded.net/ruffle_wrapper/lib/5d3e5d908118de813bff.wasm:wasm-function[3925]:0x445194)
    at core::panicking::panic_fmt::h91d2023e5afe1929 (https://uploads.ungrounded.net/ruffle_wrapper/lib/5d3e5d908118de813bff.wasm:wasm-function[4065]:0x44b91d)
    at core::option::expect_none_failed::h203584ddbc785ca2 (https://uploads.ungrounded.net/ruffle_wrapper/lib/5d3e5d908118de813bff.wasm:wasm-function[3354]:0x430a67)
    at ruffle_core::avm2::object::TObject::install_foreign_trait::h4fbf15553b663e9f (https://uploads.ungrounded.net/ruffle_wrapper/lib/5d3e5d908118de813bff.wasm:wasm-function[323]:0x9c144)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::set_property::he3dc29bc9fd20ccc (https://uploads.ungrounded.net/ruffle_wrapper/lib/5d3e5d908118de813bff.wasm:wasm-function[460]:0x144806)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.64&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1619614181%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F474000%2F474322_fishing_girl.swf%3F1229610125%22%2C%22vars%22%3A%7B%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%226089a22844415%22%2C%22NewgroundsAPI_SessionID%22%3A%22Yauae54Z4yi0GSW41OpTd19925c6d5a288d32eb1e5c5bd63a306727142a8RiHb%22%2C%22NewgroundsAPI_UserName%22%3A%22MessorCorvus%22%2C%22NewgroundsAPI_UserID%22%3A9121489%2C%22ng_username%22%3A%22MessorCorvus%22%7D%2C%22width%22%3A640%2C%22height%22%3A480%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F474000%2Fflash_474322.png%3Ff1364574425%22%7D
SWF URL: https://uploads.ungrounded.net/474000/474322_fishing_girl.swf?1229610125

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-04-28
Channel: nightly
Built: 2021-04-28T00:15:05.059Z
Commit: 5a6117722d08695a471f62474f70d08ae1dcd760

**Comment by Poopooracoocoo** [comment]
Link to Fishing Girl on Newgrounds:
https://www.newgrounds.com/portal/view/474322?emulate=flash
