### ISSUE TITLE
Error on http://www.zuzunza.com/myflash/game_detail.html?game_id=547258&category=&y_category=&tm1=&order=&writer=&from=&searchword=%EB%A7%8C%ED%99%94%EC%BA%90%EB%A6%AD&search_what=1&ml=19&wi=joonbaby1.png&hc=0&cp=1&p=

### ISSUE THREAD

**Issue by shin1022** [ruffle-rs/ruffle#4183]
# Error Info
Error name: Error
Error message: panicked at 'range end index 2 out of range for slice of length 0', core/src/avm1/globals/movie_clip.rs:725:45
Error stack:
```
Error: panicked at 'range end index 2 out of range for slice of length 0', core/src/avm1/globals/movie_clip.rs:725:45
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (http://www.zuzunza.com/ruffle/ruffle.js:1:6799)
    at std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f (http://www.zuzunza.com/ruffle/8010f9be08ca2f55253297e95a72ef45.wasm:wasm-function[1319]:0x26d032)
    at std::sync::once::Once::call_inner::h02eac160d339afc2 (http://www.zuzunza.com/ruffle/8010f9be08ca2f55253297e95a72ef45.wasm:wasm-function[1589]:0x29e913)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801 (http://www.zuzunza.com/ruffle/8010f9be08ca2f55253297e95a72ef45.wasm:wasm-function[4613]:0x38065e)
    at std::panicking::rust_panic_with_hook::h123718ba3bf480af (http://www.zuzunza.com/ruffle/8010f9be08ca2f55253297e95a72ef45.wasm:wasm-function[3452]:0x354705)
    at std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2 (http://www.zuzunza.com/ruffle/8010f9be08ca2f55253297e95a72ef45.wasm:wasm-function[4116]:0x373a92)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925 (http://www.zuzunza.com/ruffle/8010f9be08ca2f55253297e95a72ef45.wasm:wasm-function[4967]:0x385ead)
    at rust_begin_unwind (http://www.zuzunza.com/ruffle/8010f9be08ca2f55253297e95a72ef45.wasm:wasm-function[4843]:0x3845ee)
    at core::panicking::panic_fmt::h285dc015a87be5a4 (http://www.zuzunza.com/ruffle/8010f9be08ca2f55253297e95a72ef45.wasm:wasm-function[4969]:0x385f11)
    at core::slice::index::slice_end_index_len_fail::h6f6253f4aa8173a8 (http://www.zuzunza.com/ruffle/8010f9be08ca2f55253297e95a72ef45.wasm:wasm-function[4332]:0x379f89)
```

# Player Info
Allows script access: false

# Page Info
Page URL: http://www.zuzunza.com/myflash/game_detail.html?game_id=547258&category=&y_category=&tm1=&order=&writer=&from=&searchword=%EB%A7%8C%ED%99%94%EC%BA%90%EB%A6%AD&search_what=1&ml=19&wi=joonbaby1.png&hc=0&cp=1&p=
SWF URL: http://www.zuzunza.com/myflash/swf/547258.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-02-05
Channel: nightly
Built: 2021-02-05T00:17:35.210Z
Commit: b5749ee2285e240f87757f95369d5af2159e2812

**Comment by relrelb** [comment]
Fixed by #3447. Please [update your extension](https://github.com/ruffle-rs/ruffle/wiki/Using-Ruffle#browser-extension) to the latest nightly.
