### ISSUE TITLE
Error on https://homestarrunner.com/main

### ISSUE THREAD

**Issue by Itsdotcom** [ruffle-rs/ruffle#4256]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: JsValue(TypeError: s(...).createBuffer is not a function
TypeError: s(...).createBuffer is not a function
    at https://homestarrunner.com/assets/js/ruffle.1616687759.js:1:11293
    at https://homestarrunner.com/assets/js/ruffle.1616687759.js:1:4505
    at web_sys::features::gen_AudioContext::AudioContext::create_buffer::hd8ce47d669268a30 (https://homestarrunner.com/assets/js/44a34a452a04b301ca6e4923f6f0828e.wasm:wasm-function[5305]:0x40c740)
    at ruffle_web::audio::WebAudioBackend::decompress_to_audio_buffer::h90ddeabd92a3770d (https://homestarrunner.com/assets/js/44a34a452a04b301ca6e4923f6f0828e.wasm:wasm-function[493]:0x160de8)
    at <ruffle_web::audio::WebAudioBackend as ruffle_core::backend::audio::AudioBackend>::register_sound::h5af5afd895df3143 (https://homestarrunner.com/assets/js/44a34a452a04b301ca6e4923f6f0828e.wasm:wasm-function[2781]:0x37fef1)
    at ruffle_core::display_object::movie_clip::MovieClip::preload::{{closure}}::h7be1871efcfa0c77 (https://homestarrunner.com/assets/js/44a34a452a04b301ca6e4923f6f0828e.wasm:wasm-function[290]:0x3e70a)
    at ruffle_core::tag_utils::decode_tags::h8825abb8378fca8f (https://homestarrunner.com/assets/js/44a34a452a04b301ca6e4923f6f0828e.wasm:wasm-function[1504]:0x2ce19d)
    at ruffle_core::display_object::movie_clip::MovieClip::preload::h97a2628ba54a7187 (https://homestarrunner.com/assets/js/44a34a452a04b301ca6e4923f6f0828e.wasm:wasm-function[860]:0x21e21b)
    at ruffle_core::player::Player::set_root_movie::h3cbae2326990d0f5 (https://homestarrunner.com/assets/js/44a34a452a04b301ca6e4923f6f0828e.wasm:wasm-function[360]:0xdf356)
    at <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h76ae825727d5b40f (https://homestarrunner.com/assets/js/44a34a452a04b301ca6e4923f6f0828e.wasm:wasm-function[630]:0x1b7e1a))', web/src/audio.rs:712:14
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: JsValue(TypeError: s(...).createBuffer is not a function
TypeError: s(...).createBuffer is not a function
    at https://homestarrunner.com/assets/js/ruffle.1616687759.js:1:11293
    at https://homestarrunner.com/assets/js/ruffle.1616687759.js:1:4505
    at web_sys::features::gen_AudioContext::AudioContext::create_buffer::hd8ce47d669268a30 (https://homestarrunner.com/assets/js/44a34a452a04b301ca6e4923f6f0828e.wasm:wasm-function[5305]:0x40c740)
    at ruffle_web::audio::WebAudioBackend::decompress_to_audio_buffer::h90ddeabd92a3770d (https://homestarrunner.com/assets/js/44a34a452a04b301ca6e4923f6f0828e.wasm:wasm-function[493]:0x160de8)
    at <ruffle_web::audio::WebAudioBackend as ruffle_core::backend::audio::AudioBackend>::register_sound::h5af5afd895df3143 (https://homestarrunner.com/assets/js/44a34a452a04b301ca6e4923f6f0828e.wasm:wasm-function[2781]:0x37fef1)
    at ruffle_core::display_object::movie_clip::MovieClip::preload::{{closure}}::h7be1871efcfa0c77 (https://homestarrunner.com/assets/js/44a34a452a04b301ca6e4923f6f0828e.wasm:wasm-function[290]:0x3e70a)
    at ruffle_core::tag_utils::decode_tags::h8825abb8378fca8f (https://homestarrunner.com/assets/js/44a34a452a04b301ca6e4923f6f0828e.wasm:wasm-function[1504]:0x2ce19d)
    at ruffle_core::display_object::movie_clip::MovieClip::preload::h97a2628ba54a7187 (https://homestarrunner.com/assets/js/44a34a452a04b301ca6e4923f6f0828e.wasm:wasm-function[860]:0x21e21b)
    at ruffle_core::player::Player::set_root_movie::h3cbae2326990d0f5 (https://homestarrunner.com/assets/js/44a34a452a04b301ca6e4923f6f0828e.wasm:wasm-function[360]:0xdf356)
    at <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h76ae825727d5b40f (https://homestarrunner.com/assets/js/44a34a452a04b301ca6e4923f6f0828e.wasm:wasm-function[630]:0x1b7e1a))', web/src/audio.rs:712:14
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://homestarrunner.com/assets/js/ruffle.1616687759.js:1:6553)
    at std::sync::once::Once::call_once::{{closure}}::hce6501f6f20767e4 (https://homestarrunner.com/assets/js/44a34a452a04b301ca6e4923f6f0828e.wasm:wasm-function[1483]:0x2c9b25)
    at std::sync::once::Once::call_inner::hd3d269a4946f2df2 (https://homestarrunner.com/assets/js/44a34a452a04b301ca6e4923f6f0828e.wasm:wasm-function[1771]:0x2ff7df)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h6ed7686ed76cb258 (https://homestarrunner.com/assets/js/44a34a452a04b301ca6e4923f6f0828e.wasm:wasm-function[5275]:0x40bea6)
    at std::panicking::rust_panic_with_hook::h4f753dc70b771d8e (https://homestarrunner.com/assets/js/44a34a452a04b301ca6e4923f6f0828e.wasm:wasm-function[4041]:0x3dce1e)
    at std::panicking::begin_panic_handler::{{closure}}::h5c9fc29957309ae8 (https://homestarrunner.com/assets/js/44a34a452a04b301ca6e4923f6f0828e.wasm:wasm-function[4761]:0x3fe968)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h92808941d97e9b21 (https://homestarrunner.com/assets/js/44a34a452a04b301ca6e4923f6f0828e.wasm:wasm-function[5648]:0x411c18)
    at rust_begin_unwind (https://homestarrunner.com/assets/js/44a34a452a04b301ca6e4923f6f0828e.wasm:wasm-function[5522]:0x4102c3)
    at core::panicking::panic_fmt::hbd8a975261a5f466 (https://homestarrunner.com/assets/js/44a34a452a04b301ca6e4923f6f0828e.wasm:wasm-function[5649]:0x411c4e)
    at core::option::expect_none_failed::hbea1e2e5b59d80cc (https://homestarrunner.com/assets/js/44a34a452a04b301ca6e4923f6f0828e.wasm:wasm-function[4877]:0x4022e8)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://homestarrunner.com/main
SWF URL: https://homestarrunner.com/media/pages/main/6/d4baaac546-1609209060/main6.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-03-25
Channel: nightly
Built: 2021-03-25T00:36:18.574Z
Commit: f96a41403697d362aa051d0977873489269300b3

**Comment by Herschel** [comment]
Thanks for the report. Does this issue occur consistently for you? Or did it only happen once? Were you navigating away from the page when it happened?

Thank you!

**Comment by Itsdotcom** [comment]
This issue does happen consistently for me. It occurred when trying to view the main menu and again when I tried to watch a sbmail.

**Comment by Sonikkustar** [comment]
The web page doesn't seem to load for me so I can't test the web version, but I loaded up the SWF in the latest nightly and it seems to work for me. The main menu loads for me without any errors, though trying to click on any of the buttons leads to a 404 error when it opens the browser.

![image](https://github.com/ruffle-rs/ruffle/assets/22226938/db2a88f1-f888-4de5-9b61-b15667eb3829)

Tested on **ruffle-nightly-2024_02_03-windows-x86_64**

**Comment by adrian17** [comment]
The error mentioned is about a browser API, so whether it's actually fixed or not - checking with the desktop version unfortunately doesn't confirm anything here.
