### ISSUE TITLE
Error on https://armorgames.com/play/14170/arkandian-explorer

### ISSUE THREAD

**Issue by jamespagedev** [ruffle-rs/ruffle#4274]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', render/webgl/src/lib.rs:661:48
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', render/webgl/src/lib.rs:661:48
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://agi.armorgames.com/ruffle/ruffle.js:1:6924)
    at std::sync::once::Once::call_once::{{closure}}::h098c4530511c1407 (https://agi.armorgames.com/ruffle/64a2872b3d65e0591f0b.wasm:wasm-function[838]:0x228302)
    at std::sync::once::Once::call_inner::hf7fd718057964857 (https://agi.armorgames.com/ruffle/64a2872b3d65e0591f0b.wasm:wasm-function[1230]:0x2aac4f)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h6c44fc25588b0f32 (https://agi.armorgames.com/ruffle/64a2872b3d65e0591f0b.wasm:wasm-function[3690]:0x4328c0)
    at std::panicking::rust_panic_with_hook::h9d91fa0fae16500f (https://agi.armorgames.com/ruffle/64a2872b3d65e0591f0b.wasm:wasm-function[2689]:0x39a30c)
    at rust_begin_unwind (https://agi.armorgames.com/ruffle/64a2872b3d65e0591f0b.wasm:wasm-function[3892]:0x437fde)
    at core::panicking::panic_fmt::h91d2023e5afe1929 (https://agi.armorgames.com/ruffle/64a2872b3d65e0591f0b.wasm:wasm-function[4004]:0x43b8fa)
    at core::panicking::panic::h5da66f104e83c46a (https://agi.armorgames.com/ruffle/64a2872b3d65e0591f0b.wasm:wasm-function[3834]:0x435d07)
    at ruffle_render_webgl::WebGlRenderBackend::register_bitmap::h71b5da20bdd14fb3 (https://agi.armorgames.com/ruffle/64a2872b3d65e0591f0b.wasm:wasm-function[1353]:0x2c8090)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::register_bitmap_raw::hc4b7aa6d3e8c48ac (https://agi.armorgames.com/ruffle/64a2872b3d65e0591f0b.wasm:wasm-function[3088]:0x3bb14e)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://armorgames.com/play/14170/arkandian-explorer?tag-referral=adventure
SWF URL: https://cache.armorgames.com/files/games/arkandian-explorer-14170.swf?v=1373587528

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-04-26
Channel: nightly
Built: 2021-04-26T00:14:53.853Z
Commit: 3e9ae40b175a671dade3f49be9369956c6bdd73c

**Comment by kjarosh** [comment]
Should be fixed as of the newest version
