### ISSUE TITLE
Error on https://www.spiele-umsonst.de/bloons-tower-defense-1-t101.html

### ISSUE THREAD

**Issue by FeFling** [ruffle-rs/ruffle#4280]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', web/src/lib.rs:993:50
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', web/src/lib.rs:993:50
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://www.spiele-umsonst.de/ruffle/ruffle.js?v29:1:7479)
    at std::sync::once::Once::call_once::{{closure}}::h098c4530511c1407 (https://www.spiele-umsonst.de/ruffle/349d49a671de87a3e810.wasm:wasm-function[1227]:0x2ba694)
    at std::sync::once::Once::call_inner::hf7fd718057964857 (https://www.spiele-umsonst.de/ruffle/349d49a671de87a3e810.wasm:wasm-function[1250]:0x2c22b8)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h6c44fc25588b0f32 (https://www.spiele-umsonst.de/ruffle/349d49a671de87a3e810.wasm:wasm-function[3750]:0x44c00b)
    at std::panicking::rust_panic_with_hook::h9d91fa0fae16500f (https://www.spiele-umsonst.de/ruffle/349d49a671de87a3e810.wasm:wasm-function[2743]:0x3aa0ea)
    at rust_begin_unwind (https://www.spiele-umsonst.de/ruffle/349d49a671de87a3e810.wasm:wasm-function[3956]:0x451c86)
    at core::panicking::panic_fmt::h91d2023e5afe1929 (https://www.spiele-umsonst.de/ruffle/349d49a671de87a3e810.wasm:wasm-function[4103]:0x458d4d)
    at core::panicking::panic::h5da66f104e83c46a (https://www.spiele-umsonst.de/ruffle/349d49a671de87a3e810.wasm:wasm-function[3896]:0x44f4e0)
    at ruffle_web::Ruffle::on_metadata::heb78e9164bc1c280 (https://www.spiele-umsonst.de/ruffle/349d49a671de87a3e810.wasm:wasm-function[1156]:0x2a3dfc)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h555f8f4afee82003 (https://www.spiele-umsonst.de/ruffle/349d49a671de87a3e810.wasm:wasm-function[4020]:0x457b6f)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.spiele-umsonst.de/bloons-tower-defense-1-t101.html
SWF URL: https://www.spiele-umsonst.de/azad/downloads/flashgames/bloons-td.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-05-03
Channel: nightly
Built: 2021-05-03T00:12:09.006Z
Commit: f2256a661be22fd12ae1ec3b40574d7cca670a27

**Comment by Sonikkustar** [comment]
The site updated Ruffle to nightly 2022-09-29. Seems to work now. Haven't ran into any issues while playing.
![image](https://user-images.githubusercontent.com/22226938/194680847-a5d33823-be1d-45ee-86bb-baf25489590c.png)

**Comment by dginovker** [comment]
I've played BTD1 dozens of times on Ruffle in the last year+, game is good. Can close
