### ISSUE TITLE
Error on https://www.ixbt.com/storage/lsi-sas9211-8i.shtml

### ISSUE THREAD

**Issue by token0** [ruffle-rs/ruffle#4320]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:499:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:499:50
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://hkodngfplidedahenjkehgabkladbhad/dist/ruffle.js?uniqueMessageSuffix=94031668288:1:7476)
    at std::sync::once::Once::call_once::{{closure}}::h6e694fc45f651103 (chrome-extension://hkodngfplidedahenjkehgabkladbhad/dist/21481aef0dd584f24873.wasm:wasm-function[1070]:0x27ba0b)
    at std::sync::once::Once::call_inner::h99e47643887ee5a5 (chrome-extension://hkodngfplidedahenjkehgabkladbhad/dist/21481aef0dd584f24873.wasm:wasm-function[944]:0x24ffef)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hb552ca3003b47989 (chrome-extension://hkodngfplidedahenjkehgabkladbhad/dist/21481aef0dd584f24873.wasm:wasm-function[3793]:0x411bf4)
    at std::panicking::rust_panic_with_hook::h03201bc01a0ed891 (chrome-extension://hkodngfplidedahenjkehgabkladbhad/dist/21481aef0dd584f24873.wasm:wasm-function[2939]:0x39d756)
    at rust_begin_unwind (chrome-extension://hkodngfplidedahenjkehgabkladbhad/dist/21481aef0dd584f24873.wasm:wasm-function[3998]:0x417458)
    at core::panicking::panic_fmt::hd44f353696296fec (chrome-extension://hkodngfplidedahenjkehgabkladbhad/dist/21481aef0dd584f24873.wasm:wasm-function[4146]:0x41deb9)
    at core::option::expect_none_failed::hf7dab2706f1a5551 (chrome-extension://hkodngfplidedahenjkehgabkladbhad/dist/21481aef0dd584f24873.wasm:wasm-function[3380]:0x4016bd)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::hbd740e7843876002 (chrome-extension://hkodngfplidedahenjkehgabkladbhad/dist/21481aef0dd584f24873.wasm:wasm-function[586]:0x18e8c0)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::register_glyph_shape::h6379b2ca89c5e8e5 (chrome-extension://hkodngfplidedahenjkehgabkladbhad/dist/21481aef0dd584f24873.wasm:wasm-function[2149]:0x34dcd5)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://www.ixbt.com/storage/lsi-sas9211-8i.shtml
SWF URL: https://www.ixbt.com/storage/lsi-sas9211/atto.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-05-12
Channel: nightly
Built: 2021-05-12T00:13:11.225Z
Commit: ea4ea9922a031b49ac4cc9a593389f64b0042c9c

**Comment by tsunamistate** [comment]
@token0 could you please retry reproducing the error on latest Ruffle?
I can't reproduce it on 1dd669a0e37288af3acc786c6a924c579f4ec81b nightly 2021-05-19

Also updating graphics drivers might help

**Comment by token0** [comment]
OK, I have just nailed down the problem.
Manually set chrome://flags/#use-angle to D3D11 was the issue. (A new version of ruffle does not make difference)
Ruffle works after I reset that flag to default.
