### ISSUE TITLE
Error on https://www.i-gamer.net/play/11756.html

### ISSUE THREAD

**Issue by Ben980107** [ruffle-rs/ruffle#4357]
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', web/src/lib.rs:847:49
Error stack:
```
Error: panicked at 'already borrowed: BorrowMutError', web/src/lib.rs:847:49
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://www.i-gamer.net/play/ruffle/ruffle.js:1:6915)
    at wasm-function[1196]:183
    at wasm-function[1803]:675
    at wasm-function[5310]:67
    at wasm-function[4085]:222
    at wasm-function[4791]:159
    at wasm-function[5683]:40
    at wasm-function[5554]:89
    at wasm-function[5685]:48
    at wasm-function[4907]:123
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://www.i-gamer.net/play/11756.html
SWF URL: https://www.i-gamer.net/game638/flash4/6.2690_resort_cnu.swf

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-04-04
Channel: nightly
Built: 2021-04-04T00:42:01.875Z
Commit: e2f124ee34eb27c0f6463a76534b4936e750d58a

**Comment by Poopooracoocoo** [comment]
That version of Chrome is unsupported.

**Comment by Lord-McSweeney** [comment]
Closing as the site was using a version of Ruffle that is now 4 years outdated
