### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by ToughSun14** [ruffle-rs/ruffle#4425]
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', core/src/avm2/object/function_object.rs:280:5
Error stack:
```
Error: panicked at 'already borrowed: BorrowMutError', core/src/avm2/object/function_object.rs:280:5
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://uploads.ungrounded.net/ruffle_wrapper/lib/ruffle.js?1621891360:1:7026)
    at std::sync::once::Once::call_once::{{closure}}::h6e694fc45f651103 (https://uploads.ungrounded.net/ruffle_wrapper/lib/ae45875d0030f6d51176.wasm:wasm-function[1073]:0x2825f8)
    at std::sync::once::Once::call_inner::h99e47643887ee5a5 (https://uploads.ungrounded.net/ruffle_wrapper/lib/ae45875d0030f6d51176.wasm:wasm-function[947]:0x25b1e0)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hb552ca3003b47989 (https://uploads.ungrounded.net/ruffle_wrapper/lib/ae45875d0030f6d51176.wasm:wasm-function[3826]:0x406bfa)
    at std::panicking::rust_panic_with_hook::h03201bc01a0ed891 (https://uploads.ungrounded.net/ruffle_wrapper/lib/ae45875d0030f6d51176.wasm:wasm-function[2974]:0x3a7968)
    at rust_begin_unwind (https://uploads.ungrounded.net/ruffle_wrapper/lib/ae45875d0030f6d51176.wasm:wasm-function[4034]:0x40c724)
    at core::panicking::panic_fmt::hd44f353696296fec (https://uploads.ungrounded.net/ruffle_wrapper/lib/ae45875d0030f6d51176.wasm:wasm-function[4182]:0x4131b4)
    at core::option::expect_none_failed::hf7dab2706f1a5551 (https://uploads.ungrounded.net/ruffle_wrapper/lib/ae45875d0030f6d51176.wasm:wasm-function[3410]:0x3f4f4f)
    at <ruffle_core::avm2::object::function_object::FunctionObject as ruffle_core::avm2::object::TObject>::install_method::h367ff40b9f895d93 (https://uploads.ungrounded.net/ruffle_wrapper/lib/ae45875d0030f6d51176.wasm:wasm-function[1807]:0x328418)
    at ruffle_core::avm2::object::TObject::install_foreign_trait::h95c184e374f848f1 (https://uploads.ungrounded.net/ruffle_wrapper/lib/ae45875d0030f6d51176.wasm:wasm-function[321]:0x96cd5)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.64&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1621891360%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F557000%2F557775_N64.swf%3F1293651482%22%2C%22vars%22%3A%7B%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%2260ad0c5b6dab7%22%2C%22NewgroundsAPI_SessionID%22%3A%22p5RhJVOaiGSxjoHEp5S3ec76f31025ca415263792d9fca36fa0858caca16QWUQ%22%2C%22NewgroundsAPI_UserName%22%3A%22ToughSun14%22%2C%22NewgroundsAPI_UserID%22%3A5994475%2C%22ng_username%22%3A%22ToughSun14%22%7D%2C%22width%22%3A550%2C%22height%22%3A400%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F557000%2Fflash_557775.png%3Ff1364594270%22%7D
SWF URL: https://uploads.ungrounded.net/557000/557775_N64.swf?1293651482

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-05-24
Channel: nightly
Built: 2021-05-24T00:13:49.377Z
Commit: aa7dc503852999b2520206ac28bdbc27ba2a920a

**Comment by Poopooracoocoo** [comment]
SWF version of NiN10Doh: ToThe64thPower can now be found on Internet Archive: https://archive.org/details/nin10doh-tothe64thpower
