### ISSUE TITLE
Error on https://connectdot.connectsolutions.com/l8hl94rczl8/?refresh-parent=true

### ISSUE THREAD

**Issue by demeke-tech** [ruffle-rs/ruffle#4428]
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/gc-arena-0.2.0/src/gc_cell.rs:62:29
Error stack:
```
Error: panicked at 'already borrowed: BorrowMutError', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/gc-arena-0.2.0/src/gc_cell.rs:62:29
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (<anonymous>:3:6318)
    at std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f (chrome-extension://kajnfloacekelnfgckmnnkeeaajfkeja/dist/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[1265]:0x24e3c9)
    at std::sync::once::Once::call_inner::h02eac160d339afc2 (chrome-extension://kajnfloacekelnfgckmnnkeeaajfkeja/dist/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[1528]:0x27e7a0)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801 (chrome-extension://kajnfloacekelnfgckmnnkeeaajfkeja/dist/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[4309]:0x3537a0)
    at std::panicking::rust_panic_with_hook::h123718ba3bf480af (chrome-extension://kajnfloacekelnfgckmnnkeeaajfkeja/dist/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[3299]:0x32c417)
    at std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2 (chrome-extension://kajnfloacekelnfgckmnnkeeaajfkeja/dist/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[3916]:0x3495f5)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925 (chrome-extension://kajnfloacekelnfgckmnnkeeaajfkeja/dist/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[4655]:0x358eda)
    at rust_begin_unwind (chrome-extension://kajnfloacekelnfgckmnnkeeaajfkeja/dist/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[4526]:0x3574b8)
    at core::panicking::panic_fmt::h285dc015a87be5a4 (chrome-extension://kajnfloacekelnfgckmnnkeeaajfkeja/dist/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[4657]:0x358f3e)
    at core::option::expect_none_failed::hb95d2b1dc5448c17 (chrome-extension://kajnfloacekelnfgckmnnkeeaajfkeja/dist/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[3996]:0x34be07)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://connectdot.connectsolutions.com/l8hl94rczl8/?refresh-parent=true
SWF URL: https://connectdot.connectsolutions.com/l8hl94rczl8/default/viewer.swf?aicc_url=https%3A%2F%2Fconnectdot.connectsolutions.com%2Fservlet%2Fverify%3Fsco-id%3D1040471468%3B1313895506%26airspeed%3D1&aicc_sid=h55789itn4w5o2ugch9odsw8u8k49f99&airspeed=1%2Flmsproxy%3Fsco-id%3D1040471468%26link-transcript-id%3D1313895506%26sid%3Dh55789itn4w5o2ugch9odsw8u8k49f99%26qdata%3D&baseurl=%2Fl8hl94rczl8%2Fdefault%2F&plugin=plugin.swf&host=connectdot.connectsolutions.com&link-transcript-id=1313895506&path=%2Fl8hl94rczl8%2F&refresh-parent=true&reserved-license-id=1313886656&sco-id=1040480814&ticket=h55789itn4w5o2ugch9odsw8u8k49f99&transcript-id=1313895505&isLive=false&room=1040471468;session=breezbreez8ic7443o49m4ddzu&ticket=h55789itn4w5o2ugch9odsw8u8k49f99&proxy=false&appInstance=7/1030732548-2/output/&ott=oxfhp7sypg&css=airspeed&fcsContent=true&pbMode=normal&conStrings=rtmps%3A%2F%2Fdot-fms6.connectsolutions.com%3A443%2F%3Frtmp%3A%2F%2Flocalhost%3A8506%2F&connectors=iad-acts03.cosocloud.com,iad-acts05.cosocloud.com&connector_proto=wss:443&lang=en&account_id=7

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-25
Channel: nightly
Built: 2021-01-25T01:05:41.178Z
Commit: 32fd3fb71befbceecbba7c73d08af5ddd0f5a3d0

**Comment by Lord-McSweeney** [comment]
Closing as the site was using a version of Ruffle that is now 4 years outdated
