### ISSUE TITLE
Error on https://g.vseigru.net/7/flash/igra-razborki-s-byvshimi/

### ISSUE THREAD

**Issue by kellabre** [ruffle-rs/ruffle#4439]
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', web/src/lib.rs:832:49
Error stack:
```
Error: panicked at 'already borrowed: BorrowMutError', web/src/lib.rs:832:49
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://g.vseigru.net/lib/floader/index.min.js:1:16661)
    at std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f (wasm-function[1276]:168)
    at std::sync::once::Once::call_inner::h02eac160d339afc2 (wasm-function[1533]:675)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801 (wasm-function[4371]:67)
    at std::panicking::rust_panic_with_hook::h123718ba3bf480af (wasm-function[3312]:224)
    at std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2 (wasm-function[3929]:159)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925 (wasm-function[4705]:40)
    at rust_begin_unwind (wasm-function[4583]:89)
    at core::panicking::panic_fmt::h285dc015a87be5a4 (wasm-function[4707]:48)
    at core::option::expect_none_failed::hb95d2b1dc5448c17 (wasm-function[4012]:123)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://g.vseigru.net/7/flash/igra-razborki-s-byvshimi/
SWF URL: https://g.vseigru.net/7/flash/igra-razborki-s-byvshimi/igra-razborki-s-byvshimi.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.162 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-02-01
Channel: nightly
Built: 2021-02-01T00:36:59.488Z
Commit: d1fb36fbe2b31b9392d995ac67315aa02aee3fbc

**Comment by Lord-McSweeney** [comment]
Closing as the site was using a version of Ruffle that is now 4 years outdated
