### ISSUE TITLE
Error on https://astd.hentaisexpert.com/play.php?flash=undress

### ISSUE THREAD

**Issue by nogu01** [ruffle-rs/ruffle#4448]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/library.rs:291:46
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/library.rs:291:46
    at Object.U (https://astd.hentaisexpert.com/ruffle/core.ruffle.ab9406d542303de5ee9b.js:1:21277)
    at __wbg_new_df6e6ab7a65c4c4d (https://astd.hentaisexpert.com/ruffle/ruffle.js:1:38987)
    at std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f (https://astd.hentaisexpert.com/ruffle/14d80b2900ca11106a81.module.wasm:wasm-function[1288]:0x2636a1)
    at std::sync::once::Once::call_inner::h02eac160d339afc2 (https://astd.hentaisexpert.com/ruffle/14d80b2900ca11106a81.module.wasm:wasm-function[1539]:0x291d92)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801 (https://astd.hentaisexpert.com/ruffle/14d80b2900ca11106a81.module.wasm:wasm-function[4281]:0x3658db)
    at std::panicking::rust_panic_with_hook::h123718ba3bf480af (https://astd.hentaisexpert.com/ruffle/14d80b2900ca11106a81.module.wasm:wasm-function[3312]:0x34053c)
    at std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2 (https://astd.hentaisexpert.com/ruffle/14d80b2900ca11106a81.module.wasm:wasm-function[3889]:0x35b7fa)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925 (https://astd.hentaisexpert.com/ruffle/14d80b2900ca11106a81.module.wasm:wasm-function[4627]:0x36b02f)
    at rust_begin_unwind (https://astd.hentaisexpert.com/ruffle/14d80b2900ca11106a81.module.wasm:wasm-function[4500]:0x36966c)
    at core::panicking::panic_fmt::h285dc015a87be5a4 (https://astd.hentaisexpert.com/ruffle/14d80b2900ca11106a81.module.wasm:wasm-function[4629]:0x36b093)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://astd.hentaisexpert.com/play.php?flash=undress
SWF URL: https://astd.hentaisexpert.com/undress.swf

# Browser Info
Useragent: Mozilla/5.0 (Linux; Android 10; moto g(9) play) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Mobile Safari/537.36
OS: Linux armv8l

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-12
Channel: nightly
Built: 2021-01-12T00:55:17.048Z
Commit: 73d123091014e190f4bc4d8edf98cab2e671cc3a

**Comment by kjarosh** [comment]
Should be fixed as of today
