### ISSUE TITLE
Erro no https://www.jogos360.com.br/obaid.html

### ISSUE THREAD

**Issue by Thaipolar** [ruffle-rs/ruffle#4502]
#Puta que pariu caralhooo to toda me tremenu

# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: JsValue(InvalidStateError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
Error: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
    at https://www.jogos360.com.br/assets/ruffle.js:1:26863
    at https://www.jogos360.com.br/assets/ruffle.js:1:4463
    at web_sys::features::gen_CanvasRenderingContext2d::CanvasRenderingContext2d::draw_image_with_html_canvas_element::h6f0eaf17aa6f7dc8 (https://www.jogos360.com.br/assets/349d49a671de87a3e810.wasm:wasm-function[3835]:0x44e317)
    at <ruffle_render_canvas::WebCanvasRenderBackend as ruffle_core::backend::render::RenderBackend>::pop_mask::ha6a53f4d027e5730 (https://www.jogos360.com.br/assets/349d49a671de87a3e810.wasm:wasm-function[828]:0x2435bc)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render_self::h40793588fb3d0a97 (https://www.jogos360.com.br/assets/349d49a671de87a3e810.wasm:wasm-function[2309]:0x38035e)
    at ruffle_core::display_object::render_base::h391e689ac24f381b (https://www.jogos360.com.br/assets/349d49a671de87a3e810.wasm:wasm-function[1582]:0x30b89e)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render::h9cead5fa694da17f (https://www.jogos360.com.br/assets/349d49a671de87a3e810.wasm:wasm-function[3300]:0x3d8dfd)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render_self::h40793588fb3d0a97 (https://www.jogos360.com.br/assets/349d49a671de87a3e810.wasm:wasm-function[2309]:0x3804c2)
    at ruffle_core::display_object::render_base::h391e689ac24f381b (https://www.jogos360.com.br/assets/349d49a671de87a3e810.wasm:wasm-function[1582]:0x30b89e)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render::h9cead5fa694da17f (https://www.jogos360.com.br/assets/349d49a671de87a3e810.wasm:wasm-function[3300]:0x3d8dfd))', render/canvas/src/lib.rs:682:14

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.jogos360.com.br/obaid.html
SWF URL: https://cdn.jogos360.com.br/files/games/ob/ai/obaid.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36 Edg/91.0.864.37
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-05-03
Channel: nightly
Built: 2021-05-03T00:12:09.006Z
Commit: f2256a661be22fd12ae1ec3b40574d7cca670a27

**Comment by relrelb** [comment]
Fixed by #7026.
