### ISSUE TITLE
Error on https://careers.un.org/lbw/media/jobapplication/en-US/index.htm

### ISSUE THREAD

**Issue by why-4218280** [ruffle-rs/ruffle#4527]
# Error Info
Error name: Error
Error message: panicked at 'No script object for display object', core/src/avm1/activation.rs:409:18
Error stack:
```
Error: panicked at 'No script object for display object', core/src/avm1/activation.rs:409:18
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (<anonymous>:3:6318)
    at std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f (chrome-extension://kajnfloacekelnfgckmnnkeeaajfkeja/dist/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[1265]:0x24e3c9)
    at std::sync::once::Once::call_inner::h02eac160d339afc2 (chrome-extension://kajnfloacekelnfgckmnnkeeaajfkeja/dist/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[1528]:0x27e7a0)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801 (chrome-extension://kajnfloacekelnfgckmnnkeeaajfkeja/dist/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[4309]:0x3537a0)
    at std::panicking::rust_panic_with_hook::h123718ba3bf480af (chrome-extension://kajnfloacekelnfgckmnnkeeaajfkeja/dist/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[3299]:0x32c417)
    at std::panicking::begin_panic::{{closure}}::h056d8f376f71d86d (chrome-extension://kajnfloacekelnfgckmnnkeeaajfkeja/dist/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[4693]:0x359505)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h2a23366d4ea70d1b (chrome-extension://kajnfloacekelnfgckmnnkeeaajfkeja/dist/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[4635]:0x358b4f)
    at std::panicking::begin_panic::h93180c743f3529ea (chrome-extension://kajnfloacekelnfgckmnnkeeaajfkeja/dist/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[4695]:0x359556)
    at ruffle_core::avm1::activation::Activation::run_with_child_frame_for_display_object::hfccf087e8db38b36 (chrome-extension://kajnfloacekelnfgckmnnkeeaajfkeja/dist/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[742]:0x1bb7c2)
    at ruffle_core::display_object::edit_text::EditText::try_bind_text_field_variable::h72a339f3832040a6 (chrome-extension://kajnfloacekelnfgckmnnkeeaajfkeja/dist/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[2101]:0x2cb5a4)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: UN_Careers_Personal_History_Profile_Jan13_2013_Medium_quality.swf
Param menu: false
Param quality: high
Param wmode: window
Param bgcolor: #f5f4f1
Param flashvars: variable1=value1
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined

# Page Info
Page URL: https://careers.un.org/lbw/media/jobapplication/en-US/index.htm
SWF URL: https://careers.un.org/lbw/media/jobapplication/en-US/UN_Careers_Personal_History_Profile_Jan13_2013_Medium_quality.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-25
Channel: nightly
Built: 2021-01-25T01:05:41.178Z
Commit: 32fd3fb71befbceecbba7c73d08af5ddd0f5a3d0

**Comment by n0samu** [comment]
A lot of new errors now:
```
ERROR run_frame:run_all_phases_avm2: ruffle_core::display_object::movie_clip: Got "RustError("XML.appendChild is not yet implemented for XmlListObject(XmlListObject { ptr: 0x12034251990 })")" when constructing AVM2 side of movie clip of type captivate.veela_as3::CaptivateMainTimeline
WARN run_frame: ruffle_core::library: Tried to overwrite class ClassObject { name: captivate.veela_as3::rdItem, ptr: 0x120382510b0 } id=85 with symbol id=88 from same movie
ERROR run_frame: ruffle_core::tag_utils: Error running definition tag: DefineBitsJpeg3, got Couldn't register bitmap
ERROR run_frame:run_all_phases_avm2: ruffle_core::display_object::movie_clip: Error occured when running AVM2 frame script: TypeError: Error #1009: Cannot access a property or method of a null object reference. (accessing field: slideLoaded)
        at captivate.veela_as3::rdSlide/onSlideLoad()
        at captivate.veela_as3::rdSlide/frame1()
ERROR run_frame:run_all_phases_avm2: ruffle_core::display_object::movie_clip: Error occured when running AVM2 frame script: TypeError: Error #1009: Cannot access a property or method of a null object reference. (accessing field: m_ItemtoInitialVisibilityMap)
        at captivate.veela_as3::rdItem/SetInitialVisibilityifStatic()
        at captivate.veela_as3::rdItem/initBasicVariables()
        at captivate.veela_as3::rdItem/initItemVariables()
        at captivate.veela_as3::rdItem/frame1()
ERROR run_frame:run_all_phases_avm2: ruffle_core::display_object::movie_clip: Error occured when running AVM2 frame script: TypeError: Error #1009: Cannot access a property or method of a null object reference. (accessing field: m_movie_mc)
        at captivate.veela_as3::rdButton/initItemVariables()
        at captivate.veela_as3::rdItem/frame1()
```
(This is just a sampling of them but I think it covers the major types)

**Comment by Lord-McSweeney** [comment]
This seems to be working now
