### ISSUE TITLE
Error on http://powerpets.com/games/gameScreen.asp?gameid=49&section=6&nocache=58036

### ISSUE THREAD

**Issue by mmmb0p** [ruffle-rs/ruffle#4561]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/library.rs:359:46
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/library.rs:359:46
    at Object.J (http://powerpets.com/script/ruffle/core.ruffle.0197a207ce1d77ef54e9.js:1:21286)
    at __wbg_new_df6e6ab7a65c4c4d (http://powerpets.com/script/ruffle/ruffle.js:1:38978)
    at std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f (http://powerpets.com/script/ruffle/a19bc719b8c007cbc2f4.module.wasm:wasm-function[1280]:0x264d71)
    at std::sync::once::Once::call_inner::h02eac160d339afc2 (http://powerpets.com/script/ruffle/a19bc719b8c007cbc2f4.module.wasm:wasm-function[1548]:0x295c9c)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801 (http://powerpets.com/script/ruffle/a19bc719b8c007cbc2f4.module.wasm:wasm-function[4312]:0x369bc1)
    at std::panicking::rust_panic_with_hook::h123718ba3bf480af (http://powerpets.com/script/ruffle/a19bc719b8c007cbc2f4.module.wasm:wasm-function[3310]:0x342e79)
    at std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2 (http://powerpets.com/script/ruffle/a19bc719b8c007cbc2f4.module.wasm:wasm-function[3919]:0x35f9c0)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925 (http://powerpets.com/script/ruffle/a19bc719b8c007cbc2f4.module.wasm:wasm-function[4655]:0x36f25b)
    at rust_begin_unwind (http://powerpets.com/script/ruffle/a19bc719b8c007cbc2f4.module.wasm:wasm-function[4529]:0x36d8db)
    at core::panicking::panic_fmt::h285dc015a87be5a4 (http://powerpets.com/script/ruffle/a19bc719b8c007cbc2f4.module.wasm:wasm-function[4657]:0x36f2bf)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: http://images.powerpets.com/games/additionmissionv1.swf?memberCode=0&uid=604454&gender=w
Param allowfullscreen: true
Param allowscriptaccess: always
Param quality: high
Param wmode: direct
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined

# Page Info
Page URL: http://powerpets.com/games/gameScreen.asp?gameid=49&section=6&nocache=58036
SWF URL: http://images.powerpets.com/games/additionmissionv1.swf?memberCode=0&uid=604454&gender=w

# Browser Info
Useragent: Mozilla/5.0 (Linux; Android 11; SM-N986U) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Mobile Safari/537.36
OS: Linux aarch64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-16
Channel: nightly
Built: 2021-01-16T01:09:33.302Z
Commit: 9df7facdb8d37a5d007a13c25efcc176ed4675e0

**Comment by n0samu** [comment]
Seems like the website has been taken down and was not archived :(
