### ISSUE TITLE
Error on https://collegesexgames.com/play.php?flash=window-girl

### ISSUE THREAD

**Issue by ptjd** [ruffle-rs/ruffle#4566]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/library.rs:291:46
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/library.rs:291:46
    at Object.U (https://collegesexgames.com/ruffle/core.ruffle.ab9406d542303de5ee9b.js:1:21277)
    at __wbg_new_df6e6ab7a65c4c4d (https://collegesexgames.com/ruffle/ruffle.js:1:38987)
    at std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f (https://collegesexgames.com/ruffle/14d80b2900ca11106a81.module.wasm:wasm-function[1288]:0x2636a1)
    at std::sync::once::Once::call_inner::h02eac160d339afc2 (https://collegesexgames.com/ruffle/14d80b2900ca11106a81.module.wasm:wasm-function[1539]:0x291d92)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801 (https://collegesexgames.com/ruffle/14d80b2900ca11106a81.module.wasm:wasm-function[4281]:0x3658db)
    at std::panicking::rust_panic_with_hook::h123718ba3bf480af (https://collegesexgames.com/ruffle/14d80b2900ca11106a81.module.wasm:wasm-function[3312]:0x34053c)
    at std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2 (https://collegesexgames.com/ruffle/14d80b2900ca11106a81.module.wasm:wasm-function[3889]:0x35b7fa)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925 (https://collegesexgames.com/ruffle/14d80b2900ca11106a81.module.wasm:wasm-function[4627]:0x36b02f)
    at rust_begin_unwind (https://collegesexgames.com/ruffle/14d80b2900ca11106a81.module.wasm:wasm-function[4500]:0x36966c)
    at core::panicking::panic_fmt::h285dc015a87be5a4 (https://collegesexgames.com/ruffle/14d80b2900ca11106a81.module.wasm:wasm-function[4629]:0x36b093)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://collegesexgames.com/play.php?flash=window-girl
SWF URL: https://collegesexgames.com/swf/window-girl.swf

# Browser Info
Useragent: Mozilla/5.0 (Linux; Android 11; SHG03) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.88 Mobile Safari/537.36
OS: Linux armv8l

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-12
Channel: nightly
Built: 2021-01-12T00:55:17.048Z
Commit: 73d123091014e190f4bc4d8edf98cab2e671cc3a

**Comment by jhwgh1968** [comment]
Tried this with commit 6146502b1a427bd83b8073f26662abb5959da2b2 on desktop. Seems to generally work okay, and I could not reproduce the issue.

I did see one error message on the console, though:

```
[2021-06-26T04:05:26Z ERROR ruffle_core::display_object::movie_clip] Unable to instantiate display node id 1626, reason being: Not a DisplayObject
```

**Comment by kjarosh** [comment]
Should be fixed as of today
