### ISSUE TITLE
Error on https://gaymes.net/manful-the-it-technician/

### ISSUE THREAD

**Issue by Kizune2231** [ruffle-rs/ruffle#4589]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/library.rs:359:46
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/library.rs:359:46
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://gaymes.net/wp-content/themes/gameking/ruffle/ruffle.js:1:6333)
    at std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f (<anonymous>:wasm-function[1280]:0x263ca7)
    at std::sync::once::Once::call_inner::h02eac160d339afc2 (<anonymous>:wasm-function[1548]:0x294bd2)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801 (<anonymous>:wasm-function[4312]:0x368af7)
    at std::panicking::rust_panic_with_hook::h123718ba3bf480af (<anonymous>:wasm-function[3310]:0x341daf)
    at std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2 (<anonymous>:wasm-function[3919]:0x35e8f6)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925 (<anonymous>:wasm-function[4655]:0x36e191)
    at rust_begin_unwind (<anonymous>:wasm-function[4529]:0x36c811)
    at core::panicking::panic_fmt::h285dc015a87be5a4 (<anonymous>:wasm-function[4657]:0x36e1f5)
    at core::panicking::panic::h0abe4e7a620ae568 (<anonymous>:wasm-function[4464]:0x36b714)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://gaymes.net/manful-the-it-technician/
SWF URL: https://gaymes.net/wp-content/uploads/games/custom/H/Humplex-Manful-The-IT-Technician.swf

# Browser Info
Useragent: Mozilla/5.0 (Linux; Android 11; SM-A525F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.88 Mobile Safari/537.36
OS: Linux armv8l

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-17
Channel: nightly
Built: 2021-01-17T01:05:59.152Z
Commit: c2b768c453f281a988c71a829e7a71bb106302fa

**Comment by torokati44** [comment]
Different SWF, but exact same issue as #4588.
