### ISSUE TITLE
Error on https://www.comdotgame.com/play/qwop?ruffle

### ISSUE THREAD

**Issue by Bright9000** [ruffle-rs/ruffle#4608]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/library.rs:359:46
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/library.rs:359:46
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://echo.comdotgame.com/ruffle/ruffle.js?1:1:6392)
    at std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f (<anonymous>:wasm-function[1276]:0x25acf1)
    at std::sync::once::Once::call_inner::h02eac160d339afc2 (<anonymous>:wasm-function[1533]:0x289f4e)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801 (<anonymous>:wasm-function[4371]:0x36167b)
    at std::panicking::rust_panic_with_hook::h123718ba3bf480af (<anonymous>:wasm-function[3312]:0x338d3c)
    at std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2 (<anonymous>:wasm-function[3929]:0x35600d)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925 (<anonymous>:wasm-function[4705]:0x3669fe)
    at rust_begin_unwind (<anonymous>:wasm-function[4583]:0x3651a1)
    at core::panicking::panic_fmt::h285dc015a87be5a4 (<anonymous>:wasm-function[4707]:0x366a62)
    at core::panicking::panic::h0abe4e7a620ae568 (<anonymous>:wasm-function[4517]:0x36409e)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: https://echo.comdotgame.com/4x90xhl3k0/games/files/002049c78239667b279c9367c4e3b2d4.swf
Param allowscriptaccess: always
Param bgcolor: ffffff
Param wmode: gpu
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined
Attribute 6: undefined

# Page Info
Page URL: https://www.comdotgame.com/play/qwop?ruffle
SWF URL: https://echo.comdotgame.com/4x90xhl3k0/games/files/002049c78239667b279c9367c4e3b2d4.swf

# Browser Info
Useragent: Mozilla/5.0 (Linux; Android 11; SM-G981V) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Mobile Safari/537.36
OS: Linux aarch64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-02-01
Channel: nightly
Built: 2021-02-01T00:36:59.488Z
Commit: d1fb36fbe2b31b9392d995ac67315aa02aee3fbc

**Comment by kjarosh** [comment]
Should be fixed as of today
