### ISSUE TITLE
Error on https://girlsgames.su/zabota/190-fabrika-malyshej.html

### ISSUE THREAD

**Issue by BelkaKwipi** [ruffle-rs/ruffle#4716]
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', web/src/lib.rs:613:42
Error stack:
```
Error: panicked at 'already borrowed: BorrowMutError', web/src/lib.rs:613:42
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://girlsgames.su/template/js/ruffle.js:1:6940)
    at std::sync::once::Once::call_once::{{closure}}::h098c4530511c1407 (https://girlsgames.su/template/js/e80928e7593a6b28a58cd8e4c670b73c.wasm:wasm-function[819]:0x220527)
    at std::sync::once::Once::call_inner::hf7fd718057964857 (https://girlsgames.su/template/js/e80928e7593a6b28a58cd8e4c670b73c.wasm:wasm-function[1216]:0x2a379a)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h6c44fc25588b0f32 (https://girlsgames.su/template/js/e80928e7593a6b28a58cd8e4c670b73c.wasm:wasm-function[3681]:0x42d20d)
    at std::panicking::rust_panic_with_hook::h9d91fa0fae16500f (https://girlsgames.su/template/js/e80928e7593a6b28a58cd8e4c670b73c.wasm:wasm-function[2675]:0x391f22)
    at rust_begin_unwind (https://girlsgames.su/template/js/e80928e7593a6b28a58cd8e4c670b73c.wasm:wasm-function[3883]:0x432bf8)
    at core::panicking::panic_fmt::h91d2023e5afe1929 (https://girlsgames.su/template/js/e80928e7593a6b28a58cd8e4c670b73c.wasm:wasm-function[3991]:0x43599b)
    at core::option::expect_none_failed::h203584ddbc785ca2 (https://girlsgames.su/template/js/e80928e7593a6b28a58cd8e4c670b73c.wasm:wasm-function[3311]:0x41e07a)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::hbbcc364c4cbd1c61 (https://girlsgames.su/template/js/e80928e7593a6b28a58cd8e4c670b73c.wasm:wasm-function[2322]:0x377322)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h595933476ce8a839 (https://girlsgames.su/template/js/e80928e7593a6b28a58cd8e4c670b73c.wasm:wasm-function[4124]:0x437acd)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: /games/1/fabrika-malyshej.swf
Param movie: /games/1/fabrika-malyshej.swf
Param quality: high
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined

# Page Info
Page URL: https://girlsgames.su/zabota/190-fabrika-malyshej.html
SWF URL: https://girlsgames.su/games/1/fabrika-malyshej.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-04-22
Channel: nightly
Built: 2021-04-22T00:15:37.772Z
Commit: 8176e0a6336f43a1212a0cd843c02fd56fc2b652

**Comment by Lord-McSweeney** [comment]
Closing as the site was using a version of Ruffle that is now 4 years outdated
