### ISSUE TITLE
Error on http://www.giercownia.pl/gra/5952/bubble_struggle_2/

### ISSUE THREAD

**Issue by rwitczyk** [ruffle-rs/ruffle#4749]
# Error Info
Error name: Error
Error message: panicked at 'range end index 2 out of range for slice of length 1', core/src/avm1/globals/movie_clip.rs:614:45
Error stack:
```
Error: panicked at 'range end index 2 out of range for slice of length 1', core/src/avm1/globals/movie_clip.rs:614:45
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (http://www.giercownia.pl/public/js/ruffle/ruffle.js:1:6799)
    at std::sync::once::Once::call_once::{{closure}}::hce6501f6f20767e4 (http://www.giercownia.pl/public/js/ruffle/4d640ad5aa95d1360f7c8c38e9c8b0d8.wasm:wasm-function[1327]:0x26ba91)
    at std::sync::once::Once::call_inner::hd3d269a4946f2df2 (http://www.giercownia.pl/public/js/ruffle/4d640ad5aa95d1360f7c8c38e9c8b0d8.wasm:wasm-function[1604]:0x29efac)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h6ed7686ed76cb258 (http://www.giercownia.pl/public/js/ruffle/4d640ad5aa95d1360f7c8c38e9c8b0d8.wasm:wasm-function[4639]:0x3823e3)
    at std::panicking::rust_panic_with_hook::h4f753dc70b771d8e (http://www.giercownia.pl/public/js/ruffle/4d640ad5aa95d1360f7c8c38e9c8b0d8.wasm:wasm-function[3509]:0x357cb7)
    at std::panicking::begin_panic_handler::{{closure}}::h5c9fc29957309ae8 (http://www.giercownia.pl/public/js/ruffle/4d640ad5aa95d1360f7c8c38e9c8b0d8.wasm:wasm-function[4146]:0x37594f)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h92808941d97e9b21 (http://www.giercownia.pl/public/js/ruffle/4d640ad5aa95d1360f7c8c38e9c8b0d8.wasm:wasm-function[4985]:0x387ab4)
    at rust_begin_unwind (http://www.giercownia.pl/public/js/ruffle/4d640ad5aa95d1360f7c8c38e9c8b0d8.wasm:wasm-function[4870]:0x3863b1)
    at core::panicking::panic_fmt::hbd8a975261a5f466 (http://www.giercownia.pl/public/js/ruffle/4d640ad5aa95d1360f7c8c38e9c8b0d8.wasm:wasm-function[4986]:0x387aea)
    at core::slice::index::slice_end_index_len_fail::h137fe51578ce6a78 (http://www.giercownia.pl/public/js/ruffle/4d640ad5aa95d1360f7c8c38e9c8b0d8.wasm:wasm-function[4367]:0x37c018)
```

# Player Info
Allows script access: false

# Page Info
Page URL: http://www.giercownia.pl/gra/5952/bubble_struggle_2/
SWF URL: http://gry.giercownia.pl/gry/b/1193044120_bubble_struggle_2.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-02-14
Channel: nightly
Built: 2021-02-14T00:19:03.523Z
Commit: ecd873eb39c141f9bf2e41454c7a47d5f7e9507c

**Comment by danielhjacobs** [comment]
Fixed by #3447. Try updating your extension to the [latest release](https://ruffle.rs/#downloads).
