### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html this is problem help us there is issues

### ISSUE THREAD

**Issue by deividbinev12** [ruffle-rs/ruffle#4768]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:858:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:858:18
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://uploads.ungrounded.net/ruffle_wrapper/lib/ruffle.js?1625243018:1:7026)
    at std::sync::once::Once::call_once::{{closure}}::he57af21d1247c45f (https://uploads.ungrounded.net/ruffle_wrapper/lib/d0db97dbd42aad5e218a.wasm:wasm-function[1001]:0x27781d)
    at std::sync::once::Once::call_inner::h79faa41f4d270a0b (https://uploads.ungrounded.net/ruffle_wrapper/lib/d0db97dbd42aad5e218a.wasm:wasm-function[967]:0x26d288)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h38cf076358a63666 (https://uploads.ungrounded.net/ruffle_wrapper/lib/d0db97dbd42aad5e218a.wasm:wasm-function[3869]:0x41ac56)
    at std::panicking::rust_panic_with_hook::hbdbceb5cd158bf19 (https://uploads.ungrounded.net/ruffle_wrapper/lib/d0db97dbd42aad5e218a.wasm:wasm-function[2993]:0x3b93e5)
    at rust_begin_unwind (https://uploads.ungrounded.net/ruffle_wrapper/lib/d0db97dbd42aad5e218a.wasm:wasm-function[4079]:0x420578)
    at core::panicking::panic_fmt::h3ab5417155b7ba3b (https://uploads.ungrounded.net/ruffle_wrapper/lib/d0db97dbd42aad5e218a.wasm:wasm-function[4229]:0x427344)
    at core::panicking::panic::h5bfdfaa3db9a4b4a (https://uploads.ungrounded.net/ruffle_wrapper/lib/d0db97dbd42aad5e218a.wasm:wasm-function[4023]:0x41dcfa)
    at core::ops::function::FnOnce::call_once::h54a4376cf11af2c5 (https://uploads.ungrounded.net/ruffle_wrapper/lib/d0db97dbd42aad5e218a.wasm:wasm-function[860]:0x24a50d)
    at ruffle_core::avm1::function::Executable::exec::h8e7357a0bef754eb (https://uploads.ungrounded.net/ruffle_wrapper/lib/d0db97dbd42aad5e218a.wasm:wasm-function[360]:0xd00e3)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.64&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1625243018%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F484000%2F484931_peeps.swf%3F1509024282%22%2C%22vars%22%3A%7B%22ngio_session_id%22%3A%2286328819.62504ed0f41e06050c061cde6f1c658aca031a84bb6281%22%2C%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%2260e14f0de52d1%22%2C%22NewgroundsAPI_SessionID%22%3A%22IdyCsr2VLhCO4ggl6H2nd107a9353c63bded8d8139ce646750c4dc89213fU6TW%22%2C%22NewgroundsAPI_UserName%22%3A%22deivid-Binev%22%2C%22NewgroundsAPI_UserID%22%3A7016168%2C%22ng_username%22%3A%22deivid-Binev%22%7D%2C%22width%22%3A640%2C%22height%22%3A450%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F484000%2Fflash_484931_card.png%3Ff1609851325%22%7D
SWF URL: https://uploads.ungrounded.net/484000/484931_peeps.swf?1509024282

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-07-02
Channel: nightly
Built: 2021-07-02T00:10:16.343Z
Commit: 7ba7cce5c46a47fa52da52aa79f80dc7d74e4a5

There is Problem Game Ruffles
https://www.newgrounds.com/portal/view/484931
go fix please

**Comment by Poopooracoocoo** [comment]
Portal Defenders

**Comment by dginovker** [comment]
Works on 0.1.0.544
