### ISSUE TITLE
Error on http://www.powerpets.com/games/gameScreen.asp?gameid=33&section=6&nocache=29170

### ISSUE THREAD

**Issue by Kaz1969** [ruffle-rs/ruffle#4787]
# Error Info
Error name: Error
Error message: panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`: cannot recursively acquire mutex', /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys/wasm/../unsupported/mutex.rs:23:9
Error stack:
```
Error: panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`: cannot recursively acquire mutex', /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys/wasm/../unsupported/mutex.rs:23:9
    at Object.J (http://www.powerpets.com/script/ruffle/core.ruffle.0197a207ce1d77ef54e9.js:1:21286)
    at __wbg_new_df6e6ab7a65c4c4d (http://www.powerpets.com/script/ruffle/ruffle.js:1:38978)
    at std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f (http://www.powerpets.com/script/ruffle/a19bc719b8c007cbc2f4.module.wasm:wasm-function[1280]:0x264d71)
    at std::sync::once::Once::call_inner::h02eac160d339afc2 (http://www.powerpets.com/script/ruffle/a19bc719b8c007cbc2f4.module.wasm:wasm-function[1548]:0x295c9c)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801 (http://www.powerpets.com/script/ruffle/a19bc719b8c007cbc2f4.module.wasm:wasm-function[4312]:0x369bc1)
    at std::panicking::rust_panic_with_hook::h123718ba3bf480af (http://www.powerpets.com/script/ruffle/a19bc719b8c007cbc2f4.module.wasm:wasm-function[3310]:0x342e79)
    at std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2 (http://www.powerpets.com/script/ruffle/a19bc719b8c007cbc2f4.module.wasm:wasm-function[3919]:0x35f9e7)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925 (http://www.powerpets.com/script/ruffle/a19bc719b8c007cbc2f4.module.wasm:wasm-function[4655]:0x36f25b)
    at rust_begin_unwind (http://www.powerpets.com/script/ruffle/a19bc719b8c007cbc2f4.module.wasm:wasm-function[4529]:0x36d8db)
    at std::panicking::begin_panic_fmt::h96153d9dc0e882ed (http://www.powerpets.com/script/ruffle/a19bc719b8c007cbc2f4.module.wasm:wasm-function[4625]:0x36ed04)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: http://images.powerpets.com/games/badgerblast_v2_6.swf?memberCode=1&uid=791941&gender=w
Param allowfullscreen: true
Param allowscriptaccess: always
Param quality: high
Param wmode: direct
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined

# Page Info
Page URL: http://www.powerpets.com/games/gameScreen.asp?gameid=33&section=6&nocache=29170
SWF URL: http://images.powerpets.com/games/badgerblast_v2_6.swf?memberCode=1&uid=791941&gender=w

# Browser Info
Useragent: Mozilla/5.0 (Linux; Android 8.0.0; SM-G935F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.120 Mobile Safari/537.36
OS: Linux armv8l

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-16
Channel: nightly
Built: 2021-01-16T01:09:33.302Z
Commit: 9df7facdb8d37a5d007a13c25efcc176ed4675e0

**Comment by Lord-McSweeney** [comment]
Closing as the SWF was run with a version of Ruffle that is now five years outdated
