### ISSUE TITLE
Error on https://g.vseigru.net/14/igra-pdd-ocherednost-proezda-perekrestka/

### ISSUE THREAD

**Issue by alexanderuz** [ruffle-rs/ruffle#4835]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:490:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:490:50
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://g.vseigru.net/lib/floader/index.min.js:1:16661)
    at std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f (<anonymous>:wasm-function[1276]:0x25acf1)
    at std::sync::once::Once::call_inner::h02eac160d339afc2 (<anonymous>:wasm-function[1533]:0x289f4e)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801 (<anonymous>:wasm-function[4371]:0x36167b)
    at std::panicking::rust_panic_with_hook::h123718ba3bf480af (<anonymous>:wasm-function[3312]:0x338d3c)
    at std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2 (<anonymous>:wasm-function[3929]:0x356034)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925 (<anonymous>:wasm-function[4705]:0x3669fe)
    at rust_begin_unwind (<anonymous>:wasm-function[4583]:0x3651a1)
    at core::panicking::panic_fmt::h285dc015a87be5a4 (<anonymous>:wasm-function[4707]:0x366a62)
    at core::option::expect_none_failed::hb95d2b1dc5448c17 (<anonymous>:wasm-function[4012]:0x358a52)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://g.vseigru.net/14/igra-pdd-ocherednost-proezda-perekrestka/
SWF URL: https://g.vseigru.net/14/igra-pdd-ocherednost-proezda-perekrestka/igra-pdd-ocherednost-proezda-perekrestka.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-02-01
Channel: nightly
Built: 2021-02-01T00:36:59.488Z
Commit: d1fb36fbe2b31b9392d995ac67315aa02aee3fbc

**Comment by jhwgh1968** [comment]
This seems to work on ruffle desktop commit 3982f3af9811cfc32c6f7eaf06aa3c8c81b91226. If the site owner upgraded their ruffle version, that might solve it.
