### ISSUE TITLE
Error on https://ruffle.rs/demo/

### ISSUE THREAD

**Issue by TheRealOhead** [ruffle-rs/ruffle#4848]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object.rs:1214:34
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object.rs:1214:34
    at t.wbg.__wbg_new_df6e6ab7a65c4c4d (https://ruffle.rs/demo/index.js:1:17613)
    at std::sync::once::Once::call_once::{{closure}}::h5df181b90ad904c1 (https://ruffle.rs/demo/48b82e3e152a1a91a62f.wasm:wasm-function[1008]:0x27f05e)
    at std::sync::once::Once::call_inner::h79faa41f4d270a0b (https://ruffle.rs/demo/48b82e3e152a1a91a62f.wasm:wasm-function[974]:0x274b00)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hbd170ba35c598204 (https://ruffle.rs/demo/48b82e3e152a1a91a62f.wasm:wasm-function[3882]:0x421769)
    at std::panicking::rust_panic_with_hook::hbdbceb5cd158bf19 (https://ruffle.rs/demo/48b82e3e152a1a91a62f.wasm:wasm-function[2999]:0x3c00dc)
    at rust_begin_unwind (https://ruffle.rs/demo/48b82e3e152a1a91a62f.wasm:wasm-function[4094]:0x427111)
    at core::panicking::panic_fmt::h3ab5417155b7ba3b (https://ruffle.rs/demo/48b82e3e152a1a91a62f.wasm:wasm-function[4244]:0x42dee4)
    at core::panicking::panic::h5bfdfaa3db9a4b4a (https://ruffle.rs/demo/48b82e3e152a1a91a62f.wasm:wasm-function[4036]:0x424814)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::construct_frame::h1180b1759458e5b5 (https://ruffle.rs/demo/48b82e3e152a1a91a62f.wasm:wasm-function[3731]:0x41c599)
    at <ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::construct_frame::hc559f3b35f0e429b (https://ruffle.rs/demo/48b82e3e152a1a91a62f.wasm:wasm-function[382]:0xe9d3d)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://ruffle.rs/demo/

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-07-13
Channel: nightly
Built: 2021-07-13T00:11:20.184Z
Commit: c241ac6ace6bcb9d86e836caeb30b5035937dd4d

I tried to play Run 1 :|

**Comment by Poopooracoocoo** [comment]
Got a link to the SWF?

Did it panic instantly or after a certain action?
