### ISSUE TITLE
Error on https://playsexgames.xxx/busting-a-nun/

### ISSUE THREAD

**Issue by Vietnamvo** [ruffle-rs/ruffle#4880]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/library.rs:450:46
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/library.rs:450:46
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://playsexgames.xxx/html/ruffle.js:1:7026)
    at std::sync::once::Once::call_once::{{closure}}::h098c4530511c1407 (https://playsexgames.xxx/html/d6dd295efb44ba365d0d.wasm:wasm-function[1028]:0x2759ad)
    at std::sync::once::Once::call_inner::hf7fd718057964857 (https://playsexgames.xxx/html/d6dd295efb44ba365d0d.wasm:wasm-function[1233]:0x2a5afa)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h6c44fc25588b0f32 (https://playsexgames.xxx/html/d6dd295efb44ba365d0d.wasm:wasm-function[3718]:0x443b09)
    at std::panicking::rust_panic_with_hook::h9d91fa0fae16500f (https://playsexgames.xxx/html/d6dd295efb44ba365d0d.wasm:wasm-function[2709]:0x394d06)
    at rust_begin_unwind (https://playsexgames.xxx/html/d6dd295efb44ba365d0d.wasm:wasm-function[3923]:0x4493b4)
    at core::panicking::panic_fmt::h91d2023e5afe1929 (https://playsexgames.xxx/html/d6dd295efb44ba365d0d.wasm:wasm-function[4064]:0x44fed2)
    at core::panicking::panic::h5da66f104e83c46a (https://playsexgames.xxx/html/d6dd295efb44ba365d0d.wasm:wasm-function[3864]:0x44708a)
    at ruffle_core::library::Library::library_for_movie_mut::h43c5e4bfcf830365 (https://playsexgames.xxx/html/d6dd295efb44ba365d0d.wasm:wasm-function[678]:0x1dbea4)
    at ruffle_core::player::Player::set_root_movie::hf9bbdab424c9270e (https://playsexgames.xxx/html/d6dd295efb44ba365d0d.wasm:wasm-function[333]:0xaab78)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://playsexgames.xxx/busting-a-nun/
SWF URL: https://playsexgames.xxx/play-sex-games/bustin_a_nun.swf

# Browser Info
Useragent: Mozilla/5.0 (Linux; U; Android 5.1.1; vi-vn; PLE-701L Build/HuaweiMediaPad) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/61.0.3163.128 Mobile Safari/537.36 XiaoMi/Mint Browser/3.7.2
OS: Linux aarch64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-05-05
Channel: nightly
Built: 2021-05-05T00:12:57.039Z
Commit: b82391726f76c059b3c33636e6c9980a4fdac5c4

**Comment by Kippykip** [comment]
...Welp your kink works fine on my end on ruffle nightly.
