### ISSUE TITLE
Error on https://6games.eu/files/file/game.php

### ISSUE THREAD

**Issue by Spyninjas** [ruffle-rs/ruffle#5003]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:849:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:849:18
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (https://6games.eu/ruffle/ruffle.js?v4:1:6738)
    at std::sync::once::Once::call_once::{{closure}}::hffa00ec013760742 (https://6games.eu/ruffle/bc0dca71c99df687a576.wasm:wasm-function[1023]:0x2899fb)
    at std::sync::once::Once::call_inner::h79faa41f4d270a0b (https://6games.eu/ruffle/bc0dca71c99df687a576.wasm:wasm-function[988]:0x2756ea)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h66812a3cc7a9c482 (https://6games.eu/ruffle/bc0dca71c99df687a576.wasm:wasm-function[3931]:0x424831)
    at std::panicking::rust_panic_with_hook::hbdbceb5cd158bf19 (https://6games.eu/ruffle/bc0dca71c99df687a576.wasm:wasm-function[3072]:0x3d3e4c)
    at rust_begin_unwind (https://6games.eu/ruffle/bc0dca71c99df687a576.wasm:wasm-function[4147]:0x42a77b)
    at core::panicking::panic_fmt::h3ab5417155b7ba3b (https://6games.eu/ruffle/bc0dca71c99df687a576.wasm:wasm-function[4301]:0x431611)
    at core::panicking::panic::h5bfdfaa3db9a4b4a (https://6games.eu/ruffle/bc0dca71c99df687a576.wasm:wasm-function[4086]:0x427bdc)
    at core::ops::function::FnOnce::call_once::h78b0343d6987a9da (https://6games.eu/ruffle/bc0dca71c99df687a576.wasm:wasm-function[880]:0x250e1b)
    at ruffle_core::avm1::function::Executable::exec::he8bf2c1a211d8699 (https://6games.eu/ruffle/bc0dca71c99df687a576.wasm:wasm-function[367]:0xdba53)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://6games.eu/files/file/game.php?gid=492&lns=eng&isb=0
SWF URL: https://6games.eu/files/file/492-electricman-2.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; CrOS x86_64 13597.105.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.208 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-07-25
Channel: nightly
Built: 2021-07-25T00:13:03.752Z
Commit: 66bfff7687e4885eb6b0a9699b06ce806a3ba579

**Comment by jhwgh1968** [comment]
This seems to work on ruffle desktop commit 3982f3af9811cfc32c6f7eaf06aa3c8c81b91226. Perhaps if the site owner updated ruffle this would be resolved?

**Comment by sombraguerrero** [comment]
> 
> 
> This seems to work on ruffle desktop commit [3982f3a](https://github.com/ruffle-rs/ruffle/commit/3982f3af9811cfc32c6f7eaf06aa3c8c81b91226). Perhaps if the site owner updated ruffle this would be resolved?

Unfortunately no, that commit is not the root of this issue. Confirmed the issue persists in 8/30 desktop build.
