### ISSUE TITLE
Error on https://mysexgamer.com/game/struggling-of-rapture-part-2

### ISSUE THREAD

**Issue by AKBARD176** [ruffle-rs/ruffle#5013]
# Error Info
Error name: Error
Error message: panicked at 'already mutably borrowed: BorrowError', core/src/display_object/edit_text.rs:1383:16
Error stack:
```
Error: panicked at 'already mutably borrowed: BorrowError', core/src/display_object/edit_text.rs:1383:16
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://mysexgamer.com/assets/ruffle/ruffle.js:1:7026)
    at std::sync::once::Once::call_once::{{closure}}::h6e694fc45f651103 (<anonymous>:wasm-function[1085]:0x28c132)
    at std::sync::once::Once::call_inner::h99e47643887ee5a5 (<anonymous>:wasm-function[960]:0x26329f)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hb552ca3003b47989 (<anonymous>:wasm-function[3856]:0x41f24c)
    at std::panicking::rust_panic_with_hook::h03201bc01a0ed891 (<anonymous>:wasm-function[3008]:0x3bacee)
    at rust_begin_unwind (<anonymous>:wasm-function[4064]:0x424b97)
    at core::panicking::panic_fmt::hd44f353696296fec (<anonymous>:wasm-function[4212]:0x42b594)
    at core::option::expect_none_failed::hf7dab2706f1a5551 (<anonymous>:wasm-function[3448]:0x40d618)
    at ruffle_core::display_object::movie_clip::MovieClip::preload::hc1aa22a23a3780b3 (<anonymous>:wasm-function[627]:0x1bc42c)
    at ruffle_core::player::Player::set_root_movie::h5cc1cee597baa183 (<anonymous>:wasm-function[322]:0x9e6af)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: https://v8p5i7f9.ssl.hwcdn.net/games/swf/5/a/f/5af6ca68f721443d26c081f02b7fe4e0/5af6ca68f721443d26c081f02b7fe4e0.swf
Param movie: https://v8p5i7f9.ssl.hwcdn.net/games/swf/5/a/f/5af6ca68f721443d26c081f02b7fe4e0/5af6ca68f721443d26c081f02b7fe4e0.swf
Param quality: high
Param bgcolor: #000000
Param play: true
Param loop: true
Param wmode: window
Param scale: showall
Param menu: true
Param devicefont: false
Param allowScriptAccess: always
Param SCALE: default
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined
Attribute 6: undefined

# Page Info
Page URL: https://mysexgamer.com/game/struggling-of-rapture-part-2
SWF URL: https://v8p5i7f9.ssl.hwcdn.net/games/swf/5/a/f/5af6ca68f721443d26c081f02b7fe4e0/5af6ca68f721443d26c081f02b7fe4e0.swf

# Browser Info
Useragent: Mozilla/5.0 (Linux; Android 10; vivo 1935) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.120 Mobile Safari/537.36
OS: Linux aarch64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-06-17
Channel: nightly
Built: 2021-06-17T00:11:56.220Z
Commit: 622f35eb713c224a980ab67eb251a4b6880e1834

**Comment by jhwgh1968** [comment]
I was not able to reproduce the errors with ruffle desktop commit 3982f3af9811cfc32c6f7eaf06aa3c8c81b91226.
