### ISSUE TITLE
Error on https://www.oyunkuzusu.com/koturum-et-onu-2-oyna.html

### ISSUE THREAD

**Issue by elifsura** [ruffle-rs/ruffle#5028]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: JsValue(InvalidStateError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
Error: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
    at https://www.oyunkuzusu.com/ruffle.js:1:26863
    at https://www.oyunkuzusu.com/ruffle.js:1:4463
    at web_sys::features::gen_CanvasRenderingContext2d::CanvasRenderingContext2d::draw_image_with_html_canvas_element::h398e3172b9db6968 (https://www.oyunkuzusu.com/c804762e5aacff21db07.wasm:wasm-function[3934]:0x411d52)
    at <ruffle_render_canvas::WebCanvasRenderBackend as ruffle_core::backend::render::RenderBackend>::pop_mask::h1f00bd85358254fe (https://www.oyunkuzusu.com/c804762e5aacff21db07.wasm:wasm-function[854]:0x239b74)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render_self::h0813dc855b2ccaeb (https://www.oyunkuzusu.com/c804762e5aacff21db07.wasm:wasm-function[1914]:0x33f2e6)
    at ruffle_core::display_object::render_base::ha3c97458f83396a6 (https://www.oyunkuzusu.com/c804762e5aacff21db07.wasm:wasm-function[1647]:0x3110a8)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render::h40f34b20466a571f (https://www.oyunkuzusu.com/c804762e5aacff21db07.wasm:wasm-function[3248]:0x3d0d05)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render_self::h0813dc855b2ccaeb (https://www.oyunkuzusu.com/c804762e5aacff21db07.wasm:wasm-function[1914]:0x33fb08)
    at ruffle_core::display_object::render_base::ha3c97458f83396a6 (https://www.oyunkuzusu.com/c804762e5aacff21db07.wasm:wasm-function[1647]:0x3110a8)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render::h40f34b20466a571f (https://www.oyunkuzusu.com/c804762e5aacff21db07.wasm:wasm-function[3248]:0x3d0d2f))', render/canvas/src/lib.rs:682:14

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.oyunkuzusu.com/koturum-et-onu-2-oyna.html
SWF URL: https://www.oyunkuzusu.com/oyunlar/koturum_et_onu_2_secure.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-06-06
Channel: nightly
Built: 2021-06-06T00:18:06.916Z
Commit: aee37276ecdeccbf7bfef46e48f1c175cf76ff7c

**Comment by relrelb** [comment]
Fixed by #7026.
