### ISSUE TITLE
Error on https://www.e-players.net/preview.php

### ISSUE THREAD

**Issue by johnhuy** [ruffle-rs/ruffle#5043]
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', web/src/lib.rs:847:49
Error stack:
```
Error: panicked at 'already borrowed: BorrowMutError', web/src/lib.rs:847:49
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://www.e-players.net/ruffle/ruffle.js:1:6553)
    at std::sync::once::Once::call_once::{{closure}}::hce6501f6f20767e4 (wasm-function[1362]:169)
    at std::sync::once::Once::call_inner::hd3d269a4946f2df2 (wasm-function[1632]:675)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h6ed7686ed76cb258 (wasm-function[4833]:67)
    at std::panicking::rust_panic_with_hook::h4f753dc70b771d8e (wasm-function[3686]:224)
    at std::panicking::begin_panic_handler::{{closure}}::h5c9fc29957309ae8 (wasm-function[4348]:159)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h92808941d97e9b21 (wasm-function[5189]:40)
    at rust_begin_unwind (wasm-function[5068]:89)
    at core::panicking::panic_fmt::hbd8a975261a5f466 (wasm-function[5190]:48)
    at core::option::expect_none_failed::hbea1e2e5b59d80cc (wasm-function[4448]:123)
```

# Player Info
Allows script access: false
Player type: Object
SWF URL: https://e1.gamevui.com/images/flash/games/gamehanhdong/dragonfist3.swf?gId=830
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined

# Page Info
Page URL: https://www.e-players.net/preview.php?data=https://e1.gamevui.com/images/flash/games/gamehanhdong/dragonfist3.swf?gId=830
SWF URL: https://e1.gamevui.com/images/flash/games/gamehanhdong/dragonfist3.swf?gId=830

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3235.0 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-03-02
Channel: nightly
Built: 2021-03-02T00:17:52.607Z
Commit: 697ab274146e96a762b49ae047a6f528337ceb20

**Comment by Lord-McSweeney** [comment]
Closing as the site was using a version of Ruffle that is now 4 years outdated
