### ISSUE TITLE
Error on https://www.vap.co.jp/elfenlied/main.html

### ISSUE THREAD

**Issue by MustacheDuctTape** [ruffle-rs/ruffle#5067]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm1/activation.rs:1302:22
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm1/activation.rs:1302:22
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/ruffle.js?uniqueMessageSuffix=21424111849:1:7476)
    at std::sync::once::Once::call_once::{{closure}}::h5df181b90ad904c1 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/da8291897c0cd59250d4.wasm:wasm-function[1004]:0x27f5f7)
    at std::sync::once::Once::call_inner::h79faa41f4d270a0b (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/da8291897c0cd59250d4.wasm:wasm-function[968]:0x26aa7a)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hbd170ba35c598204 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/da8291897c0cd59250d4.wasm:wasm-function[3879]:0x425bcc)
    at std::panicking::rust_panic_with_hook::hbdbceb5cd158bf19 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/da8291897c0cd59250d4.wasm:wasm-function[3010]:0x3bfdb3)
    at rust_begin_unwind (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/da8291897c0cd59250d4.wasm:wasm-function[4091]:0x42b574)
    at core::panicking::panic_fmt::h3ab5417155b7ba3b (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/da8291897c0cd59250d4.wasm:wasm-function[4241]:0x432347)
    at core::panicking::panic::h5bfdfaa3db9a4b4a (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/da8291897c0cd59250d4.wasm:wasm-function[4033]:0x428c77)
    at ruffle_core::avm1::activation::Activation::do_action::h2d1b276c41c1e6b2 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/da8291897c0cd59250d4.wasm:wasm-function[291]:0x2260b)
    at ruffle_core::avm1::activation::Activation::run_actions::h86894d3fb046d578 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/da8291897c0cd59250d4.wasm:wasm-function[2425]:0x3958f3)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://www.vap.co.jp/elfenlied/main.html
SWF URL: https://www.vap.co.jp/elfenlied/main.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-07-21
Channel: nightly
Built: 2021-07-21T00:12:58.313Z
Commit: d2eb46d3be8dcb884847f4ecf0e3f25f9fe075bc

**Comment by dginovker** [comment]
Works on 0.1.0.544. Is also semi-nude so maybe nsfw?

**Comment by n0samu** [comment]
Actually the crash still happens if you click "Introduction" on the main menu. And I tried it with extension version 2022-07-27, and there's the same issue, so it's not a regression since you tested it.

**Comment by n0samu** [comment]
The problem seems to be related to loading text from a txt file. #7400 is another Japanese site that does the same thing and seems to be affected by this same bug.
