### ISSUE TITLE
Error on http://tdsheep.tdsheepvillage.com/

### ISSUE THREAD

**Issue by FlowRays** [ruffle-rs/ruffle#5127]
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', core/src/avm2/object/function_object.rs:280:5
Error stack:
```
Error: panicked at 'already borrowed: BorrowMutError', core/src/avm2/object/function_object.rs:280:5
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/ruffle.js?uniqueMessageSuffix=72861998021:1:7476)
    at std::sync::once::Once::call_once::{{closure}}::h5df181b90ad904c1 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/da8291897c0cd59250d4.wasm:wasm-function[1004]:0x27f5f7)
    at std::sync::once::Once::call_inner::h79faa41f4d270a0b (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/da8291897c0cd59250d4.wasm:wasm-function[968]:0x26aa7a)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hbd170ba35c598204 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/da8291897c0cd59250d4.wasm:wasm-function[3879]:0x425bcc)
    at std::panicking::rust_panic_with_hook::hbdbceb5cd158bf19 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/da8291897c0cd59250d4.wasm:wasm-function[3010]:0x3bfdb3)
    at rust_begin_unwind (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/da8291897c0cd59250d4.wasm:wasm-function[4091]:0x42b59b)
    at core::panicking::panic_fmt::h3ab5417155b7ba3b (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/da8291897c0cd59250d4.wasm:wasm-function[4241]:0x432347)
    at core::result::unwrap_failed::h9bf99bca88ba05dc (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/da8291897c0cd59250d4.wasm:wasm-function[3458]:0x413bab)
    at ruffle_core::avm2::object::TObject::install_foreign_trait::hb744491a62617608 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/da8291897c0cd59250d4.wasm:wasm-function[326]:0xa9d6b)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::set_property::h7c837903c0467b0d (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/da8291897c0cd59250d4.wasm:wasm-function[931]:0x25640f)
```

# Player Info
Allows script access: true

# Page Info
Page URL: http://tdsheep.tdsheepvillage.com/
SWF URL: http://tdsheep.tdsheepvillage.com/static/images/swf/TDSheepMain.swf?version=0.1

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-07-21
Channel: nightly
Built: 2021-07-21T00:12:58.313Z
Commit: d2eb46d3be8dcb884847f4ecf0e3f25f9fe075bc

**Comment by dginovker** [comment]
AS3

**Comment by n0samu** [comment]
Panic seems to be fixed
