### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by lajbel** [ruffle-rs/ruffle#5154]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:858:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:858:18
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (https://uploads.ungrounded.net/ruffle_wrapper/lib/ruffle.js?1630001320:1:7576)
    at std::sync::once::Once::call_once::{{closure}}::hdc00d7da63128799 (https://uploads.ungrounded.net/ruffle_wrapper/lib/e112735cbb3920aa6a3c.wasm:wasm-function[917]:0x244cff)
    at std::sync::once::Once::call_inner::h96e3a490169c6c27 (https://uploads.ungrounded.net/ruffle_wrapper/lib/e112735cbb3920aa6a3c.wasm:wasm-function[1173]:0x2a28ed)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h34a21969c4579926 (https://uploads.ungrounded.net/ruffle_wrapper/lib/e112735cbb3920aa6a3c.wasm:wasm-function[4038]:0x42e625)
    at std::panicking::rust_panic_with_hook::h2d9079427a2d996a (https://uploads.ungrounded.net/ruffle_wrapper/lib/e112735cbb3920aa6a3c.wasm:wasm-function[2907]:0x3c34e4)
    at rust_begin_unwind (https://uploads.ungrounded.net/ruffle_wrapper/lib/e112735cbb3920aa6a3c.wasm:wasm-function[4252]:0x434029)
    at core::panicking::panic_fmt::h1fea623755fffed7 (https://uploads.ungrounded.net/ruffle_wrapper/lib/e112735cbb3920aa6a3c.wasm:wasm-function[4408]:0x43adda)
    at core::panicking::panic::h38cac710b5048ca0 (https://uploads.ungrounded.net/ruffle_wrapper/lib/e112735cbb3920aa6a3c.wasm:wasm-function[4187]:0x431583)
    at core::ops::function::FnOnce::call_once::ha40e6113ced28e4c (https://uploads.ungrounded.net/ruffle_wrapper/lib/e112735cbb3920aa6a3c.wasm:wasm-function[891]:0x23867f)
    at ruffle_core::avm1::function::Executable::exec::h6321fa6c8b3e93cb (https://uploads.ungrounded.net/ruffle_wrapper/lib/e112735cbb3920aa6a3c.wasm:wasm-function[385]:0xe74c4)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.64&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1630001320%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F484000%2F484931_peeps.swf%3F1509024282%22%2C%22vars%22%3A%7B%22ngio_session_id%22%3A%2275226430.57750f188d8216c50a78ec6a69ea6882acf4d7e1cd7d7d%22%2C%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%226128ddff17a72%22%2C%22NewgroundsAPI_SessionID%22%3A%22luxeFxnBfckEDo7G6WbCe3a4bd42e8f0189612f755b0947a55ad62e3d409TRbM%22%2C%22NewgroundsAPI_UserName%22%3A%22LaJBel%22%2C%22NewgroundsAPI_UserID%22%3A9008270%2C%22ng_username%22%3A%22LaJBel%22%7D%2C%22width%22%3A640%2C%22height%22%3A450%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F484000%2Fflash_484931_card.png%3Ff1609851325%22%7D
SWF URL: https://uploads.ungrounded.net/484000/484931_peeps.swf?1509024282

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-08-26
Channel: nightly
Built: 2021-08-26T00:12:02.563Z
Commit: 0aed180da897f27827da41b1e2d8db5b4c486658
Is extension: false

**Comment by Poopooracoocoo** [comment]
Link to Portal Defenders on Newgrounds:
https://www.newgrounds.com/portal/view/484931

**Comment by lajbel** [comment]
Fixed
