### ISSUE TITLE
Error on chrome-extension://aheledfnkemlpklffpgaofpcmofcfphk/player.html

### ISSUE THREAD

**Issue by Vistakirk** [ruffle-rs/ruffle#5189]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: JsValue(InvalidStateError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The HTMLImageElement provided is in the 'broken' state.
Error: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The HTMLImageElement provided is in the 'broken' state.
    at chrome-extension://aheledfnkemlpklffpgaofpcmofcfphk/dist/player.js:1:29214
    at T (chrome-extension://aheledfnkemlpklffpgaofpcmofcfphk/dist/player.js:1:4897)
    at s.wbg.__wbg_drawImage_ff0075aa41bc6155 (chrome-extension://aheledfnkemlpklffpgaofpcmofcfphk/dist/player.js:1:29188)
    at web_sys::features::gen_CanvasRenderingContext2d::CanvasRenderingContext2d::draw_image_with_html_image_element::h726b7478f71b13c8 (chrome-extension://aheledfnkemlpklffpgaofpcmofcfphk/dist/d0109ad57d5486eb7e0e.wasm:wasm-function[4135]:0x431297)
    at <ruffle_render_canvas::WebCanvasRenderBackend as ruffle_core::backend::render::RenderBackend>::get_bitmap_pixels::h884cbf6df79fea42 (chrome-extension://aheledfnkemlpklffpgaofpcmofcfphk/dist/d0109ad57d5486eb7e0e.wasm:wasm-function[1143]:0x299870)
    at ruffle_core::avm1::globals::bitmap_data::load_bitmap::h2b5148be3588515a (chrome-extension://aheledfnkemlpklffpgaofpcmofcfphk/dist/d0109ad57d5486eb7e0e.wasm:wasm-function[787]:0x212d52)
    at ruffle_core::avm1::function::Executable::exec::hb45896e559f84c63 (chrome-extension://aheledfnkemlpklffpgaofpcmofcfphk/dist/d0109ad57d5486eb7e0e.wasm:wasm-function[385]:0xe79e9)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call::h976a1f32062fb35e (chrome-extension://aheledfnkemlpklffpgaofpcmofcfphk/dist/d0109ad57d5486eb7e0e.wasm:wasm-function[710]:0x1f0bed)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h42f37fc240275d16 (chrome-extension://aheledfnkemlpklffpgaofpcmofcfphk/dist/d0109ad57d5486eb7e0e.wasm:wasm-function[699]:0x1e7c28)
    at ruffle_core::avm1::activation::Activation::do_action::hc6ccf6c677b1431f (chrome-extension://aheledfnkemlpklffpgaofpcmofcfphk/dist/d0109ad57d5486eb7e0e.wasm:wasm-function[304]:0xd28b))', render/canvas/src/lib.rs:729:14

# Player Info
Allows script access: false

# Page Info
Page URL: chrome-extension://aheledfnkemlpklffpgaofpcmofcfphk/player.html?url=http://onemorelevel.com/static/games3/hex-empire.swf
SWF URL: http://onemorelevel.com/static/games3/hex-empire.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-08-31
Channel: nightly
Built: 2021-08-31T00:13:32.984Z
Commit: 587c42302705258c31f9162493272edff73ca1d2
Is extension: true

**Comment by relrelb** [comment]
Fixed by #9358.
