### ISSUE TITLE
Ruffle Error on https://totaljerkface.com/divine_intervention.tjf

### ISSUE THREAD

**Issue by arosasvhudoznik61** [ruffle-rs/ruffle#5213]
# Error Info
Error name: Error
Error message: panicked at 'cannot recursively acquire mutex', /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys/wasm/../unsupported/mutex.rs:22:9
Error stack:
```
Error: panicked at 'cannot recursively acquire mutex', /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys/wasm/../unsupported/mutex.rs:22:9
    at Object.Q (https://totaljerkface.com/js/libruffle/core.ruffle.5e850f90e6e2fab0bb54.js:1:20877)
    at __wbg_new_df6e6ab7a65c4c4d (https://totaljerkface.com/js/libruffle/ruffle.js:1:38192)
    at https://totaljerkface.com/js/libruffle/cbe7657b7dc9d70da5a6.module.wasm:wasm-function[1324]:0x254c8e
    at https://totaljerkface.com/js/libruffle/cbe7657b7dc9d70da5a6.module.wasm:wasm-function[1491]:0x272a47
    at https://totaljerkface.com/js/libruffle/cbe7657b7dc9d70da5a6.module.wasm:wasm-function[4066]:0x338300
    at https://totaljerkface.com/js/libruffle/cbe7657b7dc9d70da5a6.module.wasm:wasm-function[3161]:0x315621
    at https://totaljerkface.com/js/libruffle/cbe7657b7dc9d70da5a6.module.wasm:wasm-function[4427]:0x33dc16
    at https://totaljerkface.com/js/libruffle/cbe7657b7dc9d70da5a6.module.wasm:wasm-function[4378]:0x33d372
    at https://totaljerkface.com/js/libruffle/cbe7657b7dc9d70da5a6.module.wasm:wasm-function[4428]:0x33dc3f
    at https://totaljerkface.com/js/libruffle/cbe7657b7dc9d70da5a6.module.wasm:wasm-function[1470]:0x26f1ad
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://totaljerkface.com/divine_intervention.tjf
SWF URL: https://totaljerkface.com/swf/di_level1.swf

# Browser Info
Useragent: Mozilla/5.0 (Linux; arm_64; Android 11; SM-P610) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 YaBrowser/21.6.3.113.01 Safari/537.36
OS: Linux aarch64

# Ruffle Info
Version: 0.1.0
Name: nightly 2020-12-31
Channel: nightly
Built: 2020-12-31T00:48:27.350Z
Commit: ea3b6f59dfd7c528f2ae305c4dba2d351ada9302

**Comment by dginovker** [comment]
Works on 0.1.0.544
