### ISSUE TITLE
Error on https://www.azdressup.com/bratz/bratz-babyz-fish-tank.html

### ISSUE THREAD

**Issue by psychedpolkadot** [ruffle-rs/ruffle#5269]
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', web/src/lib.rs:847:49
Error stack:
```
Error: panicked at 'already borrowed: BorrowMutError', web/src/lib.rs:847:49
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://www.azdressup.com/css/ruffle.js:1:6553)
    at std::sync::once::Once::call_once::{{closure}}::hce6501f6f20767e4 (https://www.azdressup.com/css/5cf6745297fb4a9d7eff6801084361aa.wasm:wasm-function[1355]:0x27a9f3)
    at std::sync::once::Once::call_inner::hd3d269a4946f2df2 (https://www.azdressup.com/css/5cf6745297fb4a9d7eff6801084361aa.wasm:wasm-function[1636]:0x2af37a)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h6ed7686ed76cb258 (https://www.azdressup.com/css/5cf6745297fb4a9d7eff6801084361aa.wasm:wasm-function[4834]:0x3a52f0)
    at std::panicking::rust_panic_with_hook::h4f753dc70b771d8e (https://www.azdressup.com/css/5cf6745297fb4a9d7eff6801084361aa.wasm:wasm-function[3692]:0x379b0d)
    at std::panicking::begin_panic_handler::{{closure}}::h5c9fc29957309ae8 (https://www.azdressup.com/css/5cf6745297fb4a9d7eff6801084361aa.wasm:wasm-function[4350]:0x398a7e)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h92808941d97e9b21 (https://www.azdressup.com/css/5cf6745297fb4a9d7eff6801084361aa.wasm:wasm-function[5190]:0x3aac3f)
    at rust_begin_unwind (https://www.azdressup.com/css/5cf6745297fb4a9d7eff6801084361aa.wasm:wasm-function[5069]:0x3a93f2)
    at core::panicking::panic_fmt::hbd8a975261a5f466 (https://www.azdressup.com/css/5cf6745297fb4a9d7eff6801084361aa.wasm:wasm-function[5191]:0x3aac75)
    at core::option::expect_none_failed::hbea1e2e5b59d80cc (https://www.azdressup.com/css/5cf6745297fb4a9d7eff6801084361aa.wasm:wasm-function[4449]:0x39bc4e)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.azdressup.com/bratz/bratz-babyz-fish-tank.html
SWF URL: https://www.azdressup.com/media/0711/bratzfishtank.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36 Edg/93.0.961.38
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-02-27
Channel: nightly
Built: 2021-02-27T00:17:48.863Z
Commit: 8500a676cfb694dc46fd258c0802c3dee4d61f66

**Comment by Lord-McSweeney** [comment]
Closing as the site was using a version of Ruffle that is now 4 years outdated
