### ISSUE TITLE
Error on chrome-extension://lgaiicajmmcokonifgobeajakbplgcfk/player.html

### ISSUE THREAD

**Issue by flingsmashfan** [ruffle-rs/ruffle#5291]
# Error Info
Error name: Error
Error message: panicked at 'index out of bounds: the len is 169819 but the index is 169819', core/src/backend/render.rs:510:33
Error stack:
```
Error: panicked at 'index out of bounds: the len is 169819 but the index is 169819', core/src/backend/render.rs:510:33
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://lgaiicajmmcokonifgobeajakbplgcfk/dist/player.js:1:7576)
    at std::sync::once::Once::call_once::{{closure}}::hdc00d7da63128799 (chrome-extension://lgaiicajmmcokonifgobeajakbplgcfk/dist/9a3f7d7b8382071fb6b9.wasm:wasm-function[916]:0x24529f)
    at std::sync::once::Once::call_inner::h96e3a490169c6c27 (chrome-extension://lgaiicajmmcokonifgobeajakbplgcfk/dist/9a3f7d7b8382071fb6b9.wasm:wasm-function[1171]:0x2a2cd1)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h34a21969c4579926 (chrome-extension://lgaiicajmmcokonifgobeajakbplgcfk/dist/9a3f7d7b8382071fb6b9.wasm:wasm-function[4040]:0x42fb92)
    at std::panicking::rust_panic_with_hook::h2d9079427a2d996a (chrome-extension://lgaiicajmmcokonifgobeajakbplgcfk/dist/9a3f7d7b8382071fb6b9.wasm:wasm-function[2906]:0x3c434e)
    at rust_begin_unwind (chrome-extension://lgaiicajmmcokonifgobeajakbplgcfk/dist/9a3f7d7b8382071fb6b9.wasm:wasm-function[4254]:0x43587c)
    at core::panicking::panic_fmt::h1fea623755fffed7 (chrome-extension://lgaiicajmmcokonifgobeajakbplgcfk/dist/9a3f7d7b8382071fb6b9.wasm:wasm-function[4410]:0x43c602)
    at core::panicking::panic_bounds_check::haaec889ba18dd685 (chrome-extension://lgaiicajmmcokonifgobeajakbplgcfk/dist/9a3f7d7b8382071fb6b9.wasm:wasm-function[3752]:0x424310)
    at ruffle_core::backend::render::decode_define_bits_lossless::ha6a2548d44b473d0 (chrome-extension://lgaiicajmmcokonifgobeajakbplgcfk/dist/9a3f7d7b8382071fb6b9.wasm:wasm-function[411]:0x104848)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::register_bitmap_png::h76f6297292858fde (chrome-extension://lgaiicajmmcokonifgobeajakbplgcfk/dist/9a3f7d7b8382071fb6b9.wasm:wasm-function[3488]:0x3f764e)
```

# Player Info
Allows script access: false

# Page Info
Page URL: chrome-extension://lgaiicajmmcokonifgobeajakbplgcfk/player.html?url=https://web.archive.org/web/20030810231625id_/http://www.multidmedia.com/software/flashstudio/fsp_interface.swf
SWF URL: https://web.archive.org/web/20030810231625id_/http://www.multidmedia.com/software/flashstudio/fsp_interface.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-08-29
Channel: nightly
Built: 2021-08-29T00:13:47.345Z
Commit: 3982f3af9811cfc32c6f7eaf06aa3c8c81b91226
Is extension: true

**Comment by relrelb** [comment]
Might be related to #1191.

**Comment by Lord-McSweeney** [comment]
I can still reproduce this issue
