### ISSUE TITLE
Error on https://www.minijuegos.com/helpers/game/sandbox.php

### ISSUE THREAD

**Issue by ivaneliascalu** [ruffle-rs/ruffle#5319]
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', core/src/avm2/object/function_object.rs:280:5
Error stack:
```
Error: panicked at 'already borrowed: BorrowMutError', core/src/avm2/object/function_object.rs:280:5
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/ruffle.js?uniqueMessageSuffix=64124014409:1:7476)
    at std::sync::once::Once::call_once::{{closure}}::h5df181b90ad904c1 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/da8291897c0cd59250d4.wasm:wasm-function[1004]:0x27f5f7)
    at std::sync::once::Once::call_inner::h79faa41f4d270a0b (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/da8291897c0cd59250d4.wasm:wasm-function[968]:0x26aa7a)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hbd170ba35c598204 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/da8291897c0cd59250d4.wasm:wasm-function[3879]:0x425bcc)
    at std::panicking::rust_panic_with_hook::hbdbceb5cd158bf19 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/da8291897c0cd59250d4.wasm:wasm-function[3010]:0x3bfdb3)
    at rust_begin_unwind (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/da8291897c0cd59250d4.wasm:wasm-function[4091]:0x42b59b)
    at core::panicking::panic_fmt::h3ab5417155b7ba3b (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/da8291897c0cd59250d4.wasm:wasm-function[4241]:0x432347)
    at core::result::unwrap_failed::h9bf99bca88ba05dc (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/da8291897c0cd59250d4.wasm:wasm-function[3458]:0x413bab)
    at ruffle_core::avm2::object::TObject::install_foreign_trait::hb744491a62617608 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/da8291897c0cd59250d4.wasm:wasm-function[326]:0xa9d6b)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::set_property::h7c837903c0467b0d (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/da8291897c0cd59250d4.wasm:wasm-function[931]:0x25640f)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: https://www.minijuegosgratis.com/flash1234/no_hotlink/raze2_2.swf
Param quality: high
Param allowscriptaccess: always
Param allowfullscreen: false
Param wmode: direct
Param flashvars: mp_log_level=4&mp_game_id=19331&mp_game_url=https%3A%2F%2Fwww.minijuegos.com%2Fembed%2Fraze-2&mp_site_name=minijuegos.com&mp_site_url=https%3A%2F%2Fwww.minijuegos.com%2F&mp_api_id=&mp_api_as3_url=&mp_api_as3_url_bck=&mp_api_user_id=&mp_api_user_token=&mp_locale=es_ES&mp_timezone=America%2FLima&mp_embed=false&mp_base_path=https%3A%2F%2Fwww.minijuegosgratis.com%2Fflash1234%2Fno_hotlink%2F
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined
Attribute 6: undefined

# Page Info
Page URL: https://www.minijuegos.com/helpers/game/sandbox.php?mp_assets=https%3A%2F%2Fs2.minijuegosgratis.com%2F&mp_embed=0&mp_game_id=19331&mp_game_uid=raze-2&mp_game_url=https%3A%2F%2Fwww.minijuegos.com%2Fembed%2Fraze-2&mp_int=1&mp_locale=es_ES&mp_player_type=FLASH&mp_player_url=aHR0cHM6Ly93d3cubWluaWp1ZWdvc2dyYXRpcy5jb20vZmxhc2gxMjM0L25vX2hvdGxpbmsvcmF6ZTJfMi5zd2Y%3D&mp_site_https_url=https%3A%2F%2Fwww.minijuegos.com%2F&mp_site_name=minijuegos.com&mp_site_url=https%3A%2F%2Fwww.minijuegos.com%2F&mp_timezone=America%2FLima&mp_view_type=
SWF URL: https://www.minijuegosgratis.com/flash1234/no_hotlink/raze2_2.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36 OPR/78.0.4093.186
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-07-21
Channel: nightly
Built: 2021-07-21T00:12:58.313Z
Commit: d2eb46d3be8dcb884847f4ecf0e3f25f9fe075bc

**Comment by serkonda7** [comment]
I was not able to reproduce this issue with a recent version of ruffle. Can this be closed?
