### ISSUE TITLE
Error on https://www.jogos360.com.br/baby_blimp.html

### ISSUE THREAD

**Issue by ster4** [ruffle-rs/ruffle#5384]
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', web/src/lib.rs:679:42
Error stack:
```
Error: panicked at 'already borrowed: BorrowMutError', web/src/lib.rs:679:42
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://www.jogos360.com.br/assets/ruffle.js:1:7479)
    at std::sync::once::Once::call_once::{{closure}}::h098c4530511c1407 (https://www.jogos360.com.br/assets/349d49a671de87a3e810.wasm:wasm-function[1227]:0x2ba694)
    at std::sync::once::Once::call_inner::hf7fd718057964857 (https://www.jogos360.com.br/assets/349d49a671de87a3e810.wasm:wasm-function[1250]:0x2c22b8)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h6c44fc25588b0f32 (https://www.jogos360.com.br/assets/349d49a671de87a3e810.wasm:wasm-function[3750]:0x44c00b)
    at std::panicking::rust_panic_with_hook::h9d91fa0fae16500f (https://www.jogos360.com.br/assets/349d49a671de87a3e810.wasm:wasm-function[2743]:0x3aa0ea)
    at rust_begin_unwind (https://www.jogos360.com.br/assets/349d49a671de87a3e810.wasm:wasm-function[3956]:0x451cad)
    at core::panicking::panic_fmt::h91d2023e5afe1929 (https://www.jogos360.com.br/assets/349d49a671de87a3e810.wasm:wasm-function[4103]:0x458d4d)
    at core::option::expect_none_failed::h203584ddbc785ca2 (https://www.jogos360.com.br/assets/349d49a671de87a3e810.wasm:wasm-function[3383]:0x43d463)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::h5e97eda0a9fa799e (https://www.jogos360.com.br/assets/349d49a671de87a3e810.wasm:wasm-function[1334]:0x2d0658)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h08b35b209a139415 (https://www.jogos360.com.br/assets/349d49a671de87a3e810.wasm:wasm-function[4231]:0x45acb2)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.jogos360.com.br/baby_blimp.html
SWF URL: https://cdn.jogos360.com.br/files/games/ba/by/baby-blimp.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36 Edg/94.0.992.31
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-05-03
Channel: nightly
Built: 2021-05-03T00:12:09.006Z
Commit: f2256a661be22fd12ae1ec3b40574d7cca670a27

**Comment by ster4** [comment]
bug

**Comment by Poopooracoocoo** [comment]
Quick test from SWF on Ruffle demo:

https://user-images.githubusercontent.com/51363864/135429835-93bfa741-5cee-4dfb-8ba9-0e45a77d7d39.mp4
