### ISSUE TITLE
Error on https://ruffle.rs/demo/

### ISSUE THREAD

**Issue by devhammed** [ruffle-rs/ruffle#5445]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:494:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:494:50
    at r.wbg.__wbg_new_df6e6ab7a65c4c4d (https://ruffle.rs/demo/index.js:1:16826)
    at std::sync::once::Once::call_once::{{closure}}::hf7c73d58e4b9dc97 (https://ruffle.rs/demo/96a53aa08027bd2f869d.wasm:wasm-function[1023]:0x2b8330)
    at std::sync::once::Once::call_inner::hc44ad7f626385660 (https://ruffle.rs/demo/96a53aa08027bd2f869d.wasm:wasm-function[1285]:0x3132da)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h16a4fefa008aae53 (https://ruffle.rs/demo/96a53aa08027bd2f869d.wasm:wasm-function[4381]:0x4b2503)
    at std::panicking::rust_panic_with_hook::he9bfe03219d715ba (https://ruffle.rs/demo/96a53aa08027bd2f869d.wasm:wasm-function[3215]:0x441edc)
    at rust_begin_unwind (https://ruffle.rs/demo/96a53aa08027bd2f869d.wasm:wasm-function[4610]:0x4b8523)
    at core::panicking::panic_fmt::hbf21a3d4bbb82bf8 (https://ruffle.rs/demo/96a53aa08027bd2f869d.wasm:wasm-function[4800]:0x4bfb39)
    at core::result::unwrap_failed::h27f43d993c3864a1 (https://ruffle.rs/demo/96a53aa08027bd2f869d.wasm:wasm-function[3906]:0x49f457)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::hac2cf32645130353 (https://ruffle.rs/demo/96a53aa08027bd2f869d.wasm:wasm-function[729]:0x223c15)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::register_glyph_shape::hea2d6ac358ab2d06 (https://ruffle.rs/demo/96a53aa08027bd2f869d.wasm:wasm-function[2503]:0x3f5d5f)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://ruffle.rs/demo/
SWF URL: https://ruffle.rs/demo/swfs/synj1.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-10-10
Channel: nightly
Built: 2021-10-10T00:15:07.407Z
Commit: b0e3698c44f4b88c6673c18648cd8fd53b9f6ad1
Is extension: false

**Comment by Poopooracoocoo** [comment]
Could you please provide more information? Were you trying to play Synj vs. Horrid Part 1? The demo does not currently tell the developers what SWF you tried to play if you played your own SWF.
