### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by Filename99** [ruffle-rs/ruffle#5477]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', render/webgl/src/lib.rs:656:48
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', render/webgl/src/lib.rs:656:48
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (https://uploads.ungrounded.net/ruffle_wrapper/lib/ruffle.js?1634050641:1:6863)
    at std::sync::once::Once::call_once::{{closure}}::h0f65e93e537a4a81 (https://uploads.ungrounded.net/ruffle_wrapper/lib/d0c41fcabf02fbab0f7e.wasm:wasm-function[1029]:0x2ca4dc)
    at std::sync::once::Once::call_inner::hc44ad7f626385660 (https://uploads.ungrounded.net/ruffle_wrapper/lib/d0c41fcabf02fbab0f7e.wasm:wasm-function[1292]:0x327b82)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h6ca12c217eb2f4f2 (https://uploads.ungrounded.net/ruffle_wrapper/lib/d0c41fcabf02fbab0f7e.wasm:wasm-function[4386]:0x4be0f9)
    at std::panicking::rust_panic_with_hook::he9bfe03219d715ba (https://uploads.ungrounded.net/ruffle_wrapper/lib/d0c41fcabf02fbab0f7e.wasm:wasm-function[3223]:0x456ff8)
    at rust_begin_unwind (https://uploads.ungrounded.net/ruffle_wrapper/lib/d0c41fcabf02fbab0f7e.wasm:wasm-function[4618]:0x4c41c3)
    at core::panicking::panic_fmt::hbf21a3d4bbb82bf8 (https://uploads.ungrounded.net/ruffle_wrapper/lib/d0c41fcabf02fbab0f7e.wasm:wasm-function[4811]:0x4cb8a4)
    at core::panicking::panic::h2fd385a887c8bf13 (https://uploads.ungrounded.net/ruffle_wrapper/lib/d0c41fcabf02fbab0f7e.wasm:wasm-function[4551]:0x4c14ae)
    at ruffle_render_webgl::WebGlRenderBackend::register_bitmap::hbd7791c819520a5e (https://uploads.ungrounded.net/ruffle_wrapper/lib/d0c41fcabf02fbab0f7e.wasm:wasm-function[1482]:0x35ba3f)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::register_bitmap_raw::h7c2634b20adb13a3 (https://uploads.ungrounded.net/ruffle_wrapper/lib/d0c41fcabf02fbab0f7e.wasm:wasm-function[3840]:0x482efd)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.64&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1634050641%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F592000%2F592473_MadnessGame_ULTIMATE.swf%3F1507662264%22%2C%22vars%22%3A%7B%22ngio_session_id%22%3A%2263528668.1461ac6cc186163e188565e242234a59cf952e310495d3%22%2C%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%2261681cc6cb102%22%2C%22NewgroundsAPI_SessionID%22%3A%22OAuZ64BggUxEiS1kAwT5017b35ebe5467f55987c54926dfe36d22ee6901beXPx%22%2C%22NewgroundsAPI_UserName%22%3A%22Filename99%22%2C%22NewgroundsAPI_UserID%22%3A7922852%2C%22ng_username%22%3A%22Filename99%22%7D%2C%22width%22%3A850%2C%22height%22%3A530%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F592000%2Fflash_592473_card.png%3Ff1608170534%22%7D
SWF URL: https://uploads.ungrounded.net/592000/592473_MadnessGame_ULTIMATE.swf?1507662264

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36 OPR/79.0.4143.72
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-10-12
Channel: nightly
Built: 2021-10-12T00:14:48.831Z
Commit: 60ef1ba38b21ceb244b5925f80310d87b9bf6c7f
Is extension: false

**Comment by Herschel** [comment]
WebGL failed to create a bitmap; we should remove the `unwrap` from inside `WebGlRenderBackend::register_bitmap`.

**Comment by kjarosh** [comment]
Should be fixed as of the newest version
