### ISSUE TITLE
Error on https://ruffle.rs/demo/

### ISSUE THREAD

**Issue by juaniesteban1020** [ruffle-rs/ruffle#5491]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:849:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:849:18
    at r.wbg.__wbg_new_df6e6ab7a65c4c4d (https://ruffle.rs/demo/index.js:1:16826)
    at std::sync::once::Once::call_once::{{closure}}::hbc3e76004faf5843 (https://ruffle.rs/demo/3dd6c595425e4b4e4d7a.wasm:wasm-function[1027]:0x2c0c54)
    at std::sync::once::Once::call_inner::hc44ad7f626385660 (https://ruffle.rs/demo/3dd6c595425e4b4e4d7a.wasm:wasm-function[1292]:0x31b94b)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h23da166c23bc7e1a (https://ruffle.rs/demo/3dd6c595425e4b4e4d7a.wasm:wasm-function[4392]:0x4bc343)
    at std::panicking::rust_panic_with_hook::he9bfe03219d715ba (https://ruffle.rs/demo/3dd6c595425e4b4e4d7a.wasm:wasm-function[3214]:0x44b8e2)
    at rust_begin_unwind (https://ruffle.rs/demo/3dd6c595425e4b4e4d7a.wasm:wasm-function[4623]:0x4c23c2)
    at core::panicking::panic_fmt::hbf21a3d4bbb82bf8 (https://ruffle.rs/demo/3dd6c595425e4b4e4d7a.wasm:wasm-function[4817]:0x4c9ad0)
    at core::panicking::panic::h2fd385a887c8bf13 (https://ruffle.rs/demo/3dd6c595425e4b4e4d7a.wasm:wasm-function[4556]:0x4bf6ad)
    at core::ops::function::FnOnce::call_once::h8686fa0177bbb676 (https://ruffle.rs/demo/3dd6c595425e4b4e4d7a.wasm:wasm-function[1004]:0x2b7ffc)
    at ruffle_core::avm1::function::Executable::exec::h67427effb9e1e718 (https://ruffle.rs/demo/3dd6c595425e4b4e4d7a.wasm:wasm-function[422]:0x125d90)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://ruffle.rs/demo/

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-10-17
Channel: nightly
Built: 2021-10-17T00:14:24.515Z
Commit: e9efc2841bef47670139fc4d9d493383aaba32b4
Is extension: false

**Comment by Herschel** [comment]
Hello, which SWF were you trying to run? Thank you!

**Comment by Poopooracoocoo** [comment]
@Herschel there are quite a few issues where the reporter hasn't replied... Should we close issues like these? 

A label could be added for such issues

**Comment by Poopooracoocoo** [comment]
Closing due to a lack of response from reporter.
