### ISSUE TITLE
Error on https://www.i-gamer.net/play/976.html

### ISSUE THREAD

**Issue by chaidachaida** [ruffle-rs/ruffle#5510]
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', web/src/lib.rs:847:49
Error stack:
```
Error: panicked at 'already borrowed: BorrowMutError', web/src/lib.rs:847:49
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://www.i-gamer.net/play/ruffle/ruffle.js:1:6915)
    at wasm-function[1196]:183
    at wasm-function[1803]:675
    at wasm-function[5310]:67
    at wasm-function[4085]:222
    at wasm-function[4791]:159
    at wasm-function[5683]:40
    at wasm-function[5554]:89
    at wasm-function[5685]:48
    at wasm-function[4907]:123
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://www.i-gamer.net/play/976.html
SWF URL: https://www.i-gamer.net/game662/flash2/1.244_content.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3314.0 Safari/537.36 SE 2.X MetaSr 1.0
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-04-04
Channel: nightly
Built: 2021-04-04T00:42:01.875Z
Commit: e2f124ee34eb27c0f6463a76534b4936e750d58a

**Comment by Lord-McSweeney** [comment]
Closing as the site was using a version of Ruffle that is now 4 years outdated
