### ISSUE TITLE
Error on http://www.marv.jp/special/game/wii/runefactory/special/index.html

### ISSUE THREAD

**Issue by QLammy** [ruffle-rs/ruffle#5572]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:494:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:494:50
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://jfehikcjkkfnnmnicdejbgmbimlpkkpd/dist/ruffle.js?id=55287407675:1:7036)
    at std::sync::once::Once::call_once::{{closure}}::h5c607ed08f988e53 (chrome-extension://jfehikcjkkfnnmnicdejbgmbimlpkkpd/dist/00de09682f2d1fb871c2.wasm:wasm-function[1004]:0x2ec1ac)
    at std::sync::once::Once::call_inner::hf1b92ab8c222362b (chrome-extension://jfehikcjkkfnnmnicdejbgmbimlpkkpd/dist/00de09682f2d1fb871c2.wasm:wasm-function[1326]:0x359a06)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h3097032c631d0165 (chrome-extension://jfehikcjkkfnnmnicdejbgmbimlpkkpd/dist/00de09682f2d1fb871c2.wasm:wasm-function[4591]:0x4e7391)
    at std::panicking::rust_panic_with_hook::ha223473efd20893e (chrome-extension://jfehikcjkkfnnmnicdejbgmbimlpkkpd/dist/00de09682f2d1fb871c2.wasm:wasm-function[3279]:0x4a2d3c)
    at rust_begin_unwind (chrome-extension://jfehikcjkkfnnmnicdejbgmbimlpkkpd/dist/00de09682f2d1fb871c2.wasm:wasm-function[4653]:0x4e9894)
    at core::panicking::panic_fmt::hca0bee0b11468063 (chrome-extension://jfehikcjkkfnnmnicdejbgmbimlpkkpd/dist/00de09682f2d1fb871c2.wasm:wasm-function[4853]:0x4f4242)
    at core::result::unwrap_failed::hcbbd7f1ba3fa06cb (chrome-extension://jfehikcjkkfnnmnicdejbgmbimlpkkpd/dist/00de09682f2d1fb871c2.wasm:wasm-function[3937]:0x4d070d)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::hf1750bd21578be22 (chrome-extension://jfehikcjkkfnnmnicdejbgmbimlpkkpd/dist/00de09682f2d1fb871c2.wasm:wasm-function[702]:0x24d3f0)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::register_glyph_shape::ha4a28e0c2756b134 (chrome-extension://jfehikcjkkfnnmnicdejbgmbimlpkkpd/dist/00de09682f2d1fb871c2.wasm:wasm-function[1836]:0x3e7aad)
```

# Player Info
Allows script access: true

# Page Info
Page URL: http://www.marv.jp/special/game/wii/runefactory/special/index.html
SWF URL: http://www.marv.jp/special/game/wii/runefactory/special/img/comment/Paku_Romi.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-10-31
Channel: nightly
Built: 2021-10-31T00:13:01.667Z
Commit: 039777c41ef6b62989d93e8e24b9065afac1f6cb
Is extension: true

**Comment by Toad06** [comment]
Closing in favor of #1905 as this is the same issue. Thanks for reporting.
