### ISSUE TITLE
Error on https://es.games68.com/games.php?id=2121706

### ISSUE THREAD

**Issue by mannuuuuk** [ruffle-rs/ruffle#5618]
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/gc-arena-0.2.0/src/gc_cell.rs:62:29
Error stack:
```
Error: panicked at 'already borrowed: BorrowMutError', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/gc-arena-0.2.0/src/gc_cell.rs:62:29
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://es.games68.com/include/ruffle/ruffle.js:1:6333)
    at std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f (https://es.games68.com/include/ruffle/43f8e1e34e0629f740121b10aab750da.wasm:wasm-function[1280]:0x263ca7)
    at std::sync::once::Once::call_inner::h02eac160d339afc2 (https://es.games68.com/include/ruffle/43f8e1e34e0629f740121b10aab750da.wasm:wasm-function[1548]:0x294bd2)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801 (https://es.games68.com/include/ruffle/43f8e1e34e0629f740121b10aab750da.wasm:wasm-function[4312]:0x368af7)
    at std::panicking::rust_panic_with_hook::h123718ba3bf480af (https://es.games68.com/include/ruffle/43f8e1e34e0629f740121b10aab750da.wasm:wasm-function[3310]:0x341daf)
    at std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2 (https://es.games68.com/include/ruffle/43f8e1e34e0629f740121b10aab750da.wasm:wasm-function[3919]:0x35e91d)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925 (https://es.games68.com/include/ruffle/43f8e1e34e0629f740121b10aab750da.wasm:wasm-function[4655]:0x36e191)
    at rust_begin_unwind (https://es.games68.com/include/ruffle/43f8e1e34e0629f740121b10aab750da.wasm:wasm-function[4529]:0x36c811)
    at core::panicking::panic_fmt::h285dc015a87be5a4 (https://es.games68.com/include/ruffle/43f8e1e34e0629f740121b10aab750da.wasm:wasm-function[4657]:0x36e1f5)
    at core::option::expect_none_failed::hb95d2b1dc5448c17 (https://es.games68.com/include/ruffle/43f8e1e34e0629f740121b10aab750da.wasm:wasm-function[4000]:0x3611f4)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: games/5110321e45e9f.swf
Param movie: games/5110321e45e9f.swf
Param quality: high
Param allowScriptAccess: always
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://es.games68.com/games.php?id=2121706
SWF URL: https://es.games68.com/games/5110321e45e9f.swf

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-17
Channel: nightly
Built: 2021-01-17T01:05:59.152Z
Commit: c2b768c453f281a988c71a829e7a71bb106302fa

**Comment by Lord-McSweeney** [comment]
This seems to be working now
