### ISSUE TITLE
Error on https://math-worksheets.ruralanemone.repl.co/get/aHR0cHM6Ly93d3cuZ2FtZWZsYXJlLmNvbQ==/embed/raze-3/

### ISSUE THREAD

**Issue by unlockedperson** [ruffle-rs/ruffle#5619]
# Error Info
Error name: TypeError
Error message: str.startsWith is not a function
Error stack:
```
TypeError: str.startsWith is not a function
    at rewrite_url (https://math-worksheets.ruralanemone.repl.co/get/static/inject.js:9:13)
    at window.fetch (https://math-worksheets.ruralanemone.repl.co/get/static/inject.js:29:11)
    at r (https://math-worksheets.ruralanemone.repl.co/get/aHR0cHM6Ly93d3cuZ2FtZWZsYXJlLmNvbQ==/emulators/ruffle/ruffle.js?id=da8d984f7e8e19a42727:1:35852)
    at https://math-worksheets.ruralanemone.repl.co/get/aHR0cHM6Ly93d3cuZ2FtZWZsYXJlLmNvbQ==/emulators/ruffle/ruffle.js?id=da8d984f7e8e19a42727:1:38300
    at V (https://math-worksheets.ruralanemone.repl.co/get/aHR0cHM6Ly93d3cuZ2FtZWZsYXJlLmNvbQ==/emulators/ruffle/ruffle.js?id=da8d984f7e8e19a42727:1:38306)
    at HTMLElement.ensureFreshInstance (https://math-worksheets.ruralanemone.repl.co/get/aHR0cHM6Ly93d3cuZ2FtZWZsYXJlLmNvbQ==/emulators/ruffle/ruffle.js?id=da8d984f7e8e19a42727:1:50841)
    at HTMLElement.load (https://math-worksheets.ruralanemone.repl.co/get/aHR0cHM6Ly93d3cuZ2FtZWZsYXJlLmNvbQ==/emulators/ruffle/ruffle.js?id=da8d984f7e8e19a42727:1:53124)
    at HTMLDocument.<anonymous> (https://math-worksheets.ruralanemone.repl.co/get/aHR0cHM6Ly93d3cuZ2FtZWZsYXJlLmNvbQ==/embed/raze-3/:1170:36)
    at l (https://math-worksheets.ruralanemone.repl.co/get/aHR0cHM6Ly93d3cuZ2FtZWZsYXJlLmNvbQ==/js/jquery.min.js?id=23c7c5d2d1317508e807:1:29892)
    at c (https://math-worksheets.ruralanemone.repl.co/get/aHR0cHM6Ly93d3cuZ2FtZWZsYXJlLmNvbQ==/js/jquery.min.js?id=23c7c5d2d1317508e807:1:30194)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://math-worksheets.ruralanemone.repl.co/get/aHR0cHM6Ly93d3cuZ2FtZWZsYXJlLmNvbQ==/embed/raze-3/

# Browser Info
Useragent: Mozilla/5.0 (X11; CrOS x86_64 13982.88.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.162 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-10-13
Channel: nightly
Built: 2021-10-13T00:10:34.426Z
Commit: c0021204c6956ba61e869db3dfd2d9dadbe0bcd0
Is extension: false

**Comment by Poopooracoocoo** [comment]
![image](https://user-images.githubusercontent.com/51363864/140919167-431a2008-62c5-48a8-bb5d-6435be8b5ffb.png)
Website issue. Try reporting this to GameFlare
