### ISSUE TITLE
Error on https://f.kbhgames.com/2018/01/bookworm/

### ISSUE THREAD

**Issue by Rae1950** [ruffle-rs/ruffle#5623]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:494:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:494:50
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (https://f.kbhgames.com/RS/asset/ruffle.js:1:7036)
    at std::sync::once::Once::call_once::{{closure}}::h5387044f596cf17b (wasm-function[1003]:0x2f5687)
    at std::sync::once::Once::call_inner::h02a6489b0ecfb269 (wasm-function[1322]:0x363092)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h4461033b8c8249d8 (wasm-function[4587]:0x4ebe27)
    at std::panicking::rust_panic_with_hook::h364974e717ed59ec (wasm-function[3245]:0x4a7005)
    at rust_begin_unwind (wasm-function[4647]:0x4ee0b4)
    at core::panicking::panic_fmt::hf69c8b08bc9d2ee5 (wasm-function[4844]:0x4f8ac2)
    at core::result::unwrap_failed::h694db13a45aa6740 (wasm-function[3920]:0x4d48c5)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::ha4c5197dc5c7413f (wasm-function[719]:0x25e12c)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::register_glyph_shape::h0bbcf7ecf7272765 (wasm-function[1831]:0x3f1fb1)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: bookworm.swf
Param movie: bookworm.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined

# Page Info
Page URL: https://f.kbhgames.com/2018/01/bookworm/
SWF URL: https://f.kbhgames.com/2018/01/bookworm/bookworm.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-11-03
Channel: nightly
Built: 2021-11-03T00:13:12.329Z
Commit: 6c7d10e4d49ef0e155bc8027b6371c1217031796
Is extension: false

**Comment by Herschel** [comment]
Closing in favor of #1905
