### ISSUE TITLE
Error on https://horsemania24.github.io/radsciencegames.github.io/game5.html - Electric Man 2

### ISSUE THREAD

**Issue by HorseMania24** [ruffle-rs/ruffle#5641]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:849:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:849:18
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (https://horsemania24.github.io/radsciencegames.github.io/scripts/ruffle/ruffle.js:1:7036)
    at std::sync::once::Once::call_once::{{closure}}::h5387044f596cf17b (https://horsemania24.github.io/radsciencegames.github.io/scripts/ruffle/86c8cc086d5464b4c06b.wasm:wasm-function[996]:0x2e8fae)
    at std::sync::once::Once::call_inner::h02a6489b0ecfb269 (https://horsemania24.github.io/radsciencegames.github.io/scripts/ruffle/86c8cc086d5464b4c06b.wasm:wasm-function[1317]:0x356eec)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h4461033b8c8249d8 (https://horsemania24.github.io/radsciencegames.github.io/scripts/ruffle/86c8cc086d5464b4c06b.wasm:wasm-function[4669]:0x4f3798)
    at std::panicking::rust_panic_with_hook::h364974e717ed59ec (https://horsemania24.github.io/radsciencegames.github.io/scripts/ruffle/86c8cc086d5464b4c06b.wasm:wasm-function[3289]:0x4a355e)
    at rust_begin_unwind (https://horsemania24.github.io/radsciencegames.github.io/scripts/ruffle/86c8cc086d5464b4c06b.wasm:wasm-function[4731]:0x4f5c63)
    at core::panicking::panic_fmt::hf69c8b08bc9d2ee5 (https://horsemania24.github.io/radsciencegames.github.io/scripts/ruffle/86c8cc086d5464b4c06b.wasm:wasm-function[4942]:0x50099d)
    at core::panicking::panic::hceae0c79b0247f98 (https://horsemania24.github.io/radsciencegames.github.io/scripts/ruffle/86c8cc086d5464b4c06b.wasm:wasm-function[4665]:0x4f2fc9)
    at core::ops::function::FnOnce::call_once::hf99a08a7a8d58165 (https://horsemania24.github.io/radsciencegames.github.io/scripts/ruffle/86c8cc086d5464b4c06b.wasm:wasm-function[1040]:0x303f4f)
    at ruffle_core::avm1::function::Executable::exec::hc98df77004cccb4f (https://horsemania24.github.io/radsciencegames.github.io/scripts/ruffle/86c8cc086d5464b4c06b.wasm:wasm-function[417]:0x15dc61)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://horsemania24.github.io/radsciencegames.github.io/game5.html
SWF URL: https://horsemania24.github.io/radsciencegames.github.io/games/electricman2.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; CrOS x86_64 13982.89.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.173 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-11-11
Channel: nightly
Built: 2021-11-11T00:14:36.131Z
Commit: 60eb88b3265601d16467672a732081b30884707d
Is extension: false

**Comment by Poopooracoocoo** [comment]
#4932
