### ISSUE TITLE
Error on https://www.alloy-wfofficial.ga/get/aHR0cHM6Ly9rZGF0YTEuY29t/2016/06/bleach-vs-naruto-26/

### ISSUE THREAD

**Issue by XdHypex2479** [ruffle-rs/ruffle#5642]
# Error Info
Error name: TypeError
Error message: str.startsWith is not a function
Error stack:
```
TypeError: str.startsWith is not a function
    at rewrite_url (https://www.alloy-wfofficial.ga/get/static/inject.js:9:13)
    at window.fetch (https://www.alloy-wfofficial.ga/get/static/inject.js:29:11)
    at r (https://www.alloy-wfofficial.ga/get/aHR0cHM6Ly9rZGF0YTEuY29t/RS/asset/ruffle.js:1:36461)
    at https://www.alloy-wfofficial.ga/get/aHR0cHM6Ly9rZGF0YTEuY29t/RS/asset/ruffle.js:1:38909
    at q (https://www.alloy-wfofficial.ga/get/aHR0cHM6Ly9rZGF0YTEuY29t/RS/asset/ruffle.js:1:38915)
    at HTMLElement.ensureFreshInstance (https://www.alloy-wfofficial.ga/get/aHR0cHM6Ly9rZGF0YTEuY29t/RS/asset/ruffle.js:1:51460)
    at HTMLElement.load (https://www.alloy-wfofficial.ga/get/aHR0cHM6Ly9rZGF0YTEuY29t/RS/asset/ruffle.js:1:53789)
    at HTMLElement.connectedCallback (https://www.alloy-wfofficial.ga/get/aHR0cHM6Ly9rZGF0YTEuY29t/RS/asset/ruffle.js:1:73101)
    at Ee (https://www.alloy-wfofficial.ga/get/aHR0cHM6Ly9rZGF0YTEuY29t/RS/asset/ruffle.js:1:75268)
    at https://www.alloy-wfofficial.ga/get/aHR0cHM6Ly9rZGF0YTEuY29t/RS/asset/ruffle.js:1:81058
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: game.swf
Param movie: game.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined

# Page Info
Page URL: https://www.alloy-wfofficial.ga/get/aHR0cHM6Ly9rZGF0YTEuY29t/2016/06/bleach-vs-naruto-26/?1

# Browser Info
Useragent: Mozilla/5.0 (X11; CrOS x86_64 14150.74.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.114 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-11-03
Channel: nightly
Built: 2021-11-03T00:13:12.329Z
Commit: 6c7d10e4d49ef0e155bc8027b6371c1217031796
Is extension: false

**Comment by Poopooracoocoo** [comment]
https://kdata1.com/2016/06/bleach-vs-naruto-26/

**Comment by Lord-McSweeney** [comment]
Not an issue with Ruffle, and the site was using a version that is now 4 years outdated
