### ISSUE TITLE
Error on https://mysexgamer.com/game/bleach-christmas

### ISSUE THREAD

**Issue by 853718973** [ruffle-rs/ruffle#5667]
#Error Info nError名称：Error nError消息：惊慌失措地在`Result：：unack()‘上对“错误”值：JsValue(TypeError：未能获取nTypeError：未能获取)，web/src/Naviator.rs：189：18 nError堆栈：n``nError：慌乱at’Result：：un环绕()‘对`Err’值：JsValue(TypeError：未能获取nTypeError：未能获取)，Wwbg.__wbg._wbg_new_df6e6ab7a65c4c4d(https://mysexgamer.com/assets/ruffle/ruffle.js:1:7026)n at std：：sync：：once：：Once：：call_once：：{{closure}}：：h6e694fc45f651103(wasm-function[1085]：0x28c132)n at std：：sync：：once：：Once：：call_inner：：h99e47643887ee5a5(wasm-std：：sync：：once：：Once：：call_inner：：h99e47643887ee5a5[960]：0x26329f)n：ops：：function：：FnOnce：：call_once{{vtable.shim}}：：hb552ca3003b47989(wasm-function[3856]：0x41f24c)n at std：：panicking：：rust_panic_with_hook：：h03201bc01a0ed891(wasm-Function[3008]：0x3bacee)n at锈蚀_BEGIN_unwind(wasm-function[4064]：0x424b97)n在核心：：恐慌：：惊恐：：fmt：：hd44f353696296fec(wasm-function[4212]：0x42b594)n位于核心：：选项：：Expect_NONE_FMT：：hf7dab2706f1a5551(wasm-function[3448]：0x40d618)n位于<core：：future：：future：：Future>：：poll：：h120ccdeae3267ee4(wasm-function[579]：0x19b250)n at<core：：future：：future：：Future>：：poll：：h120ccdeae3267ee4(wasm-function[579]：0x19b250)n at<core：：future：：future：：Future>：：poll：：h120ccdeae3267ee4(wasm-Function[519]：0x177b85)n位于<core：未来：：FROM：：FROM<T>作为核心：：未来：*未来>：投票：：h72d7af3bf06f1fd6(wasm-function[1485]：0x2ee437)n at wasm_bindgen_futures：：queue：：Queue：：new：：{{closure}}：：h4014bfc4ca727422(wasm-function[2360]：0x385723)n at<dyn core：：ops：：function：fnMut<(A，)>+Output=R作为wasm_bindgen：：closure：：WasmClosure>：：describe：：invoke：：h69dd9711782f1b19(wasm-function[4352]：0x42d8e3)n at T(https://mysexgamer.com/assets/ruffle/ruffle.js:1:4150)n at a(https://mysexgamer.com/assets/ruffle/ruffle.js:1:2798)n`n`n#Player Info nAllow脚本访问：True nPlayer类型：Object nSWFURL：https://v8p5i7f9.ssl.hwcdn.net/games/swf/8/7/7/877c0284a2995511887027603d442924/877c0284a2995511887027603d442924.swf nParam电影：https://v8p5i7f9.ssl.hwcdn.net/games/swf/8/7/7/877c0284a2995511887027603d442924/877c0284a2995511887027603d442924.swf nParam质量：高nParambgcolor：#000000 nParamPlay：真nParamWMode：Window nParamWMode：Window nParamScale：showallnParam菜单：true nParamdevicefont：false nParamDevicefont：false nParamDevicefont：false nParamScale：AverynParamScale：Default nParamScale 0：UnfinednAttribute 1：未定义nAttribute 2：unfinednAttribute 3：未定义nAttribute 4：未定义nAttribute 5：未定义nAttribute 6：nn#页面nPage URL：https：//7/7/877c0284a2995511887027603d442924/877c0284a2995511887027603d442924.swf网址：https://v8p5i7f9.ssl.hwcdn.net/games/swf/8/7/7/877c0284a2995511887027603d442924/877c0284a2995511887027603d442924.swf n#Browser Info nUseragent：Mozilla/5.0(linux；安卓10；zh-CN；JER-AN20 Build/HUAWEIJER-AN20)AppleWebKit/537.36(KHTML，类似壁虎)版本/4.0 Chrome/77.0.3865.120 MQQBrowser/12.1 Mobile Safari/537.36 COVC/045717

**Comment by Poopooracoocoo** [comment]
@853718973 can you reproduce this when you use an up to date version of Chromium?
