### ISSUE TITLE
Error on https://web140.socialquantum.com/assets/app.html

### ISSUE THREAD

**Issue by QtekTaF** [ruffle-rs/ruffle#5751]
# Error Info
Error name: Error
Error message: panicked at 'assertion failed: min <= max', /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/cmp.rs:812:9
Error stack:
```
Error: panicked at 'assertion failed: min <= max', /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/cmp.rs:812:9
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://gncbkebmjbnhmkejeokeficddcjcldmn/dist/ruffle.js?id=4144607409:1:7628)
    at std::sync::once::Once::call_once::{{closure}}::h12990387e0d952cc (chrome-extension://gncbkebmjbnhmkejeokeficddcjcldmn/dist/f23674e433c64af70aca.wasm:wasm-function[989]:0x2dec55)
    at std::sync::once::Once::call_inner::h02a6489b0ecfb269 (chrome-extension://gncbkebmjbnhmkejeokeficddcjcldmn/dist/f23674e433c64af70aca.wasm:wasm-function[1327]:0x3515f5)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hc62fbac30903ce1c (chrome-extension://gncbkebmjbnhmkejeokeficddcjcldmn/dist/f23674e433c64af70aca.wasm:wasm-function[4695]:0x4f93db)
    at std::panicking::rust_panic_with_hook::h364974e717ed59ec (chrome-extension://gncbkebmjbnhmkejeokeficddcjcldmn/dist/f23674e433c64af70aca.wasm:wasm-function[3328]:0x4a8bc4)
    at rust_begin_unwind (chrome-extension://gncbkebmjbnhmkejeokeficddcjcldmn/dist/f23674e433c64af70aca.wasm:wasm-function[4757]:0x4fbb52)
    at core::panicking::panic_fmt::hf69c8b08bc9d2ee5 (chrome-extension://gncbkebmjbnhmkejeokeficddcjcldmn/dist/f23674e433c64af70aca.wasm:wasm-function[4964]:0x506727)
    at core::panicking::panic::hceae0c79b0247f98 (chrome-extension://gncbkebmjbnhmkejeokeficddcjcldmn/dist/f23674e433c64af70aca.wasm:wasm-function[4691]:0x4f8c0c)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::set_viewport_dimensions::h7c9939bb41c00eb0 (chrome-extension://gncbkebmjbnhmkejeokeficddcjcldmn/dist/f23674e433c64af70aca.wasm:wasm-function[689]:0x2379bc)
    at ruffle_web::Ruffle::tick::h25c1c8a4e720ca13 (chrome-extension://gncbkebmjbnhmkejeokeficddcjcldmn/dist/f23674e433c64af70aca.wasm:wasm-function[587]:0x1edf68)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: //cdn.tf.socialquantum.ru/files/loader11_od_prod_468.swf
Param allowfullscreen: true
Param allowFullScreenInteractive: true
Param allowscriptaccess: always
Param allownetworking: all
Param bgcolor: #FFFFFF
Param wmode: window
Param flashvars: container=true&web_server=https%3A%2F%2Fok.ru&first_start=0&logged_user_id=891977802154734911&sig=1cdaf653b0911e6642efe3046ff3efe7&refplace=vitrine_user_apps_portlet&new_sig=1&apiconnection=41984_1638033453956&authorized=1&session_key=-s-eF7Hfbx9jEZHj8MhDE8pkbuBEF8qk6-8DJfIhauGgpZIFZMkkJbGHZM9fo8HobR9gE9H-6OBfDdHiYMAep8uiey9jHWuoawGeFcNhdNc&clientLog=0&session_secret_key=a609d3ac34c85878919ca3c510d4ed39&auth_sig=cf3feaea5f60b2ef9f615871a5290205&api_server=https%3A%2F%2Fapi.ok.ru%2F&ip_geo_location=KZ%2C16%2CKokshetau&application_key=CBAFKBABABABABABA&sq_application_type=iframe&sq_major_version=32&sq_app_start_time=1638033454993&sq_first_install=false&sq_sid=308871842
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined

# Page Info
Page URL: https://web140.socialquantum.com/assets/app.html?container=true&web_server=https%3A%2F%2Fok.ru&first_start=0&logged_user_id=891977802154734911&sig=1cdaf653b0911e6642efe3046ff3efe7&refplace=vitrine_user_apps_portlet&new_sig=1&apiconnection=41984_1638033453956&authorized=1&session_key=-s-eF7Hfbx9jEZHj8MhDE8pkbuBEF8qk6-8DJfIhauGgpZIFZMkkJbGHZM9fo8HobR9gE9H-6OBfDdHiYMAep8uiey9jHWuoawGeFcNhdNc&clientLog=0&session_secret_key=a609d3ac34c85878919ca3c510d4ed39&auth_sig=cf3feaea5f60b2ef9f615871a5290205&api_server=https%3A%2F%2Fapi.ok.ru%2F&ip_geo_location=KZ%2C16%2CKokshetau&application_key=CBAFKBABABABABABA

# Browser Info
Useragent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-11-27
Channel: nightly
Built: 2021-11-27T00:12:38.118Z
Commit: e2b821e92fbea70bb8a845a289c44cc1a16cc919
Is extension: true

**Comment by QtekTaF** [comment]
Crome, https://ok.ru/game/fermer -> go to error load file "loader11_od_prod_468.swf".

**Comment by QtekTaF** [comment]
Ubuntu - don't Vulcan. No. Windows 7 - the error situation is repeated.

**Comment by Lord-McSweeney** [comment]
Should have been fixed by #6458 a long time ago
