### ISSUE TITLE
Error on http://dons-fun4all.com/forums/index.php?autocom=arcade&do=play&gameid=34021

### ISSUE THREAD

**Issue by XeenaJackson** [ruffle-rs/ruffle#5763]
# Error Info
Error name: Error
Error message: panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`: cannot recursively acquire mutex', /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys/wasm/../unsupported/mutex.rs:23:9
Error stack:
```
Error: panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`: cannot recursively acquire mutex', /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys/wasm/../unsupported/mutex.rs:23:9
    at Object.Z (http://dons-fun4all.com/forums/ruffle/core.ruffle.a63e1c79e919bd6509c7.js:1:21277)
    at __wbg_new_df6e6ab7a65c4c4d (http://dons-fun4all.com/forums/ruffle/ruffle.js:1:39257)
    at std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f (http://dons-fun4all.com/forums/ruffle/9787cfba420e7deb83df.module.wasm:wasm-function[1274]:0x264cdf)
    at std::sync::once::Once::call_inner::h02eac160d339afc2 (http://dons-fun4all.com/forums/ruffle/9787cfba420e7deb83df.module.wasm:wasm-function[1538]:0x295324)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801 (http://dons-fun4all.com/forums/ruffle/9787cfba420e7deb83df.module.wasm:wasm-function[4317]:0x36a68d)
    at std::panicking::rust_panic_with_hook::h123718ba3bf480af (http://dons-fun4all.com/forums/ruffle/9787cfba420e7deb83df.module.wasm:wasm-function[3314]:0x343811)
    at std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2 (http://dons-fun4all.com/forums/ruffle/9787cfba420e7deb83df.module.wasm:wasm-function[3925]:0x3604fb)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925 (http://dons-fun4all.com/forums/ruffle/9787cfba420e7deb83df.module.wasm:wasm-function[4659]:0x36fcf7)
    at rust_begin_unwind (http://dons-fun4all.com/forums/ruffle/9787cfba420e7deb83df.module.wasm:wasm-function[4533]:0x36e366)
    at std::panicking::begin_panic_fmt::h96153d9dc0e882ed (http://dons-fun4all.com/forums/ruffle/9787cfba420e7deb83df.module.wasm:wasm-function[4629]:0x36f78f)
```

# Player Info
Allows script access: true

# Page Info
Page URL: http://dons-fun4all.com/forums/index.php?autocom=arcade&do=play&gameid=34021
SWF URL: http://dons-fun4all.com/forums/arcade/ArkadiumSkeeBall_v32.swf?ibpro_gameid=2619580

# Browser Info
Useragent: Mozilla/5.0 (Linux; Android 10; 100003561) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36
OS: Linux armv8l

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-14
Channel: nightly
Built: 2021-01-14T01:08:37.174Z
Commit: c1c1c59bb51d2d20d2e601b5e4ff75ddfca528cb

**Comment by Poopooracoocoo** [comment]
Note: Site requires login.

**Comment by Poopooracoocoo** [comment]
@XeenaJackson 
Could you ask the site administrators to update their version of Ruffle? It's very old. 
Your browser is also not up to date.

**Comment by XeenaJackson** [comment]
I will do this. Thank you very much ...

**Comment by Lord-McSweeney** [comment]
Closing as the SWF was run with a version of Ruffle that is now five years outdated
