### ISSUE TITLE
Error on https://skolavefurinn.is/system/files/skolavefurinn_efni/_opid/islenska/bokmenntir/letlestur/aefingar1/index_bok1.html

### ISSUE THREAD

**Issue by dev-arunraja** [ruffle-rs/ruffle#5769]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:490:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:490:50
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://skolavefurinn.is/ruffle_nightly_2021_02_14_selfhosted/ruffle.js:1:6799)
    at std::sync::once::Once::call_once::{{closure}}::hce6501f6f20767e4 (wasm://wasm/0124c336:wasm-function[1327]:0x26ba91)
    at std::sync::once::Once::call_inner::hd3d269a4946f2df2 (wasm://wasm/0124c336:wasm-function[1604]:0x29efac)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h6ed7686ed76cb258 (wasm://wasm/0124c336:wasm-function[4639]:0x3823e3)
    at std::panicking::rust_panic_with_hook::h4f753dc70b771d8e (wasm://wasm/0124c336:wasm-function[3509]:0x357cb7)
    at std::panicking::begin_panic_handler::{{closure}}::h5c9fc29957309ae8 (wasm://wasm/0124c336:wasm-function[4146]:0x37594f)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h92808941d97e9b21 (wasm://wasm/0124c336:wasm-function[4985]:0x387ab4)
    at rust_begin_unwind (wasm://wasm/0124c336:wasm-function[4870]:0x3863b1)
    at core::panicking::panic_fmt::hbd8a975261a5f466 (wasm://wasm/0124c336:wasm-function[4986]:0x387aea)
    at core::option::expect_none_failed::hbea1e2e5b59d80cc (wasm://wasm/0124c336:wasm-function[4244]:0x378a28)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://skolavefurinn.is/system/files/skolavefurinn_efni/_opid/islenska/bokmenntir/letlestur/aefingar1/index_bok1.html
SWF URL: https://skolavefurinn.is/system/files/skolavefurinn_efni/_opid/islenska/bokmenntir/letlestur/aefingar1/bok1_staerra_1.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-02-14
Channel: nightly
Built: 2021-02-14T00:19:03.523Z
Commit: ecd873eb39c141f9bf2e41454c7a47d5f7e9507c

**Comment by Poopooracoocoo** [comment]
Note: SWF URL requires login.

@dev-arunraja Could you contact the website administrator and ask them to update Ruffle and keep it up to date regularly? The issue may get fixed.

**Comment by Herschel** [comment]
Closing in favor of #1905
