### ISSUE TITLE
Error on https://sbx2.manzschulbuch.at/docpool/manz/oa/y0gb5lpkz/9783706853927.html

### ISSUE THREAD

**Issue by FebriBen** [ruffle-rs/ruffle#5789]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: UnquotedValue(23)', core/src/html/text_format.rs:620:55
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: UnquotedValue(23)', core/src/html/text_format.rs:620:55
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://hnmcfnnelmkigilmoolnoaomapakfede/dist/ruffle.js?id=77799272291:1:7628)
    at std::sync::once::Once::call_once::{{closure}}::h6f6ea56fd6eb0153 (chrome-extension://hnmcfnnelmkigilmoolnoaomapakfede/dist/8abf0a0ffc50a9f61348.wasm:wasm-function[999]:0x3022e9)
    at std::sync::once::Once::call_inner::h02a6489b0ecfb269 (chrome-extension://hnmcfnnelmkigilmoolnoaomapakfede/dist/8abf0a0ffc50a9f61348.wasm:wasm-function[1359]:0x37fe26)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::he60880e8d4402e2b (chrome-extension://hnmcfnnelmkigilmoolnoaomapakfede/dist/8abf0a0ffc50a9f61348.wasm:wasm-function[4748]:0x50ef4e)
    at std::panicking::rust_panic_with_hook::h364974e717ed59ec (chrome-extension://hnmcfnnelmkigilmoolnoaomapakfede/dist/8abf0a0ffc50a9f61348.wasm:wasm-function[3359]:0x4c7423)
    at rust_begin_unwind (chrome-extension://hnmcfnnelmkigilmoolnoaomapakfede/dist/8abf0a0ffc50a9f61348.wasm:wasm-function[4809]:0x5115ba)
    at core::panicking::panic_fmt::hf69c8b08bc9d2ee5 (chrome-extension://hnmcfnnelmkigilmoolnoaomapakfede/dist/8abf0a0ffc50a9f61348.wasm:wasm-function[5017]:0x51c179)
    at core::result::unwrap_failed::h694db13a45aa6740 (chrome-extension://hnmcfnnelmkigilmoolnoaomapakfede/dist/8abf0a0ffc50a9f61348.wasm:wasm-function[4068]:0x4f7efc)
    at ruffle_core::html::text_format::FormatSpans::from_html::{{closure}}::h464c4b6d371523f1 (chrome-extension://hnmcfnnelmkigilmoolnoaomapakfede/dist/8abf0a0ffc50a9f61348.wasm:wasm-function[1982]:0x4153b4)
    at ruffle_core::html::text_format::FormatSpans::from_html::h78b0dffe68e42df1 (chrome-extension://hnmcfnnelmkigilmoolnoaomapakfede/dist/8abf0a0ffc50a9f61348.wasm:wasm-function[322]:0x96c7d)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://sbx2.manzschulbuch.at/docpool/manz/oa/y0gb5lpkz/9783706853927.html
SWF URL: https://sbx2.manzschulbuch.at/docpool/manz/general/oa/oa.swf

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-12-02
Channel: nightly
Built: 2021-12-02T00:11:23.895Z
Commit: e3dfeb5a44c3a728cfe50642e480f3ea3498c099
Is extension: true

**Comment by adrian17** [comment]
@relrelb

**Comment by relrelb** [comment]
Another unrelated but interesting bug - This SWF triggers an integer overflow, which panics on debug builds.
