### ISSUE TITLE
Error on https://billiesbluestheplay.com/index-1.html

### ISSUE THREAD

**Issue by coucouvitis** [ruffle-rs/ruffle#5818]
firefox on linux manjaro, & linux mint ( 19.3 & 20.04): works w/o error
linux chromium under manjaro generated the error msg below
chromium on linux mint and edge on windows 10 shows a play button for the audio;
     the video is not rendered at all
the web-page is https://billiebluestheplay.com/index-1.html
the 'script' has been added to the .htaccess
----------------------------
# Error Info
Error name: Error
Error message: panicked at 'assertion failed: min <= max', /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/cmp.rs:816:9
Error stack:
```
Error: panicked at 'assertion failed: min <= max', /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/cmp.rs:816:9
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (https://billiesbluestheplay.com/js/ruffle.js:1:7628)
    at std::sync::once::Once::call_once::{{closure}}::h28627feee31e90eb (https://billiesbluestheplay.com/js/510213222482c40adc6b.wasm:wasm-function[1040]:0x31af69)
    at std::sync::once::Once::call_inner::hf9144d66ddc67dec (https://billiesbluestheplay.com/js/510213222482c40adc6b.wasm:wasm-function[1252]:0x3750ae)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::ha861918671b1460e (https://billiesbluestheplay.com/js/510213222482c40adc6b.wasm:wasm-function[4757]:0x521a55)
    at std::panicking::rust_panic_with_hook::h606d7c7f7a423b98 (https://billiesbluestheplay.com/js/510213222482c40adc6b.wasm:wasm-function[3335]:0x4db0b4)
    at rust_begin_unwind (https://billiesbluestheplay.com/js/510213222482c40adc6b.wasm:wasm-function[4820]:0x524329)
    at core::panicking::panic_fmt::h6314b5c91abe7349 (https://billiesbluestheplay.com/js/510213222482c40adc6b.wasm:wasm-function[5031]:0x52eeae)
    at core::panicking::panic::hec1fc057bd0baf0b (https://billiesbluestheplay.com/js/510213222482c40adc6b.wasm:wasm-function[4754]:0x5212bb)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::set_viewport_dimensions::h46de69d1e9946036 (https://billiesbluestheplay.com/js/510213222482c40adc6b.wasm:wasm-function[718]:0x2734b9)
    at ruffle_web::Ruffle::tick::hb2b3b01b33be7c87 (https://billiesbluestheplay.com/js/510213222482c40adc6b.wasm:wasm-function[605]:0x22083e)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: intro.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined

# Page Info
Page URL: https://billiesbluestheplay.com/index-1.html

# Browser Info
Useragent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-12-05
Channel: nightly
Built: 2021-12-05T00:13:33.026Z
Commit: 0b6cd454155ec9ecd4aef425055e44110240cc8a
Is extension: false

**Comment by Lord-McSweeney** [comment]
Should have been fixed by #6458 a long time ago
