### ISSUE TITLE
Error on https://perso.crans.org/geneau/NewCligne/ressources/1_sche_cine_base_cours

### ISSUE THREAD

**Issue by Amineham-prog** [ruffle-rs/ruffle#5820]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:499:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:499:50
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://perso.crans.org/geneau/NewCligne/ruffle/ruffle.js:1:7026)
    at std::sync::once::Once::call_once::{{closure}}::h6e694fc45f651103 (https://perso.crans.org/geneau/NewCligne/ruffle/7ffcd216fe492199a010.wasm:wasm-function[1074]:0x27f4c3)
    at std::sync::once::Once::call_inner::h99e47643887ee5a5 (https://perso.crans.org/geneau/NewCligne/ruffle/7ffcd216fe492199a010.wasm:wasm-function[948]:0x25807b)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hb552ca3003b47989 (https://perso.crans.org/geneau/NewCligne/ruffle/7ffcd216fe492199a010.wasm:wasm-function[3824]:0x406344)
    at std::panicking::rust_panic_with_hook::h03201bc01a0ed891 (https://perso.crans.org/geneau/NewCligne/ruffle/7ffcd216fe492199a010.wasm:wasm-function[2973]:0x3a7749)
    at rust_begin_unwind (https://perso.crans.org/geneau/NewCligne/ruffle/7ffcd216fe492199a010.wasm:wasm-function[4032]:0x40be6e)
    at core::panicking::panic_fmt::hd44f353696296fec (https://perso.crans.org/geneau/NewCligne/ruffle/7ffcd216fe492199a010.wasm:wasm-function[4180]:0x4128fe)
    at core::option::expect_none_failed::hf7dab2706f1a5551 (https://perso.crans.org/geneau/NewCligne/ruffle/7ffcd216fe492199a010.wasm:wasm-function[3408]:0x3f4696)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::hd0177d89d3ee36e6 (https://perso.crans.org/geneau/NewCligne/ruffle/7ffcd216fe492199a010.wasm:wasm-function[595]:0x1a5321)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::register_glyph_shape::h4e5da350d1cdad7d (https://perso.crans.org/geneau/NewCligne/ruffle/7ffcd216fe492199a010.wasm:wasm-function[2168]:0x362797)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://perso.crans.org/geneau/NewCligne/ressources/1_sche_cine_base_cours
SWF URL: https://perso.crans.org/geneau/NewCligne/ressources/1_sche_cine_base_cours.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-05-22
Channel: nightly
Built: 2021-05-22T00:13:24.653Z
Commit: 7717b97027019f7194999cdbc6b13f6520a2dc19

**Comment by Herschel** [comment]
Closing in favor of #1905
