### ISSUE TITLE
Error on https://simplehai.axisdirect.in/dynamicWeb/demo/TradingUser/index.html

### ISSUE THREAD

**Issue by ghosh7ananta** [ruffle-rs/ruffle#5836]
# Error Info
Error name: Error
Error message: panicked at 'assertion failed: min <= max', /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/cmp.rs:816:9
Error stack:
```
Error: panicked at 'assertion failed: min <= max', /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/cmp.rs:816:9
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://kajnjoilalegembnngbploibablhhaoa/dist/ruffle.js?id=52318788086:1:7628)
    at std::sync::once::Once::call_once::{{closure}}::h8b88e6aa08fbb40d (chrome-extension://kajnjoilalegembnngbploibablhhaoa/dist/71199bf3d6612d1d1121.wasm:wasm-function[1024]:0x3225bd)
    at std::sync::once::Once::call_inner::hf9144d66ddc67dec (chrome-extension://kajnjoilalegembnngbploibablhhaoa/dist/71199bf3d6612d1d1121.wasm:wasm-function[1239]:0x3698bd)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h3ab0488d22755852 (chrome-extension://kajnjoilalegembnngbploibablhhaoa/dist/71199bf3d6612d1d1121.wasm:wasm-function[4738]:0x529f01)
    at std::panicking::rust_panic_with_hook::h606d7c7f7a423b98 (chrome-extension://kajnjoilalegembnngbploibablhhaoa/dist/71199bf3d6612d1d1121.wasm:wasm-function[3347]:0x4e3c97)
    at rust_begin_unwind (chrome-extension://kajnjoilalegembnngbploibablhhaoa/dist/71199bf3d6612d1d1121.wasm:wasm-function[4801]:0x52b622)
    at core::panicking::panic_fmt::h6314b5c91abe7349 (chrome-extension://kajnjoilalegembnngbploibablhhaoa/dist/71199bf3d6612d1d1121.wasm:wasm-function[5014]:0x53629d)
    at core::panicking::panic::hec1fc057bd0baf0b (chrome-extension://kajnjoilalegembnngbploibablhhaoa/dist/71199bf3d6612d1d1121.wasm:wasm-function[4735]:0x529767)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::set_viewport_dimensions::h090030320a082c98 (chrome-extension://kajnjoilalegembnngbploibablhhaoa/dist/71199bf3d6612d1d1121.wasm:wasm-function[694]:0x25a0ab)
    at ruffle_web::Ruffle::tick::h98d8d54201e811f2 (chrome-extension://kajnjoilalegembnngbploibablhhaoa/dist/71199bf3d6612d1d1121.wasm:wasm-function[581]:0x208e34)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://simplehai.axisdirect.in/dynamicWeb/demo/TradingUser/index.html

# Browser Info
Useragent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-12-10
Channel: nightly
Built: 2021-12-10T00:15:07.261Z
Commit: ce2eff8b258e0911c3b800ce8385f3fb68710be8
Is extension: true

**Comment by Lord-McSweeney** [comment]
Should have been fixed by #6458 a long time ago
