### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by Neospood** [ruffle-rs/ruffle#5866]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:862:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:862:18
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (https://uploads.ungrounded.net/ruffle_wrapper/lib/ruffle.js?1639324228:1:7628)
    at std::sync::once::Once::call_once::{{closure}}::h8b88e6aa08fbb40d (https://uploads.ungrounded.net/ruffle_wrapper/lib/731179ae1716fbb60e1c.wasm:wasm-function[986]:0x309429)
    at std::sync::once::Once::call_inner::hf9144d66ddc67dec (https://uploads.ungrounded.net/ruffle_wrapper/lib/731179ae1716fbb60e1c.wasm:wasm-function[1175]:0x34d23f)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h3ab0488d22755852 (https://uploads.ungrounded.net/ruffle_wrapper/lib/731179ae1716fbb60e1c.wasm:wasm-function[4623]:0x4f98ff)
    at std::panicking::rust_panic_with_hook::h606d7c7f7a423b98 (https://uploads.ungrounded.net/ruffle_wrapper/lib/731179ae1716fbb60e1c.wasm:wasm-function[3217]:0x4b37c5)
    at rust_begin_unwind (https://uploads.ungrounded.net/ruffle_wrapper/lib/731179ae1716fbb60e1c.wasm:wasm-function[4686]:0x4fb01d)
    at core::panicking::panic_fmt::h6314b5c91abe7349 (https://uploads.ungrounded.net/ruffle_wrapper/lib/731179ae1716fbb60e1c.wasm:wasm-function[4896]:0x505b86)
    at core::panicking::panic::hec1fc057bd0baf0b (https://uploads.ungrounded.net/ruffle_wrapper/lib/731179ae1716fbb60e1c.wasm:wasm-function[4620]:0x4f9165)
    at core::ops::function::FnOnce::call_once::hf2847eaac0d0b0dc (https://uploads.ungrounded.net/ruffle_wrapper/lib/731179ae1716fbb60e1c.wasm:wasm-function[1033]:0x3257ec)
    at ruffle_core::avm1::function::Executable::exec::hd3e79afc52b5b7a9 (https://uploads.ungrounded.net/ruffle_wrapper/lib/731179ae1716fbb60e1c.wasm:wasm-function[437]:0x194baa)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.64&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1639324228%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F526000%2F526470_beastgame_ng.swf%3F1381183836%22%2C%22vars%22%3A%7B%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%2261b9e23631ee2%22%2C%22NewgroundsAPI_SessionID%22%3A%22%22%2C%22NewgroundsAPI_UserName%22%3A%22%26lt%3Bdeleted%26gt%3B%22%2C%22NewgroundsAPI_UserID%22%3A0%2C%22ng_username%22%3A%22%26lt%3Bdeleted%26gt%3B%22%7D%2C%22width%22%3A640%2C%22height%22%3A480%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F526000%2Fflash_526470_card.png%3Ff1610478129%22%7D
SWF URL: https://uploads.ungrounded.net/526000/526470_beastgame_ng.swf?1381183836

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-12-12
Channel: nightly
Built: 2021-12-12T00:14:30.969Z
Commit: 1f5979f1681cd886e0e2b8245ec43190175b58ba
Is extension: false

**Comment by Poopooracoocoo** [comment]
Duplicate if #3756
