### ISSUE TITLE
Error on https://6935-kumquat-toad-y0qcfbln.ws-us23.gitpod.io/get/aHR0cHM6Ly91cGxvYWRzLnVuZ3JvdW5kZWQubmV0/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by ianbrandt975** [ruffle-rs/ruffle#5867]
# Error Info
Error name: TypeError
Error message: str.startsWith is not a function
Error stack:
```
TypeError: str.startsWith is not a function
    at rewrite_url (https://6935-kumquat-toad-y0qcfbln.ws-us23.gitpod.io/get/static/inject.js:9:13)
    at window.fetch (https://6935-kumquat-toad-y0qcfbln.ws-us23.gitpod.io/get/static/inject.js:29:11)
    at r (https://6935-kumquat-toad-y0qcfbln.ws-us23.gitpod.io/get/aHR0cHM6Ly91cGxvYWRzLnVuZ3JvdW5kZWQubmV0/ruffle_wrapper/lib/ruffle.js?1639324228:1:36540)
    at https://6935-kumquat-toad-y0qcfbln.ws-us23.gitpod.io/get/aHR0cHM6Ly91cGxvYWRzLnVuZ3JvdW5kZWQubmV0/ruffle_wrapper/lib/ruffle.js?1639324228:1:38988
    at q (https://6935-kumquat-toad-y0qcfbln.ws-us23.gitpod.io/get/aHR0cHM6Ly91cGxvYWRzLnVuZ3JvdW5kZWQubmV0/ruffle_wrapper/lib/ruffle.js?1639324228:1:38994)
    at HTMLElement.ensureFreshInstance (https://6935-kumquat-toad-y0qcfbln.ws-us23.gitpod.io/get/aHR0cHM6Ly91cGxvYWRzLnVuZ3JvdW5kZWQubmV0/ruffle_wrapper/lib/ruffle.js?1639324228:1:51719)
    at HTMLElement.load (https://6935-kumquat-toad-y0qcfbln.ws-us23.gitpod.io/get/aHR0cHM6Ly91cGxvYWRzLnVuZ3JvdW5kZWQubmV0/ruffle_wrapper/lib/ruffle.js?1639324228:1:54092)
    at preReqUpdated (https://6935-kumquat-toad-y0qcfbln.ws-us23.gitpod.io/get/aHR0cHM6Ly91cGxvYWRzLnVuZ3JvdW5kZWQubmV0/ruffle_wrapper/ruffleembed.html?v=1.0.64&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1639324228%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F592000%2F592473_MadnessGame_ULTIMATE.swf%3F1507662264%22%2C%22vars%22%3A%7B%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%2261ba180b68c43%22%2C%22NewgroundsAPI_SessionID%22%3A%22%22%2C%22NewgroundsAPI_UserName%22%3A%22%26lt%3Bdeleted%26gt%3B%22%2C%22NewgroundsAPI_UserID%22%3A0%2C%22ng_username%22%3A%22%26lt%3Bdeleted%26gt%3B%22%7D%2C%22width%22%3A850%2C%22height%22%3A530%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F592000%2Fflash_592473_card.png%3Ff1608170534%22%7D:123:14)
    at HTMLAudioElement.<anonymous> (https://6935-kumquat-toad-y0qcfbln.ws-us23.gitpod.io/get/aHR0cHM6Ly91cGxvYWRzLnVuZ3JvdW5kZWQubmV0/ruffle_wrapper/ruffleembed.html?v=1.0.64&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1639324228%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F592000%2F592473_MadnessGame_ULTIMATE.swf%3F1507662264%22%2C%22vars%22%3A%7B%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%2261ba180b68c43%22%2C%22NewgroundsAPI_SessionID%22%3A%22%22%2C%22NewgroundsAPI_UserName%22%3A%22%26lt%3Bdeleted%26gt%3B%22%2C%22NewgroundsAPI_UserID%22%3A0%2C%22ng_username%22%3A%22%26lt%3Bdeleted%26gt%3B%22%7D%2C%22width%22%3A850%2C%22height%22%3A530%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F592000%2Fflash_592473_card.png%3Ff1608170534%22%7D:183:7)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://6935-kumquat-toad-y0qcfbln.ws-us23.gitpod.io/get/aHR0cHM6Ly91cGxvYWRzLnVuZ3JvdW5kZWQubmV0/ruffle_wrapper/ruffleembed.html?v=1.0.64&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1639324228%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F592000%2F592473_MadnessGame_ULTIMATE.swf%3F1507662264%22%2C%22vars%22%3A%7B%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%2261ba180b68c43%22%2C%22NewgroundsAPI_SessionID%22%3A%22%22%2C%22NewgroundsAPI_UserName%22%3A%22%26lt%3Bdeleted%26gt%3B%22%2C%22NewgroundsAPI_UserID%22%3A0%2C%22ng_username%22%3A%22%26lt%3Bdeleted%26gt%3B%22%7D%2C%22width%22%3A850%2C%22height%22%3A530%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F592000%2Fflash_592473_card.png%3Ff1608170534%22%7D

# Browser Info
Useragent: Mozilla/5.0 (X11; CrOS x86_64 14092.77.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.107 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-12-12
Channel: nightly
Built: 2021-12-12T00:14:30.969Z
Commit: 1f5979f1681cd886e0e2b8245ec43190175b58ba
Is extension: false

**Comment by Lord-McSweeney** [comment]
Not an issue with Ruffle, and the site was using a version that is now 4 years outdated
