### ISSUE TITLE
Error on https://ruffle.rs/demo/ with Epic privacy browser

### ISSUE THREAD

**Issue by jsesh12** [ruffle-rs/ruffle#5894]
I'm using the Epic privacy browser; it's chromium and I have the ruffle extension installed but am unable to successfully run a swf on any website

# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: JsValue(TypeError: h(...).createBuffer is not a function
TypeError: h(...).createBuffer is not a function
    at https://ruffle.rs/demo/index.js:1:29427
    at z (https://ruffle.rs/demo/index.js:1:14062)
    at r.wbg.__wbg_createBuffer_79833a4052d7b42a (https://ruffle.rs/demo/index.js:1:29392)
    at web_sys::features::gen_AudioContext::AudioContext::create_buffer::hcdde228961bf60e3 (https://ruffle.rs/demo/9ccd222c768c77f17e68.wasm:wasm-function[4739]:0x51c771)
    at ruffle_web::audio::WebAudioBackend::decompress_to_audio_buffer::h34834f1125f162c9 (https://ruffle.rs/demo/9ccd222c768c77f17e68.wasm:wasm-function[515]:0x1a8ef1)
    at <ruffle_web::audio::WebAudioBackend as ruffle_core::backend::audio::AudioBackend>::register_sound::ha25a76e4fa3ff6cd (https://ruffle.rs/demo/9ccd222c768c77f17e68.wasm:wasm-function[2347]:0x449cba)
    at ruffle_core::display_object::movie_clip::MovieClip::preload::hf7c5ceb34d843d15 (https://ruffle.rs/demo/9ccd222c768c77f17e68.wasm:wasm-function[860]:0x2a9bda)
    at ruffle_core::player::Player::set_root_movie::hd715aedac84b4a86 (https://ruffle.rs/demo/9ccd222c768c77f17e68.wasm:wasm-function[393]:0x10a5a4)
    at <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hb2626e2e0f7dee3d (https://ruffle.rs/demo/9ccd222c768c77f17e68.wasm:wasm-function[592]:0x203296)
    at <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h323deb15990a3a73 (https://ruffle.rs/demo/9ccd222c768c77f17e68.wasm:wasm-function[1781]:0x3e5312))', web/src/audio.rs:739:14
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: JsValue(TypeError: h(...).createBuffer is not a function
TypeError: h(...).createBuffer is not a function
    at https://ruffle.rs/demo/index.js:1:29427
    at z (https://ruffle.rs/demo/index.js:1:14062)
    at r.wbg.__wbg_createBuffer_79833a4052d7b42a (https://ruffle.rs/demo/index.js:1:29392)
    at web_sys::features::gen_AudioContext::AudioContext::create_buffer::hcdde228961bf60e3 (https://ruffle.rs/demo/9ccd222c768c77f17e68.wasm:wasm-function[4739]:0x51c771)
    at ruffle_web::audio::WebAudioBackend::decompress_to_audio_buffer::h34834f1125f162c9 (https://ruffle.rs/demo/9ccd222c768c77f17e68.wasm:wasm-function[515]:0x1a8ef1)
    at <ruffle_web::audio::WebAudioBackend as ruffle_core::backend::audio::AudioBackend>::register_sound::ha25a76e4fa3ff6cd (https://ruffle.rs/demo/9ccd222c768c77f17e68.wasm:wasm-function[2347]:0x449cba)
    at ruffle_core::display_object::movie_clip::MovieClip::preload::hf7c5ceb34d843d15 (https://ruffle.rs/demo/9ccd222c768c77f17e68.wasm:wasm-function[860]:0x2a9bda)
    at ruffle_core::player::Player::set_root_movie::hd715aedac84b4a86 (https://ruffle.rs/demo/9ccd222c768c77f17e68.wasm:wasm-function[393]:0x10a5a4)
    at <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hb2626e2e0f7dee3d (https://ruffle.rs/demo/9ccd222c768c77f17e68.wasm:wasm-function[592]:0x203296)
    at <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h323deb15990a3a73 (https://ruffle.rs/demo/9ccd222c768c77f17e68.wasm:wasm-function[1781]:0x3e5312))', web/src/audio.rs:739:14
    at r.wbg.__wbg_new_df6e6ab7a65c4c4d (https://ruffle.rs/demo/index.js:1:17269)
    at std::sync::once::Once::call_once::{{closure}}::hb176d9ca4b52f458 (https://ruffle.rs/demo/9ccd222c768c77f17e68.wasm:wasm-function[1043]:0x3126a9)
    at std::sync::once::Once::call_inner::hf9144d66ddc67dec (https://ruffle.rs/demo/9ccd222c768c77f17e68.wasm:wasm-function[1239]:0x356807)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h68060cde5ebde89c (https://ruffle.rs/demo/9ccd222c768c77f17e68.wasm:wasm-function[4881]:0x51fd2e)
    at std::panicking::rust_panic_with_hook::h606d7c7f7a423b98 (https://ruffle.rs/demo/9ccd222c768c77f17e68.wasm:wasm-function[3372]:0x4cabac)
    at rust_begin_unwind (https://ruffle.rs/demo/9ccd222c768c77f17e68.wasm:wasm-function[4953]:0x524eda)
    at core::panicking::panic_fmt::h6314b5c91abe7349 (https://ruffle.rs/demo/9ccd222c768c77f17e68.wasm:wasm-function[5176]:0x530088)
    at core::result::unwrap_failed::hd584efb7b84bf326 (https://ruffle.rs/demo/9ccd222c768c77f17e68.wasm:wasm-function[4164]:0x5079a2)
    at ruffle_web::audio::WebAudioBackend::decompress_to_audio_buffer::h34834f1125f162c9 (https://ruffle.rs/demo/9ccd222c768c77f17e68.wasm:wasm-function[515]:0x1a92e7)
    at <ruffle_web::audio::WebAudioBackend as ruffle_core::backend::audio::AudioBackend>::register_sound::ha25a76e4fa3ff6cd (https://ruffle.rs/demo/9ccd222c768c77f17e68.wasm:wasm-function[2347]:0x449cba)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://ruffle.rs/demo/
SWF URL: https://ruffle.rs/demo/swfs/bitey1.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-12-18
Channel: nightly
Built: 2021-12-18T00:13:10.207Z
Commit: a25a25adbcb8aa3440ba12ddf5a65b381eeae881
Is extension: false

**Comment by Poopooracoocoo** [comment]
You should also make a post on their forum if you haven't already. https://forum.epicbrowser.com/viewforum.php?id=8
Chances are that they disable something that Ruffle uses. I reckon it's the AudioContext API. Ruffle doesn't [officially support ](https://github.com/ruffle-rs/ruffle/wiki)browsers that disable functionality like Epic and Tor.

**Comment by jsesh12** [comment]
@Poopooracoocoo , thanks for the info. I'll make a post on Epic's forum as well.
