### ISSUE TITLE
Error on https://www.gamenora.com/upload/games/swf/Driving%20Force%204/

### ISSUE THREAD

**Issue by Github2503** [ruffle-rs/ruffle#5911]
# Error Info
Error name: Error
Error message: panicked at 'index out of bounds: the len is 2 but the index is 2', /home/runner/.cargo/git/checkouts/nihav-vp6-660fee9efdd4622a/9416fcc/nihav-duck/src/codecs/vp56.rs:1032:12
Error stack:
```
Error: panicked at 'index out of bounds: the len is 2 but the index is 2', /home/runner/.cargo/git/checkouts/nihav-vp6-660fee9efdd4622a/9416fcc/nihav-duck/src/codecs/vp56.rs:1032:12
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (https://www.gamenora.com/upload/games/swf/ruffle.js:1:6869)
    at std::sync::once::Once::call_once::{{closure}}::h0f65e93e537a4a81 (https://www.gamenora.com/upload/games/swf/d0c41fcabf02fbab0f7e.wasm:wasm-function[1029]:0x2ca4dc)
    at std::sync::once::Once::call_inner::hc44ad7f626385660 (https://www.gamenora.com/upload/games/swf/d0c41fcabf02fbab0f7e.wasm:wasm-function[1292]:0x327b82)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h6ca12c217eb2f4f2 (https://www.gamenora.com/upload/games/swf/d0c41fcabf02fbab0f7e.wasm:wasm-function[4386]:0x4be0f9)
    at std::panicking::rust_panic_with_hook::he9bfe03219d715ba (https://www.gamenora.com/upload/games/swf/d0c41fcabf02fbab0f7e.wasm:wasm-function[3223]:0x456ff8)
    at rust_begin_unwind (https://www.gamenora.com/upload/games/swf/d0c41fcabf02fbab0f7e.wasm:wasm-function[4618]:0x4c41ea)
    at core::panicking::panic_fmt::hbf21a3d4bbb82bf8 (https://www.gamenora.com/upload/games/swf/d0c41fcabf02fbab0f7e.wasm:wasm-function[4811]:0x4cb8a4)
    at core::panicking::panic_bounds_check::h808b524af17640b1 (https://www.gamenora.com/upload/games/swf/d0c41fcabf02fbab0f7e.wasm:wasm-function[4089]:0x4b4045)
    at nihav_duck::codecs::vp56::VP56Decoder::predict_dc::h35fa849b15a15e38 (https://www.gamenora.com/upload/games/swf/d0c41fcabf02fbab0f7e.wasm:wasm-function[1170]:0x303dc3)
    at nihav_duck::codecs::vp56::VP56Decoder::decode_planes::he6f557e7194bd904 (https://www.gamenora.com/upload/games/swf/d0c41fcabf02fbab0f7e.wasm:wasm-function[308]:0x5f31e)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.gamenora.com/upload/games/swf/Driving%20Force%204/
SWF URL: https://www.gamenora.com/upload/games/swf/Driving%20Force%204/driving_force_4.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; CrOS x86_64 14324.41.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4692.53 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-10-12
Channel: nightly
Built: 2021-10-12T00:14:48.831Z
Commit: 60ef1ba38b21ceb244b5925f80310d87b9bf6c7f
Is extension: false

**Comment by torokati44** [comment]
Thanks for the report!
Do you perhaps remember what you did, or what was happening in the game, in the moment the error happened?
Any small detail can matter...
Or can you perhaps reproduce the error on purpose? That would help us a lot in finding and fixing the cause of this crash.

**Comment by torokati44** [comment]
To reproduce:
- Get through the tutorial
- Select one of the missions (I chose the bottom right mission on the first - already available - level, called "Quick ...something")
- Keep hitting the other cars
- When the damage meter is almost full, hit the last car while driving on the right side, without nitro on the left side of its back, wrecking your own car
