### ISSUE TITLE
Error on https://www.superhry.cz/games/2277/

### ISSUE THREAD

**Issue by tereza-dev** [ruffle-rs/ruffle#5917]
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', core/src/avm2/object/function_object.rs:280:5
Error stack:
```
Error: panicked at 'already borrowed: BorrowMutError', core/src/avm2/object/function_object.rs:280:5
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (https://www.superhry.cz/js/ruffle_13-7-2021/ruffle.js:1:7476)
    at std::sync::once::Once::call_once::{{closure}}::h5df181b90ad904c1 (https://www.superhry.cz/js/ruffle_13-7-2021/48b82e3e152a1a91a62f.wasm:wasm-function[1008]:0x27f05e)
    at std::sync::once::Once::call_inner::h79faa41f4d270a0b (https://www.superhry.cz/js/ruffle_13-7-2021/48b82e3e152a1a91a62f.wasm:wasm-function[974]:0x274b00)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hbd170ba35c598204 (https://www.superhry.cz/js/ruffle_13-7-2021/48b82e3e152a1a91a62f.wasm:wasm-function[3882]:0x421769)
    at std::panicking::rust_panic_with_hook::hbdbceb5cd158bf19 (https://www.superhry.cz/js/ruffle_13-7-2021/48b82e3e152a1a91a62f.wasm:wasm-function[2999]:0x3c00dc)
    at rust_begin_unwind (https://www.superhry.cz/js/ruffle_13-7-2021/48b82e3e152a1a91a62f.wasm:wasm-function[4094]:0x427138)
    at core::panicking::panic_fmt::h3ab5417155b7ba3b (https://www.superhry.cz/js/ruffle_13-7-2021/48b82e3e152a1a91a62f.wasm:wasm-function[4244]:0x42dee4)
    at core::result::unwrap_failed::h9bf99bca88ba05dc (https://www.superhry.cz/js/ruffle_13-7-2021/48b82e3e152a1a91a62f.wasm:wasm-function[3457]:0x40f57b)
    at ruffle_core::avm2::object::TObject::install_foreign_trait::hb744491a62617608 (https://www.superhry.cz/js/ruffle_13-7-2021/48b82e3e152a1a91a62f.wasm:wasm-function[326]:0xa49fd)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::set_property::h7c837903c0467b0d (https://www.superhry.cz/js/ruffle_13-7-2021/48b82e3e152a1a91a62f.wasm:wasm-function[497]:0x1627b8)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.superhry.cz/games/2277/
SWF URL: https://www.superhry.cz/cnt_img/002/2277.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36 Edg/96.0.1054.62
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-07-13
Channel: nightly
Built: 2021-07-13T00:11:20.184Z
Commit: c241ac6ace6bcb9d86e836caeb30b5035937dd4d

**Comment by Lord-McSweeney** [comment]
Looking at an archived version https://web.archive.org/web/20210102002422/http://www.superhry.cz/cnt_img/002/2277.swf, the issue seems to be fixed (I played through the whole game).
