### ISSUE TITLE
Error on http://www.ferryhalim.com/orisinal/g2/applegame.htm

### ISSUE THREAD

**Issue by flashliberty5467** [ruffle-rs/ruffle#5924]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:494:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:494:50
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://copkmmjhaeoclglpnighiijjmnmdiaom/dist/ruffle.js?id=54600408874:1:6703)
    at std::sync::once::Once::call_once::{{closure}}::h2a5914e357df5b02 (chrome-extension://copkmmjhaeoclglpnighiijjmnmdiaom/dist/c5c02c4e65c1c4423a97.wasm:wasm-function[990]:0x30f0ab)
    at std::sync::once::Once::call_inner::hf9144d66ddc67dec (chrome-extension://copkmmjhaeoclglpnighiijjmnmdiaom/dist/c5c02c4e65c1c4423a97.wasm:wasm-function[1195]:0x354b94)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h2b08ffde388f7cc2 (chrome-extension://copkmmjhaeoclglpnighiijjmnmdiaom/dist/c5c02c4e65c1c4423a97.wasm:wasm-function[4712]:0x505beb)
    at std::panicking::rust_panic_with_hook::h606d7c7f7a423b98 (chrome-extension://copkmmjhaeoclglpnighiijjmnmdiaom/dist/c5c02c4e65c1c4423a97.wasm:wasm-function[3248]:0x4b1c8a)
    at rust_begin_unwind (chrome-extension://copkmmjhaeoclglpnighiijjmnmdiaom/dist/c5c02c4e65c1c4423a97.wasm:wasm-function[4776]:0x507361)
    at core::panicking::panic_fmt::h6314b5c91abe7349 (chrome-extension://copkmmjhaeoclglpnighiijjmnmdiaom/dist/c5c02c4e65c1c4423a97.wasm:wasm-function[4991]:0x512348)
    at core::result::unwrap_failed::hd584efb7b84bf326 (chrome-extension://copkmmjhaeoclglpnighiijjmnmdiaom/dist/c5c02c4e65c1c4423a97.wasm:wasm-function[4018]:0x4ee3c5)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::h99e18f2587d0d861 (chrome-extension://copkmmjhaeoclglpnighiijjmnmdiaom/dist/c5c02c4e65c1c4423a97.wasm:wasm-function[706]:0x274bcb)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::register_shape::h0082ec8aeada4aa4 (chrome-extension://copkmmjhaeoclglpnighiijjmnmdiaom/dist/c5c02c4e65c1c4423a97.wasm:wasm-function[2839]:0x48de3d)
```

# Player Info
Allows script access: true

# Page Info
Page URL: http://www.ferryhalim.com/orisinal/g2/applegame.htm
SWF URL: http://www.ferryhalim.com/orisinal/g2/00applegame.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; CrOS x86_64 14268.67.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.111 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-12-22
Channel: nightly
Built: 2021-12-22T00:14:15.814Z
Commit: 74ab24c0c3345025a1b7297c526c37783ecc9990
Is extension: true

**Comment by Poopooracoocoo** [comment]
@flashliberty5467 When did you see this? I played through the games a few times without issue on my system running Chrome  96 on Windows 10.

**Comment by Herschel** [comment]
Closing in favor of #1905
