### ISSUE TITLE
Error on http://jessicasprague-m3.com/secure/classes/Digital4/lesson_1/CS5/DIDer_L1_T1_CS5/DIDer_L1_T1_CS5.html

### ISSUE THREAD

**Issue by tlkauffman** [ruffle-rs/ruffle#5949]
# Error Info
Error name: Error
Error message: panicked at 'assertion failed: min <= max', /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/cmp.rs:816:9
Error stack:
```
Error: panicked at 'assertion failed: min <= max', /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/cmp.rs:816:9
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://mdmfccmdnoploojejajphablkcmfhack/dist/ruffle.js?id=67411620890:1:6703)
    at std::sync::once::Once::call_once::{{closure}}::h2a5914e357df5b02 (chrome-extension://mdmfccmdnoploojejajphablkcmfhack/dist/c5c02c4e65c1c4423a97.wasm:wasm-function[990]:0x30f0ab)
    at std::sync::once::Once::call_inner::hf9144d66ddc67dec (chrome-extension://mdmfccmdnoploojejajphablkcmfhack/dist/c5c02c4e65c1c4423a97.wasm:wasm-function[1195]:0x354b94)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h2b08ffde388f7cc2 (chrome-extension://mdmfccmdnoploojejajphablkcmfhack/dist/c5c02c4e65c1c4423a97.wasm:wasm-function[4712]:0x505beb)
    at std::panicking::rust_panic_with_hook::h606d7c7f7a423b98 (chrome-extension://mdmfccmdnoploojejajphablkcmfhack/dist/c5c02c4e65c1c4423a97.wasm:wasm-function[3248]:0x4b1c8a)
    at rust_begin_unwind (chrome-extension://mdmfccmdnoploojejajphablkcmfhack/dist/c5c02c4e65c1c4423a97.wasm:wasm-function[4776]:0x507340)
    at core::panicking::panic_fmt::h6314b5c91abe7349 (chrome-extension://mdmfccmdnoploojejajphablkcmfhack/dist/c5c02c4e65c1c4423a97.wasm:wasm-function[4991]:0x512348)
    at core::panicking::panic::hec1fc057bd0baf0b (chrome-extension://mdmfccmdnoploojejajphablkcmfhack/dist/c5c02c4e65c1c4423a97.wasm:wasm-function[4709]:0x505451)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::set_viewport_dimensions::h5a7080617aa6f50c (chrome-extension://mdmfccmdnoploojejajphablkcmfhack/dist/c5c02c4e65c1c4423a97.wasm:wasm-function[700]:0x2701bd)
    at ruffle_web::Ruffle::tick::hb37e299891d44469 (chrome-extension://mdmfccmdnoploojejajphablkcmfhack/dist/c5c02c4e65c1c4423a97.wasm:wasm-function[602]:0x22efd8)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: DIDer_L1_T1_CS5_controller.swf
Param movie: DIDer_L1_T1_CS5_controller.swf
Param quality: best
Param bgcolor: #1a1a1a
Param allowfullscreen: true
Param scale: showall
Param allowscriptaccess: always
Param flashvars: autostart=false&thumb=FirstFrame.png&thumbscale=45&color=0x1A1A1A,0x1A1A1A
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: http://jessicasprague-m3.com/secure/classes/Digital4/lesson_1/CS5/DIDer_L1_T1_CS5/DIDer_L1_T1_CS5.html
SWF URL: http://jessicasprague-m3.com/secure/classes/Digital4/lesson_1/CS5/DIDer_L1_T1_CS5/DIDer_L1_T1_CS5_controller.swf

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-12-22
Channel: nightly
Built: 2021-12-22T00:14:15.814Z
Commit: 74ab24c0c3345025a1b7297c526c37783ecc9990
Is extension: true

**Comment by Lord-McSweeney** [comment]
Should have been fixed by #6458 a long time ago
