### ISSUE TITLE
Error on https://fgn.cdn.serverable.com/common/flashes/nf/kanzen_koryaku_f/index.html

### ISSUE THREAD

**Issue by s8050199** [ruffle-rs/ruffle#5978]
# Error Info
Error name: Error
Error message: panicked at 'attempt to calculate the remainder with a divisor of zero', core/src/display_object/video.rs:178:13
Error stack:
```
Error: panicked at 'attempt to calculate the remainder with a divisor of zero', core/src/display_object/video.rs:178:13
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (https://fgn.cdn.serverable.com/common/flashes/js/ruffle211222/ruffle.js:1:6703)
    at std::sync::once::Once::call_once::{{closure}}::h2a5914e357df5b02 (https://fgn.cdn.serverable.com/common/flashes/js/ruffle211222/c5c02c4e65c1c4423a97.wasm:wasm-function[990]:0x30f0ab)
    at std::sync::once::Once::call_inner::hf9144d66ddc67dec (https://fgn.cdn.serverable.com/common/flashes/js/ruffle211222/c5c02c4e65c1c4423a97.wasm:wasm-function[1195]:0x354b94)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h2b08ffde388f7cc2 (https://fgn.cdn.serverable.com/common/flashes/js/ruffle211222/c5c02c4e65c1c4423a97.wasm:wasm-function[4712]:0x505beb)
    at std::panicking::rust_panic_with_hook::h606d7c7f7a423b98 (https://fgn.cdn.serverable.com/common/flashes/js/ruffle211222/c5c02c4e65c1c4423a97.wasm:wasm-function[3248]:0x4b1c8a)
    at rust_begin_unwind (https://fgn.cdn.serverable.com/common/flashes/js/ruffle211222/c5c02c4e65c1c4423a97.wasm:wasm-function[4776]:0x507340)
    at core::panicking::panic_fmt::h6314b5c91abe7349 (https://fgn.cdn.serverable.com/common/flashes/js/ruffle211222/c5c02c4e65c1c4423a97.wasm:wasm-function[4991]:0x512348)
    at core::panicking::panic::hec1fc057bd0baf0b (https://fgn.cdn.serverable.com/common/flashes/js/ruffle211222/c5c02c4e65c1c4423a97.wasm:wasm-function[4709]:0x505451)
    at ruffle_core::display_object::video::Video::seek::h0d7664ab0e9dedb5 (https://fgn.cdn.serverable.com/common/flashes/js/ruffle211222/c5c02c4e65c1c4423a97.wasm:wasm-function[762]:0x290698)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::h11cc83f648152384 (https://fgn.cdn.serverable.com/common/flashes/js/ruffle211222/c5c02c4e65c1c4423a97.wasm:wasm-function[1736]:0x3ddc25)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: ~CompleteFF_SWF.swf
Param movie: ~CompleteFF_SWF.swf
Param quality: high
Param bgcolor: #000000
Param play: true
Param loop: true
Param wmode: window
Param scale: showall
Param menu: true
Param devicefont: false
Param allowScriptAccess: sameDomain
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://fgn.cdn.serverable.com/common/flashes/nf/kanzen_koryaku_f/index.html?d=20130226161644
SWF URL: https://fgn.cdn.serverable.com/common/flashes/nf/kanzen_koryaku_f/~CompleteFF_SWF.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-12-22
Channel: nightly
Built: 2021-12-22T00:14:15.814Z
Commit: 74ab24c0c3345025a1b7297c526c37783ecc9990
Is extension: false

**Comment by Herschel** [comment]
Fixed by #6607.
