### ISSUE TITLE
Error on https://ruffle.rs/demo/

### ISSUE THREAD

**Issue by Interact-fan** [ruffle-rs/ruffle#5988]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:494:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:494:50
    at r.wbg.__wbg_new_df6e6ab7a65c4c4d (https://ruffle.rs/demo/index.js:1:17269)
    at std::sync::once::Once::call_once::{{closure}}::hf7836615a2b5ea67 (https://ruffle.rs/demo/8ce1e88fd1c238065f69.wasm:wasm-function[1030]:0x303913)
    at std::sync::once::Once::call_inner::hf9144d66ddc67dec (https://ruffle.rs/demo/8ce1e88fd1c238065f69.wasm:wasm-function[1228]:0x347b76)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::he23ab71a90290f23 (https://ruffle.rs/demo/8ce1e88fd1c238065f69.wasm:wasm-function[4844]:0x51dcb8)
    at std::panicking::rust_panic_with_hook::h606d7c7f7a423b98 (https://ruffle.rs/demo/8ce1e88fd1c238065f69.wasm:wasm-function[3357]:0x4c6f9c)
    at rust_begin_unwind (https://ruffle.rs/demo/8ce1e88fd1c238065f69.wasm:wasm-function[4918]:0x522ee9)
    at core::panicking::panic_fmt::h6314b5c91abe7349 (https://ruffle.rs/demo/8ce1e88fd1c238065f69.wasm:wasm-function[5138]:0x52de80)
    at core::result::unwrap_failed::hd584efb7b84bf326 (https://ruffle.rs/demo/8ce1e88fd1c238065f69.wasm:wasm-function[4135]:0x505d89)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::h63c5fa4f74491c8d (https://ruffle.rs/demo/8ce1e88fd1c238065f69.wasm:wasm-function[740]:0x2566c2)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::register_glyph_shape::h10c7b790f9667754 (https://ruffle.rs/demo/8ce1e88fd1c238065f69.wasm:wasm-function[1889]:0x3eefcf)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://ruffle.rs/demo/
SWF URL: https://ruffle.rs/demo/swfs/flyguy.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; CrOS aarch64 14150.87.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.124 Safari/537.36
OS: Linux aarch64

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-01-04
Channel: nightly
Built: 2022-01-04T00:13:37.692Z
Commit: a9e86a73cf17845356a3bd38fe42c50e584a693c
Is extension: false

**Comment by Poopooracoocoo** [comment]
@Interact-fan Hello! Thank you for the report. Could you please tell us what device you have? (it's particularly interesting that it's an ARM64 Chrome OS device!) And what comes up in the browser's developer console?

**Comment by Herschel** [comment]
Closing in favor of #1905
