### ISSUE TITLE
Error on https://homestarrunner.com/main

### ISSUE THREAD

**Issue by Erhannis** [ruffle-rs/ruffle#5996]
# Error Info
Error name: Error
Error message: panicked at 'assertion failed: min <= max', /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/cmp.rs:816:9
Error stack:
```
Error: panicked at 'assertion failed: min <= max', /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/cmp.rs:816:9
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (https://homestarrunner.com/assets/js/ruffle.1641227736.js:1:6703)
    at std::sync::once::Once::call_once::{{closure}}::hd7ead8121c6a35d0 (https://homestarrunner.com/assets/js/6d3250a4583f23d5b287.wasm:wasm-function[980]:0x2f38ff)
    at std::sync::once::Once::call_inner::hf9144d66ddc67dec (https://homestarrunner.com/assets/js/6d3250a4583f23d5b287.wasm:wasm-function[1181]:0x33985e)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::he4d4296fb40dce2d (https://homestarrunner.com/assets/js/6d3250a4583f23d5b287.wasm:wasm-function[4674]:0x4ff0ad)
    at std::panicking::rust_panic_with_hook::h606d7c7f7a423b98 (https://homestarrunner.com/assets/js/6d3250a4583f23d5b287.wasm:wasm-function[3236]:0x4aaa03)
    at rust_begin_unwind (https://homestarrunner.com/assets/js/6d3250a4583f23d5b287.wasm:wasm-function[4737]:0x5005d7)
    at core::panicking::panic_fmt::h6314b5c91abe7349 (https://homestarrunner.com/assets/js/6d3250a4583f23d5b287.wasm:wasm-function[4953]:0x50b576)
    at core::panicking::panic::hec1fc057bd0baf0b (https://homestarrunner.com/assets/js/6d3250a4583f23d5b287.wasm:wasm-function[4671]:0x4fe913)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::set_viewport_dimensions::haeaad34909cd2556 (https://homestarrunner.com/assets/js/6d3250a4583f23d5b287.wasm:wasm-function[689]:0x245487)
    at ruffle_web::Ruffle::tick::h81bee42040571b91 (https://homestarrunner.com/assets/js/6d3250a4583f23d5b287.wasm:wasm-function[592]:0x1f3ec8)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://homestarrunner.com/main

# Browser Info
Useragent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-01-03
Channel: nightly
Built: 2022-01-03T00:13:37.756Z
Commit: 3010c505aa989bb8e19dba2341c65c7d74ad73ee
Is extension: false

**Comment by Sonikkustar** [comment]
Page loads fine without any issues:
![Image](https://github.com/user-attachments/assets/e4e13bf5-b622-458b-9aa4-5b5460fb868e)

**Comment by Lord-McSweeney** [comment]
Should have been fixed by #6458 a long time ago
