### ISSUE TITLE
Error on https://www.clickjogos.com.br/jogos/fog-free-kick

### ISSUE THREAD

**Issue by E-RYAN1770** [ruffle-rs/ruffle#6007]
# Error Info
Error name: TypeError
Error message: Failed to fetch
Error stack:
```
TypeError: Failed to fetch
    at https://www.clickjogos.com.br/ruffle/ruffle.js:2887:19
    at Array.forEach (<anonymous>)
    at Object.Si.f.wasm (https://www.clickjogos.com.br/ruffle/ruffle.js:2881:22)
    at https://www.clickjogos.com.br/ruffle/ruffle.js:1690:62
    at Array.reduce (<anonymous>)
    at Function.Si.e (https://www.clickjogos.com.br/ruffle/ruffle.js:1690:37)
    at o (https://www.clickjogos.com.br/ruffle/ruffle.js:390:35)
    at o.next (<anonymous>)
    at https://www.clickjogos.com.br/ruffle/ruffle.js:418:47
    at new Promise (<anonymous>)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: https://img.clickjogos.com.br/dl/8/8b61dc856101f479ae9d0bc401a04424/src.swf
Param movie: https://img.clickjogos.com.br/dl/8/8b61dc856101f479ae9d0bc401a04424/src.swf
Param allowScriptAccess: always
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://www.clickjogos.com.br/jogos/fog-free-kick

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-15
Channel: nightly
Built: 2021-01-15T01:03:45.335Z
Commit: 09a48a71d8608803fd5dba4343c5f10c928f9652

**Comment by kjarosh** [comment]
Should be fixed as of the newest version
