### ISSUE TITLE
Error on https://ruffle.rs/demo/

### ISSUE THREAD

**Issue by Donovoi** [ruffle-rs/ruffle#6013]
# Error Info
Error name: Error
Error message: panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:562:5
Error stack:
```
Error: panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:562:5
    at r.wbg.__wbg_new_df6e6ab7a65c4c4d (https://ruffle.rs/demo/index.js:1:17269)
    at std::sync::once::Once::call_once::{{closure}}::hf7836615a2b5ea67 (https://ruffle.rs/demo/de25a2ce123f902c8fcd.wasm:wasm-function[1030]:0x300d67)
    at std::sync::once::Once::call_inner::hf9144d66ddc67dec (https://ruffle.rs/demo/de25a2ce123f902c8fcd.wasm:wasm-function[1231]:0x3472d2)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::he23ab71a90290f23 (https://ruffle.rs/demo/de25a2ce123f902c8fcd.wasm:wasm-function[4870]:0x51f266)
    at std::panicking::rust_panic_with_hook::h606d7c7f7a423b98 (https://ruffle.rs/demo/de25a2ce123f902c8fcd.wasm:wasm-function[3358]:0x4c5b09)
    at rust_begin_unwind (https://ruffle.rs/demo/de25a2ce123f902c8fcd.wasm:wasm-function[4945]:0x5244b5)
    at core::panicking::panic_fmt::h6314b5c91abe7349 (https://ruffle.rs/demo/de25a2ce123f902c8fcd.wasm:wasm-function[5166]:0x52f53d)
    at core::panicking::panic::hec1fc057bd0baf0b (https://ruffle.rs/demo/de25a2ce123f902c8fcd.wasm:wasm-function[4867]:0x51eacc)
    at alloc::raw_vec::capacity_overflow::h4b49014830cafe63 (https://ruffle.rs/demo/de25a2ce123f902c8fcd.wasm:wasm-function[5606]:0x534dc1)
    at ruffle_core::tag_utils::SwfMovie::from_data::h91e72d36efb628ab (https://ruffle.rs/demo/de25a2ce123f902c8fcd.wasm:wasm-function[386]:0xf2736)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://ruffle.rs/demo/

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-01-08
Channel: nightly
Built: 2022-01-08T00:12:57.266Z
Commit: bb3ef68499eb0ab9af42edc0089a01069b942425
Is extension: false

**Comment by adrian17** [comment]
Could you please say which SWF you tried to load?

**Comment by Donovoi** [comment]
Hi sorry about the late reply. I dont have access to the original file, we were doing file carving. And the file was a 50mb swf file. Is there a way to validate a swf file before using the tool? 

Also the desktop program crashed so I'm assuming it is the same issue.

**Comment by adrian17** [comment]
I don't think it's about validating a file; it's just that without seeing it, I don't think we'll be able to reproduce this issue, and thus figure it out :/

**Comment by Donovoi** [comment]
I've got a few other swf that will most likely do the same thing I can send them as a google drive url?

**Comment by n0samu** [comment]
@Donovoi yes, please send any SWF file you can find that reproduces the issue

**Comment by n0samu** [comment]
Closing due to lack of response. @Donovoi If you provide an SWF that reproduces the problem I will reopen the issue.
