### ISSUE TITLE
Error on https://h-flash.com/hot-goomba-sex/

### ISSUE THREAD

**Issue by josue946** [ruffle-rs/ruffle#6035]
# Error Info
Error name: Error
Error message: panicked at 'assertion failed: min <= max', /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/cmp.rs:816:9
Error stack:
```
Error: panicked at 'assertion failed: min <= max', /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/cmp.rs:816:9
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (https://h-flash.com/data/ruffle/ruffle.js:1:6703)
    at std::sync::once::Once::call_once::{{closure}}::h2a5914e357df5b02 (https://h-flash.com/data/ruffle/c5c02c4e65c1c4423a97.wasm:wasm-function[990]:0x30f0ab)
    at std::sync::once::Once::call_inner::hf9144d66ddc67dec (https://h-flash.com/data/ruffle/c5c02c4e65c1c4423a97.wasm:wasm-function[1195]:0x354b94)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h2b08ffde388f7cc2 (https://h-flash.com/data/ruffle/c5c02c4e65c1c4423a97.wasm:wasm-function[4712]:0x505beb)
    at std::panicking::rust_panic_with_hook::h606d7c7f7a423b98 (https://h-flash.com/data/ruffle/c5c02c4e65c1c4423a97.wasm:wasm-function[3248]:0x4b1c8a)
    at rust_begin_unwind (https://h-flash.com/data/ruffle/c5c02c4e65c1c4423a97.wasm:wasm-function[4776]:0x507340)
    at core::panicking::panic_fmt::h6314b5c91abe7349 (https://h-flash.com/data/ruffle/c5c02c4e65c1c4423a97.wasm:wasm-function[4991]:0x512348)
    at core::panicking::panic::hec1fc057bd0baf0b (https://h-flash.com/data/ruffle/c5c02c4e65c1c4423a97.wasm:wasm-function[4709]:0x505451)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::set_viewport_dimensions::h5a7080617aa6f50c (https://h-flash.com/data/ruffle/c5c02c4e65c1c4423a97.wasm:wasm-function[700]:0x2701bd)
    at ruffle_web::Ruffle::tick::hb37e299891d44469 (https://h-flash.com/data/ruffle/c5c02c4e65c1c4423a97.wasm:wasm-function[602]:0x22efd8)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://h-flash.com/hot-goomba-sex/
SWF URL: https://h-flash.com/data/swf/2013/08/Hot%20Goomba%20Sex.swf

# Browser Info
Useragent: Mozilla/5.0 (Linux; Android 6.0.1; SM-G570M Build/MMB29K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/96.0.4664.104 Mobile Safari/537.36
OS: Linux armv8l

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-12-22
Channel: nightly
Built: 2021-12-22T00:14:15.814Z
Commit: 74ab24c0c3345025a1b7297c526c37783ecc9990
Is extension: false

**Comment by Lord-McSweeney** [comment]
Should have been fixed by #6458 a long time ago
