### ISSUE TITLE
Error on http://www.gatoconbota.com/gamon/bratz-pecera/

### ISSUE THREAD

**Issue by jackileiva** [ruffle-rs/ruffle#6050]
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', web/src/lib.rs:836:49
Error stack:
```
Error: panicked at 'already borrowed: BorrowMutError', web/src/lib.rs:836:49
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (http://www.gatoconbota.com/ruffle/ruffle.js:1:6349)
    at std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f (http://www.gatoconbota.com/ruffle/aafdd926c74ff1ff1e03a02091c0405b.wasm:wasm-function[1267]:0x24ef2a)
    at std::sync::once::Once::call_inner::h02eac160d339afc2 (http://www.gatoconbota.com/ruffle/aafdd926c74ff1ff1e03a02091c0405b.wasm:wasm-function[1528]:0x27ed9a)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801 (http://www.gatoconbota.com/ruffle/aafdd926c74ff1ff1e03a02091c0405b.wasm:wasm-function[4308]:0x353f1a)
    at std::panicking::rust_panic_with_hook::h123718ba3bf480af (http://www.gatoconbota.com/ruffle/aafdd926c74ff1ff1e03a02091c0405b.wasm:wasm-function[3299]:0x32cc21)
    at std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2 (http://www.gatoconbota.com/ruffle/aafdd926c74ff1ff1e03a02091c0405b.wasm:wasm-function[3916]:0x349dfc)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925 (http://www.gatoconbota.com/ruffle/aafdd926c74ff1ff1e03a02091c0405b.wasm:wasm-function[4654]:0x359654)
    at rust_begin_unwind (http://www.gatoconbota.com/ruffle/aafdd926c74ff1ff1e03a02091c0405b.wasm:wasm-function[4525]:0x357c32)
    at core::panicking::panic_fmt::h285dc015a87be5a4 (http://www.gatoconbota.com/ruffle/aafdd926c74ff1ff1e03a02091c0405b.wasm:wasm-function[4656]:0x3596b8)
    at core::option::expect_none_failed::hb95d2b1dc5448c17 (http://www.gatoconbota.com/ruffle/aafdd926c74ff1ff1e03a02091c0405b.wasm:wasm-function[3995]:0x34c594)
```

# Player Info
Allows script access: true

# Page Info
Page URL: http://www.gatoconbota.com/gamon/bratz-pecera/
SWF URL: http://www.gatoconbota.com/mm/go/swf/bratz-pecera.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-26
Channel: nightly
Built: 2021-01-26T00:36:48.131Z
Commit: 7856cdd3d770e406ce546bf1745d8046d7b716f8

**Comment by Lord-McSweeney** [comment]
This seems to be working now
