### ISSUE TITLE
Error on https://ruffle.rs/demo/

### ISSUE THREAD

**Issue by wanderingmagus** [ruffle-rs/ruffle#6057]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm2/object.rs:305:48
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm2/object.rs:305:48
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (https://ruffle.rs/demo/966.index.js:1:7291)
    at std::sync::once::Once::call_once::{{closure}}::h62bc8fc4a570c751 (https://ruffle.rs/demo/49b73fc673ec26aef403.wasm:wasm-function[1072]:0x30a156)
    at std::sync::once::Once::call_inner::h6fd514b461aaa35e (https://ruffle.rs/demo/49b73fc673ec26aef403.wasm:wasm-function[1207]:0x33de3c)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h93d1178f27f44b80 (https://ruffle.rs/demo/49b73fc673ec26aef403.wasm:wasm-function[4842]:0x4eb240)
    at std::panicking::rust_panic_with_hook::h19d99b2b2597d628 (https://ruffle.rs/demo/49b73fc673ec26aef403.wasm:wasm-function[3300]:0x49e023)
    at core::panicking::panic_fmt::hbc500cb2b2c8690c (https://ruffle.rs/demo/49b73fc673ec26aef403.wasm:wasm-function[5133]:0x4facbd)
    at core::panicking::panic::h7ae74ceab81e332c (https://ruffle.rs/demo/49b73fc673ec26aef403.wasm:wasm-function[4839]:0x4ead67)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::hd24006f5ef899a4b (https://ruffle.rs/demo/49b73fc673ec26aef403.wasm:wasm-function[357]:0x7ac9a)
    at ruffle_core::avm2::activation::Activation::do_next_opcode::he3f0d7ad8eef274f (https://ruffle.rs/demo/49b73fc673ec26aef403.wasm:wasm-function[351]:0x4b626)
    at ruffle_core::avm2::activation::Activation::run_actions::h438308019d572849 (https://ruffle.rs/demo/49b73fc673ec26aef403.wasm:wasm-function[2983]:0x48129a)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://ruffle.rs/demo/

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-01-14
Channel: nightly
Built: 2022-01-14T00:17:13.789Z
Commit: 483028707f437dbe00b270fc700f4454dd60aa27
Is extension: false

**Comment by kjarosh** [comment]
Should be fixed as of today—the related code has been heavily rewritten. (See https://github.com/ruffle-rs/ruffle/pull/7095)
