### ISSUE TITLE
Error on http://blogofholding.com/dungeonrobber/

### ISSUE THREAD

**Issue by lukamusmaximus** [ruffle-rs/ruffle#6080]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/html/text_format.rs:756:54
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/html/text_format.rs:756:54
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://ndkmnmegoiommemiilpiaoifdlllfjli/dist/966.js:1:6962)
    at std::sync::once::Once::call_once::{{closure}}::h681a2944be530e42 (chrome-extension://ndkmnmegoiommemiilpiaoifdlllfjli/dist/022684bed3c073b639bf.wasm:wasm-function[1026]:0x2fc8e5)
    at std::sync::once::Once::call_inner::h6fd514b461aaa35e (chrome-extension://ndkmnmegoiommemiilpiaoifdlllfjli/dist/022684bed3c073b639bf.wasm:wasm-function[1163]:0x330d82)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h8e1dd73398f2b1c4 (chrome-extension://ndkmnmegoiommemiilpiaoifdlllfjli/dist/022684bed3c073b639bf.wasm:wasm-function[4671]:0x4cd138)
    at std::panicking::rust_panic_with_hook::h19d99b2b2597d628 (chrome-extension://ndkmnmegoiommemiilpiaoifdlllfjli/dist/022684bed3c073b639bf.wasm:wasm-function[3183]:0x4829c4)
    at core::panicking::panic_fmt::hbc500cb2b2c8690c (chrome-extension://ndkmnmegoiommemiilpiaoifdlllfjli/dist/022684bed3c073b639bf.wasm:wasm-function[4947]:0x4d8f21)
    at core::panicking::panic::h7ae74ceab81e332c (chrome-extension://ndkmnmegoiommemiilpiaoifdlllfjli/dist/022684bed3c073b639bf.wasm:wasm-function[4668]:0x4ccc5f)
    at ruffle_core::html::text_format::FormatSpans::from_html::h9e3d3c5cd843252a (chrome-extension://ndkmnmegoiommemiilpiaoifdlllfjli/dist/022684bed3c073b639bf.wasm:wasm-function[321]:0x8bee8)
    at ruffle_core::display_object::edit_text::EditText::set_html_text::he6263e974873f033 (chrome-extension://ndkmnmegoiommemiilpiaoifdlllfjli/dist/022684bed3c073b639bf.wasm:wasm-function[2401]:0x42beb9)
    at core::ops::function::FnOnce::call_once::h0ed9af160ec73732 (chrome-extension://ndkmnmegoiommemiilpiaoifdlllfjli/dist/022684bed3c073b639bf.wasm:wasm-function[2170]:0x40df88)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: randomdungeonmap14.swf
Param movie: randomdungeonmap14.swf
Param quality: high
Param bgcolor: #ffffff
Param play: true
Param loop: true
Param wmode: window
Param scale: noscale
Param menu: true
Param devicefont: false
Param allowScriptAccess: sameDomain
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: http://blogofholding.com/dungeonrobber/
SWF URL: http://blogofholding.com/dungeonrobber/randomdungeonmap14.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-01-15
Channel: nightly
Built: 2022-01-15T00:14:26.227Z
Commit: 31443cc9e7017e2f14d56d415730746245feb31e
Is extension: true

**Comment by relrelb** [comment]
Same issue as #6016.
