### ISSUE TITLE
Error on https://archive.org/details/cascade-homestuck

### ISSUE THREAD

**Issue by melickgarrett** [ruffle-rs/ruffle#6093]
# Error Info
Error name: Error
Error message: panicked at 'assertion failed: min <= max', /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/cmp.rs:816:9
Error stack:
```
Error: panicked at 'assertion failed: min <= max', /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/cmp.rs:816:9
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (https://cors.archive.org/cors/emularity_engine_v1/ruffle.js:1:6703)
    at std::sync::once::Once::call_once::{{closure}}::hdee01963557c8b87 (https://ia801902.us.archive.org/cors_get.php?path=/18/items/emularity_engine_v1/6a4730a83caca4e15604.wasm:wasm-function[1000]:0x30efb6)
    at std::sync::once::Once::call_inner::hf9144d66ddc67dec (https://ia801902.us.archive.org/cors_get.php?path=/18/items/emularity_engine_v1/6a4730a83caca4e15604.wasm:wasm-function[1192]:0x35318b)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h9e75ef83c7eceddf (https://ia801902.us.archive.org/cors_get.php?path=/18/items/emularity_engine_v1/6a4730a83caca4e15604.wasm:wasm-function[4707]:0x50c322)
    at std::panicking::rust_panic_with_hook::h606d7c7f7a423b98 (https://ia801902.us.archive.org/cors_get.php?path=/18/items/emularity_engine_v1/6a4730a83caca4e15604.wasm:wasm-function[3243]:0x4b900c)
    at rust_begin_unwind (https://ia801902.us.archive.org/cors_get.php?path=/18/items/emularity_engine_v1/6a4730a83caca4e15604.wasm:wasm-function[4770]:0x50d84f)
    at core::panicking::panic_fmt::h6314b5c91abe7349 (https://ia801902.us.archive.org/cors_get.php?path=/18/items/emularity_engine_v1/6a4730a83caca4e15604.wasm:wasm-function[4983]:0x518753)
    at core::panicking::panic::hec1fc057bd0baf0b (https://ia801902.us.archive.org/cors_get.php?path=/18/items/emularity_engine_v1/6a4730a83caca4e15604.wasm:wasm-function[4704]:0x50bb88)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::set_viewport_dimensions::h756a219cc69b84a2 (https://ia801902.us.archive.org/cors_get.php?path=/18/items/emularity_engine_v1/6a4730a83caca4e15604.wasm:wasm-function[706]:0x26f940)
    at ruffle_web::Ruffle::tick::hb9d842e238c03a03 (https://ia801902.us.archive.org/cors_get.php?path=/18/items/emularity_engine_v1/6a4730a83caca4e15604.wasm:wasm-function[602]:0x22bebd)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://archive.org/details/cascade-homestuck

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-12-16
Channel: nightly
Built: 2021-12-16T00:12:02.888Z
Commit: 07c533045604f42610bb3ca5480d9443b78f7fb7
Is extension: false

**Comment by Lord-McSweeney** [comment]
Should have been fixed by #6458 a long time ago
