### ISSUE TITLE
Error on chrome-extension://gcgigolgfibadekjdlmknphnbbmnbibg/player.html

### ISSUE THREAD

**Issue by deividbinev12** [ruffle-rs/ruffle#6095]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/html/text_format.rs:756:54
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/html/text_format.rs:756:54
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://gcgigolgfibadekjdlmknphnbbmnbibg/dist/966.js:1:6962)
    at std::sync::once::Once::call_once::{{closure}}::hc85ce564f2ea66ba (chrome-extension://gcgigolgfibadekjdlmknphnbbmnbibg/dist/94c05bf8f8acf3a139e6.wasm:wasm-function[1030]:0x301984)
    at std::sync::once::Once::call_inner::h6fd514b461aaa35e (chrome-extension://gcgigolgfibadekjdlmknphnbbmnbibg/dist/94c05bf8f8acf3a139e6.wasm:wasm-function[1163]:0x3346d0)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::he301baa1a5c81c58 (chrome-extension://gcgigolgfibadekjdlmknphnbbmnbibg/dist/94c05bf8f8acf3a139e6.wasm:wasm-function[4677]:0x4d1345)
    at std::panicking::rust_panic_with_hook::h19d99b2b2597d628 (chrome-extension://gcgigolgfibadekjdlmknphnbbmnbibg/dist/94c05bf8f8acf3a139e6.wasm:wasm-function[3186]:0x4869d5)
    at core::panicking::panic_fmt::hbc500cb2b2c8690c (chrome-extension://gcgigolgfibadekjdlmknphnbbmnbibg/dist/94c05bf8f8acf3a139e6.wasm:wasm-function[4951]:0x4dd0d6)
    at core::panicking::panic::h7ae74ceab81e332c (chrome-extension://gcgigolgfibadekjdlmknphnbbmnbibg/dist/94c05bf8f8acf3a139e6.wasm:wasm-function[4674]:0x4d0e6c)
    at ruffle_core::html::text_format::FormatSpans::from_html::h896d86cab7bf7e91 (chrome-extension://gcgigolgfibadekjdlmknphnbbmnbibg/dist/94c05bf8f8acf3a139e6.wasm:wasm-function[321]:0x8d009)
    at ruffle_core::display_object::edit_text::EditText::set_html_text::he3c25949d7cb16d7 (chrome-extension://gcgigolgfibadekjdlmknphnbbmnbibg/dist/94c05bf8f8acf3a139e6.wasm:wasm-function[2406]:0x42ff20)
    at <ruffle_core::avm1::object::stage_object::StageObject as ruffle_core::avm1::object::TObject>::set_local::h3b5326eb6fe821da (chrome-extension://gcgigolgfibadekjdlmknphnbbmnbibg/dist/94c05bf8f8acf3a139e6.wasm:wasm-function[695]:0x257ff2)
```

# Player Info
Allows script access: false

# Page Info
Page URL: chrome-extension://gcgigolgfibadekjdlmknphnbbmnbibg/player.html?url=https://gamefilez.mofunzone.com/gamefilez/matrixbullettimefighting.swf?1280278279
SWF URL: https://gamefilez.mofunzone.com/gamefilez/matrixbullettimefighting.swf?1280278279

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36 Edg/97.0.1072.62
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-01-17
Channel: nightly
Built: 2022-01-17T00:18:08.085Z
Commit: 059c1a34174a546521d1ebc32fd1411a079c2708
Is extension: true

**Comment by relrelb** [comment]
I'm almost sure this was already fixed by #6084. Can you please update Ruffle and confirm?
