### ISSUE TITLE
Error on https://homestarrunner.com/dman3

### ISSUE THREAD

**Issue by whitericeputting** [ruffle-rs/ruffle#6098]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:494:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:494:50
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (https://homestarrunner.com/assets/js/ruffle.1641227736.js:1:6703)
    at std::sync::once::Once::call_once::{{closure}}::hd7ead8121c6a35d0 (https://homestarrunner.com/assets/js/6d3250a4583f23d5b287.wasm:wasm-function[980]:0x2f38ff)
    at std::sync::once::Once::call_inner::hf9144d66ddc67dec (https://homestarrunner.com/assets/js/6d3250a4583f23d5b287.wasm:wasm-function[1181]:0x33985e)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::he4d4296fb40dce2d (https://homestarrunner.com/assets/js/6d3250a4583f23d5b287.wasm:wasm-function[4674]:0x4ff0ad)
    at std::panicking::rust_panic_with_hook::h606d7c7f7a423b98 (https://homestarrunner.com/assets/js/6d3250a4583f23d5b287.wasm:wasm-function[3236]:0x4aaa03)
    at rust_begin_unwind (https://homestarrunner.com/assets/js/6d3250a4583f23d5b287.wasm:wasm-function[4737]:0x5005f8)
    at core::panicking::panic_fmt::h6314b5c91abe7349 (https://homestarrunner.com/assets/js/6d3250a4583f23d5b287.wasm:wasm-function[4953]:0x50b576)
    at core::result::unwrap_failed::hd584efb7b84bf326 (https://homestarrunner.com/assets/js/6d3250a4583f23d5b287.wasm:wasm-function[3989]:0x4e81c8)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::heb05543b9cbe5ea3 (https://homestarrunner.com/assets/js/6d3250a4583f23d5b287.wasm:wasm-function[695]:0x249e84)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::register_shape::hf2f207158d2e1949 (https://homestarrunner.com/assets/js/6d3250a4583f23d5b287.wasm:wasm-function[2815]:0x4857dd)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://homestarrunner.com/dman3
SWF URL: https://homestarrunner.com/media/pages/dman3/f0e50731c9-1609375302/thydungeonman3.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-01-03
Channel: nightly
Built: 2022-01-03T00:13:37.756Z
Commit: 3010c505aa989bb8e19dba2341c65c7d74ad73ee
Is extension: false

**Comment by Herschel** [comment]
Closing in favor of #1905
