### ISSUE TITLE
Error on chrome-extension://hhlkdmgdkpgpnobdbgpejgknipmbmihe/player.html

### ISSUE THREAD

**Issue by Vanquan123a** [ruffle-rs/ruffle#6109]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm2/object.rs:305:48
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm2/object.rs:305:48
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://hhlkdmgdkpgpnobdbgpejgknipmbmihe/dist/966.js:1:6962)
    at std::sync::once::Once::call_once::{{closure}}::h4dcb78b97de78bcf (chrome-extension://hhlkdmgdkpgpnobdbgpejgknipmbmihe/dist/8c84922ac55449dc628f.wasm:wasm-function[1032]:0x303aa1)
    at std::sync::once::Once::call_inner::h9279eef47cf85b81 (chrome-extension://hhlkdmgdkpgpnobdbgpejgknipmbmihe/dist/8c84922ac55449dc628f.wasm:wasm-function[1171]:0x3397a9)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h7e6cf7c840665392 (chrome-extension://hhlkdmgdkpgpnobdbgpejgknipmbmihe/dist/8c84922ac55449dc628f.wasm:wasm-function[4680]:0x4d6936)
    at std::panicking::rust_panic_with_hook::h47a0e203360b6c10 (chrome-extension://hhlkdmgdkpgpnobdbgpejgknipmbmihe/dist/8c84922ac55449dc628f.wasm:wasm-function[3195]:0x48c602)
    at core::panicking::panic_fmt::h4ca53049f45e3264 (chrome-extension://hhlkdmgdkpgpnobdbgpejgknipmbmihe/dist/8c84922ac55449dc628f.wasm:wasm-function[4954]:0x4e26c1)
    at core::panicking::panic::h35778e3c18266c93 (chrome-extension://hhlkdmgdkpgpnobdbgpejgknipmbmihe/dist/8c84922ac55449dc628f.wasm:wasm-function[4677]:0x4d645d)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::h640a2e26c8018276 (chrome-extension://hhlkdmgdkpgpnobdbgpejgknipmbmihe/dist/8c84922ac55449dc628f.wasm:wasm-function[319]:0x7966d)
    at ruffle_core::avm2::activation::Activation::do_next_opcode::hfeb3a14a7657719f (chrome-extension://hhlkdmgdkpgpnobdbgpejgknipmbmihe/dist/8c84922ac55449dc628f.wasm:wasm-function[312]:0x2df33)
    at ruffle_core::avm2::activation::Activation::run_actions::h6d51e9527e6f32fc (chrome-extension://hhlkdmgdkpgpnobdbgpejgknipmbmihe/dist/8c84922ac55449dc628f.wasm:wasm-function[2895]:0x470996)
```

# Player Info
Allows script access: false

# Page Info
Page URL: chrome-extension://hhlkdmgdkpgpnobdbgpejgknipmbmihe/player.html?url=http://43.249.193.247:8081/loading.swf
SWF URL: http://43.249.193.247:8081/loading.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-01-21
Channel: nightly
Built: 2022-01-21T00:17:44.053Z
Commit: 4d8db1e64d36cc59c98c63b6883971cf01c5c9e3
Is extension: true

**Comment by kjarosh** [comment]
Should be fixed as of today—the related code has been heavily rewritten. (See https://github.com/ruffle-rs/ruffle/pull/7095)
