### ISSUE TITLE
Error on https://sexgamefun.com/sex_games_jessica_rabbit_fucks_roger.php

### ISSUE THREAD

**Issue by NasTheOne** [ruffle-rs/ruffle#6155]
# Error Info
Error name: TypeError
Error message: Failed to fetch
Error stack:
```
TypeError: Failed to fetch
    at https://www.sexgamefun.com/assets/ruffle/ruffle.js:1:68047
    at Array.forEach (<anonymous>)
    at Object.yi.f.wasm (https://www.sexgamefun.com/assets/ruffle/ruffle.js:1:67974)
    at https://www.sexgamefun.com/assets/ruffle/ruffle.js:1:35888
    at Array.reduce (<anonymous>)
    at Function.yi.e (https://www.sexgamefun.com/assets/ruffle/ruffle.js:1:35865)
    at o (https://www.sexgamefun.com/assets/ruffle/ruffle.js:1:2651)
    at o.next (<anonymous>)
    at https://www.sexgamefun.com/assets/ruffle/ruffle.js:1:2951
    at new Promise (<anonymous>)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://sexgamefun.com/sex_games_jessica_rabbit_fucks_roger.php

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-12
Channel: nightly
Built: 2021-01-12T00:55:17.048Z
Commit: 73d123091014e190f4bc4d8edf98cab2e671cc3a

**Comment by kjarosh** [comment]
Should be fixed as of the newest version
