### ISSUE TITLE
Error on chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/player.html

### ISSUE THREAD

**Issue by sunt2049** [ruffle-rs/ruffle#6156]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm2/object.rs:305:48
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm2/object.rs:305:48
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:1:6962)
    at std::sync::once::Once::call_once::{{closure}}::h4dcb78b97de78bcf (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/f91bedccc781eba86e58.wasm:wasm-function[1019]:0x2f8ef2)
    at std::sync::once::Once::call_inner::h9279eef47cf85b81 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/f91bedccc781eba86e58.wasm:wasm-function[1157]:0x32aaba)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h7e6cf7c840665392 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/f91bedccc781eba86e58.wasm:wasm-function[4721]:0x4d76d9)
    at std::panicking::rust_panic_with_hook::h47a0e203360b6c10 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/f91bedccc781eba86e58.wasm:wasm-function[3188]:0x482726)
    at core::panicking::panic_fmt::h4ca53049f45e3264 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/f91bedccc781eba86e58.wasm:wasm-function[4992]:0x4e3325)
    at core::panicking::panic::h35778e3c18266c93 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/f91bedccc781eba86e58.wasm:wasm-function[4718]:0x4d7200)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::h640a2e26c8018276 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/f91bedccc781eba86e58.wasm:wasm-function[334]:0xaa5cf)
    at ruffle_core::avm2::activation::Activation::do_next_opcode::hfeb3a14a7657719f (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/f91bedccc781eba86e58.wasm:wasm-function[312]:0x2e3f1)
    at ruffle_core::avm2::activation::Activation::run_actions::h6d51e9527e6f32fc (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/f91bedccc781eba86e58.wasm:wasm-function[2894]:0x468802)
```

# Player Info
Allows script access: false

# Page Info
Page URL: chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/player.html?url=https%3A%2F%2Fsuperobamaworld.com%2Fsow2014%2FSOW.swf
SWF URL: https://superobamaworld.com/sow2014/SOW.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-01-27
Channel: nightly
Built: 2022-01-27T00:15:35.472Z
Commit: 43b21e5d4d619b4d2b6e9b5ca9f6270c8ea45599
Is extension: true

**Comment by kjarosh** [comment]
Should be fixed as of today—the related code has been heavily rewritten. (See https://github.com/ruffle-rs/ruffle/pull/7095)
