### ISSUE TITLE
Error on https://acf.pbxww.com/index.php

### ISSUE THREAD

**Issue by Rob3487** [ruffle-rs/ruffle#6181]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm2/object.rs:305:48
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm2/object.rs:305:48
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:1:6962)
    at std::sync::once::Once::call_once::{{closure}}::h4dcb78b97de78bcf (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/b2fc0abe3dbbf4e736aa.wasm:wasm-function[1016]:0x2f3fd8)
    at std::sync::once::Once::call_inner::h9279eef47cf85b81 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/b2fc0abe3dbbf4e736aa.wasm:wasm-function[1152]:0x3276ac)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h7e6cf7c840665392 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/b2fc0abe3dbbf4e736aa.wasm:wasm-function[4725]:0x4d3db3)
    at std::panicking::rust_panic_with_hook::h47a0e203360b6c10 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/b2fc0abe3dbbf4e736aa.wasm:wasm-function[3192]:0x47f3dc)
    at core::panicking::panic_fmt::h4ca53049f45e3264 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/b2fc0abe3dbbf4e736aa.wasm:wasm-function[4996]:0x4df9ff)
    at core::panicking::panic::h35778e3c18266c93 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/b2fc0abe3dbbf4e736aa.wasm:wasm-function[4722]:0x4d38da)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::h640a2e26c8018276 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/b2fc0abe3dbbf4e736aa.wasm:wasm-function[353]:0xd7eb5)
    at ruffle_core::avm2::activation::Activation::do_next_opcode::hfeb3a14a7657719f (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/b2fc0abe3dbbf4e736aa.wasm:wasm-function[312]:0x2daff)
    at ruffle_core::avm2::activation::Activation::run_actions::h6d51e9527e6f32fc (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/b2fc0abe3dbbf4e736aa.wasm:wasm-function[2900]:0x4656f9)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: swf/pbxwwhd.4606.swf
Param movie: swf/pbxwwhd.4606.swf
Param scale: noScale
Param wmode: direct
Param allowFullScreenInteractive: true
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined

# Page Info
Page URL: https://acf.pbxww.com/index.php?r=1643659604.8675
SWF URL: https://acf.pbxww.com/swf/pbxwwhd.4606.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-01-31
Channel: nightly
Built: 2022-01-31T00:17:51.537Z
Commit: 83cc9dc30834acdf8bc03c9fe7392713a7e53792
Is extension: true

**Comment by Poopooracoocoo** [comment]
@Rob3487 Got another link or could you perhaps explain what this is?

The only thing I see there is ERROR 401 - SSO BUNDLE NOT SENT. For the developers to fix this error they'll need to be able to reproduce it themselves.

**Comment by Rob3487** [comment]
Hi!

Unfortunately this is a logged area, one would have to create an account to
recreate the circumstance. I understand that this makes things
very difficult to solve the issue, I only reported it because the report
bug window popped up when it happened. That being said, flash reaching EOL
has caused significant disruption to the virtual PBX industry as possibly
the most popular small dollar solution was flash based (the one that this
bug relates to), possibly there would be some demand for your plugin if it
did solve the flash problem with this pbx software...?

I'll find a workaround for my needs - thank you for following up.

Regards,

Rob
Sent using EngageBay <https://eblink1.com/website>

**Comment by kjarosh** [comment]
Should be fixed as of today—the related code has been heavily rewritten. (See https://github.com/ruffle-rs/ruffle/pull/7095)
