### ISSUE TITLE
Error on https://www.ridesims.com/ride-simulators/Free-Spin

### ISSUE THREAD

**Issue by pug-pebbles** [ruffle-rs/ruffle#6187]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:494:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:494:50
    at u.wbg.__wbg_new_df6e6ab7a65c4c4d (https://ridesims.com/ruffle/ruffle.js?a=2022-02-01-12-14:1:7173)
    at std::sync::once::Once::call_once::{{closure}}::h5387044f596cf17b (https://www.ridesims.com/ruffle/2da79230c52ac9361cc6.wasm:wasm-function[1003]:0x2f13ae)
    at std::sync::once::Once::call_inner::h02a6489b0ecfb269 (https://www.ridesims.com/ruffle/2da79230c52ac9361cc6.wasm:wasm-function[1334]:0x363d84)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h4461033b8c8249d8 (https://www.ridesims.com/ruffle/2da79230c52ac9361cc6.wasm:wasm-function[4690]:0x4f0908)
    at std::panicking::rust_panic_with_hook::h364974e717ed59ec (https://www.ridesims.com/ruffle/2da79230c52ac9361cc6.wasm:wasm-function[3314]:0x4ac005)
    at rust_begin_unwind (https://www.ridesims.com/ruffle/2da79230c52ac9361cc6.wasm:wasm-function[4752]:0x4f3097)
    at core::panicking::panic_fmt::hf69c8b08bc9d2ee5 (https://www.ridesims.com/ruffle/2da79230c52ac9361cc6.wasm:wasm-function[4959]:0x4fdbf8)
    at core::result::unwrap_failed::h694db13a45aa6740 (https://www.ridesims.com/ruffle/2da79230c52ac9361cc6.wasm:wasm-function[4011]:0x4d8f01)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::ha4c5197dc5c7413f (https://www.ridesims.com/ruffle/2da79230c52ac9361cc6.wasm:wasm-function[703]:0x252b5d)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::register_glyph_shape::h0bbcf7ecf7272765 (https://www.ridesims.com/ruffle/2da79230c52ac9361cc6.wasm:wasm-function[1846]:0x3f11c2)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://www.ridesims.com/ride-simulators/Free-Spin
SWF URL: https://www.ridesims.com/sites/default/files/2021-12/FreeSpinsV1.0_12.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-11-16
Channel: nightly
Built: 2021-11-16T00:14:48.393Z
Commit: 24db13ae1e12d2153a7577b998d500a9533ca338
Is extension: false

**Comment by JamesAllgood** [comment]
This can probably be closed, ride sims is running an older version of ruffle at the moment 

im the web developer for the website

**Comment by Herschel** [comment]
Closing in favor of #1905
