### ISSUE TITLE
Error on https://ead.murciaeduca.es/pluginfile.php/912707/mod_resource/content/2/AS06/AS06_Web/index.html

### ISSUE THREAD

**Issue by Desiree313** [ruffle-rs/ruffle#6209]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:494:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:494:50
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:1:6962)
    at std::sync::once::Once::call_once::{{closure}}::h4dcb78b97de78bcf (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/b2fc0abe3dbbf4e736aa.wasm:wasm-function[1016]:0x2f3fd8)
    at std::sync::once::Once::call_inner::h9279eef47cf85b81 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/b2fc0abe3dbbf4e736aa.wasm:wasm-function[1152]:0x3276ac)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h7e6cf7c840665392 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/b2fc0abe3dbbf4e736aa.wasm:wasm-function[4725]:0x4d3db3)
    at std::panicking::rust_panic_with_hook::h47a0e203360b6c10 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/b2fc0abe3dbbf4e736aa.wasm:wasm-function[3192]:0x47f3dc)
    at core::panicking::panic_fmt::h4ca53049f45e3264 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/b2fc0abe3dbbf4e736aa.wasm:wasm-function[4996]:0x4dfa20)
    at core::result::unwrap_failed::h6d050dbd00b66340 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/b2fc0abe3dbbf4e736aa.wasm:wasm-function[4023]:0x4bc7e4)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::ha51e1fedf51093c8 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/b2fc0abe3dbbf4e736aa.wasm:wasm-function[747]:0x26e0aa)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::register_glyph_shape::h0c0da880d9cb52d2 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/b2fc0abe3dbbf4e736aa.wasm:wasm-function[1778]:0x3bbf34)
    at ruffle_core::font::Font::from_swf_tag::h5ad897948c72965a (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/b2fc0abe3dbbf4e736aa.wasm:wasm-function[839]:0x295e01)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: AS06_CONT_R03_Efectos_calorfrio_utilidades_contraindicaciones.swf
Param width: 550
Param height: 350
Param play: false
Param scale: exactfit
Param src: AS06_CONT_R03_Efectos_calorfrio_utilidades_contraindicaciones.swf
Param allowfullscreen: true
Param movie: AS06_CONT_R03_Efectos_calorfrio_utilidades_contraindicaciones.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined

# Page Info
Page URL: https://ead.murciaeduca.es/pluginfile.php/912707/mod_resource/content/2/AS06/AS06_Web/index.html
SWF URL: https://ead.murciaeduca.es/pluginfile.php/912707/mod_resource/content/2/AS06/AS06_Web/AS06_CONT_R03_Efectos_calorfrio_utilidades_contraindicaciones.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.81 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-02-03
Channel: nightly
Built: 2022-02-03T00:19:02.660Z
Commit: 0152a6aa344927cc8290b090ac2d3b4db4ecd1fc
Is extension: true

**Comment by Toad06** [comment]
Closing in favor of https://github.com/ruffle-rs/ruffle/issues/1905 as this is the same issue. Thanks for reporting.
