### ISSUE TITLE
Error on https://ruffle.rs/demo/

### ISSUE THREAD

**Issue by DowncastEnd** [ruffle-rs/ruffle#6213]
# Error Info
Error name: Error
Error message: panicked at 'assertion failed: min <= max', /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/cmp.rs:816:9
Error stack:
```
Error: panicked at 'assertion failed: min <= max', /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/cmp.rs:816:9
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (https://ruffle.rs/demo/966.index.js:1:7291)
    at std::sync::once::Once::call_once::{{closure}}::h9e36c2f9a5daab07 (https://ruffle.rs/demo/37409d23aa107a04ec96.wasm:wasm-function[1060]:0x2fc9c2)
    at std::sync::once::Once::call_inner::h9279eef47cf85b81 (https://ruffle.rs/demo/37409d23aa107a04ec96.wasm:wasm-function[1196]:0x330191)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::ha4fb5aa526be63ff (https://ruffle.rs/demo/37409d23aa107a04ec96.wasm:wasm-function[4892]:0x4ec6c5)
    at std::panicking::rust_panic_with_hook::h47a0e203360b6c10 (https://ruffle.rs/demo/37409d23aa107a04ec96.wasm:wasm-function[3306]:0x4952fb)
    at core::panicking::panic_fmt::h4ca53049f45e3264 (https://ruffle.rs/demo/37409d23aa107a04ec96.wasm:wasm-function[5181]:0x4fc0c2)
    at core::panicking::panic::h35778e3c18266c93 (https://ruffle.rs/demo/37409d23aa107a04ec96.wasm:wasm-function[4889]:0x4ec1ec)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::set_viewport_dimensions::h80dff603b109a6ce (https://ruffle.rs/demo/37409d23aa107a04ec96.wasm:wasm-function[728]:0x25c589)
    at ruffle_web::Ruffle::tick::h6894f89c7efebd69 (https://ruffle.rs/demo/37409d23aa107a04ec96.wasm:wasm-function[653]:0x227c46)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h0828ca3313f5dcc4 (https://ruffle.rs/demo/37409d23aa107a04ec96.wasm:wasm-function[5765]:0x5096ce)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://ruffle.rs/demo/

# Browser Info
Useragent: Mozilla/5.0 (Linux; Android 12; SM-N976V) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.98 Mobile Safari/537.36
OS: Linux aarch64

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-02-03
Channel: nightly
Built: 2022-02-03T00:14:48.452Z
Commit: 0152a6aa344927cc8290b090ac2d3b4db4ecd1fc
Is extension: false

**Comment by Poopooracoocoo** [comment]
Which SWF were you trying to play?

**Comment by n0samu** [comment]
Old issue with no information provided, closing
