### ISSUE TITLE
Error on https://mm.metrogame.net/metro/ok/

### ISSUE THREAD

**Issue by Artem-kurnevic** [ruffle-rs/ruffle#6218]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm2/object.rs:305:48
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm2/object.rs:305:48
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/662.js:1:6962)
    at std::sync::once::Once::call_once::{{closure}}::h4dcb78b97de78bcf (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/0c4ec6b13a062158e9fc.wasm:wasm-function[965]:0x2faaf7)
    at std::sync::once::Once::call_inner::h9279eef47cf85b81 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/0c4ec6b13a062158e9fc.wasm:wasm-function[1179]:0x345266)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h7e6cf7c840665392 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/0c4ec6b13a062158e9fc.wasm:wasm-function[4733]:0x4f5d36)
    at std::panicking::rust_panic_with_hook::h47a0e203360b6c10 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/0c4ec6b13a062158e9fc.wasm:wasm-function[3244]:0x4a307f)
    at core::panicking::panic_fmt::h4ca53049f45e3264 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/0c4ec6b13a062158e9fc.wasm:wasm-function[5003]:0x501e7d)
    at core::panicking::panic::h35778e3c18266c93 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/0c4ec6b13a062158e9fc.wasm:wasm-function[4730]:0x4f585d)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::h640a2e26c8018276 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/0c4ec6b13a062158e9fc.wasm:wasm-function[352]:0xdb41d)
    at ruffle_core::avm2::activation::Activation::do_next_opcode::hfeb3a14a7657719f (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/0c4ec6b13a062158e9fc.wasm:wasm-function[312]:0x2f13e)
    at ruffle_core::avm2::activation::Activation::run_actions::h6d51e9527e6f32fc (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/0c4ec6b13a062158e9fc.wasm:wasm-function[2851]:0x481ead)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: //st.metrogame.net/metro/st/files/450d220bbb25/ok_news.swf
Param allowScriptAccess: always
Param wmode: opaque
Param flashvars: platform=ok&code=metro&protocol=http&chat_host=95.213.174.12
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined
Attribute 6: undefined

# Page Info
Page URL: https://mm.metrogame.net/metro/ok/?container=true&web_server=https%3A%2F%2Fok.ru&first_start=0&logged_user_id=582919448993&sig=d22ab6d54e45bcfb497d46fc05ac1892&refplace=vitrine_user_apps_portlet&new_sig=1&apiconnection=93020928_1644083952634&authorized=1&session_key=-s-1BGm8IRnbIEplszPbDEsAESu9Boo8GUObBF-lpvmbpKtjJUsAIor8pWqbEEn-qVqBnKJBHsNdEGqDsvpgpEmjLwsADom9HWogCErgIc&clientLog=0&session_secret_key=c8e03fba188b691cb708a1adccb5aab0&auth_sig=12c4c941253ed41ce9087c3727f2adeb&api_server=https%3A%2F%2Fapi.ok.ru%2F&ip_geo_location=RU%2C46%2CSaransk&application_key=CBAEGMIGABABABABA
SWF URL: https://st.metrogame.net/metro/st/files/450d220bbb25/ok_news.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.82 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-02-03
Channel: nightly
Built: 2022-02-03T00:19:02.660Z
Commit: 0152a6aa344927cc8290b090ac2d3b4db4ecd1fc
Is extension: true

**Comment by kjarosh** [comment]
Should be fixed as of today—the related code has been heavily rewritten. (See https://github.com/ruffle-rs/ruffle/pull/7095)
