### ISSUE TITLE
Error on http://search.10jqka.com.cn/news/trace

### ISSUE THREAD

**Issue by EternityMar22** [ruffle-rs/ruffle#6232]
# Error Info
Error name: TypeError
Error message: n.match is not a function
Error stack:
```
TypeError: n.match is not a function
    at Object.K [as getOriginFromUrl] (http://s.thsi.cn/js/chameleon/chameleon.min.1644289.js:1:7943)
    at X (http://s.thsi.cn/js/chameleon/chameleon.min.1644289.js:1:18582)
    at http://s.thsi.cn/js/chameleon/chameleon.min.1644289.js:1:16469
    at http://s.thsi.cn/cb?/js/common/monitor/1.0/monitor.min.js:1:2667
    at new Promise (<anonymous>)
    at window.fetch (http://s.thsi.cn/cb?/js/common/monitor/1.0/monitor.min.js:1:2639)
    at n (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:1:37001)
    at chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/ruffle.js?id=94655003604:1:4822
    at async HTMLElement.ensureFreshInstance (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/ruffle.js?id=94655003604:1:17549)
    at async HTMLElement.load (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/ruffle.js?id=94655003604:1:19980)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: /publicbe699820/swf/SouNiuTimeTunnel.swf
Param flashvars: movieName=QeeChart_SouNiuTimeTunneldetail&config=a=1&chartW=645&chartH=216
Param bgColor: #FFFFFF
Param quality: high
Param allowScriptAccess: always
Param wmode: opaque
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined

# Page Info
Page URL: http://search.10jqka.com.cn/news/trace?stockcode=603596&flag=Apo

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-02-08
Channel: nightly
Built: 2022-02-08T00:19:02.354Z
Commit: 6c4a10792dd9349047d3b4b8d0d3a540dca6dd52
Is extension: true

**Comment by Lord-McSweeney** [comment]
Not an issue with Ruffle
