### ISSUE TITLE
Error on http://jakemandell.com/adaptivepitch/

### ISSUE THREAD

**Issue by ChaoticEnigma1121** [ruffle-rs/ruffle#6255]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: JsValue(TypeError: f(...).createBuffer is not a function
TypeError: f(...).createBuffer is not a function
    at chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:1:13508
    at I (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:1:4168)
    at c.wbg.__wbg_createBuffer_79833a4052d7b42a (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:1:13473)
    at web_sys::features::gen_AudioContext::AudioContext::create_buffer::heaed8aef18eabb5b (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/38613bceb96ab2a83e69.wasm:wasm-function[4571]:0x4ced4f)
    at ruffle_web::audio::WebAudioBackend::decompress_to_audio_buffer::hd96db1a6225fcb65 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/38613bceb96ab2a83e69.wasm:wasm-function[465]:0x199937)
    at <ruffle_web::audio::WebAudioBackend as ruffle_core::backend::audio::AudioBackend>::register_sound::h6f61c1f4648866ce (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/38613bceb96ab2a83e69.wasm:wasm-function[2207]:0x4033ab)
    at ruffle_core::display_object::movie_clip::MovieClip::preload::h54ab68b9ccb8f47e (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/38613bceb96ab2a83e69.wasm:wasm-function[855]:0x29e533)
    at ruffle_core::player::Player::set_root_movie::h83070360117c29c4 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/38613bceb96ab2a83e69.wasm:wasm-function[357]:0xde8e5)
    at <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h7fe0b0a8d1ec60ec (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/38613bceb96ab2a83e69.wasm:wasm-function[564]:0x1f99b5)
    at <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h2665a6b2ebc24af9 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/38613bceb96ab2a83e69.wasm:wasm-function[1843]:0x3c553b))', web/src/audio.rs:749:14

# Player Info
Allows script access: true

# Page Info
Page URL: http://jakemandell.com/adaptivepitch/
SWF URL: http://jakemandell.com/adaptivepitch/adaptivepitch450.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.82 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-02-11
Channel: nightly
Built: 2022-02-11T00:16:10.120Z
Commit: a23836b782c0ba48405036e869ff51e2b1fdf7d4
Is extension: true

**Comment by Sonikkustar** [comment]
Seems to work on the latest (as of this post) desktop build:
![Image](https://github.com/user-attachments/assets/50f036f3-c590-4dca-8ba0-55d0238c7ae7)

Tested on **ruffle-nightly-2024_11_02-windows-x86_64**
