### ISSUE TITLE
Error on https://www.jogos360.com.br/head_action_soccer.html

### ISSUE THREAD

**Issue by Alice-Grem** [ruffle-rs/ruffle#6258]
# Error Info
Error name: Error
Error message: panicked at 'index out of bounds: the len is 260 but the index is 260', core/src/backend/render.rs:477:33
Error stack:
```
Error: panicked at 'index out of bounds: the len is 260 but the index is 260', core/src/backend/render.rs:477:33
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.1c979334da677afbcdb2.js:1:6964)
    at std::sync::once::Once::call_once::{{closure}}::h4dcb78b97de78bcf (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.2.12/8136578cccbaf4758176.wasm:wasm-function[1020]:0x2f5e19)
    at std::sync::once::Once::call_inner::h9279eef47cf85b81 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.2.12/8136578cccbaf4758176.wasm:wasm-function[1155]:0x3273e7)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h7e6cf7c840665392 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.2.12/8136578cccbaf4758176.wasm:wasm-function[4690]:0x4cd884)
    at std::panicking::rust_panic_with_hook::h47a0e203360b6c10 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.2.12/8136578cccbaf4758176.wasm:wasm-function[3173]:0x47a998)
    at core::panicking::panic_fmt::h4ca53049f45e3264 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.2.12/8136578cccbaf4758176.wasm:wasm-function[4957]:0x4d941a)
    at core::panicking::panic_bounds_check::h859d2a727fd634e5 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.2.12/8136578cccbaf4758176.wasm:wasm-function[4189]:0x4be296)
    at ruffle_core::backend::render::decode_define_bits_lossless::hb462e638fd507a7d (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.2.12/8136578cccbaf4758176.wasm:wasm-function[426]:0x1701f7)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::register_bitmap_png::h77aaf09537630c9d (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.2.12/8136578cccbaf4758176.wasm:wasm-function[3842]:0x4ad7c5)
    at ruffle_core::display_object::movie_clip::MovieClipData::define_bits_lossless::ha54551d9c51d3a83 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.2.12/8136578cccbaf4758176.wasm:wasm-function[1351]:0x35ac16)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.jogos360.com.br/head_action_soccer.html
SWF URL: https://cdn.jogos360.com.br/files/games/he/ad/head-action-soccer.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.82 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-02-12
Channel: nightly
Built: 2022-02-12T00:19:18.042Z
Commit: ad2b8ea00778913b23a65fb847e3bec505876648
Is extension: false

**Comment by adrian17** [comment]
2 colors + 1x255 image means 261 bytes, but the decompressed zlib has 260 bytes...?
But at a glance, it's even weirder than that, in JPEXS this tag looks mixed with some actionscript code...?
So it's either some breakage that Ruffle should recognize and ignore, or it's part of an AS obfuscation, which... we should also recognize and ignore :) Not sure what exactly we should recognize though...

![image](https://user-images.githubusercontent.com/4729533/153730389-be96b700-06eb-460e-a0e4-527b287cf1b6.png)
