### ISSUE TITLE
Error on chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/player.html

### ISSUE THREAD

**Issue by Sir03** [ruffle-rs/ruffle#6289]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/library.rs:329:26
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/library.rs:329:26
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:1:6962)
    at std::sync::once::Once::call_once::{{closure}}::h57f353594701b2e5 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/b0d007fedf2800e8ad0b.wasm:wasm-function[1025]:0x2f7ffd)
    at std::sync::once::Once::call_inner::h9279eef47cf85b81 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/b0d007fedf2800e8ad0b.wasm:wasm-function[1158]:0x328e18)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h06ccaed8fde3b163 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/b0d007fedf2800e8ad0b.wasm:wasm-function[4697]:0x4d086f)
    at std::panicking::rust_panic_with_hook::h47a0e203360b6c10 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/b0d007fedf2800e8ad0b.wasm:wasm-function[3179]:0x47cec5)
    at core::panicking::panic_fmt::h4ca53049f45e3264 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/b0d007fedf2800e8ad0b.wasm:wasm-function[4959]:0x4dc29c)
    at core::panicking::panic::h35778e3c18266c93 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/b0d007fedf2800e8ad0b.wasm:wasm-function[4694]:0x4d0396)
    at ruffle_core::avm2::globals::flash::display::loaderinfo::application_domain::h82db9314a8e44d52 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/b0d007fedf2800e8ad0b.wasm:wasm-function[2498]:0x432a9a)
    at ruffle_core::avm2::function::Executable::exec::h4c5b8f4a0cc601f2 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/b0d007fedf2800e8ad0b.wasm:wasm-function[863]:0x2b28e9)
    at ruffle_core::avm2::object::TObject::call_method::hd91210869bdd7624 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/b0d007fedf2800e8ad0b.wasm:wasm-function[1386]:0x36257d)
```

# Player Info
Allows script access: false

# Page Info
Page URL: chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/player.html?url=https%3A%2F%2Fstatic1.e621.net%2Fdata%2F3e%2F48%2F3e484b804222737161910756cf0ffd14.swf
SWF URL: https://static1.e621.net/data/3e/48/3e484b804222737161910756cf0ffd14.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-02-14
Channel: nightly
Built: 2022-02-14T00:18:21.503Z
Commit: 4e2f7b02fc3521b437912eccf36762fe50ba5976
Is extension: true

**Comment by n0samu** [comment]
This problem seems to be fixed now. Please leave a comment if anything is still broken and I can reopen the issue.
