### ISSUE TITLE
Error on http://szhong.4399.com/4399swf//upload_swf/ftp13/linqinson/20131223/lxycj1/game3D.htm

### ISSUE THREAD

**Issue by JacobPolito** [ruffle-rs/ruffle#6318]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm2/object.rs:305:48
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm2/object.rs:305:48
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:1:6962)
    at std::sync::once::Once::call_once::{{closure}}::ha69306374a0d7c42 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/18f70695ff32c2ad02b2.wasm:wasm-function[1024]:0x2f8ea2)
    at std::sync::once::Once::call_inner::h9279eef47cf85b81 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/18f70695ff32c2ad02b2.wasm:wasm-function[1157]:0x32a34e)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hd4ed35f37e0c71aa (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/18f70695ff32c2ad02b2.wasm:wasm-function[4695]:0x4d1df4)
    at std::panicking::rust_panic_with_hook::h47a0e203360b6c10 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/18f70695ff32c2ad02b2.wasm:wasm-function[3177]:0x47e42e)
    at core::panicking::panic_fmt::h4ca53049f45e3264 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/18f70695ff32c2ad02b2.wasm:wasm-function[4957]:0x4dd821)
    at core::panicking::panic::h35778e3c18266c93 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/18f70695ff32c2ad02b2.wasm:wasm-function[4692]:0x4d191b)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::hb14471f61fd47c8a (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/18f70695ff32c2ad02b2.wasm:wasm-function[335]:0xaaff8)
    at ruffle_core::avm2::activation::Activation::do_next_opcode::h7c31ed8f24ad452a (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/18f70695ff32c2ad02b2.wasm:wasm-function[312]:0x2db35)
    at ruffle_core::avm2::activation::Activation::run_actions::he150933e25312304 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/18f70695ff32c2ad02b2.wasm:wasm-function[2890]:0x464708)
```

# Player Info
Allows script access: false

# Page Info
Page URL: http://szhong.4399.com/4399swf//upload_swf/ftp13/linqinson/20131223/lxycj1/game3D.htm
SWF URL: http://szhong.4399.com/4399swf//upload_swf/ftp13/linqinson/20131223/lxycj1/main.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36 Edg/98.0.1108.56
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-02-19
Channel: nightly
Built: 2022-02-19T00:15:44.456Z
Commit: 2ca62ecf4bac5696d2da084b1f5d5c6ba2a4e0f7
Is extension: true

**Comment by kjarosh** [comment]
Should be fixed as of today—the related code has been heavily rewritten. (See https://github.com/ruffle-rs/ruffle/pull/7095)
