### ISSUE TITLE
Error on https://funkypotato.com/gun-mayhem-2-more-mayhem/

### ISSUE THREAD

**Issue by Crossoverfan96** [ruffle-rs/ruffle#6322]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:494:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:494:50
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (https://funkypotato.com/ruffle/core.ruffle.08124f6dd5c7e72ca855.js:1:6964)
    at std::sync::once::Once::call_once::{{closure}}::h4dcb78b97de78bcf (https://funkypotato.com/ruffle/f91bedccc781eba86e58.wasm:wasm-function[1019]:0x2f8ef2)
    at std::sync::once::Once::call_inner::h9279eef47cf85b81 (https://funkypotato.com/ruffle/f91bedccc781eba86e58.wasm:wasm-function[1157]:0x32aaba)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h7e6cf7c840665392 (https://funkypotato.com/ruffle/f91bedccc781eba86e58.wasm:wasm-function[4721]:0x4d76d9)
    at std::panicking::rust_panic_with_hook::h47a0e203360b6c10 (https://funkypotato.com/ruffle/f91bedccc781eba86e58.wasm:wasm-function[3188]:0x482726)
    at core::panicking::panic_fmt::h4ca53049f45e3264 (https://funkypotato.com/ruffle/f91bedccc781eba86e58.wasm:wasm-function[4992]:0x4e3346)
    at core::result::unwrap_failed::h6d050dbd00b66340 (https://funkypotato.com/ruffle/f91bedccc781eba86e58.wasm:wasm-function[4020]:0x4c018b)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::ha51e1fedf51093c8 (https://funkypotato.com/ruffle/f91bedccc781eba86e58.wasm:wasm-function[750]:0x27194e)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::register_glyph_shape::h0c0da880d9cb52d2 (https://funkypotato.com/ruffle/f91bedccc781eba86e58.wasm:wasm-function[1780]:0x3bf796)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render_self::hc3743e229ae42b22 (https://funkypotato.com/ruffle/f91bedccc781eba86e58.wasm:wasm-function[3176]:0x47f1bd)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: /gamez/gun-mayhem-2-more-mayhem.swf
Param movie: /gamez/gun-mayhem-2-more-mayhem.swf
Param quality: best
Param bgcolor: #000000
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined

# Page Info
Page URL: https://funkypotato.com/gun-mayhem-2-more-mayhem/
SWF URL: https://funkypotato.com/gamez/gun-mayhem-2-more-mayhem.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; CrOS x86_64 14388.61.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.107 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-01-26
Channel: nightly
Built: 2022-01-26T00:18:09.413Z
Commit: d5986a72947f5552b29805e3971ce58939fdd1a2
Is extension: false

**Comment by Herschel** [comment]
Closing in favor of #1905
