### ISSUE TITLE
Error on https://hmekke.herokuapp.com/dhdncjshd/aHR0cHM6Ly9zaHNnYW1lcy5naXRodWIuaW8=/g/734653d2/henry-stickmin---crossing-the-pit

### ISSUE THREAD

**Issue by B0MBUM** [ruffle-rs/ruffle#6392]
# Error Info
Error name: TypeError
Error message: str.startsWith is not a function
Error stack:
```
TypeError: str.startsWith is not a function
    at rewrite_url (https://hmekke.herokuapp.com/dhdncjshd/utils/assets/inject.js:11:13)
    at window.fetch (https://hmekke.herokuapp.com/dhdncjshd/utils/assets/inject.js:31:11)
    at n (https://hmekke.herokuapp.com/dhdncjshd/aHR0cHM6Ly9obWVra2UuaGVyb2t1YXBwLmNvbQ==/dhdncjshd/aHR0cHM6Ly9zaHNnYW1lcy5naXRodWIuaW8=/ruffle/core.ruffle.3c40dc0bd68b80f95b7b.js:1:36891)
    at https://hmekke.herokuapp.com/dhdncjshd/aHR0cHM6Ly9zaHNnYW1lcy5naXRodWIuaW8=/ruffle/ruffle.js:1:17456
    at async T.ensureFreshInstance (https://hmekke.herokuapp.com/dhdncjshd/aHR0cHM6Ly9zaHNnYW1lcy5naXRodWIuaW8=/ruffle/ruffle.js:1:16202)
    at async T.load (https://hmekke.herokuapp.com/dhdncjshd/aHR0cHM6Ly9zaHNnYW1lcy5naXRodWIuaW8=/ruffle/ruffle.js:1:19688)
```

# Player Info
Allows script access: false
Player type: Object
SWF URL: https://cdn.jsdelivr.net/gh/JoshMerlino/shsg-pfile/games/henry-stickmin---crossing-the-pit.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://hmekke.herokuapp.com/dhdncjshd/aHR0cHM6Ly9zaHNnYW1lcy5naXRodWIuaW8=/g/734653d2/henry-stickmin---crossing-the-pit

# Browser Info
Useragent: Mozilla/5.0 (X11; CrOS x86_64 14388.52.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.91 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-02-19
Channel: nightly
Built: 2022-02-19T00:15:44.456Z
Commit: 2ca62ecf4bac5696d2da084b1f5d5c6ba2a4e0f7
Is extension: false

**Comment by n0samu** [comment]
This problem occurs because the website is overriding the fetch API with its own wrapper function:
```let fetch_rewrite = window.fetch;  window.fetch = function(url, options) {
    url = rewrite_url(url);
    return fetch_rewrite.apply(this, arguments);
}```
The `rewrite_url` function assumes that it will be passed a URL as a string, calling the `startsWith` method that only works on strings. However, Ruffle passes a URL object to the fetch API, not a string. The website's script does not deal with this case and throws an error, so Ruffle does not work.
