### ISSUE TITLE
Error on https://www.invisionsportsarcade.com/index.php

### ISSUE THREAD

**Issue by bllsht2** [ruffle-rs/ruffle#6405]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm2/object.rs:305:48
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm2/object.rs:305:48
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (https://www.invisionsportsarcade.com/ruffle/core.ruffle.b409b6b0a11c855f8463.js:1:7572)
    at std::sync::once::Once::call_once::{{closure}}::h04c6018a30aae0b2 (wasm://wasm/017f11b2:wasm-function[990]:0x2c53bc)
    at std::sync::once::Once::call_inner::h51a70f81ef530383 (wasm://wasm/017f11b2:wasm-function[1495]:0x358f1d)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h629785d4908f37da (wasm://wasm/017f11b2:wasm-function[4930]:0x4a4fa8)
    at std::panicking::rust_panic_with_hook::h12b2f0179ff84c92 (wasm://wasm/017f11b2:wasm-function[3295]:0x44a505)
    at core::panicking::panic_fmt::hf0d93ec1ac504cf9 (wasm://wasm/017f11b2:wasm-function[5217]:0x4b2602)
    at core::panicking::panic::h5d6906e2c1099660 (wasm://wasm/017f11b2:wasm-function[4927]:0x4a4acf)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::he53bacc4a9ffa176 (wasm://wasm/017f11b2:wasm-function[413]:0x141fc1)
    at ruffle_core::avm2::activation::Activation::run_actions::h46b8ca0573825365 (wasm://wasm/017f11b2:wasm-function[313]:0xa57b)
    at ruffle_core::avm2::function::Executable::exec::he6322ea690c15bd6 (wasm://wasm/017f11b2:wasm-function[727]:0x24f2c7)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://www.invisionsportsarcade.com/index.php?autocom=arcade&do=play&gameid=40013
SWF URL: https://www.invisionsportsarcade.com/arcade/CrazyCollapseAS3v2TH.swf?ibpro_gameid=7042299

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-03-03
Channel: nightly
Built: 2022-03-03T00:16:21.104Z
Commit: 2faabfb58e2640261ea351d3d3a05382da73b5ad
Is extension: false

**Comment by kjarosh** [comment]
Should be fixed as of today—the related code has been heavily rewritten. (See https://github.com/ruffle-rs/ruffle/pull/7095)
