### ISSUE TITLE
Error on https://www.dolldivine.com/animal-maker-collection.php

### ISSUE THREAD

**Issue by PantherRoars** [ruffle-rs/ruffle#6430]
# Error Info
Error name: Error
Error message: panicked at 'assertion failed: min <= max', /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/cmp.rs:816:9
Error stack:
```
Error: panicked at 'assertion failed: min <= max', /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/cmp.rs:816:9
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (https://www.dolldivine.com/ruffle/core.ruffle.dd69ca56c8243738e0cc.js:1:6964)
    at std::sync::once::Once::call_once::{{closure}}::h4dcb78b97de78bcf (wasm-function[965]:0x2faaf7)
    at std::sync::once::Once::call_inner::h9279eef47cf85b81 (wasm-function[1179]:0x345266)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h7e6cf7c840665392 (wasm-function[4733]:0x4f5d36)
    at std::panicking::rust_panic_with_hook::h47a0e203360b6c10 (wasm-function[3244]:0x4a307f)
    at core::panicking::panic_fmt::h4ca53049f45e3264 (wasm-function[5003]:0x501e7d)
    at core::panicking::panic::h35778e3c18266c93 (wasm-function[4730]:0x4f585d)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::set_viewport_dimensions::h97b1ff6d070e44bc (wasm-function[693]:0x267eab)
    at ruffle_web::Ruffle::tick::hf8a4913ed3d1fe2b (wasm-function[588]:0x21ab65)
    at <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h06c843e3835d8519 (wasm-function[390]:0x148fb5)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://www.dolldivine.com/animal-maker-collection.php

# Browser Info
Useragent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-01-31
Channel: nightly
Built: 2022-01-31T00:17:51.537Z
Commit: 83cc9dc30834acdf8bc03c9fe7392713a7e53792
Is extension: false

**Comment by Lord-McSweeney** [comment]
Should have been fixed by #6458 a long time ago
