### ISSUE TITLE
Error on https://aulavirtual33.educa.madrid.org/ies.sanjuandelacruz.pozuelodealarcon/pluginfile.php/42792/mod_resource/content/1/AI03/AI03_Web/index.html

### ISSUE THREAD

**Issue by Yoayla** [ruffle-rs/ruffle#6435]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:494:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:494:50
    at u.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://kkiahfkkojnfcifhanegmkdgbfbpcdha/dist/ruffle.js?id=22296409101:1:7173)
    at std::sync::once::Once::call_once::{{closure}}::ha2a6e9c1727c0056 (chrome-extension://kkiahfkkojnfcifhanegmkdgbfbpcdha/dist/60a5dad30d6929f3cbe6.wasm:wasm-function[987]:0x2d87bd)
    at std::sync::once::Once::call_inner::h02a6489b0ecfb269 (chrome-extension://kkiahfkkojnfcifhanegmkdgbfbpcdha/dist/60a5dad30d6929f3cbe6.wasm:wasm-function[1327]:0x34bee7)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h5c1b8acd952e19de (chrome-extension://kkiahfkkojnfcifhanegmkdgbfbpcdha/dist/60a5dad30d6929f3cbe6.wasm:wasm-function[4691]:0x4f3237)
    at std::panicking::rust_panic_with_hook::h364974e717ed59ec (chrome-extension://kkiahfkkojnfcifhanegmkdgbfbpcdha/dist/60a5dad30d6929f3cbe6.wasm:wasm-function[3327]:0x4a2e37)
    at rust_begin_unwind (chrome-extension://kkiahfkkojnfcifhanegmkdgbfbpcdha/dist/60a5dad30d6929f3cbe6.wasm:wasm-function[4753]:0x4f59cf)
    at core::panicking::panic_fmt::hf69c8b08bc9d2ee5 (chrome-extension://kkiahfkkojnfcifhanegmkdgbfbpcdha/dist/60a5dad30d6929f3cbe6.wasm:wasm-function[4960]:0x500530)
    at core::result::unwrap_failed::h694db13a45aa6740 (chrome-extension://kkiahfkkojnfcifhanegmkdgbfbpcdha/dist/60a5dad30d6929f3cbe6.wasm:wasm-function[4019]:0x4dbb52)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::h4a49cf94641b67f6 (chrome-extension://kkiahfkkojnfcifhanegmkdgbfbpcdha/dist/60a5dad30d6929f3cbe6.wasm:wasm-function[695]:0x23921d)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::register_glyph_shape::hd56109184b1ca824 (chrome-extension://kkiahfkkojnfcifhanegmkdgbfbpcdha/dist/60a5dad30d6929f3cbe6.wasm:wasm-function[1838]:0x3d763b)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: AI03_CONT_R35_PATOLOGIARAQUIS.swf
Param play: false
Param scale: exactfit
Param src: AI03_CONT_R35_PATOLOGIARAQUIS.swf
Param width: 550
Param height: 350
Param allowfullscreen: true
Param movie: AI03_CONT_R35_PATOLOGIARAQUIS.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined

# Page Info
Page URL: https://aulavirtual33.educa.madrid.org/ies.sanjuandelacruz.pozuelodealarcon/pluginfile.php/42792/mod_resource/content/1/AI03/AI03_Web/index.html?embed=1
SWF URL: https://aulavirtual33.educa.madrid.org/ies.sanjuandelacruz.pozuelodealarcon/pluginfile.php/42792/mod_resource/content/1/AI03/AI03_Web/AI03_CONT_R35_PATOLOGIARAQUIS.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-11-24
Channel: nightly
Built: 2021-11-24T00:13:46.423Z
Commit: da4ed75bc82957aa6fff8c6178d1f798466be8be
Is extension: true

**Comment by Herschel** [comment]
Closing in favor of #1905
