### ISSUE TITLE
Error on https://www.jamesweb.co.uk/flashiframe.php

### ISSUE THREAD

**Issue by CSeriestechhero** [ruffle-rs/ruffle#6462]
# Error Info
Error name: Error
Error message: panicked at 'assertion failed: min <= max', /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/cmp.rs:817:9
Error stack:
```
Error: panicked at 'assertion failed: min <= max', /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/cmp.rs:817:9
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (https://www.jamesweb.co.uk/assets/ruffle/core.ruffle.4f942424819c1a15aec4.js:1:7572)
    at std::sync::once::Once::call_once::{{closure}}::h9bbf01ee609e3a75 (https://www.jamesweb.co.uk/assets/ruffle/41c2d9381d370d3c9949.wasm:wasm-function[1024]:0x2c513d)
    at std::sync::once::Once::call_inner::h51a70f81ef530383 (https://www.jamesweb.co.uk/assets/ruffle/41c2d9381d370d3c9949.wasm:wasm-function[1467]:0x33517b)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h360f2d0dfec34f5b (https://www.jamesweb.co.uk/assets/ruffle/41c2d9381d370d3c9949.wasm:wasm-function[4911]:0x483844)
    at std::panicking::rust_panic_with_hook::h12b2f0179ff84c92 (https://www.jamesweb.co.uk/assets/ruffle/41c2d9381d370d3c9949.wasm:wasm-function[3230]:0x426b89)
    at core::panicking::panic_fmt::hf0d93ec1ac504cf9 (https://www.jamesweb.co.uk/assets/ruffle/41c2d9381d370d3c9949.wasm:wasm-function[5197]:0x48f8fe)
    at core::panicking::panic::h5d6906e2c1099660 (https://www.jamesweb.co.uk/assets/ruffle/41c2d9381d370d3c9949.wasm:wasm-function[4908]:0x48336b)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::set_viewport_dimensions::h070fe4e526bf136e (https://www.jamesweb.co.uk/assets/ruffle/41c2d9381d370d3c9949.wasm:wasm-function[633]:0x209a90)
    at ruffle_web::Ruffle::tick::h67110e3b656b503e (https://www.jamesweb.co.uk/assets/ruffle/41c2d9381d370d3c9949.wasm:wasm-function[555]:0x1c721b)
    at <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hf8353cf13f6b9398 (https://www.jamesweb.co.uk/assets/ruffle/41c2d9381d370d3c9949.wasm:wasm-function[375]:0x101df8)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: flash/windowsrg.swf
Param movie: flash/windowsrg.swf
Param quality: high
Param play: true
Param loop: true
Param wmode: window
Param scale: showall
Param menu: true
Param devicefont: false
Param allowScriptAccess: sameDomain
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined

# Page Info
Page URL: https://www.jamesweb.co.uk/flashiframe.php?jw=windowsrg

# Browser Info
Useragent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-03-14
Channel: nightly
Built: 2022-03-14T00:20:13.350Z
Commit: f8f2764ac7569f0f38cde3938f631f8c644c9cf7
Is extension: false

**Comment by Lord-McSweeney** [comment]
Should have been fixed by #6458 a long time ago
