### ISSUE TITLE
Error on https://aulavirtual33.educa.madrid.org/ies.sanjuandelacruz.pozuelodealarcon/pluginfile.php/42792/mod_resource/content/1/AI03/AI03_Web/index.html

### ISSUE THREAD

**Issue by Yoayla** [ruffle-rs/ruffle#6463]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:490:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:490:50
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://chnphfcamjjnngdigkcgeehhcdkkciil/dist/966.js:1:7570)
    at std::sync::once::Once::call_once::{{closure}}::ha27d2325af960a5b (chrome-extension://chnphfcamjjnngdigkcgeehhcdkkciil/dist/1efd2883e915fdd7784d.wasm:wasm-function[1024]:0x2c4eb0)
    at std::sync::once::Once::call_inner::h51a70f81ef530383 (chrome-extension://chnphfcamjjnngdigkcgeehhcdkkciil/dist/1efd2883e915fdd7784d.wasm:wasm-function[1467]:0x334f07)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hf341824e07fc18a0 (chrome-extension://chnphfcamjjnngdigkcgeehhcdkkciil/dist/1efd2883e915fdd7784d.wasm:wasm-function[4915]:0x48382d)
    at std::panicking::rust_panic_with_hook::h12b2f0179ff84c92 (chrome-extension://chnphfcamjjnngdigkcgeehhcdkkciil/dist/1efd2883e915fdd7784d.wasm:wasm-function[3231]:0x426a51)
    at core::panicking::panic_fmt::hf0d93ec1ac504cf9 (chrome-extension://chnphfcamjjnngdigkcgeehhcdkkciil/dist/1efd2883e915fdd7784d.wasm:wasm-function[5201]:0x48f908)
    at core::result::unwrap_failed::hd5a60243cf946632 (chrome-extension://chnphfcamjjnngdigkcgeehhcdkkciil/dist/1efd2883e915fdd7784d.wasm:wasm-function[4134]:0x46b18c)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::ha06542393f459715 (chrome-extension://chnphfcamjjnngdigkcgeehhcdkkciil/dist/1efd2883e915fdd7784d.wasm:wasm-function[740]:0x240029)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::register_glyph_shape::hb26b511004939de4 (chrome-extension://chnphfcamjjnngdigkcgeehhcdkkciil/dist/1efd2883e915fdd7784d.wasm:wasm-function[1724]:0x36e835)
    at ruffle_core::font::Font::from_swf_tag::h1f0b151256637dd9 (chrome-extension://chnphfcamjjnngdigkcgeehhcdkkciil/dist/1efd2883e915fdd7784d.wasm:wasm-function[839]:0x26d9ce)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: AI03_CONT_R46_RHPMBRO.swf
Param width: 550
Param height: 500
Param play: false
Param scale: exactfit
Param src: AI03_CONT_R46_RHPMBRO.swf
Param allowfullscreen: true
Param movie: AI03_CONT_R46_RHPMBRO.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined

# Page Info
Page URL: https://aulavirtual33.educa.madrid.org/ies.sanjuandelacruz.pozuelodealarcon/pluginfile.php/42792/mod_resource/content/1/AI03/AI03_Web/index.html?embed=1
SWF URL: https://aulavirtual33.educa.madrid.org/ies.sanjuandelacruz.pozuelodealarcon/pluginfile.php/42792/mod_resource/content/1/AI03/AI03_Web/AI03_CONT_R46_RHPMBRO.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-03-15
Channel: nightly
Built: 2022-03-15T00:16:55.349Z
Commit: e9167cf43c44f6511145301c0127722446b6ece5
Is extension: true

**Comment by Herschel** [comment]
Closing in favor of #1905
