### ISSUE TITLE
OOM error / vec capacity overflow error when reading fuzzed SWF file

### ISSUE THREAD

**Issue by ghost** [ruffle-rs/ruffle#6473]
I tested this file on the demo page, and it failed. The file has base64 `RldT//8o//8=` (github doesn't make it easy to attach binary files that it doesn't like, so hopefully the base64 is good enough!)

When ran with address sanitizer, it fails with 

```
==4002093== ERROR: libFuzzer: out-of-memory (malloc(4294912255))
   To change the out-of-memory limit use -rss_limit_mb=<N>

    #0 0x556caad02ff1 in __sanitizer_print_stack_trace /rustc/llvm/src/llvm-project/compiler-rt/lib/asan/asan_stack.cpp:87:3
    #1 0x556cab33d328 in fuzzer::PrintStackTrace() (/home/jess/.cache/cargo/target/x86_64-unknown-linux-gnu/release/fuzz_target_1+0xa4b328) (BuildId: 24047da10f2449c9a397051d7855a3d778ddc853)
    #2 0x556cab317214 in fuzzer::Fuzzer::HandleMalloc(unsigned long) (/home/jess/.cache/cargo/target/x86_64-unknown-linux-gnu/release/fuzz_target_1+0xa25214) (BuildId: 24047da10f2449c9a397051d7855a3d778ddc853)
    #3 0x556cab317281 in fuzzer::MallocHook(void const volatile*, unsigned long) (/home/jess/.cache/cargo/target/x86_64-unknown-linux-gnu/release/fuzz_target_1+0xa25281) (BuildId: 24047da10f2449c9a397051d7855a3d778ddc853)
    #4 0x556caad0a277 in __sanitizer::RunMallocHooks(void const*, unsigned long) /rustc/llvm/src/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_common.cpp:316:5
    #5 0x556caac791bb in __asan::Allocator::Allocate(unsigned long, unsigned long, __sanitizer::BufferedStackTrace*, __asan::AllocType, bool) /rustc/llvm/src/llvm-project/compiler-rt/lib/asan/asan_allocator.cpp:600:5
    #6 0x556caac78b33 in __asan::asan_malloc(unsigned long, __sanitizer::BufferedStackTrace*) /rustc/llvm/src/llvm-project/compiler-rt/lib/asan/asan_allocator.cpp:953:34
    #7 0x556caacf8e3d in malloc /rustc/llvm/src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:70:10
    #8 0x556caad47887 in swf::read::decompress_swf::h31f16e2dab9a4774 (/home/jess/.cache/cargo/target/x86_64-unknown-linux-gnu/release/fuzz_target_1+0x455887) (BuildId: 24047da10f2449c9a397051d7855a3d778ddc853)
    #9 0x556caadb3034 in rust_fuzzer_test_input (/home/jess/.cache/cargo/target/x86_64-unknown-linux-gnu/release/fuzz_target_1+0x4c1034) (BuildId: 24047da10f2449c9a397051d7855a3d778ddc853)
    #10 0x556cab3029d8 in __rust_try libfuzzer_sys.9a61624b-cgu.0
    #11 0x556cab301d18 in LLVMFuzzerTestOneInput (/home/jess/.cache/cargo/target/x86_64-unknown-linux-gnu/release/fuzz_target_1+0xa0fd18) (BuildId: 24047da10f2449c9a397051d7855a3d778ddc853)
    #12 0x556cab317931 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/home/jess/.cache/cargo/target/x86_64-unknown-linux-gnu/release/fuzz_target_1+0xa25931) (BuildId: 24047da10f2449c9a397051d7855a3d778ddc853)
    #13 0x556cab30b86a in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) (/home/jess/.cache/cargo/target/x86_64-unknown-linux-gnu/release/fuzz_target_1+0xa1986a) (BuildId: 24047da10f2449c9a397051d7855a3d778ddc853)
    #14 0x556cab30f882 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/home/jess/.cache/cargo/target/x86_64-unknown-linux-gnu/release/fuzz_target_1+0xa1d882) (BuildId: 24047da10f2449c9a397051d7855a3d778ddc853)
    #15 0x556caac77892 in main (/home/jess/.cache/cargo/target/x86_64-unknown-linux-gnu/release/fuzz_target_1+0x385892) (BuildId: 24047da10f2449c9a397051d7855a3d778ddc853)
    #16 0x7f27e6dde30f in __libc_start_call_main libc-start.c
    #17 0x7f27e6dde3c0 in __libc_start_main@GLIBC_2.2.5 (/usr/lib/libc.so.6+0x2d3c0) (BuildId: 85766e9d8458b16e9c7ce6e07c712c02b8471dbc)
    #18 0x556caac77a34 in _start (/home/jess/.cache/cargo/target/x86_64-unknown-linux-gnu/release/fuzz_target_1+0x385a34) (BuildId: 24047da10f2449c9a397051d7855a3d778ddc853)

SUMMARY: libFuzzer: out-of-memory
```

The code I used to fuzz is

```rust
#![no_main]
use libfuzzer_sys::fuzz_target;

fuzz_target!(|data: &[u8]| {
    let c = std::io::Cursor::new(data);
    let buf = swf::decompress_swf(c);
});
```

When I run this through the scanner, it doesn't crash the scanner, but the scanner says it failed to decompress.

The error from the demo page is:

# Error Info
Error name: Error
Error message: panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:518:5
Error stack:
```
966/e/c.wbg.__wbg_new_df6e6ab7a65c4c4d@https://ruffle.rs/demo/966.index.js:1:7291
std::sync::once::Once::call_once::{{closure}}::hf65f47aeb5c696fc@https://ruffle.rs/demo/91d64c2051521227f823.wasm:wasm-function[1061]:0x2c7f5a
std::sync::once::Once::call_inner::h51a70f81ef530383@https://ruffle.rs/demo/91d64c2051521227f823.wasm:wasm-function[1513]:0x33be2f
core::ops::function::FnOnce::call_once{{vtable.shim}}::h1121c931a88fc4d9@https://ruffle.rs/demo/91d64c2051521227f823.wasm:wasm-function[5093]:0x498b90
std::panicking::rust_panic_with_hook::h12b2f0179ff84c92@https://ruffle.rs/demo/91d64c2051521227f823.wasm:wasm-function[3352]:0x438ff3
core::panicking::panic_fmt::hf0d93ec1ac504cf9@https://ruffle.rs/demo/91d64c2051521227f823.wasm:wasm-function[5396]:0x4a834d
core::panicking::panic::h5d6906e2c1099660@https://ruffle.rs/demo/91d64c2051521227f823.wasm:wasm-function[5090]:0x4986b7
alloc::raw_vec::capacity_overflow::h0d69774cff02e19b@https://ruffle.rs/demo/91d64c2051521227f823.wasm:wasm-function[5818]:0x4ae6e4
alloc::raw_vec::RawVec<T,A>::allocate_in::h7a1f45e882832d42@https://ruffle.rs/demo/91d64c2051521227f823.wasm:wasm-function[4587]:0x48ae80
ruffle_core::tag_utils::SwfMovie::from_data::hfbcdf170758eec6b@https://ruffle.rs/demo/91d64c2051521227f823.wasm:wasm-function[472]:0x1643fd
ruffle_load_data@https://ruffle.rs/demo/91d64c2051521227f823.wasm:wasm-function[4405]:0x483c02
load_data@https://ruffle.rs/demo/966.index.js:1:5029
load@https://ruffle.rs/demo/index.js:1:30331

```

# Player Info
Allows script access: false

# Page Info
Page URL: https://ruffle.rs/demo/

# Browser Info
Useragent: Mozilla/5.0 (X11; Linux x86_64; rv:97.0) Gecko/20100101 Firefox/97.0
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-03-17
Channel: nightly
Built: 2022-03-17T00:15:39.270Z
Commit: 50bdb4091434753016950707f7ace5f24df70989
Is extension: false

---

How should we be handling this? Have decompress_swf take a size limit, and just hard fail on anything more than that? Rust also has fallible allocation, but in my experience that doesn't work terribly well on linux desktop, due to overcommit.

**Comment by adrian17** [comment]
> How should we be handling this?

I'm not sure if this is a big deal.
I think panicking on completely malformed input isn't wrong for end-user application; admittedly it would be nice to give users a nice error message, but not sure if we want to handle every possible edge case.
This isn't a segfault, it's a panic; in a way, this already is a "hard fail above some size limit" - at least on wasm, which is currently by definition limited to 32-bit address space.

**Comment by Lord-McSweeney** [comment]
Fixed by #23962. Running the SWF in the web player now brings up the invalid SWF screen instead of a "capacity overflow" panic.
