### ISSUE TITLE
Error on http://systems.open.ac.uk/materials/T552/pages/rich/rp-miners.html

### ISSUE THREAD

**Issue by mcdogfood** [ruffle-rs/ruffle#6482]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:490:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:490:50
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:1:7570)
    at std::sync::once::Once::call_once::{{closure}}::h8cc59a0b8a1b03e2 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/6eb258805834d3c235ef.wasm:wasm-function[1023]:0x2c3c5c)
    at std::sync::once::Once::call_inner::h51a70f81ef530383 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/6eb258805834d3c235ef.wasm:wasm-function[1457]:0x330fa0)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::haa76f48d1b3c2435 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/6eb258805834d3c235ef.wasm:wasm-function[4908]:0x4827fd)
    at std::panicking::rust_panic_with_hook::h12b2f0179ff84c92 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/6eb258805834d3c235ef.wasm:wasm-function[3229]:0x42594c)
    at core::panicking::panic_fmt::hf0d93ec1ac504cf9 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/6eb258805834d3c235ef.wasm:wasm-function[5191]:0x48e8ba)
    at core::result::unwrap_failed::hd5a60243cf946632 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/6eb258805834d3c235ef.wasm:wasm-function[4133]:0x46a34f)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::h151e83d5ba38548e (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/6eb258805834d3c235ef.wasm:wasm-function[738]:0x23ea43)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::register_glyph_shape::h9762dd0f72c1996b (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/6eb258805834d3c235ef.wasm:wasm-function[1719]:0x36d1d5)
    at ruffle_core::font::Font::from_swf_tag::hb3c572cd383cb8f7 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/6eb258805834d3c235ef.wasm:wasm-function[834]:0x269dca)
```

# Player Info
Allows script access: true

# Page Info
Page URL: http://systems.open.ac.uk/materials/T552/pages/rich/rp-miners.html
SWF URL: http://systems.open.ac.uk/materials/T552/pages/rich/rp-miners.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-03-18
Channel: nightly
Built: 2022-03-18T00:17:54.702Z
Commit: e5b6e8c8b7198cd016bb0f37a683718f30a3bcac
Is extension: true

**Comment by Herschel** [comment]
Closing in favor of #1905
