### ISSUE TITLE
Error on https://www.throwtheproject.com/play/modern-tactics-3/

### ISSUE THREAD

**Issue by bendangelo** [ruffle-rs/ruffle#6499]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:490:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:490:50
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.6d983a448cfe5f68f798.js:1:7441)
    at std::sync::once::Once::call_once::{{closure}}::hd22b02eba3e9e551 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.3.20/816eb16c9dfe4160d8f1.wasm:wasm-function[1028]:0x2c3c36)
    at std::sync::once::Once::call_inner::h51a70f81ef530383 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.3.20/816eb16c9dfe4160d8f1.wasm:wasm-function[1456]:0x330661)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hdfc5065ab5dd32a2 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.3.20/816eb16c9dfe4160d8f1.wasm:wasm-function[4909]:0x47fddd)
    at std::panicking::rust_panic_with_hook::h12b2f0179ff84c92 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.3.20/816eb16c9dfe4160d8f1.wasm:wasm-function[3233]:0x423d25)
    at core::panicking::panic_fmt::hf0d93ec1ac504cf9 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.3.20/816eb16c9dfe4160d8f1.wasm:wasm-function[5197]:0x48c27c)
    at core::result::unwrap_failed::hd5a60243cf946632 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.3.20/816eb16c9dfe4160d8f1.wasm:wasm-function[4136]:0x467c56)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::h7f67d0024cad63ac (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.3.20/816eb16c9dfe4160d8f1.wasm:wasm-function[738]:0x23e2a9)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::register_shape::h20bb8cd928dd4c8d (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.3.20/816eb16c9dfe4160d8f1.wasm:wasm-function[3240]:0x424b8a)
    at ruffle_core::drawing::Drawing::render::h87e75154f5711cb6 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.3.20/816eb16c9dfe4160d8f1.wasm:wasm-function[663]:0x21a882)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: /assets/flash/modern-tactics-3.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined

# Page Info
Page URL: https://www.throwtheproject.com/play/modern-tactics-3/
SWF URL: https://www.throwtheproject.com/assets/flash/modern-tactics-3.swf

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-03-20
Channel: nightly
Built: 2022-03-20T00:19:20.070Z
Commit: bee70c99de599fa22cdd7b96b475b98c40d8319c
Is extension: false

**Comment by Herschel** [comment]
Closing in favor of #1905
