### ISSUE TITLE
Error on https://www.txori.com/index.php

### ISSUE THREAD

**Issue by tj1221** [ruffle-rs/ruffle#6500]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', render/webgl/src/lib.rs:656:48
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', render/webgl/src/lib.rs:656:48
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (https://www.txori.com/data/system/ruffle/core.ruffle.25973f3ed2b17396c464.js:1:6964)
    at std::sync::once::Once::call_once::{{closure}}::h4dcb78b97de78bcf (wasm://wasm/01867266:wasm-function[1016]:0x2f3fd8)
    at std::sync::once::Once::call_inner::h9279eef47cf85b81 (wasm://wasm/01867266:wasm-function[1152]:0x3276ac)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h7e6cf7c840665392 (wasm://wasm/01867266:wasm-function[4725]:0x4d3db3)
    at std::panicking::rust_panic_with_hook::h47a0e203360b6c10 (wasm://wasm/01867266:wasm-function[3192]:0x47f3dc)
    at core::panicking::panic_fmt::h4ca53049f45e3264 (wasm://wasm/01867266:wasm-function[4996]:0x4df9ff)
    at core::panicking::panic::h35778e3c18266c93 (wasm://wasm/01867266:wasm-function[4722]:0x4d38da)
    at ruffle_render_webgl::WebGlRenderBackend::register_bitmap::h55b28931426de6f2 (wasm://wasm/01867266:wasm-function[1646]:0x39dcf8)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::register_bitmap_raw::h17dd41a7eea7cf46 (wasm://wasm/01867266:wasm-function[3914]:0x4b4e44)
    at ruffle_core::bitmap::bitmap_data::BitmapData::bitmap_handle::h0e7be25bb5a164d2 (wasm://wasm/01867266:wasm-function[1700]:0x3a9f53)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: data/documents/dbz/dbdev.swf?id=1614081248
Param quality: high
Param AllowScriptAccess: sameDomain 
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined

# Page Info
Page URL: https://www.txori.com/index.php?static5/dbdevolution
SWF URL: https://www.txori.com/data/documents/dbz/dbdev.swf?id=1614081248

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-02-03
Channel: nightly
Built: 2022-02-03T00:19:02.660Z
Commit: 0152a6aa344927cc8290b090ac2d3b4db4ecd1fc
Is extension: false

**Comment by kjarosh** [comment]
Should be fixed as of the newest version
