### ISSUE TITLE
Error on http://web.archive.org/web/20110529013748/http://www.youtube.com/watch

### ISSUE THREAD

**Issue by SylviaOctoCat** [ruffle-rs/ruffle#6502]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm2/object.rs:305:48
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm2/object.rs:305:48
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/662.js:1:7439)
    at std::sync::once::Once::call_once::{{closure}}::hd22b02eba3e9e551 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/53089a3a667da0a4f160.wasm:wasm-function[995]:0x2c79e5)
    at std::sync::once::Once::call_inner::h51a70f81ef530383 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/53089a3a667da0a4f160.wasm:wasm-function[1493]:0x358735)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hdfc5065ab5dd32a2 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/53089a3a667da0a4f160.wasm:wasm-function[4916]:0x4a2a03)
    at std::panicking::rust_panic_with_hook::h12b2f0179ff84c92 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/53089a3a667da0a4f160.wasm:wasm-function[3291]:0x449cd8)
    at core::panicking::panic_fmt::hf0d93ec1ac504cf9 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/53089a3a667da0a4f160.wasm:wasm-function[5205]:0x4b0409)
    at core::panicking::panic::h5d6906e2c1099660 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/53089a3a667da0a4f160.wasm:wasm-function[4913]:0x4a252a)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::h0bc1e80a94e87a10 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/53089a3a667da0a4f160.wasm:wasm-function[412]:0x141698)
    at ruffle_core::avm2::activation::Activation::run_actions::h47bb02ed8c539bef (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/53089a3a667da0a4f160.wasm:wasm-function[312]:0xa51c)
    at ruffle_core::avm2::function::Executable::exec::h32e5e87495ef2c82 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/53089a3a667da0a4f160.wasm:wasm-function[726]:0x250669)
```

# Player Info
Allows script access: true

# Page Info
Page URL: http://web.archive.org/web/20110529013748/http://www.youtube.com/watch?v=HXW2vlNu5Rs
SWF URL: http://s.ytimg.com/yt/swfbin/watch_as3-vfl9JbLK7.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-03-20
Channel: nightly
Built: 2022-03-20T00:19:20.070Z
Commit: bee70c99de599fa22cdd7b96b475b98c40d8319c
Is extension: true

**Comment by kjarosh** [comment]
Should be fixed as of today—the related code has been heavily rewritten. (See https://github.com/ruffle-rs/ruffle/pull/7095)
