### ISSUE TITLE
Got this error when trying to run pinata-hunter 1

### ISSUE THREAD

**Issue by Imatschoolandeverythingisblockedplshelp** [ruffle-rs/ruffle#6503]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm2/object.rs:305:48
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm2/object.rs:305:48
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (https://ruffle.rs/demo/966.index.js:1:7160)
    at std::sync::once::Once::call_once::{{closure}}::h5aab3f10449ba9a1 (https://ruffle.rs/demo/fa43b184ed7e76e3318f.wasm:wasm-function[1075]:0x2cef73)
    at std::sync::once::Once::call_inner::h51a70f81ef530383 (https://ruffle.rs/demo/fa43b184ed7e76e3318f.wasm:wasm-function[1513]:0x340ce4)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hb847fc3d85a14a0d (https://ruffle.rs/demo/fa43b184ed7e76e3318f.wasm:wasm-function[5111]:0x49c302)
    at std::panicking::rust_panic_with_hook::h12b2f0179ff84c92 (https://ruffle.rs/demo/fa43b184ed7e76e3318f.wasm:wasm-function[3369]:0x43d371)
    at core::panicking::panic_fmt::hf0d93ec1ac504cf9 (https://ruffle.rs/demo/fa43b184ed7e76e3318f.wasm:wasm-function[5419]:0x4abe1f)
    at core::panicking::panic::h5d6906e2c1099660 (https://ruffle.rs/demo/fa43b184ed7e76e3318f.wasm:wasm-function[5108]:0x49be29)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::hdac6eb59cdbf6345 (https://ruffle.rs/demo/fa43b184ed7e76e3318f.wasm:wasm-function[438]:0x12e533)
    at ruffle_core::avm2::activation::Activation::run_actions::h80754352461de2ed (https://ruffle.rs/demo/fa43b184ed7e76e3318f.wasm:wasm-function[350]:0xaa3f)
    at ruffle_core::avm2::function::Executable::exec::h3d00a9a437ae5cfa (https://ruffle.rs/demo/fa43b184ed7e76e3318f.wasm:wasm-function[744]:0x238c96)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://ruffle.rs/demo/

# Browser Info
Useragent: Mozilla/5.0 (X11; CrOS x86_64 14469.41.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.57 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-03-21
Channel: nightly
Built: 2022-03-21T00:17:51.490Z
Commit: b7a60384cfbd8e81b5d4126ca3c3894a1954bb2e
Is extension: false

**Comment by n0samu** [comment]
This problem seems to be fixed now. Please leave a comment if anything is still broken and I can reopen the issue.
