### ISSUE TITLE
Error on http://lse-sign.bcbl.eu/web-busqueda/

### ISSUE THREAD

**Issue by NicAOB97** [ruffle-rs/ruffle#6603]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:490:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:490:50
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://phblpfibnmcaapffkonhcjhcmamefjgb/dist/966.js:1:7439)
    at std::sync::once::Once::call_once::{{closure}}::h9d9f5504bc648392 (chrome-extension://phblpfibnmcaapffkonhcjhcmamefjgb/dist/66fec4f47bbad2d0f2e5.wasm:wasm-function[1020]:0x2b1ab6)
    at std::sync::once::Once::call_inner::h51a70f81ef530383 (chrome-extension://phblpfibnmcaapffkonhcjhcmamefjgb/dist/66fec4f47bbad2d0f2e5.wasm:wasm-function[1482]:0x3315dd)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h682da277e124560a (chrome-extension://phblpfibnmcaapffkonhcjhcmamefjgb/dist/66fec4f47bbad2d0f2e5.wasm:wasm-function[4965]:0x489736)
    at std::panicking::rust_panic_with_hook::h12b2f0179ff84c92 (chrome-extension://phblpfibnmcaapffkonhcjhcmamefjgb/dist/66fec4f47bbad2d0f2e5.wasm:wasm-function[3330]:0x42ed1c)
    at core::panicking::panic_fmt::hf0d93ec1ac504cf9 (chrome-extension://phblpfibnmcaapffkonhcjhcmamefjgb/dist/66fec4f47bbad2d0f2e5.wasm:wasm-function[5252]:0x495abd)
    at core::result::unwrap_failed::hd5a60243cf946632 (chrome-extension://phblpfibnmcaapffkonhcjhcmamefjgb/dist/66fec4f47bbad2d0f2e5.wasm:wasm-function[4182]:0x471224)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::h4cf11611f41e1086 (chrome-extension://phblpfibnmcaapffkonhcjhcmamefjgb/dist/66fec4f47bbad2d0f2e5.wasm:wasm-function[737]:0x23ef59)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::register_glyph_shape::h66ca1bf2d5c000a0 (chrome-extension://phblpfibnmcaapffkonhcjhcmamefjgb/dist/66fec4f47bbad2d0f2e5.wasm:wasm-function[1733]:0x36951f)
    at ruffle_core::font::Font::from_swf_tag::h970edd90d8df171d (chrome-extension://phblpfibnmcaapffkonhcjhcmamefjgb/dist/66fec4f47bbad2d0f2e5.wasm:wasm-function[775]:0x24dc1d)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: mediaplayer.swf?file=http%3A%2F%2Flse-sign.bcbl.eu%2Fvideos%2F2963.flv
Param src: mediaplayer.swf?file=http%3A%2F%2Flse-sign.bcbl.eu%2Fvideos%2F2963.flv
Param bgColor: #000
Param wmode: direct
Param allowFullScreen: true
Param fullScreenAspectRatio: landscape
Param scale: exactfit
Param autoplay: false
Param flashvars: file=http%3A%2F%2Flse-sign.bcbl.eu%2Fvideos%2F2963.flv&autostart=true
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined

# Page Info
Page URL: http://lse-sign.bcbl.eu/web-busqueda/?page_id=55#
SWF URL: http://lse-sign.bcbl.eu/web-busqueda/mediaplayer.swf?file=http%3A%2F%2Flse-sign.bcbl.eu%2Fvideos%2F2963.flv

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-04-03
Channel: nightly
Built: 2022-04-03T00:18:05.594Z
Commit: 0aff256c1afefcf8be5e18cde5e43222a01c34c5
Is extension: true

**Comment by Herschel** [comment]
Thanks for the reprot. Closing in favor of #1905.
