### ISSUE TITLE
Error on chrome-extension://lcpljnhkbdebenbbehdnbmhhjhmnlieh/player.html

### ISSUE THREAD

**Issue by xPATRICKx01** [ruffle-rs/ruffle#6618]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm2/object.rs:305:48
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm2/object.rs:305:48
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://lcpljnhkbdebenbbehdnbmhhjhmnlieh/dist/662.js:1:7439)
    at std::sync::once::Once::call_once::{{closure}}::h9d9f5504bc648392 (chrome-extension://lcpljnhkbdebenbbehdnbmhhjhmnlieh/dist/f83ee02a4cb39cccd9f6.wasm:wasm-function[982]:0x2bc313)
    at std::sync::once::Once::call_inner::h51a70f81ef530383 (chrome-extension://lcpljnhkbdebenbbehdnbmhhjhmnlieh/dist/f83ee02a4cb39cccd9f6.wasm:wasm-function[1508]:0x3527e9)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h682da277e124560a (chrome-extension://lcpljnhkbdebenbbehdnbmhhjhmnlieh/dist/f83ee02a4cb39cccd9f6.wasm:wasm-function[4969]:0x4a6645)
    at std::panicking::rust_panic_with_hook::h12b2f0179ff84c92 (chrome-extension://lcpljnhkbdebenbbehdnbmhhjhmnlieh/dist/f83ee02a4cb39cccd9f6.wasm:wasm-function[3341]:0x44b645)
    at core::panicking::panic_fmt::hf0d93ec1ac504cf9 (chrome-extension://lcpljnhkbdebenbbehdnbmhhjhmnlieh/dist/f83ee02a4cb39cccd9f6.wasm:wasm-function[5256]:0x4b3eec)
    at core::panicking::panic::h5d6906e2c1099660 (chrome-extension://lcpljnhkbdebenbbehdnbmhhjhmnlieh/dist/f83ee02a4cb39cccd9f6.wasm:wasm-function[4966]:0x4a616c)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::h09739f46b24c98e8 (chrome-extension://lcpljnhkbdebenbbehdnbmhhjhmnlieh/dist/f83ee02a4cb39cccd9f6.wasm:wasm-function[336]:0x9fa9e)
    at ruffle_core::avm2::activation::Activation::run_actions::h98c35cca155c2e71 (chrome-extension://lcpljnhkbdebenbbehdnbmhhjhmnlieh/dist/f83ee02a4cb39cccd9f6.wasm:wasm-function[313]:0x236ca)
    at ruffle_core::avm2::script::Script::globals::h5f1ce7582dec1012 (chrome-extension://lcpljnhkbdebenbbehdnbmhhjhmnlieh/dist/f83ee02a4cb39cccd9f6.wasm:wasm-function[1289]:0x31ad8e)
```

# Player Info
Allows script access: false

# Page Info
Page URL: chrome-extension://lcpljnhkbdebenbbehdnbmhhjhmnlieh/player.html?url=http%3A%2F%2Fdkesp-res-salagame-com.akamaized.net%2Fgame.swf
SWF URL: http://dkesp-res-salagame-com.akamaized.net/game.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.84 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-04-04
Channel: nightly
Built: 2022-04-04T00:16:46.763Z
Commit: 6ec3049e024a2c564b265862c31c7db8a789ff0f
Is extension: true

**Comment by kjarosh** [comment]
Should be fixed as of today—the related code has been heavily rewritten. (See https://github.com/ruffle-rs/ruffle/pull/7095)
