### ISSUE TITLE
Error on https://armorgames.com/play/777/four-second-firestorm

### ISSUE THREAD

**Issue by Rulis88** [ruffle-rs/ruffle#6643]
# Error Info
Error name: Error
Error message: panicked at 'attempt to calculate the remainder with a divisor of zero', core/src/display_object/video.rs:176:13
Error stack:
```
Error: panicked at 'attempt to calculate the remainder with a divisor of zero', core/src/display_object/video.rs:176:13
    at u.wbg.__wbg_new_df6e6ab7a65c4c4d (https://agi.armorgames.com/ruffle/ruffle.js:1:7173)
    at std::sync::once::Once::call_once::{{closure}}::ha2a6e9c1727c0056 (https://agi.armorgames.com/ruffle/2ac0e03f886c1de9a1d4.wasm:wasm-function[998]:0x2e4725)
    at std::sync::once::Once::call_inner::h02a6489b0ecfb269 (https://agi.armorgames.com/ruffle/2ac0e03f886c1de9a1d4.wasm:wasm-function[1329]:0x354a63)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h5c1b8acd952e19de (https://agi.armorgames.com/ruffle/2ac0e03f886c1de9a1d4.wasm:wasm-function[4703]:0x4f1c42)
    at std::panicking::rust_panic_with_hook::h364974e717ed59ec (https://agi.armorgames.com/ruffle/2ac0e03f886c1de9a1d4.wasm:wasm-function[3305]:0x4a0f2b)
    at rust_begin_unwind (https://agi.armorgames.com/ruffle/2ac0e03f886c1de9a1d4.wasm:wasm-function[4766]:0x4f45d8)
    at core::panicking::panic_fmt::hf69c8b08bc9d2ee5 (https://agi.armorgames.com/ruffle/2ac0e03f886c1de9a1d4.wasm:wasm-function[4973]:0x4ff15a)
    at core::panicking::panic::hceae0c79b0247f98 (https://agi.armorgames.com/ruffle/2ac0e03f886c1de9a1d4.wasm:wasm-function[4699]:0x4f1473)
    at ruffle_core::display_object::video::Video::seek::h2a325afbaf9aa5cd (https://agi.armorgames.com/ruffle/2ac0e03f886c1de9a1d4.wasm:wasm-function[761]:0x267490)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::ha4bd6f8efe676404 (https://agi.armorgames.com/ruffle/2ac0e03f886c1de9a1d4.wasm:wasm-function[1738]:0x3c650a)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://armorgames.com/play/777/four-second-firestorm
SWF URL: https://cache.armorgames.com/files/games/four-second-firestor-777.swf?v=1373587520

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.84 Safari/537.36 OPR/85.0.4341.47
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-11-21
Channel: nightly
Built: 2021-11-21T00:13:29.381Z
Commit: a305b80789234133cd666e1c9f1abcde247818cb
Is extension: false

**Comment by Toad06** [comment]
I think that this issue is already fixed on our end (cc. #6607), however the build that Armorgames is using is really outdated. You should try to get in touch with them and ask to update their build of Ruffle.

**Comment by Rulis88** [comment]
fuck off, tranny.
    On Thursday, April 7, 2022, 09:18:56 PM GMT+3, Toad06 ***@***.***> wrote:  
 
 


I think that this issue is already fixed on our end (cc. #6607), however the build that Armorgames is using is really outdated. You should try to get in touch with them and ask to update their build of Ruffle.
