### ISSUE TITLE
Error on https://ruffle.rs/demo/

### ISSUE THREAD

**Issue by Games-From-Flash** [ruffle-rs/ruffle#6692]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/library.rs:329:26
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/library.rs:329:26
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (https://ruffle.rs/demo/966.index.js:1:7197)
    at std::sync::once::Once::call_once::{{closure}}::he6e984b98bfd4469 (https://ruffle.rs/demo/684c378ac33688c7abc2.wasm:wasm-function[1060]:0x2b1ec6)
    at std::sync::once::Once::call_inner::h07d0245bef259c27 (https://ruffle.rs/demo/684c378ac33688c7abc2.wasm:wasm-function[1504]:0x32b01a)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::ha12d7190a4c11fdc (https://ruffle.rs/demo/684c378ac33688c7abc2.wasm:wasm-function[5082]:0x48fa42)
    at std::panicking::rust_panic_with_hook::h623ac32ff431b114 (https://ruffle.rs/demo/684c378ac33688c7abc2.wasm:wasm-function[3347]:0x42c7f8)
    at core::panicking::panic_fmt::h5118e89563022e7e (https://ruffle.rs/demo/684c378ac33688c7abc2.wasm:wasm-function[5171]:0x496df3)
    at core::panicking::panic::he88f1b1582b09c8c (https://ruffle.rs/demo/684c378ac33688c7abc2.wasm:wasm-function[5080]:0x48f5d5)
    at ruffle_core::avm2::globals::flash::display::loaderinfo::application_domain::hdb54f8e86a7e24c9 (https://ruffle.rs/demo/684c378ac33688c7abc2.wasm:wasm-function[2377]:0x3c41f4)
    at ruffle_core::avm2::function::Executable::exec::h0911552b73e4a89d (https://ruffle.rs/demo/684c378ac33688c7abc2.wasm:wasm-function[843]:0x24a432)
    at ruffle_core::avm2::object::TObject::call_method::h2debab9b13265cdd (https://ruffle.rs/demo/684c378ac33688c7abc2.wasm:wasm-function[1208]:0x2daa61)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://ruffle.rs/demo/

# Browser Info
Useragent: Mozilla/5.0 (X11; CrOS x86_64 14268.67.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.111 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-04-12
Channel: nightly
Built: 2022-04-12T00:15:51.044Z
Commit: 24f00238a77021bea392e0a91c2125ff6e5d7430
Is extension: false

**Comment by n0samu** [comment]
Hi, what SWF were you trying to play when the error occurred?

**Comment by n0samu** [comment]
Old issue with no information provided, closing
