### ISSUE TITLE
Error on http://www.mygamesworld.com/game/7825/The_Fog_Fall_2.html

### ISSUE THREAD

**Issue by cculligan1972** [ruffle-rs/ruffle#6779]
# Error Info
Error name: Error
Error message: panicked at 'index out of bounds: the len is 260 but the index is 260', core/src/backend/render.rs:477:33
Error stack:
```
Error: panicked at 'index out of bounds: the len is 260 but the index is 260', core/src/backend/render.rs:477:33
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (http://www.mygamesworld.com/jscripts/core.ruffle.9257751f207a7db4a8f4.js:1:7572)
    at std::sync::once::Once::call_once::{{closure}}::h04c6018a30aae0b2 (http://www.mygamesworld.com/jscripts/37414a2c1295e4921309.wasm:wasm-function[1023]:0x2c1985)
    at std::sync::once::Once::call_inner::h51a70f81ef530383 (http://www.mygamesworld.com/jscripts/37414a2c1295e4921309.wasm:wasm-function[1459]:0x32fd41)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h629785d4908f37da (http://www.mygamesworld.com/jscripts/37414a2c1295e4921309.wasm:wasm-function[4922]:0x482981)
    at std::panicking::rust_panic_with_hook::h12b2f0179ff84c92 (http://www.mygamesworld.com/jscripts/37414a2c1295e4921309.wasm:wasm-function[3239]:0x4256ab)
    at core::panicking::panic_fmt::hf0d93ec1ac504cf9 (http://www.mygamesworld.com/jscripts/37414a2c1295e4921309.wasm:wasm-function[5209]:0x48eaab)
    at core::panicking::panic_bounds_check::hebe834b116d5d452 (http://www.mygamesworld.com/jscripts/37414a2c1295e4921309.wasm:wasm-function[4372]:0x4737f9)
    at ruffle_core::backend::render::decode_define_bits_lossless::h97375947af071113 (http://www.mygamesworld.com/jscripts/37414a2c1295e4921309.wasm:wasm-function[405]:0x13847a)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::register_bitmap_png::h72a84ebb2fdcb59a (http://www.mygamesworld.com/jscripts/37414a2c1295e4921309.wasm:wasm-function[3976]:0x461393)
    at ruffle_core::display_object::movie_clip::MovieClipData::define_bits_lossless::he8f7d01c8520d270 (http://www.mygamesworld.com/jscripts/37414a2c1295e4921309.wasm:wasm-function[1297]:0x306900)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: http://www.mygamesworld.com/files/file/fogfall2v32mrX.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined

# Page Info
Page URL: http://www.mygamesworld.com/game/7825/The_Fog_Fall_2.html
SWF URL: http://www.mygamesworld.com/files/file/fogfall2v32mrX.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36
OS: Linux armv8l

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-03-04
Channel: nightly
Built: 2022-03-04T00:15:35.142Z
Commit: 31446785f9804fcd8090da4670a9f4038a558e6e
Is extension: false

**Comment by Sonikkustar** [comment]
I don't know what caused this error, but the game appears to work fine now. The only issue I see is the score counter continuously going up every frame, but that might be related to another issue and I don't know if that's how scoring works when this game is played on base Flash.

![Image](https://github.com/user-attachments/assets/aae41eae-ce2f-4134-9b21-56daf7dcb77f)
