### ISSUE TITLE
\Error on https://www.hockeygames.org/bob-and-bobek-shooting-on-goal/

### ISSUE THREAD

**Issue by fleuryfan292929** [ruffle-rs/ruffle#6807]
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', core/src/avm2/object/script_object.rs:69:16
Error stack:
```
Error: panicked at 'already borrowed: BorrowMutError', core/src/avm2/object/script_object.rs:69:16
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (https://www.hockeygames.org/ruffle/core.ruffle.08124f6dd5c7e72ca855.js:1:6964)
    at std::sync::once::Once::call_once::{{closure}}::h4dcb78b97de78bcf (https://www.hockeygames.org/ruffle/f91bedccc781eba86e58.wasm:wasm-function[1019]:0x2f8ef2)
    at std::sync::once::Once::call_inner::h9279eef47cf85b81 (https://www.hockeygames.org/ruffle/f91bedccc781eba86e58.wasm:wasm-function[1157]:0x32aaba)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h7e6cf7c840665392 (https://www.hockeygames.org/ruffle/f91bedccc781eba86e58.wasm:wasm-function[4721]:0x4d76d9)
    at std::panicking::rust_panic_with_hook::h47a0e203360b6c10 (https://www.hockeygames.org/ruffle/f91bedccc781eba86e58.wasm:wasm-function[3188]:0x482726)
    at core::panicking::panic_fmt::h4ca53049f45e3264 (https://www.hockeygames.org/ruffle/f91bedccc781eba86e58.wasm:wasm-function[4992]:0x4e3346)
    at core::result::unwrap_failed::h6d050dbd00b66340 (https://www.hockeygames.org/ruffle/f91bedccc781eba86e58.wasm:wasm-function[4020]:0x4c018b)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::init_property::h7c69b9a6a6c622fd (https://www.hockeygames.org/ruffle/f91bedccc781eba86e58.wasm:wasm-function[444]:0x18a935)
    at ruffle_core::avm2::activation::Activation::do_next_opcode::hfeb3a14a7657719f (https://www.hockeygames.org/ruffle/f91bedccc781eba86e58.wasm:wasm-function[312]:0x268eb)
    at ruffle_core::avm2::activation::Activation::run_actions::h6d51e9527e6f32fc (https://www.hockeygames.org/ruffle/f91bedccc781eba86e58.wasm:wasm-function[2894]:0x468802)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://www.hockeygames.org/bob-and-bobek-shooting-on-goal/
SWF URL: https://hockeygames.org/wp-content/games/bob-and-bobek-shooting-on-goal.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; CrOS x86_64 14526.89.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.133 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-01-26
Channel: nightly
Built: 2022-01-26T00:18:09.413Z
Commit: d5986a72947f5552b29805e3971ce58939fdd1a2
Is extension: false

**Comment by parkerlreed** [comment]
Keep in mind this is AVM2 so support is a ways off either way.
