### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by ThunderStarDev** [ruffle-rs/ruffle#6841]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', render/webgl/src/lib.rs:658:48
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', render/webgl/src/lib.rs:658:48
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.f6cd19fddd4f688cfec1.js:1:7708)
    at std::sync::once::Once::call_once::{{closure}}::h802bfeb6f8bb5638 (https://uploads.ungrounded.net/ruffle_wrapper/lib/bc8758488c7afe706462.wasm:wasm-function[1013]:0x2ab43f)
    at std::sync::once::Once::call_inner::h07d0245bef259c27 (https://uploads.ungrounded.net/ruffle_wrapper/lib/bc8758488c7afe706462.wasm:wasm-function[1443]:0x31e454)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h9ecdeaaea35085f8 (https://uploads.ungrounded.net/ruffle_wrapper/lib/bc8758488c7afe706462.wasm:wasm-function[4920]:0x4783ed)
    at std::panicking::rust_panic_with_hook::h623ac32ff431b114 (https://uploads.ungrounded.net/ruffle_wrapper/lib/bc8758488c7afe706462.wasm:wasm-function[3240]:0x41b033)
    at core::panicking::panic_fmt::h5118e89563022e7e (https://uploads.ungrounded.net/ruffle_wrapper/lib/bc8758488c7afe706462.wasm:wasm-function[5002]:0x47c2a0)
    at core::panicking::panic::he88f1b1582b09c8c (https://uploads.ungrounded.net/ruffle_wrapper/lib/bc8758488c7afe706462.wasm:wasm-function[4918]:0x477f80)
    at ruffle_render_webgl::WebGlRenderBackend::register_bitmap::h8b98aa9c3028b91d (https://uploads.ungrounded.net/ruffle_wrapper/lib/bc8758488c7afe706462.wasm:wasm-function[1710]:0x35c2d0)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::register_bitmap_raw::h3359e08104d8f047 (https://uploads.ungrounded.net/ruffle_wrapper/lib/bc8758488c7afe706462.wasm:wasm-function[4029]:0x45a68a)
    at ruffle_core::bitmap::bitmap_data::BitmapData::bitmap_handle::h760de3d51712f279 (https://uploads.ungrounded.net/ruffle_wrapper/lib/bc8758488c7afe706462.wasm:wasm-function[1621]:0x349123)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.66&useloader=1&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1650293381%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F592000%2F592473_MadnessGame_ULTIMATE.swf%3F1507662264%22%2C%22vars%22%3A%7B%22ngio_session_id%22%3A%2204148877.593ca33791e626287943adc026d36bdfe49b59bcfc1aa2%22%2C%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%22626e19733bc53%22%2C%22NewgroundsAPI_SessionID%22%3A%22R0nwEOXePpj9GZgFDwh46dd334fe18f8cc353305b584af0f1a69a3a54403RUMQ%22%2C%22NewgroundsAPI_UserName%22%3A%22MertoneMarden%22%2C%22NewgroundsAPI_UserID%22%3A9389900%2C%22ng_username%22%3A%22MertoneMarden%22%7D%2C%22width%22%3A850%2C%22height%22%3A530%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F592000%2Fflash_592473_card.png%3Ff1608170534%22%7D
SWF URL: https://uploads.ungrounded.net/592000/592473_MadnessGame_ULTIMATE.swf?1507662264

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-04-18
Channel: nightly
Built: 2022-04-18T00:19:04.299Z
Commit: 3305ac69c456fe62c08d244b875775a5c9b7479e
Is extension: false

**Comment by kjarosh** [comment]
Should be fixed as of the newest version
