### ISSUE TITLE
Error on https://games.crazygames.com/en_US/madness-project-nexus/index.html

### ISSUE THREAD

**Issue by DontAsKLm** [ruffle-rs/ruffle#6842]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: JsValue(InvalidStateError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
Error: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
    at https://files.crazygames.com/gameframe/ruffle/2022-02-19/core.ruffle.3c40dc0bd68b80f95b7b.js:1:28384
    at I (https://files.crazygames.com/gameframe/ruffle/2022-02-19/core.ruffle.3c40dc0bd68b80f95b7b.js:1:4170)
    at c.wbg.__wbg_drawImage_9492b361f8b31282 (https://files.crazygames.com/gameframe/ruffle/2022-02-19/core.ruffle.3c40dc0bd68b80f95b7b.js:1:28358)
    at web_sys::features::gen_CanvasRenderingContext2d::CanvasRenderingContext2d::draw_image_with_html_canvas_element::hf0104bdada0c443a (https://files.crazygames.com/gameframe/ruffle/2022-02-19/18f70695ff32c2ad02b2.wasm:wasm-function[4623]:0x4d05f4)
    at <ruffle_render_canvas::WebCanvasRenderBackend as ruffle_core::backend::render::RenderBackend>::pop_mask::h5d88226b390b2da2 (https://files.crazygames.com/gameframe/ruffle/2022-02-19/18f70695ff32c2ad02b2.wasm:wasm-function[992]:0x2ed6ff)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render_self::h94770404df29678f (https://files.crazygames.com/gameframe/ruffle/2022-02-19/18f70695ff32c2ad02b2.wasm:wasm-function[3166]:0x47bc3f)
    at ruffle_core::display_object::render_base::h0bdf04f938a85e38 (https://files.crazygames.com/gameframe/ruffle/2022-02-19/18f70695ff32c2ad02b2.wasm:wasm-function[1580]:0x391339)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render::hfeb31beb7aac1fe2 (https://files.crazygames.com/gameframe/ruffle/2022-02-19/18f70695ff32c2ad02b2.wasm:wasm-function[3754]:0x4ab08d)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render_self::h94770404df29678f (https://files.crazygames.com/gameframe/ruffle/2022-02-19/18f70695ff32c2ad02b2.wasm:wasm-function[3166]:0x47bd24)
    at ruffle_core::display_object::render_base::h0bdf04f938a85e38 (https://files.crazygames.com/gameframe/ruffle/2022-02-19/18f70695ff32c2ad02b2.wasm:wasm-function[1580]:0x391339)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render::hfeb31beb7aac1fe2 (https://files.crazygames.com/gameframe/ruffle/2022-02-19/18f70695ff32c2ad02b2.wasm:wasm-function[3754]:0x4ab08d)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render_self::h94770404df29678f (https://files.crazygames.com/gameframe/ruffle/2022-02-19/18f70695ff32c2ad02b2.wasm:wasm-function[3166]:0x47bd24)
    at ruffle_core::display_object::render_base::h0bdf04f938a85e38 (https://files.crazygames.com/gameframe/ruffle/2022-02-19/18f70695ff32c2ad02b2.wasm:wasm-function[1580]:0x391339)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render::hfeb31beb7aac1fe2 (https://files.crazygames.com/gameframe/ruffle/2022-02-19/18f70695ff32c2ad02b2.wasm:wasm-function[3754]:0x4ab08d)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render_self::h94770404df29678f (https://files.crazygames.com/gameframe/ruffle/2022-02-19/18f70695ff32c2ad02b2.wasm:wasm-function[3166]:0x479b5b)
    at ruffle_core::display_object::render_base::h0bdf04f938a85e38 (https://files.crazygames.com/gameframe/ruffle/2022-02-19/18f70695ff32c2ad02b2.wasm:wasm-function[1580]:0x391339)
    at <ruffle_core::display_object::stage::Stage as ruffle_core::display_object::TDisplayObject>::render::hf170f8f6eb21bada (https://files.crazygames.com/gameframe/ruffle/2022-02-19/18f70695ff32c2ad02b2.wasm:wasm-function[1301]:0x350f54)
    at ruffle_web::Ruffle::tick::he9f9c79a3f561482 (https://files.crazygames.com/gameframe/ruffle/2022-02-19/18f70695ff32c2ad02b2.wasm:wasm-function[612]:0x22056d)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h466717537c66ebc6 (https://files.crazygames.com/gameframe/ruffle/2022-02-19/18f70695ff32c2ad02b2.wasm:wasm-function[5520]:0x4eb300)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h827399ce0eead02e (https://files.crazygames.com/gameframe/ruffle/2022-02-19/18f70695ff32c2ad02b2.wasm:wasm-function[5097]:0x4e0992)
    at R (https://files.crazygames.com/gameframe/ruffle/2022-02-19/core.ruffle.3c40dc0bd68b80f95b7b.js:1:2955)
    at c (https://files.crazygames.com/gameframe/ruffle/2022-02-19/core.ruffle.3c40dc0bd68b80f95b7b.js:1:2521)
    at r (https://gameframe.crazygames.com/crazygames-gameframe-v1.bundle.js:2:337534))', render/canvas/src/lib.rs:824:14

# Player Info
Allows script access: false

# Page Info
Page URL: https://games.crazygames.com/en_US/madness-project-nexus/index.html

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-02-19
Channel: nightly
Built: 2022-02-19T00:15:44.456Z
Commit: 2ca62ecf4bac5696d2da084b1f5d5c6ba2a4e0f7
Is extension: false

**Comment by DontAsKLm** [comment]
pls help

**Comment by relrelb** [comment]
Fixed by #9358.
