### ISSUE TITLE
Error on https://kdata1.com/2016/06/bleach-vs-naruto-26/

### ISSUE THREAD

**Issue by Anime1619** [ruffle-rs/ruffle#6908]
# Error Info
Error name: Error
Error message: panicked at 'assertion failed: min <= max', /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/cmp.rs:817:9
Error stack:
```
Error: panicked at 'assertion failed: min <= max', /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/cmp.rs:817:9
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (https://kdata1.com/RS/asset/core.ruffle.cfafeead7fa4cdb619a5.js:1:7572)
    at std::sync::once::Once::call_once::{{closure}}::h04c6018a30aae0b2 (wasm://wasm/017752a6:wasm-function[1019]:0x2c1212)
    at std::sync::once::Once::call_inner::h51a70f81ef530383 (wasm://wasm/017752a6:wasm-function[1458]:0x32fa13)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h629785d4908f37da (wasm://wasm/017752a6:wasm-function[4925]:0x48459f)
    at std::panicking::rust_panic_with_hook::h12b2f0179ff84c92 (wasm://wasm/017752a6:wasm-function[3240]:0x426969)
    at core::panicking::panic_fmt::hf0d93ec1ac504cf9 (wasm://wasm/017752a6:wasm-function[5213]:0x4906ea)
    at core::panicking::panic::h5d6906e2c1099660 (wasm://wasm/017752a6:wasm-function[4922]:0x4840c6)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::set_viewport_dimensions::hdb7e649abcb5401d (wasm://wasm/017752a6:wasm-function[630]:0x206b43)
    at ruffle_web::Ruffle::tick::h2b7345cbc1c3bf01 (wasm://wasm/017752a6:wasm-function[552]:0x1c2749)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h2876aacc6fbcb275 (wasm://wasm/017752a6:wasm-function[5794]:0x49e66d)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: game.swf
Param movie: game.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined

# Page Info
Page URL: https://kdata1.com/2016/06/bleach-vs-naruto-26/?1
SWF URL: https://kdata1.com/2016/06/bleach-vs-naruto-26/game.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36 Edg/99.0.1150.67
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-03-02
Channel: nightly
Built: 2022-03-02T00:16:18.285Z
Commit: cbbdb7baa94e0996fd8696976a2fa3e1151c16f9
Is extension: false

**Comment by Herschel** [comment]
Fixed in https://github.com/ruffle-rs/ruffle/commit/e45810f585b634b6f1e374e406ccecde1c16ead6, website needs to update Ruffle.
