### ISSUE TITLE
Error on https://unblockeds-games.com/zombocalypse-2

### ISSUE THREAD

**Issue by kjdfdhsaf** [ruffle-rs/ruffle#6940]
# Error Info
Error name: Error
Error message: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:568:14
Error stack:
```
Error: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:568:14
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:1:7485)
    at std::sync::once::Once::call_once::{{closure}}::hc3464e04dbb9beda (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/d61290f89b852d670c31.wasm:wasm-function[978]:0x28eff0)
    at std::sync::once::Once::call_inner::h07d0245bef259c27 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/d61290f89b852d670c31.wasm:wasm-function[1436]:0x30b089)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h44f701de063d4daa (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/d61290f89b852d670c31.wasm:wasm-function[4922]:0x462acf)
    at std::panicking::rust_panic_with_hook::h623ac32ff431b114 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/d61290f89b852d670c31.wasm:wasm-function[3260]:0x40832a)
    at core::panicking::panic_fmt::h5118e89563022e7e (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/d61290f89b852d670c31.wasm:wasm-function[5003]:0x466753)
    at core::option::expect_failed::h52436cb58dfe4ec3 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/d61290f89b852d670c31.wasm:wasm-function[5626]:0x474032)
    at ruffle_core::display_object::stage::Stage::root_clip::hd4ea96e47c77684d (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/d61290f89b852d670c31.wasm:wasm-function[3574]:0x41e855)
    at ruffle_web::Ruffle::tick::hc25780ec640c7235 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/d61290f89b852d670c31.wasm:wasm-function[533]:0x1a15fe)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::ha67e2dc288fd70c7 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/d61290f89b852d670c31.wasm:wasm-function[5802]:0x47c704)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: /games/zombocalypse2.swf
Param wmode: direct
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined

# Page Info
Page URL: https://unblockeds-games.com/zombocalypse-2
SWF URL: https://unblockeds-games.com/games/zombocalypse2.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; CrOS x86_64 14526.89.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.133 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-05-10
Channel: nightly
Built: 2022-05-10T00:13:56.424Z
Commit: 4f05d1852dd6c8e654aead0dcff7fefbc07264c9
Is extension: true

**Comment by Lord-McSweeney** [comment]
With #10026:
```
WARN ruffle_core::stub: Encountered stub: AVM2 flash.display3D.Context3D.setDepthTest()
WARN ruffle_core::stub: Encountered stub: AVM2 flash.display3D.Context3D.setRenderToBackBuffer()
WARN ruffle_render_wgpu::context3d: configureBackBuffer: anti_alias=0 is not yet implemented
WARN ruffle_render_wgpu::context3d: configureBackBuffer: depth_and_stencil is not yet implemented
WARN ruffle_render_wgpu::context3d: Context3D::present: Clear command with mask 7fffffff not implemeneted
```
