### ISSUE TITLE
Error on chrome-extension://hbpljbemllijocbdjoaejleaakcblalc/player.html

### ISSUE THREAD

**Issue by natalie5985** [ruffle-rs/ruffle#6958]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm2/object.rs:308:48
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm2/object.rs:308:48
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://hbpljbemllijocbdjoaejleaakcblalc/dist/966.js:1:7485)
    at std::sync::once::Once::call_once::{{closure}}::hc3464e04dbb9beda (chrome-extension://hbpljbemllijocbdjoaejleaakcblalc/dist/664f962a4ce56c14c040.wasm:wasm-function[979]:0x2904d6)
    at std::sync::once::Once::call_inner::h07d0245bef259c27 (chrome-extension://hbpljbemllijocbdjoaejleaakcblalc/dist/664f962a4ce56c14c040.wasm:wasm-function[1430]:0x30bce1)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h44f701de063d4daa (chrome-extension://hbpljbemllijocbdjoaejleaakcblalc/dist/664f962a4ce56c14c040.wasm:wasm-function[4913]:0x462f3d)
    at std::panicking::rust_panic_with_hook::h623ac32ff431b114 (chrome-extension://hbpljbemllijocbdjoaejleaakcblalc/dist/664f962a4ce56c14c040.wasm:wasm-function[3250]:0x408abe)
    at core::panicking::panic_fmt::h5118e89563022e7e (chrome-extension://hbpljbemllijocbdjoaejleaakcblalc/dist/664f962a4ce56c14c040.wasm:wasm-function[4994]:0x466b9b)
    at core::panicking::panic::he88f1b1582b09c8c (chrome-extension://hbpljbemllijocbdjoaejleaakcblalc/dist/664f962a4ce56c14c040.wasm:wasm-function[4911]:0x462ad6)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::h831a7d5f2dc1a8ab (chrome-extension://hbpljbemllijocbdjoaejleaakcblalc/dist/664f962a4ce56c14c040.wasm:wasm-function[326]:0x7611a)
    at ruffle_core::avm2::activation::Activation::run_actions::had6b5f0b2ab1010a (chrome-extension://hbpljbemllijocbdjoaejleaakcblalc/dist/664f962a4ce56c14c040.wasm:wasm-function[313]:0x213dc)
    at ruffle_core::avm2::script::Script::globals::h2250d1e072a604e5 (chrome-extension://hbpljbemllijocbdjoaejleaakcblalc/dist/664f962a4ce56c14c040.wasm:wasm-function[1249]:0x2e4679)
```

# Player Info
Allows script access: false

# Page Info
Page URL: chrome-extension://hbpljbemllijocbdjoaejleaakcblalc/player.html?url=https%3A%2F%2Fxp-scg-drblood.101xp.com%2Fgame.swf
SWF URL: https://xp-scg-drblood.101xp.com/game.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36 Edg/101.0.1210.39
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-05-12
Channel: nightly
Built: 2022-05-12T00:13:39.018Z
Commit: 938d80146c7c33c4851b64cf819920e8f8a4076b
Is extension: true

**Comment by kjarosh** [comment]
Should be fixed as of today—the related code has been heavily rewritten.
