### ISSUE TITLE
Error on https://www.juegosarea.com/dragonball-z-creator.html

### ISSUE THREAD

**Issue by juiloallendes** [ruffle-rs/ruffle#6964]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: JsValue(InvalidStateError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
Error: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
    at https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.e8e4f916dcc9dd4b7920.js:1:28694
    at L (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.e8e4f916dcc9dd4b7920.js:1:3908)
    at c.wbg.__wbg_drawImage_5d4f6b1d51d3b118 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.e8e4f916dcc9dd4b7920.js:1:28668)
    at web_sys::features::gen_CanvasRenderingContext2d::CanvasRenderingContext2d::draw_image_with_html_canvas_element::hc8276166311b8747 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.5.13/2cdb5311433b0c4f772f.wasm:wasm-function[4837]:0x460f4d)
    at <ruffle_render_canvas::WebCanvasRenderBackend as ruffle_core::backend::render::RenderBackend>::pop_mask::h4de3fbd914f32e5f (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.5.13/2cdb5311433b0c4f772f.wasm:wasm-function[880]:0x26d0db)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render_self::h338f41ca8317b3f6 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.5.13/2cdb5311433b0c4f772f.wasm:wasm-function[2521]:0x3c3c0c)
    at ruffle_core::display_object::render_base::hf7441ed05a29f020 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.5.13/2cdb5311433b0c4f772f.wasm:wasm-function[1499]:0x31dc84)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render::hc1643955a55fbe59 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.5.13/2cdb5311433b0c4f772f.wasm:wasm-function[3824]:0x43b241)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render_self::h338f41ca8317b3f6 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.5.13/2cdb5311433b0c4f772f.wasm:wasm-function[2521]:0x3c437f)
    at ruffle_core::display_object::render_base::hf7441ed05a29f020 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.5.13/2cdb5311433b0c4f772f.wasm:wasm-function[1499]:0x31dc84))', render/canvas/src/lib.rs:832:14

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.juegosarea.com/dragonball-z-creator.html
SWF URL: https://cdn.juegosarea.com/files/games/dr/ag/dragonball-z-creator.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-05-13
Channel: nightly
Built: 2022-05-13T00:14:12.907Z
Commit: edad1569fbb235527ed3241b51e28fa323eca637
Is extension: false

**Comment by relrelb** [comment]
Fixed by #9358.
