### ISSUE TITLE
Error on https://www.superhry.cz/hra/13785-angry-birds-hd

### ISSUE THREAD

**Issue by tynuska12** [ruffle-rs/ruffle#6967]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm2/object.rs:305:48
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm2/object.rs:305:48
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (https://www.superhry.cz/js/ruffle_20220104/ruffle.js:1:6703)
    at std::sync::once::Once::call_once::{{closure}}::hd1b4f64c6a058fdf (https://www.superhry.cz/js/ruffle_20220104/cd7e6f7aaff275ad7eb9.wasm:wasm-function[983]:0x2f9eff)
    at std::sync::once::Once::call_inner::hf9144d66ddc67dec (https://www.superhry.cz/js/ruffle_20220104/cd7e6f7aaff275ad7eb9.wasm:wasm-function[1181]:0x33f23b)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h7c91d9e8737f5a50 (https://www.superhry.cz/js/ruffle_20220104/cd7e6f7aaff275ad7eb9.wasm:wasm-function[4674]:0x5052ae)
    at std::panicking::rust_panic_with_hook::h606d7c7f7a423b98 (https://www.superhry.cz/js/ruffle_20220104/cd7e6f7aaff275ad7eb9.wasm:wasm-function[3234]:0x4b0abb)
    at rust_begin_unwind (https://www.superhry.cz/js/ruffle_20220104/cd7e6f7aaff275ad7eb9.wasm:wasm-function[4737]:0x5067d8)
    at core::panicking::panic_fmt::h6314b5c91abe7349 (https://www.superhry.cz/js/ruffle_20220104/cd7e6f7aaff275ad7eb9.wasm:wasm-function[4949]:0x5116c1)
    at core::panicking::panic::hec1fc057bd0baf0b (https://www.superhry.cz/js/ruffle_20220104/cd7e6f7aaff275ad7eb9.wasm:wasm-function[4671]:0x504b14)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::hefeca2a2afbb57c9 (https://www.superhry.cz/js/ruffle_20220104/cd7e6f7aaff275ad7eb9.wasm:wasm-function[2153]:0x41892f)
    at ruffle_core::avm2::activation::Activation::do_next_opcode::ha6c3586a7be8611a (https://www.superhry.cz/js/ruffle_20220104/cd7e6f7aaff275ad7eb9.wasm:wasm-function[313]:0x4b00f)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.superhry.cz/hra/13785-angry-birds-hd
SWF URL: https://www.superhry.cz/cnt_img/013/13785.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36 Edg/100.0.1185.50
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-01-04
Channel: nightly
Built: 2022-01-04T00:13:48.083Z
Commit: a9e86a73cf17845356a3bd38fe42c50e584a693c
Is extension: false

**Comment by kjarosh** [comment]
Should be fixed as of today—the related code has been heavily rewritten.
