### ISSUE TITLE
Error on https://games.yo-yoo.co.il/games_play.php

### ISSUE THREAD

**Issue by 777hhh** [ruffle-rs/ruffle#6968]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/html/text_format.rs:756:54
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/html/text_format.rs:756:54
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (https://www.yo-yoo.co.il/101/ruffle/ruffle.js:1:7158)
    at std::sync::once::Once::call_once::{{closure}}::hd1b4f64c6a058fdf (https://www.yo-yoo.co.il/101/ruffle/42ef41f25116839c8e75.wasm:wasm-function[995]:0x2f58da)
    at std::sync::once::Once::call_inner::hf9144d66ddc67dec (https://www.yo-yoo.co.il/101/ruffle/42ef41f25116839c8e75.wasm:wasm-function[1189]:0x33b8db)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h7c91d9e8737f5a50 (https://www.yo-yoo.co.il/101/ruffle/42ef41f25116839c8e75.wasm:wasm-function[4699]:0x505559)
    at std::panicking::rust_panic_with_hook::h606d7c7f7a423b98 (https://www.yo-yoo.co.il/101/ruffle/42ef41f25116839c8e75.wasm:wasm-function[3242]:0x4b1ba1)
    at rust_begin_unwind (https://www.yo-yoo.co.il/101/ruffle/42ef41f25116839c8e75.wasm:wasm-function[4766]:0x506d72)
    at core::panicking::panic_fmt::h6314b5c91abe7349 (https://www.yo-yoo.co.il/101/ruffle/42ef41f25116839c8e75.wasm:wasm-function[4978]:0x511c44)
    at core::panicking::panic::hec1fc057bd0baf0b (https://www.yo-yoo.co.il/101/ruffle/42ef41f25116839c8e75.wasm:wasm-function[4696]:0x504dbf)
    at ruffle_core::html::text_format::FormatSpans::from_html::hc726236c340f24af (https://www.yo-yoo.co.il/101/ruffle/42ef41f25116839c8e75.wasm:wasm-function[320]:0x84221)
    at ruffle_core::display_object::edit_text::EditText::set_html_text::h8145119f272c9890 (https://www.yo-yoo.co.il/101/ruffle/42ef41f25116839c8e75.wasm:wasm-function[2479]:0x450cd7)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://games.yo-yoo.co.il/games_play.php?game=3418
SWF URL: https://www.bubblebox.com/swf6/20138751/bomber_at_war_2.swf?gameVersion=1

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-01-11
Channel: nightly
Built: 2022-01-11T00:13:04.329Z
Commit: b39ab9034c5bff008a6cff32d0890e5d4cc0942b
Is extension: false

**Comment by relrelb** [comment]
I think this issue has already been fixed, and the SWF works in latest Ruffle nightly release. Feel free to re-open if I'm wrong.
