### ISSUE TITLE
Error on https://web.archive.org/web/20111012220511/http://www.youtube.com/watch?v=fRf7JbpMOBs

### ISSUE THREAD

**Issue by DougWolfDoggo** [ruffle-rs/ruffle#6980]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm2/object.rs:308:48
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm2/object.rs:308:48
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:1:7485)
    at std::sync::once::Once::call_once::{{closure}}::hc3464e04dbb9beda (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/b8d28947a2b0a8f19725.wasm:wasm-function[978]:0x290346)
    at std::sync::once::Once::call_inner::h07d0245bef259c27 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/b8d28947a2b0a8f19725.wasm:wasm-function[1431]:0x30c0fd)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h44f701de063d4daa (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/b8d28947a2b0a8f19725.wasm:wasm-function[4913]:0x462de0)
    at std::panicking::rust_panic_with_hook::h623ac32ff431b114 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/b8d28947a2b0a8f19725.wasm:wasm-function[3250]:0x40896f)
    at core::panicking::panic_fmt::h5118e89563022e7e (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/b8d28947a2b0a8f19725.wasm:wasm-function[4994]:0x466a3e)
    at core::panicking::panic::he88f1b1582b09c8c (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/b8d28947a2b0a8f19725.wasm:wasm-function[4911]:0x462979)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::h831a7d5f2dc1a8ab (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/b8d28947a2b0a8f19725.wasm:wasm-function[326]:0x76118)
    at ruffle_core::avm2::activation::Activation::run_actions::had6b5f0b2ab1010a (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/b8d28947a2b0a8f19725.wasm:wasm-function[313]:0x213da)
    at ruffle_core::avm2::function::Executable::exec::h82672c4778654bea (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/b8d28947a2b0a8f19725.wasm:wasm-function[721]:0x212265)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://web.archive.org/web/20111012220511/http://www.youtube.com/watch?v=fRf7JbpMOBs
SWF URL: http://s.ytimg.com/yt/swfbin/watch_as3-vflTGhsfb.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.84 Safari/537.36 OPR/85.0.4341.79
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-05-14
Channel: nightly
Built: 2022-05-14T00:17:29.589Z
Commit: a453aa73afbd8d8ab509bd7cbd2366a024ca8649
Is extension: true

**Comment by kjarosh** [comment]
Should be fixed as of today—the related code has been heavily rewritten.
