### ISSUE TITLE
Error on https://www.invisionsportsarcade.com/index.php

### ISSUE THREAD

**Issue by bllsht2** [ruffle-rs/ruffle#7079]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm2/object.rs:308:48
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm2/object.rs:308:48
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/662.js:1:7022)
    at std::sync::once::Once::call_once::{{closure}}::h2b3586a1c348e776 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/3d6e68115ff8590b1679.wasm:wasm-function[1132]:0x2b911b)
    at std::sync::once::Once::call_inner::h8a142b2dcc139875 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/3d6e68115ff8590b1679.wasm:wasm-function[1462]:0x3175ab)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h0e8f59b7c29e471d (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/3d6e68115ff8590b1679.wasm:wasm-function[4760]:0x460532)
    at std::panicking::rust_panic_with_hook::he2a025723e105e28 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/3d6e68115ff8590b1679.wasm:wasm-function[3218]:0x40996c)
    at core::panicking::panic_fmt::hb02133958c1e7d35 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/3d6e68115ff8590b1679.wasm:wasm-function[4942]:0x467557)
    at core::panicking::panic::hc28e7cc2aa792341 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/3d6e68115ff8590b1679.wasm:wasm-function[4852]:0x462544)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::h1413879ef91690f5 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/3d6e68115ff8590b1679.wasm:wasm-function[491]:0x17a60b)
    at ruffle_core::avm2::activation::Activation::run_actions::h7e7a9e1115700638 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/3d6e68115ff8590b1679.wasm:wasm-function[316]:0x2256e)
    at ruffle_core::avm2::function::Executable::exec::h2c3df1b29090e035 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/3d6e68115ff8590b1679.wasm:wasm-function[737]:0x21f748)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://www.invisionsportsarcade.com/index.php?autocom=arcade&do=play&gameid=34878
SWF URL: https://www.invisionsportsarcade.com/arcade/XMASMahj2016AS3v2MAX.swf?ibpro_gameid=6243081

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-05-23
Channel: nightly
Built: 2022-05-23T00:17:04.570Z
Commit: 4f6959184b51f53547436a1a7be4a5df46fcd859
Is extension: true

**Comment by kjarosh** [comment]
Should be fixed as of today—the related code has been heavily rewritten.
