### ISSUE TITLE
Error on https://ruffle.rs/demo/

### ISSUE THREAD

**Issue by l123sd** [ruffle-rs/ruffle#7102]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm2/object.rs:308:48
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm2/object.rs:308:48
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (https://ruffle.rs/demo/966.index.js:1:8220)
    at std::sync::once::Once::call_once::{{closure}}::h7fa47e3c73b3cd43 (https://ruffle.rs/demo/ac68a25ed0a60fd1f746.wasm:wasm-function[1234]:0x2b9ef3)
    at std::sync::once::Once::call_inner::h8a142b2dcc139875 (https://ruffle.rs/demo/ac68a25ed0a60fd1f746.wasm:wasm-function[1462]:0x2f7904)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h81a7d47a510b3842 (https://ruffle.rs/demo/ac68a25ed0a60fd1f746.wasm:wasm-function[4915]:0x4518b1)
    at std::panicking::rust_panic_with_hook::he2a025723e105e28 (https://ruffle.rs/demo/ac68a25ed0a60fd1f746.wasm:wasm-function[3242]:0x3f2742)
    at core::panicking::panic_fmt::hb02133958c1e7d35 (https://ruffle.rs/demo/ac68a25ed0a60fd1f746.wasm:wasm-function[5106]:0x45b2fb)
    at core::panicking::panic::hc28e7cc2aa792341 (https://ruffle.rs/demo/ac68a25ed0a60fd1f746.wasm:wasm-function[5007]:0x45323c)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::hb351e5c1076e63fb (https://ruffle.rs/demo/ac68a25ed0a60fd1f746.wasm:wasm-function[513]:0x15a786)
    at ruffle_core::avm2::activation::Activation::run_actions::hb64dd659c864546f (https://ruffle.rs/demo/ac68a25ed0a60fd1f746.wasm:wasm-function[354]:0xa854)
    at ruffle_core::avm2::script::Script::globals::h891bfa4a9ea19914 (https://ruffle.rs/demo/ac68a25ed0a60fd1f746.wasm:wasm-function[1261]:0x2c26c8)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://ruffle.rs/demo/

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.0.0 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-05-28
Channel: nightly
Built: 2022-05-28T00:13:09.617Z
Commit: aad3ad6c087816b2259123c78f00b3d22b1b61de
Is extension: false

**Comment by n0samu** [comment]
Old issue with no information provided, closing
