### ISSUE TITLE
Error on https://play.cplegacy.com/

### ISSUE THREAD

**Issue by Cupcake567** [ruffle-rs/ruffle#7117]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:500:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:500:50
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.3b64b24078093e7563da.js:1:7024)
    at std::sync::once::Once::call_once::{{closure}}::h2b3586a1c348e776 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.5.30/0d3c79f331e54b6385be.wasm:wasm-function[1182]:0x2ae273)
    at std::sync::once::Once::call_inner::h8a142b2dcc139875 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.5.30/0d3c79f331e54b6385be.wasm:wasm-function[1406]:0x2e9848)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h0e8f59b7c29e471d (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.5.30/0d3c79f331e54b6385be.wasm:wasm-function[4752]:0x4390a3)
    at std::panicking::rust_panic_with_hook::he2a025723e105e28 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.5.30/0d3c79f331e54b6385be.wasm:wasm-function[3140]:0x3dd913)
    at core::panicking::panic_fmt::hb02133958c1e7d35 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.5.30/0d3c79f331e54b6385be.wasm:wasm-function[4935]:0x43eff0)
    at core::result::unwrap_failed::h68fdaca771c68bb6 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.5.30/0d3c79f331e54b6385be.wasm:wasm-function[4078]:0x423803)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::hec2f1d11faa34644 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.5.30/0d3c79f331e54b6385be.wasm:wasm-function[714]:0x1fde98)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::register_shape::h2e3dd5d74111800b (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.5.30/0d3c79f331e54b6385be.wasm:wasm-function[3173]:0x3dfbc0)
    at ruffle_core::display_object::movie_clip::MovieClipData::define_shape::h7cfb9c64e8cca9dd (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.5.30/0d3c79f331e54b6385be.wasm:wasm-function[2073]:0x36ffc0)
    at ruffle_core::display_object::movie_clip::MovieClip::preload::hb3a1bdecfc6db20b (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.5.30/0d3c79f331e54b6385be.wasm:wasm-function[814]:0x22ef81)
    at <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hfcc88d86816c3df8 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.5.30/0d3c79f331e54b6385be.wasm:wasm-function[456]:0x13dd75)
    at <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h7f0b3da3c15b2497 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.5.30/0d3c79f331e54b6385be.wasm:wasm-function[1939]:0x35b033)
    at wasm_bindgen_futures::queue::Queue::new::{{closure}}::hf6f8e75dc21a5b85 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.5.30/0d3c79f331e54b6385be.wasm:wasm-function[2154]:0x37a02a)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h6fb2540f55cb3894 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.5.30/0d3c79f331e54b6385be.wasm:wasm-function[5302]:0x449a52)
    at L (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.3b64b24078093e7563da.js:1:3842)
    at c (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.3b64b24078093e7563da.js:1:2490)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://play.cplegacy.com/
SWF URL: https://cpl-prod.b-cdn.net/assets/media/swf/games/boot.swf

# Browser Info
Useragent: Mozilla/5.0 (Linux; Android 12; SM-G986U1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.61 Mobile Safari/537.36
OS: Linux aarch64

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-05-30
Channel: nightly
Built: 2022-05-30T00:15:27.924Z
Commit: ec23a64a13041ae46a370d5516f961c12999d41d
Is extension: false

**Comment by Toad06** [comment]
Closing in favor of #1905 (same issue). Thanks for reporting.
