### ISSUE TITLE
Error on https://669270955-atari-embeds.googleusercontent.com/embeds/16cb204cf3a9d4d223a0a3fd8b0eec5d/inner-frame-minified.html

### ISSUE THREAD

**Issue by JOSHYneedsBBC** [ruffle-rs/ruffle#7131]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:849:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:849:18
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (https://www-sites-opensocial.googleusercontent.com/gadgets/proxy/refresh=3600&container=enterprise/https://lablockedgames.com/ruffle/ruffle.js:1:7476)
    at std::sync::once::Once::call_once::{{closure}}::h5df181b90ad904c1 (wasm://wasm/0151bd52:wasm-function[1008]:0x27f039)
    at std::sync::once::Once::call_inner::h79faa41f4d270a0b (wasm://wasm/0151bd52:wasm-function[974]:0x274adb)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hbd170ba35c598204 (wasm://wasm/0151bd52:wasm-function[3882]:0x421744)
    at std::panicking::rust_panic_with_hook::hbdbceb5cd158bf19 (wasm://wasm/0151bd52:wasm-function[2999]:0x3c00b7)
    at rust_begin_unwind (wasm://wasm/0151bd52:wasm-function[4094]:0x4270ec)
    at core::panicking::panic_fmt::h3ab5417155b7ba3b (wasm://wasm/0151bd52:wasm-function[4244]:0x42debf)
    at core::panicking::panic::h5bfdfaa3db9a4b4a (wasm://wasm/0151bd52:wasm-function[4036]:0x4247ef)
    at core::ops::function::FnOnce::call_once::h862d0560e2b20be7 (wasm://wasm/0151bd52:wasm-function[869]:0x25246b)
    at ruffle_core::avm1::function::Executable::exec::h590beaec26993867 (wasm://wasm/0151bd52:wasm-function[364]:0xd6a4e)
```

# Player Info
Allows script access: false
Player type: Object
SWF URL: https://www-sites-opensocial.googleusercontent.com/gadgets/proxy/refresh=3600&container=enterprise/https://frivez.com/games/electric-man.swf
Param wmode: direct
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined

# Page Info
Page URL: https://669270955-atari-embeds.googleusercontent.com/embeds/16cb204cf3a9d4d223a0a3fd8b0eec5d/inner-frame-minified.html?jsh=m%3B%2F_%2Fscs%2Fabc-static%2F_%2Fjs%2Fk%3Dgapi.lb.en.KVSPb_Y8pSk.O%2Fd%3D1%2Frs%3DAHpOoo9gW8E5WGSmGcbq8d2kz7xJze20YQ%2Fm%3D__features__
SWF URL: https://www-sites-opensocial.googleusercontent.com/gadgets/proxy/refresh=3600&container=enterprise/https://frivez.com/games/electric-man.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; CrOS x86_64 14324.80.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.102 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-07-16
Channel: nightly
Built: 2021-07-16T00:11:44.228Z
Commit: 5dde3ecabf255ecbeab7d9dcd122517492bc0e66

**Comment by n0samu** [comment]
Actually duplicate of #4932. (This game doesn't work yet, sorry!)
