### ISSUE TITLE
Error on https://udico.co/dct/dct

### ISSUE THREAD

**Issue by jimk1962** [ruffle-rs/ruffle#7132]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: JsValue(InvalidStateError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
Error: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
    at https://udicowebflow.s3.us-east-2.amazonaws.com/DCT/ruffle/core.ruffle.250840c802a98abb21a2.js:1:28464
    at D (https://udicowebflow.s3.us-east-2.amazonaws.com/DCT/ruffle/core.ruffle.250840c802a98abb21a2.js:1:4170)
    at c.wbg.__wbg_drawImage_9492b361f8b31282 (https://udicowebflow.s3.us-east-2.amazonaws.com/DCT/ruffle/core.ruffle.250840c802a98abb21a2.js:1:28438)
    at web_sys::features::gen_CanvasRenderingContext2d::CanvasRenderingContext2d::draw_image_with_html_canvas_element::h6335a83e86b8a2f0 (https://udicowebflow.s3.us-east-2.amazonaws.com/DCT/ruffle/1e45ad06d2e185d06daf.wasm:wasm-function[4623]:0x4c77a3)
    at <ruffle_render_canvas::WebCanvasRenderBackend as ruffle_core::backend::render::RenderBackend>::pop_mask::h15dec22dea9a1fb9 (https://udicowebflow.s3.us-east-2.amazonaws.com/DCT/ruffle/1e45ad06d2e185d06daf.wasm:wasm-function[987]:0x2e2f74)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render_self::h700dfb16be234ea1 (https://udicowebflow.s3.us-east-2.amazonaws.com/DCT/ruffle/1e45ad06d2e185d06daf.wasm:wasm-function[3172]:0x473325)
    at ruffle_core::display_object::render_base::hcad626383704f7cf (https://udicowebflow.s3.us-east-2.amazonaws.com/DCT/ruffle/1e45ad06d2e185d06daf.wasm:wasm-function[1582]:0x387c92)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render::h6627012eabfea848 (https://udicowebflow.s3.us-east-2.amazonaws.com/DCT/ruffle/1e45ad06d2e185d06daf.wasm:wasm-function[3754]:0x4a235f)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render_self::h700dfb16be234ea1 (https://udicowebflow.s3.us-east-2.amazonaws.com/DCT/ruffle/1e45ad06d2e185d06daf.wasm:wasm-function[3172]:0x471241)
    at ruffle_core::display_object::render_base::hcad626383704f7cf (https://udicowebflow.s3.us-east-2.amazonaws.com/DCT/ruffle/1e45ad06d2e185d06daf.wasm:wasm-function[1582]:0x387c92))', render/canvas/src/lib.rs:824:14

# Player Info
Allows script access: false

# Page Info
Page URL: https://udico.co/dct/dct
SWF URL: https://udicowebflow.s3.us-east-2.amazonaws.com/DCT/Udico_DCT6_beta06.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-02-24
Channel: nightly
Built: 2022-02-24T00:17:59.239Z
Commit: 056eee8b46c91e2dbbb54530bb30554766a703ff
Is extension: false

**Comment by relrelb** [comment]
Fixed by #9358.
