### ISSUE TITLE
Error on chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/player.html

### ISSUE THREAD

**Issue by aROBLOXguy** [ruffle-rs/ruffle#7157]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm2/object.rs:308:48
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm2/object.rs:308:48
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:1:7022)
    at std::sync::once::Once::call_once::{{closure}}::h2027a447bec228ec (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/10ec1938b10a74137670.wasm:wasm-function[1184]:0x2aee95)
    at std::sync::once::Once::call_inner::h8a142b2dcc139875 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/10ec1938b10a74137670.wasm:wasm-function[1406]:0x2e9ee3)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hd3865d0bba70fdf0 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/10ec1938b10a74137670.wasm:wasm-function[4744]:0x43931e)
    at std::panicking::rust_panic_with_hook::he2a025723e105e28 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/10ec1938b10a74137670.wasm:wasm-function[3143]:0x3de187)
    at core::panicking::panic_fmt::hb02133958c1e7d35 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/10ec1938b10a74137670.wasm:wasm-function[4926]:0x43f37f)
    at core::panicking::panic::hc28e7cc2aa792341 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/10ec1938b10a74137670.wasm:wasm-function[4837]:0x43b378)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::hc8221bbdd1706a15 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/10ec1938b10a74137670.wasm:wasm-function[471]:0x152121)
    at ruffle_core::avm2::activation::Activation::run_actions::hf71eb191842b5e68 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/10ec1938b10a74137670.wasm:wasm-function[315]:0xa044)
    at ruffle_core::avm2::function::Executable::exec::h25d5350afbc689f4 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/10ec1938b10a74137670.wasm:wasm-function[714]:0x1fb501)
```

# Player Info
Allows script access: false

# Page Info
Page URL: chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/player.html?url=https%3A%2F%2Fweb.archive.org%2Fweb%2F20130927234348if_%2Fhttp%3A%2F%2Fs.ytimg.com%2Fyts%2Fswfbin%2Fwatch_as3-vflEFPMBh.swf
SWF URL: https://web.archive.org/web/20130927234348if_/http://s.ytimg.com/yts/swfbin/watch_as3-vflEFPMBh.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.61 Safari/537.36
Platform: Win32
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-06-03
Channel: nightly
Built: 2022-06-03T00:15:33.659Z
Commit: 53ef80f51443342b6f40e48e843655a062bbd37c
Is extension: true

**Comment by kjarosh** [comment]
Should be fixed as of today—the related code has been heavily rewritten. (See https://github.com/ruffle-rs/ruffle/pull/7095)
