### ISSUE TITLE
Error on https://homestarrunner.com/dman3

### ISSUE THREAD

**Issue by WAAZKOR** [ruffle-rs/ruffle#7160]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:490:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:490:50
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (https://homestarrunner.com/assets/js/core.ruffle.9f34461512943190570b.js:1:7087)
    at std::sync::once::Once::call_once::{{closure}}::h9f25555b76706740 (https://homestarrunner.com/assets/js/86493978e1f931ba61f6.wasm:wasm-function[1007]:0x2ac927)
    at std::sync::once::Once::call_inner::h07d0245bef259c27 (https://homestarrunner.com/assets/js/86493978e1f931ba61f6.wasm:wasm-function[1442]:0x32163b)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h51a4a6ecbb3638ab (https://homestarrunner.com/assets/js/86493978e1f931ba61f6.wasm:wasm-function[4902]:0x474dff)
    at std::panicking::rust_panic_with_hook::h623ac32ff431b114 (https://homestarrunner.com/assets/js/86493978e1f931ba61f6.wasm:wasm-function[3243]:0x424dbd)
    at core::panicking::panic_fmt::h5118e89563022e7e (https://homestarrunner.com/assets/js/86493978e1f931ba61f6.wasm:wasm-function[4974]:0x478bd8)
    at core::result::unwrap_failed::ha62420c192a556da (https://homestarrunner.com/assets/js/86493978e1f931ba61f6.wasm:wasm-function[4098]:0x45d216)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::hbce29b2eed37c6d4 (https://homestarrunner.com/assets/js/86493978e1f931ba61f6.wasm:wasm-function[737]:0x22ce2d)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::register_shape::h7a187220cc18d67f (https://homestarrunner.com/assets/js/86493978e1f931ba61f6.wasm:wasm-function[3270]:0x426ddc)
    at ruffle_core::drawing::Drawing::render::h54a0c99faacd1987 (https://homestarrunner.com/assets/js/86493978e1f931ba61f6.wasm:wasm-function[651]:0x206958)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://homestarrunner.com/dman3
SWF URL: https://homestarrunner.com/media/pages/dman3/f0e50731c9-1609375302/thydungeonman3.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-04-09
Channel: nightly
Built: 2022-04-09T00:17:35.442Z
Commit: d7532ae6540cec3aabcbe14ac7e38691e2c74f78
Is extension: false

**Comment by Toad06** [comment]
Closing in favor of https://github.com/ruffle-rs/ruffle/issues/1905 (same issue). Thanks for reporting.
