### ISSUE TITLE
Error on https://f.kbhgames.com/RS/game.php

### ISSUE THREAD

**Issue by toast-t-bread** [ruffle-rs/ruffle#7190]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:500:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:500:50
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:1:7022)
    at std::sync::once::Once::call_once::{{closure}}::hf4bd8358d66e2cc8 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/bb8b9a8ee86b26f77767.wasm:wasm-function[1184]:0x2aed45)
    at std::sync::once::Once::call_inner::h8a142b2dcc139875 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/bb8b9a8ee86b26f77767.wasm:wasm-function[1406]:0x2e9d97)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h1ffe884207fb3c6a (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/bb8b9a8ee86b26f77767.wasm:wasm-function[4746]:0x4394ed)
    at std::panicking::rust_panic_with_hook::he2a025723e105e28 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/bb8b9a8ee86b26f77767.wasm:wasm-function[3142]:0x3de058)
    at core::panicking::panic_fmt::hb02133958c1e7d35 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/bb8b9a8ee86b26f77767.wasm:wasm-function[4928]:0x43f574)
    at core::result::unwrap_failed::h68fdaca771c68bb6 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/bb8b9a8ee86b26f77767.wasm:wasm-function[4075]:0x423d5a)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::hda4ccf5cbc3b9011 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/bb8b9a8ee86b26f77767.wasm:wasm-function[716]:0x1fe81d)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::register_glyph_shape::h5ac900dda04cb20e (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/bb8b9a8ee86b26f77767.wasm:wasm-function[1618]:0x319da6)
    at ruffle_core::font::Font::from_swf_tag::hce5da37036303f68 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/bb8b9a8ee86b26f77767.wasm:wasm-function[654]:0x1deb14)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://f.kbhgames.com/RS/game.php?r=//f.kbhgames.com/2018/swf/bloondefense3.swf&w=640&h=480
SWF URL: https://f.kbhgames.com/2018/swf/bloondefense3.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-06-07
Channel: nightly
Built: 2022-06-07T00:18:43.684Z
Commit: 487017e7c513ee5397e514069b00c490a3c60463
Is extension: true

**Comment by kjarosh** [comment]
Should be fixed as of the newest version
