### ISSUE TITLE
Error on https://www.albinoblacksheep.com/games/orbox

### ISSUE THREAD

**Issue by Argent094** [ruffle-rs/ruffle#7191]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/movie_clip.rs:3108:14
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/movie_clip.rs:3108:14
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://www.albinoblacksheep.com/script/ruffle_nightly_2021_01_26_selfhosted/ruffle.js:1:6349)
    at std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f (https://www.albinoblacksheep.com/script/ruffle_nightly_2021_01_26_selfhosted/aafdd926c74ff1ff1e03a02091c0405b.wasm:wasm-function[1267]:0x24ef2a)
    at std::sync::once::Once::call_inner::h02eac160d339afc2 (https://www.albinoblacksheep.com/script/ruffle_nightly_2021_01_26_selfhosted/aafdd926c74ff1ff1e03a02091c0405b.wasm:wasm-function[1528]:0x27ed9a)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801 (https://www.albinoblacksheep.com/script/ruffle_nightly_2021_01_26_selfhosted/aafdd926c74ff1ff1e03a02091c0405b.wasm:wasm-function[4308]:0x353f1a)
    at std::panicking::rust_panic_with_hook::h123718ba3bf480af (https://www.albinoblacksheep.com/script/ruffle_nightly_2021_01_26_selfhosted/aafdd926c74ff1ff1e03a02091c0405b.wasm:wasm-function[3299]:0x32cc21)
    at std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2 (https://www.albinoblacksheep.com/script/ruffle_nightly_2021_01_26_selfhosted/aafdd926c74ff1ff1e03a02091c0405b.wasm:wasm-function[3916]:0x349dd5)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925 (https://www.albinoblacksheep.com/script/ruffle_nightly_2021_01_26_selfhosted/aafdd926c74ff1ff1e03a02091c0405b.wasm:wasm-function[4654]:0x359654)
    at rust_begin_unwind (https://www.albinoblacksheep.com/script/ruffle_nightly_2021_01_26_selfhosted/aafdd926c74ff1ff1e03a02091c0405b.wasm:wasm-function[4525]:0x357c32)
    at core::panicking::panic_fmt::h285dc015a87be5a4 (https://www.albinoblacksheep.com/script/ruffle_nightly_2021_01_26_selfhosted/aafdd926c74ff1ff1e03a02091c0405b.wasm:wasm-function[4656]:0x3596b8)
    at core::panicking::panic::h0abe4e7a620ae568 (https://www.albinoblacksheep.com/script/ruffle_nightly_2021_01_26_selfhosted/aafdd926c74ff1ff1e03a02091c0405b.wasm:wasm-function[4459]:0x356af7)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: /swf/games/orbox(www.albinoblacksheep.com).swf
Param movie: /swf/games/orbox(www.albinoblacksheep.com).swf
Param quality: high
Param menu: true
Param wmode: window
Param allowFullScreen: true
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://www.albinoblacksheep.com/games/orbox
SWF URL: https://www.albinoblacksheep.com/swf/games/orbox(www.albinoblacksheep.com).swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-26
Channel: nightly
Built: 2021-01-26T00:36:48.131Z
Commit: 7856cdd3d770e406ce546bf1745d8046d7b716f8

**Comment by Argent094** [comment]
I was trying to open the Orbox game (by Rubilon), and got the error message referenced above....

**Comment by n0samu** [comment]
This problem has already been fixed in the latest Ruffle version - the site needs to update their version of Ruffle. You can contact them here: https://www.albinoblacksheep.com/contact/

**Comment by Argent094** [comment]
OK, the folks at albinoblacksheep.com have updated Ruffle; everything works as expected, now.
Thanks,Stuart Herring
    On Tuesday, June 7, 2022, 01:59:23 AM CDT, nosamu ***@***.***> wrote:  
 
 


This problem has already been fixed in the latest Ruffle version - the site needs to update their version of Ruffle. You can contact them here: https://www.albinoblacksheep.com/contact/

**Comment by n0samu** [comment]
I'm happy to hear it!
