### ISSUE TITLE
Error on https://web.archive.org/web/20140607171505/http://www.youtube.com/watch?v=1_S0TeWm-fU

### ISSUE THREAD

**Issue by Werwulf62141** [ruffle-rs/ruffle#7195]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm2/object.rs:308:48
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm2/object.rs:308:48
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:1:7022)
    at std::sync::once::Once::call_once::{{closure}}::hf4bd8358d66e2cc8 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/bb8b9a8ee86b26f77767.wasm:wasm-function[1184]:0x2aed45)
    at std::sync::once::Once::call_inner::h8a142b2dcc139875 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/bb8b9a8ee86b26f77767.wasm:wasm-function[1406]:0x2e9d97)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h1ffe884207fb3c6a (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/bb8b9a8ee86b26f77767.wasm:wasm-function[4746]:0x4394ed)
    at std::panicking::rust_panic_with_hook::he2a025723e105e28 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/bb8b9a8ee86b26f77767.wasm:wasm-function[3142]:0x3de058)
    at core::panicking::panic_fmt::hb02133958c1e7d35 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/bb8b9a8ee86b26f77767.wasm:wasm-function[4928]:0x43f54e)
    at core::panicking::panic::hc28e7cc2aa792341 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/bb8b9a8ee86b26f77767.wasm:wasm-function[4839]:0x43b547)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::h9df7cdcb636b951e (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/bb8b9a8ee86b26f77767.wasm:wasm-function[471]:0x151fdc)
    at ruffle_core::avm2::activation::Activation::run_actions::ha8f0ce73339876f9 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/bb8b9a8ee86b26f77767.wasm:wasm-function[315]:0xa046)
    at ruffle_core::avm2::function::Executable::exec::h5521f14aa83a20d3 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/bb8b9a8ee86b26f77767.wasm:wasm-function[714]:0x1fb3bc)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://web.archive.org/web/20140607171505/http://www.youtube.com/watch?v=1_S0TeWm-fU
SWF URL: http://s.ytimg.com/yts/swfbin/player-vflmTHkPE/watch_as3.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-06-07
Channel: nightly
Built: 2022-06-07T00:18:43.684Z
Commit: 487017e7c513ee5397e514069b00c490a3c60463
Is extension: true

**Comment by kjarosh** [comment]
Should be fixed as of today—the related code has been heavily rewritten. (See https://github.com/ruffle-rs/ruffle/pull/7095)
