### ISSUE TITLE
Error on chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/player.html

### ISSUE THREAD

**Issue by JFed-9** [ruffle-rs/ruffle#7201]
I was playing Electric Man 2 on MaxGames.com, and it seems to always have bugs using Ruffle. I start a game, make it through the first half of the tutorial, then it speeds through the second half, and the game is almost softlocked. You can mash the mouse button to click on a level, but as soon as the countdown ends, it crashes (probably since there aren't supposed to already be enemies before the match starts).

# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:1:7022)
    at std::sync::once::Once::call_once::{{closure}}::hf4bd8358d66e2cc8 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/bb8b9a8ee86b26f77767.wasm:wasm-function[1184]:0x2aed45)
    at std::sync::once::Once::call_inner::h8a142b2dcc139875 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/bb8b9a8ee86b26f77767.wasm:wasm-function[1406]:0x2e9d97)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h1ffe884207fb3c6a (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/bb8b9a8ee86b26f77767.wasm:wasm-function[4746]:0x4394ed)
    at std::panicking::rust_panic_with_hook::he2a025723e105e28 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/bb8b9a8ee86b26f77767.wasm:wasm-function[3142]:0x3de058)
    at core::panicking::panic_fmt::hb02133958c1e7d35 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/bb8b9a8ee86b26f77767.wasm:wasm-function[4928]:0x43f54e)
    at core::panicking::panic::hc28e7cc2aa792341 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/bb8b9a8ee86b26f77767.wasm:wasm-function[4839]:0x43b547)
    at core::ops::function::FnOnce::call_once::h4faf124a219f785d (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/bb8b9a8ee86b26f77767.wasm:wasm-function[1051]:0x287b38)
    at ruffle_core::avm1::function::Executable::exec::h1e3c90f25dc88eb1 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/bb8b9a8ee86b26f77767.wasm:wasm-function[358]:0xc9f6a)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h109691e3d62f182b (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/bb8b9a8ee86b26f77767.wasm:wasm-function[541]:0x1944e1)
```

# Player Info
Allows script access: false

# Page Info
Page URL: chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/player.html?url=https%3A%2F%2Ffarm.maxgames.com%2Felectricman2_maxgamesMTU5.swf
SWF URL: https://farm.maxgames.com/electricman2_maxgamesMTU5.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36 Edg/102.0.1245.33
Platform: Win32
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-06-07
Channel: nightly
Built: 2022-06-07T00:18:43.684Z
Commit: 487017e7c513ee5397e514069b00c490a3c60463
Is extension: true

**Comment by n0samu** [comment]
This issue is being reported at least several times per week. Closing in favor of #4932.
