### ISSUE TITLE
Error on chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/player.html

### ISSUE THREAD

**Issue by dmhp2996543** [ruffle-rs/ruffle#7214]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm2/object.rs:308:48
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm2/object.rs:308:48
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:1:7022)
    at std::sync::once::Once::call_once::{{closure}}::hf4bd8358d66e2cc8 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/bb242d25001a8b4f1a4a.wasm:wasm-function[1206]:0x2b4d45)
    at std::sync::once::Once::call_inner::h8a142b2dcc139875 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/bb242d25001a8b4f1a4a.wasm:wasm-function[1404]:0x2ea9df)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h1ffe884207fb3c6a (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/bb242d25001a8b4f1a4a.wasm:wasm-function[4740]:0x439f36)
    at std::panicking::rust_panic_with_hook::he2a025723e105e28 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/bb242d25001a8b4f1a4a.wasm:wasm-function[3134]:0x3de933)
    at core::panicking::panic_fmt::hb02133958c1e7d35 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/bb242d25001a8b4f1a4a.wasm:wasm-function[4922]:0x43ff97)
    at core::panicking::panic::hc28e7cc2aa792341 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/bb242d25001a8b4f1a4a.wasm:wasm-function[4833]:0x43bf90)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::h9df7cdcb636b951e (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/bb242d25001a8b4f1a4a.wasm:wasm-function[396]:0xfd566)
    at ruffle_core::avm2::activation::Activation::run_actions::ha8f0ce73339876f9 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/bb242d25001a8b4f1a4a.wasm:wasm-function[315]:0xa4be)
    at ruffle_core::avm2::script::Script::globals::hf6c092326d349758 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/bb242d25001a8b4f1a4a.wasm:wasm-function[645]:0x1dcd68)
```

# Player Info
Allows script access: false

# Page Info
Page URL: chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/player.html?url=http%3A%2F%2Fcdn.eos05.com%3A811%2F20220105%2Floading.swf
SWF URL: http://cdn.eos05.com:811/20220105/loading.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-06-12
Channel: nightly
Built: 2022-06-12T00:13:41.089Z
Commit: bd88e5e95a8e75562c39f44078a4bda786e809c6
Is extension: true

**Comment by n0samu** [comment]
This is definitely a strange issue. This SWF uses ActionScript 3, so Ruffle should display a warning about it, but instead it spams a "Failed to lock Ruffle core" message in the console and shows this error.

**Comment by kjarosh** [comment]
Should be fixed as of today—the related code has been heavily rewritten. (See https://github.com/ruffle-rs/ruffle/pull/7095)
