### ISSUE TITLE
Error at chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/player.html?url=http%3A%2F%2Fi.flipline.com%2Fgamefiles%2Fpapashotdoggeria%2Fpapashotdoggeria_v2.swf

### ISSUE THREAD

**Issue by Filename99** [ruffle-rs/ruffle#7279]
# Error Info
Error name: Error
Error message: Failed to fetch: http://i.flipline.com/gamefiles/papashotdoggeria/papashotdoggeria_v2.swf
Error stack:
```
Error: Failed to fetch: http://i.flipline.com/gamefiles/papashotdoggeria/papashotdoggeria_v2.swf
    at M.displayRootMovieDownloadFailedMessage (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/player.js:1:36731)
    at c.wbg.__wbg_displayRootMovieDownloadFailedMessage_1a5c34096259685a (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:1:8047)
    at <ruffle_web::ui::WebUiBackend as ruffle_core::backend::ui::UiBackend>::display_root_movie_download_failed_message::h767cf1353c36cf7d (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/281927c7350b43fd966f.wasm:wasm-function[5642]:0x448edd)
    at <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hbd0a09a2cc56a00a (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/281927c7350b43fd966f.wasm:wasm-function[560]:0x1bce32)
    at <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h7c8dc94962164a1f (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/281927c7350b43fd966f.wasm:wasm-function[1911]:0x351cfd)
    at wasm_bindgen_futures::queue::Queue::new::{{closure}}::hecbd40711c9dbe6f (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/281927c7350b43fd966f.wasm:wasm-function[2119]:0x36f81c)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hd96d956c8ead6a7f (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/281927c7350b43fd966f.wasm:wasm-function[5232]:0x43ebe7)
    at L (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:1:3840)
    at c (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:1:2488)
```

# Player Info
Allows script access: false

# Page Info
Page URL: chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/player.html?url=http%3A%2F%2Fi.flipline.com%2Fgamefiles%2Fpapashotdoggeria%2Fpapashotdoggeria_v2.swf
SWF URL: http://i.flipline.com/gamefiles/papashotdoggeria/papashotdoggeria_v2.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.160 YaBrowser/22.5.2.615 Yowser/2.5 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-06-20
Channel: nightly
Built: 2022-06-20T00:17:11.892Z
Commit: b4bed3c931213ba369a3c835efc8b657e8becafd
Is extension: true

**Comment by n0samu** [comment]
This seems to be a problem specifically with the Yandex Browser - other browsers work fine, but Yandex Browser freezes when trying to load an SWF via the Ruffle extension's internal player page.
