### ISSUE TITLE
Error on https://h-flash.com/hentime-hentai-artist-2/

### ISSUE THREAD

**Issue by he00830490** [ruffle-rs/ruffle#7296]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm2/object.rs:305:48
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm2/object.rs:305:48
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (https://h-flash.com/data/ruffle/core.ruffle.f278ea4a450805461cf1.js:1:7441)
    at std::sync::once::Once::call_once::{{closure}}::h6bc0eae8713deb80 (https://h-flash.com/data/ruffle/9499b1bd3439add91006.wasm:wasm-function[1015]:0x2ad562)
    at std::sync::once::Once::call_inner::h51a70f81ef530383 (https://h-flash.com/data/ruffle/9499b1bd3439add91006.wasm:wasm-function[1468]:0x32b11c)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h4e9c305d26dd965f (https://h-flash.com/data/ruffle/9499b1bd3439add91006.wasm:wasm-function[4961]:0x484024)
    at std::panicking::rust_panic_with_hook::h12b2f0179ff84c92 (https://h-flash.com/data/ruffle/9499b1bd3439add91006.wasm:wasm-function[3327]:0x4295cf)
    at core::panicking::panic_fmt::hf0d93ec1ac504cf9 (https://h-flash.com/data/ruffle/9499b1bd3439add91006.wasm:wasm-function[5248]:0x49038a)
    at core::panicking::panic::h5d6906e2c1099660 (https://h-flash.com/data/ruffle/9499b1bd3439add91006.wasm:wasm-function[4958]:0x483b4b)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::h4095175aa0577f5e (https://h-flash.com/data/ruffle/9499b1bd3439add91006.wasm:wasm-function[334]:0x9110f)
    at ruffle_core::avm2::activation::Activation::run_actions::h36a24ffda344bf15 (https://h-flash.com/data/ruffle/9499b1bd3439add91006.wasm:wasm-function[313]:0x21f3e)
    at ruffle_core::avm2::function::Executable::exec::h0d2f5467534b6b2e (https://h-flash.com/data/ruffle/9499b1bd3439add91006.wasm:wasm-function[796]:0x25674e)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://h-flash.com/hentime-hentai-artist-2/
SWF URL: https://h-flash.com/data/swf/2022/06/hentai-artist-popular-girls.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-04-05
Channel: nightly
Built: 2022-04-05T00:18:48.690Z
Commit: e456fb3ed69778e58013fb6034f52a331107829e
Is extension: false

**Comment by kjarosh** [comment]
Should be fixed as of today—the related code has been heavily rewritten. (See https://github.com/ruffle-rs/ruffle/pull/7095)
