### ISSUE TITLE
Error on chrome-extension://ncobpllnedjmbnnjfkojpbijjfefihdb/player.html

### ISSUE THREAD

**Issue by EditaNEmilis** [ruffle-rs/ruffle#7347]
# Error Info
Error name: Error
Error message: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:576:14
Error stack:
```
Error: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:576:14
    at V.e.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://ncobpllnedjmbnnjfkojpbijjfefihdb/dist/966.js:1:6063)
    at std::sync::once::Once::call_once::{{closure}}::h0555ef98a007fd4c (chrome-extension://ncobpllnedjmbnnjfkojpbijjfefihdb/dist/7d199d7a4979f610d722.wasm:wasm-function[1200]:0x2afd6a)
    at std::sync::once::Once::call_inner::hecc7c66a7de7e98e (chrome-extension://ncobpllnedjmbnnjfkojpbijjfefihdb/dist/7d199d7a4979f610d722.wasm:wasm-function[1381]:0x2e7fad)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h41cceef5ab38a800 (chrome-extension://ncobpllnedjmbnnjfkojpbijjfefihdb/dist/7d199d7a4979f610d722.wasm:wasm-function[4684]:0x4260b0)
    at std::panicking::rust_panic_with_hook::h8888bbc201384d7b (chrome-extension://ncobpllnedjmbnnjfkojpbijjfefihdb/dist/7d199d7a4979f610d722.wasm:wasm-function[3082]:0x3d85a3)
    at core::panicking::panic_fmt::h18b15be283411c65 (chrome-extension://ncobpllnedjmbnnjfkojpbijjfefihdb/dist/7d199d7a4979f610d722.wasm:wasm-function[4868]:0x42c2b2)
    at core::option::expect_failed::h710363cb391a4194 (chrome-extension://ncobpllnedjmbnnjfkojpbijjfefihdb/dist/7d199d7a4979f610d722.wasm:wasm-function[5479]:0x439582)
    at ruffle_core::display_object::stage::Stage::root_clip::h6ae0659e89aca5c7 (chrome-extension://ncobpllnedjmbnnjfkojpbijjfefihdb/dist/7d199d7a4979f610d722.wasm:wasm-function[3414]:0x3ee8dd)
    at ruffle_web::Ruffle::tick::h26d707f08aa3325a (chrome-extension://ncobpllnedjmbnnjfkojpbijjfefihdb/dist/7d199d7a4979f610d722.wasm:wasm-function[608]:0x1c1403)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::hba8789de29c9be32 (chrome-extension://ncobpllnedjmbnnjfkojpbijjfefihdb/dist/7d199d7a4979f610d722.wasm:wasm-function[5657]:0x44111d)
```

# Player Info
Allows script access: false

# Page Info
Page URL: chrome-extension://ncobpllnedjmbnnjfkojpbijjfefihdb/player.html?url=https%3A%2F%2Fi.notdoppler.com%2Ffiles%2Fdeadparadise.swf
SWF URL: https://i.notdoppler.com/files/deadparadise.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-07-04
Channel: nightly
Built: 2022-07-04T00:18:13.302Z
Commit: 49e8f4e939c6b0e388a707c33c48ea397be72109
Is extension: true

**Comment by Dinnerbone** [comment]
Fixed in #10026
