### ISSUE TITLE
Error on https://www.clickjogos.com.br/jogos/table-football

### ISSUE THREAD

**Issue by guilhermeponciano-via** [ruffle-rs/ruffle#7355]
# Error Info
Error name: ReferenceError
Error message: WebAssembly is not defined
Error stack:
```
ReferenceError: WebAssembly is not defined
    at https://www.clickjogos.com.br/ruffle/ruffle.js:2901:24
    at Array.forEach (<anonymous>)
    at Object.Si.f.wasm (https://www.clickjogos.com.br/ruffle/ruffle.js:2881:22)
    at https://www.clickjogos.com.br/ruffle/ruffle.js:1690:62
    at Array.reduce (<anonymous>)
    at Function.Si.e (https://www.clickjogos.com.br/ruffle/ruffle.js:1690:37)
    at o (https://www.clickjogos.com.br/ruffle/ruffle.js:390:35)
    at o.next (<anonymous>)
    at https://www.clickjogos.com.br/ruffle/ruffle.js:418:47
    at new Promise (<anonymous>)
```

# Player Info
Allows script access: false
Player type: Object
SWF URL: https://img.clickjogos.com.br/dl/1/18d4c6adb6f413f3837e0abd59b3af05/src.swf
Param movie: https://img.clickjogos.com.br/dl/1/18d4c6adb6f413f3837e0abd59b3af05/src.swf
Param allowScriptAccess: never
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://www.clickjogos.com.br/jogos/table-football

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-15
Channel: nightly
Built: 2021-01-15T01:03:45.335Z
Commit: 09a48a71d8608803fd5dba4343c5f10c928f9652

**Comment by Lord-McSweeney** [comment]
Not an issue with Ruffle, and the site was using a version that is now 4 years outdated
