### ISSUE TITLE
error report on http://www.games82.net/play/magical-unicorn-rainbow-magic/

### ISSUE THREAD

**Issue by flashliberty5467** [ruffle-rs/ruffle#7357]
# Error Info
Error name: Error
Error message: Failed to fetch: http://www.games82.net/play/magical-unicorn-rainbow-magic/produse/174.swf
Error stack:
```
Error: Failed to fetch: http://www.games82.net/play/magical-unicorn-rainbow-magic/produse/174.swf
    at L.displayRootMovieDownloadFailedMessage (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/ruffle.js?id=26080719660:1:36067)
    at V.e.wbg.__wbg_displayRootMovieDownloadFailedMessage_1a5c34096259685a (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:1:6628)
    at <ruffle_web::ui::WebUiBackend as ruffle_core::backend::ui::UiBackend>::display_root_movie_download_failed_message::h6c09c6bc0bd5658e (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/983ae153ff64ec311136.wasm:wasm-function[5656]:0x440f01)
    at <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h135626980dd207bb (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/983ae153ff64ec311136.wasm:wasm-function[554]:0x196be7)
    at <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h6558145c18618fb2 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/983ae153ff64ec311136.wasm:wasm-function[1923]:0x3582af)
    at wasm_bindgen_futures::queue::Queue::new::{{closure}}::h774be0b30bbc39fc (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/983ae153ff64ec311136.wasm:wasm-function[2121]:0x379589)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h9615cf94f2a27930 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/983ae153ff64ec311136.wasm:wasm-function[5229]:0x43696b)
    at k (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:1:3012)
    at c (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:1:2435)
```

# Player Info
Allows script access: false

# Page Info
Page URL: http://www.games82.net/play/magical-unicorn-rainbow-magic/
SWF URL: http://www.games82.net/play/magical-unicorn-rainbow-magic/produse/174.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14816.82.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-07-05
Channel: nightly
Built: 2022-07-05T00:15:59.716Z
Commit: cfe3d379053f096081e184d3dc4d133ab0925e19
Is extension: true

**Comment by n0samu** [comment]
The problem is exactly what the error message states: the SWF file no longer exists on the server, so there is nothing for Ruffle to load. There's a reason why we don't show the "Report Bug" link for this particular error!

**Comment by n0samu** [comment]
Thanks for the additional information. You're right, and it turns out the issue is that Ruffle is not obeying the HTML <base> tag when constructing relative URLs. Fix incoming!

**Comment by n0samu** [comment]
In case it's useful, here's the minimal example that I've been testing my fix with locally:
[base-tag-testing.zip](https://github.com/ruffle-rs/ruffle/files/9060229/base-tag-testing.zip)
