### ISSUE TITLE
Error on http://www.upv.es/plano/plano-2d-es.html

### ISSUE THREAD

**Issue by swaree** [ruffle-rs/ruffle#7361]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 1064, error_len: Some(1) }', core/src/loader.rs:738:38
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 1064, error_len: Some(1) }', core/src/loader.rs:738:38
    at V.e.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:1:6063)
    at std::sync::once::Once::call_once::{{closure}}::haa939b9bd60c7889 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/983ae153ff64ec311136.wasm:wasm-function[1198]:0x2aba47)
    at std::sync::once::Once::call_inner::hecc7c66a7de7e98e (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/983ae153ff64ec311136.wasm:wasm-function[1379]:0x2e3bb6)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h3c0af66c5f925deb (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/983ae153ff64ec311136.wasm:wasm-function[4684]:0x425efd)
    at std::panicking::rust_panic_with_hook::h8888bbc201384d7b (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/983ae153ff64ec311136.wasm:wasm-function[3081]:0x3d831a)
    at core::panicking::panic_fmt::h18b15be283411c65 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/983ae153ff64ec311136.wasm:wasm-function[4868]:0x42c09f)
    at core::result::unwrap_failed::he84b58f6b44a7df4 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/983ae153ff64ec311136.wasm:wasm-function[4010]:0x411139)
    at ruffle_core::loader::Loader::load_url_loader::{{closure}}::{{closure}}::set_data::h4116e7c6cb98f7db (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/983ae153ff64ec311136.wasm:wasm-function[1265]:0x2ca619)
    at <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h94c1767270eecd27 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/983ae153ff64ec311136.wasm:wasm-function[986]:0x26df43)
    at <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h6558145c18618fb2 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/983ae153ff64ec311136.wasm:wasm-function[1923]:0x3582af)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: ./2d/Vera.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined

# Page Info
Page URL: http://www.upv.es/plano/plano-2d-es.html
SWF URL: http://www.upv.es/plano/2d/Vera.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-07-05
Channel: nightly
Built: 2022-07-05T00:15:59.716Z
Commit: cfe3d379053f096081e184d3dc4d133ab0925e19
Is extension: true

**Comment by EmperorBale** [comment]
Fixed by #7420
