### ISSUE TITLE
Error on https://www.furaffinity.net/view/22435338/

### ISSUE THREAD

**Issue by ronhin375** [ruffle-rs/ruffle#7364]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: JsValue(TypeError: f(...).createBuffer is not a function
TypeError: f(...).createBuffer is not a function
    at https://d.furaffinity.net/media/ruffle-nightly-2022_02_24-selfhosted/core.ruffle.250840c802a98abb21a2.js:1:13590
    at D (https://d.furaffinity.net/media/ruffle-nightly-2022_02_24-selfhosted/core.ruffle.250840c802a98abb21a2.js:1:4170)
    at c.wbg.__wbg_createBuffer_79833a4052d7b42a (https://d.furaffinity.net/media/ruffle-nightly-2022_02_24-selfhosted/core.ruffle.250840c802a98abb21a2.js:1:13555)
    at web_sys::features::gen_AudioContext::AudioContext::create_buffer::hc8df3009c5c85780 (https://d.furaffinity.net/media/ruffle-nightly-2022_02_24-selfhosted/1e45ad06d2e185d06daf.wasm:wasm-function[4552]:0x4c5cdf)
    at ruffle_web::audio::WebAudioBackend::decompress_to_audio_buffer::ha64fbe90b04689dc (https://d.furaffinity.net/media/ruffle-nightly-2022_02_24-selfhosted/1e45ad06d2e185d06daf.wasm:wasm-function[465]:0x19c900)
    at <ruffle_web::audio::WebAudioBackend as ruffle_core::backend::audio::AudioBackend>::register_sound::h4db45c4d978e97b7 (https://d.furaffinity.net/media/ruffle-nightly-2022_02_24-selfhosted/1e45ad06d2e185d06daf.wasm:wasm-function[2216]:0x3fb6fb)
    at ruffle_core::display_object::movie_clip::MovieClip::preload::h735c2e68d4418559 (https://d.furaffinity.net/media/ruffle-nightly-2022_02_24-selfhosted/1e45ad06d2e185d06daf.wasm:wasm-function[854]:0x294523)
    at ruffle_core::player::Player::set_root_movie::h000393239ba3a466 (https://d.furaffinity.net/media/ruffle-nightly-2022_02_24-selfhosted/1e45ad06d2e185d06daf.wasm:wasm-function[352]:0xd4539)
    at <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hc5b4ece0924a0c47 (https://d.furaffinity.net/media/ruffle-nightly-2022_02_24-selfhosted/1e45ad06d2e185d06daf.wasm:wasm-function[563]:0x1f5118)
    at <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h991f08ace8025fbd (https://d.furaffinity.net/media/ruffle-nightly-2022_02_24-selfhosted/1e45ad06d2e185d06daf.wasm:wasm-function[1849]:0x3bc7e4))', web/src/audio.rs:749:14

# Player Info
Allows script access: false
Player type: Object
SWF URL: //d.furaffinity.net/art/dracoshu/1486892190/1485646559.dracoshu_game.swf
Param movie: //d.furaffinity.net/art/dracoshu/1486892190/1485646559.dracoshu_game.swf
Param quality: high
Param wmode: direct
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined
Attribute 6: undefined

# Page Info
Page URL: https://www.furaffinity.net/view/22435338/
SWF URL: https://d.furaffinity.net/art/dracoshu/1486892190/1485646559.dracoshu_game.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-02-24
Channel: nightly
Built: 2022-02-24T00:17:59.239Z
Commit: 056eee8b46c91e2dbbb54530bb30554766a703ff
Is extension: false

**Comment by n0samu** [comment]
Probably fixed a long time ago
