### ISSUE TITLE
Error on https://w8.snokido.com/games/flash/index.html

### ISSUE THREAD

**Issue by hirotton** [ruffle-rs/ruffle#7370]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', render/webgl/src/lib.rs:658:48
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', render/webgl/src/lib.rs:658:48
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (https://w8.snokido.com/games/flash/ruffle/220405/core.ruffle.d9ac1083cc51964a91e9.js:1:6879)
    at std::sync::once::Once::call_once::{{closure}}::h34724c5a615dd91e (https://w8.snokido.com/games/flash/ruffle/220405/be50d821cdf1f4d4809f.wasm:wasm-function[1004]:0x29ef2c)
    at std::sync::once::Once::call_inner::h07d0245bef259c27 (https://w8.snokido.com/games/flash/ruffle/220405/be50d821cdf1f4d4809f.wasm:wasm-function[1455]:0x317ed5)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h1cc7f1c9e77acd09 (https://w8.snokido.com/games/flash/ruffle/220405/be50d821cdf1f4d4809f.wasm:wasm-function[4941]:0x46f5d0)
    at std::panicking::rust_panic_with_hook::h623ac32ff431b114 (https://w8.snokido.com/games/flash/ruffle/220405/be50d821cdf1f4d4809f.wasm:wasm-function[3268]:0x413e09)
    at core::panicking::panic_fmt::h5118e89563022e7e (https://w8.snokido.com/games/flash/ruffle/220405/be50d821cdf1f4d4809f.wasm:wasm-function[5026]:0x47373d)
    at core::panicking::panic::he88f1b1582b09c8c (https://w8.snokido.com/games/flash/ruffle/220405/be50d821cdf1f4d4809f.wasm:wasm-function[4939]:0x46f169)
    at ruffle_render_webgl::WebGlRenderBackend::register_bitmap::h16c15c16ded47781 (https://w8.snokido.com/games/flash/ruffle/220405/be50d821cdf1f4d4809f.wasm:wasm-function[1730]:0x35562d)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::register_bitmap_raw::h1d53c327e3004d28 (https://w8.snokido.com/games/flash/ruffle/220405/be50d821cdf1f4d4809f.wasm:wasm-function[4034]:0x4516b9)
    at ruffle_core::bitmap::bitmap_data::BitmapData::bitmap_handle::hb925187340995102 (https://w8.snokido.com/games/flash/ruffle/220405/be50d821cdf1f4d4809f.wasm:wasm-function[1639]:0x341f3f)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://w8.snokido.com/games/flash/index.html?g=fairy-tail-vs-one-piece/11/game
SWF URL: https://w8.snokido.com/games/flash/fairy-tail-vs-one-piece/11/game.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-05-04
Channel: nightly
Built: 2022-05-04T00:18:20.135Z
Commit: d1d6b56615ef701794c2b642ffb8a5b986f874e8
Is extension: false

**Comment by kjarosh** [comment]
Should be fixed as of the newest version
