### ISSUE TITLE
Error on https://g.vseigru.net/7/flash/igra-novyj-mir-super-mario-3/

### ISSUE THREAD

**Issue by DotsenkoRoman** [ruffle-rs/ruffle#7374]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:493:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:493:50
    at _0x5beea5.<computed>.<computed> (https://g.vseigru.net/lib/floader/index.min.js:1:92996)
    at std::sync::once::Once::call_once::{{closure}}::h8abebda14d1aaa35 (wasm://wasm/0162a83e:wasm-function[951]:0x2665ca)
    at std::sync::once::Once::call_inner::h96e3a490169c6c27 (wasm://wasm/0162a83e:wasm-function[1203]:0x2c3839)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::he4589c2a93c6a647 (wasm://wasm/0162a83e:wasm-function[4160]:0x455261)
    at std::panicking::rust_panic_with_hook::h2d9079427a2d996a (wasm://wasm/0162a83e:wasm-function[2986]:0x3e6c61)
    at rust_begin_unwind (wasm://wasm/0162a83e:wasm-function[4380]:0x45ae4c)
    at core::panicking::panic_fmt::h1fea623755fffed7 (wasm://wasm/0162a83e:wasm-function[4556]:0x46229e)
    at core::result::unwrap_failed::he87c4da48746e896 (wasm://wasm/0162a83e:wasm-function[3683]:0x441b82)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::hd9837a2beb71c16c (wasm://wasm/0162a83e:wasm-function[664]:0x1d70d0)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::register_glyph_shape::h0756eca7aacbd70f (wasm://wasm/0162a83e:wasm-function[2337]:0x39db0e)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://g.vseigru.net/7/flash/igra-novyj-mir-super-mario-3/
SWF URL: https://g.vseigru.net/7/flash/igra-novyj-mir-super-mario-3/novyj-super-mario-3.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-09-07
Channel: nightly
Built: 2021-09-07T00:13:42.794Z
Commit: b90436cffe3499acb42c5a41856002ddd1dc7024
Is extension: false

**Comment by Toad06** [comment]
Closing in favor of https://github.com/ruffle-rs/ruffle/issues/1905 (same issue). Thanks for reporting.
