### ISSUE TITLE
i got error report on similar to the fixed issue #7357 https://www.dailygames.com/games/run-dont-stop.html it works fine in a browser that supports flash

### ISSUE THREAD

**Issue by flashliberty5467** [ruffle-rs/ruffle#7378]
thank you to the devs for fixing #7357 it fixes the issues with that website but i find a simalar issue with https://www.dailygames.com/games/run-dont-stop.html

![ruffle flash 11 09 08 PM](https://user-images.githubusercontent.com/64484245/178091169-353e2af7-ed9e-49be-b6d5-8665d76f5ca0.png)

# Error Info
Error name: Error
Error message: Failed to fetch: https://www.dailygames.com/games/RunDontStop-AVENTURAS-W2A.swf?codigo=j9x9r52
Error stack:
```
Error: Failed to fetch: https://www.dailygames.com/games/RunDontStop-AVENTURAS-W2A.swf?codigo=j9x9r52
    at D.displayRootMovieDownloadFailedMessage (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/ruffle.js?id=11079114587:1:36061)
    at V.e.wbg.__wbg_displayRootMovieDownloadFailedMessage_1a5c34096259685a (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:1:6628)
    at <ruffle_web::ui::WebUiBackend as ruffle_core::backend::ui::UiBackend>::display_root_movie_download_failed_message::hb8759aa083ef5603 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/d5858fbd68915684114c.wasm:wasm-function[5640]:0x43ffd5)
    at <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h969b1fa076f8c705 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/d5858fbd68915684114c.wasm:wasm-function[555]:0x197cec)
    at <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hff435146d5130798 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/d5858fbd68915684114c.wasm:wasm-function[1920]:0x358583)
    at wasm_bindgen_futures::queue::Queue::new::{{closure}}::hb655bdde396642d8 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/d5858fbd68915684114c.wasm:wasm-function[2120]:0x37a11f)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hcc0ab244b5baa4b2 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/d5858fbd68915684114c.wasm:wasm-function[5213]:0x435a3d)
    at k (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:1:3012)
    at c (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:1:2435)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: https://www.dailygames.com/games/RunDontStop-AVENTURAS-W2A.swf?codigo=j9x9r52 
Param quality: high
Param allowScriptAccess: always
Param wmode: direct
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://www.dailygames.com/games/run-dont-stop.html
SWF URL: https://www.dailygames.com/games/RunDontStop-AVENTURAS-W2A.swf?codigo=j9x9r52

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14816.82.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-07-08
Channel: nightly
Built: 2022-07-08T00:14:25.918Z
Commit: 7fa35f2a82c94f805377d2e0c61f15b37ee5bc2a
Is extension: true

**Comment by n0samu** [comment]
This error occurs because of mixed content blocking in modern browsers. The main page requires HTTPS, as shown below...
```
curl -I http://www.dailygames.com/games/run-dont-stop.html
HTTP/1.1 301 Moved Permanently
Location: https://www.dailygames.com/games/run-dont-stop.html
```
Yet the SWF URL redirects to an HTTP location:
```
curl -I -L https://www.dailygames.com/games/RunDontStop-AVENTURAS-W2A.swf?codigo=5d39tiu
HTTP/1.1 301 Moved Permanently
Location: https://www.dailygames.com/includes/obtenerJuego.php?juego=RunDontStop-AVENTURAS-W2A.swf&codigo=5d39tiu

HTTP/1.1 302 Found
Location: http://swf1.juegosdiarios.com/11aa_3kujbcdyr/RunDontStop-AVENTURAS-W2A.swf
```
Browsers do not allow access to HTTP URLs from HTTPS pages, so this redirect fails, and Ruffle is unable to load the SWF file. And because the initial URL is HTTPS, Ruffle has no way of knowing this is going to happen and cannot prevent it.

You might wonder, as I did, if Ruffle could somehow detect a redirect to an HTTPS URL and upgrade it to HTTPS. Unfortunately, the Fetch API prevents this. A mixed content block is treated as a network error, which causes the promise to be rejected, and no information about the destination URL is provided in the error. The Fetch API provides a [redirect mode](https://fetch.spec.whatwg.org/#concept-request-redirect-mode) that can be set, but it only lets you choose to *never* receive information about the response, which is not helpful in the slightest.

Interestingly, the ancient XMLHttpRequest API does provide a way to get the destination URL of a failed redirect:
```
let origUrl = 'https://www.dailygames.com/games/RunDontStop-AVENTURAS-W2A.swf?codigo=5d39tiu'
let redirUrl = null;
let client = new XMLHttpRequest();
client.open("HEAD", url3, true);
client.send();
client.onreadystatechange = function() {
  redirUrl = client.getResponseHeader("Location");
}
```
redirURL will be set to `http://swf1.juegosdiarios.com/11aa_3kujbcdyr/RunDontStop-AVENTURAS-W2A.swf`, and Ruffle could upgrade the URL to HTTPS and fetch that instead.

But this is a lot of effort to make to fix a completely broken site! We should note that this site doesn't even work in more modern browsers that support Flash, such as Firefox ESR 78.

Another option is to modify the logic that triggers the below screen to account for this case:
![image](https://user-images.githubusercontent.com/71368227/178121321-fdfda103-e85e-4f7b-8ba9-cf286f82b0f7.png)
That would probably mean passing the HTTP status code as an argument to the `display_root_movie_download_failed_message` function, which could display that screen unless we know the server returned an error (4xx or 5xx). If `window.location.origin` = `swfUrl.origin`, we can count on receiving some reply from the server.

**Comment by aeivin3085-cloud** [comment]
<img width="1103" height="621" alt="Image" src="https://github.com/user-attachments/assets/1113513d-f6ab-4fa9-bbc5-08aa3b0c89ee" />
