### ISSUE TITLE
Error on https://games.crazygames.com/pt_BR/the-visitor/index.html

### ISSUE THREAD

**Issue by marcinholsp** [ruffle-rs/ruffle#7383]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: JsValue(InvalidStateError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
Error: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
    at https://files.crazygames.com/gameframe/ruffle/2022-05-17/core.ruffle.1d691580347605e7089e.js:1:28694
    at L (https://files.crazygames.com/gameframe/ruffle/2022-05-17/core.ruffle.1d691580347605e7089e.js:1:3908)
    at c.wbg.__wbg_drawImage_5d4f6b1d51d3b118 (https://files.crazygames.com/gameframe/ruffle/2022-05-17/core.ruffle.1d691580347605e7089e.js:1:28668)
    at web_sys::features::gen_CanvasRenderingContext2d::CanvasRenderingContext2d::draw_image_with_html_canvas_element::h5e2725942e7ddfb4 (https://files.crazygames.com/gameframe/ruffle/2022-05-17/3ca577b52db5bd6a3fb0.wasm:wasm-function[4837]:0x460eff)
    at <ruffle_render_canvas::WebCanvasRenderBackend as ruffle_core::backend::render::RenderBackend>::pop_mask::hba249197f1762bfd (https://files.crazygames.com/gameframe/ruffle/2022-05-17/3ca577b52db5bd6a3fb0.wasm:wasm-function[879]:0x26cfe5)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render_self::h1aad3f91d0689244 (https://files.crazygames.com/gameframe/ruffle/2022-05-17/3ca577b52db5bd6a3fb0.wasm:wasm-function[2521]:0x3c452c)
    at ruffle_core::display_object::render_base::hb5777752d91a9e42 (https://files.crazygames.com/gameframe/ruffle/2022-05-17/3ca577b52db5bd6a3fb0.wasm:wasm-function[1498]:0x31d19e)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render::ha368a8714e00e779 (https://files.crazygames.com/gameframe/ruffle/2022-05-17/3ca577b52db5bd6a3fb0.wasm:wasm-function[3822]:0x43b159)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render_self::h1aad3f91d0689244 (https://files.crazygames.com/gameframe/ruffle/2022-05-17/3ca577b52db5bd6a3fb0.wasm:wasm-function[2521]:0x3c43c9)
    at ruffle_core::display_object::render_base::hb5777752d91a9e42 (https://files.crazygames.com/gameframe/ruffle/2022-05-17/3ca577b52db5bd6a3fb0.wasm:wasm-function[1498]:0x31d19e)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render::ha368a8714e00e779 (https://files.crazygames.com/gameframe/ruffle/2022-05-17/3ca577b52db5bd6a3fb0.wasm:wasm-function[3822]:0x43b159)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render_self::h1aad3f91d0689244 (https://files.crazygames.com/gameframe/ruffle/2022-05-17/3ca577b52db5bd6a3fb0.wasm:wasm-function[2521]:0x3c22a9)
    at ruffle_core::display_object::render_base::hb5777752d91a9e42 (https://files.crazygames.com/gameframe/ruffle/2022-05-17/3ca577b52db5bd6a3fb0.wasm:wasm-function[1498]:0x31d19e)
    at <ruffle_core::display_object::stage::Stage as ruffle_core::display_object::TDisplayObject>::render::haac91e4f4fffccc1 (https://files.crazygames.com/gameframe/ruffle/2022-05-17/3ca577b52db5bd6a3fb0.wasm:wasm-function[1233]:0x2defe0)
    at ruffle_web::Ruffle::tick::h72c32e382ff7c3dc (https://files.crazygames.com/gameframe/ruffle/2022-05-17/3ca577b52db5bd6a3fb0.wasm:wasm-function[535]:0x1a4652)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h83f84c4202dfeef8 (https://files.crazygames.com/gameframe/ruffle/2022-05-17/3ca577b52db5bd6a3fb0.wasm:wasm-function[5792]:0x47ca5a)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h9b5cf45bc3df0eb9 (https://files.crazygames.com/gameframe/ruffle/2022-05-17/3ca577b52db5bd6a3fb0.wasm:wasm-function[5361]:0x471822)
    at F (https://files.crazygames.com/gameframe/ruffle/2022-05-17/core.ruffle.1d691580347605e7089e.js:1:3282)
    at c (https://files.crazygames.com/gameframe/ruffle/2022-05-17/core.ruffle.1d691580347605e7089e.js:1:2392)
    at r (https://gameframe.crazygames.com/crazygames-gameframe-v1.bundle.js:2:306334))', render/canvas/src/lib.rs:832:14

# Player Info
Allows script access: false

# Page Info
Page URL: https://games.crazygames.com/pt_BR/the-visitor/index.html

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-05-17
Channel: nightly
Built: 2022-05-17T00:16:53.792Z
Commit: ede81be4279e0af289ebc5057ebcdb12d5f99a38
Is extension: false

**Comment by relrelb** [comment]
Fixed by #9358.
