### ISSUE TITLE
Error on https://f.kbhgames.com/RS/game.php

### ISSUE THREAD

**Issue by shreyvalia1** [ruffle-rs/ruffle#7408]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:500:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:500:50
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (https://f.kbhgames.com/RS/asset/core.ruffle.4eb0604eba48fe4cbd7c.js:1:7024)
    at std::sync::once::Once::call_once::{{closure}}::hfcef47ecdbff91ce (wasm://wasm/01648fd6:wasm-function[1207]:0x2b2c48)
    at std::sync::once::Once::call_inner::h8a142b2dcc139875 (wasm://wasm/01648fd6:wasm-function[1413]:0x2ec791)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hdb9fff54a76be75f (wasm://wasm/01648fd6:wasm-function[4754]:0x43bb43)
    at std::panicking::rust_panic_with_hook::he2a025723e105e28 (wasm://wasm/01648fd6:wasm-function[3189]:0x3e27ef)
    at core::panicking::panic_fmt::hb02133958c1e7d35 (wasm://wasm/01648fd6:wasm-function[4937]:0x441a43)
    at core::result::unwrap_failed::h68fdaca771c68bb6 (wasm://wasm/01648fd6:wasm-function[4082]:0x426562)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::h021ffbd5edff797a (wasm://wasm/01648fd6:wasm-function[712]:0x2033c6)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::register_shape::h1e2b81005d1d773e (wasm://wasm/01648fd6:wasm-function[3218]:0x3e4724)
    at ruffle_core::drawing::Drawing::render::h5a06073bb06603c5 (wasm://wasm/01648fd6:wasm-function[637]:0x1df8f1)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://f.kbhgames.com/RS/game.php?r=//f.kbhgames.com/2018/swf/nninjagame.swf&w=750&h=545
SWF URL: https://f.kbhgames.com/2018/swf/nninjagame.swf

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-05-20
Channel: nightly
Built: 2022-05-20T00:13:55.393Z
Commit: c503f78e13d9a595be0e315b18ce27267cdf94fc
Is extension: false

**Comment by kjarosh** [comment]
Should be fixed as of the newest version
