### ISSUE TITLE
Error on https://www.oyunkuzusu.com/gladyator-2-oyna.html

### ISSUE THREAD

**Issue by Federal2** [ruffle-rs/ruffle#7416]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: JsValue(InvalidStateError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
Error: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
    at https://www.oyunkuzusu.com/ruffle.js:1:29390
    at T (https://www.oyunkuzusu.com/ruffle.js:1:4047)
    at c.wbg.__wbg_drawImage_9492b361f8b31282 (https://www.oyunkuzusu.com/ruffle.js:1:29364)
    at web_sys::features::gen_CanvasRenderingContext2d::CanvasRenderingContext2d::draw_image_with_html_canvas_element::he80ac8642eeb482b (https://www.oyunkuzusu.com/86c8cc086d5464b4c06b.wasm:wasm-function[4597]:0x4f1ce3)
    at <ruffle_render_canvas::WebCanvasRenderBackend as ruffle_core::backend::render::RenderBackend>::pop_mask::h7a171b2169aa7ef7 (https://www.oyunkuzusu.com/86c8cc086d5464b4c06b.wasm:wasm-function[1026]:0x2fdf08)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render_self::h9fb2a252e3dd81a5 (https://www.oyunkuzusu.com/86c8cc086d5464b4c06b.wasm:wasm-function[3276]:0x4a17d1)
    at ruffle_core::display_object::render_base::h0abef15dbe1dca73 (https://www.oyunkuzusu.com/86c8cc086d5464b4c06b.wasm:wasm-function[1594]:0x3ab22b)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render::h278a6e48beefbb2f (https://www.oyunkuzusu.com/86c8cc086d5464b4c06b.wasm:wasm-function[3768]:0x4cbc99)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render_self::h9fb2a252e3dd81a5 (https://www.oyunkuzusu.com/86c8cc086d5464b4c06b.wasm:wasm-function[3276]:0x4a200c)
    at ruffle_core::display_object::render_base::h0abef15dbe1dca73 (https://www.oyunkuzusu.com/86c8cc086d5464b4c06b.wasm:wasm-function[1594]:0x3ab22b))', render/canvas/src/lib.rs:691:14
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: JsValue(InvalidStateError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
Error: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
    at https://www.oyunkuzusu.com/ruffle.js:1:29390
    at T (https://www.oyunkuzusu.com/ruffle.js:1:4047)
    at c.wbg.__wbg_drawImage_9492b361f8b31282 (https://www.oyunkuzusu.com/ruffle.js:1:29364)
    at web_sys::features::gen_CanvasRenderingContext2d::CanvasRenderingContext2d::draw_image_with_html_canvas_element::he80ac8642eeb482b (https://www.oyunkuzusu.com/86c8cc086d5464b4c06b.wasm:wasm-function[4597]:0x4f1ce3)
    at <ruffle_render_canvas::WebCanvasRenderBackend as ruffle_core::backend::render::RenderBackend>::pop_mask::h7a171b2169aa7ef7 (https://www.oyunkuzusu.com/86c8cc086d5464b4c06b.wasm:wasm-function[1026]:0x2fdf08)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render_self::h9fb2a252e3dd81a5 (https://www.oyunkuzusu.com/86c8cc086d5464b4c06b.wasm:wasm-function[3276]:0x4a17d1)
    at ruffle_core::display_object::render_base::h0abef15dbe1dca73 (https://www.oyunkuzusu.com/86c8cc086d5464b4c06b.wasm:wasm-function[1594]:0x3ab22b)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render::h278a6e48beefbb2f (https://www.oyunkuzusu.com/86c8cc086d5464b4c06b.wasm:wasm-function[3768]:0x4cbc99)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render_self::h9fb2a252e3dd81a5 (https://www.oyunkuzusu.com/86c8cc086d5464b4c06b.wasm:wasm-function[3276]:0x4a200c)
    at ruffle_core::display_object::render_base::h0abef15dbe1dca73 (https://www.oyunkuzusu.com/86c8cc086d5464b4c06b.wasm:wasm-function[1594]:0x3ab22b))', render/canvas/src/lib.rs:691:14
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (https://www.oyunkuzusu.com/ruffle.js:1:7036)
    at std::sync::once::Once::call_once::{{closure}}::h5387044f596cf17b (https://www.oyunkuzusu.com/86c8cc086d5464b4c06b.wasm:wasm-function[996]:0x2e8fae)
    at std::sync::once::Once::call_inner::h02a6489b0ecfb269 (https://www.oyunkuzusu.com/86c8cc086d5464b4c06b.wasm:wasm-function[1317]:0x356eec)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h4461033b8c8249d8 (https://www.oyunkuzusu.com/86c8cc086d5464b4c06b.wasm:wasm-function[4669]:0x4f3798)
    at std::panicking::rust_panic_with_hook::h364974e717ed59ec (https://www.oyunkuzusu.com/86c8cc086d5464b4c06b.wasm:wasm-function[3289]:0x4a355e)
    at rust_begin_unwind (https://www.oyunkuzusu.com/86c8cc086d5464b4c06b.wasm:wasm-function[4731]:0x4f5c84)
    at core::panicking::panic_fmt::hf69c8b08bc9d2ee5 (https://www.oyunkuzusu.com/86c8cc086d5464b4c06b.wasm:wasm-function[4942]:0x50099d)
    at core::result::unwrap_failed::h694db13a45aa6740 (https://www.oyunkuzusu.com/86c8cc086d5464b4c06b.wasm:wasm-function[3994]:0x4dbcab)
    at <ruffle_render_canvas::WebCanvasRenderBackend as ruffle_core::backend::render::RenderBackend>::pop_mask::h7a171b2169aa7ef7 (https://www.oyunkuzusu.com/86c8cc086d5464b4c06b.wasm:wasm-function[1026]:0x2fe09e)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render_self::h9fb2a252e3dd81a5 (https://www.oyunkuzusu.com/86c8cc086d5464b4c06b.wasm:wasm-function[3276]:0x4a17d1)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.oyunkuzusu.com/gladyator-2-oyna.html
SWF URL: https://www.oyunkuzusu.com/oyunlar/gladyator_2_secure.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-11-11
Channel: nightly
Built: 2021-11-11T00:14:36.131Z
Commit: 60eb88b3265601d16467672a732081b30884707d
Is extension: false

**Comment by relrelb** [comment]
Fixed by #9358.
