### ISSUE TITLE
Error loading swf

### ISSUE THREAD

**Issue by BallsInteractive** [ruffle-rs/ruffle#7431]
Hello,
currently I am having an issue with the Ruffle script from here:
https://unpkg.com/@ruffle-rs/ruffle
Here's the output:
# Error Info
Error name: Error
Error message: Failed to fetch: https://archive.org/download/alephdneocities/Main.swf
Error stack:
```
Error: Failed to fetch: https://archive.org/download/alephdneocities/Main.swf
    at L.displayRootMovieDownloadFailedMessage (https://unpkg.com/@ruffle-rs/ruffle:1:36136)
    at V.e.wbg.__wbg_displayRootMovieDownloadFailedMessage_1a5c34096259685a (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.d740f882ead6b6d20ad6.js:1:6630)
    at <ruffle_web::ui::WebUiBackend as ruffle_core::backend::ui::UiBackend>::display_root_movie_download_failed_message::hfc18b66903acf08e (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/394b4474abb608bf906e.wasm:wasm-function[5655]:0x447581)
    at <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h7a536f5bfd21c4d1 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/394b4474abb608bf906e.wasm:wasm-function[570]:0x1a909d)
    at <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hcd21e9627d065cbc (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/394b4474abb608bf906e.wasm:wasm-function[1925]:0x35cc49)
    at wasm_bindgen_futures::queue::Queue::new::{{closure}}::h252dae8c7768768d (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/394b4474abb608bf906e.wasm:wasm-function[2129]:0x380a94)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h96ab439b5823ee8f (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/394b4474abb608bf906e.wasm:wasm-function[5228]:0x43ca43)
    at k (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.d740f882ead6b6d20ad6.js:1:3014)
    at c (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.d740f882ead6b6d20ad6.js:1:2437)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://alephd.neocities.org/
SWF URL: https://archive.org/download/alephdneocities/Main.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-07-16
Channel: nightly
Built: 2022-07-16T00:17:41.463Z
Commit: cad3cd8dbfbf13e2d09688434f09aba0bce46e78
Is extension: false

Here's the website I am using it on:
https://alephd.neocities.org/

**Comment by n0samu** [comment]
Because of CORS policies, you generally cannot load files originating from other sites on your own site. This is a limitation of the modern web that Ruffle cannot do anything about. You can learn more about CORS here: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
If you need further help, feel free to make a topic on the Discussion tab or join our Discord server.
