### ISSUE TITLE
Error on https://www.minijuegos.com/helpers/game/sandbox.php

### ISSUE THREAD

**Issue by conino99** [ruffle-rs/ruffle#7479]
# Error Info
Error name: Error
Error message: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:576:14
Error stack:
```
Error: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:576:14
    at V.e.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:1:6063)
    at std::sync::once::Once::call_once::{{closure}}::h96c2b4473ff6d536 (wasm://wasm/0160c3f6:wasm-function[1205]:0x2b1618)
    at std::sync::once::Once::call_inner::h1c414562e2619117 (wasm://wasm/0160c3f6:wasm-function[1377]:0x2e6810)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h14edbfd8adf99b9a (wasm://wasm/0160c3f6:wasm-function[4677]:0x42b6f9)
    at std::panicking::rust_panic_with_hook::h1c368a27f9b0afe1 (wasm://wasm/0160c3f6:wasm-function[3067]:0x3dc417)
    at core::panicking::panic_fmt::hcdb13a4b2416cf82 (wasm://wasm/0160c3f6:wasm-function[4859]:0x43180f)
    at core::option::expect_failed::h9f179d8645f7b768 (wasm://wasm/0160c3f6:wasm-function[5470]:0x43eab0)
    at ruffle_core::display_object::stage::Stage::root_clip::ha5c2687f2091a1a5 (wasm://wasm/0160c3f6:wasm-function[3394]:0x3f24de)
    at ruffle_web::Ruffle::tick::h80b89f3b236277b4 (wasm://wasm/0160c3f6:wasm-function[609]:0x1bfbae)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h62d65489931f7892 (wasm://wasm/0160c3f6:wasm-function[5647]:0x446adf)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: https://www.minijuegosgratis.com/flash1234/no_hotlink/cutefarmhospital.swf
Param quality: high
Param allowscriptaccess: always
Param allowfullscreen: false
Param wmode: direct
Param flashvars: mp_log_level=4&mp_game_id=24101&mp_game_url=https%3A%2F%2Fwww.minijuegos.com%2Fembed%2Fcute-farm-hospital&mp_site_name=minijuegos.com&mp_site_url=https%3A%2F%2Fwww.minijuegos.com%2F&mp_api_id=&mp_api_as3_url=&mp_api_as3_url_bck=&mp_api_user_id=&mp_api_user_token=&mp_locale=es_ES&mp_timezone=America%2FSantiago&mp_embed=false&mp_base_path=https%3A%2F%2Fwww.minijuegosgratis.com%2Fflash1234%2Fno_hotlink%2F
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined
Attribute 6: undefined

# Page Info
Page URL: https://www.minijuegos.com/helpers/game/sandbox.php?mp_assets=https%3A%2F%2Fs2.minijuegosgratis.com%2F&mp_embed=0&mp_game_id=24101&mp_game_uid=cute-farm-hospital&mp_game_url=https%3A%2F%2Fwww.minijuegos.com%2Fembed%2Fcute-farm-hospital&mp_int=1&mp_locale=es_ES&mp_player_type=FLASH&mp_player_url=aHR0cHM6Ly93d3cubWluaWp1ZWdvc2dyYXRpcy5jb20vZmxhc2gxMjM0L25vX2hvdGxpbmsvY3V0ZWZhcm1ob3NwaXRhbC5zd2Y%3D&mp_site_https_url=https%3A%2F%2Fwww.minijuegos.com%2F&mp_site_name=minijuegos.com&mp_site_url=https%3A%2F%2Fwww.minijuegos.com%2F&mp_timezone=America%2FSantiago&mp_view_type=
SWF URL: https://www.minijuegosgratis.com/flash1234/no_hotlink/cutefarmhospital.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.114 Safari/537.36
Platform: Win32
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-07-25
Channel: nightly
Built: 2022-07-25T00:17:23.429Z
Commit: afb9ecc4ab8a6f6b9b295ddcb029a4ca80230a9e
Is extension: true

**Comment by Lord-McSweeney** [comment]
Needs `GetDescendants` after #10026.

**Comment by Lord-McSweeney** [comment]
Gets stuck at 25% loaded now, no errors.
