### ISSUE TITLE
Error on http://list.lshitv.com/zhibo/gangaotai/fenghuangxianggang.html

### ISSUE THREAD

**Issue by kapamay** [ruffle-rs/ruffle#7489]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Cannot access property com.demonsters.debugger:IMonsterDebuggerConnection::connected of null or undefined"', core/src/timer.rs:115:26
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Cannot access property com.demonsters.debugger:IMonsterDebuggerConnection::connected of null or undefined"', core/src/timer.rs:115:26
    at V.e.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:1:6063)
    at std::sync::once::Once::call_once::{{closure}}::h5fd96c2e051bcaea (wasm://wasm/015fd002:wasm-function[1203]:0x2af7b5)
    at std::sync::once::Once::call_inner::h1c414562e2619117 (wasm://wasm/015fd002:wasm-function[1380]:0x2e6df6)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h37057bbdf9b38d3b (wasm://wasm/015fd002:wasm-function[4679]:0x429983)
    at std::panicking::rust_panic_with_hook::h1c368a27f9b0afe1 (wasm://wasm/015fd002:wasm-function[3070]:0x3db257)
    at core::panicking::panic_fmt::hcdb13a4b2416cf82 (wasm://wasm/015fd002:wasm-function[4862]:0x42fad9)
    at core::result::unwrap_failed::he825aa6f43b16604 (wasm://wasm/015fd002:wasm-function[4006]:0x414a86)
    at ruffle_web::Ruffle::tick::h80b50c1388bb570b (wasm://wasm/015fd002:wasm-function[605]:0x1be7f0)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h003f4238e6e75a30 (wasm://wasm/015fd002:wasm-function[5648]:0x444ece)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h0b6a561d0c890fb1 (wasm://wasm/015fd002:wasm-function[5209]:0x43a1d1)
```

# Player Info
Allows script access: false

# Page Info
Page URL: http://list.lshitv.com/zhibo/gangaotai/fenghuangxianggang.html
SWF URL: http://g.alicdn.com/de/prismplayer-flash/1.2.16/PrismPlayer.swf?vurl=rtmp://58.200.131.2:1935/livetv/fhzw&autoPlay=true

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-07-26
Channel: nightly
Built: 2022-07-26T00:15:49.797Z
Commit: df07f610e7f7950e2a3d772553cbcc59b70c2d74
Is extension: true

**Comment by Lord-McSweeney** [comment]
This no longer panics
