### ISSUE TITLE
Panic clicking links in desktop

### ISSUE THREAD

**Issue by Dinnerbone** [ruffle-rs/ruffle#757]
I ran a bisect and it was caused by ba43b3d50b5f537755c1af304ec65d0061ea1c4d - updating winit from 0.22.1 to 0.22.2

To reproduce, click the Armor Games logo in Achievement Unlocked - though it seems to happen with any clickable link.

I'm running Windows, and have not tested OSX or Linux.

```
thread 'main' panicked at 'either event handler is re-entrant (likely), or no event handler is registered (very unlikely)', C:\Users\dinne\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop\runner.rs:235:37
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.46\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print_fmt
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\sys_common\backtrace.rs:78
   2: std::sys_common::backtrace::_print::{{impl}}::fmt
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\sys_common\backtrace.rs:59
   3: core::fmt::write
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libcore\fmt\mod.rs:1069
   4: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\io\mod.rs:1504
   5: std::sys_common::backtrace::_print
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\sys_common\backtrace.rs:62
   6: std::sys_common::backtrace::print
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\sys_common\backtrace.rs:49
   7: std::panicking::default_hook::{{closure}}
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\panicking.rs:198
   8: std::panicking::default_hook
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\panicking.rs:218
   9: std::panicking::rust_panic_with_hook
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\panicking.rs:511
  10: std::panicking::begin_panic_handler
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\panicking.rs:419
  11: core::panicking::panic_fmt
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libcore\panicking.rs:111
  12: core::option::expect_failed
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libcore\option.rs:1260
  13: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  14: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<T>::call_event_handler
  15: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<T>::move_state_to
  16: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  17: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<T>::catch_unwind
  18: winit::platform_impl::platform::event_loop::EventLoopThreadExecutor::execute_in_thread
  19: DefSubclassProc
  20: DefSubclassProc
  21: CallWindowProcW
  22: DispatchMessageW
  23: IsWindowVisible
  24: KiUserCallbackDispatcher
  25: NtUserDispatchMessage
  26: DispatchMessageW
  27: SignalFileOpen
  28: SHELL32_GetIconOverlayManager
  29: Ordinal99
  30: ShellExecuteExW
  31: ShellExecuteExW
  32: ShellExecuteW
  33: webbrowser::open_browser
  34: webbrowser::open
  35: <ruffle_desktop::navigator::ExternalNavigatorBackend as ruffle_core::backend::navigator::NavigatorBackend>::navigate_to_url
  36: ruffle_core::avm1::Avm1::run_current_frame
  37: ruffle_core::avm1::Avm1::run_stack_till_empty
  38: ruffle_core::player::Player::run_actions
  39: ruffle_core::player::Player::handle_event
  40: <alloc::raw_vec::RawVec<T,A> as core::ops::drop::Drop>::drop
  41: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  42: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<T>::call_event_handler
  43: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<T>::send_event
  44: winit::platform_impl::platform::event_loop::public_window_callback::{{closure}}
  45: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<T>::catch_unwind
  46: winit::platform_impl::platform::event_loop::public_window_callback
  47: DefSubclassProc
  48: DefSubclassProc
  49: CallWindowProcW
  50: CallWindowProcW
  51: glPushClientAttrib
  52: CallWindowProcW
  53: DispatchMessageW
  54: winit::platform_impl::platform::event_loop::subclass_window
  55: winit::platform_impl::platform::event_loop::EventLoop<T>::new
  56: core::ptr::drop_in_place
  57: <std::collections::hash::map::DefaultHasher as core::hash::Hasher>::write
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

Process finished with exit code -1

```

**Comment by Herschel** [comment]
Seems to be https://github.com/rust-windowing/winit/issues/1602 and/or https://github.com/rust-windowing/winit/issues/1587. Could maybe downgrade to 21.0.

**Comment by Herschel** [comment]
This seems to be fixed in the latest winit master.
