### ISSUE TITLE
Error on https://anime-chan.me/4423-poigrayte-s-geroyami-hitalii.html

### ISSUE THREAD

**Issue by marrrr32** [ruffle-rs/ruffle#7589]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:493:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:493:50
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (https://anime-chan.me/ruffle/ruffle.js:1:7576)
    at std::sync::once::Once::call_once::{{closure}}::hdc00d7da63128799 (wasm://wasm/015803c6:wasm-function[916]:0x24529f)
    at std::sync::once::Once::call_inner::h96e3a490169c6c27 (wasm://wasm/015803c6:wasm-function[1171]:0x2a2cd1)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h34a21969c4579926 (wasm://wasm/015803c6:wasm-function[4040]:0x42fb92)
    at std::panicking::rust_panic_with_hook::h2d9079427a2d996a (wasm://wasm/015803c6:wasm-function[2906]:0x3c434e)
    at rust_begin_unwind (wasm://wasm/015803c6:wasm-function[4254]:0x43587c)
    at core::panicking::panic_fmt::h1fea623755fffed7 (wasm://wasm/015803c6:wasm-function[4410]:0x43c602)
    at core::result::unwrap_failed::he87c4da48746e896 (wasm://wasm/015803c6:wasm-function[3580]:0x41cc47)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::h9a356dad0f67686a (wasm://wasm/015803c6:wasm-function[644]:0x1bc263)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::register_glyph_shape::hfaefd5f8a84ed573 (wasm://wasm/015803c6:wasm-function[2279]:0x375081)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://anime-chan.me/4423-poigrayte-s-geroyami-hitalii.html
SWF URL: https://anime-chan.me/uploads/files/1330381745_interactive_russia_flash_game_by_namioki-d4bt5y2.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.148 YaBrowser/22.7.2.899 Yowser/2.5 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-08-29
Channel: nightly
Built: 2021-08-29T00:13:47.345Z
Commit: 3982f3af9811cfc32c6f7eaf06aa3c8c81b91226
Is extension: false

**Comment by n0samu** [comment]
I think this error is likely related to the very large number of Ruffle embeds on the page, which could go over the browser's limit for simultaneous WebGL contexts. Not really sure though.

**Comment by kjarosh** [comment]
Should be fixed as of the newest version
