### ISSUE TITLE
Ruffle Error on https://freeasteroids.org/

### ISSUE THREAD

**Issue by Debco99** [ruffle-rs/ruffle#7614]
# Error Info
Error name: ReferenceError
Error message: WebAssembly is not defined
Error stack:
```
ReferenceError: WebAssembly is not defined
    at https://turbo.freevideogamesonline.org/includes/js/flash-emulator/ruffle.js:1:67324
    at Array.forEach (<anonymous>)
    at vi.f.wasm (https://turbo.freevideogamesonline.org/includes/js/flash-emulator/ruffle.js:1:66977)
    at https://turbo.freevideogamesonline.org/includes/js/flash-emulator/ruffle.js:1:35299
    at Array.reduce (<anonymous>)
    at vi.e (https://turbo.freevideogamesonline.org/includes/js/flash-emulator/ruffle.js:1:35276)
    at o (https://turbo.freevideogamesonline.org/includes/js/flash-emulator/ruffle.js:1:2595)
    at o.next (<anonymous>)
    at https://turbo.freevideogamesonline.org/includes/js/flash-emulator/ruffle.js:1:2895
    at new Promise (<anonymous>)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://freeasteroids.org/

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.81 Safari/537.36 Edg/104.0.1293.47
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2020-12-31
Channel: nightly
Built: 2020-12-31T00:48:27.350Z
Commit: ea3b6f59dfd7c528f2ae305c4dba2d351ada9302

**Comment by n0samu** [comment]
This problem is caused by Microsoft Edge's "Enhance your security on the web" feature. [See the FAQ for a solution to the problem](https://github.com/ruffle-rs/ruffle/wiki/Frequently-Asked-Questions-For-Users#edge-webassembly-error).
