### ISSUE TITLE
Error on https://www.gamezhero.com/get-game-code/2b296ab4f2db709cc20056f93c4b04ee

### ISSUE THREAD

**Issue by leosimon123** [ruffle-rs/ruffle#7654]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm2/object.rs:308:48
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm2/object.rs:308:48
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (https://www.gamezhero.com/js/min/libs/ruffle/core.ruffle.7ec7db74324868608218.js:1:7024)
    at std::sync::once::Once::call_once::{{closure}}::h2027a447bec228ec (https://www.gamezhero.com/js/min/libs/ruffle/ca8b3755b083d344eb84.wasm:wasm-function[1184]:0x2aee95)
    at std::sync::once::Once::call_inner::h8a142b2dcc139875 (https://www.gamezhero.com/js/min/libs/ruffle/ca8b3755b083d344eb84.wasm:wasm-function[1406]:0x2e9ee3)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hd3865d0bba70fdf0 (https://www.gamezhero.com/js/min/libs/ruffle/ca8b3755b083d344eb84.wasm:wasm-function[4744]:0x439225)
    at std::panicking::rust_panic_with_hook::he2a025723e105e28 (https://www.gamezhero.com/js/min/libs/ruffle/ca8b3755b083d344eb84.wasm:wasm-function[3143]:0x3de187)
    at core::panicking::panic_fmt::hb02133958c1e7d35 (https://www.gamezhero.com/js/min/libs/ruffle/ca8b3755b083d344eb84.wasm:wasm-function[4926]:0x43f286)
    at core::panicking::panic::hc28e7cc2aa792341 (https://www.gamezhero.com/js/min/libs/ruffle/ca8b3755b083d344eb84.wasm:wasm-function[4837]:0x43b27f)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::hc8221bbdd1706a15 (https://www.gamezhero.com/js/min/libs/ruffle/ca8b3755b083d344eb84.wasm:wasm-function[471]:0x152121)
    at ruffle_core::avm2::activation::Activation::run_actions::hf71eb191842b5e68 (https://www.gamezhero.com/js/min/libs/ruffle/ca8b3755b083d344eb84.wasm:wasm-function[315]:0xa4b8)
    at ruffle_core::avm2::script::Script::globals::hdf2a18cb2bab2153 (https://www.gamezhero.com/js/min/libs/ruffle/ca8b3755b083d344eb84.wasm:wasm-function[1211]:0x2b766a)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.gamezhero.com/get-game-code/2b296ab4f2db709cc20056f93c4b04ee
SWF URL: https://files.gamezhero.com/game/580/3af/5803afd4823ce464/data/LEGCAL.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-06-05
Channel: nightly
Built: 2022-06-05T00:19:04.302Z
Commit: 9e4d13f201634b5d24e2cc9a40c78fc9306eb3c3
Is extension: false

**Comment by kjarosh** [comment]
Should be fixed as of today—the related code has been heavily rewritten.
