### ISSUE TITLE
Ruffle Error on https://freetennis.org/

### ISSUE THREAD

**Issue by Porkpigiscool** [ruffle-rs/ruffle#7690]
# Error Info
Error name: ReferenceError
Error message: WebAssembly is not defined
Error stack:
```
ReferenceError: WebAssembly is not defined
    at https://turbo.freevideogamesonline.org/includes/js/flash-emulator/ruffle.js:1:67324
    at Array.forEach (<anonymous>)
    at vi.f.wasm (https://turbo.freevideogamesonline.org/includes/js/flash-emulator/ruffle.js:1:66977)
    at https://turbo.freevideogamesonline.org/includes/js/flash-emulator/ruffle.js:1:35299
    at Array.reduce (<anonymous>)
    at vi.e (https://turbo.freevideogamesonline.org/includes/js/flash-emulator/ruffle.js:1:35276)
    at o (https://turbo.freevideogamesonline.org/includes/js/flash-emulator/ruffle.js:1:2595)
    at o.next (<anonymous>)
    at https://turbo.freevideogamesonline.org/includes/js/flash-emulator/ruffle.js:1:2895
    at new Promise (<anonymous>)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://freetennis.org/

# Browser Info
Useragent: Mozilla/5.0 (X11; CrOS x86_64 14695.107.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2020-12-31
Channel: nightly
Built: 2020-12-31T00:48:27.350Z
Commit: ea3b6f59dfd7c528f2ae305c4dba2d351ada9302

**Comment by n0samu** [comment]
This error is not related to the Ruffle version. It may be related to interference from a browser extension or script on the webpage, but it is very difficult to know for sure. Another possibility is WebAssembly being manually disabled via the browser's settings.

**Comment by Croworbit** [comment]
This website uses a version of ruffle from 2020, thats 4 years out of date!

they broke CORS, and they need to update their site and Ruffle. let them know!
