### ISSUE TITLE
Error on https://www.ticketshow.com.ec/rps/synopsism.aspx

### ISSUE THREAD

**Issue by ernestoliberio** [ruffle-rs/ruffle#7743]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: JsValue(InvalidStateError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
Error: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
    at https://www.ticketshow.com.ec/js/ruffle/ruffle.js:1:26863
    at https://www.ticketshow.com.ec/js/ruffle/ruffle.js:1:4463
    at web_sys::features::gen_CanvasRenderingContext2d::CanvasRenderingContext2d::draw_image_with_html_canvas_element::hb27bb4b4b66ddc9d (https://www.ticketshow.com.ec/js/ruffle/ed8fb1278950d8015875.wasm:wasm-function[3947]:0x421971)
    at <ruffle_render_canvas::WebCanvasRenderBackend as ruffle_core::backend::render::RenderBackend>::pop_mask::hd465240d127d8403 (https://www.ticketshow.com.ec/js/ruffle/ed8fb1278950d8015875.wasm:wasm-function[858]:0x2527ea)
    at ruffle_core::display_object::render_base::h6769e03bc30d4015 (https://www.ticketshow.com.ec/js/ruffle/ed8fb1278950d8015875.wasm:wasm-function[1584]:0x310028)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render::hf6a00150f4152096 (https://www.ticketshow.com.ec/js/ruffle/ed8fb1278950d8015875.wasm:wasm-function[3232]:0x3dfc70)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render_self::h5ab774dcc7be3abf (https://www.ticketshow.com.ec/js/ruffle/ed8fb1278950d8015875.wasm:wasm-function[2251]:0x37e46b)
    at ruffle_core::display_object::render_base::h6769e03bc30d4015 (https://www.ticketshow.com.ec/js/ruffle/ed8fb1278950d8015875.wasm:wasm-function[1584]:0x310035)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render::hf6a00150f4152096 (https://www.ticketshow.com.ec/js/ruffle/ed8fb1278950d8015875.wasm:wasm-function[3232]:0x3dfc70)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render_self::h5ab774dcc7be3abf (https://www.ticketshow.com.ec/js/ruffle/ed8fb1278950d8015875.wasm:wasm-function[2251]:0x37e46b))', render/canvas/src/lib.rs:692:14

# Player Info
Allows script access: true

# Page Info
Page URL: https://www.ticketshow.com.ec/rps/synopsism.aspx?evento=7763
SWF URL: https://www.ticketshow.com.ec/rps/Swf/PuntoVenta/locationconCargaLoader.swf

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-06-21
Channel: nightly
Built: 2021-06-21T00:13:14.876Z
Commit: 56c260fa7478538da685545c9f5c9e736cde6cb3

**Comment by crsov** [comment]
Your ruffle version is very old, please try on latest version.

**Comment by n0samu** [comment]
Closing in favor of #9358
