### ISSUE TITLE
Error on https://homestarrunner.com/dman3

### ISSUE THREAD

**Issue by mickeymox** [ruffle-rs/ruffle#7748]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:507:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:507:50
    at V.e.wbg.__wbg_new_df6e6ab7a65c4c4d (https://homestarrunner.com/assets/js/core.ruffle.cf4f7ec804fb9cda28d8.js:1:7361)
    at std::sync::once::Once::call_once::{{closure}}::h681ef9b1238d7996 (wasm://wasm/016920ee:wasm-function[1404]:0x2f74a0)
    at std::sync::once::Once::call_inner::h00971925aa1adad3 (wasm://wasm/016920ee:wasm-function[1368]:0x2eff53)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::ha9f19eebf74dc8ce (wasm://wasm/016920ee:wasm-function[4782]:0x43bdab)
    at std::panicking::rust_panic_with_hook::h84feca33bd4bd229 (wasm://wasm/016920ee:wasm-function[3498]:0x402155)
    at core::panicking::panic_fmt::hc171d095bc4a492d (wasm://wasm/016920ee:wasm-function[4960]:0x4416cf)
    at core::result::unwrap_failed::h68ab818eb89182b6 (wasm://wasm/016920ee:wasm-function[4070]:0x424fa9)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::hf7074a53cc0353e7 (wasm://wasm/016920ee:wasm-function[698]:0x2036ce)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_render::backend::RenderBackend>::register_shape::hf81bbdc1abb4740a (wasm://wasm/016920ee:wasm-function[3160]:0x3eb922)
    at ruffle_core::drawing::Drawing::render::hf467012e3414d904 (wasm://wasm/016920ee:wasm-function[627]:0x1d93ab)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://homestarrunner.com/dman3
SWF URL: https://homestarrunner.com/media/pages/dman3/f0e50731c9-1609375302/thydungeonman3.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
Platform: Win32
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-08-16
Channel: nightly
Built: 2022-08-16T00:14:29.101Z
Commit: 82716d9be3feaa3dda3d75409533123b756aa9a4
Is extension: false

**Comment by n0samu** [comment]
Closing in favor of #8179 (same error)
