### ISSUE TITLE
Error on https://games.inbox.lv/request.php

### ISSUE THREAD

**Issue by hiral2011** [ruffle-rs/ruffle#7750]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:491:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:491:50
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://games.inbox.lv/assets/games/js/ruffle/ruffle.js?9ec5206ddf650e8:1:7026)
    at std::sync::once::Once::call_once::{{closure}}::h6e694fc45f651103 (https://games.inbox.lv/assets/games/js/ruffle/c544f80f26d01180229b.wasm:wasm-function[1077]:0x2894c7)
    at std::sync::once::Once::call_inner::h99e47643887ee5a5 (https://games.inbox.lv/assets/games/js/ruffle/c544f80f26d01180229b.wasm:wasm-function[955]:0x260f36)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hb552ca3003b47989 (https://games.inbox.lv/assets/games/js/ruffle/c544f80f26d01180229b.wasm:wasm-function[3849]:0x41da0b)
    at std::panicking::rust_panic_with_hook::h03201bc01a0ed891 (https://games.inbox.lv/assets/games/js/ruffle/c544f80f26d01180229b.wasm:wasm-function[3000]:0x3b912e)
    at rust_begin_unwind (https://games.inbox.lv/assets/games/js/ruffle/c544f80f26d01180229b.wasm:wasm-function[4057]:0x423356)
    at core::panicking::panic_fmt::hd44f353696296fec (https://games.inbox.lv/assets/games/js/ruffle/c544f80f26d01180229b.wasm:wasm-function[4205]:0x429ca5)
    at core::option::expect_none_failed::hf7dab2706f1a5551 (https://games.inbox.lv/assets/games/js/ruffle/c544f80f26d01180229b.wasm:wasm-function[3440]:0x40bdcc)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::he06901c88d3868a1 (https://games.inbox.lv/assets/games/js/ruffle/c544f80f26d01180229b.wasm:wasm-function[603]:0x1a917f)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::register_glyph_shape::h7dde7e72de3b7b27 (https://games.inbox.lv/assets/games/js/ruffle/c544f80f26d01180229b.wasm:wasm-function[2170]:0x3625a7)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: /uploads/games/1039.swf
Param movie: /uploads/games/1039.swf
Param wmode: window
Param menu: false
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://games.inbox.lv/request.php?action=GAME_OBJ
SWF URL: https://games.inbox.lv/uploads/games/1039.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-06-15
Channel: nightly
Built: 2021-06-15T00:11:56.508Z
Commit: 6146502b1a427bd83b8073f26662abb5959da2b2

**Comment by kjarosh** [comment]
Should be fixed as of the newest version
