### ISSUE TITLE
Error on https://www.lesjeuxgratuits.fr/jeu-billard-en-ligne

### ISSUE THREAD

**Issue by Alain-Provist** [ruffle-rs/ruffle#7764]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: JsValue(InvalidStateError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
Error: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
    at https://www.lesjeuxgratuits.fr/js/ruffle_nightly_2021_01_28_selfhosted/ruffle.js:1:26398
    at https://www.lesjeuxgratuits.fr/js/ruffle_nightly_2021_01_28_selfhosted/ruffle.js:1:4647
    at web_sys::features::gen_CanvasRenderingContext2d::CanvasRenderingContext2d::draw_image_with_html_canvas_element::h4b3986a4e8714088 (https://www.lesjeuxgratuits.fr/js/ruffle_nightly_2021_01_28_selfhosted/c2b443b5d3c1e95c719f5c7fa8f05fa4.wasm:wasm-function[4447]:0x35eb03)
    at <ruffle_render_canvas::WebCanvasRenderBackend as ruffle_core::backend::render::RenderBackend>::pop_mask::ha6a53f4d027e5730 (https://www.lesjeuxgratuits.fr/js/ruffle_nightly_2021_01_28_selfhosted/c2b443b5d3c1e95c719f5c7fa8f05fa4.wasm:wasm-function[1039]:0x220144)
    at ruffle_core::display_object::container::TDisplayObjectContainer::render_children::hfcd2a832b1541aaf (https://www.lesjeuxgratuits.fr/js/ruffle_nightly_2021_01_28_selfhosted/c2b443b5d3c1e95c719f5c7fa8f05fa4.wasm:wasm-function[1188]:0x244589)
    at <ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::render::h532e28ba6d1f06ee (https://www.lesjeuxgratuits.fr/js/ruffle_nightly_2021_01_28_selfhosted/c2b443b5d3c1e95c719f5c7fa8f05fa4.wasm:wasm-function[3350]:0x337201)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render::ha62b240ae503659a (https://www.lesjeuxgratuits.fr/js/ruffle_nightly_2021_01_28_selfhosted/c2b443b5d3c1e95c719f5c7fa8f05fa4.wasm:wasm-function[3124]:0x32a937)
    at ruffle_core::display_object::container::TDisplayObjectContainer::render_children::hfcd2a832b1541aaf (https://www.lesjeuxgratuits.fr/js/ruffle_nightly_2021_01_28_selfhosted/c2b443b5d3c1e95c719f5c7fa8f05fa4.wasm:wasm-function[1188]:0x2446d2)
    at <ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::render::h532e28ba6d1f06ee (https://www.lesjeuxgratuits.fr/js/ruffle_nightly_2021_01_28_selfhosted/c2b443b5d3c1e95c719f5c7fa8f05fa4.wasm:wasm-function[3350]:0x337201)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render::ha62b240ae503659a (https://www.lesjeuxgratuits.fr/js/ruffle_nightly_2021_01_28_selfhosted/c2b443b5d3c1e95c719f5c7fa8f05fa4.wasm:wasm-function[3124]:0x32a937))', render/canvas/src/lib.rs:685:14

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.lesjeuxgratuits.fr/jeu-billard-en-ligne
SWF URL: https://www.lesjeuxgratuits.fr/swf/8.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-28
Channel: nightly
Built: 2021-01-28T00:36:59.079Z
Commit: 5e0527c59944d5888128c63f37d23880fdb0c6ff

**Comment by Alain-Provist** [comment]
Pour s'inscrire sur votre site, il faut parler Anglais ; et une bonne partie de notre planète ne parle pas Anglais !

**Comment by relrelb** [comment]
Fixed by #9358.
