### ISSUE TITLE
Error on http://www.verbouwkompas.nl./

### ISSUE THREAD

**Issue by feyyazesat** [ruffle-rs/ruffle#7810]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: UnableToCreateVAO', render/webgl/src/lib.rs:561:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: UnableToCreateVAO', render/webgl/src/lib.rs:561:50
    at e.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:1:5743)
    at std::sync::once::Once::call_once::{{closure}}::h2b0dd13dece8b2bd (wasm://wasm/016ae5c6:wasm-function[934]:0x26ac3f)
    at std::sync::once::Once::call_inner::h00971925aa1adad3 (wasm://wasm/016ae5c6:wasm-function[1370]:0x2f96e0)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hcedf29f658f02358 (wasm://wasm/016ae5c6:wasm-function[4798]:0x441c82)
    at std::panicking::rust_panic_with_hook::h84feca33bd4bd229 (wasm://wasm/016ae5c6:wasm-function[3519]:0x408f9d)
    at core::panicking::panic_fmt::hc171d095bc4a492d (wasm://wasm/016ae5c6:wasm-function[4975]:0x447567)
    at core::result::unwrap_failed::h68ab818eb89182b6 (wasm://wasm/016ae5c6:wasm-function[4106]:0x42b612)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::h2a0f4d55ecb0af74 (wasm://wasm/016ae5c6:wasm-function[665]:0x1ede50)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_render::backend::RenderBackend>::register_glyph_shape::h96b9bc5d192719fa (wasm://wasm/016ae5c6:wasm-function[1712]:0x344512)
    at ruffle_core::font::Font::from_swf_tag::hff73ceecc23a62a2 (wasm://wasm/016ae5c6:wasm-function[644]:0x1de7dc)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: g-force.swf
Param flashvars: contentfile=introductie/g-force.xml&klus=introductie&bookmark=undefined
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined

# Page Info
Page URL: http://www.verbouwkompas.nl./#/introductie/
SWF URL: http://www.verbouwkompas.nl./g-force.swf

# Browser Info
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
Platform: MacIntel
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-08-30
Channel: nightly
Built: 2022-08-30T00:18:51.591Z
Commit: 36450619109b6ed510991b311f4888c0784eba8e
Is extension: true

# Metadata

**Comment by kjarosh** [comment]
Should be fixed as of the newest version
