### ISSUE TITLE
Alien Hominid panics in Microsoft Edge 105's Enhanced Security Mode

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#7849]
# Error Info
Error name: Error
Error message: panicked at 'index out of bounds: the len is 9 but the index is 9', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/lyon_tessellation-1.0.1/src/fill.rs:1547:27
Error stack:
```
Error: panicked at 'index out of bounds: the len is 9 but the index is 9', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/lyon_tessellation-1.0.1/src/fill.rs:1547:27
    at G.n.wbg.__wbg_new_df6e6ab7a65c4c4d (https://ruffle.rs/demo/662.index.js:1:6819)
    at std::sync::once::Once::call_once::{{closure}}::h198ac0e8fb54773d (wasm://wasm/017df606:wasm-function[963]:0x0)
    at std::sync::once::Once::call_inner::h00971925aa1adad3 (wasm://wasm/017df606:wasm-function[1488]:0x0)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h31a9f440927699f0 (wasm://wasm/017df606:wasm-function[5010]:0x0)
    at std::panicking::rust_panic_with_hook::h84feca33bd4bd229 (wasm://wasm/017df606:wasm-function[3690]:0x0)
    at core::panicking::panic_fmt::hc171d095bc4a492d (wasm://wasm/017df606:wasm-function[5199]:0x0)
    at core::panicking::panic_bounds_check::hba06abf6b514a1a1 (wasm://wasm/017df606:wasm-function[4465]:0x0)
    at lyon_tessellation::fill::FillTessellator::process_events::hdfec8c7907959ad3 (wasm://wasm/017df606:wasm-function[368]:0x0)
    at lyon_tessellation::fill::FillTessellator::tessellate_impl::h68bea4228d2df416 (wasm://wasm/017df606:wasm-function[578]:0x0)
    at ruffle_render::tessellator::ShapeTessellator::tessellate_shape::hed13ce21eb8207fe (wasm://wasm/017df606:wasm-function[501]:0x0)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://ruffle.rs/demo/
SWF URL: https://ruffle.rs/demo/swfs/alien_hominid.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 Edg/105.0.1343.25
Platform: Win32
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-09-02
Channel: nightly
Built: 2022-09-02T00:17:35.177Z
Commit: 5c27c76cbaea425f944f9a55d4be41367377dbc8
Is extension: false

# Metadata
width: 550
height: 400
frameRate: 24
numFrames: 24
swfVersion: 6
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 2037879

**Comment by n0samu** [comment]
The error happens immediately after selecting Alien Hominid from the dropdown on the Ruffle demo site.

**Comment by n0samu** [comment]
This seems to be fixed in the latest Edge update (105.0.1343.42)

**Comment by whobiggs** [comment]
It works now in a fashion but is incredibly slow and jerky

**Comment by danielhjacobs** [comment]
@whobiggs Unfortunately, we can't help it if Microsoft decides to use a slower WebAssembly engine with enhanced security. Microsoft Edge's safer WebAssembly interpreter is still in its infancy. It will probably gain improved performance in time. In the meantime, you can disable Enhanced Security or add exceptions for specific sites as described on https://learn.microsoft.com/en-us/deployedge/microsoft-edge-security-browse-safer#enhanced-security-sites.

**Comment by whobiggs** [comment]
Hi Daniel, I've turned that off and it works great now, many thanks for that 👍
