### ISSUE TITLE
Error on https://fgn.cdn.serverable.com/common/flashes/nf/touch_the_girl/index.html

### ISSUE THREAD

**Issue by jhairvaletinxd** [ruffle-rs/ruffle#7860]
# Error Info
Error name: Error
Error message: panicked at 'assertion failed: min <= max', /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/cmp.rs:816:9
Error stack:
```
Error: panicked at 'assertion failed: min <= max', /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/cmp.rs:816:9
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (https://fgn.cdn.serverable.com/common/flashes/js/ruffle211222/ruffle.js:1:6703)
    at std::sync::once::Once::call_once::{{closure}}::h2a5914e357df5b02 (https://fgn.cdn.serverable.com/common/flashes/js/ruffle211222/c5c02c4e65c1c4423a97.wasm:wasm-function[990]:0x30f0ab)
    at std::sync::once::Once::call_inner::hf9144d66ddc67dec (https://fgn.cdn.serverable.com/common/flashes/js/ruffle211222/c5c02c4e65c1c4423a97.wasm:wasm-function[1195]:0x354b94)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h2b08ffde388f7cc2 (https://fgn.cdn.serverable.com/common/flashes/js/ruffle211222/c5c02c4e65c1c4423a97.wasm:wasm-function[4712]:0x505beb)
    at std::panicking::rust_panic_with_hook::h606d7c7f7a423b98 (https://fgn.cdn.serverable.com/common/flashes/js/ruffle211222/c5c02c4e65c1c4423a97.wasm:wasm-function[3248]:0x4b1c8a)
    at rust_begin_unwind (https://fgn.cdn.serverable.com/common/flashes/js/ruffle211222/c5c02c4e65c1c4423a97.wasm:wasm-function[4776]:0x507340)
    at core::panicking::panic_fmt::h6314b5c91abe7349 (https://fgn.cdn.serverable.com/common/flashes/js/ruffle211222/c5c02c4e65c1c4423a97.wasm:wasm-function[4991]:0x512348)
    at core::panicking::panic::hec1fc057bd0baf0b (https://fgn.cdn.serverable.com/common/flashes/js/ruffle211222/c5c02c4e65c1c4423a97.wasm:wasm-function[4709]:0x505451)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::set_viewport_dimensions::h5a7080617aa6f50c (https://fgn.cdn.serverable.com/common/flashes/js/ruffle211222/c5c02c4e65c1c4423a97.wasm:wasm-function[700]:0x2701bd)
    at ruffle_web::Ruffle::tick::hb37e299891d44469 (https://fgn.cdn.serverable.com/common/flashes/js/ruffle211222/c5c02c4e65c1c4423a97.wasm:wasm-function[602]:0x22efd8)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: touchthegirl_sv.swf
Param movie: touchthegirl_sv.swf
Param quality: high
Param bgcolor: #000000
Param play: true
Param loop: true
Param wmode: window
Param scale: showall
Param menu: true
Param devicefont: false
Param allowScriptAccess: sameDomain
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://fgn.cdn.serverable.com/common/flashes/nf/touch_the_girl/index.html?d=20200415122149?e=MTY2MjQ1MTk3NQ%3D%3D
SWF URL: https://fgn.cdn.serverable.com/common/flashes/nf/touch_the_girl/touchthegirl_sv.swf

# Browser Info
Useragent: Mozilla/5.0 (Linux; Android 11; 2201117TY) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Mobile Safari/537.36
OS: Linux armv8l

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-12-22
Channel: nightly
Built: 2021-12-22T00:14:15.814Z
Commit: 74ab24c0c3345025a1b7297c526c37783ecc9990
Is extension: false

**Comment by jhairvaletinxd** [comment]
Xd

**Comment by n0samu** [comment]
Should be fixed by #9108

**Comment by Lord-McSweeney** [comment]
I'm pretty sure that wasn't what fixed it, seeing as there's a `set_viewport_dimensions` in the stack trace.

**Comment by n0samu** [comment]
I'm not opening the SWF to check the issue so I guess I'll just reopen it then lol

**Comment by Lord-McSweeney** [comment]
Should have been fixed by #6458 a long time ago
