### ISSUE TITLE
Error on http://www.oyuncenneti.com/kirmizi-tosbaga-oyna.html

### ISSUE THREAD

**Issue by enes1232442** [ruffle-rs/ruffle#7864]
# Error Info
Error name: Error
Error message: panicked at 'index out of bounds: the len is 2 but the index is 3', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/lyon_tessellation-0.17.10/src/fill.rs:1329:13
Error stack:
```
Error: panicked at 'index out of bounds: the len is 2 but the index is 3', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/lyon_tessellation-0.17.10/src/fill.rs:1329:13
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (http://www.oyuncenneti.com/ruffle.js:1:7036)
    at std::sync::once::Once::call_once::{{closure}}::h5387044f596cf17b (http://www.oyuncenneti.com/86c8cc086d5464b4c06b.wasm:wasm-function[996]:0x0)
    at std::sync::once::Once::call_inner::h02a6489b0ecfb269 (http://www.oyuncenneti.com/86c8cc086d5464b4c06b.wasm:wasm-function[1317]:0x0)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h4461033b8c8249d8 (http://www.oyuncenneti.com/86c8cc086d5464b4c06b.wasm:wasm-function[4669]:0x0)
    at std::panicking::rust_panic_with_hook::h364974e717ed59ec (http://www.oyuncenneti.com/86c8cc086d5464b4c06b.wasm:wasm-function[3289]:0x0)
    at rust_begin_unwind (http://www.oyuncenneti.com/86c8cc086d5464b4c06b.wasm:wasm-function[4731]:0x0)
    at core::panicking::panic_fmt::hf69c8b08bc9d2ee5 (http://www.oyuncenneti.com/86c8cc086d5464b4c06b.wasm:wasm-function[4942]:0x0)
    at core::panicking::panic_bounds_check::h1d84519ec46ed48c (http://www.oyuncenneti.com/86c8cc086d5464b4c06b.wasm:wasm-function[4187]:0x0)
    at lyon_tessellation::fill::FillTessellator::process_events::h8c6e72bab723bdff (http://www.oyuncenneti.com/86c8cc086d5464b4c06b.wasm:wasm-function[336]:0x0)
    at lyon_tessellation::fill::FillTessellator::tessellate_impl::h4144057b3fbc5f9d (http://www.oyuncenneti.com/86c8cc086d5464b4c06b.wasm:wasm-function[637]:0x0)
```

# Player Info
Allows script access: false

# Page Info
Page URL: http://www.oyuncenneti.com/kirmizi-tosbaga-oyna.html
SWF URL: http://www.oyuncenneti.com/oyunlar/kirmizi_tosbaga.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 Edg/105.0.1343.27
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-11-11
Channel: nightly
Built: 2021-11-11T00:14:36.131Z
Commit: 60eb88b3265601d16467672a732081b30884707d
Is extension: false

**Comment by n0samu** [comment]
See also: #7849

**Comment by n0samu** [comment]
Closing in favor of #7849
