### ISSUE TITLE
Error on https://flashstorage.games/embed/electric-man

### ISSUE THREAD

**Issue by TrentTrentTrent** [ruffle-rs/ruffle#7870]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:812:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:812:18
    at W.n.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:1:5256)
    at std::sync::once::Once::call_once::{{closure}}::hd2dd5af86508d22e (wasm://wasm/016ca582:wasm-function[937]:0x2665c8)
    at std::sync::once::Once::call_inner::h00971925aa1adad3 (wasm://wasm/016ca582:wasm-function[1378]:0x2ef11d)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hc24950feb424fb14 (wasm://wasm/016ca582:wasm-function[4809]:0x442bff)
    at std::panicking::rust_panic_with_hook::h84feca33bd4bd229 (wasm://wasm/016ca582:wasm-function[3563]:0x40942c)
    at core::panicking::panic_fmt::hc171d095bc4a492d (wasm://wasm/016ca582:wasm-function[4983]:0x448fb4)
    at core::panicking::panic::h3b7a8a1eaf47fc0f (wasm://wasm/016ca582:wasm-function[4893]:0x44434d)
    at core::ops::function::FnOnce::call_once::hd1d8ef73d7f604e1 (wasm://wasm/016ca582:wasm-function[1022]:0x27f975)
    at ruffle_core::avm1::function::Executable::exec::hc3210dd9b7203ff7 (wasm://wasm/016ca582:wasm-function[353]:0xd8b51)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h66d4123389adcc68 (wasm://wasm/016ca582:wasm-function[817]:0x234ed6)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://flashstorage.games/embed/electric-man
SWF URL: https://flashstorage.games/public/storage/games/FLASHJanuary2022/electric-man.swf?at=2022-09-04%2006:47:48

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-09-04
Channel: nightly
Built: 2022-09-04T00:16:27.336Z
Commit: 3b752cc600297c101ce6abd768614c258e28317c
Is extension: true

# Metadata
width: 640
height: 400
frameRate: 18
numFrames: 36
swfVersion: 6
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 3609377

**Comment by TrentTrentTrent** [comment]
Closing this, I've found duplicates of this issue.
