### ISSUE TITLE
Error on https://ruffle.rs/demo/

### ISSUE THREAD

**Issue by abdullah1116** [ruffle-rs/ruffle#7871]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: UnableToCreateVAO', render/webgl/src/lib.rs:561:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: UnableToCreateVAO', render/webgl/src/lib.rs:561:50
    at W.n.wbg.__wbg_new_df6e6ab7a65c4c4d (https://ruffle.rs/demo/966.index.js:1:6195)
    at std::sync::once::Once::call_once::{{closure}}::h74e298cc9ce209a0 (wasm://wasm/017656ea:wasm-function[989]:0x274ee0)
    at std::sync::once::Once::call_inner::h00971925aa1adad3 (wasm://wasm/017656ea:wasm-function[1436]:0x2f434f)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h7a8b08757dbfcccc (wasm://wasm/017656ea:wasm-function[4981]:0x458897)
    at std::panicking::rust_panic_with_hook::h84feca33bd4bd229 (wasm://wasm/017656ea:wasm-function[3685]:0x41b74c)
    at core::panicking::panic_fmt::hc171d095bc4a492d (wasm://wasm/017656ea:wasm-function[5172]:0x463056)
    at core::result::unwrap_failed::h68ab818eb89182b6 (wasm://wasm/017656ea:wasm-function[4277]:0x43ea89)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::h601053d837dbdd41 (wasm://wasm/017656ea:wasm-function[709]:0x1fcf89)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_render::backend::RenderBackend>::register_glyph_shape::ha0fa96c40f84e1f5 (wasm://wasm/017656ea:wasm-function[1825]:0x3535cb)
    at ruffle_core::font::Font::from_swf_tag::had6ad8b9c0d1936d (wasm://wasm/017656ea:wasm-function[688]:0x1f3970)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://ruffle.rs/demo/

# Browser Info
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-09-05
Channel: nightly
Built: 2022-09-05T00:15:21.484Z
Commit: acdb7678621c1f5fd5f13d5fc5a82d870f9720c0
Is extension: false

# Metadata
width: 700
height: 600
frameRate: 30
numFrames: 2
swfVersion: 14
backgroundColor: null
isActionScript3: true
uncompressedLength: 32867074

**Comment by OneOfMany07** [comment]
(random internet person here who just opened that URL)

Did you get this error immediately after loading the page?  Or did you do something to trigger it like upload an SWF or pick from the dropdown list?  If you did something then steps to reproduce it are often useful.

**Comment by n0samu** [comment]
Old issue with no information provided, closing
