### ISSUE TITLE
Error on https://fgn.cdn.serverable.com/common/flashes/nf/touch_the_girl/index.html

### ISSUE THREAD

**Issue by Kiyo2005** [ruffle-rs/ruffle#7897]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:494:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:494:50
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (https://fgn.cdn.serverable.com/common/flashes/js/ruffle211222/ruffle.js:1:6703)
    at std::sync::once::Once::call_once::{{closure}}::h2a5914e357df5b02 (https://fgn.cdn.serverable.com/common/flashes/js/ruffle211222/c5c02c4e65c1c4423a97.wasm:wasm-function[990]:0x30f0ab)
    at std::sync::once::Once::call_inner::hf9144d66ddc67dec (https://fgn.cdn.serverable.com/common/flashes/js/ruffle211222/c5c02c4e65c1c4423a97.wasm:wasm-function[1195]:0x354b94)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h2b08ffde388f7cc2 (https://fgn.cdn.serverable.com/common/flashes/js/ruffle211222/c5c02c4e65c1c4423a97.wasm:wasm-function[4712]:0x505beb)
    at std::panicking::rust_panic_with_hook::h606d7c7f7a423b98 (https://fgn.cdn.serverable.com/common/flashes/js/ruffle211222/c5c02c4e65c1c4423a97.wasm:wasm-function[3248]:0x4b1c8a)
    at rust_begin_unwind (https://fgn.cdn.serverable.com/common/flashes/js/ruffle211222/c5c02c4e65c1c4423a97.wasm:wasm-function[4776]:0x507361)
    at core::panicking::panic_fmt::h6314b5c91abe7349 (https://fgn.cdn.serverable.com/common/flashes/js/ruffle211222/c5c02c4e65c1c4423a97.wasm:wasm-function[4991]:0x512348)
    at core::result::unwrap_failed::hd584efb7b84bf326 (https://fgn.cdn.serverable.com/common/flashes/js/ruffle211222/c5c02c4e65c1c4423a97.wasm:wasm-function[4018]:0x4ee3c5)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::h99e18f2587d0d861 (https://fgn.cdn.serverable.com/common/flashes/js/ruffle211222/c5c02c4e65c1c4423a97.wasm:wasm-function[706]:0x274bcb)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::register_shape::h0082ec8aeada4aa4 (https://fgn.cdn.serverable.com/common/flashes/js/ruffle211222/c5c02c4e65c1c4423a97.wasm:wasm-function[2839]:0x48de3d)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: touchthegirl_sv.swf
Param movie: touchthegirl_sv.swf
Param quality: high
Param bgcolor: #000000
Param play: true
Param loop: true
Param wmode: window
Param scale: showall
Param menu: true
Param devicefont: false
Param allowScriptAccess: sameDomain
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://fgn.cdn.serverable.com/common/flashes/nf/touch_the_girl/index.html?d=20220208005747
SWF URL: https://fgn.cdn.serverable.com/common/flashes/nf/touch_the_girl/touchthegirl_sv.swf

# Browser Info
Useragent: Mozilla/5.0 (Linux; Android 12; SOG02) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Mobile Safari/537.36
OS: Linux aarch64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-12-22
Channel: nightly
Built: 2021-12-22T00:14:15.814Z
Commit: 74ab24c0c3345025a1b7297c526c37783ecc9990
Is extension: false

**Comment by kjarosh** [comment]
Should be fixed as of the newest version
