### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by mecool54** [ruffle-rs/ruffle#7905]
# Error Info
Error name: Error
Error message: panicked at 'index out of bounds: the len is 7 but the index is 7', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/lyon_tessellation-1.0.1/src/fill.rs:1547:27
Error stack:
```
Error: panicked at 'index out of bounds: the len is 7 but the index is 7', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/lyon_tessellation-1.0.1/src/fill.rs:1547:27
    at e.wbg.__wbg_new_df6e6ab7a65c4c4d (https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.4d295c5f86ba9bdd719b.js:1:5804)
    at std::sync::once::Once::call_once::{{closure}}::h00e9527065505d48 (wasm://wasm/01736d0e:wasm-function[886]:0x0)
    at std::sync::once::Once::call_inner::h00971925aa1adad3 (wasm://wasm/01736d0e:wasm-function[1426]:0x0)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h962959d96d2b047f (wasm://wasm/01736d0e:wasm-function[4818]:0x0)
    at std::panicking::rust_panic_with_hook::h84feca33bd4bd229 (wasm://wasm/01736d0e:wasm-function[3597]:0x0)
    at core::panicking::panic_fmt::hc171d095bc4a492d (wasm://wasm/01736d0e:wasm-function[4995]:0x0)
    at core::panicking::panic_bounds_check::hba06abf6b514a1a1 (wasm://wasm/01736d0e:wasm-function[4352]:0x0)
    at lyon_tessellation::fill::FillTessellator::process_events::hdfec8c7907959ad3 (wasm://wasm/01736d0e:wasm-function[327]:0x0)
    at lyon_tessellation::fill::FillTessellator::tessellate_impl::h68bea4228d2df416 (wasm://wasm/01736d0e:wasm-function[525]:0x0)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::heb60c705ea5cb7bb (wasm://wasm/01736d0e:wasm-function[606]:0x0)
```

# Player Info
Allows script access: true
Renderer: WebGL

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.67&useloader=1&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1662473966%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F592000%2F592473_MadnessGame_ULTIMATE.swf%3F1507662264%22%2C%22vars%22%3A%7B%22ngio_session_id%22%3A%2225567883.9a9280d2c2813694cbc2337cb37a60d1429b3c88b192ca%22%2C%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%2263182de67101c%22%2C%22NewgroundsAPI_SessionID%22%3A%22pKtbkQVnURHg6pwSm7X36367e4ddc6053ebcaa6470c783c9b2bd42728e47EZYM%22%2C%22NewgroundsAPI_UserName%22%3A%22Wdgaster-Theimposter%22%2C%22NewgroundsAPI_UserID%22%3A8984575%2C%22ng_username%22%3A%22Wdgaster-Theimposter%22%7D%2C%22width%22%3A850%2C%22height%22%3A530%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F592000%2Fflash_592473_card.png%3Ff1608170534%22%2C%22warnOnUnsupportedContent%22%3Afalse%7D
SWF URL: https://uploads.ungrounded.net/592000/592473_MadnessGame_ULTIMATE.swf?1507662264

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 Edg/105.0.1343.27
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-09-06
Channel: nightly
Built: 2022-09-06T00:19:30.559Z
Commit: 45960de7dc0e21a7a1841c91c9d3693fefff6520
Is extension: false

# Metadata
width: 850
height: 530
frameRate: 30
numFrames: 30
swfVersion: 10
backgroundColor: #FFFFFF
isActionScript3: false
uncompressedLength: 20491352

**Comment by n0samu** [comment]
Same issue as #7849

**Comment by Herschel** [comment]
Closing in favor of #7849.
