### ISSUE TITLE
Error on https://www.comdotgame.com/play/tifa-abuse

### ISSUE THREAD

**Issue by ahaata78** [ruffle-rs/ruffle#7919]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: JsValue(TypeError: o(...).createBuffer is not a function
TypeError: o(...).createBuffer is not a function
    at https://echo.comdotgame.com/ruffle/core.ruffle.3954d0ff848daf37a82e.js:1:29823
    at P (https://echo.comdotgame.com/ruffle/core.ruffle.3954d0ff848daf37a82e.js:1:3178)
    at V.e.wbg.__wbg_createBuffer_4d396c7e99dd4d2a (https://echo.comdotgame.com/ruffle/core.ruffle.3954d0ff848daf37a82e.js:1:29788)
    at web_sys::features::gen_AudioContext::AudioContext::create_buffer::h6827b1d09f78eb81 (https://echo.comdotgame.com/ruffle/692de0edd8f3444d5442.wasm:wasm-function[4590]:0x4239ee)
    at ruffle_web::audio::WebAudioBackend::decompress_to_audio_buffer::hc5437d240a719eba (https://echo.comdotgame.com/ruffle/692de0edd8f3444d5442.wasm:wasm-function[418]:0x11fd2f)
    at <ruffle_web::audio::WebAudioBackend as ruffle_core::backend::audio::AudioBackend>::register_sound::h094a65e209f5bc78 (https://echo.comdotgame.com/ruffle/692de0edd8f3444d5442.wasm:wasm-function[2216]:0x3828d7)
    at ruffle_core::display_object::movie_clip::MovieClip::preload::h4f3c114fe8433618 (https://echo.comdotgame.com/ruffle/692de0edd8f3444d5442.wasm:wasm-function[822]:0x228756)
    at ruffle_core::player::Player::set_root_movie::h95ae13a6789c3efb (https://echo.comdotgame.com/ruffle/692de0edd8f3444d5442.wasm:wasm-function[372]:0xedc28)
    at <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h969b1fa076f8c705 (https://echo.comdotgame.com/ruffle/692de0edd8f3444d5442.wasm:wasm-function[554]:0x196eef)
    at <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hff435146d5130798 (https://echo.comdotgame.com/ruffle/692de0edd8f3444d5442.wasm:wasm-function[1924]:0x358424))', web/src/audio.rs:749:14

# Player Info
Allows script access: true
Player type: Object
SWF URL: https://echo.comdotgame.com/4x90xhl3k0/games/files/08599310a44e1842a269c9e78e263167.swf
Param allowscriptaccess: always
Param bgcolor: ffffff
Param wmode: gpu
Param base: https://echo.comdotgame.com/4x90xhl3k0/games/files/tifa-abuse/
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined
Attribute 6: undefined

# Page Info
Page URL: https://www.comdotgame.com/play/tifa-abuse
SWF URL: https://echo.comdotgame.com/4x90xhl3k0/games/files/08599310a44e1842a269c9e78e263167.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.102 Safari/537.36 Edg/104.0.1293.63
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-07-06
Channel: nightly
Built: 2022-07-06T00:17:12.303Z
Commit: 265dcd2e8dc424871b034cbceafb1fbadb76714a
Is extension: false

**Comment by n0samu** [comment]
Same error as #7918
