### ISSUE TITLE
Error on https://www.coolmath-games.com/sites/cmatgame/files/ruffle1/ruffle.html

### ISSUE THREAD

**Issue by LKEWXD** [ruffle-rs/ruffle#7959]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:505:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:505:50
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (https://www.coolmath-games.com/sites/cmatgame/files/ruffle1/core.ruffle.b04f36c96b058154301e.js:1:7024)
    at std::sync::once::Once::call_once::{{closure}}::h88eaa18dadf92e1d (https://www.coolmath-games.com/sites/cmatgame/files/ruffle1/8cc6756b5f26f22e3ad3.wasm:wasm-function[1165]:0x2a36ad)
    at std::sync::once::Once::call_inner::h8a142b2dcc139875 (https://www.coolmath-games.com/sites/cmatgame/files/ruffle1/8cc6756b5f26f22e3ad3.wasm:wasm-function[1364]:0x2db1e1)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hdf61c261967f450e (https://www.coolmath-games.com/sites/cmatgame/files/ruffle1/8cc6756b5f26f22e3ad3.wasm:wasm-function[4681]:0x4231cc)
    at std::panicking::rust_panic_with_hook::he2a025723e105e28 (https://www.coolmath-games.com/sites/cmatgame/files/ruffle1/8cc6756b5f26f22e3ad3.wasm:wasm-function[3087]:0x3c7cfb)
    at core::panicking::panic_fmt::hb02133958c1e7d35 (https://www.coolmath-games.com/sites/cmatgame/files/ruffle1/8cc6756b5f26f22e3ad3.wasm:wasm-function[4864]:0x429366)
    at core::result::unwrap_failed::h68fdaca771c68bb6 (https://www.coolmath-games.com/sites/cmatgame/files/ruffle1/8cc6756b5f26f22e3ad3.wasm:wasm-function[3994]:0x40d31b)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::hcaabff3249811b0e (https://www.coolmath-games.com/sites/cmatgame/files/ruffle1/8cc6756b5f26f22e3ad3.wasm:wasm-function[715]:0x204688)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::register_shape::hf355593e7ff57b25 (https://www.coolmath-games.com/sites/cmatgame/files/ruffle1/8cc6756b5f26f22e3ad3.wasm:wasm-function[3113]:0x3c9334)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render_self::h98dade6c7d69d856 (https://www.coolmath-games.com/sites/cmatgame/files/ruffle1/8cc6756b5f26f22e3ad3.wasm:wasm-function[2385]:0x385685)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: https://www.coolmath-games.com/sites/cmatgame/files/games/learn_to_fly_final_3.54k_coolmath_1.swf
Param allowScriptAccess: always
Param movie: learn_to_fly_final_3.54k_coolmath_1.swf
Param menu: false
Param quality: high
Param wmode: direct
Param scale: exactfit
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://www.coolmath-games.com/sites/cmatgame/files/ruffle1/ruffle.html?f=learn_to_fly_final_3.54k_coolmath_1.swf&w=640&h=480
SWF URL: https://www.coolmath-games.com/sites/cmatgame/files/games/learn_to_fly_final_3.54k_coolmath_1.swf

# Browser Info
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Platform: MacIntel
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-06-30
Channel: nightly
Built: 2022-06-30T00:18:36.829Z
Commit: c7bf11ece542140203d4368a6c7eca296c134b2b
Is extension: false

**Comment by kjarosh** [comment]
Should be fixed as of the newest version
