### ISSUE TITLE
Error on https://www.faceyourmanga.com/editmangatar.php

### ISSUE THREAD

**Issue by p0008874** [ruffle-rs/ruffle#7986]
# Error Info
Error name: Error
Error message: panicked at 'No script object for display object', core/src/avm1/runtime.rs:167:18
Error stack:
```
Error: panicked at 'No script object for display object', core/src/avm1/runtime.rs:167:18
    at W.n.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:1:5312)
    at std::sync::once::Once::call_once::{{closure}}::ha360d592741a73b3 (wasm://wasm/0178b726:wasm-function[1138]:0x2be549)
    at std::sync::once::Once::call_inner::h00971925aa1adad3 (wasm://wasm/0178b726:wasm-function[1439]:0x3142c9)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h613b00154d20bc2b (wasm://wasm/0178b726:wasm-function[4836]:0x46fa4b)
    at std::panicking::rust_panic_with_hook::h84feca33bd4bd229 (wasm://wasm/0178b726:wasm-function[3601]:0x437d78)
    at core::panicking::panic_fmt::hc171d095bc4a492d (wasm://wasm/0178b726:wasm-function[5023]:0x476149)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::h68ecc143bb0ed5dc (wasm://wasm/0178b726:wasm-function[1539]:0x32d591)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::hbfc46c0fb8042703 (wasm://wasm/0178b726:wasm-function[476]:0x17b6e3)
    at ruffle_core::display_object::movie_clip::MovieClip::place_object::hdfa492ac717b56ed (wasm://wasm/0178b726:wasm-function[1214]:0x2d1704)
    at <ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::construct_frame::h74102018eec5fdba (wasm://wasm/0178b726:wasm-function[391]:0x118c91)
```

# Player Info
Allows script access: true
Renderer: WebGL

# Page Info
Page URL: https://www.faceyourmanga.com/editmangatar.php
SWF URL: https://www.faceyourmanga.com/MAIN.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-09-14
Channel: nightly
Built: 2022-09-14T00:18:10.072Z
Commit: e08f8d47ab17d27b28997cd94b650dbfd58555d2
Is extension: true

# Metadata
width: 900
height: 520
frameRate: 30
numFrames: 1
swfVersion: 9
backgroundColor: #FFFFFF
isActionScript3: true
uncompressedLength: 12070

**Comment by n0samu** [comment]
This error occurs because the page has an AVM2 loader SWF that loads an AVM1 SWF. Ruffle does not support running AVM1 SWFs through AVM2 loaders yet. But loading the main AVM1 SWF directly in Ruffle via this URL seems to work fine: https://www.faceyourmanga.com/FYM2.swf?vF=1&vL=en
Related: #7899

**Comment by p0008874** [comment]
https://user-images.githubusercontent.com/75534590/212527165-ace943af-83b2-4015-9e7b-4c96fd9c0485.mp4
