### ISSUE TITLE
Error on https://ruffle.rs/demo/

### ISSUE THREAD

**Issue by p0008874** [ruffle-rs/ruffle#8014]
# Error Info
Error name: Error
Error message: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:573:14
Error stack:
```
Error: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:573:14
    at W.n.wbg.__wbg_new_df6e6ab7a65c4c4d (https://ruffle.rs/demo/966.index.js:1:5667)
    at std::sync::once::Once::call_once::{{closure}}::h32b8be6cf8b757f0 (wasm://wasm/018953de:wasm-function[1060]:0x29d6fe)
    at std::sync::once::Once::call_inner::h00971925aa1adad3 (wasm://wasm/018953de:wasm-function[1533]:0x330d54)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::ha74b43c9fad00c07 (wasm://wasm/018953de:wasm-function[5118]:0x4967cb)
    at std::panicking::rust_panic_with_hook::h84feca33bd4bd229 (wasm://wasm/018953de:wasm-function[3799]:0x45b9a4)
    at core::panicking::panic_fmt::hc171d095bc4a492d (wasm://wasm/018953de:wasm-function[5327]:0x4a1b31)
    at core::option::expect_failed::h0a5cf22f891a14fb (wasm://wasm/018953de:wasm-function[6059]:0x4b4a6d)
    at ruffle_core::display_object::stage::Stage::root_clip::h439d794178c0ba9a (wasm://wasm/018953de:wasm-function[3768]:0x458d95)
    at ruffle_web::Ruffle::tick::h273ec0ab23250fb0 (wasm://wasm/018953de:wasm-function[699]:0x1f959d)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::hd4fc2d80fbd7f88e (wasm://wasm/018953de:wasm-function[6297]:0x4bd588)
```

# Player Info
Allows script access: false
Renderer: WebGL

# Page Info
Page URL: https://ruffle.rs/demo/

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-09-18
Channel: nightly
Built: 2022-09-18T00:18:21.159Z
Commit: bfca30fed71342124dd7bc5a8aaa3c3ebf91a2d0
Is extension: false

# Metadata
width: 792
height: 600
frameRate: 60
numFrames: 2
swfVersion: 14
backgroundColor: null
isActionScript3: true
uncompressedLength: 1471114

**Comment by p0008874** [comment]
SWF used is N v2
https://www.thewayoftheninja.org/n.html

**Comment by n0samu** [comment]
Different game, but this is the same error that keeps occurring in Tank 2012: #5832
