### ISSUE TITLE
Error on chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/player.html

### ISSUE THREAD

**Issue by peepoostpin** [ruffle-rs/ruffle#8030]
# Error Info
Error name: Error
Error message: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:573:14
Error stack:
```
Error: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:573:14
    at W.n.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:1:5312)
    at std::sync::once::Once::call_once::{{closure}}::ha360d592741a73b3 (wasm://wasm/017cacaa:wasm-function[1138]:0x2c083f)
    at std::sync::once::Once::call_inner::h00971925aa1adad3 (wasm://wasm/017cacaa:wasm-function[1447]:0x320287)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h613b00154d20bc2b (wasm://wasm/017cacaa:wasm-function[4879]:0x478fc0)
    at std::panicking::rust_panic_with_hook::h84feca33bd4bd229 (wasm://wasm/017cacaa:wasm-function[3630]:0x441860)
    at core::panicking::panic_fmt::hc171d095bc4a492d (wasm://wasm/017cacaa:wasm-function[5070]:0x47f7eb)
    at core::option::expect_failed::h0a5cf22f891a14fb (wasm://wasm/017cacaa:wasm-function[5753]:0x491ae4)
    at ruffle_core::display_object::stage::Stage::root_clip::h90b7577398f62905 (wasm://wasm/017cacaa:wasm-function[3600]:0x43ed39)
    at ruffle_web::Ruffle::tick::h2f06be8515ce5317 (wasm://wasm/017cacaa:wasm-function[632]:0x1ec73d)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::hbea0329c336ba683 (wasm://wasm/017cacaa:wasm-function[5982]:0x49a75d)
```

# Player Info
Allows script access: false
Renderer: WebGL

# Page Info
Page URL: chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/player.html?url=https%3A%2F%2Fstatic.familyspace.ru%2Fswf%2Ftree%2Ftree.test.domain.swf
SWF URL: https://static.familyspace.ru/swf/tree/tree.test.domain.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-09-19
Channel: nightly
Built: 2022-09-19T00:15:10.357Z
Commit: 9b9c95bfe28cb862d44e9517e94e9de73acd9de3
Is extension: true

# Metadata
width: 1000
height: 950
frameRate: 30
numFrames: 2
swfVersion: 14
backgroundColor: null
isActionScript3: true
uncompressedLength: 1327237

**Comment by Dinnerbone** [comment]
Panic is fixed in https://github.com/ruffle-rs/ruffle/pull/10026
