### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by Picklenugget1** [ruffle-rs/ruffle#8031]
# Error Info
Error name: Error
Error message: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:573:14
Error stack:
```
Error: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:573:14
    at W.n.wbg.__wbg_new_df6e6ab7a65c4c4d (https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.9f799b172fb83660e1a8.js:1:5314)
    at std::sync::once::Once::call_once::{{closure}}::ha360d592741a73b3 (wasm://wasm/017cacaa:wasm-function[1138]:0x2c083f)
    at std::sync::once::Once::call_inner::h00971925aa1adad3 (wasm://wasm/017cacaa:wasm-function[1447]:0x320287)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h613b00154d20bc2b (wasm://wasm/017cacaa:wasm-function[4879]:0x478fc0)
    at std::panicking::rust_panic_with_hook::h84feca33bd4bd229 (wasm://wasm/017cacaa:wasm-function[3630]:0x441860)
    at core::panicking::panic_fmt::hc171d095bc4a492d (wasm://wasm/017cacaa:wasm-function[5070]:0x47f7eb)
    at core::option::expect_failed::h0a5cf22f891a14fb (wasm://wasm/017cacaa:wasm-function[5753]:0x491ae4)
    at ruffle_core::display_object::stage::Stage::root_clip::h90b7577398f62905 (wasm://wasm/017cacaa:wasm-function[3600]:0x43ed39)
    at ruffle_core::display_object::movie_clip::MovieClip::is_button_mode::h9ac3d8e3a96dc93e (wasm://wasm/017cacaa:wasm-function[1198]:0x2cfa12)
    at ruffle_core::player::Player::update_mouse_state::h5919d51136590b6e (wasm://wasm/017cacaa:wasm-function[323]:0xb4613)
```

# Player Info
Allows script access: true
Renderer: WebGL

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.67&useloader=1&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1663589521%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F642000%2F642341_tota-ag9.swf%3F1404925564%22%2C%22vars%22%3A%7B%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%22632a1851b3935%22%2C%22NewgroundsAPI_SessionID%22%3A%22%22%2C%22NewgroundsAPI_UserName%22%3A%22%26lt%3Bdeleted%26gt%3B%22%2C%22NewgroundsAPI_UserID%22%3A0%2C%22ng_username%22%3A%22%26lt%3Bdeleted%26gt%3B%22%7D%2C%22width%22%3A640%2C%22height%22%3A480%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F642000%2Fflash_642341_card.png%3Ff1601078292%22%2C%22warnOnUnsupportedContent%22%3Afalse%7D
SWF URL: https://uploads.ungrounded.net/642000/642341_tota-ag9.swf?1404925564

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS aarch64 14989.85.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Platform: Linux aarch64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-09-19
Channel: nightly
Built: 2022-09-19T00:15:10.357Z
Commit: 9b9c95bfe28cb862d44e9517e94e9de73acd9de3
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 60
numFrames: 2
swfVersion: 10
backgroundColor: null
isActionScript3: true
uncompressedLength: 6857591

**Comment by Dinnerbone** [comment]
Panic is fixed in https://github.com/ruffle-rs/ruffle/pull/10026. Game is now blocked on modifying XML.
