### ISSUE TITLE
Error on https://homestarrunner.com/dman3

### ISSUE THREAD

**Issue by RiledUp42** [ruffle-rs/ruffle#8032]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: UnableToCreateVAO', render/webgl/src/lib.rs:561:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: UnableToCreateVAO', render/webgl/src/lib.rs:561:50
    at e.wbg.__wbg_new_df6e6ab7a65c4c4d (https://homestarrunner.com/assets/js/core.ruffle.0707ef4d43431132870f.js:1:5745)
    at std::sync::once::Once::call_once::{{closure}}::h2b0dd13dece8b2bd (wasm://wasm/016b902e:wasm-function[943]:0x274ea3)
    at std::sync::once::Once::call_inner::h00971925aa1adad3 (wasm://wasm/016b902e:wasm-function[1380]:0x2fb420)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hcedf29f658f02358 (wasm://wasm/016b902e:wasm-function[4818]:0x444048)
    at std::panicking::rust_panic_with_hook::h84feca33bd4bd229 (wasm://wasm/016b902e:wasm-function[3539]:0x40b90a)
    at core::panicking::panic_fmt::hc171d095bc4a492d (wasm://wasm/016b902e:wasm-function[4993]:0x44988e)
    at core::result::unwrap_failed::h68ab818eb89182b6 (wasm://wasm/016b902e:wasm-function[4124]:0x42d912)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::h2a0f4d55ecb0af74 (wasm://wasm/016b902e:wasm-function[666]:0x1ee1d5)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_render::backend::RenderBackend>::register_shape::h5c540e73034209bf (wasm://wasm/016b902e:wasm-function[3195]:0x3f4ab8)
    at ruffle_core::drawing::Drawing::render::h8529eb4621468733 (wasm://wasm/016b902e:wasm-function[628]:0x1d70d0)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://homestarrunner.com/dman3
SWF URL: https://homestarrunner.com/media/pages/dman3/f0e50731c9-1609375302/thydungeonman3.swf

# Browser Info
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Platform: MacIntel
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-09-02
Channel: nightly
Built: 2022-09-02T00:17:59.385Z
Commit: 5c27c76cbaea425f944f9a55d4be41367377dbc8
Is extension: false

# Metadata
width: 550
height: 400
frameRate: 24
numFrames: 258
swfVersion: 7
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 1200460

**Comment by n0samu** [comment]
Closing in favor of #8179 (same error)
