### ISSUE TITLE
Error on https://armorgames.com/play/6507/operation-blackknife

### ISSUE THREAD

**Issue by Picklenugget1** [ruffle-rs/ruffle#8047]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: UnableToCreateVAO', render/webgl/src/lib.rs:564:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: UnableToCreateVAO', render/webgl/src/lib.rs:564:50
    at W.n.wbg.__wbg_new_df6e6ab7a65c4c4d (https://agi.armorgames.com/ruffle/core.ruffle.62a5b45e6d4e022d7d4b.js:1:5314)
    at std::sync::once::Once::call_once::{{closure}}::hc7e1e9ccae1dc751 (wasm://wasm/0171db26:wasm-function[946]:0x272e6a)
    at std::sync::once::Once::call_inner::h00971925aa1adad3 (wasm://wasm/0171db26:wasm-function[1397]:0x2f6e0e)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::heaafb58166fe27c7 (wasm://wasm/0171db26:wasm-function[4859]:0x453959)
    at std::panicking::rust_panic_with_hook::h84feca33bd4bd229 (wasm://wasm/0171db26:wasm-function[3612]:0x41caa7)
    at core::panicking::panic_fmt::hc171d095bc4a492d (wasm://wasm/0171db26:wasm-function[5046]:0x45a07e)
    at core::result::unwrap_failed::h68ab818eb89182b6 (wasm://wasm/0171db26:wasm-function[4173]:0x43ec00)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::hc521ab87d86bebf7 (wasm://wasm/0171db26:wasm-function[661]:0x1f54a3)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_render::backend::RenderBackend>::register_shape::h756d765b60ac17fc (wasm://wasm/0171db26:wasm-function[3247]:0x403d5e)
    at ruffle_core::drawing::Drawing::render::ha35d4584b3592edc (wasm://wasm/0171db26:wasm-function[628]:0x1e1622)
```

# Player Info
Allows script access: true
Renderer: WebGL

# Page Info
Page URL: https://armorgames.com/play/6507/operation-blackknife?tag-referral=space
SWF URL: https://cache.armorgames.com/files/games/operation-blackknife-6507.swf?v=1373587523

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS aarch64 14989.107.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Platform: Linux aarch64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-09-12
Channel: nightly
Built: 2022-09-12T00:14:33.190Z
Commit: 474fd7fa8f74cabf40e7d091ac8e847dffd2814e
Is extension: false

# Metadata
width: 650
height: 400
frameRate: 30
numFrames: 8
swfVersion: 10
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 5292636

**Comment by kjarosh** [comment]
Should be fixed as of the newest version
