### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by Picklenugget1** [ruffle-rs/ruffle#8053]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: UnableToCreateVAO', render/webgl/src/lib.rs:564:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: UnableToCreateVAO', render/webgl/src/lib.rs:564:50
    at W.n.wbg.__wbg_new_df6e6ab7a65c4c4d (https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.e1b4c26055260cecdb25.js:1:5314)
    at std::sync::once::Once::call_once::{{closure}}::h28fa05460bbcf5b3 (wasm://wasm/01814f52:wasm-function[1179]:0x2e329b)
    at std::sync::once::Once::call_inner::h00971925aa1adad3 (wasm://wasm/01814f52:wasm-function[1480]:0x337afb)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h0020dcf09a90a4c0 (wasm://wasm/01814f52:wasm-function[4944]:0x48c08f)
    at std::panicking::rust_panic_with_hook::h84feca33bd4bd229 (wasm://wasm/01814f52:wasm-function[3640]:0x4535e5)
    at core::panicking::panic_fmt::hc171d095bc4a492d (wasm://wasm/01814f52:wasm-function[5133]:0x49283c)
    at core::result::unwrap_failed::h68ab818eb89182b6 (wasm://wasm/01814f52:wasm-function[4230]:0x472e1a)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::hc521ab87d86bebf7 (wasm://wasm/01814f52:wasm-function[701]:0x21d933)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_render::backend::RenderBackend>::register_shape::h756d765b60ac17fc (wasm://wasm/01814f52:wasm-function[3401]:0x441c10)
    at ruffle_core::drawing::Drawing::render::hfde5fa581be09dc2 (wasm://wasm/01814f52:wasm-function[665]:0x20649f)
```

# Player Info
Allows script access: true
Renderer: WebGL

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.67&useloader=1&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1663852238%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F492000%2F492477_Sonny2_Version2_2.swf%3F1242769327%22%2C%22vars%22%3A%7B%22ngio_session_id%22%3A%2288741706.1f8c07ba92d2367c3ac1378cfbc8582b24616bca17c74f%22%2C%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%22632d29dc02d12%22%2C%22NewgroundsAPI_SessionID%22%3A%22NtTsRgEfXvg9NDaI605We79098052a367f27443e8cc1c08e13711b642d68WZ3t%22%2C%22NewgroundsAPI_UserName%22%3A%22picklenugget8%22%2C%22NewgroundsAPI_UserID%22%3A11924416%2C%22ng_username%22%3A%22picklenugget8%22%7D%2C%22width%22%3A800%2C%22height%22%3A575%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F492000%2Fflash_492477_card.png%3Ff1623161197%22%2C%22warnOnUnsupportedContent%22%3Afalse%7D
SWF URL: https://uploads.ungrounded.net/492000/492477_Sonny2_Version2_2.swf?1242769327

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS aarch64 14989.107.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Platform: Linux aarch64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-09-22
Channel: nightly
Built: 2022-09-22T00:19:18.228Z
Commit: c31e9e2b1199494597399fe3fdf9d09663b7bbe2
Is extension: false

# Metadata
width: 800
height: 575
frameRate: 30
numFrames: 449
swfVersion: 9
backgroundColor: #0E1215
isActionScript3: false
uncompressedLength: 24197154

**Comment by kjarosh** [comment]
Should be fixed as of the newest version
