### ISSUE TITLE
Error on https://mahjongtown.com/game/mahjong-games/mahjong-tower/

### ISSUE THREAD

**Issue by BigAl607** [ruffle-rs/ruffle#8082]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: JsValue(InvalidStateError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
Error: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
    at https://mahjongtown.com/scripts/ruffle/ruffle.js:1:26582
    at https://mahjongtown.com/scripts/ruffle/ruffle.js:1:4551
    at web_sys::features::gen_CanvasRenderingContext2d::CanvasRenderingContext2d::draw_image_with_html_canvas_element::h37e1d9b188d431c0 (https://mahjongtown.com/scripts/ruffle/e80928e7593a6b28a58cd8e4c670b73c.wasm:wasm-function[3764]:0x42f305)
    at <ruffle_render_canvas::WebCanvasRenderBackend as ruffle_core::backend::render::RenderBackend>::pop_mask::ha6a53f4d027e5730 (https://mahjongtown.com/scripts/ruffle/e80928e7593a6b28a58cd8e4c670b73c.wasm:wasm-function[812]:0x21e5b5)
    at <ruffle_core::display_object::edit_text::EditText as ruffle_core::display_object::TDisplayObject>::render_self::h99f53da430893117 (https://mahjongtown.com/scripts/ruffle/e80928e7593a6b28a58cd8e4c670b73c.wasm:wasm-function[414]:0x1117cf)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render::h13dd39cfc226902b (https://mahjongtown.com/scripts/ruffle/e80928e7593a6b28a58cd8e4c670b73c.wasm:wasm-function[820]:0x2214d5)
    at ruffle_core::display_object::container::TDisplayObjectContainer::render_children::hab12b1551337d56a (https://mahjongtown.com/scripts/ruffle/e80928e7593a6b28a58cd8e4c670b73c.wasm:wasm-function[945]:0x258c21)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render::h13dd39cfc226902b (https://mahjongtown.com/scripts/ruffle/e80928e7593a6b28a58cd8e4c670b73c.wasm:wasm-function[820]:0x221f9c)
    at ruffle_core::display_object::container::TDisplayObjectContainer::render_children::hab12b1551337d56a (https://mahjongtown.com/scripts/ruffle/e80928e7593a6b28a58cd8e4c670b73c.wasm:wasm-function[945]:0x258c21)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render::h13dd39cfc226902b (https://mahjongtown.com/scripts/ruffle/e80928e7593a6b28a58cd8e4c670b73c.wasm:wasm-function[820]:0x221f9c))', render/canvas/src/lib.rs:682:14

# Player Info
Allows script access: false
Player type: Object
SWF URL: http://mahjongtown.com/gamefiles/mahjong/mahjong-tower.swf
Param movie: http://mahjongtown.com/gamefiles/mahjong/mahjong-tower.swf
Param quality: high
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined

# Page Info
Page URL: https://mahjongtown.com/game/mahjong-games/mahjong-tower/
SWF URL: http://mahjongtown.com/gamefiles/mahjong/mahjong-tower.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-04-22
Channel: nightly
Built: 2021-04-22T00:15:37.772Z
Commit: 8176e0a6336f43a1212a0cd843c02fd56fc2b652

**Comment by relrelb** [comment]
Fixed by #9358.
