### ISSUE TITLE
Error on http://kidsciencechallenge.com/archiveyear3/index.php

### ISSUE THREAD

**Issue by PeggyOCO** [ruffle-rs/ruffle#8110]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: UnableToCreateVAO', render/webgl/src/lib.rs:564:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: UnableToCreateVAO', render/webgl/src/lib.rs:564:50
    at W.n.wbg.__wbg_new_df6e6ab7a65c4c4d (http://kidsciencechallenge.com/ruffle/core.ruffle.9f799b172fb83660e1a8.js:1:5314)
    at std::sync::once::Once::call_once::{{closure}}::ha360d592741a73b3 (wasm://wasm/017ca5a6:wasm-function[1138]:0x2c083f)
    at std::sync::once::Once::call_inner::h00971925aa1adad3 (wasm://wasm/017ca5a6:wasm-function[1447]:0x320287)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h613b00154d20bc2b (wasm://wasm/017ca5a6:wasm-function[4879]:0x478fc0)
    at std::panicking::rust_panic_with_hook::h84feca33bd4bd229 (wasm://wasm/017ca5a6:wasm-function[3630]:0x441860)
    at core::panicking::panic_fmt::hc171d095bc4a492d (wasm://wasm/017ca5a6:wasm-function[5070]:0x47f7eb)
    at core::result::unwrap_failed::h68ab818eb89182b6 (wasm://wasm/017ca5a6:wasm-function[4231]:0x4650d4)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::hc521ab87d86bebf7 (wasm://wasm/017ca5a6:wasm-function[685]:0x20edd4)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_render::backend::RenderBackend>::register_glyph_shape::hac87c7c2ae2e32db (wasm://wasm/017ca5a6:wasm-function[1856]:0x38046e)
    at ruffle_core::font::Font::from_swf_tag::hc2ad40514fa96546 (wasm://wasm/017ca5a6:wasm-function[663]:0x1fd688)
```

# Player Info
Allows script access: true
Renderer: WebGL

# Page Info
Page URL: http://kidsciencechallenge.com/archiveyear3/index.php#/1c
SWF URL: http://kidsciencechallenge.com/archiveyear3/Year3_archive.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-09-18
Channel: nightly
Built: 2022-09-18T00:18:51.800Z
Commit: bfca30fed71342124dd7bc5a8aaa3c3ebf91a2d0
Is extension: false

# Metadata
width: 950
height: 900
frameRate: 30
numFrames: 113
swfVersion: 8
backgroundColor: #FFFFFF
isActionScript3: false
uncompressedLength: 407441

**Comment by kjarosh** [comment]
Should be fixed as of the newest version
