### ISSUE TITLE
Error on https://www.games-kids.com/game/11855/elsa-and-rapunzel-snapchat-rivals.html

### ISSUE THREAD

**Issue by katherine2629** [ruffle-rs/ruffle#8114]
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', core/src/avm2/object/script_object.rs:69:16
Error stack:
```
Error: panicked at 'already borrowed: BorrowMutError', core/src/avm2/object/script_object.rs:69:16
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (https://st.wgplayer.com/ruffle/20220311/core.ruffle.ece9e8fa5a7d72d73689.js:1:7572)
    at std::sync::once::Once::call_once::{{closure}}::h9bbf01ee609e3a75 (https://st.wgplayer.com/ruffle/20220311/e058efe76d47eae2be9a.wasm:wasm-function[1022]:0x2c13d0)
    at std::sync::once::Once::call_inner::h51a70f81ef530383 (https://st.wgplayer.com/ruffle/20220311/e058efe76d47eae2be9a.wasm:wasm-function[1462]:0x3307cf)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h360f2d0dfec34f5b (https://st.wgplayer.com/ruffle/20220311/e058efe76d47eae2be9a.wasm:wasm-function[4911]:0x480d1f)
    at std::panicking::rust_panic_with_hook::h12b2f0179ff84c92 (https://st.wgplayer.com/ruffle/20220311/e058efe76d47eae2be9a.wasm:wasm-function[3232]:0x4248e9)
    at core::panicking::panic_fmt::hf0d93ec1ac504cf9 (https://st.wgplayer.com/ruffle/20220311/e058efe76d47eae2be9a.wasm:wasm-function[5196]:0x48cdc8)
    at core::result::unwrap_failed::hd5a60243cf946632 (https://st.wgplayer.com/ruffle/20220311/e058efe76d47eae2be9a.wasm:wasm-function[4134]:0x468825)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::init_property::hf377828f32467ca3 (https://st.wgplayer.com/ruffle/20220311/e058efe76d47eae2be9a.wasm:wasm-function[483]:0x18a5e3)
    at ruffle_core::avm2::activation::Activation::run_actions::h84679fe188db2bed (https://st.wgplayer.com/ruffle/20220311/e058efe76d47eae2be9a.wasm:wasm-function[313]:0x1e8bf)
    at ruffle_core::avm2::function::Executable::exec::h5a497f7edc9101fd (https://st.wgplayer.com/ruffle/20220311/e058efe76d47eae2be9a.wasm:wasm-function[702]:0x22ced1)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.games-kids.com/game/11855/elsa-and-rapunzel-snapchat-rivals.html
SWF URL: https://www.games-kids.com/files/swf/elsa-and-rapunzel-snapchat-rivals-1465814694.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-03-10
Channel: nightly
Built: 2022-03-10T00:17:15.298Z
Commit: 5a1e41752672f4d0f81a5790e465c20c798a29c9
Is extension: false

**Comment by swfgamefiles** [comment]
seriously lmao
