### ISSUE TITLE
Error on http://www.gamekidgame.com/christmas_games/deep_freeze.html

### ISSUE THREAD

**Issue by lewandovski7** [ruffle-rs/ruffle#8125]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:493:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:493:50
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (http://www.gamekidgame.com/ruffle2/ruffle.js:1:7576)
    at std::sync::once::Once::call_once::{{closure}}::h8d5062b5fa07a345 (http://www.gamekidgame.com/ruffle2/28a5ba98f2c7feadc6e7.wasm:wasm-function[887]:0x236b47)
    at std::sync::once::Once::call_inner::h96e3a490169c6c27 (http://www.gamekidgame.com/ruffle2/28a5ba98f2c7feadc6e7.wasm:wasm-function[1124]:0x28f8b7)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h845e5fc77b435882 (http://www.gamekidgame.com/ruffle2/28a5ba98f2c7feadc6e7.wasm:wasm-function[3943]:0x410bd2)
    at std::panicking::rust_panic_with_hook::h2d9079427a2d996a (http://www.gamekidgame.com/ruffle2/28a5ba98f2c7feadc6e7.wasm:wasm-function[2819]:0x3a7343)
    at rust_begin_unwind (http://www.gamekidgame.com/ruffle2/28a5ba98f2c7feadc6e7.wasm:wasm-function[4156]:0x4165c9)
    at core::panicking::panic_fmt::h1fea623755fffed7 (http://www.gamekidgame.com/ruffle2/28a5ba98f2c7feadc6e7.wasm:wasm-function[4307]:0x41d334)
    at core::result::unwrap_failed::he87c4da48746e896 (http://www.gamekidgame.com/ruffle2/28a5ba98f2c7feadc6e7.wasm:wasm-function[3486]:0x3fdfc1)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::h707d30d281cf901d (http://www.gamekidgame.com/ruffle2/28a5ba98f2c7feadc6e7.wasm:wasm-function[627]:0x1ad9d6)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::register_glyph_shape::h667e7cd8b004f4b0 (http://www.gamekidgame.com/ruffle2/28a5ba98f2c7feadc6e7.wasm:wasm-function[2198]:0x356377)
```

# Player Info
Allows script access: true

# Page Info
Page URL: http://www.gamekidgame.com/christmas_games/deep_freeze.html
SWF URL: http://www.gamekidgame.com/christmas_games/deepfreeze.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-08-04
Channel: nightly
Built: 2021-08-04T00:13:29.267Z
Commit: d40cf5aee4ca7a82120bb9b7fffef72a01c6980e
Is extension: false

**Comment by kjarosh** [comment]
Should be fixed as of the newest version
