### ISSUE TITLE
Error on https://fgn.cdn.serverable.com/common/flashes/nf/chat_with_elita/index.html

### ISSUE THREAD

**Issue by punkz4life** [ruffle-rs/ruffle#8126]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/html/text_format.rs:622:58
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/html/text_format.rs:622:58
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (https://fgn.cdn.serverable.com/common/flashes/js/ruffle211222/ruffle.js:1:6703)
    at std::sync::once::Once::call_once::{{closure}}::h2a5914e357df5b02 (https://fgn.cdn.serverable.com/common/flashes/js/ruffle211222/c5c02c4e65c1c4423a97.wasm:wasm-function[990]:0x30f0ab)
    at std::sync::once::Once::call_inner::hf9144d66ddc67dec (https://fgn.cdn.serverable.com/common/flashes/js/ruffle211222/c5c02c4e65c1c4423a97.wasm:wasm-function[1195]:0x354b94)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h2b08ffde388f7cc2 (https://fgn.cdn.serverable.com/common/flashes/js/ruffle211222/c5c02c4e65c1c4423a97.wasm:wasm-function[4712]:0x505beb)
    at std::panicking::rust_panic_with_hook::h606d7c7f7a423b98 (https://fgn.cdn.serverable.com/common/flashes/js/ruffle211222/c5c02c4e65c1c4423a97.wasm:wasm-function[3248]:0x4b1c8a)
    at rust_begin_unwind (https://fgn.cdn.serverable.com/common/flashes/js/ruffle211222/c5c02c4e65c1c4423a97.wasm:wasm-function[4776]:0x507340)
    at core::panicking::panic_fmt::h6314b5c91abe7349 (https://fgn.cdn.serverable.com/common/flashes/js/ruffle211222/c5c02c4e65c1c4423a97.wasm:wasm-function[4991]:0x512348)
    at core::panicking::panic::hec1fc057bd0baf0b (https://fgn.cdn.serverable.com/common/flashes/js/ruffle211222/c5c02c4e65c1c4423a97.wasm:wasm-function[4709]:0x505451)
    at ruffle_core::html::text_format::FormatSpans::from_html::h473734bc74e7e6ed (https://fgn.cdn.serverable.com/common/flashes/js/ruffle211222/c5c02c4e65c1c4423a97.wasm:wasm-function[320]:0x85ec2)
    at ruffle_core::display_object::edit_text::EditText::set_html_text::h7828b79a1794b861 (https://fgn.cdn.serverable.com/common/flashes/js/ruffle211222/c5c02c4e65c1c4423a97.wasm:wasm-function[3225]:0x4adccd)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: chat_with_elita.swf
Param movie: chat_with_elita.swf
Param quality: high
Param bgcolor: #C9B59B
Param play: true
Param loop: true
Param wmode: window
Param scale: showall
Param menu: true
Param devicefont: false
Param allowScriptAccess: sameDomain
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://fgn.cdn.serverable.com/common/flashes/nf/chat_with_elita/index.html?d=20080322121745
SWF URL: https://fgn.cdn.serverable.com/common/flashes/nf/chat_with_elita/chat_with_elita.swf

# Browser Info
Useragent: Mozilla/5.0 (Linux; Android 11) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-12-22
Channel: nightly
Built: 2021-12-22T00:14:15.814Z
Commit: 74ab24c0c3345025a1b7297c526c37783ecc9990
Is extension: false

**Comment by kjarosh** [comment]
Should be fixed by https://github.com/ruffle-rs/ruffle/pull/14953
