### ISSUE TITLE
Error on chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/player.html

### ISSUE THREAD

**Issue by vtrevisa** [ruffle-rs/ruffle#8128]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: UnableToCreateVAO', render/webgl/src/lib.rs:564:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: UnableToCreateVAO', render/webgl/src/lib.rs:564:50
    at W.e.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:1:6845)
    at std::sync::once::Once::call_once::{{closure}}::h73fc39b54ec29717 (wasm://wasm/017e8b06:wasm-function[1021]:0x2a382a)
    at std::sync::once::Once::call_inner::hb30cfbde5209eed0 (wasm://wasm/017e8b06:wasm-function[1486]:0x3273a0)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h0d648d6ec080e3d2 (wasm://wasm/017e8b06:wasm-function[4920]:0x484684)
    at std::panicking::rust_panic_with_hook::hb09154fa23e06c37 (wasm://wasm/017e8b06:wasm-function[3620]:0x4413e8)
    at core::panicking::panic_fmt::h9e229748e3ae9f9d (wasm://wasm/017e8b06:wasm-function[5073]:0x487acd)
    at core::result::unwrap_failed::h5da0ab182d2c24a1 (wasm://wasm/017e8b06:wasm-function[4217]:0x46b637)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::hffe9537af5eeb8f3 (wasm://wasm/017e8b06:wasm-function[720]:0x232b38)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_render::backend::RenderBackend>::register_glyph_shape::hd15cc6d80d8cf8aa (wasm://wasm/017e8b06:wasm-function[1893]:0x37f21c)
    at ruffle_core::font::Font::from_swf_tag::hdefed7d78749ed68 (wasm://wasm/017e8b06:wasm-function[629]:0x200030)
```

# Player Info
Allows script access: false
Renderer: WebGL

# Page Info
Page URL: chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/player.html?url=http%3A%2F%2Fdata.mybrute.com%2Fswf%2Fuc.swf%3Fv%3D18
SWF URL: http://data.mybrute.com/swf/uc.swf?v=18

# Browser Info
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-09-29
Channel: nightly
Built: 2022-09-29T00:19:25.847Z
Commit: 8f72842b2f186c4098ff277c510af41272d14377
Is extension: true

# Metadata
width: 400
height: 300
frameRate: 30
numFrames: 1
swfVersion: 9
backgroundColor: #FFFFFF
isActionScript3: true
uncompressedLength: 29171

**Comment by kjarosh** [comment]
Should be fixed as of the newest version
