### ISSUE TITLE
Error on https://www.txori.com/index.php

### ISSUE THREAD

**Issue by fireonjames** [ruffle-rs/ruffle#8158]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', render/webgl/src/lib.rs:955:48
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', render/webgl/src/lib.rs:955:48
    at e.wbg.__wbg_new_df6e6ab7a65c4c4d (https://www.txori.com/data/system/ruffle/core.ruffle.4fc04524158d7e5b4290.js:1:5804)
    at std::sync::once::Once::call_once::{{closure}}::h8ea9ab9bf1a6fa87 (<anonymous>:wasm-function[974]:0x2b0a77)
    at std::sync::once::Once::call_inner::hb30cfbde5209eed0 (<anonymous>:wasm-function[1544]:0x356655)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h7b268efc0b6187e5 (<anonymous>:wasm-function[4978]:0x4b83ee)
    at std::panicking::rust_panic_with_hook::hb09154fa23e06c37 (<anonymous>:wasm-function[3685]:0x473835)
    at core::panicking::panic_fmt::h9e229748e3ae9f9d (<anonymous>:wasm-function[5131]:0x4be85b)
    at core::panicking::panic::h6f5024a57ca8da86 (<anonymous>:wasm-function[5033]:0x4b9355)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_render::backend::RenderBackend>::register_bitmap::h80dd6ea7e14e2b56 (<anonymous>:wasm-function[2134]:0x3d616f)
    at ruffle_render::backend::RenderBackend::register_bitmap_png::hbd33338875be4068 (<anonymous>:wasm-function[2412]:0x3f8990)
    at ruffle_core::display_object::movie_clip::MovieClipData::define_bits_lossless::hbda98c7ace4d3eff (<anonymous>:wasm-function[1003]:0x2b966d)
```

# Player Info
Allows script access: true
Renderer: WebGL
Player type: Object
SWF URL: data/documents/dbz/dbdev_dev.swf?id=1655667956
Param quality: high
Param AllowScriptAccess: sameDomain 
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://www.txori.com/index.php?static5/dbdevolution
SWF URL: https://www.txori.com/data/documents/dbz/dbdev_dev.swf?id=1655667956

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-09-23
Channel: nightly
Built: 2022-09-23T00:15:34.189Z
Commit: a17352a01ad50a0f52666c054b22cec51306689c
Is extension: false

# Metadata
width: 500
height: 300
frameRate: 60
numFrames: 1
swfVersion: 8
backgroundColor: #FFFFFF
isActionScript3: false
uncompressedLength: 18400

**Comment by kjarosh** [comment]
Should be fixed as of the newest version
