### ISSUE TITLE
Error on chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/player.html

### ISSUE THREAD

**Issue by SevenSix75** [ruffle-rs/ruffle#8182]
# Error Info
Error name: Error
Error message: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:573:14
Error stack:
```
Error: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:573:14
    at W.e.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:1:6845)
    at std::sync::once::Once::call_once::{{closure}}::h73fc39b54ec29717 (wasm://wasm/017e8c46:wasm-function[1021]:0x2a382a)
    at std::sync::once::Once::call_inner::hb30cfbde5209eed0 (wasm://wasm/017e8c46:wasm-function[1486]:0x3273a0)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h0d648d6ec080e3d2 (wasm://wasm/017e8c46:wasm-function[4920]:0x4846d4)
    at std::panicking::rust_panic_with_hook::hb09154fa23e06c37 (wasm://wasm/017e8c46:wasm-function[3620]:0x441438)
    at core::panicking::panic_fmt::h9e229748e3ae9f9d (wasm://wasm/017e8c46:wasm-function[5073]:0x487b1d)
    at core::option::expect_failed::ha758e0d1c5165b94 (wasm://wasm/017e8c46:wasm-function[5742]:0x49a2fb)
    at ruffle_web::Ruffle::tick::h6af632469979f791 (wasm://wasm/017e8c46:wasm-function[663]:0x215ede)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h60d726a424d28b1d (wasm://wasm/017e8c46:wasm-function[5953]:0x4a1527)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h970c39b503fdbae6 (wasm://wasm/017e8c46:wasm-function[5431]:0x491fcd)
```

# Player Info
Allows script access: false
Renderer: WebGL

# Page Info
Page URL: chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/player.html?url=http%3A%2F%2Fcache.hackedfreegames.com%2Fuploads%2Fgames%2Ffiles%2F6L80ZQS2Q82F.swf%3Fversion%3D1
SWF URL: http://cache.hackedfreegames.com/uploads/games/files/6L80ZQS2Q82F.swf?version=1

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-10-03
Channel: nightly
Built: 2022-10-03T00:16:38.776Z
Commit: 286755962f215c15b87c39ff94bb68adab6b8760
Is extension: true

# Metadata
width: 640
height: 480
frameRate: 25
numFrames: 13
swfVersion: 9
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 4029247

**Comment by n0samu** [comment]
Oh I found it: http://www.hackedfreegames.com/game/3731/mecha-arena

**Comment by Dinnerbone** [comment]
Panic is fixed in https://github.com/ruffle-rs/ruffle/pull/10026
