### ISSUE TITLE
Error on https://game5390.konggames.com/games/bradido/tarnation/frame/me-wanna-Ruffle/

### ISSUE THREAD

**Issue by Linkarf** [ruffle-rs/ruffle#8202]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: UnableToCreateVAO', render/webgl/src/lib.rs:564:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: UnableToCreateVAO', render/webgl/src/lib.rs:564:50
    at W.e.wbg.__wbg_new_df6e6ab7a65c4c4d (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.818bd70895644cf52bfd.js:1:6847)
    at std::sync::once::Once::call_once::{{closure}}::h5de940ebe16b9c56 (wasm://wasm/017fd55a:wasm-function[1024]:0x2a8161)
    at std::sync::once::Once::call_inner::hb30cfbde5209eed0 (wasm://wasm/017fd55a:wasm-function[1487]:0x32b642)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::he4ac1563548cf67a (wasm://wasm/017fd55a:wasm-function[4930]:0x489130)
    at std::panicking::rust_panic_with_hook::hb09154fa23e06c37 (wasm://wasm/017fd55a:wasm-function[3627]:0x445ee2)
    at core::panicking::panic_fmt::h9e229748e3ae9f9d (wasm://wasm/017fd55a:wasm-function[5085]:0x48c5e6)
    at core::result::unwrap_failed::h5da0ab182d2c24a1 (wasm://wasm/017fd55a:wasm-function[4226]:0x47008a)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::h15314ee2f4eb73a3 (wasm://wasm/017fd55a:wasm-function[724]:0x237ae9)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_render::backend::RenderBackend>::register_shape::h150064e54aaf93e3 (wasm://wasm/017fd55a:wasm-function[3387]:0x434a62)
    at ruffle_core::drawing::Drawing::render::h642b5106467241b5 (wasm://wasm/017fd55a:wasm-function[697]:0x22a00d)
```

# Player Info
Allows script access: true
Renderer: WebGL

# Page Info
Page URL: https://game5390.konggames.com/games/bradido/tarnation/frame/me-wanna-Ruffle/?kongregate_host=www.kongregate.com
SWF URL: http://game5390.konggames.com/gamez/0000/5390/live/tarnation_v7p.swf?kongregate_game_version=1205904559

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-10-05
Channel: nightly
Built: 2022-10-05T00:18:27.765Z
Commit: 414e926e6a61b5c5c02d244ab3f4cc8079d7d0ae
Is extension: false

# Metadata
width: 600
height: 400
frameRate: 30
numFrames: 112
swfVersion: 8
backgroundColor: #8DB366
isActionScript3: false
uncompressedLength: 807905

**Comment by kjarosh** [comment]
Should be fixed as of the newest version
