### ISSUE TITLE
Error on https://watchdocumentaries.com/return-man-2-game/

### ISSUE THREAD

**Issue by jaylenr907** [ruffle-rs/ruffle#8215]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: UnableToCreateVAO', render/webgl/src/lib.rs:564:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: UnableToCreateVAO', render/webgl/src/lib.rs:564:50
    at W.e.wbg.__wbg_new_df6e6ab7a65c4c4d (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.a5a3737e9b5245475835.js:1:6847)
    at std::sync::once::Once::call_once::{{closure}}::h6ba3ee80d6ca129f (wasm://wasm/017ff2d2:wasm-function[1024]:0x2a831c)
    at std::sync::once::Once::call_inner::hb30cfbde5209eed0 (wasm://wasm/017ff2d2:wasm-function[1487]:0x32b6b4)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::ha5bfda863bee82e7 (wasm://wasm/017ff2d2:wasm-function[4934]:0x4897bc)
    at std::panicking::rust_panic_with_hook::hb09154fa23e06c37 (wasm://wasm/017ff2d2:wasm-function[3631]:0x446643)
    at core::panicking::panic_fmt::h9e229748e3ae9f9d (wasm://wasm/017ff2d2:wasm-function[5089]:0x48cc72)
    at core::result::unwrap_failed::h5da0ab182d2c24a1 (wasm://wasm/017ff2d2:wasm-function[4229]:0x4706df)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::h15314ee2f4eb73a3 (wasm://wasm/017ff2d2:wasm-function[724]:0x237b6c)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_render::backend::RenderBackend>::register_shape::h150064e54aaf93e3 (wasm://wasm/017ff2d2:wasm-function[3390]:0x435114)
    at ruffle_core::display_object::movie_clip::MovieClipData::define_shape::h1025209e69f73023 (wasm://wasm/017ff2d2:wasm-function[2318]:0x3cad08)
```

# Player Info
Allows script access: true
Renderer: WebGL
Player type: Object
SWF URL: /wp-content/uploads/games/return-man-2/return-man-2.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined

# Page Info
Page URL: https://watchdocumentaries.com/return-man-2-game/
SWF URL: https://watchdocumentaries.com/wp-content/uploads/games/return-man-2/return-man-2.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-10-06
Channel: nightly
Built: 2022-10-06T00:17:35.767Z
Commit: 4b2907ead56e5806f441fcb7e32e1030166cb2d2
Is extension: false

# Metadata
width: 640
height: 450
frameRate: 24
numFrames: 20
swfVersion: 15
backgroundColor: undefined
isActionScript3: false
uncompressedLength: 13290458

**Comment by kjarosh** [comment]
Should be fixed as of the newest version
