### ISSUE TITLE
Error on https://playmariogames.com/luigi-go-adventure

### ISSUE THREAD

**Issue by c4artisan** [ruffle-rs/ruffle#8246]
# Error Info
Error name: Error
Error message: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:573:14
Error stack:
```
Error: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:573:14
    at W.n.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:1:6845)
    at std::sync::once::Once::call_once::{{closure}}::h6ba3ee80d6ca129f (wasm://wasm/01800756:wasm-function[1035]:0x2a7210)
    at std::sync::once::Once::call_inner::hb30cfbde5209eed0 (wasm://wasm/01800756:wasm-function[1498]:0x32a258)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::ha5bfda863bee82e7 (wasm://wasm/01800756:wasm-function[4956]:0x48841a)
    at std::panicking::rust_panic_with_hook::hb09154fa23e06c37 (wasm://wasm/01800756:wasm-function[3645]:0x444624)
    at core::panicking::panic_fmt::h9e229748e3ae9f9d (wasm://wasm/01800756:wasm-function[5111]:0x48b8d0)
    at core::option::expect_failed::ha758e0d1c5165b94 (wasm://wasm/01800756:wasm-function[5785]:0x49e0da)
    at ruffle_web::Ruffle::tick::hcce3b9c42455dc22 (wasm://wasm/01800756:wasm-function[673]:0x21a799)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::hfb791d31cd1d45d9 (wasm://wasm/01800756:wasm-function[6001]:0x4a5445)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h476982f031f67f47 (wasm://wasm/01800756:wasm-function[5472]:0x495d39)
```

# Player Info
Allows script access: true
Renderer: WebGL

# Page Info
Page URL: https://playmariogames.com/luigi-go-adventure
SWF URL: https://playmariogames.com/storage/swf/luigi-go-adventure.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-10-08
Channel: nightly
Built: 2022-10-08T00:21:16.770Z
Commit: 5c9471436371f24f1d95011d21b5cddb7fc4ee7f
Is extension: true

# Metadata
width: 640
height: 480
frameRate: 30
numFrames: 2
swfVersion: 11
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 5529876

**Comment by c4artisan** [comment]
as a side note, this also makes flappy mario and luigi crash
