### ISSUE TITLE
Error on https://simple-education.xyz/swf.html

### ISSUE THREAD

**Issue by j-ack789** [ruffle-rs/ruffle#8253]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:814:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:814:18
    at W.n.wbg.__wbg_new_df6e6ab7a65c4c4d (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.96e8bbc4ac06599a18dc.js:1:6847)
    at std::sync::once::Once::call_once::{{closure}}::h6ba3ee80d6ca129f (wasm://wasm/017fda8e:wasm-function[1035]:0x2a678f)
    at std::sync::once::Once::call_inner::hb30cfbde5209eed0 (wasm://wasm/017fda8e:wasm-function[1500]:0x32a080)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::ha5bfda863bee82e7 (wasm://wasm/017fda8e:wasm-function[4959]:0x487777)
    at std::panicking::rust_panic_with_hook::hb09154fa23e06c37 (wasm://wasm/017fda8e:wasm-function[3648]:0x444156)
    at core::panicking::panic_fmt::h9e229748e3ae9f9d (wasm://wasm/017fda8e:wasm-function[5114]:0x48ac11)
    at core::panicking::panic::h6f5024a57ca8da86 (wasm://wasm/017fda8e:wasm-function[5015]:0x488733)
    at core::ops::function::FnOnce::call_once::h2b64b87dbbaf5054 (wasm://wasm/017fda8e:wasm-function[1131]:0x2c6ff6)
    at ruffle_core::avm1::function::Executable::exec::h7dbb30579b1dd750 (wasm://wasm/017fda8e:wasm-function[371]:0x10b3d7)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h55e375c84faa5088 (wasm://wasm/017fda8e:wasm-function[443]:0x162351)
```

# Player Info
Allows script access: false
Renderer: WebGL

# Page Info
Page URL: https://simple-education.xyz/swf.html?notebook=electricman2
SWF URL: https://simple-education.xyz/swffiles/electricman2.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14989.107.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-10-10
Channel: nightly
Built: 2022-10-10T00:16:25.636Z
Commit: 10c19fef5751b3fd648fb997864f953de9ce9a72
Is extension: false

# Metadata
width: 640
height: 400
frameRate: 18
numFrames: 36
swfVersion: 6
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 3641749

**Comment by n0samu** [comment]
Duplicate of #4932
