### ISSUE TITLE
Error on http://www.hydcd.com/baike/yingyuyinbiao.htm

### ISSUE THREAD

**Issue by lukow** [ruffle-rs/ruffle#8322]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', render/webgl/src/lib.rs:997:48
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', render/webgl/src/lib.rs:997:48
    at U.n.wbg.__wbg_new_f9bb493369a83c12 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:1:6811)
    at std::sync::once::Once::call_once::{{closure}}::hc0104d6321319ac0 (wasm://wasm/0180c36a:wasm-function[1031]:0x296df7)
    at std::sync::once::Once::call_inner::hb30cfbde5209eed0 (wasm://wasm/0180c36a:wasm-function[1488]:0x325ff5)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h6143650320584ffd (wasm://wasm/0180c36a:wasm-function[4910]:0x48851a)
    at std::panicking::rust_panic_with_hook::hb09154fa23e06c37 (wasm://wasm/0180c36a:wasm-function[3620]:0x446e14)
    at core::panicking::panic_fmt::h9e229748e3ae9f9d (wasm://wasm/0180c36a:wasm-function[5129]:0x48cc1e)
    at core::panicking::panic::h6f5024a57ca8da86 (wasm://wasm/0180c36a:wasm-function[4965]:0x48948c)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_render::backend::RenderBackend>::register_bitmap::hb7a796668a56efd1 (wasm://wasm/0180c36a:wasm-function[1996]:0x39ab2c)
    at ruffle_render::backend::RenderBackend::register_bitmap_png::h1f21f5c00975ba74 (wasm://wasm/0180c36a:wasm-function[2618]:0x3ebce7)
    at ruffle_core::display_object::movie_clip::MovieClipData::define_bits_lossless::hab9afb6d65ad6101 (wasm://wasm/0180c36a:wasm-function[1275]:0x2ef77d)
```

# Player Info
Allows script access: true
Renderer: WebGL

# Page Info
Page URL: http://www.hydcd.com/baike/yingyuyinbiao.htm
SWF URL: http://www.hydcd.com/baike/image/flash_yinbiao.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-10-17
Channel: nightly
Built: 2022-10-17T00:20:39.827Z
Commit: 36844e5e2f2476b1c288e4ecaa1ecefbf2ba6972
Is extension: true

# Metadata
width: 530
height: 353
frameRate: 30
numFrames: 2284
swfVersion: 7
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 330938

**Comment by kjarosh** [comment]
Should be fixed as of the newest version
