### ISSUE TITLE
Error on https://www.newgrounds.com/portal/view/546416/format/flash?emulate=flash

### ISSUE THREAD

**Issue by brenc** [ruffle-rs/ruffle#8332]
This was reported by a user on an old game _Robot Wants Fishy_.

https://www.newgrounds.com/portal/view/546416/format/flash?emulate=flash

# Error Info
Error name: Error
Error message: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:573:14
Error stack:
```
Error: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:573:14
    at U.n.wbg.__wbg_new_f9bb493369a83c12 (https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.693681cdd011a3528fc6.js:1:6805)
    at std::sync::once::Once::call_once::{{closure}}::hc0104d6321319ac0 (wasm://wasm/0180b6da:wasm-function[1216]:0x2c247f)
    at std::sync::once::Once::call_inner::hb30cfbde5209eed0 (wasm://wasm/0180b6da:wasm-function[1491]:0x3112a5)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h6143650320584ffd (wasm://wasm/0180b6da:wasm-function[4895]:0x4883bd)
    at std::panicking::rust_panic_with_hook::hb09154fa23e06c37 (wasm://wasm/0180b6da:wasm-function[3599]:0x4461be)
    at core::panicking::panic_fmt::h9e229748e3ae9f9d (wasm://wasm/0180b6da:wasm-function[5114]:0x48cae7)
    at core::option::expect_failed::ha758e0d1c5165b94 (wasm://wasm/0180b6da:wasm-function[5795]:0x49f19a)
    at ruffle_core::display_object::stage::Stage::root_clip::h3d0b0406c4d3620e (wasm://wasm/0180b6da:wasm-function[3573]:0x443bc5)
    at ruffle_web::Ruffle::tick::h4573fa911c064658 (wasm://wasm/0180b6da:wasm-function[650]:0x1e2486)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h37f698ed307a20db (wasm://wasm/0180b6da:wasm-function[6015]:0x4a6878)
```

# Player Info
Allows script access: true
Renderer: WebGL

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.67&useloader=1&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1666098931%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F546000%2F546416_robotfishy_locallock.swf%3F1282786253%22%2C%22vars%22%3A%7B%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%22635037b9c7b69%22%2C%22NewgroundsAPI_SessionID%22%3A%22GnWQbk2fr3qXGjjqyoUx4b0c91a5ab8e093f75ce98c619745779ff26902ewNWu%22%2C%22NewgroundsAPI_UserName%22%3A%22BrentHeMan%22%2C%22NewgroundsAPI_UserID%22%3A1730331%2C%22ng_username%22%3A%22BrentHeMan%22%7D%2C%22width%22%3A640%2C%22height%22%3A480%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F546000%2Fflash_546416.png%3Ff1364587210%22%2C%22warnOnUnsupportedContent%22%3Afalse%7D
SWF URL: https://uploads.ungrounded.net/546000/546416_robotfishy_locallock.swf?1282786253

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-10-18
Channel: nightly
Built: 2022-10-18T00:18:04.871Z
Commit: bdc041677a2c6a04e02a65cbb2b53911dd7467f6
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 60
numFrames: 2
swfVersion: 10
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 2792347

**Comment by n0samu** [comment]
Fixed by #10026
