### ISSUE TITLE
Error on https://hentaifoundrytube.com/uLmZTz*-android&legitimate&and&erza&assfucking&calling*-

### ISSUE THREAD

**Issue by Aa1aegrerg34** [ruffle-rs/ruffle#8335]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: UnableToCreateVAO', render/webgl/src/lib.rs:577:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: UnableToCreateVAO', render/webgl/src/lib.rs:577:50
    at U.n.wbg.__wbg_new_f9bb493369a83c12 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.d2a036980506b72110b9.js:1:6805)
    at std::sync::once::Once::call_once::{{closure}}::hfe7eb802e4d6ae27 (wasm://wasm/0180ae7e:wasm-function[1216]:0x2c2302)
    at std::sync::once::Once::call_inner::hb30cfbde5209eed0 (wasm://wasm/0180ae7e:wasm-function[1491]:0x311126)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h3a8d5809fdb8bfde (wasm://wasm/0180ae7e:wasm-function[4895]:0x4881a0)
    at std::panicking::rust_panic_with_hook::hb09154fa23e06c37 (wasm://wasm/0180ae7e:wasm-function[3599]:0x445fcf)
    at core::panicking::panic_fmt::h9e229748e3ae9f9d (wasm://wasm/0180ae7e:wasm-function[5114]:0x48c8ca)
    at core::result::unwrap_failed::h5da0ab182d2c24a1 (wasm://wasm/0180ae7e:wasm-function[4196]:0x46eadb)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::h8305ec0b73b87067 (wasm://wasm/0180ae7e:wasm-function[692]:0x1fbf57)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_render::backend::RenderBackend>::register_glyph_shape::he426a9472adde85c (wasm://wasm/0180ae7e:wasm-function[1889]:0x36ef4e)
    at ruffle_core::font::Font::from_swf_tag::h9026caf5a0f76f8d (wasm://wasm/0180ae7e:wasm-function[682]:0x1f2f5e)
```

# Player Info
Allows script access: true
Renderer: WebGL
Player type: Object
SWF URL: https://content.gspotpanel.com/games/swf/8/b/1/8b10f99086c5c6e9b637d4dd1e7f5268/8b10f99086c5c6e9b637d4dd1e7f5268.swf
Param movie: https://content.gspotpanel.com/games/swf/8/b/1/8b10f99086c5c6e9b637d4dd1e7f5268/8b10f99086c5c6e9b637d4dd1e7f5268.swf
Param quality: high
Param bgcolor: #000000
Param play: true
Param loop: true
Param menu: true
Param devicefont: false
Param scale: showall
Param wmode: window
Param allowScriptAccess: always
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined

# Page Info
Page URL: https://hentaifoundrytube.com/uLmZTz*-android&legitimate&and&erza&assfucking&calling*-
SWF URL: https://content.gspotpanel.com/games/swf/8/b/1/8b10f99086c5c6e9b637d4dd1e7f5268/8b10f99086c5c6e9b637d4dd1e7f5268.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36 Edg/106.0.1370.47
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-10-19
Channel: nightly
Built: 2022-10-19T00:18:01.234Z
Commit: 058a7a8b661929a2de2931717aad3f6296c8aca0
Is extension: false

# Metadata

**Comment by kjarosh** [comment]
Should be fixed as of the newest version
