### ISSUE TITLE
Error on https://fgn.cdn.serverable.com/common/flashes/nf/breeding_season/index.html

### ISSUE THREAD

**Issue by GodBerl** [ruffle-rs/ruffle#8344]
# Error Info
Error name: Error
Error message: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:573:14
Error stack:
```
Error: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:573:14
    at W.n.wbg.__wbg_new_df6e6ab7a65c4c4d (https://fgn.cdn.serverable.com/common/flashes/js/ruffle221013/core.ruffle.c6fbe1d7464df286fdfb.js:1:6847)
    at std::sync::once::Once::call_once::{{closure}}::hf9ee3cf8881ab9cc (wasm://wasm/01803f76:wasm-function[1029]:0x2a2c96)
    at std::sync::once::Once::call_inner::hb30cfbde5209eed0 (wasm://wasm/01803f76:wasm-function[1493]:0x3285d3)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h9e53a26a8ce616de (wasm://wasm/01803f76:wasm-function[4921]:0x4875eb)
    at std::panicking::rust_panic_with_hook::hb09154fa23e06c37 (wasm://wasm/01803f76:wasm-function[3619]:0x4454f1)
    at core::panicking::panic_fmt::h9e229748e3ae9f9d (wasm://wasm/01803f76:wasm-function[5112]:0x48b363)
    at core::option::expect_failed::ha758e0d1c5165b94 (wasm://wasm/01803f76:wasm-function[5785]:0x49dc89)
    at ruffle_web::Ruffle::tick::hcb865cc692df77c5 (wasm://wasm/01803f76:wasm-function[666]:0x215446)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h8271d03c5ade39ce (wasm://wasm/01803f76:wasm-function[6004]:0x4a5470)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::heb1d46c70fb35121 (wasm://wasm/01803f76:wasm-function[5475]:0x495a7a)
```

# Player Info
Allows script access: true
Renderer: WebGL
Player type: Object
SWF URL: brseason771.swf
Param movie: brseason771.swf
Param quality: high
Param bgcolor: #ffffff
Param play: true
Param loop: true
Param wmode: window
Param scale: showall
Param menu: true
Param devicefont: false
Param allowScriptAccess: sameDomain
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined

# Page Info
Page URL: https://fgn.cdn.serverable.com/common/flashes/nf/breeding_season/index.html?d=20160107225324?e=MTY2NjQ5OTc1Mg%3D%3D
SWF URL: https://fgn.cdn.serverable.com/common/flashes/nf/breeding_season/brseason771.swf

# Browser Info
User Agent: Mozilla/5.0 (Linux; Android 12; SM-F711N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Mobile Safari/537.36
Platform: Linux aarch64
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-10-13
Channel: nightly
Built: 2022-10-13T00:21:23.904Z
Commit: feda41d6c1e22027dbebfc157087050adc4a9acb
Is extension: false

# Metadata
width: 960
height: 720
frameRate: 28
numFrames: 2
swfVersion: 28
backgroundColor: #FFFFFF
isActionScript3: true
uncompressedLength: 26690565

**Comment by kjarosh** [comment]
Should be fixed as of the newest version
