### ISSUE TITLE
Error on https://en.gameslol.net/data/fairyvop11/

### ISSUE THREAD

**Issue by Phatbui1** [ruffle-rs/ruffle#8367]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', render/webgl/src/lib.rs:997:48
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', render/webgl/src/lib.rs:997:48
    at U.n.wbg.__wbg_new_f9bb493369a83c12 (https://en.gameslol.net/data/ruffle/core.ruffle.de235ca0856a5f9a935c.js:1:6805)
    at std::sync::once::Once::call_once::{{closure}}::hfe7eb802e4d6ae27 (wasm://wasm/0180d1c6:wasm-function[1216]:0x2c230d)
    at std::sync::once::Once::call_inner::hb30cfbde5209eed0 (wasm://wasm/0180d1c6:wasm-function[1491]:0x311131)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h3a8d5809fdb8bfde (wasm://wasm/0180d1c6:wasm-function[4897]:0x48898d)
    at std::panicking::rust_panic_with_hook::hb09154fa23e06c37 (wasm://wasm/0180d1c6:wasm-function[3600]:0x446476)
    at core::panicking::panic_fmt::h9e229748e3ae9f9d (wasm://wasm/0180d1c6:wasm-function[5116]:0x48d091)
    at core::panicking::panic::h6f5024a57ca8da86 (wasm://wasm/0180d1c6:wasm-function[4952]:0x4898ff)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_render::backend::RenderBackend>::register_bitmap::he102aac81b0ebb5a (wasm://wasm/0180d1c6:wasm-function[1988]:0x386369)
    at ruffle_core::bitmap::bitmap_data::BitmapData::bitmap_handle::h8b0e5bf967e2b51d (wasm://wasm/0180d1c6:wasm-function[1443]:0x306e92)
    at ruffle_core::bitmap::bitmap_data::BitmapData::draw::h6d74c1245206ace1 (wasm://wasm/0180d1c6:wasm-function[760]:0x219617)
```

# Player Info
Allows script access: true
Renderer: WebGL

# Page Info
Page URL: https://en.gameslol.net/data/fairyvop11/?lang=en
SWF URL: https://en.gameslol.net/data/fairyvop11/game.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-10-21
Channel: nightly
Built: 2022-10-21T00:19:26.241Z
Commit: 4cb122461ee5c892a2801077d3173b531e79cb83
Is extension: false

# Metadata
width: 600
height: 400
frameRate: 30
numFrames: 167
swfVersion: 8
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 19127248

**Comment by kjarosh** [comment]
Should be fixed as of the newest version
