### ISSUE TITLE
Error on https://ruffle.rs/demo/

### ISSUE THREAD

**Issue by coolguy564738** [ruffle-rs/ruffle#8369]
# Error Info
Error name: Error
Error message: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:573:14
Error stack:
```
Error: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:573:14
    at n.wbg.__wbg_new_f9bb493369a83c12 (https://ruffle.rs/demo/966.index.js:1:6474)
    at std::sync::once::Once::call_once::{{closure}}::hc4fb9d82aeb52559 (wasm://wasm/018d9746:wasm-function[1294]:0x2d1e8a)
    at std::sync::once::Once::call_inner::hb30cfbde5209eed0 (wasm://wasm/018d9746:wasm-function[1580]:0x322b23)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hbbc4588f994f9b9b (wasm://wasm/018d9746:wasm-function[5127]:0x4a6256)
    at std::panicking::rust_panic_with_hook::hb09154fa23e06c37 (wasm://wasm/018d9746:wasm-function[3760]:0x4607ab)
    at core::panicking::panic_fmt::h9e229748e3ae9f9d (wasm://wasm/018d9746:wasm-function[5361]:0x4afa26)
    at core::option::expect_failed::ha758e0d1c5165b94 (wasm://wasm/018d9746:wasm-function[6090]:0x4c2ec6)
    at ruffle_core::display_object::stage::Stage::root_clip::h976d36b3d597d380 (wasm://wasm/018d9746:wasm-function[3733]:0x45e0ca)
    at ruffle_web::Ruffle::tick::h7b8ba9bde31d7d60 (wasm://wasm/018d9746:wasm-function[717]:0x1ef55d)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h7f784b2d312feefa (wasm://wasm/018d9746:wasm-function[6320]:0x4ca420)
```

# Player Info
Allows script access: false
Renderer: WebGL

# Page Info
Page URL: https://ruffle.rs/demo/

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-10-24
Channel: nightly
Built: 2022-10-24T00:21:19.066Z
Commit: 84f3739ece57f39960563aca60b43eab07c6c329
Is extension: false

# Metadata
width: 720
height: 480
frameRate: 60
numFrames: 2
swfVersion: 18
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 16983323

**Comment by n0samu** [comment]
Hi, what SWF were you trying to play?

**Comment by n0samu** [comment]
No information provided, closing
