### ISSUE TITLE
Error on https://mysexgamer.com/game/fapwall-v0-4

### ISSUE THREAD

**Issue by 4445aaaaaaaa** [ruffle-rs/ruffle#8388]
# Error Info
Error name: Error
Error message: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:573:14
Error stack:
```
Error: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:573:14
    at W.n.wbg.__wbg_new_f9bb493369a83c12 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:1:6803)
    at std::sync::once::Once::call_once::{{closure}}::h5f05b50e8dc86d7f (wasm://wasm/01816eca:wasm-function[1217]:0x2c3933)
    at std::sync::once::Once::call_inner::hb30cfbde5209eed0 (wasm://wasm/01816eca:wasm-function[1494]:0x31309f)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h78a41c580a314c21 (wasm://wasm/01816eca:wasm-function[4908]:0x48a7ea)
    at std::panicking::rust_panic_with_hook::hb09154fa23e06c37 (wasm://wasm/01816eca:wasm-function[3605]:0x447fec)
    at core::panicking::panic_fmt::h9e229748e3ae9f9d (wasm://wasm/01816eca:wasm-function[5129]:0x48ef81)
    at core::option::expect_failed::ha758e0d1c5165b94 (wasm://wasm/01816eca:wasm-function[5810]:0x4a1515)
    at ruffle_core::display_object::stage::Stage::root_clip::hc417915b2648292a (wasm://wasm/01816eca:wasm-function[3579]:0x4459f3)
    at ruffle_web::Ruffle::tick::hccc857bfae858e2a (wasm://wasm/01816eca:wasm-function[649]:0x1e32cf)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::hb49ccd392d7eefad (wasm://wasm/01816eca:wasm-function[6031]:0x4a8ccd)
```

# Player Info
Allows script access: true
Renderer: WebGL
Player type: Object
SWF URL: https://v8p5i7f9.ssl.hwcdn.net/games/swf/c/d/8/cd8084b61403a4bc00692a903c0996f2/cd8084b61403a4bc00692a903c0996f2.swf
Param movie: https://v8p5i7f9.ssl.hwcdn.net/games/swf/c/d/8/cd8084b61403a4bc00692a903c0996f2/cd8084b61403a4bc00692a903c0996f2.swf
Param quality: high
Param bgcolor: #000000
Param play: true
Param loop: true
Param wmode: window
Param scale: showall
Param menu: true
Param devicefont: false
Param allowScriptAccess: always
Param SCALE: default
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined

# Page Info
Page URL: https://mysexgamer.com/game/fapwall-v0-4
SWF URL: https://v8p5i7f9.ssl.hwcdn.net/games/swf/c/d/8/cd8084b61403a4bc00692a903c0996f2/cd8084b61403a4bc00692a903c0996f2.swf

# Browser Info
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
Platform: MacIntel
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-10-25
Channel: nightly
Built: 2022-10-25T00:42:50.518Z
Commit: 014982d18e205d86d84eb9cf484ec6bb9a643224
Is extension: true

# Metadata
width: 1500
height: 700
frameRate: 30
numFrames: 2
swfVersion: 9
backgroundColor: #B9C4CE
isActionScript3: true
uncompressedLength: 4043109

**Comment by Dinnerbone** [comment]
Crash was fixed in #10026.
