### ISSUE TITLE
Error on https://game85328.konggames.com/games/Pseudolonewolf/mardek-rpg-chapter-3/frame/3474a3f8-fcd0-4707-9a69-51902e055f2d/

### ISSUE THREAD

**Issue by afeene01** [ruffle-rs/ruffle#8391]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', render/webgl/src/lib.rs:997:48
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', render/webgl/src/lib.rs:997:48
    at W.n.wbg.__wbg_new_f9bb493369a83c12 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.891e9ea1d974528e08b2.js:1:6805)
    at std::sync::once::Once::call_once::{{closure}}::h5b3584428e2c6e9f (wasm://wasm/0181631a:wasm-function[1217]:0x2c3933)
    at std::sync::once::Once::call_inner::hb30cfbde5209eed0 (wasm://wasm/0181631a:wasm-function[1494]:0x3130a1)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h2ad31bbb08635044 (wasm://wasm/0181631a:wasm-function[4902]:0x48a663)
    at std::panicking::rust_panic_with_hook::hb09154fa23e06c37 (wasm://wasm/0181631a:wasm-function[3603]:0x44806e)
    at core::panicking::panic_fmt::h9e229748e3ae9f9d (wasm://wasm/0181631a:wasm-function[5123]:0x48edd4)
    at core::panicking::panic::h6f5024a57ca8da86 (wasm://wasm/0181631a:wasm-function[4957]:0x48b5d5)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_render::backend::RenderBackend>::register_bitmap::he96ae61ab281c30e (wasm://wasm/0181631a:wasm-function[1989]:0x3880de)
    at ruffle_core::bitmap::bitmap_data::BitmapData::bitmap_handle::hd520e365d3fc43ef (wasm://wasm/0181631a:wasm-function[1447]:0x308aae)
    at core::ops::function::FnOnce::call_once::he164035f9486fdf4 (wasm://wasm/0181631a:wasm-function[1103]:0x2987c8)
```

# Player Info
Allows script access: true
Renderer: WebGL

# Page Info
Page URL: https://game85328.konggames.com/games/Pseudolonewolf/mardek-rpg-chapter-3/frame/3474a3f8-fcd0-4707-9a69-51902e055f2d/?kongregate_host=www.kongregate.com
SWF URL: https://game85328.konggames.com/gamez/0008/5328/live/MARDEK3.swf?kongregate_game_version=1282393110

# Browser Info
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
Platform: MacIntel
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-10-26
Channel: nightly
Built: 2022-10-26T00:15:48.681Z
Commit: fd76f67bd22102879e119ccd18d646ae01390048
Is extension: false

# Metadata
width: 720
height: 528
frameRate: 30
numFrames: 554
swfVersion: 9
backgroundColor: #554433
isActionScript3: false
uncompressedLength: 23299145

**Comment by kjarosh** [comment]
Should be fixed as of the newest version
