### ISSUE TITLE
Error on https://www.gameslol.net/one-piece-fighting-1199.html

### ISSUE THREAD

**Issue by shinigami20055555** [ruffle-rs/ruffle#8399]
# Error Info
Error name: Error
Error message: panicked at 'No script object for display object', core/src/avm1/runtime.rs:167:18
Error stack:
```
Error: panicked at 'No script object for display object', core/src/avm1/runtime.rs:167:18
    at W.n.wbg.__wbg_new_f9bb493369a83c12 (chrome-extension://coejhjbfhjdnefogmaaaiffljbgcpdko/dist/966.js:1:6803)
    at std::sync::once::Once::call_once::{{closure}}::h5b3584428e2c6e9f (wasm://wasm/0181631a:wasm-function[1217]:0x2c3933)
    at std::sync::once::Once::call_inner::hb30cfbde5209eed0 (wasm://wasm/0181631a:wasm-function[1494]:0x3130a1)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h2ad31bbb08635044 (wasm://wasm/0181631a:wasm-function[4902]:0x48a663)
    at std::panicking::rust_panic_with_hook::hb09154fa23e06c37 (wasm://wasm/0181631a:wasm-function[3603]:0x44806e)
    at core::panicking::panic_fmt::h9e229748e3ae9f9d (wasm://wasm/0181631a:wasm-function[5123]:0x48edd4)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::h9315fd6b7f9935e2 (wasm://wasm/0181631a:wasm-function[1903]:0x37409c)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::hff40a014e6db0094 (wasm://wasm/0181631a:wasm-function[485]:0x16d48b)
    at ruffle_core::display_object::movie_clip::MovieClip::place_object::hd624a96911c0b93c (wasm://wasm/0181631a:wasm-function[1252]:0x2cc92f)
    at <ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::construct_frame::h9162480b3f146815 (wasm://wasm/0181631a:wasm-function[399]:0x1069cc)
```

# Player Info
Allows script access: true
Renderer: WebGL

# Page Info
Page URL: https://www.gameslol.net/one-piece-fighting-1199.html
SWF URL: https://www.gameslol.net/data/onepiecefighting/game.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-10-26
Channel: nightly
Built: 2022-10-26T00:15:48.681Z
Commit: fd76f67bd22102879e119ccd18d646ae01390048
Is extension: true

# Metadata
width: 800
height: 600
frameRate: 50
numFrames: 1
swfVersion: 15
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 12139505

**Comment by n0samu** [comment]
I'm also getting this crash, along with these warnings immediately before:
```
[WARN  ruffle_core::display_object::movie_clip] DoAction tag in AVM2 movie
[WARN  ruffle_core::display_object::movie_clip] DoAction tag in AVM2 movie
```

**Comment by Lord-McSweeney** [comment]
Even after the mixed AVM fixes, this is still broken with the same panic:
```
thread 'main' panicked at core/src/avm1/runtime.rs:185:18:
No script object for display object
```

**Comment by Lord-McSweeney** [comment]
This no longer panics, so closing this issue in favor of #21673.
