### ISSUE TITLE
Error on https://ducklife2hacked.weebly.com/duck-life-5-hacked.html

### ISSUE THREAD

**Issue by sokah404** [ruffle-rs/ruffle#8408]
# Error Info
Error name: Error
Error message: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:573:14
Error stack:
```
Error: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:573:14
    at W.n.wbg.__wbg_new_f9bb493369a83c12 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:1:6803)
    at std::sync::once::Once::call_once::{{closure}}::h5b3584428e2c6e9f (wasm://wasm/01817672:wasm-function[1219]:0x2c72f4)
    at std::sync::once::Once::call_inner::hb30cfbde5209eed0 (wasm://wasm/01817672:wasm-function[1496]:0x316a03)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h2ad31bbb08635044 (wasm://wasm/01817672:wasm-function[4905]:0x48a8e5)
    at std::panicking::rust_panic_with_hook::hb09154fa23e06c37 (wasm://wasm/01817672:wasm-function[3604]:0x4481b1)
    at core::panicking::panic_fmt::h9e229748e3ae9f9d (wasm://wasm/01817672:wasm-function[5126]:0x48f07c)
    at core::option::expect_failed::ha758e0d1c5165b94 (wasm://wasm/01817672:wasm-function[5807]:0x4a1610)
    at ruffle_core::display_object::stage::Stage::root_clip::h45eb1d59f3fecb3e (wasm://wasm/01817672:wasm-function[3578]:0x445bb8)
    at ruffle_web::Ruffle::tick::h9e2be084d311cde0 (wasm://wasm/01817672:wasm-function[650]:0x1e6de5)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::hd179cea27987d938 (wasm://wasm/01817672:wasm-function[6028]:0x4a8dc8)
```

# Player Info
Allows script access: true
Renderer: WebGL

# Page Info
Page URL: https://ducklife2hacked.weebly.com/duck-life-5-hacked.html
SWF URL: https://www.hackedarcadegames.com/swf/Duck-Life-Treasure-Hunt-Ldrp13.swf?version=1417497996

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 15054.98.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-10-28
Channel: nightly
Built: 2022-10-28T00:16:16.599Z
Commit: 68471723b365a5d4b4f728e1d193a4d87d3bebdb
Is extension: true

# Metadata
width: 800
height: 450
frameRate: 50
numFrames: 1
swfVersion: 17
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 9346348

**Comment by Lord-McSweeney** [comment]
Panic fixed by #10026.
