### ISSUE TITLE
Error on http://andkon.com/arcade/puzzle/candyconveyor/

### ISSUE THREAD

**Issue by Treborcd** [ruffle-rs/ruffle#8418]
# Error Info
Error name: Error
Error message: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:573:14
Error stack:
```
Error: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:573:14
    at W.n.wbg.__wbg_new_f9bb493369a83c12 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:1:6803)
    at std::sync::once::Once::call_once::{{closure}}::h5b3584428e2c6e9f (wasm://wasm/01817c06:wasm-function[1219]:0x2c7431)
    at std::sync::once::Once::call_inner::hb30cfbde5209eed0 (wasm://wasm/01817c06:wasm-function[1496]:0x316b40)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h2ad31bbb08635044 (wasm://wasm/01817c06:wasm-function[4905]:0x48aa22)
    at std::panicking::rust_panic_with_hook::hb09154fa23e06c37 (wasm://wasm/01817c06:wasm-function[3604]:0x4482ee)
    at core::panicking::panic_fmt::h9e229748e3ae9f9d (wasm://wasm/01817c06:wasm-function[5126]:0x48f1b9)
    at core::option::expect_failed::ha758e0d1c5165b94 (wasm://wasm/01817c06:wasm-function[5807]:0x4a174d)
    at ruffle_core::display_object::stage::Stage::root_clip::h45eb1d59f3fecb3e (wasm://wasm/01817c06:wasm-function[3578]:0x445cf5)
    at ruffle_web::Ruffle::tick::h9e2be084d311cde0 (wasm://wasm/01817c06:wasm-function[650]:0x1e6de5)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::hd179cea27987d938 (wasm://wasm/01817c06:wasm-function[6028]:0x4a8f05)
```

# Player Info
Allows script access: true
Renderer: WebGL

# Page Info
Page URL: http://andkon.com/arcade/puzzle/candyconveyor/
SWF URL: http://andkon.com/arcade/puzzle/candyconveyor/candyconveyor.swf

# Browser Info
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Platform: MacIntel
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-10-30
Channel: nightly
Built: 2022-10-30T00:16:05.457Z
Commit: ee52ce32908d9f50e52c707575c6d404745117dc
Is extension: true

# Metadata
width: 640
height: 480
frameRate: 100
numFrames: 3
swfVersion: 9
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 1252919

**Comment by Lord-McSweeney** [comment]
Fixed by #10026.
