### ISSUE TITLE
Error on https://en.gameslol.net/the-anime-world-972.html

### ISSUE THREAD

**Issue by MinhTrick** [ruffle-rs/ruffle#8428]
# Error Info
Error name: Error
Error message: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:573:14
Error stack:
```
Error: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:573:14
    at U.n.wbg.__wbg_new_f9bb493369a83c12 (https://en.gameslol.net/data/ruffle/core.ruffle.de235ca0856a5f9a935c.js:1:6805)
    at std::sync::once::Once::call_once::{{closure}}::hfe7eb802e4d6ae27 (wasm://wasm/0180d1c6:wasm-function[1216]:0x2c230d)
    at std::sync::once::Once::call_inner::hb30cfbde5209eed0 (wasm://wasm/0180d1c6:wasm-function[1491]:0x311131)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h3a8d5809fdb8bfde (wasm://wasm/0180d1c6:wasm-function[4897]:0x48898d)
    at std::panicking::rust_panic_with_hook::hb09154fa23e06c37 (wasm://wasm/0180d1c6:wasm-function[3600]:0x446476)
    at core::panicking::panic_fmt::h9e229748e3ae9f9d (wasm://wasm/0180d1c6:wasm-function[5116]:0x48d0b7)
    at core::option::expect_failed::ha758e0d1c5165b94 (wasm://wasm/0180d1c6:wasm-function[5797]:0x49f76e)
    at ruffle_core::display_object::stage::Stage::root_clip::h7e071e485ba9854b (wasm://wasm/0180d1c6:wasm-function[3574]:0x443e7d)
    at ruffle_web::Ruffle::tick::h6e92b0763dce0040 (wasm://wasm/0180d1c6:wasm-function[650]:0x1e230b)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::hcbe5b4d015a3dfc7 (wasm://wasm/0180d1c6:wasm-function[6017]:0x4a6e4c)
```

# Player Info
Allows script access: true
Renderer: WebGL

# Page Info
Page URL: https://en.gameslol.net/the-anime-world-972.html
SWF URL: https://en.gameslol.net/data/972.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-10-21
Channel: nightly
Built: 2022-10-21T00:19:26.241Z
Commit: 4cb122461ee5c892a2801077d3173b531e79cb83
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 30
numFrames: 2
swfVersion: 13
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 7094720

**Comment by Lord-McSweeney** [comment]
Panic fixed by #10026, however the game requests an asset from the domain `www.dofreegames.com`, which is down.
