### ISSUE TITLE
Error on https://archive.org/details/flash_supermario63

### ISSUE THREAD

**Issue by Scott-Steinheiser** [ruffle-rs/ruffle#8434]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: UnableToCreateVAO', render/webgl/src/lib.rs:564:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: UnableToCreateVAO', render/webgl/src/lib.rs:564:50
    at W.n.wbg.__wbg_new_df6e6ab7a65c4c4d (https://cors.archive.org/cors/emularity_engine_v1/core.ruffle.9f799b172fb83660e1a8.js:1:5314)
    at std::sync::once::Once::call_once::{{closure}}::ha360d592741a73b3 (wasm://wasm/017cacaa:wasm-function[1138]:0x2c083f)
    at std::sync::once::Once::call_inner::h00971925aa1adad3 (wasm://wasm/017cacaa:wasm-function[1447]:0x320287)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h613b00154d20bc2b (wasm://wasm/017cacaa:wasm-function[4879]:0x478fc0)
    at std::panicking::rust_panic_with_hook::h84feca33bd4bd229 (wasm://wasm/017cacaa:wasm-function[3630]:0x441860)
    at core::panicking::panic_fmt::hc171d095bc4a492d (wasm://wasm/017cacaa:wasm-function[5070]:0x47f7eb)
    at core::result::unwrap_failed::h68ab818eb89182b6 (wasm://wasm/017cacaa:wasm-function[4231]:0x4650d4)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::hc521ab87d86bebf7 (wasm://wasm/017cacaa:wasm-function[685]:0x20edd4)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_render::backend::RenderBackend>::register_shape::h756d765b60ac17fc (wasm://wasm/017cacaa:wasm-function[3390]:0x4308a4)
    at ruffle_core::display_object::movie_clip::MovieClipData::define_shape::hec5660356a07ee20 (wasm://wasm/017cacaa:wasm-function[2263]:0x3c6078)
```

# Player Info
Allows script access: false
Renderer: WebGL

# Page Info
Page URL: https://archive.org/details/flash_supermario63

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14989.108.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-09-19
Channel: nightly
Built: 2022-09-19T00:15:10.357Z
Commit: 9b9c95bfe28cb862d44e9517e94e9de73acd9de3
Is extension: false

# Metadata
width: 450
height: 300
frameRate: 32
numFrames: 25
swfVersion: 8
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 19339460

**Comment by kjarosh** [comment]
Should be fixed as of the newest version
