### ISSUE TITLE
Error on https://ruffle.rs/demo/

### ISSUE THREAD

**Issue by luki531** [ruffle-rs/ruffle#8436]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: UnableToCreateVAO', render/webgl/src/lib.rs:577:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: UnableToCreateVAO', render/webgl/src/lib.rs:577:50
    at n.wbg.__wbg_new_f9bb493369a83c12 (https://ruffle.rs/demo/966.index.js:1:6474)
    at std::sync::once::Once::call_once::{{closure}}::ha9223c98442fc27b (wasm://wasm/018ee4ee:wasm-function[1299]:0x2d9dae)
    at std::sync::once::Once::call_inner::hb30cfbde5209eed0 (wasm://wasm/018ee4ee:wasm-function[1586]:0x32b308)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h039a278984da6dca (wasm://wasm/018ee4ee:wasm-function[5133]:0x4aa60d)
    at std::panicking::rust_panic_with_hook::hb09154fa23e06c37 (wasm://wasm/018ee4ee:wasm-function[3759]:0x4649c4)
    at core::panicking::panic_fmt::h9e229748e3ae9f9d (wasm://wasm/018ee4ee:wasm-function[5367]:0x4b3ed3)
    at core::result::unwrap_failed::h5da0ab182d2c24a1 (wasm://wasm/018ee4ee:wasm-function[4398]:0x48f994)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::hbce23e6441888471 (wasm://wasm/018ee4ee:wasm-function[761]:0x20d008)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_render::backend::RenderBackend>::register_glyph_shape::h37e57ed068e68360 (wasm://wasm/018ee4ee:wasm-function[1987]:0x38a52b)
    at ruffle_core::font::Font::from_swf_tag::h0b63672f17b52bf1 (wasm://wasm/018ee4ee:wasm-function[752]:0x207a32)
```

# Player Info
Allows script access: false
Renderer: WebGL

# Page Info
Page URL: https://ruffle.rs/demo/
SWF URL: https://ruffle.rs/demo/logo-anim.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-11-01
Channel: nightly
Built: 2022-11-01T00:17:44.778Z
Commit: da02dc453d8ef2403dda19b2d48f7f0e7734d6d5
Is extension: false

# Metadata
width: 600
height: 400
frameRate: 30
numFrames: 1
swfVersion: 15
backgroundColor: #31497D
isActionScript3: false
uncompressedLength: 40440

**Comment by kjarosh** [comment]
Should be fixed as of the newest version
