### ISSUE TITLE
Error on https://www.comdotgame.com/play/bdsm-club

### ISSUE THREAD

**Issue by kimlucky1108** [ruffle-rs/ruffle#8455]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: UnableToCreateVAO', render/webgl/src/lib.rs:577:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: UnableToCreateVAO', render/webgl/src/lib.rs:577:50
    at W.n.wbg.__wbg_new_df6e6ab7a65c4c4d (https://echo.comdotgame.com/ruffle/core.ruffle.c6fbe1d7464df286fdfb.js:1:6847)
    at std::sync::once::Once::call_once::{{closure}}::hf9ee3cf8881ab9cc (wasm://wasm/01803f76:wasm-function[1029]:0x2a2c96)
    at std::sync::once::Once::call_inner::hb30cfbde5209eed0 (wasm://wasm/01803f76:wasm-function[1493]:0x3285d3)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h9e53a26a8ce616de (wasm://wasm/01803f76:wasm-function[4921]:0x4875eb)
    at std::panicking::rust_panic_with_hook::hb09154fa23e06c37 (wasm://wasm/01803f76:wasm-function[3619]:0x4454f1)
    at core::panicking::panic_fmt::h9e229748e3ae9f9d (wasm://wasm/01803f76:wasm-function[5112]:0x48b363)
    at core::result::unwrap_failed::h5da0ab182d2c24a1 (wasm://wasm/01803f76:wasm-function[4215]:0x46e462)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::h242271782ef79a90 (wasm://wasm/01803f76:wasm-function[709]:0x22b185)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_render::backend::RenderBackend>::register_shape::h7dab801d8fce0fe7 (wasm://wasm/01803f76:wasm-function[3379]:0x435033)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render_self::hdfaf8b7414baee80 (wasm://wasm/01803f76:wasm-function[2554]:0x3e49ae)
```

# Player Info
Allows script access: true
Renderer: WebGL
Player type: Object
SWF URL: https://echo.comdotgame.com/4x90xhl3k0/games/files/b6b50c9a33569a4146fdcd7335b735c3.swf
Param allowscriptaccess: always
Param bgcolor: ffffff
Param wmode: gpu
Param flashvars: id=2298744
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined
Attribute 6: undefined

# Page Info
Page URL: https://www.comdotgame.com/play/bdsm-club
SWF URL: https://echo.comdotgame.com/4x90xhl3k0/games/files/b6b50c9a33569a4146fdcd7335b735c3.swf

# Browser Info
User Agent: Mozilla/5.0 (Linux; Android 12; SAMSUNG SM-A516N/KSS4DVI2) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/18.0 Chrome/99.0.4844.88 Mobile Safari/537.36
Platform: Linux aarch64
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-10-13
Channel: nightly
Built: 2022-10-13T00:21:23.904Z
Commit: feda41d6c1e22027dbebfc157087050adc4a9acb
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 25
numFrames: 3
swfVersion: 7
backgroundColor: #FFFFFF
isActionScript3: false
uncompressedLength: 8985680

**Comment by kjarosh** [comment]
Should be fixed as of the newest version
