### ISSUE TITLE
Error on https://ruffle.rs/demo/

### ISSUE THREAD

**Issue by TehDomic** [ruffle-rs/ruffle#8461]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: UnableToCreateVAO', render/webgl/src/lib.rs:577:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: UnableToCreateVAO', render/webgl/src/lib.rs:577:50
    at n.wbg.__wbg_new_f9bb493369a83c12 (https://ruffle.rs/demo/662.index.js:1:7102)
    at std::sync::once::Once::call_once::{{closure}}::ha9223c98442fc27b (<anonymous>:wasm-function[1352]:0x30b8d1)
    at std::sync::once::Once::call_inner::hb30cfbde5209eed0 (<anonymous>:wasm-function[1657]:0x35a7c6)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h039a278984da6dca (<anonymous>:wasm-function[5147]:0x4cf653)
    at std::panicking::rust_panic_with_hook::hb09154fa23e06c37 (<anonymous>:wasm-function[3785]:0x489153)
    at core::panicking::panic_fmt::h9e229748e3ae9f9d (<anonymous>:wasm-function[5381]:0x4dbb6c)
    at core::result::unwrap_failed::h5da0ab182d2c24a1 (<anonymous>:wasm-function[4418]:0x4b3d82)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::hbce23e6441888471 (<anonymous>:wasm-function[710]:0x205cc8)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_render::backend::RenderBackend>::register_shape::h22dfdcdffc3d15bd (<anonymous>:wasm-function[3054]:0x451161)
    at ruffle_core::display_object::movie_clip::MovieClipData::define_shape::h8275b90ea2767d74 (<anonymous>:wasm-function[2225]:0x3d8419)
```

# Player Info
Allows script access: false
Renderer: WebGL

# Page Info
Page URL: https://ruffle.rs/demo/

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS armv7l 13597.84.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.187 Safari/537.36
Platform: Linux armv7l
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-11-03
Channel: nightly
Built: 2022-11-03T00:16:35.742Z
Commit: 6dbf78ae59aa325145ca8d55902cbfc3cd23a24e
Is extension: false

# Metadata
width: 672
height: 504
frameRate: 15
numFrames: 14490
swfVersion: 5
backgroundColor: #FFFFFF
isActionScript3: false
uncompressedLength: 19700091

**Comment by n0samu** [comment]
Old issue with no information provided, closing
