### ISSUE TITLE
Error on https://vc2.urmia.ac.ir/p46xtz3pvbcc/

### ISSUE THREAD

**Issue by mohsenzahab** [ruffle-rs/ruffle#8479]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: UnableToCreateVAO', render/webgl/src/lib.rs:577:23
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: UnableToCreateVAO', render/webgl/src/lib.rs:577:23
    at W.n.wbg.__wbg_new_f9bb493369a83c12 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:1:6505)
    at std::sync::once::Once::call_once::{{closure}}::h9abcd8d2861dbb63 (wasm://wasm/0184b59e:wasm-function[837]:0x25dddc)
    at std::sync::once::Once::call_inner::h34aee843864daceb (wasm://wasm/0184b59e:wasm-function[1357]:0x312b20)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h20c00e1373f93c44 (wasm://wasm/0184b59e:wasm-function[4884]:0x498b94)
    at std::panicking::rust_panic_with_hook::h70a0e195f4db2a29 (wasm://wasm/0184b59e:wasm-function[3623]:0x458d57)
    at core::panicking::panic_fmt::h751be80779d42b53 (wasm://wasm/0184b59e:wasm-function[5107]:0x49d548)
    at core::result::unwrap_failed::h2dc706d948c22960 (wasm://wasm/0184b59e:wasm-function[4205]:0x47f0e5)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::hac14c9eb62754981 (wasm://wasm/0184b59e:wasm-function[650]:0x2000a6)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_render::backend::RenderBackend>::register_glyph_shape::h04baf0ad0d41ddd2 (wasm://wasm/0184b59e:wasm-function[1982]:0x3a5604)
    at ruffle_core::font::Font::from_swf_tag::ha252b7d76e48b39b (wasm://wasm/0184b59e:wasm-function[659]:0x203a5e)
```

# Player Info
Allows script access: true
Renderer: WebGL

# Page Info
Page URL: https://vc2.urmia.ac.ir/p46xtz3pvbcc/?session=breezbreezu3yo4yqzkaygsuw6
SWF URL: https://vc2.urmia.ac.ir/common/meetingAS3/launcher/launcher.swf?ver=10.8.0

# Browser Info
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-11-04
Channel: nightly
Built: 2022-11-04T00:16:33.453Z
Commit: d16e9e15118bba9b01527ac042c3c00bb987a23f
Is extension: true

# Metadata
width: 500
height: 375
frameRate: 24
numFrames: 1
swfVersion: 13
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 81134

**Comment by kjarosh** [comment]
Should be fixed as of the newest version
