### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by Geokureli** [ruffle-rs/ruffle#8491]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: UnableToCreateVAO', render/webgl/src/lib.rs:577:23
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: UnableToCreateVAO', render/webgl/src/lib.rs:577:23
    at W.n.wbg.__wbg_new_f9bb493369a83c12 (https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.530da309ab8cea301079.js:1:6507)
    at std::sync::once::Once::call_once::{{closure}}::h9abcd8d2861dbb63 (wasm://wasm/0184b59e:wasm-function[837]:0x25dddc)
    at std::sync::once::Once::call_inner::h34aee843864daceb (wasm://wasm/0184b59e:wasm-function[1357]:0x312b20)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h20c00e1373f93c44 (wasm://wasm/0184b59e:wasm-function[4884]:0x498b94)
    at std::panicking::rust_panic_with_hook::h70a0e195f4db2a29 (wasm://wasm/0184b59e:wasm-function[3623]:0x458d57)
    at core::panicking::panic_fmt::h751be80779d42b53 (wasm://wasm/0184b59e:wasm-function[5107]:0x49d548)
    at core::result::unwrap_failed::h2dc706d948c22960 (wasm://wasm/0184b59e:wasm-function[4205]:0x47f0e5)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::hac14c9eb62754981 (wasm://wasm/0184b59e:wasm-function[650]:0x2000a6)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_render::backend::RenderBackend>::replace_shape::h0da48c9fdee65efc (wasm://wasm/0184b59e:wasm-function[2204]:0x3ca89e)
    at ruffle_core::drawing::Drawing::render::h5ec2238b03ce85f8 (wasm://wasm/0184b59e:wasm-function[671]:0x20e6bd)
```

# Player Info
Allows script access: true
Renderer: WebGL

# Page Info
Page URL: https://www.newgrounds.com/portal/view/270585
SWF URL: https://uploads.ungrounded.net/270000/270585_Marvin_Spectrum.swf?1128809087

# Browser Info
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Platform: MacIntel
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-11-04
Channel: nightly
Built: 2022-11-04T00:16:33.453Z
Commit: d16e9e15118bba9b01527ac042c3c00bb987a23f
Is extension: false

# Metadata
width: 525
height: 275
frameRate: 25
numFrames: 12
swfVersion: 7
backgroundColor: #787485
isActionScript3: false
uncompressedLength: 1819087

**Comment by kjarosh** [comment]
Should be fixed as of the newest version
