### ISSUE TITLE
Error on chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/player.html

### ISSUE THREAD

**Issue by Belegkarnil** [ruffle-rs/ruffle#8494]
# Error Info
Error name: Error
Error message: panicked at 'No script object for display object', core/src/avm1/runtime.rs:167:18
Error stack:
```
Error: panicked at 'No script object for display object', core/src/avm1/runtime.rs:167:18
    at W.n.wbg.__wbg_new_f9bb493369a83c12 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:1:6505)
    at std::sync::once::Once::call_once::{{closure}}::h9abcd8d2861dbb63 (wasm://wasm/0184931e:wasm-function[837]:0x25e443)
    at std::sync::once::Once::call_inner::h34aee843864daceb (wasm://wasm/0184931e:wasm-function[1354]:0x312430)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h20c00e1373f93c44 (wasm://wasm/0184931e:wasm-function[4883]:0x4981ff)
    at std::panicking::rust_panic_with_hook::h70a0e195f4db2a29 (wasm://wasm/0184931e:wasm-function[3622]:0x458a61)
    at core::panicking::panic_fmt::h751be80779d42b53 (wasm://wasm/0184931e:wasm-function[5106]:0x49cb85)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::h3c285de4a6db5e1e (wasm://wasm/0184931e:wasm-function[2155]:0x3c1a4a)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::h68ee7dc86d21738c (wasm://wasm/0184931e:wasm-function[536]:0x1a3b9d)
    at ruffle_core::display_object::movie_clip::MovieClip::place_object::h142f6c0b76cb115f (wasm://wasm/0184931e:wasm-function[1291]:0x3013b1)
    at <ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::construct_frame::h780ec6a95e609bad (wasm://wasm/0184931e:wasm-function[381]:0x10e8ed)
```

# Player Info
Allows script access: false
Renderer: Canvas

# Page Info
Page URL: chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/player.html?url=https%3A%2F%2Fwww.newbiecontest.org%2Fepreuves%2Fjavascript%2FNewbieFlash2.swf
SWF URL: https://www.newbiecontest.org/epreuves/javascript/NewbieFlash2.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-11-07
Channel: nightly
Built: 2022-11-07T00:19:26.394Z
Commit: 2e04ccc8fe806754fd25b6b1c7262e7e5ca37e57
Is extension: true

# Metadata
width: 400
height: 200
frameRate: 24
numFrames: 1
swfVersion: 14
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 71957

**Comment by n0samu** [comment]
I had some trouble accessing the SWF file, so here it is as an attachment: [NewbieFlash2.zip](https://github.com/ruffle-rs/ruffle/files/9953803/NewbieFlash2.zip)

**Comment by Lord-McSweeney** [comment]
This seems to be working now
