### ISSUE TITLE
Error on chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/player.html

### ISSUE THREAD

**Issue by Torukun** [ruffle-rs/ruffle#8497]
# Error Info
Error name: Error
Error message: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:572:9
Error stack:
```
Error: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:572:9
    at W.n.wbg.__wbg_new_f9bb493369a83c12 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:1:6505)
    at std::sync::once::Once::call_once::{{closure}}::h9abcd8d2861dbb63 (wasm://wasm/0184931e:wasm-function[837]:0x25e443)
    at std::sync::once::Once::call_inner::h34aee843864daceb (wasm://wasm/0184931e:wasm-function[1354]:0x312430)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h20c00e1373f93c44 (wasm://wasm/0184931e:wasm-function[4883]:0x4981ff)
    at std::panicking::rust_panic_with_hook::h70a0e195f4db2a29 (wasm://wasm/0184931e:wasm-function[3622]:0x458a61)
    at core::panicking::panic_fmt::h751be80779d42b53 (wasm://wasm/0184931e:wasm-function[5106]:0x49cbb3)
    at core::option::expect_failed::h2290d18a0c9a6a24 (wasm://wasm/0184931e:wasm-function[5767]:0x4aef44)
    at ruffle_core::display_object::stage::Stage::root_clip::h413e2b05659439e4 (wasm://wasm/0184931e:wasm-function[3562]:0x452f14)
    at ruffle_web::Ruffle::tick::h38087431bfe5118f (wasm://wasm/0184931e:wasm-function[639]:0x1f080d)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::hf5b270d4504b5c7d (wasm://wasm/0184931e:wasm-function[6004]:0x4b6a34)
```

# Player Info
Allows script access: false
Renderer: WebGL

# Page Info
Page URL: chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/player.html?url=https%3A%2F%2Fswf.ugamezone.com%2Fswf%2F20190619%2F7cb7a4ad2b7b471183b858094c1706d8.swf
SWF URL: https://swf.ugamezone.com/swf/20190619/7cb7a4ad2b7b471183b858094c1706d8.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-11-07
Channel: nightly
Built: 2022-11-07T00:19:26.394Z
Commit: 2e04ccc8fe806754fd25b6b1c7262e7e5ca37e57
Is extension: true

# Metadata
width: 700
height: 510
frameRate: 30
numFrames: 3
swfVersion: 10
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 6320447

**Comment by kjarosh** [comment]
Should be fixed as of the newest version
