### ISSUE TITLE
Error on https://ruffle.rs/demo/

### ISSUE THREAD

**Issue by NEMo110307** [ruffle-rs/ruffle#8511]
# Error Info
Error name: Error
Error message: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:572:9
Error stack:
```
Error: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:572:9
    at n.wbg.__wbg_new_f9bb493369a83c12 (https://ruffle.rs/demo/966.index.js:1:6942)
    at std::sync::once::Once::call_once::{{closure}}::h64327ef92939c0dc (wasm://wasm/019167f2:wasm-function[1128]:0x2bdaa7)
    at std::sync::once::Once::call_inner::h34aee843864daceb (wasm://wasm/019167f2:wasm-function[1434]:0x321d6e)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h64da0a046ab9c5a3 (wasm://wasm/019167f2:wasm-function[5115]:0x4b5e5a)
    at std::panicking::rust_panic_with_hook::h70a0e195f4db2a29 (wasm://wasm/019167f2:wasm-function[3780]:0x473465)
    at core::panicking::panic_fmt::h751be80779d42b53 (wasm://wasm/019167f2:wasm-function[5354]:0x4bf686)
    at core::option::expect_failed::h2290d18a0c9a6a24 (wasm://wasm/019167f2:wasm-function[6064]:0x4d27cc)
    at ruffle_core::display_object::stage::Stage::root_clip::hf8974c914f24f656 (wasm://wasm/019167f2:wasm-function[3720]:0x46d918)
    at ruffle_web::Ruffle::tick::h1efcb3000575d49d (wasm://wasm/019167f2:wasm-function[703]:0x1fa683)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h100fe08e4d0257ee (wasm://wasm/019167f2:wasm-function[6305]:0x4da2d9)
```

# Player Info
Allows script access: false
Renderer: WebGL

# Page Info
Page URL: https://ruffle.rs/demo/

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 15054.98.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-11-09
Channel: nightly
Built: 2022-11-09T00:17:22.202Z
Commit: f31f52f2daf2a26805f9994df63d293fb4a309aa
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 30
numFrames: 2
swfVersion: 10
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 6556598

**Comment by n0samu** [comment]
Hi, what SWF file were you trying to play?

**Comment by n0samu** [comment]
No information provided, closing
