### ISSUE TITLE
Error on chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/player.html

### ISSUE THREAD

**Issue by Gamemaster4285** [ruffle-rs/ruffle#8512]
# Error Info
Error name: Error
Error message: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:572:9
Error stack:
```
Error: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:572:9
    at W.n.wbg.__wbg_new_f9bb493369a83c12 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:1:6430)
    at std::sync::once::Once::call_once::{{closure}}::hade171d180e8c1b3 (wasm://wasm/01847da2:wasm-function[837]:0x25df96)
    at std::sync::once::Once::call_inner::h34aee843864daceb (wasm://wasm/01847da2:wasm-function[1354]:0x311f20)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h2b5ff8f72074c3e7 (wasm://wasm/01847da2:wasm-function[4883]:0x497c2d)
    at std::panicking::rust_panic_with_hook::h70a0e195f4db2a29 (wasm://wasm/01847da2:wasm-function[3622]:0x4584a2)
    at core::panicking::panic_fmt::h751be80779d42b53 (wasm://wasm/01847da2:wasm-function[5106]:0x49c5e1)
    at core::option::expect_failed::h2290d18a0c9a6a24 (wasm://wasm/01847da2:wasm-function[5768]:0x4ae97c)
    at ruffle_core::display_object::stage::Stage::root_clip::h3a092df12ae06787 (wasm://wasm/01847da2:wasm-function[3562]:0x45295b)
    at ruffle_web::Ruffle::tick::h888878a53ecfea0c (wasm://wasm/01847da2:wasm-function[639]:0x1f0392)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h4aa053802fae5111 (wasm://wasm/01847da2:wasm-function[6004]:0x4b629f)
```

# Player Info
Allows script access: false
Renderer: WebGL

# Page Info
Page URL: chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/player.html?url=http%3A%2F%2Fdampgnat.com%2Fadverputt%2FAdverPutt.swf%3Frefresh%3D32
SWF URL: http://dampgnat.com/adverputt/AdverPutt.swf?refresh=32

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 15117.86.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-11-09
Channel: nightly
Built: 2022-11-09T00:16:25.978Z
Commit: f31f52f2daf2a26805f9994df63d293fb4a309aa
Is extension: true

# Metadata
width: 1000
height: 800
frameRate: 30
numFrames: 1
swfVersion: 10
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 1225046

__This error was found in__ **[AdverPutt by DampGnat](http://www.dampgnat.com/adverputt/)**

**Comment by kjarosh** [comment]
Should be fixed as of the newest version
