### ISSUE TITLE
Error on https://zonzaemgame.com/bbs/board.php

### ISSUE THREAD

**Issue by kmz0512** [ruffle-rs/ruffle#8527]
# Error Info
Error name: Error
Error message: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:573:14
Error stack:
```
Error: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:573:14
    at W.e.wbg.__wbg_new_df6e6ab7a65c4c4d (https://zonzaemgame.com/ruffle/core.ruffle.818bd70895644cf52bfd.js:1:6847)
    at std::sync::once::Once::call_once::{{closure}}::h5de940ebe16b9c56 (wasm://wasm/017fd55a:wasm-function[1024]:0x2a8161)
    at std::sync::once::Once::call_inner::hb30cfbde5209eed0 (wasm://wasm/017fd55a:wasm-function[1487]:0x32b642)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::he4ac1563548cf67a (wasm://wasm/017fd55a:wasm-function[4930]:0x489130)
    at std::panicking::rust_panic_with_hook::hb09154fa23e06c37 (wasm://wasm/017fd55a:wasm-function[3627]:0x445ee2)
    at core::panicking::panic_fmt::h9e229748e3ae9f9d (wasm://wasm/017fd55a:wasm-function[5085]:0x48c5e6)
    at core::option::expect_failed::ha758e0d1c5165b94 (wasm://wasm/017fd55a:wasm-function[5755]:0x49ed9a)
    at ruffle_web::Ruffle::tick::heaa97029ab307844 (wasm://wasm/017fd55a:wasm-function[664]:0x21a356)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::he812fc031c8d34a5 (wasm://wasm/017fd55a:wasm-function[5967]:0x4a60cf)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h3bec651515dbb6f4 (wasm://wasm/017fd55a:wasm-function[5444]:0x496a0b)
```

# Player Info
Allows script access: false
Renderer: WebGL

# Page Info
Page URL: https://zonzaemgame.com/bbs/board.php?bo_table=game_bug&wr_id=461
SWF URL: http://www.hackedarcadegames.com/swf/obliterate-everything-2-hp6.swf?version=1360223185

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 Edg/107.0.1418.42
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-10-05
Channel: nightly
Built: 2022-10-05T00:18:27.765Z
Commit: 414e926e6a61b5c5c02d244ab3f4cc8079d7d0ae
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 30
numFrames: 3
swfVersion: 10
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 10515492

**Comment by kjarosh** [comment]
Should be fixed as of the newest version
