### ISSUE TITLE
Error on https://ruffle.rs/demo/

### ISSUE THREAD

**Issue by aChenForLife** [ruffle-rs/ruffle#8552]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:751:33
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:751:33
    at n.wbg.__wbg_new_f9bb493369a83c12 (https://ruffle.rs/demo/966.index.js:1:6942)
    at std::sync::once::Once::call_once::{{closure}}::h64327ef92939c0dc (wasm://wasm/01914c4e:wasm-function[970]:0x27cfbc)
    at std::sync::once::Once::call_inner::h34aee843864daceb (wasm://wasm/01914c4e:wasm-function[1429]:0x31bf90)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h64da0a046ab9c5a3 (wasm://wasm/01914c4e:wasm-function[5115]:0x4b58e1)
    at std::panicking::rust_panic_with_hook::h70a0e195f4db2a29 (wasm://wasm/01914c4e:wasm-function[3791]:0x473ccb)
    at core::panicking::panic_fmt::h751be80779d42b53 (wasm://wasm/01914c4e:wasm-function[5361]:0x4bf293)
    at core::panicking::panic::h8af046397a2bf65d (wasm://wasm/01914c4e:wasm-function[5167]:0x4b678b)
    at core::ops::function::FnOnce::call_once::h209da6a2f93e25fc (wasm://wasm/01914c4e:wasm-function[1320]:0x2f32b0)
    at ruffle_core::avm1::function::Executable::exec::h72458d268ee12cba (wasm://wasm/01914c4e:wasm-function[416]:0xe0361)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h8e74fdcbd1d25127 (wasm://wasm/01914c4e:wasm-function[975]:0x27f1c9)
```

# Player Info
Allows script access: false
Renderer: WebGL

# Page Info
Page URL: https://ruffle.rs/demo/

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS aarch64 14989.107.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Platform: Linux aarch64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-11-12
Channel: nightly
Built: 2022-11-12T00:16:57.512Z
Commit: 08270efee72ab8fe31b1448d76bcda09c8af264e
Is extension: false

# Metadata
width: 640
height: 400
frameRate: 18
numFrames: 36
swfVersion: 6
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 3609377

**Comment by n0samu** [comment]
Hi, what SWF file were you trying to play?

**Comment by aChenForLife** [comment]
2d ko boxing. I won, and it crashed.

**Comment by n0samu** [comment]
Does it happen after you win the first fight, or sometime later? Also, can you provide a link or attachment containing the SWF file? (You can put the SWF into a ZIP file and attach that.)

**Comment by aChenForLife** [comment]
first fight

**Comment by n0samu** [comment]
I'm not having that issue with the copy of the game that I found. Please attach a ZIP file containing the SWF file that you are trying to play, or provide a link to the game.

**Comment by aChenForLife** [comment]
here:
https://mail.google.com/mail/u/0?ui=2&ik=1da0ab4644&attid=0.1&permmsgid=msg-a:r4447373082208267438&view=att&disp=safe&realattid=f_lald54zq0

**Comment by n0samu** [comment]
Hi, unfortunately that link does not work. It looks like you tried to attach it as an email attachment. Please log onto GitHub and upload it to your message there, or upload the file to Google Drive and share the link to that.
