### ISSUE TITLE
Error on http://sonic.sega.jp/riders/ShootingStarStory/

### ISSUE THREAD

**Issue by PedroRafael215** [ruffle-rs/ruffle#8553]
# Error Info
Error name: Error
Error message: panicked at 'string indices out of bounds', core/src/avm2/globals/string.rs:527:34
Error stack:
```
Error: panicked at 'string indices out of bounds', core/src/avm2/globals/string.rs:527:34
    at W.n.wbg.__wbg_new_f9bb493369a83c12 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:1:6897)
    at std::sync::once::Once::call_once::{{closure}}::hade171d180e8c1b3 (wasm://wasm/0184644a:wasm-function[1059]:0x2a649d)
    at std::sync::once::Once::call_inner::h34aee843864daceb (wasm://wasm/0184644a:wasm-function[1352]:0x30d597)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h2b5ff8f72074c3e7 (wasm://wasm/0184644a:wasm-function[4886]:0x497453)
    at std::panicking::rust_panic_with_hook::h70a0e195f4db2a29 (wasm://wasm/0184644a:wasm-function[3635]:0x458a0b)
    at core::panicking::panic_fmt::h751be80779d42b53 (wasm://wasm/0184644a:wasm-function[5116]:0x49bfbb)
    at core::option::expect_failed::h2290d18a0c9a6a24 (wasm://wasm/0184644a:wasm-function[5776]:0x4adf7d)
    at ruffle_core::avm2::globals::string::substr::h97787de91305fdf5 (wasm://wasm/0184644a:wasm-function[1049]:0x2a3c1d)
    at ruffle_core::avm2::function::Executable::exec::h4d97a05bf99efbab (wasm://wasm/0184644a:wasm-function[571]:0x1bb0ea)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::h2d82b5da8735c97c (wasm://wasm/0184644a:wasm-function[601]:0x1d004f)
```
AVM2 stack:
```
    at String/substr()
    at myAS::textAnimation/randomTxtFnc()
    at myAS::textAnimation/textChange()
```

# Player Info
Allows script access: true
Renderer: Canvas

# Page Info
Page URL: http://sonic.sega.jp/riders/ShootingStarStory/
SWF URL: http://sonic.sega.jp/riders/ShootingStarStory/swf/top.swf

# Browser Info
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Platform: MacIntel
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-11-15
Channel: nightly
Built: 2022-11-15T00:15:53.122Z
Commit: 99a4172e2b9672999595b8e3e7774a49e964288a
Is extension: true

# Metadata
width: 800
height: 720
frameRate: 26
numFrames: 177
swfVersion: 9
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 415645

**Comment by n0samu** [comment]
See #9968

**Comment by adrian17** [comment]
The panic should have been fixed by https://github.com/ruffle-rs/ruffle/pull/16571 .
