### ISSUE TITLE
Error on https://www.weblfg.com/ruffle/raftwars2

### ISSUE THREAD

**Issue by BrandgrandRealMe** [ruffle-rs/ruffle#8567]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: UnableToCreateVAO', render/webgl/src/lib.rs:577:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: UnableToCreateVAO', render/webgl/src/lib.rs:577:50
    at W.n.wbg.__wbg_new_df6e6ab7a65c4c4d (https://www.weblfg.com/lib/ruffle/core.ruffle.c00b1522f61b16f6f730.js:1:6847)
    at std::sync::once::Once::call_once::{{closure}}::h6ba3ee80d6ca129f (wasm://wasm/01800756:wasm-function[1035]:0x2a7210)
    at std::sync::once::Once::call_inner::hb30cfbde5209eed0 (wasm://wasm/01800756:wasm-function[1498]:0x32a258)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::ha5bfda863bee82e7 (wasm://wasm/01800756:wasm-function[4956]:0x48841a)
    at std::panicking::rust_panic_with_hook::hb09154fa23e06c37 (wasm://wasm/01800756:wasm-function[3645]:0x444624)
    at core::panicking::panic_fmt::h9e229748e3ae9f9d (wasm://wasm/01800756:wasm-function[5111]:0x48b8d0)
    at core::result::unwrap_failed::h5da0ab182d2c24a1 (wasm://wasm/01800756:wasm-function[4250]:0x46f245)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::h75164fb62a2c6baa (wasm://wasm/01800756:wasm-function[721]:0x234ad8)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_render::backend::RenderBackend>::replace_shape::hbf67d83588b1dbd2 (wasm://wasm/01800756:wasm-function[2244]:0x3bf54d)
    at ruffle_core::drawing::Drawing::render::h3964fdec41108d00 (wasm://wasm/01800756:wasm-function[706]:0x22a3df)
```

# Player Info
Allows script access: true
Renderer: WebGL
Player type: Object
SWF URL: /static/swf/rw2.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined

# Page Info
Page URL: https://www.weblfg.com/ruffle/raftwars2
SWF URL: https://www.weblfg.com/static/swf/rw2.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36 OPR/92.0.0.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-10-08
Channel: nightly
Built: 2022-10-08T00:21:16.770Z
Commit: 5c9471436371f24f1d95011d21b5cddb7fc4ee7f
Is extension: false

# Metadata
width: 700
height: 500
frameRate: 35
numFrames: 17
swfVersion: 11
backgroundColor: #FFFFFF
isActionScript3: false
uncompressedLength: 5061748

**Comment by kjarosh** [comment]
Should be fixed as of the newest version
