### ISSUE TITLE
Error on https://play.dragonfable.com/game/web.asp

### ISSUE THREAD

**Issue by rizwanfirdaus** [ruffle-rs/ruffle#8570]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: UnableToCreateVAO', render/webgl/src/lib.rs:577:23
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: UnableToCreateVAO', render/webgl/src/lib.rs:577:23
    at W.n.wbg.__wbg_new_f9bb493369a83c12 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:1:6972)
    at std::sync::once::Once::call_once::{{closure}}::h868aa5cd1fef1a90 (wasm://wasm/0184666e:wasm-function[1059]:0x2a65b0)
    at std::sync::once::Once::call_inner::h34aee843864daceb (wasm://wasm/0184666e:wasm-function[1352]:0x30d6aa)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h117918d4b59dff10 (wasm://wasm/0184666e:wasm-function[4886]:0x497566)
    at std::panicking::rust_panic_with_hook::h70a0e195f4db2a29 (wasm://wasm/0184666e:wasm-function[3635]:0x458b1e)
    at core::panicking::panic_fmt::h751be80779d42b53 (wasm://wasm/0184666e:wasm-function[5116]:0x49c0ce)
    at core::result::unwrap_failed::h2dc706d948c22960 (wasm://wasm/0184666e:wasm-function[4211]:0x47f11c)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::hde0aaa911201b028 (wasm://wasm/0184666e:wasm-function[644]:0x1f40d1)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_render::backend::RenderBackend>::register_shape::h467527af1937e1d8 (wasm://wasm/0184666e:wasm-function[3444]:0x44b635)
    at ruffle_core::display_object::movie_clip::MovieClipData::define_shape::h9e7a53bbf50606cd (wasm://wasm/0184666e:wasm-function[2238]:0x3d0ad3)
```

# Player Info
Allows script access: true
Renderer: WebGL

# Page Info
Page URL: https://play.dragonfable.com/game/web.asp
SWF URL: https://play.dragonfable.com/game/DFLoader.swf?ver=182987

# Browser Info
User Agent: Mozilla/5.0 (Linux; Android 13; SM-S908E) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Mobile Safari/537.36
Platform: Linux aarch64
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-11-16
Channel: nightly
Built: 2022-11-16T00:18:41.332Z
Commit: b3debc96afab2882c70ee27cf4dd5230874e803b
Is extension: true

# Metadata
width: 750
height: 550
frameRate: 24
numFrames: 10
swfVersion: 8
backgroundColor: #660000
isActionScript3: false
uncompressedLength: 6702

**Comment by shadow-absorber** [comment]
got similar issue

**Comment by kjarosh** [comment]
Should be fixed as of the newest version
