### ISSUE TITLE
Error on https://dragonlord.battleon.com/game/web.asp

### ISSUE THREAD

**Issue by rizwanfirdaus** [ruffle-rs/ruffle#8580]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: UnableToCreateVAO', render/webgl/src/lib.rs:577:23
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: UnableToCreateVAO', render/webgl/src/lib.rs:577:23
    at W.n.wbg.__wbg_new_f9bb493369a83c12 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:1:6972)
    at std::sync::once::Once::call_once::{{closure}}::h868aa5cd1fef1a90 (wasm://wasm/0184dde6:wasm-function[1060]:0x2a6ba8)
    at std::sync::once::Once::call_inner::h34aee843864daceb (wasm://wasm/0184dde6:wasm-function[1353]:0x30d91f)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h117918d4b59dff10 (wasm://wasm/0184dde6:wasm-function[4892]:0x49833f)
    at std::panicking::rust_panic_with_hook::h70a0e195f4db2a29 (wasm://wasm/0184dde6:wasm-function[3646]:0x459986)
    at core::panicking::panic_fmt::h751be80779d42b53 (wasm://wasm/0184dde6:wasm-function[5122]:0x49cea7)
    at core::result::unwrap_failed::h2dc706d948c22960 (wasm://wasm/0184dde6:wasm-function[4220]:0x47fd6f)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::hde0aaa911201b028 (wasm://wasm/0184dde6:wasm-function[645]:0x1f4259)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_render::backend::RenderBackend>::register_shape::h467527af1937e1d8 (wasm://wasm/0184dde6:wasm-function[3454]:0x44c2fd)
    at ruffle_core::display_object::movie_clip::MovieClipData::define_shape::h9e7a53bbf50606cd (wasm://wasm/0184dde6:wasm-function[2243]:0x3d1293)
```

# Player Info
Allows script access: true
Renderer: WebGL

# Page Info
Page URL: https://dragonlord.battleon.com/game/web.asp
SWF URL: https://dragonlord.battleon.com/game/DFLoader.swf?ver=1330461

# Browser Info
User Agent: Mozilla/5.0 (Linux; Android 13; SM-S908E) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Mobile Safari/537.36
Platform: Linux aarch64
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-11-19
Channel: nightly
Built: 2022-11-19T00:15:56.117Z
Commit: 7e2b876ab333dbd10488a5eebc0e5ca958d3f953
Is extension: true

# Metadata
width: 750
height: 550
frameRate: 24
numFrames: 10
swfVersion: 8
backgroundColor: #660000
isActionScript3: false
uncompressedLength: 6702

**Comment by kjarosh** [comment]
Should be fixed as of the newest version
