### ISSUE TITLE
Error on http://andkon.com/arcade/missiledefender/defendyournuts/

### ISSUE THREAD

**Issue by r1kkir0t** [ruffle-rs/ruffle#8618]
# Error Info
Error name: Error
Error message: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:572:9
Error stack:
```
Error: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:572:9
    at W.n.wbg.__wbg_new_f9bb493369a83c12 (chrome-extension://kkjcilhdeegjgnkidmlofbndbjeidgam/dist/966.js:1:6897)
    at std::sync::once::Once::call_once::{{closure}}::h6dceed65b46ff778 (wasm://wasm/01868cf2:wasm-function[1057]:0x29f964)
    at std::sync::once::Once::call_inner::h34aee843864daceb (wasm://wasm/01868cf2:wasm-function[1351]:0x306795)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h5488990682f4686e (wasm://wasm/01868cf2:wasm-function[4917]:0x498ea2)
    at std::panicking::rust_panic_with_hook::h70a0e195f4db2a29 (wasm://wasm/01868cf2:wasm-function[3662]:0x4597b5)
    at core::panicking::panic_fmt::h751be80779d42b53 (wasm://wasm/01868cf2:wasm-function[5151]:0x49dae8)
    at core::option::expect_failed::h2290d18a0c9a6a24 (wasm://wasm/01868cf2:wasm-function[5810]:0x4b0dd2)
    at ruffle_core::display_object::stage::Stage::root_clip::h29828e5fdbf42c0e (wasm://wasm/01868cf2:wasm-function[3599]:0x454a57)
    at ruffle_web::Ruffle::tick::h611e019cdcc4f21d (wasm://wasm/01868cf2:wasm-function[634]:0x1e6711)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h5e114c52879cf21a (wasm://wasm/01868cf2:wasm-function[6044]:0x4b856b)
```

# Player Info
Allows script access: true
Renderer: WebGL

# Page Info
Page URL: http://andkon.com/arcade/missiledefender/defendyournuts/
SWF URL: http://andkon.com/arcade/missiledefender/defendyournuts/defendyournuts.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.5304.107 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-11-24
Channel: nightly
Built: 2022-11-24T00:18:37.581Z
Commit: c10244b0a4a0f0d03df82eecdd8a354d052aa76f
Is extension: true

# Metadata
width: 750
height: 500
frameRate: 30
numFrames: 2
swfVersion: 10
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 2425540

**Comment by Lord-McSweeney** [comment]
You also get
```
Uncaught RuntimeError: unreachable
    at std::panicking::rust_panic_with_hook::h70a0e195f4db2a29 (01870b0e:0x45cefa)
    at core::panicking::panic_fmt::h751be80779d42b53 (01870b0e:0x4a0412)
    at core::option::expect_failed::h2290d18a0c9a6a24 (01870b0e:0x4b37e6)
    at ruffle_web::Ruffle::tick::h611e019cdcc4f21d (01870b0e:0x1ee52e)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h5e114c52879cf21a (01870b0e:0x4bb05a)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hb73bf7feb23ce812 (01870b0e:0x4aa030)
    at S (966.js:1:2576)
    at c (966.js:1:2253)
```

in the console after the original error.

**Comment by NyanCatTW1** [comment]
Here is what I get after running it on commit 0c851ec
```
➜  /home/nyancat/Tools/ruffle git:(master) RUST_BACKTRACE=1 cargo run --release --package=ruffle_desktop -- ~/Downloads/defendyournuts.swf   
    Finished release [optimized] target(s) in 0.31s
     Running `target/release/ruffle_desktop /home/nyancat/Downloads/defendyournuts.swf`
thread 'main' panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:580:9
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic_display
   3: core::panicking::panic_str
   4: core::option::expect_failed
   5: ruffle_core::context::UpdateContext::update_sounds
   6: ruffle_core::player::Player::run_frame
   7: ruffle_core::player::Player::tick
   8: ruffle_desktop::App::run::{{closure}}
   9: winit::platform_impl::platform::x11::EventLoop<T>::run_return::single_iteration
  10: winit::platform_impl::platform::x11::EventLoop<T>::run_return
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
AVM2 stack trace: 
[1]    30159 IOT instruction  RUST_BACKTRACE=1 cargo run --release --package=ruffle_desktop -- 
```

**Comment by Lord-McSweeney** [comment]
Seems to be working fine now.
