### ISSUE TITLE
error report on https://www.freeaddictinggames.com/game/the-great-sperm-race/

### ISSUE THREAD

**Issue by flashliberty5467** [ruffle-rs/ruffle#8619]
### Describe the bug

the game works on puffin browser on chromeos

![great spermrace](https://user-images.githubusercontent.com/64484245/204073765-ef7a59cc-befd-414b-a095-e568f50c5b0d.png)

but yet in google chrome with ruffle i get this image

![Screenshot 2022-11-25 11 30 30 PM](https://user-images.githubusercontent.com/64484245/204073788-189756c0-d458-4043-bc89-14108829cfaf.png)

![swf doesent exist](https://user-images.githubusercontent.com/64484245/204073924-1ea0d2e8-f783-4122-a990-7a2e1d99286d.png)

this is the error report i got

# Player Info
Allows script access: true

# Page Info
Page URL: https://www.freeaddictinggames.com/game/the-great-sperm-race/
SWF URL: https://www.freeaddictinggames.com/loader/ima-vast-preroll.swf?v=2

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 15117.111.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-11-25
Channel: nightly
Built: 2022-11-25T00:16:08.207Z
Commit: 14f27a9e4a2f7c838bb680c98cf8697df2888022
Is extension: true

# Metadata

### Expected behavior

for the game to function on the website

### Affected platform

Browser's extension

### Operating system

ChromeOS

### Browser

Version 107.0.5304.110 (Official Build) (64-bit)

### Additional information

# Error Info
Error name: Error
Error message: Failed to fetch: https://www.freeaddictinggames.com/loader/ima-vast-preroll.swf?v=2
Error stack:
```
Error: Failed to fetch: https://www.freeaddictinggames.com/loader/ima-vast-preroll.swf?v=2
    at N.displayRootMovieDownloadFailedMessage (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/ruffle.js?id=61060355555:1:42937)
    at W.n.wbg.__wbg_displayRootMovieDownloadFailedMessage_c90a7f0f0b73e4df (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:1:6249)
    at <ruffle_web::ui::WebUiBackend as ruffle_core::backend::ui::UiBackend>::display_root_movie_download_failed_message::hee70a46b2ecc5471 (wasm://wasm/01870b0e:wasm-function[6016]:0x4baeff)
    at <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hf5d613163c5b8d3c (wasm://wasm/01870b0e:wasm-function[511]:0x18a783)
    at <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h4f18ce5cbeee944f (wasm://wasm/01870b0e:wasm-function[1006]:0x2979ee)
    at wasm_bindgen_futures::queue::Queue::new::{{closure}}::hb52c7898c215ef92 (wasm://wasm/01870b0e:wasm-function[2158]:0x3c6727)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hda4ce02dc8cb37c1 (wasm://wasm/01870b0e:wasm-function[5485]:0x4aa0c6)
    at closure2917 externref shim (wasm://wasm/01870b0e:wasm-function[5604]:0x4acfdf)
    at C (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:1:2728)
    at c (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:1:2253)
```

# Player Info
Allows script access: true
Renderer: WebGL

# Page Info
Page URL: https://www.freeaddictinggames.com/game/the-great-sperm-race/
SWF URL: https://www.freeaddictinggames.com/loader/ima-vast-preroll.swf?v=2

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 15117.111.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-11-25
Channel: nightly
Built: 2022-11-25T00:16:08.207Z
Commit: 14f27a9e4a2f7c838bb680c98cf8697df2888022
Is extension: true

# Metadata

**Comment by n0samu** [comment]
This site is using a script that conflicts with Ruffle, specifically MooTools. Same problem as #8348, #6065, #2567 and #2463.

**Comment by Lord-McSweeney** [comment]
If you open Chrome Devtools and look at network requests, it's requesting
https://www.freeaddictinggames.com/game/the-great-sperm-race/[object%20Object]
instead of the regular swf file.

**Comment by danielhjacobs** [comment]
I can't see MooTools on this page (anymore at least). On the HTTPS version of this page the content can't work because it's [mixed content](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content). Even if you disable your browsers built-in protection and allow mixed content, the content still doesn't work because of [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS), since the HTTP version of the SWFs are requested, which counts as a different origin. That version of this page can't work without the site owner making changes to the site.

The more interesting issue is on http://www.freeaddictinggames.com/game/the-great-sperm-race/. That page tries to load http://www.freeaddictinggames.com/loader/ima-vast-preroll.swf?v=2 and http://www.freeaddictinggames.com/games/the-great-sperm-race/the-great-sperm-race.swf. Those files both exist, when I click those links they download, and the SWF file plays fine in the demo. There are no CORS errors in the console. However, for reasons which I don't actually know, the Network tab says NS_BINDING_ABORTED for both those files and the console says "Asynchronous error occurred: Invalid SWF: Couldn't read SWF: Invalid data: Invalid SWF"
