### ISSUE TITLE
Error on https://kdata1.com/2016/06/bleach-vs-naruto-26/

### ISSUE THREAD

**Issue by mardenluiz** [ruffle-rs/ruffle#8622]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:507:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:507:50
    at V.e.wbg.__wbg_new_df6e6ab7a65c4c4d (https://kdata1.com/RS/asset/core.ruffle.b8761a63d4d1c4cf146c.js:1:7361)
    at std::sync::once::Once::call_once::{{closure}}::hcbf386cd48bf2059 (wasm://wasm/0169bd9a:wasm-function[1410]:0x2fc922)
    at std::sync::once::Once::call_inner::h00971925aa1adad3 (wasm://wasm/0169bd9a:wasm-function[1369]:0x2f3b00)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h670ec8284b02886c (wasm://wasm/0169bd9a:wasm-function[4781]:0x43e534)
    at std::panicking::rust_panic_with_hook::h84feca33bd4bd229 (wasm://wasm/0169bd9a:wasm-function[3493]:0x4044ee)
    at core::panicking::panic_fmt::hc171d095bc4a492d (wasm://wasm/0169bd9a:wasm-function[4960]:0x443ccd)
    at core::result::unwrap_failed::h68ab818eb89182b6 (wasm://wasm/0169bd9a:wasm-function[4070]:0x427672)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::h7920295a5d3e6f84 (wasm://wasm/0169bd9a:wasm-function[704]:0x2083ed)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_render::backend::RenderBackend>::register_glyph_shape::h51cddeb61686ae05 (wasm://wasm/0169bd9a:wasm-function[1710]:0x349ee3)
    at ruffle_core::font::Font::from_swf_tag::hd57e6a58f20306e9 (wasm://wasm/0169bd9a:wasm-function[637]:0x1e8182)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: game.swf
Param movie: game.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined

# Page Info
Page URL: https://kdata1.com/2016/06/bleach-vs-naruto-26/?1
SWF URL: https://kdata1.com/2016/06/bleach-vs-naruto-26/game.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-08-18
Channel: nightly
Built: 2022-08-18T00:17:22.879Z
Commit: 1e18fc2227772efb8821891f092ad045088c130d
Is extension: false

**Comment by kjarosh** [comment]
Should be fixed as of the newest version
