### ISSUE TITLE
Error on https://www.wowgame.jp/game_html/7145.html

### ISSUE THREAD

**Issue by haruP7** [ruffle-rs/ruffle#8628]
# Error Info
Error name: Error
Error message: panicked at 'No script object for display object', core/src/avm1/runtime.rs:165:18
Error stack:
```
Error: panicked at 'No script object for display object', core/src/avm1/runtime.rs:165:18
    at D.n.wbg.__wbg_new_f9bb493369a83c12 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:1:6897)
    at std::sync::once::Once::call_once::{{closure}}::h0ab5ca72bc5fb51e (wasm://wasm/0190d1aa:wasm-function[927]:0x26ccbe)
    at std::sync::once::Once::call_inner::h34aee843864daceb (wasm://wasm/0190d1aa:wasm-function[1399]:0x3175fd)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h1fcf7cbfc0d55608 (wasm://wasm/0190d1aa:wasm-function[4964]:0x4bc0a8)
    at std::panicking::rust_panic_with_hook::h70a0e195f4db2a29 (wasm://wasm/0190d1aa:wasm-function[3762]:0x47b2d0)
    at core::panicking::panic_fmt::h751be80779d42b53 (wasm://wasm/0190d1aa:wasm-function[5202]:0x4c0dff)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::he6e8c57d19d5d8da (wasm://wasm/0190d1aa:wasm-function[2019]:0x3bfbbc)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::h338003d71f04df9a (wasm://wasm/0190d1aa:wasm-function[481]:0x171d99)
    at ruffle_core::display_object::movie_clip::MovieClip::place_object::hb7fd78b6f218b4a3 (wasm://wasm/0190d1aa:wasm-function[1332]:0x306afc)
    at <ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::construct_frame::h80055f9726fa561e (wasm://wasm/0190d1aa:wasm-function[410]:0x123f74)
```

# Player Info
Allows script access: true
Renderer: WebGL

# Page Info
Page URL: https://www.wowgame.jp/game_html/7145.html
SWF URL: https://www.wowgame.jp/game_files/7145/7145.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-11-27
Channel: nightly
Built: 2022-11-27T00:19:26.108Z
Commit: 0c851ecfdea3b8bd0160d81795c9c0ad7186846b
Is extension: true

# Metadata
width: 800
height: 440
frameRate: 50
numFrames: 2
swfVersion: 17
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 5562121

**Comment by Lord-McSweeney** [comment]
Fixed by #11005
