### ISSUE TITLE
Error on https://h-flash.com/you-cant-escape-this-little-devil-eng/

### ISSUE THREAD

**Issue by calvinnapierh** [ruffle-rs/ruffle#8632]
# Error Info
Error name: Error
Error message: panicked at 'assertion failed: min <= max', /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/cmp.rs:865:9
Error stack:
```
Error: panicked at 'assertion failed: min <= max', /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/cmp.rs:865:9
    at U.n.wbg.__wbg_new_f9bb493369a83c12 (https://h-flash.com/data/ruffle/core.ruffle.7ecc2d52e8f222ff95a4.js:1:6813)
    at std::sync::once::Once::call_once::{{closure}}::hc0104d6321319ac0 (wasm://wasm/0180c36a:wasm-function[1031]:0x296df7)
    at std::sync::once::Once::call_inner::hb30cfbde5209eed0 (wasm://wasm/0180c36a:wasm-function[1488]:0x325ff5)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h6143650320584ffd (wasm://wasm/0180c36a:wasm-function[4910]:0x48851a)
    at std::panicking::rust_panic_with_hook::hb09154fa23e06c37 (wasm://wasm/0180c36a:wasm-function[3620]:0x446e14)
    at core::panicking::panic_fmt::h9e229748e3ae9f9d (wasm://wasm/0180c36a:wasm-function[5129]:0x48cc1e)
    at core::panicking::panic::h6f5024a57ca8da86 (wasm://wasm/0180c36a:wasm-function[4965]:0x48948c)
    at ruffle_core::player::Player::update_drag::h6c256899c0da8d32 (wasm://wasm/0180c36a:wasm-function[1440]:0x31a23b)
    at ruffle_core::player::Player::handle_event::h56a2e42469ea5067 (wasm://wasm/0180c36a:wasm-function[326]:0x82f19)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h3af4c01d4fcd5392 (wasm://wasm/0180c36a:wasm-function[1155]:0x2cccc3)
```

# Player Info
Allows script access: false
Renderer: WebGL

# Page Info
Page URL: https://h-flash.com/you-cant-escape-this-little-devil-eng/
SWF URL: https://h-flash.com/data/swf/2021/11/little-devil-eng.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.5249.126 Safari/537.36 OPR/92.0.4561.11
Platform: Linux i686
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-10-17
Channel: nightly
Built: 2022-10-17T00:20:39.827Z
Commit: 36844e5e2f2476b1c288e4ecaa1ecefbf2ba6972
Is extension: false

# Metadata
width: 800
height: 600
frameRate: 24
numFrames: 175
swfVersion: 41
backgroundColor: #FFFFFF
isActionScript3: true
uncompressedLength: 46121294

**Comment by n0samu** [comment]
Looks like the same problem as #8382

**Comment by Lord-McSweeney** [comment]
Same creator, too.
