### ISSUE TITLE
Error on https://yaldagames.com/game/index.php

### ISSUE THREAD

**Issue by Iujki7788i** [ruffle-rs/ruffle#8639]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: UnableToCreateVAO', render/webgl/src/lib.rs:564:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: UnableToCreateVAO', render/webgl/src/lib.rs:564:50
    at W.n.wbg.__wbg_new_df6e6ab7a65c4c4d (https://yaldagames.com/ruffle/2022-09-19/core.ruffle.9f799b172fb83660e1a8.js:1:5314)
    at std::sync::once::Once::call_once::{{closure}}::ha360d592741a73b3 (wasm://wasm/017cacaa:wasm-function[1138]:0x2c083f)
    at std::sync::once::Once::call_inner::h00971925aa1adad3 (wasm://wasm/017cacaa:wasm-function[1447]:0x320287)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h613b00154d20bc2b (wasm://wasm/017cacaa:wasm-function[4879]:0x478fc0)
    at std::panicking::rust_panic_with_hook::h84feca33bd4bd229 (wasm://wasm/017cacaa:wasm-function[3630]:0x441860)
    at core::panicking::panic_fmt::hc171d095bc4a492d (wasm://wasm/017cacaa:wasm-function[5070]:0x47f7eb)
    at core::result::unwrap_failed::h68ab818eb89182b6 (wasm://wasm/017cacaa:wasm-function[4231]:0x4650d4)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::hc521ab87d86bebf7 (wasm://wasm/017cacaa:wasm-function[685]:0x20edd4)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_render::backend::RenderBackend>::register_shape::h756d765b60ac17fc (wasm://wasm/017cacaa:wasm-function[3390]:0x4308a4)
    at ruffle_core::display_object::movie_clip::MovieClipData::define_shape::hec5660356a07ee20 (wasm://wasm/017cacaa:wasm-function[2263]:0x3c6078)
```

# Player Info
Allows script access: true
Renderer: WebGL
Player type: Object
SWF URL: /game/655/655.swf
Param movie: /game/655/655.swf
Param quality: high
Param play: true
Param loop: true
Param wmode: window
Param scale: showall
Param menu: true
Param allowFullScreen: true
Param devicefont: false
Param allowScriptAccess: always
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined

# Page Info
Page URL: https://yaldagames.com/game/index.php?i=655&width=640&height=720
SWF URL: https://yaldagames.com/game/655/655.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 Edg/107.0.1418.30
Platform: Win32
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-09-19
Channel: nightly
Built: 2022-09-19T00:15:10.357Z
Commit: 9b9c95bfe28cb862d44e9517e94e9de73acd9de3
Is extension: false

# Metadata
width: 900
height: 1000
frameRate: 24
numFrames: 505
swfVersion: 15
backgroundColor: #CCCCCC
isActionScript3: false
uncompressedLength: 9970236

**Comment by kjarosh** [comment]
Should be fixed as of the newest version
