### ISSUE TITLE
Error on https://games.crazygames.com/es_ES/extreme-pamplona/index.html

### ISSUE THREAD

**Issue by CABRERO01** [ruffle-rs/ruffle#8669]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: UnableToCreateVAO', render/webgl/src/lib.rs:577:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: UnableToCreateVAO', render/webgl/src/lib.rs:577:50
    at W.n.wbg.__wbg_new_df6e6ab7a65c4c4d (https://files.crazygames.com/gameframe/ruffle/2022-10-08/core.ruffle.c00b1522f61b16f6f730.js:1:6847)
    at std::sync::once::Once::call_once::{{closure}}::h6ba3ee80d6ca129f (wasm://wasm/01800756:wasm-function[1035]:0x2a7210)
    at std::sync::once::Once::call_inner::hb30cfbde5209eed0 (wasm://wasm/01800756:wasm-function[1498]:0x32a258)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::ha5bfda863bee82e7 (wasm://wasm/01800756:wasm-function[4956]:0x48841a)
    at std::panicking::rust_panic_with_hook::hb09154fa23e06c37 (wasm://wasm/01800756:wasm-function[3645]:0x444624)
    at core::panicking::panic_fmt::h9e229748e3ae9f9d (wasm://wasm/01800756:wasm-function[5111]:0x48b8d0)
    at core::result::unwrap_failed::h5da0ab182d2c24a1 (wasm://wasm/01800756:wasm-function[4250]:0x46f245)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::h75164fb62a2c6baa (wasm://wasm/01800756:wasm-function[721]:0x234ad8)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_render::backend::RenderBackend>::register_glyph_shape::h8de0b3196aeee169 (wasm://wasm/01800756:wasm-function[1910]:0x382491)
    at ruffle_core::font::Font::from_swf_tag::hb1fdb0c7d8fc8ecb (wasm://wasm/01800756:wasm-function[642]:0x20645f)
```

# Player Info
Allows script access: false
Renderer: WebGL

# Page Info
Page URL: https://games.crazygames.com/es_ES/extreme-pamplona/index.html
SWF URL: https://files.crazygames.com/extreme-pamplona/extreme-pamplona.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-10-08
Channel: nightly
Built: 2022-10-08T00:21:16.770Z
Commit: 5c9471436371f24f1d95011d21b5cddb7fc4ee7f
Is extension: false

# Metadata
width: 800
height: 400
frameRate: 24
numFrames: 2
swfVersion: 8
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 1390857

**Comment by kjarosh** [comment]
Should be fixed as of the newest version
