### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by SirAngelThe3rd** [ruffle-rs/ruffle#8678]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:750:32
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:750:32
    at D.n.wbg.__wbg_new_f9bb493369a83c12 (https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.4a4391e10bc6afa5ec80.js:1:6899)
    at std::sync::once::Once::call_once::{{closure}}::h0ab5ca72bc5fb51e (wasm://wasm/0190d8c2:wasm-function[927]:0x26ccbe)
    at std::sync::once::Once::call_inner::h34aee843864daceb (wasm://wasm/0190d8c2:wasm-function[1399]:0x3175fd)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h1fcf7cbfc0d55608 (wasm://wasm/0190d8c2:wasm-function[4964]:0x4bc0a8)
    at std::panicking::rust_panic_with_hook::h70a0e195f4db2a29 (wasm://wasm/0190d8c2:wasm-function[3762]:0x47b2d0)
    at core::panicking::panic_fmt::h751be80779d42b53 (wasm://wasm/0190d8c2:wasm-function[5202]:0x4c0dff)
    at core::panicking::panic::h8af046397a2bf65d (wasm://wasm/0190d8c2:wasm-function[5020]:0x4bd061)
    at core::ops::function::FnOnce::call_once::hbb0991013a5c8917 (wasm://wasm/0190d8c2:wasm-function[1285]:0x2f7225)
    at ruffle_core::avm1::function::Executable::exec::h3aad39b3ff2b2237 (wasm://wasm/0190d8c2:wasm-function[367]:0xefa4b)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::hbeb39f19b62e58f5 (wasm://wasm/0190d8c2:wasm-function[1437]:0x3212e3)
```

# Player Info
Allows script access: true
Renderer: WebGL

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.67&useloader=1&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1669652226%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F484000%2F484931_peeps.swf%3F1509024282%22%2C%22vars%22%3A%7B%22ngio_session_id%22%3A%2213047005.3c37b15a4eb836ef8bbd004ddb4f9a6522e2c210715098%22%2C%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%22638be4a51c7e9%22%2C%22NewgroundsAPI_SessionID%22%3A%22XkoAtTAopwWs48VkL0Zy486ce3b4f1e55729a17c41fa5fd71d61b5a26e0dOm4R%22%2C%22NewgroundsAPI_UserName%22%3A%22S1rC0w%22%2C%22NewgroundsAPI_UserID%22%3A13487502%2C%22ng_username%22%3A%22S1rC0w%22%7D%2C%22width%22%3A640%2C%22height%22%3A450%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F484000%2Fflash_484931_card.png%3Ff1609851325%22%2C%22warnOnUnsupportedContent%22%3Afalse%7D
SWF URL: https://uploads.ungrounded.net/484000/484931_peeps.swf?1509024282

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 15117.111.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-11-28
Channel: nightly
Built: 2022-11-28T00:18:55.230Z
Commit: 5d5a56a7a33408b5a4d27a574c543e8c9365c3b6
Is extension: false

# Metadata
width: 640
height: 450
frameRate: 35
numFrames: 19
swfVersion: 9
backgroundColor: #999999
isActionScript3: false
uncompressedLength: 12314677

**Comment by n0samu** [comment]
Hi, can you tell us what led up to this error? Did it happen at a specific point in the game?

**Comment by n0samu** [comment]
Closing in favor of #8875
