### ISSUE TITLE
Error on https://www.txori.com/index.php

### ISSUE THREAD

**Issue by Doom412** [ruffle-rs/ruffle#8727]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: UnableToCreateVAO', render/webgl/src/lib.rs:577:23
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: UnableToCreateVAO', render/webgl/src/lib.rs:577:23
    at W.n.wbg.__wbg_new_f9bb493369a83c12 (https://www.txori.com/data/system/ruffle/core.ruffle.908f55297e6fed608f53.js:1:6974)
    at std::sync::once::Once::call_once::{{closure}}::h868aa5cd1fef1a90 (wasm://wasm/0184666e:wasm-function[1059]:0x2a65b0)
    at std::sync::once::Once::call_inner::h34aee843864daceb (wasm://wasm/0184666e:wasm-function[1352]:0x30d6aa)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h117918d4b59dff10 (wasm://wasm/0184666e:wasm-function[4886]:0x497566)
    at std::panicking::rust_panic_with_hook::h70a0e195f4db2a29 (wasm://wasm/0184666e:wasm-function[3635]:0x458b1e)
    at core::panicking::panic_fmt::h751be80779d42b53 (wasm://wasm/0184666e:wasm-function[5116]:0x49c0ce)
    at core::result::unwrap_failed::h2dc706d948c22960 (wasm://wasm/0184666e:wasm-function[4211]:0x47f11c)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::hde0aaa911201b028 (wasm://wasm/0184666e:wasm-function[644]:0x1f40d1)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_render::backend::RenderBackend>::register_shape::h467527af1937e1d8 (wasm://wasm/0184666e:wasm-function[3444]:0x44b635)
    at ruffle_core::display_object::movie_clip::MovieClipData::define_shape::h9e7a53bbf50606cd (wasm://wasm/0184666e:wasm-function[2238]:0x3d0ad3)
```

# Player Info
Allows script access: true
Renderer: WebGL
Player type: Object
SWF URL: data/documents/dbz/dbdev_dev.swf?id=1655667956
Param quality: high
Param AllowScriptAccess: sameDomain 
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://www.txori.com/index.php?static5/dbdevolution
SWF URL: https://www.txori.com/data/documents/dbz/dbdev_dev.swf?id=1655667956

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 Edg/107.0.1418.30
Platform: Win32
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-11-16
Channel: nightly
Built: 2022-11-16T00:18:41.332Z
Commit: b3debc96afab2882c70ee27cf4dd5230874e803b
Is extension: false

# Metadata
width: 500
height: 300
frameRate: 60
numFrames: 1
swfVersion: 8
backgroundColor: #FFFFFF
isActionScript3: false
uncompressedLength: 18400

**Comment by kjarosh** [comment]
Should be fixed as of the newest version
