### ISSUE TITLE
Error on https://www.shellshocklive.com/flash/

### ISSUE THREAD

**Issue by Gabriel97434** [ruffle-rs/ruffle#8776]
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', core/src/avm2/object/function_object.rs:138:28
Error stack:
```
Error: panicked at 'already borrowed: BorrowMutError', core/src/avm2/object/function_object.rs:138:28
    at D.n.wbg.__wbg_new_f9bb493369a83c12 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:1:6972)
    at std::sync::once::Once::call_once::{{closure}}::h4f7445f5740cc36b (wasm://wasm/019183be:wasm-function[926]:0x26bfb3)
    at std::sync::once::Once::call_inner::h34aee843864daceb (wasm://wasm/019183be:wasm-function[1401]:0x319534)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h7dfd384227ef6d86 (wasm://wasm/019183be:wasm-function[4989]:0x4bd65f)
    at std::panicking::rust_panic_with_hook::h70a0e195f4db2a29 (wasm://wasm/019183be:wasm-function[3768]:0x47c447)
    at core::panicking::panic_fmt::h751be80779d42b53 (wasm://wasm/019183be:wasm-function[5230]:0x4c24bc)
    at core::result::unwrap_failed::h2dc706d948c22960 (wasm://wasm/019183be:wasm-function[4303]:0x4a15b9)
    at gc_arena::gc_cell::GcCell<T>::write::h9fc6d22963555386 (wasm://wasm/019183be:wasm-function[3279]:0x459992)
    at ruffle_core::avm2::object::TObject::call_method::h7a5a327410c78013 (wasm://wasm/019183be:wasm-function[1173]:0x2bc326)
    at ruffle_core::avm2::object::TObject::get_property::hb755f215a9daa380 (wasm://wasm/019183be:wasm-function[920]:0x26a2cc)
```

# Player Info
Allows script access: true
Renderer: WebGL

# Page Info
Page URL: https://www.shellshocklive.com/flash/
SWF URL: https://www.shellshocklive.com/flash/ShellShockLive.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 15117.111.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-12-13
Channel: nightly
Built: 2022-12-13T00:16:27.259Z
Commit: 02360b28dca80263c8e93cde2467c487688770ac
Is extension: true

# Metadata
width: 800
height: 600
frameRate: 40
numFrames: 1
swfVersion: 10
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 20107

**Comment by Lord-McSweeney** [comment]
No longer panics, but still fails to load. Error: `VerifyError: Trait isPlaying in class RoomBox has same name as trait isPlaying in class MovieClip, but does not override it`.
