### ISSUE TITLE
Error on https://play.cplegacy.com/

### ISSUE THREAD

**Issue by ArchangelAgent** [ruffle-rs/ruffle#8811]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:507:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:507:50
    at V.e.wbg.__wbg_new_df6e6ab7a65c4c4d (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.7.10/core.ruffle.9ad35a5d0da0269c48da.js:1:6065)
    at std::sync::once::Once::call_once::{{closure}}::h9f9c02c969530d8e (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.7.10/0a8f331705ed868db888.wasm:wasm-function[1195]:0x2abb35)
    at std::sync::once::Once::call_inner::hecc7c66a7de7e98e (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.7.10/0a8f331705ed868db888.wasm:wasm-function[1371]:0x2e2adb)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hc9fc7eed6fb9d9d0 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.7.10/0a8f331705ed868db888.wasm:wasm-function[4669]:0x4251d1)
    at std::panicking::rust_panic_with_hook::h8888bbc201384d7b (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.7.10/0a8f331705ed868db888.wasm:wasm-function[3069]:0x3d78a4)
    at core::panicking::panic_fmt::h18b15be283411c65 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.7.10/0a8f331705ed868db888.wasm:wasm-function[4853]:0x42b373)
    at core::result::unwrap_failed::he84b58f6b44a7df4 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.7.10/0a8f331705ed868db888.wasm:wasm-function[3994]:0x410320)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::hf98f89811b2241ba (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.7.10/0a8f331705ed868db888.wasm:wasm-function[704]:0x1f5794)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::register_glyph_shape::hda5a868394eef002 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.7.10/0a8f331705ed868db888.wasm:wasm-function[1708]:0x331eca)
    at ruffle_core::font::Font::from_swf_tag::h80330225ac07ba9c (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.7.10/0a8f331705ed868db888.wasm:wasm-function[656]:0x1da440)
    at ruffle_core::player::Player::set_root_movie::h95ae13a6789c3efb (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.7.10/0a8f331705ed868db888.wasm:wasm-function[372]:0xed4ed)
    at <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hb637ed2dc4e764b2 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.7.10/0a8f331705ed868db888.wasm:wasm-function[570]:0x1a86b9)
    at <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hff435146d5130798 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.7.10/0a8f331705ed868db888.wasm:wasm-function[1919]:0x358370)
    at wasm_bindgen_futures::queue::Queue::new::{{closure}}::hb655bdde396642d8 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.7.10/0a8f331705ed868db888.wasm:wasm-function[2120]:0x37a0a8)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hcc0ab244b5baa4b2 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.7.10/0a8f331705ed868db888.wasm:wasm-function[5213]:0x435c13)
    at k (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.7.10/core.ruffle.9ad35a5d0da0269c48da.js:1:3014)
    at c (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.7.10/core.ruffle.9ad35a5d0da0269c48da.js:1:2437)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://play.cplegacy.com/
SWF URL: https://cpl-prod.b-cdn.net/assets/media/swf/books/boot.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-07-10
Channel: nightly
Built: 2022-07-10T00:19:08.480Z
Commit: 78ebf06f55eff05db6939166973bbfa08641300b
Is extension: false

**Comment by Poopooracoocoo** [comment]
@ArchangelAgent In which minigame did you see this error?

**Comment by kjarosh** [comment]
Should be fixed as of the newest version
