### ISSUE TITLE
Error on http://www.andkon.com/arcade/puzzle/candyconveyor/

### ISSUE THREAD

**Issue by charleslavoie1** [ruffle-rs/ruffle#8818]
# Error Info
Error name: Error
Error message: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:580:9
Error stack:
```
Error: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:580:9
    at imports.wbg.__wbg_new_f9bb493369a83c12 (chrome-extension://mdfknmapaohdfmgkhhaihgfcdabiefbo/dist/966.js:645:21)
    at std::sync::once::Once::call_once::{{closure}}::ha7687e41144ec39a (wasm://wasm/01912dba:wasm-function[1095]:0x2a377c)
    at std::sys_common::once::generic::Once::call::h62f79875d8dd2a00 (wasm://wasm/01912dba:wasm-function[1404]:0x31a16a)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hb259f62dc432889a (wasm://wasm/01912dba:wasm-function[5027]:0x4bb576)
    at std::panicking::rust_panic_with_hook::he04cb00575f2a1e3 (wasm://wasm/01912dba:wasm-function[3730]:0x475899)
    at core::panicking::panic_fmt::h586d720a90aa8503 (wasm://wasm/01912dba:wasm-function[5268]:0x4c03cb)
    at core::option::expect_failed::h1e9a9cbb22bbd6ac (wasm://wasm/01912dba:wasm-function[5944]:0x4d395b)
    at ruffle_core::display_object::stage::Stage::root_clip::hb205d199bc57325a (wasm://wasm/01912dba:wasm-function[3734]:0x475bd8)
    at ruffle_web::Ruffle::tick::hb249abdb3358693e (wasm://wasm/01912dba:wasm-function[645]:0x1eb49f)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::ha9cea59bc43ccdda (wasm://wasm/01912dba:wasm-function[6187]:0x4dbcd9)
```

# Player Info
Allows script access: true
Renderer: WebGL

# Page Info
Page URL: http://www.andkon.com/arcade/puzzle/candyconveyor/
SWF URL: http://www.andkon.com/arcade/puzzle/candyconveyor/candyconveyor.swf

# Browser Info
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Platform: MacIntel
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-12-16
Channel: nightly
Built: 2022-12-16T00:16:00.140Z
Commit: d26b5ab0188c86c4ee73e32a6400eb7902473148
Is extension: true

# Metadata
width: 640
height: 480
frameRate: 100
numFrames: 3
swfVersion: 9
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 1252919

**Comment by Lord-McSweeney** [comment]
"`Got error when creating AVM2 side of bitmap: RustError("Param <Unnamed Parameter> (index 0) was missing when calling ")`" is shown in the console before that.
