### ISSUE TITLE
Error on https://h-flash.com/how-to-discipline-a-shoplifting-girl-eng/

### ISSUE THREAD

**Issue by Kaylaslut** [ruffle-rs/ruffle#8845]
# Error Info
Error name: Error
Error message: panicked at 'assertion failed: min <= max', /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/cmp.rs:865:9
Error stack:
```
Error: panicked at 'assertion failed: min <= max', /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/cmp.rs:865:9
    at U.n.wbg.__wbg_new_f9bb493369a83c12 (https://h-flash.com/data/ruffle/core.ruffle.7ecc2d52e8f222ff95a4.js:1:6813)
    at std::sync::once::Once::call_once::{{closure}}::hc0104d6321319ac0 (wasm://wasm/0180c36a:wasm-function[1031]:0x296df7)
    at std::sync::once::Once::call_inner::hb30cfbde5209eed0 (wasm://wasm/0180c36a:wasm-function[1488]:0x325ff5)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h6143650320584ffd (wasm://wasm/0180c36a:wasm-function[4910]:0x48851a)
    at std::panicking::rust_panic_with_hook::hb09154fa23e06c37 (wasm://wasm/0180c36a:wasm-function[3620]:0x446e14)
    at core::panicking::panic_fmt::h9e229748e3ae9f9d (wasm://wasm/0180c36a:wasm-function[5129]:0x48cc1e)
    at core::panicking::panic::h6f5024a57ca8da86 (wasm://wasm/0180c36a:wasm-function[4965]:0x48948c)
    at ruffle_core::player::Player::update_drag::h6c256899c0da8d32 (wasm://wasm/0180c36a:wasm-function[1440]:0x31a23b)
    at ruffle_web::Ruffle::tick::h4573fa911c064658 (wasm://wasm/0180c36a:wasm-function[653]:0x1f070b)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h37f698ed307a20db (wasm://wasm/0180c36a:wasm-function[6024]:0x4a691c)
```

# Player Info
Allows script access: false
Renderer: WebGL

# Page Info
Page URL: https://h-flash.com/how-to-discipline-a-shoplifting-girl-eng/
SWF URL: https://h-flash.com/data/swf/2019/11/how-to-discipline-a-shoplifting-girl-eng.swf

# Browser Info
User Agent: Mozilla/5.0 (Linux; Android 11; SM-A125U1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Mobile Safari/537.36
Platform: Linux armv8l
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-10-17
Channel: nightly
Built: 2022-10-17T00:20:39.827Z
Commit: 36844e5e2f2476b1c288e4ecaa1ecefbf2ba6972
Is extension: false

# Metadata
width: 600
height: 600
frameRate: 24
numFrames: 124
swfVersion: 10
backgroundColor: #999999
isActionScript3: true
uncompressedLength: 18648693

**Comment by n0samu** [comment]
Looks like the same problem as #8382, #8632, #8839
