### ISSUE TITLE
Error on Cathode Raybots

### ISSUE THREAD

**Issue by Dungeonation** [ruffle-rs/ruffle#8896]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create renderbuffer object"', C:\Users\nosamu\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-hal-0.14.1\src\gles\device.rs:554:48
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create renderbuffer object"', C:\Users\nosamu\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-hal-0.14.1\src\gles\device.rs:554:48
    at n.wbg.__wbg_new_f9bb493369a83c12 (https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.d2df3dbd13353e9c3bcf.js:1:6944)
    at std::sync::once::Once::call_once::{{closure}}::h80426984c62ac990 (wasm://wasm/020d7966:wasm-function[1593]:0x3c798a)
    at std::sync::once::Once::call_inner::hb30cfbde5209eed0 (wasm://wasm/020d7966:wasm-function[1938]:0x426eed)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h13f33de6f3dec6e8 (wasm://wasm/020d7966:wasm-function[6447]:0x628826)
    at std::panicking::rust_panic_with_hook::hb09154fa23e06c37 (wasm://wasm/020d7966:wasm-function[4615]:0x59e6f9)
    at core::panicking::panic_fmt::h9e229748e3ae9f9d (wasm://wasm/020d7966:wasm-function[6718]:0x6442af)
    at core::result::unwrap_failed::h5da0ab182d2c24a1 (wasm://wasm/020d7966:wasm-function[5439]:0x5e778c)
    at wgpu::Device::create_texture::h14f8e108447a4709 (wasm://wasm/020d7966:wasm-function[5544]:0x5edab1)
    at ruffle_render_wgpu::commands::CommandTarget::new::hb963c7c67cbcf476 (wasm://wasm/020d7966:wasm-function[1358]:0x36e754)
    at ruffle_render_wgpu::surface::Surface::draw_commands_to::hd30679b452c17706 (wasm://wasm/020d7966:wasm-function[676]:0x1f9ba7)
```

# Player Info
Allows script access: true
Renderer: WebGL through wgpu

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.67&useloader=1&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1671717208%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F610000%2F610807_BossKilla54.swf%3F1593639593%22%2C%22vars%22%3A%7B%22ngio_session_id%22%3A%2239248004.400f28e20e4a36108dc86af881b897d0d6829100346841%22%2C%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%2263a4e02e8458f%22%2C%22NewgroundsAPI_SessionID%22%3A%22gGnziagKJWNaY8DrEIhpe2109fc5807c11c7ec9987267ad1916f1bde9cdfwuAw%22%2C%22NewgroundsAPI_UserName%22%3A%22Dungeonation%22%2C%22NewgroundsAPI_UserID%22%3A5431202%2C%22ng_username%22%3A%22Dungeonation%22%7D%2C%22width%22%3A800%2C%22height%22%3A450%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F610000%2Fflash_610807_card.png%3Ff1643659596%22%2C%22warnOnUnsupportedContent%22%3Afalse%7D
SWF URL: https://uploads.ungrounded.net/610000/610807_BossKilla54.swf?1593639593

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 OPR/93.0.0.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-12-22
Channel: nightly
Built: 2022-12-22T11:40:16.211Z
Commit: 6610c817d6018d672bc4cb31585317bd88eff157
Is extension: false

# Metadata
width: 800
height: 450
frameRate: 60
numFrames: 6
swfVersion: 8
backgroundColor: #CCCCCC
isActionScript3: false
uncompressedLength: 19178754

**Comment by n0samu** [comment]
Not sure if you're aware, but Newgrounds is testing a Ruffle build with an experimental render backend right now. These issues will hopefully be ironed out.

Did you get this crash while in fullscreen mode? We have a report from Tom Fulp that the renderer tends to crash in fullscreen mode.

**Comment by n0samu** [comment]
Got a reply from Dungeonation on Discord. He says the crash did not occur in fullscreen mode. So this must be an unrelated problem.

**Comment by Dungeonation** [comment]
I should probably also mention that my browser window went completely black for one or two seconds before the "something went wrong" screen, which happened each time I tested the crash.
