### ISSUE TITLE
Error on https://www.gamesflow.com/jeux.php

### ISSUE THREAD

**Issue by TenObok** [ruffle-rs/ruffle#8899]
# Error Info
Error name: Error
Error message: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:580:9
Error stack:
```
Error: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:580:9
    at imports.wbg.__wbg_new_f9bb493369a83c12 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:645:21)
    at std::sync::once::Once::call_once::{{closure}}::h2e61d96ea4417fe9 (wasm://wasm/018f336e:wasm-function[1098]:0x2a793e)
    at std::sys_common::once::generic::Once::call::h62f79875d8dd2a00 (wasm://wasm/018f336e:wasm-function[1410]:0x3186b8)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hc298a7f922019542 (wasm://wasm/018f336e:wasm-function[5022]:0x4b3271)
    at std::panicking::rust_panic_with_hook::he04cb00575f2a1e3 (wasm://wasm/018f336e:wasm-function[3748]:0x46f19b)
    at core::panicking::panic_fmt::h586d720a90aa8503 (wasm://wasm/018f336e:wasm-function[5264]:0x4b80ea)
    at core::option::expect_failed::h1e9a9cbb22bbd6ac (wasm://wasm/018f336e:wasm-function[5940]:0x4cb59c)
    at ruffle_core::display_object::stage::Stage::root_clip::hce7143ccaa376c8d (wasm://wasm/018f336e:wasm-function[3752]:0x46f4da)
    at ruffle_web::Ruffle::tick::hdcb4afd54d8a568d (wasm://wasm/018f336e:wasm-function[648]:0x1f284c)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h5b63cba1bdda8f36 (wasm://wasm/018f336e:wasm-function[6184]:0x4d38fe)
```

# Player Info
Allows script access: true
Renderer: WebGL

# Page Info
Page URL: https://www.gamesflow.com/jeux.php?id=5000093
SWF URL: https://www.gamesflow.com/jeux/570cef013a1f8.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-12-22
Channel: nightly
Built: 2022-12-22T00:14:42.760Z
Commit: 7a09dd563980b378eb2b6702a227c7b346b5ae3e
Is extension: true

# Metadata
width: 800
height: 600
frameRate: 24
numFrames: 2
swfVersion: 15
backgroundColor: #FFFFFF
isActionScript3: true
uncompressedLength: 527707

**Comment by n0samu** [comment]
Same error as #8905. See also: #8006.

**Comment by TenObok** [comment]
Didnt't ask + ratio

sob., 24 gru 2022, 01:35 użytkownik nosamu ***@***.***>
napisał:
