### ISSUE TITLE
Error on https://homestarrunner.com/dman3

### ISSUE THREAD

**Issue by banjobeatnik** [ruffle-rs/ruffle#8908]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: UnableToCreateVAO', render/webgl/src/lib.rs:577:23
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: UnableToCreateVAO', render/webgl/src/lib.rs:577:23
    at W.n.wbg.__wbg_new_f9bb493369a83c12 (https://homestarrunner.com/assets/js/core.ruffle.530da309ab8cea301079.js:1:6507)
    at std::sync::once::Once::call_once::{{closure}}::h9abcd8d2861dbb63 (wasm://wasm/0184b59e:wasm-function[837]:0x25dddc)
    at std::sync::once::Once::call_inner::h34aee843864daceb (wasm://wasm/0184b59e:wasm-function[1357]:0x312b20)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h20c00e1373f93c44 (wasm://wasm/0184b59e:wasm-function[4884]:0x498b94)
    at std::panicking::rust_panic_with_hook::h70a0e195f4db2a29 (wasm://wasm/0184b59e:wasm-function[3623]:0x458d57)
    at core::panicking::panic_fmt::h751be80779d42b53 (wasm://wasm/0184b59e:wasm-function[5107]:0x49d548)
    at core::result::unwrap_failed::h2dc706d948c22960 (wasm://wasm/0184b59e:wasm-function[4205]:0x47f0e5)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::hac14c9eb62754981 (wasm://wasm/0184b59e:wasm-function[650]:0x2000a6)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_render::backend::RenderBackend>::register_shape::h781c0bde228de5df (wasm://wasm/0184b59e:wasm-function[3430]:0x449e05)
    at ruffle_core::drawing::Drawing::render::h5ec2238b03ce85f8 (wasm://wasm/0184b59e:wasm-function[671]:0x20e725)
```

# Player Info
Allows script access: true
Renderer: WebGL

# Page Info
Page URL: https://homestarrunner.com/dman3
SWF URL: https://homestarrunner.com/media/pages/dman3/f0e50731c9-1660831051/thydungeonman3.swf

# Browser Info
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
Platform: MacIntel
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-11-04
Channel: nightly
Built: 2022-11-04T00:16:33.453Z
Commit: d16e9e15118bba9b01527ac042c3c00bb987a23f
Is extension: false

# Metadata
width: 550
height: 400
frameRate: 24
numFrames: 258
swfVersion: 7
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 1200460

**Comment by banjobeatnik** [comment]
I was playing the game, a second time, after it crashing a 1st time and not having an account with GitHub, when it crashed, again, this time, before it did the first time.

**Comment by n0samu** [comment]
Looks like the same error as #8179. Did it happen at the same points in the game for you too?
From that issue:
> The game shut down when I was just trying to exit the bar. I exited the bar once or twice before without any issues, but I did have the same issue trying to get away from the cannibalistic monk.

**Comment by banjobeatnik** [comment]
No, I hadn't gotten out of the the fields... First time, it was when I went West, I think? Then the second time, it was when I first GOT to the crossroads. As I said, the second time was before the first.

**Comment by n0samu** [comment]
Alright, thanks for the info!

**Comment by banjobeatnik** [comment]
NP! 👍

**Comment by kjarosh** [comment]
Should be fixed as of the newest version
