### ISSUE TITLE
Error on https://www.vap.co.jp/elfenlied/staff.html 

### ISSUE THREAD

**Issue by Andym8** [ruffle-rs/ruffle#8912]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm1/activation.rs:1237:38
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm1/activation.rs:1237:38
    at imports.wbg.__wbg_new_f9bb493369a83c12 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:645:21)
    at std::sync::once::Once::call_once::{{closure}}::h2e61d96ea4417fe9 (wasm://wasm/018f336e:wasm-function[1098]:0x2a793e)
    at std::sys_common::once::generic::Once::call::h62f79875d8dd2a00 (wasm://wasm/018f336e:wasm-function[1410]:0x3186b8)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hc298a7f922019542 (wasm://wasm/018f336e:wasm-function[5022]:0x4b3271)
    at std::panicking::rust_panic_with_hook::he04cb00575f2a1e3 (wasm://wasm/018f336e:wasm-function[3748]:0x46f19b)
    at core::panicking::panic_fmt::h586d720a90aa8503 (wasm://wasm/018f336e:wasm-function[5264]:0x4b80bc)
    at core::panicking::panic::h0859aaac783261b2 (wasm://wasm/018f336e:wasm-function[5076]:0x4b41a3)
    at ruffle_core::avm1::activation::Activation::run_actions::h079d6bd6c21aea97 (wasm://wasm/018f336e:wasm-function[302]:0x3888c)
    at ruffle_core::avm1::runtime::Avm1::run_stack_frame_for_action::h55cd115eb740ef0a (wasm://wasm/018f336e:wasm-function[945]:0x2738e2)
    at ruffle_core::player::Player::run_actions::hd89f218b98acfade (wasm://wasm/018f336e:wasm-function[462]:0x15af78)
```

# Player Info
Allows script access: true
Renderer: WebGL

# Page Info
Page URL: https://www.vap.co.jp/elfenlied/staff.html
SWF URL: https://www.vap.co.jp/elfenlied/staff.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-12-22
Channel: nightly
Built: 2022-12-22T00:14:42.760Z
Commit: 7a09dd563980b378eb2b6702a227c7b346b5ae3e
Is extension: true

# Metadata
width: 750
height: 450
frameRate: 24
numFrames: 89
swfVersion: 6
backgroundColor: #FFE5EE
isActionScript3: false
uncompressedLength: 68249

**Comment by n0samu** [comment]
Same problem as #5067 and #8113

**Comment by Andym8** [comment]
i hope this gets fixed
