### ISSUE TITLE
Error on chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/player.html

### ISSUE THREAD

**Issue by BerkaySarikaya** [ruffle-rs/ruffle#8913]
# Error Info
Error name: Error
Error message: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:580:9
Error stack:
```
Error: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:580:9
    at imports.wbg.__wbg_new_f9bb493369a83c12 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:645:21)
    at std::sync::once::Once::call_once::{{closure}}::h2e61d96ea4417fe9 (wasm://wasm/018f336e:wasm-function[1098]:0x2a793e)
    at std::sys_common::once::generic::Once::call::h62f79875d8dd2a00 (wasm://wasm/018f336e:wasm-function[1410]:0x3186b8)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hc298a7f922019542 (wasm://wasm/018f336e:wasm-function[5022]:0x4b3271)
    at std::panicking::rust_panic_with_hook::he04cb00575f2a1e3 (wasm://wasm/018f336e:wasm-function[3748]:0x46f19b)
    at core::panicking::panic_fmt::h586d720a90aa8503 (wasm://wasm/018f336e:wasm-function[5264]:0x4b80ea)
    at core::option::expect_failed::h1e9a9cbb22bbd6ac (wasm://wasm/018f336e:wasm-function[5940]:0x4cb59c)
    at ruffle_core::display_object::stage::Stage::root_clip::hce7143ccaa376c8d (wasm://wasm/018f336e:wasm-function[3752]:0x46f4da)
    at ruffle_web::Ruffle::tick::hdcb4afd54d8a568d (wasm://wasm/018f336e:wasm-function[648]:0x1f284c)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h5b63cba1bdda8f36 (wasm://wasm/018f336e:wasm-function[6184]:0x4d38fe)
```

# Player Info
Allows script access: false
Renderer: Canvas

# Page Info
Page URL: chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/player.html?url=http%3A%2F%2Fcache.hackedfreegames.com%2Fuploads%2Fgames%2Ffiles%2F4CT1Q3OG2Y7B.swf%3Fversion%3D3
SWF URL: http://cache.hackedfreegames.com/uploads/games/files/4CT1Q3OG2Y7B.swf?version=3

# Browser Info
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Platform: MacIntel
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-12-22
Channel: nightly
Built: 2022-12-22T00:14:42.760Z
Commit: 7a09dd563980b378eb2b6702a227c7b346b5ae3e
Is extension: true

# Metadata
width: 800
height: 600
frameRate: 30
numFrames: 101
swfVersion: 9
backgroundColor: #999999
isActionScript3: true
uncompressedLength: 16194414

**Comment by kjarosh** [comment]
Should be fixed as of the newest version
