### ISSUE TITLE
Error on https://ruffle.rs/demo/

### ISSUE THREAD

**Issue by Hachieii** [ruffle-rs/ruffle#8914]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: UnableToCreateVAO', render/webgl/src/lib.rs:582:23
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: UnableToCreateVAO', render/webgl/src/lib.rs:582:23
    at n.wbg.__wbg_new_f9bb493369a83c12 (https://ruffle.rs/demo/966.index.js:1:6285)
    at std::sync::once::Once::call_once::{{closure}}::ha6382b669ac514f8 (wasm://wasm/01a9b78a:wasm-function[1190]:0x2c6fee)
    at std::sys_common::once::generic::Once::call::h62f79875d8dd2a00 (wasm://wasm/01a9b78a:wasm-function[1515]:0x33e461)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h7b25e41b76d36760 (wasm://wasm/01a9b78a:wasm-function[5377]:0x4f7c72)
    at std::panicking::rust_panic_with_hook::he04cb00575f2a1e3 (wasm://wasm/01a9b78a:wasm-function[3967]:0x4a494a)
    at core::panicking::panic_fmt::h586d720a90aa8503 (wasm://wasm/01a9b78a:wasm-function[5645]:0x501bfe)
    at core::result::unwrap_failed::h1d03d3774c363770 (wasm://wasm/01a9b78a:wasm-function[4618]:0x4d211e)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::hedc15fedd103d827 (wasm://wasm/01a9b78a:wasm-function[706]:0x1fe9cc)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_render::backend::RenderBackend>::register_glyph_shape::h86848bb445a8c29a (wasm://wasm/01a9b78a:wasm-function[2185]:0x3e8ee1)
    at ruffle_core::font::Font::from_swf_tag::hf96f0752e53450f1 (wasm://wasm/01a9b78a:wasm-function[733]:0x212241)
```

# Player Info
Allows script access: false
Renderer: WebGL

# Page Info
Page URL: https://ruffle.rs/demo/
SWF URL: https://ruffle.rs/demo/logo-anim.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-12-22
Channel: nightly
Built: 2022-12-22T00:15:12.911Z
Commit: 7a09dd563980b378eb2b6702a227c7b346b5ae3e
Is extension: false

# Metadata
width: 600
height: 400
frameRate: 30
numFrames: 1
swfVersion: 15
backgroundColor: #31497D
isActionScript3: false
uncompressedLength: 40440

**Comment by kjarosh** [comment]
Should be fixed as of the newest version
