### ISSUE TITLE
fireboynwatergirl.com#

### ISSUE THREAD

**Issue by bankroll300** [ruffle-rs/ruffle#8941]
# Error Info
Error name: Error
Error message: panicked at 'No script object for display object', core/src/avm1/runtime.rs:165:18
Error stack:
```
Error: panicked at 'No script object for display object', core/src/avm1/runtime.rs:165:18
    at imports.wbg.__wbg_new_f9bb493369a83c12 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:645:21)
    at std::sync::once::Once::call_once::{{closure}}::h2e61d96ea4417fe9 (wasm://wasm/018f1a9e:wasm-function[1098]:0x2a6c57)
    at std::sys_common::once::generic::Once::call::h62f79875d8dd2a00 (wasm://wasm/018f1a9e:wasm-function[1410]:0x3179d1)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hc298a7f922019542 (wasm://wasm/018f1a9e:wasm-function[5024]:0x4b2a83)
    at std::panicking::rust_panic_with_hook::he04cb00575f2a1e3 (wasm://wasm/018f1a9e:wasm-function[3750]:0x46e9f9)
    at core::panicking::panic_fmt::h586d720a90aa8503 (wasm://wasm/018f1a9e:wasm-function[5266]:0x4b78ce)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::hc67b923d49e8c0d9 (wasm://wasm/018f1a9e:wasm-function[1765]:0x37297b)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::h3cd7d535cbeb2028 (wasm://wasm/018f1a9e:wasm-function[484]:0x1762b5)
    at ruffle_core::display_object::movie_clip::MovieClip::place_object::hf9486ca25cc8f28c (wasm://wasm/018f1a9e:wasm-function[1332]:0x3038ed)
    at <ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::construct_frame::hc56801695f86fd9f (wasm://wasm/018f1a9e:wasm-function[404]:0x11b51e)
```

# Player Info
Allows script access: true
Renderer: WebGL

# Page Info
Page URL: https://www.fireboynwatergirl.com/?p=game&id=310
SWF URL: https://www.fireboynwatergirl.com/swf/fireboy-racing.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-12-25
Channel: nightly
Built: 2022-12-25T00:15:38.799Z
Commit: 6dc628e49f7a1de9115a68eb99f0b8ce2e1f14a8
Is extension: true

# Metadata
width: 640
height: 480
frameRate: 30
numFrames: 2
swfVersion: 14
backgroundColor: #003A5C
isActionScript3: true
uncompressedLength: 985404

**Comment by Lord-McSweeney** [comment]
Looks like unimplemented `Loader.unload`.

**Comment by n0samu** [comment]
The error now is: 
`WARN run_frame:run_all_phases_avm2: ruffle_core::display_object::movie_clip: DoAction tag in AVM2 movie`

This is an AVM1 game encrypted with MochiCrypt, which uses AVM2. Ruffle does not correctly play AVM1 movies loaded by AVM2 movies right now.

Same issue as #9502, #8310, #9065, etc.

**Comment by Lord-McSweeney** [comment]
Seems to be playable with #11005.
