### ISSUE TITLE
Error on chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/player.html

### ISSUE THREAD

**Issue by ryoshioni** [ruffle-rs/ruffle#8962]
# Error Info
Error name: Error
Error message: panicked at 'No script object for display object', core/src/avm1/activation.rs:382:18
Error stack:
```
Error: panicked at 'No script object for display object', core/src/avm1/activation.rs:382:18
    at imports.wbg.__wbg_new_f9bb493369a83c12 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:640:21)
    at std::sync::once::Once::call_once::{{closure}}::h07c839951d6d0b0f (wasm://wasm/018ff4e6:wasm-function[1095]:0x2bb1e7)
    at std::sys_common::once::generic::Once::call::h62f79875d8dd2a00 (wasm://wasm/018ff4e6:wasm-function[1400]:0x3215a4)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h5a01fde47a9be61a (wasm://wasm/018ff4e6:wasm-function[5064]:0x4b50de)
    at std::panicking::rust_panic_with_hook::he04cb00575f2a1e3 (wasm://wasm/018ff4e6:wasm-function[3744]:0x476567)
    at core::panicking::panic_fmt::h586d720a90aa8503 (wasm://wasm/018ff4e6:wasm-function[5305]:0x4b9ee7)
    at ruffle_core::display_object::edit_text::EditText::try_bind_text_field_variable::h5928dbfecaa85284 (wasm://wasm/018ff4e6:wasm-function[2460]:0x405e66)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::he76b851b42a0426c (wasm://wasm/018ff4e6:wasm-function[1817]:0x3932f9)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::h58fe0e6fe785da4d (wasm://wasm/018ff4e6:wasm-function[788]:0x247dec)
    at ruffle_core::display_object::movie_clip::MovieClip::place_object::h0184133c7528d906 (wasm://wasm/018ff4e6:wasm-function[1329]:0x30e989)
```

# Player Info
Allows script access: false
Renderer: WebGL

# Page Info
Page URL: chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/player.html?url=http%3A%2F%2Fi.notdoppler.com%2Ffiles%2Fgingerbreadcircus.swf
SWF URL: http://i.notdoppler.com/files/gingerbreadcircus.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.54
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-12-29
Channel: nightly
Built: 2022-12-29T00:16:34.344Z
Commit: 8b9bae8ca610fa6081ef84a267453936784c2ac5
Is extension: true

# Metadata
width: 540
height: 380
frameRate: 31
numFrames: 2
swfVersion: 10
backgroundColor: #CCCCCC
isActionScript3: true
uncompressedLength: 1332669

**Comment by Lord-McSweeney** [comment]
This SWF uses the unimplemented `Loader.unload`.
