### ISSUE TITLE
Error on http://www.7k7k.com/swf/154967.htm

### ISSUE THREAD

**Issue by ElisaMin** [ruffle-rs/ruffle#9065]
# Error Info
Error name: Error
Error message: panicked at 'No script object for display object', core/src/avm1/activation.rs:382:18
Error stack:
```
Error: panicked at 'No script object for display object', core/src/avm1/activation.rs:382:18
    at imports.wbg.__wbg_new_f9bb493369a83c12 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:585:21)
    at std::sync::once::Once::call_once::{{closure}}::h636b0dd15fef5920 (wasm://wasm/01995dea:wasm-function[1106]:0x2b9365)
    at std::sys_common::once::generic::Once::call::h62f79875d8dd2a00 (wasm://wasm/01995dea:wasm-function[1429]:0x332525)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h659018fbe4d07f63 (wasm://wasm/01995dea:wasm-function[4918]:0x4c58e9)
    at std::panicking::rust_panic_with_hook::he04cb00575f2a1e3 (wasm://wasm/01995dea:wasm-function[3600]:0x4837f7)
    at core::panicking::panic_fmt::h586d720a90aa8503 (wasm://wasm/01995dea:wasm-function[5126]:0x4cb334)
    at ruffle_core::display_object::edit_text::EditText::try_bind_text_field_variable::h2fdb9b5cac6025ad (wasm://wasm/01995dea:wasm-function[2494]:0x41b889)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::hfec510ec1620e4c6 (wasm://wasm/01995dea:wasm-function[1836]:0x3965d8)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::h1663241d8a7c4d1e (wasm://wasm/01995dea:wasm-function[495]:0x16e935)
    at ruffle_core::display_object::movie_clip::MovieClip::place_object::h2dbd978998725e56 (wasm://wasm/01995dea:wasm-function[1347]:0x31dc58)
```

# Player Info
Allows script access: false
null

# Page Info
Page URL: http://www.7k7k.com/swf/154967.htm
SWF URL: http://flash.7k7k.com/cms/cms10/20150717/1513233191/88.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-01-07
Channel: nightly
Built: 2023-01-07T00:14:37.441Z
Commit: d332a174c318ab2fb11bece591735077739a1c8e
Is extension: true

# Metadata
width: 360
height: 480
frameRate: 30
numFrames: 2
swfVersion: 11
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 2234432

**Comment by Lord-McSweeney** [comment]
The screen flickers between the two frames, and the following shows up in the console:
`WARN core/src/display_object/movie_clip.rs:674 DoInitAction tag in AVM2 movie`
`WARN core/src/display_object/movie_clip.rs:3627 DoAction tag in AVM2 movie`

**Comment by n0samu** [comment]
This is an AVM2 loader SWF that loads the actual game (an AVM1 SWF) via embedded BinaryData. If I extract the BinaryData as an SWF file (using JPEXS) and run it in Ruffle, it works fine.

**Comment by Lord-McSweeney** [comment]
Fixed by #11005
