### ISSUE TITLE
Error Loading SWF

### ISSUE THREAD

**Issue by BorjanEch0** [ruffle-rs/ruffle#9068]
### Describe the bug

When loading the swf i get the following error uwing selfhosted or browser variant.

`# Error Info
Error name: Error
Error message: Failed to fetch: http://webosaurs.world/site.swf
Error stack:
```
Error: Failed to fetch: http://webosaurs.world/site.swf
    at $.displayRootMovieDownloadFailedMessage (http://webosaurs.world/ruffle/ruffle.js:1:43554)
    at W.n.wbg.__wbg_displayRootMovieDownloadFailedMessage_c90a7f0f0b73e4df (http://webosaurs.world/ruffle/core.ruffle.aa79af40580d7ea81bb1.js:1:6468)
    at <ruffle_web::ui::WebUiBackend as ruffle_core::backend::ui::UiBackend>::display_root_movie_download_failed_message::hc8b03ca7ece21621 (wasm://wasm/01995dea:wasm-function[6081]:0x4f5eac)
    at <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hb2ca55896c35111f (wasm://wasm/01995dea:wasm-function[509]:0x178c6e)
    at <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hb71c9189bcb14d9c (wasm://wasm/01995dea:wasm-function[644]:0x1daf0c)
    at wasm_bindgen_futures::queue::Queue::new::{{closure}}::h21e2b94aa32a9b0e (wasm://wasm/01995dea:wasm-function[2254]:0x3f7a62)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h57aa5740ad376544 (wasm://wasm/01995dea:wasm-function[5463]:0x4d761f)
    at closure2970 externref shim (wasm://wasm/01995dea:wasm-function[5598]:0x4dadf8)
    at C (http://webosaurs.world/ruffle/core.ruffle.aa79af40580d7ea81bb1.js:1:2730)
    at c (http://webosaurs.world/ruffle/core.ruffle.aa79af40580d7ea81bb1.js:1:2255)
```

# Player Info
Allows script access: true
null
Player type: Object
SWF URL: site.swf
Param quality: high
Param scale: noscale
Param wmode: transparent
Param flashvars: version=1673176611289&url_root=http://webosaurs.world/&url_wservice=http://webosaurs.world:8080/webosaurs/service?action=&miniclip=true
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined
Attribute 6: undefined

# Page Info
Page URL: http://webosaurs.world/
SWF URL: http://webosaurs.world/site.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-01-08
Channel: nightly
Built: 2023-01-08T00:14:58.659Z
Commit: 1b71e288fd984ace46f69c1a2e27e2e2ed31333b
Is extension: false

# Metadata
`
the swf is available @ http://webosaurs.world

### Expected behavior

using a VM of windows 7 and latest working flashplayr loads the swf.

### Affected platform

Self-hosted version

### Operating system

Windows 11 for browser, hosted on ubuntu 18.04

### Browser

Google Chrome

**Comment by Lord-McSweeney** [comment]
This is a problem with the server. The server returns a 503 error, and Ruffle shows that it failed to fetch the SWF file.

**Comment by BorjanEch0** [comment]
Hi, thank you very much  for the insight and time, how can i debug the swf to find what it needs, im reconstructing an old site, i have most of the files but i rely on debug data and 404's to find where they belong.
