### ISSUE TITLE
Error on https://f.kbhgames.com/RS/game.php

### ISSUE THREAD

**Issue by Dynnammo** [ruffle-rs/ruffle#9072]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: UnableToCreateVAO', render/webgl/src/lib.rs:583:23
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: UnableToCreateVAO', render/webgl/src/lib.rs:583:23
    at W.n.wbg.__wbg_new_f9bb493369a83c12 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.aa79af40580d7ea81bb1.js:1:5285)
    at std::sync::once::Once::call_once::{{closure}}::h636b0dd15fef5920 (wasm://wasm/01995dea:wasm-function[1106]:0x2b9365)
    at std::sys_common::once::generic::Once::call::h62f79875d8dd2a00 (wasm://wasm/01995dea:wasm-function[1429]:0x332525)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h659018fbe4d07f63 (wasm://wasm/01995dea:wasm-function[4918]:0x4c58e9)
    at std::panicking::rust_panic_with_hook::he04cb00575f2a1e3 (wasm://wasm/01995dea:wasm-function[3600]:0x4837f7)
    at core::panicking::panic_fmt::h586d720a90aa8503 (wasm://wasm/01995dea:wasm-function[5126]:0x4cb362)
    at core::result::unwrap_failed::h1d03d3774c363770 (wasm://wasm/01995dea:wasm-function[4207]:0x4a7daf)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::hb75befa56200fe16 (wasm://wasm/01995dea:wasm-function[637]:0x1d74a3)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_render::backend::RenderBackend>::register_shape::h427518b8f85d3f3d (wasm://wasm/01995dea:wasm-function[3481]:0x47aa79)
    at ruffle_core::drawing::Drawing::render::h56256297685a75be (wasm://wasm/01995dea:wasm-function[676]:0x1e8708)
```

# Player Info
Allows script access: true
null

# Page Info
Page URL: https://f.kbhgames.com/RS/game.php?r=//f.kbhgames.com/2018/swf/the_last_villagw.swf&w=800&h=600
SWF URL: https://f.kbhgames.com/2018/swf/the_last_villagw.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-01-08
Channel: nightly
Built: 2023-01-08T00:14:58.659Z
Commit: 1b71e288fd984ace46f69c1a2e27e2e2ed31333b
Is extension: false

# Metadata
width: 800
height: 600
frameRate: 30
numFrames: 13
swfVersion: 8
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 18396611

**Comment by Lord-McSweeney** [comment]
"WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost"
Why was the context lost in the middle of the game?

**Comment by n0samu** [comment]
> WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost

@Lord-McSweeney where does the issue say that? Or did you reproduce the issue and see that yourself?

**Comment by Dynnammo** [comment]
Hey there. Sorry for late answer. 

I just tried to play this game : https://kbhgames.com/game/the-last-village, and received this error when trying to make the moves.

To reproduce : Play > Strategy > "create some moves" > Execute moves

![image](https://user-images.githubusercontent.com/33259633/211250776-2abd7a13-cc2c-401b-a67a-c2ac8447b888.png)

**Comment by Lord-McSweeney** [comment]
I got the same issue, but I was able to move them a couple times before the issue occured (on Day 5).

**Comment by Dynnammo** [comment]
> I got the same issue, but I was able to move them a couple times before the issue occured (on Day 5).

Yeah, didn't mention it but same situation by me. What I did as a workaround is saving progress *before* each **Execute moves**, but I didn't investigate further.

**Comment by kjarosh** [comment]
Should be fixed as of the newest version
