### ISSUE TITLE
Error on https://ruffle.rs/demo/

### ISSUE THREAD

**Issue by ghost** [ruffle-rs/ruffle#9082]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: UnableToCreateVAO', render/webgl/src/lib.rs:583:23
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: UnableToCreateVAO', render/webgl/src/lib.rs:583:23
    at U.n.wbg.__wbg_new_f9bb493369a83c12 (https://ruffle.rs/demo/966.index.js:1:5394)
    at std::sync::once::Once::call_once::{{closure}}::hdf9d6c6d3382f2fd (wasm://wasm/01ba330e:wasm-function[1258]:0x2df6e1)
    at std::sys_common::once::generic::Once::call::h62f79875d8dd2a00 (wasm://wasm/01ba330e:wasm-function[1592]:0x35dc2c)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h5421a1bb37570da3 (wasm://wasm/01ba330e:wasm-function[5484]:0x51e460)
    at std::panicking::rust_panic_with_hook::he04cb00575f2a1e3 (wasm://wasm/01ba330e:wasm-function[3903]:0x4c0db9)
    at core::panicking::panic_fmt::h586d720a90aa8503 (wasm://wasm/01ba330e:wasm-function[5712]:0x5245eb)
    at core::result::unwrap_failed::h1d03d3774c363770 (wasm://wasm/01ba330e:wasm-function[4640]:0x4fb557)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::h6a4b798652d77fe9 (wasm://wasm/01ba330e:wasm-function[769]:0x2125d3)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_render::backend::RenderBackend>::register_glyph_shape::h217a1c2c19d72f48 (wasm://wasm/01ba330e:wasm-function[2278]:0x411a11)
    at ruffle_core::font::Font::from_swf_tag::h39f68bb9302440ef (wasm://wasm/01ba330e:wasm-function[815]:0x22a40c)
```

# Player Info
Allows script access: false
null

# Page Info
Page URL: https://ruffle.rs/demo/
SWF URL: https://ruffle.rs/demo/swfs/saturday_morning_watchmen.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-01-08
Channel: nightly
Built: 2023-01-08T00:18:30.139Z
Commit: 1b71e288fd984ace46f69c1a2e27e2e2ed31333b
Is extension: false

# Metadata
width: 699
height: 525
frameRate: 25
numFrames: 2160
swfVersion: 9
backgroundColor: #FFFFFF
isActionScript3: false
uncompressedLength: 6490001

**Comment by kjarosh** [comment]
Should be fixed as of the newest version
