### ISSUE TITLE
Error on https://class.ece.uw.edu/341/riskin/lesson3/

### ISSUE THREAD

**Issue by EezyE** [ruffle-rs/ruffle#9110]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: UnableToCreateVAO', render/webgl/src/lib.rs:583:23
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: UnableToCreateVAO', render/webgl/src/lib.rs:583:23
    at imports.wbg.__wbg_new_f9bb493369a83c12 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:585:21)
    at std::sync::once::Once::call_once::{{closure}}::h636b0dd15fef5920 (wasm://wasm/019957ea:wasm-function[1106]:0x2b89bb)
    at std::sys_common::once::generic::Once::call::h62f79875d8dd2a00 (wasm://wasm/019957ea:wasm-function[1429]:0x331b7b)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h659018fbe4d07f63 (wasm://wasm/019957ea:wasm-function[4919]:0x4c57ce)
    at std::panicking::rust_panic_with_hook::he04cb00575f2a1e3 (wasm://wasm/019957ea:wasm-function[3601]:0x4836dc)
    at core::panicking::panic_fmt::h586d720a90aa8503 (wasm://wasm/019957ea:wasm-function[5127]:0x4cb247)
    at core::result::unwrap_failed::h1d03d3774c363770 (wasm://wasm/019957ea:wasm-function[4208]:0x4a7c94)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::hb75befa56200fe16 (wasm://wasm/019957ea:wasm-function[637]:0x1d734a)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_render::backend::RenderBackend>::register_glyph_shape::h742d0ced66ba7965 (wasm://wasm/019957ea:wasm-function[2086]:0x3dec41)
    at ruffle_core::font::Font::from_swf_tag::h4526d156beb04165 (wasm://wasm/019957ea:wasm-function[679]:0x1e933d)
```

# Player Info
Allows script access: true
null

# Page Info
Page URL: https://class.ece.uw.edu/341/riskin/lesson3/
SWF URL: https://class.ece.uw.edu/341/riskin/lesson3/pg7_ex1.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-01-10
Channel: nightly
Built: 2023-01-10T00:15:26.678Z
Commit: 14ee9b43fb077d73d332db2fdef705be1f687958
Is extension: true

# Metadata
width: 400
height: 300
frameRate: 12
numFrames: 15
swfVersion: 9
backgroundColor: #FFFFFF
isActionScript3: false
uncompressedLength: 9784

**Comment by Lord-McSweeney** [comment]
`ERROR web/src/lib.rs:1320 Error creating WebGL renderer: Couldn't create GL context`
The content of the SWF (and also the portion of the browser window which contains) becomes transparent and I can see my other desktop windows below it.

**Comment by EezyE** [comment]
When I paste the URL for the SWF in a new tab, the player works and I can view the content. However, I can't view the content on the website.

**Comment by Lord-McSweeney** [comment]
On the page, there's also several warnings: `WARNING: Too many active WebGL contexts. Oldest context will be lost.` As the first WebGL contexts is, Ruffle panics, which causes every ruffle object to panic, even if the WebGL context for that player isn't lost.

**Comment by n0samu** [comment]
The problem occurs for me in Chrome but not Firefox. I guess the WebGL context limit must vary by browser.

**Comment by EezyE** [comment]
I was finally able to get it working in Firefox as well, but I had to download the Firefox Developer version so I could change the xpinstall.signatures.required in about:config to false because the Ruffle extension isn't signed. 

https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox?as=u&utm_source=inproduct

**Comment by kjarosh** [comment]
Should be fixed as of the newest version
