### ISSUE TITLE
Error on https://h-flash.com/super-nina-wars-1/

### ISSUE THREAD

**Issue by Thejoker92921** [ruffle-rs/ruffle#9155]
# Error Info
Error name: Error
Error message: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:580:9
Error stack:
```
Error: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:580:9
    at D.n.wbg.__wbg_new_f9bb493369a83c12 (https://h-flash.com/data/ruffle/core.ruffle.b5d6ce968050f90fdce9.js:1:6507)
    at std::sync::once::Once::call_once::{{closure}}::h2e61d96ea4417fe9 (wasm://wasm/018fcb8a:wasm-function[1102]:0x2aa466)
    at std::sys_common::once::generic::Once::call::h62f79875d8dd2a00 (wasm://wasm/018fcb8a:wasm-function[1415]:0x31b27d)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hc298a7f922019542 (wasm://wasm/018fcb8a:wasm-function[5033]:0x4b585e)
    at std::panicking::rust_panic_with_hook::he04cb00575f2a1e3 (wasm://wasm/018fcb8a:wasm-function[3756]:0x471db6)
    at core::panicking::panic_fmt::h586d720a90aa8503 (wasm://wasm/018fcb8a:wasm-function[5275]:0x4ba6d7)
    at core::option::expect_failed::h1e9a9cbb22bbd6ac (wasm://wasm/018fcb8a:wasm-function[5951]:0x4cdb96)
    at ruffle_core::display_object::stage::Stage::root_clip::hce7143ccaa376c8d (wasm://wasm/018fcb8a:wasm-function[3761]:0x4721cc)
    at ruffle_web::Ruffle::tick::hdcb4afd54d8a568d (wasm://wasm/018fcb8a:wasm-function[648]:0x1f3ea1)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h5b63cba1bdda8f36 (wasm://wasm/018fcb8a:wasm-function[6195]:0x4d5ef8)
```

# Player Info
Allows script access: false
Renderer: WebGL

# Page Info
Page URL: https://h-flash.com/super-nina-wars-1/
SWF URL: https://h-flash.com/data/swf/2022/05/PurpleMantis-152745-Super_Nina_Wars_Episode_I.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-12-21
Channel: nightly
Built: 2022-12-21T00:16:40.503Z
Commit: 5cf5c8d5e5d3b37a38cf133aa587b7f925612f21
Is extension: false

# Metadata
width: 600
height: 947
frameRate: 29.96875
numFrames: 2
swfVersion: 10
backgroundColor: #FFFFFF
isActionScript3: true
uncompressedLength: 3017469

**Comment by Lord-McSweeney** [comment]
This is on the broken `Loader.unload` commit, which broke because of #8871 (my own PR).

**Comment by kjarosh** [comment]
Should be fixed as of the newest version
