### ISSUE TITLE
Error on https://www.furaffinity.net/view/17371095/

### ISSUE THREAD

**Issue by lonakmmma88777** [ruffle-rs/ruffle#9159]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: UnableToCreateVAO', render/webgl/src/lib.rs:577:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: UnableToCreateVAO', render/webgl/src/lib.rs:577:50
    at W.n.wbg.__wbg_new_df6e6ab7a65c4c4d (https://d.furaffinity.net/media/ruffle-nightly-2022_10_14-selfhosted/core.ruffle.166543534d0d6de8f27f.js:1:6847)
    at std::sync::once::Once::call_once::{{closure}}::hf9ee3cf8881ab9cc (wasm://wasm/01800c06:wasm-function[1030]:0x2a119d)
    at std::sync::once::Once::call_inner::hb30cfbde5209eed0 (wasm://wasm/01800c06:wasm-function[1498]:0x327c9b)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h9e53a26a8ce616de (wasm://wasm/01800c06:wasm-function[4930]:0x4868ea)
    at std::panicking::rust_panic_with_hook::hb09154fa23e06c37 (wasm://wasm/01800c06:wasm-function[3625]:0x444699)
    at core::panicking::panic_fmt::h9e229748e3ae9f9d (wasm://wasm/01800c06:wasm-function[5121]:0x48a662)
    at core::result::unwrap_failed::h5da0ab182d2c24a1 (wasm://wasm/01800c06:wasm-function[4222]:0x46d686)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::h242271782ef79a90 (wasm://wasm/01800c06:wasm-function[709]:0x229370)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_render::backend::RenderBackend>::register_shape::h7dab801d8fce0fe7 (wasm://wasm/01800c06:wasm-function[3385]:0x434498)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render_self::hdfaf8b7414baee80 (wasm://wasm/01800c06:wasm-function[2560]:0x3e41fc)
```

# Player Info
Allows script access: false
Renderer: WebGL
Player type: Object
SWF URL: //d.furaffinity.net/art/alsnapz/1590186628/1439336748.alsnapz_panftr_v1_2015_08_11z_release.swf
Param movie: //d.furaffinity.net/art/alsnapz/1590186628/1439336748.alsnapz_panftr_v1_2015_08_11z_release.swf
Param quality: high
Param wmode: direct
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined
Attribute 6: undefined

# Page Info
Page URL: https://www.furaffinity.net/view/17371095/
SWF URL: https://d.furaffinity.net/art/alsnapz/1590186628/1439336748.alsnapz_panftr_v1_2015_08_11z_release.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-10-14
Channel: nightly
Built: 2022-10-14T00:22:21.438Z
Commit: b0b0e55c240e7d505d1ee64f61764de554885e5f
Is extension: false

# Metadata
width: 1000
height: 800
frameRate: 30
numFrames: 23
swfVersion: 8
backgroundColor: #333333
isActionScript3: false
uncompressedLength: 376412

**Comment by kjarosh** [comment]
Should be fixed as of the newest version
