### ISSUE TITLE
Error on https://epog123.github.io/flash/ltf3/

### ISSUE THREAD

**Issue by unnamed1248** [ruffle-rs/ruffle#9206]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create buffer object"', /home/runner/.cargo/git/checkouts/wgpu-e4487c3622394142/f1fdd1c/wgpu-hal/src/gles/device.rs:517:24
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create buffer object"', /home/runner/.cargo/git/checkouts/wgpu-e4487c3622394142/f1fdd1c/wgpu-hal/src/gles/device.rs:517:24
    at W.n.wbg.__wbg_new_f9bb493369a83c12 (https://epog123.github.io/flash/ruffle/core.ruffle.f0ce61b681f73e438823.js:1:5353)
    at std::sync::once::Once::call_once::{{closure}}::h9e3723fd36a2f2e0 (wasm://wasm/0272008a:wasm-function[1569]:0x408f49)
    at std::sys_common::once::generic::Once::call::h8801249ea31ccf7a (wasm://wasm/0272008a:wasm-function[1976]:0x49a317)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h873170ea797b55df (wasm://wasm/0272008a:wasm-function[7083]:0x742711)
    at std::panicking::rust_panic_with_hook::hb42d415afcc11f2f (wasm://wasm/0272008a:wasm-function[5011]:0x6a5bc1)
    at core::panicking::panic_fmt::h32de9c76c9d5eb0c (wasm://wasm/0272008a:wasm-function[7402]:0x751419)
    at core::result::unwrap_failed::h5f2e1804ca266e0b (wasm://wasm/0272008a:wasm-function[5913]:0x6e9dff)
    at wgpu_hal::gles::device::<impl wgpu_hal::Device<wgpu_hal::gles::Api> for wgpu_hal::gles::Device>::create_buffer::h9a83615559ae7356 (wasm://wasm/0272008a:wasm-function[1988]:0x49d78a)
    at wgpu_core::device::Device<A>::create_buffer::he81f312390133546 (wasm://wasm/0272008a:wasm-function[2139]:0x4c1e7a)
    at <T as wgpu::context::DynContext>::device_create_buffer::h4a6eac6f900cb6e3 (wasm://wasm/0272008a:wasm-function[5696]:0x6d969b)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://epog123.github.io/flash/ltf3/
SWF URL: https://epog123.github.io/flash/ltf3/ltf3.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14816.131.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-01-17
Channel: nightly
Built: 2023-01-17T00:23:16.925Z
Commit: 5878bb0c5d6372758eb50b31bb701497205893ad
Is extension: false

# Metadata
width: 720
height: 540
frameRate: 60
numFrames: 3
swfVersion: 28
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 22132440

**Comment by ePog123** [comment]
I should probably add that I was trying to run AS3 content.
