### ISSUE TITLE
Error on https://game117271.konggames.com/games/Rete/villainous/frame/e09fafa7-2852-4817-85fc-74d6d48de3db/

### ISSUE THREAD

**Issue by Cat-Meister** [ruffle-rs/ruffle#9224]
# Error Info
Error name: Error
Error message: panicked at 'already mutably borrowed: BorrowError', core/src/avm2/globals/flash/display/bitmapdata.rs:299:46
Error stack:
```
Error: panicked at 'already mutably borrowed: BorrowError', core/src/avm2/globals/flash/display/bitmapdata.rs:299:46
    at W.n.wbg.__wbg_new_f9bb493369a83c12 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.3d1c00c72fcfbb2885b0.js:1:5353)
    at std::sync::once::Once::call_once::{{closure}}::h5f93984c1300ca75 (wasm://wasm/0271625a:wasm-function[1568]:0x404867)
    at std::sys_common::once::generic::Once::call::h8801249ea31ccf7a (wasm://wasm/0271625a:wasm-function[1975]:0x495c62)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::he904c54109aabe24 (wasm://wasm/0271625a:wasm-function[7083]:0x7404dc)
    at std::panicking::rust_panic_with_hook::hb42d415afcc11f2f (wasm://wasm/0271625a:wasm-function[5006]:0x6a15a5)
    at core::panicking::panic_fmt::h32de9c76c9d5eb0c (wasm://wasm/0271625a:wasm-function[7403]:0x74f240)
    at core::result::unwrap_failed::h5f2e1804ca266e0b (wasm://wasm/0271625a:wasm-function[5914]:0x6e5cf2)
    at gc_arena::gc_cell::GcCell<T>::read::h013f5578868507ca (wasm://wasm/0271625a:wasm-function[6452]:0x718421)
    at ruffle_core::avm2::globals::flash::display::bitmapdata::copy_pixels::h257cd269347a7d71 (wasm://wasm/0271625a:wasm-function[561]:0x188eff)
    at ruffle_core::avm2::function::Executable::exec::h71b787596b0f38ed (wasm://wasm/0271625a:wasm-function[888]:0x2e70af)
```
AVM2 stack:
```
    at flash.display::BitmapData/copyPixels()
    at FireEffect/_-Hm()
    at Preloader/_-Ep()
    at Preloader()
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://game117271.konggames.com/games/Rete/villainous/frame/e09fafa7-2852-4817-85fc-74d6d48de3db/?kongregate_host=www.kongregate.com&swf_player_to_use=Ruffle
SWF URL: http://game117271.konggames.com/gamez/0011/7271/live/TowerConquest_secure.swf?kongregate_game_version=1311177342

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-01-19
Channel: nightly
Built: 2023-01-19T00:18:19.997Z
Commit: f83c573734f569c08197840aeb0fb2cd3dd78028
Is extension: false

# Metadata
width: 800
height: 600
frameRate: 30
numFrames: 2
swfVersion: 10
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 7517173

**Comment by MartySVK** [comment]
same issue - https://github.com/ruffle-rs/ruffle/issues/10032

**Comment by n0samu** [comment]
Seems like this panic disappeared between nighly builds 2023-03-16 and 2023-03-17, though I'm not sure why.
