### ISSUE TITLE
Simple game panicked at 'Error in Queue::submit: not enough memory left'

### ISSUE THREAD

**Issue by Jmousy** [ruffle-rs/ruffle#9260]
# How to reproduce

[Prepared for You.zip](https://github.com/ruffle-rs/ruffle/files/10474010/Prepared.for.You.zip)

When loading is complete, click on the **chocolate cake**(초코케익) on the left of the three cakes. The screen freezes, and refreshes and the crash appears immediately.

This issue works fine on Nightly (confirmed on `2022-12-25`) before the recent graphics-related update. (maybe..?)

![image](https://user-images.githubusercontent.com/75052171/213907329-3156b88b-3da3-4769-a307-ca5a75f4dc86.png)

![image](https://user-images.githubusercontent.com/75052171/213907407-074a29ef-7218-44d0-9036-ddc6e799cbd9.png)

# Error Info
Error name: Error
Error message: panicked at 'Error in Queue::submit: not enough memory left', /home/runner/.cargo/git/checkouts/wgpu-e4487c3622394142/a154700/wgpu/src/backend/direct.rs:306:9
Error stack:
```
Error: panicked at 'Error in Queue::submit: not enough memory left', /home/runner/.cargo/git/checkouts/wgpu-e4487c3622394142/a154700/wgpu/src/backend/direct.rs:306:9
    at W.n.wbg.__wbg_new_f9bb493369a83c12 (https://ruffle.rs/demo/966.index.js:1:5341)
    at std::sync::once::Once::call_once::{{closure}}::h7ddedd4f5478200a (wasm://wasm/0272a32a:wasm-function[1579]:0x40bb4a)
    at std::sys_common::once::generic::Once::call::h8801249ea31ccf7a (wasm://wasm/0272a32a:wasm-function[1980]:0x49f578)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h62e682da65381621 (wasm://wasm/0272a32a:wasm-function[7089]:0x744af5)
    at std::panicking::rust_panic_with_hook::hb42d415afcc11f2f (wasm://wasm/0272a32a:wasm-function[5016]:0x6a5714)
    at core::panicking::panic_fmt::h32de9c76c9d5eb0c (wasm://wasm/0272a32a:wasm-function[7409]:0x753867)
    at <T as wgpu::context::DynContext>::queue_submit::h4a84a8d88714423b (wasm://wasm/0272a32a:wasm-function[2427]:0x5265fa)
    at <ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::submit_frame::hf71fd84f1454b1e5 (wasm://wasm/0272a32a:wasm-function[823]:0x2b619e)
    at ruffle_web::Ruffle::tick::h13d7cda5593ef0ec (wasm://wasm/0272a32a:wasm-function[636]:0x20ba5c)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h832db464f1ced67f (wasm://wasm/0272a32a:wasm-function[8932]:0x78d1c4)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://ruffle.rs/demo/

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-01-22
Channel: nightly
Built: 2023-01-22T00:18:44.495Z
Commit: 8717aff938542c03a093b4a2067b6c0ea58e0506
Is extension: false

# Metadata
width: 400
height: 300
frameRate: 12
numFrames: 105
swfVersion: 4
backgroundColor: #FFFFFF
isActionScript3: false
uncompressedLength: 319469

**Comment by n0samu** [comment]
Okay, this is quite bad... I'm surprised anything that happens in the browser can cause this.
![image](https://user-images.githubusercontent.com/71368227/213907641-459eb5c4-2a65-4248-83d1-0bb8b80dc3c1.png)

**Comment by n0samu** [comment]
And this is definitely a wgpu issue because if I force the WebGL renderer to be used, the problem goes away.

**Comment by Jmousy** [comment]
I don't know if it's helpful, but I'm attaching my system environment as well:

- OS: Windows 10 Pro 22H2
- CPU: Intel Core i5-7500
- Memory: 24 GB
- GPU: NVIDIA Geforce 1070 ti
