### ISSUE TITLE
Error on https://game115608.konggames.com/games/light_bringer777/learn-to-fly-2/frame/7008023d-e623-4959-ba58-3d1b1416625d/

### ISSUE THREAD

**Issue by BrtulaArme** [ruffle-rs/ruffle#9264]
# Error Info| (crashing when ramp length is 5 points or more)
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/bitmap/bitmap_data.rs:1294:22
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/bitmap/bitmap_data.rs:1294:22
    at W.n.wbg.__wbg_new_f9bb493369a83c12 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.19c6df49ad4e68a0d8c4.js:1:5353)
    at std::sync::once::Once::call_once::{{closure}}::h5f93984c1300ca75 (wasm://wasm/0272537e:wasm-function[1577]:0x40b296)
    at std::sys_common::once::generic::Once::call::h8801249ea31ccf7a (wasm://wasm/0272537e:wasm-function[1978]:0x49ecc4)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::he904c54109aabe24 (wasm://wasm/0272537e:wasm-function[7085]:0x743b54)
    at std::panicking::rust_panic_with_hook::hb42d415afcc11f2f (wasm://wasm/0272537e:wasm-function[5011]:0x6a469e)
    at core::panicking::panic_fmt::h32de9c76c9d5eb0c (wasm://wasm/0272537e:wasm-function[7405]:0x752898)
    at core::panicking::panic::hff08c7cf90edd9fe (wasm://wasm/0272537e:wasm-function[7127]:0x745aea)
    at ruffle_core::bitmap::bitmap_data::BitmapData::draw::h630d9a6cfd468667 (wasm://wasm/0272537e:wasm-function[984]:0x31d2ba)
    at ruffle_core::avm1::globals::bitmap_data::draw::h0f6251a09d0449d2 (wasm://wasm/0272537e:wasm-function[580]:0x1a45da)
    at ruffle_core::avm1::function::Executable::exec::h2e3cc91fdb59f4a0 (wasm://wasm/0272537e:wasm-function[571]:0x1983a5)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://game115608.konggames.com/games/light_bringer777/learn-to-fly-2/frame/7008023d-e623-4959-ba58-3d1b1416625d/?kongregate_host=www.kongregate.com
SWF URL: https://game115608.konggames.com/gamez/0011/5608/live/secure_Learn2Fly.swf?kongregate_game_version=1541118719

# Browser Info
User Agent: Mozilla/5.0 (Linux; Android 10; V TAB Z1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Platform: Linux armv8l
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-01-22
Channel: nightly
Built: 2023-01-22T00:21:09.604Z
Commit: 8717aff938542c03a093b4a2067b6c0ea58e0506
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 33
numFrames: 46
swfVersion: 10
backgroundColor: #2379B1
isActionScript3: false
uncompressedLength: 7042769

**Comment by BrtulaArme** [comment]
If you get 5 points of ramp length or more the game crashes when you play.

**Comment by BrtulaArme** [comment]
Update: hitting the final obstacle (wall) also crashes the game. İ'm starting to think that's because i'm playing on mobile. But perhaps it can be fixed?

**Comment by Lord-McSweeney** [comment]
Original issue still happening- see #13036.
