### ISSUE TITLE
Error on https://www.dolldivine.com/ascension-couple-creator

### ISSUE THREAD

**Issue by Rhart19** [ruffle-rs/ruffle#9267]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: UnableToCreateVAO', render/webgl/src/lib.rs:582:23
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: UnableToCreateVAO', render/webgl/src/lib.rs:582:23
    at D.n.wbg.__wbg_new_f9bb493369a83c12 (https://www.dolldivine.com/ruffle/core.ruffle.76697483ef0100b9d528.js:1:6432)
    at std::sync::once::Once::call_once::{{closure}}::h456b15a3372f5cac (wasm://wasm/018d6452:wasm-function[1098]:0x2a59d6)
    at std::sys_common::once::generic::Once::call::h62f79875d8dd2a00 (wasm://wasm/018d6452:wasm-function[1390]:0x30d6f1)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::haaf675683a690fa4 (wasm://wasm/018d6452:wasm-function[5077]:0x4ae89e)
    at std::panicking::rust_panic_with_hook::he04cb00575f2a1e3 (wasm://wasm/018d6452:wasm-function[3738]:0x469820)
    at core::panicking::panic_fmt::h586d720a90aa8503 (wasm://wasm/018d6452:wasm-function[5283]:0x4b2ce3)
    at core::result::unwrap_failed::h1d03d3774c363770 (wasm://wasm/018d6452:wasm-function[4360]:0x4919fb)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::haadc26a5d1537fc7 (wasm://wasm/018d6452:wasm-function[631]:0x1e6baf)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_render::backend::RenderBackend>::register_shape::h598fce9bbe5b531b (wasm://wasm/018d6452:wasm-function[3609]:0x461272)
    at ruffle_core::display_object::movie_clip::MovieClipData::define_shape::hf39a7586a673ee67 (wasm://wasm/018d6452:wasm-function[2327]:0x3e4d98)
```

# Player Info
Allows script access: true
Renderer: WebGL

# Page Info
Page URL: https://www.dolldivine.com/ascension-couple-creator
SWF URL: https://www.dolldivine.com/games/main.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Platform: Linux aarch64
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-01-05
Channel: nightly
Built: 2023-01-05T00:14:28.740Z
Commit: 4919e2a638701d6606d2d5b1e01b535de62da98f
Is extension: false

# Metadata
width: 900
height: 650
frameRate: 24
numFrames: 3
swfVersion: 15
backgroundColor: #FFFFFF
isActionScript3: false
uncompressedLength: 9162519

**Comment by kjarosh** [comment]
Should be fixed as of the newest version
