### ISSUE TITLE
Error on https://taco.topgweb.repl.co/prefix/aHR0cHM6Ly93d3cudHdvcGxheWVyZ2FtZXMub3Jn/gameframe/dunkers

### ISSUE THREAD

**Issue by solalusi** [ruffle-rs/ruffle#9290]
# Error Info
Error name: TypeError
Error message: str.startsWith is not a function
Error stack:
```
TypeError: str.startsWith is not a function
    at rewrite_url (https://taco.topgweb.repl.co/prefix/static/inject.js:11:13)
    at window.fetch (https://taco.topgweb.repl.co/prefix/static/inject.js:31:11)
    at https://taco.topgweb.repl.co/prefix/aHR0cHM6Ly93d3cudHdvcGxheWVyZ2FtZXMub3Jn/dist/ruffle/ruffle.js:1:5466
    at async E.ensureFreshInstance (https://taco.topgweb.repl.co/prefix/aHR0cHM6Ly93d3cudHdvcGxheWVyZ2FtZXMub3Jn/dist/ruffle/ruffle.js:1:23595)
    at async E.load (https://taco.topgweb.repl.co/prefix/aHR0cHM6Ly93d3cudHdvcGxheWVyZ2FtZXMub3Jn/dist/ruffle/ruffle.js:1:26460)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://taco.topgweb.repl.co/prefix/aHR0cHM6Ly93d3cudHdvcGxheWVyZ2FtZXMub3Jn/gameframe/dunkers

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 15183.78.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-11-12
Channel: nightly
Built: 2022-11-12T00:15:57.157Z
Commit: 08270efee72ab8fe31b1448d76bcda09c8af264e
Is extension: false

# Metadata

**Comment by n0samu** [comment]
Same issue as #5619
