### ISSUE TITLE
Error on chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/player.html

### ISSUE THREAD

**Issue by nikitadrokin** [ruffle-rs/ruffle#9299]
# Error Info
Error name: Error
Error message: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:594:9
Error stack:
```
Error: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:594:9
    at imports.wbg.__wbg_new_f9bb493369a83c12 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:593:21)
    at std::sync::once::Once::call_once::{{closure}}::h12bc79b958c1e518 (wasm://wasm/027a3dee:wasm-function[1588]:0x414c8d)
    at std::sys_common::once::generic::Once::call::h8801249ea31ccf7a (wasm://wasm/027a3dee:wasm-function[1997]:0x4aa604)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::ha4d6c55415044158 (wasm://wasm/027a3dee:wasm-function[7154]:0x760447)
    at std::panicking::rust_panic_with_hook::hb42d415afcc11f2f (wasm://wasm/027a3dee:wasm-function[5075]:0x6bcb69)
    at core::panicking::panic_fmt::h32de9c76c9d5eb0c (wasm://wasm/027a3dee:wasm-function[7478]:0x76f21d)
    at core::option::expect_failed::hb1beef3e49ebedf1 (wasm://wasm/027a3dee:wasm-function[8566]:0x798add)
    at ruffle_core::display_object::stage::Stage::root_clip::hee2f08cf0070ee82 (wasm://wasm/027a3dee:wasm-function[4159]:0x66ad49)
    at ruffle_web::Ruffle::tick::h6a410a69eebc2a8c (wasm://wasm/027a3dee:wasm-function[639]:0x211e3c)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h18ff63d9e5cad5c8 (wasm://wasm/027a3dee:wasm-function[9009]:0x7a91b7)
```

# Player Info
Allows script access: false

# Page Info
Page URL: chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/player.html?url=https%3A%2F%2F13f2309a-a-62cb3a1a-s-sites.googlegroups.com%2Fsite%2F34567u786564656578yui%2FRobot%2520Wants%2520Fishy.swf%3Fattachauth%3DANoY7cp_IXwHwdOc5R4tSZ2Xw3ad66_xVkyF8tYUwwzQYgZU4-qr1HFP2x9sUgOg5r_VPmffW5iWljhcZBOJLry40gWArbQVKhXS0wBHrYXa05vwVRd_pR5t47WE14zA-2UpDHqvZmbpNh1qBisQEbAGsRb5XQfOSoK0rtgbwwgHqZEaknS599rRL7D6XTnO77SFqqW8jOemn6fNuDrRtP4qczqZlphkKKQb9UIpfNU-VJL3bulPBVc%253D%26attredirects%3D1
SWF URL: https://13f2309a-a-62cb3a1a-s-sites.googlegroups.com/site/34567u786564656578yui/Robot%20Wants%20Fishy.swf?attachauth=ANoY7cp_IXwHwdOc5R4tSZ2Xw3ad66_xVkyF8tYUwwzQYgZU4-qr1HFP2x9sUgOg5r_VPmffW5iWljhcZBOJLry40gWArbQVKhXS0wBHrYXa05vwVRd_pR5t47WE14zA-2UpDHqvZmbpNh1qBisQEbAGsRb5XQfOSoK0rtgbwwgHqZEaknS599rRL7D6XTnO77SFqqW8jOemn6fNuDrRtP4qczqZlphkKKQb9UIpfNU-VJL3bulPBVc%3D&attredirects=1

# Browser Info
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Platform: MacIntel
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-01-25
Channel: nightly
Built: 2023-01-25T00:23:19.947Z
Commit: f213ec40fc92ddb5e41573594b2737262d17a04c
Is extension: true

# Metadata
width: 640
height: 480
frameRate: 60
numFrames: 2
swfVersion: 10
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 2791593

**Comment by kjarosh** [comment]
Should be fixed as of the newest version
