### ISSUE TITLE
Error on https://www.jogos360.com.br/soccer_dribble.html

### ISSUE THREAD

**Issue by AliceGrem** [ruffle-rs/ruffle#9311]
# Error Info
Error name: Error
Error message: panicked at 'No script object for display object', core/src/avm1/activation.rs:379:18
Error stack:
```
Error: panicked at 'No script object for display object', core/src/avm1/activation.rs:379:18
    at W.n.wbg.__wbg_new_f9bb493369a83c12 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.09e6298eafa7ebdb12d1.js:1:5353)
    at std::sync::once::Once::call_once::{{closure}}::h12bc79b958c1e518 (wasm://wasm/027a3dee:wasm-function[1588]:0x414c8d)
    at std::sys_common::once::generic::Once::call::h8801249ea31ccf7a (wasm://wasm/027a3dee:wasm-function[1997]:0x4aa604)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::ha4d6c55415044158 (wasm://wasm/027a3dee:wasm-function[7154]:0x760447)
    at std::panicking::rust_panic_with_hook::hb42d415afcc11f2f (wasm://wasm/027a3dee:wasm-function[5075]:0x6bcb69)
    at core::panicking::panic_fmt::h32de9c76c9d5eb0c (wasm://wasm/027a3dee:wasm-function[7478]:0x76f1ef)
    at ruffle_core::display_object::edit_text::EditText::try_bind_text_field_variable::habc4d773a7cfb069 (wasm://wasm/027a3dee:wasm-function[3502]:0x61a9de)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::hf1a63820ef35f3aa (wasm://wasm/027a3dee:wasm-function[2715]:0x577ecc)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::h3078917b731fc5e4 (wasm://wasm/027a3dee:wasm-function[720]:0x2667a2)
    at ruffle_core::display_object::movie_clip::MovieClip::place_object::hdf5de2c34de0aaa3 (wasm://wasm/027a3dee:wasm-function[1543]:0x4079a1)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.jogos360.com.br/soccer_dribble.html
SWF URL: https://cdn.jogos360.com.br/files/games/so/cc/soccer-dribble.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-01-25
Channel: nightly
Built: 2023-01-25T00:23:19.947Z
Commit: f213ec40fc92ddb5e41573594b2737262d17a04c
Is extension: false

# Metadata
width: 550
height: 400
frameRate: 30
numFrames: 2
swfVersion: 10
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 489984

**Comment by Lord-McSweeney** [comment]
Fixed by #11005
