### ISSUE TITLE
Error on https://armorgames.com/play/15272/mars-colonies

### ISSUE THREAD

**Issue by riek-lt** [ruffle-rs/ruffle#9313]
# Error Info
Error name: Error
Error message: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:594:9
Error stack:
```
Error: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:594:9
    at W.n.wbg.__wbg_new_f9bb493369a83c12 (https://agi.armorgames.com/ruffle/latest/core.ruffle.bcc051e635a9e70a739a.js:1:5353)
    at std::sync::once::Once::call_once::{{closure}}::h7e6b96cea392c96b (wasm://wasm/027a46de:wasm-function[1590]:0x415453)
    at std::sys_common::once::generic::Once::call::h8801249ea31ccf7a (wasm://wasm/027a46de:wasm-function[1995]:0x4a9f65)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hd937bf3f89ff4f2e (wasm://wasm/027a46de:wasm-function[7150]:0x760542)
    at std::panicking::rust_panic_with_hook::hb42d415afcc11f2f (wasm://wasm/027a46de:wasm-function[5077]:0x6bcf17)
    at core::panicking::panic_fmt::h32de9c76c9d5eb0c (wasm://wasm/027a46de:wasm-function[7474]:0x76f036)
    at core::option::expect_failed::hb1beef3e49ebedf1 (wasm://wasm/027a46de:wasm-function[8562]:0x79890e)
    at ruffle_core::display_object::stage::Stage::root_clip::h7bc7f9770350bcdf (wasm://wasm/027a46de:wasm-function[4161]:0x66b0d2)
    at ruffle_web::Ruffle::tick::he5328642d8ee868f (wasm://wasm/027a46de:wasm-function[639]:0x212028)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h9c9cb17dca020579 (wasm://wasm/027a46de:wasm-function[9006]:0x7a918b)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://armorgames.com/play/15272/mars-colonies?ruffle
SWF URL: https://cache.armorgames.com/files/games/mars-colonies-15272.swf?v=1373587528

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-01-26
Channel: nightly
Built: 2023-01-26T00:19:01.046Z
Commit: 56fd9adbf91c01440fae7dc1d2024aa297938b43
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 30
numFrames: 2
swfVersion: 10
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 6556598

**Comment by kjarosh** [comment]
Should be fixed as of the newest version
