### ISSUE TITLE
Ruffle Error on https://freeinvaders.org/

### ISSUE THREAD

**Issue by IvoVelinov02** [ruffle-rs/ruffle#9314]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:477:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:477:50
    at Object.Q (https://turbo.freevideogamesonline.org/includes/js/flash-emulator/core.ruffle.5e850f90e6e2fab0bb54.js:1:20877)
    at __wbg_new_df6e6ab7a65c4c4d (https://turbo.freevideogamesonline.org/includes/js/flash-emulator/ruffle.js:1:38192)
    at https://turbo.freevideogamesonline.org/includes/js/flash-emulator/cbe7657b7dc9d70da5a6.module.wasm:wasm-function[1324]:0x254c8e
    at https://turbo.freevideogamesonline.org/includes/js/flash-emulator/cbe7657b7dc9d70da5a6.module.wasm:wasm-function[1491]:0x272a47
    at https://turbo.freevideogamesonline.org/includes/js/flash-emulator/cbe7657b7dc9d70da5a6.module.wasm:wasm-function[4066]:0x338300
    at https://turbo.freevideogamesonline.org/includes/js/flash-emulator/cbe7657b7dc9d70da5a6.module.wasm:wasm-function[3161]:0x315621
    at https://turbo.freevideogamesonline.org/includes/js/flash-emulator/cbe7657b7dc9d70da5a6.module.wasm:wasm-function[4375]:0x33d2f1
    at https://turbo.freevideogamesonline.org/includes/js/flash-emulator/cbe7657b7dc9d70da5a6.module.wasm:wasm-function[4405]:0x33d854
    at https://turbo.freevideogamesonline.org/includes/js/flash-emulator/cbe7657b7dc9d70da5a6.module.wasm:wasm-function[4277]:0x33be08
    at https://turbo.freevideogamesonline.org/includes/js/flash-emulator/cbe7657b7dc9d70da5a6.module.wasm:wasm-function[4406]:0x33d88a
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://freeinvaders.org/
SWF URL: https://freeinvaders.org/space-invaders.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2020-12-31
Channel: nightly
Built: 2020-12-31T00:48:27.350Z
Commit: ea3b6f59dfd7c528f2ae305c4dba2d351ada9302

**Comment by Croworbit** [comment]
This website uses a version of ruffle from 2020, thats 4 years out of date!

they broke CORS, and they need to update their site and they need to update Ruffle. let them know!

their email is `hello@freevideogames.org `

**Comment by kjarosh** [comment]
Should be fixed as of the newest version
