### ISSUE TITLE
Error on https://www.comdotgame.com/play/how-to-discipline-a-shoplifting-girl-english

### ISSUE THREAD

**Issue by Upyours1** [ruffle-rs/ruffle#9331]
# Error Info
Error name: Error
Error message: panicked at 'assertion failed: min <= max', /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/cmp.rs:869:9
Error stack:
```
Error: panicked at 'assertion failed: min <= max', /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/cmp.rs:869:9
    at V.e.wbg.__wbg_new_f9bb493369a83c12 (https://echo.comdotgame.com/ruffle/core.ruffle.f6ddc5b37c1f42d63f0c.js:1:7410)
    at std::sync::once::Once::call_once::{{closure}}::hcd46b3a2543691b9 (<anonymous>:wasm-function[871]:0x273145)
    at std::sync::once::Once::call_inner::h34aee843864daceb (<anonymous>:wasm-function[1449]:0x343fb2)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hb7a03847d0b7780a (<anonymous>:wasm-function[5006]:0x4daa44)
    at std::panicking::rust_panic_with_hook::h70a0e195f4db2a29 (<anonymous>:wasm-function[3787]:0x49676b)
    at core::panicking::panic_fmt::h751be80779d42b53 (<anonymous>:wasm-function[5248]:0x4e368c)
    at core::panicking::panic::h8af046397a2bf65d (<anonymous>:wasm-function[5062]:0x4db9f8)
    at ruffle_core::player::Player::update_drag::h3b82de7de88e95e5 (<anonymous>:wasm-function[1553]:0x35fc88)
    at ruffle_core::player::Player::handle_event::h67a0dcfc0425a08f (<anonymous>:wasm-function[328]:0xb6cee)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::hadcfa7fd1304c7f0 (<anonymous>:wasm-function[1103]:0x2cc3be)
```

# Player Info
Allows script access: true
Renderer: WebGL
Player type: Object
SWF URL: https://echo.comdotgame.com/4x90xhl3k0/games/files/70013404b08967ba2c8d5f70b0d4a1d3.swf
Param allowscriptaccess: always
Param bgcolor: ffffff
Param wmode: gpu
Param base: https://echo.comdotgame.com/4x90xhl3k0/games/files/how-to-discipline-a-shoplifting-girl-english/
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined
Attribute 6: undefined

# Page Info
Page URL: https://www.comdotgame.com/play/how-to-discipline-a-shoplifting-girl-english
SWF URL: https://echo.comdotgame.com/4x90xhl3k0/games/files/70013404b08967ba2c8d5f70b0d4a1d3.swf

# Browser Info
User Agent: Mozilla/5.0 (Linux; Android 9; LM-T600) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36
Platform: Linux armv8l
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-12-07
Channel: nightly
Built: 2022-12-07T00:18:07.185Z
Commit: 2bb4e2e549ab39d2f2cb7d8194ac21bb1ca2e682
Is extension: false

# Metadata
width: 600
height: 600
frameRate: 24
numFrames: 124
swfVersion: 10
backgroundColor: #999999
isActionScript3: true
uncompressedLength: 18499220

**Comment by Lord-McSweeney** [comment]
This issue has already been fixed. Contact the site owner and tell them to update their Ruffle version.
