### ISSUE TITLE
Error on chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/player.html

### ISSUE THREAD

**Issue by Mebrouk2006** [ruffle-rs/ruffle#9336]
# Error Info
Error name: Error
Error message: panicked at 'Error in Queue::submit: not enough memory left', /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/c585127/wgpu/src/backend/direct.rs:316:9
Error stack:
```
Error: panicked at 'Error in Queue::submit: not enough memory left', /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/c585127/wgpu/src/backend/direct.rs:316:9
    at imports.wbg.__wbg_new_f9bb493369a83c12 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:593:21)
    at std::sync::once::Once::call_once::{{closure}}::hc4aa6f2ed20b0f6c (wasm://wasm/027be45a:wasm-function[1923]:0x4853bd)
    at std::sys_common::once::generic::Once::call::he3f17a186e209b2a (wasm://wasm/027be45a:wasm-function[1855]:0x475687)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h39b0b077af712957 (wasm://wasm/027be45a:wasm-function[7194]:0x7698d9)
    at std::panicking::rust_panic_with_hook::hd000e9fb43b5781d (wasm://wasm/027be45a:wasm-function[5102]:0x6c565a)
    at core::panicking::panic_fmt::h9d972fcdb087ce21 (wasm://wasm/027be45a:wasm-function[7500]:0x7784a6)
    at <T as wgpu::context::DynContext>::queue_submit::h97dc6bdfcc99c455 (wasm://wasm/027be45a:wasm-function[2310]:0x508db1)
    at <ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::submit_frame::hc5c8a8249bfa1da9 (wasm://wasm/027be45a:wasm-function[810]:0x285de7)
    at ruffle_web::Ruffle::tick::h98a74f07ff5c61e0 (wasm://wasm/027be45a:wasm-function[654]:0x2060bf)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h9e6d9796ffd9ddd4 (wasm://wasm/027be45a:wasm-function[9047]:0x7b09ef)
```

# Player Info
Allows script access: false

# Page Info
Page URL: chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/player.html?url=https%3A%2F%2Fwixmp-ed30a86b8c4ca887773594c2.wixmp.com%2Ff%2F5ea6eb44-c9ae-4a5b-87f8-6e422b9daeef%2Fde3k6b-bd294585-4853-4dbe-a16e-d89608e9d209.swf%3Ftoken%3DeyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsImV4cCI6MTY3NDk0MDU3MSwiaWF0IjoxNjc0OTM5OTYxLCJqdGkiOiI2M2Q1OGU0M2E2NDE3Iiwib2JqIjpbW3sicGF0aCI6IlwvZlwvNWVhNmViNDQtYzlhZS00YTViLTg3ZjgtNmU0MjJiOWRhZWVmXC9kZTNrNmItYmQyOTQ1ODUtNDg1My00ZGJlLWExNmUtZDg5NjA4ZTlkMjA5LnN3ZiJ9XV0sImF1ZCI6WyJ1cm46c2VydmljZTpmaWxlLmRvd25sb2FkIl19.Q5nt9pImP916BbkT2lGW-iYKrRMy9BQEyjxWMXNCrLY%26filename%3Dbunnykill_by_mottis_de3k6b.swf
SWF URL: https://wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/5ea6eb44-c9ae-4a5b-87f8-6e422b9daeef/de3k6b-bd294585-4853-4dbe-a16e-d89608e9d209.swf?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsImV4cCI6MTY3NDk0MDU3MSwiaWF0IjoxNjc0OTM5OTYxLCJqdGkiOiI2M2Q1OGU0M2E2NDE3Iiwib2JqIjpbW3sicGF0aCI6IlwvZlwvNWVhNmViNDQtYzlhZS00YTViLTg3ZjgtNmU0MjJiOWRhZWVmXC9kZTNrNmItYmQyOTQ1ODUtNDg1My00ZGJlLWExNmUtZDg5NjA4ZTlkMjA5LnN3ZiJ9XV0sImF1ZCI6WyJ1cm46c2VydmljZTpmaWxlLmRvd25sb2FkIl19.Q5nt9pImP916BbkT2lGW-iYKrRMy9BQEyjxWMXNCrLY&filename=bunnykill_by_mottis_de3k6b.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-01-28
Channel: nightly
Built: 2023-01-28T00:24:19.196Z
Commit: 7d234956eb425652342103ea55fae58272601029
Is extension: true

# Metadata
width: 300
height: 200
frameRate: 18
numFrames: 4107
swfVersion: 5
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 4138248

**Comment by sombraguerrero** [comment]
https://www.deviantart.com/mottis/art/Bunnykill-23680739

**Comment by sombraguerrero** [comment]
[bunnykill_by_mottis_de3k6b.zip](https://github.com/ruffle-rs/ruffle/files/10528615/bunnykill_by_mottis_de3k6b.zip)
