### ISSUE TITLE
Error on http://www.oyuncenneti.com/sakin-olme-oyna.html

### ISSUE THREAD

**Issue by RagonTEC** [ruffle-rs/ruffle#9343]
# Error Info
Error name: Error
Error message: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:594:9
Error stack:
```
Error: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:594:9
    at W.n.wbg.__wbg_new_f9bb493369a83c12 (http://www.oyuncenneti.com/core.ruffle.aa79af40580d7ea81bb1.js:1:5285)
    at std::sync::once::Once::call_once::{{closure}}::h636b0dd15fef5920 (wasm://wasm/019957ea:wasm-function[1106]:0x2b89bb)
    at std::sys_common::once::generic::Once::call::h62f79875d8dd2a00 (wasm://wasm/019957ea:wasm-function[1429]:0x331b7b)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h659018fbe4d07f63 (wasm://wasm/019957ea:wasm-function[4919]:0x4c57ce)
    at std::panicking::rust_panic_with_hook::he04cb00575f2a1e3 (wasm://wasm/019957ea:wasm-function[3601]:0x4836dc)
    at core::panicking::panic_fmt::h586d720a90aa8503 (wasm://wasm/019957ea:wasm-function[5127]:0x4cb247)
    at core::option::expect_failed::h1e9a9cbb22bbd6ac (wasm://wasm/019957ea:wasm-function[5822]:0x4ed593)
    at ruffle_core::display_object::stage::Stage::root_clip::h667f15876c5b22e5 (wasm://wasm/019957ea:wasm-function[3609]:0x483d9c)
    at ruffle_web::Ruffle::tick::h5694d464ab31f20e (wasm://wasm/019957ea:wasm-function[408]:0x11131e)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::hcb5bf027e71ffda6 (wasm://wasm/019957ea:wasm-function[6071]:0x4f5bb2)
```

# Player Info
Allows script access: true
null

# Page Info
Page URL: http://www.oyuncenneti.com/sakin-olme-oyna.html
SWF URL: http://www.oyuncenneti.com/oyunlar/sakin_olme.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-01-10
Channel: nightly
Built: 2023-01-10T00:15:26.678Z
Commit: 14ee9b43fb077d73d332db2fdef705be1f687958
Is extension: false

# Metadata
width: 792
height: 600
frameRate: 60
numFrames: 2
swfVersion: 14
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 1465215

**Comment by kjarosh** [comment]
Should be fixed as of the newest version
