### ISSUE TITLE
Error on https://www.play-games.com/embed/15001.html

### ISSUE THREAD

**Issue by sussybakav3** [ruffle-rs/ruffle#9345]
# Error Info
Error name: Error
Error message: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:580:9
Error stack:
```
Error: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:580:9
    at D.n.wbg.__wbg_new_f9bb493369a83c12 (https://www.play-games.com/js/frontend/vendor/ruffle/core.ruffle.d923f9d0e46b0ebe5a5e.js:1:6432)
    at std::sync::once::Once::call_once::{{closure}}::h07c839951d6d0b0f (wasm://wasm/018fe846:wasm-function[1095]:0x2baf52)
    at std::sys_common::once::generic::Once::call::h62f79875d8dd2a00 (wasm://wasm/018fe846:wasm-function[1401]:0x32164a)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h5a01fde47a9be61a (wasm://wasm/018fe846:wasm-function[5064]:0x4b4dee)
    at std::panicking::rust_panic_with_hook::he04cb00575f2a1e3 (wasm://wasm/018fe846:wasm-function[3743]:0x4761b0)
    at core::panicking::panic_fmt::h586d720a90aa8503 (wasm://wasm/018fe846:wasm-function[5305]:0x4b9c25)
    at core::option::expect_failed::h1e9a9cbb22bbd6ac (wasm://wasm/018fe846:wasm-function[5981]:0x4cd016)
    at ruffle_core::display_object::stage::Stage::root_clip::h08fdee4bec874afd (wasm://wasm/018fe846:wasm-function[3748]:0x4765c6)
    at ruffle_web::Ruffle::tick::h5ebf2eb5e40a6af5 (wasm://wasm/018fe846:wasm-function[647]:0x1fa302)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h827cf3c1225c1c3e (wasm://wasm/018fe846:wasm-function[6225]:0x4d5378)
```

# Player Info
Allows script access: false
Renderer: WebGL

# Page Info
Page URL: https://www.play-games.com/embed/15001.html
SWF URL: https://www.play-games.com/files/swf/dead-paradise-2_1491306225.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Platform: Win32
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-01-03
Channel: nightly
Built: 2023-01-03T00:14:54.147Z
Commit: 0e2fbe4cf79011710b71191fb58e13b9811c72dc
Is extension: false

# Metadata
width: 800
height: 600
frameRate: 31
numFrames: 2
swfVersion: 14
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 16453979

**Comment by kjarosh** [comment]
Should be fixed as of the newest version
