### ISSUE TITLE
Error on chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/player.html

### ISSUE THREAD

**Issue by Stefflontwerk4nic** [ruffle-rs/ruffle#9348]
# Error Info
Error name: Error
Error message: panicked at 'No script object for display object', core/src/avm1/activation.rs:379:18
Error stack:
```
Error: panicked at 'No script object for display object', core/src/avm1/activation.rs:379:18
    at imports.wbg.__wbg_new_f9bb493369a83c12 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:593:21)
    at std::sync::once::Once::call_once::{{closure}}::hc4aa6f2ed20b0f6c (wasm://wasm/027bebea:wasm-function[1923]:0x4853c5)
    at std::sys_common::once::generic::Once::call::he3f17a186e209b2a (wasm://wasm/027bebea:wasm-function[1855]:0x47568f)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h39b0b077af712957 (wasm://wasm/027bebea:wasm-function[7195]:0x7699e6)
    at std::panicking::rust_panic_with_hook::hd000e9fb43b5781d (wasm://wasm/027bebea:wasm-function[5103]:0x6c5767)
    at core::panicking::panic_fmt::h9d972fcdb087ce21 (wasm://wasm/027bebea:wasm-function[7501]:0x778585)
    at ruffle_core::display_object::edit_text::EditText::try_bind_text_field_variable::h1c0716b554583491 (wasm://wasm/027bebea:wasm-function[3509]:0x61f709)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::h671a6c5204c416e2 (wasm://wasm/027bebea:wasm-function[2708]:0x57a140)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::heacfe26b9f67eda3 (wasm://wasm/027bebea:wasm-function[727]:0x2445ce)
    at ruffle_core::display_object::movie_clip::MovieClip::place_object::hc8ebefe79037126d (wasm://wasm/027bebea:wasm-function[1232]:0x365c90)
```

# Player Info
Allows script access: false

# Page Info
Page URL: chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/player.html?url=https%3A%2F%2Fwww.sevelina.com%2Fimages%2Fswf%2Fhalloween-best-friends.swf
SWF URL: https://www.sevelina.com/images/swf/halloween-best-friends.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Platform: Win32
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-01-29
Channel: nightly
Built: 2023-01-29T00:19:12.661Z
Commit: 85dc100ee9d353d842433ec24430a934401fb035
Is extension: true

# Metadata
width: 745
height: 540
frameRate: 30
numFrames: 2
swfVersion: 10
backgroundColor: #FFFFFF
isActionScript3: true
uncompressedLength: 1101480

**Comment by Stefflontwerk4nic** [comment]
# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) HD Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: PUSH_CONSTANTS
Available features: TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | CLEAR_TEXTURE | MULTIVIEW
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface samples: 4
Surface size: Extent3d { width: 745, height: 540, depth_or_array_layers: 1 }

# Page Info
Page URL: https://sevelina.com/dress-up/chic-capes/
SWF URL: https://sevelina.com/images/swf/capes.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Platform: Win32
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-01-29
Channel: nightly
Built: 2023-01-29T00:19:12.661Z
Commit: 85dc100ee9d353d842433ec24430a934401fb035
Is extension: true

# Metadata
width: 745
height: 540
frameRate: 24
numFrames: 2
swfVersion: 10
backgroundColor: #FFFFFF
isActionScript3: true
uncompressedLength: 619233 sevelina dress up site please fix issue i love this website.

**Comment by Lord-McSweeney** [comment]
Fixed by #11005
