### ISSUE TITLE
Error on chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/player.html

### ISSUE THREAD

**Issue by Stefflontwerk4nic** [ruffle-rs/ruffle#9352]
# Error Info
Error name: Error
Error message: panicked at 'No script object for display object', core/src/avm1/activation.rs:379:18
Error stack:
```
Error: panicked at 'No script object for display object', core/src/avm1/activation.rs:379:18
    at imports.wbg.__wbg_new_f9bb493369a83c12 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:596:21)
    at std::sync::once::Once::call_once::{{closure}}::h24436b3e76607d05 (wasm://wasm/027c294e:wasm-function[1925]:0x4855e1)
    at std::sys_common::once::generic::Once::call::he3f17a186e209b2a (wasm://wasm/027c294e:wasm-function[1857]:0x4758ab)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hdf8faf7e861f36fc (wasm://wasm/027c294e:wasm-function[7197]:0x769895)
    at std::panicking::rust_panic_with_hook::hd000e9fb43b5781d (wasm://wasm/027c294e:wasm-function[5104]:0x6c4a1f)
    at core::panicking::panic_fmt::h9d972fcdb087ce21 (wasm://wasm/027c294e:wasm-function[7502]:0x7783f5)
    at ruffle_core::display_object::edit_text::EditText::try_bind_text_field_variable::ha4a007830dee0088 (wasm://wasm/027c294e:wasm-function[3507]:0x61f1de)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::h2852286861940ffb (wasm://wasm/027c294e:wasm-function[2708]:0x579fee)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::h3410c452b43fa93d (wasm://wasm/027c294e:wasm-function[729]:0x244a11)
    at ruffle_core::display_object::movie_clip::MovieClip::place_object::hf4339ba2de2ec1f6 (wasm://wasm/027c294e:wasm-function[1233]:0x365bcf)
```

# Player Info
Allows script access: false

# Page Info
Page URL: chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/player.html?url=https%3A%2F%2Fwww.sevelina.com%2Fwp-content%2Fuploads%2F2010%2F10%2F3713.swf
SWF URL: https://www.sevelina.com/wp-content/uploads/2010/10/3713.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Platform: Win32
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-01-30
Channel: nightly
Built: 2023-01-30T00:19:04.244Z
Commit: 15c7b6520b525a67f5224855ec7e49eb0604aa07
Is extension: true

# Metadata
width: 745
height: 560
frameRate: 12
numFrames: 2
swfVersion: 10
backgroundColor: #FFFFFF
isActionScript3: true
uncompressedLength: 807389

**Comment by Lord-McSweeney** [comment]
Fixed by #11005
