### ISSUE TITLE
Error on chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/player.html

### ISSUE THREAD

**Issue by xmystvc** [ruffle-rs/ruffle#9387]
# Error Info
Error name: Error
Error message: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:594:9
Error stack:
```
Error: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:594:9
    at imports.wbg.__wbg_new_f9bb493369a83c12 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:596:21)
    at std::sync::once::Once::call_once::{{closure}}::h24436b3e76607d05 (wasm://wasm/027a13a6:wasm-function[1921]:0x48dea0)
    at std::sys_common::once::generic::Once::call::he3f17a186e209b2a (wasm://wasm/027a13a6:wasm-function[1855]:0x47daa8)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hdf8faf7e861f36fc (wasm://wasm/027a13a6:wasm-function[7118]:0x7611cb)
    at std::panicking::rust_panic_with_hook::hd000e9fb43b5781d (wasm://wasm/027a13a6:wasm-function[5050]:0x6bedb5)
    at core::panicking::panic_fmt::h9d972fcdb087ce21 (wasm://wasm/027a13a6:wasm-function[7429]:0x76fef8)
    at core::option::expect_failed::h2a3c274559c0100e (wasm://wasm/027a13a6:wasm-function[8605]:0x79a609)
    at ruffle_core::display_object::stage::Stage::root_clip::h5e15fdfcc38dec3c (wasm://wasm/027a13a6:wasm-function[5042]:0x6bdd03)
    at ruffle_core::player::Player::update_mouse_state::h1730235dc45a9918 (wasm://wasm/027a13a6:wasm-function[552]:0x163269)
    at ruffle_core::player::Player::handle_event::hef52cff41c3ffe42 (wasm://wasm/027a13a6:wasm-function[521]:0x1268db)
```

# Player Info
Allows script access: false

# Page Info
Page URL: chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/player.html?url=http%3A%2F%2Fi.notdoppler.com%2Ffiles%2Fsupercrazyguitarmaniacdeluxe4.swf
SWF URL: http://i.notdoppler.com/files/supercrazyguitarmaniacdeluxe4.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 OPR/94.0.0.0
Platform: Win32
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-02-02
Channel: nightly
Built: 2023-02-02T00:19:19.827Z
Commit: 198e40fd2ef4a36b7a3679d24dd3e567bdc63423
Is extension: true

# Metadata
width: 720
height: 450
frameRate: 30
numFrames: 2
swfVersion: 11
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 15774347

**Comment by kjarosh** [comment]
Should be fixed as of the newest version
