### ISSUE TITLE
Error on https://www.neopets.com/games/play_flash.phtml

### ISSUE THREAD

**Issue by zeusbobcat** [ruffle-rs/ruffle#9394]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create buffer object"', /home/runner/.cargo/git/checkouts/wgpu-e4487c3622394142/a154700/wgpu-hal/src/gles/device.rs:469:24
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create buffer object"', /home/runner/.cargo/git/checkouts/wgpu-e4487c3622394142/a154700/wgpu-hal/src/gles/device.rs:469:24
    at W.n.wbg.__wbg_new_f9bb493369a83c12 (chrome-extension://oakbcaafbicdddpdlhbchhpblmhefngh/dist/966.js:1:5351)
    at std::sync::once::Once::call_once::{{closure}}::h5f93984c1300ca75 (wasm://wasm/02716a0a:wasm-function[1567]:0x40425f)
    at std::sys_common::once::generic::Once::call::h8801249ea31ccf7a (wasm://wasm/02716a0a:wasm-function[1975]:0x4959cd)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::he904c54109aabe24 (wasm://wasm/02716a0a:wasm-function[7086]:0x740531)
    at std::panicking::rust_panic_with_hook::hb42d415afcc11f2f (wasm://wasm/02716a0a:wasm-function[5008]:0x6a159c)
    at core::panicking::panic_fmt::h32de9c76c9d5eb0c (wasm://wasm/02716a0a:wasm-function[7406]:0x74f295)
    at core::result::unwrap_failed::h5f2e1804ca266e0b (wasm://wasm/02716a0a:wasm-function[5916]:0x6e5ce9)
    at wgpu_hal::gles::device::<impl wgpu_hal::Device<wgpu_hal::gles::Api> for wgpu_hal::gles::Device>::create_buffer::hf475e87f44e8a9c2 (wasm://wasm/02716a0a:wasm-function[2012]:0x49e053)
    at wgpu_core::device::Device<A>::create_buffer::hbdaffc815ef2db43 (wasm://wasm/02716a0a:wasm-function[2138]:0x4bd525)
    at <T as wgpu::context::DynContext>::device_create_buffer::h166d05347403a944 (wasm://wasm/02716a0a:wasm-function[5700]:0x6d5611)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://www.neopets.com/games/play_flash.phtml?va=&game_id=801&nc_referer=&age=1&hiscore=2510&sp=0&questionSet=&r=8638579&&width=528&height=580&quality=high&inpage=1
SWF URL: https://images.neopets.com/games/gaming_system/np8_loader_v3_24.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-01-19
Channel: nightly
Built: 2023-01-19T06:30:28.821Z
Commit: f19e31d005c278685fea2de5aaa1c89675ce8714
Is extension: true

# Metadata
width: 1000
height: 1000
frameRate: 24
numFrames: 21
swfVersion: 8
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 9994

**Comment by Lord-McSweeney** [comment]
#9303 also affects the SWF.
