### ISSUE TITLE
Error on https://game156019.konggames.com/games/gamezhero/railroad-shunting-puzzle-2/frame/cba83ec3-8fe6-43aa-a0ee-c4bdf33c6d5c/

### ISSUE THREAD

**Issue by IF-chan** [ruffle-rs/ruffle#9483]
# Error Info
Error name: Error
Error message: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:596:9
Error stack:
```
Error: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:596:9
    at W.n.wbg.__wbg_new_f9bb493369a83c12 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.5f99a2874ba4b3ba3f07.js:1:5412)
    at std::sync::once::Once::call_once::{{closure}}::hd9c405109539950c (wasm://wasm/027dfc2e:wasm-function[1901]:0x48c4d8)
    at std::sys_common::once::generic::Once::call::he3f17a186e209b2a (wasm://wasm/027dfc2e:wasm-function[1833]:0x4795c5)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hb4f4a7404e793259 (wasm://wasm/027dfc2e:wasm-function[7181]:0x76cd10)
    at std::panicking::rust_panic_with_hook::hd000e9fb43b5781d (wasm://wasm/027dfc2e:wasm-function[5070]:0x6c75d8)
    at core::panicking::panic_fmt::h9d972fcdb087ce21 (wasm://wasm/027dfc2e:wasm-function[7489]:0x77b977)
    at core::option::expect_failed::h2a3c274559c0100e (wasm://wasm/027dfc2e:wasm-function[8676]:0x7a6462)
    at ruffle_core::display_object::stage::Stage::root_clip::h0b020d21dbebe6f3 (wasm://wasm/027dfc2e:wasm-function[5060]:0x6c639e)
    at ruffle_web::Ruffle::tick::hd5e77e455ba1adeb (wasm://wasm/027dfc2e:wasm-function[658]:0x20abf6)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h5c220df24882599d (wasm://wasm/027dfc2e:wasm-function[9123]:0x7b78b9)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://game156019.konggames.com/games/gamezhero/railroad-shunting-puzzle-2/frame/cba83ec3-8fe6-43aa-a0ee-c4bdf33c6d5c/?kongregate_host=www.kongregate.com
SWF URL: https://game156019.konggames.com/gamez/0015/6019/live/railroadshuntingpuzzle2_v1.6.swf?kongregate_game_version=1349357809

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-02-09
Channel: nightly
Built: 2023-02-09T00:19:16.619Z
Commit: a818dd0918ae0d8741160eed6f72e2c74f4f4556
Is extension: false

# Metadata
width: 640
height: 500
frameRate: 60
numFrames: 3
swfVersion: 11
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 6138976

**Comment by n0samu** [comment]
Fixed a long time ago by #10026
