### ISSUE TITLE
Error on https://www.arcadeprehacks.com/game/540/Swords-and-Sandals-3.html

### ISSUE THREAD

**Issue by Danlif1** [ruffle-rs/ruffle#9485]
# Error Info
Error name: Error
Error message: panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:518:5
Error stack:
```
Error: panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:518:5
    at imports.wbg.__wbg_new_f9bb493369a83c12 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:596:21)
    at std::sync::once::Once::call_once::{{closure}}::hd9c405109539950c (wasm://wasm/027dfc2e:wasm-function[1901]:0x48c4d8)
    at std::sys_common::once::generic::Once::call::he3f17a186e209b2a (wasm://wasm/027dfc2e:wasm-function[1833]:0x4795c5)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hb4f4a7404e793259 (wasm://wasm/027dfc2e:wasm-function[7181]:0x76cd10)
    at std::panicking::rust_panic_with_hook::hd000e9fb43b5781d (wasm://wasm/027dfc2e:wasm-function[5070]:0x6c75d8)
    at core::panicking::panic_fmt::h9d972fcdb087ce21 (wasm://wasm/027dfc2e:wasm-function[7489]:0x77b949)
    at alloc::raw_vec::capacity_overflow::h9b8fdd50660a9bc3 (wasm://wasm/027dfc2e:wasm-function[7284]:0x776ff3)
    at alloc::raw_vec::RawVec<T,A>::reserve_for_push::h51321d12b1134bc9 (wasm://wasm/027dfc2e:wasm-function[4835]:0x6b1641)
    at alloc::collections::vec_deque::VecDeque<T,A>::grow::h0181d9d57f8599b2 (wasm://wasm/027dfc2e:wasm-function[5554]:0x6eb894)
    at <ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::interactive::TInteractiveObject>::event_dispatch::h583467a0fdd1f4dd (wasm://wasm/027dfc2e:wasm-function[1042]:0x31c9d2)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://www.arcadeprehacks.com/game/540/Swords-and-Sandals-3.html
SWF URL: https://www.arcadeprehacks.com/swf/ss3_loader.swf

# Browser Info
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Platform: MacIntel
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-02-09
Channel: nightly
Built: 2023-02-09T00:19:16.619Z
Commit: a818dd0918ae0d8741160eed6f72e2c74f4f4556
Is extension: true

# Metadata
width: 640
height: 480
frameRate: 30
numFrames: 1
swfVersion: 9
backgroundColor: #FFFFFF
isActionScript3: false
uncompressedLength: 191

**Comment by n0samu** [comment]
The game's assets are no longer online, but I can confirm that this problem still occurs when accessing the SWF via the Wayback Machine: https://web.archive.org/web/20210131081129/http://www.arcadeprehacks.com/swf/ss3_loader.swf

**Comment by Danlif1** [comment]
If the game's assets are no longer online there is nothing that can be done
