### ISSUE TITLE
Error on https://www.minijuegos.com/helpers/game/sandbox.php

### ISSUE THREAD

**Issue by jordanbu** [ruffle-rs/ruffle#9560]
# Error Info
Error name: Error
Error message: panicked at 'Error in Queue::submit: not enough memory left', /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/c585127/wgpu/src/backend/direct.rs:316:9
Error stack:
```
Error: panicked at 'Error in Queue::submit: not enough memory left', /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/c585127/wgpu/src/backend/direct.rs:316:9
    at W.n.wbg.__wbg_new_f9bb493369a83c12 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.3a82f09aa0849e9bf576.js:1:5412)
    at std::sync::once::Once::call_once::{{closure}}::hb0a1d9ef34c32d8b (wasm://wasm/027f79f2:wasm-function[1949]:0x4a2222)
    at std::sys_common::once::generic::Once::call::h6b012ac601cc39bf (wasm://wasm/027f79f2:wasm-function[1884]:0x491281)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h7ac2449e123715e3 (wasm://wasm/027f79f2:wasm-function[7266]:0x771495)
    at std::panicking::rust_panic_with_hook::hbafe3e603d331223 (wasm://wasm/027f79f2:wasm-function[5157]:0x6cbdf5)
    at core::panicking::panic_fmt::h1d17fc068f528130 (wasm://wasm/027f79f2:wasm-function[7575]:0x7801fc)
    at <T as wgpu::context::DynContext>::queue_submit::h26c789d7c346b99e (wasm://wasm/027f79f2:wasm-function[2313]:0x51be57)
    at <ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::submit_frame::h2efd02429a3f7e17 (wasm://wasm/027f79f2:wasm-function[819]:0x2a1439)
    at ruffle_web::Ruffle::tick::hfbc64bcaed98b1c4 (wasm://wasm/027f79f2:wasm-function[665]:0x21d391)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::hd20356713a3dfdba (wasm://wasm/027f79f2:wasm-function[9212]:0x7bbab1)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.minijuegos.com/helpers/game/sandbox.php?mp_assets=https%3A%2F%2Fs2.minijuegosgratis.com%2F&mp_embed=0&mp_game_id=11007&mp_game_uid=light-bot&mp_game_url=https%3A%2F%2Fwww.minijuegos.com%2Fembed%2Flight-bot&mp_int=1&mp_locale=es_ES&mp_player_type=FLASH&mp_player_url=aHR0cHM6Ly93d3cubWluaWp1ZWdvc2dyYXRpcy5jb20vZmxhc2gxMjM0L25vX2hvdGxpbmsvbGlnaHRib3Quc3dm&mp_site_https_url=https%3A%2F%2Fwww.minijuegos.com%2F&mp_site_name=minijuegos.com&mp_site_url=https%3A%2F%2Fwww.minijuegos.com%2F&mp_timezone=America%2FLa_Paz&mp_view_type=
SWF URL: https://www.minijuegosgratis.com/flash1234/no_hotlink/lightbot.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-02-13
Channel: nightly
Built: 2023-02-13T00:19:43.223Z
Commit: b848ab68606c27c863988487e69e1754eadde193
Is extension: false

# Metadata
width: 650
height: 320
frameRate: 30
numFrames: 7
swfVersion: 8
backgroundColor: #999999
isActionScript3: false
uncompressedLength: 749901

**Comment by jordanbu** [comment]
no sirve para nada este jueguitooooooooooo
