### ISSUE TITLE
Error on https://www.twoplayergames.org/gameframe/dragon-ball-fierce-fighting-2-9

### ISSUE THREAD

**Issue by marlonfeerreira** [ruffle-rs/ruffle#9586]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', render/webgl/src/lib.rs:997:23
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', render/webgl/src/lib.rs:997:23
    at W.n.wbg.__wbg_new_f9bb493369a83c12 (https://www.twoplayergames.org/dist/ruffle/core.ruffle.fe07824c1b902e12cdf0.js:1:6899)
    at std::sync::once::Once::call_once::{{closure}}::hade171d180e8c1b3 (wasm://wasm/018460fe:wasm-function[1059]:0x2a63ca)
    at std::sync::once::Once::call_inner::h34aee843864daceb (wasm://wasm/018460fe:wasm-function[1352]:0x30d4c4)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h2b5ff8f72074c3e7 (wasm://wasm/018460fe:wasm-function[4886]:0x497380)
    at std::panicking::rust_panic_with_hook::h70a0e195f4db2a29 (wasm://wasm/018460fe:wasm-function[3635]:0x458938)
    at core::panicking::panic_fmt::h751be80779d42b53 (wasm://wasm/018460fe:wasm-function[5116]:0x49beba)
    at core::panicking::panic::h8af046397a2bf65d (wasm://wasm/018460fe:wasm-function[4938]:0x49822a)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_render::backend::RenderBackend>::register_bitmap::h82daf9b40665cc22 (wasm://wasm/018460fe:wasm-function[2046]:0x3b2e4a)
    at ruffle_core::display_object::bitmap::Bitmap::new::h1a93ebbca0834533 (wasm://wasm/018460fe:wasm-function[1500]:0x332416)
    at ruffle_core::display_object::movie_clip::MovieClipData::define_bits_lossless::h756654a73f9fec88 (wasm://wasm/018460fe:wasm-function[1849]:0x390da3)
```

# Player Info
Allows script access: false
Renderer: WebGL

# Page Info
Page URL: https://www.twoplayergames.org/gameframe/dragon-ball-fierce-fighting-2-9

# Browser Info
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-11-12
Channel: nightly
Built: 2022-11-12T00:15:57.157Z
Commit: 08270efee72ab8fe31b1448d76bcda09c8af264e
Is extension: false

# Metadata
width: 550
height: 400
frameRate: 30
numFrames: 8
swfVersion: 15
backgroundColor: #999999
isActionScript3: false
uncompressedLength: 23507924

**Comment by kjarosh** [comment]
Should be fixed as of the newest version
