### ISSUE TITLE
Error on chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/player.html

### ISSUE THREAD

**Issue by IonDischarge** [ruffle-rs/ruffle#9629]
# Error Info
Error name: Error
Error message: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:611:9
Error stack:
```
Error: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:611:9
    at imports.wbg.__wbg_new_f9bb493369a83c12 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:596:21)
    at std::sync::once::Once::call_once::{{closure}}::hfcec2cf17a6c3683 (wasm://wasm/0281e88e:wasm-function[1950]:0x4ad32f)
    at std::sys_common::once::generic::Once::call::h6b012ac601cc39bf (wasm://wasm/0281e88e:wasm-function[1884]:0x49c02a)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h315d2ce986e29f2a (wasm://wasm/0281e88e:wasm-function[7287]:0x779b56)
    at std::panicking::rust_panic_with_hook::hbafe3e603d331223 (wasm://wasm/0281e88e:wasm-function[5176]:0x6d4224)
    at core::panicking::panic_fmt::h1d17fc068f528130 (wasm://wasm/0281e88e:wasm-function[7596]:0x7888ca)
    at core::option::expect_failed::hde6894209e142acf (wasm://wasm/0281e88e:wasm-function[8785]:0x7b2e20)
    at ruffle_core::display_object::stage::Stage::root_clip::hebdca7d6c5e3d7d9 (wasm://wasm/0281e88e:wasm-function[5166]:0x6d2fea)
    at ruffle_web::Ruffle::tick::hcd5ea5c8778cdd4b (wasm://wasm/0281e88e:wasm-function[664]:0x227696)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::hdd4d66b11b56f7fa (wasm://wasm/0281e88e:wasm-function[9232]:0x7c41ac)
```

# Player Info
Allows script access: false

# Page Info
Page URL: chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/player.html?url=https%3A%2F%2Fia800104.us.archive.org%2F1%2Fitems%2Farmorgames%2Fboss-slayer-133243467.swf
SWF URL: https://ia800104.us.archive.org/1/items/armorgames/boss-slayer-133243467.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-02-18
Channel: nightly
Built: 2023-02-18T00:22:15.889Z
Commit: f7b0c021a9c5986047cae8273d63fe4db8eab22a
Is extension: true

# Metadata
width: 640
height: 480
frameRate: 60
numFrames: 2
swfVersion: 12
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 2729418

**Comment by Lord-McSweeney** [comment]
After #10026, this needs `GlowFilter` to display correctly, and some text is overflowing, but otherwise the gameplay works correctly.
