### ISSUE TITLE
Error on https://www.gameszap.com/game/11139/pac-adventure-draculas-castle.html

### ISSUE THREAD

**Issue by SimulationWithDaniel** [ruffle-rs/ruffle#9653]
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', core/src/bitmap/bitmap_data.rs:259:45
Error stack:
```
Error: panicked at 'already borrowed: BorrowMutError', core/src/bitmap/bitmap_data.rs:259:45
    at W.n.wbg.__wbg_new_f9bb493369a83c12 (https://www.gameszap.com/js/frontend/ruffle/core.ruffle.d8443eb0440769c91080.js:1:5387)
    at std::sync::once::Once::call_once::{{closure}}::hfcec2cf17a6c3683 (wasm://wasm/0280091a:wasm-function[1948]:0x4a2797)
    at std::sys_common::once::generic::Once::call::h6b012ac601cc39bf (wasm://wasm/0280091a:wasm-function[1883]:0x4917ec)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h315d2ce986e29f2a (wasm://wasm/0280091a:wasm-function[7271]:0x77300c)
    at std::panicking::rust_panic_with_hook::hbafe3e603d331223 (wasm://wasm/0280091a:wasm-function[5161]:0x6cd861)
    at core::panicking::panic_fmt::h1d17fc068f528130 (wasm://wasm/0280091a:wasm-function[7580]:0x781d80)
    at core::result::unwrap_failed::ha2d692f1494e5dde (wasm://wasm/0280091a:wasm-function[5885]:0x706bbb)
    at ruffle_core::bitmap::bitmap_data::wrapper::BitmapDataWrapper::sync::h41d324d9a8ecb595 (wasm://wasm/0280091a:wasm-function[4213]:0x679b54)
    at ruffle_core::avm1::object::bitmap_data::BitmapDataObject::bitmap_data::hc3899de5266ecb27 (wasm://wasm/0280091a:wasm-function[6574]:0x731e6a)
    at ruffle_core::avm1::globals::bitmap_data::copy_pixels::hc056c5779addbb91 (wasm://wasm/0280091a:wasm-function[678]:0x2294c3)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: https://www.gameszap.com/files/swf/pac-adventure-draculas-castle-1537793906.swf
Param movie: https://www.gameszap.com/files/swf/pac-adventure-draculas-castle-1537793906.swf
Param SCALE: exactfit
Param BGCOLOR: #FFF
Param AllowScriptAccess: always
Param quality: high
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined

# Page Info
Page URL: https://www.gameszap.com/game/11139/pac-adventure-draculas-castle.html
SWF URL: https://www.gameszap.com/files/swf/pac-adventure-draculas-castle-1537793906.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-02-15
Channel: nightly
Built: 2023-02-15T00:19:44.491Z
Commit: 1e12f2d49b30396054fbf54b9c3742c52aa9bd7f
Is extension: false

# Metadata
width: 585
height: 585
frameRate: 20
numFrames: 2
swfVersion: 8
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 3194665

**Comment by Lord-McSweeney** [comment]
See also #9578.

**Comment by n0samu** [comment]
This is a regression caused by #9184
