### ISSUE TITLE
Error on http://www.andkon.com/arcade/puzzle/candyconveyor/

### ISSUE THREAD

**Issue by Treborcd** [ruffle-rs/ruffle#9654]
# Error Info
Error name: Error
Error message: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:611:9
Error stack:
```
Error: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:611:9
    at imports.wbg.__wbg_new_f9bb493369a83c12 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:596:21)
    at std::sync::once::Once::call_once::{{closure}}::hfcec2cf17a6c3683 (wasm://wasm/0281efe2:wasm-function[1952]:0x4ae0c8)
    at std::sys_common::once::generic::Once::call::h6b012ac601cc39bf (wasm://wasm/0281efe2:wasm-function[1887]:0x49d0e1)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h315d2ce986e29f2a (wasm://wasm/0281efe2:wasm-function[7288]:0x779c54)
    at std::panicking::rust_panic_with_hook::hbafe3e603d331223 (wasm://wasm/0281efe2:wasm-function[5177]:0x6d4322)
    at core::panicking::panic_fmt::h1d17fc068f528130 (wasm://wasm/0281efe2:wasm-function[7597]:0x7889c8)
    at core::option::expect_failed::hde6894209e142acf (wasm://wasm/0281efe2:wasm-function[8786]:0x7b2f1e)
    at ruffle_core::display_object::stage::Stage::root_clip::hebdca7d6c5e3d7d9 (wasm://wasm/0281efe2:wasm-function[5167]:0x6d30e8)
    at ruffle_web::Ruffle::tick::hcd5ea5c8778cdd4b (wasm://wasm/0281efe2:wasm-function[664]:0x227693)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::hdd4d66b11b56f7fa (wasm://wasm/0281efe2:wasm-function[9233]:0x7c42aa)
```

# Player Info
Allows script access: true

# Page Info
Page URL: http://www.andkon.com/arcade/puzzle/candyconveyor/
SWF URL: http://www.andkon.com/arcade/puzzle/candyconveyor/candyconveyor.swf

# Browser Info
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Platform: MacIntel
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-02-20
Channel: nightly
Built: 2023-02-20T00:19:50.499Z
Commit: f7a12698b9a5dbfc39529ab5e4abd75880579b99
Is extension: true

# Metadata
width: 640
height: 480
frameRate: 100
numFrames: 3
swfVersion: 9
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 1252919

**Comment by n0samu** [comment]
Fixed by #10026
