### ISSUE TITLE
Error on https://www.y8.com/games/feeding_frenzy_tuna

### ISSUE THREAD

**Issue by sarah-noor-12232** [ruffle-rs/ruffle#9666]
# Error Info
Error name: Error
Error message: panicked at 'No script object for display object', core/src/avm1/activation.rs:372:18
Error stack:
```
Error: panicked at 'No script object for display object', core/src/avm1/activation.rs:372:18
    at imports.wbg.__wbg_new_f9bb493369a83c12 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:596:21)
    at std::sync::once::Once::call_once::{{closure}}::hfcec2cf17a6c3683 (wasm://wasm/0281efe2:wasm-function[1952]:0x4ae0c8)
    at std::sys_common::once::generic::Once::call::h6b012ac601cc39bf (wasm://wasm/0281efe2:wasm-function[1887]:0x49d0e1)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h315d2ce986e29f2a (wasm://wasm/0281efe2:wasm-function[7288]:0x779c54)
    at std::panicking::rust_panic_with_hook::hbafe3e603d331223 (wasm://wasm/0281efe2:wasm-function[5177]:0x6d4322)
    at core::panicking::panic_fmt::h1d17fc068f528130 (wasm://wasm/0281efe2:wasm-function[7597]:0x78899a)
    at ruffle_core::display_object::edit_text::EditText::try_bind_text_field_variable::h018b8055f2ca652f (wasm://wasm/0281efe2:wasm-function[3586]:0x62d202)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::h619429c22793f41b (wasm://wasm/0281efe2:wasm-function[2744]:0x582f76)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::h12667dcd5bc2c65d (wasm://wasm/0281efe2:wasm-function[721]:0x25d90c)
    at ruffle_core::display_object::movie_clip::MovieClip::place_object::hb3f7be01839936e4 (wasm://wasm/0281efe2:wasm-function[1463]:0x3e262f)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.y8.com/games/feeding_frenzy_tuna
SWF URL: https://img-hws.y8.com/cloud/y8-flash-game/contents/item_versions/flash_games/93743/original/tuna_growing.swf?1522719061

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 OPR/94.0.0.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-02-20
Channel: nightly
Built: 2023-02-20T00:19:50.499Z
Commit: f7a12698b9a5dbfc39529ab5e4abd75880579b99
Is extension: true

# Metadata
width: 640
height: 480
frameRate: 30
numFrames: 2
swfVersion: 9
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 1875930

**Comment by n0samu** [comment]
Note that the game shows a blank white screen for about 20 seconds before it loads, even in Flash Player.
