### ISSUE TITLE
Error on https://alienjogos.com.br/ben10/ultimate-alien-warrior/

### ISSUE THREAD

**Issue by Pedroca2005BR** [ruffle-rs/ruffle#9707]
# Error Info
Error name: Error
Error message: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:596:9
Error stack:
```
Error: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:596:9
    at W.n.wbg.__wbg_new_f9bb493369a83c12 (https://alienjogos.com.br/ruffle/core.ruffle.8ca5d4a55b794e206353.js:1:5412)
    at std::sync::once::Once::call_once::{{closure}}::hd9c405109539950c (wasm://wasm/027d6046:wasm-function[1929]:0x495d68)
    at std::sys_common::once::generic::Once::call::he3f17a186e209b2a (wasm://wasm/027d6046:wasm-function[1860]:0x482b2c)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hb4f4a7404e793259 (wasm://wasm/027d6046:wasm-function[7151]:0x76ab34)
    at std::panicking::rust_panic_with_hook::hd000e9fb43b5781d (wasm://wasm/027d6046:wasm-function[5041]:0x6c4b21)
    at core::panicking::panic_fmt::h9d972fcdb087ce21 (wasm://wasm/027d6046:wasm-function[7459]:0x77979b)
    at core::option::expect_failed::h2a3c274559c0100e (wasm://wasm/027d6046:wasm-function[8646]:0x7a425a)
    at ruffle_core::display_object::stage::Stage::root_clip::h0b020d21dbebe6f3 (wasm://wasm/027d6046:wasm-function[5031]:0x6c38e7)
    at ruffle_web::Ruffle::tick::hd5e77e455ba1adeb (wasm://wasm/027d6046:wasm-function[660]:0x211cce)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h5c220df24882599d (wasm://wasm/027d6046:wasm-function[9093]:0x7b56b1)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://alienjogos.com.br/ben10/ultimate-alien-warrior/
SWF URL: https://alienjogos.com.br/ben10/ultimate-alien-warrior/ultimate-alien-warrior.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-02-08
Channel: nightly
Built: 2023-02-08T00:19:50.635Z
Commit: 83f88a6f3e6757993d09b6bc97303739f86d4c30
Is extension: false

# Metadata
width: 960
height: 540
frameRate: 60
numFrames: 2
swfVersion: 13
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 9214174

**Comment by Lord-McSweeney** [comment]
After #10026 this has performance issues while loading levels and also needs `TextField.mouseWheelEnabled`, but plays correctly.
