### ISSUE TITLE
Error on chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/player.html

### ISSUE THREAD

**Issue by Lord-McSweeney** [ruffle-rs/ruffle#9723]
Error thrown before panic:
`Error dispatching event EventObject(EventObject { type: "addedToStage", class: flash.events::Event, ptr: 0x84e1d8 }) to handler FunctionObject(FunctionObject { ptr: 0x9698c0 }) : RustError("Cannot coerce Object(ScriptObject(ScriptObject { name: com.google.analytics::GATracker, ptr: 0x3c1aa68 })) to an flash.events::IEventDispatcher")`

# Error Info
Error name: Error
Error message: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:627:9
Error stack:
```
Error: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:627:9
    at imports.wbg.__wbg_new_f9bb493369a83c12 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:596:21)
    at std::sync::once::Once::call_once::{{closure}}::hfcec2cf17a6c3683 (wasm://wasm/0283308a:wasm-function[1957]:0x4af4c6)
    at std::sys_common::once::generic::Once::call::h6b012ac601cc39bf (wasm://wasm/0283308a:wasm-function[1894]:0x49f690)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h315d2ce986e29f2a (wasm://wasm/0283308a:wasm-function[7286]:0x77a6d9)
    at std::panicking::rust_panic_with_hook::hbafe3e603d331223 (wasm://wasm/0283308a:wasm-function[5176]:0x6d48cf)
    at core::panicking::panic_fmt::h1d17fc068f528130 (wasm://wasm/0283308a:wasm-function[7599]:0x789569)
    at core::option::expect_failed::hde6894209e142acf (wasm://wasm/0283308a:wasm-function[8792]:0x7b3dc3)
    at ruffle_core::player::Player::update_mouse_state::h7e6b070caa72db95 (wasm://wasm/0283308a:wasm-function[550]:0x171d43)
    at ruffle_core::player::Player::handle_event::he3f1fa3e9ff0083d (wasm://wasm/0283308a:wasm-function[515]:0xfddf8)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h9f30dc1e122c4749 (wasm://wasm/0283308a:wasm-function[765]:0x280cf2)
```

# Player Info
Allows script access: false

# Page Info
Page URL: chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/player.html?url=https%3A%2F%2Fwww.getsupernova.com%2Fgames%2Fcolormove.swf
SWF URL: https://www.getsupernova.com/games/colormove.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-02-25
Channel: nightly
Built: 2023-02-25T00:19:43.168Z
Commit: 79cc42c739084c81f473d729d23b633c9f629dea
Is extension: true

# Metadata
width: 792
height: 576
frameRate: 60
numFrames: 2
swfVersion: 16
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 6992482

**Comment by Lord-McSweeney** [comment]
This seems to be working fine now.
