### ISSUE TITLE
Error on https://ruffle.rs/demo/

### ISSUE THREAD

**Issue by CrazyFlasher** [ruffle-rs/ruffle#9812]
# Error Info
Error name: Error
Error message: panicked at 'No script object for display object', core/src/avm1/activation.rs:374:18
Error stack:
```
Error: panicked at 'No script object for display object', core/src/avm1/activation.rs:374:18
    at W.n.wbg.__wbg_new_15d3966e9981a196 (https://ruffle.rs/demo/339.index.js:1:46501)
    at std::sync::once::Once::call_once::{{closure}}::h444e36a1b355b0d5 (wasm://wasm/028c1172:wasm-function[2011]:0x4d3f1f)
    at std::sys_common::once::generic::Once::call::h6b012ac601cc39bf (wasm://wasm/028c1172:wasm-function[1943]:0x4c277b)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hdb7e1770f2a56782 (wasm://wasm/028c1172:wasm-function[7376]:0x799109)
    at std::panicking::rust_panic_with_hook::hbafe3e603d331223 (wasm://wasm/028c1172:wasm-function[5228]:0x6f1c43)
    at core::panicking::panic_fmt::h1d17fc068f528130 (wasm://wasm/028c1172:wasm-function[7695]:0x7a80e4)
    at ruffle_core::display_object::edit_text::EditText::try_bind_text_field_variable::hb770dbabbcc37073 (wasm://wasm/028c1172:wasm-function[3617]:0x646f7b)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::hb76bc866e8854e1a (wasm://wasm/028c1172:wasm-function[2666]:0x58a4c9)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::ha635cb2f3c41d7d8 (wasm://wasm/028c1172:wasm-function[727]:0x26c857)
    at ruffle_core::display_object::movie_clip::MovieClip::place_object::h1a26bc6b547282a2 (wasm://wasm/028c1172:wasm-function[1478]:0x3fd609)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://ruffle.rs/demo/

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-03-02
Channel: nightly
Built: 2023-03-02T00:25:08.532Z
Commit: fcaa17308cfafe88ed2850a14be8e52293082633
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 45
numFrames: 2
swfVersion: 10
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 569011

**Comment by Lord-McSweeney** [comment]
Please upload the SWF file or provide a link to the file.

**Comment by CrazyFlasher** [comment]
[killAnsip.zip](https://github.com/ruffle-rs/ruffle/files/10879093/killAnsip.zip)

**Comment by Lord-McSweeney** [comment]
Seems like this has been working for a while now
