### ISSUE TITLE
Error on http://flashghetto.com/games/super_crazy_guitar_maniac_deluxe_4

### ISSUE THREAD

**Issue by Anthony-Riello** [ruffle-rs/ruffle#9823]
# Error Info
Error name: Error
Error message: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:594:9
Error stack:
```
Error: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:594:9
    at W.n.wbg.__wbg_new_f9bb493369a83c12 (http://fgn.cdn.serverable.com/common/flashes/js/ruffle230112/core.ruffle.83566026b042a7a8a30e.js:1:5285)
    at std::sync::once::Once::call_once::{{closure}}::h414d1d35ae912360 (wasm://wasm/019ad0b6:wasm-function[1107]:0x2bb74d)
    at std::sys_common::once::generic::Once::call::h8801249ea31ccf7a (wasm://wasm/019ad0b6:wasm-function[1425]:0x32e4fe)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h400100c7887fb97b (wasm://wasm/019ad0b6:wasm-function[4917]:0x4cb1b3)
    at std::panicking::rust_panic_with_hook::hb42d415afcc11f2f (wasm://wasm/019ad0b6:wasm-function[3604]:0x4896b3)
    at core::panicking::panic_fmt::h32de9c76c9d5eb0c (wasm://wasm/019ad0b6:wasm-function[5125]:0x4d0c1f)
    at core::option::expect_failed::hb1beef3e49ebedf1 (wasm://wasm/019ad0b6:wasm-function[5818]:0x4f2f9e)
    at ruffle_core::display_object::stage::Stage::root_clip::h9967046689b231aa (wasm://wasm/019ad0b6:wasm-function[3612]:0x489d73)
    at ruffle_core::player::Player::update_mouse_state::h58a7feabcce10bee (wasm://wasm/019ad0b6:wasm-function[344]:0xaccc9)
    at ruffle_core::player::Player::handle_event::hc4e33c8dd8ba8538 (wasm://wasm/019ad0b6:wasm-function[323]:0x874d6)
```

# Player Info
Allows script access: false
null

# Page Info
Page URL: http://flashghetto.com/games/super_crazy_guitar_maniac_deluxe_4
SWF URL: http://fgn.cdn.serverable.com/common/flashes/ff/s/super_crazy_guitar_maniac_deluxe_4.swf?d=20120216203039

# Browser Info
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
Platform: MacIntel
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-01-12
Channel: nightly
Built: 2023-01-12T00:15:13.700Z
Commit: 6c71f5b2a69895a1ca04a12c60afade3b8033b33
Is extension: false

# Metadata
width: 720
height: 450
frameRate: 30
numFrames: 2
swfVersion: 11
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 15774347

**Comment by Lord-McSweeney** [comment]
Needs GetDescendants after #10026.

**Comment by Lord-McSweeney** [comment]
Seems to work fine now.
