### ISSUE TITLE
Error with Papa's Pastaria

### ISSUE THREAD

**Issue by amruthn1** [ruffle-rs/ruffle#9852]
# Error Info
Error name: Error
Error message: panicked at 'already mutably borrowed: BorrowError', core/src/avm2/globals/flash/display/bitmap_data.rs:292:46
Error stack:
```
Error: panicked at 'already mutably borrowed: BorrowError', core/src/avm2/globals/flash/display/bitmap_data.rs:292:46
    at W.n.wbg.__wbg_new_15d3966e9981a196 (https://ruffle.rs/demo/339.index.js:1:46501)
    at std::sync::once::Once::call_once::{{closure}}::hc59ac3595ac97c01 (wasm://wasm/02941d36:wasm-function[2041]:0x4e9ee7)
    at std::sys_common::once::generic::Once::call::h6b012ac601cc39bf (wasm://wasm/02941d36:wasm-function[1976]:0x4dbfd4)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hf8c3619c8c8cf2e2 (wasm://wasm/02941d36:wasm-function[7460]:0x7b2cdc)
    at std::panicking::rust_panic_with_hook::hbafe3e603d331223 (wasm://wasm/02941d36:wasm-function[5253]:0x70ae8f)
    at core::panicking::panic_fmt::h1d17fc068f528130 (wasm://wasm/02941d36:wasm-function[7789]:0x7c1f7e)
    at core::result::unwrap_failed::ha2d692f1494e5dde (wasm://wasm/02941d36:wasm-function[6004]:0x743795)
    at gc_arena::gc_cell::GcCell<T>::read::h0180865fda2cd124 (wasm://wasm/02941d36:wasm-function[6832]:0x785a3a)
    at ruffle_core::avm2::globals::flash::display::bitmap_data::copy_pixels::h8f7d594739c27b57 (wasm://wasm/02941d36:wasm-function[634]:0x20f9a2)
    at ruffle_core::avm2::function::Executable::exec::hb196da6f82d0ed6f (wasm://wasm/02941d36:wasm-function[844]:0x2ddb6b)
```
AVM2 stack:
```
    at flash.display::BitmapData/flash::display::BitmapData::copyPixels()
    at pastaGame.models::PastaOrder/drawIntoSlices()
    at pastaGame.models::PastaTopping/screenUpdate()
    at pastaGame.models::PastaOrder/updateBuildPasta()
    at pastaGame.models::FoodOrder/updateBuildPasta()
    at pastaGame.screens::BuildScreen/updateScreen()
    at pastaGame.events::GameControls/gameCycle()
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://ruffle.rs/demo/

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-03-04
Channel: nightly
Built: 2023-03-04T00:19:41.505Z
Commit: 1ef539e31bc58569d10abda9a70ab9c0d5c03349
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 30
numFrames: 2
swfVersion: 10
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 13955205

**Comment by Lord-McSweeney** [comment]
See #9578
