### ISSUE TITLE
Error on https://unblockedgamesroom.com/chaos-faction-2/

### ISSUE THREAD

**Issue by Toxiccrowyt** [ruffle-rs/ruffle#9880]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:632:28
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:632:28
    at W.n.wbg.__wbg_new_15d3966e9981a196 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.318c287647bc6ddfd4a5.js:1:46442)
    at std::sync::once::Once::call_once::{{closure}}::he918ee3086b261a7 (wasm://wasm/0294aade:wasm-function[2039]:0x4f07fb)
    at std::sys_common::once::generic::Once::call::h6b012ac601cc39bf (wasm://wasm/0294aade:wasm-function[1972]:0x4e12ad)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h2612a5ee62d4acb8 (wasm://wasm/0294aade:wasm-function[7469]:0x7b46b8)
    at std::panicking::rust_panic_with_hook::hbafe3e603d331223 (wasm://wasm/0294aade:wasm-function[5256]:0x70b66b)
    at core::panicking::panic_fmt::h1d17fc068f528130 (wasm://wasm/0294aade:wasm-function[7798]:0x7c392c)
    at core::panicking::panic::h27b5eefa3e4ff738 (wasm://wasm/0294aade:wasm-function[7190]:0x78f727)
    at ruffle_core::display_object::container::ChildContainer::replace_at_depth::hc61ea058b651e18d (wasm://wasm/0294aade:wasm-function[1325]:0x3ce767)
    at ruffle_core::display_object::container::TDisplayObjectContainer::replace_at_depth::heb3ed44fd8f28065 (wasm://wasm/0294aade:wasm-function[4896]:0x6ed066)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::h3c50fc93781043cb (wasm://wasm/0294aade:wasm-function[705]:0x26500c)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: /wp-content/uploads/assets/chaos-faction-2/chaos-faction-2.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined

# Page Info
Page URL: https://unblockedgamesroom.com/chaos-faction-2/
SWF URL: https://unblockedgamesroom.com/wp-content/uploads/assets/chaos-faction-2/chaos-faction-2.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-03-06
Channel: nightly
Built: 2023-03-06T00:20:07.108Z
Commit: 806c0fe052cd26a88b6a64353a15155a5f27b1e8
Is extension: false

# Metadata
width: 800
height: 600
frameRate: 38
numFrames: 1266
swfVersion: 8
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 14265928

**Comment by Sonikkustar** [comment]
Not sure what triggered this issue, but I was able to boot up the game just fine:
![image](https://github.com/ruffle-rs/ruffle/assets/22226938/edb0b173-76dd-4d5f-88f3-abb735864b57)

Seems like the site displays this at a resolution this game wasn't made for though so the sides don't display properly.

Site now uses **nightly-2023-11-13**.

**Comment by kjarosh** [comment]
Fixed by https://github.com/ruffle-rs/ruffle/pull/10362
