### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by Kwing95** [ruffle-rs/ruffle#9909]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:632:28
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:632:28
    at W.n.wbg.__wbg_new_15d3966e9981a196 (https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.318c287647bc6ddfd4a5.js:1:46442)
    at std::sync::once::Once::call_once::{{closure}}::he918ee3086b261a7 (wasm://wasm/0294aade:wasm-function[2039]:0x4f07fb)
    at std::sys_common::once::generic::Once::call::h6b012ac601cc39bf (wasm://wasm/0294aade:wasm-function[1972]:0x4e12ad)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h2612a5ee62d4acb8 (wasm://wasm/0294aade:wasm-function[7469]:0x7b46b8)
    at std::panicking::rust_panic_with_hook::hbafe3e603d331223 (wasm://wasm/0294aade:wasm-function[5256]:0x70b66b)
    at core::panicking::panic_fmt::h1d17fc068f528130 (wasm://wasm/0294aade:wasm-function[7798]:0x7c392c)
    at core::panicking::panic::h27b5eefa3e4ff738 (wasm://wasm/0294aade:wasm-function[7190]:0x78f727)
    at ruffle_core::display_object::container::ChildContainer::replace_at_depth::hc61ea058b651e18d (wasm://wasm/0294aade:wasm-function[1325]:0x3ce767)
    at ruffle_core::display_object::container::TDisplayObjectContainer::replace_at_depth::heb3ed44fd8f28065 (wasm://wasm/0294aade:wasm-function[4896]:0x6ed066)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::h3c50fc93781043cb (wasm://wasm/0294aade:wasm-function[705]:0x26500c)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.67&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1678114734%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2Ftmp%2F4564000%2F4564154%2Ffile%2F76a55e291678223494.swf%3F1678223494%22%2C%22vars%22%3A%7B%22ngio_session_id%22%3A%2258823615.78516cd49a7046b7f9819224ce968fa5bf3b31e8cde1eb%22%2C%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%226407a95025431%22%2C%22NewgroundsAPI_SessionID%22%3A%22o6Go0golsNZh5cITpAaM4f185f72fc3c57172e660d2ce1d173cd5d04121aO8sW%22%2C%22NewgroundsAPI_UserName%22%3A%22Kwing%22%2C%22NewgroundsAPI_UserID%22%3A2051581%2C%22ng_username%22%3A%22Kwing%22%7D%2C%22width%22%3A1200%2C%22height%22%3A675%2C%22icon%22%3A%22https%3A%2F%2Fimg.ngfiles.com%2Fdefaults%2Ficon-portal-xl.gif%3Ff1601395813%22%2C%22warnOnUnsupportedContent%22%3Afalse%7D
SWF URL: https://uploads.ungrounded.net/tmp/4564000/4564154/file/76a55e291678223494.swf?1678223494

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-03-06
Channel: nightly
Built: 2023-03-06T00:20:07.108Z
Commit: 806c0fe052cd26a88b6a64353a15155a5f27b1e8
Is extension: false

# Metadata
width: 1200
height: 675
frameRate: 30
numFrames: 4
swfVersion: 15
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 3481155

**Comment by n0samu** [comment]
Hi, it looks like this error is coming from a private/temporary Newgrounds project. Can you attach the necessary files to reproduce the error?

**Comment by kjarosh** [comment]
Fixed by https://github.com/ruffle-rs/ruffle/pull/10362
