### ISSUE TITLE
Error on http://ducklife12345.com/games/duck-life-8-hacked/

### ISSUE THREAD

**Issue by jytyun** [ruffle-rs/ruffle#9934]
# Error Info
Error name: Error
Error message: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:625:9
Error stack:
```
Error: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:625:9
    at W.n.wbg.__wbg_new_15d3966e9981a196 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.d47c1fc8f81804494577.js:1:46443)
    at std::sync::once::Once::call_once::{{closure}}::h232d3d481290a400 (wasm://wasm/0294c58a:wasm-function[2042]:0x4f326d)
    at std::sys_common::once::generic::Once::call::h6b012ac601cc39bf (wasm://wasm/0294c58a:wasm-function[1977]:0x4e44a8)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h68563d86acb3fcd8 (wasm://wasm/0294c58a:wasm-function[7469]:0x7b4e11)
    at std::panicking::rust_panic_with_hook::hbafe3e603d331223 (wasm://wasm/0294c58a:wasm-function[5272]:0x70d90d)
    at core::panicking::panic_fmt::h1d17fc068f528130 (wasm://wasm/0294c58a:wasm-function[7799]:0x7c4020)
    at core::option::expect_failed::hde6894209e142acf (wasm://wasm/0294c58a:wasm-function[9017]:0x7ef7bb)
    at ruffle_core::display_object::stage::Stage::root_clip::hb4bcd66219241510 (wasm://wasm/0294c58a:wasm-function[5266]:0x70ca4b)
    at ruffle_web::Ruffle::tick::h0965383f85ea7d5c (wasm://wasm/0294c58a:wasm-function[673]:0x240a48)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h984cd2a9ee1e1aa7 (wasm://wasm/0294c58a:wasm-function[9493]:0x801986)
```

# Player Info
Allows script access: true

# Page Info
Page URL: http://ducklife12345.com/games/duck-life-8-hacked/
SWF URL: http://ducklife12345.com/wp-content/uploads/a851f3da.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-03-09
Channel: nightly
Built: 2023-03-09T00:20:13.637Z
Commit: fc223e959b1529b94a4276e2b08238f9e61197b1
Is extension: false

# Metadata
width: 720
height: 593
frameRate: 60
numFrames: 5
swfVersion: 22
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 123942

**Comment by n0samu** [comment]
Fixed by #10026. But the SWF seems to have no content and does not do anything even in Flash Player.
