### ISSUE TITLE
Error on https://gamejolt.net/

### ISSUE THREAD

**Issue by Iaon0** [ruffle-rs/ruffle#9935]
# Error Info
Error name: Error
Error message: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:625:9
Error stack:
```
Error: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:625:9
    at imports.wbg.__wbg_new_15d3966e9981a196 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:2154:21)
    at std::sync::once::Once::call_once::{{closure}}::h232d3d481290a400 (wasm://wasm/0294a55a:wasm-function[2037]:0x4f1ae7)
    at std::sys_common::once::generic::Once::call::h6b012ac601cc39bf (wasm://wasm/0294a55a:wasm-function[1972]:0x4e2c41)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h68563d86acb3fcd8 (wasm://wasm/0294a55a:wasm-function[7469]:0x7b4d0f)
    at std::panicking::rust_panic_with_hook::hbafe3e603d331223 (wasm://wasm/0294a55a:wasm-function[5272]:0x70ca1c)
    at core::panicking::panic_fmt::h1d17fc068f528130 (wasm://wasm/0294a55a:wasm-function[7800]:0x7c4025)
    at core::option::expect_failed::hde6894209e142acf (wasm://wasm/0294a55a:wasm-function[9014]:0x7ef6d5)
    at ruffle_core::display_object::stage::Stage::root_clip::hb4bcd66219241510 (wasm://wasm/0294a55a:wasm-function[5266]:0x70bb5a)
    at ruffle_web::Ruffle::tick::h0965383f85ea7d5c (wasm://wasm/0294a55a:wasm-function[672]:0x23efbd)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h984cd2a9ee1e1aa7 (wasm://wasm/0294a55a:wasm-function[9482]:0x801848)
```

# Player Info
Allows script access: false
Player type: Object
SWF URL: https://cdn-files.gamejolt.net/EVMrT1k4nMDyUJecIYPbpQ==,1678414453/data/games/0/2/12752/files/5419be8e2eb1a/CantEscape.swf?gjapi_username=idk_an_original_name&gjapi_token=Bendyeye
Param allowFullScreen: true
Param allowFullScreenInteractive: true
Param wmode: direct
Param flashvars: %3Fgjapi_username%3Didk_an_original_name%26gjapi_token%3DBendyeye
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined

# Page Info
Page URL: https://gamejolt.net/?token=NGwf5gpjoYeiTKRnB4BLXgAwUJ2a3D
SWF URL: https://cdn-files.gamejolt.net/EVMrT1k4nMDyUJecIYPbpQ==,1678414453/data/games/0/2/12752/files/5419be8e2eb1a/CantEscape.swf?gjapi_username=idk_an_original_name&gjapi_token=Bendyeye

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.5414.120 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-03-08
Channel: nightly
Built: 2023-03-08T00:26:27.990Z
Commit: 93834b63de27a43e37dd84ba8f3750aaa8ffc1ab
Is extension: true

# Metadata
width: 640
height: 480
frameRate: 24
numFrames: 2
swfVersion: 18
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 6952015

**Comment by n0samu** [comment]
Fixed by #10026
