### ISSUE TITLE
Error on https://f.kbhgames.com/RS/game.php

### ISSUE THREAD

**Issue by Robert9157** [ruffle-rs/ruffle#9945]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm2/globals/flash/geom/transform.rs:15:8
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm2/globals/flash/geom/transform.rs:15:8
    at W.n.wbg.__wbg_new_15d3966e9981a196 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.d47c1fc8f81804494577.js:1:46443)
    at std::sync::once::Once::call_once::{{closure}}::h232d3d481290a400 (wasm://wasm/0294c58a:wasm-function[2042]:0x4f326d)
    at std::sys_common::once::generic::Once::call::h6b012ac601cc39bf (wasm://wasm/0294c58a:wasm-function[1977]:0x4e44a8)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h68563d86acb3fcd8 (wasm://wasm/0294c58a:wasm-function[7469]:0x7b4e11)
    at std::panicking::rust_panic_with_hook::hbafe3e603d331223 (wasm://wasm/0294c58a:wasm-function[5272]:0x70d90d)
    at core::panicking::panic_fmt::h1d17fc068f528130 (wasm://wasm/0294c58a:wasm-function[7799]:0x7c3ff2)
    at core::panicking::panic::h27b5eefa3e4ff738 (wasm://wasm/0294c58a:wasm-function[7191]:0x790a58)
    at ruffle_core::avm2::globals::flash::geom::transform::get_display_object::h41ca03602897bf5d (wasm://wasm/0294c58a:wasm-function[3474]:0x64fa40)
    at ruffle_core::avm2::globals::flash::geom::transform::get_color_transform::h34f4fe9593309664 (wasm://wasm/0294c58a:wasm-function[2618]:0x59a3e8)
    at ruffle_core::avm2::function::Executable::exec::h33e27d3ff89e605b (wasm://wasm/0294c58a:wasm-function[860]:0x2e4994)
```
AVM2 stack:
```
    at flash.geom::Transform/flash::geom::Transform::colorTransform()
    at game.info::Alerter()
    at game::Game()
    at prep::PrepCreateAppPhases/performStep()
    at prep::PrepAbstract/perform()
    at prep::Preper/step()
    at prep::Preper/prepare()
    at App/onBootFrame()
    at App$/OnBootFrame()
    at Doc/onBootFrame()
    at Doc$/OnBootFrame()
    at Doc/frame4()
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://f.kbhgames.com/RS/game.php?r=//f.kbhgames.com/2018/swf/ricobrix.swf&w=550&h=550
SWF URL: https://f.kbhgames.com/2018/swf/ricobrix.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-03-09
Channel: nightly
Built: 2023-03-09T00:20:13.637Z
Commit: fc223e959b1529b94a4276e2b08238f9e61197b1
Is extension: false

# Metadata
width: 550
height: 550
frameRate: 30
numFrames: 8
swfVersion: 10
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 3370646

**Comment by kjarosh** [comment]
The code related to the panic changed a lot, so I would expect it's fixed.

The issue with the game currently is that clicking "start game" does not work, I'll leave this issue open as there's no other issue with this SWF.
