### ISSUE TITLE
Error on https://archive.org/details/sonic-riders-shooting-star-story-website

### ISSUE THREAD

**Issue by gunkypoops** [ruffle-rs/ruffle#9968]
# Error Info
Error name: Error
Error message: panicked at 'string indices out of bounds', core/src/avm2/globals/string.rs:527:34
Error stack:
```
Error: panicked at 'string indices out of bounds', core/src/avm2/globals/string.rs:527:34
    at W.n.wbg.__wbg_new_f9bb493369a83c12 (https://cors.archive.org/cors/emularity_engine_v1/core.ruffle.af250268e116cd1fb80a.js:1:5353)
    at std::sync::once::Once::call_once::{{closure}}::h5f93984c1300ca75 (wasm://wasm/02716a0a:wasm-function[1567]:0x40425f)
    at std::sys_common::once::generic::Once::call::h8801249ea31ccf7a (wasm://wasm/02716a0a:wasm-function[1975]:0x4959cd)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::he904c54109aabe24 (wasm://wasm/02716a0a:wasm-function[7086]:0x740531)
    at std::panicking::rust_panic_with_hook::hb42d415afcc11f2f (wasm://wasm/02716a0a:wasm-function[5008]:0x6a159c)
    at core::panicking::panic_fmt::h32de9c76c9d5eb0c (wasm://wasm/02716a0a:wasm-function[7406]:0x74f295)
    at core::option::expect_failed::hb1beef3e49ebedf1 (wasm://wasm/02716a0a:wasm-function[8488]:0x778b27)
    at ruffle_core::avm2::globals::string::substr::h5e5c1ca0453f976c (wasm://wasm/02716a0a:wasm-function[1859]:0x478895)
    at ruffle_core::avm2::function::Executable::exec::h71b787596b0f38ed (wasm://wasm/02716a0a:wasm-function[888]:0x2e6eb2)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::h4ed835e6cf6c366f (wasm://wasm/02716a0a:wasm-function[2622]:0x55335d)
```
AVM2 stack:
```
    at String/substr()
    at myAS::textAnimation/randomTxtFnc()
    at myAS::textAnimation/textChange()
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://archive.org/details/sonic-riders-shooting-star-story-website#

# Browser Info
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 OPR/95.0.0.0
Platform: MacIntel
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-01-20
Channel: nightly
Built: 2023-01-20T00:18:09.569Z
Commit: f19e31d005c278685fea2de5aaa1c89675ce8714
Is extension: false

# Metadata
width: 800
height: 720
frameRate: 26
numFrames: 177
swfVersion: 9
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 415645

**Comment by Lord-McSweeney** [comment]
Seems to work differently on desktop, reaching a different panic a little later:
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm2/globals/flash/geom/transform.rs:15:8
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
AVM2 stack trace: 
	at flash.geom::Transform/flash::geom::Transform::colorTransform()
	at myAS::menuBtn()
	at top_fla::mc_text_anmation_20/frame1()
```

**Comment by n0samu** [comment]
This seems to no longer panic on desktop, but it's still hitting the same panic on web.

**Comment by adrian17** [comment]
The panic should have been fixed by https://github.com/ruffle-rs/ruffle/pull/16571 .
